### ISSUE TITLE
[Issue]: Endless log messages: System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by fiechr** [jellyfin/jellyfin#10071]
### Please describe your bug

Everytime the library gets scanned or updates by a scheduled task I get a lot (at least a few hundreds) of messages like this:

```
Aug 02 20:12:42 jellyfin[904812]: [20:12:42] [WRN] Cannot fetch image from http://image.tmdb.org/t/p/original/n9NorD6bQfFJlW4IcJ6WoGiAKcR.jpg
Aug 02 20:12:42 jellyfin[904812]: System.InvalidOperationException: Operation is not valid due to the current state of the object.
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
Aug 02 20:12:42 jellyfin[904812]: [20:12:42] [WRN] Cannot fetch image from http://image.tmdb.org/t/p/original/xGKavu5mcGBOQMSawk9voZeEzN6.jpg
Aug 02 20:12:42 jellyfin[904812]: System.InvalidOperationException: Operation is not valid due to the current state of the object.
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
Aug 02 20:12:42 jellyfin[904812]: [20:12:42] [WRN] Cannot fetch image from http://image.tmdb.org/t/p/original/lSXxMaASqm9TfnKaDNaxolEOW3A.jpg
Aug 02 20:12:42 jellyfin[904812]: System.InvalidOperationException: Operation is not valid due to the current state of the object.
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
Aug 02 20:12:42 jellyfin[904812]: [20:12:42] [WRN] Cannot fetch image from http://image.tmdb.org/t/p/original/x4RtcVvCF3xw6bMXHiUC14Vahf9.jpg
Aug 02 20:12:42 jellyfin[904812]: System.InvalidOperationException: Operation is not valid due to the current state of the object.
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
Aug 02 20:12:42 jellyfin[904812]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

I'm new to jellyfin and have no idea where to look first. I only use jellyfin for some local video files and the initial scan worked fine for all the metadata, I also see the images (including actors) and playback to my iPad with works fine too.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Server 23.04
- Linux Kernel: 6.2.0-26-generic
- Virtualization: -
- Clients: iPadOS, Android
- Browser: Chrome
- FFmpeg Version: jellyfin PPA installed version
- Playback Method: -
- Hardware Acceleration: - 
- GPU Model: iGPU
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: IPv4 and IPv6, SSL enabled
- Storage: internal SSD (all storage default values)
```

### Jellyfin logs

```shell
Aug 02 20:30:03 systemd[1]: Started jellyfin.service - Jellyfin Media Server.
Aug 02 20:30:03 sudo[908230]: pam_unix(sudo:session): session closed for user root
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Jellyfin version: 10.8.10
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Environment Variables: ["[JELLYFIN_WEB_OPT, --webdir=/usr/share/jell>
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/sha>
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Operating system: Linux
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Architecture: X64
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] 64-Bit Process: True
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] User Interactive: True
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Processor count: 4
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Program data path: /var/lib/jellyfin
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Web resources path: /usr/share/jellyfin/web
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Application directory: /usr/lib/jellyfin/bin/
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Setting cache path: /var/cache/jellyfin
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Loading assemblies
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Loaded assembly InfuseSync, Version=1.4.2.0, Culture=neutral, Public>
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Defined LAN addresses : [fc00::/7,fe80::/10,10.0.0.0/8,172.16.0.0/12>
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Defined LAN exclusions : []
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Using LAN addresses: [fc00::/7,fe80::/10,10.0.0.0/8,172.16.0.0/12,19>
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Using bind addresses: []
Aug 02 20:30:03 jellyfin[908279]: [20:30:03] [INF] Using bind exclusions: []
Aug 02 20:30:05 jellyfin[908279]: [20:30:05] [INF] InfuseSync is starting.
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: InfuseSync 1.4.2.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: TMDb 10.8.10.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: Studio Images 10.8.10.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: OMDb 10.8.10.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: MusicBrainz 10.8.10.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Loaded plugin: AudioDB 10.8.10.0
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Kestrel listening on All Addresses
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Running startup tasks
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Infuse housekeeping task scheduled.
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Daily trigger for Remove Old Cached Data set to fire at 2023-08-03 0>
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Daily trigger for Extract Chapter Images set to fire at 2023-08-03 0>
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Found ffmpeg version 5.1.3
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h26>
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv">
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwuploa>
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", ">
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] ServerId: 0f69237be8ce4bea946a1c2a19b9dd29
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Executed all pre-startup entry points in 0:00:00.085758
Aug 02 20:30:06 jellyfin[908279]: [20:30:06] [INF] Core startup complete
Aug 02 20:30:07 jellyfin[908279]: [20:30:07] [INF] Executed all post-startup entry points in 0:00:00.1436972
Aug 02 20:30:07 jellyfin[908279]: [20:30:07] [INF] Startup complete 0:00:03.6616181
Aug 02 20:30:09 jellyfin[908279]: [20:30:09] [INF] StartupTrigger fired for task: Update Plugins
Aug 02 20:30:09 jellyfin[908279]: [20:30:09] [INF] Queuing task PluginUpdateTask
Aug 02 20:30:09 jellyfin[908279]: [20:30:09] [INF] Executing Update Plugins
Aug 02 20:30:10 jellyfin[908279]: [20:30:10] [INF] Update Plugins Completed after 0 minute(s) and 0 seconds
Aug 02 20:30:10 jellyfin[908279]: [20:30:10] [INF] ExecuteQueuedTasks
Aug 02 20:30:12 jellyfin[908279]: [20:30:12] [INF] No matching device profile found. The default will need to be used.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Closing this issue as it does not appear to contain an actual Jellyfin bug. The URLs in question return "file not found" from The Movie Database. Head to our support channels either on our forums or on our Matrix/Discord server and someone can help take a look at your logs and your configurations to help you solve the problem.
