### ISSUE TITLE
[Issue]: jellyfin error processing xmltv files for livetv schedule

### ISSUE THREAD

**Issue by socphoenix** [jellyfin/jellyfin#10086]
### Please describe your bug

Jellyfin stopped working with xmltv guides about a week ago on my system. There appears to be an issue with the xml parser. It is reporting: 
`[2023-08-05 10:31:13.523 -06:00] [ERR] [49] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.Xml.XmlException: Root element is missing.` 

The guide looks fine as best I can tell, I have one from iptv-epg scraper used yesterday [here.](https://drive.google.com/file/d/14WBh9gs16U2ZgWsYHWswUx5bn0vJ6e1G/view?usp=sharing)

Due to the size of the log I tried to include only relevant information below. the full log [is here](https://drive.google.com/file/d/1QJ40OvFE7tex5in0gePzVBR3DuGwYm3O/view?usp=sharing) if needed.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: FreeBSD 13.2
- Linux Kernel:
- Virtualization:
- Clients:Linux/MacOS
- Browser:Safari, Chrome, Firefox
- FFmpeg Version: 6.0
- Playback Method:
- Hardware Acceleration: none
- GPU Model: none
- Plugins:
- Reverse Proxy:
- Base URL: lan ip : 192.168.50.30
- Networking: wired 1G
- Storage: local
```

### Jellyfin logs

```shell
[2023-08-05 10:31:13.462 -06:00] [INF] [49] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Found epg channel in "XmlTV" null "Zee Zest" "ZeeZest.in"
[2023-08-05 10:31:13.516 -06:00] [INF] [49] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[2023-08-05 10:31:13.516 -06:00] [INF] [49] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "https://www.bevy.be/bevyfiles/unitedstates.xml"
[2023-08-05 10:31:13.516 -06:00] [ERR] [49] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Jellyfin.XmlTv.XmlTvReader.GetChannels()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by socphoenix** [comment]
Found the issue with this. iptv's "npm run grab" command is not properly formatting the guide .xml. See [this issue](https://github.com/iptv-org/epg/issues/2161).

Current workaround is to run 
`npx epg-grabber --config=sites/tvtv.us/tvtv.us.config.js --channels=sites/tvtv.us/tvtv.us.channels.xml --output=guides/en/tvtv.us.xml --days=2`
