### ISSUE TITLE
No compatible streams are currently available - Broken ffmpeg command

### ISSUE THREAD

**Issue by Mountaineer1024** [jellyfin/jellyfin#1013]
**Describe the bug**
Some videos incorrectly attempt to transcode, resulting in user message: "Playback Error
No compatible streams are currently available. Please try again later or contact your system administrator for details."
I believe this is an incorrectly configured (possibly corrupted) chrome install failing to identify it's codec support, resulting in Jellyfin attempting to transcode with a broken output string.

**To Reproduce**
1) Click play on a movie that is MKV format with default subtitles turned on. (disabling subtitles on the movie allowed it to play)
2) Jellyfin incorrectly believes Chrome cannot display the MKV and attempts to transcode to webm.
3) Error

**Expected behavior**
Video shouldn't transcode when unnecessary.
FFMpeg shouldn't get issued invalid instructions resulting in transcode failure.

**Logs**
MediaInfo of the problematic file: https://pastebin.com/GdZhZKqV

Excerpt from log when error occurs:
[2019-02-26 22:28:25.407 +10:30] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of inner exception stack trace ---
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod) in /repo/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 403
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod) in /repo/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 241
at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping) in /repo/Mono.Nat/Upnp/UpnpNatDevice.cs:line 232
at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device) in /repo/Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs:line 248

Output of ffmpeg inside docker when it attempts to transcode the video (as it does when triggered by jellyfin):
https://pastebin.com/8SiDTEJ1

**System (please complete the following information):**
Docker running on Xubuntu 18.10
Chrome 72.0.3626.119 (Official Build) (64-bit)
Jellyfin 10.2.1

**Additional context**
Resolved initial issue by resetting all flags to default in chrome://flags
Now all videos can play.
Unsure what flag was problematic :-/

**Comment by t0ma5** [comment]
same issue here

**Comment by crispyaus** [comment]
check you have `hardware acceleration ON` in chrome.
