### ISSUE TITLE
[Issue]: Constant Crashing due to 'An invalid IP address was specified' error

### ISSUE THREAD

**Issue by CyferShepard** [jellyfin/jellyfin#10132]
### Please describe your bug

Hi, im having an issue where jellyfin constantly crashes and restarts with the error being ```System.ArgumentException: An invalid IP address was specified. (Parameter 'address')```.

Im running on Ubuntu 20.04

Not really sure how to replicate this error.
Jellyfin version 10.8.10

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 20.04
- Linux Kernel:
- Virtualization: Proxmox
- Clients: All
- Browser: All
- FFmpeg Version: latest
- Playback Method: Both Transcode and Direct
- Hardware Acceleration: NVidia
- GPU Model: Quadro P400
- Plugins:
- Reverse Proxy: Yes
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-08-19 21:36:35.178 +02:00] [WRN] Slow HTTP Response from "https://jellyfin.nexus.local/Sessions/Playing/Progress" to "10.0.0.20" in 0:00:01.2606852 with Status Code 204
[2023-08-19 21:36:57.759 +02:00] [INF] Defined LAN addresses : "[10.0.0.0/24]"
[2023-08-19 21:36:57.759 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-19 21:36:57.759 +02:00] [INF] Using LAN addresses: "[10.0.0.0/24]"
[2023-08-19 21:36:59.849 +02:00] [INF] Defined LAN addresses : "[10.0.0.0/24]"
[2023-08-19 21:36:59.849 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-19 21:36:59.849 +02:00] [INF] Using LAN addresses: "[10.0.0.0/24]"
[2023-08-19 21:37:01.939 +02:00] [INF] Defined LAN addresses : "[10.0.0.0/24]"
[2023-08-19 21:37:01.939 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-19 21:37:01.939 +02:00] [INF] Using LAN addresses: "[10.0.0.0/24]"
[2023-08-19 21:37:09.378 +02:00] [INF] Defined LAN addresses : "[10.0.0.0/24]"
[2023-08-19 21:37:09.380 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-19 21:37:09.381 +02:00] [INF] Using LAN addresses: "[10.0.0.0/24]"
[2023-08-19 21:37:10.470 +02:00] [FTL] Unhandled Exception
System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[2023-08-19 21:37:12.197 +02:00] [INF] Jellyfin version: "10.8.10"```
```

### Please attach any screenshots here

https://cdn.discordapp.com/attachments/773650260903591946/1142523970856439921/image.png
![](https://cdn.discordapp.com/attachments/773650260903591946/1142523970856439921/image.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Do you by chance have an interface which keeps getting reset? Like a crashing docker container?

**Comment by CyferShepard** [comment]
HI, im not running in docker, its running in an ubuntu vm inside proxmox

**Comment by 0x25CBFC4F** [comment]
@CyferShepard, hey! Stack trace looks incomplete to me. Could you show more logs?

**Comment by CyferShepard** [comment]
Hey, Il add it in tomorrow morning, just powered off for the night. But this is pretty much it, IV combed through the logs and its mainly the same. But after the last item in the error log it says jellyfin media server has stopped. Then jellyfin media server has started and that's when it basically restarts

**Comment by CyferShepard** [comment]
Hi, heres the full log.
```[2023-08-21 00:41:16.609 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=2400&recursive=true&limit=200" to "REDACTED" in 0:00:00.6278019 with Status Code 200
[2023-08-21 00:41:16.776 +02:00] [INF] Processing playback tracker : "c67a2c0911a07019077e5d3d3373b26777e93641-f1984d0458cf45c5bc58d229d5115a33-91dfde5fae980633e967f36219198420"
[2023-08-21 00:41:17.288 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=2600&recursive=true&limit=200" to "REDACTED" in 0:00:00.6625803 with Status Code 200
[2023-08-21 00:41:17.937 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=2800&recursive=true&limit=200" to "REDACTED" in 0:00:00.6304722 with Status Code 200
[2023-08-21 00:41:18.499 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:18.500 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:18.500 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:18.648 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=3000&recursive=true&limit=200" to "REDACTED" in 0:00:00.6938854 with Status Code 200
[2023-08-21 00:41:19.287 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=3200&recursive=true&limit=200" to "REDACTED" in 0:00:00.6201294 with Status Code 200
[2023-08-21 00:41:19.935 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Items?parentId=REDACTED&startIndex=3400&recursive=true&limit=200" to "REDACTED" in 0:00:00.6302117 with Status Code 200
[2023-08-21 00:41:20.633 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:20.633 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:20.633 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:22.731 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:22.731 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:22.732 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:23.123 +02:00] [FTL] Unhandled Exception
System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2023-08-21 00:41:25.076 +02:00] [INF] Jellyfin version: "10.8.9"
[2023-08-21 00:41:25.158 +02:00] [INF] Environment Variables: ["[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]"]
[2023-08-21 00:41:25.168 +02:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-08-21 00:41:25.170 +02:00] [INF] Operating system: "Linux"
[2023-08-21 00:41:25.170 +02:00] [INF] Architecture: X64
[2023-08-21 00:41:25.172 +02:00] [INF] 64-Bit Process: True
[2023-08-21 00:41:25.172 +02:00] [INF] User Interactive: True
[2023-08-21 00:41:25.172 +02:00] [INF] Processor count: 8
[2023-08-21 00:41:25.172 +02:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-08-21 00:41:25.173 +02:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-08-21 00:41:25.173 +02:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-08-21 00:41:25.669 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2023-08-21 00:41:25.814 +02:00] [INF] Loading assemblies
[2023-08-21 00:41:25.852 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.AniDB, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/AniDB_7.0.0.0/Jellyfin.Plugin.AniDB.dll"
[2023-08-21 00:41:25.857 +02:00] [INF] Loaded assembly "MediaBrowser.Plugins.SmtpNotifications, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Email_9.0.0.0/MediaBrowser.Plugins.SmtpNotifications.dll"
[2023-08-21 00:41:25.932 +02:00] [INF] Loaded assembly "MailKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b" from "/var/lib/jellyfin/plugins/Email_9.0.0.0/MailKit.dll"
[2023-08-21 00:41:26.026 +02:00] [INF] Loaded assembly "BouncyCastle.Crypto, Version=1.8.8.0, Culture=neutral, PublicKeyToken=0e99375e54769942" from "/var/lib/jellyfin/plugins/Email_9.0.0.0/BouncyCastle.Crypto.dll"
[2023-08-21 00:41:26.057 +02:00] [INF] Loaded assembly "MimeKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" from "/var/lib/jellyfin/plugins/Email_9.0.0.0/MimeKit.dll"
[2023-08-21 00:41:26.061 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.Fanart, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Fanart_10.0.0.0/Jellyfin.Plugin.Fanart.dll"
[2023-08-21 00:41:26.062 +02:00] [INF] Skipping disabled plugin "1.1.1.0" of "Jellyscrub" 
[2023-08-21 00:41:26.065 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_13.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2023-08-21 00:41:26.066 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Skin Manager_2.0.1/Jellyfin.Plugin.SkinManager.dll"
[2023-08-21 00:41:26.068 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.ThemeSongs, Version=10.8.0.1, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Theme Songs_10.8.0.1/Jellyfin.Plugin.ThemeSongs.dll"
[2023-08-21 00:41:26.075 +02:00] [INF] Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_9.0.0.0/TvDbSharper.dll"
[2023-08-21 00:41:26.083 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.Tvdb, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_9.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2023-08-21 00:41:26.083 +02:00] [INF] Skipping disabled plugin "10.0.0.0" of "TheTVDB" 
[2023-08-21 00:41:26.085 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TMDb Box Sets_10.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll"
[2023-08-21 00:41:26.399 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:26.399 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:26.400 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:26.407 +02:00] [INF] Using bind addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:26.407 +02:00] [INF] Using bind exclusions: "[]"
[2023-08-21 00:41:34.302 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:34.302 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:34.302 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:34.460 +02:00] [INF] Loaded plugin: "AniDB" "7.0.0.0"
[2023-08-21 00:41:34.462 +02:00] [INF] Loaded plugin: "Email Notifications" "9.0.0.0"
[2023-08-21 00:41:34.465 +02:00] [INF] Loaded plugin: "Fanart" "10.0.0.0"
[2023-08-21 00:41:34.467 +02:00] [INF] Loaded plugin: "Playback Reporting" "13.0.0.0"
[2023-08-21 00:41:34.468 +02:00] [INF] Loaded plugin: "Skin Manager" "2.0.1"
[2023-08-21 00:41:34.470 +02:00] [INF] Loaded plugin: "Theme Songs" "10.8.0.1"
[2023-08-21 00:41:34.471 +02:00] [INF] Loaded plugin: "TheTVDB" "9.0.0.0"
[2023-08-21 00:41:34.473 +02:00] [INF] Loaded plugin: "TMDb Box Sets" "10.0.0.0"
[2023-08-21 00:41:34.475 +02:00] [INF] Loaded plugin: "TMDb" "10.8.9.0"
[2023-08-21 00:41:34.476 +02:00] [INF] Loaded plugin: "Studio Images" "10.8.9.0"
[2023-08-21 00:41:34.477 +02:00] [INF] Loaded plugin: "OMDb" "10.8.9.0"
[2023-08-21 00:41:34.478 +02:00] [INF] Loaded plugin: "MusicBrainz" "10.8.9.0"
[2023-08-21 00:41:34.479 +02:00] [INF] Loaded plugin: "AudioDB" "10.8.9.0"
[2023-08-21 00:41:34.687 +02:00] [INF] Kestrel listening on "10.0.0.99/32"
[2023-08-21 00:41:35.585 +02:00] [INF] Running startup tasks
[2023-08-21 00:41:35.589 +02:00] [INF] TaskCleanDb Loaded
[2023-08-21 00:41:35.594 +02:00] [INF] TaskRunBackup Loaded
[2023-08-21 00:41:35.663 +02:00] [INF] Daily trigger for "Playback Reporting Trim Db" set to fire at 2023-08-22 00:00:00.000 +02:00, which is 23:18:24.3364585 from now.
[2023-08-21 00:41:35.706 +02:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 2023-08-21 02:00:00.000 +02:00, which is 01:18:24.2935213 from now.
[2023-08-21 00:41:35.828 +02:00] [INF] Found ffmpeg version "4.4.1"
[2023-08-21 00:41:35.904 +02:00] [INF] Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2023-08-21 00:41:35.935 +02:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2023-08-21 00:41:35.966 +02:00] [INF] Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-08-21 00:41:36.186 +02:00] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2023-08-21 00:41:36.456 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:36.457 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:36.458 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:36.553 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Sessions/Playing/Progress" to "10.0.0.184" in 0:00:00.6455074 with Status Code 503
[2023-08-21 00:41:36.575 +02:00] [INF] FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2023-08-21 00:41:36.577 +02:00] [INF] ServerId: "REDACTED"
[2023-08-21 00:41:36.844 +02:00] [INF] Executed all pre-startup entry points in 0:00:00.2257318
[2023-08-21 00:41:36.844 +02:00] [INF] Core startup complete
[2023-08-21 00:41:36.845 +02:00] [INF] EventMonitorEntryPoint Running
[2023-08-21 00:41:36.859 +02:00] [INF] Sqlite version: 3.38.3
[2023-08-21 00:41:36.862 +02:00] [INF] Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-7.5.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_FOREIGN_KEYS,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_RTREE,ENABLE_SNAPSHOT,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=32766,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1
[2023-08-21 00:41:36.870 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/playback_reporting.db" is "delete"
[2023-08-21 00:41:36.870 +02:00] [INF] Initialize PlaybackActivity Repository
[2023-08-21 00:41:36.871 +02:00] [INF] PlaybackActivity table schema OK
[2023-08-21 00:41:36.871 +02:00] [INF] Expected : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2023-08-21 00:41:36.871 +02:00] [INF] Received : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2023-08-21 00:41:37.345 +02:00] [INF] Watching directory "/home/cyfer/NexusStorage/MediaFolder/Anime Movies"
[2023-08-21 00:41:37.348 +02:00] [INF] Executed all post-startup entry points in 0:00:00.5036629
[2023-08-21 00:41:37.348 +02:00] [INF] Startup complete 0:00:12.6949677
[2023-08-21 00:41:37.348 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.349 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.360 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.361 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.403 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.412 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:37.437 +02:00] [INF] Watching directory "REDACTED"
[2023-08-21 00:41:38.548 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:38.548 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:38.548 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:38.714 +02:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2023-08-21 00:41:38.715 +02:00] [INF] Queuing task "PluginUpdateTask"
[2023-08-21 00:41:38.722 +02:00] [INF] Executing "Update Plugins"
[2023-08-21 00:41:39.754 +02:00] [WRN] Slow HTTP Response from "http://10.0.0.99:8096/Sessions/Playing/Progress" to "10.0.0.184" in 0:00:01.0273401 with Status Code 204
[2023-08-21 00:41:40.671 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:40.672 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:40.673 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:42.810 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:42.810 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:42.810 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:44.860 +02:00] [INF] "Update Plugins" Completed after 0 minute(s) and 6 seconds
[2023-08-21 00:41:44.875 +02:00] [INF] ExecuteQueuedTasks
[2023-08-21 00:41:44.935 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:44.935 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:44.935 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:47.047 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:47.047 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:47.047 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:49.140 +02:00] [INF] Defined LAN addresses : "[10.0.0.99/32]"
[2023-08-21 00:41:49.140 +02:00] [INF] Defined LAN exclusions : "[]"
[2023-08-21 00:41:49.140 +02:00] [INF] Using LAN addresses: "[10.0.0.99/32]"
[2023-08-21 00:41:53.798 +02:00] [INF] WS "10.0.0.184" request```

**Comment by CyferShepard** [comment]
I tried downgrading to 10.8.9 but the result was the same

**Comment by CyferShepard** [comment]
Just an update, i can confirm this is only happening when im watching media that requires transcoding, direct plays dont trigger this crash. Im not sure why but as my drivers are never updated and i only run the following drivers NVIDIA-Linux-x86_64-515.76 for stability. Been using it for over a year now

**Comment by lettore** [comment]
I also have the same problem, it triggers randomly when another container is starting. This is a problem that I have from six months now.

**Comment by Shadowghost** [comment]
We are listening on network change events which triggers a full reload of all network bindings. in 10.9 this will a) be less spammy due to changed log levels and b) more accurate since we are excluding some adapters which we can't bind to anyways.

**Comment by CyferShepard** [comment]
Hi, just wanted to check if there is any progress on this issue, it's been happening non stop every couple minutes, it's abit Random but it crashes anywhere between 10-12 times in an hour non stop. Its made using jellyfin annoying. So far iv tried installing on docker and the issue still seems to persist. Are there any tips you could recommend so that I could work around this issue or reduce the frequency of crashes?

**Comment by cvium** [comment]
Duplicate of https://github.com/jellyfin/jellyfin/issues/8687
