### ISSUE TITLE
When the disk is full, Jellyfin stops working, and logs show SQL errors

### ISSUE THREAD

**Issue by dandar** [jellyfin/jellyfin#10187]
When the disk is full, Jellyfin stops working, and logs show SQL errors such as read-only or permission problems, or worse, loss of user table records. The logs should show "FATAL ERROR: DISK FULL" and "WARNING:  LOW DISK SPACE  x% disk space remaining". The web dashboards should also show such warnings and errors. When/If only a few kilobytes are free on disk, then Jellyfin should close databases and stop gracefully to ensure there is no data loss and open/unclosed db files.

Disk space seems to be most important for the DB files `jellyfin.db` and `library.db`.  It took me several days of intermittent troubleshooting to figure out what's going on - tested on Alpine Linux, I have not tested it in Windows, Mac, or other Linux platforms.  Example current log errors:
```
----------
[2023-08-31 23:04:45.749 -07:00] [ERR] [230] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.D
   
----------
[2023-08-27 22:03:14.044 -07:00] [ERR] [24] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/Playing/Progress".
Error: SQLitePCL.pretty.SQLiteException: cannot rollback - no transaction is active
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.RollbackTransaction(IDatabaseConnection This)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteUserDataRepository.PersistUserData(Int64 internalUserId, String key, UserItemData userData, CancellationToken cancellationToken) in /home/buildozer/aports/community/jellyfin/src/jellyfin-10.8.10/Emby.Server.Implementations/Data/SqliteUserDataRepository.cs:line 190

----- system messages log -----
Aug 21 00:30:04 alpine-dok daemon.err /etc/init.d/jellyfin[2148]: ERROR: jellyfin failed to start
...
Aug 27 00:21:52 alpine-dok daemon.info supervise-daemon[2074]: Supervisor command line: supervise-daemon jellyfin --start --respawn-delay 2 --respawn-max 5 --respawn-period 1800 --user jellyfin:jellyfin /usr/bin/jellyfin -- --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --logdir /var/log/jellyfin 
Aug 27 00:21:52 alpine-dok daemon.info supervise-daemon[2076]: Child command line: /usr/bin/jellyfin --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --logdir /var/log/jellyfin 
...
Aug 27 14:25:17 alpine-dok daemon.info supervise-daemon[2075]: stopping /usr/bin/jellyfin, pid 2076
Aug 27 14:25:17 alpine-dok daemon.debug supervise-daemon[2075]: Will stop PID 2076
Aug 27 14:25:17 alpine-dok daemon.debug supervise-daemon[2075]: Sending signal 15 to PID 2076
...
Aug 27 14:50:03 alpine-dok daemon.info supervise-daemon[15247]: Supervisor command line: supervise-daemon jellyfin --start --respawn-delay 2 --respawn-max 5 --respawn-period 1800 --user jellyfin:jellyfin /usr/bin/jellyfin -- --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --logdir /var/log/jellyfin 
Aug 27 14:50:03 alpine-dok daemon.info supervise-daemon[15249]: Child command line: /usr/bin/jellyfin --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --logdir /var/log/jellyfin 
...
Aug 27 22:52:20 alpine-dok daemon.info supervise-daemon[2076]: stopping /usr/bin/jellyfin, pid 2077

```

**Comment by cvium** [comment]
I don't see how this is Jellyfin's responsibility. Things like disk usage should be part of your own monitoring setup.

**Comment by mvforell** [comment]
I agree that monitoring disk usage isn't Jellyfin's responsibility, but I just hit this issue and Jellyfin just kept crashing, which noticably impacted my Raspberry Pi's load. I'd argue that a graceful shutdown in case of no available disk space would be preferable to the current state.

**Comment by joshuaboniface** [comment]
@mvforell There isn't really any way to do that. From Jellyfin's perspective, all it sees is an attempt to write which fails. It crashes, then whatever is managing the service restarts it. Thus it would be up to the service manager (e.g. systemd, docker, whatever) to stop it from restarting constantly after it fails too many times. I know systemd and our service unit handle this by default, but I'm not sure about Docker.
