### ISSUE TITLE
[Issue]: Missing image for plugin subtitle extract

### ISSUE THREAD

**Issue by cyberpunk2350** [jellyfin/jellyfin#10191]
### Please describe your bug

Receiving multiple errors in the log regarding the image file for the Subtitle Extract Plugin being missing and unable to be downloaded

I went to the [pulgin page](https://repo.jellyfin.org/releases/plugin/subtitle-extract/) and downloaded the plugin to my PC, found in the image URL from the `meta.json` (` "imageUrl": "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-subtitleextract.png"`)  when I went to the URL I also received a 404 error. 
When I went to the parent directory `https://repo.jellyfin.org/releases/plugin/images/` I found images listed for most of the official plugins but none for this plugin.
 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12.2.0-14
- Linux Kernel: 6.2.16-6-pve
- Virtualization: LXC
- Clients: n/a
- Browser: n/a
- FFmpeg Version:
- Playback Method: n/a
- Hardware Acceleration: none
- GPU Model: none
- Plugins: Subtitle Extractor
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: nfs
```

### Jellyfin logs

```shell
[2023-09-03 16:03:54.581 +00:00] [ERR] Failed to download image to path "/var/lib/jellyfin/plugins/Subtitle Extract_2.0.0.0/jellyfin-plugin-subtitleextract.png" on disk.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Plugins.PluginManager.GenerateManifest(PackageInfo packageInfo, Version version, String path, PluginStatus status)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cyberpunk2350** [comment]
closing and moving to https://github.com/jellyfin/jellyfin-plugin-subtitleextract
