### ISSUE TITLE
Crash while real time monitoring music library, Archlinux ARM

### ISSUE THREAD

**Issue by onny** [jellyfin/jellyfin#1019]
**Describe the bug**

Jellyfin server crashes while streaming music.

**To Reproduce**

Crash after about 30 seconds playing any random song.

**Expected behavior**

Play song without crash.

**Logs**

```
Feb 28 10:21:26 picloud dotnet[25342]: ffprobe version n4.1.1 Copyright (c) 2007-2019 the FFmpeg developers
Feb 28 10:21:26 picloud dotnet[25342]:   built with gcc 8.2.1 (GCC) 20181127
Feb 28 10:21:26 picloud dotnet[25342]:   configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-omx --enable-shared --enable-version3 --host-cflags='"-fPIC"'
Feb 28 10:21:26 picloud dotnet[25342]:   libavutil      56. 22.100 / 56. 22.100
Feb 28 10:21:26 picloud dotnet[25342]:   libavcodec     58. 35.100 / 58. 35.100
Feb 28 10:21:26 picloud dotnet[25342]:   libavformat    58. 20.100 / 58. 20.100
Feb 28 10:21:26 picloud dotnet[25342]:   libavdevice    58.  5.100 / 58.  5.100
Feb 28 10:21:26 picloud dotnet[25342]:   libavfilter     7. 40.101 /  7. 40.101
Feb 28 10:21:26 picloud dotnet[25342]:   libswscale      5.  3.100 /  5.  3.100
Feb 28 10:21:26 picloud dotnet[25342]:   libswresample   3.  3.100 /  3.  3.100
Feb 28 10:21:26 picloud dotnet[25342]:   libpostproc    55.  3.100 / 55.  3.100
Feb 28 10:21:27 picloud dotnet[25342]: Input #0, flac, from 'file:/mnt/audio/music/Roudoudou/Tout l'univers. Listener's Digest (1998)/07_-_Roudoudou_-_Peace_and_tranquility_to_earth.flac':
Feb 28 10:21:27 picloud dotnet[25342]:   Metadata:
Feb 28 10:21:27 picloud dotnet[25342]:     ARTIST          : Roudoudou
Feb 28 10:21:27 picloud dotnet[25342]:     TITLE           : Peace and tranquility to earth
Feb 28 10:21:27 picloud dotnet[25342]:     ALBUM           : Tout l'univers. Listener's Digest
Feb 28 10:21:27 picloud dotnet[25342]:     DATE            : 1998
Feb 28 10:21:27 picloud dotnet[25342]:     track           : 07
Feb 28 10:21:27 picloud dotnet[25342]:     GENRE           : Electronic
Feb 28 10:21:27 picloud dotnet[25342]:     COMMENT         : Track 7
Feb 28 10:21:27 picloud dotnet[25342]:   Duration: 00:04:13.71, start: 0.000000, bitrate: 849 kb/s
Feb 28 10:21:27 picloud dotnet[25342]:     Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
Feb 28 10:21:59 picloud dotnet[25342]: [10:21:59] [FTL] Unhandled Exception
Feb 28 10:21:59 picloud dotnet[25342]: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
Feb 28 10:21:59 picloud dotnet[25342]:    --- End of inner exception stack trace ---
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.ThrowIfExceptional()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Feb 28 10:21:59 picloud dotnet[25342]: --- End of stack trace from previous location where exception was thrown ---
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Feb 28 10:21:59 picloud dotnet[25342]: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
Feb 28 10:21:59 picloud dotnet[25342]:    --- End of inner exception stack trace ---
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.ThrowIfExceptional()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Feb 28 10:21:59 picloud dotnet[25342]: --- End of stack trace from previous location where exception was thrown ---
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Feb 28 10:21:59 picloud dotnet[25342]:    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Feb 28 10:22:09 picloud systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
Feb 28 10:22:09 picloud systemd[1]: jellyfin.service: Failed with result 'signal'.
Feb 28 10:22:09 picloud systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
Feb 28 10:22:09 picloud systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 224.
Feb 28 10:22:09 picloud systemd[1]: Stopped Jellyfin Media Server.
Feb 28 10:22:09 picloud systemd[1]: Started Jellyfin Media Server.
```

**System (please complete the following information):**
 - OS: Archlinux ARM
 - Browser: Chrome
 - Jellyfin Version: 10.2.1

**Comment by onny** [comment]
This issue seems not to be related with streaming and more with real time monitoring and media fetching, according to this issue found in the emby forum: https://emby.media/community/index.php?/topic/61219-emy-server-suddenly-started-crashing/
After disabling real time monitoring for the music library, the server doesn't crash anymore.

**Comment by DrPandemic** [comment]
Same root problem than https://github.com/jellyfin/jellyfin/issues/465
