### ISSUE TITLE
[Issue]: Error loading cert from /path/to/cert.pfx

### ISSUE THREAD

**Issue by JustinBrow** [jellyfin/jellyfin#10286]
### Please describe your bug

I generated a cert using certbot
`sudo certbot certonly --dns-cloudflare --dns-cloudflare-credentials /path/to/cf.cred  -d jellyfin.domain.net,jellyfin.internal.domain.net`

Then converted it to pkcs12
`sudo openssl pkcs12 -export -inkey /etc/letsencrypt/live/jellyfin.domain.net/privkey.pem -in /etc/letsencrypt/live/jellyfin.domain.net/fullchain.pem -out /etc/certs/jellyfin.domain.net.pfx`

Unable to access Jellyfin via HTTPS
Error loading cert from /path/to/cert.pfx found in logs.
For the first attempt put a password on the cert and put that in the password box. For the second attempt I used a cert without a password.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12.1.0
- Linux Kernel:6.1.0-12
- Virtualization: Microsoft Hyper-V 2019
- Clients: Browser
- Browser: Microsoft Edge 117
- Reverse Proxy: N/a
- Base URL: none
```

### Jellyfin logs

```shell
[2023-09-26 23:37:37.480 -04:00] [ERR] Error loading cert from "/path/to/cert.pfx"
Interop+Crypto+OpenSslCryptographicException: error:10080002:BIO routines::system lib
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Emby.Server.Implementations.ApplicationHost.GetCertificate(String path, String password)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustinBrow** [comment]
It was a permission issue. Service user didn't have read permission to the certificate file.
