### ISSUE TITLE
[Issue]: Bad Request when calling /Users/AuthenticateByName causes all users to be kicked out

### ISSUE THREAD

**Issue by owenashurst** [jellyfin/jellyfin#10309]
### Please describe your bug

I have a third party app I wrote, and when I make a call to `/Users/AuthenticateByName` for a user (with an `X-Emby-Token` within the headers), if it returns a Bad Request, it kicks all users out.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Any
- Linux Kernel: Any
- Virtualization: N/A
- Clients: API call
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
[2023-09-30 11:16:43.087 +00:00] [ERR] [72] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Users/AuthenticateByName".
System.ArgumentNullException: Value cannot be null. (Parameter 'appName')
   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
   at lambda_method1448(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
FYI you should not use the `X-Emby-Token` heaer, it will be removed at some point. You can read the following documentation on how to authorize to a Jellyfin server: https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f

**Comment by owenashurst** [comment]
> FYI you should not use the `X-Emby-Token` heaer, it will be removed at some point. You can read the following documentation on how to authorize to a Jellyfin server: https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f

Thanks @nielsvanvelzen. Is it on any roadmap to use proper JWT authentication? The only reason I ask is because I'd like to extract claims from the JWT so I know what someone is doing when authenticated through my API.

**Comment by nielsvanvelzen** [comment]
We don't really work with a roadmap, all of us just work on the stuff we want to work on. I don't think there is anyone working on authentication changes right now.

**Comment by olafur-palsson** [comment]
Can I suggest adding some validation to requests so that the request will be rejected with a 400?

**Comment by VCSocial** [comment]
@owenashurst just to double check you are already getting a 400 in response right? Do you have a sample request like a cURL that I could use to reproduce the issue on my local? I can't guarantee I can address this but if I have availability I'd like to take a look.

**Comment by caesarm** [comment]
> @owenashurst just to double check you are already getting a 400 in response right? Do you have a sample request like a cURL that I could use to reproduce the issue on my local? I can't guarantee I can address this but if I have availability I'd like to take a look.

I saw this same behavior when I called /Users/AuthenticateByName and didn't set the Authentication header. The web client session I already had open stopped working. I reloaded the page and it forced me to log back in. I did get a 400 status code when I did this in the API. Hope it helps.

**Comment by owenashurst** [comment]
> > @owenashurst just to double check you are already getting a 400 in response right? Do you have a sample request like a cURL that I could use to reproduce the issue on my local? I can't guarantee I can address this but if I have availability I'd like to take a look.
> 
> I saw this same behavior when I called /Users/AuthenticateByName and didn't set the Authentication header. The web client session I already had open stopped working. I reloaded the page and it forced me to log back in. I did get a 400 status code when I did this in the API. Hope it helps. 

Thanks for confirming! I don't understand why it kicks everyone out though. It's not just the user you're signing on as. It's everybody.
