### ISSUE TITLE
[Issue]: Jellyfin does not scan extras on some films

### ISSUE THREAD

**Issue by random-human-being** [jellyfin/jellyfin#10408]
### Please describe your bug

Some extras do not show up alongside the film they belong to.

For instance, I have the following film in:
`/media/Films/A french film (2003)/A_french_film.x264.DVD.mkv`
with the following folder...
`/media/Films/A french film (2003)/shorts/`
... containing the following files:
`L'echelle.mkv  La Boule.mkv   La Fleur.mkv`
The films shows up in the web interface, but the extra do not.

Conversely, the following film and the corresponding extra show up properly:
`/media/Films/Another french film (1999)/Another_french_film.x264.1080p.BluRay.mkv`
with the folder
`/media/Films/Another french film (1999)/interviews/`
containing
`Interview.with.Some.Guy.mkv   Interview.with.Some.Other.Dude.mkv   Interview.Number.Three.mkv`

(I have altered the names while keeping a similar syntax, i.e. replaced spaces with spaces and dots with dots)

The corresponding log for the extras that fail to scan is shown below.

### Jellyfin Version

10.8.z

### if other:

10.8.11

### Environment

```markdown
- OS: LibreELEC 10.0.4
- Linux Kernel: 5.10.161
- Virtualization: Docker
- Clients: Web UI
- Browser: Firefox
- Plugins: Jellyfin Ignore (set to ignore */*.azw3
- Reverse Proxy: Caddy
- Base URL: none
- Networking: https
- Storage: HDD
```

### Jellyfin logs

```shell
[2023-10-15 14:19:13.287 +00:00] [ERR] [58] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/media/Films/A french film (2003)/A_french_film.x264.DVD.mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.Ignore.IgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<FindExtras>g__GetExtra|168_0(FileSystemMetadata file, ExtraType extraType, <>c__DisplayClass168_0& )
   at Emby.Server.Implementations.Library.LibraryManager.FindExtras(BaseItem owner, IReadOnlyList`1 fileSystemChildren, IDirectoryService directoryService)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshExtras(BaseItem item, MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EpicKnarvik97** [comment]
I'm experiencing the same problem for all movies with extras on Jellyfin 10.8.13, running directly on Debian Bookworm. Extras used to work, but after improving my folder structure, and moving every movie to its own folder, with year and IMDB-id, no movie extras is displayed. Some movies were in collections, some were not.

Every movie with extras spams the error message:

```
[2024-03-20 20:21:18.605 +01:00] [ERR] Error refreshing owned items for "/movies/Folder (Year) [imdbid-tt0000000]/Movie (Year) [imdbid-tt0000000].mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.Ignore.IgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<FindExtras>g__GetExtra|168_0(FileSystemMetadata file, ExtraType extraType, <>c__DisplayClass168_0& )
   at Emby.Server.Implementations.Library.LibraryManager.FindExtras(BaseItem owner, IReadOnlyList`1 fileSystemChildren, IDirectoryService directoryService)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshExtras(BaseItem item, MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

**Comment by Bond-009** [comment]
This is an issue with the plugin you're using, I'm assuming it's this one: https://github.com/fdett/jellyfin-ignore/blob/master/Jellyfin.Plugin.Ignore/IgnoreRule.cs#L61

`parent` can be null, but the plugin doesn't take this into account
