### ISSUE TITLE
[Issue]: Empty Playlists in latest version 10.9.0

### ISSUE THREAD

**Issue by Morethanevil** [jellyfin/jellyfin#10509]
### Please describe your bug

I am using Jellyfin in docker (official image) and I had the playlist bug too. It was fixed as mentioned [here](https://github.com/jellyfin/jellyfin/issues/10272) and I updated to the latest unstable image (jellyfin/jellyfin:20231101.1-unstable)

The playlists were back but empty, so I manually recreated them. It worked fine with third party apps too. But after I run docker compose down and docker compose up, they were empty again. Everything else works! The volumes are mounted correctly, I did not change them. I tried to reproduce this bug again. I created a playlist, added 2 songs, run docker compose down and docker compose up again and they are empty again.

I just want my playlists 😟
I can not downgrade to v10.8.10, Jellyfin won't start.

### Jellyfin Version

Other

### if other:

10.9.0-unstable

### Environment

```markdown
- OS: Ubuntu Server 22.04
- Linux Kernel:
- Virtualization: Dockerimage jellyfin/jellyfin:20231101.1-unstable
- Clients: all
- Browser: Firefox Vivaldi
- FFmpeg Version: docker
- Playback Method: - 
- Hardware Acceleration: VAAPI
- GPU Model: AMD iGPU
- Plugins: -
- Reverse Proxy: -
- Base URL: https
- Networking: Host-network
- Storage: -
```

### Jellyfin logs

```shell
Created playlist "Test" and adding 2 items

[07:42:07] [INF] [20] Jellyfin.Drawing.ImageProcessor: Creating image collage and saving to /cache/temp/5fa910862db74b1ba0547119acdce65d.png
[07:42:07] [INF] [20] Jellyfin.Drawing.ImageProcessor: Completed creation of image collage and saved to /cache/temp/5fa910862db74b1ba0547119acdce65d.png

Restart via docker compose down && docker compose up -d



[07:43:17] [INF] [1] Main: Jellyfin version: 10.9.0
[07:43:17] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_PublishedServerUrl, https://jf.mymte.de]"]
[07:43:17] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[07:43:17] [INF] [1] Main: Operating system: Linux 6.5.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 20 15:53:48 UTC 2023
[07:43:17] [INF] [1] Main: Architecture: X64
[07:43:17] [INF] [1] Main: 64-Bit Process: True
[07:43:17] [INF] [1] Main: User Interactive: True
[07:43:17] [INF] [1] Main: Processor count: 12
[07:43:17] [INF] [1] Main: Program data path: /config
[07:43:17] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[07:43:17] [INF] [1] Main: Application directory: /jellyfin/
[07:43:17] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[07:43:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bookshelf, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bookshelf_9.0.0.0/Jellyfin.Plugin.Bookshelf.dll
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Reports_15.0.0.0/Jellyfin.Plugin.Reports.dll
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_10.0.0.0/Jellyfin.Plugin.Tvdb.dll
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_10.0.0.0/TvDbSharper.dll
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942 from /config/plugins/Webhook_11.0.0.0/BouncyCastle.Crypto.dll
[07:43:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Handlebars, Version=2.1.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661 from /config/plugins/Webhook_11.0.0.0/Handlebars.dll
[07:43:17] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Webhook_11.0.0.0/Jellyfin.Plugin.Webhook.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Notifications.INotificationService' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Notifications.INotificationService' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "192.168.0.80", "172.20.0.1", "172.19.0.1", "172.29.0.1", "172.21.0.1", "172.23.0.1", "172.22.0.1", "172.25.0.1", "172.27.0.1", "172.28.0.1", "172.24.0.1", "::1", "fd00::7656:3cff:fe43:190d", "fe80::7656:3cff:fe43:190d%2", "fd00:112::1", "fe80::42:66ff:fe3c:caf3%4", "fe80::1%4", "fe80::42:6ff:fe76:825%6", "fe80::42:8fff:fed1:1b30%7", "fe80::42:fff:fe9c:ad22%9", "fe80::42:b1ff:fee7:40b3%10", "fe80::42:60ff:fecd:5ec9%11", "fe80::42:41ff:fe1b:f3cf%12", "fe80::42:b1ff:fe95:3a35%13", "fe80::42:f7ff:fef2:d805%14", "fe80::42:34ff:fe72:8467%82"]
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[07:43:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bookshelf 9.0.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 15.0.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 10.0.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.0.0
[07:43:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.0.0
[07:43:20] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[07:43:20] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[07:43:20] [INF] [1] Main: Kestrel is listening on 127.0.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on ::1
[07:43:20] [INF] [1] Main: Kestrel is listening on 192.168.0.80
[07:43:20] [INF] [1] Main: Kestrel is listening on fd00::7656:3cff:fe43:190d
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::7656:3cff:fe43:190d%2
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.20.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fd00:112::1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:66ff:fe3c:caf3%4
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::1%4
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.19.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:6ff:fe76:825%6
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.29.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:8fff:fed1:1b30%7
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.21.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:fff:fe9c:ad22%9
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.23.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:b1ff:fee7:40b3%10
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.22.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:60ff:fecd:5ec9%11
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.25.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:41ff:fe1b:f3cf%12
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.27.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:b1ff:fe95:3a35%13
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.28.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:f7ff:fef2:d805%14
[07:43:20] [INF] [1] Main: Kestrel is listening on 172.24.0.1
[07:43:20] [INF] [1] Main: Kestrel is listening on fe80::42:34ff:fe72:8467%82
[07:43:20] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {996baf50-1d7a-4fed-b200-7bfefe184f8a} may be persisted to storage in unencrypted form.
[07:43:20] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[07:43:20] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Trickplay-Bilder generieren set to fire at 2023-11-02 03:00:00.000 +00:00, which is 19:16:39.5092735 from now.
[07:43:20] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extrahiere Kapitel-Bilder set to fire at 2023-11-02 02:00:00.000 +00:00, which is 18:16:39.5072898 from now.
[07:43:20] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.3
[07:43:20] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[07:43:20] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libsvtav1", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[07:43:20] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[07:43:20] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[07:43:21] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: VAAPI device /dev/dri/renderD128 is AMD GPU
[07:43:21] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: VAAPI device /dev/dri/renderD128 supports Vulkan DRM interop
[07:43:21] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
[07:43:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 4900df976fae4f9dbedf1494973b6092
[07:43:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0459285
[07:43:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[07:43:21] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /medien/video1
[07:43:21] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /medien/video2
[07:43:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1425211
[07:43:21] [INF] [1] Main: Startup complete 0:00:03.8354925
[07:43:21] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /medien/video3
[07:43:21] [INF] [22] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /medien/music
[07:43:23] [INF] [21] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in test cannot be found at /medien/music/Various Artists/Oxford Street Proposal - All of me.mp3
[07:43:23] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: TaskCleanCollectionsAndPlaylists Completed after 0 minute(s) and 0 seconds
[07:43:24] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: Aktualisiere Plugins Completed after 0 minute(s) and 1 seconds
[07:43:40] [INF] [21] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 46.142.8.164 request
[07:43:40] [WRN] [21] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 46.142.8.164 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[07:43:40] [INF] [21] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 46.142.8.164 closed
[07:43:45] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS fd00::9aef:9bcb:a41b:ac8b request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
```
I can not downgrade to v10.8.10, Jellyfin won't start.
```
Well that is expected, upgrading is a one-way street, it's called `unstable` for a reason.
There were a lot of changes regarding playlists in 10.9, e.g. playlist ACLs, playlists being user-only by default, so the issue might not be the same. If this can be reproduced reliably on a clean 10.9 install it would help us a lot.

**Comment by Morethanevil** [comment]
I can provide logs or anything elsed needed, but I can not reset the whole installation. Too much work, mark anything as read or watched again, import libaries and set the pictures... Sorry this would be too much. I am logged in as admin, I only have a second user without admin rights, but this happens on the admin account too. 

I am fine with the unstable version, it works except this playlist bug :(

**Comment by Morethanevil** [comment]
I tried a little bit with differfent files, maybe this is a hint:

[17:28:24] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /medien/music
[17:28:25] [INF] [22] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in Muuuuusiiik cannot be found at /medien/music/Bravo Hits/Bravo Hits 070/CD1/03.Lady Gaga-Alejandro.flac
[17:28:25] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: TaskCleanCollectionsAndPlaylists Completed after 0 minute(s) and 0 seconds
[17:28:26] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Aktualisiere Plugins Completed after 0 minute(s) and 1 seconds


Jellyfin cleaned the files at startup because the folder contains spaces. Maybe that is the case with files too.  But the files are available in Jellyfin after the startup. I can listen to them in the webapp and third party apps.

I can view the folder contents on my CLI with

ls /medien/music/Bravo\ Hits/Bravo\ Hits\ 070/CD1/

![Screenshot 2023-11-01 183305](https://github.com/jellyfin/jellyfin/assets/110860055/d4cbb8f8-ee80-4296-87bc-35498237c5b5)

**Comment by Morethanevil** [comment]
Setup v10.8.12, Playlists are working again. Closing this issue now

Nonetheless thanks for your hard work

**Comment by viasux** [comment]
I'm having this issue on v10.9.7

![image](https://github.com/jellyfin/jellyfin/assets/47131867/edcfbbf3-2792-444e-9194-17fb8b697882)

**Comment by bigfloppa234** [comment]
I am also expericing this issue - I have the Jellyfin app installed on TrueNAS and every time it gets restarted, my playlists get emptied 
![image](https://github.com/jellyfin/jellyfin/assets/104149053/36bd4ee5-3101-45c2-9c43-b9f8adfe66f7)
![image](https://github.com/jellyfin/jellyfin/assets/104149053/4a6aaea0-054b-42fe-acbb-0efcd6cea4cf)

**Comment by zynexiz** [comment]
Been having the same issue, all my playlists where suddenly empty. Just noticed that the android app I'm using to play the music from Jellyfin (Symfonium) stores a local copy of the playlist, so I could just push the local copy to Jellyfin to restore it.

**Comment by onny** [comment]
Could we please reopen the issue? Still experiencing the issue with the latest version (10.9.7) @Bond-009

**Comment by Bond-009** [comment]
Please open a new issue if you're experiencing this.
(Since this was closed by the OP and not stalebot I won't reopen it)
