### ISSUE TITLE
[Issue]: Send "Stop Stream" UDP message to HDHomeRun before "Start Stream" UDP message

### ISSUE THREAD

**Issue by habeebtc** [jellyfin/jellyfin#10505]
### Send "Stop Stream" UDP message to HDHomeRun before "Start Stream" UDP message

Currently when you start a stream, it sends a UDP message to tell the box the IP and port to use for the stream. If there is already a stream being broadcast, it will fail with an error "Failed to Open Tuner" or "Tuner Busy" or somesuch.

The problem is - the stream can continue on even if the consumer has stopped listening. Such is the nature of UDP. I have had a few situations where if transcoding failed to start properly, the stream would just run forever, and you can't retry because the tuner is already in use - even though the UDP packet being sent is asking to start a new stream being sent to the same destination port and IP that already is receiving a stream. This is just one use case, I have run into other combinations of weird behaviors where I try a stream first with the HDHomeRun app, and for some reason the stream continues on after I close the HDHomeRun app, and then JellyFin can't start a new stream.

I originally submitted this as a feature request: 

https://features.jellyfin.org/posts/2418/send-stop-stream-udp-message-to-hdhomerun-before-start-stream-udp-message

...But they advised I submit this as a server issue.

Why I think this is a feature request:

Let's consider the two possible outcomes of either sending STOP before START, or not sending STOP before START UDP messages to the tuner:

**Not sending STOP**

1. Opens up the possibility of a runaway stream if some issue occurs (STOP message getting lost or not sent for some reason by JellyFin or another client)
2. Also avoids killing off a stream another user is watching, allowing them to continue.  JellyFin is a multi-user system after all.

**Sending STOP**

1. Can clean up a runaway stream
2. Also will interrupt another user in the process of streaming

In a perfect world, you'd be presented the option to stop the existing stream if there's one ongoing.  JellyFin should be able to differentiate between a stream it is broadcasting (which it should have knowledge of; you can see this in the dashboard), and one it is being sent but not using (which, it would not be at all aware of).  If JellyFin is not aware of the runaway stream, it will should send STOP before START and the user will be unaware that there was ever an issue.  I only own one supported streaming device but I *think* this is going to be true of most streaming devices.

So - that's actually more than a one-line fix, hence my posting it as a feature request.  STOP before START would be implemented in the various plugins, and also the main system in order to check and prompt.  You guys tell me if it should be a feature request, or a server issue.  Either way!

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows server 2022
- Virtualization: NA
- Clients: Web, Android, WebOS
- Browser: Brave
- FFmpeg Version:
- Playback Method: LiveTV
- Hardware Acceleration: NA
- GPU Model: NA 
- Plugins: none
- Reverse Proxy: NGINX
- Base URL: 
- Networking: 1x GB Ethernet
- Storage: 2x 14tb SATA mirrored
```

### Jellyfin logs

```shell
[2023-10-30 01:14:11.160 -05:00] [INF] [94] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="http://192.168.2.13", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported, AudioCodecNotSupported ) "media:/videos/23f50ea8-47eb-4700-cd53-009b224ac0ce/master.m3u8?MediaSourceId=native_38e2ec422972cf18ae399822dbeeeca8_bc6b703ade5c83c9c39f37fa83a79f71&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=-1&VideoBitrate=139808000&AudioBitrate=192000&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-rangetype=SDR&h264-level=52&h264-deinterlace=true&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported,%20AudioCodecNotSupported"
[2023-10-30 01:14:11.163 -05:00] [INF] [94] Emby.Server.Implementations.LiveTv.LiveTvManager: Opening channel stream from "Emby", external channel Id: "hdhr_11.1"
[2023-10-30 01:14:11.165 -05:00] [INF] [94] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Streaming Channel "hdhr_11.1"
[2023-10-30 01:14:11.166 -05:00] [INF] [94] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: GetChannelStream: channel id: "hdhr_11.1". stream id: "native_38e2ec422972cf18ae399822dbeeeca8_bc6b703ade5c83c9c39f37fa83a79f71" profile: "native"
[2023-10-30 01:14:11.169 -05:00] [INF] [94] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Opening HDHR UDP Live stream from "192.168.2.13"
[2023-10-30 01:14:11.172 -05:00] [ERR] [120] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error opening live stream:
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunManager.StartStreaming(IPAddress remoteIp, IPAddress localIp, Int32 localPort, IHdHomerunChannelCommands commands, Int32 numTuners, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunUdpStream.Open(CancellationToken openCancellationToken)
[2023-10-30 01:14:11.175 -05:00] [ERR] [120] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error opening tuner
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by habeebtc** [comment]
For anyone reading this who might want a manual workaround - I have found that loading the HDH app from the destination of the runaway stream will pick up the existing stream.  Exiting the HDH app usually sends the STOP message, and you're back in a good state.
