### ISSUE TITLE
[Issue]: Error with database "Value cannot be null"

### ISSUE THREAD

**Issue by mateowtf** [jellyfin/jellyfin#10545]
### Please describe your bug

Hi, a few hours after upgrade to 10.8.12 the database got corrupted(?), I cant start the server, look like I have the same problem as described [here](https://github.com/jellyfin/jellyfin/issues/7928#issue-1269919742) that can be fixed by setting a value to PasswordResetProviderId with the command 

```shell
sqlite3 jellyfin.db "update Users SET PasswordResetProviderId = 'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' where PasswordResetProviderId = '';"
```

But it doesnt work for me, my server still not starting.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.2.19
- Virtualization: NO
```

### Jellyfin logs

```shell
[2023-11-08 09:06:07.072 +01:00] [FTL] Error while starting server.
System.ArgumentNullException: Value cannot be null. (Parameter 'authenticationProviderId')
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method44(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chris-Codes-It** [comment]
@mateowtf a similar SQL command needs to be run to fix this issue

`update Users SET AuthenticationProviderId = 'Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider' where PasswordResetProviderId = '';`

**Comment by imbotcode** [comment]
Hey, I had a similar problem, the issue was due to a User with an empty `AuthenticationProviderId` in the database:
```shell
sqlite3 jellyfin.db "SELECT count(1) FROM Users WHERE AuthenticationProviderId = '';"
1
``` 
If the command above returns 1 or more, you can fix it by doing this:
```shell
sqlite3 jellyfin.db "UPDATE Users SET AuthenticationProviderId = 'Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider' WHERE AuthenticationProviderId = '';"
``` 
Then the first command should return 0
