### ISSUE TITLE
[Issue]: Post processing doesn't work on shows with an exclamation point in the path (linux)

### ISSUE THREAD

**Issue by pygmymarmoset** [jellyfin/jellyfin#10555]
### Please describe your bug

Trying to run post processing on Jeopardy (official name "Jeopardy!") results in failure.

Log lines:

[2023-11-07 20:00:00.011 -08:00] [INF] Running recording post processor "/usr/local/bin/jf.bash" "/var/lib/jellyfin/data/livetv/recordings/Jeopardy!/Season 40/Jeopardy! S40E42 Champions Wildcard.ts"
[2023-11-07 20:00:00.031 -08:00] [INF] Recording post-processing script completed with exit code 1

Example when run manually:

$ "/usr/local/bin/jf.bash" "/var/lib/jellyfin/data/livetv/recordings/Jeopardy!/Season 40/Jeopardy! S40E41 Champions Wildcard.ts"
-bash: !/Season: event not found
$ 

Command line arguments are just: {path}

Adding single quotes around that (IE '{path}') has the same result.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Linux Kernel: 5.10.0-26-amd64
- Virtualization: kvm
- Clients: n/a
- Browser: n/a
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:  n/a
- Hardware Acceleration: n/a 
- GPU Model: n/a 
- Plugins: n/a 
- Reverse Proxy: n/a
- Base URL: n/a 
- Networking: n/a
- Storage: n/a
```

### Jellyfin logs

```shell
[2023-11-07 20:00:00.011 -08:00] [INF] Running recording post processor "/usr/local/bin/jf.bash" "/var/lib/jellyfin/data/livetv/recordings/Jeopardy!/Season 40/Jeopardy! S40E42 Champions Wildcard.ts"
[2023-11-07 20:00:00.031 -08:00] [INF] Recording post-processing script completed with exit code 1
```

### Please attach any screenshots here

![Screenshot at 2023-11-08 19-57-51](https://github.com/jellyfin/jellyfin/assets/5187169/0f663a06-84e5-44ab-a91c-4e6668ad0a45)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chibiconsulting** [comment]
Could the ['] character also cause this?

Error recording to "/Recordings/NCIS: Hawai'i/Season 3/NCIS: Hawai'i S03E05 Serve and Protect.ts"
System.IO.IOException: Invalid argument : '/Recordings/NCIS: Hawai'i/Season 3'
  at System.IO.FileSystem.CreateDirectory(String fullPath)
  at System.IO.Directory.CreateDirectory(String path)
  at Emby.Server.Implementations.LiveTv.EmbyTV.DirectRecorder.RecordFromDirectStreamProvider(IDirectStreamProvider directStreamProvider, String targetFile, TimeSpan duration, Action onStarted, CancellationToken cancellationToken)
  at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo)

Version: 10.8.13
Operating System: Linux
Architecture: X64

**Comment by Shadowghost** [comment]
Looks like a missed path escape somewhere in the recorder logic, I'll take a look if I find some time if nobody else does.

**Comment by crobibero** [comment]
The post processing arguments should be `"{path}"`
Did you happen to modify this field? On my server the path variable is quoted

**Comment by crobibero** [comment]
> The post processing arguments should be `"{path}"` Did you happen to modify this field? On my server the path variable is quoted

**Comment by pygmymarmoset** [comment]
@crobibero I have tried it both with and without the quotes, as well as trying with single quotes (should have put it back to stock before taking the screenshot)
