### ISSUE TITLE
[Issue]: Error updating device info for  tv

### ISSUE THREAD

**Issue by burncode** [jellyfin/jellyfin#10608]
### Please describe your bug

It has been running very well until recently。My Xiaomi TV cannot connect to the Jellyfin server，But all other devices are good, such as Android phones, web browsers, and vlc.

log:

[13:22:17] [ERR] [19] Emby.Dlna.Main.DlnaHost: Error updating device info for  burncode‘s tv
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.DlnaHttpClient.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.DlnaHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-11-20 13:22:16.749 +08:00] [INF] [22] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
DeviceIdentification { FriendlyName: " burncode的电视", ModelNumber: null, SerialNumber: null, ModelName: "Xiaomi MediaRenderer", ModelDescription: "Xiaomi MediaRenderer", ModelUrl: "http://www.xiaomi.com/hezi", Manufacturer: "Xiaomi", ManufacturerUrl: "http://www.xiaomi.com/", Headers: [] }
[2023-11-20 13:22:16.753 +08:00] [INF] [22] Emby.Dlna.Main.DlnaHost: DLNA Session created for " burncode的电视" - "Xiaomi MediaRenderer"
[2023-11-20 13:22:17.539 +08:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "更新插件" Completed after 0 minute(s) and 2 seconds
[2023-11-20 13:22:17.758 +08:00] [ERR] [19] Emby.Dlna.Main.DlnaHost: Error updating device info for " burncode的电视"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.DlnaHttpClient.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.DlnaHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
[2023-11-20 13:31:27.955 +08:00] [INF] [36] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.50.132" request
[2023-11-20 13:32:16.236 +08:00] [INF] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-11-20 13:32:16.242 +08:00] [WRN] [10] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.50.132" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-20 13:32:16.300 +08:00] [INF] [10] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.50.132" closed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solidsnake1298** [comment]
May I ask why you closed this ticket?  Were you able to resolve this issue.  I'm working with another user with a similar problem with their Xiaomi TV.
