### ISSUE TITLE
Poster cannot be downloaded[Issue]: 

### ISSUE THREAD

**Issue by oditian** [jellyfin/jellyfin#10616]
### Please describe your bug

Tip: 
Root element is missing
Insufficient disk space
My disk space is enough

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-11-22 20:43:10.587 +08:00] [ERR] [90] MediaBrowser.XbmcMetadata.Savers.MovieNfoSaver: Error reading existing xml tags from "\\192.168.0.*\xxx.nfo".
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCustomTags(String path, IReadOnlyCollection`1 xmlTagsUsed, XmlWriter writer, ILogger`1 logger)
[2023-11-22 20:43:10.633 +08:00] [ERR] [125] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: 磁盘空间不足。
   at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2023-11-22 20:43:27.262 +08:00] [WRN] [56] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Items/7ad19e74b1a18f932e3cb5867c2a8882/Images/Backdrop/0?tag=596f37ac63521ad8dea7af9a4abb278d&maxWidth=2880&quality=80" to "127.0.0.1" in 0:00:00.8177361 with Status Code 200
[2023-11-22 20:43:41.476 +08:00] [ERR] [56] Emby.Drawing.ImageProcessor: Error encoding image
System.IO.InvalidDataException: Skia unable to read image D:\SoftWare\Media\Jellyfin\data\metadata\library\54\54fd99733a2fcdd6281e1c6c8ff3c027\backdrop.jpg
   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat outputFormat)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
[2023-11-22 20:43:41.476 +08:00] [ERR] [124] Emby.Drawing.ImageProcessor: Error encoding image
System.IO.InvalidDataException: Skia unable to read image D:\SoftWare\Media\Jellyfin\data\metadata\library\54\54fd99733a2fcdd6281e1c6c8ff3c027\backdrop.jpg
   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat outputFormat)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
[2023-11-22 20:47:12.363 +08:00] [INF] [141] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-11-22 20:48:12.418 +08:00] [INF] [122] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-11-22 20:49:12.487 +08:00] [INF] [68] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, the logs indicate that you do not have enough disk space in the metadata directory. Please make sure that there is sufficient free space in both your media library and your JF metadata drive and your system is not corrupted. Closing this as it does not contain an actual Jellyfin bug.
