### ISSUE TITLE
[Issue]: Startup problem jellyfin-web

### ISSUE THREAD

**Issue by porsevdv** [jellyfin/jellyfin#10615]
### Please describe your bug

hello everyone, I understand the error is already known, but everything that I found did not help me solve it after starting the service, it takes just a couple of minutes, and the service stops working only if you run it directly from the console.
Method with the command ln -s /usr/share/jellyfin/web /usr/lib/jellyfin/bin/jellyfin-web does not work

### Jellyfin Version

10.8.z

### if other:

10.8.12

### Environment

```markdown
- Debin
- kernel 6
- GPU Model: intel
```

### Jellyfin logs

```shell
[2023-11-21 20:30:23.203 +05:00] [INF] Jellyfin version: "10.8.12"
[2023-11-21 20:30:23.313 +05:00] [INF] Environment Variables: ["[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]"]
[2023-11-21 20:30:23.321 +05:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-11-21 20:30:23.323 +05:00] [INF] Operating system: "Linux"
[2023-11-21 20:30:23.324 +05:00] [INF] Architecture: X64
[2023-11-21 20:30:23.326 +05:00] [INF] 64-Bit Process: True
[2023-11-21 20:30:23.326 +05:00] [INF] User Interactive: True
[2023-11-21 20:30:23.326 +05:00] [INF] Processor count: 4
[2023-11-21 20:30:23.326 +05:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-11-21 20:30:23.326 +05:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-11-21 20:30:23.326 +05:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-11-21 20:30:23.476 +05:00] [FTL] Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2023-11-21 20:30:24.678 +05:00] [INF] Jellyfin version: "10.8.12"
[2023-11-21 20:30:24.789 +05:00] [INF] Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]"]
[2023-11-21 20:30:24.797 +05:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-11-21 20:30:24.800 +05:00] [INF] Operating system: "Linux"
[2023-11-21 20:30:24.800 +05:00] [INF] Architecture: X64
[2023-11-21 20:30:24.802 +05:00] [INF] 64-Bit Process: True
[2023-11-21 20:30:24.802 +05:00] [INF] User Interactive: True
[2023-11-21 20:30:24.802 +05:00] [INF] Processor count: 4
[2023-11-21 20:30:24.802 +05:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-11-21 20:30:24.803 +05:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-11-21 20:30:24.803 +05:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-11-21 20:30:24.948 +05:00] [FTL] Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2023-11-21 20:30:26.157 +05:00] [INF] Jellyfin version: "10.8.12"
[2023-11-21 20:30:26.269 +05:00] [INF] Environment Variables: ["[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]"]
[2023-11-21 20:30:26.276 +05:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-11-21 20:30:26.278 +05:00] [INF] Operating system: "Linux"
[2023-11-21 20:30:26.279 +05:00] [INF] Architecture: X64
[2023-11-21 20:30:26.281 +05:00] [INF] 64-Bit Process: True
[2023-11-21 20:30:26.281 +05:00] [INF] User Interactive: True
[2023-11-21 20:30:26.281 +05:00] [INF] Processor count: 4
[2023-11-21 20:30:26.281 +05:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-11-21 20:30:26.281 +05:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-11-21 20:30:26.281 +05:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-11-21 20:30:27.657 +05:00] [INF] Jellyfin version: "10.8.12"
[2023-11-21 20:30:27.769 +05:00] [INF] Environment Variables: ["[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]"]
[2023-11-21 20:30:27.777 +05:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-11-21 20:30:27.779 +05:00] [INF] Operating system: "Linux"
[2023-11-21 20:30:27.780 +05:00] [INF] Architecture: X64
[2023-11-21 20:30:27.782 +05:00] [INF] 64-Bit Process: True
[2023-11-21 20:30:27.782 +05:00] [INF] User Interactive: True
[2023-11-21 20:30:27.782 +05:00] [INF] Processor count: 4
[2023-11-21 20:30:27.782 +05:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-11-21 20:30:27.783 +05:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-11-21 20:30:27.783 +05:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-11-21 20:30:27.929 +05:00] [FTL] Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2023-11-21 20:30:29.140 +05:00] [INF] Jellyfin version: "10.8.12"
[2023-11-21 20:30:29.253 +05:00] [INF] Environment Variables: ["[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_USER, jellyfin]"]
[2023-11-21 20:30:29.260 +05:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-11-21 20:30:29.263 +05:00] [INF] Operating system: "Linux"
[2023-11-21 20:30:29.263 +05:00] [INF] Architecture: X64
[2023-11-21 20:30:29.265 +05:00] [INF] 64-Bit Process: True
[2023-11-21 20:30:29.265 +05:00] [INF] User Interactive: True
[2023-11-21 20:30:29.265 +05:00] [INF] Processor count: 4
[2023-11-21 20:30:29.266 +05:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-11-21 20:30:29.266 +05:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-11-21 20:30:29.266 +05:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-11-21 20:30:29.414 +05:00] [FTL] Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

### Please attach any screenshots here

![2023-11-22 00 00 47](https://github.com/jellyfin/jellyfin/assets/55794273/0119eb92-b064-4914-bafc-147065593460)
![2023-11-22 00 50 16](https://github.com/jellyfin/jellyfin/assets/55794273/60cc538a-4fe2-4ecc-810b-530a1bdde9b0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
However i agree that JF either should print a more verbose and concrete message or try to heal the configuration if possible and if not should print another verbose message.

**Comment by CyferShepard** [comment]
Hi Im also having this issue, my OS drive ran out of space which then seems to have triggered this error, im running Jellyfin in Docker V.10.8.13, freeing up space didnt fix the problem

**Comment by CyferShepard** [comment]
Thanks @JPVenson , managed to figure that out, just was stuck on how to access the docker volume, eventually i got it mounted on another container and was able to repair it
