### ISSUE TITLE
[Issue]: Websocket remote party closed causes memory leak

### ISSUE THREAD

**Issue by Spiritreader** [jellyfin/jellyfin#10614]
### Please describe your bug

HI, I've talked to Venson 2.0 on the Matrix jellyfin troubleshoot channel about a memory leak issue I've been encountering.

The pattern is that after a few days/weeks, suddenly Jellyfin's memory usage starts rising indefinitely in a very short timeframe.
At that point any updates to the database are no longer possible.
It's no longer possible to log in and create a new user session, and new playback sessions are no longer updated / stored.

I've included the events in question that cause the issue. There are multiple of these events per day, around 10-20 until at some point the issue starts appearing.

Grafana Jellyfin RAM usage screenshot
![image](https://github.com/jellyfin/jellyfin/assets/18438899/f80356ae-1903-4c12-b300-052e4f14eeab)

This goes on until the system runs out of memory, or, the container memory limit has been reached. Then either jellyfin or the system hangs.

Related to #10613

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Slackware 15.0
- Linux Kernel: 5.19.17-Unraid
- Virtualization: Docker
- Clients: All
- Browser: Any
- FFmpeg Version: ffmpeg version 5.1.3-Jellyfin
- Playback Method: Any
- Hardware Acceleration: NVENC
- GPU Model: GTX 1070
- Plugins: PlaybackReportingPlugin
- Reverse Proxy: Yes
- Base URL: None
- Networking: Bridge
- Storage: local, appdata on ssd
```

### Jellyfin logs

```shell
[2023-11-21 00:19:53.962 +01:00] [WRN] [97] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 04:21:18.467 +01:00] [WRN] [107] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 09:45:16.337 +01:00] [WRN] [69] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 10:12:26.702 +01:00] [WRN] [78] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 11:41:38.947 +01:00] [WRN] [37] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 16:48:05.022 +01:00] [WRN] [56] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 16:52:51.379 +01:00] [WRN] [120] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 18:18:52.589 +01:00] [WRN] [58] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 18:37:29.907 +01:00] [WRN] [57] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 21:24:26.143 +01:00] [WRN] [28] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 21:31:29.051 +01:00] [WRN] [49] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 21:56:08.191 +01:00] [WRN] [113] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-11-21 22:24:20.117 +01:00] [WRN] [299] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "client" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake.
```

```
System.Exception: Error saving playback state: database is locked
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at Jellyfin.Api.Controllers.PlaystateController.ReportPlaybackProgress(PlaybackProgressInfo playbackProgressInfo)
   at lambda_method432(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Please don't truncate the log. A lot of the context is missing.

**Comment by Spiritreader** [comment]
> Please don't truncate the log. A lot of the context is missing.

I've been instructed to create this issue to document https://github.com/jellyfin/jellyfin/pull/10613

This was fixed by @JPVenson and hasn't happened again since the fix got merged.
