### ISSUE TITLE
[Issue]: Cannot download subtitles because file already exists

### ISSUE THREAD

**Issue by zjeffer** [jellyfin/jellyfin#10662]
### Please describe your bug

I have a movie that automatically downloaded 2 subtitles (one for each language I enabled in the jellyfin settings).
One of them is not correctly synced, so I'm trying to download a different one.

I'm having two problems:

1. I cannot delete the existing subtitle. If I do, it automatically redownloads it from opensubtitles. 
2. I cannot download a new one. If I do, I get the error in the log. It's saying that the subtitle cannot be downloaded because the file already exists. It seems it always wants to download it to the same filename (`<movie filename>.<language>.srt`), no matter which file I download. I would assume it should download the file to something like `<movie filename>.<language>.<number>.srt`, but it doesn't try to do that.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Raspberry Pi Bookworm
- Linux Kernel: `6.1.0-rpi4-rpi-v8`
- Virtualization: Docker
- Clients: Jellyfin Media Player on Linux
- Browser: Firefox
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: OpenSubtitles
- Reverse Proxy:
- Base URL:
- Networking: 
- Storage: 4TB External HDD
```

### Jellyfin logs

```shell
[17:25:46] [INF] [93] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 997
[17:25:48] [INF] [78] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
[17:25:48] [INF] [78] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
[17:25:48] [ERR] [78] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
System.AggregateException: One or more errors occurred. (Access to the path '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' is denied.) (The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.)
 ---> System.UnauthorizedAccessException: Access to the path '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
   --- End of inner exception stack trace ---
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)
 ---> (Inner Exception #1) System.IO.IOException: The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)<---
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zjeffer** [comment]
The download works if I manually delete the .srt file through ssh in `/config/data/metadata/library/...`, but that obviously isn't a good solution:

```
[18:17:05] [INF] [42] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 996
[18:17:06] [INF] [47] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
[18:17:06] [INF] [47] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
```

**Comment by zjeffer** [comment]
Thanks for pointing me in the right direction ;)

I got help from @sevenrats in the matrix chat: the issue was my PUID and PGUID were not set correctly in my docker-compose file. I had to add this to my jellyfin service:

```yaml
environment:
  - PUID=1000
  - PGID=1000
```

Now the files correctly download. I still can't download multiple files, though (same "already exists" error), but we think it's an issue with the OpenSubtitles plugin. I'll ask them for information about this.
