### ISSUE TITLE
[Issue]: macOS Jellyfin combined installer 10.8.13 is missing ffprobe

### ISSUE THREAD

**Issue by mplough** [jellyfin/jellyfin#10664]
### Please describe your bug

With the Jellyfin 10.8.10 combined installer on macOS, both `ffmpeg` and `ffprobe` are present:

```console
$ cd [path/to/Jellyfin 10.8.10.app]/Contents/Macos
$ find . -name 'ff*'
./ffmpeg
./ffprobe
```

With 10.8.13, `ffprobe is absent:

```console
$ cd [path/to/Jellyfin 10.8.13.app]/Contents/Macos
$ find . -name 'ff*'
./ffmpeg
```

This results in tons of log output of this form when scanning library data:
```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ffprobe' with working directory '/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mplough** [comment]
@felix920506 - what is the right repo for this issue?
