### ISSUE TITLE
[Issue]: Multi-Part Audiobook being treated as folder with indivdual files instead of one book

### ISSUE THREAD

**Issue by verybadsoldier** [jellyfin/jellyfin#10668]
### Please describe your bug

When having an audiobook in one folder consisting of multiple MP3 files, then JF does not treat it as one audiobook but treats it as a folder showing multiples files.

I have this structure:
```
D:\JELLYTEST\BOOKS
└───audiobooks
    └───John Doe
        └───MyAudiobook
                01 Chapter.mp3
                02 Chapter.mp3
                03 Chapter.mp3
                04 Chapter.mp3
                05 Chapter.mp3
```

Then in JF, the "MyAudiobook" is shown as a folder which you cannot play directly:
![image](https://github.com/jellyfin/jellyfin/assets/364469/094a110a-8dc2-49bd-ad03-dca37024c5fe)

Then, inside this folder I get individual files that I can play:
![image](https://github.com/jellyfin/jellyfin/assets/364469/6d36e590-afce-4565-aefa-c03ef503ce78)

Also, on the landing page, as "New Media", every file as shown as separate audiobook:
![image](https://github.com/jellyfin/jellyfin/assets/364469/cafb4960-8790-43c8-8844-6707b0fc3fd2)

My expectation of this whole thing would be, that "MyAudiobook" is detected as one single audiobook by JF and you can directly play it. Also, on the landing page, it should only show up as one audiobook.

But maybe my expectation is just wrong, thanks!

I usually use JF on Linux as docker, but for this demonstration purpose, I have set up an instance on my Windows machine to make it easier to play around with it.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Plugins: Bookshelf
- Storage: Local
```

### Jellyfin logs

```shell
[15:16:18] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:18] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: CollectionFolderImageProvider reports change to C:\Users\vbs\AppData\Local\jellyfin\root\default\Bücher
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Running CollectionFolderImageProvider for C:\Users\vbs\AppData\Local\jellyfin\root\default\Bücher
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 83f9e93e64281eca1beab3b7c2cf2be3
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 5
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 10
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart fa9178b3db68df960288e9c08deb1f86
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 12
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 5
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 14
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 10
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 624314d3d13bfe17e56ab7354c786065
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 14.8
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 12
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 624314d3d13bfe17e56ab7354c786065 5
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 15.600000000000001
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 14
[15:16:18] [DBG] [78] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 624314d3d13bfe17e56ab7354c786065 10
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 8778a07f6a08f18edd99e817738582ce
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 16
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 14.8
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 624314d3d13bfe17e56ab7354c786065 12
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 8778a07f6a08f18edd99e817738582ce 5
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 16.4
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 15.600000000000001
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 624314d3d13bfe17e56ab7354c786065 14
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 8778a07f6a08f18edd99e817738582ce 10
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete 8778a07f6a08f18edd99e817738582ce
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 22
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 30
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 624314d3d13bfe17e56ab7354c786065 50
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete 624314d3d13bfe17e56ab7354c786065
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 30
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress fa9178b3db68df960288e9c08deb1f86 50
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete fa9178b3db68df960288e9c08deb1f86
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 50
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 50
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.FolderMetadataService: FolderImageProvider reports change to D:\jellytest\books\audiobooks
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.FolderMetadataService: Running FolderImageProvider for D:\jellytest\books\audiobooks
[15:16:18] [DBG] [65] MediaBrowser.Providers.Folders.FolderMetadataService: FolderImageProvider reports change to D:\jellytest\books\audiobooks\John Doe
[15:16:18] [DBG] [65] MediaBrowser.Providers.Folders.FolderMetadataService: Running FolderImageProvider for D:\jellytest\books\audiobooks\John Doe
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.FolderMetadataService: FolderImageProvider reports change to D:\jellytest\books\audiobooks\John Doe\MyAudiobook
[15:16:18] [DBG] [78] MediaBrowser.Providers.Folders.FolderMetadataService: Running FolderImageProvider for D:\jellytest\books\audiobooks\John Doe\MyAudiobook
[15:16:18] [DBG] [25] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 70
[15:16:18] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 80
[15:16:18] [DBG] [42] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 70
[15:16:18] [DBG] [65] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 90
[15:16:18] [DBG] [66] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 100
[15:16:19] [DBG] [66] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 83f9e93e64281eca1beab3b7c2cf2be3 100
[15:16:19] [DBG] [64] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete 83f9e93e64281eca1beab3b7c2cf2be3
[15:16:19] [DBG] [65] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[15:16:20] [DBG] [64] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 127.0.0.1 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[15:16:25] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[15:16:27] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [64] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [64] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [64] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [42] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [25] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [64] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [42] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [25] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:27] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [84] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [84] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SongCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SongCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter) in C:\Users\vbs\Documents\Projects\jellyfin\Jellyfin.Api\ModelBinders\CommaDelimitedArrayModelBinder.cs:line 67
[15:16:28] [DBG] [78] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:28] [DBG] [78] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:29] [DBG] [78] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:29] [DBG] [78] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:29] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:29] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:29] [DBG] [65] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SongCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SongCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter) in C:\Users\vbs\Documents\Projects\jellyfin\Jellyfin.Api\ModelBinders\CommaDelimitedArrayModelBinder.cs:line 67
[15:16:30] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:30] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:30] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:30] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:30] [DBG] [65] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SongCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SongCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter) in C:\Users\vbs\Documents\Projects\jellyfin\Jellyfin.Api\ModelBinders\CommaDelimitedArrayModelBinder.cs:line 67
[15:16:31] [DBG] [78] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[15:16:31] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:31] [DBG] [65] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:31] [DBG] [66] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:31] [DBG] [66] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[15:16:31] [DBG] [66] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SongCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SongCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter) in C:\Users\vbs\Documents\Projects\jellyfin\Jellyfin.Api\ModelBinders\CommaDelimitedArrayModelBinder.cs:line 67
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexfornuto** [comment]
Commenting for un-stalenes. This is an issue I'd appreciate being looked at.

**Comment by nylimited** [comment]
The described behaviour is true and not likely correct. Audiobooks are often comprised of many (hundreds) of tracks, nonetheless, they make up one book.  The treatment should be not unlike a music album with multiple tracks - play next, play all, etc.  Seldom would anyone use shuffle in an audiobook.

**Comment by nowottnya** [comment]
I'm happy to see that there is already a pull request for this issue. Just installed Jellyfin for the first time was disappointed that my audiobooks were not displayed as I expected. Looking forward to the next release were the fix is included.

**Comment by seimenx** [comment]
Any chance of the MR to be reviewed? Would make the audio book experience so much more workable!

**Comment by felix920506** [comment]
Web team is quite busy, maybe you can look at the code and leave your own review so the web team has less work to do.

**Comment by alexfornuto** [comment]
un-staling comment. Issue is valid. PR is in place to resolve.

**Comment by benediktkeller** [comment]
unstaling comment. Pull request waiting for review and release.

**Comment by imhoff** [comment]
This continues to be a problem for anyone that has collections of audiobooks and practically makes Jellyfin unusable for such media. There should be at least a note in the documentation on missing multi-part support until this PR is integrated.

**Comment by 0x62ash** [comment]
> This continues to be a problem for anyone that has collections of audiobooks and practically makes Jellyfin unusable for such media. There should be at least a note in the documentation on missing multi-part support until this PR is integrated.

A temporary solution is to add audiobooks as a Music Library.

**Comment by benediktkeller** [comment]
> > This continues to be a problem for anyone that has collections of audiobooks and practically makes Jellyfin unusable for such media. There should be at least a note in the documentation on missing multi-part support until this PR is integrated.
> 
> A temporary solution is to add audiobooks as a Music Library.

I don't think so, as a music library it won't keep my progress, so it's not useable to me...

**Comment by Mouseater** [comment]
Still an issue, is this even being looked at? Does anyone know of a plugin or work around for this?

**Comment by Proxycon** [comment]
I wanted to chip in, the issue persists and eliminates Jellyfin as Audiobook Server. The fixing [pull request](https://github.com/jellyfin/jellyfin-web/pull/5603) is waiting for review for 2 years and of course by now 5k commits behind. I would appreciate a revisit very much.

**Comment by Mouseater** [comment]
It would be really nice if someone from Jellyfin could at least respond here, this issue makes jellyfin a none option for audio books for a lot of users and if there is a fix in a PR why can't we get it in?

**Comment by Victor-Hugenay** [comment]
Does anyone here have the skills to code a plugin for this? I mean, it's 'just' combining existing functions to a new media type.

**Comment by Mouseater** [comment]
> Does anyone here have the skills to code a plugin for this? I mean, it's 'just' combining existing functions to a new media type.

The comment above mine has a link to a PR from 2 years ago where someone put the code up to fix the issue that just got ignored and never reviewed. It's likely that at this point the Jellyfin devs just don't care about audiobook support is my guess and their only focus is tv/movies.

**Comment by RadioFoxProductions** [comment]
Still a major issue for the software and it's been this long? really? major problem, especially because when i first started setting up my server nobody said anything about this being an issue. I've just moved to using audiobookshelf when i can, but this shouldnt be a problem at all.

Having this issue too, if you couldnt tell

**Comment by Proxycon** [comment]
I switched to AudioBookShelf already, this looks like it's not a priority (which is fair, just unfortunate)

**Comment by Mouseater** [comment]
Audio book shelf has been my solution as well for now, I really like Jellyfin though and wanted to stay inside there for all of my media. I think that audio books are extremely low though since the music player also needs work and I imagine more people are asking for music when compared to audiobooks.
