### ISSUE TITLE
[Issue]: Locked out of Admin Account

### ISSUE THREAD

**Issue by nzagler** [jellyfin/jellyfin#10670]
### Please describe your bug

Can somebody help me with this?
i have already tried to give me acces again with the jellyfin.db file (https://jellyfin.org/docs/general/administration/troubleshooting/)
but it just wont work.
```
[20:23:42] [INF] [36] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for Smart TV - Renderer
[20:25:36] [ERR] [53] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[20:25:36] [INF] [53] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for steini has been denied because this account is currently disabled (IP: MYIP.MYIP.MYIP.MYIP).
[20:25:36] [ERR] [53] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: [MYIP.MYIP.MYIP] The steini account is currently disabled. Please consult with your administrator. URL POST /Users/authenticatebyname.

```

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: UnraidOS
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: Vivaldi
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sjorge** [comment]
Have you tried the 'Forget Password' button on the login screen ?
It should write a temp password to a file on the host.

**Comment by felix920506** [comment]
Please head to our chat rooms or forum for support https://jellyfin.org/contact
