### ISSUE TITLE
[Issue]: Cannot Delete Backdrop Images

### ISSUE THREAD

**Issue by brandoningli** [jellyfin/jellyfin#10683]
### Please describe your bug

I added a custom backdrop image jpg to an album, and it initially displayed fine. However, it suddenly went black, and I cannot delete it from the Edit Images UI. If I attempt to add it again, it shows another empty card in the backdrop section, and I cannot delete that one either. I am _not_ storing artwork in the media folders.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Server 20.04 LTS
- Linux Kernel: 5.4
- Virtualization: ESXi VM
- Clients: Android, Roku
- Browser: Firefox
- FFmpeg Version: 5.1.4
- Playback Method: Direct
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: apache
- Base URL: none
- Networking: Host
- Storage: SMB for media, local for artwork
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brandoningli** [comment]
I'll work on adding these specifics here soon, but I just ran across one more potentially useful piece of information:
When attempting to visit one of the file urls directly (https://jellyfin.mydomain/Items/772761c93bfad29b2762eb41d4e6e282/Images/Backdrop/3?maxWidth=430&tag=103cb1581a118072a839bea9e844373b&quality=80), I get a message saying `WorldWired Tour, St. Louis, Missouri, June 4, 2017 does not have an image of type Backdrop`, with `WorldWired Tour, St. Louis, Missouri, June 4, 2017` being the name of the album.

Here is the Edit Images dialog as well. 
![image](https://github.com/jellyfin/jellyfin/assets/6826623/080f0e47-e26c-41c4-9542-7951de3e17c6)

**Comment by brandoningli** [comment]
1. **operating system and version**: Ubuntu 20.04 Server LTS
2. **the file tree itself (the directory of the media)**: Media in e.g. `/mnt/music/Metallica/WorldWired Tour, St. Louis, Missouri, June 4, 2017/101 - Hardwired.m4a`. Metadata in `/var/lib/jellyfin/metadata`.
3. **the permissions on your metadata directory**: `drwxr-xr-x 7 jellyfin jellyfin`
4. **the specific titles and urls to the jpegs you have been able to produce this with (you can get these with inspector)**: The specific JPG doesn't seem to be an issue, but one I've had this issue with is `https://cdn.media.amplience.net/i/metallica/2017-06jun04_social` as `met_busch_2017.jpg`
5. **picture of or clear descriptions of what you see above and beyond "empty" and "black". picture would be best.**
![image](https://github.com/jellyfin/jellyfin/assets/6826623/83033ec3-5c0f-4481-9d8a-370082758ec8)
(See my previous comment for a screenshot of the edit images modal)

**Comment by brandoningli** [comment]
Keeping this open. Any progress on recreating the issue? I'll also make sure I'm up to date and try again on my end once I have an opportunity.

**Comment by kandykarter** [comment]
I have this issue or a variant thereof. I tried to add backdrop images to a movie, and got an endless spinning wheel. From my logs:

> [2024-05-13 19:25:29.533 -07:00] [ERR] [112] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/data/movies/Audrey Rose (1977)/backdrop1.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-05-13 19:25:29.562 -07:00] [ERR] [115] Jellyfin.Drawing.ImageProcessor: Error encoding image
System.IO.InvalidDataException: Skia unable to read image /data/movies/Audrey Rose (1977)/backdrop1.jpg
   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat outputFormat)
   at Jellyfin.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
[2024-05-13 19:25:29.565 -07:00] [ERR] [112] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/d0eb187ae298fd4c7e5be7099c3c8c58/Images/Backdrop/0".
System.UnauthorizedAccessException: Access to the path '/data/movies/Audrey Rose (1977)/backdrop1.jpg' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-05-13 19:25:29.573 -07:00] [ERR] [112] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN3JHJV1QEP4"", Request id ""0HN3JHJV1QEP4:00000009"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (25 of 0).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

This does not occur with other movies in the library, _however_ it does give me an endless spinning wheel if I try to change the order of the backdrop images on any film.

**Comment by brandoningli** [comment]
Still seeing this.

**Comment by sotornien** [comment]
I do also face this Problem but only with Backdrops. Banner and Covers can be uploaded, changed and deleted. It only affects Backdrops.

After Uploading a picture as Backdrop, the WebUI receives a 404 for this Image

![image](https://github.com/user-attachments/assets/1b9e7d85-a7dd-462a-8e36-2ecf24c56419)

**Comment by leso-kn** [comment]
Just discovered this issue on my instance as well. Running inside docker on Ubuntu 22.04 LTS 64-bit, Jellyfin v10.9.11.

Just as described by the previous comment this only affects backdrops and only folders (e.g. music albums), all other images work. Accessing the uploaded file results in a 404, more precisely the message "`<album name>` does not have an image of type Backdrop".

FYI, a workaround to delete all backgrounds on an element is to "Update metadata" > "Replace all metadata" and check "Replace existing images".

**Comment by sotornien** [comment]
There must be something messed up in the Database, because even autodetecting Images from the Libraries Folder ends in the same situation. What I mean:

- I Updated the Metadata with replacing all existing Images. Result: Images are gone
- Uploading cover.jpg and backdrop.jpg to the Library via FTP (I did not use the Upload function on the WebUI)
- Rescanning Metadata. Result: The cover was found and is shown as usual. The Backdrop was also detected, but the Image is not shown (still the 404).

So Jellyfin detects the default files in the Music Library (cover.jpg and backdrop.jpg), but still only is able to show the cover. Renaming  the backdrop.jpg to background.jpg did not help.

**Comment by sotornien** [comment]
Ok I figured it out on which Albums it happens. There was a common and (in my case) its the folder Structure. If you put your Album into Subfolders on your server, than the Issue hits. Stil seems to be a bug as Folder Covers are always working.

**Comment by leso-kn** [comment]
This issue is still present @jellyfin-bot

**Comment by theguymadmax** [comment]
This is a duplicate of #13119. If PR #13119 is merged, it will resolve the issue.
