### ISSUE TITLE
[Issue]: Cannot delete media files

### ISSUE THREAD

**Issue by PaulDotSH** [jellyfin/jellyfin#10713]
### Please describe your bug

After changing the permissions of the library folders and files to a variety of modes, jellyfin keeps throwing a "System.UnauthorizedAccessException".
I am using ubuntu server and used the installer, I start jellyfin with systemctl, my home folder contains my media.

ls -hl output
```
jellyfinn@jellyfinn:~$ ls -hl
total 36K
drwxrwxrwx   7 jellyfinn jellyfinn 4.0K Dec 12 11:26 anime
drwxrwxrwx   5 jellyfinn jellyfinn 4.0K Dec 12 09:58 movies
drwxrwxrwx 215 jellyfinn jellyfinn  16K Dec 11 22:55 Music
drwxrwxrwx   2 jellyfinn jellyfinn 4.0K Dec  9 22:04 photos
drwxrwxrwx   3 jellyfinn jellyfinn 4.0K Dec 11 23:53 shows
drwxrwxrwx   3 jellyfinn jellyfinn 4.0K Dec  9 22:12 Sync
```
jellyfinn is the user on the virtual server

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu server 22.04
- Linux Kernel: 5.15
- Virtualization: kvm
- Clients: Browser, Android, Linux
- Browser: Chrome 120
- FFmpeg Version: bundle with jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: None
- GPU Model: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2023-12-12 11:20:58.221 +00:00] [ERR] Error processing request. URL "DELETE" "/Items/9d86a87a2e41af9b671eddde4e950416".
System.UnauthorizedAccessException: Access to the path '/home/jellyfinn/anime/sample/test.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, BaseItem parent, Boolean notifyParentItem)
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, Boolean notifyParentItem)
   at Jellyfin.Api.Controllers.LibraryController.DeleteItem(Guid itemId)
   at lambda_method1032(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soundsbyjs** [comment]
I had to run chmod a+rx on my media folders. Jellyfin also needs read and write access in the directories up the tree, so if you're putting them in your ~/, it won't work. I had to make a media folder on /

**Comment by felix920506** [comment]
Hi, this is a permissions issue and not a Jellyfin issue.
Please head to our chatrooms or forum for support.
https://jellyfin.org/contact

**Comment by felix920506** [comment]
Closing as a non issue.
