### ISSUE TITLE
[Issue]: Deleting playlist throws System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist'

### ISSUE THREAD

**Issue by yagarea** [jellyfin/jellyfin#10717]
### Please describe your bug

When I try to delete empty music playlist I get this error loged in logs:

```
System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist' (e532cecc1f125932b13c1d8ff4a5bb9e) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2023-12-12 19:46:06.921 +00:00] [INF] Removing item, Type: "Playlist", Name: "00 - Guns N' Roses - Appetite For Destruction", Path: "/userdata/groups/ggu-media/Music/Guns N' Roses/1987 - Appetite For Destruction (1997 MFSL Gold UltraDisc)/00 - Guns N' Roses - Appetite For Destruction.m3u8", Id: 96ca220d-ba2c-b532-7e33-b32d5a75d17e
[2023-12-12 19:46:06.921 +00:00] [INF] Deleting item path, Type: "Playlist", Name: "00 - Guns N' Roses - Appetite For Destruction", Path: "/userdata/groups/ggu-media/Music/Guns N' Roses/1987 - Appetite For Destruction (1997 MFSL Gold UltraDisc)/00 - Guns N' Roses - Appetite For Destruction.m3u8", Id: 96ca220d-ba2c-b532-7e33-b32d5a75d17e
[2023-12-12 19:46:06.927 +00:00] [ERR] Error processing request: "Could not find a part of the path '/userdata/groups/ggu-media/Music/Guns N' Roses/1987 - Appetite For Destruction (1997 MFSL Gold UltraDisc)/00 - Guns N' Roses - Appetite For Destruction.m3u8'". URL "DELETE" "/Items/96ca220dba2cb5327e33b32d5a75d17e".
[2023-12-12 19:46:11.197 +00:00] [ERR] Error refreshing item
System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist' (2d361024563771422622fbdbebf5a558) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2023-12-12 19:46:11.276 +00:00] [ERR] Error refreshing item
System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist' (b549980972e23d513164e3d73789db12) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass67_0.<<RefreshAllMetadataForContainer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

and jellyfin displays this:
![image](https://github.com/jellyfin/jellyfin/assets/14349169/41e8d09f-f5ff-43ea-bbad-f0a1e105284b)

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Debian linux
- Virtualization: lxd
- Clients: web
- Browser: firefox
- Networking: local
- Storage: HDD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
does this issue have any symptoms other than lines in a log file?

**Comment by yagarea** [comment]
> does this issue have any symptoms other than lines in a log file?

No, everything works normal except the playlist stays unremoved.

**Comment by yagarea** [comment]
If you need any more information or log I can provide it.

**Comment by yagarea** [comment]
Yes, issue still remains. There where no updates since this issue was made.

![image](https://github.com/jellyfin/jellyfin/assets/14349169/73468612-c538-4524-bb4c-9db8a6492905)

**Comment by Shadowghost** [comment]
Can you please check on unstable, there have been a ton of changes on playlists.

**Comment by crobibero** [comment]
> > Can you please check on unstable, there have been a ton of changes on playlists.
> 
> Are unstable versions packaged or do I need to compile it myself ?

https://jellyfin.org/posts/testing-10.9.0

**Comment by yagarea** [comment]
This issue seems completely fixed in jellyfin 10.9.1.

I think this issue can be closed. Thank you for your great work.
