### ISSUE TITLE
[Issue]: Delete a user with API Error

### ISSUE THREAD

**Issue by BroserBros** [jellyfin/jellyfin#10722]
### Please describe your bug

According to the API files and my research, user deletion should be simple. All I need is ID and then sending DELETE request.

Now I wrote the following python code below. The request is sent successfully, but Jellyfin reacts strangely. I did not include authentication methods to avoid confusion.

```shell
def deleteUser(userid):
    url = '/Users/' + str(userid)
    res = requests.delete('{}{}?api_key={}'.format(JELLYFIN_URL, url, JELLYFIN_API_KEY))
    print(res.content)
    return res

def run():
    msg = deleteUser(userid)
    print(msg)
```

The ERROR added in log 

### Jellyfin Version

Other

### if other:

10.8.11

### Environment

```markdown
- OS: Windows
- Linux Kernel:
- Virtualization:
- Clients: Python
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-12-13 21:10:51.225 +03:00] [ERR] [227] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "DELETE" "/Users/65833499c7944becabe746c763c98377".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Api.Controllers.UserController.DeleteUser(Guid userId)
   at lambda_method1863(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please test if this happens on Master.
Do keep in mind that the upgrade to Master is currently irreversible so please keep a backup of Jellyfin files if you chose to upgrade your existing instance.

**Comment by BroserBros** [comment]
@terrelsa13 now im checking your error but first please delete URL and api keys on your logs because it is dangerous

**Comment by BroserBros** [comment]
@terrelsa13 I think problem is your code. In Python try the use 

> requests

Actually instead of using this main your code just use my codes. I rearranged the codes for you. Don't forget to customize lines 9-13 and write the username of the user who needs to be deleted in the **which_user_deleted** variable in line 53. I will be waiting for the result.

```shell
#!/usr/bin/env python3
import os
import requests
import socket
import json


##  SERVER  ##
VERBOSE = False
JELLYFIN_URL = '_________'
JELLYFIN_API_KEY = '_________'
JELLYFIN_ADMIN_USERNAME = '_________'
JELLYFIN_ADMIN_PASSWORD = '_________'


# Jellyfin API #

token_header = None


def load_token_header(file):
    global token_header
    if os.path.exists(file):
        with open(file, 'r') as f:
            token_header = {'X-Emby-Token': '{}'.format(f.readline())}
        return True
    return False


def save_token(file, token):
    with open(file, 'w+') as f:
        f.write(str(token))


def postWithToken(hdr, method, data=None):
    hdr = {'accept': 'application/json', 'Content-Type': 'application/json', **hdr}
    res = requests.post('{}{}'.format(JELLYFIN_URL, method), headers=hdr, data=json.dumps(data))
    print(res.text)
    if VERBOSE:
        print(res.content)
    return res


def deleteUser(userid): 
    url = '/Users/' + str(userid)
    res = requests.delete('{}{}?api_key={}'.format(JELLYFIN_URL, url, JELLYFIN_API_KEY))
    print(res.content)
    print(JELLYFIN_URL + url + "?api_key=" + JELLYFIN_API_KEY)
    return res


def getuserid():
    which_user_deleted = "test"
    url = '/Users'
    res = requests.get('{}{}?api_key={}'.format(JELLYFIN_URL, url, JELLYFIN_API_KEY))
    res_return = res.json()
    size = len(res_return)
    print(size)
    whiled=0
    while True:
        whiled+=1
        if whiled >= size:
            break
        record = res_return[whiled]
        username = record["Name"]
        userid = record["Id"]
        print(str(whiled) + " | UserID: " + str(userid) + " - Username: " + username)
        
        if which_user_deleted in username:
            deleteUser(userid)

    
        
def authenticate():
    global token_header
    if not load_token_header('.jf_token'):
        xEmbyAuth = {
            'X-Emby-Authorization': 'Emby UserId="{UserId}", Client="{Client}", Device="{Device}", DeviceId="{'
                                    'DeviceId}", Version="{Version}", Token="""'.format(
                UserId="",  # not required, if it was we would have to first request the UserId from the username
                Client='account-automation',
                Device=socket.gethostname(),
                DeviceId=hash(socket.gethostname()),
                Version=1,
                Token=""  # not required
            )}
        data = {'Username': JELLYFIN_ADMIN_USERNAME, 'Password': JELLYFIN_ADMIN_PASSWORD,
                'Pw': JELLYFIN_ADMIN_PASSWORD}
        try:
            res = postWithToken(hdr=xEmbyAuth, method='/Users/AuthenticateByName', data=data).json()
            token_header = {'X-Emby-Token': '{}'.format(res['AccessToken'])}
            save_token('.jf_token', res['AccessToken'])
        except Exception as e:
            print('Could not log into Jellyfin.\n{}'.format(e))


# Helper functions #

def status(response):
    if VERBOSE:
        print(response.status_code)
    if response:
        return True
    return False


def checkVars():
    return all([JELLYFIN_URL, JELLYFIN_ADMIN_USERNAME, JELLYFIN_API_KEY, JELLYFIN_ADMIN_PASSWORD])

def run():
    getuserid()



msg = run()
print(msg)
```

**Comment by terrelsa13** [comment]
@BroserBros Thank you for the suggestion. The urllib.request module I am using works for several other API calls, deletes media from emby, and was deleting media on jellyfin until recently. Something jellyfin API related has changed, but I cannot find in any of the jellyfin API tools what is now different.

**Comment by nielsvanvelzen** [comment]
Please do not use the deprecated authorization headers, it will break the script in a future Jellyfin release. See https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f for more details.

**Comment by terrelsa13** [comment]
I was testing on my "other" server and spoke too soon. Looks like I am still having the same issue with Jellyfin. ```System.NullReferenceException: Object reference not set to an instance of an object.``` I have verified the itemId is correct and have tried the itemId with and without dashes.

**itemId:** ```c0ccd812-4cf7-5279-fb26-ddc5801c0982```
**itemId:** ```c0ccd8124cf75279fb26ddc5801c0982```

Worth mentioning, I can ```'DELETE'``` API keys and successfully send all of my other other ```'GET'``` and ```'POST'``` requests without issue.

Is there an alternate ```itemId``` I should be using to delete media?

```
HTTPError: Unable to get information from server during processing of: delete_media_item_request_for_c0ccd8124cf75279fb26ddc5801c0982
  Object: <bound method Request.header_items of <urllib.request.Request object at 0x7f459cbfe8c0>>
     URL: http://172.31.14.151:8096/Items/c0ccd8124cf75279fb26ddc5801c0982
  Method: DELETE
  Header: {'Authorization': 'MediaBrowser Client="mumc.py", Device="Multi-User Media Cleaner", DeviceId="MUMC", Version="5.3.21-beta", Token="445c9efe8faf4513a0eeb20521c5db81"', 'Content-type': 'application/json'}
    Data: None

HTTPError: 500 - Internal Server Error
```

```c#
[2024-01-09 20:35:22.953 -05:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-01-09 20:35:22.956 -05:00] [ERR] Error processing request. URL "DELETE" "/Items/c0ccd812-4cf7-5279-fb26-ddc5801c0982".
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Controller.Entities.BaseItem.IsAuthorizedToDelete(User user, List`1 allCollectionFolders)
   at Jellyfin.Api.Controllers.LibraryController.DeleteItem(Guid itemId)
   at lambda_method1376(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-01-09 20:35:23.445 -05:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
```

What am I doing incorrectly?

**Comment by terrelsa13** [comment]
Same exact error using ```requests``` and a different media item.

```python
import requests

res = requests.delete('{}?ApiKey={}'.format('http://172.31.14.151:8096/Items/c0ccd8124cf75279fb26ddc5801c0982', '445c9efe8faf4513a0eeb20521c5db81'))
```

**Comment by nielsvanvelzen** [comment]
In 10.8 you can only use the DeleteItem operation with user access tokens. Not API keys, that is why the error happens. This will change with 10.9 though.

**Comment by terrelsa13** [comment]
Yep. That's what my issue was. Once I grabbed a key using authenticateByUserName I was able to delete media items. Also good to know we will soon be able to delete using API keys generated in the GUI
