### ISSUE TITLE
[Issue]: Deleting a video damaged the associated files of other videos

### ISSUE THREAD

**Issue by tanmoumou252** [jellyfin/jellyfin#10755]
### Deleting a video damaged the associated files of other videos

Deleting a video damaged the associated files of other videos, and the id of the video associated files was reused. 
When deleting a TV show video named SxxE1 on the web playback page, related extra files such as `SxxE1-thumb.jpg`, `SxxE1.nfo`, `SxxE1.forced.eng.srt`, etc. will also be deleted.  
However, in this jellyfin version, deleting SxxE1 will also delete the extra files for SxxE10 to SxxE19, but the video files for SxxE10 to SxxE19 will remain unchanged. 
 In summary, attempting to delete SxxE1 and its associated files will inadvertently delete the associated files for SxxE10 to SxxE19 as well.  
The log shows that it reported an error after deleting itself, and the error message was approximately: cannot find corresponding extra file. 
It seems that these associated files from SxxE10 to SxxE19 shared the id of SxxE1, but I am not sure how this happened and if it is related to the 10.8.13 version of Jellyfin. After re-downloading the images from TMDb using tinyMediaManager, it seems that the id is no longer shared and the deletion issue should not occur again. 
Translated from Chinese, assisted by ChatGPT.If there are any issues with the description, I hope you don't mind. 

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS:Windows 11 22631.2861
- Linux Kernel:
- Virtualization:
- Clients:Browser
- Browser:Firefox 121, Chrome 120
- FFmpeg Version: 5.1.4-Jellyfin
- Playback Method:direct play
- Hardware Acceleration:AMD amf
- GPU Model:RX6600
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: local hard disk
```

### Jellyfin logs

```shell
[2023-12-21 09:21:45.766 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E1.mp4", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.768 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E1.mp4", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.781 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E1-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.783 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E1.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.784 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E10-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.785 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E10.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.786 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E11-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.789 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E11.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.790 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E12-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.791 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E12.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.793 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E13-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.794 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E13.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.795 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E14-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.796 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E14.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.798 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E15-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.799 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E15.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.800 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E16-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.801 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E16.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.802 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E17-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.803 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E17.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.804 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E18-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.805 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E18.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.806 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E19-thumb.jpg", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:45.808 +08:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Episode", Name: "我是社长也是假面骑士", Path: "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E19.nfo", Id: 148c52f5-359a-f61e-f076-dedafb41d3a1
[2023-12-21 09:21:47.769 +08:00] [INF] [64] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "*:10e6:9691:ac0b:6c6e" closed
[2023-12-21 09:21:48.207 +08:00] [INF] [92] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "*:10e6:9691:ac0b:6c6e" request
[2023-12-21 09:22:45.828 +08:00] [INF] [78] Emby.Server.Implementations.IO.LibraryMonitor: "第 30 季 零一" ("D:\番剧\单季番剧\假面骑士 (1971)\S30") will be refreshed.
[2023-12-21 09:22:45.860 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E10-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.884 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E11-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.903 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E12-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.922 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E13-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.940 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E14-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.959 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E15-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.977 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E16-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:45.996 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E17-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:46.015 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E18-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:46.034 +08:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\番剧\单季番剧\假面骑士 (1971)\S30\S30E19-thumb.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-12-21 09:22:49.255 +08:00] [INF] [10] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2023-12-21 09:22:49.294 +08:00] [INF] [10] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "1". EnableAudioPlaybackTranscoding: True
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Hey,

I assume this is caused by your use of an unsupported naming scheme.
Please format your media according to your docs: https://jellyfin.org/docs/general/server/media/shows/


Especially using full 2 or 3 digit numbers when specifying your episode, so a fully compliant path would be:
`D:\番剧\单季番剧\假面骑士 (1971)\Season 01\假面骑士 S01E01.mkv.`
Please notice that the name of the series is part of the episode, the `Season` folder name is fully written out and the season and episode numbers are also written with leading zeros.

I assume this will fully fix your issues, if the issue still arises if you changed that please feel free to comment or reopen this bug.

**Comment by oddstr13** [comment]
Sounds like it deleted all files starting with the episode file name, but knowing not to touch video files

**Comment by tanmoumou252** [comment]
Okay, thank you for your response. I will organize the files again and hopefully everything goes smoothly.  
![屏幕截图 2023-12-23 084331](https://github.com/jellyfin/jellyfin/assets/118299342/b78b9c80-2a5a-4f6b-afad-fec9decb5d7d)

However, I still have to say something that you may have already heard: 
when the nfo files are intact and the nfo specifies the specific episodes, it seems unnecessary to consider sorting the file names according to the leading zero format, as this would make the strings in the nfo file meaningless.
