### ISSUE TITLE
Reset password feature broken and unable to unlock admin user

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#1076]
I tried to login on a new PC, but forgot my password, tried 5 different passwords, none of them worked, checked my mobile and was logged out on android (the beta app). I tried to login on mobile, it failed.

I went to a PC where my password is saved and it Jellyfin was used 20minutes before, but as I clicked on category, I was logged out. I tried to reset password, but it says:

![screenshot_20190308_151829](https://user-images.githubusercontent.com/2544251/54037199-789dbc00-41b5-11e9-9a4e-34ff558089c5.png)

I don't know what I'm supposed to do with this information and missing translations labels... but ok. I ssh to my server, cd to jellyfin config dir and the file is a follows:

```
Use your web browser to visit:

http://192.168.1.100:8096/web/index.html#!/forgotpasswordpin.html

Enter the following pin code:

2787

The pin code will expire at 21
```

![screenshot_20190308_152112](https://user-images.githubusercontent.com/2544251/54037478-2c9f4700-41b6-11e9-876b-6a7dd31bc503.png)

1. It shows link to LAN IP, I can't access it from where I am.
2. When I visit correct URL I'm presented with list of users I have on my system, even all of them are marked as hidden from dashboard - which looks like information leak, these username are not public for a very good reason.
3. I still don't know what I am supposed to do with this PIN and how to reset password of my users who is also an admin

I'm redirected to **HeaderPleaseSignIn**, trying to login with my saved username + password, but it doesn't work. I check logs, my user is still disabled. I try to check another non-admin user... it also doesn't work. I check logs, another user disabled:

```
[2019-03-08 15:11:28.816 +00:00] [ERR] The XXXX account is currently disabled. Please consult with your administrator.
```

I am system administrator, my account is locked, I can't reset password, my account has been locked by attempts to login.

Ergo, your can be trapped away from your server by anyone who knows your username on jellyfin.

Please advise how I can unlock my account.

**Comment by anthonylavado** [comment]
Regarding 2, #1057 is filed for it.

**Comment by taking** [comment]
+1
I have the same problem.

**Comment by JustAMan** [comment]
We also need a separate issue for users' names leak. @agilob can you submit one?

**Comment by agilob** [comment]
https://github.com/jellyfin/jellyfin/issues/1086

**Comment by anthonylavado** [comment]
>https://github.com/jellyfin/jellyfin/issues/1086 ...

@agilob we agree, that’s why we’re fixing things as we get them :-)

**Comment by grafixeyehero** [comment]
this is happening again 
![50923435-041cfa00-145e-11e9-92b8-0a752fc72225](https://user-images.githubusercontent.com/32230989/55579037-05d62100-5720-11e9-8af0-4c4dd0964672.jpg)

System (please complete the following information):

    OS: Windows
    Jellyfin Version: 10.3.0-rc1

**Comment by anthonylavado** [comment]
>this is happening again  ...

@grafixeyehero did you build it, or download a binary?

**Comment by grafixeyehero** [comment]
i build it

**Comment by grafixeyehero** [comment]
https://github.com/jellyfin/jellyfin-web/pull/229 Fix "Password Reset by PIN" page #229

**Comment by grafixeyehero** [comment]
and another thing when entering the pin code dosent seem to rest the password

here is the log

`[02:32:50] [ERR] Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: No Users found with a password reset request matching pin E4-9B-D0-33
   at Emby.Server.Implementations.Library.DefaultPasswordResetProvider.RedeemPasswordResetPin(String pin) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Library\DefaultPasswordResetProvider.cs:line 75
   at Emby.Server.Implementations.Library.UserManager.RedeemPasswordResetPin(String pin) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Library\UserManager.cs:line 926
   at MediaBrowser.Api.UserService.Post(ForgotPasswordPin request) in C:\Users\admin\Documents\GitHub\Jellyfin\MediaBrowser.Api\UserService.cs:line 531
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 575
`

**Comment by vicovaro** [comment]
> +1
> I have the same problem.
> 
> I found a temporary solution.
> /etc/jellyfin/users/[Administrator UserID]/policy.xml
> IsDisabled: true -> false
> InvalidLoginAttemptCount: 5 -> 0
> 
> service jellyfin restart

You are the solution sir!

**Comment by tuhinadri** [comment]
I'm currently not on my home network! I want to change my password! I fully setup jfa-go! this is sending me emails for welcome email as SMTP! but why it's not working remotely for the password!
![image](https://user-images.githubusercontent.com/57254086/110887740-d1f2d580-8310-11eb-861a-2cddf8484d62.png)

**Comment by liquidmind313** [comment]
where can i find this files on MacOS?
