### ISSUE TITLE
[Issue]: Can't edit seasons metadata

### ISSUE THREAD

**Issue by pisekpiskovec** [jellyfin/jellyfin#10783]
### Please describe your bug

Suddenly I can't change the season metadata. The last time this was working was 24.12.23 cause I was adding and editing Baked Snowman (Pečený Sněhulák). On 25.12. I wasn't doing anything with jf, on 26.12. I added some more series and finally on 27.12. I wanted to edit them. After editing series data I wanted to edit the seasons, however I couldn't do it as it was still spinning. Editing episodes is working as well.

What I found out is that I can edit season data as long as the season has its own folder.
This is the file structure I've been using so far *(not working anymore)*
```
serie/
   - /01x01.mp4
   - /01x02.mp4
   - /02x00.mp4
```
and this is what I found out is working
```
serie/
   - /season 1/
            - /01x01.mp4
            - /01x02.mp4
   - /season 2/
            - /02x00.mp4
```

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 6.1.44-v8+
- Virtualization: none, running as apt package
- FFmpeg Version: 4.4.1-4-bullseye, 5.1.4-2-bullseye
- Hardware Acceleration: V4L2
- Plugins: AniDB, AniList, Anime, AudioDB, MusicBrainz, OMDb, Open Subtitles, SkinManager, Studio Images, TMDb, YoutubeMetadata
- Reverse Proxy: none
- Base URL: none
- Storage: local
```

### Jellyfin logs

```shell
[2023-12-29 20:22:02.071 +01:00] [ERR] Error processing request. URL "GET" "/Items/4a484a0798adbe0ea518c51386352f1b/MetadataEditor".
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at Emby.Server.Implementations.IO.ManagedFileSystem.NormalizePath(String path)
   at Emby.Server.Implementations.IO.ManagedFileSystem.AreEqual(String path1, String path2)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass156_0.<GetContentTypeOverride>b__0(NameValuePair i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Emby.Server.Implementations.Library.LibraryManager.GetContentTypeOverride(String path, Boolean inherit)
   at Emby.Server.Implementations.Library.LibraryManager.GetConfiguredContentType(BaseItem item)
   at Jellyfin.Api.Controllers.ItemUpdateController.GetMetadataEditorInfo(Guid itemId)
   at lambda_method1181(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any browser or client logs here

![Screenshot_20231229_220127](https://github.com/jellyfin/jellyfin/assets/77384152/edc686a8-f8b8-4ec9-82e3-e9c4a320c271)

### Please attach any screenshots here

![Screenshot_20231229_222827](https://github.com/jellyfin/jellyfin/assets/77384152/094f6f17-f270-40f4-8506-22e95d0f35fc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Are you saving the metadata alongside the media files?

**Comment by pisekpiskovec** [comment]
No, I do not. They should be stored elsewhere.

**Comment by pisekpiskovec** [comment]
Somehow, it's fixed. This is why I love Linux and open-source stuff. It's not working? Give it some time and it'll fix itself.
![](https://github.com/jellyfin/jellyfin/assets/77384152/f4267098-ae31-4821-842e-86259a11d4e0)
