### ISSUE TITLE
[Issue]: Localhost does not load on macOS

### ISSUE THREAD

**Issue by maschulloo** [jellyfin/jellyfin#10786]
### Please describe your bug

I can no longer access localhost on my MacBook. It does not load. 
Apparently because SQL Database is locked, but I don't know how to fix it.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: macOS 14.2
- Browser: Safari 17.2
```

### Jellyfin logs

```shell
[2023-12-30 17:42:21.906 +01:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2023-12-30 17:42:21.991 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /Users/maximilianschultz/.local/share/jellyfin/log]"]
[2023-12-30 17:42:21.998 +01:00] [INF] [1] Main: Arguments: ["/Applications/Jellyfin.app/Contents/MacOS/jellyfin.dll", "--webdir", "/Applications/Jellyfin.app/Contents/Resources/jellyfin-web"]
[2023-12-30 17:42:22.012 +01:00] [INF] [1] Main: Operating system: "macOS"
[2023-12-30 17:42:22.013 +01:00] [INF] [1] Main: Architecture: X64
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: 64-Bit Process: True
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: User Interactive: True
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: Processor count: 8
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: Program data path: "/Users/maximilianschultz/.local/share/jellyfin"
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: Web resources path: "/Applications/Jellyfin.app/Contents/Resources/jellyfin-web"
[2023-12-30 17:42:22.014 +01:00] [INF] [1] Main: Application directory: "/Applications/Jellyfin.app/Contents/MacOS/"
[2023-12-30 17:42:22.361 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/Users/maximilianschultz/.cache/jellyfin"
[2023-12-30 17:42:22.398 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-12-30 17:42:22.543 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-12-30 17:42:22.543 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-12-30 17:42:22.544 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-12-30 17:42:22.563 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-12-30 17:42:22.563 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-12-30 17:42:25.296 +01:00] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean readOnly)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2023-12-30 17:42:25.310 +01:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2023-12-30 17:42:25.360 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-12-30 17:42:25.365 +01:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please head to our chat rooms or forum for support. https://jellyfin.org/contact
