### ISSUE TITLE
[Issue]: Jellyfin docker crashes when multiple errors occure

### ISSUE THREAD

**Issue by UniverseDevel** [jellyfin/jellyfin#10802]
### Please describe your bug

When I scan library with home videos of my daghter, Jellyfin docker crashes and due to restart policy boots right back up. I see no ffmpech logs or any error from ffmpeg that would tell me what the issue might be. Also I am not sure what ffmpeg command is being triggered so cannot test it myself to see the error.
EDIT: It crashed on me recently again and it seems that it is doing this when there are multiple errors in a row. More logs added. This time I was just browsing after watching some videos. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Raspbian GNU/Linux 11 (bullseye)
- Linux Kernel: 6.1.21-v8+
- Virtualization: 24.0.7, build afdd53b
- Clients: Browser
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- FFmpeg Version: 4.3.6-0+deb11u1+rpt5
- Playback Method: mostly direct
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: localy mounted NFS (NAS)
```

### Jellyfin logs

```shell
[17:41:09] [ERR] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for file:"/path/to/file/video.mp4"
[17:41:09] [ERR] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: I-frame image extraction failed, will attempt standard way. Input: file:"/path/to/file/video.mp4"
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/path/to/file/video.mp4"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
[17:41:51] [INF] [63] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 2 inactive WebSockets.
[17:42:51] [INF] [66] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 2 inactive WebSockets.
[17:43:32] [INF] [25] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Killing ffmpeg process
[17:43:56] [INF] [1] Main: Jellyfin version: 10.8.13
[17:43:57] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_PublishedServerUrl, 10.0.0.10]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]"]
[17:43:57] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[17:43:57] [INF] [1] Main: Operating system: Linux
[17:43:57] [INF] [1] Main: Architecture: Arm
[17:43:57] [INF] [1] Main: 64-Bit Process: False
[17:43:57] [INF] [1] Main: User Interactive: True
[17:43:57] [INF] [1] Main: Processor count: 4

EDIT:
[19:56:34] [ERR] [125] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session e1be776cba9823ea1aa8be775189772c not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[19:56:35] [ERR] [125] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session e1be776cba9823ea1aa8be775189772c not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[19:56:35] [INF] [104] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 10.0.1.2 request
[19:56:36] [ERR] [99] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session e1be776cba9823ea1aa8be775189772c not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[19:56:37] [ERR] [112] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session e1be776cba9823ea1aa8be775189772c not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[19:56:37] [WRN] [81] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://10.0.0.10:8096/Users/ead1653f2d3049fdab796edb7853d631/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 to 10.0.1.2 in 0:00:01.9452855 with Status Code 200
[19:56:38] [WRN] [127] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://10.0.0.10:8096/Users/ead1653f2d3049fdab796edb7853d631/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book to 10.0.1.2 in 0:00:02.4664574 with Status Code 200
[19:56:46] [INF] [1] Main: Jellyfin version: 10.8.13
[19:56:46] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_PublishedServerUrl, 10.0.0.10]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]"]
[19:56:47] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[19:56:47] [INF] [1] Main: Operating system: Linux
[19:56:47] [INF] [1] Main: Architecture: Arm
[19:56:47] [INF] [1] Main: 64-Bit Process: False
[19:56:47] [INF] [1] Main: User Interactive: True
[19:56:47] [INF] [1] Main: Processor count: 4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
What "restart policy" is triggering the restart? out of memory? too high CPU? or what else?

**Comment by UniverseDevel** [comment]
Restart policy in docker starts it up automatically after crash, as it is set to "unless stopped". That means container crashes and docker starts it again as it was not manually stopped. I have no idea what is causing the crash, the logs seem to not contain such information as you can see them attached yourself. There are couple of errors and then container starts booting from scratch because it crashed. Zabbix monitoring sometimes catches that container exited with non-zero exit code.

**Comment by felix920506** [comment]
You should be able to grab the log files from the file system if you mounted in the relevant paths.
