### ISSUE TITLE
[Issue]: Unhandled exception after upgrading from stable (010.8.13-1) to unstable (20231115.15) on nated env

### ISSUE THREAD

**Issue by zeus86** [jellyfin/jellyfin#10875]
### Please describe your bug

I am currently on 10.8.13 on ubuntu (lxc) and wanted to try out the new downmixing options introduced as a result of #1986 . I use a reverse-proxy (haproxy on pfsense) to enable access from the internet and for https-offloading, and locally I use the same hostname to access the jellyfin instance (so technically speaking this is nat-reflection).

after upgrading to the packages from `deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal unstable` (instead of `main`) jellyfin was no longer reachable via the https-webinterface throwing the following exception once per second as soon the first attempt to access the webui is made: 

```
Jan 16 14:57:40 jellyfin jellyfin[676117]: [14:57:40] [ERR] Connection id "0HN0MJC0DB2LT", Request id "0HN0MJC0DB2LT:00000001": An unhandled exception was thrown by the application.
Jan 16 14:57:40 jellyfin jellyfin[676117]: System.UriFormatException: Invalid URI: The hostname could not be parsed.
Jan 16 14:57:40 jellyfin jellyfin[676117]:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
Jan 16 14:57:40 jellyfin jellyfin[676117]:    at System.Uri..ctor(String uriString)
Jan 16 14:57:40 jellyfin jellyfin[676117]:    at System.UriBuilder.get_Uri()
Jan 16 14:57:40 jellyfin jellyfin[676117]:    at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
Jan 16 14:57:40 jellyfin jellyfin[676117]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

via the container's local ip+port 8096 jellyfin was reachable normally. 

i use the following in the relevant configs:
```
general->settings->server name: FQDN-hostname (not the hostname of the lxc container)
advanced->networking
   -> base url: blank
   -> lan networks: 10.10.0.0/16 (all my local networks are within this range)
   -> known proxies: comma-separated list of all insterfaces as well as private and public IPs of my router (which does the nat and ssl stuff)
   -> published server URIs: address os the webinterface as you would type it into your browser (https://<FQDN>/)
```

for now i reverted back to stable, but some help what I might have missed here would be very appreciated. 

PS.: please make the mentioned downmixing-feature available in stable. following the PR belonging to that, it is very unlikely to break something!

### Jellyfin Version

10.8.13-1

### Environment

```markdown
- OS: Ubuntu 20.04 focal x64_64
- Linux Kernel: 5.15.126-1-pve
- Virtualization: LXC
- Clients: web
- Browser: ff
- FFmpeg Version: 5.1.4-2-focal
- Hardware Acceleration: none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zeus86** [comment]
it may be, that this is loosely related to #9781
