### ISSUE TITLE
[Issue]: Slow HTTP Response causing crashed since updating version

### ISSUE THREAD

**Issue by Tim-Roy** [jellyfin/jellyfin#10916]
### Please describe your bug

I updated from 10.8.13 from 10.8.11 today and began having issues with jellyfin freezing, requiring a manual restart. This occurs both when trying to watch through Roku and a browser.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Ubuntu Server 22.04
- Linux Kernel:5.15.0-92-generic
- Virtualization:Docker
- Clients:Roku,browser
- Browser:Firefox
- FFmpeg Version:4.4.2
- Playback Method:Direct Stream
- Hardware Acceleration:N/A
- GPU Model:N/A
- Plugins:N/A
- Reverse Proxy:none
- Base URL:yes
- Networking:bridge
- Storage:local
```

### Jellyfin logs

```shell
[19:40:35] [WRN] [42] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items?EnableTotalRecordCount=false&Filters=IsFavorite&Limit=20&recursive=true&sortby=random to <REDACTED> in 0:00:01.7413528 with Status Code 200
[19:40:35] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=6836c8442c6c264d7f20697b93713863 to <REDACTED> in 0:00:01.9697577 with Status Code 200
[19:40:35] [WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=4514ec850e5ad0c47b58444e17b6346c to <REDACTED> in 0:00:01.8884138 with Status Code 200
[19:40:35] [WRN] [45] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=27b4b3c186f4674def36324b841ccb18 to <REDACTED> in 0:00:01.9158118 with Status Code 200
[19:40:35] [WRN] [47] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 to <REDACTED> in 0:00:01.9893124 with Status Code 200
[19:40:35] [WRN] [46] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=126da52296a67ee818b9593a3c1afebc to <REDACTED> in 0:00:02.0043043 with Status Code 200
[19:40:36] [WRN] [24] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Shows/NextUp?DisableFirstEpisode=false&EnableRewatching=false&EnableTotalRecordCount=false&ImageTypeLimit=1&limit=24&NextUpDateCutoff=2023-01-27T03%3A40%3A32Z&recursive=true&SortBy=DatePlayed&SortOrder=Descending&UserId=1e8f1543d6ae4b8cb8a5b567a3d6671a to <REDACTED> in 0:00:03.80852 with Status Code 200
[19:40:36] [WRN] [36] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Resume?EnableTotalRecordCount=false&Filters=IsResumable&recursive=true&SortBy=DatePlayed&SortOrder=Descending to <REDACTED> in 0:00:03.4523467 with Status Code 200
[19:40:52] [ERR] [3] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/library/8e/8ea1294fb48fbc2cfef82de5fe83df14/logo.svg
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at SkiaSharp.Extended.Svg.ColorHelper.TryParse(String str, SKColor& color)
   at SkiaSharp.Extended.Svg.SKSvg.ReadPaints(Dictionary`2 style, SKPaint& strokePaint, SKPaint& fillPaint, Boolean isGroup)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.LoadElements(IEnumerable`1 elements, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.Load(XDocument xdoc)
   at SkiaSharp.Extended.Svg.SKSvg.Load(XmlReader reader)
   at SkiaSharp.Extended.Svg.SKSvg.Load(Stream stream)
   at SkiaSharp.Extended.Svg.SKSvg.Load(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[19:42:16] [WRN] [53] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/577687fdf03e8c522fc25199b36ae6ad?fields=Chapters to <REDACTED> in 0:00:42.0066256 with Status Code 200
[19:45:29] [WRN] [64] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Capabilities/Full to <REDACTED> in 0:00:00.9137032 with Status Code 204
[19:46:27] [WRN] [57] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Views/ to <REDACTED> in 0:01:00.0798507 with Status Code 200
[19:46:35] [WRN] [58] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/LiveTv/Programs/Recommended?enableImageTypes=Primary%2CThumb%2CBackdrop&enableTotalRecordCount=false&fields=ChannelInfo%2CPrimaryImageAspectRatio&imageTypeLimit=1&isAiring=true&limit=16&userId=1e8f1543d6ae4b8cb8a5b567a3d6671a to <REDACTED> in 0:00:04.8335566 with Status Code 200
[19:46:36] [WRN] [54] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 to <REDACTED> in 0:00:04.3094527 with Status Code 200
[19:46:47] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Resume?EnableTotalRecordCount=false&Filters=IsResumable&recursive=true&SortBy=DatePlayed&SortOrder=Descending to <REDACTED> in 0:00:19.0415664 with Status Code 200
[19:46:48] [WRN] [24] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items?EnableTotalRecordCount=false&Filters=IsFavorite&Limit=20&recursive=true&sortby=random to <REDACTED> in 0:00:13.7754931 with Status Code 200
[19:46:52] [WRN] [64] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=126da52296a67ee818b9593a3c1afebc to <REDACTED> in 0:00:24.8927979 with Status Code 200
[19:47:23] [WRN] [55] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=6836c8442c6c264d7f20697b93713863 to <REDACTED> in 0:00:51.7596573 with Status Code 200
[19:47:31] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/2e073a820efe12957a42d5e11a63bd44?fields=Chapters to <REDACTED> in 0:00:25.4889911 with Status Code 200
[19:47:32] [WRN] [57] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=4514ec850e5ad0c47b58444e17b6346c to <REDACTED> in 0:01:05.2834694 with Status Code 200
[19:47:57] [WRN] [51] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&ImageTypeLimit=1&Limit=16&ParentId=27b4b3c186f4674def36324b841ccb18 to <REDACTED> in 0:01:24.4365185 with Status Code 200
[19:47:57] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Shows/5228e29bb343270f7370f6842d805178/Episodes?Limit=50&StartItemId=2e073a820efe12957a42d5e11a63bd44&UserId=1e8f1543d6ae4b8cb8a5b567a3d6671a to <REDACTED> in 0:00:26.7518978 with Status Code 200
[19:48:03] [INF] [51] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for r. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[19:48:03] [INF] [51] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Official Roku Client, Path=<REDACTED>, AudioStreamIndex=1, SubtitleStreamIndex=-2 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/2e073a82-0efe-1295-7a42-d5e11a63bd44/stream.mov?MediaSourceId=2e073a820efe12957a42d5e11a63bd44&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&SubtitleStreamIndex=-2&api_key=<token>&SubtitleMethod=Encode&Tag=d0d54526a65a7659b41a472598824406
[19:48:03] [WRN] [51] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Items/2e073a820efe12957a42d5e11a63bd44/PlaybackInfo?audiostreamindex=1&AutoOpenLiveStream=true&IsPlayback=true&MaxStaticBitrate=140000000&MaxStreamingBitrate=140000000&mediasourceid=2e073a820efe12957a42d5e11a63bd44&StartTimeTicks=0&SubtitleStreamIndex=-2&UserId=1e8f1543d6ae4b8cb8a5b567a3d6671a to <REDACTED> in 0:00:05.2955417 with Status Code 200
[19:48:27] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Users/1e8f1543d6ae4b8cb8a5b567a3d6671a/Items/2e073a820efe12957a42d5e11a63bd44?fields=Chapters to <REDACTED> in 0:00:23.6301233 with Status Code 200
[19:48:34] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:07.0980967 with Status Code 200
[19:48:47] [WRN] [34] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:12.6301537 with Status Code 200
[19:48:55] [WRN] [43] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:06.1408684 with Status Code 206
[19:49:04] [WRN] [11] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:09.5253384 with Status Code 206
[19:49:14] [WRN] [71] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:05.2427868 with Status Code 206
[19:49:23] [WRN] [77] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Videos/2e073a820efe12957a42d5e11a63bd44/stream?AudioStreamIndex=1&Container=mp4&mediasourceid=2e073a820efe12957a42d5e11a63bd44&PlaySessionId=d905ff602db14680b74b70ae3580f596&Static=true to <REDACTED> in 0:00:04.9412307 with Status Code 206
[19:49:27] [WRN] [54] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing to <REDACTED> in 0:00:22.3618205 with Status Code 204
[19:49:41] [WRN] [74] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:06.7345553 with Status Code 204
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3fbd46b80] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3fbd46b80] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3fbd46b80] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3fbd46b80] error reading header
file:<REDACTED>: Invalid data found when processing input
[19:49:59] [ERR] [42] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in ffprobe
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[19:50:11] [WRN] [69] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:06.3605896 with Status Code 204
[19:50:39] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:03.9469096 with Status Code 204
[19:51:09] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:04.6691033 with Status Code 204
[19:51:47] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:12.6902372 with Status Code 204
[19:52:11] [WRN] [28] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:06.6836175 with Status Code 204
[19:52:43] [WRN] [3] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:08.071416 with Status Code 204
[19:53:20] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:14.8819036 with Status Code 204
[19:53:44] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:09.1795847 with Status Code 204
[19:54:22] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:16.989885 with Status Code 204
[19:54:42] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from <REDACTED>/Sessions/Playing/Progress to <REDACTED> in 0:00:07.5932192 with Status Code 204
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solidsnake1298** [comment]
What docker image are you using?

**Comment by Tim-Roy** [comment]
> What docker image are you using?

jellyfin/jellyfin:latest (10.8.13)

**Comment by vgambier** [comment]
Oh, I thought this was just me. The same happened to me, I updated to latest recently.

Sometimes files play just fine, but if "something" happens (seems random - once the whole thing came crashing down after I changed the subtitle track), I suddenly get a lot of "Slow HTTP Response" in the logs, and I'm eventually forced to restart to get it to a usable state again.

**Comment by felix920506** [comment]
@vgambier please provide a concrete and specific set of steps that will recreate the issue consistently, thanks.

**Comment by vgambier** [comment]
@felix920506 Fair enough. I will update with more information if I figure out any actionable steps. But as it stands I would probably rephrase my comment as "I've been having performance issues since I updated - the app is sometimes extremely slow, and when it is slow, it is prone to crashes. Rebooting the server usually helps with that". It could be due to something unrelated to the update, but I have not identified any external causes.

**Comment by felix920506** [comment]
@vgambier Please provide your setup and system specs if you are having performance issues.

**Comment by vgambier** [comment]
@felix920506 Jellyfin is running on a home server, in a docker container. Internet speed is not as high as I'd want, but I never figured out how to reliably test it from the actual server (if you have any recommendations, I'm all ears). It's advertised as 300 Mbit/s. Other servers running do not seem to be throttled to this extent. 

```
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Host: X9SCL/X9SCM 0123456789 
Kernel: 6.1.0-0.deb11.13-amd64 
CPU: Intel Xeon E31270 (8) @ 3.800GHz 
GPU: 04:03.0 Matrox Electronics Systems Ltd. MGA  
Memory: 15970MiB 
```

Hope this is useful. Thank you.

**Comment by felix920506** [comment]
@vgambier Thanks for confirming that you aren't running JF on a potato.

**Comment by vgambier** [comment]
@felix920506 I am not very knowledgeable about hardware. I genuinely have no idea how adequate or overkill my specs are for Jellyfin.

**Comment by solidsnake1298** [comment]
We just wanted to make sure you weren't running Jellyfin and 10 other services on a Raspberry Pi.

**Comment by vgambier** [comment]
I haven't had any issues in the last few days, so I think it was Internet issues unrelated to Jellyfin. The only things I can remember changing are ethernet cables and domain name / domain name registrar.

**Comment by JesseGuerrero** [comment]
I have this issue too

**Comment by bfourgeaud** [comment]
Same Problem here since update to 10.8.13 on freeBSD x64 !
Nothing has changed in the server config, just jellyfin update. And now every action seems slow and jellyfin keeps hours updating libraries, and it causes the streaming services to be unusable. I have to watch my films directly from the smb network share.

**Comment by Finallf** [comment]
Same Problem here since update to 10.8.13

**Comment by StefanLobbenmeier** [comment]
I think it would be nice to get some general information on how to go about debugging this. I have the same issue on my raspberry pi, can reproduce most easily by skipping around in the video a few times. Resolves itself after a jellyfin restart or waiting for a day (probably less, but definitely more than 10 minutes)

I also get messages about some requests taking more than 500ms, but nothing crazy, usually in the range of 0.5-1s. I am not sure if that middleware can reliably report requests that take forever though (I suspect it only prints a message when the request actually completes).

looking at htop everything looks fine though, I have 1GB of memory to spare and not using any CPU. I already moved media and configuration on an external HDD since the SD card can be slow, and I disabled swap, so there should be no need to load anything from disk anymore. Maybe there could be loading from SD card if the .net runtime loads classes from it, but I doubt that could freeze up everything

**Comment by StefanLobbenmeier** [comment]
I tried Plex on the same raspberry pi with the same library and the performance is much better. Not sure what jellyfin does different, but I imagine this means fixing this issue would improve the performance on any platform.

There are some ideas that maybe should be fixed on the client side (in my case SwiftFin, but I think most clients have similar issues):
- keeping the video bufferered before and after the playback cursor, so no request needs to be made when skipping around 
- Maybe having an offline version. The client could download the next episode in advance to be more independent of server performance 

On the server side, I suspect there is some issue with stopping the stream, since the first stream always works no problem. It’s really hard to debug since it also freezes up the whole device and it takes a long time to ssh into it. Maybe it’s possible to debug by reducing the priority

**Comment by felix920506** [comment]
A first good step would be to enable debug logging. Steps can be found on the project website. https://jellyfin.org
