### ISSUE TITLE
[Issue]: Plugins fail to update and load

### ISSUE THREAD

**Issue by MCHellspawn** [jellyfin/jellyfin#10920]
### Please describe your bug

The scheduled task to update plugins fails always. And the catalog page to load plugins will not load. Existing plugins are working correctly. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel: 6.2.0-37-generic
- Virtualization: yes, KVM
- Clients: Browser
- Browser: Firefox and Chrome
- FFmpeg Version: Don't know how to find this
- Playback Method: 
- Hardware Acceleration: none
- GPU Model:
- Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, OMDb, SkinManager, Studio Images, TMDb, TVHeadend
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2024-01-27 10:30:07.844 -05:00] [ERR] Error
System.NotSupportedException: The 'ttps' scheme is not supported.
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-01-27 10:30:07.859 -05:00] [INF] "Update Plugins" Failed after 0 minute(s) and 0 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MCHellspawn** [comment]
Nevermind, figured it out. I missed the "h" in "https://" on a plugin repo. My bad.
