### ISSUE TITLE
[Issue]: .m3u music playlists are detected but not playable

### ISSUE THREAD

**Issue by hartman8227** [jellyfin/jellyfin#10998]
### Please describe your bug

I had created an m3u playlist from a folder of mp3s using the following command:
```
ls -1 *.mp3 > playlist.m3u
```
I then had added the folder as a new library. Jellyfin saw the playlist no problem, but the playlist was empty. Attempting to play the playlist anyway gave an error about not being able to play the format sent.

I was able to get it working by refreshing the metadata of the playlist. Not sure why that worked though

### Reproduction Steps

In linux, from a folder of MP3s create an M3U playlist with the following command

ls -1 *.mp3 > playlist.m3u

Add the folder as a new music library.

Go to Playlists.

Attempt to play playlist.

### To Get Playlist Working

1) Open the playlist in Jellyfin
2) Select the 3 stacked dots
3) Select Refresh Metadata
  - Refresh Mode: Scan for New and Updated files
4) Click Refresh

Within a minute or so the playlist will begin to populate. You may need to refresh the screen though.

### Jellyfin Version

10.8.13

### Environment

```markdown
Docker container on Ubuntu Server 22.04
```

### Jellyfin logs

```shell
Didn't see anything relevent but I've got alot of errors like this in the logs:

[2024-02-12 05:08:14.581 +00:00] [ERR] [24] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/0a800b2717211433fd988e3fe083695b/playbackinfo".
System.ArgumentNullException: Value cannot be null. (Parameter 'item')
   at Emby.Server.Implementations.Library.MediaSourceManager.GetStaticMediaSources(BaseItem item, Boolean enablePathSubstitution, User user)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetPlaybackMediaSources(BaseItem item, User user, Boolean allowMediaProbe, Boolean enablePathSubstitution, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.GetPlaybackInfo(Guid id, Nullable`1 userId, String mediaSourceId, String liveStreamId)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPlaybackInfo(Guid itemId, Guid userId)
   at lambda_method531(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-02-12 05:08:14.585 +00:00] [ERR] [42] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/bdaf8ac5270d843d558072eb4614e529/playbackinfo".
System.ArgumentNullException: Value cannot be null. (Parameter 'item')
   at Emby.Server.Implementations.Library.MediaSourceManager.GetStaticMediaSources(BaseItem item, Boolean enablePathSubstitution, User user)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetPlaybackMediaSources(BaseItem item, User user, Boolean allowMediaProbe, Boolean enablePathSubstitution, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.GetPlaybackInfo(Guid id, Nullable`1 userId, String mediaSourceId, String liveStreamId)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPlaybackInfo(Guid itemId, Guid userId)
   at lambda_method531(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
/Audio/bb47f82739096c1649bc86bb74a12c4f/hls1/main/29.ts

{"Protocol":0,"Id":"bb47f82739096c1649bc86bb74a12c4f","Path":"/media1/media/music/Third Eye Blind/Third Eye Blind - Blue 1999/08. Third Eye Blind - The Red Summer Sun.flac","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"flac","Size":41977804,"Name":"08. Third Eye Blind - The Red Summer Sun","IsRemote":false,"ETag":"8f3b36bcd98a372e858efbc0ceb2ccb3","RunTimeTicks":3254666752,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"flac","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/44100","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"FLAC - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":1031818,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":44100,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":1031818,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:01:27.000  -i file:"/media1/media/music/Third Eye Blind/Third Eye Blind - Blue 1999/08. Third Eye Blind - The Red Summer Sun.flac" -map_metadata -1 -map_chapters -1 -threads 0   -acodec libfdk_aac -ab 256000 -ac 2 -ar 44100 -vn -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 29 -hls_segment_filename "/config/transcodes/7995594351fb9559b00986e2a1759031%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/7995594351fb9559b00986e2a1759031.m3u8"


ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[flac @ 0x55d1bfd31600] Discarding ID3 tags because more suitable tags were found.
Input #0, flac, from 'file:/media1/media/music/Third Eye Blind/Third Eye Blind - Blue 1999/08. Third Eye Blind - The Red Summer Sun.flac':
  Metadata:
    ARTIST          : Third Eye Blind
    TITLE           : The Red Summer Sun
    ALBUM           : Blue
    DATE            : 1999
    track           : 08
    COMMENT         : Track 8
  Duration: 00:05:25.47, start: 0.000000, bitrate: 1031 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[mpegts @ 0x55d1bfdacd00] frame size not set
Output #0, hls, to '/config/transcodes/7995594351fb9559b00986e2a1759031.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac, 44100 Hz, stereo, s16, 256 kb/s
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903129.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903130.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903131.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903132.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903133.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903134.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903135.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903136.ts' for writing
size=N/A time=00:00:25.35 bitrate=N/A speed=50.6x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903137.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903138.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903139.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903140.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903141.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903142.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903143.ts' for writing
size=N/A time=00:00:47.55 bitrate=N/A speed=47.4x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903144.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903145.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903146.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903147.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903148.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903149.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903150.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903151.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903152.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903153.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903154.ts' for writing
size=N/A time=00:01:18.76 bitrate=N/A speed=52.4x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903155.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903156.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903157.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903158.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903159.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903160.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903161.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903162.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903163.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903164.ts' for writing
size=N/A time=00:01:48.48 bitrate=N/A speed=54.2x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903165.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903166.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903167.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903168.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903169.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903170.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903171.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903172.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903173.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903174.ts' for writing
size=N/A time=00:02:19.87 bitrate=N/A speed=55.9x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903175.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903176.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903177.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903178.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903179.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903180.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903181.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903182.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903183.ts' for writing
size=N/A time=00:02:46.62 bitrate=N/A speed=55.4x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903184.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903185.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903186.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903187.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903188.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903189.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903190.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903191.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903192.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903193.ts' for writing
size=N/A time=00:03:16.34 bitrate=N/A speed=  56x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903194.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903195.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903196.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903197.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903198.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a175903199.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031100.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031101.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031102.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031103.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031104.ts' for writing
size=N/A time=00:03:49.22 bitrate=N/A speed=57.2x    
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031105.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031106.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031107.ts' for writing
[hls @ 0x55d1bfd377c0] Opening '/config/transcodes/7995594351fb9559b00986e2a1759031108.ts' for writing
size=N/A time=00:03:58.49 bitrate=N/A speed=57.6x    
video:0kB audio:7454kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Closing this report as Invalid for the following reasons:
1. Conflicting information is provided within the same report: MP3 is stated in the issue description but the provided logs clearly point towards FLAC source files
2. Client information is not provided at all
3. `[flac @ 0x55d1bfd31600] Discarding ID3 tags because more suitable tags were found.` indicates non conformant source media files which is known to cause issues
