### ISSUE TITLE
[Issue]: Japanese fonts not included

### ISSUE THREAD

**Issue by yamanobe96** [jellyfin/jellyfin#11047]
### Please describe your bug

When creating a collection or Japanese library, □□□ is displayed because there is no font.

### Reproduction Steps

Create a library with Japanese names in a Japanese environment

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:synology nas DSM 7.2.1-69057 Update 3
- Linux Kernel: no
- Virtualization: docker
- Clients: blowser
- Browser: chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
It's not an error, so it has nothing to do with it, but it's essential, so I'll post it.

[2024-02-22 00:05:51.945 +00:00] [INF] [73] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-02-22 00:05:53.646 +00:00] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio" to "127.0.0.1" in 0:00:01.2645079 with Status Code 200
[2024-02-22 00:05:53.647 +00:00] [WRN] [117] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book" to "127.0.0.1" in 0:00:01.2643684 with Status Code 200
[2024-02-22 00:05:53.761 +00:00] [WRN] [73] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=5b25154d75fdf242f3d75270557c32e6" to "127.0.0.1" in 0:00:01.3492341 with Status Code 200
[2024-02-22 00:05:53.762 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=65f0fce906c59239307ee962e7e19593" to "127.0.0.1" in 0:00:01.3564659 with Status Code 200
[2024-02-22 00:05:53.959 +00:00] [WRN] [42] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=2aa1d857635177546f8785032805c532" to "127.0.0.1" in 0:00:01.1381332 with Status Code 200
[2024-02-22 00:05:53.976 +00:00] [WRN] [91] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=c63fe534597a4c5084a43a784ddc8624&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-02-22T00%3A05%3A55.427Z&EnableRewatching=false" to "127.0.0.1" in 0:00:01.5788324 with Status Code 200
[2024-02-22 00:08:31.983 +00:00] [ERR] [84] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/video/アニメ/君に届け 2ND SEASON"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/video/アニメ/君に届け 2ND SEASON'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2024-02-22 00:08:31.993 +00:00] [ERR] [84] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/video/アニメ/君に届け 2ND SEASON'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
[2024-02-22 00:08:47.433 +00:00] [INF] [92] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 62331216-8ae3-cd2c-02cb-ca45e6a95beb-"装甲騎兵ボトムズ": "{\"Tmdb\":\"32377\"}"
[2024-02-22 00:08:49.928 +00:00] [ERR] [112] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/video/アニメ/Ef - a Tale of Melodies/folder.jpg'". URL "GET" "/Items/5465c80c85ae3cc5e318490dde3ea9a6/Images/Primary".
[2024-02-22 00:09:43.815 +00:00] [INF] [112] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 4d33b88d-143b-9254-00d8-84ffd0a2d6aa-"プリンセスナイン 如月女子高野球部": "{\"Tmdb\":\"34757\"}"
[2024-02-22 00:10:12.044 +00:00] [INF] [125] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item f850f3fb-d67a-e2dc-ec78-2594fd2990ce-"ブラスレイター": "{\"Tmdb\":\"34216\"}"
[2024-02-22 00:10:56.868 +00:00] [WRN] [58] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/4d33b88d143b925400d884ffd0a2d6aa?ReplaceAllImages=true" to "127.0.0.1" in 0:01:13.0554794 with Status Code 204
[2024-02-22 00:11:11.988 +00:00] [WRN] [112] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/f850f3fbd67ae2dcec782594fd2990ce?ReplaceAllImages=true" to "127.0.0.1" in 0:00:59.9457543 with Status Code 204
[2024-02-22 00:11:39.965 +00:00] [INF] [100] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-02-22 00:11:51.966 +00:00] [INF] [58] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-02-22 00:12:03.966 +00:00] [INF] [125] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-02-22 00:12:59.814 +00:00] [INF] [124] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 5a7922f2-6e77-9618-ef81-fc7789e778f9-"IS 〈インフィニット・ストラトス〉": "{\"Tmdb\":\"46025\"}"
[2024-02-22 00:13:09.561 +00:00] [INF] [127] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item f6010dcf-607b-c470-fc42-3357eaf8edfb-"魔法少女まどか☆マギカ": "{\"Tmdb\":\"39218\"}"
[2024-02-22 00:13:21.117 +00:00] [INF] [58] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item d5175f63-da39-58b8-524f-157f39f07ac3-"TIGER & BUNNY": "{\"Tmdb\":\"39659\"}"
[2024-02-22 00:13:33.939 +00:00] [INF] [42] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item a2cffb8a-fe0a-e890-2576-960d727f9917-"ストライクウィッチーズ": "{\"Tmdb\":\"35464\"}"
[2024-02-22 00:13:44.214 +00:00] [INF] [53] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item c99e4fdd-ffe4-ba38-877d-047be37c6620-"キルミーベイベー": "{\"Tmdb\":\"73598\"}"
[2024-02-22 00:14:54.886 +00:00] [WRN] [53] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/f6010dcf607bc470fc423357eaf8edfb?ReplaceAllImages=true" to "127.0.0.1" in 0:01:45.3279375 with Status Code 204
[2024-02-22 00:15:55.588 +00:00] [WRN] [124] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/d5175f63da3958b8524f157f39f07ac3?ReplaceAllImages=true" to "127.0.0.1" in 0:02:34.4729693 with Status Code 204
[2024-02-22 00:16:27.583 +00:00] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/623312168ae3cd2c02cbca45e6a95beb?ReplaceAllImages=true" to "127.0.0.1" in 0:07:40.1519446 with Status Code 204
[2024-02-22 00:16:54.862 +00:00] [WRN] [127] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/5a7922f26e779618ef81fc7789e778f9?ReplaceAllImages=true" to "127.0.0.1" in 0:03:55.0497077 with Status Code 204
[2024-02-22 00:18:07.142 +00:00] [WRN] [113] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/a2cffb8afe0ae8902576960d727f9917?ReplaceAllImages=true" to "127.0.0.1" in 0:04:33.2045835 with Status Code 204
[2024-02-22 00:19:02.703 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Items/RemoteSearch/Apply/c99e4fddffe4ba38877d047be37c6620?ReplaceAllImages=true" to "127.0.0.1" in 0:05:18.4905161 with Status Code 204
[2024-02-22 00:19:15.072 +00:00] [ERR] [124] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/video/アニメ/Ef - a Tale of Melodies/backdrop.jpg'". URL "GET" "/Items/5465c80c85ae3cc5e318490dde3ea9a6/Images/Backdrop".
[2024-02-22 00:19:15.456 +00:00] [ERR] [112] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/video/アニメ/Ef - a Tale of Melodies/folder.jpg'". URL "GET" "/Items/5465c80c85ae3cc5e318490dde3ea9a6/Images/Primary".
[2024-02-22 00:19:19.635 +00:00] [WRN] [95] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "127.0.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-02-22 00:19:19.640 +00:00] [INF] [95] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-02-22 00:19:20.767 +00:00] [INF] [124] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-02-22 00:20:44.775 +00:00] [INF] [127] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-02-22 00:20:56.776 +00:00] [INF] [73] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-02-22 00:31:19.367 +00:00] [WRN] [54] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items?Recursive=true&IncludeItemTypes=Audio,AudioBook&ParentId=2aa1d857635177546f8785032805c532&ExcludeLocationTypes=Virtual&SortBy=DateCreated&SortOrder=Descending&Fields=DateCreated&CollapseBoxSetItems=false&limit=1&UserId=c63fe534597a4c5084a43a784ddc8624" to "127.0.0.1" in 0:00:00.8027661 with Status Code 200
[2024-02-22 01:03:02.821 +00:00] [WRN] [110] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "127.0.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-02-22 01:03:02.841 +00:00] [INF] [110] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-02-22 01:10:16.299 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "プラグインの更新"
[2024-02-22 01:10:16.299 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2024-02-22 01:10:16.299 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "プラグインの更新"
[2024-02-22 01:10:19.034 +00:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: "プラグインの更新" Completed after 0 minute(s) and 2 seconds
[2024-02-22 01:10:19.035 +00:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 01:43:36.415 +00:00] [WRN] [81] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Users/c63fe534597a4c5084a43a784ddc8624/Items?Recursive=true&IncludeItemTypes=Audio,AudioBook&ParentId=2627e7d2c827d9bd908128d0320a8263&ExcludeLocationTypes=Virtual&SortBy=DateCreated&SortOrder=Descending&Fields=DateCreated&CollapseBoxSetItems=false&limit=1&UserId=c63fe534597a4c5084a43a784ddc8624" to "127.0.0.1" in 0:00:00.6605996 with Status Code 200
[2024-02-22 02:00:00.000 +00:00] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: "DailyTrigger" fired for task: "チャプター画像を抽出する"
[2024-02-22 02:00:00.000 +00:00] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ChapterImagesTask"
[2024-02-22 02:00:00.000 +00:00] [INF] [50] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "チャプター画像を抽出する"
[2024-02-22 02:00:00.727 +00:00] [ERR] [67] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for "file:\"/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4\""
[2024-02-22 02:00:00.727 +00:00] [ERR] [67] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: I-frame image extraction failed, will attempt standard way. Input: "file:\"/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4\""
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
[2024-02-22 02:00:00.800 +00:00] [ERR] [67] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for "file:\"/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4\""
[2024-02-22 02:00:00.800 +00:00] [ERR] [67] Emby.Server.Implementations.MediaEncoder.EncodingManager: Error extracting chapter images for "/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4"
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/video/アニメ/君に届け 2ND SEASON/special/映像特典 「ミニ届劇場・ロミオとジュリエット 3D(SBS)」.mp4"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, Nullable`1 targetFormat, CancellationToken cancellationToken)
   at Emby.Server.Implementations.MediaEncoder.EncodingManager.RefreshChapterImages(Video video, IDirectoryService directoryService, IReadOnlyList`1 chapters, Boolean extractImages, Boolean saveChapters, CancellationToken cancellationToken)
[2024-02-22 02:00:00.803 +00:00] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: "チャプター画像を抽出する" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:00:00.805 +00:00] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:00:01.002 +00:00] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "チャプター画像を抽出する" set to fire at 2024-02-23 02:00:00.000 +00:00, which is 23:59:58.9979420 from now.
[2024-02-22 02:41:06.105 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "不足している字幕をダウンロードする"
[2024-02-22 02:41:06.106 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "SubtitleScheduledTask"
[2024-02-22 02:41:06.106 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "不足している字幕をダウンロードする"
[2024-02-22 02:41:06.106 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: "不足している字幕をダウンロードする" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:41:06.109 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:41:06.420 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "ログの掃除"
[2024-02-22 02:41:06.420 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "DeleteLogFileTask"
[2024-02-22 02:41:06.420 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "ログの掃除"
[2024-02-22 02:41:06.427 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "ログの掃除" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:41:06.427 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:41:06.652 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "トランスコードディレクトリの削除"
[2024-02-22 02:41:06.652 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "DeleteTranscodeFileTask"
[2024-02-22 02:41:06.652 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "トランスコードディレクトリの削除"
[2024-02-22 02:41:06.652 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "トランスコードディレクトリの削除" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:41:06.652 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:41:06.936 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "TasksRefreshChannels"
[2024-02-22 02:41:06.936 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "RefreshChannelsScheduledTask"
[2024-02-22 02:41:06.936 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "TasksRefreshChannels"
[2024-02-22 02:41:06.938 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "TasksRefreshChannels" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:41:06.938 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:41:07.684 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "データベースの最適化"
[2024-02-22 02:41:07.684 +00:00] [INF] [100] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "OptimizeDatabaseTask"
[2024-02-22 02:41:07.684 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "データベースの最適化"
[2024-02-22 02:41:07.684 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.Tasks.OptimizeDatabaseTask: Optimizing and vacuuming jellyfin.db...
[2024-02-22 02:41:07.724 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.Tasks.OptimizeDatabaseTask: jellyfin.db optimized successfully!
[2024-02-22 02:41:07.724 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: "データベースの最適化" Completed after 0 minute(s) and 0 seconds
[2024-02-22 02:41:07.725 +00:00] [INF] [86] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-02-22 02:49:44.027 +00:00] [INF] [107] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-02-22 02:50:32.059 +00:00] [INF] [66] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-02-22 02:50:42.862 +00:00] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/video/アニメ/Ef - a Tale of Melodies/folder.jpg'". URL "GET" "/Items/5465c80c85ae3cc5e318490dde3ea9a6/Images/Primary".
[2024-02-22 02:50:44.059 +00:00] [INF] [82] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-02-22 02:50:47.434 +00:00] [WRN] [82] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "127.0.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-02-22 02:50:47.439 +00:00] [INF] [82] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-02-22 02:50:48.550 +00:00] [INF] [43] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-02-22 02:51:03.813 +00:00] [WRN] [97] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://100.74.116.86:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=c63fe534597a4c5084a43a784ddc8624&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-02-22T02%3A51%3A06.334Z&EnableRewatching=false" to "127.0.0.1" in 0:00:00.5227218 with Status Code 200
```

### Please attach any screenshots here

![c525ce64-45cd-4454-aeb4-194fb573ca82](https://github.com/jellyfin/jellyfin/assets/46581513/cf3f419c-fe63-48d0-b0cf-25cce618e9fc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Ahhh, interesting. The image is rendered server-side and if there is no CJK fonts on the server then CJS characters will look like this.

This can be fixed by adding CJK fonts to our Docker image. However, we must implement this carefully. Because CJK characters share the same UTF-8 encoding but may appear differently depending on the locale settings of the machine. For example, below is `U+8FD4` in different locales:
![image](https://github.com/jellyfin/jellyfin/assets/12995396/bb5758c7-5bb1-4bd6-9b2f-9ef523ad5415)

So we may also need an option to allow modify the local settings in the docker image via env variables to show the correct character.

**Comment by nielsvanvelzen** [comment]
Closing as duplicate of #5008
