### ISSUE TITLE
[Issue]: reset user root folder path failed

### ISSUE THREAD

**Issue by schalkiii** [jellyfin/jellyfin#11057]
### Please describe your bug

Hi all, I'm having problems migrating jellyfin configurations and media libraries from my old computer to my new one!

The logs show that the root folder should have been properly reset to the path of the new username

[2024-02-23 23:17:15.974 +08:00] [INF] [1] Emby.Server.Implementations.Library.LibraryManager: reset user root folder path to "C:\Users\Schal\AppData\Local\ Jellyfin\root\default"

But when scanning the media library, the path looked for is the same as the old username at previous PC with ".000".

[2024-02-23 23:33:55.248 +08:00] [ERR] [53] Emby.Server.Implementations.ScheduledTasks.TaskManager: error
[System.IO](http://system.io/).DirectoryNotFoundException: Unable to find part of path 'C:\Users\Schal.000\AppData\Local\Jellyfin\root\default\movie'.

It seems  reset user root folder path failed.  Or can I manually change the user root directory setting to work around ?

### Reproduction Steps

1. migrating local appdata of jellyfin  from old computer to new one
2. scan media library

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Windows 11
```

### Jellyfin logs

```shell
[2024-02-23 23:17:15.974 +08:00] [INF] [1] Emby.Server.Implementations.Library.LibraryManager: reset user root folder path to "C:\Users\Schal\AppData\Local\ Jellyfin\root\default"

[2024-02-24 10:38:39.277 +08:00] [ERR] [283] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Schal.000\AppData\Local\Jellyfin\root\default\电影'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.RequiresRefresh()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass68_0.<<RefreshChildMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.UserRootFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, Jellyfin currently handle media libraries based on their filesystem path.

The path for existing items won't be changed even if you update the library settings.

This is a limitation of how Jellyfin currently works and there are already similar open issues.

Your only ways out of this are to make the media library path EXACTLY the same as what the path used to be on the old setup, or to use a 3rd party migration script that may or may not cause bad things to happen. 

Closing as duplicate
