### ISSUE TITLE
[Issue]: DLNA settings menu does not work in Jellyfin unstable

### ISSUE THREAD

**Issue by iwch** [jellyfin/jellyfin#11065]
### Please describe your bug

I recently upgraded my 10.8.13 installation to 10.9.0 (unstable). DLNA stopped working after the upgrade, so I navigated to the DLNA settings menu in the dashboard. I get a blue spinning wheel in this interface, seemingly forever. Changing the settings does not seem to work. I see exceptions in the logs when I navigate to this menu (pasted below).

### Reproduction Steps

1. Run the Jellyfin/jellyfin:unstable docker image
2. Open the DLNA settings in the management dashboard

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6.5.0-21-generic
- Virtualization: N/A
- Clients: Web client
- Browser: Firefox, Chromium
- FFmpeg Version: The default in the docker container
- Playback Method: N/A
- Hardware Acceleration: Enabled, VA-API
- GPU Model: Ryzen 5650G
- Plugins: None
- Reverse Proxy: Nginx
- Base URL: -
- Networking: Docker Macvlan 
- Storage: local RAIDZ2 array
```

### Jellyfin logs

```shell
jellyfin               | [19:58:07] [ERR] [8] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Configuration/dlna.
jellyfin               | MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key dlna not found.
jellyfin               |    at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c.<GetConfiguration>b__41_0(String k, BaseConfigurationManager configurationManager)
jellyfin               |    at Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfiguration(String key)
jellyfin               |    at lambda_method1106(Closure, Object, Object[])
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
jellyfin               | --- End of stack trace from previous location ---
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin               | --- End of stack trace from previous location ---
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin               | --- End of stack trace from previous location ---
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin               |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin               |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin               |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin               |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin               |    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin               |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin               |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin               |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin               |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin               |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin               |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin               |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin               |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin               |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfin               |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin               |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Jellyfin 10.9 does not have DLNA enabled by default as the functionality was moved to a new plugin. You'll need to install the [DLNA plugin](https://github.com/jellyfin/jellyfin-plugin-dlna).

**Comment by nielsvanvelzen** [comment]
The fact that the DLNA options are still available in the dashboard might be a bug. I'm not sure if the web part was also moved to the plugin or if there are still changes to be made on the web client.

**Comment by iwch** [comment]
@nielsvanvelzen Is that plugin available to install via any repository?

**Comment by crobibero** [comment]
No, there is no unstable plugin repository.

**Comment by johngianni** [comment]
I just follow up on this matter, as the DLNA plug-in is not working as of current source code state of server and plugin itself. 
I've compiled both solutions and the plugin is not loaded by the server with the following error:

`Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/DLNA/Jellyfin.Plugin.Dlna.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GetIcon' in type 'Jellyfin.Plugin.Dlna.DlnaManager' from assembly 'Jellyfin.Plugin.Dlna, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

It's worth mentioning that the unstable versions of the two modules were working 4 5 weeks ago from the latest master branch. 
I've managed to load the plug-in deleting from the iDLNAManager interface the geticon function, but then the DLNA server would not stream any content to devices.

**Comment by crobibero** [comment]
Plugins aren't supported for unstable versions of Jellyfin. It will be updated once 10.9 is in its release cycle.

**Comment by TimGels** [comment]
Related issue on web: [#5234](https://github.com/jellyfin/jellyfin-web/issues/5234)

**Comment by thornbill** [comment]
Closing in favor of the web issue.
