### ISSUE TITLE
[Issue]: MovieMetadataService: Error in The Open Movie Database System

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#11073]
### Please describe your bug

Error message in the logs:

```
[ERR] [65] MediaBrowser.Providers.Movies.MovieMetadataService: Error in The Open Movie Database
System.Text.Json.JsonException: 't' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 0 | Byt
ePositionInLine: 53.
 ---> System.Text.Json.JsonReaderException: 't' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | B
ytePositionInLine: 53.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte,
ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert
, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOption
s options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStac
k& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStac
k& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buf
fer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderSt
ate, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken canc
ellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, J
sonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions option
s, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureItemInfo(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetRootObject(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.Fetch[T](MetadataResult`1 itemResult, String imdbId, String language,
String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetResult[T](ItemLookupInfo info, CancellationToken cancellationTo
ken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType
id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Reproduction Steps

Not sure I can give some direction here, it just happens on my platform, when I run a `Scan for New or updated files` on a library. And it obviously seem related to calls to OMDB API.

All I can say is I followed this closed issue https://github.com/jellyfin/jellyfin/issues/4965
and deleted /cachedir/omdb/*.json and relaunched `
Search for missing metadata` (which created a few occurence of this) on libraries and tried `Scan for New or updated files` again, and it sill produces the error log.

### Jellyfin Version

10.8.13

### Environment

```markdown
I don't think it applies here.

- OS: Ubuntu 22.04
- Linux Kernel: 5.x
- Virtualization: on Bhyve on TrueNas
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GlenNicholls** [comment]
@nodje and @jellyfin-bot I'm seeing this in `12.1`. Can you please reopen if you're still seeing this or lmk if you'd like me to open a duplicate?
