### ISSUE TITLE
[Issue]: Issues displaying srt subtitles in jellyfin firetv app

### ISSUE THREAD

**Issue by itsjakeman** [jellyfin/jellyfin#11099]
### Please describe your bug

If subtitles gets replaced it seems it wont pickup new file on firetv. All other devices show the subtitles. removing and adding back into library does not solve the issue. Issues just started happening in last version update.

### Reproduction Steps

Add video with subtitle file but only containing a partial of the movie.
Replace subtitles with correct version, rescan libary
Movie on jellyfin app will detect new subtitle but will not display it.

### Jellyfin Version

10.8.13

### if other:

FireTV

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-03-03 13:13:54.341 -06:00] [INF] Adding playback tracker : f0a089860104d74295ac324cc16a3e61d5abec9a-5ed13f69a0c44e0a97eebd950e36e451-70de5365fb71636bb813f929f914a4b4
[2024-03-03 13:13:54.341 -06:00] [INF] PlaybackTracker : Adding Start Event : 03/03/2024 13:13:54
[2024-03-03 13:13:54.341 -06:00] [INF] Creating StartPlaybackTimer Task
[2024-03-03 13:13:54.341 -06:00] [INF] StartPlaybackTimer : Entered
[2024-03-03 13:13:54.837 -06:00] [INF] Started user data sync
[2024-03-03 13:13:54.856 -06:00] [ERR] An error has occurred in UserUpdateTimerCallback
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SaveUserChanges(List`1 dtos, List`1 itemRefs, String userName, String userId)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SendNotifications(IEnumerable`1 changes, List`1 itemRefs, CancellationToken cancellationToken)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.UpdateTimerCallback(Object state)
[2024-03-03 13:13:55.330 -06:00] [INF] Processing playback tracker : "f0a089860104d74295ac324cc16a3e61d5abec9a-5ed13f69a0c44e0a97eebd950e36e451-70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:13:57.251 -06:00] [INF] session.RemoteEndPoint : "10.10.77.177"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : event_playing_id     = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : event_user_id        = "018d78cd3b824899a5de06c764201e6a"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : session_playing_id   = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : session_user_id      = "018d78cd3b824899a5de06c764201e6a"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : e.DeviceName         = "Firefox"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : ItemName             = "Harriet"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : ItemId               = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : ItemType             = "Movie"
[2024-03-03 13:13:57.252 -06:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-03-03 13:13:57.252 -06:00] [INF] Playback tracker found, adding playback info : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTIyLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTIyLjB8MTcwNzM3MzE5OTM3MA11-018d78cd3b824899a5de06c764201e6a-70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:13:57.252 -06:00] [INF] Saving playback tracking activity in DB
[2024-03-03 13:13:57.255 -06:00] [INF] StartPlaybackTimer : Exited
[2024-03-03 13:13:58.080 -06:00] [INF] Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTIyLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTIyLjB8MTcwNzM3MzE5OTM3MA11-018d78cd3b824899a5de06c764201e6a-70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:14:08.098 -06:00] [ERR] Can't scrobble: User "jelly-admin" not logged in (True)
[2024-03-03 13:14:14.339 -06:00] [INF] session.RemoteEndPoint : "10.7.77.27"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : event_playing_id     = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : event_user_id        = "5ed13f69a0c44e0a97eebd950e36e451"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : event_user_id_int    = 2
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : session_playing_id   = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : session_user_id      = "5ed13f69a0c44e0a97eebd950e36e451"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : e.ClientName         = "Android TV"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : e.DeviceName         = "Living Room FireTV"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : ItemName             = "Harriet"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : ItemId               = "70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:14:14.339 -06:00] [INF] StartPlaybackTimer : ItemType             = "Movie"
[2024-03-03 13:14:14.340 -06:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-03-03 13:14:14.340 -06:00] [INF] Playback tracker found, adding playback info : "f0a089860104d74295ac324cc16a3e61d5abec9a-5ed13f69a0c44e0a97eebd950e36e451-70de5365fb71636bb813f929f914a4b4"
[2024-03-03 13:14:14.340 -06:00] [INF] Saving playback tracking activity in DB
[2024-03-03 13:14:14.341 -06:00] [INF] StartPlaybackTimer : Exited
[2024-03-03 13:14:15.065 -06:00] [INF] Playback stopped reported by app "Android TV" "0.16.6" playing "Harriet". Stopped at "398039" ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
I cannot reproduce your issue on master or on 10.8.13 in the web client with your provided information. But this issue should be moved to the android tv client repo if that is where you encounter this issue. https://github.com/jellyfin/jellyfin-androidtv
