### ISSUE TITLE
[Issue]: Installed subtitle fonts location!

### ISSUE THREAD

**Issue by sentakuhm** [jellyfin/jellyfin#11105]
### Please describe your bug

Idk if this an issue or not, i just want to mention this if anyone had the situation as me, the the client on android tv not viewing ASS subtitles correctly even if installed all needed fonts in the server.

### Reproduction Steps

1. I Installed fonts to `~/.local/share/fonts` as user followed arch wiki, but that doesn't show correct subtitle on client.
2. I moved all `~/.local/share/fonts` to system wide folder '/usr/share/fonts', and this worked very well, showing correct fonts.

so, i just put this if you want mentioned this in Documentations page, that fonts work when installed in system wide directory.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Arch linux.
- Linux Kernel: linux-zen latest.
- Virtualization:
- Clients:
- Browser: Firefox.
- FFmpeg Version:ffmpeg version 6.0.1-Jellyfin
- Playback Method:Jellyfin on android tv.
- Hardware Acceleration:Vaapi.
- GPU Model:Rx 6800.
- Plugins: default.
- Reverse Proxy:no.
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-03-04 08:29:49.076 +01:00] [INF] [4] Main: Jellyfin version: "10.8.13"
[2024-03-04 08:29:49.097 +01:00] [INF] [4] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/sentaku/.local/share/jellyfin/log]"]
[2024-03-04 08:29:49.099 +01:00] [INF] [4] Main: Arguments: ["/usr/lib/jellyfin/jellyfin.dll", "--ffmpeg"]
[2024-03-04 08:29:49.100 +01:00] [INF] [4] Main: Operating system: "Linux"
[2024-03-04 08:29:49.100 +01:00] [INF] [4] Main: Architecture: X64
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: 64-Bit Process: True
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: User Interactive: True
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: Processor count: 16
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: Program data path: "/home/sentaku/.local/share/jellyfin"
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: Web resources path: "/usr/share/jellyfin-web"
[2024-03-04 08:29:49.101 +01:00] [INF] [4] Main: Application directory: "/usr/lib/jellyfin/"
[2024-03-04 08:29:49.126 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration"]
[2024-03-04 08:29:49.181 +01:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/home/sentaku/.cache/jellyfin"
[2024-03-04 08:29:49.186 +01:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-03-04 08:29:49.231 +01:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-03-04 08:29:49.232 +01:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2024-03-04 08:29:49.232 +01:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-03-04 08:29:49.240 +01:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2024-03-04 08:29:49.240 +01:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2024-03-04 08:29:49.981 +01:00] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[2024-03-04 08:29:50.286 +01:00] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: EFCore migrations applied successfully
[2024-03-04 08:29:50.637 +01:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-03-04 08:29:50.638 +01:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/home/sentaku/.cache/jellyfin"
[2024-03-04 08:29:50.641 +01:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.13.0"
[2024-03-04 08:29:50.642 +01:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.13.0"
[2024-03-04 08:29:50.642 +01:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.13.0"
[2024-03-04 08:29:50.642 +01:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.13.0"
[2024-03-04 08:29:50.643 +01:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.13.0"
[2024-03-04 08:29:50.676 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase"]
[2024-03-04 08:29:50.677 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddDefaultPluginRepository"'
[2024-03-04 08:29:50.677 +01:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-03-04 08:29:50.677 +01:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/home/sentaku/.cache/jellyfin"
[2024-03-04 08:29:50.678 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddDefaultPluginRepository"' applied successfully
[2024-03-04 08:29:50.684 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"ReaddDefaultPluginRepository"'
[2024-03-04 08:29:50.684 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"ReaddDefaultPluginRepository"' applied successfully
[2024-03-04 08:29:50.684 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddPeopleQueryIndex"'
[2024-03-04 08:29:50.685 +01:00] [INF] [4] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[2024-03-04 08:29:50.697 +01:00] [INF] [4] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_PeopleNameListOrder
[2024-03-04 08:29:50.709 +01:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddPeopleQueryIndex"' applied successfully
[2024-03-04 08:29:50.714 +01:00] [INF] [4] Main: Kestrel listening on "Any IP4 Address"
[2024-03-04 08:29:50.899 +01:00] [WRN] [4] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {3e4c56f8-93e0-4ebb-b68e-deb326a50aeb} may be persisted to storage in unencrypted form.
[2024-03-04 08:29:50.923 +01:00] [ERR] [4] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again.
[2024-03-04 08:29:50.923 +01:00] [FTL] [4] Main: Error while starting server.
System.IO.IOException: Failed to bind to address http://0.0.0.0:8096: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2024-03-04 08:29:50.928 +01:00] [INF] [4] Main: Running query planner optimizations in the database... This might take a while
[2024-03-04 08:29:50.966 +01:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-03-04 08:29:50.967 +01:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2024-03-04 08:29:50.968 +01:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2024-03-04 08:29:50.968 +01:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2024-03-04 08:29:50.970 +01:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
You are using the web client. For subtitles here you should set fallback fonts under playback in the dashboard.

Closing this as it is a configuration issue and not an actual Jellyfin bug

**Comment by sentakuhm** [comment]
i already set woff2 fallback fonts about 8mb folder size.
