### ISSUE TITLE
[Issue]: SVG BlurHash exception

### ISSUE THREAD

**Issue by TimGels** [jellyfin/jellyfin#11128]
### Please describe your bug

On master branch 10.9 unstable, I am getting an exception when the program calls the `BlurHashEncoder.Encode` method. Currently testing on commit 83d2bc3f9f13c62f6d3ef16c4fe75f0f5a18110d.

### Reproduction Steps

1. Have a clean setup
2. Add `Spice and Wolf (2008) [tmdbid-26707]` as show title and add some mkv files as episodes
3. Set up jellyfin by walking through the setup
4. Refresh main page for good measure

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Windows 11
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: Web browsers
- Browser: Firefox & Edge
- FFmpeg Version: 5.x
- Playback Method: Not relevant
- Hardware Acceleration: No
- GPU Model: RX 6900XT
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-03-08 22:11:57.318 +01:00] [INF] [34] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-03-08 22:12:42.657 +01:00] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: "TMDB" ("D:\TestMedia\TMDB") will be refreshed.
[2024-03-08 22:13:18.775 +01:00] [INF] [18] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-08 22:13:18.836 +01:00] [ERR] [19] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "C:\Users\Tim\AppData\Local\jellyfin\metadata\library\86\86e9cc25d8aa5cedfd51ecfc43f56432\logo.svg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path) in C:\Users\Tim\source\repos\jellyfin\src\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 198
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions) in C:\Users\Tim\source\repos\jellyfin\src\Jellyfin.Drawing\ImageProcessor.cs:line 402
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in C:\Users\Tim\source\repos\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1899
[2024-03-08 22:13:19.137 +01:00] [ERR] [31] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (1a32d394eaa58eea567095acabd8d7cd) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:20.265 +01:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "C:\Users\Tim\AppData\Local\jellyfin\metadata\library\86\86e9cc25d8aa5cedfd51ecfc43f56432\logo.svg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path) in C:\Users\Tim\source\repos\jellyfin\src\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 198
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions) in C:\Users\Tim\source\repos\jellyfin\src\Jellyfin.Drawing\ImageProcessor.cs:line 402
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in C:\Users\Tim\source\repos\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1899
[2024-03-08 22:13:19.137 +01:00] [ERR] [22] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (d11d33a4c31a604beea7976f0581dcd4) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.137 +01:00] [ERR] [21] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (1a32d394eaa58eea567095acabd8d7cd) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.151 +01:00] [ERR] [19] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (85359463ce83dc5b290a085f4f93cff4) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.142 +01:00] [ERR] [18] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (93deeb8a70d3207934a096f33eb1370d) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.137 +01:00] [ERR] [12] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (1a32d394eaa58eea567095acabd8d7cd) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:20.254 +01:00] [ERR] [5] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (93deeb8a70d3207934a096f33eb1370d) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.137 +01:00] [ERR] [50] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (85359463ce83dc5b290a085f4f93cff4) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:19.137 +01:00] [ERR] [49] MediaBrowser.Controller.Entities.BaseItem: Error refreshing folder
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (85359463ce83dc5b290a085f4f93cff4) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 974
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 972
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass63_1.<ValidateChildrenInternal2>b__0(Double innerPercent) in C:\Users\Tim\source\repos\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 441
[2024-03-08 22:13:30.817 +01:00] [INF] [56] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-08 22:16:19.099 +01:00] [INF] [61] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-08 22:19:07.255 +01:00] [INF] [22] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-08 22:22:31.458 +01:00] [INF] [31] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-08 22:23:20.867 +01:00] [INF] [1] Main: Jellyfin version: "10.9.0"```
```

### Please attach any screenshots here

Exception seen in visual studio
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/6b575657-d6ef-4fe2-954d-fcbef338dab2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
#11127
