### ISSUE TITLE
[Issue]: Playback error when playing/shuffling collections

### ISSUE THREAD

**Issue by BBaoVanC** [jellyfin/jellyfin#11216]
### Please describe your bug

Not sure if this is related to #6193 and #7226. I get the "Playback Error: This client isn't compatible with the media and the server isn't sending a compatible media format." message when trying to shuffle a collection. If it matters I am using FLAC music albums. I sent part of the log file, there's an error there but not sure if it's related. I do see on browser in the Network tab of developer console that it fires a request to `http://jellyfin.[local]/Users/fb6c78b4615b4420be7eb1511cea0a74/Items?ParentId=a0aa92d3cd494a0b6fcba6323e6b8f05&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio%2CVideo&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false` which returns a seemingly empty response: `{"Items":[],"TotalRecordCount":0,"StartIndex":0}`. It also shows in console:

```
Requesting http://jellyfin.[local]/Users/fb6c78b4615b4420be7eb1511cea0a74/Items?ParentId=a0aa92d3cd494a0b6fcba6323e6b8f05&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio%2CVideo&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false [main.jellyfin.bundle.js:2:791231](http://jellyfin.[local]/web/main.jellyfin.bundle.js?d5f64bca077b6d6aaf33)
Uncaught (in promise) undefined
```

### Reproduction Steps

1. Create collection (in this case I am using a couple Minecraft soundtrack albums)
2. Click shuffle button in the collection
3. Observe error

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-18-amd64
- Virtualization: Docker
- Clients: Web, macOS (Jellyfin Media Player v1.9.1)
- Browser: Firefox 123.0.1
- FFmpeg Version: N/A (using Jellyfin official Docker image)
- Playback Method: Direct Play FLAC
- Hardware Acceleration: none
- GPU Model: N/A
- Plugins: last.fm
- Reverse Proxy: Caddy
- Base URL: none
- Networking: Docker bridge
- Storage: local bind mount
```

### Jellyfin logs

```shell
[2024-03-26 05:18:55.095 +00:00] [DBG] [14] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: SongCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SongCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[2024-03-26 05:18:55.143 +00:00] [DBG] [14] MediaBrowser.Controller.Entities.BaseItem: "BoxSet": Query requires post-filtering due to LinkedChildren.
[2024-03-26 05:18:55.552 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.552 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.892 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.892 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.892 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.892 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.899 +00:00] [DBG] [14] MediaBrowser.Controller.Entities.BaseItem: "BoxSet": Query requires post-filtering due to LinkedChildren.
[2024-03-26 05:18:55.900 +00:00] [DBG] [14] MediaBrowser.Controller.Entities.BaseItem: "BoxSet": Query requires post-filtering due to LinkedChildren.
[2024-03-26 05:18:55.964 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:55.964 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:57.552 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:57.553 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:18:57.558 +00:00] [DBG] [11] MediaBrowser.Controller.Entities.BaseItem: "BoxSet": Query requires post-filtering due to LinkedChildren.
[2024-03-26 05:19:02.019 +00:00] [DBG] [14] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 2 WebSockets.
[2024-03-26 05:19:07.205 +00:00] [DBG] [14] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "10.0.0.60" received message: WebSocketMessage`1 { MessageType: SessionsStop, MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2024-03-26 05:19:07.208 +00:00] [DBG] [14] Jellyfin.Api.WebSocketListeners.SessionInfoWebSocketListener: WS "10.0.0.60" stop transmitting to "SessionInfoWebSocketListener"
[2024-03-26 05:19:07.209 +00:00] [DBG] [14] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "10.0.0.60" received message: WebSocketMessage`1 { MessageType: ScheduledTasksInfoStop, MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2024-03-26 05:19:07.209 +00:00] [DBG] [14] Jellyfin.Api.WebSocketListeners.ScheduledTasksWebSocketListener: WS "10.0.0.60" stop transmitting to "ScheduledTasksWebSocketListener"
[2024-03-26 05:19:07.209 +00:00] [DBG] [14] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "10.0.0.60" received message: WebSocketMessage`1 { MessageType: ScheduledTasksInfoStop, MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2024-03-26 05:19:07.209 +00:00] [DBG] [14] Jellyfin.Api.WebSocketListeners.ScheduledTasksWebSocketListener: WS "10.0.0.60" stop transmitting to "ScheduledTasksWebSocketListener"
[2024-03-26 05:19:07.240 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:07.240 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:07.244 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:07.244 +00:00] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:08.710 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:08.710 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-03-26 05:19:13.829 +00:00] [DBG] [14] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
```

### Please attach any browser or client logs here

```
Requesting http://jellyfin.[local]/Users/fb6c78b4615b4420be7eb1511cea0a74/Items?ParentId=a0aa92d3cd494a0b6fcba6323e6b8f05&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio%2CVideo&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false [main.jellyfin.bundle.js:2:791231](http://jellyfin.[local]/web/main.jellyfin.bundle.js?d5f64bca077b6d6aaf33)
Uncaught (in promise) undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EgorBakanov** [comment]
Fixed in 10.9 version but it seems like the resulted playlist doesn't separate different albums and they all mixed together
