### ISSUE TITLE
[Issue]: Can't add libraries on 10.9 beta

### ISSUE THREAD

**Issue by foux** [jellyfin/jellyfin#11237]
### Please describe your bug

Hello,
I'm trying to test 10.9. FOr that I create a brand new server, and want to add libraries without any metadata fetchers (the library will retrieve the metadatas from the NFO and images already created by my main instance.
After clicking the create button, I go back to an empty list of libraries

### Reproduction Steps

1. Create a brand new jellyfin instance
2. Add any type of library, but disabling all metadata fetchers, only checking NFO and downloading image into source folder
3. Create the library

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.6.22-1-lts
- Virtualization: Docker
- Clients: Web
- Browser: Chrome
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: N.A
- Hardware Acceleration: N.A
- GPU Model: N.A
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Brdige
- Storage: local
```

### Jellyfin logs

```shell
[2024-03-28 08:13:22.361 +01:00] [INF] [1] Main: Startup complete 0:00:01.8798115
[2024-03-28 08:13:25.132 +01:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "TaskCleanCollectionsAndPlaylists" Completed after 0 minute(s) and 0 seconds
[2024-03-28 08:13:25.897 +01:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2024-03-28 08:13:47.734 +01:00] [INF] [8] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-03-28 08:13:47.736 +01:00] [INF] [8] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-03-28 08:13:47.736 +01:00] [INF] [21] Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
[2024-03-28 08:13:47.855 +01:00] [WRN] [18] Jellyfin.Server.Implementations.Users.UserManager: No users, creating one with username "MyJellyfinUser"
[2024-03-28 08:15:51.970 +01:00] [INF] [26] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-03-28 08:15:51.970 +01:00] [INF] [26] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-03-28 08:15:55.158 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-03-28 08:15:55.158 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-03-28 08:15:55.158 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-03-28 08:15:55.159 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "172.19.0.2"]
[2024-03-28 08:15:55.159 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-03-28 08:15:55.159 +01:00] [INF] [23] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[2024-03-28 08:15:56.642 +01:00] [INF] [23] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-03-28 08:15:56.643 +01:00] [INF] [23] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-03-28 08:15:56.657 +01:00] [INF] [3] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-03-28 08:15:56.741 +01:00] [WRN] [3] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-03-28 08:15:56.753 +01:00] [WRN] [23] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-03-28 08:15:56.765 +01:00] [ERR] [27] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2024-03-28 08:15:56.775 +01:00] [INF] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Analyser la médiathèque" Completed after 0 minute(s) and 0 seconds
[2024-03-28 08:16:11.099 +01:00] [INF] [21] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "foux-admin" has succeeded.
[2024-03-28 08:16:11.100 +01:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "foux-admin": 0/0
[2024-03-28 08:16:11.137 +01:00] [INF] [21] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 88af494b-9a07-43c0-a21a-a49c8ad2f75a
[2024-03-28 08:16:11.349 +01:00] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.10.93" request
[2024-03-28 08:16:23.585 +01:00] [INF] [24] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-03-28 08:16:23.593 +01:00] [WRN] [24] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-03-28 08:16:23.599 +01:00] [WRN] [3] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-03-28 08:16:23.619 +01:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2024-03-28 08:16:23.622 +01:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Analyser la médiathèque" Completed after 0 minute(s) and 0 seconds
[2024-03-28 08:16:59.361 +01:00] [INF] [24] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:17:01.751 +01:00] [INF] [16] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.10.93" request
[2024-03-28 08:17:11.362 +01:00] [INF] [24] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:17:23.361 +01:00] [INF] [24] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-03-28 08:19:59.363 +01:00] [INF] [32] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:22:47.365 +01:00] [INF] [35] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:25:35.364 +01:00] [INF] [46] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:28:23.368 +01:00] [INF] [53] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:31:47.367 +01:00] [INF] [71] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-28 08:36:47.367 +01:00] [INF] [88] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### FFmpeg logs

N.A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
The logs don't show any library getting added

**Comment by foux** [comment]
@nielsvanvelzen indeed when I click on create they don't get added. I just go back to the libraries list without my ny library

**Comment by foux** [comment]
@nielsvanvelzen OK sorry, my bad, it was my fault : I didn't add any Folders....
But I didn't get any warning, just the page closing
