### ISSUE TITLE
[Issue]: .net7 breaking change collectible-assemblies

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin#11251]
### Please describe your bug

A breaking change in .net7 affects `Emby.Server.Implementations.Serialization.MyXmlSerializer`

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/collectible-assemblies

### Reproduction Steps

update plugin build from .net6 (10.8) to .net8 (10.9)
 
related: https://github.com/ConfusedPolarBear/intro-skipper/issues/174

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
Docker
```

### Jellyfin logs

```shell
[2024-03-28 23:48:18.715 +01:00] [ERR] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.AggregateException: One or more errors occurred. (A non-collectible assembly may not reference a collectible assembly.)
 ---> System.NotSupportedException: A non-collectible assembly may not reference a collectible assembly.
   at System.Reflection.Emit.RuntimeModuleBuilder.<GetTypeRef>g____PInvoke|13_0(QCallModule __module_native, UInt16* __strFullName_native, QCallModule __refedModule_native, Int32 __tkResolution_native)
   at System.Reflection.Emit.RuntimeModuleBuilder.GetTypeTokenWorkerNoLock(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.RuntimeModuleBuilder.GetTypeTokenInternal(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(Type clsArgument, Boolean lastWasGenericInst)
   at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(Type clsArgument, Boolean lastWasGenericInst)
   at System.Reflection.Emit.RuntimeILGenerator.DeclareLocal(Type localType, Boolean pinned)
   at System.Xml.Serialization.CodeGenerator.DeclareLocal(Type type, String name)
   at System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(Type type, String name)
   at System.Xml.Serialization.ReflectionAwareILGen.WriteArrayLocalDecl(String typeName, String variableName, SourceInfo initValue, TypeDesc arrayTypeDesc)
   at System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(SourceInfo source, ElementAccessor element, String arrayName, Boolean writeAccessor)
   at System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(SourceInfo source, String enumSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, String arrayName, Boolean writeAccessors, Boolean isNullable)
   at System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(SourceInfo source, String choiceSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc memberTypeDesc, Boolean writeAccessors)
   at System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
   at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.<>c.<GetSerializer>b__1_0(String _, Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.GetSerializer(Type type)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToWriter(Object obj, XmlWriter writer)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToStream(Object obj, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.SaveTimestamps()
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.UpdateTimestamps(Dictionary`2 newTimestamps, AnalysisMode mode)
   at ConfusedPolarBear.Plugin.IntroSkipper.ChapterAnalyzer.AnalyzeMediaFiles(ReadOnlyCollection`1 analysisQueue, AnalysisMode mode, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(ReadOnlyCollection`1 items, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.<>c__DisplayClass5_0.<AnalyzeItems>b__0(KeyValuePair`2 season)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I'm not sure if there is anything we can do to resolve this.
It would likely be best to just cache the xml serializer in the plugin

**Comment by oddstr13** [comment]
Relevant docs on the error; https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/collectible-assemblies

**Comment by gnattu** [comment]
Hello, do you have a more supported plugin that can easily reproduce this issue?

The plugin you pointed to is not going to work with Jellyfin 10.9, even without this problem.

When we are evaluating mitigation paths we want to verify the functionality as well.

**Comment by gnattu** [comment]
I downloaded your build of 10.9 preview: https://github.com/jumoog/intro-skipper/releases/tag/10.9%2Fpreview

And I performed both analyzation on a library with more than 200 episodes, and both successes without the exception raised:

<img width="855" alt="image" src="https://github.com/jellyfin/jellyfin/assets/12995396/0b05ca98-c6d3-4ac3-a2cc-7eaae47b8175">

Please provide more detailed reproduction step otherwise we cannot do much to test our theories.

**Comment by phyzical** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/5182053/747440d6-729d-40ab-9984-69caf414d35d)

just jumped across to linux servers nightly build can confirm it seems to be plotting along for me too after manually installing the above dll

**Comment by jumoog** [comment]
> I downloaded your build of 10.9 preview: [jumoog/intro-skipper@`10.9%2Fpreview` (release)](https://github.com/jumoog/intro-skipper/releases/tag/10.9%2Fpreview)
> 
> And I performed both analyzation on a library with more than 200 episodes, and both successes without the exception raised:
> <img alt="image" width="855" src="https://private-user-images.githubusercontent.com/12995396/318171486-0b05ca98-c6d3-4ac3-a2cc-7eaae47b8175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTM4NjcsIm5iZiI6MTcxMTc5MzU2NywicGF0aCI6Ii8xMjk5NTM5Ni8zMTgxNzE0ODYtMGIwNWNhOTgtYzZkMy00YWMzLWEyY2MtN2VhYWU0N2I4MTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDEwMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmM2YxOGUyMjgzMmYwMDVkYzVkYmEzYTdkZWQ2YWUyMTNiNGJhYzA2NWU3MWEyMTUzMjRjYWY1NzFkNzViNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKWUWWBYDtItoBPQ_4wjpg9Br7tT_Euk1QrA6IA5gOY">
> 
> Please provide more detailed reproduction step otherwise we cannot do much to test our theories.

I no longer have this problem because I now use [DataContractSerializer](https://github.com/jumoog/intro-skipper/commit/ef1e3f59c796cd391fa168541bd7331da19ef17a).

But I reported the problem because it may affect others.

**Comment by gnattu** [comment]
> I no longer have this problem because I now use [DataContractSerializer](https://github.com/jumoog/intro-skipper/commit/ef1e3f59c796cd391fa168541bd7331da19ef17a).
> 
> But I reported the problem because it may affect others.

We will need a reproducible example to test our theory and fix things.

I tried to mimic the xml behavior in a newly created plugin but it does not raise the exception for me.

**Comment by gnattu** [comment]
Alright, just reproduced successfully with your migration reverted.

I'm going to post a potential fix for discussion.

**Comment by jumoog** [comment]
maybe this PR isn't needed anymore since nobody else had this problem
