### ISSUE TITLE
[Issue]: 8 Empty Collections "Collections".."Collections8"

### ISSUE THREAD

**Issue by Explosion-Scratch** [jellyfin/jellyfin#11258]
### Please describe your bug

I just set up Jellyfin and it keeps creating 8 collections:

<img width="1152" alt="image" src="https://github.com/jellyfin/jellyfin/assets/61319150/316e3a9a-3416-4acc-b10b-f2f5d3b1405e">

I can delete these but then they Re-appear. Auto create collections is off for both my Movies and Music libraries.

### Reproduction Steps

Go to dashboard

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Ubuntu 22
- Linux Kernel: aarch64 Linux 5.10.160-legacy-rk35xx
- Virtualization: Docker
- Clients: Browser (probably all the others)
- Browser: Chrome 120
- FFmpeg Version: 6.0.1-1+git20240229.99d938d6~jammy
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: Rockchip GPU on Orange PI 5B
- Plugins: Default plugins
- Reverse Proxy: Cloudflare tunnels
- Base URL: https://jf.[MY_DOMAIN]/
- Networking: ??
- Storage: lots
```

### Jellyfin logs

Sometimes I get error refreshing item but nothing collections related it seems:
```shell
[2024-03-29 02:02:59.793 +00:00] [ERR] [50] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist' (5e6effafcbd46ccf500c0bf0d78b5965) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass67_0.<<RefreshAllMetadataForContainer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

### FFmpeg logs

N/A

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

See above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Explosion-Scratch** [comment]
@jellyfin-bot I edited it 🥺

**Comment by sebastianpc** [comment]
I am having the same issue, except with about 500 collections.

```Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Series' (4214d73d98ca02d08d08754a591c730b) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Series' (ac89b023c89dccb24115f12e5c5e11cb) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Folder' (67c71f7f1f66d8200b5460fc3ff68708) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Folder' (67c71f7f1f66d8200b5460fc3ff68708) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Folder' (67c71f7f1f66d8200b5460fc3ff68708) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'Series' (ac89b023c89dccb24115f12e5c5e11cb) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: [18:43:12] [ERR] Error refreshing folder
Apr 04 18:43:12 HOSTNAME jellyfin[382017]: System.InvalidOperationException: Cannot update refresh progress of item 'AggregateFolder' (f27caa37e5142225cceded48f6553502) because a refresh for this item is not running
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Apr 04 18:43:12 HOSTNAME jellyfin[382017]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_2.<ValidateChildrenInternal2>b__1(Double innerPercent)```

Folders get deleted, and when the folders doesn't exist, a library scan fails.

**Comment by sebastianpc** [comment]
When I try to delete it from the Libraries page, I get the following error.

The folder exists when clicking the "Confirm" button, but the error below still appears

```
[19:00:36] [ERR] Error refreshing owned items for /var/lib/jellyfin/root/default/Collections360
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/Collections360'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFol>
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[19:00:36] [ERR] Error processing request: Could not find a part of the path '/var/lib/jellyfin/root/default/Collections360'. URL DELETE /Library/VirtualFolders.
```

**Comment by Shadowghost** [comment]
@sebastianpc that issue should be fixed with https://github.com/jellyfin/jellyfin/pull/11286

**Comment by sebastianpc** [comment]
I have gotten a weird state where the collections  exists on the front page, but not in the admin panel

**Comment by gnattu** [comment]
Then it related code might need the same treatment in #11352 then.

**Comment by sebastianpc** [comment]
It might be the same.
The delete request is also sent to VirtualFolder.

I just updated my jellyfin, but it seems the latest in the repos were built 4 days ago, and it appears that the fix was only merged in yesterday.

I'll take a look if its fixed next unstable build

**Comment by joshuaboniface** [comment]
Reproducing this on 10.9.0 build version 2024042215.
![Screenshot from 2024-04-24 20-08-55](https://github.com/jellyfin/jellyfin/assets/4031396/b80b5106-1263-412c-8b55-d1799c31192a)

**Comment by joshuaboniface** [comment]
Confirmed replication with a different path too. The `/var/lib/jellyfin/data/collections` folder is created, with proper perms, but is empty.

**Comment by joshuaboniface** [comment]
Worth noting I'm seeing a lot of this sort of thing too, both for playlist and collections folders:

```
Apr 24 22:53:31 jf2.p..net jellyfin[410737]: [22:53:31] [WRN] [22] MediaBrowser.Controller.Entities.BaseItem: Library folder /srv/jellyfin/data/playlists is inaccessible or empty, skipping
Apr 24 22:53:31 jf2.p..net jellyfin[410737]: [22:53:31] [WRN] [22] MediaBrowser.Controller.Entities.BaseItem: Library folder /srv/jellyfin/data/playlists is inaccessible or empty, skipping
```

Given the paths and such, might be related.

**Comment by joshuaboniface** [comment]
Another thing that might be related that's flooding the logs:

```
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: [23:02:40] [DBG] [28] Jellyfin.Drawing.ImageProcessor: Getting image size for item Person /srv/jellyfin/metadata/People/J/Jerry Bruckheimer/poster.jpg
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: [23:02:40] [ERR] [28] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /srv/jellyfin/metadata/People/J/Jerry Bruckheimer/poster.jpg
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: System.IO.FileNotFoundException: File not found
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: File name: '/srv/jellyfin/metadata/People/J/Jerry Bruckheimer/poster.jpg'
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(String path)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: [23:02:40] [DBG] [28] Jellyfin.Drawing.ImageProcessor: Getting image size for item Person /srv/jellyfin/metadata/People/D/Don Simpson/poster.jpg
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: [23:02:40] [ERR] [28] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /srv/jellyfin/metadata/People/D/Don Simpson/poster.jpg
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: System.IO.FileNotFoundException: File not found
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]: File name: '/srv/jellyfin/metadata/People/D/Don Simpson/poster.jpg' 
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(String path)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
Apr 24 23:02:40 jf2.p.bonilan.net jellyfin[412241]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

I have a hunch that all of these "file not found" errors are related; somehow some path is getting constructed incorrectly or something perhaps?
