### ISSUE TITLE
[Issue]: Unable to reliably remove Libraries

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin#11269]
### Please describe your bug

Library is still accessible and show on homepage, in the access control after removal of the Library

### Reproduction Steps

- Add a Show Library

- Add another Show Library

- Delete one of them

- Both libraries still show on homepage, still show "Latest In" sections, are still accessible, etc - but they do not show in the library admin page.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Everywhere
- Linux Kernel: Everywhere
- Virtualization: Everywhere
- Clients: Everywhere
- Browser: Everywhere
- FFmpeg Version: Not used
- Playback Method: Not used
- Hardware Acceleration: Not used
- GPU Model: Not used
- Plugins: Not used
- Reverse Proxy: Not used
- Base URL: Not used
- Networking: Localhost
- Storage: Local
```

### Jellyfin logs

```shell
[ERR] [40] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /Users/gnattu/Library/Application Support/jellyfin/root/default/Shows
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/gnattu/Library/Application Support/jellyfin/root/default/Shows'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive) in /Users/gnattu/src/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 593
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/Providers/DirectoryService.cs:line 28
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/Providers/DirectoryService.cs:line 28
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/IO/FileData.cs:line 42
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/Entities/CollectionFolder.cs:line 297
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/Entities/CollectionFolder.cs:line 183
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken) in /Users/gnattu/src/jellyfin/MediaBrowser.Controller/Entities/BaseItem.cs:line 1269
[ERR] [40] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/Users/gnattu/Library/Application Support/jellyfin/root/default/Shows'. URL DELETE /Library/VirtualFolders.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Is this the same or possibly related to #11258 ?

**Comment by gnattu** [comment]
It looks different problems to me. The Libraries are manually added and not auto created.

**Comment by nyanmisaka** [comment]
They are related. I was about to report them.
When you fail to remove a library and try to add a new one, repeatedly clicking the "Confirm" button will cause #11258.

**Comment by gnattu** [comment]
I think #11258 is about collection and not libraries? Duplicated libraries seems to be another issue.

**Comment by nyanmisaka** [comment]
At least from the pictures they are very similar.
In the error I mentioned you will get: Movies1, Movies2, Movies3, Movies4, Movies5...

**Comment by gnattu** [comment]
I got that as well but it is only created when I manually click on buttons, but in that issue OP said they are created automatically

**Comment by gnattu** [comment]
I found the cause of this issue:

https://github.com/cvium/jellyfin/blob/5e414478f2f9b42fa194126b876b639a5a0e9d48/MediaBrowser.Controller/Entities/Folder.cs#L426

In #9291, we explicitly mark the root folders are not remove able, but during the removal of the library virtual folder, we will rely this to validate if the root-folder's children are valid, and then remove all invalid entries.

By removing the `!isRoot` check the library can be removed successfully. But I don't know if there is any side effect of this yet, and I plan to add a new option specifically for UserRootFolder to validate its children.
