### ISSUE TITLE
[Issue]: The version of the native libSkiaSharp library (115.0)  is incompatible with this version of SkiaSharp

### ISSUE THREAD

**Issue by Mr-Chimp** [jellyfin/jellyfin#11346]
### Please describe your bug

I get this error when I start Jellyfin: 
`---> System.InvalidOperationException: The version of the native libSkiaSharp library (115.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).`

I am running Jellyfin on Rocky Linux 9.3 (using the generic linux files) and I manually built SkiaSharp from their git (I used these [instructions](https://github.com/mono/SkiaSharp/wiki/Building-on-Linux) in case it is relevant) 

Does that error mean that Jellyfin needs a version of SkiaSharp that is between the ranges given and the version I built is 115 or is it the other way around? 

Typically I would try and faff about with Skia until it works but the versions given in the error don't match with what I built so I was a bit confused.

Thank you

### Reproduction Steps

Install Jellyfin using 'Generic Linux' installation method
Build  SkiaSharp and copy to Jellyfin path
Start Jellyfin and watch the output

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Rocky Linux 9.3
- Linux Kernel: Linux 5.14.0-362.24.1.el9_3.x86_64 x86_64
- Virtualization: KVM
- Clients:Browser
- Browser: Brave
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method:
- Hardware Acceleration: none
- GPU Model: none
- Plugins: AniDB
- Reverse Proxy: none 
- Base URL: none
- Networking: Bridge/NAT
- Storage: NFS
```

### Jellyfin logs

```shell
[19:40:57] [ERR] [13] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for /media/storage/anime/<show_name_season_here>-thumb.jpg
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (115.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStream..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamRewindable..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamSeekable..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamAsset..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at SkiaSharp.SKCodec.Create(String filename, SKCodecResult& result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> Does that error mean that Jellyfin needs a version of SkiaSharp that is between the ranges given and the version I built is 115 

Yes

> Typically I would try and faff about with Skia until it works but the versions given in the error don't match with what I built so I was a bit confused.

The native Skia has its own version, which comes bundled with the library. The "m115" and "m88" are version numbers from Google's Skia so they will be different from the SkiaSharp's version number. It appears that you built a very new version (master branch) that is too new for us, and you will need to build one from the 2.8x release branch.

But why you are replacing the skia yourself anyway? A supported latest libskia should already be included in the portable package.

**Comment by Mr-Chimp** [comment]
Thank you for clarifying, that will help me a lot.

As for why, on start-up I was getting an error about Skia not being available and defaulting to NullImageEncoder (or something like that) so I thought I would try and solve the issue.

Thanks again
