### ISSUE TITLE
[Issue]: Not creating Seasons/Episodes during Scan

### ISSUE THREAD

**Issue by derterboy** [jellyfin/jellyfin#11345]
### Please describe your bug

JellyFin is not creating Seasons and Episodes for some TVShows

Folder structure:
/TVShows/ One Piece (1999) [tvdbid-81797]/Season 1/S01E07.mkv

The Show is created with correct metadata, but it is empty and marked as watched.

When I put the problematic TVShow into a different folder /TVShows2 without any other TVShows in it it gets scanned correctly.

I was not able to find any info in the logs so I am quite clueless how to resolve this issue.
I also did a complete reinstall, tried to use tvdb or tmdb. So this is not a metadata provider problem.

### Reproduction Steps

Only reproducable with same fuse mount. But does not work on severel different JellyFIn installs.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 22
- Linux Kernel: 5.15.0-100-generic
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Fuse Mount
```

### Jellyfin logs

```shell
Logs can be given but there is nothing showing this problem
```

### Please attach any screenshots here

![onepiece](https://github.com/jellyfin/jellyfin/assets/107677387/5bcc8cfc-a9a8-47be-a766-932017599a03)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derterboy** [comment]
I tried it with JellyFin 10.9.0 and the logs give this error:

System.InvalidOperationException: Cannot update refresh progress of item 'Serien' (c671dc069b0d04a327b1e0b6df26a0a1) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_1.<ValidateChildrenInternal2>b__0(Double innerPercent)
