### ISSUE TITLE
[bug]:  Collection is not created

### ISSUE THREAD

**Issue by HolgerKuehn** [jellyfin/jellyfin#11385]
### Please describe your bug

When trying to create a collection a folder "collection" is created and the GUI is showing spinning wheel, but freezes. Restarting the app and trying to  create a new collection creates a new folder "collection2", same result in GUI. 

https://forum.jellyfin.org/t-10-9-0-collection-are-not-created?pid=20906#pid20906

### Reproduction Steps

1. extract jellyfin_2024041505-amd64.zip to Programfolder
2. run with new datadir "C:\Program Files\Jellyfin\Server.10.9\jellyfin.exe" --service --datadir "D:\JellyfinData"
3. add movie library
4. restart
5. add collection via Movies / Collections / New Collection

### Jellyfin Version

10.9.0

### if other:

jellyfin_2024041505-amd64.zip

### Environment

```markdown
- OS: Windows 11 Pro, 22H2, build 22621.3447
- Virtualization: no
- Clients: Jellyfin Media Player 1.9.1
- FFmpeg Version: default
- Playback Method: no playback
- Hardware Acceleration: no playback
- GPU Model: Iris Xe Graphics (Intel Core I7-1165G7 11th Gen.)
- Plugins: none
- Reverse Proxy: Apache 2.4.58
- Base URL: http://jellyfin.domain.tld
- Networking: local
- Storage: NAS/rclone with local link
```

### Jellyfin logs

```shell
for log see post on forum
https://my.hidrive.com/lnk/OZBhCibCU

Posting here gives: 

There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Does the folder `D:\JellyfinData\data\collections` exist, and are there any files in it?

**Comment by HolgerKuehn** [comment]
> Does the folder `D:\JellyfinData\data\collections` exist, and are there any files or folders in it?

Sorry for the late reply. After scanning the Media, it does not exist.

The folder is created when trying to add the first collection, but stays empty.

If I try it a second time, a new folder "collection2" is created, but stays empty as well.

**Comment by TimGels** [comment]
While doing a routine check of latest master, I encountered this issue as well. I am running Jellyfin server directly from Visual Studio. Creating collections in 10.9.0 (master as of writing) is broken for me. After a page refresh the UI shows the collections, but empty.
```
[15:58:36] [ERR] [49] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Collections.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Collections.CollectionManager.EnsureLibraryFolder(String path, Boolean createIfNeeded) in C:\Users\Tim\source\repos\jellyfin\Emby.Server.Implementations\Collections\CollectionManager.cs:line 107
   at Emby.Server.Implementations.Collections.CollectionManager.CreateCollectionAsync(CollectionCreationOptions options) in C:\Users\Tim\source\repos\jellyfin\Emby.Server.Implementations\Collections\CollectionManager.cs:line 140
   at Jellyfin.Api.Controllers.CollectionController.CreateCollection(String name, String[] ids, Nullable`1 parentId, Boolean isLocked) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Controllers\CollectionController.cs:line 59
   at lambda_method1462(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\ServerStartupMessageMiddleware.cs:line 41
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\WebSocketHandlerMiddleware.cs:line 33
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\IpBasedAccessValidationMiddleware.cs:line 36
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\LanFilteringMiddleware.cs:line 37
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\QueryStringDecodingMiddleware.cs:line 36
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\RobotsRedirectionMiddleware.cs:line 43
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\LegacyEmbyRouteRewriteMiddleware.cs:line 51
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\ResponseTimeMiddleware.cs:line 66
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in C:\Users\Tim\source\repos\jellyfin\Jellyfin.Api\Middleware\ExceptionMiddleware.cs:line 55
```
![image](https://github.com/jellyfin/jellyfin/assets/43609220/7cbf793e-3239-4c4e-aa2e-77bfc91a9c79)
![image](https://github.com/jellyfin/jellyfin/assets/43609220/cc794b16-292d-4c70-9280-77706afbe5c4)
