### ISSUE TITLE
[Issue]: 10.9 SQLite Error 5: 'database is locked'.

### ISSUE THREAD

**Issue by gitdeath** [jellyfin/jellyfin#11387]
### Please describe your bug

Library Scans fail.

I've copied my 10.8.13 docker config with new volumes and pointing to '2024041505' instead of 'latest', I copied my swag setup changing to jellyfin-dev, instead of jellyfin.

I did a clean install for this test using the same storage devices, docker nodes, reverse proxy, etc. as 10.8.13 is running currently.

Physically and logically (except the name, and the folder of the volumes) everything is the same. 

### Reproduction Steps

1. Start 10.9 Jellyfin Docker container (fresh database)
2. Add libraries 
3. Run Scan All

### Jellyfin Version

Unstable (master branch)

### if other:

10.9 - 2024041505

### Environment

```markdown
- OS:
- Linux Kernel: Linux transcode-worker2 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: Swag
- Base URL: N/A
- Networking: Bridge
- Storage: NFS
```

### Jellyfin logs

```shell
[2024-04-18 16:02:45.977 -05:00] [ERR] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-04-18 16:02:45.978 -05:00] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 56 seconds
[2024-04-18 16:02:46.021 -05:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies4k"
[2024-04-18 16:02:46.068 -05:00] [INF] [69] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/homevideo"
[2024-04-18 16:02:46.989 -05:00] [INF] [46] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies"
[2024-04-18 16:02:48.969 -05:00] [INF] [65] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/tvshows"
[2024-04-18 16:03:17.577 -05:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/movies"
[2024-04-18 16:03:17.583 -05:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/tvshows"
[2024-04-18 16:03:17.586 -05:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/homevideo"
[2024-04-18 16:03:17.586 -05:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/movies4k"
[2024-04-18 16:03:17.586 -05:00] [INF] [55] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-04-18 16:03:17.680 -05:00] [WRN] [55] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-04-18 16:03:17.742 -05:00] [WRN] [46] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-04-18 16:04:25.385 -05:00] [ERR] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-04-18 16:04:25.394 -05:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 1 minute(s) and 7 seconds
[2024-04-18 16:04:25.484 -05:00] [INF] [20] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies4k"
[2024-04-18 16:04:25.522 -05:00] [INF] [3] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/homevideo"
[2024-04-18 16:04:27.389 -05:00] [INF] [36] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies"
[2024-04-18 16:04:28.735 -05:00] [INF] [57] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/tvshows"
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/59674699/aa2a44e1-4ec3-44b6-8d49-c2ddb7e2b79d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Could you please post your config file?

**Comment by gitdeath** [comment]
> Could you please post your config file?

Happy to post whatever is needed, however I'm not sure what you are after here. Are you looking for one or more of the .xml files in the config directory?

**Comment by JPVenson** [comment]
There are really only two reasons for this particular exception to happen:
1. Two or more Jellyfin instances try to access the same database at the same time
2. You configured your jellyfin instance to read the database over a network share

Thats what i wanted to verify

**Comment by gitdeath** [comment]
I'm 100% using NFS.. But, as I've said 10.8.x has worked for years in the exact same setup with no issues at all - this is because the real issue with sqlite over NFS with lock disabled is multiple access which I do not do. Did something change with 10.9 db access that is known to cause issue?

**Comment by JPVenson** [comment]
SqLite, the whole concept is not supposed to be accessed over a network share. We also warn against that in our docs same goes for the official sqlite one, why it worked for all that time is my guess, it should never had to. 
However i am sory this was never supported or is within our hands.

**Comment by KoffeinKaio** [comment]
any plans to support another database format?

IMHO storing eveything jelly has in a network filesystem is a valid usecase

**Comment by JPVenson** [comment]
@KoffeinKaio I agree that its not optimal. We are currently reworking our data access layer step by step, as soon as that is finished we will be able to support other relational database systems like pgsql or mysql. However there is still quite a lot of work to do until we are there.

**Comment by gitdeath** [comment]
> @JPVenson
> 
> Im having alot off issues errors such as "Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked' " as well as "Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database is locked'".
> 
> My media is on a network storage, but my cache and database is on the machine that's running the jellyfin server (win 10 with lots of cores and 2 gpus).
> 
> Is the locking of the database because of the network storage, or would it be something else entirely? Im just about to put in an issue/bugreport with a few logs to see if we can capture the problem, but just want to know if it is something as simple as you can't use a nas for media because of how sqlite reacts to a network drive?
> 
> :)

My database lock crashing with the setup you've describe has reduced a lot with 10.9.2 coupled with setting the below values to 1 in General Settings of the Admin Dashboard.

![image](https://github.com/jellyfin/jellyfin/assets/59674699/87d15e7c-c36d-4818-bbbe-e1eb86eb3721)

**Comment by nothing2obvi** [comment]
@JPVenson This issue is occurring for me on 10.9.3 and I'm not using a network share. I've seen many other issues around here with the same or similar problems since 10.9.0, either `SQLite Error 5` or `SQLite Error 6`.

- #11589 
- #11839
- #11834 
- #11728 
- #11813 

Changing the parallel library scan and parallel image encoding limits did not work for me.

**Comment by gitdeath** [comment]
https://github.com/jellyfin/jellyfin/pull/10138

**Comment by mountainbiker54** [comment]
I have the same issue. All files stored on the local machine (windows server 2022std). It seems to only crash the service when the plugin "Merge Versions" runs  @its process. I changed the schedule so it happens in the middle of the morning and set windows to automatically recover the service and restart it after it crashes.

**Comment by JPVenson** [comment]
I advice everyone with that issue to first contact the community for support in our matrix channel. As mountainbiker54 already mentioned we have seen deprecated plugins causing this. 

However, this particular bug report is about accessing sqlite over a network share which is plain not supported by the underlying technology. If your setup does __not__ access the database over a network share and it happens without plugins, please open a new Bug report.

**Comment by gitdeath** [comment]
10.9.6 appears to have fixed this use case. I'll leave it run in development environment for a few days and report back. 

https://github.com/jellyfin/jellyfin/pull/11986

**Comment by gitdeath** [comment]
> 10.9.6 appears to have fixed this use case. I'll leave it run in development environment for a few days and report back.
> 
> #11986

Update:
- NFSv3 config mount with the 'nolock' option is back to functioning post fix applied in #11986 (10.9.6 release.)

**Comment by KoffeinKaio** [comment]
> > 10.9.6 appears to have fixed this use case. I'll leave it run in development environment for a few days and report back.
> > #11986
> 
> Update:
> 
> * NFSv3 config mount with the 'nolock' option is back to functioning post fix applied in [Use only 1 write connection/DB #11986](https://github.com/jellyfin/jellyfin/pull/11986) (10.9.6 release.)

Doesnt work for me in NFSv4

```
jellyfin  | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
jellyfin  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
jellyfin  |    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
jellyfin  |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
jellyfin  |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin  |    at Jellyfin.Server.Program.<Main>(String[] args)
```
But hey, at least the error is a diffrent one now. Welp. Back to localstorage

**Comment by gitdeath** [comment]
> > > 10.9.6 appears to have fixed this use case. I'll leave it run in development environment for a few days and report back.
> > > #11986
> > 
> > 
> > Update:
> > 
> > * NFSv3 config mount with the 'nolock' option is back to functioning post fix applied in [Use only 1 write connection/DB #11986](https://github.com/jellyfin/jellyfin/pull/11986) (10.9.6 release.)
> 
> Doesnt work for me in NFSv4
> 
> ```
> jellyfin  | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
> jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
> jellyfin  |    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
> jellyfin  | --- End of stack trace from previous location ---
> jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
> jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
> jellyfin  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
> jellyfin  |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
> jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
> jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
> jellyfin  |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
> jellyfin  |    at Jellyfin.Server.Program.<Main>(String[] args)
> ```
> 
> But hey, at least the error is a diffrent one now. Welp. Back to localstorage

For anyone coming across this NFSv4 never worked properly. This is because NFS locking isn't compatible with SQLite and the `nolock` attribute on NFSv4 doesn't exist (https://linux.die.net/man/5/nfs). If you need to use remote storage for the database, then it has to be NFSv3 with the `nolock` mount attribute. 

Multiple write, which was removed by 11986, is not recommended for SQLite - the delay introduced by network storage or slow systems was causing the database locked for these multiple writes.

**Comment by DieserCoookie** [comment]
Ok, so you mentioned NFSv4 doesnt work and NFSv3 does, how does one swap to that? 

I put all my files onto my Linux server over the network and get a lot of malformed errors, so i'd really appreciate an answer^^

**Comment by gitdeath** [comment]
> Ok, so you mentioned NFSv4 doesnt work and NFSv3 does, how does one swap to that?
> 
> I put all my files onto my Linux server over the network and get a lot of malformed errors, so i'd really appreciate an answer^^

However you are establishing the nfs mount use the options of `nfsvers=3` and `nolock`.

Standard fstab scenario would follow the below format where `nfsvers=3` and `nolock` would both be found in the options list:
`server:path   /mountpoint   fstype   option,option,...   0 0`

Man page for nfs fstab:
**https://manpages.ubuntu.com/manpages/focal/en/man5/nfs.5.html**
