### ISSUE TITLE
[Issue]: Arbitrary restart after Unhandled Exception

### ISSUE THREAD

**Issue by pendletong** [jellyfin/jellyfin#11417]
### Please describe your bug

After adding a new version of an existing film the scan completed (I believe) but some short time thereafter the server (and docker container) restarted due to a fatal exception

2024-04-23 08:39:44 [07:39:44] [FTL] [36] Main: Unhandled Exception
2024-04-23 08:39:44 System.NullReferenceException: Object reference not set to an instance of an object.

### Reproduction Steps

The only precursor to the restart appears to be the copying of the version file into an existing film folder but this happened almost 15 minutes before the restart

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: MacOS
- Linux Kernel:
- Virtualization: Docker image jellyfin/jellyfin
- Clients: Browser
- Browser: Arc browser on Mac OS
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: None
- GPU Model: None
- Plugins: AudioDB, MusicBrainz, OMDb, Reports, Images, TMDb
- Reverse Proxy: None
- Base URL: web/index.html
- Networking: Bridge (I think)
- Storage: Local
```

### Jellyfin logs

```shell
2024-04-23 08:23:13 [07:23:13] [INF] [43] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
2024-04-23 08:23:21 [07:23:21] [WRN] [43] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/c54ae5d343a18f161ccf0e0cceca7987 to 192.168.65.1 in 0:00:00.7231079 with Status Code 200
2024-04-23 08:23:25 [07:23:25] [INF] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
2024-04-23 08:23:37 [07:23:37] [INF] [53] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
2024-04-23 08:24:57 [07:24:57] [INF] [51] Emby.Server.Implementations.IO.LibraryMonitor: Owned (/media/movies/Owned) will be refreshed.
2024-04-23 08:26:09 [07:26:09] [INF] [51] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Following, Path: /media/movies/Owned/Following (1998)/Following (1998) - Restructured.mkv, Id: 8bd1ee2d-6d04-b984-3a52-7bd78098ec3e
2024-04-23 08:35:49 [07:35:49] [INF] [32] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
2024-04-23 08:36:01 [07:36:01] [INF] [78] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
2024-04-23 08:39:44 [07:39:44] [INF] [66] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.65.1 closed
2024-04-23 08:39:44 [07:39:44] [INF] [55] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.65.1 closed
2024-04-23 08:39:44 [07:39:44] [FTL] [36] Main: Unhandled Exception
2024-04-23 08:39:44 System.NullReferenceException: Object reference not set to an instance of an object.
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
2024-04-23 08:39:44    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__57_0(ISessionController i)
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
2024-04-23 08:39:44    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.Execute()
2024-04-23 08:39:44    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-23 08:39:44    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-23 08:39:44 [07:39:44] [FTL] [50] Main: Unhandled Exception
2024-04-23 08:39:44 System.NullReferenceException: Object reference not set to an instance of an object.
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
2024-04-23 08:39:44    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__57_0(ISessionController i)
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
2024-04-23 08:39:44    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.Execute()
2024-04-23 08:39:44    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-23 08:39:44    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Jellyfin version: 10.8.13
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_PublishedServerUrl, 192.168.68.113]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]"]
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Operating system: Linux
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Architecture: Arm64
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: 64-Bit Process: True
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: User Interactive: True
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Processor count: 8
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Program data path: /config
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
2024-04-23 08:39:45 [07:39:45] [INF] [1] Main: Application directory: /jellyfin/
2024-04-23 08:39:46 [07:39:46] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-04-23 08:39:46 [07:39:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
2024-04-23 08:39:46 [07:39:46] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Reports_15.0.0.0/Jellyfin.Plugin.Reports.dll
2024-04-23 08:39:46 [07:39:46] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2024-04-23 08:39:46 [07:39:46] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
2024-04-23 08:39:46 [07:39:46] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2024-04-23 08:39:46 [07:39:46] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
2024-04-23 08:39:46 [07:39:46] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 15.0.0.0
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.13.0
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.13.0
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.13.0
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.13.0
2024-04-23 08:40:16 [07:40:16] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.13.0
2024-04-23 08:40:17 [07:40:17] [INF] [1] Main: Kestrel listening on Any IP4 Address
2024-04-23 08:40:17 [07:40:17] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2024-04-23 08:40:17 [07:40:17] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2024-04-23 08:40:17 [07:40:17] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {56250619-ed5c-4570-9e9d-61a9fb29183d} may be persisted to storage in unencrypted form.
2024-04-23 08:40:17 [07:40:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
2024-04-23 08:40:17 [07:40:17] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2024-04-24 02:00:00.000 +00:00, which is 18:19:42.2565382 from now.
2024-04-23 08:40:17 [07:40:17] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 6.0.1
2024-04-23 08:40:17 [07:40:17] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "h264", "hevc", "mpeg2video", "mpeg4", "msmpeg4", "vp8", "libvpx", "vp9", "libvpx-vp9", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
2024-04-23 08:40:18 [07:40:18] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_v4l2m2m", "libx265", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
2024-04-23 08:40:18 [07:40:18] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["overlay_opencl", "scale_opencl", "tonemap_opencl", "zscale", "alphasrc"]
2024-04-23 08:40:18 [07:40:18] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: scale_cuda with option Output format (default "same") is not available
2024-04-23 08:40:18 [07:40:18] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: tonemap_cuda with option GPU accelerated HDR to SDR tonemapping is not available
2024-04-23 08:40:18 [07:40:18] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: overlay_vaapi with option Action to take when encountering EOF from secondary input is not available
2024-04-23 08:40:18 [07:40:18] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["drm", "opencl", "rkmpp"]
2024-04-23 08:40:18 [07:40:18] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
2024-04-23 08:40:18 [07:40:18] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 4e008e6038484ec4a04cc4256e6918ab
2024-04-23 08:40:18 [07:40:18] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0897327
2024-04-23 08:39:44 Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
2024-04-23 08:39:44    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__57_0(ISessionController i)
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
2024-04-23 08:39:44    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.Execute()
2024-04-23 08:39:44    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-23 08:39:44    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-23 08:39:44 Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
2024-04-23 08:39:44    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__57_0(ISessionController i)
2024-04-23 08:39:44    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
2024-04-23 08:39:44    at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
2024-04-23 08:39:44    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2024-04-23 08:39:44    at System.Threading.QueueUserWorkItemCallback.Execute()
2024-04-23 08:39:44    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-04-23 08:39:44    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-04-23 08:40:18 [07:40:18] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
2024-04-23 08:40:19 [07:40:19] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:01.3740526
2024-04-23 08:40:19 [07:40:19] [INF] [1] Main: Startup complete 0:00:34.2970862
2024-04-23 08:40:21 [07:40:21] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
2024-04-23 08:40:21 [07:40:21] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
2024-04-23 08:40:21 [07:40:21] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
2024-04-23 08:40:23 [07:40:23] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/other/Music Video
2024-04-23 08:40:24 [07:40:24] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 3 seconds
2024-04-23 08:40:24 [07:40:24] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
2024-04-23 08:40:25 [07:40:25] [WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Sessions/Playing/Progress to 192.168.65.1 in 0:00:00.8286002 with Status Code 204
2024-04-23 08:40:34 [07:40:34] [INF] [27] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.65.1 request
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024-04-23 08:40:34 [07:40:34] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/tv/Upgraded
2024-04-23 08:40:35 [07:40:35] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio to 192.168.65.1 in 0:00:01.0548202 with Status Code 200
2024-04-23 08:40:46 [07:40:46] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/movies3/Upgraded
2024-04-23 08:40:49 [07:40:49] [WRN] [31] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Sessions/Playing/Progress to 192.168.65.1 in 0:00:11.6547988 with Status Code 204
2024-04-23 08:40:50 [07:40:50] [WRN] [32] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Sessions/Playing/Progress to 192.168.65.1 in 0:00:05.0512903 with Status Code 204
2024-04-23 08:40:50 [07:40:50] [WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 to 192.168.65.1 in 0:00:14.4993393 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [27] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video to 192.168.65.1 in 0:00:15.3675335 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [30] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=e2c00f297a5f80af390f52f72e782147 to 192.168.65.1 in 0:00:13.5369423 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [11] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=4514ec850e5ad0c47b58444e17b6346c to 192.168.65.1 in 0:00:12.0305816 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [25] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Users/6218d248bcfc41b2b22551c4629c6f8e/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=7e64e319657a9516ec78490da03edccb to 192.168.65.1 in 0:00:15.697436 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [25] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Items/bc90b322576d4908b875e68e708daac3/Images/Primary?fillHeight=652&fillWidth=434&quality=96&tag=abd9a694186f751c0839c655fc93161f to 192.168.65.1 in 0:00:00.5065365 with Status Code 200
2024-04-23 08:40:50 [07:40:50] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://plex.local:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=6218d248bcfc41b2b22551c4629c6f8e&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-04-24T07%3A40%3A34.794Z&EnableRewatching=false to 192.168.65.1 in 0:00:15.04958 with Status Code 200
2024-04-23 08:41:00 [07:41:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/other/TV
2024-04-23 08:41:04 [07:41:04] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/movies2/Downloaded
2024-04-23 08:41:13 [07:41:13] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/movies2/Upgraded
2024-04-23 08:41:14 [07:41:14] [INF] [22] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/other/Music
2024-04-23 08:41:17 [07:41:17] [INF] [23] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/tv/Downloaded
2024-04-23 08:41:24 [07:41:24] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/other/Film
2024-04-23 08:41:28 [07:41:28] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/movies3/Owned
2024-04-23 08:41:32 [07:41:32] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/tv/Owned
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
We have improved those exception handling in master, can you try the unstable image to see if it still happens?

**Comment by pendletong** [comment]
OK, I'll run that for now and see whether I get any further exceptions

**Comment by TimGels** [comment]
@pendletong have you noticed this issue again after upgrading to 10.9?

**Comment by PeachesMLG** [comment]
Im also getting this error. I cant replicate it, however it seemed to occur when I updated my server from 10.9.2 -> 10.9.3 (Although im not sure if this is related or not)

Logs attached below (Although its nothing particuarly interesting
[Jellyfin.log](https://github.com/jellyfin/jellyfin/files/15461364/Jellyfin.log)
)

**Comment by Simsala91** [comment]
Had the same error yesterday, running on 10.9.3 as well.

``` 
[2024-06-05 01:09:03.576 +02:00] [INF] [59] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.1" closed
[2024-06-05 01:09:03.576 +02:00] [INF] [84] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.1" closed
[2024-06-05 01:09:03.589 +02:00] [FTL] [79] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__52_0(ISessionController i)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2024-06-05 01:09:03.589 +02:00] [FTL] [32] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__52_0(ISessionController i)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by pendletong** [comment]
Sorry for the delay in getting back to everyone. I changed my docker image to alway be the latest for the past couple of months and I can say that I have not seen the above issue happen since switching to latest.

**Comment by felix920506** [comment]
Fixed as far as the comments report, closing
