### ISSUE TITLE
[Issue]: Genres in music not scanned

### ISSUE THREAD

**Issue by Trenobol** [jellyfin/jellyfin#11425]
### Please describe your bug

Hi!
Genres in music stopped being scanned and displayed (genres section) I tried reinstalling docker several times

Before that, everything was fine, the tags were placed correctly

### Reproduction Steps

1. Reinstall

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Unraid 6.11.5
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: Waterfox/Centbrowser
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-04-24 17:01:03.386 +03:00] [INF] [4] Main: Jellyfin version: "10.8.13"
[2024-04-24 17:01:03.401 +03:00] [INF] [4] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]"]
[2024-04-24 17:01:03.403 +03:00] [INF] [4] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Operating system: "Linux"
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Architecture: X64
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: 64-Bit Process: True
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: User Interactive: True
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Processor count: 8
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Program data path: "/config"
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Web resources path: "/jellyfin/jellyfin-web"
[2024-04-24 17:01:03.404 +03:00] [INF] [4] Main: Application directory: "/jellyfin/"
[2024-04-24 17:01:03.445 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration"]
[2024-04-24 17:01:03.516 +03:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:01:03.524 +03:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-04-24 17:01:03.585 +03:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-04-24 17:01:03.585 +03:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2024-04-24 17:01:03.585 +03:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-04-24 17:01:03.592 +03:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2024-04-24 17:01:03.592 +03:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2024-04-24 17:01:04.445 +03:00] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[2024-04-24 17:01:04.720 +03:00] [INF] [4] Jellyfin.Server.Implementations.JellyfinDbProvider: EFCore migrations applied successfully
[2024-04-24 17:01:05.033 +03:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:01:05.034 +03:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:01:05.037 +03:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.13.0"
[2024-04-24 17:01:05.038 +03:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.13.0"
[2024-04-24 17:01:05.038 +03:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.13.0"
[2024-04-24 17:01:05.038 +03:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.13.0"
[2024-04-24 17:01:05.038 +03:00] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.13.0"
[2024-04-24 17:01:05.078 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase"]
[2024-04-24 17:01:05.079 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddDefaultPluginRepository"'
[2024-04-24 17:01:05.079 +03:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:01:05.079 +03:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:01:05.079 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddDefaultPluginRepository"' applied successfully
[2024-04-24 17:01:05.087 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"ReaddDefaultPluginRepository"'
[2024-04-24 17:01:05.087 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"ReaddDefaultPluginRepository"' applied successfully
[2024-04-24 17:01:05.088 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddPeopleQueryIndex"'
[2024-04-24 17:01:05.088 +03:00] [INF] [4] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[2024-04-24 17:01:05.091 +03:00] [INF] [4] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_PeopleNameListOrder
[2024-04-24 17:01:05.094 +03:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddPeopleQueryIndex"' applied successfully
[2024-04-24 17:01:05.099 +03:00] [INF] [4] Main: Kestrel listening on "Any IP4 Address"
[2024-04-24 17:01:05.343 +03:00] [WRN] [4] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {73778121-9589-46fc-950d-67964b012231} may be persisted to storage in unencrypted form.
[2024-04-24 17:01:05.360 +03:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-04-24 17:01:05.381 +03:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-04-25 02:00:00.000 +03:00, which is 08:58:54.6190095 from now.
[2024-04-24 17:01:05.538 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.4"
[2024-04-24 17:01:05.577 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-04-24 17:01:05.598 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-04-24 17:01:05.620 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-04-24 17:01:05.750 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-04-24 17:01:05.860 +03:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-04-24 17:01:05.861 +03:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: ServerId: "aa71f1f7c6d149f4a7f727b54dcd0a23"
[2024-04-24 17:01:05.949 +03:00] [INF] [11] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0827657
[2024-04-24 17:01:05.949 +03:00] [INF] [11] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-04-24 17:01:06.064 +03:00] [INF] [11] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1149617
[2024-04-24 17:01:06.064 +03:00] [INF] [11] Main: Startup complete 0:00:02.8157005
[2024-04-24 17:01:08.384 +03:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2024-04-24 17:01:08.385 +03:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2024-04-24 17:01:08.386 +03:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2024-04-24 17:01:33.342 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:01:33.343 +03:00] [WRN] [6] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-04-24 17:02:30.457 +03:00] [INF] [12] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:02:30.459 +03:00] [INF] [12] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:02:30.459 +03:00] [INF] [16] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[2024-04-24 17:02:30.575 +03:00] [WRN] [24] Jellyfin.Server.Implementations.Users.UserManager: No users, creating one with username "root"
[2024-04-24 17:02:48.407 +03:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Обновление плагинов" Cancelled after 1 minute(s) and 40 seconds
[2024-04-24 17:02:48.419 +03:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-04-24 17:03:05.492 +03:00] [INF] [24] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:03:05.493 +03:00] [INF] [24] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:03:08.460 +03:00] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-04-24 17:03:08.460 +03:00] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2024-04-24 17:03:08.460 +03:00] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-04-24 17:03:08.460 +03:00] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2024-04-24 17:03:08.460 +03:00] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2024-04-24 17:03:09.720 +03:00] [INF] [27] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:03:09.721 +03:00] [INF] [27] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-24 17:03:09.722 +03:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "RefreshMediaLibraryTask"
[2024-04-24 17:03:09.722 +03:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Сканирование медиатеки"
[2024-04-24 17:03:09.725 +03:00] [INF] [26] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-04-24 17:03:09.887 +03:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2024-04-24 17:03:09.908 +03:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Сканирование медиатеки" Completed after 0 minute(s) and 0 seconds
[2024-04-24 17:03:09.909 +03:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-04-24 17:03:20.020 +03:00] [INF] [3] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Max" has succeeded.
[2024-04-24 17:03:20.021 +03:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "Max": 0/0
[2024-04-24 17:03:20.057 +03:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user e552589d-e8c8-46ba-9f72-98fa871a0f96
[2024-04-24 17:03:20.252 +03:00] [INF] [12] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.253.0.2" request
[2024-04-24 17:04:16.805 +03:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "RefreshMediaLibraryTask"
[2024-04-24 17:04:16.805 +03:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Сканирование медиатеки"
[2024-04-24 17:04:16.810 +03:00] [INF] [11] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-04-24 17:04:31.830 +03:00] [ERR] [23] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2024-04-24 17:06:11.854 +03:00] [INF] [30] Emby.Server.Implementations.Library.LibraryManager: Post-scan task cancelled: "ArtistsPostScanTask"
[2024-04-24 17:06:11.855 +03:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Сканирование медиатеки" Cancelled after 1 minute(s) and 55 seconds
[2024-04-24 17:06:11.857 +03:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-04-24 17:06:11.895 +03:00] [INF] [37] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/Русское"
[2024-04-24 17:07:05.209 +03:00] [ERR] [14] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/e552589de8c846ba9f7298fa871a0f96/Items/54e0a20c610716b065e59cc27083dab0".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method1078(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-04-24 17:07:25.988 +03:00] [ERR] [39] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/e552589de8c846ba9f7298fa871a0f96/Items/7c983efba6be35f33e1d0f1c602bf9d0".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method1078(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-04-24 17:10:55.389 +03:00] [INF] [42] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-04-24 17:10:55.390 +03:00] [INF] [42] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
```

### Please attach any screenshots here

![1713967535240](https://github.com/jellyfin/jellyfin/assets/118353130/f6a3baac-9aa8-4466-a050-34869b492fd0)
![1713967544548](https://github.com/jellyfin/jellyfin/assets/118353130/3b1e5779-b94a-490f-a06e-95816ea4815a)
![1713967548084](https://github.com/jellyfin/jellyfin/assets/118353130/4d8095c6-2401-439f-ba4f-7266bf7b5002)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SodaWithoutSparkles** [comment]
From my experience, they are scanned, just very slowly. It might take a few hours or even a day. 

This is likely a duplicate issue as I remember commenting on a similar one.

**Comment by Trenobol** [comment]
> From my experience, they are scanned, just very slowly. It might take a few hours or even a day.
> 
> This is likely a duplicate issue as I remember commenting on a similar one.

I have tried to completely delete/add a music library
I tried to create a new clean docker container for music
Anyway, there are no genres at all...

**Comment by felix920506** [comment]
Duplicate of #6036
