### ISSUE TITLE
Help Needed！Some troubles about  .strm

### ISSUE THREAD

**Issue by Akimio521** [jellyfin/jellyfin#11447]
### Please describe your bug

I've been having some trouble with Jellyfin recently that I haven't been able to figure out, so I'm reaching out here for help.

I read in the Jellyfin documentation that it supports files with the ".strm" extension. I put an HTTPS URL link into a .strm file (opening this URL in a browser downloads an MKV video file directly). When I play this .strm file in Jellyfin, I found that the client tries to access the URL address in the .strm file. If the access is successful, the video file is obtained directly from the URL, and all traffic does not go through the Jellyfin server, unless the client cannot access the URL in the .strm file normally or the client requests transcoding.

### Reproduction Steps

after I added multiple .strm files, I found that the client no longer tries to access the URL, but instead the server directly streams the media. This takes up Jellyfin server bandwidth and wastes resources, which I don't want. 

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Synogy DSM7.2
- Linux Kernel:5.15
- Virtualization:docker
- Clients:Browser，iOS
- Browser:Safari
- FFmpeg Version:ffmpeg version 6.0.1-Jellyfin
- Playback Method:direct play，direct stream
- Hardware Acceleration:qsv
- GPU Model:Intel UHD Graphics 16 EUs
- Plugins:none
- Reverse Proxy:none
- Base URL:none
- Networking:bridge
- Storage:cloud
```

### Jellyfin logs

```shell
[2024-04-26 15:47:32.986 +00:00] [WRN] [134] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://my-jellyfin-server.example.com/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=a6a8202baa9f4809a992e045922b55a6&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-04-27T15%3A47%3A28.743Z&EnableRewatching=false" to "192.168.1.1" in 0:00:04.0383719 with Status Code 200
[2024-04-26 15:47:38.913 +00:00] [INF] [135] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 200M -probesize 1G -i \"https://myserver.example.com/d/动漫/A-Z/B/86-不存在的地域-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS&CHT].mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-04-26 15:47:49.823 +00:00] [INF] [128] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" request
[2024-04-26 15:47:52.649 +00:00] [ERR] [193] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-04-26 15:47:52.841 +00:00] [INF] [193] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "akimio". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-04-26 15:47:52.843 +00:00] [INF] [193] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Expo iOS fMP4 Video Profile", Path="https://myserver.example.com/d/动漫/A-Z/B/86-不存在的地域-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS&CHT].mkv", AudioStreamIndex=null, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported ) "media:/videos/e5f1cc84-3224-35ae-d69f-89eea8db8c97/master.m3u8?MediaSourceId=e5f1cc84322435aed69f89eea8db8c97&VideoCodec=hevc,h264&AudioCodec=aac,mp3,flac,alac&VideoBitrate=139808000&AudioBitrate=192000&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=2ed9d040bf7be509b76988eb870578d0&SegmentContainer=mp4&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&hevc-profile=main,main10&hevc-level=183&hevc-deinterlace=true&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported"
[2024-04-26 15:47:52.843 +00:00] [WRN] [193] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://my-jellyfin-server.example.com/Items/e5f1cc84322435aed69f89eea8db8c97/PlaybackInfo?UserId=a6a8202baa9f4809a992e045922b55a6&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&SubtitleStreamIndex=-1&MediaSourceId=e5f1cc84322435aed69f89eea8db8c97&MaxStreamingBitrate=140000000" to "192.168.1.1" in 0:00:14.0035494 with Status Code 200
[2024-04-26 15:47:53.528 +00:00] [INF] [135] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-04-26 15:47:53.529 +00:00] [INF] [135] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -autorotate 0 -i \"https://myserver.example.com/d/动漫/A-Z/B/86-不存在的地域-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS&CHT].mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 4 -hls_segment_type fmp4 -hls_fmp4_init_filename \"4503e337ecc197b1008d7e8455606dce-1.mp4\" -start_number 0 -hls_base_url \"hls/4503e337ecc197b1008d7e8455606dce/\" -hls_segment_filename \"/config/transcodes/4503e337ecc197b1008d7e8455606dce%d.mp4\" -hls_playlist_type event -hls_list_size 0 -y \"/config/transcodes/4503e337ecc197b1008d7e8455606dce.m3u8\""
[2024-04-26 15:48:21.350 +00:00] [WRN] [135] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://my-jellyfin-server.example.com/videos/e5f1cc84-3224-35ae-d69f-89eea8db8c97/live.m3u8?DeviceId=5bb8b151-e498-4a73-bdea-b1281ff14ea2&MediaSourceId=e5f1cc84322435aed69f89eea8db8c97&VideoCodec=hevc,h264&AudioCodec=aac,mp3,flac,alac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=f427232779e24ce68a689d7442bdf78f&api_key=ff3c4b4a1d8b42158b3b6f34c3804490&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=2ed9d040bf7be509b76988eb870578d0&SegmentContainer=mp4&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&hevc-profile=main,main10&hevc-level=183&hevc-deinterlace=true&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported" to "192.168.1.1" in 0:00:27.824585 with Status Code 200
[2024-04-26 15:48:37.863 +00:00] [INF] [134] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-04-26 15:48:49.862 +00:00] [INF] [134] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-04-26 15:49:34.601 +00:00] [INF] [134] Jellyfin.Api.Helpers.TranscodingJobHelper: Stopping ffmpeg process with q command for "/config/transcodes/4503e337ecc197b1008d7e8455606dce.m3u8"
[2024-04-26 15:49:34.621 +00:00] [INF] [155] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 200M -probesize 1G -i \"https://myserver.example.com/d/动漫/A-Z/B/86-不存在的地域-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS&CHT].mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-04-26 15:49:37.869 +00:00] [WRN] [121] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-04-26 15:49:37.887 +00:00] [INF] [121] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" closed
[2024-04-26 15:49:39.604 +00:00] [INF] [134] Jellyfin.Api.Helpers.TranscodingJobHelper: Killing FFmpeg process for "/config/transcodes/4503e337ecc197b1008d7e8455606dce.m3u8"
[2024-04-26 15:49:39.605 +00:00] [INF] [134] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/config/transcodes/4503e337ecc197b1008d7e8455606dce.m3u8"
[2024-04-26 15:49:39.625 +00:00] [ERR] [134] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 137
[2024-04-26 15:49:41.005 +00:00] [INF] [211] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" request
[2024-04-26 15:49:41.109 +00:00] [INF] [98] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Mobile (iPadOS)" "1.5.0" playing "可否勿忘我". Stopped at "0" ms
[2024-04-26 15:49:41.197 +00:00] [WRN] [98] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://my-jellyfin-server.example.com/Sessions/Playing/Stopped" to "192.168.1.1" in 0:00:06.5993062 with Status Code 204
```

### FFmpeg logs

```shell
/videos/e5f1cc84-3224-35ae-d69f-89eea8db8c97/live.m3u8

{"Protocol":1,"Id":"e5f1cc84322435aed69f89eea8db8c97","Path":"https://alist-web-proxy-myserver.example.com/d/\u52A8\u6F2B/A-Z/B/86-\u4E0D\u5B58\u5728\u7684\u5730\u57DF-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS\u0026CHT].mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"strm","Size":null,"Name":"86-\u4E0D\u5B58\u5728\u7684\u6218\u533A - S01E07 - \u7B2C7\u96C6","IsRemote":true,"ETag":"2ed9d040bf7be509b76988eb870578d0","RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[],"MediaAttachments":[],"Formats":[],"Bitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -autorotate 0 -i "https://myserver.example.com/d/动漫/A-Z/B/86-不存在的地域-/Season%2001/[Sakurato]%2086%20Eiti%20Shikkusu%20[07][HEVC-10bit%201080p%20AAC][CHS&CHT].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 4 -hls_segment_type fmp4 -hls_fmp4_init_filename "4503e337ecc197b1008d7e8455606dce-1.mp4" -start_number 0 -hls_base_url "hls/4503e337ecc197b1008d7e8455606dce/" -hls_segment_filename "/config/transcodes/4503e337ecc197b1008d7e8455606dce%d.mp4" -hls_playlist_type event -hls_list_size 0 -y "/config/transcodes/4503e337ecc197b1008d7e8455606dce.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
Hi.  A member of our triage team has already asked you to move this support request into our support channels. I am happy to help you in our Matrix or Discord spaces. A continued lack of respect for our moderation actions would likely result in an enforcement action.  Please join us on Matrix or Discord to resolve your support case.
