### ISSUE TITLE
[Bug] Unable to use custom css in the latest Release Candidate

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin#11441]
### Please describe your bug

Custom CSS feature is not working in the latest RC for 10.9 released on 22 April. Custom CSS does get applied when it is saved but on reloading the webpage custom CSS is not loaded. Opening element inspector shows that style tag that should contain custom CSS contains 'undefined'

### Reproduction Steps

1. Go to dashboard > general or user settings > display set custom css
2. Reload your webpage

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-04-26 01:34:58.013 +05:30] [WRN] [53] Jellyfin.Networking.Manager.NetworkManager: IPv6 is disabled in Jellyfin, but enabled in the OS. This may affect how the interface is selected.
[2024-04-26 01:34:58.016 +05:30] [WRN] [53] Jellyfin.Networking.Manager.NetworkManager: "Redacted": External request received, no matching external bind address found, trying internal addresses.
[2024-04-26 01:34:58.016 +05:30] [WRN] [53] Jellyfin.Networking.Manager.NetworkManager: "Redacted": External request received, but no external interface found. Need to route through internal network.
[2024-04-26 02:00:01.294 +05:30] [INF] [82] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-04-27 02:00:00.000 +05:30, which is 23:59:58.7100214 from now.
[2024-04-26 02:00:09.419 +05:30] [INF] [84] Emby.Server.Implementations.MediaEncoder.EncodingManager: Stopping chapter extraction for "Something Important…" because a chapter was found with a position greater than the runtime.
[2024-04-26 02:01:03.128 +05:30] [INF] [84] Emby.Server.Implementations.MediaEncoder.EncodingManager: Stopping chapter extraction for "Ocean's Three and a Half" because a chapter was found with a position greater than the runtime.
[2024-04-26 02:01:03.855 +05:30] [INF] [84] Emby.Server.Implementations.MediaEncoder.EncodingManager: Stopping chapter extraction for "Peter's Progress" because a chapter was found with a position greater than the runtime.
[2024-04-26 02:02:35.895 +05:30] [INF] [84] Emby.Server.Implementations.MediaEncoder.EncodingManager: Stopping chapter extraction for "WHERE I REALLY COME FROM" because a chapter was found with a position greater than the runtime.
[2024-04-26 02:03:15.615 +05:30] [INF] [84] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Extract Chapter Images" Completed after 3 minute(s) and 15 seconds
[2024-04-26 03:00:01.131 +05:30] [INF] [61] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-04-27 03:00:00.000 +05:30, which is 23:59:58.8751256 from now.
[2024-04-26 03:00:05.062 +05:30] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Generate Trickplay Images" Completed after 0 minute(s) and 4 seconds
[2024-04-26 03:08:20.061 +05:30] [WRN] [16] Microsoft.AspNetCore.Server.Kestrel: As of "04/25/2024 21:38:10 +00:00", the heartbeat has been running for "00:00:03.3795728" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-04-26 03:09:25.578 +05:30] [WRN] [16] Microsoft.AspNetCore.Server.Kestrel: As of "04/25/2024 21:39:24 +00:00", the heartbeat has been running for "00:00:06.2970348" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-04-26 03:57:11.377 +05:30] [WRN] [16] Microsoft.AspNetCore.Server.Kestrel: As of "04/25/2024 22:27:10 +00:00", the heartbeat has been running for "00:00:01.9543688" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-04-26 04:19:41.578 +05:30] [WRN] [16] Microsoft.AspNetCore.Server.Kestrel: As of "04/25/2024 22:49:32 +00:00", the heartbeat has been running for "00:00:01.8269097" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-04-26 04:24:14.931 +05:30] [WRN] [16] Microsoft.AspNetCore.Server.Kestrel: As of "04/25/2024 22:54:03 +00:00", the heartbeat has been running for "00:00:01.6195372" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-04-26 04:26:18.759 +05:30] [INF] [1] Main: Jellyfin version: "10.9.0"
[2024-04-26 04:26:19.444 +05:30] [INF] [1] Main: Environment Variables: ["[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]"]
[2024-04-26 04:26:19.457 +05:30] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-04-26 04:26:19.478 +05:30] [INF] [1] Main: Operating system: "Debian GNU/Linux 12 (bookworm)"
[2024-04-26 04:26:19.490 +05:30] [INF] [1] Main: Architecture: Arm64
[2024-04-26 04:26:19.493 +05:30] [INF] [1] Main: 64-Bit Process: True
[2024-04-26 04:26:19.494 +05:30] [INF] [1] Main: User Interactive: True
[2024-04-26 04:26:19.495 +05:30] [INF] [1] Main: Processor count: 4
[2024-04-26 04:26:19.496 +05:30] [INF] [1] Main: Program data path: "/config"
[2024-04-26 04:26:19.497 +05:30] [INF] [1] Main: Log directory path: "/config/log"
[2024-04-26 04:26:19.498 +05:30] [INF] [1] Main: Config directory path: "/config/config"
[2024-04-26 04:26:19.502 +05:30] [INF] [1] Main: Cache path: "/cache"
[2024-04-26 04:26:19.502 +05:30] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2024-04-26 04:26:19.503 +05:30] [INF] [1] Main: Application directory: "/jellyfin/"
[2024-04-26 04:26:22.438 +05:30] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-26 04:26:27.963 +05:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-04-26 04:26:28.369 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniDB, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniDB_7.0.0.0/Jellyfin.Plugin.AniDB.dll"
[2024-04-26 04:26:28.432 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniList_7.0.0.0/Jellyfin.Plugin.AniList.dll"
[2024-04-26 04:26:28.611 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniSearch, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniSearch_4.0.0.0/Jellyfin.Plugin.AniSearch.dll"
[2024-04-26 04:26:28.717 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Fanart_10.0.0.0/Jellyfin.Plugin.Fanart.dll"
[2024-04-26 04:26:28.723 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "3.0.0.0" of "IMVDb" 
[2024-04-26 04:26:28.892 +05:30] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Intro Skipper_0.1.7.0/ConfusedPolarBear.Plugin.IntroSkipper.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[2024-04-26 04:26:29.134 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Kitsu, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Kitsu_4.0.0.0/Jellyfin.Plugin.Kitsu.dll"
[2024-04-26 04:26:29.290 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.NapiSub, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/NapiSub_1.0.1.0/Jellyfin.Plugin.NapiSub.dll"
[2024-04-26 04:26:29.432 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Open Subtitles_19.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2024-04-26 04:26:29.663 +05:30] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Shoko_3.0.1.0/Shokofin.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[2024-04-26 04:26:29.982 +05:30] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/TheTVDB_10.0.0.0/Jellyfin.Plugin.Tvdb.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[2024-04-26 04:26:30.117 +05:30] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/TMDb Box Sets_10.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[2024-04-26 04:26:30.606 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TVmaze_10.0.0.0/Flurl.dll"
[2024-04-26 04:26:30.627 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TVmaze_10.0.0.0/Flurl.Http.dll"
[2024-04-26 04:26:30.638 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TvMaze, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TVmaze_10.0.0.0/Jellyfin.Plugin.TvMaze.dll"
[2024-04-26 04:26:30.809 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc" from "/config/plugins/TVmaze_10.0.0.0/Polly.dll"
[2024-04-26 04:26:30.828 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TVmaze_10.0.0.0/TvMaze.Api.Client.dll"
[2024-04-26 04:26:32.386 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-04-26 04:26:32.387 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-04-26 04:26:32.390 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-04-26 04:26:32.401 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "192.168.29.60", "172.30.0.1", "172.28.0.1", "172.18.0.1", "172.26.0.1", "172.24.0.1", "172.29.0.1", "172.20.0.1"]
[2024-04-26 04:26:32.408 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-04-26 04:26:32.409 +05:30] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[2024-04-26 04:29:20.661 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniDB" "7.0.0.0"
[2024-04-26 04:29:20.685 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "7.0.0.0"
[2024-04-26 04:29:20.766 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniSearch" "4.0.0.0"
[2024-04-26 04:29:20.800 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Fanart" "10.0.0.0"
[2024-04-26 04:29:20.822 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Kitsu" "4.0.0.0"
[2024-04-26 04:29:20.845 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "NapiSub" "1.0.1.0"
[2024-04-26 04:29:20.868 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "19.0.0.0"
[2024-04-26 04:29:20.901 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TVmaze" "10.0.0.0"
[2024-04-26 04:29:20.904 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.0.0"
[2024-04-26 04:29:20.906 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.0.0"
[2024-04-26 04:29:20.908 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.0.0"
[2024-04-26 04:29:21.169 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.0.0"
[2024-04-26 04:29:21.170 +05:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.0.0"
[2024-04-26 04:29:21.765 +05:30] [INF] [1] Main: Kestrel is listening on "127.0.0.1"
[2024-04-26 04:29:21.773 +05:30] [INF] [1] Main: Kestrel is listening on "192.168.29.60"
[2024-04-26 04:29:21.774 +05:30] [INF] [1] Main: Kestrel is listening on "172.30.0.1"
[2024-04-26 04:29:21.774 +05:30] [INF] [1] Main: Kestrel is listening on "172.28.0.1"
[2024-04-26 04:29:21.775 +05:30] [INF] [1] Main: Kestrel is listening on "172.18.0.1"
[2024-04-26 04:29:21.776 +05:30] [INF] [1] Main: Kestrel is listening on "172.26.0.1"
[2024-04-26 04:29:21.776 +05:30] [INF] [1] Main: Kestrel is listening on "172.24.0.1"
[2024-04-26 04:29:21.776 +05:30] [INF] [1] Main: Kestrel is listening on "172.29.0.1"
[2024-04-26 04:29:21.776 +05:30] [INF] [1] Main: Kestrel is listening on "172.20.0.1"
[2024-04-26 04:29:25.229 +05:30] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/wwwroot". Static files may be unavailable.
[2024-04-26 04:29:25.699 +05:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-04-26 04:29:26.036 +05:30] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-04-27 03:00:00.000 +05:30, which is 22:30:33.9635913 from now.
[2024-04-26 04:29:26.404 +05:30] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-04-27 02:00:00.000 +05:30, which is 21:30:33.5951823 from now.
[2024-04-26 04:29:27.765 +05:30] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/drive/4k Movies"
[2024-04-26 04:29:29.331 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-04-26 04:29:29.496 +05:30] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/drivetwo/Cartoons"
[2024-04-26 04:29:30.263 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_rkmpp", "h264", "h264_rkmpp", "hevc", "hevc_rkmpp", "mpeg1_rkmpp", "mpeg2video", "mpeg2_rkmpp", "mpeg4", "mpeg4_rkmpp", "msmpeg4", "vp8", "vp8_rkmpp", "libvpx", "vp9", "vp9_rkmpp", "libvpx-vp9", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-04-26 04:29:30.590 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "libx264", "h264_v4l2m2m", "h264_rkmpp", "libx265", "hevc_rkmpp", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-04-26 04:29:30.795 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["overlay_opencl", "overlay_rkrga", "scale_opencl", "scale_rkrga", "tonemap_opencl", "vpp_rkrga", "zscale", "alphasrc"]
[2024-04-26 04:29:30.874 +05:30] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "scale_cuda" with option "Output format (default \"same\")" is not available
[2024-04-26 04:29:31.033 +05:30] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "tonemap_cuda" with option "GPU accelerated HDR to SDR tonemapping" is not available
[2024-04-26 04:29:31.339 +05:30] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2024-04-26 04:29:31.434 +05:30] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vulkan" with option "Action to take when encountering EOF from secondary input" is not available
[2024-04-26 04:29:31.667 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["drm", "opencl", "rkmpp"]
[2024-04-26 04:29:32.694 +05:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-04-26 04:29:32.829 +05:30] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/moviestwo"
[2024-04-26 04:29:33.099 +05:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "49203adaf5e34fc68cd36dbd4aea8a3e"
[2024-04-26 04:29:33.099 +05:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-04-26 04:29:33.100 +05:30] [INF] [1] Main: Startup complete 0:03:18.4026155
[2024-04-26 04:29:34.582 +05:30] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/music"
[2024-04-26 04:29:35.102 +05:30] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/tvshowstwo"
[2024-04-26 04:29:36.982 +05:30] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/Anime"
[2024-04-26 04:29:42.306 +05:30] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 12 seconds
[2024-04-26 04:29:47.738 +05:30] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 17 seconds
[2024-04-26 04:29:49.979 +05:30] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/movies"
[2024-04-26 04:29:56.372 +05:30] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/tvshows"
[2024-04-26 07:37:20.505 +05:30] [WRN] [34] Jellyfin.Networking.Manager.NetworkManager: IPv6 is disabled in Jellyfin, but enabled in the OS. This may affect how the interface is selected.
[2024-04-26 07:37:20.581 +05:30] [WRN] [34] Jellyfin.Networking.Manager.NetworkManager: "Redacted": External request received, no matching external bind address found, trying internal addresses.
[2024-04-26 07:37:20.584 +05:30] [WRN] [34] Jellyfin.Networking.Manager.NetworkManager: "Redacted": External request received, but no external interface found. Need to route through internal network.
[2024-04-26 09:30:44.116 +05:30] [INF] [77] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.29.246" request
[2024-04-26 09:31:32.008 +05:30] [WRN] [75] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.29.246" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-04-26 09:31:32.109 +05:30] [INF] [75] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.29.246" closed
[2024-04-26 09:31:34.856 +05:30] [INF] [40] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.29.246" request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
I'm unable to reproduce this issue. When I add some obvious CSS in the dashboard and save it, then reload the page it shows as expected. Your logs do indicate your attempting to use various incompatible plugins, perhaps this causes the issue.

```css
body { background: red !important; }
```

**Comment by prayag17** [comment]
I got this exact issue even with demo.jellyfin.org/unstable . Go to user preferences > display try your CSS, it wont work after reload.
[recording.webm](https://github.com/jellyfin/jellyfin/assets/55829513/73924fdc-918a-4913-8f1d-0e7a68c5f67a)

**Comment by nielsvanvelzen** [comment]
Thanks for clarifying. I tested it via the dashboard which worked fine, doing it via user preferences does indeed cause the CSS to not work after a reload.
