### ISSUE TITLE
Crashes when visiting EPG

### ISSUE THREAD

**Issue by MightySmallBalls** [jellyfin/jellyfin#1147]
Jellyfin crashes when  visiting EPG with XMLtv.epg present with pictures.

To Reproduce add xmltv epg and iptv service via xtreme codes

**Logs**
[2019-03-22 21:30:31.351 +01:00] [INF] HttpClientManager "GET": "http://pici.life/lg/NL/NPO_Humor.png"
[2019-03-22 21:30:31.769 +01:00] [INF] Getting image size for item "LiveTvChannel" "C:\jellyfin\pici.life\DE\3sat.png"

**System (please complete the following information):**
 - OS: Windows x64
 - Browser: Safari
 - Jellyfin Version: 10.2.2
 - Reverse proxy: Citrix Netscaler VPX8000 v12.1

**Additional context**
If I create the fie it continues until it misses another file. It will always crash on the same file until it is created....I cannot find any of the files in the http get on the disk.

**Comment by fruhnow** [comment]
Logs don't contain any errors. Can you try providing more detail? Thanks in advance

**Comment by MightySmallBalls** [comment]
Will post logs here soon...

**Comment by MightySmallBalls** [comment]
Seems it crashes due to faulty m3u....if you look at the log one of the rows are missing http:// infront of the image so jellyfin didnt download it hence the crash on size. Maybe add check for http:// and if missing add it and then add check for fileexists around the file size function.



[2019-03-22 21:08:17.893 +01:00] [INF] Found m3u channel: "-1 tvg-id=\"skyarts.de\" tvg-name=\"Sky Arts HD DE\" tvg-logo=\"pici.life/skyartshd.png\" group-title=\"Germany\",Sky Arts HD DE"
[2019-03-22 21:08:17.895 +01:00] [INF] Found m3u channel: "-1 tvg-id=\"skyarts.de\" tvg-name=\"Sky Arts FHD DE\" tvg-logo=\"http://pici.life/skyartehd_2.png\" group-title=\"Germany\",Sky Arts FHD DE"



[2019-03-22 21:22:42.791 +01:00] [INF] Getting image size for item "LiveTvChannel" "C:\jellyfin\pici.life\skyartshd.png"
[2019-03-22 21:22:42.805 +01:00] [ERR] Failed to determine primary image aspect ratio for "C:\jellyfin\pici.life\skyartshd.png"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info, Boolean updateItem)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
