### ISSUE TITLE
[Issue]: LiveTV playback fails when Tuner does not allow http HEAD method

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#11493]
### Please describe your bug

Web reports `Playback failed due to a server error.`  LiveTV is being provided by [ErsatzTV](https://github.com/ErsatzTV/ErsatzTV).

Works on current stable, started failing after upgrading to unstable

### Reproduction Steps

1. Have livetv provided by ErsatzTV
2. Click Play on a channel
3. Failure

### Jellyfin Version

Unstable (master branch)

### if other:

Build 2024050117

### Environment

```markdown
- OS: Proxmox
- Linux Kernel: 6.5.13-3-pve
- Virtualization: Docker
- Clients: Web
- Browser: Firefox
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method:
- Hardware Acceleration: NVENC
- GPU Model: T400
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[17:49:22] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for matt. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[17:49:22] [INF] [46] Jellyfin.LiveTv.LiveTvMediaSourceProvider: Opening channel stream from Emby, external channel Id: m3u_f42b0e9e6f9cc8e31d1abe0fe67da9cd449cc5645d336352556a6ee0760b3ca1
[17:49:22] [INF] [46] Jellyfin.LiveTv.DefaultLiveTvService: Streaming Channel m3u_f42b0e9e6f9cc8e31d1abe0fe67da9cd449cc5645d336352556a6ee0760b3ca1
[17:49:22] [ERR] [29] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.LiveTv.TunerHosts.M3UTunerHost.GetChannelStream(TunerHostInfo tunerHost, ChannelInfo channel, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
[17:49:22] [ERR] [29] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/ef4b76c8160c93cc34c686770d6f7459/PlaybackInfo.
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
   at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.DefaultLiveTvService.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.LiveTvMediaSourceProvider.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.OpenMediaSource(HttpContext httpContext, LiveStreamRequest request)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
   at lambda_method1427(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Your tuner does not support http HEAD method for content type checking

**Comment by gnattu** [comment]
ErsatzTV/ErsatzTV#1683

It seems like ErsatzTV fixed this on their side but has not released a version includes this yet.

**Comment by JohnTrabusca** [comment]
I'm also running into this issue with xteve as the M3U provider. Jellyfin tries to send HTTP HEAD requests to xteve over an nginx proxy, but xteve does not seem to support HEAD requests on m3u's and therefore the connection hangs, resulting in a 504 thrown by the Proxy and an exception created by Jellyfin as it doesn't seem to handle 504's gracefully. Asides from obviously switching to a well-maintained xteve alternative, is there anything that could be done to prevent jellyfin from sending HEAD requests?

**Comment by gnattu** [comment]
> I'm also running into this issue with xteve as the M3U provider. Jellyfin tries to send HTTP HEAD requests to xteve over an nginx proxy, but xteve does not seem to support HEAD requests on m3u's and therefore the connection hangs, resulting in a 504 thrown by the Proxy and an exception created by Jellyfin as it doesn't seem to handle 504's gracefully. Asides from obviously switching to a well-maintained xteve alternative, is there anything that could be done to prevent jellyfin from sending HEAD requests?

`504` is really one of the worst case we can handle gracefully. It means gateway timeout. Currently we don't have built-in method to do this, but you can setup your own reverse proxy like in front of it, and actively return a 405 to the client.

Like:

```
if ($request_method = HEAD ) {
    return 405 "<b>Method Not Allowed</b>
";
}
```
