### ISSUE TITLE
Auto-discovery causes server to stop responding

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#11498]
_Originally reported by @firecore:_

We have checked the latest unstable 10.9 build on Debian 11 and macOS and the Jellyfin server stopped responding to Infuse when auto-discovering. At the same time, we see the following error in Jellyfin logs:

```shell
2024-05-06 13:57:34.426 +04:00] [ERR] Failed to receive data from socket
System.Net.Sockets.SocketException (98): Address already in use
  at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
  at System.Net.Sockets.Socket.Bind(EndPoint localEP)
  at Jellyfin.Networking.AutoDiscoveryHost.RespondToV2Message(IPAddress responderIp, IPEndPoint endpoint, CancellationToken cancellationToken)
  at Jellyfin.Networking.AutoDiscoveryHost.ListenForAutoDiscoveryMessage(IPAddress listenAddress, IPAddress respondAddress, CancellationToken cancellationToken)
```

Same behavior when we run a console command on Debian 11.
`echo -n "who is JellyfinServer?" | nc -u -b 255.255.255.255 7359.`
We have also checked the Kodi app for Jellyfin and the behavior is identical. 

### Jellyfin Version

Unstable (master branch)

**Comment by nielsvanvelzen** [comment]
I've been able to reproduce this issue on Windows 10. This dirty patch made it work again for me, obviously not a proper fix but should help getting there.

```diff
Index: src/Jellyfin.Networking/AutoDiscoveryHost.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Jellyfin.Networking/AutoDiscoveryHost.cs b/src/Jellyfin.Networking/AutoDiscoveryHost.cs
--- a/src/Jellyfin.Networking/AutoDiscoveryHost.cs	(revision 36755318233b75be08399711e2d0afbf78e7a69d)
+++ b/src/Jellyfin.Networking/AutoDiscoveryHost.cs	(date 1715010218775)
@@ -110,7 +110,7 @@
                     var text = Encoding.UTF8.GetString(result.Buffer);
                     if (text.Contains("who is JellyfinServer?", StringComparison.OrdinalIgnoreCase))
                     {
-                        await RespondToV2Message(respondAddress, result.RemoteEndPoint, cancellationToken).ConfigureAwait(false);
+                        await RespondToV2Message(udpClient, respondAddress, result.RemoteEndPoint, cancellationToken).ConfigureAwait(false);
                     }
                 }
                 catch (SocketException ex)
@@ -130,7 +130,7 @@
         }
     }
 
-    private async Task RespondToV2Message(IPAddress responderIp, IPEndPoint endpoint, CancellationToken cancellationToken)
+    private async Task RespondToV2Message(UdpClient udpClient, IPAddress responderIp, IPEndPoint endpoint, CancellationToken cancellationToken)
     {
         var localUrl = _appHost.GetSmartApiUrl(endpoint.Address);
         if (string.IsNullOrEmpty(localUrl))
@@ -141,11 +141,11 @@
 
         var response = new ServerDiscoveryInfo(localUrl, _appHost.SystemId, _appHost.FriendlyName);
 
-        using var responder = new UdpClient(new IPEndPoint(responderIp, PortNumber));
+        // using var responder = new UdpClient(new IPEndPoint(responderIp, PortNumber));
         try
         {
             _logger.LogDebug("Sending AutoDiscovery response");
-            await responder
+            await udpClient
                 .SendAsync(JsonSerializer.SerializeToUtf8Bytes(response).AsMemory(), endpoint, cancellationToken)
                 .ConfigureAwait(false);
         }
```

Tested using the "discover" command in the kotlin-sdk cli sample

**Comment by firecore** [comment]
Nice work team! 👏
