### ISSUE TITLE
[Issue]: Marking items as played with api key broken on unstable

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin#11501]
### Please describe your bug

It's not longer possible to update an items' played status using an api key.

I have a few scripts that do so and they all stopped working after upgrading to unstable.
They do a POST to `/Users/<userId>/PlayedItems/<itemId>`, this now throws a stacktrace in the jellfin log. (attached below)

Looking at the code this endpoint is obsolete, so I tried what I think is the new end point.
By sending a POST to `/UserPlayedItems/<itemId>?userId=<userId>`, this result in nearly the same stacktrace.

Note in both cases I was using an API key, I think somehow the info is not properly parsed when doing so. The web interface seems to not have issues, but that is not using an API key.

### Reproduction Steps

I was able to get the same trace when using curl, not 100% sure those are correct. (I will test once I am back on stable)

```
curl -v -H 'X-Emby-Token: <snip>' -H 'X-Emby-Authorization: MediaBrowser, Client="other", Device="script", DeviceId="script", Version="0.0.0"' -X POST https://<host>/jellyfin/Users/<userId>/PlayedItems/<itemId>
```

```
curl -v -H 'X-Emby-Token: <snip>'' -H 'X-Emby-Authorization: MediaBrowser, Client="other", Device="script", DeviceId="script", Version="0.0.0"' -X POST 'https://<host>/jellyfin/UserPlayedItems/<itemId>?userId=<userId>'
```

The scripts are node/typescript where I use axios, relevant bits

```typescript
import axios from 'axios';
import https from 'node:https';
import fs from 'node:fs';

const url = "https://example.org/jellyfin";
const apiKey = "...";
const userId = "...";
const itemId = "...";
const caFile = undefined;

const httpClient = caFile ?
  new https.Agent({ ca: fs.readFileSync(caFile), keepAlive: true }) :
  new https.Agent({ keepAlive: true });
const client = axios.create({
  baseURL: url.endsWith("/") ?  url : `${url}/`,
  httpsAgent: httpClient,
  timeout: 10000,
  headers: {
    "Accept": "application/json",
    "X-Emby-Token": apiKey,
    "X-Emby-Authorization": 'MediaBrowser, Client="other", Device="script", DeviceId="script", Version="0.0.0"',
  }
});


await client.post(`/Users/${userId}/PlayedItems/${itemId}`);
```

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: GNU/Linux 6.5.0-26-generic x86_64 (for ARC support)
- Virtualization: BHYVE
- Clients: Browser
- Browser: Firefox 124.0b9 (64-bit)
- FFmpeg Version: jellyfin-ffmpeg6 - 6.0.1-5-jammy
- Playback Method: Transcode (Ends up playing without subs transcoded to AV1)
- Hardware Acceleration: QSV (also tried without, no difference)
- GPU Model: Intel Arc A310 Low Profile 4GB (ASRock)
- Plugins: AniDB, AniList, AudioDB, Cover Art Archive, Fanart, MusicBrainz, OMDb, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, Trakt, Webhook
- Reverse Proxy: apache
- Base URL: /jellyfin
- Networking: vnic
- Storage: local (config) + NFS (media)
```

### Jellyfin logs

```shell
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]: [19:07:41] [ERR] Error processing request. URL POST /Users/5ec9a0d2bb85452ab00760fc7fadbc7a/PlayedItems/4e4ccc5311f3116b9ade1ca75f6e7d6b.
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]: System.ArgumentException: Guid can't be empty (Parameter 'id')
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Helpers.RequestHelpers.GetSession(ISessionManager sessionManager, IUserManager userManager, HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem(Nullable`1 userId, Guid itemId, Nullable`1 datePlayed)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at lambda_method2539(Closure, Object)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]: --- End of stack trace from previous location ---
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]: --- End of stack trace from previous location ---
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
May 06 19:07:41 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]: [19:12:07] [ERR] Error processing request. URL POST /UserPlayedItems/4e4ccc5311f3116b9ade1ca75f6e7d6b.
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]: System.ArgumentException: Guid can't be empty (Parameter 'id')
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Helpers.RequestHelpers.GetSession(ISessionManager sessionManager, IUserManager userManager, HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem(Nullable`1 userId, Guid itemId, Nullable`1 datePlayed)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at lambda_method2547(Closure, Object)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]: --- End of stack trace from previous location ---
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]: --- End of stack trace from previous location ---
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
May 06 19:12:07 artemis.acheron.be jellyfin[1398405]:    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sjorge** [comment]
I can confirm the script (unmodified) works on stable but not unstable using a POST to `/Users/<userId>/PlayedItems/<itemId>`

**Comment by nielsvanvelzen** [comment]
Does this also happen when you use the non-deprecated authorization headers?
https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f

**Comment by sjorge** [comment]
@nielsvanvelzen not sure, I downgraded already to have a usable system again.

If I find time before the Thursday I'll update with that info. Will be away after for a few days.

**Comment by sjorge** [comment]
```
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]: [21:57:30] [ERR] Error processing request. URL POST /Users/5ec9a0d2bb85452ab00760fc7fadbc7a/PlayedItems/440703a6874f9f4938b261e777be9b8e.
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]: System.ArgumentException: Guid can't be empty (Parameter 'id')
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Helpers.RequestHelpers.GetSession(ISessionManager sessionManager, IUserManager userManager, HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem(Nullable`1 userId, Guid itemId, Nullable`1 datePlayed)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at lambda_method1424(Closure, Object)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]: --- End of stack trace from previous location ---
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]: --- End of stack trace from previous location ---
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
May 06 21:57:30 artemis.acheron.be jellyfin[1417595]:    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Same with the other header Niels asked about.

Just to be sure I also filled in the tags more sanely.

```
    [Symbol(headers)]: Headers {
      "accept": "application/json",
      "content-type": "application/x-www-form-urlencoded",
      "authorization": "MediaBrowser Token=\"<snip>\", Client=\"jellyfin-anilist-sync\", Device=\"script\", DeviceId=\"0de6b4ba\", Version=\"1.0.0\"",
      "user-agent": "axios/1.6.8",
      "accept-encoding": "gzip, compress, deflate, br",
    },
```

But that also had no extra ffect.

**Comment by gnattu** [comment]
<img width="1512" alt="image" src="https://github.com/jellyfin/jellyfin/assets/12995396/87ec4e90-1abb-4b95-8636-9e41d704562d">

I cannot reproduce this. Using your exact command and Base URL.

**Comment by gnattu** [comment]
I figured it out. Using API Key only without actual login the http context will not have any user info and therefore won't allow update even if a userId has already being specified in the request.

**Comment by sjorge** [comment]
@gnattu #11408 was a similar issue where the userId was not properly used with API Keys (I was hitting that one before, now I am hitting this one). So as you mentioned in the PR, there might be other spots were there are still issues.

I probably won't find them (🙏) as updating the Played data is the last thing 2 of my scripts do so I assume that I won't hit anything new.
