### ISSUE TITLE
[Issue]: SSL handshake failure when attempting to access plugin repo

### ISSUE THREAD

**Issue by Beninjam101** [jellyfin/jellyfin#11525]
### Please describe your bug

Jellyfin is unable to access the plugin repository.

This issue occurs on two Macs running MacOS 13.6.6 & 14.3.1, on both my home wifi and phone hotspot.

The logs indicate an SSL error; however, I have no problems accessing the json file through either a web browser or curl. The redirect works fine.

The exact same error is present in the logs in all cases.

### Reproduction Steps

1. Open Jellyfin
2. Error occurs

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: MacOS 13.6.6 / 14.3.1
- Linux Kernel: none
- Virtualization: Native
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 7
- Playback Method: N/A
- Hardware Acceleration: none
- GPU Model: Radeon Pro 560 4 GB / AMD Radeon Pro 5500M 8 GB
- Plugins: Default
- Reverse Proxy: none
- Base URL: none
- Networking: Host / NAT
- Storage: local
```

### Jellyfin logs

```shell
[2024-05-11 03:29:49.489 +10:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2024-05-11 03:29:51.770 +10:00] [ERR] [7] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: handshake failure
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
[2024-05-11 03:29:51.783 +10:00] [INF] [7] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 2 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Beninjam101** [comment]
I should note that I did not have this issue a few weeks ago when I set up the server, and there have not been any changes to my network since then.

**Comment by joshuaboniface** [comment]
If you visit https://repo.jellyfin.org/releases/plugin/manifest-stable.json?mirrorlist which mirror server is it directing you to? It's possible one of them is being wonky.

**Comment by Beninjam101** [comment]
I'm being directed to the Sydney, Australia mirror at https://syd1.mirror.jellyfin.org/.
I'm receiving valid json data from this mirror; if I add "https://syd1.mirror.jellyfin.org/files/plugin/manifest.json" as a repo in Jellyfin it is able to list plugins but not install them.

**Comment by joshuaboniface** [comment]
Very curious, and this is happening repeatedly within Jellyfin? Also if you use the mirror directly which issues are reported by the plugin install, similar SSL verification failures?

**Comment by joshuaboniface** [comment]
Verified that all the SSL certs are valid, and the server should be responding. One thing I'm wondering, do you have IPv6 enabled? If you `curl` with `-6` and `-4` explicitly do you get a failure?

**Comment by Beninjam101** [comment]
Yes, the SSL verification failures when attempting a plugin install while using the mirror directly at a glance looks identical the the above. IPv6 is disabled in Jellyfin. Running curl with -6 and -4 is successful.

**Comment by joshuaboniface** [comment]
How do things look now? Just curious if the change I made makes any difference.

**Comment by Beninjam101** [comment]
We're up and running! Whatever you changed seems to have done the trick.
Thank you for being so helpful; I really appreciate it.

**Comment by joshuaboniface** [comment]
Thanks for confirming! I just restored our old Let's Encrypt cert, which isn't really a solution since it expires at the end of the month. I'll do a bit more testing to see what might have changed and why.

**Comment by Beninjam101** [comment]
That's definitely not ideal. Let me know if you need me to run any more tests.

**Comment by joshuaboniface** [comment]
Thanks, can you test once more now and confirm if it still looks OK?

**Comment by Beninjam101** [comment]
It's still working! Not sure if it's my imagination or internet connection but it does seems to be a little slower now though.

**Comment by joshuaboniface** [comment]
The slowness might just be normal variance (thanks, DigitalOcean) but the fact it's still working definitely proves my suspicions about the issue.

The underlying issue was two-parted:

1. I upgraded our SSL termination host a few weeks back and with that came a newer version of Certbot which now defaults to using ECDSA keys instead of RSA keys, and then I generated a new certificate Tuesday to reflect a domain change. This meant that the new cert was using ECDSA instead of RSA.
2. Jellyfin stable uses .NET 6, and it seems that .NET 6 does not support ECDSA SSL keys, which is why there was a handshake failure. Combined with the new cert this caused the issue.

I've reconfigured things so we explicitly request an RSA-based cert now, so that should be good going forward!

**Comment by gnattu** [comment]
If you still have time, can you test with this repo as well?

https://gnattu.net/.well-known/jellyfin.json

You can add this into the plugin repo and load the catalog, click into any plugin and see if this repo appears as a valid install source? Because we are having strange findings now and we want to rule out cause of the certificate issue. You don't have to install anything from that repo and only need to check if the catalogue loads.

**Comment by Beninjam101** [comment]
Hi gnattu,
I'm able to both view the catalog and successfully install plugins from your repo.

**Comment by joshuaboniface** [comment]
Just to add some more info here for posterity:

It seems the issue actually includes the interplay of HAProxy as well, which is what we use as our SSL terminating load-balancer/proxy. We weren't able to replicate the issue behind NGiNX so it definitely seems like HAProxy is a critical part of the problem.

Given that RSA certs are still available and will likely continue to be available indefinitely, until we hear otherwise, I'm going to consider it not worth digging in any further and just stick with that solution. Glad everything is working now!

**Comment by psaumur** [comment]
I know this is likely necro'd but I am having the same issue as the OP and haven't been able to find a solution for it online.
Am using the linuxserver.io docker container deployment of Jellyfin Server v10.10.7 on Ubuntu 24.04

Log snippet :

```
[2025-07-04 21:49:18.199 -07:00] [ERR] [31] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://sfo1.mirror.jellyfin.org/files/plugin/manifest.json"
System.Net.Http.HttpRequestException: Resource temporarily unavailable (sfo1.mirror.jellyfin.org:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Jellyfin.Networking.HappyEyeballs.HttpClientExtension.AttemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at Jellyfin.Networking.HappyEyeballs.HttpClientExtension.OnConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

This is the same error for each plugin repo.
I have full network access to the Public internet. Ports open on 80/443 in Firewall. DNS is resolving correctly. IPv4 and IPv6 are enabled on the Host and within Jellyfin.
