### ISSUE TITLE
Catalogue will not load[Issue]: 

### ISSUE THREAD

**Issue by cAble-SWG** [jellyfin/jellyfin#11521]
### Please describe your bug

When going to the plugins and clicking the catalogue, nothing loads.. 

"no available plugins". 

The stable Repo is in the repo listings.

Tried many workarounds, but can get the catalogue to list.

Running windows 10 x64

### Reproduction Steps

This issue never resolves and always reproduces. 

### Jellyfin Version

10.8.13

### Environment

```markdown
n
```

### Jellyfin logs

```shell
none
```

### Please attach any browser or client logs here

none

### Please attach any screenshots here

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cAble-SWG** [comment]
I can add private repos and the catalogue will update. The main jellyfin one will not update the catalogue

**Comment by crobibero** [comment]
It's likely a network issue but since you didn't provide any logs all we can do is guess.

**Comment by cAble-SWG** [comment]
[Log.txt](https://github.com/jellyfin/jellyfin/files/15262597/Log.txt)

**Comment by cAble-SWG** [comment]
sorry. i missed. log posted

**Comment by crobibero** [comment]
Your server is having ssl issues. The certificate is valid, so it is an issue on your end. 

```
[2024-05-09 11:23:14.641 +01:00] [ERR] [13] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)

```

**Comment by joshuaboniface** [comment]
It does seem like this was an actual issue. See #11525 for a full explanation.
