### ISSUE TITLE
stack traces and playback errors after upgrade to 10.9.0

### ISSUE THREAD

**Issue by Wurzelmann** [jellyfin/jellyfin#11543]
**Describe The Bug**
Since the upgrade to 10.9.0 today, I have massive playback errors with most video files (does not matter if MP4, MKV or AVI), some are working, but approx. 90 % aren't any more.

**Steps To Reproduce**

1. after upgrade to 10.9.0 start movie or series
2. experience playback error right after clicking play

**Expected Behavior**
Expected behaviour: playback of video files (worked fine before upgrade to 10.9.0

**Logs**

from /var/log/jellyfin/jellyfin20240512.log while starting playback on video:

```
[2024-05-12 00:29:31.338 +02:00] [ERR] Error processing request. URL "GET" "/videos/28713f35-547f-e43c-e226-3af1936b0223/hls1/main/-1.mp4".
System.ArgumentNullException: Value cannot be null. (Parameter '_mediaEncoder.EncoderPath')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1285(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Screenshots**
no screenshots

**System (please complete the following information):**
 - Platform: Linux, Debian 12.5
 - Browser: Firefox 115.10.0esr, Chromium Version 124.0.6367.201

 - Jellyfin Version: 10.9.0

**Comment by gnattu** [comment]
Does `/usr/lib/jellyfin-ffmpeg/ffmpeg` exist in your system?

**Comment by joshuaboniface** [comment]
Also what is your output of `systemctl status jellyfin`? Somehow it's not finding ffmpeg where it should be.

**Comment by Wurzelmann** [comment]
> Does `/usr/lib/jellyfin-ffmpeg/ffmpeg` exist in your system?

Oh, it does not, but I'm sure it was there before the 10.9.0 upgrade. I checked the installed packages and **jellyfin-ffmpeg** was not working any more, but either **jellyfin-ffmpeg6** or **jellyfin-ffmpeg5** were offered as a replacement. I installed **jellyfin-ffmpeg6** and not it is working again!

Thank you very much for this pointer, case closed!

**Comment by Wurzelmann** [comment]
> Also what is your output of `systemctl status jellyfin`? Somehow it's not finding ffmpeg where it should be.

I'm not using systemd, I checked all relevant logs for hints and found nothing indicating the real problem (missing jellyfin-ffmpeg6 package). Thanks anyway!

**Comment by boredazfcuk** [comment]
Not sure why this has been closed. I've just upgraded and to 10.9.0 and I'm experiencing the same issue.

**Comment by Wurzelmann** [comment]
> Not sure why this has been closed. I've just upgraded and to 10.9.0 and I'm experiencing the same issue.
> 
> I've found ffmpeg at /usr/lib/jellyfin-ffmpeg/ffmpeg
> 
> The encoding.xml file lists it being here: /usr/lib/jellyfin-ffmpeg/ffmpeg
> 
> But this is blank and not editable: ![image](https://private-user-images.githubusercontent.com/14807258/329869060-84ac2f0b-89e4-4f42-8f62-f2ea33a27505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzY1OTUsIm5iZiI6MTcxNTUzNjI5NSwicGF0aCI6Ii8xNDgwNzI1OC8zMjk4NjkwNjAtODRhYzJmMGItODllNC00ZjQyLThmNjItZjJlYTMzYTI3NTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE3NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MzlhMTA3YzRiYzg4NzljYTNkNjNmMTI0OWQ4N2E5MGE0MjQ1N2M4NWMzMzQ5MjIyNTVjNTkzNThiMmM2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LveKW3naeaNUUzRbPbxarc6pimyFD1L0ayk58Yg-OIc)
> 


Technically, it is not a bug, I guess, because the replacement of ffmpeg is mentioned in the changelog (I skimmed it before upgrading, but did not see that part):

https://github.com/jellyfin/jellyfin/releases/v10.9.0 see

"fix: swap to jellyfin-ffmpeg5 [PR https://github.com/jellyfin/jellyfin/pull/9256], by @brettpetch"

but the package jellyfin-server does not require the package **jellyfin-ffmpeg5** which would replace the old **ffmpeg** package, so I guess this is the real bug: missing dependencies in the Debian package.

Anyway: I installed **jellyfin-ffmpeg6**, restarted jellyfin and it worked again (see FFmpeg path, which should be populated again afterwards)

**Comment by gnattu** [comment]
> encoding.xml

encoding.xml is deprecated and should no longer being used. You should use `--ffmpeg` cli parameter to specify where the ffmpeg is.

**Comment by boredazfcuk** [comment]
> Anyway: I installed **jellyfin-ffmpeg6**, restarted jellyfin and it worked again (see FFmpeg path, which should be populated again afterwards)

How did you manage that?

My container thinks it's already installed:
```
dpkg --list *jellyfin-ffmpeg6*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version          Architecture Description
+++-================-================-============-================================================================
ii  jellyfin-ffmpeg6 6.0.1-6-bookworm amd64        Tools for transcoding, streaming and playing of multimedia files
```
Or do you mean you installed jellyfin-ffmpeg5?

**Comment by Wurzelmann** [comment]
I installed jellyfin-ffmpeg6, not 5, don't ask me why, I just chose the "newer" one. Oh and I'm not using Docker, sorry, Debian on baremetal.

**Comment by gnattu** [comment]
You should not use jellyfin-ffmpeg5 with 10.9. Please don't look at the changelog from years ago to make any deicision

**Comment by boredazfcuk** [comment]
Found this in the logs, but again, I couldn't modify the location of ffmpeg in the UI
```
[19:27:26] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder

System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/local/bin/ffmpeg' with working directory '/config'. No such file or directory

   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)

   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)

   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)

   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
```
Linked the location with:
```
root@jellyfin:/config# ln -s /usr/share/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg
```
Restarted Jellyfin and it's back in action

**Comment by gnattu** [comment]
> I couldn't modify the location of ffmpeg in the UI

This is intentionally removed due to security reasons. Please, please, please, use the `--ffmpeg` cli parameter to configure the ffmpeg location, okay?

**Comment by boredazfcuk** [comment]
> > I couldn't modify the location of ffmpeg in the UI
> 
> This is intentionally removed due to security reasons. Please, please, please, use the `--ffmpeg` cli parameter to configure the ffmpeg location, okay?

CLI parameter for what? I'm using the Docker container. Will configuring with the parameter survive container re-creation? I have /config mapped to persistent storage.

**Comment by gnattu** [comment]
> > > I couldn't modify the location of ffmpeg in the UI
> > 
> > 
> > This is intentionally removed due to security reasons. Please, please, please, use the `--ffmpeg` cli parameter to configure the ffmpeg location, okay?
> 
> CLI parameter for which command? I'm using the Docker container and don't ever connect to the container to issue commands. Will configuring with the parameter survive container re-creation? I have /config mapped to persistent storage.

Then it seems like you are not using our official docker container.

This cli is straight in our entrypoint:

https://github.com/jellyfin/jellyfin-packaging/blob/a974263fbfdb924632c0553ceb83588cf75e0272/docker/Dockerfile#L199

**Comment by Wurzelmann** [comment]
> You should not use jellyfin-ffmpeg5 with 10.9. Please don't look at the changelog from years ago to make any deicision

for the record: jellyfin-ffmpeg5 is mentioned in yesterday's changelog or was your comment not targeted at me?

**Comment by boredazfcuk** [comment]
> for the record: jellyfin-ffmpeg5 is mentioned in yesterday's changelog or was your comment not targeted at me?

I just connected to my container and saw that jellyfin-ffmpeg6 was already installed. With the link mentioning the swap out to jellyfin-mpeg5, I thought you meant you'd rolled back but typo'd it.

**Comment by gnattu** [comment]
> > You should not use jellyfin-ffmpeg5 with 10.9. Please don't look at the changelog from years ago to make any deicision
> 
> for the record: jellyfin-ffmpeg5 is mentioned in yesterday's changelog or was your comment not targeted at me?

That is done a year ago before our new CI. Remember the changelog contains 2 years of changes and not all of them reflects to the latest status.

**Comment by boredazfcuk** [comment]
> > > > I couldn't modify the location of ffmpeg in the UI
> > > 
> > > 
> > > This is intentionally removed due to security reasons. Please, please, please, use the `--ffmpeg` cli parameter to configure the ffmpeg location, okay?
> > 
> > 
> > CLI parameter for which command? I'm using the Docker container and don't ever connect to the container to issue commands. Will configuring with the parameter survive container re-creation? I have /config mapped to persistent storage.
> 
> Then it seems like you are not using our official docker container image.
> 
> This cli is straight in our entrypoint:
> 
> https://github.com/jellyfin/jellyfin-packaging/blob/a974263fbfdb924632c0553ceb83588cf75e0272/docker/Dockerfile#L199

Cool. I created my own Dockerfile built from jellyfin/jellyfin and my entrypoint is pointing to a script I wrote. I was then handing over to your entrypoint with:
```
exec "/jellyfin/jellyfin" --datadir "/config" --cachedir "/cache" --ffmpeg "/usr/local/bin/ffmpeg"
```
Seems the relocation of the ffmpeg binary messed it up.

**Comment by Wurzelmann** [comment]
> > > You should not use jellyfin-ffmpeg5 with 10.9. Please don't look at the changelog from years ago to make any deicision
> > 
> > 
> > for the record: jellyfin-ffmpeg5 is mentioned in yesterday's changelog or was your comment not targeted at me?
> 
> That is done a year ago before our new CI. Remember the changelog contains 2 years of changes and not all of them reflects to the latest status.
> 
> We are on ffmpeg6 now, all 10.9 installation should use ffmpeg6

Thanks for clarifying, I just wanted to make sure I did the right thing. Thanks for your work and the support too! <3

**Comment by boredazfcuk** [comment]
Oops. Sorry if I caused any panic lol.
