### ISSUE TITLE
[Issue]: Trickplay image generation failing

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/jellyfin#11556]
### Please describe your bug

Running the trickplay image generation task causes the attached log output.

### Reproduction Steps

1. Enable trickplay image generation on libraries
2. Run the scheduled task
3. Observe logs

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1.79-Unraid
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome 124.0.6367.202 (Official Build) (64-bit) (cohort: M124 Rollout) 
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin 
- Playback Method: N/A
- Hardware Acceleration: VAAPI
- GPU Model: AMD Ryzen 5 PRO 4650G with Radeon Graphics
- Plugins: AniDB, AudioDB, jellyscrub, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Studio Images, Subtitle Extract, TMDb, TMDb Trailers, Trakt, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[2024-05-12 18:27:00.886 +09:00] [INF] [41] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for "/data/media/TVShows/Demo/test.mp4" [ID: 9859214e-8bfc-87c4-a04e-642cf2f6f57d]
[2024-05-12 18:27:00.886 +09:00] [INF] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vaapi=va@dr -init_hw_device vulkan=vk@dr -filter_hw_device vk -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/data/media/Demo/test.mp4\" -noautoscale -an -sn -vf \"fps=0.5,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,hwmap=derive_device=vulkan,format=vulkan,libplacebo=upscaler=none:downscaler=none:w=320:h=146:format=bgra:tonemapping=bt.2390:peak_detect=0:color_primaries=bt709:color_trc=bt709:colorspace=bt709,hwmap=derive_device=vaapi,format=vaapi,scale_vaapi=format=nv12\" -threads 1 -c:v mjpeg_vaapi -qscale:v 4 -f image2 \"/config/cache/temp/8ceea609869e46e681dcaeff4282d38d/%08d.jpg\""
[2024-05-12 18:27:01.667 +09:00] [ERR] [39] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Try disable hardware encoding for trickplay and see if it would success.

**Comment by ericswpark** [comment]
@gnattu thanks, seems like the following option was the culprit:

<img width="665" alt="image" src="https://github.com/jellyfin/jellyfin/assets/13326074/8278be96-7f05-407a-bdb2-6fecadb16106">

Unchecked it and ran the task again and now it's progressing fine.

I am using VAAPI though; maybe an incompatibility with AMD GPUs? Feel free to close the issue if this is intended behavior.

**Comment by gnattu** [comment]
The mjpeg encoder has a very limited hardware platform support, and I don't think it is compatible with anything but Intel atm.

**Comment by gnattu** [comment]
Closing as hardware compatibility issue

**Comment by gnattu** [comment]
> @gnattu I'm seeing this using an Intel GPU (A380) with 10.9.1 when hardware encoding is enabled - for whatever reason, though, I'm seeing ffmpeg's stderr in logs. The error I'm seeing is `[mjpeg_vaapi @ 0x557871ed2480] Invalid quality value 472 (must be 1-100)`. Is there anything actionable that could be done (on Jellyfin's side) to fix this or is it just a matter of needing to leave hardware encoding off until the hardware encoder matures?
> 
> FWIW, execing into the container and manually running the `ffmpeg` command with lower `qscale` values does yield changes, but the only value that works is 0, which isn't even in the documented valid range for that value (1-31). 1 still yields `Invalid quality value 118 (must be 1-100)`

Hardware encoders use different definition of quality. For VAAPI, what you are specifying is the quant and will be multiplied by 118 to get the real quality but that one ranges from 1-100. Such conversion probably should be handled by server otherwise the user can only use the default value.

**Comment by Therkelsen** [comment]
I'm having the same issue running on a Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz which does support QSV.
`[2024-06-13 03:00:00.412 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:00.483 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:00.617 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:02.836 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:02.882 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:02.927 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:02.971 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.016 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.060 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.103 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.148 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.191 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.234 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:03.279 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:05.919 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:07.894 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:13.051 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:15.566 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:18.328 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-13 03:00:20.592 +02:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)`

**Comment by HerrDoktor9001** [comment]
Can confirm the issue persists in the latest version of Jellyfin (10.10.7), using an Intel i5-4590 CPU (as far as I'm aware, a QSV supporting CPU). Disabling hardware encoding as suggested above fixes the issue. With it enabled I get the following error spam: 

```
[2025-10-02` 11:37:58.581 **:**] [ERR] [109] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(IReadOnlyList`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, LibraryOptions libraryOptions, CancellationToken `cancellationToken)
```

**Comment by gnattu** [comment]
> Can confirm the issue persists in the latest version of Jellyfin (10.10.7), using an Intel i5-4590 CPU (as far as I'm aware, a QSV supporting CPU). Disabling hardware encoding as suggested above fixes the issue. With it enabled I get the following error spam:
> 
> ```
> [2025-10-02` 11:37:58.581 **:**] [ERR] [109] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
> System.ArgumentException: Can't create trickplay from 0 images.
>    at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(IReadOnlyList`1 images, Int32 width, TrickplayOptions options, String outputDir)
>    at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, LibraryOptions libraryOptions, CancellationToken `cancellationToken)
> ```

https://github.com/jellyfin/jellyfin/issues/14432#issuecomment-3045609027

Haswell CPU has poor platform support for its mjpeg encoder.
