### ISSUE TITLE
[Issue]: [10.9.0] An unhandled exception was thrown by the application

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin#11563]
### Please describe your bug

I am not sure, it was in the log after the sever slowed down.

### Reproduction Steps

I am not sure.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:ubuntu
- Linux Kernel: N/A
- Virtualization: no
- Clients: ATV
- Browser: N/A
- FFmpeg Version: 6.0
- Playback Method: ATV
- Hardware Acceleration: VAAPI
- GPU Model:none
- Plugins: Skip intro + Jellyfin plugins
- Reverse Proxy: no
- Base URL: N.A
- Networking: local
- Storage: local
```

### Jellyfin logs

```shell
[ERR] Connection id "" "", Request id "" "": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (6533602 of 6533316).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Internal.FileResultHelper.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by David-Moreira** [comment]
I've just updated to 10.9 and I also noticed jellyfin started crashing when playing a video sometime after, it could be 10m it could be 30mI really couldn't tell exactly, so I also can't tell what might trigger it. By checking the logs I've seen a similar error with content mismatch. Since I personally don't have alot of time to troubleshoot I reverted back to a backup in v10.8.13

But I'd like if we can keep an eye on this and figuring out what triggers this behaviour.

**Comment by David-Moreira** [comment]
I see. I can confirm that I am also using the same `intro-skipper` plugin.

**Comment by gnattu** [comment]
If you are having issues with scanning causing the server to hang, can you try reduce the scan concurrency to a conservative value like 1? It is located in the Dashboard -> General the performance section. The default concurrency value could be too high for your disk and causing all kinds of IO hang.

**Comment by jumoog** [comment]
Please try scanning without the plugin

**Comment by David-Moreira** [comment]
> Everything was fine until I told it to scan but is the issue jellyfin or the plugin and is this issue anything to do with the server becoming completely unresponsive?

Oh in my case even though I do have the same plugin `intro-skipper plugin` it was not scanning, as I only scan on "off-hours". 
I had this behaviour at least 3 times before going ahead and just reverting back to my backup since I don't have time to troubleshoot today.
So I wouldn't be so sure it's an issue with the scanning?

**Comment by jumoog** [comment]
Scanning works fine. I notice that it removes old TV series from the DB that no longer exist. But after scanning everything went fine. Overall very high IO.

**Comment by jumoog** [comment]
Whats your ulimit?

**Comment by gnattu** [comment]
> @gnattu There was no number set,
> 
> Parallel library scan tasks limit is now 4 Parallel image encoding limit is now 2
> 
> @David-Moreira that to me says it might not be the plugin.

No number set = 2* logical cpu count, a very high concurrency

**Comment by David-Moreira** [comment]
@VampiricAlien are you able to reproduce the issue though? In order to properly test these settings you're changing?

**Comment by gnattu** [comment]
> @gnattu Would be a good idea in the text field to mention CPU count.

We plan to reduce the concurrency to a more conservative number in the future because this default value is too high for most of the underlying disks.

**Comment by Raul824** [comment]
could anyone tell me how is the intro skipper working in jellyfin 10.9.
I tried uninstalling and reinstalling from the fork of Bobby306 but it always says Not Supported post installation.

**Comment by David-Moreira** [comment]
@VampiricAlien how's it been with 10.9.1?

**Comment by David-Moreira** [comment]
@VampiricAlien have you tried **10.9.2**?
