### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by luky92** [jellyfin/jellyfin#11562]
### Please describe your bug

upgrade from 10.813 to 10.9.0

### Reproduction Steps

migrate jellyfin 10.8.13 to 10.9.0 with empty string rating  rating 

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:Docker linux server image 
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
llyfin   | [13:20:34] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateRatingLevels: Recalculating parental rating levels based on rating string.
jellyfin   | [13:20:34] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateRatingLevels'
jellyfin   | System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
jellyfin   |    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
jellyfin   |    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
jellyfin   |    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
jellyfin   |    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
jellyfin   |    at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
jellyfin   |    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
jellyfin   | [13:20:34] [FTL] [1] Main: Error while starting server
jellyfin   | System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
jellyfin   |    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
jellyfin   |    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
jellyfin   |    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(Str
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Duplicate #11532
