### ISSUE TITLE
[Issue]: "Connection Failure" when trying to log in

### ISSUE THREAD

**Issue by roydbt** [jellyfin/jellyfin#11574]
### Please describe your bug

I've jsut updated to 10.9.0, and when I went to check the new web interface there was no media on the home page. I tried to disconnect and reconnect, only to discover that I can't log in using the same credentials as before. The full message is:
```
Connection Failure
We're unable to connect to the selected server right now. Please ensure it is running and try again.
```
I could not get more complete logs as right now it is stuck on the loading spinner in the web interface and no exceptions were thrown in the logs, only the first few line over and over again.

### Reproduction Steps

1. Log on to the web interface
2. Notice how the spinner is still there despite everything loaded up
3. Click on "Manual Login"
4. Enter your credentials
5. See this error on screen

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Raspberry Pi OS bookworm
- Linux Kernel: 6.6.20+rpt-rpi-2712
- Virtualization: Docker
- Clients: Browser
- Browser: Safari 17.4.1
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: NAT
- Storage: local
```

### Jellyfin logs

```shell
[21:29:09] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[21:29:09] [INF] [22] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Invalid token. URL GET /socket.
[21:29:09] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [INF] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:09] [ERR] [22] Microsoft.EntityFrameworkCore.Query: An exception occurred while iterating over the results of a query for context type 'Jellyfin.Server.Implementations.JellyfinDbContext'.
System.ArgumentException: The value cannot be an empty string. (Parameter 'passwordResetProviderId')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method43(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
System.ArgumentException: The value cannot be an empty string. (Parameter 'passwordResetProviderId')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method43(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
[21:29:09] [ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /users/public.
System.ArgumentException: The value cannot be an empty string. (Parameter 'passwordResetProviderId')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method43(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Jellyfin.Server.Implementations.Users.UserManager.get_Users()
   at Jellyfin.Api.Controllers.UserController.Get(Nullable`1 isHidden, Nullable`1 isDisabled, Boolean filterByDevice, Boolean filterByNetwork)
   at Jellyfin.Api.Controllers.UserController.GetPublicUsers()
   at lambda_method18(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[21:29:15] [INF] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:15] [INF] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:15] [INF] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[21:29:15] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:15] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[21:29:15] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
You somehow have a user without a password reset provider.
Shutdown Jellyfin and run the following sql statement:

```
sqlite3 jellyfin.db "UPDATE Users SET PasswordResetProviderId='Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' WHERE PasswordResetProviderId IS NULL;"
```

**Comment by roydbt** [comment]
The web still won't load, only showing a loading spinner

**Comment by crobibero** [comment]
Try clearing your browser cache

**Comment by crobibero** [comment]
Closing as the original issue is fixed. Since you seem to be encountering a different issue, please open a new issue with fresh logs and description.

**Comment by ACR-Jeff** [comment]
I am confused as to why this was closed, The OP never stated the issue was solved? I have this same issue, Yet nothing has solved it for me, It would be great to have more info on this without being closed prematurely.

**Comment by roydbt** [comment]
For me running:
‘’’
sqlite3 jellyfin.db "UPDATE Users SET PasswordResetProviderId='Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' WHERE PasswordResetProviderId IS '';"
‘’’
Solved it (replacing NULL with an empty string)

**Comment by ACR-Jeff** [comment]
> For me running:
> 
> ```
> sqlite3 jellyfin.db "UPDATE Users SET PasswordResetProviderId='Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' WHERE PasswordResetProviderId IS '';"
> ```
> 
> Solved it (replacing NULL with an empty string)

Thank you, I will give this a try
