### ISSUE TITLE
[Issue]: service not binding and server not reachable 

### ISSUE THREAD

**Issue by spupuz** [jellyfin/jellyfin#11593]
### Please describe your bug

when startick the docker stack the serve try to bind the tcp ports but fails
using brdiged or host mode in docker do not change, the stack was working correctly wit previous version of jellyifin:

```
version: '3.5'
services:
  jellyfin:
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
     # - /dev/dri/kfd:/dev/dri/kfd # Remove this device if you don't use the OpenCL tone-mapping
    #image: jellyfin/jellyfin:unstable
    #network_mode: host
    image: jellyfin/jellyfin
    user: 1000:1000
    group_add:
      - "117" # Change this to match your "render" host group id and remove this comment
      - "44" # Change this to match your "video" host group id and remove this comment
    environment:
      - ROC_ENABLE_PRE_VEGA=1
    container_name: jellyfin
    volumes:
      - /zfsfiles/DockerConfig/jellyfin/cache:/cache
      - /zfsfiles/DockerConfig/jellyfin/config:/config
      - /zfsfiles/Music:/data/music
      - /zfsfiles/Movies:/data/movies
      - /zfsfiles/TV:/data/tvshows
      - /zfsfiles/books:/data/books
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096/tcp
      - 8920:8920/tcp
    restart: 'unless-stopped'
```

### Reproduction Steps

mostly this is the problem i got in logs:

[08:11:38] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[08:11:38] [FTL] [1] Main: Error while starting server

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: debian (OMV) docker
- Linux Kernel: proxmox kernel 6.5
- Virtualization: docker
- Clients: -
- Browser: -
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: VAAPI
- GPU Model: Radeon XT 550
- Plugins: 
- Reverse Proxy: NGINX PROXY MANAGER
- Base URL:
- Networking: bridged docker
- Storage: ZFS raid
```

### Jellyfin logs

```shell
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "192.168.112.2"]
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[08:11:35] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniDB 8.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniList 7.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniSearch 5.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bookshelf 11.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Fanart 11.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Kitsu 5.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OPDS Feed 5.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Open Subtitles 20.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 14.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 15.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Session Cleaner 3.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Simkl 5.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Subtitle Extract 3.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 11.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb Box Sets 11.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TVmaze 11.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: VGMdb 4.0.0.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.1.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.1.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.1.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.1.0
[08:11:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.1.0
[08:11:38] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[08:11:38] [FTL] [1] Main: Error while starting server
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Simkl.API.SimklApi' while attempting to activate 'Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[08:11:38] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[08:11:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[08:11:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[08:11:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[08:11:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
[08:11:39] [INF] [1] Main: Jellyfin version: 10.9.1
[08:11:39] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]"]
[08:11:39] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[08:11:39] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[08:11:39] [INF] [1] Main: Architecture: X64
[08:11:39] [INF] [1] Main: 64-Bit Process: True
[08:11:39] [INF] [1] Main: User Interactive: True
[08:11:39] [INF] [1] Main: Processor count: 12
[08:11:39] [INF] [1] Main: Program data path: /config
[08:11:39] [INF] [1] Main: Log directory path: /config/log
[08:11:39] [INF] [1] Main: Config directory path: /config/config
[08:11:39] [INF] [1] Main: Cache path: /cache
[08:11:39] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[08:11:39] [INF] [1] Main: Application directory: /jellyfin/
[08:11:39] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[08:11:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniDB, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AniDB_8.0.0.0/Jellyfin.Plugin.AniDB.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniList, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AniList_7.0.0.0/Jellyfin.Plugin.AniList.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniSearch, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AniSearch_5.0.0.0/Jellyfin.Plugin.AniSearch.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bookshelf, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bookshelf_11.0.0.0/Jellyfin.Plugin.Bookshelf.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Fanart_11.0.0.0/Jellyfin.Plugin.Fanart.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 3.0.0.0 of IMVDb 
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 1.4.2.0 of InfuseSync 
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 0.1.7.0 of Intro Skipper 
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Kitsu, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Kitsu_5.0.0.0/Jellyfin.Plugin.Kitsu.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 4.0.0.0 of OPDS 
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Opds, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/OPDS_5.0.0.0/Jellyfin.Plugin.Opds.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Reports_15.0.0.0/Jellyfin.Plugin.Reports.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 16.0.0.0 of Reports 
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Session Cleaner_3.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Simkl, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Simkl_5.0.0.0/Jellyfin.Plugin.Simkl.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Subtitle Extract_3.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_11.0.0.0/Tvdb.Sdk.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_11.0.0.0/Jellyfin.Plugin.Tvdb.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TVmaze_11.0.0.0/TvMaze.Api.Client.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TVmaze_11.0.0.0/Flurl.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TvMaze, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TVmaze_11.0.0.0/Jellyfin.Plugin.TvMaze.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TVmaze_11.0.0.0/Flurl.Http.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc from /config/plugins/TVmaze_11.0.0.0/Polly.dll
[08:11:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Vgmdb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/VGMdb_4.0.0.0/Jellyfin.Plugin.Vgmdb.dll
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "192.168.112.2"]
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[08:11:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
```

### FFmpeg logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
The version of Simkl plugin no longer compatible with current Jellyfin.

**Comment by spupuz** [comment]
so how can i remove it if the sever does not start?

**Comment by gnattu** [comment]
Go to your data folder, look for the plugin folder and remove this plugin.

**Comment by spupuz** [comment]
you made my day!!! great what was this plugin for?

**Comment by gnattu** [comment]
> you made my day!!! great what was this plugin for?

https://github.com/jellyfin/jellyfin-plugin-simkl

If you don’t know what’s that for then no need to install
