### ISSUE TITLE
Jellyfin not starting after update to 10.9 and 10.9.1

### ISSUE THREAD

**Issue by riddertommie** [jellyfin/jellyfin#11595]
### Please describe your bug

Using Docker (linuxserver/jellyfin:latest) After yesterday update 10.9 no contact possible with jellyfin server. Normaly I wait for 1 or 2 days to see if tere is a update. This morning there was 10.9.1 but after updating stil no contact with server. 

Don't know what to do here, any help welcome.

### Reproduction Steps

Upgrading to 10.9 
Upgrading to 10.9.1

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS:Ubuntu
- Linux Kernel:
- Virtualization: Docker
- Clients: Jellyfin for Kodi, jellyfin for android tv, jellyfin for android.
- Browser: Brave, Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Yes
- Base URL: 
- Networking: 
- Storage:
```

### Jellyfin logs

```shell
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
**** permissions for /dev/dri/card0 are good ****
**** permissions for /dev/dri/renderD128 are good ****
[custom-init] No custom files found, skipping...
[11:43:20] [INF] [1] Main: Jellyfin version: 10.9.1
[11:43:20] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_PublishedServerUrl, 192.168.2.200]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
[11:43:20] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[11:43:20] [INF] [1] Main: Operating system: Ubuntu 22.04.4 LTS
[11:43:20] [INF] [1] Main: Architecture: X64
[11:43:20] [INF] [1] Main: 64-Bit Process: True
[11:43:20] [INF] [1] Main: User Interactive: True
[11:43:20] [INF] [1] Main: Processor count: 4
[11:43:20] [INF] [1] Main: Program data path: /config/data
[11:43:20] [INF] [1] Main: Log directory path: /config/log
[11:43:20] [INF] [1] Main: Config directory path: /config
[11:43:20] [INF] [1] Main: Cache path: /config/cache
[11:43:20] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[11:43:20] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[11:43:21] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[11:43:22] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Fanart_11.0.0.0/Jellyfin.Plugin.Fanart.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Kodi Sync Queue_10.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LiteDB, Version=5.0.19.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from /config/data/plugins/Kodi Sync Queue_10.0.0.0/LiteDB.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MediaCleaner, Version=2.15.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Media Cleaner_2.15.0.0/MediaCleaner.dll
[11:43:22] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'.
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /config/data/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /config/data/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /config/data/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /config/data/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /config/data/plugins/Reports_17.0.0.0/ClosedXML.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Session Cleaner_3.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Subtitle Extract_4.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_11.0.0.0/Tvdb.Sdk.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_11.0.0.0/Jellyfin.Plugin.Tvdb.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TVmaze_11.0.0.0/Flurl.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TVmaze_11.0.0.0/TvMaze.Api.Client.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc from /config/data/plugins/TVmaze_11.0.0.0/Polly.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TvMaze, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TVmaze_11.0.0.0/Jellyfin.Plugin.TvMaze.dll
[11:43:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TVmaze_11.0.0.0/Flurl.Http.dll
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["192.168.2.0/24"]
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["192.168.2.0/24"]
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[11:43:22] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Fanart 11.0.0.0
[11:43:26] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.KodiSyncQueuePlugin: KodiSyncQueue is starting...
[11:43:26] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Kodi Sync Queue 10.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Media Cleaner 2.15.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 14.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 17.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Session Cleaner 3.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Subtitle Extract 4.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 11.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb Box Sets 11.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TVmaze 11.0.0.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.1.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.1.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.1.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.1.0
[11:43:26] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.1.0
[11:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[11:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: EventMonitorEntryPoint Running
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite version: 3.41.2
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-9.4.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_FOREIGN_KEYS,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_MATH_FUNCTIONS,ENABLE_RTREE,ENABLE_SNAPSHOT,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=32766,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for /config/data/data/playback_reporting.db is delete
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Initialize PlaybackActivity Repository
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: PlaybackActivity table schema OK
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Expected : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
[11:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Received : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
[11:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {107010c3-6cdb-40cd-af78-a1d0f15773be} may be persisted to storage in unencrypted form.
[11:43:28] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: /run/s6-rc:s6-rc-init:aGolKd/servicedirs/svc-jellyfin/wwwroot. Static files may be unavailable.
[11:43:28] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[11:43:28] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask: Retention task scheduled
[11:43:28] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /config/data/data/collections
[11:43:28] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /mnt/raid0/Music
[11:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: TaskCleanDb Loaded
[11:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskRunBackup: TaskRunBackup Loaded
[11:43:28] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /data/tvshows
[11:43:28] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /data/movies
[11:43:28] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Remove Old Sync Data set to fire at 2024-05-14 00:01:00.000 +02:00, which is 12:17:31.1513585 from now.
[11:43:28] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Playback Reporting Trim Db set to fire at 2024-05-14 00:00:00.000 +02:00, which is 12:16:31.1403301 from now.
[11:43:28] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Generate Trickplay Images set to fire at 2024-05-14 03:00:00.000 +02:00, which is 15:16:31.1236423 from now.
[11:43:28] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2024-05-14 02:00:00.000 +02:00, which is 14:16:31.1209710 from now.
[11:43:28] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 6.0.1
[11:43:29] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[11:43:29] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[11:43:29] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[11:43:29] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[11:43:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: VAAPI device /dev/dri/renderD128 is Intel GPU (iHD)
[11:43:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: VAAPI device /dev/dri/renderD128 supports Vulkan DRM interop
[11:43:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
[11:43:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 38e20968656648dbbd697793d3bdac31
[11:43:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[11:43:30] [INF] [1] Main: Startup complete 0:00:10.5221568
[11:43:31] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean up collections and playlists Completed after 0 minute(s) and 0 seconds
[11:43:34] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
You are having incompatible plugin MergeVersions please remove it from your plugin folder

**Comment by riddertommie** [comment]
Hi gnattu, i tought it was none related but i removed it. got below error:

Same error. 

[11:26:31] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
[11:35:19] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
[11:42:09] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
[11:43:22] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin

**Comment by dancingmadkefka** [comment]
I have pretty much the same issue. I just updated from I think 10.8.3 to 10.9.1. I have restarted a few times and the result is always the same - main GUI loads, can click on menu but not content, can click on dashboard but no other menu, cannnot get into any other page after dashboard. Clicking on movies etc first, causes me not to be able to load the dashboard. 

main errors in log:
[2024-05-13 04:09:07.798 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[2024-05-13 04:09:07.798 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

[2024-05-13 04:09:07.868 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {cbd34b59-ef80-4d6c-94ba-2e7f97109bbb} may be persisted to storage in unencrypted form.
[2024-05-13 04:09:08.632 -07:00] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/run/s6-rc:s6-rc-init:HDEDka/servicedirs/service-jellyfin/wwwroot". Static files may be unavailable.

**Comment by gnattu** [comment]
> I have pretty much the same issue. I just updated from I think 10.8.3 to 10.9.1. I have restarted a few times and the result is always the same - main GUI loads, can click on menu but not content, can click on dashboard but no other menu, cannnot get into any other page after dashboard. Clicking on movies etc first, causes me not to be able to load the dashboard.
> 
> main errors in log: [2024-05-13 04:09:07.798 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage. [2024-05-13 04:09:07.798 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
> 
> [2024-05-13 04:09:07.868 -07:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {cbd34b59-ef80-4d6c-94ba-2e7f97109bbb} may be persisted to storage in unencrypted form. [2024-05-13 04:09:08.632 -07:00] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/run/s6-rc:s6-rc-init:HDEDka/servicedirs/service-jellyfin/wwwroot". Static files may be unavailable.
> 
> Update: works on other devices and browsers, just not on Chrome which I was using. So not sure if it's related to this.

Clear your Chrome cache, you are having a separate issue.

**Comment by gnattu** [comment]
To OP: I noticed that no network interface has been detected, can you follow the instruction here: https://github.com/jellyfin/jellyfin/issues/11548#issuecomment-2106100017

So that the virtual interfaces can be picked up, and see if it would work again?

**Comment by riddertommie** [comment]
Hi, sorry for the late reaction. Busy week.

Clearing the cache from browser (brave) did not work. Deleting network.xml did work. 

Thanks!

**Comment by dwongdev** [comment]
I had the same issue as you. It was something to do with my plugins folder.

1. Stop Jellyfin.
2. I renamed my plugins folder to plugins.backup
(docker/jellyfin/config/plugins).
3. Start Jellyfin. Your Jellyfin should run at this point.
4. It will create a new Plugins folder.
5. Stop Jellyfin.
6. Trial and error. Copy and paste one by one or whatever from plugins.backup into new Plugins folder.
7. Start Jellyfin.
8. Rinse and repeat to find the rogue plugin. Go to Step 5.

(For me, it was Simkl plugin, Jellyfin runs well now. Before couldn't start up. I think it was my portainer/watchtower gone buggy).

Hope this helps.
