### ISSUE TITLE
[Issue]: Database lock blocks my jellyfin server

### ISSUE THREAD

**Issue by derrezzz** [jellyfin/jellyfin#11608]
### Please describe your bug

Since the last update, occasional errors, without particular server activity, persist and force me to restart it.
No problems before update

### Reproduction Steps

Docker container

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Docker Container
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: NPM
- Base URL:
- Networking: 
- Storage: 
```

### Jellyfin logs

```shell
[2024-05-13 18:37:46.147 +02:00] [ERR] [76] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,045"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [78] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,045"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [38] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,046"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [21] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,046"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [11] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,046"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [26] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,045"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [84] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,045"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [20] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,044"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [79] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,046"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [75] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,046"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [86] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,044"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [83] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,052"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [71] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,044"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.147 +02:00] [ERR] [53] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("30,044"ms) [Parameters=["@p10='?' (DbType = Int32), @p0='?' (Size = 32), @p1='?' (Size = 12), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (DbType = DateTime), @p6='?' (Size = 168), @p7='?' (Size = 6), @p8='?' (DbType = Boolean), @p9='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""UPDATE \"Devices\" SET \"AccessToken\" = @p0, \"AppName\" = @p1, \"AppVersion\" = @p2, \"DateCreated\" = @p3, \"DateLastActivity\" = @p4, \"DateModified\" = @p5, \"DeviceId\" = @p6, \"DeviceName\" = @p7, \"IsActive\" = @p8, \"UserId\" = @p9
WHERE \"Id\" = @p10
RETURNING 1;"
[2024-05-13 18:37:46.196 +02:00] [ERR] [79] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Server.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Security.AuthorizationContext.GetAuthorizationInfoFromDictionary(Dictionary`2 auth, IHeaderDictionary headers, IQueryCollection queryString)
   at Jellyfin.Server.Implementations.Security.AuthorizationContext.GetAuthorizationInfoFromDictionary(Dictionary`2 auth, IHeaderDictionary headers, IQueryCollection queryString)
   at Jellyfin.Server.Implementations.Security.AuthorizationContext.GetAuthorizationInfo(HttpRequest requestContext)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrCosmo** [comment]
Possible duplicate #11589

**Comment by felix920506** [comment]
should already be fixed
