### ISSUE TITLE
[Issue]: Virtual items treated like real items cause log spam at each Library Scan

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin#11609]
### Please describe your bug

At each Library Scan in the log appeared lines of virtual (path empty) items removal, also if in previous Library Scan the exactly same lines appears in the log.
The strange thing is that such virtual items (representing series episodes missing in my library, in my case specials, various unknown items, etc.) seems are treated as real items, at point that after virtual item removal tvdb/tvmaze scan starts and obviously fails as there is no real data in virtual items.
I see this behavior when I add in the library files represented by virtual items but it is not the case (none of such file is present in my library).

During Library Scan I collected (at debug level) what happens in relation at a single virtual item (that to the progressive number I isolated them). In the first part there is the virtual item removal attempt (skipped as it is virtual). In the second part the error on tvdb/tvmaze metadata parsing.
Log lines posted (always the first part sometimes the second part) are repeated for each virtual item not removed at each Library Scan (only name and id changes).

I not see any effect of this issue at exception of extra log lines (normally only INF/WRN visible), that does not appear in Jellyfin 10.8.x.

Maybe there are dirty virtual items in my library that Library Scan is unable to remove?

### Reproduction Steps

Run Library Scan (same log lines appears at each Library Scan)

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian RPi4
- Virtualization: Docker (linuxserver image)
- Clients: Jellyfin Media Player, Android TV
- Browser: Firefox
- Plugins: AudioDB v10.9.1.0; MusicBrainz v10.9.1.0; OMDb v10.9.1.0; Studio Images v10.9.1.0; Subtitle Extract v4.0.0.0; TMDb Box Sets v11.0.0.0; TMDb v10.9.1.0; TVmaze v11.0.0.0; TheTVDB v11.0.0.0
```

### Jellyfin logs

```shell
# First part
[2024-05-13 19:12:34.396 +02:00] [DBG] [58] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Delete VirtualItem "<ITEM_NAME>" - S00E23
[2024-05-13 19:12:34.397 +02:00] [INF] [58] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "<ITEM_NAME>", Path: "", Id: 858225a4-25c1-caa0-1455-e2afbed053c2
[2024-05-13 19:12:34.401 +02:00] [DBG] [58] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: "OnLibraryManagerItemRemoved": Refreshing "<ITEM_NAME>" [0]
[2024-05-13 19:12:34.402 +02:00] [DBG] [58] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Skip: "Updated item is Virtual".
# Second part
[2024-05-13 19:12:42.584 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "ProbeProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.584 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "TvdbEpisodeProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.960 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "TvMazeEpisodeProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.960 +02:00] [DBG] [54] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata] Starting for "<ITEM_NAME>"
[2024-05-13 19:12:42.961 +02:00] [WRN] [54] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadataInternal(EpisodeInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2024-05-13 19:12:42.961 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: "TvMazeEpisodeProvider" returned no metadata for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "TmdbEpisodeProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: "TmdbEpisodeProvider" returned no metadata for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "OmdbEpisodeProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: "OmdbEpisodeProvider" returned no metadata for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "TrickplayProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.962 +02:00] [DBG] [54] MediaBrowser.Providers.TV.EpisodeMetadataService: Running "SubsMetadataProvider" for "<ITEM_NAME>"
[2024-05-13 19:12:42.967 +02:00] [DBG] [54] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: "OnLibraryManagerItemUpdated": Refreshing Item "<ITEM_NAME>" [None, MetadataDownload]
[2024-05-13 19:12:42.967 +02:00] [DBG] [54] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Skip: Updated item is "Virtual".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> I not see any effect of this issue at exception of extra log lines (normally only INF/WRN visible), that does not appear in Jellyfin 10.8.x.


So I would think this is a non-issue. The season handling is changed in 10.9 and if the result is correct I would not mind such logging too much.

**Comment by RealGreenDragon** [comment]
> > I not see any effect of this issue at exception of extra log lines (normally only INF/WRN visible), that does not appear in Jellyfin 10.8.x.
> 
> So I would think this is a non-issue. The season handling is changed in 10.9 and if the result is correct I would not mind such logging too much.

Can be true, but I think that having in logs a spam of INF/WRN messages related at elements not present (and probably will be never) in my library.
Absurdly, if I have only 1 on 100 episodes of a series (often more including specials) at every Library Scan (or series selective scan of new/updated files) 99 totally useless (unless maybe in debug) log lines will be added in log files.
In my opinion at informational level logs should be cleaner as possible to help troubleshooting.

**Comment by RealGreenDragon** [comment]
I found that the cause of Virtual Items spam is the "missing episodes fetcher" metadata downloader.

Since I'm not interested in this function I disabled it.

Now both Virtual Items logs and "System.ArgumentException: season" logs disappeared.

I believe Virtual Items logs are part of standard "missing episodes fetcher" work, but I'm unsure if also "System.ArgumentException: season" logs are normal.

Notice me if more testing in this is required (as I disabled "missing episodes fetcher" in v10.9.11 and the "System.ArgumentException: season" logs are still present).
