### ISSUE TITLE
[Issue]: Docker container Jellyfin crashing after 10.9 update

### ISSUE THREAD

**Issue by sk0003mk** [jellyfin/jellyfin#11611]
### Please describe your bug

After upgrading to 10.9, the container keeps crashing each time it starts. Running it on Synology Docker, DSM 7.2, see logs below.

### Reproduction Steps

None.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Synology Docker
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'FixPlaylistOwner'

System.TypeInitializationException: The type initializer for 'ICU4N.Text.Transliterator' threw an exception.

 ---> System.TypeInitializationException: The type initializer for 'ICU4N.Globalization.UCultureInfo' threw an exception.

 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')

en is an invalid culture identifier.

   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)

   at ICU4N.Globalization.UCultureInfo..cctor()

   --- End of inner exception stack trace ---

   at ICU4N.Globalization.UCultureInfo.get_CurrentCulture()

   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, OpenType openType)

   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.<>c__DisplayClass25_0.<GetRootType>b__0(String key)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at ICU4N.Util.UResourceBundle.GetRootType(String baseName, Assembly root)

   at ICU4N.Util.UResourceBundle.InstantiateBundle(String baseName, String localeName, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root)

   at ICU4N.Text.Transliterator..cctor()

   --- End of inner exception stack trace ---

   at ICU4N.Text.Transliterator.GetInstance(String id)

   at Jellyfin.Extensions.StringExtensions.<>c.<.cctor>b__8_0()

   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)

   at System.Lazy`1.CreateValue()

   at Jellyfin.Extensions.StringExtensions.Transliterated(String text)

   at MediaBrowser.Controller.Entities.BaseItem.ModifySortChunks(ReadOnlySpan`1 name)

   at MediaBrowser.Controller.Entities.BaseItem.CreateSortName()

   at MediaBrowser.Controller.Entities.BaseItem.get_SortName()

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(SqliteConnection db, IEnumerable`1 tuples)

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)

   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)

   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()

   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)

[14:52:10] [FTL] [1] Main: Error while starting server

System.TypeInitializationException: The type initializer for 'ICU4N.Text.Transliterator' threw an exception.

 ---> System.TypeInitializationException: The type initializer for 'ICU4N.Globalization.UCultureInfo' threw an exception.

 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')

en is an invalid culture identifier.

   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)

   at ICU4N.Globalization.UCultureInfo..cctor()

   --- End of inner exception stack trace ---

   at ICU4N.Globalization.UCultureInfo.get_CurrentCulture()

   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, OpenType openType)

   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.<>c__DisplayClass25_0.<GetRootType>b__0(String key)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at ICU4N.Util.UResourceBundle.GetRootType(String baseName, Assembly root)

   at ICU4N.Util.UResourceBundle.InstantiateBundle(String baseName, String localeName, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root, Boolean disableFallback)

   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root)

   at ICU4N.Text.Transliterator..cctor()

   --- End of inner exception stack trace ---

   at ICU4N.Text.Transliterator.GetInstance(String id)

   at Jellyfin.Extensions.StringExtensions.<>c.<.cctor>b__8_0()

   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)

   at System.Lazy`1.CreateValue()

   at Jellyfin.Extensions.StringExtensions.Transliterated(String text)

   at MediaBrowser.Controller.Entities.BaseItem.ModifySortChunks(ReadOnlySpan`1 name)

   at MediaBrowser.Controller.Entities.BaseItem.CreateSortName()

   at MediaBrowser.Controller.Entities.BaseItem.get_SortName()

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(SqliteConnection db, IEnumerable`1 tuples)

   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)

   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)

   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()

   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)

   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)

   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)

[14:52:10] [INF] [1] Main: Running query planner optimizations in the database... This might take a while

[14:52:10] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost

[14:52:10] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider

[14:52:10] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider

[14:52:10] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
> Docker users: If you encounter problems loading your homepage, you may need to remove the DOTNET_SYSTEM_GLOBALIZATION_INVARIANT environment variable from your container, as this is no longer valid in Jellyfin 10.9.0. For more details please see these issues.

https://jellyfin.org/posts/jellyfin-release-10.9.0#key-release-notesbreaking-changes
