### ISSUE TITLE
[Issue]: Home Videos & Photos Showing Folder for Multiple CDs

### ISSUE THREAD

**Issue by JasonHorkles** [jellyfin/jellyfin#11616]
### Please describe your bug

I have a Home Videos and Photos library with a couple folders with the item name. Inside said folders is Film-cd1.mp4 and so on. This works as usual with regular movie libraries, but on Home Videos and Photos, it shows a folder for the item first and then has a single film within that folder. The discs show properly when clicking that film, but I don't think that folder should be there (rather just the first film instead).

### Reproduction Steps

1. Create a Home Videos and Photos library
2. Create a folder in the source directory with whatever name
3. In said folder, add at least 2 videos with -cd1 and -cd2 respectively
4. Refresh library and see that there's now a folder that only goes to the -cd1 file and shows nothing extra

### Jellyfin Version

10.9.0

### if other:

N/A

### Environment

```markdown
- OS: Ubuntu server 22.04.4 LTS
- Linux Kernel: 6.5.13-3-pve
- Virtualization: LXC
- Clients: Any
- Browser: Any
- FFmpeg Version: 6.0.1
- Playback Method: N/A
- Hardware Acceleration: AMD AMF
- GPU Model: Ryzen 7 5700G
- Plugins: AudioDB, DLNA, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Session Cleaner, Studio Images, Subtitle Extract, TMDb, Webhook
- Reverse Proxy: Nginx
- Base URL: None
- Networking: Proxmox bridge
- Storage: Local
```

### Jellyfin logs

```shell
[2024-05-13 18:45:05.944 -06:00] [INF] Jellyfin version: "10.9.0"
[2024-05-13 18:45:06.014 -06:00] [INF] Environment Variables: ["[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS --datadir $JELLYFIN_DATA_DIR --configdir $JELLYFIN_CONFIG_DIR --logdir $JELLYFIN_LOG_DIR --cachedir $JELLYFIN_CACHE_DIR]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]"]
[2024-05-13 18:45:06.016 -06:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-05-13 18:45:06.016 -06:00] [INF] Operating system: "Ubuntu 22.04.4 LTS"
[2024-05-13 18:45:06.016 -06:00] [INF] Architecture: X64
[2024-05-13 18:45:06.016 -06:00] [INF] 64-Bit Process: True
[2024-05-13 18:45:06.016 -06:00] [INF] User Interactive: True
[2024-05-13 18:45:06.016 -06:00] [INF] Processor count: 8
[2024-05-13 18:45:06.016 -06:00] [INF] Program data path: "/var/lib/jellyfin"
[2024-05-13 18:45:06.016 -06:00] [INF] Log directory path: "/var/log/jellyfin"
[2024-05-13 18:45:06.016 -06:00] [INF] Config directory path: "/etc/jellyfin"
[2024-05-13 18:45:06.016 -06:00] [INF] Cache path: "/var/cache/jellyfin"
[2024-05-13 18:45:06.016 -06:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2024-05-13 18:45:06.017 -06:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2024-05-13 18:45:06.292 -06:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-05-13 18:45:06.471 -06:00] [INF] Loading assemblies
[2024-05-13 18:45:06.537 -06:00] [INF] Loaded assembly "Nick.Plugin.Jellyscrub, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Jellyscrub_2.0.0.0/Nick.Plugin.Jellyscrub.dll"
[2024-05-13 18:45:06.554 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2024-05-13 18:45:06.560 -06:00] [INF] Loaded assembly "SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll"
[2024-05-13 18:45:06.560 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2024-05-13 18:45:06.620 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll"
[2024-05-13 18:45:06.639 -06:00] [INF] Loaded assembly "ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll"
[2024-05-13 18:45:06.643 -06:00] [INF] Loaded assembly "SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll"
[2024-05-13 18:45:06.648 -06:00] [INF] Loaded assembly "System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll"
[2024-05-13 18:45:06.710 -06:00] [INF] Loaded assembly "DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll"
[2024-05-13 18:45:06.712 -06:00] [INF] Loaded assembly "ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll"
[2024-05-13 18:45:06.714 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.SessionCleaner, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Session Cleaner_3.0.0.0/Jellyfin.Plugin.SessionCleaner.dll"
[2024-05-13 18:45:06.716 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.SubtitleExtract, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Subtitle Extract_3.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll"
[2024-05-13 18:45:06.788 -06:00] [INF] Loaded assembly "MQTTnet, Version=4.3.3.952, Culture=neutral, PublicKeyToken=fdb7629f2e364a63" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/MQTTnet.dll"
[2024-05-13 18:45:06.809 -06:00] [INF] Loaded assembly "BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/BouncyCastle.Cryptography.dll"
[2024-05-13 18:45:06.811 -06:00] [INF] Loaded assembly "Jellyfin.Plugin.Webhook, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/Jellyfin.Plugin.Webhook.dll"
[2024-05-13 18:45:06.812 -06:00] [INF] Loaded assembly "MQTTnet.Extensions.ManagedClient, Version=4.3.3.952, Culture=neutral, PublicKeyToken=fdb7629f2e364a63" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/MQTTnet.Extensions.ManagedClient.dll"
[2024-05-13 18:45:06.819 -06:00] [INF] Loaded assembly "MimeKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/MimeKit.dll"
[2024-05-13 18:45:06.825 -06:00] [INF] Loaded assembly "Handlebars, Version=2.1.6.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/Handlebars.dll"
[2024-05-13 18:45:06.834 -06:00] [INF] Loaded assembly "MailKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b" from "/var/lib/jellyfin/plugins/Webhook_12.0.0.0/MailKit.dll"
[2024-05-13 18:45:06.914 -06:00] [INF] Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-13 18:45:06.914 -06:00] [INF] Defined LAN exclusions: []
[2024-05-13 18:45:06.914 -06:00] [INF] Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-13 18:45:06.915 -06:00] [INF] Using bind addresses: ["127.0.0.1", "192.168.1.7"]
[2024-05-13 18:45:06.915 -06:00] [INF] Remote IP filter is "Allowlist"
[2024-05-13 18:45:06.915 -06:00] [INF] Filter list: []
[2024-05-13 18:45:08.263 -06:00] [WRN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2024-05-13 18:45:08.263 -06:00] [WRN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2024-05-13 18:45:08.263 -06:00] [WRN] PLEASE VISIT THE JELLYSCRUB PLUGIN CONFIG PAGE TO CONVERT TRICKPLAY FILES
[2024-05-13 18:45:08.263 -06:00] [WRN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2024-05-13 18:45:08.263 -06:00] [WRN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2024-05-13 18:45:08.272 -06:00] [INF] Attempting to inject trickplay script code in "/usr/share/jellyfin/web/index.html"
[2024-05-13 18:45:08.277 -06:00] [ERR] Encountered exception while writing to "/usr/share/jellyfin/web/index.html": "System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Nick.Plugin.Jellyscrub.JellyscrubPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)"
[2024-05-13 18:45:08.281 -06:00] [INF] Loaded plugin: "Jellyscrub" "2.0.0.0"
[2024-05-13 18:45:08.286 -06:00] [INF] Loaded plugin: "Open Subtitles" "20.0.0.0"
[2024-05-13 18:45:08.288 -06:00] [INF] Loaded plugin: "Playback Reporting" "14.0.0.0"
[2024-05-13 18:45:08.288 -06:00] [INF] Loaded plugin: "Reports" "17.0.0.0"
[2024-05-13 18:45:08.289 -06:00] [INF] Loaded plugin: "Session Cleaner" "3.0.0.0"
[2024-05-13 18:45:08.290 -06:00] [INF] Loaded plugin: "Subtitle Extract" "3.0.0.0"
[2024-05-13 18:45:08.290 -06:00] [INF] Loaded plugin: "Webhook" "12.0.0.0"
[2024-05-13 18:45:08.291 -06:00] [INF] Loaded plugin: "TMDb" "10.9.0.0"
[2024-05-13 18:45:08.291 -06:00] [INF] Loaded plugin: "Studio Images" "10.9.0.0"
[2024-05-13 18:45:08.291 -06:00] [INF] Loaded plugin: "OMDb" "10.9.0.0"
[2024-05-13 18:45:08.304 -06:00] [INF] Loaded plugin: "MusicBrainz" "10.9.0.0"
[2024-05-13 18:45:08.304 -06:00] [INF] Loaded plugin: "AudioDB" "10.9.0.0"
[2024-05-13 18:45:08.356 -06:00] [INF] Kestrel is listening on "127.0.0.1"
[2024-05-13 18:45:08.357 -06:00] [INF] Kestrel is listening on "192.168.1.7"
[2024-05-13 18:45:08.362 -06:00] [INF] EventMonitorEntryPoint Running
[2024-05-13 18:45:08.367 -06:00] [INF] Sqlite version: 3.41.2
[2024-05-13 18:45:08.368 -06:00] [INF] Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-9.4.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_FOREIGN_KEYS,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_MATH_FUNCTIONS,ENABLE_RTREE,ENABLE_SNAPSHOT,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=32766,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1
[2024-05-13 18:45:08.375 -06:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/playback_reporting.db" is "delete"
[2024-05-13 18:45:08.376 -06:00] [INF] Initialize PlaybackActivity Repository
[2024-05-13 18:45:08.381 -06:00] [INF] PlaybackActivity table schema OK
[2024-05-13 18:45:08.381 -06:00] [INF] Expected : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2024-05-13 18:45:08.381 -06:00] [INF] Received : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2024-05-13 18:45:08.517 -06:00] [INF] Starting NAT discovery
[2024-05-13 18:45:08.843 -06:00] [WRN] The WebRootPath was not found: "/var/lib/jellyfin/wwwroot". Static files may be unavailable.
[2024-05-13 18:45:08.889 -06:00] [INF] Watching directory "/mnt/movies2/Kids"
[2024-05-13 18:45:08.889 -06:00] [INF] Running startup tasks
[2024-05-13 18:45:08.889 -06:00] [INF] Watching directory "/mnt/movies2/Christmas"
[2024-05-13 18:45:08.890 -06:00] [INF] Watching directory "/mnt/movies2/The Archives"
[2024-05-13 18:45:08.890 -06:00] [INF] TaskCleanDb Loaded
[2024-05-13 18:45:08.891 -06:00] [INF] Watching directory "/mnt/movies2/Religious"
[2024-05-13 18:45:08.891 -06:00] [INF] Watching directory "/mnt/movies2/Shows"
[2024-05-13 18:45:08.891 -06:00] [INF] TaskRunBackup Loaded
[2024-05-13 18:45:08.900 -06:00] [INF] Watching directory "/mnt/movies1/Movies"
[2024-05-13 18:45:08.901 -06:00] [INF] Daily trigger for "Playback Reporting Trim Db" set to fire at 2024-05-14 00:00:00.000 -06:00, which is 05:14:51.0981148 from now.
[2024-05-13 18:45:08.915 -06:00] [INF] Daily trigger for "Generate Trickplay Images" set to fire at 2024-05-14 03:00:00.000 -06:00, which is 08:14:51.0844698 from now.
[2024-05-13 18:45:08.916 -06:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 2024-05-14 02:00:00.000 -06:00, which is 07:14:51.0834262 from now.
[2024-05-13 18:45:09.010 -06:00] [INF] Found ffmpeg version "6.0.1"
[2024-05-13 18:45:09.049 -06:00] [INF] Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-05-13 18:45:09.064 -06:00] [INF] Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-05-13 18:45:09.080 -06:00] [INF] Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-05-13 18:45:09.159 -06:00] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-05-13 18:45:09.259 -06:00] [INF] FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-05-13 18:45:09.260 -06:00] [INF] ServerId: "e9bfb2938e084c3184c50acfe461800f"
[2024-05-13 18:45:09.260 -06:00] [INF] Core startup complete
[2024-05-13 18:45:09.260 -06:00] [INF] Startup complete 0:00:03.6601184
```

### Please attach any screenshots here

Folder:
![image](https://github.com/jellyfin/jellyfin/assets/51760372/9eb2733d-ed89-40f0-b546-f2d99522e1de)
Inside folder:
![image](https://github.com/jellyfin/jellyfin/assets/51760372/86e2e896-ba00-41bb-93e6-5612bbb4abc2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonHorkles** [comment]
Issue is still happening

**Comment by JasonHorkles** [comment]
Still an issue

**Comment by theguymadmax** [comment]
This isn’t a bug; your naming scheme is triggering the [additional parts feature](https://jellyfin.org/docs/general/server/media/movies#movies-split-across-multiple-parts). To maintain your naming scheme, enclose "cdx" in curly brackets.
film - {cd1}.ext
film - {cd2}.ext

![Image](https://github.com/user-attachments/assets/1e7cf81d-6661-484a-85b3-d1d7c3ce1200)

**Comment by JasonHorkles** [comment]
@theguymadmax that's what I want though. My issue is that it creates a whole new folder for the item rather than having the item be in the library with the rest of the other films

**Comment by JasonHorkles** [comment]
Example: LotR in the middle has 2 CDs to it, but it shows as just 1 film in the library.

![Image](https://github.com/user-attachments/assets/2622b29e-fbac-4799-b7b7-e9bca9a65af5)

However, when it's in a Videos & Photos library, it shows it as a folder first (image 1) and then you can click into the film afterwards (image 2)

![Image](https://github.com/user-attachments/assets/3bb2130c-86a7-4173-8b03-eb94bd80f430)

![Image](https://github.com/user-attachments/assets/d4b66be8-c94f-4cce-93d9-197e5c95e427)

**Comment by theguymadmax** [comment]
The Home Videos and Photos library is not intended to function like a Movies/Shows library. To avoid creating an additional folder level when viewing your library, you should add the folder as a root directory for each multipart CD, as outlined below. Note that library paths cannot be recursive.

Example Library Paths:
```
Library (Home Videos and Photos)
/media/Home Videos/
/media/Home Movies/Baby Animals
/media/Home Movies/Pets
```


Folders should be organized as follows:
```
/media/Home Videos
    video1.mp4
    video2.mp4
    photo1.jpg
   ....

/media/Home Movies/Baby Animals
    Baby Animals - cd1.mp4
    Baby Animals - cd2.mp4

/media/Home Movies/Pets
    Pets - cd1.mp4
    Pets - cd2.mp4
```
