### ISSUE TITLE
[Issue]: Desending is not a valid value for SortOrder

### ISSUE THREAD

**Issue by thermionic** [jellyfin/jellyfin#11645]
### Please describe your bug

While creating a log for a different issue, I saw what appears to be a possible typo in the default 10.9.1 configuration

I have not checked older versions.

Small snippet example as below, instance with 10 lines before and after below
```
System.FormatException: Desending is not a valid value for SortOrder.
 ---> System.ArgumentException: Requested value 'Desending' was not found.
```
No results shown in Github issues or the forum for "Desending"
No results in Google for "Desending is not a valid value for SortOrder"

### Reproduction Steps

1. clean deploy of Jellyfin 10.9.1 docker on Ubuntu 22.04
2. connect with browser and set username and password for initial user
3. login with initial user
4. shut down docker container
5. add logging.json with `"MinimumLevel": "Debug"`
6. start up docker container
7. connect with browser and add "Movie" library
8. browse library
9. extract log with docker log jellyfin > logofile.log
10. see error in log as per description

### Jellyfin Version

10.9.0

### if other:

10.9.1 (not in dropdown)

### Environment

```markdown
- OS: Linux (Ubuntu 22.04)
- Linux Kernel: 6.5.0-35-generic
- Virtualization: Docker
- Clients: Browser
- Browser: Edge 124 
- FFmpeg Version: as per Docker
- Playback Method: n/a
- Hardware Acceleration: QSV
- GPU Model: CometLake-S GT2 (UHD Graphics 630)
- Plugins: only built in
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local for config, NFS for media

Docker Compose

version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    group_add:
      - "109"
    volumes:
      - /mnt/nvme1/jellyfin/jellyfin-config:/config
      - /mnt/nvme1/jellyfin/jellyfin-cache:/cache
      - /mnt/Demo:/Demo
    devices:
     - /dev/dri/renderD128:/dev/dri/renderD128
    network_mode: 'host'
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"

```
```


### Jellyfin logs

```shell
[20:32:14] [DBG] [22] MediaBrowser.Controller.Entities.BaseItem: Movies has no parental rating set.
[20:32:14] [DBG] [22] MediaBrowser.Controller.Entities.BaseItem: Playlists has no parental rating set.
[20:32:14] [DBG] [22] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.53.229:8096/Users/d50bbe2e24a9475ea954efb88ef9e3f8/Items/2260f1e10b17b8ee25d44e3def334928 to 192.168.53.194 in 0:00:00.8429788 with Status Code 200
[20:32:14] [DBG] [22] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[20:32:14] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Movies has no parental rating set.
[20:32:14] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Playlists has no parental rating set.
[20:32:14] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[20:32:14] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[20:32:14] [DBG] [24] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.53.229:8096/Items/2260f1e10b17b8ee25d44e3def334928?userId=d50bbe2e24a9475ea954efb88ef9e3f8 to 192.168.53.194 in 0:00:00.8632441 with Status Code 200
[20:32:14] [DBG] [18] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: Desending is not a valid value for SortOrder.
 ---> System.ArgumentException: Requested value 'Desending' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[20:32:14] [DBG] [18] MediaBrowser.Controller.Entities.BaseItem: Movies has no parental rating set.
[20:32:14] [DBG] [18] MediaBrowser.Controller.Entities.BaseItem: Playlists has no parental rating set.
[20:32:15] [DBG] [24] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[20:32:15] [DBG] [24] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Demo has no parental rating set.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: root has no parental rating set.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Movies has no parental rating set.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Playlists has no parental rating set.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Peter Sallis has no parental rating set.
[20:32:15] [DBG] [24] MediaBrowser.Controller.Entities.BaseItem: Nick Park has no parental rating set.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thermionic** [comment]
[debugwithmetadata.log](https://github.com/jellyfin/jellyfin/files/15313892/debugwithmetadata.log)
 full log

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-web/blob/b87c5693919e7ac60dba8948a53fa3d9e5eefbd8/src/scripts/itemsByName.js#L128
