### ISSUE TITLE
[Issue]: Trickplay throws error when trying to generate files

### ISSUE THREAD

**Issue by kura** [jellyfin/jellyfin#11652]
### Please describe your bug

Jellyfin throws this error when trying to generate trickplay data, but it seems to only do this after most if not all of my trickplay files were generated on a previous run.

Additionally previously it was trying to generate BIF files for a file that does not exist in my library, despite rescanning all libraries and running all clean up jobs.

Hardware acceleration is disabled for trickplay generation.

```
[09:37:55] [ERR] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[09:37:55] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate BIF Files Failed after 0 minute(s) and 0 seconds
```

### Reproduction Steps

1. On my Jellyfin install (Docker container on Linux)
2. With Jellyfin 10.8.x and Jellyscrub 1.1.1.0
3. Generate trickplay `.bif` files, storing in the media library
4. Upgrade to Jellyfin 10.9.1 and Jellyscrub 2.0.0
5. Use Jellyscrub's convert to convert to new trickplay format
6. Use Jellyscrub's checker and delete functionality to delete old trickplay files that have been migrated
7. Disable Jellyscrub and restart
8. Run Jellyfin's Generate BIF files task

### Jellyfin Version

10.9.1

### Environment

```markdown
- OS: Ubuntu 22.04.4 (LTS)
- Linux Kernel: 5.10.60
- Virtualization: Docker
- Clients: Browser, Jellyfin Media Player and Jellyfin AndroidTV
- Browser: Firefox 126.0
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: NVENC
- GPU Model: Nvidia Quadro P2200
- Plugins: AniDB, AudioDB, Cover Art Archive, Fanart, Intro Skipper, Kitsu, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, TVmaze, TheTVDB, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[09:52:33] [ERR] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[09:52:33] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate BIF Files Failed after 0 minute(s) and 0 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
You are using a version of a plugin that isn't fully compatible with 10.9.

**Comment by crobibero** [comment]
Nick.Plugin.Jellyscrub

This line says otherwise

**Comment by kura** [comment]
How... The plugin is removed...?
![2024-05-15_11-11](https://github.com/jellyfin/jellyfin/assets/109507/05629c8b-49d8-434b-a28d-cdd30e2c65bf)

**Comment by JPVenson** [comment]
Removed the plugin _and restarted_?

**Comment by kura** [comment]
It's fine. I'll manually purge the plugins directory later and hope that fixes it. I guess something may have gone wonky when I deleted the plugin from the UI.

**Comment by JackJ74** [comment]
Same line of error on my side when I run the generate BIF image in scheduled task. BUT after I uninstalled Jellyscrub plug-in and restart, the plug-in automatically re-appeared! If I DISABLE Jellyscrub, a downgraded version of Jellyscrub (I.e. v1.0.0.9) will be installed by itself alongside with v1.1.0.0 version of Jellyscrub (in disabled state). The repo for Jellyscrub has been removed. Any idea?
