### ISSUE TITLE
[Issue]: Jellyfin 10.9.1 freezing frequently

### ISSUE THREAD

**Issue by navilg** [jellyfin/jellyfin#11688]
### Please describe your bug

Jellyfin is freezing frequently. I see in log that its because of missing path for a library. But it should not have freezed because of this, instead it should ignore if any library path is not found.

### Reproduction Steps

1. Install jellyfin 10.9.1
2. Have library created with few paths
3. Delete one of the path from server
4. Watch some videos or movie for some time.
5. It is very random and jellyfin keeps freezing.

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel:6.5.0 
- Virtualization: Docker
- Clients: Android, Browser
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[17:07:19] [ERR] [809] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Error validating images for /config/data/root/default/Movies
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/movies/comedy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFiles(String path, IReadOnlyList`1 extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IEnumerable`1 paths, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[17:07:19] [ERR] [809] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Error validating images for /config/data/root/default/TV Shows
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/tvshows/comedy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFiles(String path, IReadOnlyList`1 extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IEnumerable`1 paths, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[17:07:19] [ERR] [809] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Error validating images for /config/data/root/default/Shows
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/tvshows/comedy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFiles(String path, IReadOnlyList`1 extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IEnumerable`1 paths, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Duplicate #11624
