### ISSUE TITLE
[Issue]: Deleted library still shown on home

### ISSUE THREAD

**Issue by Jeefongithub** [jellyfin/jellyfin#11690]
### Please describe your bug

I recently have been troubleshooting some issues with my tv show library. I decided it would be easiest to delete the library and recreate it. I deleted the library however the library is still shown on user home page and the metadata editor. When i try to scan libraries to see if that will remove it the scan fails. I see no relevant error in logs to why it failed

### Reproduction Steps

1. delete tv show library
2. verify library still shown to user
3. scan all libraries
4. verify from tasks scan library failed

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: debian 12
- Linux Kernel:6.5.13
- Virtualization:proxmox
- Clients:web
- Browser:firefox
- FFmpeg Version:
- Playback Method:direct
- Hardware Acceleration:none
- GPU Model:none
- Plugins:tvdb,jellyscrub
- Reverse Proxy:nginx
- Base URL: 192.168.35.7
- Networking: 10GB nic
- Storage:proxmox lxc stored on iscsi lun
```

### Jellyfin logs

```shell
[2024-05-17 04:33:57.650 +00:00] [ERR] Error refreshing owned items for "/var/lib/jellyfin/root/default/TV Shows"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/TV Shows'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2024-05-17 04:33:57.653 +00:00] [ERR] Error in Directory watcher for: "/Storage/Comics"
System.UnauthorizedAccessException: Access to the path '/Storage/Comics/lost+found' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2024-05-17 04:33:57.653 +00:00] [INF] Stopping directory watching for path "/Storage/Comics"
[2024-05-17 04:33:57.654 +00:00] [ERR] Error in Directory watcher for: "/Storage/E-Books"
System.UnauthorizedAccessException: Access to the path '/Storage/E-Books/lost+found' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2024-05-17 04:33:57.654 +00:00] [INF] Stopping directory watching for path "/Storage/E-Books"
[2024-05-17 04:33:57.653 +00:00] [INF] Skipping realtime monitor for "/Storage/Music" because the path does not exist
[2024-05-17 04:33:57.656 +00:00] [INF] Skipping realtime monitor for "/Storage/Music_Videos" because the path does not exist
[2024-05-17 04:33:57.656 +00:00] [ERR] Error executing Scheduled Task
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/TV Shows'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.RequiresRefresh()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken, Boolean removeRoot)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-17 04:33:57.657 +00:00] [INF] "Scan Media Library" Failed after 0 minute(s) and 0 seconds
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/53583661/e658eefa-1e9b-46df-b641-455e4283663e)
![image](https://github.com/jellyfin/jellyfin/assets/53583661/23b8014a-5097-4d84-9645-0131e9a35246)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
fsck is creating `lost+found` folder to your folders where may indicating fs corruption is in place, and jellyfin apparently has no permission to access those folders.

And this will happen if Jellyfin is unable to validate the root folder which is caused by complicated reasons, this really should not happen to a normal setup. Can you try adding back the TV Shows library(with the same name) and delete it again after fixing your fs issue?

Also, 10.9.1 is out and you really should update to that version first.

**Comment by Jeefongithub** [comment]
I probably should have spaced out these changes but updated to 10.9.1 and recreated the library. The issue i was experiencing that caused me to want to delete the library appears to be solved which could be from either of the actions but didn't test in-between. It would appear that I'm all set thanks a ton @gnattu
