### ISSUE TITLE
Error processing request. URL "GET"` for displaying lyrics

### ISSUE THREAD

**Issue by Fabien98** [jellyfin/jellyfin#11708]
### Please describe your bug

The new Lyrics endpoint seems to work randomly.
Some .lrc files are played and some are not.

Here's attached a log of an encountered error

### Reproduction Steps

- The .lrc file is next to the .mp3 file.
- filenames are the same.
- "no lyrics" displayed in the Jellyfin web interface

the lrc file display correctly the lyrics when playing the mp3 with an other local software.
I have other songs with .lrc next to it where the lyrics are displaying flawessly in web interface

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.4-3
- Virtualization: Yes
- Clients: Browser
- Browser: Firefox 126
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: n/a
- Hardware Acceleration: no
- GPU Model: Nvidia
- Plugins: Artwork /AudioDB /Cover Art Archive /Fanart1 /MusicBrainz /Open Subtitles /Playback Reporting /Reports /Studio Images /TMDb /TMDb Box Sets
- Reverse Proxy: none
- Base URL: http://192.168.1.157
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : event_playing_id     = "5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : event_user_id        = "c4aa224cd8cc41a4889ae7de02ec3fba"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : session_playing_id   = "5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : session_user_id      = "c4aa224cd8cc41a4889ae7de02ec3fba"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : e.DeviceName         = "Firefox"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : ItemName             = "Arcade Fire - The Suburbs (The Suburbs)"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : ItemId               = "5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : ItemType             = "Audio"
[2024-05-18 01:02:46.985 +02:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-05-18 01:02:46.985 +02:00] [INF] Playback tracker found, adding playback info : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:02:46.985 +02:00] [INF] Saving playback tracking activity in DB
[2024-05-18 01:02:47.004 +02:00] [INF] StartPlaybackTimer : Exited
[2024-05-18 01:02:47.093 +02:00] [INF] Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:03:05.011 +02:00] [ERR] Error processing request. URL "GET" "/Items".
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[System.Int32]'.
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at MediaBrowser.Controller.Entities.UserViewBuilder.SortAndPage(IEnumerable`1 items, Nullable`1 totalRecordLimit, InternalItemsQuery query, ILibraryManager libraryManager, Boolean enableSorting)
   at MediaBrowser.Controller.Entities.Folder.PostFilterAndSort(IEnumerable`1 items, InternalItemsQuery query, Boolean enableSorting)
   at MediaBrowser.Controller.Entities.Folder.QueryRecursive(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.UserRootFolder.GetItemsInternal(InternalItemsQuery query)
   at Jellyfin.Api.Controllers.ItemsController.GetItems(Nullable`1 userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, Nullable`1 adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isMovie, Nullable`1 isSeries, Nullable`1 isNews, Nullable`1 isKids, Nullable`1 isSports, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, BaseItemKind[] excludeItemTypes, BaseItemKind[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, MediaType[] mediaTypes, ImageType[] imageTypes, ItemSortBy[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
   at lambda_method1314(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-05-18 01:03:08.201 +02:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.9.2" playing "The Suburbs". Stopped at "26029" ms
[2024-05-18 01:03:08.217 +02:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "mp4", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: hls, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], SubtitleProfiles: [] }
[2024-05-18 01:03:08.219 +02:00] [INF] User policy for "fabien". EnableAudioPlaybackTranscoding: True
[2024-05-18 01:03:08.220 +02:00] [INF] Playback stop tracker found, processing stop : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-5224c13d32efb3fa817ce53e1b95b8f4"
[2024-05-18 01:03:08.221 +02:00] [INF] PlaybackTracker : Adding Stop Event : 05/18/2024 01:03:08
[2024-05-18 01:03:08.221 +02:00] [INF] Saving playback tracking activity in DB
[2024-05-18 01:03:08.243 +02:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "mp4", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: hls, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], SubtitleProfiles: [] }
[2024-05-18 01:03:08.248 +02:00] [INF] User policy for "fabien". EnableAudioPlaybackTranscoding: True
[2024-05-18 01:03:08.416 +02:00] [INF] Adding playback tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-0f160696d8a897b8509de1c82f090b2e
[2024-05-18 01:03:08.416 +02:00] [INF] PlaybackTracker : Adding Start Event : 05/18/2024 01:03:08
[2024-05-18 01:03:08.416 +02:00] [INF] Creating StartPlaybackTimer Task
[2024-05-18 01:03:08.416 +02:00] [INF] StartPlaybackTimer : Entered
[2024-05-18 01:03:08.491 +02:00] [INF] Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-0f160696d8a897b8509de1c82f090b2e"
[2024-05-18 01:03:26.998 +02:00] [INF] Refreshing guide with 7 days of guide data
[2024-05-18 01:03:27.012 +02:00] [INF] "Refresh Guide" Completed after 0 minute(s) and 3 seconds
[2024-05-18 01:03:28.416 +02:00] [INF] session.RemoteEndPoint : "192.168.1.136"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : event_playing_id     = "0f160696d8a897b8509de1c82f090b2e"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : event_user_id        = "c4aa224cd8cc41a4889ae7de02ec3fba"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : session_playing_id   = "0f160696d8a897b8509de1c82f090b2e"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : session_user_id      = "c4aa224cd8cc41a4889ae7de02ec3fba"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : e.DeviceName         = "Firefox"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : ItemName             = "Peter Doherty - Last of the English Roses (Grace/Wastelands)"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : ItemId               = "0f160696d8a897b8509de1c82f090b2e"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : ItemType             = "Audio"
[2024-05-18 01:03:28.417 +02:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-05-18 01:03:28.417 +02:00] [INF] Playback tracker found, adding playback info : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-0f160696d8a897b8509de1c82f090b2e"
[2024-05-18 01:03:28.417 +02:00] [INF] Saving playback tracking activity in DB
[2024-05-18 01:03:28.432 +02:00] [INF] StartPlaybackTimer : Exited
[2024-05-18 01:03:28.896 +02:00] [INF] Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE3LjB8MTY5NTc4ODIwNzI0NQ11-c4aa224cd8cc41a4889ae7de02ec3fba-0f160696d8a897b8509de1c82f090b2e"
```

### FFmpeg logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What is your exact naming scheme

**Comment by Fabien98** [comment]
For the first song played _(which is NOT working)_

- 01 - The Suburbs.mp3
- 01 - The Suburbs.lrc
The whole album in this folder is not playing lrc

For the second song played _(which is working)_

- 02 - Last of the English Roses.lrc
- 02 - Last of the English Roses.mp3
The whole album in this folder is OK playing lrc

Naming scheme is the  same in both case

**Comment by crobibero** [comment]
Thanks for sharing your filenames. What about the rest of the paths?

**Comment by Fabien98** [comment]
I should have precised the whole path indeed:

- \\disque 1\Musiques\Peter Doherty\2009 - GraceWastelands\01 - The Suburbs.mp3
- \\disque 1\Musiques\The Arcade Fire\2010- The Suburbs\02 - Last of the English Roses.mp3

**Comment by Fabien98** [comment]
**I'm seeing maybe where the problem could come from.**
For "01 - The Suburbs.mp3" the lrc file has been added to the jellyfin library **AFTER** the .mp3 file (with a specific software)
For "02 - Last of the English Roses.mp3" the lrc file has been added to the jellyfin library **IN THE SAME TIME** than the .mp3 file

I just tried to put some new .lrc with existing songs and it's NOT working.
I added some new songs to the Jellyfin library WITH .lrc files along and it's working.

**So I think it would be fine if Jellyfin could handle .lrc files added subsequently**

**Comment by gnattu** [comment]
Do a find missing metadata scan, will it fix it for you?

**Comment by Fabien98** [comment]
No I should have precised as well, but I have done several metadata scan without luck.
Still the same behaviour.
The .lrc file is not linked with the existing .mp3 file after a scan.

**Comment by Fabien98** [comment]
I recently updated to Jellyfin 10.9.3.
The bug is solved apparently.

I tried to reproduce the bug.

- Upload a new mp3 file WITHOUT .lrc file / metadata scan
- Add the .lrc file / new metadata scan

The lyrics are now displayed event if the .lrc file is added susbequently.
Thanks!
