### ISSUE TITLE
[Issue]: "Unable to convert any images to local" errors

### ISSUE THREAD

**Issue by ch6574** [jellyfin/jellyfin#11703]
### Please describe your bug

I see a lot of errors in the log, one example is as follows:

```
May 17 21:50:10 jellyfin jellyfin[223]: [21:50:10] [WRN] Unable to precache https://json.schedulesdirect.org/20141201/image/5d0a0460c75452c2fff0e2c950e7c98db7f245b7d233822da909bff72b36025f.jpg?toke>
May 17 21:50:10 jellyfin jellyfin[223]: System.InvalidOperationException: Unable to convert any images to local
May 17 21:50:10 jellyfin jellyfin[223]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
May 17 21:50:10 jellyfin jellyfin[223]:    at Jellyfin.LiveTv.Guide.GuideManager.<>c__DisplayClass21_0.<<PrecacheImages>b__2>d.MoveNext()
```

Also this:

```
May 17 21:57:42 jellyfin jellyfin[223]: [21:57:42] [ERR] Error processing request. URL GET /Items/2f44280097eb7bd56e6b48f12d1226a1/Images/Primary.
May 17 21:57:42 jellyfin jellyfin[223]: System.InvalidOperationException: Unable to convert any images to local
May 17 21:57:42 jellyfin jellyfin[223]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 format, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
May 17 21:57:42 jellyfin jellyfin[223]:    at lambda_method1121(Closure, Object)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Reproduction Steps

1. Jellyfin 10.9.2 (or 10.9.1, and earlier)
2. Refresh the live TV guide data against Schedules Direct
3. Observe the first example error in the log

Also 
1. Browse to something in the library (e.g. a movie) that has a "More  Like This" entry for a TV show with no image
2. Observe the second error in the log.

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.4-3-pve
- Virtualization: Yes (lxc container)
- Clients: Browser
- Browser: Firefox 125
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: n/a
- Hardware Acceleration: vaapi
- GPU Model: Intel iHD
- Plugins: none
- Reverse Proxy: none
- Base URL: n/a
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
May 17 21:57:42 jellyfin jellyfin[223]: [21:57:42] [ERR] Error processing request. URL GET /Items/2f44280097eb7bd56e6b48f12d1226a1/Images/Primary.
May 17 21:57:42 jellyfin jellyfin[223]: System.InvalidOperationException: Unable to convert any images to local
May 17 21:57:42 jellyfin jellyfin[223]:    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 format, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
May 17 21:57:42 jellyfin jellyfin[223]:    at lambda_method1121(Closure, Object)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 17 21:57:42 jellyfin jellyfin[223]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
May 17 21:57:42 jellyfin jellyfin[223]:    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
The error just means that Jellyfin did not find any image for the entity, so it can't save anything to its local image store.

**Comment by ch6574** [comment]
OK, but should it be filling up the log with stack traces if this is a normal event?

**Comment by mjohl** [comment]
This is flooding the log for no reason and should be scaled down to the info level at best.
Clean log and TV Guide refresh and the log gets peppered.

![Screenshot 2024-06-25 065910](https://github.com/jellyfin/jellyfin/assets/4193377/8a1aa35d-5acf-4298-942e-93ef8c5e9d28)

**Comment by mjohl** [comment]
Any update on this? I pulled the code and commented out the log entry. Based on the comments above, it should by info or debug level, not error. And if it is an error, guidance to resolving would be nice.

**Comment by Aetherinox** [comment]
Agreed. I am diagnosing an issue, and this gets spammed in console while I'm trying to look for more important things.

**Comment by brianjmurrell** [comment]
Can this issue be reopened please?

If there is nothing the user is required to do to rectify this, it really shouldn't be spamming the log at `ERR` level as others have suggested.

**Comment by Mateleo** [comment]
`ImageSaver.GetStandardSavePath` should fall back to sniffing magic bytes when `Content-Type` is missing, exactly like every browser does.
Is it possible to reopen the issue ?
