### ISSUE TITLE
[Issue]: Jellyfin stop working, invalid address or port bind

### ISSUE THREAD

**Issue by doctorase** [jellyfin/jellyfin#11716]
### Please describe your bug

1.- Docker Jellyfin server in synology NAS managed with portainer stack

My Jellyfin was working fine, but a few days ago it suddenly stopped working with this error in portainer log.

I've searched a bit on internet and it seems a port issue, that something else is using the same port, but i didn't added any new container and any of my containers is using the same port. I've read the nerwork.xml file, but i'm not sure if i need to change something. 

This is the content in nerwork.xml
`<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <BaseUrl />
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <CertificatePath />
  <CertificatePassword />
  <InternalHttpPort>8096</InternalHttpPort>
  <InternalHttpsPort>8920</InternalHttpsPort>
  <PublicHttpPort>8096</PublicHttpPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <AutoDiscovery>true</AutoDiscovery>
  <EnableUPnP>false</EnableUPnP>
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>false</EnableIPv6>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <LocalNetworkSubnets />
  <LocalNetworkAddresses />
  <KnownProxies />
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>
    <string>veth</string>
  </VirtualInterfaceNames>
  <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
  <PublishedServerUriBySubnet />
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
</NetworkConfiguration>`

Any idea how to solve it?

### Reproduction Steps

1.-  Restart/Start conatiner 
2.- The error is shown in the conatiner logs and Jellyfin adress doesn't work

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Synology NAS (linux)
- Linux Kernel:
- Virtualization: Docker
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Synology reverse proxy
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[14:40:14] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[14:40:14] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[14:40:14] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
[14:40:16] [INF] [1] Main: Jellyfin version: 10.9.2
[14:40:16] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_PublishedServerUrl, https://jellyfin.ron2012.synology.me]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
[14:40:16] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[14:40:16] [INF] [1] Main: Operating system: Ubuntu 22.04.4 LTS
[14:40:16] [INF] [1] Main: Architecture: X64
[14:40:16] [INF] [1] Main: 64-Bit Process: True
[14:40:16] [INF] [1] Main: User Interactive: True
[14:40:16] [INF] [1] Main: Processor count: 4
[14:40:16] [INF] [1] Main: Program data path: /config/data
[14:40:16] [INF] [1] Main: Log directory path: /config/log
[14:40:16] [INF] [1] Main: Config directory path: /config
[14:40:16] [INF] [1] Main: Cache path: /config/cache
[14:40:16] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[14:40:16] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[14:40:16] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[14:40:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 2.9.0.0 of Ani-Sync 
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 3.0.0.0 of Ani-Sync 
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 0.1.7.0 of Intro Skipper 
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Simkl, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Simkl_5.0.0.0/Jellyfin.Plugin.Simkl.dll
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Skin Manager_2.0.1/Jellyfin.Plugin.SkinManager.dll
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 1.2103.2821.743 of TheMovieDb 
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 10.0.0.0 of TheTVDB 
[14:40:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Trakt, Version=25.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Trakt_25.0.0.0/Trakt.dll
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.20.0.12"]
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[14:40:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 14.0.0.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Simkl 5.0.0.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Skin Manager 2.0.1
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Trakt 25.0.0.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.2.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.2.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.2.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.2.0
[14:40:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.2.0
[14:40:29] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[14:40:29] [FTL] [1] Main: Error while starting server
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Simkl.API.SimklApi' while attempting to activate 'Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[14:40:29] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[14:40:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[14:40:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[14:40:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[14:40:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
[14:40:31] [INF] [1] Main: Jellyfin version: 10.9.2
[14:40:31] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_PublishedServerUrl, https://jellyfin.XXXX.synology.me]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
[14:40:31] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[14:40:31] [INF] [1] Main: Operating system: Ubuntu 22.04.4 LTS
[14:40:31] [INF] [1] Main: Architecture: X64
[14:40:31] [INF] [1] Main: 64-Bit Process: True
[14:40:31] [INF] [1] Main: User Interactive: True
[14:40:31] [INF] [1] Main: Processor count: 4
[14:40:31] [INF] [1] Main: Program data path: /config/data
[14:40:31] [INF] [1] Main: Log directory path: /config/log
[14:40:31] [INF] [1] Main: Config directory path: /config
[14:40:31] [INF] [1] Main: Cache path: /config/cache
[14:40:31] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[14:40:31] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[14:40:32] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[14:40:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 2.9.0.0 of Ani-Sync 
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 3.0.0.0 of Ani-Sync 
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 0.1.7.0 of Intro Skipper 
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Simkl, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Simkl_5.0.0.0/Jellyfin.Plugin.Simkl.dll
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Skin Manager_2.0.1/Jellyfin.Plugin.SkinManager.dll
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 1.2103.2821.743 of TheMovieDb 
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 10.0.0.0 of TheTVDB 
[14:40:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Trakt, Version=25.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Trakt_25.0.0.0/Trakt.dll
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.20.0.12"]
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[14:40:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> Jellyfin.Plugin.Simkl.API.SimklApi

It is clear that you are using an outdated plugin that prevents jellyfin from start. Go to your data folder and remove that dll

**Comment by doctorase** [comment]
It works! Thanks for your time!
