### ISSUE TITLE
[Issue]: Cant scan my library after update to 10.9.2

### ISSUE THREAD

**Issue by mihavidakovic** [jellyfin/jellyfin#11714]
### Please describe your bug

When I try to scan my library for new movies/series the process fails. No new stuff gets added that are new on my HDD. 

### Reproduction Steps

I run jellyfin in Docker on my linux machine. Here is my docker-compose.yml:

```
services:
  jellyfin:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "jellyfin"

    devices:
      - "/dev/dri:dev/dri"
      - "/dev/nvidia-caps:/dev/nvidia-caps"
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"

    entrypoint:
      - "/jellyfin/jellyfin"

    environment:
      - "JELLYFIN_PublishedServerUrl=https://video.miha.dev"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HEALTHCHECK_URL=http://localhost:8096/health"
      - "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"
      - "LC_ALL=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "JELLYFIN_DATA_DIR=/config"
      - "JELLYFIN_CACHE_DIR=/cache"
      - "JELLYFIN_CONFIG_DIR=/config/config"
      - "JELLYFIN_LOG_DIR=/config/log"
      - "JELLYFIN_WEB_DIR=/jellyfin/jellyfin-web"
      - "JELLYFIN_FFMPEG=/usr/lib/jellyfin-ffmpeg/ffmpeg"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "MALLOC_TRIM_THRESHOLD_=131072"

    expose:
      - "8096/tcp"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    hostname: "myhserver"

    image: "jellyfin/jellyfin:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "ee46b940eaaa54aec852823ba4a2f39da8516de8215d2dff5cfe14edaddaf7af"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:b27de364af61892a0d4f2d51bd3f84d13a43a640854dc534cb33b14110529c8d"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "jellyfin"
      com.docker.compose.project.config_files: "/home/myh/services/jellyfin/docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/myh/services/jellyfin"
      com.docker.compose.service: "jellyfin"
      com.docker.compose.version: "2.18.1"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    privileged: true

    restart: "unless-stopped"

    security_opt:
      - "label=disable"

    volumes:
      - "/mnt/disk2/media/cache:/cache"
      - "/mnt/disk2/media/config:/config"
      - "/mnt/disk2/media:/media"

version: "3.6"
```

### Jellyfin Version

Master branch

### if other:

10.9.2

### Environment

```markdown
- OS:Linux
- Linux Kernel:
- Virtualization:Docker
- Clients:Browser
- Browser:Brave
```

### Jellyfin logs

```shell
[2024-05-18 12:01:54.576 +00:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Preišči knjižnico predstavnosti" Failed after 0 minute(s) and 0 seconds
[2024-05-18 12:01:54.613 +00:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies"
[2024-05-18 12:01:54.619 +00:00] [INF] [30] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/series"
[2024-05-18 12:02:23.813 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-05-18 12:02:53.815 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-05-18 12:03:23.813 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-05-18 12:03:53.814 +00:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-05-18 12:04:06.751 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/movies"
[2024-05-18 12:04:06.752 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/series"
[2024-05-18 12:04:06.753 +00:00] [INF] [31] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-05-18 12:04:06.756 +00:00] [WRN] [31] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-05-18 12:04:06.773 +00:00] [WRN] [22] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-05-18 12:04:07.146 +00:00] [ERR] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.TypeInitializationException: The type initializer for 'ICU4N.Text.Transliterator' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ICU4N.Globalization.UCultureInfo' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at ICU4N.Globalization.UCultureInfo..cctor()
   --- End of inner exception stack trace ---
   at ICU4N.Globalization.UCultureInfo.get_CurrentCulture()
   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, OpenType openType)
   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.<>c__DisplayClass25_0.<GetRootType>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ICU4N.Util.UResourceBundle.GetRootType(String baseName, Assembly root)
   at ICU4N.Util.UResourceBundle.InstantiateBundle(String baseName, String localeName, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root)
   at ICU4N.Text.Transliterator..cctor()
   --- End of inner exception stack trace ---
   at ICU4N.Text.Transliterator.GetInstance(String id)
   at Jellyfin.Extensions.StringExtensions.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Jellyfin.Extensions.StringExtensions.Transliterated(String text)
   at MediaBrowser.Controller.Entities.BaseItem.ModifySortChunks(ReadOnlySpan`1 name)
   at MediaBrowser.Controller.Entities.BaseItem.CreateSortName()
   at MediaBrowser.Controller.Entities.BaseItem.get_SortName()
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(SqliteConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-18 12:04:07.148 +00:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Preišči knjižnico predstavnosti" Failed after 0 minute(s) and 0 seconds
[2024-05-18 12:04:07.187 +00:00] [INF] [28] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/series"
[2024-05-18 12:04:07.187 +00:00] [INF] [23] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/movies"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
```
"DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"
```

Remove this enviroment

**Comment by mihavidakovic** [comment]
> ```
> "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"
> ```
> 
> Remove this env var

This fixed my issue. Thank you!

**Comment by MoonOverMiami** [comment]
Please fix this. 10.9.2 is not working. Serious bug in any type of scan. They all fail at some point.

I've tried scanning just one library, all folders, etc. It stops scanning.

**Comment by cvium** [comment]
Wrong issue you are writing in.

**Comment by MoonOverMiami** [comment]
Libraries will not complete a scan. Both All or This library only complete partial scan.
Synology DS1621+. 32 gb RAM.
Jellyfin 10.9.2
