### ISSUE TITLE
[Issue]: Trickplay unable to set process priority

### ISSUE THREAD

**Issue by NotSaifA** [jellyfin/jellyfin#11727]
### Please describe your bug

When setting trickplay process priority to anything higher than normal I get a permission denied error. The image generation still completes successfully.

### Reproduction Steps

With log level set to 'Debug' 
1. Set trickplay process priority to High or Above normal in GUI.
2. Run 'Generate Trickplay Images' scheduled task
3. See error in logs

### Jellyfin Version

10.9.2

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: 5.15.0-107-generic
- Virtualization: Docker version 26.1.3
- FFmpeg Version: 6.0.1-Jellyfin
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[2024-05-18 19:44:23.563 -04:00] [DBG] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Generate Trickplay Images"
[2024-05-18 19:44:23.567 -04:00] [DBG] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Trickplay refresh for 22593b6d-9d68-6609-d027-ab4fe14b9d63 (replace existing: False)
[2024-05-18 19:44:23.575 -04:00] [DBG] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Found existing trickplay files for 22593b6d-9d68-6609-d027-ab4fe14b9d63. Exiting
[2024-05-18 19:44:23.575 -04:00] [DBG] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Trickplay refresh for 2f843d77-e6b1-92f5-7da4-4e98ba087eac (replace existing: False)
[2024-05-18 19:44:23.577 -04:00] [DBG] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Found existing trickplay files for 2f843d77-e6b1-92f5-7da4-4e98ba087eac. Exiting
[2024-05-18 19:44:23.578 -04:00] [DBG] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Trickplay refresh for 967bd68c-ab04-7f5a-2989-97a518bf2bdb (replace existing: False)
[2024-05-18 19:44:23.579 -04:00] [INF] [44] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for "/data/media/tv/show/Season 01/S01E06.mkv" [ID: 967bd68c-ab04-7f5a-2989-97a518bf2bdb]
[2024-05-18 19:44:23.579 -04:00] [INF] [44] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 16 -noautorotate -i file:\"/data/media/tv/show/Season 01/S01E06.mkv\" -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,320)/2)*2:trunc(ow/a/2)*2,format=yuv420p\" -threads 16 -c:v mjpeg -qscale:v 4 -f image2 \"/cache/temp/d6a6165dd2e441a5a361d621e9f9fd5b/%08d.jpg\""
[2024-05-18 19:44:23.581 -04:00] [DBG] [44] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Unable to set process priority to High for "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 16 -noautorotate -i file:\"/data/media/tv/show/Season 01/S01E06.mkv\" -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,320)/2)*2:trunc(ow/a/2)*2,format=yuv420p\" -threads 16 -c:v mjpeg -qscale:v 4 -f image2 \"/cache/temp/d6a6165dd2e441a5a361d621e9f9fd5b/%08d.jpg\""
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractVideoImagesOnIntervalInternal(String inputArg, String filterParam, String vidEncoder, Nullable`1 outputThreads, Nullable`1 qualityScale, Nullable`1 priority, CancellationToken cancellationToken)
[2024-05-18 20:00:31.072 -04:00] [INF] [39] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Finished creation of trickplay files for "/data/media/tv/show/Season 01/S01E06.mkv"
[2024-05-18 20:00:31.076 -04:00] [DBG] [39] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Trickplay refresh for c90a6a97-6d8b-9f39-0dc7-feebc0dd1560 (replace existing: False)
[2024-05-18 20:00:31.079 -04:00] [INF] [39] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for "/data/media/tv/show/Season 01/S01E03.mkv" [ID: c90a6a97-6d8b-9f39-0dc7-feebc0dd1560]
[2024-05-18 20:00:31.080 -04:00] [INF] [39] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 16 -noautorotate -i file:\"/data/media/tv/show/Season 01/S01E03.mkv\" -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,320)/2)*2:trunc(ow/a/2)*2,format=yuv420p\" -threads 16 -c:v mjpeg -qscale:v 4 -f image2 \"/cache/temp/7c4222b77dcd4eb8af373e8a5f5c0809/%08d.jpg\""
[2024-05-18 20:00:31.080 -04:00] [DBG] [39] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Unable to set process priority to High for "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 16 -noautorotate -i file:\"/data/media/tv/show/Season 01/S01E03.mkv\" -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,320)/2)*2:trunc(ow/a/2)*2,format=yuv420p\" -threads 16 -c:v mjpeg -qscale:v 4 -f image2 \"/cache/temp/7c4222b77dcd4eb8af373e8a5f5c0809/%08d.jpg\""
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractVideoImagesOnIntervalInternal(String inputArg, String filterParam, String vidEncoder, Nullable`1 outputThreads, Nullable`1 qualityScale, Nullable`1 priority, CancellationToken cancellationToken)
[2024-05-18 20:14:04.910 -04:00] [INF] [63] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Finished creation of trickplay files for "/data/media/tv/show/Season 01/S01E03.mkv"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
I think you have to run as root/use a privileged container to set such priority. But using such priority is a bad idea anyway as trickplay is a long-running process and will use up almost all CPU time if you make it above normal.
