### ISSUE TITLE
[Issue]: 'Emby.Server.Implementations.Session.SessionManager' Cannot access a disposed object.

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin#11720]
### Please describe your bug

restarting the server via dashboard

### Reproduction Steps

- start a movie
- restart via dashboard

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- Virtualization: Docker
```

### Jellyfin logs

```shell
2024-05-18T18:19:44.868942154Z [20:19:44] [ERR] [43] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:19:44.868975574Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:19:44.868981683Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:19:44.868987033Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:19:44.868992413Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:19:45.160988032Z [20:19:45] [ERR] [54] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:19:45.161016101Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:19:45.161020581Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:19:45.161024371Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:19:45.161028221Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This seems like a non-issue as the server is restarting. Are you experiencing issues that you think these errors are related to?

**Comment by jumoog** [comment]
Yes, not sure if this is related, but sometimes I do not see the playback progress that I need for my plugin autoskip functionality.

**Comment by felix920506** [comment]
If the server is getting restarted mid playback leading to issues then there's really not much we can do. 

Please open a separate report for your playback progress problem.

**Comment by felix920506** [comment]
Welp I was just told that it shouldn't happen anymore in 10.9.10
