### ISSUE TITLE
[Issue]: Can't add films with multiple versions to collections (After update to 10.9.x)

### ISSUE THREAD

**Issue by lukaslindnermusic** [jellyfin/jellyfin#11736]
### Please describe your bug

I have a collection for a film series where I have multiple versions for each film (01 - 4K UHD HDR, 02 - HD, 03 - DVD).

After the update, they all disappeared from the collection (except one).
They still were added in the xml file (config > data > collections > My Collection [boxset] > collection.xml). I removed them from the xml file and then did a library scan. Then I tried to re-add them. A film with just one version is no problem, but if I try to re-add a film with multiple versions, the film path to the first/default version gets added to the collection.xml file, but it does not show up in the collection itself. 

With my Film library, all versions are there and play just fine. I just can't add them to the collection.

However, two films stayed in the collection with all versions. I just can't pinpoint why. There are no noticeable differences.

The problem was introduced with the update from 10.8.13 to 10.9.1 and it stayed with the update to 10.9.2.

### Reproduction Steps

1. Add a film with multiple versions to a film library
2. Add that film to a collection
3. Check if it appears in the collection

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: DSM 7.2.1-69057 Update 5 (Synology)
- Linux Kernel: /
- Virtualization: Docker
- Clients: Jellyfin Media Player on Intel Mac, Jellyfin Web
- Browser: Safari 17.4.1
- FFmpeg Version: the one that came with the docker image
- Playback Method: /
- Hardware Acceleration: none
- GPU Model: /
- Plugins: AudioDB, Jellyscrub (already migrated), MusicBrainz, OMDb, Playback Reporting, Studio Images, TMDb, Webhook
- Reverse Proxy: /
- Base URL: /
- Networking: Host
- Storage: Local RAID5
```

### Jellyfin logs

```shell
Somehow, the adding to a collection does not get logged.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by photonconvergence** [comment]
I'm able to reproduce. Had one item partially disappear from a collection as described above.

Created a test collection (did not allow to search internet for images and metadata) and added a number of movies with multiple versions. All movies were detected, automatically identified and grouped by Jellyfin. Below is the folder structure and file naming for each movie. Items in bold were correctly added to the test collection. The other movies did not appear.

3D Rarities Volume II (2020)
 |_3D Rarities Volume II (2020) - Corazon y la Espada.mkv
 |_3D Rarities Volume II (2020) - Shorts.mk3d
 |_3D Rarities Volume II (2020) - The Stereo Photography of Harold Lloyd.mkv
 
**The 40 Year Old Virgin (2005)
 |_The 40 Year Old Virgin (2005) - Theatrical Cut.mkv
 |_The 40 Year Old Virgin (2005) - Unrated Cut.mkv
 |_deleted scenes
 |_extras
 |_featurettes
 |_trailers**

**1917 (2019)
 |_1917 (2019) - 1080p.mkv
 |_1917 (2019) - 2160p.mkv
 |_featurettes**
 
**The Accountant (2016)
 |_The Accountant (2016) - 1080p.mkv
 |_The Accountant (2016) - 2160p.mkv
 |_featurettes**

The Adventures of Tintin (2011)
 |_The Adventures of Tintin (2011) - 2D.mkv
 |_The Adventures of Tintin (2011) - 3D.mkv
 |_featurettes
 
Alien (1979)
 |_Alien (1979) - 2003 Director's cut.mkv
 |_Alien (1979) - Theatrical Cut.mkv
 |_extras
 |_featurettes
 
**Alien Resurrection (1997)
 |_Alien Resurrection (1997) - Special Edition.mkv
 |_Alien Resurrection (1997) - Theatrical Edition.mkv
 |_featurettes**
 
Aladdin (1994)
 |_Aladdin (1994) - 1080p.mkv
 |_Aladdin (1994) - 2160p.mkv
 |_Aladdin (1994) - Singalong - 1080p.mkv
 |_deleted scenes
 |_extras
 |_featurettes

 Logs - this is what shows in the log every time an item is added to the test collection:
```
[2024-05-19 11:29:53.034 -07:00] [ERR] [27] MediaBrowser.Providers.BoxSets.BoxSetMetadataService: Error in "Dynamic Image Provider"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/metadata/library/75/75f6ac62f33b8e0b6468e72cb1268e37/poster.jpg'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateSingleImage(IEnumerable`1 itemsWithImages, String outputPathWithoutExtension, ImageType imageType)
   at Emby.Server.Implementations.Collections.CollectionImageProvider.CreateImage(BaseItem item, IReadOnlyCollection`1 itemsWithImages, String outputPathWithoutExtension, ImageType imageType, Int32 imageIndex)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, IReadOnlyList`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-19 11:29:58.041 -07:00] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
[2024-05-19 11:29:58.152 -07:00] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Updated 1 items
[2024-05-19 11:29:58.152 -07:00] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished library sync, taking "00:00:00.1109316"
```

Additional note - The item that disappeared from a collection on upgrade from 10.8.13 is able to be added to other collections without issue and appears as it should with all versions.  However, deleting it from the original collection and re-adding it to the same collection results in only one version appearing.

**Comment by ashanrath** [comment]
Also reproduced, doesn't appear to be any work around. Attempted to disable the plugin and re-enable, including manually deleting the Collections library and associated directory. No luck.

**Comment by lukaslindnermusic** [comment]
> Additional note - The item that disappeared from a collection on upgrade from 10.8.13 is able to be added to other collections without issue and appears as it should with all versions. However, deleting it from the original collection and re-adding it to the same collection results in only one version appearing.

I tried this. For me, this does not work. Neither with another collection that already existed nor with a newly created one.
However, with the newly created one, as the item I tried to add is the only one, the artwork for the collection itself gets set to the movie artwork. But when I open the collection, the movie (with three versions) does not appear and I only get a empty collection screen. Also, the artwork in the collection view itself does not appear, it only appears in the collections list view.

There is no folder.jpg or backdrop.jpg in the newly created Test Collection folder (config > data > collections > Test [boxset]) but the collection.xml is there with the first version of the movie correctly added to it. 

With the collection that already existed, the first version of the movie as well got added to the collection.xml.

**Comment by lukaslindnermusic** [comment]
> Also reproduced, doesn't appear to be any work around. Attempted to disable the plugin and re-enable, including manually deleting the Collections library and associated directory. No luck.

what plugin did you try to disable?

**Comment by ashanrath** [comment]
> > Also reproduced, doesn't appear to be any work around. Attempted to disable the plugin and re-enable, including manually deleting the Collections library and associated directory. No luck.
> 
> what plugin did you try to disable?

The "TMDb Box Sets" plugin.

**Comment by ashanrath** [comment]
Copied to https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/80 as not sure if the root cause is server or plugin.

**Comment by lukaslindnermusic** [comment]
> Copied to [jellyfin/jellyfin-plugin-tmdbboxsets#80](https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/80) as not sure if the root cause is server or plugin.

I have installed the "TMDb" plugin, but not the "TMDb Box Sets" plugin. So I guess, at least with the issues I am experiencing, it has nothing to do with the Box Sets plugin.

**Comment by TheMelmacian** [comment]
I had this problem, too. What worked for me was to go to the folder of the Multi-Version film, moved all versions but one in a subfolder with `.ignore` (Extras folder works too), remove all .nfo files and re-scanned the film. After that I added the other versions back.

**Comment by ashanrath** [comment]
> I had this problem, too. What worked for me was to go to the folder of the Multi-Version film, moved all versions but one in a subfolder with `.ignore` (Extras folder works too), remove all .nfo files and re-scanned the film. After that I added the other versions back.

While it's good to have a workaround, it's not really feasible on larger libraries.

**Comment by alwe2710** [comment]
I also have the same problem here. In my view the problem originates in the way Jellyfin organizes collections: by file names. It could use the id's it already uses for playback etc., different versions still get categorized by the same id. 
Tell me if I'm wrong, because I believe this would be the best solution.

**Comment by felix920506** [comment]
Marking confirmed by multiple reports

**Comment by entropi** [comment]
As a variation on this bug, I've been seeing this behavior:

1. Add a single versioned movie to a collection (or have it automatically added based on metadata), e.g "foo (2024) - 1080p.mkv"

2. After it's in the collection, add a second version of the movie ("foo (2024) - 2160p.mkv".

Bad behavior: I now see two entries for the movie in the collection. One with the original version only, with the resolution now in the displayed name, and another multi-version entry that behaves correctly. I'm able to manually remove the old single version in the web UI.

Maybe the above info/behavior helps with finding the source of the bug.

**Comment by JkBoyo** [comment]
I think this is related to issue #10226 also on the triage board.

**Comment by theguymadmax** [comment]
This issue stemmed from a change in the sorting behavior for alternative versions in 10.9 and this [bug](https://github.com/jellyfin/jellyfin/issues/12070#issuecomment-2362605950). With 10.10 on the horizon, many users are likely to encounter this again, as the sorting behavior for alt versions will revert to what it was in 10.8.

10.8
Library Sort order (files sort alphabetic despite resolution)
Movie (2000)
--Movie (2000)  -  Theatrical.mkv     [File is 1080p]
--Movie (2000)  -  Director’s Cut.mkv    [File is 2160p]

Database:
Movie (2000)  -  Theatrical.mkv     - MediaBrowser.Controller.Entities.Movies.Movie (Main version)
Movie (2000)  -  Director’s Cut.mkv   - MediaBrowser.Controller.Entities.Video (Alt version)

10.9
Library Sort Order (files sort higher resolution first)
Movie (2000)
--Movie (2000)  -  Director’s Cut.mkv    [File is 2160p]
--Movie (2000)  -  Theatrical.mkv     [File is 1080p]

Database: 
Movie (2000)  -  Director’s Cut.mkv   - MediaBrowser.Controller.Entities.Movies.Movie (Main version)
Movie (2000)  -  Theatrical.mkv     - MediaBrowser.Controller.Entities.Video (Alt version)
Movie (2000)  -  Director’s Cut.mkv   - MediaBrowser.Controller.Entities.Video (Alt version)

In 10.9, the 2160p version is now sorted first becoming the main version, while the 1080p version is now considered an alternative. The bug preventing the deletion of alternative versions, leads to duplicate entries for “Movie (2000) - Director’s Cut.mkv” in the database—one marked as the main version and the other as an alt version. This duplication results in the file not appearing in collections. To resolve this, you can edit the database to remove the old alt version of “Movie (2000) - Director’s Cut.mkv.” After doing so, the file should correctly show up in collections.

Here's an example from 10.10, now that versions are properly sorted. The "Original" gets sorted first in 10.10, but "Remastered" used to be sorted first in 10.9. This change has resulted in duplicate entries in the database, causing the item to disappear from collections, even though it still exists in the XML file. Once I remove the duplicate "Original" entry from the database, it reappears in the collections immediately.

![10 10](https://github.com/user-attachments/assets/3c960ca3-64a7-4e01-ae4c-3785433ff3ae)

**Comment by alpha-tango-kilo** [comment]
Thanks for the explanation! Does that also mean people that haven't manually tweaked their database or otherwise fixed this somehow since 10.8 stand a chance at having things magically start working again when 10.10 comes out and the sort order matches the database?

**Comment by JkBoyo** [comment]
> This issue stemmed from a change in the sorting behavior for alternative versions in 10.9 and this [bug](https://github.com/jellyfin/jellyfin/issues/12070#issuecomment-2362605950). With 10.10 on the horizon, many users are likely to encounter this again, as the sorting behavior for alt versions will revert to what it was in 10.8.
> 
> 10.8 Library Sort order (files sort alphabetic despite resolution) Movie (2000) --Movie (2000) - Theatrical.mkv [File is 1080p] --Movie (2000) - Director’s Cut.mkv [File is 2160p]
> 
> Database: Movie (2000) - Theatrical.mkv - MediaBrowser.Controller.Entities.Movies.Movie (Main version) Movie (2000) - Director’s Cut.mkv - MediaBrowser.Controller.Entities.Video (Alt version)
> 
> 10.9 Library Sort Order (files sort higher resolution first) Movie (2000) --Movie (2000) - Director’s Cut.mkv [File is 2160p] --Movie (2000) - Theatrical.mkv [File is 1080p]
> 
> Database: Movie (2000) - Director’s Cut.mkv - MediaBrowser.Controller.Entities.Movies.Movie (Main version) Movie (2000) - Theatrical.mkv - MediaBrowser.Controller.Entities.Video (Alt version) Movie (2000) - Director’s Cut.mkv - MediaBrowser.Controller.Entities.Video (Alt version)
> 
> In 10.9, the 2160p version is now sorted first becoming the main version, while the 1080p version is now considered an alternative. The bug preventing the deletion of alternative versions, leads to duplicate entries for “Movie (2000) - Director’s Cut.mkv” in the database—one marked as the main version and the other as an alt version. This duplication results in the file not appearing in collections. To resolve this, you can edit the database to remove the old alt version of “Movie (2000) - Director’s Cut.mkv.” After doing so, the file should correctly show up in collections.
> 
> Here's an example from 10.10, now that versions are properly sorted. The "Original" gets sorted first in 10.10, but "Remastered" used to be sorted first in 10.9. This change has resulted in duplicate entries in the database, causing the item to disappear from collections, even though it still exists in the XML file. Once I remove the duplicate "Original" entry from the database, it reappears in the collections immediately.
> 
> ![10 10](https://private-user-images.githubusercontent.com/171496228/369588569-3c960ca3-64a7-4e01-ae4c-3785433ff3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDUzMjgsIm5iZiI6MTcyNjk0NTAyOCwicGF0aCI6Ii8xNzE0OTYyMjgvMzY5NTg4NTY5LTNjOTYwY2EzLTY0YTctNGUwMS1hZTRjLTM3ODU0MzNmZjNhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxODU3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDIyYWUyY2YyNDYxZjQ1MWQ3YzY0NDM5MGNhNjk3NWRmNDQ3NWIyM2FkOWJhYWY2Y2VhZWJiYmIyNjJjZmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RRywWvncNMWeJHy6QwFY42hCgKSHodLS8rLPWof-UJw)

How do you do database alterations to fix this? just straight up edit the xml?

**Comment by theguymadmax** [comment]
Currently, version 10.10 is unlikely to resolve this issue and may even impact more users based on their naming structures. Hopefully, this narrows it down so the devs can implement a fix. Until then, editing the database remains the best workaround besides a fresh install. Here’s a quick rundown:

1. Download [SQLite Browser](https://sqlitebrowser.org/).
2. Shut down the server.
3. Open `library.db` (always back up first!). Locations vary:
   - `/var/lib/jellyfin/data/library.db`
   - `X:\ProgramData\Jellyfin\Server\data\library.db`
   - `X:\Users\Username\AppData\Local\jellyfin\data\library.db`
4. Choose the “Browse Data” tab and select “TypedBaseItems.”
5. Filter for the movie title in “Filter in any column”; you can refine it using the “Path” field.
6. Find the duplicate entry of type “MediaBrowser.Controller.Entities.Video,” right-click, and delete the record.
7. Click “Write Changes,” close the database, and restart the server.

**Comment by kwm1800** [comment]
@theguymadmax : I was writing a response, but yours is much better. Thank you.


I have a feeling if the fix has to be done by database editor, many people won't like it since it always has a chance to corrupt the entire database and ruin someone's day (or days).

**Comment by JkBoyo** [comment]
Do we think that these sets of issues could or should be resolved into 1 to reduce the number off issues it's taking up on the triage board? It feels like having 3 open issues that reference the same underlying problem is just gonna make it hard for people to fix/find the underlying issue.

**Comment by alpha-tango-kilo** [comment]
I'll close my issue (#10226) in favour of this one once I've confirmed the fix above works (which I'll try once 10.10 comes out)

**Comment by kwm1800** [comment]
> I'll close my issue (#10226) in favour of this one once I've confirmed the fix above works (which I'll try once 10.10 comes out)

Not sure above can be regarded as a "fix." It is quite confusing to verify which duplicated entry is causing the issue. For my case, it did not help much.

**Comment by ashanrath** [comment]
> Currently, version 10.10 is unlikely to resolve this issue and may even impact more users based on their naming structures. Hopefully, this narrows it down so the devs can implement a fix. Until then, editing the database remains the best workaround besides a fresh install. Here’s a quick rundown:
> 
> 1. Download [SQLite Browser](https://sqlitebrowser.org/).
> 2. Shut down the server.
> 3. Open `library.db` (always back up first!). Locations vary:
>    
>    * `/var/lib/jellyfin/data/library.db`
>    * `X:\ProgramData\Jellyfin\Server\data\library.db`
>    * `X:\Users\Username\AppData\Local\jellyfin\data\library.db`
> 4. Choose the “Browse Data” tab and select “TypedBaseItems.”
> 5. Filter for the movie title in “Filter in any column”; you can refine it using the “Path” field.
> 6. Find the duplicate entry of type “MediaBrowser.Controller.Entities.Video,” right-click, and delete the record.
> 7. Click “Write Changes,” close the database, and restart the server.

From a DB perspective, this actually seems a simpler work around than I thought. I've just tested a couple of impacted entries, deleting the MediaBrowser.Controller.Entities.Video rows and retaining the main MediaBrowser.Controller.Entities.Movies.Movie before running a metadata refresh to check for new/updated files. Problem solved.

Am I missing something, or is it potentially as simple as:
`delete from TypedBaseItems where type = 'MediaBrowser.Controller.Entities.Video'`
then running a fresh scan to re-add them. If I'm understanding correctly, no actual metadata is lost as Jellyfin will only be readingf from the main anyway?

This feels like too much of a blunt force approach, but I can't see a significant down-side yet.

**Comment by alpha-tango-kilo** [comment]
> Currently, version 10.10 is unlikely to resolve this issue and may even impact more users based on their naming structures. Hopefully, this narrows it down so the devs can implement a fix. Until then, editing the database remains the best workaround besides a fresh install. Here’s a quick rundown:
> 
> 1. Download [SQLite Browser](https://sqlitebrowser.org/).
> 
> 2. ... etc.

I gave this a go today and have now managed to sort out my movie collections, thank you very much for the point in the right direction!

The process I followed to success was ultimately a bit more involved though. I don't know if it was all strictly necessary but this is what I followed:

1. I deleted all the broken collections from Jellyfin
2. Shutdown Jellyfin
3. Purge **all** `MediaBrowser.Controller.Entities.Video` entries for all the movies I wanted to be in the collections (just removing duplicates didn't work)
4. Start up Jellyfin, request it to scan the movie library
5. Notice all my borked collections have magically reappeared (??), but I'm able to remove the "Video" entries from them and add the movies into thme to get them to work
6. Manually search for images for all collections - I was watching the server logs and Jellyfin seemed to think it didn't have the images but in some cases I could see them in the app... in any case searching and downloading new covers & backdrops for all effected collections fixed it

Now everything is right with the world, many thanks @theguymadmax!

**Comment by alpha-tango-kilo** [comment]
Having found a few more entries in my Jellyfin server that needed fixing, I have also discovered a weird new side effect. When I add movies to collections after fixing their records (removing all `MediaBrowser.Controller.Entities.Video` entries and re-scanning the library), they do now show in the collection, but still also show in the main library page

<details>
<summary>Examples</summary>

![Image](https://github.com/user-attachments/assets/d230539e-4182-4d6f-9865-72d3cf454803)

![Image](https://github.com/user-attachments/assets/8809c930-b558-43bf-972d-467cd27fe8c7)

</details>

Not sure what's causing this but if I can help anyone by providing bits of my database or something, let me know!

**Comment by NiklasBr** [comment]
I was just bit by this or something very similar. I renamed a folder from `Twentieth Century Fox` to `20th Century Studios` and now all the movies inside that folder and collection no longer shows up.

I have cleared all caches, scanned library, restarted, cleaned up collections and playlist. But they all show like this in the log:

```log
[2025-04-23 18:09:43.766 +02:00] [WRN] [16] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path "M:\...Movie.mp4"
```

**Comment by JkBoyo** [comment]
I can't say when it was fixed or what changed but I just went into my library added a movie with multiple versions to a collection and it worked now so for me anyways it is fixed.  Can anyone else on this thread verify this?

**Comment by alpha-tango-kilo** [comment]
Off the back of your comment I went through and tried with my collections with partial success. I was able to create some collections and populate them with movies fine, but not all of them. So a step in the right direction I guess? I just worry now that my database is filled with crud from all the attempts and trying to make this work lol

**Comment by fn1701** [comment]
# Jellyfin BoxSet Movie ID Correction Guide

## Table of Contents

1. [Introduction & Cause](#introduction--cause)
2. [Manual explanatory Fix for One Collection (sqlite shell)](https://github.com/fn1701/scripts-for-Jellyfin-issue-11736/blob/main/Manual_sqlite_Fix_for_One_Collection.md)
3. [Manual Fix for One Collection (bash scripts)](https://github.com/fn1701/scripts-for-Jellyfin-issue-11736/blob/main/Manual_bash_Fix_for_One_Collection.md)
4. [Script-Based Fix for all or one Collections](https://github.com/fn1701/scripts-for-Jellyfin-issue-11736/blob/main/Script-Based_Fix_for_all_or_one_Collections.md)

### Introduction & Cause

I seem to have identified the root cause and a manual database-based fix for this issue.

#### Cause

When adding a movie (this occurred sometimes with single- and always with multi-version movies) instead of
the `Type = MediaBrowser.Controller.Entities.Movies.Movie`'s Id
the `Type = MediaBrowser.Controller.Entities.Video`'s Id is added to
the collection (`Type = MediaBrowser.Controller.Entities.Movies.BoxSet`) in the database.

#### Consequence

As a result, the movie is not recognized as part of the collection.
In some cases, the video is shown in its own row.

#### Quick Fix

Replace the `.Video` ID in the `Data` field of the database with the `.Movies.Movie` Id.

##### Persistence of the Fix

2025-11-29
I just did that and it worked. I expect that for Manual (`Data = {...,"Type":"Manual",...}`), collections  the changes will persist across future Library Scans and Updates. If I am wrong, I will update this.

Update 2026-01-23:
It persists until you change something in the collection and Jellyfin has to rewrite the JSON-Object inside the db.

**Comment by Maltavius** [comment]
Do we have a non-hack-the-database solution to this?
I'm on 10.11.11 and this is still an issue. Removing one version of a file breaks the collections.

**Comment by alpha-tango-kilo** [comment]
I think the hope/dream is that 12.0 should fix this for good and no longer require manual database fixes. How well that'll play out in reality with existing installations and dodgy metadata / database entries, I'm not sure. I'll try my luck when 12.0 comes out as stable, and continue to live with my broken collections otherwise. It's not that big of a deal to me.
