### ISSUE TITLE
Recording m3u Live TV broken in 10.9.2 (not the access denied error)

### ISSUE THREAD

**Issue by pw-h** [jellyfin/jellyfin#11756]
### Please describe your bug

Recording an IPTV channel fails in 10.9.2

### Reproduction Steps

Running 10.9.2 in a docker container on a Synology D918+ in network host mode.  

Using the iptv plugin https://github.com/Kevinjil/Jellyfin.Xtream, but problem arises when using a 'm3u tuner' LIVE TV source also.

I have set the recording path to /mnt/tv_opnames, and verified from within the container that i can create and delete files in tjat destination.

The error appears irrespective of wether i access jellyfin through a reverse proxy or directly.

The IPTV Live TV channels play fine (irrespective if transcoding is enabled or not), but pressing 'record' results in an everlating spinning circle, and this is logged:

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Synology DSM 7.1
- Linux Kernel: DSM 7.1
- Virtualization: Synology Container Manager
- Clients: Windows 11
- Browser: Chrome
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Chrome browser
- Hardware Acceleration: API (VAAPI)
- GPU Model: DS918+
- Plugins: https://github.com/Kevinjil/Jellyfin.Xtream
- Reverse Proxy: NGINX
- Base URL: none
- Networking: Home LAN
- Storage: Synology DS918+ host
```

### Jellyfin logs

```shell
`[2024-05-20 14:45:29.518 +00:00] [ERR] [72] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/LiveTv/Timers".
System.NotImplementedException: The method or operation is not implemented.
   at Jellyfin.Xtream.LiveTvService.CreateTimerAsync(TimerInfo info, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.LiveTvManager.CreateTimer(TimerInfoDto timer, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.LiveTvController.CreateTimer(TimerInfoDto timerInfo)
   at lambda_method1268(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> `Jellyfin.Xtream.LiveTvService.CreateTimerAsync `

Your plugin is not compatible. Please remove it an retest

**Comment by pw-h** [comment]
Removed the plugin, restarted the Jellyfin server, added a 'm3u tuner' source for Live TV using a fresh made m3u file.

Al channels in this m3u file play perferctly in VLC, however Jellyfin 10.9.2. persistently keeps logging:

[2024-05-21 07:35:08.982 +00:00] [ERR] [43] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---

Using m3u tuners was a straight forward process in 10.8.13, but is nothing but trouble in 10.9.2 so far..

**Comment by pw-h** [comment]
It is confirmed that recording with the https://github.com/Kevinjil/Jellyfin.Xtream plugin is not implemented yet, so i's close this issue. Now i only have to get Live TV via a m3u source working (like it always has in 10.8.13...)

**Comment by rpm5099** [comment]
Has there been an update on the status of that plugin?

**Comment by felix920506** [comment]
@rpm5099 That is a 3rd party plugin. Please ask the plugin author.

**Comment by rpm5099** [comment]
> [@rpm5099](https://github.com/rpm5099) That is a 3rd party plugin. Please ask the plugin author.

Yeah, I found [this issue](https://github.com/Kevinjil/Jellyfin.Xtream/issues/46) over on his project.  He seems to be claiming that jellyfin does not make it's recording api available to plugins.
