### ISSUE TITLE
[Issue]: Trickplay images do not generate because of zero division exception

### ISSUE THREAD

**Issue by Gylesie** [jellyfin/jellyfin#11784]
### Please describe your bug

I noticed that trickplay images are not being generated, despite everyday I see a task in progress and takes ages.

### Reproduction Steps

1. Run trickplay generation task

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: 6.8.0-31-generic
- Virtualization: Docker
- Clients: -
- Browser: -
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: Intro Skipper, Merge Versions, Trakt
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: CIFS
```

### Jellyfin logs

```shell
[DBG] [33] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Trickplay refresh for 1a3aa11a-cb50-03fe-12fe-c9e1880e152c (replace existing: False)
[INF] [33] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for "........" [ID: 1a3aa11a-cb50-03fe-12fe-c9e1880e152c]
[INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"......" -noautoscale -an -sn -vf \"fps=10,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=132:format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv\" -threads 12 -c:v mjpeg_qsv -qscale:v 4 -f image2 \"/config/cache/temp/....\""

[ERR] [33] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> `fps=10`

Why are you generating trick-play images at this high frame-rate? You need at least 1 second interval otherwise it will fail like this.
