### ISSUE TITLE
Android TV Crashing after 10.9.2 update, multiple devices

### ISSUE THREAD

**Issue by ierc** [jellyfin/jellyfin#11809]
### Please describe your bug

After updating to server 10.9.2 (on docker using the official repo) both of my Android TV apps crash after playing a minute or so of content. Tried multiple files and kept getting crashes. I'm uploading the crash logs for both my Shield TV and Sony Bravia. Both Android clients are up to date with the latest Android app, I tried rebooting, reinstalling the app and nothing. Everything works fine after rolling back to 10.9.1.

### Reproduction Steps

Open Jellyfin, try to play content

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Ubuntu Server and official Docker image
- Linux Kernel: Linux 5.15.0-107-generic x86_64
- Virtualization: NA
- Clients: Android TV app
- Browser: NA
- FFmpeg Version: ffmpeg version 4.4.2-0ubuntu0.22.04.1
- Playback Method: Direct Play (tried exo and libvlc)
- Hardware Acceleration: NA
- GPU Model: NA
- Plugins: Trakt, Webhook, opensubtitles
- Reverse Proxy: No
- Base URL: NA
- Networking:
- Storage:
```

### Jellyfin logs

```shell
---
client: Jellyfin for Android TV
client_version: 0.16.10
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.BaseItemDto.getParentThumbItemId()' on a null object reference
	at org.jellyfin.androidtv.util.ImageUtils.getImageAspectRatio(ImageUtils.java:39)
	at org.jellyfin.androidtv.ui.presentation.CardPresenter$ViewHolder.setItem(CardPresenter.java:112)
	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:368)
	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1318)
	at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1402)
	at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1508)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4078)
	at android.view.View.measure(View.java:25490)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25490)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25490)
	at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1600)
	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1702)
	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
	at android.view.View.layout(View.java:22868)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3646)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3040)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2018)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8467)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

  
***Logcat***: 
```log
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at android.os.Handler.handleCallback(Handler.java:938)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at android.os.Looper.loop(Looper.java:223)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at java.lang.reflect.Method.invoke(Native Method)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-22 19:56:27.604 E/AndroidRuntime(26795): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-22 19:56:27.604 E/ACRA    (26795): ACRA caught a NullPointerException for org.jellyfin.androidtv
05-22 19:56:27.604 E/ACRA    (26795): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID org.jellyfin.sdk.model.api.BaseItemDto.getParentThumbItemId()' on a null object reference
05-22 19:56:27.604 E/ACRA    (26795): 	at org.jellyfin.androidtv.util.ImageUtils.getImageAspectRatio(ImageUtils.java:39)
05-22 19:56:27.604 E/ACRA    (26795): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter$ViewHolder.setItem(CardPresenter.java:112)
05-22 19:56:27.604 E/ACRA    (26795): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:368)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1318)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1402)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1508)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4078)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.measure(View.java:25490)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.measure(View.java:25490)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.measure(View.java:25490)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1600)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1702)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
05-22 19:56:27.604 E/ACRA    (26795): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-22 19:56:27.604 E/ACRA    (26795): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.View.layout(View.java:22868)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3646)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3040)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2018)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8467)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.Choreographer.doFrame(Choreographer.java:731)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.os.Handler.handleCallback(Handler.java:938)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.os.Looper.loop(Looper.java:223)
05-22 19:56:27.604 E/ACRA    (26795): 	at android.app.ActivityThread.main(ActivityThread.java:7668)
05-22 19:56:27.604 E/ACRA    (26795): 	at java.lang.reflect.Method.invoke(Native Method)
05-22 19:56:27.604 E/ACRA    (26795): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-22 19:56:27.604 E/ACRA    (26795): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-22 19:56:27.604 D/ACRA    (26795): Building report
05-22 19:56:27.605 D/ACRA    (26795): Starting collectors with priority FIRST
05-22 19:56:27.606 D/ACRA    (26795): Calling collector org.acra.collector.DropBoxCollector
05-22 19:56:27.606 D/ACRA    (26795): Calling collector org.acra.collector.LogCatCollector
05-22 19:56:27.606 D/ACRA    (26795): Collector org.acra.collector.DropBoxCollector completed
05-22 19:56:27.606 D/ACRA    (26795): Calling collector org.acra.collector.StacktraceCollector
05-22 19:56:27.606 D/ACRA    (26795): Collector org.acra.collector.StacktraceCollector completed
05-22 19:56:27.616 D/ACRA    (26795): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.10` (`161099`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"darcy","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"mdarcy","DISPLAY":"RQ1A.210105.003.7825230_3167.5736","FINGERPRINT":"NVIDIA\/mdarcy\/mdarcy:11\/RQ1A.210105.003\/7825230_3167.5736:user\/release-keys","HARDWARE":"darcy","HOST":"mobile-u64-5308-d7000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"mdarcy","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975826000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825230_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":161099,"VERSION_NAME":"0.16.10"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `mdarcy`  
***Device model***: `SHIELD Android TV`  

### Crash information

***Start time***: `2024-05-22T19:56:02.339-05:00`  
***Crash time***: `2024-05-22T19:56:27.683-05:00`
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Alliyance** [comment]
From time to time, I get this also crash report "NullPointerException" when I tried to open chromecast or firetv. Before that new version, only firetv was doing this. But I can still play any movie, direct play on Linux system.

**Comment by fice-t** [comment]
@nielsvanvelzen I was just about to open a new issue in the ATV repo for this crash. However, my server version is still on `10.8.13`.

In my case, I have not been present for the crashes myself. The timing suggests that it crashed upon waking (or powering on) the ATV device, likely when the last open program was Jellyfin.

**Comment by TimGels** [comment]
This appears to be an Android TV client issue instead of Jellyfin Server.
