### ISSUE TITLE
[Issue]: Jellyfin Crashes

### ISSUE THREAD

**Issue by PeachesMLG** [jellyfin/jellyfin#11846]
### Please describe your bug

Jellyfin crashed due to a NPE

### Reproduction Steps

N/A

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Nvidia
- GPU Model:
- Plugins: IntroSkipper
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-05-27 09:38:31.585 +01:00] [INF] [54] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "x.x.x.x" request
[2024-05-27 09:41:39.803 +01:00] [INF] [54] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "x.x.x.x" closed
[2024-05-27 09:41:39.803 +01:00] [INF] [62] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "x.x.x.x" closed
[2024-05-27 09:41:39.803 +01:00] [FTL] [60] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
   at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
   at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__52_0(ISessionController i)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2024-05-27 09:41:39.803 +01:00] [FTL] [61] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.WebSocketController.<>c.<GetActiveSockets>b__12_0(IWebSocketConnection i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Session.WebSocketController.get_HasOpenSockets()
   at Emby.Server.Implementations.Session.WebSocketController.get_IsSessionActive()
   at Emby.Server.Implementations.Session.SessionManager.<>c.<CloseIfNeededAsync>b__52_0(ISessionController i)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Session.SessionManager.CloseIfNeededAsync(SessionInfo session)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
Do you have an idea what steps you took resulting in this?

**Comment by PeachesMLG** [comment]
Nope, I opened up the web ui, didnt really do anything and it crashed

**Comment by PeachesMLG** [comment]
Here are the full logs if needed, only other thing worth mentioning is this did happen as soon as I upgraded to 10.9.3, so potentially that caused something somehow?

[Jellyfin.log](https://github.com/jellyfin/jellyfin/files/15456676/Jellyfin.log)

**Comment by TimGels** [comment]
This seems to be already reported at https://github.com/jellyfin/jellyfin/issues/11417

**Comment by TimGels** [comment]
Closing this in favor of the already reported issue https://github.com/jellyfin/jellyfin/issues/11417

**Comment by PeachesMLG** [comment]
> This seems to be already reported at #11417

mb, I had a look around for one already posted but couldnt find one.
