### ISSUE TITLE
[bug] [solved]: Jellyfin 10.9.3 in docker not searching/updating libraries

### ISSUE THREAD

**Issue by karlh001** [jellyfin/jellyfin#11906]
### Please describe your bug

**Forum is down at time of writing**

I upgraded to 10.9.3 (from 10.8.13) using the jellyfin/jellyfin docker image. 

After this, I can no longer add media. After lots of troubling shooting and playing with permissions I finally found the answer: there is a bug with the docker image.

Log result after failed library scan:
```

[2024-06-01 08:20:05.591 +00:00] [INF] [55] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-06-01 08:20:06.029 +00:00] [WRN] [55] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-06-01 08:20:06.288 +00:00] [ERR] [59] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/var/lib/jellyfin/root/default/Films"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/Films'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)

```

It took me a while to notice that the path cannot be found:

`'/var/lib/jellyfin/root/default/Films'.`

I assumed this was the path which was rerouted through docker volume, but after accessing the docker container shell I realised it is not (I should have known earler that it should be /config). Jellyfin should be looking for /config not /var/lib/jellyfin.

I added this new volume to the compose file, and all was well.

`- /media/XYZ/jellyfin_docker/var_lib:/var/lib/jellyfin # Added to resolve bug 10.9.3 scanning library`

A rescan was initated and all new films appeared. 

### Reproduction Steps

Use docker image 10.9.3
Follow instructions to create docker compose file
Results is wrong

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-06-01 08:20:05.591 +00:00] [INF] [55] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-06-01 08:20:06.029 +00:00] [WRN] [55] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-06-01 08:20:06.288 +00:00] [ERR] [59] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/var/lib/jellyfin/root/default/Films"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/Films'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
N/A
Play was flawless through troubleshooting
```

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
This usually means you are using an old installation which does not use the same path.

The DB will store absolute paths and if it was not `/config` before it will use that path. So yes, you need to do something like this if you don't want to fix your db after migration.

**Comment by karlh001** [comment]
I wonder if when upgrading the database from 10.8.13 to 10.9.3 the path was overwritten.
Prior to upgrade, I was using in docker container with no issue to `/config` with the same database.
_This is a legacy database that used to be on bare metal a year ago._

**Comment by cvium** [comment]
You didn't use LSIO's image before?

**Comment by Kha611** [comment]
update
