### ISSUE TITLE
[Issue]: Audio Normalization fails on Radio Show/Podcast collections due to `OutOfMemoryException`

### ISSUE THREAD

**Issue by mihawk90** [jellyfin/jellyfin#11909]
### Please describe your bug

I noticed immediately after the upgrade that the Audio Normalization would eventually fail for me. In the logs I could see that it eventually hit an `OutOfMemoryException`:
```log
[2024-06-01 11:57:53.532 +00:00] [ERR] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.IO.StreamReader.ReadToEndAsyncInternal(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.CalculateLUFSAsync(String inputArgs, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-06-01 11:57:53.563 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Audio Normalization" Failed after 53 minute(s) and 49 seconds
```

But because the Normalization process logs absolutely nothing it took me a while to get down to the cause.

With Debug logging I figured that it passes a `.concat` text file to ffmpeg's `concat` filter. The files seem to be written on a per-album basis (which in itself makes sense of course).
However the problem with that comes when one organises Radio Shows or Podcasts into a single Album. Luckily JF doesn't immediately clean up the text file after the task fails, so I was able to pull the offending album fairly easily:
[625f488c-7c25-4d0e-97ca-dcf0e93def36.concat.txt](https://github.com/user-attachments/files/15522079/625f488c-7c25-4d0e-97ca-dcf0e93def36.concat.txt)

As you can tell this list is quite long and it should be noted every episode is 2h minimum (more for specials). So whenever JF encounters this album it will eventually just run out of memory.

I haven't tracked down yet whether it is ffmpeg or JF itself that is running out of memory, but judging from the ffmpeg command used:
```
[2024-06-01 11:51:06.427 +00:00] [DBG] [11] Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask: Starting ffmpeg with arguments: "-hide_banner -f concat -safe 0 -i \"/cache/transcodes/625f488c-7c25-4d0e-97ca-dcf0e93def36.concat\" -af ebur128=framelog=verbose -f null -"
```
.. I would assume it is JF itself since ffmpeg just pipes its output back.

### Reproduction Steps

1. Add an album with a massive size to the library (I guess?)
2. Start the Audio Normalization task via Scheduled Tasks
3. optional: Monitor progress via `watch -e cat "*"` in JF's `/cache/transcodes/` directory
4. Wait for it to hit `OutOfMemoryException`

Obviously these steps heavily depend on how much memory you actually have.

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: TrueNAS Scale
- Linux Kernel: Linux truenas 6.6.29-production+truenas #1 SMP PREEMPT_DYNAMIC Wed May 29 15:05:57 UTC 2024 x86_64 GNU/Linux
- Virtualization: Docker/Kubernetes (TrueNAS official App)
- Clients: Browser
- Browser: Vivaldi
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: whatever Docker does by default 😅
- Storage: local
```

### Jellyfin logs

```shell
[2024-06-01 11:51:06.427 +00:00] [DBG] [11] Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask: Starting ffmpeg with arguments: "-hide_banner -f concat -safe 0 -i \"/cache/transcodes/625f488c-7c25-4d0e-97ca-dcf0e93def36.concat\" -af ebur128=framelog=verbose -f null -"
[2024-06-01 11:51:09.090 +00:00] [DBG] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-06-01 11:51:09.090 +00:00] [DBG] [25] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-06-01 11:51:18.275 +00:00] [DBG] [8] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
...
[2024-06-01 11:57:42.275 +00:00] [DBG] [8] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2024-06-01 11:57:49.091 +00:00] [DBG] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-06-01 11:57:49.091 +00:00] [DBG] [27] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-06-01 11:57:53.532 +00:00] [ERR] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.IO.StreamReader.ReadToEndAsyncInternal(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.CalculateLUFSAsync(String inputArgs, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-06-01 11:57:53.563 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Audio Normalization" Failed after 53 minute(s) and 49 seconds
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Did 10.9.4 fix your issue?

**Comment by mihawk90** [comment]
> Did 10.9.4 fix your issue?

Still waiting on the TrueNAS App to get updated, will report back once the update is live.

**Comment by mihawk90** [comment]
It took a while (as in.. 3.5-ish hours lol) but can confirm it chugged through the entire list with no noticeable increase in memory usage.

Thanks for the fix :)
