### ISSUE TITLE
[Issue]: Certain albums not being properly scanned, throwing errors in log

### ISSUE THREAD

**Issue by kandykarter** [jellyfin/jellyfin#11908]
### Please describe your bug

Every so often I add an album to my library that Jellyfin 10.9.x seems to take issue with. On each occasion, it scans and displays the first track correctly, but attributes the remaining tracks to a "Disc 0", and displays the filenames as title. 

All my tags have been confirmed as correct while using Picard, all files play properly, and appear to have no other issues. Jellyfin identifies the albums correctly with MusicBrainz/AudioDB. 

### Reproduction Steps

1. Jellyfin 10.9.3, docker, etc.
2. Scan for new items
3. Look at new items. 

### Jellyfin Version

Master branch

### Environment

```markdown
- OS: Linux Mint
- Linux Kernel: 6.5.0-28 x86_64
- Virtualization: docker
- Clients: Web, android, kodi, not really applicable to issue
- Browser: Firefox
- FFmpeg Version: Whichever is bundled with jellyfin docker i guess
- Playback Method: N/a
- Hardware Acceleration: N/a
- GPU Model: N/a
- Plugins: Defaults + Kodi Sync Queue
- Reverse Proxy: Yes
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[2024-06-01 06:50:53.297 -07:00] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/01 Triangle.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.358 -07:00] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/02 Can't Leave The Night.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.380 -07:00] [ERR] [28] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.381 -07:00] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/03 Confessions (Feat. Leland Whitty).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.403 -07:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.405 -07:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/04 Kaleidoscope.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.425 -07:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.427 -07:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/05 Eyes Closed.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.447 -07:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.449 -07:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/06 Hedron.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.470 -07:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.484 -07:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/07 Differently, Still.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.505 -07:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.692 -07:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/08 Since You Asked Kindly.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.719 -07:00] [ERR] [22] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.897 -07:00] [INF] [22] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/09 CS60.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.923 -07:00] [ERR] [28] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-06-01 06:50:53.925 -07:00] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/music/Badbadnotgood/III/10 Sustain.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-06-01 06:50:53.950 -07:00] [ERR] [28] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
TagLib.CorruptFileException: A picture frame must contain at least 5 bytes.
   at TagLib.Id3v2.AttachmentFrame.ParseFields(ByteVector data, Byte version)
   at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
   at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_AudioFile..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### Please attach any screenshots here

![Screenshot from 2024-06-01 06-53-26](https://github.com/jellyfin/jellyfin/assets/107814899/6f7f63a3-1530-4f3c-b1bc-46b5067cf469)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kandykarter** [comment]
Solved by #11859
