### ISSUE TITLE
[Issue]: Update to 10.9.4 on docker on Synology does not start

### ISSUE THREAD

**Issue by lukaslindnermusic** [jellyfin/jellyfin#11929]
### Please describe your bug

I updated to 10.9.4 and suddenly the whole server is not reachable anymore. 
I also get a warning 1-2 minutes after the start. 

In the logs, I can see the following lines:

`2024/06/02 19:15:52 | stdout | [17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Jellyscrub 1.1.1.0
-- | -- | --
2024/06/02 19:15:52 | stdout | at Nick.Plugin.Jellyscrub.JellyscrubPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)
2024/06/02 19:15:52 | stdout | at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
2024/06/02 19:15:52 | stdout | at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024/06/02 19:15:52 | stdout | at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024/06/02 19:15:52 | stdout | at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024/06/02 19:15:52 | stdout | at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2024/06/02 19:15:52 | stdout | --- End of inner exception stack trace ---
2024/06/02 19:15:52 | stdout | ---> System.IO.IOException: Permission denied
2024/06/02 19:15:52 | stdout | [17:15:52] [ERR] [1] Nick.Plugin.Jellyscrub.JellyscrubPlugin: Encountered exception while writing to /jellyfin/jellyfin-web/index.html: System.UnauthorizedAccessException: Access to the path '/jellyfin/jellyfin-web/index.html' is denied.
`
(full log from Docker is under "Jellyfin Logs")

It seems like the Jellyscrub plugin is causing the issue (I've installed it before migrating to the new Jellyfin 10.9.x, but already migrated the plugin using the provided steps in the plugin settings).
However, I don't know if Jellyscrub itself is causing the issue or if its just the first plugin/service trying to access the jellyfin-web path and the whole path is not accessible. However, nothing works after this small update.

How can I fix this? Am I the only one with this issue? 
The server is not reachable at all.

### Reproduction Steps

1. Run Jellyfin 10.9.3 on Docker on a Synology DS 920+
2. Update the Container to latest (10.9.4).

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS: DSM 7.2.1-69057 Update 5 (Synology)
- Linux Kernel: I don't know
- Virtualization: Docker (Container Manager)
- Clients: (Jellyfin Web), Jellyfin Media Player, Finamp
- Browser: Safari...
- FFmpeg Version: (the one that comes with the docker image)
- Playback Method: ..
- Hardware Acceleration: ..
- GPU Model: /
- Plugins: AudioDB 10.9.4.0, MusicBrainz 10.9.4.0, OMDb 10.9.4.0, Studio Images 10.9.4.0, TMDb 10.9.4.0, Webhook 14.0.0.0, Playback Reporting 14.0.0.0, Jellyscrub 1.1.1.0
- Reverse Proxy: /
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
jellyfin

date	stream	content
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Jellyfin.Server.Migrations.Routines.FixAudioData: Backfilling audio lyrics data to database.
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Jellyfin.Server.Migrations.Routines.FixAudioData: Library database backed up to /config/data/library.db.bak5
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'FixAudioData'
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.4.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.4.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.4.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.4.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.4.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Webhook 14.0.0.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 14.0.0.0
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Jellyscrub 1.1.1.0
2024/06/02 19:15:52	stdout	   at Nick.Plugin.Jellyscrub.JellyscrubPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)
2024/06/02 19:15:52	stdout	   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
2024/06/02 19:15:52	stdout	   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024/06/02 19:15:52	stdout	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024/06/02 19:15:52	stdout	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024/06/02 19:15:52	stdout	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2024/06/02 19:15:52	stdout	   --- End of inner exception stack trace ---
2024/06/02 19:15:52	stdout	 ---> System.IO.IOException: Permission denied
2024/06/02 19:15:52	stdout	[17:15:52] [ERR] [1] Nick.Plugin.Jellyscrub.JellyscrubPlugin: Encountered exception while writing to /jellyfin/jellyfin-web/index.html: System.UnauthorizedAccessException: Access to the path '/jellyfin/jellyfin-web/index.html' is denied.
2024/06/02 19:15:52	stdout	[17:15:52] [INF] [1] Nick.Plugin.Jellyscrub.JellyscrubPlugin: Attempting to inject trickplay script code in /jellyfin/jellyfin-web/index.html
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: ["100.64.0.0/24"]
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.178.2", "172.17.0.1", "172.21.0.1", "100.64.0.1"]
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Webhook, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Webhook_14.0.0.0/Jellyfin.Plugin.Webhook.dll
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MimeKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814 from /config/plugins/Webhook_14.0.0.0/MimeKit.dll
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MQTTnet.Extensions.ManagedClient, Version=4.3.4.1084, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /config/plugins/Webhook_14.0.0.0/MQTTnet.Extensions.ManagedClient.dll
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Handlebars, Version=2.1.6.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661 from /config/plugins/Webhook_14.0.0.0/Handlebars.dll
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MailKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b from /config/plugins/Webhook_14.0.0.0/MailKit.dll
2024/06/02 19:15:44	stdout	[17:15:44] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938 from /config/plugins/Webhook_14.0.0.0/BouncyCastle.Cryptography.dll
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MQTTnet, Version=4.3.4.1084, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /config/plugins/Webhook_14.0.0.0/MQTTnet.dll
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Nick.Plugin.Jellyscrub, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Jellyscrub_1.1.1.0/Nick.Plugin.Jellyscrub.dll
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
2024/06/02 19:15:43	stdout	[17:15:43] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Application directory: /jellyfin/
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Cache path: /cache
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Config directory path: /config/config
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Log directory path: /config/log
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Program data path: /config
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Processor count: 4
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: User Interactive: True
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: 64-Bit Process: True
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Architecture: X64
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_DATA_DIR, /config]"]
2024/06/02 19:15:42	stdout	[17:15:42] [INF] [1] Main: Jellyfin version: 10.9.4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
If you let it run for a few minutes, will it eventually start?

**Comment by lukaslindnermusic** [comment]
> If you let it run for a few minutes, will it eventually start?

I will try that now. 
I've restored a backup of my config directory.

I also noticed another error in the logs. The logs above are already a second try.


2024/06/02 19:48:38 | stderr | Fontconfig error: No writable cache directories
-- | -- | --

**Comment by gnattu** [comment]
These errors do not seem to be related, it looks like the audio data fix migration takes abnormally long on your machine.

**Comment by lukaslindnermusic** [comment]
Oh my god! I am so sorry!
I let it sit for 10 minutes and it worked. 

I just saw that orange "Warning" next to my docker container which I never had before so I panicked!

I am sorry, it seems like everything is working now.

**Comment by joshuaboniface** [comment]
For anyone else who finds this from the pin: basically, on some machines with slower CPUs, a DB migration added in 10.9.4 to fix lyrics issues may take a very long time to run on startup, up to 10 minutes. Waiting for it to complete should be all that is necessary.

**Comment by LenzGr** [comment]
FWIW, I'm running Jellyfin in a K3S environment on TrueNAS Scale. Updating from 10.9.3 to 10.9.4 always gets stuck at this point: `Jellyfin.Server.Migrations.Routines.FixAudioData: Backfilling audio lyrics data to database.`. I rolled back to 10.9.3 after waiting several hours for this step to finish.

**Comment by gnattu** [comment]
> FWIW, I'm running Jellyfin in a K3S environment on TrueNAS Scale. Updating from 10.9.3 to 10.9.4 always gets stuck at this point: `Jellyfin.Server.Migrations.Routines.FixAudioData: Backfilling audio lyrics data to database.`. I rolled back to 10.9.3 after waiting several hours for this step to finish.

How big is your library? this is very abnormal to have it run for several hours.

**Comment by LenzGr** [comment]
> How big is your library? this is very abnormal to have it run for several hours. Or are you putting the data folder on an HDD?

Well, `library.db` is 596M in size... - I use Jellyfin for serving a wide range of assets (Videos, Pictures and Music). Checking the log file reveals an interesting pattern:

```[2024-06-04 00:00:37.152 +00:00] [INF] [1] Main: Jellyfin version: "10.9.4"
[2024-06-04 00:00:37.206 +00:00] [INF] [1] Main: Environment Variables: ["[JELLY
FIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "
[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_WEB
_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]"]
[2024-06-04 00:00:37.218 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin
.dll", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-06-04 00:00:37.219 +00:00] [INF] [1] Main: Operating system: "Debian GNU/L
inux 12 (bookworm)"
[2024-06-04 00:00:37.219 +00:00] [INF] [1] Main: Architecture: X64
[2024-06-04 00:00:37.220 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-06-04 00:00:37.223 +00:00] [INF] [1] Main: User Interactive: True
[2024-06-04 00:00:37.223 +00:00] [INF] [1] Main: Processor count: 2
[2024-06-04 00:00:37.223 +00:00] [INF] [1] Main: Program data path: "/config"
[2024-06-04 00:00:37.223 +00:00] [INF] [1] Main: Log directory path: "/config/lo
g"
[2024-06-04 00:00:37.223 +00:00] [INF] [1] Main: Config directory path: "/config
/config"
[2024-06-04 00:00:37.224 +00:00] [INF] [1] Main: Cache path: "/cache"
[2024-06-04 00:00:37.224 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/
jellyfin-web"
[2024-06-04 00:00:37.224 +00:00] [INF] [1] Main: Application directory: "/jellyf
in/"
[2024-06-04 00:00:37.707 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.B
aseConfigurationManager: Setting cache path: "/cache"
[2024-06-04 00:00:38.017 +00:00] [INF] [1] Emby.Server.Implementations.Applicati
onHost: Loading assemblies
[2024-06-04 00:00:38.056 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Skipping disabled plugin "2.0.0.0" of "DLNA"
[2024-06-04 00:00:38.266 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.
168.0.0/16"]
[2024-06-04 00:00:38.267 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Defined LAN exclusions: []
[2024-06-04 00:00:38.269 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168
.0.0/16"]
[2024-06-04 00:00:38.275 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Filtered interface addresses: ["127.0.0.1", "192.168.178.21", "172.16.0.1
", "172.17.130.68", "172.17.0.1", "172.17.0.10", "172.17.19.245"]
[2024-06-04 00:00:38.278 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Bind Addresses ["0.0.0.0"]
[2024-06-04 00:00:38.279 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Remote IP filter is "Allowlist"
[2024-06-04 00:00:38.280 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Filtered subnets: []
[2024-06-04 00:01:34.623 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "TMDb" "10.9.4.0"
[2024-06-04 00:01:34.626 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "Studio Images" "10.9.4.0"
[2024-06-04 00:01:34.628 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "OMDb" "10.9.4.0"
[2024-06-04 00:01:34.677 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "MusicBrainz" "10.9.4.0"
[2024-06-04 00:01:34.678 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "AudioDB" "10.9.4.0"
[2024-06-04 00:01:34.795 +00:00] [INF] [1] Jellyfin.Server.Migrations.MigrationR
unner: Applying migration '"FixAudioData"'
[2024-06-04 00:01:37.888 +00:00] [INF] [1] Jellyfin.Server.Migrations.Routines.F
ixAudioData: Library database backed up to "/config/data/library.db.bak78"
[2024-06-04 00:01:37.888 +00:00] [INF] [1] Jellyfin.Server.Migrations.Routines.F
ixAudioData: Backfilling audio lyrics data to database.
[2024-06-04 00:06:01.801 +00:00] [INF] [1] Main: Jellyfin version: "10.9.4"
[2024-06-04 00:06:01.883 +00:00] [INF] [1] Main: Environment Variables: ["[JELLY
FIN_CONFIG_DIR, /config/config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_
CACHE_DIR, /cache]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_FF
MPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]"]
[2024-06-04 00:06:01.911 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin
.dll", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-06-04 00:06:01.912 +00:00] [INF] [1] Main: Operating system: "Debian GNU/L
inux 12 (bookworm)"
[2024-06-04 00:06:01.912 +00:00] [INF] [1] Main: Architecture: X64
[2024-06-04 00:06:01.921 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-06-04 00:06:01.923 +00:00] [INF] [1] Main: User Interactive: True
[2024-06-04 00:06:01.923 +00:00] [INF] [1] Main: Processor count: 2
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Program data path: "/config"
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Log directory path: "/config/lo
g"
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Config directory path: "/config
/config"
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Cache path: "/cache"
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/
jellyfin-web"
[2024-06-04 00:06:01.926 +00:00] [INF] [1] Main: Application directory: "/jellyf
in/"
[2024-06-04 00:06:02.406 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.B
aseConfigurationManager: Setting cache path: "/cache"
[2024-06-04 00:06:02.568 +00:00] [INF] [1] Emby.Server.Implementations.Applicati
onHost: Loading assemblies
[2024-06-04 00:06:02.605 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Skipping disabled plugin "2.0.0.0" of "DLNA"
[2024-06-04 00:06:02.827 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.
168.0.0/16"]
[2024-06-04 00:06:02.833 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Defined LAN exclusions: []
[2024-06-04 00:06:02.834 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168
.0.0/16"]
[2024-06-04 00:06:02.837 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Filtered interface addresses: ["127.0.0.1", "192.168.178.21", "172.16.0.1
", "172.17.130.68", "172.17.0.1", "172.17.0.10", "172.17.19.245"]
[2024-06-04 00:06:02.842 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Bind Addresses ["0.0.0.0"]
[2024-06-04 00:06:02.843 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Remote IP filter is "Allowlist"
[2024-06-04 00:06:02.843 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkMa
nager: Filtered subnets: []
[2024-06-04 00:06:58.351 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "TMDb" "10.9.4.0"
[2024-06-04 00:06:58.353 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "Studio Images" "10.9.4.0"
[2024-06-04 00:06:58.354 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "OMDb" "10.9.4.0"
[2024-06-04 00:06:58.406 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "MusicBrainz" "10.9.4.0"
[2024-06-04 00:06:58.407 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.P
luginManager: Loaded plugin: "AudioDB" "10.9.4.0"
[2024-06-04 00:06:58.538 +00:00] [INF] [1] Jellyfin.Server.Migrations.MigrationR
unner: Applying migration '"FixAudioData"'
[2024-06-04 00:07:01.895 +00:00] [INF] [1] Jellyfin.Server.Migrations.Routines.F
ixAudioData: Library database backed up to "/config/data/library.db.bak79"
[2024-06-04 00:07:01.897 +00:00] [INF] [1] Jellyfin.Server.Migrations.Routines.F
ixAudioData: Backfilling audio lyrics data to database.
[2024-06-04 00:11:15.880 +00:00] [INF] [1] Main: Jellyfin version: "10.9.4"
```
It seems as if the process gets restarted every 5 mins (maybe a K3S timeout?), resulting in another backup copy of the database to be created and the migration process starting over again. I ended up with 168 backup copies of the `library.db` file (about 38G on disk) before I rolled back to the previous version...

**Comment by gnattu** [comment]
> It seems as if the process gets restarted every 5 mins (maybe a K3S timeout?)

Could of. Can you disable the auto-restart and let it run for a little bit of time?

**Comment by LenzGr** [comment]
> Can you disable the auto-restart and let it run for a little bit of time?

I will try - I'm not very familiar with how the Jellyfin pod is spawned in TrueNAS...

**Comment by LenzGr** [comment]
I'm sorry, I was not able to reproduce this behaviour - I moved my TrueNAS installation to a more powerful server and that one managed to finish the database migration within the 5 min time window.

**Comment by grobalt** [comment]
Maybe this helps you:
https://github.com/jellyfin/jellyfin/issues/12203
