### ISSUE TITLE
[Issue]: Refresh metadata -> Replace all metadata does not work on movie titles

### ISSUE THREAD

**Issue by NiklasBr** [jellyfin/jellyfin#11923]
### Please describe your bug

I had been waiting for #11743 because replacing metadata did not work in 10.9.x, unfortunately it seems that my issue was not resolved with the recent released version.

### Reproduction Steps

After adding a movie to the library folder, scan it and identify it.

At a later date, run *Refresh metadata* with the option *Replace all metadata* selected.

Many things, like tags/genre, description and so on will be replaced, but the movie title will always remain the same.

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS: Windows 11 Pro (23H2)
- Linux Kernel: -
- Virtualization: -
- Clients: Tray app + Web browser
- Browser: Firefox v126
- FFmpeg Version:  7.0.1-essentials_build-www.gyan.dev
- Playback Method: -
- Hardware Acceleration: None
- GPU Model: AMD Radeon RX 5700
- Plugins:
  - AudioDB 10.9.4.0 (active)
  - InfuseSync 1.5.0.0 (active)
  - MusicBrainz 10.9.4.0 (active)
  - OMDb 10.9.4.0 (active)
  - Studio Images 10.9.4.0 (active)
  - TMDb 10.9.4.0 (active)
- Reverse Proxy: -
- Base URL: http://localhost:8096/web/index.html
- Networking: Ethernet
- Storage: Local HDD
```

### Jellyfin logs

```shell
[2024-06-02 00:00:38.470 +02:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 00:30:37.998 +02:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 01:00:38.590 +02:00] [INF] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 01:30:38.163 +02:00] [INF] [73] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 01:59:59.804 +02:00] [INF] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-06-02 02:00:00.000 +02:00, which is 00:00:00.1959444 from now.
[2024-06-02 01:59:59.957 +02:00] [INF] [76] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Extract Chapter Images" Completed after 0 minute(s) and 1 seconds
[2024-06-02 02:00:00.687 +02:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Extract Chapter Images" Completed after 0 minute(s) and 0 seconds
[2024-06-02 02:00:01.017 +02:00] [INF] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-06-03 02:00:00.000 +02:00, which is 23:59:58.9821186 from now.
[2024-06-02 02:00:37.959 +02:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 02:30:37.989 +02:00] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 03:00:38.326 +02:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 03:30:38.791 +02:00] [INF] [77] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 04:00:37.981 +02:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 04:30:38.795 +02:00] [INF] [68] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 05:00:38.499 +02:00] [INF] [110] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 05:30:37.871 +02:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 06:00:38.253 +02:00] [INF] [41] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 06:30:38.539 +02:00] [INF] [90] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 07:00:37.901 +02:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 07:30:38.018 +02:00] [INF] [112] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 08:00:37.847 +02:00] [INF] [119] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 08:30:38.637 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 09:00:38.414 +02:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 09:30:37.954 +02:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 10:00:38.310 +02:00] [INF] [111] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 4 seconds
[2024-06-02 10:30:37.832 +02:00] [INF] [119] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Add Collection" Completed after 0 minute(s) and 3 seconds
[2024-06-02 10:42:14.677 +02:00] [INF] [1] Main: Jellyfin version: "10.9.4"
[2024-06-02 10:42:14.701 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-06-02 10:42:14.704 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-06-02 10:42:14.706 +02:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.22631"
[2024-06-02 10:42:14.707 +02:00] [INF] [1] Main: Architecture: X64
[2024-06-02 10:42:14.708 +02:00] [INF] [1] Main: 64-Bit Process: True
[2024-06-02 10:42:14.708 +02:00] [INF] [1] Main: User Interactive: True
[2024-06-02 10:42:14.709 +02:00] [INF] [1] Main: Processor count: 8
[2024-06-02 10:42:14.710 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-06-02 10:42:14.711 +02:00] [INF] [1] Main: Log directory path: "C:\ProgramData\Jellyfin\Server\log"
[2024-06-02 10:42:14.711 +02:00] [INF] [1] Main: Config directory path: "C:\ProgramData\Jellyfin\Server\config"
[2024-06-02 10:42:14.712 +02:00] [INF] [1] Main: Cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2024-06-02 10:42:14.713 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-06-02 10:42:14.714 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-06-02 10:42:15.583 +02:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2024-06-02 10:42:16.393 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-06-02 10:42:16.854 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "C:\ProgramData\Jellyfin\Server\plugins\InfuseSync_1.4.2.0\InfuseSync.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'.
Could not load file or assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'.
System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[2024-06-02 10:42:18.064 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-06-02 10:42:18.067 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-06-02 10:42:18.068 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-06-02 10:42:18.071 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.1.121", "127.0.0.1", "2a00:1598:cd28:500:9d0a:1bca:abba:d183", "2a00:1598:cd28:500:4d65:3fc0:2f1f:84c4", "2a00:1598:cd28:500:91c1:2758:f1f0:895d", "fe80::237d:6166:3496:3ea6%17", "::1"]
[2024-06-02 10:42:18.074 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[2024-06-02 10:42:18.076 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-06-02 10:42:18.077 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-06-02 10:42:22.046 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.4.0"
[2024-06-02 10:42:22.048 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.4.0"
[2024-06-02 10:42:22.049 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.4.0"
[2024-06-02 10:42:22.093 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.4.0"
[2024-06-02 10:42:22.095 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.4.0"
[2024-06-02 10:42:22.155 +02:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"FixAudioData"'
[2024-06-02 10:42:22.173 +02:00] [INF] [1] Jellyfin.Server.Migrations.Routines.FixAudioData: Library database backed up to "C:\ProgramData\Jellyfin\Server\data\library.db.bak2"
[2024-06-02 10:42:22.175 +02:00] [INF] [1] Jellyfin.Server.Migrations.Routines.FixAudioData: Backfilling audio lyrics data to database.
[2024-06-02 10:42:22.213 +02:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"FixAudioData"' applied successfully
[2024-06-02 10:42:22.229 +02:00] [INF] [1] Main: Kestrel is listening on "all interfaces"
[2024-06-02 10:42:22.522 +02:00] [INF] [1] Jellyfin.Networking.PortForwardingHost: Starting NAT discovery
[2024-06-02 10:42:23.202 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-06-02 10:42:23.203 +02:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "M:\Plex"
[2024-06-02 10:42:23.243 +02:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-06-03 02:00:00.000 +02:00, which is 15:17:36.7564045 from now.
[2024-06-02 10:42:23.413 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-06-02 10:42:23.453 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-06-02 10:42:23.488 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mjpeg_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-06-02 10:42:23.522 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-06-02 10:42:23.645 +02:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2024-06-02 10:42:23.671 +02:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vulkan" with option "Action to take when encountering EOF from secondary input" is not available
[2024-06-02 10:42:23.697 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2024-06-02 10:42:23.839 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2024-06-02 10:42:23.847 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "5a4f04d6e2d7476c95d280c970385018"
[2024-06-02 10:42:23.849 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-06-02 10:42:23.850 +02:00] [INF] [1] Main: Startup complete 0:00:10.3320714
[2024-06-02 10:42:26.285 +02:00] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "M:\Plex"
[2024-06-02 10:42:26.289 +02:00] [INF] [15] Emby.Server.Implementations.Library.LibraryManager: Validating media library
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Did you by chance lock metadata for the title?

**Comment by NiklasBr** [comment]
Just double-checked. No. And even if I had, then why would some fields like description still be updated but the title be kept as is?

**Comment by maru801** [comment]
> Just double-checked. No. And even if I had, then why would some fields like description still be updated but the title be kept as is?

It's possible to only lock specific fields of the metadata. Instead of clicking on the checkbox that locks it all, you simply scroll a bit more down on the metadata pop-ups and uncheck which field(s) you want to keep locked.

**Comment by NiklasBr** [comment]
Thanks, it was not clear from the UI. But unfortunately that was not the issue, still no, I'm not locking any fields at all with either method.

**Comment by Shadowghost** [comment]
I tried replicating this yesterday but was unable to do so. 😞

**Comment by NiklasBr** [comment]
Anything else I can do to improve the steps you use to reproduce the issue?

**Comment by kandykarter** [comment]
I have this same issue, seems to be related to the ability to re-write nfo files. Delete the nfo, then try again and it'll work.

**Comment by NiklasBr** [comment]
Interesting.

I deleted the corresponding .NFO file but when scanning the library the lone movie never appears again. I had to rename the movie file to get it to re-appear. Then after re-identifying it it will will not set the *Title* field to anything other than the filename sans extension.

Jellyfin did downloaded and set the following metadata again:

- Cast & Crew
- Description
- Studio
- Genre
- Rating

**Comment by MadaxDeLuXe** [comment]
After the update from 10.9.3 to 10.9.4 I've had a simmilar issue with a CONTAINERIZED instance: Not updating the filename with the movie title, downloading covers, ... Even when manually selecting "edit pictures" and clicking the magnifier didn't bring up any pictures.

Stopping the container, deleting the container (NOT the mapped files), and executing the compose again to create a new one did the job for me.

**Comment by LevitatingBusinessMan** [comment]
I think I am also stumbling upon this issue with my shows. All of my show and episode titles are the filename or the name of the show.

With movies it correctly sets the "Original Title" but doesn't set the actual title.

**Comment by LevitatingBusinessMan** [comment]
> I have this same issue, seems to be related to the ability to re-write nfo files. Delete the nfo, then try again and it'll work.

I also got it to work by deleting the nfo files on 10.9.4. With 10.9.3 I don't think that fix worked.

**Comment by MadaxDeLuXe** [comment]
Had Problems with names and images, too (didn't find any pics) after
updating from 10.9.3 to .4.

Stopping, deleting (Container, Volumes, everything) and rebuilding then
copying over my configs + DB + a.s.o fixed it for me.

And the Code in "web" and other "awesome jellyfin" files had changed, so
ist quit mounting my old files and startet SEDing them @boot instead. Works
like a charm now.
Maybe check that..

Rein Fernhout ***@***.***> schrieb am Mi., 5. Juni 2024,
02:42:

**Comment by Znuff** [comment]
I'm gonna #metoo on this one, as I feel like this is related/similar.


I'm using Sonarr/Radarr to write `.NFO` files to disk, next to my media. Those `.NFO` files have always been in English, because *I* prefer English.

But I set up Jellyfin to scrape all the Metadata in Romanian for all my Libraries, and usually a Refresh with "Replace all metadata" would have brought in all the info in Romanian wherever it was possible.

Since 10.9.x, this doesn't seem to be possible anymore.

No matter what I do, even down to changing an individual episode's preferred Metadata language to Romanian, it's still "stuck" on English. 

I also do notice that when I *do* a refresh, it *does* seem to pull in more info (than what it gets from the `.NFO` files), stuff like Cast info, which is not fully in the `.NFO` files.

**Comment by Shadowghost** [comment]
@Znuff the linked PR should fix your issue.

**Comment by NiklasBr** [comment]
10.9.6 fixed this for me, thanks @Shadowghost!

@Znuff how about for you?

**Comment by Znuff** [comment]
That specific PR that @Shadowghost mentioned hasn't been merged yet, from what I can see.

And no, I did already try 10.9.6, problem still exists. Episode descriptions & everything else is still not replaced.

**Comment by NiklasBr** [comment]
I suspect specifically #11921 fixed my issue.

**Comment by Shadowghost** [comment]
@Znuff  please open a new issue, this one here is fixed.
Yours appears because the changed replace logic always prefers NFOs - the 10.8 behavior allowed you to override it but it would've reverted if you ever changed the NFOs.
