### ISSUE TITLE
Crashing repeatedly on connection to api.themoviedb.org

### ISSUE THREAD

**Issue by drgnomage** [jellyfin/jellyfin#1193]
Description:

During routine scans of local files the server is attempting to reach api.themoviedb.org and it seems to be sending unexpected data back.
<br>
Reproduction:

I'm not sure what is causing the issue, I was only made aware of it by someone complaining that their download was dropping.
<br>
Expected:

No crashing during scan.
<br>

Log:
<details>

```
Apr 03 18:38:05 Media dotnet[25787]: [18:38:05] [INF] HttpClientManager GET: https://api.themoviedb.org/3/tv/82812?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings&language=en&include_image_language=en,null
Apr 03 18:38:05 Media dotnet[25787]: [18:38:05] [ERR] Error ProtocolError getting response from https://api.themoviedb.org/3/tv/82812?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings&language=en&include_image_language=en,null
Apr 03 18:38:05 Media dotnet[25787]: System.Net.WebException: The remote server returned an error: (404) Not Found.
Apr 03 18:38:05 Media dotnet[25787]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
Apr 03 18:38:05 Media dotnet[25787]:    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
Apr 03 18:38:06 Media dotnet[25787]: [18:38:05] [ERR] Error in TheMovieDb
Apr 03 18:38:06 Media dotnet[25787]: MediaBrowser.Model.Net.HttpException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
Apr 03 18:38:06 Media dotnet[25787]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
Apr 03 18:38:06 Media dotnet[25787]:    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
Apr 03 18:38:06 Media dotnet[25787]:    --- End of inner exception stack trace ---
Apr 03 18:38:06 Media dotnet[25787]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 403
Apr 03 18:38:06 Media dotnet[25787]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 241
Apr 03 18:38:06 Media dotnet[25787]:    at MediaBrowser.Providers.Movies.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/Movies/MovieDbProvider.cs:line 429
Apr 03 18:38:06 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.FetchMainResult(String id, String language, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 373
Apr 03 18:38:06 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.FetchMovieData(String tmdbId, String language, String preferredCountryCode, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 180
Apr 03 18:38:06 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 170
Apr 03 18:38:06 Media dotnet[25787]:    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
Apr 03 18:38:07 Media dotnet[25787]: [18:38:07] [INF] HttpClientManager GET: https://api.themoviedb.org/3/tv/82812?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings&language=en&include_image_language=en,null
Apr 03 18:38:07 Media dotnet[25787]: [18:38:07] [ERR] Error ProtocolError getting response from https://api.themoviedb.org/3/tv/82812?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings&language=en&include_image_language=en,null
Apr 03 18:38:07 Media dotnet[25787]: System.Net.WebException: The remote server returned an error: (404) Not Found.
Apr 03 18:38:07 Media dotnet[25787]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
Apr 03 18:38:07 Media dotnet[25787]:    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
Apr 03 18:38:07 Media dotnet[25787]: [18:38:07] [ERR] Error in TheMovieDb
Apr 03 18:38:07 Media dotnet[25787]: MediaBrowser.Model.Net.HttpException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
Apr 03 18:38:07 Media dotnet[25787]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
Apr 03 18:38:07 Media dotnet[25787]:    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
Apr 03 18:38:07 Media dotnet[25787]:    --- End of inner exception stack trace ---
Apr 03 18:38:07 Media dotnet[25787]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 403
Apr 03 18:38:07 Media dotnet[25787]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 241
Apr 03 18:38:07 Media dotnet[25787]:    at MediaBrowser.Providers.Movies.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/Movies/MovieDbProvider.cs:line 429
Apr 03 18:38:07 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.FetchMainResult(String id, String language, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 373
Apr 03 18:38:07 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.FetchMovieData(String tmdbId, String language, String preferredCountryCode, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 180
Apr 03 18:38:07 Media dotnet[25787]:    at MediaBrowser.Providers.TV.TheMovieDb.MovieDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken) in /home/josh/.cache/yay/jellyfin/src/jellyfin-10.2.2/MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs:line 170
Apr 03 18:38:07 Media dotnet[25787]:    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
Apr 03 18:38:08 Media dotnet[25787]: [18:38:08] [INF] HttpClientManager GET: https://www.theaudiodb.com/api/v1/json/195003/album-mb.php?i=4e98c9b4-92f6-3049-b9da-a1088b623672
Apr 03 18:38:08 Media dotnet[25787]: [18:38:08] [FTL] Unhandled Exception
Apr 03 18:38:08 Media dotnet[25787]: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
Apr 03 18:38:08 Media dotnet[25787]:    --- End of inner exception stack trace ---
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.ThrowIfExceptional()
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Apr 03 18:38:08 Media dotnet[25787]: --- End of stack trace from previous location where exception was thrown ---
Apr 03 18:38:08 Media dotnet[25787]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Apr 03 18:38:08 Media audit[25787]: ANOM_ABEND auid=4294967295 uid=991 gid=991 ses=4294967295 pid=25787 comm="dotnet" exe="/opt/dotnet/dotnet" sig=6 res=1
Apr 03 18:38:08 Media dotnet[25787]: Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
Apr 03 18:38:08 Media dotnet[25787]:    --- End of inner exception stack trace ---
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.ThrowIfExceptional()
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Apr 03 18:38:08 Media dotnet[25787]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Apr 03 18:38:08 Media dotnet[25787]: --- End of stack trace from previous location where exception was thrown ---
Apr 03 18:38:08 Media dotnet[25787]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Apr 03 18:38:08 Media kernel: audit: type=1701 audit(1554313088.754:2277): auid=4294967295 uid=991 gid=991 ses=4294967295 pid=25787 comm="dotnet" exe="/opt/dotnet/dotnet" sig=6 res=1
Apr 03 18:38:09 Media systemd-coredump[3678]: Removed old coredump core.dotnet.991.71b9270155134991a98e571c8dc3b68a.7303.1554291944000000.lz4.
```
</details>
</div>
<br><br>
System Info:

 - OS: Antegros 

 - Jellyfin Version: 10.2.2.0

 - Reverse proxy: Apache
<br>

**Comment by drgnomage** [comment]
I've also been running an strace and found that Jellyfin is calling some dotnet files that don't exist but the directory does.


[pid 18502] stat("/opt/dotnet/shared/Microsoft.NETCore.App/2.2.1/System.Net.Sockets.pdb", 0x7fb756ff88e0) = -1 ENOENT (No such file or directory)
[pid 18502] lstat("/opt/dotnet/shared/Microsoft.NETCore.App/2.2.1/System.Net.Sockets.pdb", 0x7fb756ff8900) = -1 ENOENT (No such file or directory

**Comment by anthonylavado** [comment]
@drgnomage Hey there! Just to ask - how was this version of Jellyfin installed? Did you build it from the master branch, or did you use a download that we have on our repo?

Also, to be sure, were you looking up information for the TV Series "Troutmann"?

**Comment by drgnomage** [comment]
@anthonylavado Hi! I installed it from the AUR so I believe it's the master branch, is there something I can do to check once it's installed?

I have never heard of "Troutmann", so that's a no.

To get rid of this error, I've been using the Open databases as they function correctly for me.

**Comment by DrPandemic** [comment]
If I'm not mistaken this issue is a duplicate of https://github.com/jellyfin/jellyfin/issues/465 (except the fact that it crashes for movies rather than music). But I'm pretty sure the root cause is the same

**Comment by drgnomage** [comment]
Hi @DrPandemic,

It does indeed look very similar, I would say it most likely has the same root cause as well.  I will close this and follow #465.
