### ISSUE TITLE
Crash on FLAC Audio Playback

### ISSUE THREAD

**Issue by omniusaspirer** [jellyfin/jellyfin#1197]
**Describe the bug**
When playing FLAC audio on a new Jellyfish install, audio will randomly crash mid playback.

**To Reproduce**
Play a few songs until you hit a crash. (No idea whether system dependent or not)

**Expected behavior**
Audio playback will not crash.

**Logs**
<details>

```
[2019-04-04 11:15:15.080 -04:00] [INF] HTTP Response 200 to "ip". Time: "109""ms". "http://ip:8096/emby/system/info/public" ""
[2019-04-04 11:15:15.081 -04:00] [INF] "HTTP GET" "http://ip:8096/emby/system/info/public". UserAgent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
[2019-04-04 11:15:15.083 -04:00] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage)
[2019-04-04 11:15:15.084 -04:00] [INF] HTTP Response 500 to "127.0.0.1". Time: "93083""ms". "http://localhost:8096/emby/Audio/95343ba27dd8f6fe6b13226c36ead18e/universal?UserId=2e98a26b421a4fcfa4422dcbc842d8d7&DeviceId=6d2c28edac71924d13f3c161dd6464f4&MaxStreamingBitrate=140000000&Container=opus,mp3|mp3,aac,m4a|aac,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1554329700297&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false" ""
[2019-04-04 11:15:15.092 -04:00] [INF] "HTTP GET" "http://localhost:8096/emby/Audio/95343ba27dd8f6fe6b13226c36ead18e/universal?UserId=2e98a26b421a4fcfa4422dcbc842d8d7&DeviceId=6d2c28edac71924d13f3c161dd6464f4&MaxStreamingBitrate=140000000&Container=opus,mp3|mp3,aac,m4a|aac,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1554329700297&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false". UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
```
</details>

**Screenshots**
Not applicable.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Jellyfin Version: 10.2.2
 - Reverse proxy: None, brand new install.

**Additional context**
None.

**Comment by screwfaze** [comment]
I noticed this too on docker using chrome

**Comment by omniusaspirer** [comment]
Been playing around with this more after updating to 10.3.0-rc2. I'm not able to see any actual errors occurring, and the issue instead seems related to an overall loss of performance within the Jellyfin tab itself on my up to date Firefox install. Overall memory consumption for the tab starts pretty low but gradually climbs to well over 1 GB.

**Comment by ferferga** [comment]
My library is 99.5% FLAC and I had not issues running Jellyfin 10.3 on Raspberry Pi 3 armhf (packages from repository) and playing them in Chrome on Windows. The only issue I'm having with FLAC is that it's impossible to play them in the Android app, but that's another issue.

**Comment by mazzystr** [comment]
Confirmed.  I can't play flac on Firefox browser or Android mobile app.
