### ISSUE TITLE
[Issue]: readonly db PR has broken EPG data update

### ISSUE THREAD

**Issue by bin101** [jellyfin/jellyfin#11985]
### Please describe your bug

#11969 has broken EPG data update

Maybe this is important:

I use 1 local m3u playlist for the TV Channels und 3 remote xmltv providers for the epg data.

### Reproduction Steps

Press "Refresh Guide Data" in "Live TV"

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.4
- Virtualization: LXC
- Clients: n/a
- Browser: n/a
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: n/a
- Reverse Proxy: n/a
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Jellyfin logs

```shell
Jun 06 08:14:09 jellyfin jellyfin[64916]: [08:14:09] [ERR] [10] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel 3sat
Jun 06 08:14:09 jellyfin jellyfin[64916]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(SqliteConnection db, IEnumerable`1 tuples)
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
Jun 06 08:14:09 jellyfin jellyfin[64916]:    at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bin101** [comment]
Duplicate of #11980
