### ISSUE TITLE
[Issue]: restart via web interface fails due to attempt to write a readonly database

### ISSUE THREAD

**Issue by errror** [jellyfin/jellyfin#12014]
### Please describe your bug

When initiating a server restart via the web interface, the service does not start again but remains stopped. The log states `[FTL] Error while starting server`, see section _Jellyfin logs_ for whole log. As systemd does not restart the service, the exit code of jellyfin must have been 0 or 143, `jellyfin.service` not unmodified.

### Reproduction Steps

1. Login as admin on web interface
2. Go to adminstrative overview
3. push restart button and confirm
4. server shuts down but does not start again

### Jellyfin Version

10.9.0

### if other:

10.9.5

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-21-amd64
- Virtualization: systemd-nspawn
- Clients: Browser, Android, Fire Stick, DLNA, IOS, ...
- Browser: Firefox 115.11.0esr
- FFmpeg Version: 6.0.1-7-bookworm (from jellyfin-ffmpeg6)
- Playback Method: Direct Play, Transcode, ...
- Hardware Acceleration: none
- GPU Model: none
- Plugins: DLNA, Kodi Sync Queue Kodi Sync Queue, LDAP Authentication, Playback Reporting, Reports, TheTVDB, TMDb Box Sets, TVmaze, Webhook
- Reverse Proxy: apache
- Base URL: /
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
Jun 07 11:26:43 media jellyfin[931085]: [11:26:43] [INF] Sending shutdown notifications
Jun 07 11:26:43 media jellyfin[931085]: [11:26:43] [INF] WS 139.19.228.8 closed
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] WS ::ffff:192.168.178.124 closed
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping NAT discovery
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing SsdpDevicePublisher
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing PlayToManager
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Running query planner optimizations in the database... This might take a while
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] SsdpCommunicationsServer disposing _BroadcastListenSocket
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] SsdpCommunicationsServer Disposing 1 sendSockets
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] SsdpCommunicationsServer disposing sendSocket from 192.168.178.127
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping directory watching for path /var/lib/jellyfin/data/collections
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping directory watching for path /ANONYMIZED
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping directory watching for path /ANONYMIZED
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping directory watching for path /ANONYMIZED
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Stopping directory watching for path /ANONYMIZED
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing CoreAppHost
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing MusicBrainzArtistProvider
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing MusicBrainzAlbumProvider
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing KodiSyncQueuePlugin
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing PluginManager
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Setting cache path: /var/cache/jellyfin
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loading assemblies
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Dlna, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Rssdp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_2.0.0.0/Rssdp.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Kodi Sync Queue_11.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly LiteDB, Version=5.0.15.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from /var/lib/jellyfin/plugins/Kodi Sync Queue_11.0.0.0/LiteDB.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f from /var/lib/jellyfin/plugins/LDAP Authentication_19.0.0.0/Novell.Directory.Ldap.NETStandard.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly LDAP-Auth, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/LDAP Authentication_19.0.0.0/LDAP-Auth.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Tvdb, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Jellyfin.Plugin.Tvdb.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Tvdb.Sdk.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TVmaze_11.0.0.0/Flurl.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.TvMaze, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TVmaze_11.0.0.0/Jellyfin.Plugin.TvMaze.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TVmaze_11.0.0.0/TvMaze.Api.Client.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc from /var/lib/jellyfin/plugins/TVmaze_11.0.0.0/Polly.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TVmaze_11.0.0.0/Flurl.Http.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly MimeKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814 from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/MimeKit.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly MQTTnet, Version=4.3.4.1084, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/MQTTnet.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Handlebars, Version=2.1.6.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661 from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/Handlebars.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly MailKit, Version=4.5.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/MailKit.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly Jellyfin.Plugin.Webhook, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/Jellyfin.Plugin.Webhook.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly MQTTnet.Extensions.ManagedClient, Version=4.3.4.1084, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/MQTTnet.Extensions.ManagedClient.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Loaded assembly BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938 from /var/lib/jellyfin/plugins/Webhook_14.0.0.0/BouncyCastle.Cryptography.dll
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Defined LAN subnets: ["ANONYMIZED"]
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Defined LAN exclusions: []
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Used LAN subnets: ["ANONYMIZED"]
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Filtered interface addresses: ["ANONYMIZED"]
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Bind Addresses ["::"]
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Remote IP filter is Allowlist
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Filtered subnets: []
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [FTL] Error while starting server
Jun 07 11:26:44 media jellyfin[931085]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
Jun 07 11:26:44 media jellyfin[931085]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Jun 07 11:26:44 media jellyfin[931085]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jun 07 11:26:44 media jellyfin[931085]:    at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
Jun 07 11:26:44 media jellyfin[931085]:    at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
Jun 07 11:26:44 media jellyfin[931085]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
Jun 07 11:26:44 media jellyfin[931085]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
Jun 07 11:26:44 media jellyfin[931085]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Jun 07 11:26:44 media jellyfin[931085]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Running query planner optimizations in the database... This might take a while
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing CoreAppHost
Jun 07 11:26:44 media jellyfin[931085]: [11:26:44] [INF] Disposing PluginManager
Jun 07 11:26:44 media systemd[1]: jellyfin.service: Deactivated successfully.
Jun 07 11:26:44 media systemd[1]: jellyfin.service: Consumed 21.680s CPU time.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
We suspect this is due to some plugins. Can you try disable the plugins one by one to isolate which one caused this?

**Comment by Strit** [comment]
Have you tried with 10.9.6 to see if it's fixed?

**Comment by Hello-World-Traveler** [comment]
10.10.1


```
jellyfin.service: Deactivated successfully.
systemd

 [INF] Disposing PluginManager
jellyfin

 [INF] Disposing CoreAppHost
jellyfin

 [INF] Running query planner optimizations in the database... This might take a while
jellyfin

at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
jellyfin

at Emby.Server.Implementations.ApplicationHost.InitializeServices()
jellyfin

at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
jellyfin

at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
jellyfin

at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
jellyfin

at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
jellyfin

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
jellyfin

[FTL] Error while starting server
```

**Comment by Hello-World-Traveler** [comment]
I found the issue to be Playback Reporting. Once disabled the server updated the plugin to 15.0.0.0 and then I found https://github.com/jellyfin/jellyfin-plugin-playbackreporting/issues/89
