### ISSUE TITLE
[Issue]: Trickplay log errors

### ISSUE THREAD

**Issue by mjeshurun** [jellyfin/jellyfin#12033]
### Please describe your bug

When generating Trickplay images on Jellyfin 10.9.6 installed with Hotio's docker container, I got the following error message on the log for various media files.

### Reproduction Steps

Manually run the Generate Trickplay Images task.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: UnRAID 6.12.10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: CometLake-S GT2 [UHD Graphics 630]
- Plugins:
- Reverse Proxy: NginxProxyManager
- Base URL:
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
[22:37:39] [INF] [54] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv [ID: 942f4ba6-8769-1145-4e9b-00cfefe584cf]
[22:37:39] [INF] [54] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=320:h=132:extra_hw_frames=24,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg"
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
[22:39:39] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: Attempting to cancel Scheduled Task Generate Trickplay Images
[22:39:39] [INF] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Stopping trickplay extraction.
[22:39:40] [INF] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Killing ffmpeg process
[22:39:40] [ERR] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=320:h=132:extra_hw_frames=24,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg"
[22:39:40] [ERR] [40] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=320:h=132:extra_hw_frames=24,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg"
at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractVideoImagesOnIntervalInternal(String inputArg, String filterParam, String vidEncoder, Nullable1 outputThreads, Nullable1 qualityScale, Nullable`1 priority, CancellationToken cancellationToken)
at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[22:39:40] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate Trickplay Images Cancelled after 2 minute(s) and 1 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
If you can get into the container shell, can you execute the command manually and see what is the error it reports? `/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=320:h=132:extra_hw_frames=24,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg"`

**Comment by gnattu** [comment]
Then it means no error is ever logged, can you try again removing the `-loglevel error` ?

**Comment by mjeshurun** [comment]
```
root@e094338beaad:/# /usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device /usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=320:h=132:extra_hw_frames=24,hwmap=derive_device=opencl,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:reverse=1:extra_hw_frames=16,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg"
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
Input #0, matroska,webm, from 'file:/data/media/tv/Masters of the Air/Masters.of.the.Air.S01E03.HDR.2160p.WEB.h265-ETHEL[TGx].mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
  Duration: 00:48:43.39, start: 0.000000, bitrate: 23471 kb/s
  Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1606 [SAR 1:1 DAR 1920:803], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 22696246
      DURATION        : 00:48:43.379000000
      NUMBER_OF_FRAMES: 70091
      NUMBER_OF_BYTES : 8293716473
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      BPS             : 768000
      DURATION        : 00:48:43.392000000
      NUMBER_OF_FRAMES: 91356
      NUMBER_OF_BYTES : 280645632
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip (default) (forced)
    Metadata:
      title           : English (forced)
      BPS             : 18
      DURATION        : 00:00:15.766000000
      NUMBER_OF_FRAMES: 4
      NUMBER_OF_BYTES : 37
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS             : 56
      DURATION        : 00:42:34.304000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 18059
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS             : 64
      DURATION        : 00:42:34.304000000
      NUMBER_OF_FRAMES: 621
      NUMBER_OF_BYTES : 20723
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(ara): Subtitle: subrip
    Metadata:
      title           : العربية
      BPS             : 78
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 28233
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(bul): Subtitle: subrip
    Metadata:
      title           : български
      BPS             : 74
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 441
      NUMBER_OF_BYTES : 26780
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(cze): Subtitle: subrip
    Metadata:
      title           : Čeština
      BPS             : 46
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 541
      NUMBER_OF_BYTES : 16639
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(dan): Subtitle: subrip
    Metadata:
      title           : dansk
      BPS             : 49
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 515
      NUMBER_OF_BYTES : 17861
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(ger): Subtitle: subrip
    Metadata:
      title           : Deutsch
      BPS             : 57
      DURATION        : 00:42:52.781000000
      NUMBER_OF_FRAMES: 530
      NUMBER_OF_BYTES : 18615
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10(gre): Subtitle: subrip
    Metadata:
      title           : Ελληνικά
      BPS             : 84
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 559
      NUMBER_OF_BYTES : 30489
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:11(spa): Subtitle: subrip
    Metadata:
      title           : Español (Latinoamérica)
      BPS             : 52
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 18891
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:12(spa): Subtitle: subrip
    Metadata:
      title           : Español (España)
      BPS             : 51
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 581
      NUMBER_OF_BYTES : 18569
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:13(est): Subtitle: subrip
    Metadata:
      title           : eesti
      BPS             : 48
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 17398
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:14(fin): Subtitle: subrip
    Metadata:
      title           : Suomi
      BPS             : 48
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 543
      NUMBER_OF_BYTES : 17463
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:15(fre): Subtitle: subrip
    Metadata:
      title           : Français (Canada)
      BPS             : 46
      DURATION        : 00:48:07.596000000
      NUMBER_OF_FRAMES: 651
      NUMBER_OF_BYTES : 16921
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:16(fre): Subtitle: subrip
    Metadata:
      title           : Français (France)
      BPS             : 46
      DURATION        : 00:48:07.596000000
      NUMBER_OF_FRAMES: 650
      NUMBER_OF_BYTES : 16900
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:17(heb): Subtitle: subrip
    Metadata:
      title           : עברית
      BPS             : 71
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 25771
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:18(hin): Subtitle: subrip
    Metadata:
      title           : हिन्दी
      BPS             : 140
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 50671
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:19(hun): Subtitle: subrip
    Metadata:
      title           : magyar
      BPS             : 49
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 568
      NUMBER_OF_BYTES : 17819
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:20(ind): Subtitle: subrip
    Metadata:
      title           : Bahasa Indonesia
      BPS             : 54
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 574
      NUMBER_OF_BYTES : 19561
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:21(ita): Subtitle: subrip
    Metadata:
      title           : Italiano
      BPS             : 53
      DURATION        : 00:48:04.176000000
      NUMBER_OF_FRAMES: 539
      NUMBER_OF_BYTES : 19305
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:22(jpn): Subtitle: subrip
    Metadata:
      title           : 日本語
      BPS             : 42
      DURATION        : 00:48:29.743000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 15635
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:23(kor): Subtitle: subrip
    Metadata:
      title           : 한국어
      BPS             : 51
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 18549
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:24(lit): Subtitle: subrip
    Metadata:
      title           : lietuvių
      BPS             : 50
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 574
      NUMBER_OF_BYTES : 18271
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:25(lav): Subtitle: subrip
    Metadata:
      title           : latviešu
      BPS             : 52
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 566
      NUMBER_OF_BYTES : 18790
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:26(may): Subtitle: subrip
    Metadata:
      title           : Bahasa Melayu
      BPS             : 53
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 573
      NUMBER_OF_BYTES : 19490
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:27(dut): Subtitle: subrip
    Metadata:
      title           : Nederlands
      BPS             : 44
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 448
      NUMBER_OF_BYTES : 15902
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:28(nor): Subtitle: subrip
    Metadata:
      title           : norsk
      BPS             : 46
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 474
      NUMBER_OF_BYTES : 16796
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:29(pol): Subtitle: subrip
    Metadata:
      title           : polski
      BPS             : 44
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 550
      NUMBER_OF_BYTES : 16106
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:30(por): Subtitle: subrip
    Metadata:
      title           : Português (Brasil)
      BPS             : 49
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 536
      NUMBER_OF_BYTES : 17975
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:31(por): Subtitle: subrip
    Metadata:
      title           : Português
      BPS             : 53
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 574
      NUMBER_OF_BYTES : 19333
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:32(rus): Subtitle: subrip
    Metadata:
      title           : Русский
      BPS             : 76
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 557
      NUMBER_OF_BYTES : 27651
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:33(slo): Subtitle: subrip
    Metadata:
      title           : Slovenčina
      BPS             : 48
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 575
      NUMBER_OF_BYTES : 17660
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:34(slv): Subtitle: subrip
    Metadata:
      title           : slovenščina
      BPS             : 42
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 495
      NUMBER_OF_BYTES : 15197
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:35(swe): Subtitle: subrip
    Metadata:
      title           : Svenska
      BPS             : 50
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 573
      NUMBER_OF_BYTES : 18393
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:36(tam): Subtitle: subrip
    Metadata:
      title           : தமிழ்
      BPS             : 181
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 65422
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:37(tel): Subtitle: subrip
    Metadata:
      title           : తెలుగు
      BPS             : 162
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 58763
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:38(tha): Subtitle: subrip
    Metadata:
      title           : ไทย
      BPS             : 114
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 41444
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:39(tur): Subtitle: subrip
    Metadata:
      title           : Türkçe
      BPS             : 50
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 544
      NUMBER_OF_BYTES : 18143
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:40(ukr): Subtitle: subrip
    Metadata:
      title           : українська
      BPS             : 74
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 27034
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:41(vie): Subtitle: subrip
    Metadata:
      title           : Tiếng Việt
      BPS             : 68
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 575
      NUMBER_OF_BYTES : 24648
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:42(chi): Subtitle: subrip
    Metadata:
      title           : 中文（简体）
      BPS             : 47
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 576
      NUMBER_OF_BYTES : 17196
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:43(chi): Subtitle: subrip
    Metadata:
      title           : 廣東話
      BPS             : 44
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 15901
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:44(chi): Subtitle: subrip
    Metadata:
      title           : 中文（繁體）
      BPS             : 50
      DURATION        : 00:48:08.889000000
      NUMBER_OF_FRAMES: 577
      NUMBER_OF_BYTES : 18269
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> mjpeg (mjpeg_qsv))
Press [q] to stop, [?] for help
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
Output #0, image2, to '/config/cache/temp/f6520cdd40664f94a468480ca27c7c6c/%08d.jpg':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0(eng): Video: mjpeg, qsv(tv, bt709, progressive), 320x132 [SAR 72:73 DAR 1920:803], q=2-31, 200 kb/s, 0.10 fps, 0.10 tbn (default)
    Metadata:
      BPS             : 22696246
      DURATION        : 00:48:43.379000000
      NUMBER_OF_FRAMES: 70091
      NUMBER_OF_BYTES : 8293716473
      _STATISTICS_WRITING_APP: mkvmerge v80.0 ('Roundabout') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc60.3.100 mjpeg_qsv
frame=  292 fps=1.0 q=-0.0 Lsize=N/A time=00:48:29.99 bitrate=N/A speed=10.2x    ts/s speed=N/A    
video:7479kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
root@e094338beaad:/# 
```

**Comment by gnattu** [comment]
So it looks like it does completes successfully. So probably that error is because you made some operation that cancels the trickplay generation, as this file does works properly with your settings.

**Comment by mjeshurun** [comment]
Ok, thank you for your help :)
I guess this issue is closed then.

**Comment by mjeshurun** [comment]
Ok, thank you for your help :)
I guess this issue is closed then.
