### ISSUE TITLE
[Issue]: Update Playlist API endpoint returning "Error processing request."

### ISSUE THREAD

**Issue by jmaximusix** [jellyfin/jellyfin#12092]
### Please describe your bug

I tried to update a playlist according to the [API documentation](https://api.jellyfin.org), but it only returns 400 "Error processing request."

### Reproduction Steps

The issue is specifically about **updating** the playlist.

To reproduce:

- Create a playlist using this `curl` request:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: MediaBrowser Token=\"redacted\"" -d '{"Name":"Cool Songs", "Ids":["df24f0ad2258f9478bfa83140655c173", "e5212f83f25b70bacf5b861e0c2a283a"], "UserId":"1741114c47c04c619998619b2ac0ebdf", "MediaType": "Audio", "IsPublic":false}' "http://localhost:8096/Playlists"
```

- the request succeeds and returns a playlist id, in my case 1aa728d63cb5f14ea3c9f59aaf5cdc39

- Now I tried updating the playlist, leaving the first song the same, but swapping out the second one for another. I used this request:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: MediaBrowser Token=\"redacted\"" -d '{"Name":"Cool Songs", "Ids":["df24f0ad2258f9478bfa83140655c173", "df1d6efc4c6364db04e2bca603d70b92"], "IsPublic":false}' "http://localhost:8096/Playlists/1aa728d63cb5f14ea3c9f59aaf5cdc39"
```

- Even though this should be fine according to the documentation, I tried adding the fields `UserId` and `MediaType` like in the request to create the playlist as well as a `"Users":[{"UserId":"1741114c47c04c619998619b2ac0ebdf","CanEdit": true}]` with no success.

### Jellyfin Version

10.9.6

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
This is the log from the server

[01:20:40] [ERR] [15] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Playlists/a35d6b41c94ffe5bd510ac5913f9b963.
System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
   at Emby.Server.Implementations.Playlists.PlaylistManager.GetPlaylists(Guid userId)
   at Emby.Server.Implementations.Playlists.PlaylistManager.GetPlaylistForUser(Guid playlistId, Guid userId)
   at Jellyfin.Api.Controllers.PlaylistsController.UpdatePlaylist(Guid playlistId, UpdatePlaylistDto updatePlaylistRequest)
   at lambda_method1290(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmaximusix** [comment]
> Hi, it seems like your issue report has the following item(s) that need to be addressed:
> 
>     * You have not filled in the environment completely.
> 
> 
> This is an automated message, currently under testing. Please file an issue [here](https://github.com/jellyfin/jellyfin-triage-scripts/issues) if you encounter any problems.

Yeah it's a software issue, I stated the jellyfin server version, it's running on linux, everything else is irrelevant

**Comment by thomas-corte** [comment]
I'm seeing the same issue on Jellyfin 10.9.7 (Docker on Raspberry Pi).

A workaround is to first delete the playlist entirely (DELETE request to /Items/<playlistId>, HTTP response 204) and then recreate it with the new items. But the update call should of course be fixed.
