### ISSUE TITLE
[Issue]: Media identification blocks for 100 seconds on TMDb connection failure, indexing fails entirely

### ISSUE THREAD

**Issue by spaceman7777** [jellyfin/jellyfin#12103]
### Please describe your bug

Failure to connect to TheMovieDb for media identification causes other metadata providers to get blocked for 100 seconds in the "Identify" metadata searcher. It also causes new media identification/indexing to fail entirely. The Open Movie Database shows results after the 100 second timeout happens.

**Reproduction:**
1. Block access to TMDb via a VPN, or some other method (such as cloudflare warp)
2. Go to: {Some Library} -> {Three dot menu for a show} -> Identify -> {Enter search term-- it appears to cache, so you need a new one every time} -> Search
3. It will then get stuck for 100 seconds, and then search results from other metadata providers will be shown.

This feature shouldn't be dependent on the ability to connect to a specific metadata provider. (It'd be less frustrating if I had split-tunnelling by application available, but on a principles level, a larger system shouldn't block for 100 seconds because one domain was inaccessible.)

**Afterward, this error is in the logs:**
[2024-06-15 16:11:09.410 -04:00] [ERR] Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchMethodInternal[T](String method, String query, Int32 page, String language, Nullable`1 includeAdult, Int32 year, String dateFormat, String region, Int32 primaryReleaseYear, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchTvShowAsync(String query, String language, Int32 page, Boolean includeAdult, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.SearchSeriesAsync(String name, String language, Int32 year, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
   
 
**Steps attempted to fix this:**
Since other metadata providers work, I tried to disable TMDb integration, but TheMovieDb plugin can't be disabled from the Dashboard->Plugins->My Plugins menu, unlike other plugins, so that isn't an option.

### Reproduction Steps

1. In an environment where TMDb is inaccessible, due to a vpn or some other means, like the popular cloudflare warp vpn.
Running Arch Linux, with Jellyfin 10.9.6

2. Standard configuration. Repo steps are done via the localhost:8096 web portal.

3. Run
Reproduction:
1. Block access to TMDb via a VPN, or some other method (such as cloudflare)
2. Got to: {Some Library} -> {Three dot menu for a show} -> Identify -> {Enter search term-- it appears to cache, so you need a new one every time} -> Search
3. It will then get stuck for 100 seconds, and then search results from other metadata providers will be shown.

4.
This error gets thrown after 100 seconds of trying to connect. After which results are shown for other, accessible, metadata providers.

[2024-06-15 16:11:09.410 -04:00] [ERR] Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchMethodInternal[T](String method, String query, Int32 page, String language, Nullable`1 includeAdult, Int32 year, String dateFormat, String region, Int32 primaryReleaseYear, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchTvShowAsync(String query, String language, Int32 page, Boolean includeAdult, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.SearchSeriesAsync(String name, String language, Int32 year, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.9.3
- Virtualization: None
- Clients: Web
- Browser: Chrome
- FFmpeg Version: built from jellyfin-ffmpeg git directly
- Playback Method: Not playback related
- Hardware Acceleration:
- GPU Model: RTX 3090
- Plugins: Standard plugins
- Reverse Proxy: None
- Base URL: localhost:8096
- Networking: Ethernet
- Storage: NVMe's
```

### Jellyfin logs

```shell
[2024-06-15 16:11:09.410 -04:00] [ERR] Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchMethodInternal[T](String method, String query, Int32 page, String language, Nullable`1 includeAdult, Int32 year, String dateFormat, String region, Int32 primaryReleaseYear, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchTvShowAsync(String query, String language, Int32 page, Boolean includeAdult, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.SearchSeriesAsync(String name, String language, Int32 year, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spaceman7777** [comment]
As a temporary fix, I've turned off DNS over TLS and DNS over HTTPS from cloudflare warp. It seems to be some issue related to ipv6, thought I'm unsure of its exact nature.

For future reference to people dealing with this issue, I'm using `warp-cli mode proxy` instead of `warp-cli mode warp+dot` or `warp-cli mode warp+doh`. I then manually set my dns to point to 1.1.1.1 and 1.0.0.1 over a non HTTPS/TLS connection.

*Whatever the case*
The indexing and Identify search should probably not have a hard requirement of TMDb working to operate correctly. Current functionality is that Identify search works after the TMDb connection times out after 100 seconds, and the results from other metadata providers are then shown. Indexing fails entirely.

The metadata provider fallback should ideally be handled gracefully, with retrievals from functioning providers getting displayed and used.

**Comment by it5c0z1mG** [comment]
Same issue with tmdb, couldnt ping the api address, 100%packet loss

Mines now fixed -

Went on to my router and turned off ipv6

Went to jellyfin networking disabled ipv6 
connectivity

Wemt back to router and turned ipv6 back on, left jellyfin off

Restarted jellyfin

Ping api sucessfull
Can access plugin settings for tmdb again
And after 3 days my library scan finally completed in seconds after being stuck at 87%.

Dont know how, dont know why, im not a genius, but i hope this helps in some way.

**Comment by GustavoAFO** [comment]
I have the same issue.


> Same issue with tmdb, couldnt ping the api address, 100%packet loss
> 
> Mines now fixed -
> 
> Went on to my router and turned off ipv6
> 
> Went to jellyfin networking disabled ipv6 connectivity
> 
> Wemt back to router and turned ipv6 back on, left jellyfin off
> 
> Restarted jellyfin
> 
> Ping api sucessfull Can access plugin settings for tmdb again And after 3 days my library scan finally completed in seconds after being stuck at 87%.
> 
> Dont know how, dont know why, im not a genius, but i hope this helps in some way.

This worked for me
