### ISSUE TITLE
[Issue]: Blurhash for some logos fails while scanning libary

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin#12106]
### Please describe your bug

I get an error for some logos and after checking a few the images mentioned in the log, they all of them have something in common -> They are large raster images.

Some logos from the logs
- Sizes are 10601x1848, 9148x2250, 4319x481
- ".png" with webP inside

Maybe related to #3687 , but i found no mentioning of the image size

### Reproduction Steps

1. Add a large logo as webP or properly png as well. Attached a logo under screenshots
2. Run the library scan and follow the logs

### Jellyfin Version

Master branch

### Environment

```markdown
- Linux Kernel: 6.9.4
- Virtualization: no
- FFmpeg Version: 6.1 and 7.0
- Hardware Acceleration: VAAPI
```

### Jellyfin logs

```shell
jellyfin[1156349]: System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin[1156349]:    at BlurHashSharp.SkiaSharp.BlurHashEncoder.EncodeInternal(Int32 xComponent, Int32 yComponent, SKBitmap bitmap)
jellyfin[1156349]:    at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
jellyfin[1156349]:    at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
jellyfin[1156349]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
jellyfin[1156349]: [ERR] [11] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /var/lib/jellyfin/metadata/library/a2/a239e5692e6312a0e608a3296af054e5/logo.png
```

### Please attach any screenshots here

![logo](https://github.com/jellyfin/jellyfin/assets/112093608/7d392c5b-a187-4bd6-8739-74e72479485b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marrobHD** [comment]
I can observe the same behavior with the latest Jellyfin version on Debian.
Folder with issues: `/media/rip/series/I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability [imdbid-tt31624309]`

Jellyfin also doesn't show the subfolder `Staffel 1` in the metadata viewer. In general Jellyfin doesn't seem to fetch/save metadata for this element.

The poster.jpg files doesn't seem to exist.
```
Jun 19 16:07:52 jellyfin jellyfin[129064]: [16:07:52] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /var/lib/jellyfin/metadata/library/09/091c2be9ba5c01a42fa19d1691a91d8c/poster.jpg
Jun 19 16:07:52 jellyfin jellyfin[129064]: System.NullReferenceException: Object reference not set to an instance of an object.
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
Jun 19 16:07:52 jellyfin jellyfin[129064]: [16:07:52] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /var/lib/jellyfin/metadata/library/32/32c1ef8de5a50da7d7741f11dafc9a8c/poster.jpg
Jun 19 16:07:52 jellyfin jellyfin[129064]: System.NullReferenceException: Object reference not set to an instance of an object.
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
Jun 19 16:07:52 jellyfin jellyfin[129064]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

**Comment by felix920506** [comment]
this is more likely to be a duplicate of #3687 than its own issue so closing as such

**Comment by theguymadmax** [comment]
@enter-a-random-username Could you double-check to ensure those PNG files aren't actually SVG files? I've encountered issues where SVGs were mistakenly identified as PNGs due to missing/invaild context headers. I believe this might have been addressed in the master branch. If they are SVG files that would explain why the blurhash is failing.

**Comment by theguymadmax** [comment]
I can confirm this bug. Reopening the issue.

**Comment by theguymadmax** [comment]
I tested out the file you linked in Matrix: https://www.themoviedb.org/tv/105248-cyberpunk-edgerunners/images/logos

When I converted it to a WebP at the same resolution, it threw an exception. However, saving the same file as a PNG at the original resolution didn’t produce any errors

**Comment by ryannathans** [comment]
Also experiencing what appears to be the same issue, though the exception mentions a jpg poster

**Comment by theguymadmax** [comment]
@ryannathans  Could you attach the jpg image that produces this error in your logs?

**Comment by ryannathans** [comment]
I have zipped it to prevent any possible re-encoding during the upload

[folder.zip](https://github.com/user-attachments/files/19697961/folder.zip)

The accompanying exception:
```
[2025-04-11 00:00:00.340 +10:00] [ERR] [29] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/var/db/jellyfin/metadata/library/32/32ac4cf5e075f044fbaaab08c02062fd/folder.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, SKCodec codec, Int32 maxWidth, Int32 maxHeight)
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, Stream stream, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

**Comment by corndog2000** [comment]
Yup, still happening. Locks up all CPU cores and freezes Jellyfin.

**Comment by milesbenson** [comment]
Had some of those errors as well, all mentioned posters in the log had 0 byte. I got rid of them by just deleting them:

find /var/lib/jellyfin/metadata -type f -size 0 -name "*.jpg" -delete

No more errors afterwards, posters where created correctly after library scan (no refresh) and had correct size.

**Comment by ryannathans** [comment]
I have zero files of zero bytes returned by that command (without -delete)

**Comment by milesbenson** [comment]
Then maybe i had another issue, sorry.

**Comment by enter-a-random-username** [comment]
> I tested out the file you linked in Matrix: https://www.themoviedb.org/tv/105248-cyberpunk-edgerunners/images/logos
> 
> When I converted it to a WebP at the same resolution, it threw an exception. However, saving the same file as a PNG at the original resolution didn’t produce any errors

@theguymadmax would be a conversion to PNG before blurhash be a valid fix? It seems to be a SkiaSharp bug that would work as workaround based on your test.

### Workaround 1 (complicated)
- Use an external software to generate and write it. Other software can handle it.

### Workaround 2 (easy)
1. Its logos and it seems most clients won't use a blurhash for a logo, so I added a transparent pixel as logo. Logo Blurhash is not often used to my knowledge
2. Write `UPDATE "BaseItemImageInfos" SET Blurhash = 'e00000fQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQ' WHERE "Blurhash" REGEXP '^$'  AND "ImageType" = '4';`

**Image**
(Downloaded https://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png and added it as logo and wrote the same hash for everything. Not the scan takes seconds over 10 minutes +)

This allows me to find the hashes later and delete them, in case this gets resolved. So correct blurhash gets generated.

_Now scan is back to sends compared to 10 minutes before_

**Comment by enter-a-random-username** [comment]
This is more or less solved for me.

libvips for faster images (so far only a test) uses BlurhashNet and not Skia. That just works (build my jellyfin with fast libvips)
https://github.com/Shadowghost/jellyfin/tree/libvips
