### ISSUE TITLE
[Issue]: Restart from dashboard fails in 10.9.7 vs 10.9.2

### ISSUE THREAD

**Issue by matthewpipes** [jellyfin/jellyfin#12161]
### Please describe your bug

I upgraded to 10.9.2 from 10.8.13 and didn't notice any bugs, but upgrading to 10.9.6 i've noticed I can't reboot JF from the dashboard. It just never comes back up. I get these errors looking at systemctl

```
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Sending shutdown notifications
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] WS 100.64.0.1 closed
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] WS 100.64.0.1 closed
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping NAT discovery
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Running query planner optimizations in the database... This might take a while
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Live stream 2153b3a6a4fa82dbae09b4411bf874d8 consumer count is now 0
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Closing live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_2153b3a6a4fa82dbae09b4411bf874d8
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Closing LiveStream
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_2153b3a6a4fa82dbae09b4411bf874d8 closed successfully
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping directory watching for path /mnt/mat-nas/jellyfin/movies
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping directory watching for path /mnt/mat-nas/jellyfin/shows
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing CoreAppHost
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing MusicBrainzArtistProvider
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing MusicBrainzAlbumProvider
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing PluginManager
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Setting cache path: /var/cache/jellyfin
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loading assemblies
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Session Cleaner_3.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Subtitle Extract_4.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.Tvdb, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Jellyfin.Plugin.Tvdb.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Tvdb.Sdk.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Defined LAN exclusions: []
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Filtered interface addresses: ["127.0.0.1", "100.64.0.2"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Bind Addresses ["0.0.0.0"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Remote IP filter is Allowlist
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Filtered subnets: []
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [FTL] Error while starting server
Jul 13 16:46:41 jellyfin jellyfin[877]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Running query planner optimizations in the database... This might take a while
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing CoreAppHost
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing PluginManager
Jul 13 16:46:41 jellyfin systemd[1]: jellyfin.service: Deactivated successfully.
Jul 13 16:46:41 jellyfin systemd[1]: jellyfin.service: Consumed 3min 8.434s CPU time.
```

### Reproduction Steps

upgrade from 10.8.13, to 10.9.2 to 10.9.7 and try to restart using the dashboard

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: ubuntu 22.04.4 LTS
- Linux Kernel:6.5.0-41-generic
- Virtualization: KVM in with proxmox
- Clients: NA
- Browser: Firefox and Chrome
- FFmpeg Version:jellyfin-ffmpeg6
- Playback Method: NA
- Hardware Acceleration: NVENC
- GPU Model: Telsa P4
- Plugins: AudioDB, MusicBrainz, OMDb, OpenSubtitles, PlaybackReporting, Reports, Session Cleaner, Studio Images, Subtitles Extract, TMDB, TheTVDB
- Reverse Proxy: nginx reverse proxy
- Base URL: NA
- Networking: NA
- Storage: local
```

### Jellyfin logs

```shell
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Sending shutdown notifications
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] WS 100.64.0.1 closed
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] WS 100.64.0.1 closed
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping NAT discovery
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Running query planner optimizations in the database... This might take a while
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Live stream 2153b3a6a4fa82dbae09b4411bf874d8 consumer count is now 0
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Closing live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_2153b3a6a4fa82dbae09b4411bf874d8
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Closing LiveStream
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_2153b3a6a4fa82dbae09b4411bf874d8 closed successfully
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping directory watching for path /mnt/mat-nas/jellyfin/movies
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Stopping directory watching for path /mnt/mat-nas/jellyfin/shows
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing CoreAppHost
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing MusicBrainzArtistProvider
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing MusicBrainzAlbumProvider
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing PluginManager
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Setting cache path: /var/cache/jellyfin
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loading assemblies
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_14.0.0.0/SQLitePCL.pretty.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Session Cleaner_3.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Subtitle Extract_4.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Jellyfin.Plugin.Tvdb, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Jellyfin.Plugin.Tvdb.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Loaded assembly Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TheTVDB_13.0.0.0/Tvdb.Sdk.dll
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Defined LAN exclusions: []
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Filtered interface addresses: ["127.0.0.1", "100.64.0.2"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Bind Addresses ["0.0.0.0"]
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Remote IP filter is Allowlist
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Filtered subnets: []
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [FTL] Error while starting server
Jul 13 16:46:41 jellyfin jellyfin[877]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Jul 13 16:46:41 jellyfin jellyfin[877]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Running query planner optimizations in the database... This might take a while
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing CoreAppHost
Jul 13 16:46:41 jellyfin jellyfin[877]: [16:46:41] [INF] Disposing PluginManager
Jul 13 16:46:41 jellyfin systemd[1]: jellyfin.service: Deactivated successfully.
Jul 13 16:46:41 jellyfin systemd[1]: jellyfin.service: Consumed 3min 8.434s CPU time.
```

### FFmpeg logs

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
> [h264_nvenc @ 0x5f8488cd1c40] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
[h264_nvenc @ 0x5f8488cd1c40] The minimum required Nvidia driver for nvenc is 520.56.06 or newer

You need a newer nvidia driver version.

**Comment by crobibero** [comment]
Sorry, just saw you posted two issues in one.

Please fully restart after upgrading (not from dashboard)

**Comment by jaiovi** [comment]
Same issue https://forum.jellyfin.org/t-i-restarted-my-server-from-web-button-but-failed-to-restart?pid=29458#pid29458

**Comment by matthewpipes** [comment]
Ok I've resolved the issue. Like @jaiovi commented this issue was discussed in the jellyfin forum and the issue stems from plugins. I stoped jellyfin and deleted all the plugins under /var/lib/jellyfin/plugins/ and then it restarted from the GUI without issue. I reinstalled the most recent plugin versions and it still works. I noticed that there were still old versions of multiple plugins still there and this may be the cause, who knows. I will mark this as resolved

**Comment by davidmurdoch** [comment]
> > but the latest version of jellyfin no longer allows for customizing the ffmpeg path
> 
> It does, just not in the UI. You can use the `--ffmpeg` argument.

I couldn't figure out where the service was started (Debian 11 install) and also wanted to get the new ffmpeg working anyway so I managed to install the updated nvidia drivers and things seem to work fine now (except I can't patch these new driver's using https://github.com/keylase/nvidia-patch yet). I do still need to figure out how/where the service is started so I can customize the ffmpeg path again, as I used to round-robin the GPUs (I have 2 installed) using it.
