### ISSUE TITLE
[Issue]: Scan Failing when adding certain new folders

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin/jellyfin#12179]
### Please describe your bug

So i have been adding some new libraries with new content. It has been fine so far but i started to get scans failing after added a few folders. It seems similar to the error i got in this #9354 issue but instead of series it says season. Obviously i didn't think to go into more detail with my answer when i figured it out last time and so far i haven't seen any duplicate folders. Really i just want to know what the error means as i think it's a me problem and not a bug. 

### Reproduction Steps

1. Create a new library with a new folder
2. Wait for the scan to finish
3. It fails and gives this error

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Windows 10
- Virtualization: No
- Clients:Jellyfin Media Player
- Browser:Firefox
- FFmpeg Version:Bundled with Jellyfin Windows installer
- Playback Method:N/A
- Hardware Acceleration:N/A
- GPU Model:Nvidia GTX 960m
- Plugins:N/A
- Reverse Proxy:Local Only
- Base URL:N/A
- Networking:Local 1Gbs
- Storage:Seagate 8TB Hard Drives
```

### Jellyfin logs

```shell
[2024-06-26 16:47:31.812 +01:00] [INF] [113] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\HDHomeRun\Recordings"
[2024-06-26 16:47:31.812 +01:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Cartoons"
[2024-06-26 16:47:31.812 +01:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\International Movies"
[2024-06-26 16:47:31.813 +01:00] [INF] [71] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Short Films"
[2024-06-26 16:47:31.813 +01:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Movies"
[2024-06-26 16:47:31.813 +01:00] [INF] [89] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "H:\TVShows(#-B)"
[2024-06-26 16:47:31.813 +01:00] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "I:\TVShows(C-E)"
[2024-06-26 16:47:31.818 +01:00] [INF] [113] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "J:\TVShows(F-K)"
[2024-06-26 16:47:31.821 +01:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "K:\TVShows(L-N)"
[2024-06-26 16:47:31.824 +01:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "L:\TVShows(O-R)"
[2024-06-26 16:47:31.824 +01:00] [ERR] [136] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.InvalidOperationException: Cannot update refresh progress of item 'Season' (9f6907f70b917bb1bc3c3602a614cce0) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-06-26 16:47:31.825 +01:00] [INF] [71] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "M:\TVShows(S)"
[2024-06-26 16:47:31.827 +01:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "N:\TVShows(T-Z)"
[2024-06-26 16:47:31.828 +01:00] [INF] [89] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "O:\Anime"
[2024-06-26 16:47:31.830 +01:00] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "P:\Anime"
[2024-06-26 16:47:31.832 +01:00] [INF] [113] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "Q:\Asian Drama"
[2024-06-26 16:47:31.833 +01:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "S:\Animemovies"
[2024-06-26 16:47:31.835 +01:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "V:\Anime"
[2024-06-26 16:47:31.843 +01:00] [INF] [136] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 9 minute(s) and 24 seconds
[2024-06-26 16:47:31.846 +01:00] [INF] [71] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "V:\Cartoons"
[2024-06-26 16:47:31.848 +01:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "V:\Movies"
[2024-06-26 16:47:31.850 +01:00] [INF] [89] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "V:\Music\AlexMusic\Artists"
[2024-06-26 16:47:31.860 +01:00] [INF] [136] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This issue was resolved in 10.9.

**Comment by Gaffers2277** [comment]
> This issue was resolved in 10.9.

Okay thank you i will update
