### ISSUE TITLE
[Issue]: Trickplay causes AMD APU crash/reset when hardware decoding set (it used to work tho having trouble find when it stopped)

### ISSUE THREAD

**Issue by cooljimy84** [jellyfin/jellyfin#12186]
### Please describe your bug

The last few days i've come to find my host at silly high load, uptime says its 62.00 or more. Looking at the logs it happens when trickplay makes it's images.

### Reproduction Steps

Run trick play with hardware decoding enabled.

### Jellyfin Version

10.9.7

### Environment

```markdown
- OS: Ubuntu lxc container
- Linux Kernel: 6.8.8-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.8-2 (2024-06-24T09:00Z) x86_64 x86_64 x86_64 GNU/Linux
- Virtualization: proxmox lxc
- Clients: 
- Browser:
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  with vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.1.1 - kisak-mesa PPA for AMD Radeon Graphics
- Playback Method: None
- Hardware Acceleration: VAAPI with 5700G
- GPU Model: APU
- Plugins: n/a
- Reverse Proxy: n/a
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Jellyfin logs

```shell
[2024-06-28 08:34:19.648 +01:00] [INF] Creating trickplay files at 320 width, for "/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E01 - Pallet Party Panic.mkv" [ID: e29076ca-fcb3-edf0-7f8b-38e8f82820fa]
[2024-06-28 08:34:19.648 +01:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vaapi=va@dr -init_hw_device vulkan=vk@dr -filter_hw_device vk -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E01 - Pallet Party Panic.mkv\" -noautoscale -an -sn -vf \"fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=240:format=nv12,hwdownload,format=nv12\" -threads 3 -c:v mjpeg -qscale:v 12 -f image2 \"/var/cache/jellyfin/temp/39cd7b0243544383aa71d2691e34196d/%08d.jpg\""
[2024-06-28 08:34:23.370 +01:00] [INF] Attempting to cancel Scheduled Task "Generate Trickplay Images"
[2024-06-28 08:34:29.356 +01:00] [INF] Saving system configuration
[2024-06-28 08:34:29.359 +01:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-06-28 08:34:29.360 +01:00] [INF] Stopping NAT discovery
[2024-06-28 08:34:32.549 +01:00] [ERR] Error creating trickplay images.
System.ArgumentException: Can't create trickplay from 0 images.
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
[2024-06-28 08:34:32.549 +01:00] [INF] "Generate Trickplay Images" Cancelled after 0 minute(s) and 15 seconds
[2024-06-28 08:34:52.554 +01:00] [INF] Creating trickplay files at 320 width, for "/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E01 - Pallet Party Panic.mkv" [ID: e29076ca-fcb3-edf0-7f8b-38e8f82820fa]
[2024-06-28 08:34:52.556 +01:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 3 -noautorotate -i file:\"/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E01 - Pallet Party Panic.mkv\" -an -sn -vf \"fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p\" -threads 3 -c:v mjpeg -qscale:v 12 -f image2 \"/var/cache/jellyfin/temp/e84db0a159b64d64beaf3596debaa9ba/%08d.jpg\""
[2024-06-28 08:35:18.881 +01:00] [INF] Finished creation of trickplay files for "/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E01 - Pallet Party Panic.mkv"
[2024-06-28 08:35:18.890 +01:00] [INF] Creating trickplay files at 320 width, for "/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E33 - Viva Las Lapras.mkv" [ID: 2bc967da-5ce6-3121-2d89-ec5e716ac300]
[2024-06-28 08:35:18.891 +01:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 3 -noautorotate -i file:\"/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E33 - Viva Las Lapras.mkv\" -an -sn -vf \"fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p\" -threads 3 -c:v mjpeg -qscale:v 12 -f image2 \"/var/cache/jellyfin/temp/d02e89310748458398e506be604fc904/%08d.jpg\""
[2024-06-28 08:35:45.092 +01:00] [INF] Finished creation of trickplay files for "/mnt/TV Shows/Pokemon (1997)/Season 2/Pokémon - S02E33 - Viva Las Lapras.mkv"
[2024-06-28 08:35:48.243 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.247 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.249 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.262 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.265 +01:00] [WRN] Video width 200 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.267 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.269 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.272 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.274 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.276 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.278 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.280 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:49.648 +01:00] [INF] Creating trickplay files at 320 width, for "/mnt/TV Shows/South Park (1997)/Season 22/South Park - S22E01 - Dead Kids.mp4" [ID: c45b40f0-bcfa-b75a-77f2-30640accac47]
[2024-06-28 08:35:49.648 +01:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 3 -noautorotate -i file:\"/mnt/TV Shows/South Park (1997)/Season 22/South Park - S22E01 - Dead Kids.mp4\" -an -sn -vf \"fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p\" -threads 3 -c:v mjpeg -qscale:v 12 -f image2 \"/var/cache/jellyfin/temp/e01f544508fb4bffa15b78964b1893ad/%08d.jpg\""
[2024-06-28 08:36:09.649 +01:00] [INF] Trickplay process unresponsive.
[2024-06-28 08:36:09.649 +01:00] [INF] Stopping trickplay extraction.
[2024-06-28 08:36:10.649 +01:00] [INF] Killing ffmpeg process
[2024-06-28 08:36:10.650 +01:00] [ERR] ffmpeg image extraction failed for "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 3 -noautorotate -i file:\"/mnt/TV Shows/South Park (1997)/Season 22/South Park - S22E01 - Dead Kids.mp4\" -an -sn -vf \"fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p\" -threads 3 -c:v mjpeg -qscale:v 12 -f image2 \"/var/cache/jellyfin/temp/e01f544508fb4bffa15b78964b1893ad/%08d.jpg\""
[2024-06-28 08:36:10.650 +01:00] [ERR] Error creating trickplay images.
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vaapi=va@dr -init_hw_device vulkan=vk@dr -filter_hw_device vk -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags +allow_profile_mismatch -noautorotate -i file:"/mnt/TV Shows/South Park (1997)/Season 22/South Park - S22E01 - Dead Kids.mp4" -noautoscale -an -sn -vf "fps=0.05000000074505806,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12" -threads 2 -c:v mjpeg_vaapi -qscale:v 0 -f image2 "/var/cache/jellyfin/temp/19d90931d2c24ef1877f2a1b6cd217ae/%08d.jpg"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractVideoImagesOnIntervalInternal(String inputArg, String filterParam, String vidEncoder, Nullable`1 outputThreads, Nullable`1 qualityScale, Nullable`1 priority, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)                                                   
[2024-06-28 08:35:48.262 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.265 +01:00] [WRN] Video width 200 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.267 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.269 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.272 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.274 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.276 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.278 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
[2024-06-28 08:35:48.280 +01:00] [WRN] Video width 192 is smaller than trickplay setting 320, using video width for thumbnails
```

### Please attach any browser or client logs here

[Fri Jun 28 08:34:19 2024] gmc_v9_0_process_interrupt: 41 callbacks suppressed
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: [mmhub0] no-retry page fault (src_id:0 ring:40 vmid:5 pasid:32770, for process ffmpeg pid 129101 thread ffmpeg:cs0 pid 129103)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x0000800102d0e000 from IH client 0x12 (VMC)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00243851
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 Faulty UTCL2 client ID: VCN (0x1c)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 MORE_FAULTS: 0x1
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 WALKER_ERROR: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x5
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 RW: 0x1
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: [mmhub0] no-retry page fault (src_id:0 ring:40 vmid:5 pasid:32770, for process ffmpeg pid 129101 thread ffmpeg:cs0 pid 129103)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x0000800102d0e000 from IH client 0x12 (VMC)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 Faulty UTCL2 client ID: MP1 (0x0)
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 WALKER_ERROR: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
[Fri Jun 28 08:34:19 2024] amdgpu 0000:0c:00.0: amdgpu: 	 RW: 0x0
[Fri Jun 28 08:34:29 2024] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring vcn_dec timeout, signaled seq=89922, emitted seq=89924
[Fri Jun 28 08:34:29 2024] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process ffmpeg pid 129101 thread ffmpeg:cs0 pid 129103
[Fri Jun 28 08:34:29 2024] amdgpu 0000:0c:00.0: amdgpu: GPU reset begin!
[Fri Jun 28 08:34:29 2024] [drm] Register(0) [mmUVD_POWER_STATUS] failed to reach value 0x00000001 != 0x00000002n
[Fri Jun 28 08:34:30 2024] [drm] Register(0) [mmUVD_RBC_RB_RPTR] failed to reach value 0x00000160 != 0x00000140n
[Fri Jun 28 08:34:30 2024] [drm] Register(0) [mmUVD_POWER_STATUS] failed to reach value 0x00000001 != 0x00000002n
[Fri Jun 28 08:34:30 2024] amdgpu 0000:0c:00.0: amdgpu: MODE2 reset
[Fri Jun 28 08:34:30 2024] amdgpu 0000:0c:00.0: amdgpu: GPU reset succeeded, trying to resume
[Fri Jun 28 08:34:30 2024] [drm] PCIE GART of 1024M enabled.
[Fri Jun 28 08:34:30 2024] [drm] PTB located at 0x000000F4BFC00000
[Fri Jun 28 08:34:30 2024] [drm] PSP is resuming...
[Fri Jun 28 08:34:31 2024] [drm] reserve 0x400000 from 0xf4bf800000 for PSP TMR
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: RAS: optional ras ta ucode is not available
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: RAP: optional rap ta ucode is not available
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: SMU is resuming...
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: SMU is resumed successfully!
[Fri Jun 28 08:34:31 2024] [drm] DMUB hardware initialized: version=0x01010028
[Fri Jun 28 08:34:31 2024] [drm] kiq ring mec 2 pipe 1 q 0
[Fri Jun 28 08:34:31 2024] [drm] VCN decode and encode initialized successfully(under DPG Mode).
[Fri Jun 28 08:34:31 2024] [drm] JPEG decode initialized successfully.
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring gfx uses VM inv eng 0 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring gfx_low uses VM inv eng 1 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring gfx_high uses VM inv eng 4 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 5 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 6 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 7 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 8 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 9 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 10 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 11 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 12 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring kiq_0.2.1.0 uses VM inv eng 13 on hub 0
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring sdma0 uses VM inv eng 0 on hub 8
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring vcn_dec uses VM inv eng 1 on hub 8
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring vcn_enc0 uses VM inv eng 4 on hub 8
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring vcn_enc1 uses VM inv eng 5 on hub 8
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: ring jpeg_dec uses VM inv eng 6 on hub 8
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: recover vram bo from shadow start
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: recover vram bo from shadow done
[Fri Jun 28 08:34:31 2024] amdgpu 0000:0c:00.0: amdgpu: GPU reset(5) succeeded!
[Fri Jun 28 08:34:31 2024] [drm] Skip scheduling IBs!
[Fri Jun 28 08:34:31 2024] [drm] Skip scheduling IBs!
[Fri Jun 28 08:34:31 2024] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cooljimy84** [comment]
just restored to 10.9.3 and it does the error, i'm sure either .2 or .3 i left it running for days and it completed fine. I suspect it might be a kernel thing (as i've change from 6.6 to 6.8 (tho can't remember when)
Gonna reboot the host into an old kernel and restore JF to last nights backup.

**Comment by cooljimy84** [comment]
Proxmox host on
6.5.13-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-5 (2024-04-05T11:03Z) x86_64 GNU/Linux
&
6.0.19-edge #1 SMP PREEMPT_DYNAMIC PVE Edge 6.0.19-1 (2023-01-13) x86_64 x86_64 x86_64 GNU/Linux
same error

Container reports the following in VAINFO
```root@Jellyfin108:~# vainfo
error: can't connect to X server!
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.0.8 - kisak-mesa PPA for AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.48, 6.0.19-edge)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc```

**Comment by cooljimy84** [comment]
So found the route cause, it was a handful of mkv and mp4 files that played fine, but would cause trickplay to crash and then cause the GPU to reset, this was then causing the host to reset the GPU.
i've removed the files i could see in the log files, and add new diffrent ones and it completes fine now.
Not sure if you still want this open ? (as a bad file shouldn't kill the server and jellyfin can hardware transcode it fine)

Looks like someone else had this as well [https://forum.jellyfin.org/t-solved-trickplay-generation-failing-trickplay-process-unresponsive](url)

**Comment by nyanmisaka** [comment]
Based on my years of experience fighting with AMDGPU on Linux, its hardware design and driver tolerance are very low, and the kernel driver is always changing and causing regression. These mean that once an unrecoverable transcoding issue occurs, you will likely encounter a hard reset or system freeze, rather than bail out gracefully like the driver from other vendors.

The ffmpeg command shown in the jellyfin logs does not have any errors, it just uses the vaapi hardware to decode and scale the video and then encodes the thumbnails using the software mjpeg encoder.

My conclusion is that it is not worth it for end users to waste time debugging on AMDGPU unless you want to learn bisect and help them fix the driver. If you want a decent experience, just plug in an intel or nvidia discrete graphics card and call it a day.

I don't have access to my APU build at the moment, I'll take a look at this when I get a chance.

**Comment by Short3D** [comment]
Ran into a similar issue recently after updating my truenas box (crash in ring comp), this solved the crash on a my 2400g when transcoding 4k content.

`amdgpu.ppfeaturemask=0xFFFF7FFF` in your grub options.

https://gitlab.freedesktop.org/drm/amd/-/issues/3400

**Comment by cooljimy84** [comment]
Kool, i'll update my grub and see if that helps (tho i put the files through handbrake and they seem to not lock up my box now)
