### ISSUE TITLE
Error when refreshing library - The data is NULL at ordinal

### ISSUE THREAD

**Issue by majkinetor** [jellyfin/jellyfin#12199]
### Please describe your bug

Library stopped refreshing after upgrading to v10.9.6 (error continues on 10.9.7).

It also shows 'Failed' in scheduled tasks

![image](https://github.com/jellyfin/jellyfin/assets/85767/3d3236e6-ed49-453c-af11-dd5dbcfdf1a2)

### Reproduction Steps

1. Use "refresh metadata" on the library
1. Expect too see new music albums but it doesn't happen

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients: Jellyfin Web 10.9.7
- Browser: Firefox
- FFmpeg Version: Comes with the server
- Playback Method:
- Hardware Acceleration: No
- GPU Model: Integrated
- Plugins: Listed bellow
- Reverse Proxy: No
- Base URL:  http://media:8096
- Networking:
- Storage:
```

### Jellyfin logs

```shell
2024-06-30 15:46:09.870 +02:00] [ERR] [26] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.InvalidOperationException: The data is NULL at ordinal 1. This method can't be called on NULL values. Check using IsDBNull before calling.
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetNull[T](Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetBlob(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetBlob(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetCachedBlob(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetStream(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetStream(Int32 ordinal)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(SqliteDataReader reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Boolean hasServiceName, Boolean queryHasStartDate, Boolean hasTrailerTypes, Boolean hasArtistFields, Boolean hasSeriesFields, Boolean skipDeserialization)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren()
   at MediaBrowser.Controller.Entities.Folder.LoadChildren()
   at MediaBrowser.Controller.Entities.Folder.get_Children()
   at MediaBrowser.Controller.Entities.Folder.GetActualChildrenDictionary()
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

Plugin logs

```
2024-06-30 15:45:52.826 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.CoverArtArchive, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Cover Art Archive_8.0.0.0\Jellyfin.Plugin.CoverArtArchive.dll"
[2024-06-30 15:45:52.829 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MetaBrainz.Common.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "C:\ProgramData\Jellyfin\Server\plugins\Cover Art Archive_8.0.0.0\MetaBrainz.Common.Json.dll"
[2024-06-30 15:45:52.831 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MetaBrainz.MusicBrainz.CoverArt, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "C:\ProgramData\Jellyfin\Server\plugins\Cover Art Archive_8.0.0.0\MetaBrainz.MusicBrainz.CoverArt.dll"
[2024-06-30 15:45:52.833 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Fanart_11.0.0.0\Jellyfin.Plugin.Fanart.dll"
[2024-06-30 15:45:52.835 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "3.0.0.0" of "IMVDb" 
[2024-06-30 15:45:52.839 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles_20.0.0.0\Jellyfin.Plugin.OpenSubtitles.dll"
[2024-06-30 15:45:52.843 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Playback Reporting_14.0.0.0\Jellyfin.Plugin.PlaybackReporting.dll"
[2024-06-30 15:45:52.846 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Playback Reporting_14.0.0.0\SQLitePCL.pretty.dll"
[2024-06-30 15:45:52.869 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\ClosedXML.dll"
[2024-06-30 15:45:52.952 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\DocumentFormat.OpenXml.dll"
[2024-06-30 15:45:52.957 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\ExcelNumberFormat.dll"
[2024-06-30 15:45:52.960 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\Jellyfin.Plugin.Reports.dll"
[2024-06-30 15:45:52.966 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\SixLabors.Fonts.dll"
[2024-06-30 15:45:52.969 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from "C:\ProgramData\Jellyfin\Server\plugins\Reports_17.0.0.0\System.IO.Packaging.dll"
[2024-06-30 15:45:52.973 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Subtitle Extract_4.0.0.0\Jellyfin.Plugin.SubtitleExtract.dll"
[2024-06-30 15:45:52.978 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_13.0.0.0\Jellyfin.Plugin.Tvdb.dll"
[2024-06-30 15:45:52.985 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Tvdb.Sdk, Version=4.7.9.1, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_13.0.0.0\Tvdb.Sdk.dll"
[2024-06-30 15:45:52.989 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Vgmdb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\VGMdb_4.0.0.0\Jellyfin.Plugin.Vgmdb.dll"
```

**Comment by felix920506** [comment]
This is an option configurable per user account. 

Click the profile on the top right, go to "home" and the option will be in there.

**Comment by felix920506** [comment]
Sorry closed wrong issue

**Comment by solidsnake1298** [comment]
Can you try uninstalling the Playback Reporting plugin, restarting, and try your scan again?

**Comment by mplough** [comment]
I'm seeing this issue on a stock install of 10.9.7 on macOS with no Playback Reporting plugin installed.  Just speculating, but I'm wondering if there's something going on with a failed or incomplete database migration from a previous version?

**Comment by gnattu** [comment]
The only change that could cause this is a failed migration that has being reported multiple times. Try https://github.com/jellyfin/jellyfin/issues/11994#issuecomment-2153332136 to fix your db.

**Comment by mplough** [comment]
> The only change that could cause this is a failed migration that has being reported multiple times. Try [#11994 (comment)](https://github.com/jellyfin/jellyfin/issues/11994#issuecomment-2153332136) to fix your db.

Thanks @gnattu, that was exactly it.

I needed to edit `migrations.xml` as explained in https://github.com/jellyfin/jellyfin/issues/11994#issuecomment-2153332136 and also set `IsStartupWizardCompleted` to `true` in `system.xml` as explained in https://github.com/jellyfin/jellyfin/issues/11994#issuecomment-2171753391.

After making those edits and restarting, the `Scan Media Library` task ran with no issues.

**Comment by majkinetor** [comment]
Thanks
