### ISSUE TITLE
[Issue]: Jellyfin crashing upon startup

### ISSUE THREAD

**Issue by Gilgamesh0028** [jellyfin/jellyfin#12254]
### Please describe your bug

Crashes upon launch. 

### Reproduction Steps

rebooted machine (previously had it working fine pre-reboot), and where upon logon jellyfin is set to auto-start. 
When I received the popup saying it failed to start, i checked the log; saw the xml error, and decided to make an issue.

### Jellyfin Version

10.9.2

### Environment

```markdown
- OS: Windows 10, 22H2
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: Local (via browser)
- Browser: Firefox
- FFmpeg Version: latest bundled (I don't recall, and lack the ability to check via jellyfin cli / GUI
- Playback Method: N/A
- Hardware Acceleration: enabled
- GPU Model: NVIDIA RTX 2080 VENTUS OC
- Plugins: anilist metadata fetcher
- Reverse Proxy: N/A
- Base URL: 127.0.0.1:8096
- Networking: 2.5Gb Ethernet
- Storage:1TB SSD (jellyfin server dir) 4TB HDD (media dir)
```

### Jellyfin logs

```shell
[2024-07-10 21:45:47.211 -06:00] [INF] [1] Main: Jellyfin version: "10.9.2"
[2024-07-10 21:45:47.227 -06:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\Users\ADMIN\Documents\Jellyfin\Server\log]"]
[2024-07-10 21:45:47.229 -06:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\Users\ADMIN\Documents\Jellyfin\Server"]
[2024-07-10 21:45:47.231 -06:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.19045"
[2024-07-10 21:45:47.232 -06:00] [INF] [1] Main: Architecture: X64
[2024-07-10 21:45:47.234 -06:00] [INF] [1] Main: 64-Bit Process: True
[2024-07-10 21:45:47.235 -06:00] [INF] [1] Main: User Interactive: True
[2024-07-10 21:45:47.236 -06:00] [INF] [1] Main: Processor count: 16
[2024-07-10 21:45:47.237 -06:00] [INF] [1] Main: Program data path: "C:\Users\ADMIN\Documents\Jellyfin\Server"
[2024-07-10 21:45:47.238 -06:00] [INF] [1] Main: Log directory path: "C:\Users\ADMIN\Documents\Jellyfin\Server\log"
[2024-07-10 21:45:47.239 -06:00] [INF] [1] Main: Config directory path: "C:\Users\ADMIN\Documents\Jellyfin\Server\config"
[2024-07-10 21:45:47.240 -06:00] [INF] [1] Main: Cache path: "C:\Users\ADMIN\Documents\Jellyfin\Server\cache"
[2024-07-10 21:45:47.241 -06:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-07-10 21:45:47.242 -06:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-07-10 21:45:47.269 -06:00] [FTL] [1] Main: Unhandled Exception
System.InvalidOperationException: There is an error in XML document (1, 1).
 ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gilgamesh0028** [comment]
As of writing this, i have no way of knowing which xml file jellyfin is attempting to load, nor which ones passed / failed. 
If someone has a script, or something (not *super* knowledgeable about xml and how jellyfin works, my area of expertise is in 3DCAD and Networking (vlans, switches, routing, etc)...)

**Comment by Bond-009** [comment]
It's failing on either `migrations.xml` or `system.xml` in the Jellyfin config dir, I think that would be `%APPDATA%/jellyfin/config` on Windows, but don't quote me on that.

**Comment by Gilgamesh0028** [comment]
ah.... yep, it's definitely `migrations.xml`. 
![image](https://github.com/jellyfin/jellyfin/assets/98428877/51e2cfb8-cc16-4321-a880-0fb6f089bc1e)

`system.xml` is all fine:
![image](https://github.com/jellyfin/jellyfin/assets/98428877/f068242a-420b-4d71-ad94-83291a3422b6)

**Comment by Gilgamesh0028** [comment]
okay, so, I upgraded to 10.9.7 (noticed that the latest release was a bit ahead of me), and after upgrading to latest, I removed `migrations.xml` from the folder, attempted to start jellyfin and the file was auto-regenerated (no longer showing `NUL` across the board)... and now it's throwing a different error.. yay.... :\ 
```
[2024-07-11 12:21:05.559 -06:00] [FTL] [1] Main: Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ActivityLog'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Emby.Server.Implementations.Data.SqliteExtensions.Query(SqliteConnection sqliteConnection, String commandText)+MoveNext()
   at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)```

**Comment by Bond-009** [comment]
It's trying to do old migrations, try setting `IsStartupWizardCompleted` to false in system.xml, start the server so it generates migrations.xml, shut it down and set it back to false.

**Comment by Gilgamesh0028** [comment]
absolutely incredible, it works!

**Comment by Furbach** [comment]
same problem, fixed in the same way. thanks

**Comment by Gilgamesh0028** [comment]
I couldn't find this issue on the issue list already, so I did a write up for future searchers who have this issue.
Glad to see it's already helped someone else! \o/

**Comment by vallovic** [comment]
Same problem happened to me just today, glad I found this issue!

The only difference is that I'm using Linux (Native), so the configurations directory is `/etc/jellyfin`.

**Comment by yellowsink** [comment]
> It's trying to do old migrations, try setting `IsStartupWizardCompleted` to false in system.xml, start the server so it generates migrations.xml, shut it down and set it back to false.

tried this before, but it wiped my entire config? was I doing it wrong?

**Comment by mgtroyas** [comment]
Same problem here today, this worked flawlessly. Thank you very much!

**Comment by bigyank** [comment]
> It's trying to do old migrations, try setting `IsStartupWizardCompleted` to false in system.xml, start the server so it generates migrations.xml, shut it down and set it back to false.

you are a hero! thanks!

**Comment by luckrnx09** [comment]
> It's trying to do old migrations, try setting `IsStartupWizardCompleted` to false in system.xml, start the server so it generates migrations.xml, shut it down and set it back to false.

Same problem today here, it works for me now! thanks~ ❤️

**Comment by debug-it** [comment]
I had the same problem, this fixed it. Thank you.

> It's trying to do old migrations, try setting `IsStartupWizardCompleted` to false in system.xml, start the server so it generates migrations.xml, shut it down and set it back to false.

**Comment by MrCrafter123** [comment]
Same thing happened after a reboot cause windows crashed, and the fix worked. Thanks!

**Comment by GAMPAGNA** [comment]
I have the same problem and I still can't solve it. I am using casaOs to do the installation. Everything was going well until at some point Jellyfin just wouldn't start. The error is :"SQLite Error 1: 'no such table: ActivityLog'."

**Comment by dorianbrown** [comment]
I've got the same issue, since today. It seems to be crashing when doing the migration.

This seems to be the problematic part of the logs:
```
jellyfin        | [23:21:47] [INF] [9] InternalCodeMigration: Perform migration 20250420070000_MigrateActivityLogDb
jellyfin        | [23:21:47] [WRN] [9] Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb: Migrating the activity database may take a while, do not stop Jellyfin.
jellyfin        | [23:21:48] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check StartupCheck with status Degraded completed after 0.0035ms with message 'Server is still starting up.'
jellyfin        | [23:21:48] [FTL] [9] InternalCodeMigration: Error: SQLite Error 1: 'no such table: ActivityLog'.
jellyfin        | [23:21:48] [ERR] [9] InternalCodeMigration: Migration 20250420070000_MigrateActivityLogDb failed
jellyfin        | Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ActivityLog'.
jellyfin        |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin        |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
jellyfin        |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
...
```

EDIT: This might be related to this new issue: https://github.com/jellyfin/jellyfin/issues/15027
