### ISSUE TITLE
[Issue]: Metadata fetch timeout - IPv6 connectivity broken

### ISSUE THREAD

**Issue by Johnny-Ich** [jellyfin/jellyfin#12255]
### Please describe your bug

When I try to fetch metadata, _TheMovieDb_ and _The Open Movie Database_ always times out.

also see -> https://github.com/jellyfin/jellyfin/issues/9438

### Reproduction Steps

1. Run Jellyfin in docker, enable IPv6 for the host and the container.
2. Confirm IPv6 connectivity by `ping6 google.de` and ping6 `jellyfin.server`
3. Run a metadata search
4. wait
5. collect logs

### Jellyfin Version

10.9.0

### if other:

Version: 10.9.7

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: 5.15.0-113-generic
- Virtualization: docker
- Clients:  Browser
- Browser: Firefox
- FFmpeg Version: don't know. that one inside the container. ffmpeg not relevant here
- Playback Method: Direct Stream
- Hardware Acceleration: none
- GPU Model: none
- Plugins: AniDB, AudioDB, LDAP-Auth, MusicBrainz, OMDb, Playback Reporting, Studio IMages, TMDb
- Reverse Proxy: none
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-10 21:27:15.284 +00:00] [ERR] [92] MediaBrowser.Providers.Manager.ProviderManager: Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.EnsureClientConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.FindByExternalIdAsync(String externalId, FindExternalSource source, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-07-10 21:28:01.290 +00:00] [ERR] [66] MediaBrowser.Providers.Manager.ProviderManager: Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.EnsureClientConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.FindByExternalIdAsync(String externalId, FindExternalSource source, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-07-10 21:28:12.716 +00:00] [ERR] [66] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".
[2024-07-10 21:28:12.717 +00:00] [WRN] [66] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Packages?PackageType=UserInstalled" to "95.115.127.250" in 0:01:40.0167596 with Status Code 500
[2024-07-10 21:28:42.856 +00:00] [ERR] [32] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".
[2024-07-10 21:28:42.856 +00:00] [WRN] [32] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Packages?PackageType=UserInstalled" to "95.115.127.250" in 0:01:40.0053185 with Status Code 500
[2024-07-10 21:28:55.340 +00:00] [ERR] [66] MediaBrowser.Providers.Manager.ProviderManager: Provider "The Open Movie Database" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetSearchResultsInternal(ItemLookupInfo searchInfo, Boolean isSearch, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-07-10 21:28:55.343 +00:00] [WRN] [66] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Items/RemoteSearch/Movie" to "95.115.127.250" in 0:03:20.0942604 with Status Code 200
[2024-07-10 21:29:41.295 +00:00] [ERR] [114] MediaBrowser.Providers.Manager.ProviderManager: Provider "The Open Movie Database" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetSearchResultsInternal(ItemLookupInfo searchInfo, Boolean isSearch, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-07-10 21:29:41.297 +00:00] [WRN] [114] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Items/RemoteSearch/Movie" to "95.115.127.250" in 0:03:20.0199121 with Status Code 200
[2024-07-10 21:31:10.344 +00:00] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".
[2024-07-10 21:31:10.344 +00:00] [WRN] [11] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Packages?PackageType=UserInstalled" to "95.115.127.250" in 0:01:40.0039808 with Status Code 500
[2024-07-10 21:31:41.936 +00:00] [ERR] [18] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".
[2024-07-10 21:31:41.936 +00:00] [WRN] [18] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://stream.gcraft.eu:8920/Packages?PackageType=UserInstalled" to "95.115.127.250" in 0:01:40.0006492 with Status Code 500
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
cc @Shadowghost

**Comment by EnzoLORMONT** [comment]
Can you check this issue : #11968 ?

**Comment by Shadowghost** [comment]
This will need fixing in the plugins I think

**Comment by mharj** [comment]
Looks like this works ok if running on Windows with IPv6 enabled (at least on versions 10.8.11 and 10.9.9), but some reason on docker container (in real Linux) it's not working and causing many issues even on scanning files. Docker image gets nicely list of ipv6 addresses for TheMovieDb api and curl does correcty redirect when tried on endpoint, so network and dns looks to working ok inside of container.

**Comment by Arcturuss** [comment]
> Looks like this works ok if running on Windows with IPv6 enabled

it really does not. got same error on Windows with ipv6 enabled and Jellyfin 10.9.11 and 10.10.0. 
if you can not reach TMDB over ipv6 (in my case, the ping fails), then Jellyfin can not either.

**Comment by Titaniumtown** [comment]
I can reproduce this bug even with ipv6 is disabled in jellyfin. Had to disable ipv6 on linux system-wide to get jellyfin to work.

Related: https://github.com/jellyfin/jellyfin/issues/8518

**Comment by Shadowghost** [comment]
I think the proper fix would be to implement happy eyeballs for the tmdb plugin's http client. Since we use a library (nowadays maintained by the jellyfin team too), we should make it possible to use the httpclient which already implements it and is provided by Jellyfin.

**Comment by Titaniumtown** [comment]
Is there a way to disable ipv6 for jellyfin specifically? The settings in jellyfin does nothing. Can it be disabled per-process on linux?

**Comment by Titaniumtown** [comment]
This seems to be a result of a broken IPv6 system config. For example, my fix: https://git.gardling.com/titaniumtown/server-config/commit/71d2bb0cb334023ccf2a531b9e7b2ed0652a07fa

After this, connectivity works.

**Comment by wolfy1339** [comment]
Not stale. Issue should be moved to the appropriate repository and fixed there

**Comment by LeGmask** [comment]
not stale, I can reproduce

**Comment by Kaz0na** [comment]
Can confirm this issues still persists. Running Jellyfin in a Rootless Podman Container on CachyOS. With IPv6 enabled on the OS level Jellyfin fails to retrieve metadata due to a timeout. If I disable IPv6 completely on the OS level metadata retrieval works succesfully.

As an aside this same issue _also_ occurs when just installing jellyfin natively instead of running it in a container.

**Comment by tonibgd** [comment]
Can confirm the issue as well. Running rootless podman container on Arch.
Only works If I disable IPv6 on the OS level.

**Comment by tonibgd** [comment]
I figured out a workaround for podman:

- Create a IPv4 only podman network: 
```sh
podman network create jellyfin-network
```
- Update your `podman run` command by adding `--network jellyfin-network`
- Start your podman container
- Inspect the new podman network, you should see your container on it
```
podman network inspect jellyfin-network
```

Verify you are using IPv4 by checking your public IP:
- Enter you container (assuming your container name is `jellyfin`:
```sh
podman exec -it jellyfin bash
```
- Run a `curl` command to check your public IP 
```
curl ifconfig.me
```

You should now see your public IPv4 IP from within the container where before you would see your public IPv6 IP.
Running the `curl` command outside the container should still return your public IPv6 IP.

**Comment by Kaz0na** [comment]
> I figured out a workaround for podman:
> 
> * Create a IPv4 only podman network:
> 
> podman network create jellyfin-network
> * Update you `podman run` command by adding `--network jellyfin-network`
> * Start your podman container
> * Inspect the new podman network, you should see your container on it
> 
> ```
> podman network inspect jellyfin-network
> ```
> 
> Verify you are using IPv4 by checking your public IP:
> 
> * Enter you container (assuming your container name is `jellyfin`:
> 
> podman exec -it jellyfin bash
> * Run a `curl` command to check your public IP
> 
> ```
> curl ifconfig.me
> ```
> 
> You should now see your public IPv4 IP from within the container where before you would see your public IPv6 IP. Running the `curl` command outside the container should still return your public IPv6 IP.

Just want to say that this worked like a charm!

**Comment by Gr3q** [comment]
Another person with this issue, most likely my problem is temporary ISP routing issues to TMDB. https://github.com/jellyfin/jellyfin/issues/15989

I will add my comments from my own issue - which I probably should close - that I think would need to be changed to make this problem less impactful as it is now

* Jellyfin shouldn't just fail - aka hang - library scan if TMDB calls time out especially if there are alternative providers enabled
* Even though I disabled TMDB for every library Image Search still didn't work (may be unrelated but I saw TMDB called, need to double check)
* While I have IPv6 disruptions, IPv4 routing works fine but Jellyfin (or dotnet) didn't succeed connecting to TMDB. Maybe curls [approach](https://everything.curl.dev/transfers/conn/names.html) could be adopted? - "ibcurl resolves the hostname to the set of addresses it resolves to. Typically this means asking for both IPv4 and IPv6 addresses and there may be a whole set of those returned to libcurl. That set of addresses is then tried until one works, or it returns failure.". As far as I know HTTPClient does this, maybe it doesn't work with timeouts (the server just not responding)?
* I don't think the timeout for connecting to metadata providers should be 100 seconds. I think it would be a lot shorter, but I won't give you a concrete number because I don't know what would be optimal.

**Comment by Shadowghost** [comment]
> Even though I disabled TMDB for every library Image Search still didn't work (may be unrelated but I saw TMDB called, need to double check)

Image proviers are configured separately to metadata providers in the library screen

> IPv6 -> IPv4 fallback is currently not implemented in TMDbLib

Should be handled with https://github.com/jellyfin/TMDbLib/pull/551 but somebody would need to test it

**Comment by Gr3q** [comment]
> Image proviers are configured separately to metadata providers in the library screen

I know, I disabled TMDB for that too. Images will load, after the timeout (so 100secs by default) event if TMDB is disabled for it. A bug in Jellyfin most likely (tested this by adjusting the timeout for the TMDB provider)

> Should be handled with https://github.com/jellyfin/TMDbLib/pull/551 but somebody would need to test it

On that branch are you using `HappyEyeballsCallback` file for anything at all? How should I use that branch in jellyfin? 
1. I created a nuget package from it locally
2. Made jellyfin use it
3. Fixed all build errors 

and it doesn't seem to make a difference. my [branch](https://github.com/Gr3q/jellyfin/tree/tmdblib-happyeyes)

**Comment by Shadowghost** [comment]
You can just remove the dependency altogether and add a direct package reference to your local TMDbLib Source code to `MediaBrowser.Providers.csproj`:
```
    <ProjectReference Include="..\..\TMDbLib\TMDbLib\TMDbLib.csproj" />
```

And seems like my last rebase lost the actual usage of the HappyEyeballs callback. Should be fixed now.

**Comment by Gr3q** [comment]
I can confirm that your branch works. Scanning is a bit slow to start off but there are enough issues with the current release around scanning so I'm going to ignore that.

My crude logic I added in jellyfin on the other hand...it just crashes jellyfin on some image downloads

**Comment by afeedhshaji** [comment]
I ran into the same error and had to disable ipv6 to get it to work.

**Comment by GAumala** [comment]
I was having this issue today and just restarted my docker container to fix it.

**Comment by KiwifruitDev** [comment]
> I ran into the same error and had to disable ipv6 to get it to work.

This also fixed the issue for me but I can no longer do this because I'm running into https://github.com/pterodactyl/panel/issues/5488 on the same machine, I'm at a catch 22 where Jellyfin works when IPv6 is disabled but Pterodactyl doesn't and if I enable IPv6 then Pterodactyl works but Jellyfin doesn't.

**Comment by KennethHoff** [comment]
Same failure here, Jellyfin 10.11.11 as a native NixOS service, not Docker, with TMDbLib 3.0.0, the version jellyfin pins.

Every metadata scan drops individual items with:

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.EnsureClientConfigAsync() (line 637)
   at MediaBrowser.Controller.LibraryTaskScheduler.LimitedConcurrencyLibraryScheduler.ProcessItem(...) (line 189)
```

The trace points at TMDbLib's own HTTP client, not Jellyfin's, which has Happy Eyeballs. `TmdbClientManager` constructs `new TMDbClient(apiKey)` at TmdbClientManager.cs:41 and never sets `Timeout`. TMDbLib's `RestClient` builds `new HttpClient(httpMessageHandler)` at RestClient.cs:43, with no IPv4 fallback. That matches the `upstream` label. The fix belongs in jellyfin/TMDbLib: Happy Eyeballs, or a way to inject a handler that has it.

For Linux users hitting this, one workaround only half works. Setting the OS sysctl `net.ipv6.conf.all/default.disable_ipv6 = 1`, which NixOS exposes as `networking.enableIPv6 = false`, does not stop it. On this host the network manager re-adds IPv6 addresses and resets the per-interface `disable_ipv6` after boot, so IPv6 stays up and requests still eat the full 100s. What did work: the `ipv6.disable=1` kernel boot parameter. IPv6 is then truly gone, connects fail instantly, and IPv4 fallback succeeds. A client-side fix should handle "IPv6 enabled but blackholed", not just "IPv6 disabled".

**Comment by Jademalo** [comment]
Same issue with NixOS, though `networking.enableIPv6 = false;` did actually fix it for me.
