### ISSUE TITLE
[Issue]: Music metadata is completely messed up, metadata from files not parsed

### ISSUE THREAD

**Issue by hikkamorii** [jellyfin/jellyfin#12269]
### Please describe your bug

Some time ago I noticed that new music in my library won't be indexed correctly, metadata from the files won't get parsed, new metadata (from plugins) doesn't seem to be picked up.

On clean jellyfin setup, scan completes fine and metadata is correct.

Re-scanning library did not work. Creating library from scratch helped, but it's not a solution since I want to keep my playlists and loved tracks. 

I have no idea how to debug this issue, and there are no logs that indicate anything bad happening. 

### Reproduction Steps

1. Add new files to the library
2. Open Dashboard -> Libraries
3. Refresh library metadata (does not matter which option)
5. Wait for scan to finish (?)
6. New media added to library, without any metadata.

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: openSUSE Leap 15.5
- Linux Kernel: 5.14.21
- Virtualization: Docker
- Clients: Browser, Finamp
- Browser: Floorp 11.14 (Based on Firefox)
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: n/a
- Reverse Proxy: nginx, none
- Base URL: n/a
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-14 01:17:41.664 +00:00] [INF] [33] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-07-14 01:17:41.668 +00:00] [INF] [33] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-07-14 01:17:41.671 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniDB, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniDB_9.0.0.0/Jellyfin.Plugin.AniDB.dll"
[2024-07-14 01:17:41.673 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniList_9.0.0.0/Jellyfin.Plugin.AniList.dll"
[2024-07-14 01:17:41.674 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.CoverArtArchive, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Cover Art Archive_8.0.0.0/Jellyfin.Plugin.CoverArtArchive.dll"
[2024-07-14 01:17:41.675 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MetaBrainz.Common.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "/config/plugins/Cover Art Archive_8.0.0.0/MetaBrainz.Common.Json.dll"
[2024-07-14 01:17:41.676 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MetaBrainz.MusicBrainz.CoverArt, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "/config/plugins/Cover Art Archive_8.0.0.0/MetaBrainz.MusicBrainz.CoverArt.dll"
[2024-07-14 01:17:41.677 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Discogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Discogs_1.0.0.0/Jellyfin.Plugin.Discogs.dll"
[2024-07-14 01:17:41.679 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Model, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Model.dll"
[2024-07-14 01:17:41.680 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Playback, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll"
[2024-07-14 01:17:41.684 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.dll"
[2024-07-14 01:17:41.684 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Rssdp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_2.0.0.0/Rssdp.dll"
[2024-07-14 01:17:41.686 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Kitsu, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Kitsu_5.0.0.0/Jellyfin.Plugin.Kitsu.dll"
[2024-07-14 01:17:41.688 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Vgmdb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/VGMdb_4.0.0.0/Jellyfin.Plugin.Vgmdb.dll"
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.21.0.2"]
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-07-14 01:17:41.692 +00:00] [INF] [33] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-07-14 01:17:45.155 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniDB" "9.0.0.0"
[2024-07-14 01:17:45.157 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "9.0.0.0"
[2024-07-14 01:17:45.158 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Cover Art Archive" "8.0.0.0"
[2024-07-14 01:17:45.160 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Discogs" "1.0.0.0"
[2024-07-14 01:17:45.161 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "DLNA" "2.0.0.0"
[2024-07-14 01:17:45.162 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Kitsu" "5.0.0.0"
[2024-07-14 01:17:45.163 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "VGMdb" "4.0.0.0"
[2024-07-14 01:17:45.163 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.7.0"
[2024-07-14 01:17:45.164 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.7.0"
[2024-07-14 01:17:45.164 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.7.0"
[2024-07-14 01:17:45.165 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.7.0"
[2024-07-14 01:17:45.166 +00:00] [INF] [33] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.7.0"
[2024-07-14 01:17:45.238 +00:00] [INF] [33] Main: Kestrel is listening on "0.0.0.0"
[2024-07-14 01:17:45.425 +00:00] [INF] [33] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1"
[2024-07-14 01:17:45.445 +00:00] [INF] [33] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "172.21.0.2"
[2024-07-14 01:17:45.839 +00:00] [WRN] [33] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/wwwroot". Static files may be unavailable.
[2024-07-14 01:17:45.856 +00:00] [INF] [33] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-07-14 01:17:45.866 +00:00] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-07-14 03:00:00.000 +00:00, which is 01:42:14.1338176 from now.
[2024-07-14 01:17:45.867 +00:00] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-07-14 02:00:00.000 +00:00, which is 00:42:14.1328457 from now.
[2024-07-14 01:17:45.870 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/mnt/ssd/shares/swiftmedia"
[2024-07-14 01:17:45.888 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-07-14 01:17:45.907 +00:00] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/mnt/arc/shares/media/Video/Music Videos"
[2024-07-14 01:17:45.909 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-07-14 01:17:45.932 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-07-14 01:17:45.963 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-07-14 01:17:46.120 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-07-14 01:17:46.485 +00:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-07-14 01:17:46.485 +00:00] [INF] [33] Emby.Server.Implementations.ApplicationHost: ServerId: "2232df5d93444f8ea4445fb7789dcbcd"
[2024-07-14 01:17:46.485 +00:00] [INF] [33] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-07-14 01:17:46.485 +00:00] [INF] [33] Main: Startup complete 0:00:04.8218874
[2024-07-14 01:17:48.869 +00:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-07-14 01:17:51.438 +00:00] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 2 seconds
[2024-07-14 01:20:06.657 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/misogiswen - THE PSYCHO BLAST Vol.2 - 08 Skeleton cruise.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:06.763 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/Dustvoxx - THE PSYCHO BLAST Vol.2 - 04 XTC Stab.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:06.899 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/Laur - THE PSYCHO BLAST Vol.2 - 10 Verzweiflung.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:06.982 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/moro - THE PSYCHO BLAST Vol.2 - 06 Apoptosis.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.053 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/Xystran - THE PSYCHO BLAST Vol.2 - 09 Conflict Memory.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.163 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/Filthy - THE PSYCHO BLAST Vol.2 - 12 DEATH BREAKFAST.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.225 +00:00] [INF] [11] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/RedOgre - THE PSYCHO BLAST Vol.2 - 07 Curse Of The Empire.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.313 +00:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/pianoid - THE PSYCHO BLAST Vol.2 - 02 WAREZ GANGSTA 1994.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.453 +00:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/t+pazolite - THE PSYCHO BLAST Vol.2 - 03 Jakeleg.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.519 +00:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/Kobaryo - THE PSYCHO BLAST Vol.2 - 01 PLASTIC BUNNY.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.589 +00:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/DJ Myosuke - THE PSYCHO BLAST Vol.2 - 11 eden.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:20:07.654 +00:00] [INF] [11] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/arc/shares/media/Audio/iTunes/iTunes Media/Music/Various Artists - THE PSYCHO BLAST Vol.2/H.U.T GiGAR - THE PSYCHO BLAST Vol.2 - 05 GRAND CHALLENGE.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-07-14 01:21:44.335 +00:00] [INF] [18] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-07-14 01:21:44.336 +00:00] [INF] [18] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-07-14 01:21:44.336 +00:00] [INF] [23] Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
```

### FFmpeg logs

```shell
n/a
```

### Please attach any screenshots here

![Screenshot 2024-07-14 at 04-21-00 Apple Music](https://github.com/user-attachments/assets/c924f518-3d0f-446f-9aa6-af5765064e40)
![Screenshot 2024-07-14 at 04-29-58 Jellyfin](https://github.com/user-attachments/assets/5f9128e3-3743-41d9-bec7-504f10db30a5)
![Screenshot_20240714_042812](https://github.com/user-attachments/assets/72a0592d-9c31-4a8f-8994-c33db567c6eb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ptasznikarium** [comment]
I just deleted physically some of my Music and after rescanning Music library the entries for deleted artist and all albums are still there

**Comment by hikkamorii** [comment]
Update: Creating library from scratch could be a solution, but you'd have to manually set "likes" and add to playlists tracks that had broken metadata (which luckily wasn't much in my case) . Otherwise, data about likes, play count and playlists seems to be able to get moved to other "new" library, because Jellyfin handles user data based on files, and not some abstract ID relative to specific library. I could be wrong, so I'd appreciate some feedback before closing the issue.

**Comment by frusanov** [comment]
> Update: Creating library from scratch could be a solution

This one didn't help me. After recreation non of the artists was recognized. I try it on 10.9.8 and 10.9.9.

After I went back to 10.8.13 everything start working as expected

**Comment by hikkamorii** [comment]
@frusanov This may be a different issue to mine, since I don't think downgrading helped me.

**Comment by DomiStyle** [comment]
I have been having exactly the same issue since the 10.9 release as well. The only way to fix the metadata after a regular library scan is to rescan with "Search for missing metadata" right after.

Not sure if related but there's many of these exceptions when scanning my music library:

```
[21:21:31] [ERR] [24] MediaBrowser.Providers.Manager.ProviderManager: ArtistProvider failed in GetImageInfos for type MusicArtist at /config/metadata/artists/Powerworld
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.String,Jellyfin.Plugin.Fanart.Dtos.Album]. Path: $.albums | LineNumber: 4 | BytePositionInLine: 15.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.ArtistProvider.AddImages(List`1 list, String path, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.ArtistProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)

[21:21:39] [ERR] [15] MediaBrowser.Providers.Manager.ProviderManager: ArtistProvider failed in GetImageInfos for type MusicArtist at /config/metadata/artists/Neonfly
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.String,Jellyfin.Plugin.Fanart.Dtos.Album]. Path: $.albums | LineNumber: 52 | BytePositionInLine: 15.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.ArtistProvider.AddImages(List`1 list, String path, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.ArtistProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Comment by XiaoKe89** [comment]
I am also experiencing this issue, was hoping 10.10 might fix it but still nothing. Even doing "Search For Missing Metadata" after doing a rescan, like DomiStyle mentioned, didn't do it for me. It's like it doesn't want to read the files built in metadata. I even attempted to remove one of the affected files and re-add it freshly but that did not help it would add the filename as the title and that's it it wont even pick up the cover art

**Comment by gnattu** [comment]
What I have in my mind is that your library or the db in your library could contains something that throw an error during the scan so the actual scanner never run because the scanning is actually cancelled due to the error thrown before running the audio prober. But we cannot help without a complete log, from scanning to the scan finishes.

**Comment by XiaoKe89** [comment]
So I was messing with stuff and I went in and was going to manually enter in some of the info and noticed that the album was locked. So I tried unlocking it and scan again and it popped up. The weird part is I've had the artist locked for a while (Because I don't want it to change the data I had manually entered in) and I've added in new tracks from that artist before without issue so it seems like in one of the updates something changed that made it so that if an Artist is locked it wont even scan the files local metadata, which if that's intended behavior fair enough I'll just remember that but it looks like for me anyways the issue was that if an item is locked it wont search for ANY metadata not even the local metadata. I tried adding in a new song from an artist I haven't used before and it popped in with all the local metadata Not sure if this is what is going on with the others but might be good to check if the Artists are locked as it seems now Jellyfin wont scan the local metadata of new files when added if the artist is locked

**Comment by DomiStyle** [comment]
@gnattu I attached two debug logs for 2 separate music library scans.

Log 1 adds a single song from a new artist: Yonaka - Seize the Power.
It correctly set everything but the album cover, which shows the artist cover instead.

Log 2 adds a single song, also from a new artist: Black Gryph0n - Insane.
It failed to set pretty much anything, no link between artist and song, the album title is the folder name, the album art is missing completely. The artist got a link to MusicBrainz but has no albums.

This is what it looks like after the normal scans:
![image](https://github.com/user-attachments/assets/d81b695e-401b-41be-bdb8-dd870ad1863c)

This is what it looks like after rescanning for missing metadata (which takes forever):
![image](https://github.com/user-attachments/assets/3c73958f-6493-4159-8ed8-f7bde57c1afd)


[log1.zip](https://github.com/user-attachments/files/17533234/log1.zip)
[log2.zip](https://github.com/user-attachments/files/17533235/log2.zip)

**Comment by flleeppyy** [comment]
I'm also experiencing the same annoying problem, since I've mass updated all of the music in my library to fix metadata issues (Using mp3tag to convert all artists listed/separated by semicolons and what not, into their own artist tags so jellyfin reads each artist tag individually and lists them correctly)) and I have to go through each song in jellyfin and do it myself in the metadata editor, for it to update, which is not ideal. What's the "Refresh Metadata" tool for anyway if it doesn't serve its purpose?

**Comment by gnattu** [comment]
@flleeppyy https://github.com/jellyfin/jellyfin/pull/12385

10.10 and 10.9 has completely different music metadata handler and this issue does not really reflect what 10.10 is doing.

**Comment by flleeppyy** [comment]
> @flleeppyy https://github.com/jellyfin/jellyfin/pull/12385
> 
> 10.10 and 10.9 has completely different music metadata handler and this issue does not really reflect what 10.10 is doing.

Ah. Well, is there an issues thread for that? cause i can't find one for my specific issue...

**Comment by gnattu** [comment]
Did the PR inked above solve your specific issue?

**Comment by flleeppyy** [comment]
> Did the PR inked above solve your specific issue?

Nope. I've had countless music that had semicolon separators and jellyfin didn't see it. I've mass edited all of my music to have multiple artist tags instead since jellyfin likes that, BUT IT ONLY WORKS IF JELLYFIN HAS NEVER SEEN THE SONG BEFORE. Refresh Metadata does not actually refresh the metadata. It's a useless button. I could change the artist to something completely different, refresh the metadata, and jellyfin just doesn't update it.

**Comment by gnattu** [comment]
You have to enable that option in library settings, did you enable that?

After enabling that you need to perform replace all metadata scan, did you perform that?

**Comment by flleeppyy** [comment]
> You have to enable that option in library settings, did you enable that?
> 
> After enabling that you need to perform replace all metadata scan, did you perform that?

I assumed replace all means it fetches metadata from selected services and replaces whatever is on the file... Which i don't want.

**Comment by voronind-com** [comment]
I fixed some metadata in music files like artist names from lowercase to correct, like from abba to ABBA. Can't force JF to pick up new values. ffprobe tells the correct values, no lowercase abba in any field. I tried all forced rescans, recreating the library, restarting JF, nuking the metadata/artists dir and no luck.

Edit: I just switched to Navidrome and it is so much better.
