### ISSUE TITLE
Corrupted jellyfin.db causes an empty migrations.xml to be created on startup

### ISSUE THREAD

**Issue by JustinLex** [jellyfin/jellyfin#12289]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

An unrelated issue seems to have corrupted my jellyfin.db, requiring me to restore my database from backup. This corruption then manifested itself as my Jellyfin container crashing on startup with the error "System.InvalidOperationException: There is an error in XML document (0, 0)." 

I saw in issue #12254 that this error can be caused by a corrupted migrations.xml file, and  `od -t x1 migrations.xml` showed that an empty migrations.xml is being created on every startup, not even any null bytes. I tried deleting migrations.xml, but a new, empty migrations.xml is created every time the container starts.

### Reproduction steps

Run Jellyfin 10.9.7 in a docker container with a corrupted jellyfin.db with 0-bytes shm and wal files, and that causes "Error: disk I/O error" in sqlite3. The env JELLYFIN_PublishedServerUrl is set to "::0". The docker image hash is `docker.io/jellyfin/jellyfin:10.9.7@sha256:76930362d2c266e8f0b2f51f1c6b039a5207525d0e138a1cdbec870c66c34b0f`.

### What is the current _bug_ behavior?

jellyfin crashes on startup with "Unhandled Exception System.InvalidOperationException: There is an error in XML document (0, 0)." when the database is corrupted

### What is the expected _correct_ behavior?

Jellyfin does not try to run migrations, and properly reports that the database is corrupted.

### Jellyfin Server version

10.9.7

### Specify the build version

unknown

### Environment

```markdown
- OS: NixOS 24.05
- Linux Kernel: 6.6.40
- Virtualization: Docker+Kubernetes
- Hardware Acceleration: none
- Plugins: Open Subtitles
- Reverse Proxy: Envoy / Project Contour
- Base URL: none
- Networking: Kubernetes, dual-stack
- Storage: CephFS, mounted to /data/media, /config, and /config/transcodes
- Jellyfin container yaml: https://codeberg.org/jlh/h5b/src/branch/main/argo/custom_applications/media/deploy-jellyfin.yaml
```

### Jellyfin logs

```shell
[13:40:44] [INF] [1] Main: Jellyfin version: 10.9.7
[13:40:44] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_SERVICE_HOST, 2600:70ff:b04f:beef:1::7450]", "[JELLYFIN_PORT, tcp://[2600:70ff:b04f:beef:1::7450]:80]", "[JELLYFIN_PORT_80_TCP, tcp://[2600:70ff:b04f:beef:1::7450]:80]", "[JELLYFIN_SERVICE_PORT, 80]", "[JELLYFIN_PORT_80_TCP_PROTO, tcp]", "[JELLYFIN_SERVICE_PORT_HTTP, 80]", "[JELLYFIN_PORT_80_TCP_PORT, 80]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_PublishedServerUrl, ::0]", "[JELLYFIN_PORT_80_TCP_ADDR, 2600:70ff:b04f:beef:1::7450]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]"]
[13:40:44] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[13:40:44] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[13:40:44] [INF] [1] Main: Architecture: X64
[13:40:44] [INF] [1] Main: 64-Bit Process: True
[13:40:44] [INF] [1] Main: User Interactive: True
[13:40:44] [INF] [1] Main: Processor count: 48
[13:40:44] [INF] [1] Main: Program data path: /config
[13:40:44] [INF] [1] Main: Log directory path: /config/log
[13:40:44] [INF] [1] Main: Config directory path: /config/config
[13:40:44] [INF] [1] Main: Cache path: /cache
[13:40:44] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[13:40:44] [INF] [1] Main: Application directory: /jellyfin/
[13:40:44] [FTL] [1] Main: Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

### Additional information

Looking forward to Postgres support coming to Jellyfin, I've been quite frustrated that this is my first corrupted database after 3 months of running Jellyfin in this configuration. It was caused by my config disk quota being full, which also caused jellyfin to segfault. Postgres gives a lot more flexibility, reliability, and automation over sqlite for advanced users.

```
[2024-07-14 00:30:00.200 +00:00] [ERR] [12] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Server.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
```
```
Jul 14 04:48:36 latios kernel: traps: jellyfin[3076920] general protection fault ip:7fbd1ac7150f sp:7fffd1129420 error:0 in libc.so.6[7fbd1ac71000+155000]
Jul 14 04:48:46 latios systemd-coredump[1512057]: Process 3076920 (jellyfin) of user 0 dumped core.
```

**Comment by JohannesKast** [comment]
I had exactly the same issue. Disk quota exceeded which lead to a corrupted database. Now the service is no longer starting and shows the same error as above. I can test when there is a fix for it.

**Comment by mghoffmann** [comment]
I'm also having the same problem. The server crashed during a full library rescan after I added 40GB of files, and now it won't start. I would be happy to test a quick fix because my alternative is to delete the db file and make all my accounts and settings again 😵🥴 The toddler needs his shows!

`journalctl --unit=jellyfin.service --no-pager | tail -n500` shows a stacktrace:

```
Jul 17 12:33:16 harry-potter jellyfin[16678]: [12:33:16] [FTL] Unhandled Exception
Jul 17 12:33:16 harry-potter jellyfin[16678]: System.InvalidOperationException: There is an error in XML document (0, 0).
Jul 17 12:33:16 harry-potter jellyfin[16678]:  ---> System.Xml.XmlException: Root element is missing.
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlReader.MoveToContent()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    --- End of inner exception stack trace ---
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Program.<Main>(String[] args)
Jul 17 12:33:16 harry-potter jellyfin[16678]: Unhandled exception. System.InvalidOperationException: There is an error in XML document (0, 0).
Jul 17 12:33:16 harry-potter jellyfin[16678]:  ---> System.Xml.XmlException: Root element is missing.
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.XmlReader.MoveToContent()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    --- End of inner exception stack trace ---
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Jul 17 12:33:16 harry-potter jellyfin[16678]:    at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by felix920506** [comment]
Confirmed by multiple reports.

**Comment by rsmartapps** [comment]
In my case my service is running with the official docker image.
> Stop container
> copy migrations.xml content from root config path and pasted in the empty migrations.xml file
> Start jellyfin container

After those steps jellyfin is running as expected

**Comment by GiggleSquid** [comment]
I can confirm the exact same has happened to me. Ran out of disk space during a rescan and boom.

jellyfin 10.9.7
NixOS
qemu vm

```Aug 25 22:04:27 squidjelly jellyfin[1479]: [22:04:27] [INF] [1] Main: Jellyfin version: 10.9.7
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:27] [INF] [1] Main: Environment Variables: ["[DOTNET_ROOT, /nix/store/5aaxwv8nv61d9flfqgn9wzvf06mb6>
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Arguments: ["/nix/store/rwa2nh5fkhpa5g0fm6b7z1cgqbbd41hn-jellyfin-10.9.7/lib/je>
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Operating system: NixOS 24.11 (Vicuna)
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Architecture: X64
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: 64-Bit Process: True
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: User Interactive: True
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Processor count: 12
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Program data path: /var/lib/jellyfin
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Log directory path: /var/lib/jellyfin/log
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Config directory path: /var/lib/jellyfin/config
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Cache path: /var/cache/jellyfin
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Web resources path: /nix/store/r1lbq2mgkbpmksf2in5c0cnqmydp9dg0-jellyfin-web-10>
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [INF] [1] Main: Application directory: /nix/store/rwa2nh5fkhpa5g0fm6b7z1cgqbbd41hn-jellyfin-10.>
Aug 25 22:04:28 squidjelly jellyfin[1479]: [22:04:28] [FTL] [1] Main: Unhandled Exception
Aug 25 22:04:28 squidjelly jellyfin[1479]: System.InvalidOperationException: There is an error in XML document (0, 0).
Aug 25 22:04:28 squidjelly jellyfin[1479]:  ---> System.Xml.XmlException: Root element is missing.
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlReader.MoveToContent()
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_Migration>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isCo>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    --- End of inner exception stack trace ---
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDes>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream st>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFac>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Program.StartApp(StartupOptions options) in /build/source/Jellyfin.Server/Program.cs>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Program.<Main>(String[] args)
Aug 25 22:04:28 squidjelly jellyfin[1479]: Unhandled exception. System.InvalidOperationException: There is an error in XML document (0, 0).
Aug 25 22:04:28 squidjelly jellyfin[1479]:  ---> System.Xml.XmlException: Root element is missing.
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.XmlReader.MoveToContent()
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_Migration>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isCo>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    --- End of inner exception stack trace ---
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDes>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream st>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFac>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Program.StartApp(StartupOptions options) in /build/source/Jellyfin.Server/Program.cs>
Aug 25 22:04:28 squidjelly jellyfin[1479]:    at Jellyfin.Server.Program.<Main>(String[] args)
Aug 25 22:04:28 squidjelly systemd[1]: jellyfin.service: Main process exited, code=dumped, status=6/ABRT```

**Comment by JPVenson** [comment]
I know it does suck, but if you ran out of space, there isn't much Jellyfin can do. If you corrupt your db/settings because of that, its gone and JF really has no way of restoring that by itself. @GiggleSquid

**Comment by mghoffmann** [comment]
Adding a disk usage check to database and XML file writes to avoid running out of space is 100% possible.

**Comment by GiggleSquid** [comment]
@JPVenson Yeah, fair enough. It just feels a bit catastrophic for something the a relatively common occurrence.

I guess it comes down to who jellyfin believes should take responsibility, the program or the user.
Either is valid, and like mghoffmann said, there *could* be checks. But I'm not sure how viable that is in reality.

I think as long as it is documented behavior, it's *fine*

**Comment by gnattu** [comment]
It would be insane to check disk usage for every write operation. This is an easy way to kill IO performance.

**Comment by mghoffmann** [comment]
It doesn't need to be for every write. It could be done for every batch of writes, with enough tolerance to never be the cause of a full disk. I e. if there's only 1MB or less left then safely abort instead of putting crucial files in an invalid state.

Also, changes to small XML files and other small file operations not outdourced to a DBMS should be done by writing in-memory buffers and then writing the buffers to files, so an exception is thrown by that file write for a full disk instead of being thrown by a byte/word/line write. I'm not yet familiar enough with Jellyfin code to do this myself but it's absolutely possible and realistic in .NET.

**Comment by JPVenson** [comment]
there are tons of tools out there that will always do a better job at this. System management is not a JF responsibility, next thing we should check the CPU temps to not overheat? 
The whole topic is far more complex if you factor in network shares and docker from JF point of view.

**Comment by mghoffmann** [comment]
I wouldn't think it's out of scope to at least keep Jellyfin from lobotomizing itself with a failed attempt at changing its own XML files. That seems to be what's happening here.

The exception in the logs that have been posted is caused by invalid XML, but it's not a third party that's made the XML invalid, it's Jellyfin. The fix might be as simple as handling an IOException a little differently during an XML write.

I would be happy to look into this if someone can point me to where in the code those XML changes are being made. Or I can try to hunt for it this weekend maybe.

**Comment by GiggleSquid** [comment]
From a users perspective I have to agree with:

> I wouldn't think it's out of scope to at least keep Jellyfin from lobotomizing itself with a failed attempt at changing its own XML files. That seems to be what's happening here.

I get JF shouldn't be handling system management, but why does it "lobotomize" itself when the system isn't managed perfectly

**Comment by mghoffmann** [comment]
Plus I doubt a full disk is the only type of exceptional circumstance that can cause this broken state. Improved handling of exceptions during XML writes could harden Jellyfin against all sorts of issues that System.IO already checks and throws exceptions for (assuming it's built on .NET, I don't even know).

**Comment by mghoffmann** [comment]
> why does it "lobotomize" itself when the system isn't managed perfectly

Right, that's the question to ask. My hunch from years of .NET experience is that an exception is being thrown during an IO operation and the method attempting it doesn't gracefully clean up the failed attempt.

**Comment by mattish91** [comment]
Oh man, i have been looking for this a while, i just couldn't figure it out and then i found this tread and it started instantly after deleting my migrations.xml that was empty.

**Comment by 24fpsDaVinci** [comment]
using docker jellyfin with external config folder, i deleted migrations.xml but docker still starts in a bootloop

**Comment by lead0r** [comment]
> using docker jellyfin with external config folder, i deleted migrations.xml but docker still starts in a bootloop

Same. I understand that once the drive is full, the database is corrupted, but how can I start fresh without having to install everything again?

**Comment by s0llvan** [comment]
Anyone have a solution please...?

**Comment by MarkFilus** [comment]
@s0llvan https://forum.jellyfin.org/t-xml-document-error-after-upgrade?pid=29940#pid29940

**Comment by s0llvan** [comment]
> @s0llvan https://forum.jellyfin.org/t-xml-document-error-after-upgrade?pid=29940#pid29940

Doesn't work 😕

![image](https://github.com/user-attachments/assets/9d4ed9dc-ae77-4973-9bed-661cbf951bff)

**Comment by s0llvan** [comment]
> @s0llvan https://forum.jellyfin.org/t-xml-document-error-after-upgrade?pid=29940#pid29940

Thanks !

**Comment by vjdw** [comment]
The code that attempts to deserialize the empty migrations.xml is here I think

https://github.com/jellyfin/jellyfin/blob/5b63d093b1f7f2704d5e56fd0b5275e4dbf0fa80/Jellyfin.Server/Migrations/MigrationRunner.cs#L85C1-L89C43

```c#
var migrationOptions = File.Exists(migrationConfigPath)
     ? (MigrationOptions)xmlSerializer.DeserializeFromFile(typeof(MigrationOptions), migrationConfigPath)!
     : new MigrationOptions();
```

Would the simple fix of checking the XML file is not empty, instead of only checking whether it exists, be good enough? Or should exception handling be added in case there is content that can't be deserialized?

Another fix would be to not create the empty XML in the first place, but this startup code should probably also be made more robust.

And this code just after it looks like it could fail in the same way.

```c#
var serverConfig = File.Exists(appPaths.SystemConfigurationFilePath)
    ? (ServerConfiguration)xmlSerializer.DeserializeFromFile(typeof(ServerConfiguration), appPaths.SystemConfigurationFilePath)!
    : new ServerConfiguration();
```

**Comment by zackpete** [comment]
> Adding a disk usage check to database and XML file writes to avoid running out of space is 100% possible.

or just store migration information in the SQLite db that is already being used so you get transactional changes and this doesn't happen

**Comment by JPVenson** [comment]
you mean like this #13950 ?
