### ISSUE TITLE
Collection folders wont disappear and cant be removed

### ISSUE THREAD

**Issue by Joly0** [jellyfin/jellyfin#12305]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I tried some settings regarding collections in jellyfin, the system did a library scan and created a collection, then created a second collection. Then i disabled the settings, but the collections wont disappear and i cant remove them

### Reproduction steps

I have no idea

### What is the current _bug_ behavior?

Collections wont disappear and cant be removed

### What is the expected _correct_ behavior?

Collections should disappear

### Jellyfin Server version

10.9.7

### Specify the build version

10.9.7

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1.79
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: yes
- Base URL: nginx
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-19 22:23:41.832 +02:00] [ERR] [40] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/config/data/root/default/Sammlungen2"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/root/default/Sammlungen2'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2024-07-19 22:23:41.833 +02:00] [ERR] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/root/default/Sammlungen2'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.RequiresRefresh()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken, Boolean removeRoot)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### Relevant screenshots or videos

![grafik](https://github.com/user-attachments/assets/5d78464d-bac1-4273-ac8b-8dc80dd93a4b)
![grafik](https://github.com/user-attachments/assets/ce47adcf-ecab-4195-87e9-7b1fbbae77e7)

**Comment by Joly0** [comment]
Is there anything i can do? I really want that folders to disappear...

**Comment by theguymadmax** [comment]
@Joly0  See my [comment](https://github.com/jellyfin/jellyfin/issues/11937#issuecomment-2148155073) in another thread with a similar issue, that may help you out.

**Comment by Joly0** [comment]
> @Joly0 See my [comment](https://github.com/jellyfin/jellyfin/issues/11937#issuecomment-2148155073) in another thread with a similar issue, that may help you out.

Wow, thanks, that worked no problem :D
