### ISSUE TITLE
[Issue] Edit images on newly created libraries are not working

### ISSUE THREAD

**Issue by navilg** [jellyfin/jellyfin#12315]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

This issue started since I upgraded to 10.9.1. It works fine for libraries which were created prior to upgrading to 10.9.*. But any libraries which I create now has a problem with Editing Images. 

When I click on "Edit Image" on a library, A circle just keep circling forever and it never opens the window to edit image of library. 

### Reproduction steps

1. Sign into jellyfin using admin account
2. Go to Dashboards
3. Go to Libraries
4. Create a new library
5. After library is created, Click on 3 dots on library
6. Click on "Edit Images"

### What is the current _bug_ behavior?

Edit images on newly create libraries don't work. It just keep loading but window of editing image does not open

### What is the expected _correct_ behavior?

It should open the edit images window like it opens for existing libraries

### Jellyfin Server version

10.9.7

### Specify version number

10.9.8

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Ubuntu 22.04 ARM
- Virtualization: Docker container
- Clients: Jellyfin Web
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Traefik
- Base URL:
- Networking:
- Storage: Local disk
```

### Jellyfin logs

```shell
[2024-07-21 09:09:27.984 +00:00] [WRN] [10] MediaBrowser.Controller.Entities.BaseItem: Library folder "/data/movies/r" is inaccessible or empty, skipping
[2024-07-21 09:09:27.985 +00:00] [WRN] [10] MediaBrowser.Controller.Entities.BaseItem: Library folder "/data/movies/d" is inaccessible or empty, skipping
[2024-07-21 09:09:27.985 +00:00] [ERR] [10] Emby.Server.Implementations.Library.LibraryManager: Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/movies/p'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, Nullable`1 collectionType, LibraryOptions libraryOptions)
[2024-07-21 09:09:27.986 +00:00] [ERR] [10] Emby.Server.Implementations.Library.LibraryManager: Error in "PlaylistResolver" resolving "/data/movies/p"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/movies/p'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.Library.Resolvers.PlaylistResolver.Resolve(ItemResolveArgs args)
   at MediaBrowser.Controller.Resolvers.ItemResolver`1.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
[2024-07-21 09:09:27.986 +00:00] [ERR] [10] Emby.Server.Implementations.IO.ManagedFileSystem: Failed to enumerate path "/data/movies/p"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/movies/p'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntryPaths(String path, Boolean recursive)
[2024-07-21 09:09:27.987 +00:00] [WRN] [10] MediaBrowser.Controller.Entities.BaseItem: Library folder "/data/movies/p" is inaccessible or empty, skipping
[2024-07-21 09:09:27.987 +00:00] [WRN] [10] MediaBrowser.Controller.Entities.BaseItem: Library folder "/data/movies/guest" is inaccessible or empty, skipping
[2024-07-21 09:09:27.990 +00:00] [WRN] [10] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/data/playlists" is inaccessible or empty, skipping
[2024-07-21 09:09:32.438 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 4 seconds
[2024-07-21 09:09:32.479 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/movies/restricted"
[2024-07-21 09:09:32.486 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/samples/scenes"
[2024-07-21 09:09:32.492 +00:00] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/movies/n"
[2024-07-21 09:09:32.493 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/tvshows/restricted"
[2024-07-21 09:09:32.498 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/tvshows/all"
[2024-07-21 09:09:32.499 +00:00] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/tvshows/n"
[2024-07-21 09:09:38.551 +00:00] [INF] [24] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-07-21 09:09:38.551 +00:00] [INF] [24] Trakt.Helpers.LibraryManagerEventsHelper: No events... stopping queue timer
[2024-07-21 09:09:42.951 +00:00] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:09:43.290 +00:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:10:03.674 +00:00] [INF] [10] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:10:13.295 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:10:24.379 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:10:43.295 +00:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:10:45.153 +00:00] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:10:54.631 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Download missing subtitles" Completed after 0 minute(s) and 2 seconds
[2024-07-21 09:11:05.693 +00:00] [INF] [10] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:11:13.298 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:11:26.284 +00:00] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:11:30.871 +00:00] [INF] [31] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-07-21 09:11:43.300 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:11:46.885 +00:00] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:12:07.574 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:12:13.298 +00:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:12:28.103 +00:00] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:12:30.854 +00:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Completed after 0 minute(s) and 1 seconds
[2024-07-21 09:12:43.297 +00:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-21 09:12:48.628 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:13:09.188 +00:00] [INF] [30] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "24040fd12f14d8251e29fe3c307b4d8591407778b0167bed-1e29fe3c307b4d8591407778b0167bed-9093fc522901f773d00b57db8c9687cc"
[2024-07-21 09:13:13.297 +00:00] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```

### Client / Browser logs

BitrateTest 524288 bytes loaded (500000 requested) in 1.433 seconds -> 2926939 bps node_modules.jellyfin-apiclient.bundle.js:2:20799
Requesting https://mymedia.cloud/jellyfin/Playback/BitrateTest?Size=1000000 node_modules.jellyfin-apiclient.bundle.js:2:20356
BitrateTest 1048576 bytes loaded (1000000 requested) in 1.615 seconds -> 5194185 bps node_modules.jellyfin-apiclient.bundle.js:2:20799
Requesting https://mymedia.cloud/jellyfin/Users/39883076915e45bb86a3a567ea006f74/Items/2a3f1a2fca6a5059514a67c770845078 node_modules.jellyfin-apiclient.bundle.js:2:13545
XHRGET
https://mymedia.cloud/jellyfin/Users/39883076915e45bb86a3a567ea006f74/Items/2a3f1a2fca6a5059514a67c770845078
[HTTP/2 404  204ms]

Request failed to https://mymedia.cloud/jellyfin/Users/39883076915e45bb86a3a567ea006f74/Items/2a3f1a2fca6a5059514a67c770845078 [object Response] node_modules.jellyfin-apiclient.bundle.js:2:13925
Reporting request failure node_modules.jellyfin-apiclient.bundle.js:2:14071
Uncaught (in promise) 
Response { type: "basic", url: "https://mymedia.cloud/jellyfin/Users/39883076915e45bb86a3a567ea006f74/Items/2a3f1a2fca6a5059514a67c770845078", redirected: false, status: 404, ok: false, statusText: "", headers: Headers(10), body: ReadableStream, bodyUsed: false }

Sending web socket message: KeepAlive node_modules.jellyfin-apiclient.bundle.js:2:18698
Received KeepAlive from server. node_modules.jellyfin-apiclient.bundle.js:2:62736
Sending web socket message: KeepAlive node_modules.jellyfin-apiclient.bundle.js:2:18698
Received KeepAlive from server. node_modules.jellyfin-apiclient.bundle.js:2:62736

**Comment by theguymadmax** [comment]
@navilg Try renaming the "p" library to something else and any other libraries that you get the "Could not find a part of the path" error message. After renaming the libraries you can then rename them to their original names.

**Comment by navilg** [comment]
Thanks @theguymadmax Those paths are not in server but was added in a library. I removed those folder paths from libraries. Now I don't see above error message logs. But issue with edit image exist

**Comment by navilg** [comment]
Was anyone able to check this ?

**Comment by xusiai** [comment]
Experiencing this as well. Renaming does not resolve the perpetual loading.

**Comment by IlIiIlIIlIiIlIlIIIlI** [comment]
Also having this issue, running via Docker on Synology NAS, version: 10.9.11. Only occurs on newly created libraries.

**Comment by navilg** [comment]
Issue not fixed
