### ISSUE TITLE
server 10.9.8 could not work on windows 10

### ISSUE THREAD

**Issue by 8423ffsf** [jellyfin/jellyfin#12341]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

after a windows10 upgrade, the jellyfin server could not start as usual. But it could work well before.when start the server , it will show a page at localhost:8096(image#1). then then nothing., and the jellyfin server show a error like the image#2
[log_20240726.log](https://github.com/user-attachments/files/16388905/log_20240726.log)

### Reproduction steps

upgrade windows10 to 22H2(19045.4651)

### What is the current _bug_ behavior?

the server could not run

### What is the expected _correct_ behavior?

the server work as usual

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS:windows 10
- Linux Kernel:none
- Virtualization:none
- Clients:exploer
- Browser:edge
- FFmpeg Version:6.0.1
- Playback Method:none
- Hardware Acceleration:host
- GPU Model:gt210
- Plugins: none
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local
```

### Jellyfin logs

```shell
[2024-07-26 15:50:01.870 +08:00] [INF] [1] Main: Jellyfin version: "10.9.8"
[2024-07-26 15:50:01.941 +08:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\Users\Administrator\AppData\Local\Jellyfin\log]"]
[2024-07-26 15:50:01.954 +08:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\Users\Administrator\AppData\Local\Jellyfin"]
[2024-07-26 15:50:01.962 +08:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.19045"
[2024-07-26 15:50:01.967 +08:00] [INF] [1] Main: Architecture: X64
[2024-07-26 15:50:01.973 +08:00] [INF] [1] Main: 64-Bit Process: True
[2024-07-26 15:50:01.977 +08:00] [INF] [1] Main: User Interactive: True
[2024-07-26 15:50:01.981 +08:00] [INF] [1] Main: Processor count: 20
[2024-07-26 15:50:01.986 +08:00] [INF] [1] Main: Program data path: "C:\Users\Administrator\AppData\Local\Jellyfin"
[2024-07-26 15:50:01.990 +08:00] [INF] [1] Main: Log directory path: "C:\Users\Administrator\AppData\Local\Jellyfin\log"
[2024-07-26 15:50:01.994 +08:00] [INF] [1] Main: Config directory path: "C:\Users\Administrator\AppData\Local\Jellyfin\config"
[2024-07-26 15:50:01.998 +08:00] [INF] [1] Main: Cache path: "C:\Users\Administrator\AppData\Local\Jellyfin\cache"
[2024-07-26 15:50:02.002 +08:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-07-26 15:50:02.006 +08:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-07-26 15:50:02.485 +08:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\Users\Administrator\AppData\Local\Jellyfin\cache"
[2024-07-26 15:50:02.750 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-07-26 15:50:02.786 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.MeiamSub.Shooter, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\Jellyfin\plugins\Shooter Subtitles_1.0.4.0\Jellyfin.MeiamSub.Shooter.dll"
[2024-07-26 15:50:02.795 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.MeiamSub.Thunder, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\Jellyfin\plugins\Thunder Subtitles_1.0.4.0\Jellyfin.MeiamSub.Thunder.dll"
[2024-07-26 15:50:02.800 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "1.7.16.0" of "MetaShark" 
[2024-07-26 15:50:02.814 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\Jellyfin\plugins\configurations\open-subtitles_19.0.0.0\Jellyfin.Plugin.OpenSubtitles.dll"
[2024-07-26 15:50:03.418 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-07-26 15:50:03.431 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-07-26 15:50:03.438 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-07-26 15:50:03.453 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.193.108", "192.168.191.108", "192.168.191.215", "127.0.0.1", "fe80::61a3:9582:9430:8c3%10", "fe80::a6a9:72:da04:7f48%7", "::1"]
[2024-07-26 15:50:03.466 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[2024-07-26 15:50:03.471 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Blocklist"
[2024-07-26 15:50:03.476 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-07-26 15:50:10.710 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MeiamSub.Shooter" "1.0.4.0"
[2024-07-26 15:50:10.719 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MeiamSub.Thunder" "1.0.4.0"
[2024-07-26 15:50:10.729 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "19.0.0.0"
[2024-07-26 15:50:10.735 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.8.0"
[2024-07-26 15:50:10.741 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.8.0"
[2024-07-26 15:50:10.746 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.8.0"
[2024-07-26 15:50:10.825 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.8.0"
[2024-07-26 15:50:10.832 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.8.0"
[2024-07-26 15:50:11.040 +08:00] [INF] [1] Main: Kestrel is listening on "all interfaces"
[2024-07-26 15:50:11.829 +08:00] [INF] [1] Jellyfin.Networking.PortForwardingHost: Starting NAT discovery
[2024-07-26 15:50:13.911 +08:00] [ERR] [1] Microsoft.Extensions.Hosting.Internal.Host: Hosting failed to start
System.Net.Sockets.SocketException (10013): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[2024-07-26 15:50:13.952 +08:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[2024-07-26 15:50:13.957 +08:00] [FTL] [1] Main: Error while starting server
System.Net.Sockets.SocketException (10013): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-07-26 15:50:13.991 +08:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2024-07-26 15:50:14.046 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-07-26 15:50:14.051 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzArtistProvider"
[2024-07-26 15:50:14.055 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2024-07-26 15:50:14.059 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "PluginManager"
```

### Relevant screenshots or videos

![image#1](https://github.com/user-attachments/assets/9d068c7d-12a8-4f97-966c-e60e46da537c)
![image#2](https://github.com/user-attachments/assets/e4758083-af7e-4088-8428-c239d2b848d8)

**Comment by gnattu** [comment]
Can you open CMD and run this?

```
netsh interface ipv4 show excludedportrange protocol=tcp
```

**Comment by 8423ffsf** [comment]
![netsh interface ipv6 show excludedportrange protocol=tcp](https://github.com/user-attachments/assets/575e3180-11b4-4430-b793-beee24ad010f)
![netsh interface ipv4 show excludedportrange protocol=tcp](https://github.com/user-attachments/assets/fd6d7094-a1e5-4d15-b36b-0e3f5e1582fb)

**Comment by gnattu** [comment]
The windows update excludes port 8001-8100 so that applications cannot bind to that... The most common reason is the winnat used by wsl2/hyper-v reserved this range so that jellyfin cannot bind to that. You can try `net stop winnat` in an admin cmd, start jellyfin, then `net start winnat` again to see if that fixed your issue. I'm not sure if this workaround could survive a reboot though.

**Comment by 8423ffsf** [comment]
After the cmd code,the server finally works
