### ISSUE TITLE
Invalid non-ASCII or control character in header: 0x4E0A

### ISSUE THREAD

**Issue by itlangzi** [jellyfin/jellyfin#1234]
> jellyfin[9430]: at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
> jellyfin[9430]: [21:54:58] [ERR] Error processing request
> jellyfin[9430]: System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x4E0A
> jellyfin[9430]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
> jellyfin[9430]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues& headerValues)
> jellyfin[9430]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues& value)
> jellyfin[9430]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
> jellyfin[9430]: at Emby.Server.Implementations.Services.ResponseHelper.WriteToResponse(IResponse response, IRequest request, Object result, CancellationToken cancellationToken)
> jellyfin[9430]: at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
> jellyfin[9430]: at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by taking** [comment]
I think this issue **Critical**
I have the same problem. Korean in the file name.

**Comment by junho76** [comment]
I met same problem.

[2019-04-21 11:18:56.779 +09:00] [ERR] Error processing request
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0xC624
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues& headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues& value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at Emby.Server.Implementations.Services.ResponseHelper.WriteToResponse(IResponse response, IRequest request, Object result, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

I guess that language charset encoding may cause error

**Comment by DrPandemic** [comment]
On which action is this triggered? If it's on download https://github.com/jellyfin/jellyfin/issues/1234 should fix it
