### ISSUE TITLE
SqliteConnection does not support nested transactions

### ISSUE THREAD

**Issue by 0x00c** [jellyfin/jellyfin#12358]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Manually scanning the library fails or running the sheduled action fails with an System.InvalidOperationException

### Reproduction steps

1. Sign in on the Jellyfin web client with an admin account (using a supported browser of your choice)
2. Navigate to admin dashboard
3. Trigger a library scan

### What is the current _bug_ behavior?

Library Scan fails immediately

### What is the expected _correct_ behavior?

Library Scan is successfull

### Jellyfin Server version

10.9.8+

### Specify version number

10.9.8

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Windows Server 2022 (Version 21H2, OS Build 20348.2582)
- Linux Kernel:
- Virtualization: KVM (virtual ServeR)
- Clients: Browser
- Browser: Chrome 127.0.6533.73
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin
- Playback Method:
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: yes
- Networking: Host
- Storage: NFS
```

### Jellyfin logs

```shell
[2024-07-30 15:17:41.341 +02:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scanne Medien-Bibliothek" Failed after 0 minute(s) and 0 seconds
[2024-07-30 15:17:51.117 +02:00] [ERR] [45] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.InvalidOperationException: SqliteConnection does not support nested transactions.
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveImages(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

### Additional information

There are a few things I want to add:

- This only fails when triggering the library scan manually or by sheduled task. 
- Library scan is successfull when it runs when the application launches
- triggering a restart from the dashboard also crashes the application and does not bring it back
- I believe this is new since 10.9.8, library scan was reliable in earlier versions

Full Log is attached:
[Log.txt](https://github.com/user-attachments/files/16428763/Log.txt)

Hence I have my Jellyfin in German, "Scanne Medien-Bibliothek" means "scan library"

**Comment by gnattu** [comment]
I believe the playback reporting plugin is misbehaving again... Can you disable it and try again?
