### ISSUE TITLE
Starting Episode start another already watched one

### ISSUE THREAD

**Issue by infinitel8p** [jellyfin/jellyfin#12352]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When attempting to play an episode, regardless of whether it's selected from the "Next Up" tab, the homescreen, or within the show itself, the player starts the episode minus four. For example, if I try to start S8E8, it instead opens S8E4 (as seen in the gif). This issue has been occurring since passing some episodes that have a second part. I have tried removing the files, scanning the library to remove them, renaming the files, and adding them again, but the issue persists.

I've noticed this only with Detective Conan so i suspect the Episodes with the multiple parts may broke something
(I have the german version which for example split S07E22 into two episodes, so i named them accordingly to keep the tvdb order `S07E22 - Das Haus der 200 Masken - Part 1` and `S07E22 - Das Haus der 200 Masken - Part 2`)

![ezgif-2-e90a0cb3c6](https://github.com/user-attachments/assets/10e87955-08f5-4528-9c6f-3355498649fd)

### Reproduction steps

1. Open Jellyfin
2. Click on Episode of Detective Conan (or navigate to shows, click Detective Conan and select Episode from next up)
3. Wrong episode starts

### What is the current _bug_ behavior?

Episode of choice minus 4 starts

### What is the expected _correct_ behavior?

Episode of choice starts

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- Linux Kernel: 6.6.31+rpt-rpi-2712
- Virtualization:
- Clients: browser, mac app, android/iphone app
- Browser: Safari
- FFmpeg Version: 5.1.5-0+rpt1+deb12u1
- Playback Method: direct
- Hardware Acceleration: none
- GPU Model: none
- Plugins: many
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-28 20:09:07.617 +02:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-07-28 20:09:10.029 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:09:19.618 +02:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-07-28 20:09:31.617 +02:00] [INF] Lost 1 WebSockets.
[2024-07-28 20:09:40.028 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:10:10.022 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:10:40.019 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:11:10.017 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:11:40.017 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-07-28 20:11:43.834 +02:00] [INF] User policy for "ludo". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-07-28 20:11:44.220 +02:00] [ERR] Error processing request. URL "POST" "/Sessions/Playing".
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'Expression tree is too large (maximum depth 1000)'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(SqliteCommand command)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemList(InternalItemsQuery query, Boolean allowExternalContent)
   at Emby.Server.Implementations.Session.SessionManager.UpdateNowPlayingItem(SessionInfo session, PlaybackProgressInfo info, BaseItem libraryItem, Boolean updateLastCheckInTime)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackStart(PlaybackStartInfo info)
   at Jellyfin.Api.Controllers.PlaystateController.ReportPlaybackStart(PlaybackStartInfo playbackStartInfo)
   at lambda_method1700(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-07-28 20:11:55.216 +02:00] [INF] WS "192.168.178.202" request
[2024-07-28 20:12:10.019 +02:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```

**Comment by felix920506** [comment]
Please provide the file structure.

**Comment by felix920506** [comment]
Can you try a rescan with "replace all metadata" option?

**Comment by JPVenson** [comment]
mind trying to put the media files into individial season folders?
```
Season 01/ 
/S01E01 - Die tödliche Perlenkette-thumb.jpg
/S01E01 - Die tödliche Perlenkette.mkv
/S01E01 - Die tödliche Perlenkette.nfo
...
Season 08/
/S08E20 - Der Wald, die Bären, die Jäger (2)-thumb.jpg
/S08E20 - Der Wald, die Bären, die Jäger (2).mkv
/S08E20 - Der Wald, die Bären, die Jäger (2).nfo
``` 

After that please try a full rescan.

**Comment by TheMelmacian** [comment]
Are the multi part episodes correctly shown as one episode inside jellyfin?

Only a workaround, but if the multi part episodes are the problem you could merge them together with mkvtoolnix (if you're OK with having only one file for these episodes). It's also possible to automatically generate chapters at the beginning of each file. And if you later decide you prefer separate files, mkvtoolnix can also split files at chapter marks.

You can use leading zeros in the folder names for the seasons. This way they are also sorted correctly in the file explorer.

**Comment by eskey0** [comment]
I think I have the same issue, for me it's for a sport with lots of episodes (38 at the moment) when you try to play the last (unwatched) one, it reproduces 2 episodes before (lets say 36 and you asked for the last one 38).

You can skip to the last one clicking next and next.
In the log of the server, the client is asking for the episode 36, so from its side looks right.

That happends in web, desktop app and android client, but NOT in the android tv app (which is weird)

I have the last server version 10.9.11 and all my clients are updated to the last possible version.

In my case they are not multipart videos, and I can reproduce it consistenlty, and provide any logs or do any test needed.

**Comment by felix920506** [comment]
Do you have specials set to play within the season?

**Comment by eskey0** [comment]
> Do you have specials set to play within the season?

Nop, just plain serie with seasons, because its a sport the tree look like this:

2023-> 2023x01, 2023x02, 2023x03...
2024-> 2024x01,2024x02.......2024x38

Have no problem with this system until mid this year, I really can't tell which version broke it.

**Comment by Erunamo86** [comment]
Hello,

I wanted to add a few observations I've made regarding (I think) the same issue with tv shows that contain single episodes split across multiple files and using the jellyfin suggested naming scheme ("S01E04 Title - pt1" and "S01E04 Title - pt2" for example).

The observations below are present across several clients I could test with (Jellyfin Media Player on Win 10, Jellyfin Web Player 10.9.11 within Vivaldi/Chrome and Firefox) and the Android client (2.6.2, but only when using the web player or integrated player in the client settings; external player like VLC works fine, see point **5.** below).

I've created a "minimal working example" (sort of) consisting of three seasons of a tv show, separate folders for each season and the first 8 episodes of each season. S01E04 and S03E01 are split into two parts and named according to the suggested naming scheme ("S01E04 Title - pt1" and "S01E04 Title - pt2"; the same for S03E01 -- in reality however I just used another media file from a later season as "S01E04 Title - pt2" and "S03E01 Title - pt2" instead of actually splitting S01E04 and S03E01).
I've also attached screenshots to illustrate my points but I hope I can explain them well enough without them. Screenshots are named according to the list of observations found below. But sometimes you have to see things :-)

[Jellyfin-split-episodes-issue.zip](https://github.com/user-attachments/files/17127620/Jellyfin-split-episodes-issue.zip)

__As soon as those two episodes are removed from the file system and "Refresh Metadata -> Scan for new and updated" is completed, the remaining episodes play without any of the below mentioned issues!__

0. The directory structure of the show contains episodes split into multiple parts (S01E04 and S03E01).

1. Navigate to season 1 or 3 of the show, Jellyfin shows both S01E04 and S03E01 as a single entry (as it should be) with "Additional Parts" present when you open the page for the individual episode. 
However, Jellyfin (for some reason) includes parts of the filename of those two episodes as the episode titles. It does not do that for the remaining episodes (that aren't split).

2. When trying to play an episode from a season's overview, the episode that is actually played varies by an offset determined by the number of additional (unexpected?) parts of episodes that came __before that episode across the whole show__.
So, in our example, if I want to start episode S01E01 it does so -- the same for each episode until S01E04 (which is the first split into 2 parts). Trying to play S01E**05** actually starts E01E**04-pt2**(!), S01E**06** starts S01E**05** and so on. This also wraps around seasons. Thus, trying to start S02E01 actually starts S01E08 (the last one in S01). 
This offset continues until S03E01 -- which is again split into two parts. From then on, the offset will be **2**: Starting S03E**02** launches S03E**01-pt1**, starting S03E**03** launches S03E**01-pt2**, starting S03E**04** starts S03E**02**, ...

3. When trying to play an episode from an individual episode's page, two things can happen depending on whether you "have and offset" or not as described in 2. above.
If you navigate to any detail page for S01E01 to S01E04 and press play -- it plays (duh!).
If you navigate to any detail page for an episode after a split episode (so, in my example anything from S01E05 onwards) Jellyfin __will not play anything__. The web player and the Jellyfin Media Player throw two errors (first "Playback Error - There was an error processing the request. Please try again later." and then "Playback Error - This client isn't compatible with the media and the server isn't sending a compatible media format") and the Android app opens the player screen without throwing an error -- but plays nothing.

4. When trying to play a file from the "More from Season X" list within an individual episode (see 3. above) it plays the files according to the offset.
So, trying to play S01E05 from its own page with the "play" button throws an error and fails (see 3. above) but selecting S01E06 from the "More from Season 1"-list immediately below actually plays S01E05.

5. Contrary to the playback issues mentioned in 2. to 4. above: actions involving the "triple bar"/"hamburger" menu  that do **not** cause Jellyfin to start playing an episode actually work correctly:
* "Media info" gives the correct path to the correct episode
* "Download" downloads the correct video file
* "Copy Stream URL" and pasting it into VLC will play the correct video.
In the same spirit, using the Android app with an external player also "resolves" the issues 2. to 4. in the sense that Jellyfin passes the correct link to VLC and VLC plays the correct file (while the internal player, as stated, doesn't).

It seems to me that somewhere when trying to play a file, the files containing "-pt" are treated as individual episodes (instead of parts of a sinlge episode) and "stuff" gets misaligned there.

I guess this is all a niche case, but the behaviour is nonetheless not as it supposed to be. At least in this state, episodes that fall into the "Episodes Split Across Multiple Parts"-case as outlined in the [docs](https://jellyfin.org/docs/general/server/media/shows/#episodes-split-across-multiple-parts) are not managed correctly across several clients.

As stated, deleting all split episodes across a show (and refreshing metadata) solves all of the above problems -- but that might not always be possible or desired. 

Or maybe I am overlooking something -- every help/solution/nudge in the right direction is much appreciated! Thanks!

**Comment by eskey0** [comment]
Just for add some information, I did have one multipart episode (with 3 parts) that totally missed, If I delete that episode (all it's parts) the playback works as expected.

**Comment by felix920506** [comment]
Try playing it in a client that isn't based on Jellyfin-web
E.g. Jellyfin-vue, Swiftfin, Androidtv (different thing from Android app)

**Comment by Erunamo86** [comment]
> Try playing it in a client that isn't based on Jellyfin-web E.g. Jellyfin-vue, Swiftfin, Androidtv (different thing from Android app)

I "borrowed" my son's FireTV Stick (AndroidTV Client 0.17.6) to do some quick tests.

On the plus side: The AndroidTV client does start the correct episodes from UI even if (single) episodes in multiple parts are present -- there is no "offset".

However on the negative side, AndroidTV seems to ignore "-pt2" files entirely (which might explain the missing "offset" to begin with).  
First, there is no "Additional Parts" section in the UI within multipart episodes (so you can't start "-pt2"-files directly like you can with jellyfin-web). 
Second, it doesn't even play "-pt2"-files after "-pt1" is about to finish. Even if autoplay of next episodes is activated in the menu, it will jump directly from (e.g.) "S03E01 - pt1" to "S03E02" skipping "S03E01 - pt2" altogether.

So while AndroidTV does play the correct episodes from the UI, it does so because it ignores additional "-pt"-files in TV shows (which isn't really ideal either.)...
