### ISSUE TITLE
Bug: Can't remove music library

### ISSUE THREAD

**Issue by yuygfgg** [jellyfin/jellyfin#12360]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I added a music folder in Jellyfin 10.9.0 (at that time it's the latest one) and removed it in the same version. And the music library keep showing up in web page since then, never removed. But I can't see it in dashboard.
<img width="1861" alt="截屏2024-07-31 09 42 53" src="https://github.com/user-attachments/assets/04d731b7-131c-4c52-84e3-fa7ea6e99637">
<img width="1861" alt="截屏2024-07-31 09 43 39" src="https://github.com/user-attachments/assets/bfdd1437-48f3-447f-b3a8-27a1f55a04e6">

### Reproduction steps

1. add a music folder, using category music
2. remove it
3. wait for over three months

### What is the current _bug_ behavior?

I can't remove it

### What is the expected _correct_ behavior?

remove successfully and never appear again

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6.5.0-41-generic
- Virtualization: N/A
- Clients: Webui
- Browser: Edge, Chrome, Firefox, Safari...
- FFmpeg Version: 7.0.1
- Playback Method: Webui, Infuse, ...
- Hardware Acceleration: QSV, VAAPI
- GPU Model: UHD600
- Plugins: AniDB9.0.0.0, AudioDB10.9.8.0, Bangumi1.6.2.0, DLNA2.0.0.0, Danmu2.0.6.0, InfuseSync1.5.0.0, MusicBrainz10.9.8.0, OMDb10.9.8.0, Studio Images10.9.8.0, TMDb10.9.8.0
- Reverse Proxy: no
- Base URL: /
- Networking: N/A
- Storage: smb, nfs
```

### Jellyfin logs

```shell
[2024-07-31 05:44:34.563 +08:00] [ERR] Error refreshing owned items for "/var/lib/jellyfin/root/default/音乐"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/音乐'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2024-07-31 05:44:34.564 +08:00] [ERR] Error executing Scheduled Task
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/音乐'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.RequiresRefresh()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken, Boolean removeRoot)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### Additional information

It's a HUGE folder. In the first days I see logs like ``` xxx album removed ```, but no longer these days.

**Comment by yuygfgg** [comment]
solved by manually create '/var/lib/jellyfin/root/default/音乐'
