### ISSUE TITLE
Permission denied when accessing some files in /cache/temp/

### ISSUE THREAD

**Issue by Lyphion** [jellyfin/jellyfin#12404]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Scanning a library of type 'Home Videos and Photos' causes _some_ subfolders to not generate a thumbnail and log an error which points to an UnauthorizedAccessException with 'Permission denied' to files inside `/cache/temp/`.

After migrating from the TrueCharts App to TrueNAS Charts and recreating my Jellyfin setup, I was unable to restore the behavior of my private image and video collection.

I checked, that all permissions are set correctly: Jellyfin runs as User/Group apps/apps and has full read access to all images/videos in the library, which can be confirmed by opening the subfolders (inside the browser) and successfully viewing the images inside the folder as a preview or fullscreen. Also the permission of the `/cache/`, `/cache/temp/` are set correctly to full access for Jellyfin:

```
drwxr-xr-x 8 apps apps    8 Aug  6 18:08 /cache
drwxr-xr-x 2 apps apps 1.4K Aug  6 18:51 /cache/temp
```

The strange thing is, for some folders the thumbnail can be generated without an error, also movies and series work without any problems.

Viewing the permissions of the files inside `/cache/temp/` we can see, that for some images no permission mask it set. The content of these files all seem valid.

```
...
---------- 1 apps apps 1.3M Feb 19  2018 66da1fd710d042f88d22cb14c3678d65.jpg
-rw-r--r-- 1 apps apps  27K Aug  6 18:32 66e942ab-3df1-4677-a8e0-0970073d8dc0.jpg
-rw-r--r-- 1 apps apps 188K Aug  6 18:34 66fd2983-c9d0-4f44-b084-c0ff689e1436.jpg
---------- 1 apps apps 3.7M Dec 19  2018 67580c38a079482d8ce645928cf990c6.jpg
---------- 1 apps apps 4.9M Oct 20  2019 67c7b76bf2b84a36af89ee7fd6b273ad.jpg
...
```

The files with '-' in the name seem to be thumbnails of episodes of series.
Restarting or recreating the container doesn't help.

### Reproduction steps

1. Create Library of type 'Home Videos and Photos'
2. Add media folders to library containing subfolders with images and videos
3. Scan library
4. Seeing that for some folder a thumbnail exists and for others not
5. Getting an UnauthorizedAccessException in the logs

### What is the current _bug_ behavior?

Unable to generate thumbnail of some subfolder inside library and getting Permission denied on files inside `/cache/temp/`

### What is the expected _correct_ behavior?

Successfully creating thumbnails of subfolders

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: TrueNAS Scale 24.04.2
- Linux Kernel: 6.6.32-production+truenas
- Virtualization: Docker/Kubernetes (TrueNAS official App)
- Clients: Browser
- Browser: Brave 1.68.134
- FFmpeg Version: 6.0.1
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: Docker/Host
- Storage: Local
```

### Jellyfin logs

```shell
[2024-08-06 18:51:05.103 +02:00] [ERR] [8] MediaBrowser.Providers.Photos.PhotoAlbumMetadataService: Error in "Dynamic Image Provider"
System.UnauthorizedAccessException: Access to the path '/cache/temp/67580c38a079482d8ce645928cf990c6.jpg' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at MediaBrowser.Model.IO.AsyncFile.OpenRead(String path)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, IReadOnlyList`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### Additional information

I already made an issue on the TrueNAS Charts Repository https://github.com/truenas/charts/issues/2683 where they pointed out that this might be an Jellyfin Issue. The behavior kept the same after updating to Jellyfin 10.9.9.

**Comment by felix920506** [comment]
You are moving from one community package to another, therefore this is not an actual bug with Jellyfin. Please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact
