### ISSUE TITLE
Error when adding XMLTV file

### ISSUE THREAD

**Issue by KintsugiUwU** [jellyfin/jellyfin#12413]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hi, after adding the XMLTV file http://www.epgitalia.tv/gzip jellyfin throws me this error for every channel available in the m3u file. 
Note that this xmltv works fine in KODI

This does not happen with this XMLTV https://tvit.leicaflorianrobert.dev/epg/list.xml

### Reproduction steps

Add the http://www.epgitalia.tv/gzip and try refreshing the tv guide

### What is the current _bug_ behavior?

System.Xml.XmlException: Name cannot begin with the '=' character, hexadecimal value 0x3D. Line 1, position 5315.

### What is the expected _correct_ behavior?

To just work

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: TrueNas Scale (Debian)
- Virtualization: Jellyfin running in Docker
- Hardware Acceleration: QuickSync
- GPU Model: Intel(R) Core(TM) i5-7500 CPU iGPU
```

### Jellyfin logs

```shell
[2024-08-09 07:25:25.667 +02:00] [ERR] [71] Jellyfin.LiveTv.Guide.GuideManager: Error getting programs for channel "Rai 1"
System.Xml.XmlException: Name cannot begin with the '=' character, hexadecimal value 0x3D. Line 1, position 5315.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at Jellyfin.XmlTv.XmlTvReader.GetChannels()
   at Jellyfin.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Listings.ListingsManager.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Listings.ListingsManager.GetProgramsAsync(ChannelInfo channel, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.DefaultLiveTvService.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Guide.GuideManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[2024-08-09 07:25:25.667 +02:00] [INF] [71] Jellyfin.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "https://tvepg.eu/it/italy/epg"
```

**Comment by AsterITA** [comment]
I'm having the exact same problem
