### ISSUE TITLE
Kubernetes versions 10.9.x

### ISSUE THREAD

**Issue by yuval987** [jellyfin/jellyfin#12410]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hi,

I have been using Jellyfin 10.8.3 in a Kubernetes environment, and it was working fine until yesterday. Suddenly, this version stopped working, so I upgraded to Jellyfin 10.9.x. I tried multiple versions within 10.9.x, but I encountered the same issues with all of them:

- Scanning the library takes a lot of time.
- The app gets stuck and freezes.
- After starting a playback session, the app crashes and the pod restarts.

I am using the official Jellyfin image.

I hope you can help me with these problems.

Thanks,

### Reproduction steps

Upgrade to 10.9.9 (10.9.8 too)

### What is the current _bug_ behavior?

Not working well

### What is the expected _correct_ behavior?

Not working well

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: linux
- Linux Kernel: k8s
- Virtualization: k8s
- Clients: all
- Browser: all
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: ldap (19.0.0) 
- Reverse Proxy: haproxy (but I tried without the proxy - same problems)
- Base URL:
- Networking: 
- Storage: nfs
```

### Jellyfin logs

```shell
nManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:13.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:14.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:15.776 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:16.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:17.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:18.775 +00:00] [ERR] [114] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:19.776 +00:00] [ERR] [114] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:20.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:21.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:22.776 +00:00] [ERR] [117] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:23.775 +00:00] [ERR] [117] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:24.776 +00:00] [ERR] [117] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:25.775 +00:00] [ERR] [114] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:26.775 +00:00] [ERR] [113] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 51e888de62ccd75b535f5b167a8fd4d2 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-08-08 04:47:27.508 +00:00] [INF] [78] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.100" request
[2024-08-08 04:47:47.390 +00:00] [INF] [84] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-08 04:47:59.982 +00:00] [INF] [73] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.

[05:15:38] [WRN] [41] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.1.100 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.

```

**Comment by gnattu** [comment]
If you are storing the DB file on NFS, we cannot help much because the current SQLite DB access pattern performs very poorly with NFS. Additionally, the upstream SQLite project maintainers have clearly stated that NFS is not a supported use case, making it very unlikely to be resolved anytime soon.

**Comment by yuval987** [comment]
Thank you. I'll try relocating the database. It was working fine with the old version (10.8.3). Was there any change related to the database in this version?
@gnattu

**Comment by gnattu** [comment]
The old version's access pattern was slow enough to prevent a lot of issues :)
