### ISSUE TITLE
FFmpeg Fails with 'Invalid Argument' Error When Extracting Multiple Attachments from MKV Files

### ISSUE THREAD

**Issue by NexiaMoe** [jellyfin/jellyfin#12450]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When try to play an Anime episode with a lot of MKV Attachment (Multiple subtitles in this case), video player is buffering forever and, in the log, there is error 

```
[2024-08-14 15:58:12.800 +00:00] [WRN] Unable to cache media attachments for File:"/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv"
MediaBrowser.Common.FfmpegException: ffmpeg media attachment extraction failed for /shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.CacheAllAttachmentsInternal(String mediaPath, String inputFile, MediaSourceInfo mediaSource, List`1 extractableAttachmentIds, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.CacheAllAttachments(String mediaPath, String inputFile, MediaSourceInfo mediaSource, CancellationToken cancellationToken) 
```

### Reproduction steps

1. Have a MKV Video file with a lot of attachments like font
2. Play with jellyfin video player at browser
3. Change the subtitle from none to any subtitle

### What is the current _bug_ behavior?

Jellyfin video player will buffering forever without error.

### What is the expected _correct_ behavior?

Video should play normally with subtitle enabled.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel: 6.8.8-2-pve
- Virtualization: LXC
- Clients: Browser
- Browser: Edge 127.0.2651.98
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: Intel QSV
- GPU Model: Intel HD 630
- Plugins: AudioDB, Intro Skipper, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2024-08-14 16:01:33.195 +00:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" " -dump_attachment:133 \"/var/lib/jellyfin/data/attachments/8/8b4ce490-14ed-61a1-29db-11bc2044e168\" -dump_attachment:134 \"/var/lib/jellyfin/data/attachments/9/98e955bc-8e4d-9e3f-2256-19983b65e5eb\" -dump_attachment:135 \"/var/lib/jellyfin/data/attachments/9/96ec00ec-fec6-3f7a-4c24-24d8b2443162\" -dump_attachment:136 \"/var/lib/jellyfin/data/attachments/0/0e712492-7e63-57d1-969d-e01b63e8432c\" -dump_attachment:137 \"/var/lib/jellyfin/data/attachments/2/2aa46dce-2f88-8a6f-5b55-0b4ed385fdd2\" -dump_attachment:138 \"/var/lib/jellyfin/data/attachments/6/6441358b-42d6-9998-59f1-9b443d7520a5\" -dump_attachment:139 \"/var/lib/jellyfin/data/attachments/9/9521ceee-e4cd-1772-0278-32f77e75b3bf\" -dump_attachment:140 \"/var/lib/jellyfin/data/attachments/0/089b09c1-a2fc-d9c5-9d28-8f1e83b14ac9\" -dump_attachment:141 \"/var/lib/jellyfin/data/attachments/7/75734cee-0203-9913-8be9-d5bad445235b\" -dump_attachment:142 \"/var/lib/jellyfin/data/attachments/3/3fa9ebee-5f82-679d-fecd-bbddd027d8cc\" -dump_attachment:143 \"/var/lib/jellyfin/data/attachments/8/8dbcf917-bf46-48ad-3b27-5eb3fe36d368\" -dump_attachment:144 \"/var/lib/jellyfin/data/attachments/b/b9dd7eef-d030-dab6-0605-b52625fcd916\" -dump_attachment:145 \"/var/lib/jellyfin/data/attachments/c/cf01592b-2126-ce0e-1ea5-cf206a460538\" -dump_attachment:146 \"/var/lib/jellyfin/data/attachments/2/20d92ee0-941d-9138-a818-d75552e83db7\" -dump_attachment:147 \"/var/lib/jellyfin/data/attachments/9/98f74534-3fb9-f3d3-9d8e-9158e1269174\" -dump_attachment:148 \"/var/lib/jellyfin/data/attachments/c/cf18b910-5ff1-ae2a-a0c2-1deb878cebd1\" -dump_attachment:149 \"/var/lib/jellyfin/data/attachments/4/4aabc0b6-29d4-8e18-eef3-903a71c1617b\" -dump_attachment:150 \"/var/lib/jellyfin/data/attachments/2/28ea0286-b867-a487-dde3-d2eb5d69745e\" -dump_attachment:151 \"/var/lib/jellyfin/data/attachments/7/7cf335ab-51f8-7d81-1e1a-fb3f5b86f334\" -dump_attachment:152 \"/var/lib/jellyfin/data/attachments/3/3a4a12ac-a7ae-80fd-2237-ab56e5fe16fa\" -dump_attachment:153 \"/var/lib/jellyfin/data/attachments/e/e5358618-fec5-18d8-c0b7-1391ec9e0b4a\" -dump_attachment:154 \"/var/lib/jellyfin/data/attachments/7/736d0428-f1df-58a7-f86e-abaf7ddea08a\" -dump_attachment:155 \"/var/lib/jellyfin/data/attachments/d/ddb57ecc-262f-8e6c-50d7-714dfa5133ce\" -dump_attachment:156 \"/var/lib/jellyfin/data/attachments/3/3c50f3fa-4c4e-f12b-42a4-0e56cb4d6542\" -dump_attachment:157 \"/var/lib/jellyfin/data/attachments/f/f02a7db5-0a06-7e72-7a4c-2ef41c8674ec\" -dump_attachment:158 \"/var/lib/jellyfin/data/attachments/c/c26f4de8-dfc4-0390-dddb-5ab4d78fd852\" -dump_attachment:159 \"/var/lib/jellyfin/data/attachments/0/001497be-8013-e31e-cab8-d8bb99ca7bb6\" -dump_attachment:160 \"/var/lib/jellyfin/data/attachments/6/688aeb9d-310c-70d9-55fe-f7190b777f6a\" -dump_attachment:161 \"/var/lib/jellyfin/data/attachments/0/08458d41-7bb0-2b23-a1c9-709d2adef127\" -dump_attachment:162 \"/var/lib/jellyfin/data/attachments/7/72724653-699f-1207-f812-f6d685af8c45\" -i \"/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv\" -t 0 -f null null"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/8/8b4ce490-14ed-61a1-29db-11bc2044e168"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/9/98e955bc-8e4d-9e3f-2256-19983b65e5eb"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/9/96ec00ec-fec6-3f7a-4c24-24d8b2443162"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/0/0e712492-7e63-57d1-969d-e01b63e8432c"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/2/2aa46dce-2f88-8a6f-5b55-0b4ed385fdd2"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/6/6441358b-42d6-9998-59f1-9b443d7520a5"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/9/9521ceee-e4cd-1772-0278-32f77e75b3bf"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/0/089b09c1-a2fc-d9c5-9d28-8f1e83b14ac9"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/7/75734cee-0203-9913-8be9-d5bad445235b"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/3/3fa9ebee-5f82-679d-fecd-bbddd027d8cc"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/8/8dbcf917-bf46-48ad-3b27-5eb3fe36d368"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/b/b9dd7eef-d030-dab6-0605-b52625fcd916"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/c/cf01592b-2126-ce0e-1ea5-cf206a460538"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/2/20d92ee0-941d-9138-a818-d75552e83db7"
[2024-08-14 16:01:34.580 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/9/98f74534-3fb9-f3d3-9d8e-9158e1269174"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/c/cf18b910-5ff1-ae2a-a0c2-1deb878cebd1"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/4/4aabc0b6-29d4-8e18-eef3-903a71c1617b"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/2/28ea0286-b867-a487-dde3-d2eb5d69745e"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/7/7cf335ab-51f8-7d81-1e1a-fb3f5b86f334"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/3/3a4a12ac-a7ae-80fd-2237-ab56e5fe16fa"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/e/e5358618-fec5-18d8-c0b7-1391ec9e0b4a"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/7/736d0428-f1df-58a7-f86e-abaf7ddea08a"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/d/ddb57ecc-262f-8e6c-50d7-714dfa5133ce"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/3/3c50f3fa-4c4e-f12b-42a4-0e56cb4d6542"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/f/f02a7db5-0a06-7e72-7a4c-2ef41c8674ec"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/c/c26f4de8-dfc4-0390-dddb-5ab4d78fd852"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/0/001497be-8013-e31e-cab8-d8bb99ca7bb6"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/6/688aeb9d-310c-70d9-55fe-f7190b777f6a"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/0/08458d41-7bb0-2b23-a1c9-709d2adef127"
[2024-08-14 16:01:34.584 +00:00] [ERR] ffmpeg media attachment extraction failed for "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" to "/var/lib/jellyfin/data/attachments/7/72724653-699f-1207-f812-f6d685af8c45"
[2024-08-14 16:01:34.584 +00:00] [WRN] Unable to cache media attachments for File:"/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv"
MediaBrowser.Common.FfmpegException: ffmpeg media attachment extraction failed for /shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.CacheAllAttachmentsInternal(String mediaPath, String inputFile, MediaSourceInfo mediaSource, List`1 extractableAttachmentIds, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.CacheAllAttachments(String mediaPath, String inputFile, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[NULL @ 0x613d8c35e400] Unable to find a suitable output format for ' -dump_attachment:133 "/var/lib/jellyfin/data/attachments/8/8b4ce490-14ed-61a1-29db-11bc2044e168" -dump_attachment:134 "/var/lib/jellyfin/data/attachments/9/98e955bc-8e4d-9e3f-2256-19983b65e5eb" -dump_attachment:135 "/var/lib/jellyfin/data/attachments/9/96ec00ec-fec6-3f7a-4c24-24d8b2443162" -dump_attachment:136 "/var/lib/jellyfin/data/attachments/0/0e712492-7e63-57d1-969d-e01b63e8432c" -dump_attachment:137 "/var/lib/jellyfin/data/attachments/2/2aa46dce-2f88-8a6f-5b55-0b4ed385fdd2" -dump_attachment:138 "/var/lib/jellyfin/data/attachments/6/6441358b-42d6-9998-59f1-9b443d7520a5" -dump_attachment:139 "/var/lib/jellyfin/data/attachments/9/9521ceee-e4cd-1772-0278-32f77e75b3bf" -dump_attachment:140 "/var/lib/jellyfin/data/attachments/0/089b09c1-a2fc-d9c5-9d28-8f1e83b14ac9" -dump_attachment:141 "/var/lib/jellyfin/data/attachments/7/75734cee-0203-9913-8be9-d5bad445235b" -dump_attachment:142 "/var/lib/jellyfin/data/attachments/3/3fa9ebee-5f82-679d-fecd-bbddd027d8cc" -dump_attachment:143 "/var/lib/jellyfin/data/attachments/8/8dbcf917-bf46-48ad-3b27-5eb3fe36d368" -dump_attachment:144 "/var/lib/jellyfin/data/attachments/b/b9dd7eef-d030-dab6-0605-b52625fcd916" -dump_attachment:145 "/var/lib/jellyfin/data/attachments/c/cf01592b-2126-ce0e-1ea5-cf206a460538" -dump_attachment:146 "/var/lib/jellyfin/data/attachments/2/20d92ee0-941d-9138-a818-d75552e83db7" -dump_attachment:147 "/var/lib/jellyfin/data/attachments/9/98f74534-3fb9-f3d3-9d8e-9158e1269174" -dump_attachment:148 "/var/lib/jellyfin/data/attachments/c/cf18b910-5ff1-ae2a-a0c2-1deb878cebd1" -dump_attachment:149 "/var/lib/jellyfin/data/attachments/4/4aabc0b6-29d4-8e18-eef3-903a71c1617b" -dump_attachment:150 "/var/lib/jellyfin/data/attachments/2/28ea0286-b867-a487-dde3-d2eb5d69745e" -dump_attachment:151 "/var/lib/jellyfin/data/attachments/7/7cf335ab-51f8-7d81-1e1a-fb3f5b86f334" -dump_attachment:152 "/var/lib/jellyfin/data/attachments/3/3a4a12ac-a7ae-80fd-2237-ab56e5fe16fa" -dump_attachment:153 "/var/lib/jellyfin/data/attachments/e/e5358618-fec5-18d8-c0b7-1391ec9e0b4a" -dump_attachment:154 "/var/lib/jellyfin/data/attachments/7/736d0428-f1df-58a7-f86e-abaf7ddea08a" -dump_attachment:155 "/var/lib/jellyfin/data/attachments/d/ddb57ecc-262f-8e6c-50d7-714dfa5133ce" -dump_attachment:156 "/var/lib/jellyfin/data/attachments/3/3c50f3fa-4c4e-f12b-42a4-0e56cb4d6542" -dump_attachment:157 "/var/lib/jellyfin/data/attachments/f/f02a7db5-0a06-7e72-7a4c-2ef41c8674ec" -dump_attachment:158 "/var/lib/jellyfin/data/attachments/c/c26f4de8-dfc4-0390-dddb-5ab4d78fd852" -dump_attachment:159 "/var/lib/jellyfin/data/attachments/0/001497be-8013-e31e-cab8-d8bb99ca7bb6" -dump_attachment:160 "/var/lib/jellyfin/data/attachments/6/688aeb9d-310c-70d9-55fe-f7190b777f6a" -dump_attachment:161 "/var/lib/jellyfin/data/attachments/0/08458d41-7bb0-2b23-a1c9-709d2adef127" -dump_attachment:162 "/var/lib/jellyfin/data/attachments/7/72724653-699f-1207-f812-f6d685af8c45" -i "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" -t 0 -f null null'
 -dump_attachment:133 "/var/lib/jellyfin/data/attachments/8/8b4ce490-14ed-61a1-29db-11bc2044e168" -dump_attachment:134 "/var/lib/jellyfin/data/attachments/9/98e955bc-8e4d-9e3f-2256-19983b65e5eb" -dump_attachment:135 "/var/lib/jellyfin/data/attachments/9/96ec00ec-fec6-3f7a-4c24-24d8b2443162" -dump_attachment:136 "/var/lib/jellyfin/data/attachments/0/0e712492-7e63-57d1-969d-e01b63e8432c" -dump_attachment:137 "/var/lib/jellyfin/data/attachments/2/2aa46dce-2f88-8a6f-5b55-0b4ed385fdd2" -dump_attachment:138 "/var/lib/jellyfin/data/attachments/6/6441358b-42d6-9998-59f1-9b443d7520a5" -dump_attachment:139 "/var/lib/jellyfin/data/attachments/9/9521ceee-e4cd-1772-0278-32f77e75b3bf" -dump_attachment:140 "/var/lib/jellyfin/data/attachments/0/089b09c1-a2fc-d9c5-9d28-8f1e83b14ac9" -dump_attachment:141 "/var/lib/jellyfin/data/attachments/7/75734cee-0203-9913-8be9-d5bad445235b" -dump_attachment:142 "/var/lib/jellyfin/data/attachments/3/3fa9ebee-5f82-679d-fecd-bbddd027d8cc" -dump_attachment:143 "/var/lib/jellyfin/data/attachments/8/8dbcf917-bf46-48ad-3b27-5eb3fe36d368" -dump_attachment:144 "/var/lib/jellyfin/data/attachments/b/b9dd7eef-d030-dab6-0605-b52625fcd916" -dump_attachment:145 "/var/lib/jellyfin/data/attachments/c/cf01592b-2126-ce0e-1ea5-cf206a460538" -dump_attachment:146 "/var/lib/jellyfin/data/attachments/2/20d92ee0-941d-9138-a818-d75552e83db7" -dump_attachment:147 "/var/lib/jellyfin/data/attachments/9/98f74534-3fb9-f3d3-9d8e-9158e1269174" -dump_attachment:148 "/var/lib/jellyfin/data/attachments/c/cf18b910-5ff1-ae2a-a0c2-1deb878cebd1" -dump_attachment:149 "/var/lib/jellyfin/data/attachments/4/4aabc0b6-29d4-8e18-eef3-903a71c1617b" -dump_attachment:150 "/var/lib/jellyfin/data/attachments/2/28ea0286-b867-a487-dde3-d2eb5d69745e" -dump_attachment:151 "/var/lib/jellyfin/data/attachments/7/7cf335ab-51f8-7d81-1e1a-fb3f5b86f334" -dump_attachment:152 "/var/lib/jellyfin/data/attachments/3/3a4a12ac-a7ae-80fd-2237-ab56e5fe16fa" -dump_attachment:153 "/var/lib/jellyfin/data/attachments/e/e5358618-fec5-18d8-c0b7-1391ec9e0b4a" -dump_attachment:154 "/var/lib/jellyfin/data/attachments/7/736d0428-f1df-58a7-f86e-abaf7ddea08a" -dump_attachment:155 "/var/lib/jellyfin/data/attachments/d/ddb57ecc-262f-8e6c-50d7-714dfa5133ce" -dump_attachment:156 "/var/lib/jellyfin/data/attachments/3/3c50f3fa-4c4e-f12b-42a4-0e56cb4d6542" -dump_attachment:157 "/var/lib/jellyfin/data/attachments/f/f02a7db5-0a06-7e72-7a4c-2ef41c8674ec" -dump_attachment:158 "/var/lib/jellyfin/data/attachments/c/c26f4de8-dfc4-0390-dddb-5ab4d78fd852" -dump_attachment:159 "/var/lib/jellyfin/data/attachments/0/001497be-8013-e31e-cab8-d8bb99ca7bb6" -dump_attachment:160 "/var/lib/jellyfin/data/attachments/6/688aeb9d-310c-70d9-55fe-f7190b777f6a" -dump_attachment:161 "/var/lib/jellyfin/data/attachments/0/08458d41-7bb0-2b23-a1c9-709d2adef127" -dump_attachment:162 "/var/lib/jellyfin/data/attachments/7/72724653-699f-1207-f812-f6d685af8c45" -i "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" -t 0 -f null null: Invalid argument
```

### Additional information

Extraction will success and video will play if I manually run ffmpeg extraction script with correct arguments while Jellyfin trying run extraction function

This is the command I run: 
```
/usr/lib/jellyfin-ffmpeg/ffmpeg \
-dump_attachment:133 /var/lib/jellyfin/data/attachments/8/8b4ce490-14ed-61a1-29db-11bc2044e168 \
-dump_attachment:134 /var/lib/jellyfin/data/attachments/9/98e955bc-8e4d-9e3f-2256-19983b65e5eb \
-dump_attachment:135 /var/lib/jellyfin/data/attachments/9/96ec00ec-fec6-3f7a-4c24-24d8b2443162 \
-dump_attachment:136 /var/lib/jellyfin/data/attachments/0/0e712492-7e63-57d1-969d-e01b63e8432c \
-dump_attachment:137 /var/lib/jellyfin/data/attachments/2/2aa46dce-2f88-8a6f-5b55-0b4ed385fdd2 \
-dump_attachment:138 /var/lib/jellyfin/data/attachments/6/6441358b-42d6-9998-59f1-9b443d7520a5 \
-dump_attachment:139 /var/lib/jellyfin/data/attachments/9/9521ceee-e4cd-1772-0278-32f77e75b3bf \
-dump_attachment:140 /var/lib/jellyfin/data/attachments/0/089b09c1-a2fc-d9c5-9d28-8f1e83b14ac9 \
-dump_attachment:141 /var/lib/jellyfin/data/attachments/7/75734cee-0203-9913-8be9-d5bad445235b \
-dump_attachment:142 /var/lib/jellyfin/data/attachments/3/3fa9ebee-5f82-679d-fecd-bbddd027d8cc \
-dump_attachment:143 /var/lib/jellyfin/data/attachments/8/8dbcf917-bf46-48ad-3b27-5eb3fe36d368 \
-dump_attachment:144 /var/lib/jellyfin/data/attachments/b/b9dd7eef-d030-dab6-0605-b52625fcd916 \
-dump_attachment:145 /var/lib/jellyfin/data/attachments/c/cf01592b-2126-ce0e-1ea5-cf206a460538 \
-dump_attachment:146 /var/lib/jellyfin/data/attachments/2/20d92ee0-941d-9138-a818-d75552e83db7 \
-dump_attachment:147 /var/lib/jellyfin/data/attachments/9/98f74534-3fb9-f3d3-9d8e-9158e1269174 \
-dump_attachment:148 /var/lib/jellyfin/data/attachments/c/cf18b910-5ff1-ae2a-a0c2-1deb878cebd1 \
-dump_attachment:149 /var/lib/jellyfin/data/attachments/4/4aabc0b6-29d4-8e18-eef3-903a71c1617b \
-dump_attachment:150 /var/lib/jellyfin/data/attachments/2/28ea0286-b867-a487-dde3-d2eb5d69745e \
-dump_attachment:151 /var/lib/jellyfin/data/attachments/7/7cf335ab-51f8-7d81-1e1a-fb3f5b86f334 \
-dump_attachment:152 /var/lib/jellyfin/data/attachments/3/3a4a12ac-a7ae-80fd-2237-ab56e5fe16fa \
-dump_attachment:153 /var/lib/jellyfin/data/attachments/e/e5358618-fec5-18d8-c0b7-1391ec9e0b4a \
-dump_attachment:154 /var/lib/jellyfin/data/attachments/7/736d0428-f1df-58a7-f86e-abaf7ddea08a \
-dump_attachment:155 /var/lib/jellyfin/data/attachments/d/ddb57ecc-262f-8e6c-50d7-714dfa5133ce \
-dump_attachment:156 /var/lib/jellyfin/data/attachments/3/3c50f3fa-4c4e-f12b-42a4-0e56cb4d6542 \
-dump_attachment:157 /var/lib/jellyfin/data/attachments/f/f02a7db5-0a06-7e72-7a4c-2ef41c8674ec \
-dump_attachment:158 /var/lib/jellyfin/data/attachments/c/c26f4de8-dfc4-0390-dddb-5ab4d78fd852 \
-dump_attachment:159 /var/lib/jellyfin/data/attachments/0/001497be-8013-e31e-cab8-d8bb99ca7bb6 \
-dump_attachment:160 /var/lib/jellyfin/data/attachments/6/688aeb9d-310c-70d9-55fe-f7190b777f6a \
-dump_attachment:161 /var/lib/jellyfin/data/attachments/0/08458d41-7bb0-2b23-a1c9-709d2adef127 \
-dump_attachment:162 /var/lib/jellyfin/data/attachments/7/72724653-699f-1207-f812-f6d685af8c45 \
-i "/shared/show/Lucky Star/Season 1/Lucky Star - S01E01 - The Girl Who Dashes Off HDTV-1080p.mkv" \
-t 0 -f null null
```

**Comment by NexiaMoe** [comment]
Let me know if need the mkv file, I can send the file.
