### ISSUE TITLE
Play to DLNA client (Onkyo receiver) broken on 10.3.1

### ISSUE THREAD

**Issue by nonplusnl** [jellyfin/jellyfin#1246]
After upgrading to 10.3.0RC2, DLNA playback to my Onkyo TX-NR515 DNLA client is broken. Jellyfin still sees the DLNA client (available in dropdown selection menu, and profile created on Jellyfin startup), but doesn't play back. This is the error logged:

[2019-04-18 21:27:05.921 +02:00] [ERR] Error ProtocolError getting response from "http://192.168.178.15:8888/upnp_control_2"

With DLNA debugging enabled:

[2019-04-23 20:26:25.959 +02:00] [ERR] Error ProtocolError getting response from "http://192.168.178.15:8888/upnp_control_2"
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

This is 10.3.0RC2/10.3.0/10.3.1 running on Xubuntu 18.04, installed as .deb.

Using 10.2.2, DLNA playback to my Onkyo TX-NR515 worked just fine. Also, downgrading from 10.3.0 back to 10.2.2 restores DLNA playback capability. See e.g. this log entry for succesful playback on 10.2.2:

[2019-04-18 21:51:44.236 +02:00] [INF] HTTP Response 206 to "192.168.178.15". Time: "28""ms". "http://192.168.178.5:8096/audio/c24eadd9-a361-4fe6-38c1-f8d31346896a/stream.mp3?DeviceProfileId=552a11fea596faba9fb948b9566a408d&amp;DeviceId=uuid:72b0cb72-a5cb-72b9-15c2-7209a5b9ac15&amp;MediaSourceId=c24eadd9a3614fe638c1f8d31346896a&amp;Static=true&amp;Tag=1050ecf6a65371dd9da63bca0e6c0ff3&amp;dlnaheaders=true" ""

I am the first to recognise that Onkyo's DLNA implementation is patchy, but it works fine in 10.2.2, but no longer in 10.3, so something must have changed in Jellyfin?

Thanks!

**Comment by agilob** [comment]
Looks related to https://github.com/jellyfin/jellyfin/issues/1078

**Comment by nonplusnl** [comment]
Problem persists in 10.3.0 release version.
I doubt whether it's related to #1078 , as "my" error did not occur in 10.2.2 and also restarting the client does not make a difference

**Comment by nonplusnl** [comment]
Solved by #1464
