### ISSUE TITLE
black screen web interface can't access anything

### ISSUE THREAD

**Issue by aimanzx** [jellyfin/jellyfin#1248]
**Describe the bug**
just black screen when trying to access web interface, i just install it and nothing works!! but when i use the android app it work, but web interface not working 

**To Reproduce**

1. 'unzip the file to c: drive'
2. Click on 'run jellyfin.exe'
3. new page open on the browser and nothing on it just black screen'
4. See black screen

**Expected behavior**

**Logs**
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)  -->

**Screenshots**

![654635163](https://user-images.githubusercontent.com/22063571/56399369-38226b00-6256-11e9-92d2-0f9c3e8203c6.PNG)
![65165163](https://user-images.githubusercontent.com/22063571/56399370-38226b00-6256-11e9-89b7-ce3eaf98b269.PNG)

)-->

**System (please complete the following information):**
 - OS: [Windows 10 64 bit (arabic) ]
 - Browser: [Firefox, microsoft edge]
 - Jellyfin Version: [e.g. (10.3.0-rc2) and (10.3.0-rc1)]
 - Reverse proxy: [?]

**Additional context**
 note! Release 10.2.2 wrok fine but newer Releases not working. -->

**Comment by sparky8251** [comment]
Is this still an issue? We had a lot of fixes roll in after the 10.3.0 update, many of which address issues like the one described.

**Comment by vexersa** [comment]
Late to the party here but I can replicate this issue by attempting to install the Open Subtitles plugin. 

After installation of Open Subtitles through the webUI, access to the webUI becomes unavailable. 

Manually removing the folder for Open Subtitles from the plugin folder resumes webUI functions.

**Comment by JustAMan** [comment]
@vexersa This sounds like a completely separate issue, please submit a new one following our issue template.

**Comment by vexersa** [comment]
@JustAMan 
Will do.
