### ISSUE TITLE
Jellyfin web interface not able to connect to server

### ISSUE THREAD

**Issue by lilGyros** [jellyfin/jellyfin#12484]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I installed a fresh Ubuntu 24.04 LTS server, because I had the same problem on 22.04 LTS.

The web-interface does load up and when I click on connect to server it gives me an error that it was not possible.

Running `jellyfin` in the terminal gives me an error saying, that the address / port is already in use.
`sudo lsof -i:8096` gives me the following:
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME

jellyfin 901 jellyfin 466u IPv4 9044 0t0 TCP *:8096 (LISTEN) 

any help appreciated!
thank you (:

### Reproduction steps

1. Install Ubuntu Server 24.04 LTS
2. UFW allow 22 and 8096
3. ssh into the server
4. curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
5. curl -sSL https://install.pi-hole.net | bash
6. ufw allow 80/tcp
ufw allow 53/tcp
ufw allow 53/udp
ufw allow 67/tcp
ufw allow 67/udp
7. connect to server IP - for me it is 192.168.1.24:8096
8. click on connect to server
9. see nothing
10. run `jellyfin` in the terminal
11. error message saying that the webserver directory is non-existent / empty
12. ln -s /usr/share/jellyfin/web/ /usr/lib/jellyfin/bin/jellyfin-web in order to create that directory

thats how I got the webpage to work, but I still cannot connect to the server I get an error message

I cannot find network.xml anywhere to change the port - I read somewhere that the file only exists after the initial setup, i dont know anything about that

### What is the current _bug_ behavior?

Not able to connect to web-server

### What is the expected _correct_ behavior?

being able to connect to the web-server

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Ubuntu Server 24.04 LTS and before that 22.04 LTS (also didn't work)
- Linux Kernel: 6.8.0-40-generic
- Virtualization: none - running on a server
- Clients: any
- Browser: Firefox (ofc lol)
- FFmpeg Version: n/a (idk how to find that out, the newest one I suppose, I installed on 20.08.2024)
- Playback Method: not working
- Hardware Acceleration:
- GPU Model: none / Intel HD Graphics 530
- CPU Model: Intel i5-6500
- 32GB DDR4 Memory (4 slots)
- Plugins: none
- Reverse Proxy: none
- Base URL: none / 192.168.1.24
- Networking: via LAN to router and router to PC which uses SSH
- Storage: local (on server)
```

### Jellyfin logs

```shell
not able to log into dashboard
```

**Comment by mi-ty** [comment]
```
at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[20:17:30] [INF] [1] Main: Jellyfin version: 10.9.9
[20:17:30] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CACHE_DIR, /config/cache]"]
[20:17:30] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[20:17:30] [INF] [1] Main: Operating system: Ubuntu 24.04 LTS
[20:17:30] [INF] [1] Main: Architecture: X64
[20:17:30] [INF] [1] Main: 64-Bit Process: True
[20:17:30] [INF] [1] Main: User Interactive: True
[20:17:30] [INF] [1] Main: Processor count: 4
[20:17:30] [INF] [1] Main: Program data path: /config/data
[20:17:30] [INF] [1] Main: Log directory path: /config/log
[20:17:30] [INF] [1] Main: Config directory path: /config
[20:17:30] [INF] [1] Main: Cache path: /config/cache
[20:17:30] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[20:17:30] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[20:17:30] [FTL] [1] Main: Unhandled Exception
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
```

Same issue after watchtower pulled the new version

**Comment by KevGamesUltimate** [comment]
" 7. connect to server IP - for me it is 192.168.1.24:8096
  8. click on connect to server
  9. see nothing "

Are you able to open the setup-wizzard manually? http://192.168.1.24:8096/web/index.html#!/wizardstart.html

**Comment by OnlyC0RE** [comment]
I also have the same error. But it happened to me twice already and it worked before that. usually in the middle of a playback of a big file. it starts this error and will not recover

**Comment by mi-ty** [comment]
The issue stemmed from the storage drive reaching capacity in my case. Perhaps the issue is the same for you, with transcodes filling the drive.

**Comment by felix920506** [comment]
Sorry but this is most likely something broken with your setup instead of an actual Jellyfin issue.
Please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact

**Comment by OnlyC0RE** [comment]
> Sorry but this is most likely something broken with your setup instead of an actual Jellyfin issue. Please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact

Seems like a Jellyfin issue if it fills up the main disk to the point it corrupts a database and stops working until full reset.

I have used Plex for years and this was never an issue. What is the difference between Plex an Jellyfin in handeling transcode cache?
