### ISSUE TITLE
Library not updated if the folder is empty

### ISSUE THREAD

**Issue by jerem2772** [jellyfin/jellyfin#12494]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I set up 2 libraries, one "Films" for all users and a second one "Films TMP" just for me.  I use this second one as a temporary folder to scrap and check all informations of the movies (Images, logo, trailer etc...) before moved them to "Films" library.

After upgrading to version 10.9.X when I move the movies from TMP folder "Films TMP" to final folder "Films" and update both libraries. The movies in "Films TMP" library aren't deleted.

### Reproduction steps

- Create a library 
- Add at least one movie
- Move or delete all files in library folder (the folder must be empty)
- Update the library

The movie are always present in the library.

![Capture d'écran 2024-08-21 165911](https://github.com/user-attachments/assets/8a75131d-c2c9-4a55-b419-9e4264ae57b9)

But if I add 1 file in a library's folder (New Text Document.txt) and I update the library, missing movies are deleted

### What is the current _bug_ behavior?

Movies aren't removed from the library if the folder is empty

### What is the expected _correct_ behavior?

That movies are removed from the library even if the folder is empty

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
My main server :

- OS: Ubuntu 20.04.6 LTS
- Virtualization: LXC

Just for testing, I setup a new VM with a fresh installation and I've also tried directly on my computer (windows 11) -> Same issues
```

### Jellyfin logs

```shell
*******************************************************************************************
*********                                                                         *********
*********         Movie added into the library folder and library updated         *********
*********                                                                         *********
*******************************************************************************************


[2024-08-21 15:33:25.083 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:33:55.082 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:34:25.082 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:34:53.873 +00:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-21 15:34:55.083 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:35:25.082 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:35:55.081 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:36:17.736 +00:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/Films_TMP/Grease (1978)/Grease (1978).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-08-21 15:36:17.760 +00:00] [ERR] Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-08-21 15:36:23.070 +00:00] [INF] Started library sync
[2024-08-21 15:36:23.163 +00:00] [INF] The movies "Grease, Grease" is/are already in their proper box set, "Grease - Saga"
[2024-08-21 15:36:23.263 +00:00] [INF] Library Sync: Added 1 items
[2024-08-21 15:36:23.263 +00:00] [INF] Finished library sync, taking "00:00:00.1931766"


*******************************************************************************************
*********                                                                         *********
*********       Delete the movie from the library folder and library updated      *********
*********                                                                         *********
*******************************************************************************************


[2024-08-21 15:36:25.081 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:36:55.081 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-08-21 15:37:18.270 +00:00] [INF] Creating image collage and saving to "/var/cache/jellyfin/temp/7fa1a1579ba946ce8bafd59c8283241a.png"
[2024-08-21 15:37:18.272 +00:00] [ERR] Error in "Dynamic Image Provider"
System.IO.FileNotFoundException: File not found
File name: '/mnt/Films_TMP/Grease (1978)/backdrop.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, Nullable`1 orientation, SKEncodedOrigin& origin)
   at Jellyfin.Drawing.Skia.SkiaHelper.GetNextValidImage(SkiaEncoder skiaEncoder, IReadOnlyList`1 paths, Int32 currentIndex, Int32& newIndex)
   at Jellyfin.Drawing.Skia.StripCollageBuilder.BuildThumbCollageBitmap(IReadOnlyList`1 paths, Int32 width, Int32 height, String libraryName)
   at Jellyfin.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(IReadOnlyList`1 paths, String outputPath, Int32 width, Int32 height, String libraryName)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateImageCollage(ImageCollageOptions options, String libraryName)
   at Jellyfin.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, String libraryName)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateCollage(BaseItem primaryItem, IEnumerable`1 items, String outputPath, Int32 width, Int32 height)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateThumbCollage(BaseItem primaryItem, IEnumerable`1 items, String outputPath, Int32 width, Int32 height)
   at Emby.Server.Implementations.Images.CollectionFolderImageProvider.CreateImage(BaseItem item, IReadOnlyCollection`1 itemsWithImages, String outputPathWithoutExtension, ImageType imageType, Int32 imageIndex)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, IReadOnlyList`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-08-21 15:37:18.273 +00:00] [WRN] Library folder "/mnt/Films_TMP" is inaccessible or empty, skipping
[2024-08-21 15:37:25.081 +00:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds


*******************************************************************************************
*********                                                                         *********
*********       One file added into the library folder and library updated        *********
*********                                                                         *********
*******************************************************************************************


[2024-08-21 15:37:39.457 +00:00] [INF] Creating image collage and saving to "/var/cache/jellyfin/temp/e6094f7a79264b008fafcb07e97fabd4.png"
[2024-08-21 15:37:39.458 +00:00] [ERR] Error in "Dynamic Image Provider"
System.IO.FileNotFoundException: File not found
File name: '/mnt/Films_TMP/Grease (1978)/backdrop.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, Nullable`1 orientation, SKEncodedOrigin& origin)
   at Jellyfin.Drawing.Skia.SkiaHelper.GetNextValidImage(SkiaEncoder skiaEncoder, IReadOnlyList`1 paths, Int32 currentIndex, Int32& newIndex)
   at Jellyfin.Drawing.Skia.StripCollageBuilder.BuildThumbCollageBitmap(IReadOnlyList`1 paths, Int32 width, Int32 height, String libraryName)
   at Jellyfin.Drawing.Skia.StripCollageBuilder.BuildThumbCollage(IReadOnlyList`1 paths, String outputPath, Int32 width, Int32 height, String libraryName)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateImageCollage(ImageCollageOptions options, String libraryName)
   at Jellyfin.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options, String libraryName)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateCollage(BaseItem primaryItem, IEnumerable`1 items, String outputPath, Int32 width, Int32 height)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateThumbCollage(BaseItem primaryItem, IEnumerable`1 items, String outputPath, Int32 width, Int32 height)
   at Emby.Server.Implementations.Images.CollectionFolderImageProvider.CreateImage(BaseItem item, IReadOnlyCollection`1 itemsWithImages, String outputPathWithoutExtension, ImageType imageType, Int32 imageIndex)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, IReadOnlyList`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-08-21 15:37:39.460 +00:00] [INF] Removing item, Type: "Movie", Name: "Grease", Path: "/mnt/Films_TMP/Grease (1978)/Grease (1978).mkv", Id: d1b19445-19ab-e5a5-0696-66cc60170903
[2024-08-21 15:37:44.498 +00:00] [INF] Started library sync
[2024-08-21 15:37:44.698 +00:00] [INF] Library Sync: Removed 1 items
[2024-08-21 15:37:44.698 +00:00] [INF] Finished library sync, taking "00:00:00.1999783"
```

**Comment by jerem2772** [comment]
Same with version 10.9.10

**Comment by crobibero** [comment]
This is intentional as we have had issues with libraries getting wiped if a folder mount fails.
