### ISSUE TITLE
10.3.0 crashes constantly,  Unhandled Exception

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#1256]
Hi

I just upgraded JF and it fails to start on Debian Buster X64, I am usingn the official repo.

Bear in mind that the previous version was working perfectly.

```

- Unit jellyfin.service has finished starting up.                                                                                                                                           
--                                                                                                                                                                                           
-- The start-up result is RESULT.                                                                                                                                                            
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Jellyfin version: 10.3.0.0
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ff
mpeg", ""]                                                                                                                                                                                   
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Operating system: Linux 4.19.0.4
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Architecture: X64                                                                                                                   
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] 64-Bit Process: True                                                                                                                
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] User Interactive: True                                                                                                              
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Processor count: 8                                                                                                                  
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Program data path: /var/lib/jellyfin                                                                                                
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web/src                                                                          
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Application directory: /usr/lib/jellyfin/bin/                                                                                       
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Setting cache path to /media/SYSTEMP/TMP/EMBY_CACHE                                                                                 
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Loading assemblies
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Loading assembly /var/lib/jellyfin/plugins/MusicBrainz.dll                                                                          
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [INF] Disposing CoreAppHost                                                                                                               
Apr 20 00:45:14 MYPC jellyfin[305]: [00:45:14] [FTL] Unhandled Exception
Apr 20 00:45:14 MYPC jellyfin[305]: System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IHasThumbImage' from assembly 'MediaBrowser.Common, Version=10.3.0.0, Cult$
re=neutral, PublicKeyToken=null'.
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)                                     
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()                                                                                           
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()                                                                           
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()                                                                                     
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)                                                                                  
Apr 20 00:45:14 MYPC jellyfin[305]:    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()                                                                                    
Apr 20 00:45:14 MYPC jellyfin[305]:    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)                                                    
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)                                                                                       
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.Main(String[] args)
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.<Main>(String[] args)
Apr 20 00:45:14 MYPC jellyfin[305]: Unhandled Exception: System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IHasThumbImage' from assembly 'MediaBrowser.Common, V$
rsion=10.3.0.0, Culture=neutral, PublicKeyToken=null'.
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)                                     
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()                                                                                           
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()                                                                           
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()                                                                                     
Apr 20 00:45:14 MYPC jellyfin[305]:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)                                                                                  
Apr 20 00:45:14 MYPC jellyfin[305]:    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()                                                                                    
Apr 20 00:45:14 MYPC jellyfin[305]:    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)                                                    
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)                                                                                       
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.Main(String[] args)
Apr 20 00:45:14 MYPC jellyfin[305]:    at Jellyfin.Server.Program.<Main>(String[] args)
Apr 20 00:45:14 MYPC systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT                                                                                       
Apr 20 00:45:14 MYPC systemd[1]: jellyfin.service: Failed with result 'signal'.
Apr 20 00:45:14 MYPC systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
Apr 20 00:45:14 MYPC systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support


```

**Comment by cvium** [comment]
It looks like you have some emby plugins installed which are not compatible with jellyfin

**Comment by gerroon** [comment]
Ok thanks, I did not know that I had those, I emptied the plugins folder and it seems tos atrt now.

**Comment by cvium** [comment]
I think the crash is caused by the DI changes in 10.3.

cc @Bond-009

**Comment by joshuaboniface** [comment]
I said it earlier on Matrix, but I'd much rather us gracefully handle these sort of Plugin failures, so at least the rest of the app can keep going and the plugin somehow report "failed". Would be a nice usability improvement!
