### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by ACR-Jeff** [jellyfin/jellyfin#12595]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to 10.9.10 No client is able to connect, 
From Jellyfin web 
![Screenshot from 2024-09-05 14-21-37](https://github.com/user-attachments/assets/0f1daa1c-9865-4be1-ba87-11a165bbd210)

From AndroidTV. I just get an `Unable to connect to server` next to the sign in button

### Reproduction steps

1. Update server to 10.9.10
2. Restart server
3. Try logging into Jellyfin-web or Jellyfin-androidtv

### What is the current _bug_ behavior?

While executing Jellyfin via Terminal:
$ jellyfin
[14:32:53] [INF] [1] Main: Jellyfin version: 10.9.10
[14:32:53] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/acr-server/.local/share/jellyfin/log]"]
[14:32:53] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[14:32:53] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[14:32:53] [INF] [1] Main: Architecture: X64
[14:32:53] [INF] [1] Main: 64-Bit Process: True
[14:32:53] [INF] [1] Main: User Interactive: True
[14:32:53] [INF] [1] Main: Processor count: 4
[14:32:53] [INF] [1] Main: Program data path: /home/acr-server/.local/share/jellyfin
[14:32:53] [INF] [1] Main: Log directory path: /home/acr-server/.local/share/jellyfin/log
[14:32:53] [INF] [1] Main: Config directory path: /home/acr-server/.config/jellyfin
[14:32:53] [INF] [1] Main: Cache path: /home/acr-server/.cache/jellyfin
[14:32:53] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[14:32:53] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[14:32:53] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings

I noticed it states `Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web` But there is no jellyfin-web in that directory on Debian 12

### What is the expected _correct_ behavior?

Login to server with admin or user and use Jellyfin

### Jellyfin Server version

10.9.10+

### Specify unstable release number

10.9.10+deb12

### Specify version number

10.9.10+deb12

### Specify the build version

10.9.10+deb12

### Environment

```markdown
- OS: Server: Debian GNU/Linux 12 (bookworm)
- Linux Kernel: 6.1.0-25-amd64
- Virtualization: none
- Clients: Nvidia Shield Android TV version 9 8.2.3
- Browser: Librewolf, Brave, Floorp, Firefox
- FFmpeg Version: 5.1.6-0+deb12u1, Jellyfin-ffmpeg6 6.0.1-8-bookworm
- Playback Method: Transcode
- Hardware Acceleration: none
- GPU Model: AMD ATI Radeon RX 580
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: ethernet
- Storage: Seagate ironwolf Pro 4TB x2
```

### Jellyfin logs

```shell
Odd I went to retrieve the logs and there is nothing newer than 10.7.7 version dated back to 2022-07-03
```

### FFmpeg logs

```shell
Can't login to provide logs
```

### Client / Browser logs

![Screenshot from 2024-09-05 15-28-45](https://github.com/user-attachments/assets/70898a96-cfb4-4cd5-ab9e-60cbe3d35833)
![Screenshot from 2024-09-05 15-30-59](https://github.com/user-attachments/assets/74232566-607f-41c4-9c4f-b685c6f9246c)

### Installation Method 

sudo apt install jellyfin

**Comment by felix920506** [comment]
How did you install Jellyfin?

**Comment by ACR-Jeff** [comment]
> How did you install Jellyfin?

`sudo apt install jellyfin`

**Comment by gnattu** [comment]
It means nothing if you don't give valid cli parameters when you execute it directly in the shell.

You first do `sudo systemctl restart jellyfin`

Then you wait for a few seconds to let the server restart, then do:

```
sudo journalctl -u jellyfin --since "$(systemctl show -p ExecMainStartTimestamp jellyfin | awk -F'=' '{print $2}')"
```

What will the out put be?

**Comment by ACR-Jeff** [comment]
> It means nothing if you don't give valid cli parameters when you execute it directly in the shell.
> 
> You first do `sudo systemctl restart jellyfin`
> 
> Then you wait for a few seconds to let the server restart, then do:
> 
> ```
> sudo journalctl -u jellyfin --since "$(systemctl show -p ExecMainStartTimestamp jellyfin | awk -F'=' '{print $2}')"
> ```
> 
> What will the out put be?

Oh ok, I am new to all of this troubleshooting Jellyfin.
[logs.log](https://github.com/user-attachments/files/16901337/logs.log)

**Comment by gnattu** [comment]
> Sep 05 17:15:36 ACR-Server jellyfin[2833]: System.UnauthorizedAccessException: Access to the path '/mnt>
Sep 05 17:15:36 ACR-Server jellyfin[2833]:  ---> System.IO.IOException: Permission denied
Sep 05 17:15:36 ACR-Server jellyfin[2833]:    --- End of inner exception stack trace ---
Sep 05 17:15:36 ACR-Server jellyfin[2833]: [17:15:36] [INF] Stopping directory watching for path /mnt/F>
Sep 05 17:15:36 ACR-Server jellyfin[2833]: [17:15:36] [ERR] Error in Directory watcher for: /mnt/MomDads
Sep 05 17:15:36 ACR-Server jellyfin[2833]: System.UnauthorizedAccessException: Access to the path '/mnt>
Sep 05 17:15:36 ACR-Server jellyfin[2833]:  ---> System.IO.IOException: Permission denied
Sep 05 17:15:36 ACR-Server jellyfin[2833]:    --- End of inner exception stack trace ---

Jellyfin does not have permission to access you mount point

**Comment by gnattu** [comment]
But this should not cause your problem. Can you try clear your browser cache and try again?

**Comment by ACR-Jeff** [comment]
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]: System.UnauthorizedAccessException: Access to the path '/mnt>
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]:  ---> System.IO.IOException: Permission denied
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]:    --- End of inner exception stack trace ---
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]: [17:15:36] [INF] Stopping directory watching for path /mnt/F>
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]: [17:15:36] [ERR] Error in Directory watcher for: /mnt/MomDads
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]: System.UnauthorizedAccessException: Access to the path '/mnt>
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]:  ---> System.IO.IOException: Permission denied
> > Sep 05 17:15:36 ACR-Server jellyfin[2833]:    --- End of inner exception stack trace ---
> 
> Jellyfin does not have permission to access your mount point

That's odd considering it had no problem in previous versions of Jellyfin with accessing my mount points, I checked permissions on my storage drives and everything appears normal as it always has, 

I have cleared my browser cache and data, Restarted my system to make sure everything closed properly, 
Restart my browser, Tried logging in Jellyfin-web with `http://192.168.1.177:8096`
Now after accessing it redirects to `http://192.168.1.177:8096/web/index.html#!/selectserver.html`, I choose the server it's found and click connect, Shows me the popup screen shot that I have posted above with `We're unable to connect`
I've tried to delete the server provided and add it again, Same.

I've even uninstalled the app on my Nvidia Shield, Cleared cache and left over data with sd maid
Reinstalled the Jellyfin-Androidtv app
Same happens every time.

**Comment by gnattu** [comment]
So that's probably something blocking the server from startup and prepare it but from the log it can only be the mount point?

Can you backup current data folder and try to start as a clean install to see if it works?

**Comment by jtgtifh** [comment]
I have encountered the same problem and the solution is for your reference. I am using windows system. First delete jellyfin.db, jellyfin.db-shm, jellyfin.db-wal in the data directory. Then backup the whole data（config directory、date directory、metadata directory ....etc.）. Then Reinstall jellyfin. Then restore the backed up data.

**Comment by jtgtifh** [comment]
I have encountered the same problem and the solution is for your reference.
 I am using windows system. 
 1、First delete jellyfin.db, jellyfin.db-shm, jellyfin.db-wal in data directory. 
2、 Then backup all the jellyfindata（data、config、metedata etc.）. 
3、Reinstall jellyfin. 
4、Restore the backed up data.
5、Re-create Admin account.
Connect Success!

**Comment by ACR-Jeff** [comment]
> I have encountered the same problem and the solution is for your reference. I am using windows system. 1、First delete jellyfin.db, jellyfin.db-shm, jellyfin.db-wal in data directory. 2、 Then backup all the jellyfindata（data、config、metedata etc.）. 3、Reinstall jellyfin. 4、Restore the backed up data. 5、Re-create Admin account. Connect Success!

Thank you, I will be sure to try this asap.

**Comment by amaccuish** [comment]
I have the same issue, Jellyfin is not listening on any port. Jellyfin version: 10.9.11

`<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <BaseUrl />
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <CertificatePath />
  <CertificatePassword />
  <InternalHttpPort>8096</InternalHttpPort>
  <InternalHttpsPort>8920</InternalHttpsPort>
  <PublicHttpPort>8096</PublicHttpPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <AutoDiscovery>true</AutoDiscovery>
  <EnableUPnP>false</EnableUPnP>
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>true</EnableIPv6>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <LocalNetworkSubnets />
  <LocalNetworkAddresses />
  <KnownProxies>
    <string>172.16.32.55</string>
    <string>127.0.0.1</string>
  </KnownProxies>
  <IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>
    <string>veth</string>
  </VirtualInterfaceNames>
  <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
  <PublishedServerUriBySubnet />
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>true</IsRemoteIPFilterBlacklist>
</NetworkConfiguration>
`

**Comment by amaccuish** [comment]
I see after writing this that jellyfin is only binding to ipv6. This is new =D.

**Comment by K0-RR** [comment]
I also have this issue. Fresh install of jellyfin from the `install-debuntu.sh`.
After typing `jellyfin` into the terminal emulator:
```
[13:42:59] [INF] [1] Main: Jellyfin version: 10.9.11
[13:42:59] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/nacia/.local/share/jellyfin/log]"]
[13:42:59] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[13:42:59] [INF] [1] Main: Operating system: Zorin OS 17.2
[13:42:59] [INF] [1] Main: Architecture: X64
[13:42:59] [INF] [1] Main: 64-Bit Process: True
[13:42:59] [INF] [1] Main: User Interactive: True
[13:42:59] [INF] [1] Main: Processor count: 16
[13:42:59] [INF] [1] Main: Program data path: /home/nacia/.local/share/jellyfin
[13:42:59] [INF] [1] Main: Log directory path: /home/nacia/.local/share/jellyfin/log
[13:42:59] [INF] [1] Main: Config directory path: /home/nacia/.config/jellyfin
[13:42:59] [INF] [1] Main: Cache path: /home/nacia/.cache/jellyfin
[13:42:59] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[13:42:59] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[13:42:59] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings
```

**Comment by K0-RR** [comment]
I also have this issue. Fresh install of jellyfin from the `install-debuntu.sh`.
After typing `jellyfin` into the terminal emulator:
```
[13:42:59] [INF] [1] Main: Jellyfin version: 10.9.11
[13:42:59] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/nacia/.local/share/jellyfin/log]"]
[13:42:59] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[13:42:59] [INF] [1] Main: Operating system: Zorin OS 17.2
[13:42:59] [INF] [1] Main: Architecture: X64
[13:42:59] [INF] [1] Main: 64-Bit Process: True
[13:42:59] [INF] [1] Main: User Interactive: True
[13:42:59] [INF] [1] Main: Processor count: 16
[13:42:59] [INF] [1] Main: Program data path: /home/nacia/.local/share/jellyfin
[13:42:59] [INF] [1] Main: Log directory path: /home/nacia/.local/share/jellyfin/log
[13:42:59] [INF] [1] Main: Config directory path: /home/nacia/.config/jellyfin
[13:42:59] [INF] [1] Main: Cache path: /home/nacia/.cache/jellyfin
[13:42:59] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[13:42:59] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[13:42:59] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings
```

Looks like the server is expecting the web client in wrong location. After doing `sudo cp /usr/share/jellyfin/web /usr/lib/jellyfin/bin/jellyfin-web` it seems to work but then crashes:
```
[13:53:28] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration", "MigrateMusicBrainzTimeout", "MigrateNetworkConfiguration"]
[13:53:28] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/nacia/.cache/jellyfin
[13:53:28] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.0.14"]
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[13:53:28] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[13:53:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.11.0
[13:53:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.11.0
[13:53:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.11.0
[13:53:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.11.0
[13:53:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.11.0
[13:53:29] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase", "FixPlaylistOwner", "MigrateRatingLevels", "FixAudioData"]
[13:53:29] [INF] [1] Main: Kestrel is listening on 0.0.0.0
[13:53:29] [ERR] [1] Jellyfin.Networking.AutoDiscoveryHost: Unable to bind to 0.0.0.0:7359
System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Jellyfin.Networking.AutoDiscoveryHost.ListenForAutoDiscoveryMessage(IPAddress listenAddress, CancellationToken cancellationToken)
[13:53:29] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: /home/nacia/wwwroot. Static files may be unavailable.
[13:53:29] [ERR] [1] Microsoft.Extensions.Hosting.Internal.Host: Hosting failed to start
System.IO.IOException: Failed to bind to address http://0.0.0.0:8096: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[13:53:29] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[13:53:29] [FTL] [1] Main: Error while starting server
System.IO.IOException: Failed to bind to address http://0.0.0.0:8096: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[13:53:29] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[13:53:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[13:53:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[13:53:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[13:53:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

**Comment by K0-RR** [comment]
https://github.com/jellyfin/jellyfin/issues/8383

**Comment by ACR-Jeff** [comment]
> Looks like the server is expecting the web client in wrong location. After doing `sudo cp /usr/share/jellyfin/web /usr/lib/jellyfin/bin/jellyfin-web` it seems to work but then crashes:
> 

From what I understand from that is it's supposed to be symlinked, Yet I am not understanding yet if it's supposed to be the web directory symlinked or the contents of the web directory, I will have to dig into this and test some more. 
Thanks, Hope I can figure this out, I have been pulling my hair out or what's left of it out over this.

**Comment by ACR-Jeff** [comment]
Ok I figured the symlink out `sudo ln -s /usr/share/jellyfin/web /usr/lib/jellyfin/bin/jellyfin-web`
Yet still facing the exact same issue

**Comment by ACR-Jeff** [comment]
Ok so I was finely able to login after the symlink with my admin account, The issue seems to now be the fact it doesn't except public ip's, I was only able to login from the server itself via jellyfin-web 127.0.0.1:8096

**Comment by ACR-Jeff** [comment]
Well I discovered an issue with LAN Networks, Any of the networks without /24 at the end will be null and void and excluded to /32 via the logs below?
![LAN-Networks](https://github.com/user-attachments/assets/31168c2d-411d-4521-a796-d8f502b8a164)

[2024-10-07 15:19:32.994 -07:00] [INF] Defined LAN subnets: ["127.0.0.1/24", "192.168.1.0/24", "192.168.1.1/24", "192.168.1.177/32", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.169/24", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/24"]
[2024-10-07 15:19:32.995 -07:00] [INF] Defined LAN exclusions: ["192.168.1.177/32", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32"]
[2024-10-07 15:19:32.995 -07:00] [INF] Used LAN subnets: ["127.0.0.1/24", "192.168.1.0/24", "192.168.1.1/24", "192.168.1.177/32", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.169/24", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/24"]
[2024-10-07 15:19:32.995 -07:00] [INF] Filtered interface addresses: ["127.0.0.1", "192.168.1.177"]
[2024-10-07 15:19:32.995 -07:00] [INF] Bind Addresses ["0.0.0.0"]
[2024-10-07 15:19:32.995 -07:00] [INF] Remote IP filter is "Allowlist"
[2024-10-07 15:19:32.995 -07:00] [INF] Filtered subnets: []
[2024-10-07 15:20:35.040 -07:00] [INF] Authentication request for "Media-Server" has succeeded.
[2024-10-07 15:20:35.040 -07:00] [INF] Current/Max sessions for user "Media-Server": 0/0
[2024-10-07 15:20:35.040 -07:00] [INF] Creating new access token for user 66d78bab-bf38-41c3-b5e4-264044c5508a
[2024-10-07 15:20:35.103 -07:00] [INF] WS "192.168.1.144" request
[2024-10-07 15:21:45.201 -07:00] [INF] WS "192.168.1.169" request
[2024-10-07 15:22:11.291 -07:00] [INF] Defined LAN subnets: ["127.0.0.1/24", "192.168.1.0/24", "192.168.1.1/24", "192.168.1.177/24", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.169/24", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/32"]
[2024-10-07 15:22:11.291 -07:00] [INF] Defined LAN exclusions: ["192.168.1.2/32", "192.168.1.22/32", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/32"]
[2024-10-07 15:22:11.291 -07:00] [INF] Used LAN subnets: ["127.0.0.1/24", "192.168.1.0/24", "192.168.1.1/24", "192.168.1.177/24", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.169/24", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/32"]
[2024-10-07 15:22:11.291 -07:00] [INF] Filtered interface addresses: ["127.0.0.1", "192.168.1.177"]
[2024-10-07 15:22:11.291 -07:00] [INF] Bind Addresses ["0.0.0.0"]
[2024-10-07 15:22:11.291 -07:00] [INF] Remote IP filter is "Allowlist"
[2024-10-07 15:22:11.291 -07:00] [INF] Filtered subnets: []
[2024-10-07 15:22:19.634 -07:00] [WRN] WS "192.168.1.144" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-10-07 15:22:19.639 -07:00] [INF] WS "192.168.1.144" closed
[2024-10-07 15:23:04.198 -07:00] [INF] WS "192.168.1.169" closed

**Comment by ACR-Jeff** [comment]
Everyone of these local LAN addresses are in my LAN Network in Jellyfin to allow access to the server, If I do not give them the /24 Subnet they are pushed into the exclusion list, In previous versions of Jellyfin this wasn't the case.
[2024-10-07 15:22:11.291 -07:00] [INF] Defined LAN exclusions: ["192.168.1.2/32", "192.168.1.22/32", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/32"]
[2024-10-07 15:22:11.291 -07:00] [INF] Used LAN subnets: ["127.0.0.1/24", "192.168.1.0/24", "192.168.1.1/24", "192.168.1.177/24", "192.168.1.2/32", "192.168.1.22/32", "192.168.1.169/24", "192.168.1.12/32", "192.168.1.143/32", "192.168.1.225/32", "192.168.1.144/32"]
