### ISSUE TITLE
Persistent crashing/corruption

### ISSUE THREAD

**Issue by shandshellin** [jellyfin/jellyfin#12645]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After scanning in some libraries then checking the libraries themselves, jellyfin will crash and get stuck in an eternal boot loop with very little info in the log. Only option is to rebuild it.....again.

### Reproduction steps

1. fresh install
2. basic setup with all tasks disabled and no realtime monitoring or transcoding, set paralell processes to 1
3. add libraries one by one
4. logs shows complete, login to verify contents of library folders
5. webui hangs then docker container reboots endlessly
6. tried the last few new versions and the behavior is the same, 10.8.13 works flawlessly

### What is the current _bug_ behavior?

crashing and breaking itself for no apparent reason

### What is the expected _correct_ behavior?

it should probably just work without breaking itself

### Jellyfin Server version

10.9.11+

### Specify unstable release number

2024090905-arm64

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Bullseye
- Linux Kernel: 6.1.21-v8+
- Virtualization: Docker
- Clients: n/a
- Browser: firefox/chrome
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration:
- GPU Model: n/a
- Plugins: default
- Reverse Proxy: n/a
- Base URL:
- Networking: basiclan
- Storage: nfs share
```

### Jellyfin logs

```shell
[2024-09-14 08:00:27.725 -06:00] [INF] [1] Main: Jellyfin version: "10.10.0"
[2024-09-14 08:00:27.751 -06:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]"]
[2024-09-14 08:00:27.760 -06:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2024-09-14 08:00:27.770 -06:00] [INF] [1] Main: Operating system: "Debian GNU/Linux 12 (bookworm)"
[2024-09-14 08:00:27.771 -06:00] [INF] [1] Main: Architecture: Arm64
[2024-09-14 08:00:27.773 -06:00] [INF] [1] Main: 64-Bit Process: True
[2024-09-14 08:00:27.774 -06:00] [INF] [1] Main: User Interactive: True
[2024-09-14 08:00:27.774 -06:00] [INF] [1] Main: Processor count: 3
[2024-09-14 08:00:27.774 -06:00] [INF] [1] Main: Program data path: "/config"
[2024-09-14 08:00:27.775 -06:00] [INF] [1] Main: Log directory path: "/config/log"
[2024-09-14 08:00:27.775 -06:00] [INF] [1] Main: Config directory path: "/config/config"
[2024-09-14 08:00:27.775 -06:00] [INF] [1] Main: Cache path: "/cache"
[2024-09-14 08:00:27.776 -06:00] [INF] [1] Main: Temp directory path: "/tmp/jellyfin"
[2024-09-14 08:00:27.777 -06:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2024-09-14 08:00:27.778 -06:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2024-09-14 08:00:28.370 -06:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-09-14 08:00:28.545 -06:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-09-14 08:00:28.862 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-14 08:00:28.863 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-09-14 08:00:28.866 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-14 08:00:28.870 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "10.0.0.112", "172.18.0.4"]
[2024-09-14 08:00:28.872 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-09-14 08:00:28.873 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-09-14 08:00:28.873 -06:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-09-14 08:00:32.790 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("84"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT COUNT(*) FROM \"sqlite_master\" WHERE \"name\" = '__EFMigrationsHistory' AND \"type\" = 'table';"
[2024-09-14 08:00:32.856 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("6"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT \"MigrationId\", \"ProductVersion\"
FROM \"__EFMigrationsHistory\"
ORDER BY \"MigrationId\";"
[2024-09-14 08:01:42.757 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("6"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT \"u\".\"Id\", \"u\".\"AudioLanguagePreference\", \"u\".\"AuthenticationProviderId\", \"u\".\"CastReceiverId\", \"u\".\"DisplayCollectionsView\", \"u\".\"DisplayMissingEpisodes\", \"u\".\"EnableAutoLogin\", \"u\".\"EnableLocalPassword\", \"u\".\"EnableNextEpisodeAutoPlay\", \"u\".\"EnableUserPreferenceAccess\", \"u\".\"HidePlayedInLatest\", \"u\".\"InternalId\", \"u\".\"InvalidLoginAttemptCount\", \"u\".\"LastActivityDate\", \"u\".\"LastLoginDate\", \"u\".\"LoginAttemptsBeforeLockout\", \"u\".\"MaxActiveSessions\", \"u\".\"MaxParentalAgeRating\", \"u\".\"MustUpdatePassword\", \"u\".\"Password\", \"u\".\"PasswordResetProviderId\", \"u\".\"PlayDefaultAudioTrack\", \"u\".\"RememberAudioSelections\", \"u\".\"RememberSubtitleSelections\", \"u\".\"RemoteClientBitrateLimit\", \"u\".\"RowVersion\", \"u\".\"SubtitleLanguagePreference\", \"u\".\"SubtitleMode\", \"u\".\"SyncPlayAccess\", \"u\".\"Username\", \"i\".\"Id\", \"i\".\"LastModified\", \"i\".\"Path\", \"i\".\"UserId\"
FROM \"Users\" AS \"u\"
LEFT JOIN \"ImageInfos\" AS \"i\" ON \"u\".\"Id\" = \"i\".\"UserId\"
ORDER BY \"u\".\"Id\", \"i\".\"Id\""
[2024-09-14 08:01:43.378 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("2"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT \"p\".\"Id\", \"p\".\"Kind\", \"p\".\"Permission_Permissions_Guid\", \"p\".\"RowVersion\", \"p\".\"UserId\", \"p\".\"Value\", \"u\".\"Id\", \"i\".\"Id\"
FROM \"Users\" AS \"u\"
LEFT JOIN \"ImageInfos\" AS \"i\" ON \"u\".\"Id\" = \"i\".\"UserId\"
INNER JOIN \"Permissions\" AS \"p\" ON \"u\".\"Id\" = \"p\".\"UserId\"
ORDER BY \"u\".\"Id\", \"i\".\"Id\""
[2024-09-14 08:01:43.456 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("2"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT \"p\".\"Id\", \"p\".\"Kind\", \"p\".\"Preference_Preferences_Guid\", \"p\".\"RowVersion\", \"p\".\"UserId\", \"p\".\"Value\", \"u\".\"Id\", \"i\".\"Id\"
FROM \"Users\" AS \"u\"
LEFT JOIN \"ImageInfos\" AS \"i\" ON \"u\".\"Id\" = \"i\".\"UserId\"
INNER JOIN \"Preferences\" AS \"p\" ON \"u\".\"Id\" = \"p\".\"UserId\"
ORDER BY \"u\".\"Id\", \"i\".\"Id\""
[2024-09-14 08:01:43.508 -06:00] [INF] [1] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand ("1"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT \"a\".\"Id\", \"a\".\"DayOfWeek\", \"a\".\"EndHour\", \"a\".\"StartHour\", \"a\".\"UserId\", \"u\".\"Id\", \"i\".\"Id\"
FROM \"Users\" AS \"u\"
LEFT JOIN \"ImageInfos\" AS \"i\" ON \"u\".\"Id\" = \"i\".\"UserId\"
INNER JOIN \"AccessSchedules\" AS \"a\" ON \"u\".\"Id\" = \"a\".\"UserId\"
ORDER BY \"u\".\"Id\", \"i\".\"Id\""
[2024-09-14 08:02:09.157 -06:00] [FTL] [1] : Failed to create/read logger configuration
System.ArgumentException: A source source must be provided. (Parameter 'source')
   at Serilog.Configuration.LoggerMinimumLevelConfiguration.Override(String source, LoggingLevelSwitch levelSwitch)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass11_1.<ApplyMinimumLevel>b__3(LoggerMinimumLevelConfiguration configuration, LoggingLevelSwitch levelSwitch)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass11_0.<ApplyMinimumLevel>g__ApplyMinimumLevelConfiguration|1(IConfigurationSection directive, Action`2 applyConfigAction)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyMinimumLevel(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, ConfigurationReaderOptions readerOptions)
   at Jellyfin.Server.Helpers.StartupHelpers.InitializeLoggingFramework(IConfiguration configuration, IApplicationPaths appPaths)
```

### Additional information

running in docker on a rpi4, resources are not an issue. version 10.8.13 runs under the exact same conditions and share with none of these issues.

**Comment by gnattu** [comment]
Is your sdcard or whatever stuff given to jellyfin full?

**Comment by shandshellin** [comment]
jellyfin's contents are on a nfs share with plenty of room, local usb drive just runs docker and has images, also lots of room.

**Comment by gnattu** [comment]
> jellyfin's contents are on a nfs share

We no longer support this kind of setup due to sqlite does not want to work with nfs well. If that is what caused the problem we can to very little. Can you try connect an SSD or at least thumb drive via usb and try if that works?

**Comment by shandshellin** [comment]
that would defeat the point of the swarm, no database locks or anything. as i said 10.8.13 works fine with the same nfs share and setup. Does the log tell you anything of use?

**Comment by shandshellin** [comment]
i use sonarr/radarr/jellyfin/lidar all on the nfs share and no issues, sometime a locked database but that is expected for databases and nfs but never locked witrh jellyfin

**Comment by solidsnake1298** [comment]
Databases, even for something like Jellyfin, have a very high number of IOP/s that NFS just doesn't handle.  And changes in 10.9 further increased the IOP load.  We even recommend against running Jellyfin's database on a hard drive for the same reason.  Now you're adding network latency into the equation.

**Comment by shandshellin** [comment]
if i install on a local drive, when it moves nodes it will no longer have access to the drive, which is the issue. There would then need to be a separate process to sync it across nodes.

**Comment by shandshellin** [comment]
i do love my persistent storage that i can backup. Is there any option in jellyfin to back itself up?

**Comment by felix920506** [comment]
storing jellyfin application files on network shares is not supported. Please head to our chat rooms or forum for help on finding alternative solutions and backup methods. https://jellyfin.org/contact

**Comment by oddstr13** [comment]
sqlite databases should never be placed on network filesystems, this is not a problem unique to Jellyfin.

I'm amazed it worked for you for any amount of time, and this has never been a supported configuration.
When I accidentally did this a few years back, I was also meet with lots of crashing and corruption issues, so it is not new to 10.9.

Putting everything *but* the sqlite files on a network share might work, but do beware that some plugins also create their own database files. (symlinks or creative mounting may be needed to achieve this)

**Comment by shandshellin** [comment]
Ok to touch back on this. I installed to a local usb on the rpi. I have ran a clean install 4 times now and it will just randomly crash or hang and corrupt the database, the same way it did on nfs. I even disabled a bunch of scheduled tasks and limited the parallell processes. I managed to scan a few libraries each time in different orders excluding certain libraries and from what i can tell 10.9+ is a steaming pile. At least on arm64. Does anyone one your team run a rpi with the latest version of jellyfin, fresh install to verify it doesn't brick after a couple days?

**Comment by shandshellin** [comment]
i have ran 10.8.13 for close to 2 years on nfs in docker swarm on rpi's with zero issues or database corruption.

**Comment by shandshellin** [comment]
to be clear i have tested it in a few rpi's with different storage etc so it can only be the software on that platform.

**Comment by gnattu** [comment]
> Does anyone one your team run a rpi with the latest version of jellyfin, fresh install to verify it doesn't brick after a couple days?

We do have one team member using rpi and his does not crash a couple of days. The problem he faced is mainly performance issue and our default thumbnail generation timeout is too short for rpi's CPU which may lead to thumbnail and trickplay generation to fail, but his database does not corrupt and his instance does not crash.

> At least on arm64.

We have lot of users running it on arm64 platforms and do not have the same issue as you so it can't be the problem. I use arm64 platforms for my home server and I will know if that is the problem.

Also your responses are not really helpful IF you want to know what caused your problem. Just ranting at us "IT'S YOUR PROBLEMS" will not get your problem fixed. You at least need to provide us logs with the time it failed the library scan and the time it just crashed. 

For example, a lot of docker users have the env var `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` set to 1 for 10.9 but that is no longer correct and will fail library scan even home page browsing if you set that to 1. It has to be set to 0 or unset as documented in the [changelog](https://jellyfin.org/posts/jellyfin-release-10.9.0#key-release-notesbreaking-changes). If you are using persistent container settings you'd better check if you have that env var set again.

**Comment by shandshellin** [comment]
This has all been fresh installs i'm testing with, nothing persisting from anything else, local install on rpi 4's. I've eliminated everything i can think of on my end, the logs show nothing just humming along and then it stops, no errors. Wiping the library database allows the madness to begin again lol. It looks like i'm going to be sticking with 10.8.13 for the foreseeable future. My only issue is with fire tv. i need to sideload an older version of the app so it sticks. Can you recommend any steps to do this or at least the link i should use to sideload the last version capable of using 10.8.13?
