### ISSUE TITLE
API ItemUpdate endpoint returns a 500 error "Error processing request."

### ISSUE THREAD

**Issue by jacobalvarez** [jellyfin/jellyfin#12646]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I fetch some items from my server using `/Items?<queryString>`, then add a tag to one of them and try to save it by POSTing to `/Items/{itemId}`. However, the request fails with a 500 error and a body of "Error processing request."

### Reproduction steps

1. fetch an item using `/Items?<queryString>`
2. push a tag to its `Tags` property array
3. POST the item as the request body JSON to `/Items/{itemId}`

### What is the current _bug_ behavior?

The response is a 500 error with a body of "Error processing request." and a logged error of "Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/0f3857fdb64c38f06eecbb23161118c6.
System.NullReferenceException: Object reference not set to an instance of an object."

### What is the expected _correct_ behavior?

A "204 Item Updated" response

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Ubuntu 18.04.4 LTS
- Linux Kernel: Linux 4.15.0-213-generic
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Caddy (also tried without proxy)
- Base URL: http://jellyfin.home
- Networking: bridge
- Storage: NFS
```

### Jellyfin logs

```shell
[13:48:04] [INF] [195] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 OPTIONS http://jellyfin.home/Items/0f3857fdb64c38f06eecbb23161118c6 - null null
[13:48:04] [INF] [195] Microsoft.AspNetCore.Cors.Infrastructure.CorsService: CORS policy execution successful.
[13:48:04] [INF] [195] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 OPTIONS http://jellyfin.home/Items/0f3857fdb64c38f06eecbb23161118c6 - 204 null null 1.6484ms
[13:48:04] [INF] [231] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://jellyfin.home/Items/0f3857fdb64c38f06eecbb23161118c6 - application/json 730
[13:48:04] [INF] [231] Microsoft.AspNetCore.Cors.Infrastructure.CorsService: CORS policy execution successful.
[13:48:05] [INF] [231] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand (129ms) [Parameters=[@__token_0='?' (Size = 32)], CommandType='Text', CommandTimeout='30']
SELECT "a"."Id", "a"."AccessToken", "a"."DateCreated", "a"."DateLastActivity", "a"."Name"
FROM "ApiKeys" AS "a"
WHERE "a"."AccessToken" = @__token_0
LIMIT 1
[13:48:05] [INF] [231] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint 'Jellyfin.Api.Controllers.ItemUpdateController.UpdateItem (Jellyfin.Api)'
[13:48:05] [INF] [231] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Route matched with {action = "UpdateItem", controller = "ItemUpdate"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] UpdateItem(System.Guid, MediaBrowser.Model.Dto.BaseItemDto) on controller Jellyfin.Api.Controllers.ItemUpdateController (Jellyfin.Api).
[13:48:05] [INF] [231] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action Jellyfin.Api.Controllers.ItemUpdateController.UpdateItem (Jellyfin.Api) in 103.2742ms
[13:48:05] [INF] [231] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint 'Jellyfin.Api.Controllers.ItemUpdateController.UpdateItem (Jellyfin.Api)'
[13:48:05] [ERR] [231] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/0f3857fdb64c38f06eecbb23161118c6.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(ManagedConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.ItemUpdateController.UpdateItem(Guid itemId, BaseItemDto request)
   at lambda_method1271(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[13:48:05] [INF] [231] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 POST http://jellyfin.home/Items/0f3857fdb64c38f06eecbb23161118c6 - 500 null text/plain 270.8467ms
```

### Additional information

Here's an example of an ItemUpdate request that fails:

```bash
curl 'http://jellyfin.home/Items/813ca99e96d42ceb810941886d59b0ae' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: MediaBrowser Token="f6d89356af9042d898fd1c32cfb10c53"' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: null' \
  -H 'Pragma: no-cache' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  --data-raw '{"Name":"Almighty God","ServerId":"a23eedb02b9f4eb7be2e5ce16f9e00fe","Id":"813ca99e96d42ceb810941886d59b0ae","HasLyrics":false,"Container":"mp3","ChannelId":null,"RunTimeTicks":1820735000,"IndexNumber":9,"ParentIndexNumber":1,"ProviderIds":{},"IsFolder":false,"Type":"Audio","Tags":["test-tag-1"],"Artists":["Cat Chat"],"ArtistItems":[{"Name":"Cat Chat","Id":"c9c492df169f944fafe2c9f898efd17b"}],"Album":"Cat. Chat - Radical Ride Around The World With Amazing Angels And Super Saints","AlbumId":"131dc6ab73b15d576c62b579160f4fd1","AlbumArtist":"Cat Chat","AlbumArtists":[{"Name":"Cat Chat","Id":"c9c492df169f944fafe2c9f898efd17b"}],"ImageTags":{},"BackdropImageTags":[],"ImageBlurHashes":{},"LocationType":"FileSystem","MediaType":"Audio"}' \
  --insecure
```

**Comment by gnattu** [comment]
If you use a token you need to use the `/Users/{userId}/Items/` endpoint. Updates without specifying userId won't work due to permission handling.

**Comment by nielsvanvelzen** [comment]
Please avoid the deprecated routes. User IDs should be specified as query parameter instead.

**Comment by gnattu** [comment]
> Please avoid the deprecated routes. User IDs should be specified as query parameter instead.

That route does not support specifying users explicitly with query parameter yet unfortunately, and it will always resolves to `00000000-0000-0000-0000-000000000000`. For this use case the user has to use the deprecated route until we implement explicit set by user id in that one.

**Comment by gnattu** [comment]
To make sure it is really related to the user failed the access check, can you try the following?

- Log in with your browser using a user that can normally edit the metadata on the file you want
- Open the developer console, and copy the token that the browser is using
- Replace that token in your curl command

If it is related to the derived user, then now you should see 204 normally because the token you provided now has a valid derived userId. If you are still seeing the same error, then it is probably due to the body format you provided is incomplete. You can compare what the web sends and what you are sending and filing the missing fields.

**Comment by jacobalvarez** [comment]
@gnattu I tried that but got the same error

> If you are still seeing the same error, then it is probably due to the body format you provided is incomplete. You can compare what the web sends and what you are sending and filing the missing fields.

 I get the items directly from `/Items` then modify them, which is the recommended way of updating them.

**Comment by gnattu** [comment]
It is really strange because I cannot reproduce it at all. Does this happen to all your files or only some of them? In the worst case you may have a corrupted DB

**Comment by jacobalvarez** [comment]
It appears to happen to all of them. I'm able to update the tags through the Jellyfin web page, which fetches the item using `/Users/{userId}/Items/{itemId}`. I switched to using that endpoint, then performing the update, and that works.

**Comment by felix920506** [comment]
According to devs, this might be fixed on master after the EFCore release, needs testing.
