### ISSUE TITLE
windows server crash sometime

### ISSUE THREAD

**Issue by lifeengines** [jellyfin/jellyfin#12656]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

[2024-09-16 23:27:20.091 +08:00] [FTL] [27] Main: Unhandled Exception
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\cache\transcodes\aee17b0b61335647adf3b57e6047711f.concat' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.KillTranscodingJob(TranscodingJob job, Boolean closeLiveStream, Func`2 delete)
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.OnTranscodeKillTimerStopped(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

### Reproduction steps

crash randomlly

### What is the current _bug_ behavior?

server exit,and not restart

### What is the expected _correct_ behavior?

server can handle this exception,dont exit

### Jellyfin Server version

10.9.11+

### Specify the build version

 10.9.11

### Environment

```markdown
- OS: Windows
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-09-16 23:27:20.091 +08:00] [FTL] [27] Main: Unhandled Exception
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\cache\transcodes\aee17b0b61335647adf3b57e6047711f.concat' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.KillTranscodingJob(TranscodingJob job, Boolean closeLiveStream, Func`2 delete)
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.OnTranscodeKillTimerStopped(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by oddstr13** [comment]
More log context would be nice, minimum 10 messages before, and everything after.

Looks to me like this could be a problem with antivirus or other software accessing the file while Jellyfin is attempting to delete it.

It would be best to exclude the cache directory, and probably others, from real time antivirus scanning.
