### ISSUE TITLE
[Issue] Problems with hardware acceleration

### ISSUE THREAD

**Issue by felixschndr** [jellyfin/jellyfin#12709]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

For some (few) titles Jellyfin fails to playback the title. After looking into the log I see the following:

Jellyfin log
```txt
[21:07:14] [ERR] [8] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 1
[21:07:14] [ERR] [8] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/01b6230d-df48-b7e6-b472-9a321370f295/hls1/main/-1.mp4.
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
```

Running the mentioned command manually I see an error from `ffmpeg`:
```txt
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
 built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
[matroska,webm @ 0x58f21209c2c0] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (50000000) and 'probesize' (50000000) options # is this an issue?
[hevc_vaapi @ 0x58f2121eda00] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
[vost#0:0/hevc_vaapi @ 0x58f2121ed700] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libfdk_aac @ 0x58f21214c180] 2 frames left in the queue on closing
Conversion failed!
```

This only happens on some players. When I try to play the video in the browser using the built-in player and on google tv with the build-in player the issue occurs. Using the android build-in player or google tv external player (VLC) the issue does not occur. I guess this has something to do with which players transcode on the server and which ones do it on the client, right?

The file is in the `HEVC` format. In the jellyfin settings I enabled hardware transcoding for `HEVC` using `VAAPI`. When disabling this, playback works, but the perfomance is very poor as the CPU isn't the fastest. I guess there is something wrong with the settings. I have the following gpu
```txt
$ lspci -nn | grep -Ei "3d|display|vga"
00:02.0 VGA compatible controller [0300]: Intel Corporation GeminiLake [UHD Graphics 600] [8086:3185] (rev 03)
```
From the [docs](https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#speed-and-quality) under `Entry-Level - HD / UHD 600, 605 and 61x` I see that `HVEC` transcoding should be possible. 

These are the settings I applied, can you see something obvious wrong?
![Screenshot 2024-09-24 213221](https://github.com/user-attachments/assets/cdf31ffc-1a75-4eb7-aa56-be81d8178246)

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Android, Browser, Google TV
- FFmpeg Version: 6.0.1
- Playback Method:
- Hardware Acceleration: See above (VAAPI or none)
- GPU Model: `00:02.0 VGA compatible controller [0300]: Intel Corporation GeminiLake [UHD Graphics 600] [8086:3185] (rev 03)`
```

### Jellyfin logs

```shell
[21:07:14] [ERR] [8] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 1
[21:07:14] [ERR] [8] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/01b6230d-df48-b7e6-b472-9a321370f295/hls1/main/-1.mp4.
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
```

### FFmpeg logs

```shell
root@bb89e5d3f63a:/#/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 50000000 -probesize 50000000 -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/data/media/HDD/Serien/Reacher/Staffel 01/S01E01 - Welcome to Margrave - Bluray-2160p.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 hevc_vaapi -tag:v:0 hvc1 -low_power 1 -rc_mode VBR -b:v 23652084 -maxrate 23652084 -bufsize 47304168 -profile:v:0 main -level 150 -sei -a53_cc -force_key_frames:0 "expr:gte(t,n_forced*3)" -filter_complex "[0:2]scale=-1:1080:fast_bilinear,scale,crop,pad=max(2160\,iw):max(1080\,ih):(ow-iw)/2:(oh-ih)/2:black@0,crop=2160:1080,format=bgra,hwupload=derive_device=vaapi[sub];[0:0]setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,procamp_vaapi=b=16:c=1,tonemap_vaapi=format=nv12:p=bt709:t=bt709:m=bt709:extra_hw_frames=32[main];[main][sub]overlay_vaapi=eof_action=pass:repeatlast=0:w=3840:h=1920" -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "b71a82d4c817907a58b69fff4e88f497-1.mp4" -start_number 0 -hls_segment_filename "/config/data/transcodes/b71a82d4c817907a58b69fff4e88f497%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/b71a82d4c817907a58b69fff4e88f497.m3u8""
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[matroska,webm @ 0x58f21209c2c0] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (50000000) and 'probesize' (50000000) options
Input #0, matroska,webm, from 'file:/data/media/HDD/Serien/Reacher/Staffel 01/S01E01 - Welcome to Margrave - Bluray-2160p.mkv':
  Metadata:
    title           : Reacher S01 2022 2160p UHD Blu-ray x265 10bit DTS-HD MA 5.1-HDS
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
    creation_time   : 2024-01-08T00:34:19.000000Z
  Duration: 00:53:01.39, start: 0.000000, bitrate: 23652 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 56.265000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 56.265000, end 622.705000
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 622.705000, end 1127.668000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 1127.668000, end 1623.330000
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 1623.330000, end 2169.918000
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 2169.918000, end 2723.220000
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 2723.220000, end 3059.306000
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 3059.306000, end 3181.387000
      Metadata:
        title           : Chapter 08
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1920, SAR 1:1 DAR 2:1, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      title           : veryzayin@HDSky
      BPS             : 20104219
      DURATION        : 00:53:01.387000000
      NUMBER_OF_FRAMES: 76277
      NUMBER_OF_BYTES : 7994912771
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)
    Metadata:
      title           : English
      BPS             : 3437758
      DURATION        : 00:53:01.387000000
      NUMBER_OF_FRAMES: 298255
      NUMBER_OF_BYTES : 1367105184
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle (default)
    Metadata:
      title           : ENG
      BPS             : 49947
      DURATION        : 00:49:18.873000000
      NUMBER_OF_FRAMES: 1708
      NUMBER_OF_BYTES : 18473539
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(chi): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      title           : CHS
      BPS             : 34364
      DURATION        : 00:51:00.599000000
      NUMBER_OF_FRAMES: 1664
      NUMBER_OF_BYTES : 13146969
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(chi): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      title           : CHT
      BPS             : 35492
      DURATION        : 00:51:00.599000000
      NUMBER_OF_FRAMES: 1664
      NUMBER_OF_BYTES : 13578463
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(chi): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      title           : CHS&ENG
      BPS             : 58465
      DURATION        : 00:51:00.599000000
      NUMBER_OF_FRAMES: 1664
      NUMBER_OF_BYTES : 22367301
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(chi): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      title           : CHT&ENG
      BPS             : 59593
      DURATION        : 00:51:00.599000000
      NUMBER_OF_FRAMES: 1664
      NUMBER_OF_BYTES : 22799025
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-01-08 00:34:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 (hevc) -> setparams:default (graph 0)
  Stream #0:2 (pgssub) -> scale:default (graph 0)
  overlay_vaapi:default (graph 0) -> Stream #0:0 (hevc_vaapi)
  Stream #0:1 -> #0:1 (dts (dca) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[matroska,webm @ 0x58f21209c2c0] sub2video: using 3840x1920 canvas
[hevc_vaapi @ 0x58f2121eda00] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
[vost#0:0/hevc_vaapi @ 0x58f2121ed700] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libfdk_aac @ 0x58f21214c180] 2 frames left in the queue on closing
Conversion failed!
```

**Comment by gnattu** [comment]
Did you passthrough your GPU correctly into the docker container?

**Comment by felixschndr** [comment]
@gnattu Yes, I did
```yaml
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin_app
    restart: unless-stopped
    ports:
      - 10001:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jellyfin.home.fschneider.me
      - JELLYFIN_FFmpeg__probesize=50000000
      - JELLYFIN_FFmpeg__analyzeduration=50000000
    volumes:
      - ./data/jellyfin/config:/config
      - /media:/data/media
    devices:
      - /dev/dri/card1
      - /dev/dri/renderD128
```
The GPU is also available in the container:
```bash
root@bb89e5d3f63a:/ ls -l /dev/dri/
total 0
crw-rw---- 1 root video     226,   1 Sep 24 21:05 card1
crw-rw---- 1 root video065z 226, 128 Sep 24 21:05 renderD128

root@bb89e5d3f63a:/ lspci -nn | grep -Ei "3d|display|vga"
00:02.0 VGA compatible controller [0300]: Intel Corporation GeminiLake [UHD Graphics 600] [8086:3185] (rev 03)
```

**Comment by gnattu** [comment]
Can you first try disable HEVC low power encoding? IIRC the Gemini Lake with Gen9 GPU does not support low power mode at all.

If that still not work can you run `/usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128` in the container and check the output?

**Comment by felixschndr** [comment]
> Can you first try disable HEVC low power encoding? IIRC the Gemini Lake with Gen9 GPU does not support low power mode at all.

This seems to work. I guess the transcoding is now running on the CPU, right? I should get a more powerful server as the playback stutters a lot since the CPU is quite weak^^

-----

> `/usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128`

```
root@a86ba56caa86:/# /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128
Trying display: drm
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.2.5 (12561f6)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
Can you see something interesting in there?

-----

Can you explain to me why the issue happens on some players and not others? Is it that on all players that work the transcoding happens on the client itself and not on the server? If so would it be an idea to disable transcoding on the server outright and let the (more powerful) clients to the work?

**Comment by gnattu** [comment]
> Can you explain to me why the issue happens on some players and not others?

Because some of them may not need transcoding at all, some of them may not support HEVC and the server will pick H264 encoder which has not enabled the low power mode from your setting.
