### ISSUE TITLE
Library scan does not complete after creating then deleting a music library that has some albums.

### ISSUE THREAD

**Issue by alayham** [jellyfin/jellyfin#12727]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Media scan times out after creating a music library, even if the library is deleted. there is no load on the server while the scan appears to run, and after the music library is deleted, the data should be the same as earlier and the scan usually takes seconds, but now it stops at 96.6%
If I leave it overnight, it appears to end or timeout, and if I start it again I get the same issue although no media files were changed. If I stop it in admin, I get the following in the logs
```
[INF] Attempting to cancel Scheduled Task "Scan Media Library"
[INF] Post-scan task cancelled: "ArtistsPostScanTask"
[INF] "Scan Media Library" Cancelled after 156 minute(s) and 17 seconds
```
This behavior seems either random or data related, if the media library contains ABBA albums, the scan succeeds. A single album by Celine Dion causes the issue

### Reproduction steps

The issue appears to be either random or data related, but once I got it, It does not go away.
1- Create a music library and add a folder that contains music.
2- when the album are detected, run a full library scan

### What is the current _bug_ behavior?

The library scan stops and does not complete.

### What is the expected _correct_ behavior?

Even if the issue is caused by the data, User data should not be allowed to break library scans. Besides, removing the data does not fix the issue.

### Jellyfin Server version

10.9.11+

### Specify version number

10.9.11

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Linux jellyfin 6.8.12-1-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-1 (2024-08-05T16:17Z) x86_64 GNU/Linux
- Linux Kernel:latest Proxmox kernel
- Virtualization: Debian lxc on Proxmon
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: 
- GPU Model:
- Plugins: uninstalled many, but that had no effect on the issue.
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Data from an NFS mount.
```

### Jellyfin logs

```shell
[INF] Attempting to cancel Scheduled Task "Scan Media Library"
[INF] Post-scan task cancelled: "ArtistsPostScanTask"
[INF] "Scan Media Library" Cancelled after 156 minute(s) and 17 seconds
```

**Comment by Hello-World-Traveler** [comment]
Is this still a bug?

**Comment by joswart** [comment]
I am seeing the same issue on my system. Not using the IMVDb.

**Comment by jajaX** [comment]
Hello,
This problem is still ongoing.
I'm seeing a lot of errors like this in my logos even though I uninstalled IMVDb !

```
Error in "IMVDb"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.results[11].discogs_id | LineNumber: 143 | BytePositionInLine: 30.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetResponseAsync[T](String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
