### ISSUE TITLE
Doesn't see mounted devices in /media/username

### ISSUE THREAD

**Issue by K0-RR** [jellyfin/jellyfin#12747]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin server doesn't show folders in the /media/username (default mount point for external drives).

### Reproduction steps

![image](https://github.com/user-attachments/assets/e9e5cf06-47e4-45c1-834a-af15039aad28)

### What is the current _bug_ behavior?

No files are visible

### What is the expected _correct_ behavior?

Disk detected

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Zorin OS 17.2 Core
- Linux Kernel: 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2
- Virtualization: none
- Clients: Browser
- Browser: Firefox and Brave
- FFmpeg Version: 
- Playback Method: none
- Hardware Acceleration: none
- GPU Model: AMD Radeon RX 6600M
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2024-09-29 14:55:42.046 +02:00] [INF] Saving system configuration
[2024-09-29 14:55:42.048 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-09-29 14:55:42.049 +02:00] [INF] Stopping NAT discovery
[2024-09-29 14:55:42.090 +02:00] [WRN] No users, creating one with username "jellyfin"
[2024-09-29 14:57:17.719 +02:00] [ERR] Error processing request. URL "POST" "/Library/VirtualFolders".
System.ArgumentException: The specified path does not exist: /media/nacia/26b229c2-2a0f-4996-9ec6-9c4431bb4331/home/nacia/Wideo/Priority/.
   at Emby.Server.Implementations.Library.LibraryManager.AddVirtualFolder(String name, Nullable`1 collectionType, LibraryOptions options, Boolean refreshLibrary)
   at Jellyfin.Api.Controllers.LibraryStructureController.AddVirtualFolder(String name, Nullable`1 collectionType, String[] paths, AddVirtualFolderDto libraryOptionsDto, Boolean refreshLibrary)
   at lambda_method665(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-09-29 14:58:31.953 +02:00] [INF] Saving system configuration
[2024-09-29 14:58:31.954 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-09-29 14:59:07.201 +02:00] [INF] Saving system configuration
[2024-09-29 14:59:07.201 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-09-29 14:59:12.366 +02:00] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-29 14:59:12.366 +02:00] [INF] Defined LAN exclusions: []
[2024-09-29 14:59:12.366 +02:00] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-29 14:59:12.366 +02:00] [INF] Filtered interface addresses: ["127.0.0.1", "192.168.0.14"]
[2024-09-29 14:59:12.366 +02:00] [INF] Bind Addresses ["0.0.0.0"]
[2024-09-29 14:59:12.366 +02:00] [INF] Remote IP filter is "Allowlist"
[2024-09-29 14:59:12.366 +02:00] [INF] Filtered subnets: []
[2024-09-29 14:59:14.374 +02:00] [INF] Saving system configuration
[2024-09-29 14:59:14.374 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-09-29 14:59:14.375 +02:00] [INF] Stopping NAT discovery
[2024-09-29 14:59:14.375 +02:00] [INF] Starting NAT discovery
[2024-09-29 14:59:14.377 +02:00] [INF] Validating media library
[2024-09-29 14:59:14.540 +02:00] [WRN] Library folder "/media/nacia" is inaccessible or empty, skipping
[2024-09-29 14:59:14.541 +02:00] [WRN] Library folder "/var/lib/jellyfin/data/playlists" is inaccessible or empty, skipping
[2024-09-29 14:59:14.587 +02:00] [WRN] Library folder "/media/nacia" is inaccessible or empty, skipping
[2024-09-29 14:59:14.587 +02:00] [WRN] Library folder "/var/lib/jellyfin/data/playlists" is inaccessible or empty, skipping
[2024-09-29 14:59:14.597 +02:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 0 seconds
[2024-09-29 14:59:22.885 +02:00] [INF] Authentication request for "jellyfin" has succeeded.
[2024-09-29 14:59:22.887 +02:00] [INF] Current/Max sessions for user "jellyfin": 0/0
[2024-09-29 14:59:22.888 +02:00] [INF] Creating new access token for user 898a3538-f636-414a-8a66-d40611a96126
[2024-09-29 14:59:23.020 +02:00] [INF] WS "127.0.0.1" request
[2024-09-29 15:06:22.189 +02:00] [INF] WS "127.0.0.1" closed
[2024-09-29 15:06:47.364 +02:00] [INF] Sending shutdown notifications
[2024-09-29 15:06:47.372 +02:00] [INF] Stopping NAT discovery
[2024-09-29 15:06:47.376 +02:00] [INF] Running query planner optimizations in the database... This might take a while
[2024-09-29 15:06:47.406 +02:00] [INF] Disposing "CoreAppHost"
[2024-09-29 15:06:47.406 +02:00] [INF] Disposing "MusicBrainzArtistProvider"
[2024-09-29 15:06:47.406 +02:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2024-09-29 15:06:47.406 +02:00] [INF] Disposing "PluginManager"
[2024-09-29 15:08:18.808 +02:00] [INF] Jellyfin version: "10.9.11"
[2024-09-29 15:08:18.830 +02:00] [INF] Environment Variables: ["[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS --datadir $JELLYFIN_DATA_DIR --configdir $JELLYFIN_CONFIG_DIR --logdir $JELLYFIN_LOG_DIR --cachedir $JELLYFIN_CACHE_DIR]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
[2024-09-29 15:08:18.832 +02:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-09-29 15:08:18.832 +02:00] [INF] Operating system: "Zorin OS 17.2"
[2024-09-29 15:08:18.832 +02:00] [INF] Architecture: X64
[2024-09-29 15:08:18.833 +02:00] [INF] 64-Bit Process: True
[2024-09-29 15:08:18.833 +02:00] [INF] User Interactive: True
[2024-09-29 15:08:18.833 +02:00] [INF] Processor count: 16
[2024-09-29 15:08:18.833 +02:00] [INF] Program data path: "/var/lib/jellyfin"
[2024-09-29 15:08:18.833 +02:00] [INF] Log directory path: "/var/log/jellyfin"
[2024-09-29 15:08:18.833 +02:00] [INF] Config directory path: "/etc/jellyfin"
[2024-09-29 15:08:18.833 +02:00] [INF] Cache path: "/var/cache/jellyfin"
[2024-09-29 15:08:18.833 +02:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2024-09-29 15:08:18.833 +02:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2024-09-29 15:08:18.949 +02:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-09-29 15:08:18.985 +02:00] [INF] Loading assemblies
[2024-09-29 15:08:19.042 +02:00] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-29 15:08:19.042 +02:00] [INF] Defined LAN exclusions: []
[2024-09-29 15:08:19.042 +02:00] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-09-29 15:08:19.043 +02:00] [INF] Filtered interface addresses: ["127.0.0.1"]
[2024-09-29 15:08:19.043 +02:00] [INF] Bind Addresses ["0.0.0.0"]
[2024-09-29 15:08:19.043 +02:00] [INF] Remote IP filter is "Allowlist"
[2024-09-29 15:08:19.043 +02:00] [INF] Filtered subnets: []
[2024-09-29 15:08:20.106 +02:00] [INF] Loaded plugin: "TMDb" "10.9.11.0"
[2024-09-29 15:08:20.106 +02:00] [INF] Loaded plugin: "Studio Images" "10.9.11.0"
[2024-09-29 15:08:20.107 +02:00] [INF] Loaded plugin: "OMDb" "10.9.11.0"
[2024-09-29 15:08:20.119 +02:00] [INF] Loaded plugin: "MusicBrainz" "10.9.11.0"
[2024-09-29 15:08:20.119 +02:00] [INF] Loaded plugin: "AudioDB" "10.9.11.0"
[2024-09-29 15:08:20.175 +02:00] [INF] Kestrel is listening on "0.0.0.0"
[2024-09-29 15:08:20.316 +02:00] [INF] Starting NAT discovery
[2024-09-29 15:08:20.567 +02:00] [WRN] The WebRootPath was not found: "/var/lib/jellyfin/wwwroot". Static files may be unavailable.
[2024-09-29 15:08:20.588 +02:00] [INF] Running startup tasks
[2024-09-29 15:08:20.599 +02:00] [INF] Daily trigger for "Generate Trickplay Images" set to fire at 2024-09-30 03:00:00.000 +02:00, which is 11:51:39.4010178 from now.
[2024-09-29 15:08:20.607 +02:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 2024-09-30 02:00:00.000 +02:00, which is 10:51:39.3922868 from now.
[2024-09-29 15:08:20.663 +02:00] [INF] Found ffmpeg version "6.0.1"
[2024-09-29 15:08:20.704 +02:00] [INF] Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-09-29 15:08:20.718 +02:00] [INF] Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-09-29 15:08:20.732 +02:00] [INF] Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-09-29 15:08:20.810 +02:00] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-09-29 15:08:20.994 +02:00] [INF] FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-09-29 15:08:20.995 +02:00] [INF] ServerId: "5e97ac2f28104a2ea7ea6d20d5dbbc15"
[2024-09-29 15:08:20.995 +02:00] [INF] Core startup complete
[2024-09-29 15:08:20.995 +02:00] [INF] Startup complete 0:00:02.3408125
[2024-09-29 15:08:23.616 +02:00] [INF] "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:08:23.651 +02:00] [ERR] An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/files/plugin/manifest.json"
System.Net.Http.HttpRequestException: Name or service not known (repo.jellyfin.org:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Jellyfin.Networking.HappyEyeballs.HttpClientExtension.AttemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at Jellyfin.Networking.HappyEyeballs.HttpClientExtension.OnConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient client, Task`1 responseTask, Boolean usingResponseHeadersRead, CancellationTokenSource linkedCTS, Func`4 deserializeMethod, TJsonOptions jsonOptions, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
[2024-09-29 15:08:23.659 +02:00] [INF] "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.609 +02:00] [INF] "Audio Normalization" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.609 +02:00] [INF] "Download missing subtitles" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.617 +02:00] [INF] Optimizing and vacuuming jellyfin.db...
[2024-09-29 15:09:20.618 +02:00] [INF] "Clean Transcode Directory" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.625 +02:00] [INF] "Clean Log Directory" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.625 +02:00] [INF] "Clean Cache Directory" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.639 +02:00] [INF] "TasksRefreshChannels" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:09:20.711 +02:00] [INF] jellyfin.db optimized successfully!
[2024-09-29 15:09:20.711 +02:00] [INF] "Optimize database" Completed after 0 minute(s) and 0 seconds
[2024-09-29 15:10:13.957 +02:00] [INF] Authentication request for "jellyfin" has succeeded.
[2024-09-29 15:10:13.958 +02:00] [INF] Current/Max sessions for user "jellyfin": 0/0
[2024-09-29 15:10:13.960 +02:00] [INF] Creating new access token for user 898a3538-f636-414a-8a66-d40611a96126
[2024-09-29 15:10:14.126 +02:00] [INF] WS "127.0.0.1" request
[2024-09-29 15:35:39.133 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 15:35:39.134 +02:00] [ERR] Error processing request: "Invalid token". URL "GET" "/socket".
[2024-09-29 15:37:09.308 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 15:37:09.309 +02:00] [ERR] Error processing request: "Invalid token". URL "GET" "/socket".
[2024-09-29 15:52:36.073 +02:00] [INF] Refreshing guide with 7 days of guide data
[2024-09-29 15:52:36.076 +02:00] [INF] "Refresh Guide" Completed after 0 minute(s) and 3 seconds
[2024-09-29 16:30:39.007 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 16:30:39.007 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 16:30:39.007 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 16:30:39.007 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 16:30:39.008 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2024-09-29 16:30:39.008 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2024-09-29 16:35:12.262 +02:00] [INF] Authentication request for "jellyfin" has succeeded.
[2024-09-29 16:35:12.262 +02:00] [INF] Current/Max sessions for user "jellyfin": 1/0
[2024-09-29 16:35:12.262 +02:00] [INF] Creating new access token for user 898a3538-f636-414a-8a66-d40611a96126
[2024-09-29 16:35:12.553 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-09-29 16:35:12.554 +02:00] [ERR] Error processing request: "Invalid token". URL "GET" "/socket".
[2024-09-29 16:35:42.530 +02:00] [INF] WS "127.0.0.1" request
```

### Additional information

Installed using https://repo.jellyfin.org/install-debuntu.sh

**Comment by K0-RR** [comment]
I should also mention that temporarily I have switched to the docker version (specified the media with `/media/nacia/26b229c2-2a0f-4996-9ec6-9c4431bb4331/home/nacia/Wideo/Priority/:/media`) and the library there works fine.

**Comment by felix920506** [comment]
This is a permissions issue. Please head to our forum or chat rooms for support. https://jellyfin.org/contact
