### ISSUE TITLE
Collections are deleted during library scan when nas is offline

### ISSUE THREAD

**Issue by pimw1** [jellyfin/jellyfin#12806]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When the library is scanned while the nas-share is unavailable, the collections are emptied (collections are still there, but do not contain any movie anymore).
![image](https://github.com/user-attachments/assets/47e7630b-c0b3-4b21-8538-fc28d2ed1a87)

It might be related to https://github.com/jellyfin/jellyfin/issues/12724

### Reproduction steps

1. Trigger a library scan while jellyfin cannot reach the nas containing the media
2. Open the collections page; every movie is removed from the collection.
3. Reattach your NAS, rescan your libraries. That scan will be succesful, but the collections are not restored.

### What is the current _bug_ behavior?

The collections are emptied (i.e. all movies removed from the collections)

### What is the expected _correct_ behavior?

The collections should show the movies when the nas is reattached and the library is scanned again.

### Jellyfin Server version

Unstable

### Specify unstable release number

10.10.0

### Specify the build version

2024100705

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS 
- Linux Kernel: 6.8.0-45-generic
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome 129.0.6668.90
- FFmpeg Version: NA
- Playback Method: NA
- Hardware Acceleration: NA
- GPU Model: NA
- Plugins: NA
- Reverse Proxy: nginx
- Base URL: NA
- Networking: network_mode: 'host'
- Storage: NFS
```

### Jellyfin logs

```shell
[2024-10-10 23:19:24.169 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie and the Diamond Castle (2008)/Barbie and the Diamond Castle (2008) [imdbid-tt1294138] - [DVD][AC3 5.1][AV1].mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie and the Magic of Pegasus (2005)/Barbie and the Magic of Pegasus (2005) [imdbid-tt0480345] - [WEBRip-1080p][AAC 5.1][h264]-YTS.MX.mp4"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie as the Island Princess (2007)/Barbie as the Island Princess (2007) [imdbid-tt1092053] - [DVD][AC3 5.1][AV1].mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie as The Princess & the Pauper (2004)/Barbie as The Princess and the Pauper (2004) [imdbid-tt0426955] - [WEBRip-1080p][AAC 5.1][x264]-LAMA.mp4"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie as Rapunzel (2002)/Barbie as Rapunzel (2002) [imdbid-tt0313255] - [HDTV-1080p][AAC 2.0][x264].mp4"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie Fairytopia Magic of the Rainbow (2007)/Barbie Fairytopia Magic of the Rainbow (2007) [imdbid-tt1007920] - [DVD][MP2 2.0][XviD].mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie in The 12 Dancing Princesses (2006)/Barbie in the 12 Dancing Princesses 2006 DVDRip XviD Eng-Hindi S.avi"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie in A Christmas Carol (2008)/Barbie.in.A.Christmas.Carol.2008.1080p.WEBRip.x265.mp4"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie in A Mermaid Tale (2010)/Barbie in A Mermaid Tale (2010) [imdbid-tt1610301] - [WEBRip-1080p][AAC 5.1][x265].mp4"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie in the Nutcracker (2001)/Barbie in the Nutcracker (2001) [imdbid-tt0288441] - [DVD][AC3 5.1][AV1].mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie Mariposa (2008)/Barbie Mariposa (2008) [imdbid-tt1201561] - [DVD][AC3 5.1][AV1].mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie of Swan Lake (2003)/Barbie of Swan Lake (2003) [imdbid-tt0383206] - [DVD][AC3 5.1][AV1]-CFF.mkv"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie Presents Thumbelina (2009)/Barbie Presents Thumbelina (2009) [imdbid-tt1398940] - [DVD][AAC 2.0][x264]-Lounge.m4v"
[2024-10-10 23:19:24.170 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Barbie Dreamtopia Collection" cannot be found at "/data/media/movies/Barbie Fairytopia (2005)/Barbie Fairytopia (2005) [imdbid-tt0450982] - [DVD][MP3 2.0][DivX].divx"
[2024-10-10 23:19:24.196 +02:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: The process cannot access the file '/config/data/collections/Barbie Dreamtopia Collection [boxset]/collection.xml' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.LocalMetadata.Savers.BaseXmlSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-10-10 23:19:24.307 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "The Dark Knight Collection" cannot be found at "/data/media/movies/The Dark Knight Rises (2012)/The Dark Knight Rises (2012) [imdbid-tt1345836] - [Remux-2160p][HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.307 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "The Dark Knight Collection" cannot be found at "/data/media/movies/The Dark Knight (2008)/The Dark Knight (2008) [imdbid-tt0468569] - [Remux-2160p Proper][HDR10][DTS-HD MA 5.1][HEVC]-FGT.mkv"
[2024-10-10 23:19:24.307 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "The Dark Knight Collection" cannot be found at "/data/media/movies/Batman Begins (2005)/Batman Begins (2005) [imdbid-tt0372784] - [Unknown][HDR10][DTS-HD MA 5.1][h265]-OLDHAM.m2ts"
[2024-10-10 23:19:24.308 +02:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: The process cannot access the file '/config/data/collections/The Dark Knight Collection [boxset]/collection.xml' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.LocalMetadata.Savers.BaseXmlSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-10-10 23:19:24.433 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars Episode I - The Phantom Menace (1999)/Star Wars Episode I The Phantom Menace (1999) [imdbid-tt0120915] - [WEBDL-2160p][HDR10][TrueHD Atmos 7.1][h265].mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars Episode II - Attack of the Clones (2002)/Star Wars Episode II Attack of the Clones (2002) [imdbid-tt0121765] - [Remux-2160p Proper][HDR10][TrueHD Atmos 7.1][HEVC]-FGT.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars Episode III - Revenge of the Sith (2005)/Star Wars Episode III Revenge of the Sith (2005) [imdbid-tt0121766] - [Bluray-2160p Proper][HDR10][TrueHD Atmos 7.1][h265]-HD.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars (1977)/Star Wars (1977) [imdbid-tt0076759] - [Remux-2160p][HDR10][TrueHD Atmos 7.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars The Rise of Skywalker (2019)/Star Wars The Rise of Skywalker (2019) [imdbid-tt2527338] - [Remux-2160p Proper][HDR10][TrueHD Atmos 7.1][HEVC]-FGT.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/The Empire Strikes Back (1980)/The Empire Strikes Back (1980) [imdbid-tt0080684] - [Remux-2160p][HDR10][TrueHD Atmos 7.1][HEVC]-SiCFoI.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Return of the Jedi (1983)/Return of the Jedi (1983) [imdbid-tt0086190] - [Remux-2160p][HDR10][TrueHD Atmos 7.1][HEVC]-EPSiLON.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars The Force Awakens (2015)/Star Wars The Force Awakens (2015) [imdbid-tt2488496] - [Bluray-2160p][HDR10][TrueHD Atmos 7.1][h265]-MONUMENT.mkv"
[2024-10-10 23:19:24.434 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "/data/media/movies/Star Wars The Last Jedi (2017)/Star Wars The Last Jedi (2017) [imdbid-tt2527336] - [Unknown][HDR10][TrueHD Atmos 7.1][h265]-OMFUG.m2ts"
[2024-10-10 23:19:24.435 +02:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: The process cannot access the file '/config/data/collections/Star Wars Collection [boxset]/collection.xml' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.LocalMetadata.Savers.BaseXmlSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-10-10 23:19:24.480 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Lord of the Rings" cannot be found at "/data/media/movies/The Lord of the Rings The Fellowship of the Ring (2001)/The Lord of the Rings The Fellowship of the Ring (2001) [imdbid-tt0120737] - Extended [Remux-2160p][DV HDR10][TrueHD Atmos 7.1][HEVC]-decibeL.mkv"
[2024-10-10 23:19:24.480 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Lord of the Rings" cannot be found at "/data/media/movies/The Lord of the Rings The Return of the King (2003)/The Lord of the Rings The Return of the King (2003) [imdbid-tt0167260] - Extended [Remux-2160p][DV HDR10][TrueHD Atmos 7.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.480 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Lord of the Rings" cannot be found at "/data/media/movies/The Lord of the Rings The Two Towers (2002)/The Lord of the Rings The Two Towers (2002) [imdbid-tt0167261] - Extended Cut [Remux-2160p][DV HDR10][TrueHD Atmos 7.1][HEVC]-THM.mkv"
[2024-10-10 23:19:24.483 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean At World's End (2007)/Pirates of the Caribbean At Worlds End (2007) [imdbid-tt0449088] - [Bluray-2160p][HDR10][TrueHD Atmos 7.1][x265]-LAMA.mkv"
[2024-10-10 23:19:24.483 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean The Curse of the Black Pearl (2003)/Pirates of the Caribbean The Curse of the Black Pearl (2003) [imdbid-tt0325980] - [BR-DISK][TrueHD 5.1][AVC]-PiR8.mkv"
[2024-10-10 23:19:24.483 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean Dead Man's Chest (2006)/Pirates of the Caribbean Dead Mans Chest (2006) [imdbid-tt0383574] - [BR-DISK][TrueHD 5.1][AVC]-PiR8.mkv"
[2024-10-10 23:19:24.484 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean Dead Men Tell No Tales (2017)/Pirates of the Caribbean Dead Men Tell No Tales (2017) [imdbid-tt1790809] - [BR-DISK][DTS-HD MA 7.1][AVC]-PiR8.mkv"
[2024-10-10 23:19:24.484 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean On Stranger Tides (2011)/Pirates of the Caribbean On Stranger Tides (2011) [imdbid-tt1298650] - [BR-DISK][DTS-HD MA 7.1][AVC]-PiR8.mkv"
[2024-10-10 23:19:24.484 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Pirates of the Caribbean Collection" cannot be found at "/data/media/movies/Pirates of the Caribbean Tales of the Code Wedlocked (2011)/Pirates of the Caribbean Tales of the Code Wedlocked (2011) [imdbid-tt2092452] - [Bluray-1080p][AAC 5.1][x265].mkv"
[2024-10-10 23:19:24.485 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Indiana Jones Collection" cannot be found at "/data/media/movies/Indiana Jones and the Dial of Destiny (2023)/Indiana Jones and the Dial of Destiny (2023) [imdbid-tt1462764] - [Remux-2160p][DV HDR10][TrueHD Atmos 7.1][HEVC]-CiNEPHiLES.mkv"
[2024-10-10 23:19:24.485 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Indiana Jones Collection" cannot be found at "/data/media/movies/Indiana Jones and the Temple of Doom (1984)/Indiana Jones and the Temple of Doom (1984) [imdbid-tt0087469] - [Remux-2160p][DV HDR10][TrueHD Atmos 7.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.485 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Indiana Jones Collection" cannot be found at "/data/media/movies/Indiana Jones and the Last Crusade (1989)/Indiana Jones and the Last Crusade (1989) [imdbid-tt0097576] - [Remux-2160p][HDR10][TrueHD Atmos 7.1][HEVC]-LEGi0N.mkv"
[2024-10-10 23:19:24.485 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Indiana Jones Collection" cannot be found at "/data/media/movies/Indiana Jones and the Kingdom of the Crystal Skull (2008)/Indiana Jones and the Kingdom of the Crystal Skull (2008) [imdbid-tt0367882] - [Unknown][DV HDR10][TrueHD Atmos 7.1][HEVC]-UnKn0wn.mkv"
[2024-10-10 23:19:24.486 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Indiana Jones Collection" cannot be found at "/data/media/movies/Raiders of the Lost Ark (1981)/Raiders of the Lost Ark (1981) [imdbid-tt0082971] - [WEBDL-2160p][DV HDR10][TrueHD Atmos 7.1][h265].mkv"
[2024-10-10 23:19:24.507 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Movie playlist" cannot be found at "/data/media/movies/The Ring (2002)/The Ring (2002) [imdbid-tt0298130] - [Remux-2160p][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.510 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Series playlist" cannot be found at "/data/media/tv/Chernobyl/Season 01/Chernobyl (2019) - S01E01 - 12345 [Bluray-2160p Remux][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.511 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Series playlist" cannot be found at "/data/media/tv/Chernobyl/Season 01/Chernobyl (2019) - S01E02 - Please Remain Calm [Bluray-2160p Remux][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.511 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Series playlist" cannot be found at "/data/media/tv/Chernobyl/Season 01/Chernobyl (2019) - S01E03 - Open Wide O Earth [Bluray-2160p Remux][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.511 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Series playlist" cannot be found at "/data/media/tv/Chernobyl/Season 01/Chernobyl (2019) - S01E04 - The Happiness of All Mankind [Bluray-2160p Remux][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.511 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Series playlist" cannot be found at "/data/media/tv/Chernobyl/Season 01/Chernobyl (2019) - S01E05 - Vichnaya Pamyat [Bluray-2160p Remux][DV HDR10][DTS-HD MA 5.1][HEVC]-FraMeSToR.mkv"
[2024-10-10 23:19:24.512 +02:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: The process cannot access the file '/config/data/playlists/Series playlist/playlist.xml' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.LocalMetadata.Savers.BaseXmlSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-10-10 23:19:24.526 +02:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
```

**Comment by pimw1** [comment]
Bump; from previous discord conversations, i understood that this is something that can be looked into after merging https://github.com/jellyfin/jellyfin/pull/12798

**Comment by pimw1** [comment]
https://github.com/jellyfin/jellyfin/pull/12798 is merged.
Question: are collections more gracefully handled since the [Refactor library.db into jellyfin.db and EFCore] ? If not, i'll keep the incident open.

**Comment by theguymadmax** [comment]
Closing as duplicate of #12734
