### ISSUE TITLE
Unable to login from EmbyCon

### ISSUE THREAD

**Issue by fandangos** [jellyfin/jellyfin#1281]
Server: Unraid 6.7.0 using Jellyfin docker 10.3.0

Login from Browser works. 
Login from EmbyCon shows access denied.

Log:
`[2019-04-22 09:40:16.937 -03:00] [INF] "Scan media library" Completed after 0 minute(s) and 1 seconds
[2019-04-22 09:40:16.939 -03:00] [INF] ExecuteQueuedTasks
[2019-04-22 09:40:18.694 -03:00] [INF] WS "http://192.168.0.198:8097/embywebsocket?api_key=d5305bee3e844051840d1ca835ff75e5&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzczLjAuMzY4My4xMDMgU2FmYXJpLzUzNy4zNnwxNTU1OTI5MDQzMzY5". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
[2019-04-22 09:40:18.695 -03:00] [WRN] Unable to determine session based on url: "http://192.168.0.198:8097/embywebsocket?api_key=d5305bee3e844051840d1ca835ff75e5&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzczLjAuMzY4My4xMDMgU2FmYXJpLzUzNy4zNnwxNTU1OTI5MDQzMzY5"
[2019-04-22 09:40:23.131 -03:00] [ERR] Error authenticating with provider "Default"
System.Exception: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Library/DefaultAuthenticationProvider.cs:line 37
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Library/UserManager.cs:line 436
[2019-04-22 09:40:23.141 -03:00] [INF] Authentication request for "TOWER" "has been denied".
[2019-04-22 09:40:23.148 -03:00] [ERR] Invalid user or password entered.
[2019-04-22 09:40:39.280 -03:00] [INF] Authentication request for "TOWER" "has succeeded".
[2019-04-22 09:40:39.287 -03:00] [INF] Creating new access token for user 660143f0-2460-4155-ab30-3a381fbfb402
[2019-04-22 09:40:40.346 -03:00] [WRN] HTTP Response 204 to "192.168.0.177". Time (slow): 0:00:00.7370765. "http://192.168.0.198:8097/emby/Sessions/Capabilities/Full"
[2019-04-22 09:40:40.412 -03:00] [WRN] HTTP Response 200 to "192.168.0.177". Time (slow): 0:00:00.6444198. "http://192.168.0.198:8097/emby/System/Info"
[2019-04-22 09:41:38.296 -03:00] [INF] Authentication request for "TOWER" "has been denied".
[2019-04-22 09:41:38.309 -03:00] [ERR] Invalid user or password entered.
[2019-04-22 09:41:38.464 -03:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: username
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Library/UserManager.cs:line 362
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Session/SessionManager.cs:line 1439
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/MediaBrowser.Api/UserService.cs:line 399
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/pkgbuild-0/jellyfin/src/jellyfin-10.3.0/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-04-22 09:46:12.670 -03:00] [INF] Jellyfin version: "10.3.0.0"
[2019-04-22 09:46:12.756 -03:00] [INF] Arguments: ["/usr/lib/jellyfin/jellyfin.dll", "--datadir", "/config/data", "--cachedir", "/config/cache", "--configdir", "/config/config", "--logdir", "/config/logs", "--ffmpeg", "/usr/bin/ffmpeg"]
[2019-04-22 09:46:12.790 -03:00] [INF] Operating system: "Linux" "4.18.20.0"
[2019-04-22 09:46:12.791 -03:00] [INF] Architecture: X64
[2019-04-22 09:46:12.798 -03:00] [INF] 64-Bit Process: True
[2019-04-22 09:46:12.799 -03:00] [INF] User Interactive: True
[2019-04-22 09:46:12.799 -03:00] [INF] Processor count: 4
[2019-04-22 09:46:12.800 -03:00] [INF] Program data path: "/config/data"
[2019-04-22 09:46:12.800 -03:00] [INF] Web resources path: "/usr/lib/jellyfin/jellyfin-web/src"
[2019-04-22 09:46:12.801 -03:00] [INF] Application directory: "/usr/lib/jellyfin/"
[2019-04-22 09:46:13.303 -03:00] [INF] Setting cache path to /config/cache
[2019-04-22 09:46:13.417 -03:00] [INF] Loading assemblies
[2019-04-22 09:46:13.760 -03:00] [INF] Sqlite version: 3.26.0
[2019-04-22 09:46:13.764 -03:00] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[2019-04-22 09:46:13.878 -03:00] [INF] Default journal_mode for "/config/data/data/users.db" is "wal"
[2019-04-22 09:46:13.893 -03:00] [INF] PRAGMA synchronous=1
[2019-04-22 09:46:14.507 -03:00] [INF] Default journal_mode for "/config/data/data/authentication.db" is "wal"
[2019-04-22 09:46:14.507 -03:00] [INF] PRAGMA synchronous=1
[2019-04-22 09:46:14.680 -03:00] [INF] Default journal_mode for "/config/data/data/activitylog.db" is "wal"
[2019-04-22 09:46:14.680 -03:00] [INF] PRAGMA synchronous=1
[2019-04-22 09:46:14.692 -03:00] [INF] Default journal_mode for "/config/data/data/displaypreferences.db" is "wal"
[2019-04-22 09:46:14.692 -03:00] [INF] PRAGMA synchronous=1
[2019-04-22 09:46:14.909 -03:00] [INF] Default journal_mode for "/config/data/data/library.db" is "wal"
[2019-04-22 09:46:14.910 -03:00] [INF] PRAGMA synchronous=1
[2019-04-22 09:46:15.232 -03:00] [INF] Calling ServiceStack AppHost.Init
[2019-04-22 09:46:19.281 -03:00] [INF] SkiaSharp version: 1.68.0.0
[2019-04-22 09:46:19.301 -03:00] [INF] Running startup tasks
[2019-04-22 09:46:19.371 -03:00] [INF] Daily trigger for "Chapter image extraction" set to fire at 04/23/2019 02:00, which is 16:13:40.6288903 from now.
[2019-04-22 09:46:19.616 -03:00] [INF] FFmpeg validation: Found ffmpeg version "4.1"
[2019-04-22 09:46:19.616 -03:00] [WRN] FFmpeg validation: The maximum recommended ffmpeg version is "4.0"
[2019-04-22 09:46:19.616 -03:00] [WRN] FFmpeg: "SetByArgument": Failed version check: "/usr/bin/ffmpeg"
[2019-04-22 09:46:19.646 -03:00] [INF] Validating media encoder at "/usr/bin/ffmpeg"
[2019-04-22 09:46:19.778 -03:00] [INF] Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2019-04-22 09:46:19.900 -03:00] [INF] Available "encoders": ["libx264", "h264_nvenc", "h264_omx", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2019-04-22 09:46:19.900 -03:00] [INF] Encoder validation complete
[2019-04-22 09:46:19.904 -03:00] [INF] FFmpeg: "SetByArgument": "/usr/bin/ffmpeg"
[2019-04-22 09:46:19.920 -03:00] [INF] ServerId: "0771c4f8c156458d8e7749d343e683b8"
[2019-04-22 09:46:20.794 -03:00] [INF] Executed all pre-startup entry points in 0:00:00.7887874
[2019-04-22 09:46:20.794 -03:00] [INF] Core startup complete
[2019-04-22 09:46:21.449 -03:00] [WRN] "GetItemList" query time (slow): 332.0421. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-04-22 09:46:21.795 -03:00] [INF] Executed all post-startup entry points in 0:00:01.0004666
[2019-04-22 09:46:22.454 -03:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2019-04-22 09:46:22.464 -03:00] [INF] Queueing task "PluginUpdateTask"
[2019-04-22 09:46:22.501 -03:00] [INF] Executing "Check for plugin updates"
[2019-04-22 09:46:22.510 -03:00] [WRN] HTTP Response 200 to "172.17.0.4". Time (slow): 0:00:00.6603378. "http://172.17.0.4:8096/system/ping"
[2019-04-22 09:46:22.592 -03:00] [INF] HttpClientManager "GET": "https://repo.jellyfin.org/releases/plugin/manifest.json"
[2019-04-22 09:46:22.613 -03:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "172.17.0.4"
[2019-04-22 09:46:23.699 -03:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 1 seconds
[2019-04-22 09:46:23.959 -03:00] [INF] ExecuteQueuedTasks
[2019-04-22 09:47:43.337 -03:00] [WRN] HTTP Response 200 to "192.168.0.177". Time (slow): 0:00:01.1600051. "http://192.168.0.198:8097/emby/System/Info"
[2019-04-22 09:47:43.402 -03:00] [INF] WS "http://192.168.0.198:8097/embywebsocket?api_key=97f964a49d394ae59329cdcf520ac997&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzczLjAuMzY4My4xMDMgU2FmYXJpLzUzNy4zNnwxNTU1OTI5MDQzMzY5". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
[2019-04-22 09:47:43.966 -03:00] [WRN] HTTP Response 204 to "192.168.0.177". Time (slow): 0:00:00.6220193. "http://192.168.0.198:8097/emby/Sessions/Capabilities/Full"`

Attempt with or without password same result.
Tried to create different users. Same result.

Always access denied.

**Comment by sparky8251** [comment]
Wonder if EmbyCon sends a prehashed password like Yatse used to?

If so, we definitely *purposefully* broke that and EmbyCon will have to update to fix it.

**Comment by fandangos** [comment]
I've tried it with Jellyfin for Kodi and I was able to log in normaly. 

So, it's a embycon thing.

**Comment by Zandengoff** [comment]
Can confirm also getting a connection error on EmbyforKodi with 10.3.1 . Going to revert back to 10.2 for now as my Kodi boxes are my main clients. Has anyone reported this to the EmbyforKodi dev yet?

**Comment by cvium** [comment]
Emby for Kodi and EmbyCon are not officially supported and the maintainers of said Kodi add-ons do not actively support Jellyfin.

We have our own fork of Emby for Kodi (which could use a hand): https://github.com/jellyfin/jellyfin-kodi
