### ISSUE TITLE
Error creating http port map, stacktrace dump

### ISSUE THREAD

**Issue by RlndVt** [jellyfin/jellyfin#1284]
**Describe the bug**
When starting Jellyfin a error is encountered and stacktrace dump is printed to log. Jellyfin does work fine though.

**To Reproduce**
(re)start Jellyfin.

**Expected behavior**
No error messages/stacktrace dumps

**Logs**
```
[2019-04-23 09:03:56.204 +02:00] [INF] Jellyfin version: "10.3.1.0"
[2019-04-23 09:03:56.228 +02:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2019-04-23 09:03:56.237 +02:00] [INF] Operating system: "Linux" "4.19.0.0"
[2019-04-23 09:03:56.238 +02:00] [INF] Architecture: X64
[2019-04-23 09:03:56.240 +02:00] [INF] 64-Bit Process: True
[2019-04-23 09:03:56.240 +02:00] [INF] User Interactive: True
[2019-04-23 09:03:56.240 +02:00] [INF] Processor count: 2
[2019-04-23 09:03:56.240 +02:00] [INF] Program data path: "/var/lib/jellyfin"
[2019-04-23 09:03:56.240 +02:00] [INF] Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web/src"
[2019-04-23 09:03:56.240 +02:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2019-04-23 09:03:56.387 +02:00] [INF] Setting cache path to /mnt/dionysus/jellyfin
[2019-04-23 09:03:56.416 +02:00] [INF] Loading assemblies
[2019-04-23 09:03:56.426 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll"
[2019-04-23 09:03:56.428 +02:00] [INF] Loaded assembly "OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles/OpenSubtitlesHandler.dll"
[2019-04-23 09:03:56.429 +02:00] [INF] Loaded assembly "Emby.AutoOrganize, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Auto Organize/Emby.AutoOrganize.dll"
[2019-04-23 09:03:56.431 +02:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TMDb Box Sets/Jellyfin.Plugin.TMDbBoxSets.dll"
[2019-04-23 09:03:56.510 +02:00] [INF] Sqlite version: 3.26.0
[2019-04-23 09:03:56.511 +02:00] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[2019-04-23 09:03:56.540 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/users.db" is "wal"
[2019-04-23 09:03:56.543 +02:00] [INF] PRAGMA synchronous=1
[2019-04-23 09:03:56.700 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/authentication.db" is "wal"
[2019-04-23 09:03:56.700 +02:00] [INF] PRAGMA synchronous=1
[2019-04-23 09:03:56.753 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/activitylog.db" is "wal"
[2019-04-23 09:03:56.753 +02:00] [INF] PRAGMA synchronous=1
[2019-04-23 09:03:56.756 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/displaypreferences.db" is "wal"
[2019-04-23 09:03:56.756 +02:00] [INF] PRAGMA synchronous=1
[2019-04-23 09:03:56.803 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/library.db" is "wal"
[2019-04-23 09:03:56.803 +02:00] [INF] PRAGMA synchronous=1
[2019-04-23 09:03:56.904 +02:00] [INF] Calling ServiceStack AppHost.Init
[2019-04-23 09:03:57.744 +02:00] [INF] SkiaSharp version: 1.68.0.0
[2019-04-23 09:03:57.749 +02:00] [INF] Running startup tasks
[2019-04-23 09:03:57.780 +02:00] [INF] Daily trigger for "Chapter image extraction" set to fire at 04/24/2019 02:00, which is 16:56:02.2190951 from now.
[2019-04-23 09:03:57.827 +02:00] [INF] FFmpeg validation: Found ffmpeg version "4.0"
[2019-04-23 09:03:57.827 +02:00] [INF] FFmpeg validation: Found suitable ffmpeg version
[2019-04-23 09:03:57.834 +02:00] [INF] Validating media encoder at "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2019-04-23 09:03:57.852 +02:00] [INF] Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2019-04-23 09:03:57.866 +02:00] [INF] Available "encoders": ["libx264", "h264_nvenc", "h264_omx", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2019-04-23 09:03:57.866 +02:00] [INF] Encoder validation complete
[2019-04-23 09:03:57.866 +02:00] [INF] FFmpeg: "Custom": "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2019-04-23 09:03:57.868 +02:00] [INF] ServerId: "33480fd5bb714f9991bd1a00d8dacf16"
[2019-04-23 09:03:58.010 +02:00] [INF] Executed all pre-startup entry points in 0:00:00.1278359
[2019-04-23 09:03:58.010 +02:00] [INF] Core startup complete
[2019-04-23 09:03:58.015 +02:00] [INF] Sqlite version: "3.26.0"
[2019-04-23 09:03:58.015 +02:00] [INF] Sqlite compiler options: "COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1"
[2019-04-23 09:03:58.015 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/fileorganization.db" is "wal"
[2019-04-23 09:03:58.017 +02:00] [INF] PRAGMA synchronous="1"
[2019-04-23 09:03:58.304 +02:00] [INF] Watching directory /mnt/dionysus/Media/Movies
[2019-04-23 09:03:58.331 +02:00] [INF] Watching directory /mnt/dionysus/Media/TV Shows
[2019-04-23 09:03:58.333 +02:00] [INF] Executed all post-startup entry points in 0:00:00.3225513
[2019-04-23 09:04:00.792 +02:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2019-04-23 09:04:00.795 +02:00] [INF] Queueing task "PluginUpdateTask"
[2019-04-23 09:04:00.803 +02:00] [INF] Executing "Check for plugin updates"
[2019-04-23 09:04:00.835 +02:00] [INF] HttpClientManager "GET": "https://repo.jellyfin.org/releases/plugin/manifest.json"
[2019-04-23 09:04:01.435 +02:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 0 seconds
[2019-04-23 09:04:01.502 +02:00] [INF] ExecuteQueuedTasks
[2019-04-23 09:04:03.923 +02:00] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)
```

**System (please complete the following information):**
 - OS: Debian GNU/Linux 9 (stretch)
 - Jellyfin Version: 10.3.1 (also seen in previous versions)
 - Reverse proxy: nginx

**Comment by phob** [comment]
I get the same error on an on
```
[2019-12-01 01:16:15.803 +01:00] [ERR] Error creating http port map
System.Net.Http.HttpRequestException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.ThrowInvalidHttpResponse()
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)
```

**Comment by anthonylavado** [comment]
This error appears if you have the “Enable automatic port mapping” setting turned on (I think it’s on by default, you are asked during setup). It’s trying to see if it can automatically open the port for you on your router, but it can’t do it.

To turn it off, go to:
- Dashboard
- Advanced > Networking
- Scroll to the bottom and disable 🔲 automatic port mapping

**Comment by tayhr** [comment]
> This error appears if you have the “Enable automatic port mapping” setting turned on (I think it’s on by default, you are asked during setup). It’s trying to see if it can automatically open the port for you on your router, but it can’t do it.
> 
> To turn it off, go to:
> 
> * Dashboard
> * Advanced > Networking
> * Scroll to the bottom and disable 🔲 automatic port mapping

I tried to disable the option but everytime I press the save button a warning pop-up appears twice 
 blocking the save event
![image](https://user-images.githubusercontent.com/18019271/75627746-ab547780-5bb1-11ea-8f2d-1fb94d606ad3.png)
