### ISSUE TITLE
Unable to connect via Android App: "Connection cannot be established. Please check the hostname and your network connection."

### ISSUE THREAD

**Issue by DGamerism** [jellyfin/jellyfin#12873]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Android app is unable to connect after updating server to 10.9.11 from 10.8.13
Android version app 2.6.2

When attempting to connect, I'm receiving the message:
> Connection cannot be established.
> Please check the hostname and your network connection.
This appears after a brief blipped view of the login screen.

Occurs when entering the IP, entering the URL, or selecting the server from the discovered "Connect to Server" prompt.

Error is different than a standard network error/incorrect address, and occurs on the same network or any outside network.
Error does not occur on any other access like web browser, only the android app.

### Reproduction steps

Open android app.
Enter IP, URL, or select from Choose a Server
Error.

### What is the current _bug_ behavior?

Login page shows briefly then the error message appears.

### What is the expected _correct_ behavior?

Login page.

### Jellyfin Server version

10.9.11+

### Specify commit id

N/A

### Specify unstable release number

N/A

### Specify version number

10.9.11

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: Android
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration:
- GPU Model: RTX 4070
- Plugins: 
- Reverse Proxy: Caddy
- Base URL:
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2024-10-24 20:55:41.492 -04:00] [INF] [1] Main: Jellyfin version: "10.9.11"
[2024-10-24 20:55:41.505 -04:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, E:\Jellyfin\Data\log]"]
[2024-10-24 20:55:41.507 -04:00] [INF] [1] Main: Arguments: ["E:\Jellyfin\Server\jellyfin.dll", "--datadir", "E:\Jellyfin\Data"]
[2024-10-24 20:55:41.508 -04:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.19045"
[2024-10-24 20:55:41.508 -04:00] [INF] [1] Main: Architecture: X64
[2024-10-24 20:55:41.509 -04:00] [INF] [1] Main: 64-Bit Process: True
[2024-10-24 20:55:41.509 -04:00] [INF] [1] Main: User Interactive: True
[2024-10-24 20:55:41.510 -04:00] [INF] [1] Main: Processor count: 20
[2024-10-24 20:55:41.511 -04:00] [INF] [1] Main: Program data path: "E:\Jellyfin\Data"
[2024-10-24 20:55:41.511 -04:00] [INF] [1] Main: Log directory path: "E:\Jellyfin\Data\log"
[2024-10-24 20:55:41.512 -04:00] [INF] [1] Main: Config directory path: "E:\Jellyfin\Data\config"
[2024-10-24 20:55:41.512 -04:00] [INF] [1] Main: Cache path: "E:\Jellyfin\Data\cache"
[2024-10-24 20:55:41.513 -04:00] [INF] [1] Main: Web resources path: "E:\Jellyfin\Server\jellyfin-web"
[2024-10-24 20:55:41.513 -04:00] [INF] [1] Main: Application directory: "E:\Jellyfin\Server\"
[2024-10-24 20:55:41.587 -04:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "E:\Jellyfin\Data\cache"
[2024-10-24 20:55:41.630 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-10-24 20:55:41.640 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "jellyfin-ani-sync, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\Ani-Sync_3.4.0.0\jellyfin-ani-sync.dll"
[2024-10-24 20:55:41.642 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\AniList_9.0.0.0\Jellyfin.Plugin.AniList.dll"
[2024-10-24 20:55:41.646 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\DLNA_3.0.0.0\Jellyfin.Plugin.Dlna.dll"
[2024-10-24 20:55:41.647 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Model, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\DLNA_3.0.0.0\Jellyfin.Plugin.Dlna.Model.dll"
[2024-10-24 20:55:41.648 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Playback, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\DLNA_3.0.0.0\Jellyfin.Plugin.Dlna.Playback.dll"
[2024-10-24 20:55:41.649 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Rssdp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\DLNA_3.0.0.0\Rssdp.dll"
[2024-10-24 20:55:41.651 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "E:\Jellyfin\Data\plugins\Open Subtitles_20.0.0.0\Jellyfin.Plugin.OpenSubtitles.dll"
[2024-10-24 20:55:41.743 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-24 20:55:41.745 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-10-24 20:55:41.745 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-24 20:55:41.747 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: [REDACT]
[2024-10-24 20:55:41.748 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-10-24 20:55:41.749 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-10-24 20:55:41.749 -04:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-10-24 20:55:45.659 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Ani-Sync" "3.4.0.0"
[2024-10-24 20:55:45.660 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "9.0.0.0"
[2024-10-24 20:55:45.661 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "DLNA" "3.0.0.0"
[2024-10-24 20:55:45.667 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "20.0.0.0"
[2024-10-24 20:55:45.668 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.11.0"
[2024-10-24 20:55:45.668 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.11.0"
[2024-10-24 20:55:45.669 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.11.0"
[2024-10-24 20:55:45.681 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.11.0"
[2024-10-24 20:55:45.681 -04:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.11.0"
[2024-10-24 20:55:45.742 -04:00] [INF] [1] Main: Kestrel is listening on "0.0.0.0"
[2024-10-24 20:55:45.831 -04:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1" with uri "http://127.0.0.1:8096/dlna/a097ff4c-9c63-4b83-a6ca-079176af4358/description.xml"
[2024-10-24 20:55:45.844 -04:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.4.25" with uri "http://192.168.4.25:8096/dlna/a097ff4c-9c63-4b83-a6ca-079176af4358/description.xml"
[2024-10-24 20:55:45.959 -04:00] [INF] [1] Jellyfin.Networking.PortForwardingHost: Starting NAT discovery
[2024-10-24 20:55:46.269 -04:00] [ERR] [10] Jellyfin.Networking.PortForwardingHost: Error creating port map on local port 8096 to public port 8089 with device "192.168.4.1:1900".
Mono.Nat.MappingException: Error ConflictInMappingEntry: ConflictInMappingEntry
   at Mono.Nat.Upnp.ResponseMessage.Decode(UpnpNatDevice device, String message)
   at Mono.Nat.Upnp.UpnpNatDevice.DecodeMessageFromResponse(Stream s, Int32 length)
   at Mono.Nat.Upnp.UpnpNatDevice.SendMessageAsync(RequestMessage message)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMapAsync(Mapping mapping)
   at Jellyfin.Networking.PortForwardingHost.CreatePortMap(INatDevice device, Int32 privatePort, Int32 publicPort)
[2024-10-24 20:55:46.528 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-10-24 20:55:46.528 -04:00] [INF] [7] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\Jellyfin Movies (Temp)"
[2024-10-24 20:55:46.528 -04:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Jellyfin\Media\Books"
[2024-10-24 20:55:46.528 -04:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Jellyfin\Media\TV Shows"
[2024-10-24 20:55:46.528 -04:00] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Media\Movies"
[2024-10-24 20:55:46.528 -04:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Jellyfin\Media\Movies"
[2024-10-24 20:55:46.528 -04:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Media\Shows"
[2024-10-24 20:55:46.541 -04:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-10-25 03:00:00.000 -04:00, which is 06:04:13.4583233 from now.
[2024-10-24 20:55:46.544 -04:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-10-25 02:00:00.000 -04:00, which is 05:04:13.4556918 from now.
[2024-10-24 20:55:46.584 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-10-24 20:55:46.608 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-10-24 20:55:46.629 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mjpeg_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-10-24 20:55:46.650 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-10-24 20:55:46.726 -04:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2024-10-24 20:55:46.742 -04:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vulkan" with option "Action to take when encountering EOF from secondary input" is not available
[2024-10-24 20:55:46.758 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2024-10-24 20:55:46.922 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2024-10-24 20:55:46.923 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "a097ff4c9c634b83a6ca079176af4358"
[2024-10-24 20:55:46.924 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-10-24 20:55:46.924 -04:00] [INF] [1] Main: Startup complete 0:00:05.5170895
[2024-10-24 20:55:49.552 -04:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-10-24 20:55:50.756 -04:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
```

### FFmpeg logs

```shell
N/A
```

### Client / Browser logs

N/A

### Relevant screenshots or videos

https://github.com/user-attachments/assets/b37e2dee-07b5-4edb-80d6-6466f0abdb19

### Additional information

I have tested this on various android devices.
A Fold 4, note 20, and Android Emulator

**Comment by doakey3** [comment]
Check to see if you are connected to a VPN. You won't be able to connect to a local network server if you are routing through a VPN.

**Comment by DGamerism** [comment]
No vpn used. I've tested over various network types. Home network, mobile
data, with vpn, and 3 other wifi connections.

**Comment by felix920506** [comment]
Does it work in a browser

**Comment by DGamerism** [comment]
Yes, all other devices used work fine for me. Browsers have been Firefox,
Chrome, Samsung Internet, and Safari as well as the IOS app.
Only android seems to be affected, I've tried on 2 physical phones and an
android emulator.

**Comment by felix920506** [comment]
Does it work if you disable ipv6?

**Comment by Aer0l0gic** [comment]
I think what solved this for me was clearing out the remote IP address filter. I suggest checking that if it's something you have configured.

**Comment by DGamerism** [comment]
Ipv6 is disabled and the error persists.

I have no remote ip filters, the field is blank to allow all addresses.
I have tried disabling remote connections, restarting, then enabling it
again but same issue.

It will looks like it connects and provides the login prompt for a few
frames, then boots back to the ip entry with the connection cannot be
established error.

**Comment by felix920506** [comment]
Does the same device connect with a browser?

**Comment by DGamerism** [comment]
Yes, connecting via browser on the same device works, only the android app
gives the error.

**Comment by iluvatyr** [comment]
I have the same problem. I am using jellyfin for several years now. Only now it logged me out of the jellyfin app and I cannot connect anymore. Going to the browser. I can use it just fine..
