### ISSUE TITLE
Duplicate libraries/media folders appear

### ISSUE THREAD

**Issue by Kladki** [jellyfin/jellyfin#12871]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Recently, I had let my disk become full, and hence had some issues with starting Jellyfin. In trying to fix it, I deleted the cache directory. After freeing more space on the disk, and fixing the errors stopping Jellyfin from starting, there was only one of each library, and media was being re-scanned since I deleted the cache. The next day, I noticed that there were suddenly two of each library visible on the homepage and library page, but not on the admin dashboard.

### Reproduction steps

1. Log onto Jellyfin from any client
2. Click on the sidebar or just look at "recently added" sections on the homepage
3. See issue

### What is the current _bug_ behavior?

There are two of each library visible, even though there is only one of each in the admin UI (as it should be).

### What is the expected _correct_ behavior?

There should only be one of each

### Jellyfin Server version

10.9.11+

### Specify the build version

Release

### Environment

```markdown
- OS: Alpine Linux
- Linux Kernel: 6.6.56
- Virtualization: None
- Clients: Browser, Findroid
- Browser: Firefox 131.0.1
- FFmpeg Version: 6.0.1_p7 (Jellyfin)
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: 
- Reverse Proxy: None
- Base URL: None
- Networking: Wireguard
- Storage: local
```

### Jellyfin logs

```shell
[2024-10-24 13:31:06.007 +01:00] [INF] [1] Main: Jellyfin version: "10.9.11"
[2024-10-24 13:31:06.062 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
[2024-10-24 13:31:06.066 +01:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/jellyfin.dll", "--webdir", "/usr/share/webapps/jellyfin-web", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin", "--logdir", "/var/log/jellyfin", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-10-24 13:31:06.066 +01:00] [INF] [1] Main: Operating system: "Alpine Linux edge"
[2024-10-24 13:31:06.066 +01:00] [INF] [1] Main: Architecture: X64
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: 64-Bit Process: True
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: User Interactive: True
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: Processor count: 2
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: Program data path: "/var/lib/jellyfin"
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: Log directory path: "/var/log/jellyfin"
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: Config directory path: "/var/lib/jellyfin/config"
[2024-10-24 13:31:06.067 +01:00] [INF] [1] Main: Cache path: "/var/cache/jellyfin"
[2024-10-24 13:31:06.068 +01:00] [INF] [1] Main: Web resources path: "/usr/share/webapps/jellyfin-web"
[2024-10-24 13:31:06.068 +01:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/"
[2024-10-24 13:31:06.293 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/var/cache/jellyfin"
[2024-10-24 13:31:06.433 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-10-24 13:31:06.477 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "jellyfin-ani-sync, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Ani-Sync_3.4.0.0/jellyfin-ani-sync.dll"
[2024-10-24 13:31:06.479 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AngleSharp.XPath, Version=2.0.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea" from "/var/lib/jellyfin/plugins/Apple Music_1.0.1.3/AngleSharp.XPath.dll"
[2024-10-24 13:31:06.482 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ITunes, Version=1.0.1.3, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Apple Music_1.0.1.3/Jellyfin.Plugin.ITunes.dll"
[2024-10-24 13:31:06.517 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AngleSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea" from "/var/lib/jellyfin/plugins/Apple Music_1.0.1.3/AngleSharp.dll"
[2024-10-24 13:31:06.518 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Namo.Plugin.InPlayerEpisodePreview, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/InPlayerEpisodePreview_1.2.4.0/Namo.Plugin.InPlayerEpisodePreview.dll"
[2024-10-24 13:31:06.521 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "ConfusedPolarBear.Plugin.IntroSkipper, Version=1.0.0.6, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Intro Skipper_1.0.0.6/ConfusedPolarBear.Plugin.IntroSkipper.dll"
[2024-10-24 13:31:06.523 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ListenBrainz.Api, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/ListenBrainz_4.0.2.0/Jellyfin.Plugin.ListenBrainz.Api.dll"
[2024-10-24 13:31:06.525 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ListenBrainz, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/ListenBrainz_4.0.2.0/Jellyfin.Plugin.ListenBrainz.dll"
[2024-10-24 13:31:06.525 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ListenBrainz.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/ListenBrainz_4.0.2.0/Jellyfin.Plugin.ListenBrainz.Common.dll"
[2024-10-24 13:31:06.526 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ListenBrainz.Http, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/ListenBrainz_4.0.2.0/Jellyfin.Plugin.ListenBrainz.Http.dll"
[2024-10-24 13:31:06.527 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ListenBrainz.MusicBrainzApi, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/ListenBrainz_4.0.2.0/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll"
[2024-10-24 13:31:06.529 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2024-10-24 13:31:06.533 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll"
[2024-10-24 13:31:06.534 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2024-10-24 13:31:06.534 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SessionCleaner, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Session Cleaner_4.0.0.0/Jellyfin.Plugin.SessionCleaner.dll"
[2024-10-24 13:31:06.542 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_15.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2024-10-24 13:31:06.556 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Tvdb.Sdk, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_15.0.0.0/Tvdb.Sdk.dll"
[2024-10-24 13:31:06.677 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["192.168.1.0/24", "fe80::/64", "192.168.2.0/24", "100.64.0.0/10", "fd7a:115c:a1e0::/48"]
[2024-10-24 13:31:06.677 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-10-24 13:31:06.678 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["192.168.1.0/24", "fe80::/64", "192.168.2.0/24", "100.64.0.0/10", "fd7a:115c:a1e0::/48"]
[2024-10-24 13:31:06.680 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.1.146", "192.168.2.1", "100.64.0.2", "::1", "2a00:23c7:a816:3201:d63d:7eff:fecf:734f", "fe80::d63d:7eff:fecf:734f%2", "fd7a:115c:a1e0::2", "fe80::d81f:2346:b9c3:7886%4"]
[2024-10-24 13:31:06.681 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[2024-10-24 13:31:06.681 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-10-24 13:31:06.681 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-10-24 13:31:11.421 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Ani-Sync" "3.4.0.0"
[2024-10-24 13:31:11.423 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Apple Music" "1.0.1.3"
[2024-10-24 13:31:11.438 +01:00] [INF] [1] Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Attempting to inject preview script code in "/usr/share/webapps/jellyfin-web/index.html"
[2024-10-24 13:31:11.452 +01:00] [ERR] [1] Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Encountered exception while writing to "/usr/share/webapps/jellyfin-web/index.html": "System.UnauthorizedAccessException: Access to the path '/usr/share/webapps/jellyfin-web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)"
[2024-10-24 13:31:11.453 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "InPlayerEpisodePreview" "1.2.4.0"
[2024-10-24 13:31:11.651 +01:00] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. See https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting#skip-button-is-not-visible for the most common issues. Error: "System.UnauthorizedAccessException: Access to the path '/usr/share/webapps/jellyfin-web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.InjectSkipButton(String webPath)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationHost applicationHost, IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)"
[2024-10-24 13:31:11.978 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Intro Skipper" "1.0.0.6"
[2024-10-24 13:31:12.098 +01:00] [INF] [1] Jellyfin.Plugin.ListenBrainz.PluginService: Activating plugin service
[2024-10-24 13:31:12.099 +01:00] [INF] [1] Jellyfin.Plugin.ListenBrainz.PluginService: Plugin service in now active
[2024-10-24 13:31:12.100 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "ListenBrainz" "4.0.2.0"
[2024-10-24 13:31:12.111 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "20.0.0.0"
[2024-10-24 13:31:12.112 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Playback Reporting" "15.0.0.0"
[2024-10-24 13:31:12.114 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Session Cleaner" "4.0.0.0"
[2024-10-24 13:31:12.115 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "15.0.0.0"
[2024-10-24 13:31:12.116 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.11.0"
[2024-10-24 13:31:12.116 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.11.0"
[2024-10-24 13:31:12.117 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.11.0"
[2024-10-24 13:31:12.136 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.11.0"
[2024-10-24 13:31:12.137 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.11.0"
[2024-10-24 13:31:12.358 +01:00] [INF] [1] Main: Kestrel is listening on "all interfaces"
[2024-10-24 13:31:12.378 +01:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Running startup enqueue
[2024-10-24 13:31:12.666 +01:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Collections"
[2024-10-24 13:31:12.684 +01:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Shows"
[2024-10-24 13:31:12.941 +01:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Movies"
[2024-10-24 13:31:12.954 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: EventMonitorEntryPoint Running
[2024-10-24 13:31:12.975 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite version: 3.41.2
[2024-10-24 13:31:12.977 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-9.4.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_FOREIGN_KEYS,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_MATH_FUNCTIONS,ENABLE_RTREE,ENABLE_SNAPSHOT,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=32766,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1
[2024-10-24 13:31:12.997 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for "/var/lib/jellyfin/data/playback_reporting.db" is "delete"
[2024-10-24 13:31:12.998 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Initialize PlaybackActivity Repository
[2024-10-24 13:31:12.998 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: PlaybackActivity table schema OK
[2024-10-24 13:31:12.998 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Expected : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2024-10-24 13:31:12.998 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Received : "datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int"
[2024-10-24 13:31:13.737 +01:00] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/wwwroot". Static files may be unavailable.
[2024-10-24 13:31:13.800 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-10-24 13:31:13.807 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: TaskCleanDb Loaded
[2024-10-24 13:31:13.808 +01:00] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskRunBackup: TaskRunBackup Loaded
[2024-10-24 13:31:13.835 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Detect Intros and Credits" set to fire at 2024-10-25 00:00:00.000 +01:00, which is 10:28:46.1642648 from now.
[2024-10-24 13:31:13.852 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Playback Reporting Trim Db" set to fire at 2024-10-25 00:00:00.000 +01:00, which is 10:28:46.1474049 from now.
[2024-10-24 13:31:13.863 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-10-25 03:00:00.000 +01:00, which is 13:28:46.1367754 from now.
[2024-10-24 13:31:13.865 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-10-25 02:00:00.000 +01:00, which is 12:28:46.1348052 from now.
[2024-10-24 13:31:13.914 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-10-24 13:31:13.972 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_qsv", "h264", "h264_qsv", "hevc", "hevc_qsv", "mpeg2video", "mpeg2_qsv", "mpeg4", "msmpeg4", "vc1_qsv", "vp8", "libvpx", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-10-24 13:31:14.008 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["av1_qsv", "av1_vaapi", "libx264", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-10-24 13:31:14.062 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "procamp_vaapi", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "zscale", "alphasrc"]
[2024-10-24 13:31:14.096 +01:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "scale_cuda" with option "Output format (default \"same\")" is not available
[2024-10-24 13:31:14.129 +01:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "tonemap_cuda" with option "GPU accelerated HDR to SDR tonemapping" is not available
[2024-10-24 13:31:14.291 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-10-24 13:31:15.111 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: VAAPI device "/dev/dri/card0" is Intel GPU (i965)
[2024-10-24 13:31:15.111 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-10-24 13:31:15.113 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "c24abcfbb7b44027b820c562e596949f"
[2024-10-24 13:31:15.113 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-10-24 13:31:15.113 +01:00] [INF] [1] Main: Startup complete 0:00:09.3754808
[2024-10-24 13:31:16.899 +01:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-10-24 13:31:18.322 +01:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2024-10-24 13:36:37.128 +01:00] [INF] [20] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:100.64.0.1" request
[2024-10-24 13:38:52.718 +01:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:100.64.0.1" request
```

### Relevant screenshots or videos

Two of each in the user page
![image](https://github.com/user-attachments/assets/cb2e5908-dd7f-44bb-a6c3-220e7b76f70e)
But only one in the admin UI
![image](https://github.com/user-attachments/assets/076709d3-865f-4dc7-bcab-890791fbf169)
On the metadata admin section, there are also two of each:
![image](https://github.com/user-attachments/assets/eaa61dee-c00e-4a88-bb02-c01a044c7329)

### Additional information

If I press "edit metadata" on the "Movies" or "Shows" duplicates, they all have the same data, excluding image and creation date (one of them is 6 days after the other). For collections, they both have all the same metadata, with the creation date matching that of the later duplicates (16/2/2023).

**Comment by Kladki** [comment]
Still an issue.

**Comment by podulator** [comment]
same

**Comment by Kladki** [comment]
The issue is still not fixed.

**Comment by Kladki** [comment]
Still having this issue.

**Comment by theguymadmax** [comment]
Running out of disk space while running Jellyfin can lead to issues/corruption with the DB.  We have implemented a disk space check before Jellyfin starts up. Unfortunately, there's not much to be done for a corrupted DB.
