### ISSUE TITLE
CANT UPGRADE FROM 10.9.11 TO 10.10

### ISSUE THREAD

**Issue by Y4M4M0M0** [jellyfin/jellyfin#12885]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

after upgrade to 10.10 the sever 
the sever shows a error then the sever window [disappeared]

### Reproduction steps

delet the old 10.9.11 then instal the 10.10 the it happened

### What is the current _bug_ behavior?

just wont boot up successfully after upgrade

### What is the expected _correct_ behavior?

just wont boot up successfully after upgrade

### Jellyfin Server version

10.9.11+

### Specify the build version

10.10

### Environment

```markdown
- OS:WINDOWS 10 SEVER 
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:NVENC
- GPU Model:nvidia t400
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:loacal
```

### Jellyfin logs

```shell
[2024-10-27 16:22:13.180 +08:00] [INF] [1] Main: Jellyfin version: "10.10.0"
[2024-10-27 16:22:13.207 +08:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\Users\Administrator\AppData\Local\jellyfin\log]"]
[2024-10-27 16:22:13.211 +08:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll"]
[2024-10-27 16:22:13.213 +08:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.20348"
[2024-10-27 16:22:13.214 +08:00] [INF] [1] Main: Architecture: X64
[2024-10-27 16:22:13.216 +08:00] [INF] [1] Main: 64-Bit Process: True
[2024-10-27 16:22:13.217 +08:00] [INF] [1] Main: User Interactive: True
[2024-10-27 16:22:13.218 +08:00] [INF] [1] Main: Processor count: 16
[2024-10-27 16:22:13.219 +08:00] [INF] [1] Main: Program data path: "C:\Users\Administrator\AppData\Local\jellyfin"
[2024-10-27 16:22:13.221 +08:00] [INF] [1] Main: Log directory path: "C:\Users\Administrator\AppData\Local\jellyfin\log"
[2024-10-27 16:22:13.222 +08:00] [INF] [1] Main: Config directory path: "C:\Users\Administrator\AppData\Local\jellyfin\config"
[2024-10-27 16:22:13.225 +08:00] [INF] [1] Main: Cache path: "C:\Users\Administrator\AppData\Local\jellyfin\cache"
[2024-10-27 16:22:13.227 +08:00] [INF] [1] Main: Temp directory path: "C:\Users\Administrator\AppData\Local\Temp\jellyfin"
[2024-10-27 16:22:13.228 +08:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-10-27 16:22:13.229 +08:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-10-27 16:22:13.449 +08:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\Users\Administrator\AppData\Local\jellyfin\cache"
[2024-10-27 16:22:13.567 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-10-27 16:22:13.588 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniDB, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\AniDB_9.0.0.0\Jellyfin.Plugin.AniDB.dll"
[2024-10-27 16:22:13.591 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\AniList_9.0.0.0\Jellyfin.Plugin.AniList.dll"
[2024-10-27 16:22:13.594 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniSearch, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\AniSearch_5.0.0.0\Jellyfin.Plugin.AniSearch.dll"
[2024-10-27 16:22:13.597 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Bangumi_1.6.2.0\AnitomySharp.dll"
[2024-10-27 16:22:13.600 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Bangumi_1.6.2.0\Fastenshtein.dll"
[2024-10-27 16:22:13.608 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Bangumi_1.6.2.0\Jellyfin.Plugin.Bangumi.dll"
[2024-10-27 16:22:13.612 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Fanart_12.0.0.0\Jellyfin.Plugin.Fanart.dll"
[2024-10-27 16:22:13.616 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Kodi Sync Queue_11.0.0.0\Jellyfin.Plugin.KodiSyncQueue.dll"
[2024-10-27 16:22:13.626 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "LiteDB, Version=5.0.15.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Kodi Sync Queue_11.0.0.0\LiteDB.dll"
[2024-10-27 16:22:13.701 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.MetaShark, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\MetaShark_2.1.0.0\Jellyfin.Plugin.MetaShark.dll"
[2024-10-27 16:22:13.708 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\Skin Manager_2.0.1\Jellyfin.Plugin.SkinManager.dll"
[2024-10-27 16:22:13.717 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\TheTVDB_15.0.0.0\Jellyfin.Plugin.Tvdb.dll"
[2024-10-27 16:22:13.730 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Tvdb.Sdk, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null" from "C:\Users\Administrator\AppData\Local\jellyfin\plugins\TheTVDB_15.0.0.0\Tvdb.Sdk.dll"
[2024-10-27 16:22:13.832 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-27 16:22:13.836 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-10-27 16:22:13.838 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-27 16:22:13.843 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.1.53", "127.0.0.1"]
[2024-10-27 16:22:13.845 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-10-27 16:22:13.846 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-10-27 16:22:13.848 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-10-27 16:22:18.740 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniDB" "9.0.0.0"
[2024-10-27 16:22:18.744 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "9.0.0.0"
[2024-10-27 16:22:18.747 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniSearch" "5.0.0.0"
[2024-10-27 16:22:18.750 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bangumi" "1.6.2.0"
[2024-10-27 16:22:18.765 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Fanart" "12.0.0.0"
[2024-10-27 16:22:18.768 +08:00] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.KodiSyncQueuePlugin: KodiSyncQueue is starting...
[2024-10-27 16:22:18.769 +08:00] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[2024-10-27 16:22:18.830 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Kodi Sync Queue" "11.0.0.0"
[2024-10-27 16:22:18.833 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MetaShark" "2.1.0.0"
[2024-10-27 16:22:18.835 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Skin Manager" "2.0.1"
[2024-10-27 16:22:18.837 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "15.0.0.0"
[2024-10-27 16:22:18.839 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.10.0.0"
[2024-10-27 16:22:18.842 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.10.0.0"
[2024-10-27 16:22:18.846 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.10.0.0"
[2024-10-27 16:22:18.869 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.10.0.0"
[2024-10-27 16:22:18.870 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.10.0.0"
[2024-10-27 16:22:19.021 +08:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[2024-10-27 16:22:19.023 +08:00] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-10-27 16:22:19.049 +08:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2024-10-27 16:22:19.097 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-10-27 16:22:19.099 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzArtistProvider"
[2024-10-27 16:22:19.100 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2024-10-27 16:22:19.103 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EpisodeProvider"
[2024-10-27 16:22:19.105 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "KodiSyncQueuePlugin"
[2024-10-27 16:22:19.114 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "PluginManager"
```

**Comment by gnattu** [comment]
`C:\Users\Administrator\AppData\Local\jellyfin\plugins\Bangumi_1.6.2.0`

You have a plugin that is not compatible with 10.10

**Comment by Y4M4M0M0** [comment]
let me try it thx

**Comment by Y4M4M0M0** [comment]
> `C:\Users\Administrator\AppData\Local\jellyfin\plugins\Bangumi_1.6.2.0`
> 
> You have a plugin that is not compatible with 10.10

just delete it  and it worked thx man
