### ISSUE TITLE
10.10.0 Jellyfin Upgrade - Trickplay Folder Permissions Issue

### ISSUE THREAD

**Issue by damnsanga** [jellyfin/jellyfin#12897]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hey all, I upgraded to JF 10.10.0 and now Jellyfin appears to start but crashes shortly after.  System is a lxc on Debian12, previously running Jellyfin 10.9.11 without any issues.

Here is the output from `service jellyfin status`:

`* jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             -jellyfin.service.conf
     Active: inactive (dead) since Sun 2024-10-27 02:29:30 UTC; 7s ago
   Duration: 39.698s
    Process: 275 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NO>
   Main PID: 275 (code=exited, status=0/SUCCESS)
        CPU: 37.515s

Oct 27 02:29:29 media-lxc jellyfin[275]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, S>
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Running query planner optimizations in the database... This >
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing CoreAppHost
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing MusicBrainzArtistProvider
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing MusicBrainzAlbumProvider
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing CoverArtArchiveImageProvider
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing ThemerrManager
Oct 27 02:29:29 media-lxc jellyfin[275]: [02:29:29] [INF] Disposing PluginManager
Oct 27 02:29:30 media-lxc systemd[1]: jellyfin.service: Deactivated successfully.
Oct 27 02:29:30 media-lxc systemd[1]: jellyfin.service: Consumed 37.515s CPU time.`

Thanks for any help.

### Reproduction steps

Upgrade jellyfin to 10.10.0 from the most recent stable release?9.11?

### What is the current _bug_ behavior?

Jellyfin starts and shutsdown after a permissions issue associated with trickplay.

I cannot find where the configuration setting to specify the location for trickplay files is specified to then manually change permissions. 

### What is the expected _correct_ behavior?

To update to 10.10.0, start JF service and run without shutting down on error

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.0

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Debian 12, LXC
- Linux Kernel:
- Virtualization: LXC
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-10-27 03:27:51.378 +00:00] [INF] Jellyfin version: "10.10.0"
[2024-10-27 03:27:51.400 +00:00] [INF] Environment Variables: ["[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS --datadir $JELLYFIN_DATA_DIR --configdir $JELLYFIN_CONFIG_DIR --logdir $JELLYFIN_LOG_DIR --cachedir $JELLYFIN_CACHE_DIR]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_USER, jellyfin]"]
[2024-10-27 03:27:51.402 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-10-27 03:27:51.404 +00:00] [INF] Operating system: "Debian GNU/Linux 12 (bookworm)"
[2024-10-27 03:27:51.404 +00:00] [INF] Architecture: X64
[2024-10-27 03:27:51.405 +00:00] [INF] 64-Bit Process: True
[2024-10-27 03:27:51.405 +00:00] [INF] User Interactive: True
[2024-10-27 03:27:51.405 +00:00] [INF] Processor count: 12
[2024-10-27 03:27:51.405 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2024-10-27 03:27:51.405 +00:00] [INF] Log directory path: "/var/log/jellyfin"
[2024-10-27 03:27:51.405 +00:00] [INF] Config directory path: "/etc/jellyfin"
[2024-10-27 03:27:51.405 +00:00] [INF] Cache path: "/var/cache/jellyfin"
[2024-10-27 03:27:51.405 +00:00] [INF] Temp directory path: "/tmp/jellyfin"
[2024-10-27 03:27:51.405 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2024-10-27 03:27:51.405 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2024-10-27 03:27:51.580 +00:00] [INF] Setting cache path: "/mnt/jellyfin-caches/cache"
[2024-10-27 03:27:51.697 +00:00] [INF] Loading assemblies
[2024-10-27 03:27:51.724 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.AniList, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/AniList_9.0.0.0/Jellyfin.Plugin.AniList.dll"
[2024-10-27 03:27:51.726 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Artwork, Version=1.2403.9.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Artwork_1.2403.9.0/Jellyfin.Plugin.Artwork.dll"
[2024-10-27 03:27:51.730 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Bookshelf, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Bookshelf_11.0.0.0/Jellyfin.Plugin.Bookshelf.dll"
[2024-10-27 03:27:51.732 +00:00] [INF] Loaded assembly "MetaBrainz.MusicBrainz.CoverArt, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "/var/lib/jellyfin/plugins/Cover Art Archive_8.2403.6.0/MetaBrainz.MusicBrainz.CoverArt.dll"
[2024-10-27 03:27:51.732 +00:00] [INF] Loaded assembly "MetaBrainz.Common.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021" from "/var/lib/jellyfin/plugins/Cover Art Archive_8.2403.6.0/MetaBrainz.Common.Json.dll"
[2024-10-27 03:27:51.733 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.CoverArtArchive, Version=8.2403.6.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Cover Art Archive_8.2403.6.0/Jellyfin.Plugin.CoverArtArchive.dll"
[2024-10-27 03:27:51.734 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Discogs, Version=1.2404.12.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Discogs_1.2404.12.0/Jellyfin.Plugin.Discogs.dll"
[2024-10-27 03:27:51.738 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Dlna.Playback, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll"
[2024-10-27 03:27:51.739 +00:00] [INF] Loaded assembly "Rssdp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/DLNA_3.0.0.0/Rssdp.dll"
[2024-10-27 03:27:51.743 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Dlna, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.dll"
[2024-10-27 03:27:51.743 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Dlna.Model, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Model.dll"
[2024-10-27 03:27:51.745 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Fanart, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Fanart_12.0.0.0/Jellyfin.Plugin.Fanart.dll"
[2024-10-27 03:27:51.745 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.FinTube, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/FinTube_1.0.1.0/Jellyfin.Plugin.FinTube.dll"
[2024-10-27 03:27:51.747 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.IMVDb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/IMVDb_4.0.0.0/Jellyfin.Plugin.IMVDb.dll"
[2024-10-27 03:27:51.748 +00:00] [INF] Loaded assembly "Namo.Plugin.InPlayerEpisodePreview, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/InPlayerEpisodePreview_1.2.4.0/Namo.Plugin.InPlayerEpisodePreview.dll"
[2024-10-27 03:27:51.750 +00:00] [INF] Loaded assembly "ConfusedPolarBear.Plugin.IntroSkipper, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Intro Skipper_1.0.0.7/ConfusedPolarBear.Plugin.IntroSkipper.dll"
[2024-10-27 03:27:51.752 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Kitsu, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Kitsu_5.0.0.0/Jellyfin.Plugin.Kitsu.dll"
[2024-10-27 03:27:51.753 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.LocalIntros, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Local Intros_3.0.0.0/Jellyfin.Plugin.LocalIntros.dll"
[2024-10-27 03:27:51.754 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.MergeVersions, Version=10.9.1.1, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Merge Versions_10.9.1.1/Jellyfin.Plugin.MergeVersions.dll"
[2024-10-27 03:27:51.759 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.NextPVR, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/NextPVR_11.0.0.0/Jellyfin.Plugin.NextPVR.dll"
[2024-10-27 03:27:51.761 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Opds, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/OPDS_5.0.0.0/Jellyfin.Plugin.Opds.dll"
[2024-10-27 03:27:51.763 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2024-10-27 03:27:51.789 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2024-10-27 03:27:51.791 +00:00] [INF] Loaded assembly "SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll"
[2024-10-27 03:27:51.931 +00:00] [INF] Loaded assembly "DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll"
[2024-10-27 03:27:51.935 +00:00] [INF] Loaded assembly "ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll"
[2024-10-27 03:27:51.943 +00:00] [INF] Loaded assembly "SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll"
[2024-10-27 03:27:51.945 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll"
[2024-10-27 03:27:51.947 +00:00] [INF] Loaded assembly "System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll"
[2024-10-27 03:27:51.973 +00:00] [INF] Loaded assembly "ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b" from "/var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll"
[2024-10-27 03:27:51.974 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Skin Manager_2.0.1/Jellyfin.Plugin.SkinManager.dll"
[2024-10-27 03:27:51.982 +00:00] [INF] Loaded assembly "YoutubeExplode, Version=6.3.16.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Themerr_2024.523.2124.32/YoutubeExplode.dll"
[2024-10-27 03:27:51.983 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Themerr, Version=2024.523.2124.32, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Themerr_2024.523.2124.32/Jellyfin.Plugin.Themerr.dll"
[2024-10-27 03:27:52.001 +00:00] [INF] Loaded assembly "Tvdb.Sdk, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_15.0.0.0/Tvdb.Sdk.dll"
[2024-10-27 03:27:52.006 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Tvdb, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_15.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2024-10-27 03:27:52.007 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll"
[2024-10-27 03:27:52.012 +00:00] [INF] Loaded assembly "Trakt, Version=25.2410.9.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Trakt_25.2410.9.0/Trakt.dll"
[2024-10-27 03:27:52.013 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.TranscodeKiller, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Transcode Killer_3.0.0.0/Jellyfin.Plugin.TranscodeKiller.dll"
[2024-10-27 03:27:52.015 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.TubeArchivistMetadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TubeArchivistMetadata_1.3.0.0/Jellyfin.Plugin.TubeArchivistMetadata.dll"
[2024-10-27 03:27:52.017 +00:00] [INF] Loaded assembly "TVHeadEnd, Version=12.2410.6.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TVHeadend_12.2410.6.0/TVHeadEnd.dll"
[2024-10-27 03:27:52.020 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.TvMaze, Version=11.2403.5.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TVmaze_11.2403.5.0/Jellyfin.Plugin.TvMaze.dll"
[2024-10-27 03:27:52.032 +00:00] [INF] Loaded assembly "Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc" from "/var/lib/jellyfin/plugins/TVmaze_11.2403.5.0/Polly.dll"
[2024-10-27 03:27:52.035 +00:00] [INF] Loaded assembly "Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TVmaze_11.2403.5.0/Flurl.Http.dll"
[2024-10-27 03:27:52.036 +00:00] [INF] Loaded assembly "TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TVmaze_11.2403.5.0/TvMaze.Api.Client.dll"
[2024-10-27 03:27:52.038 +00:00] [INF] Loaded assembly "Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TVmaze_11.2403.5.0/Flurl.dll"
[2024-10-27 03:27:52.040 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Vgmdb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/VGMdb_4.0.0.0/Jellyfin.Plugin.Vgmdb.dll"
[2024-10-27 03:27:52.061 +00:00] [INF] Loaded assembly "MimeKit, Version=4.8.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/MimeKit.dll"
[2024-10-27 03:27:52.101 +00:00] [INF] Loaded assembly "BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/BouncyCastle.Cryptography.dll"
[2024-10-27 03:27:52.105 +00:00] [INF] Loaded assembly "MQTTnet.Extensions.ManagedClient, Version=4.3.7.1207, Culture=neutral, PublicKeyToken=fdb7629f2e364a63" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/MQTTnet.Extensions.ManagedClient.dll"
[2024-10-27 03:27:52.108 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Webhook, Version=15.2410.10.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/Jellyfin.Plugin.Webhook.dll"
[2024-10-27 03:27:52.128 +00:00] [INF] Loaded assembly "MailKit, Version=4.8.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/MailKit.dll"
[2024-10-27 03:27:52.140 +00:00] [INF] Loaded assembly "Handlebars, Version=2.1.6.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/Handlebars.dll"
[2024-10-27 03:27:52.148 +00:00] [INF] Loaded assembly "MQTTnet, Version=4.3.7.1207, Culture=neutral, PublicKeyToken=fdb7629f2e364a63" from "/var/lib/jellyfin/plugins/Webhook_15.2410.10.0/MQTTnet.dll"
[2024-10-27 03:27:52.151 +00:00] [INF] Loaded assembly "NYoutubeDLP, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/YouTube Metadata_1.0.3.12/NYoutubeDLP.dll"
[2024-10-27 03:27:52.153 +00:00] [INF] Loaded assembly "System.IO.Abstractions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=96bf224d23c43e59" from "/var/lib/jellyfin/plugins/YouTube Metadata_1.0.3.12/System.IO.Abstractions.dll"
[2024-10-27 03:27:52.155 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.12, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/YouTube Metadata_1.0.3.12/Jellyfin.Plugin.YoutubeMetadata.dll"
[2024-10-27 03:27:52.334 +00:00] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-27 03:27:52.334 +00:00] [INF] Defined LAN exclusions: []
[2024-10-27 03:27:52.335 +00:00] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-27 03:27:52.336 +00:00] [INF] Filtered interface addresses: ["127.0.0.1", "10.1.2.10"]
[2024-10-27 03:27:52.336 +00:00] [INF] Bind Addresses ["0.0.0.0"]
[2024-10-27 03:27:52.336 +00:00] [INF] Remote IP filter is "Allowlist"
[2024-10-27 03:27:52.336 +00:00] [INF] Filtered subnets: []
[2024-10-27 03:28:27.948 +00:00] [INF] Loaded plugin: "AniList" "9.0.0.0"
[2024-10-27 03:28:27.950 +00:00] [INF] Loaded plugin: "Artwork" "1.2403.9.0"
[2024-10-27 03:28:27.951 +00:00] [INF] Loaded plugin: "Bookshelf" "11.0.0.0"
[2024-10-27 03:28:27.952 +00:00] [INF] Loaded plugin: "Cover Art Archive" "8.2403.6.0"
[2024-10-27 03:28:27.953 +00:00] [INF] Loaded plugin: "Discogs" "1.2404.12.0"
[2024-10-27 03:28:27.954 +00:00] [INF] Loaded plugin: "DLNA" "3.0.0.0"
[2024-10-27 03:28:27.955 +00:00] [INF] Loaded plugin: "Fanart" "12.0.0.0"
[2024-10-27 03:28:27.957 +00:00] [INF] Loaded plugin: "FinTube" "1.0.1.0"
[2024-10-27 03:28:27.957 +00:00] [INF] Loaded plugin: "IMVDb" "4.0.0.0"
[2024-10-27 03:28:27.970 +00:00] [INF] Found client script injected in "/usr/share/jellyfin/web/index.html"
[2024-10-27 03:28:27.972 +00:00] [INF] Loaded plugin: "InPlayerEpisodePreview" "1.2.4.0"
[2024-10-27 03:28:29.077 +00:00] [INF] The skip button has already been injected.
[2024-10-27 03:28:29.306 +00:00] [INF] Loaded plugin: "Intro Skipper" "1.0.0.7"
[2024-10-27 03:28:29.307 +00:00] [INF] Loaded plugin: "Kitsu" "5.0.0.0"
[2024-10-27 03:28:29.308 +00:00] [INF] Loaded plugin: "Local Intros" "3.0.0.0"
[2024-10-27 03:28:29.309 +00:00] [INF] Loaded plugin: "Merge Versions" "10.9.1.1"
[2024-10-27 03:28:29.310 +00:00] [INF] Loaded plugin: "NextPVR" "11.0.0.0"
[2024-10-27 03:28:29.311 +00:00] [INF] Loaded plugin: "OPDS Feed" "5.0.0.0"
[2024-10-27 03:28:29.324 +00:00] [INF] Loaded plugin: "Open Subtitles" "20.0.0.0"
[2024-10-27 03:28:29.401 +00:00] [INF] Loaded plugin: "Playback Reporting" "15.0.0.0"
[2024-10-27 03:28:29.406 +00:00] [INF] Loaded plugin: "Reports" "17.0.0.0"
[2024-10-27 03:28:29.407 +00:00] [INF] Loaded plugin: "Skin Manager" "2.0.1"
[2024-10-27 03:28:29.409 +00:00] [INF] Loaded plugin: "Themerr" "2024.523.2124.32"
[2024-10-27 03:28:29.410 +00:00] [INF] Loaded plugin: "Themerr" "2024.523.2124.32"
[2024-10-27 03:28:29.411 +00:00] [INF] Loaded plugin: "TheTVDB" "15.0.0.0"
[2024-10-27 03:28:29.412 +00:00] [INF] Loaded plugin: "TMDb Box Sets" "11.0.0.0"
[2024-10-27 03:28:29.413 +00:00] [INF] Loaded plugin: "Trakt" "25.2410.9.0"
[2024-10-27 03:28:29.413 +00:00] [INF] Loaded plugin: "Transcode Killer" "3.0.0.0"
[2024-10-27 03:28:29.429 +00:00] [INF] "Given TubeArchivist URL contains no schema. Adding http://..."
[2024-10-27 03:28:29.438 +00:00] [INF] "Ping..."
[2024-10-27 03:28:29.439 +00:00] [INF] "Ping..."
[2024-10-27 03:28:29.439 +00:00] [INF] "Collection display name: "
[2024-10-27 03:28:29.439 +00:00] [INF] "TubeArchivist API URL: http:///"
[2024-10-27 03:28:29.439 +00:00] [INF] "Pinging TubeArchivist API..."
[2024-10-27 03:28:29.440 +00:00] [INF] Loaded plugin: "TubeArchivist Metadata" "1.3.0.0"
[2024-10-27 03:28:29.441 +00:00] [INF] Loaded plugin: "TVHeadend" "12.2410.6.0"
[2024-10-27 03:28:29.442 +00:00] [INF] Loaded plugin: "TVmaze" "11.2403.5.0"
[2024-10-27 03:28:29.444 +00:00] [INF] Loaded plugin: "VGMdb" "4.0.0.0"
[2024-10-27 03:28:29.447 +00:00] [INF] Loaded plugin: "Webhook" "15.2410.10.0"
[2024-10-27 03:28:29.449 +00:00] [INF] Loaded plugin: "YoutubeMetadata" "1.0.3.12"
[2024-10-27 03:28:29.450 +00:00] [INF] Loaded plugin: "TMDb" "10.10.0.0"
[2024-10-27 03:28:29.450 +00:00] [INF] Loaded plugin: "Studio Images" "10.10.0.0"
[2024-10-27 03:28:29.451 +00:00] [INF] Loaded plugin: "OMDb" "10.10.0.0"
[2024-10-27 03:28:29.473 +00:00] [INF] Loaded plugin: "MusicBrainz" "10.10.0.0"
[2024-10-27 03:28:29.475 +00:00] [INF] Loaded plugin: "AudioDB" "10.10.0.0"
[2024-10-27 03:28:29.894 +00:00] [INF] Applying migration '"MoveTrickplayFiles"'
[2024-10-27 03:28:30.166 +00:00] [ERR] Could not apply migration '"MoveTrickplayFiles"'
System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at Emby.Server.Implementations.IO.ManagedFileSystem.MoveDirectory(String source, String destination)
   at Jellyfin.Server.Migrations.Routines.MoveTrickplayFiles.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-10-27 03:28:30.167 +00:00] [FTL] Error while starting server
System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at Emby.Server.Implementations.IO.ManagedFileSystem.MoveDirectory(String source, String destination)
   at Jellyfin.Server.Migrations.Routines.MoveTrickplayFiles.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-10-27 03:28:30.167 +00:00] [INF] Running query planner optimizations in the database... This might take a while
[2024-10-27 03:28:30.186 +00:00] [INF] Disposing "CoreAppHost"
[2024-10-27 03:28:30.186 +00:00] [INF] Disposing "MusicBrainzArtistProvider"
[2024-10-27 03:28:30.186 +00:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2024-10-27 03:28:30.186 +00:00] [INF] Disposing "CoverArtArchiveImageProvider"
[2024-10-27 03:28:30.187 +00:00] [INF] Disposing "ThemerrManager"
[2024-10-27 03:28:30.188 +00:00] [INF] Disposing "PluginManager"
```

### FFmpeg logs

```shell
None
```

### Client / Browser logs

Linux CLI

### Relevant screenshots or videos

None, refer above log

### Additional information

None

**Comment by Shadowghost** [comment]
Hm, seems like the permissions on your Jellyfin metadata folder are messed up. Should be fixed if you run `chown jellyfin:jellyfin /var/lib/jellyfin -r`

**Comment by damnsanga** [comment]
Hi, I changed the permissions as suggested however JF continues to shutdown.
I also tried setting the permission to 1777 on` jellyfin:jellyfin /var/lib/jellyfin -r` and had no luck.
