### ISSUE TITLE
Updating plugins fails with resource temporarily unavailable

### ISSUE THREAD

**Issue by paulmorabito** [jellyfin/jellyfin#1290]
Hi,

I'm using the latest docker image with Jellyfin version 10.3.1. The plug-in update job and also the plugins view screen fails to load with the following error:

```
[2019-04-24 00:05:03.018 +00:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2019-04-24 00:05:03.024 +00:00] [INF] Queueing task "PluginUpdateTask"
[2019-04-24 00:05:03.043 +00:00] [INF] Executing "Check for plugin updates"
[2019-04-24 00:05:03.117 +00:00] [INF] HttpClientManager "GET": "https://repo.jellyfin.org/releases/plugin/manifest.json"
[2019-04-24 00:05:13.200 +00:00] [ERR] Error UnknownError getting response from "https://repo.jellyfin.org/releases/plugin/manifest.json"
System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2019-04-24 00:05:13.295 +00:00] [ERR] Error
MediaBrowser.Model.Net.HttpException: Resource temporarily unavailable Resource temporarily unavailable ---> System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
```

I'm getting similar resource not available errors when doing media scabd too so possibly it's SSL related?

**Comment by anthonylavado** [comment]
Do you have IPv6 enabled by chance?

**Comment by paulmorabito** [comment]
No, the NAS loads the ip6 kernel model but the network settings have it
disabled and I can see no ip6 address assigned.

**Comment by paulmorabito** [comment]
This is my compose file if it helps:

```
version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest 
    network_mode: "bridge"  
    volumes:  
      - /share/persistent/jellyfin:/config  
      - /share/media:/media
    ports:
      - '8097:8096'
    environment:
      - PUID= 1000
      - PGID= 999
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    privileged: true

```

**Comment by DrPandemic** [comment]
This sounds like a problem from your Docker Compose network. Try to connect directly to your docker container `docker exec -it <container name> /bin/bash` and the container name can be found with `docker ps`. From the container, can you `curl -vhttps://repo.jellyfin.org/releases/plugin/manifest.json`?

If you get any network error from that, this means that your network setup is broken.

**Comment by paulmorabito** [comment]
Yes, you are correct. It was a networking issue. It's now fixed.

Thanks.
