### ISSUE TITLE
upgrade to 10.10.0 cannot open  webpage

### ISSUE THREAD

**Issue by sora709394** [jellyfin/jellyfin#12901]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

web cannot open

### Reproduction steps

Update to 10.10.0

### What is the current _bug_ behavior?

wen cannot open

### What is the expected _correct_ behavior?

wen can open

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS:Ubuntu
- Linux Kernel:
- Virtualization:docker
- Clients:web
- Browser:chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
jellyfin  | [jellyfin-init] Pi Libs detected loading
jellyfin  | [custom-init] No custom files found, skipping...
jellyfin  | [22:01:12] [INF] [1] Main: Jellyfin version: 10.10.0
jellyfin  | [22:01:12] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_LOG_DIR, /config/log]"]
jellyfin  | [22:01:12] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
jellyfin  | [22:01:12] [INF] [1] Main: Operating system: Ubuntu 24.04.1 LTS
jellyfin  | [22:01:12] [INF] [1] Main: Architecture: Arm64
jellyfin  | [22:01:12] [INF] [1] Main: 64-Bit Process: True
jellyfin  | [22:01:12] [INF] [1] Main: User Interactive: True
jellyfin  | [22:01:12] [INF] [1] Main: Processor count: 4
jellyfin  | [22:01:12] [INF] [1] Main: Program data path: /config/data
jellyfin  | [22:01:12] [INF] [1] Main: Log directory path: /config/log
jellyfin  | [22:01:12] [INF] [1] Main: Config directory path: /config
jellyfin  | [22:01:12] [INF] [1] Main: Cache path: /config/cache
jellyfin  | [22:01:12] [INF] [1] Main: Temp directory path: /tmp/jellyfin
jellyfin  | [22:01:12] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
jellyfin  | [22:01:12] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
jellyfin  | [22:01:13] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
jellyfin  | [22:01:14] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
jellyfin  | [22:01:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Bangumi_1.6.2.0/Jellyfin.Plugin.Bangumi.dll
jellyfin  | [22:01:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Bangumi_1.6.2.0/Fastenshtein.dll
jellyfin  | [22:01:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Bangumi_1.6.2.0/AnitomySharp.dll
jellyfin  | [22:01:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 1.0.4.0 of MeiamSub.Shooter 
jellyfin  | [22:01:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.MetaShark, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/MetaShark_2.1.0.0/Jellyfin.Plugin.MetaShark.dll
jellyfin  | [22:01:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 20.0.0.0 of Open Subtitles 
jellyfin  | [22:01:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Subtitle Extract_4.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.17.0.3"]
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
jellyfin  | [22:01:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bangumi 1.6.2.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MetaShark 2.1.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Subtitle Extract 4.0.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.0.0
jellyfin  | [22:01:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.0.0
jellyfin  | [22:01:29] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
jellyfin  | [22:01:29] [FTL] [1] Main: Error while starting server
jellyfin  | System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1 MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
jellyfin  |    at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
jellyfin  |    at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
jellyfin  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
jellyfin  |    at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
jellyfin  |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
jellyfin  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
jellyfin  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
jellyfin  | [22:01:29] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
jellyfin  | [22:01:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
jellyfin  | [22:01:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
jellyfin  | [22:01:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
jellyfin  | [22:01:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EpisodeProvider
jellyfin  | [22:01:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

**Comment by felix920506** [comment]
You have a configuration error. Please head to our chat room or forum for support. https://jellyfin.org/contact

**Comment by gnattu** [comment]
duplicate of #12885

**Comment by gnattu** [comment]
Remove the unsupported plugin as noted in the linked issue

**Comment by sora709394** [comment]
> Remove the unsupported plugin as noted in the linked issue
work now thanks.
