### ISSUE TITLE
Musicbrainz plugin returns HTTP 404 on AlbumMetadataService 

### ISSUE THREAD

**Issue by rmackinnon** [jellyfin/jellyfin#12903]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to v10.10.0, began experiencing an issue with the Musicbrainz plugin.  While scanning a library, and 

### Reproduction steps

1. sign in to the admin console
2. goto the dashboard
2. goto libraries
3. force the start of a scan of a library

### What is the current _bug_ behavior?

Requests to the musicbrainz API server fail with a HTTP 404.

### What is the expected _correct_ behavior?

Requests to the musicbrainz service should hit the API and succeed. I believe that it may not be using the "/ws/2" URI. 

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.7.7
- Virtualization: Docker
- Clients: Web, Desktop 1.11.x, DLNA
- Browser: Chrome 126.0.6478.55
- FFmpeg Version: 7.0.2
- Playback Method: Direct stream
- Hardware Acceleration: CPU Only
- GPU Model: None
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[02:11:13] [ERR] [83] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
MetaBrainz.Common.HttpError: Not Found
For usage, please see: https://musicbrainz.org/development/mmd
 ---> MetaBrainz.Common.HttpError: HTTP 404 (NotFound) 'Not Found'
   at MetaBrainz.Common.HttpUtils.EnsureSuccessfulAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   --- End of inner exception stack trace ---
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`2 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, IReadOnlyDictionary`2 options, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.LookupReleaseAsync(Guid mbid, Include inc, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[02:11:15] [ERR] [79] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
MetaBrainz.Common.HttpError: Not Found
For usage, please see: https://musicbrainz.org/development/mmd
 ---> MetaBrainz.Common.HttpError: HTTP 404 (NotFound) 'Not Found'
   at MetaBrainz.Common.HttpUtils.EnsureSuccessfulAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   --- End of inner exception stack trace ---
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`2 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, IReadOnlyDictionary`2 options, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.LookupReleaseAsync(Guid mbid, Include inc, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[02:11:15] [ERR] [13] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[02:11:15] [ERR] [85] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
   at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[02:11:15] [ERR] [13] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
   at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[02:11:15] [ERR] [13] MediaBrowser.Providers.Music.AlbumMetadataService: Error in MusicBrainz
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
   at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
N/A, issue is not transcoding oriented.
```

### Client / Browser logs

N/A, client/browser functions as intended.

### Relevant screenshots or videos

N/A

### Additional information

As far as I can tell, reading mb tags is working. I believe this may be affecting the identify feature also?

**Comment by rmackinnon** [comment]
Can I get some direction on what repo this should be in?

**Comment by crobibero** [comment]
This is in the correct repo, the MusicBrainz code lives here: https://github.com/jellyfin/jellyfin/tree/master/MediaBrowser.Providers/Plugins/MusicBrainz

**Comment by rmackinnon** [comment]
Thanks for re-triaging this.  Please let me know what I can do to assist in testing and getting to the root cause.

**Comment by voc0der** [comment]
Also getting this

**Comment by UtkarshVerma** [comment]
Was this ever fixed? I seem to be getting something similar today.

**Comment by nonplayer** [comment]
I am getting this exact error today on a brand new first-time installation.

**Comment by nibbsification** [comment]
The problem still persists
