### ISSUE TITLE
Image provider - Error reading image tag

### ISSUE THREAD

**Issue by nukeduk** [jellyfin/jellyfin#12911]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

This is the same problem like in old version of Jellyfin:
https://github.com/jellyfin/jellyfin/issues/8869

### Reproduction steps

Problem is when I scan my media folder. Huge amount of errors like below.

### What is the current _bug_ behavior?

[21:03:22] [ERR] [100] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for D:\Rodzinne\2008\05\20080502_145259_1B2AEF16.jpg
System.NotImplementedException: Unknown type/count 3/0 (0)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.Makernotes.Nikon3MakernoteReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 base_offset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseMakernote(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.Jpeg.File.ReadAPP1Segment(UInt16 length)
   at TagLib.Jpeg.File.ReadMetadata()
   at TagLib.Jpeg.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)

### What is the expected _correct_ behavior?

Read images tag without errors

### Jellyfin Server version

Master

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Windows Pro 11
- Virtualization: no
- Clients: Windows Pro 11
- Browser: Chrome
- GPU Model: Intel
- Base URL: http://192.168.1.2:8096
```

### Jellyfin logs

```shell
[21:03:22] [INF] [54] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args -analyzeduration 200M -probesize 1G -i file:"D:\Rodzinne\2022\12\20221206_054009_14162AE5.mov" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[21:03:22] [ERR] [29] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for D:\Rodzinne\2008\07\20080715_130502_46486EE3.jpg
System.NotImplementedException: Unknown type/count 3/0 (0)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.Makernotes.Nikon3MakernoteReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 base_offset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseMakernote(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.Jpeg.File.ReadAPP1Segment(UInt16 length)
   at TagLib.Jpeg.File.ReadMetadata()
   at TagLib.Jpeg.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)
[21:03:22] [ERR] [100] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for D:\Rodzinne\2008\05\20080502_145259_1B2AEF16.jpg
System.NotImplementedException: Unknown type/count 3/0 (0)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.Makernotes.Nikon3MakernoteReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 base_offset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseMakernote(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.Jpeg.File.ReadAPP1Segment(UInt16 length)
   at TagLib.Jpeg.File.ReadMetadata()
   at TagLib.Jpeg.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)
[21:03:22] [ERR] [117] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for D:\Rodzinne\2008\05\20080502_145307_5341D43C.jpg
System.NotImplementedException: Unknown type/count 3/0 (0)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.Makernotes.Nikon3MakernoteReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 base_offset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseMakernote(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.Jpeg.File.ReadAPP1Segment(UInt16 length)
   at TagLib.Jpeg.File.ReadMetadata()
   at TagLib.Jpeg.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)
[21:03:22] [ERR] [6] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for D:\Rodzinne\2008\05\20080502_145330_43C3BC9A.jpg
System.NotImplementedException: Unknown type/count 3/0 (0)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.Makernotes.Nikon3MakernoteReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 base_offset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseMakernote(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.IFD.IFDReader.ParseIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, UInt32 offset)
   at TagLib.IFD.IFDReader.CreateIFDEntry(UInt16 tag, UInt16 type, UInt32 count, Int64 baseOffset, ByteVector offsetData, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.ReadIFD(Int64 baseOffset, UInt32 offset, UInt32 maxOffset)
   at TagLib.IFD.IFDReader.Read(Int32 count)
   at TagLib.Jpeg.File.ReadAPP1Segment(UInt16 length)
   at TagLib.Jpeg.File.ReadMetadata()
   at TagLib.Jpeg.File.Read(ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)
[21:03:23] [INF] [63] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args -analyzeduration 200M -probesize 1G -i file:"D:\Rodzinne\2021\11\20211121_120903_A1307057.mov" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
```

**Comment by Rivers47** [comment]
Is https://github.com/jellyfin/jellyfin/pull/11879 is not in release yet? I have the same issue on 10.10.6

**Comment by Bond-009** [comment]
https://github.com/mono/taglib-sharp/issues/224
