### ISSUE TITLE
modify .nfo files

### ISSUE THREAD

**Issue by DZDZzzZ** [jellyfin/jellyfin#12919]
### This issue respects the following points:

- [ ] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I tried to modify the image by changing the path of the poster image in the .nfo file, because the previous image path is not easy to check. But when I refresh the metadata in Jellyfin, the path in the .nfo file changes back to the previous one. The image displayed in Jellyfin also changed to the previous one.  I tried to change title content, and it worked. But the image path still changed to the previous path. I wonder know how to make jellyfin use my .nfo file as a reference instead of modifying it. The previous content of .nfo file is obtained by scrapping.

### Reproduction steps

1. saved metadata into the .nfo file in Jellyfin.
2. modified the image path and title  in the .nfo file and saved.
3. refresh the metadata
4. check the content of  .nfo file and found image path was changed to the previous path, but the title was the content after the change.

### What is the current _bug_ behavior?

refreshing metadata changes and export .nfo file.

### What is the expected _correct_ behavior?

Read and use the modified .nfo file in Jellyfin instead of export it.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: windows 11
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Microsoft Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-10-31 14:45:13.767 +08:00] [INF] [19] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-10-31 14:45:22.869 +08:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:45:51.891 +08:00] [INF] [19] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-10-31 14:45:52.875 +08:00] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:46:22.874 +08:00] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:46:52.885 +08:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:46:57.125 +08:00] [INF] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Movie\2023-TOP250\1.STARS-804.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-10-31 14:46:57.343 +08:00] [ERR] [17] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-10-31 14:47:01.786 +08:00] [INF] [16] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-10-31 14:47:02.387 +08:00] [INF] [3] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-10-31 14:47:03.361 +08:00] [INF] [16] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-10-31 14:47:03.870 +08:00] [INF] [15] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-10-31 14:47:04.634 +08:00] [INF] [15] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-10-31 14:47:05.191 +08:00] [INF] [15] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-10-31 14:47:22.898 +08:00] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:47:52.904 +08:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-10-31 14:48:22.912 +08:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```

**Comment by DZDZzzZ** [comment]
It is so strange. Even if I unchecked all scrapers, deleted all .nfo files, checked the storage method as .nfo files, and refreshed the metadata, I still seem to get new .nfo files with the same content as my previous .nfo files before modified. 
I suspect the metadata is stored somewhere else, and Jellyfin prioritizes it over the .nfo files with the same name in the same folder as the video files.

**Comment by felix920506** [comment]
Have you tried unchecking nfo as storage method?

**Comment by tanmoumou252** [comment]
![Image](https://github.com/user-attachments/assets/bbb2cd82-b69f-418f-95e1-abae8b2c3afa)


I hope the episode number and season number are generated correctly, especially when the file name is clearly written as SxEx

**Comment by felix920506** [comment]
> Why not fix the nfo reading functionality, but consider not using nfo?

We are trying to narrow down where the issue is.

> Is reading a pre-made XML file with media metadata really that difficult?

I think you misunderstood the original report. The issue here isn't about simply scanning in nfo files. Rather, it is about Jellyfin overwriting external changes to files managed by Jellyfin.

**Comment by sevenrats** [comment]
This is not a bug, jellyfin owns the nfo when the nfo saver is active.  Ultimately, Jellyfin can _either_ serialize known data or it can deserialize unknown data but it can't magically know which is which to do both.  This use case is unfortunately unsupported.
