### ISSUE TITLE
Trickplay image generation fails on 10.10

### ISSUE THREAD

**Issue by awb1015** [jellyfin/jellyfin#12930]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to Jellyfin 10.10 I'm unable to generate trickplay images either with our without hardware acceleration. I've set the option for trickplay to save the image alongside the media in the libraries. I've verified that hardware acceleration works for playback and checked that jellyfin-ffmpeg should have proper permissions

```
alex@Server:~$ ls -l /usr/lib/jellyfin-ffmpeg/ffmpeg
-rwxr-xr-x 1 root root 374960 Oct 25 09:53 /usr/lib/jellyfin-ffmpeg/ffmpeg
```

while it is owned by root it still is `-rwxr-xr-x`  I've also verified that all directories are owned by jellyfin user/group with proper read/write/execute permissions (drwxr-xr-x) under `/tmp/jellyfin`

I was also able to attempt something similar to generating a trickplay image without issue
```
alex@Server:~$ /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 1 -i "/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv" -an -sn -vf "fps=0.1,scale=320:-1" -frames:v 1 -c:v mjpeg -qscale:v 4 -y /tmp/test.jpg
```

The result of running a `sudo vainfo` shows that I should be able to work with 10bit HEVC so I don't think my device (Intel UHD 630) is a problem, again it works to playback the file without issue.

When I check the Jellyfin logs I see the following but it never seems to complete

```
[2024-10-31 14:54:16.454 -04:00] [INF] Creating trickplay files at 320 width, for "/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv" [ID: 512fce4c-2408-2c19-de2b-d5635acf67f4]
[2024-10-31 14:54:16.466 -04:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv\" -noautoscale -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:out_range=pc:mode=hq:extra_hw_frames=24,hwmap=mode=read,format=nv12\" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 \"/tmp/jellyfin/22dae171024b4cd6b6537f71fc235d40/%08d.jpg\""
```
I also disabled hardware acceleration for decoding under trickplay and no luck there either. In this case it does at least throw an error

```
[2024-10-31 14:37:31.574 -04:00] [ERR] ffmpeg image extraction failed for "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 1 -i file:\"/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv\" -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p\" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 \"/tmp/jellyfin/9182869ebe2946d3bb2a6d0373538de5/%08d.jpg\""
[2024-10-31 14:37:31.574 -04:00] [ERR] Error creating trickplay images.
MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 1 -i file:"/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv" -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/9182869ebe2946d3bb2a6d0373538de5/%08d.jpg"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractVideoImagesOnIntervalInternal(String inputArg, String filterParam, String vidEncoder, Nullable`1 outputThreads, Nullable`1 qualityScale, Nullable`1 priority, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
```

Hopefully this is enough information. I'm definitely not a FFMPEG expert so I've tried to provide as much useful info as I could

### Reproduction steps

1. Login in to Jellyfin as admin
2. From dashboard go to playback and then trickplay. Check/uncheck `Enable hardware decoding`
3. Run task to `Generate Trickplay Images`

### What is the current _bug_ behavior?

Trickplay fails to complete or throw an error with hardware acceleration for decoding. Without hardware acceleration it throws errors.

### What is the expected _correct_ behavior?

Images would be generated for whether or not we use hardware acceleration for trickplay decoding

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

- OS: Ubuntu 24.04.1 LTS
- Linux Kernel: Linux 6.8.0-45-generic x86_64
- Virtualization: No
- Clients:
- Browser: Firefox fwiw
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Yes and no
- GPU Model: Intel UHD 630
- Plugins:
- Reverse Proxy: Caddy
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

[2024-10-31 14:54:16.454 -04:00] [INF] Creating trickplay files at 320 width, for "/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv" [ID: 512fce4c-2408-2c19-de2b-d5635acf67f4]
[2024-10-31 14:54:16.466 -04:00] [INF] Trickplay generation: "/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/media/superdrive/media/Movies/Example (2018)/Example (2018) 1080p 10bit x265 HEVC.mkv\" -noautoscale -an -sn -vf \"fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:out_range=pc:mode=hq:extra_hw_frames=24,hwmap=mode=read,format=nv12\" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 \"/tmp/jellyfin/22dae171024b4cd6b6537f71fc235d40/%08d.jpg\""

**Comment by gnattu** [comment]
This is probably due to https://github.com/jellyfin/jellyfin/pull/12226 where the system has extra protections for using system temp. The previous behavior is to use the same dir in the data folder. Can you try set Env var `TMPDIR` to the cache folder of the Jellyfin data directory?

**Comment by gnattu** [comment]
If it does not error out like it was before it is probably doing its work but it is just slow. You can check the "Only Extract from keyframes" option to speed it up and retest with a small library like only containing one video.

**Comment by gnattu** [comment]
Hardware acceleration does not speed things up significantly, sometime even slower for trickplay. The only extract from keyframes provides significant performance boost.

**Comment by gnattu** [comment]
If you run this command directly in your console, what will ffmpeg complain about?

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -skip_frame nokey -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/superdrive/media/Movies/Example 2(2018)/Example 2 (2018) 1080p 10bit x265 HEVC.mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:out_range=pc:mode=hq:extra_hw_frames=24,hwmap=mode=read,format=nv12" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/d808535671894a0eb3df2a1ec46c612c/%08d.jpg"
```

Also what CPU are you using because the `Trickplay process unresponsive` message is only seen when the process is running for a very long time but failed to generate any images and if your CPU is just too slow that is inevitable.

**Comment by alexsilsync** [comment]
My CPU is Intel Core i5-8400 CPU @ 2.80GHz

When running the command as-is I get a permission error 

```
alex@Server:~$ /usr/lib/jellyfin-ffmpeg/ffmpeg -skip_frame nokey -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/superdrive/media/Movies/Example 2(2018)/Example 2 (2018) 1080p 10bit x265 HEVC.mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:out_range=pc:mode=hq:extra_hw_frames=24,hwmap=mode=read,format=nv12" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/d808535671894a0eb3df2a1ec46c612c/%08d.jpg"
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[AVHWDeviceContext @ 0x563e52cd4780] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value 'vaapi=va:/dev/dri/renderD128,driver=iHD' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument
```

But when I run it with sudo I see the following, I don't think permissions are an issue though as Jellyfin has no trouble transcoding with hardware

```
alex@Server:~$ sudo /usr/lib/jellyfin-ffmpeg/ffmpeg -skip_frame nokey -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/superdrive/media/Movies/Example 2(2018)/Example 2 (2018) 1080p 10bit x265 HEVC.mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:out_range=pc:mode=hq:extra_hw_frames=24,hwmap=mode=read,format=nv12" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/d808535671894a0eb3df2a1ec46c612c/%08d.jpg"
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
Input #0, matroska,webm, from 'file:/media/superdrive/media/Movies/Example 2(2018)/Example 2 (2018) 1080p 10bit x265 HEVC.mkv':
  Metadata:
    title           : Example 2 (2018)
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2023-02-01T13:56:06.000000Z
  Duration: 02:41:18.81, start: 0.000000, bitrate: 7535 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
      Metadata:
        BPS             : 6949049
        DURATION        : 02:41:18.669000000
        NUMBER_OF_FRAMES: 232056
        NUMBER_OF_BYTES : 8407194335
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (HE-AAC), 48000 Hz, 7.1, fltp (default)
      Metadata:
        title           : English
        BPS             : 355503
        DURATION        : 02:41:18.806000000
        NUMBER_OF_FRAMES: 226847
        NUMBER_OF_BYTES : 430106752
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (comment)
      Metadata:
        title           : English commentary
        BPS             : 192000
        DURATION        : 02:41:18.688000000
        NUMBER_OF_FRAMES: 302459
        NUMBER_OF_BYTES : 232288512
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle (pgssub), 1920x1080 (hearing impaired)
      Metadata:
        title           : English (SDH)
        BPS             : 38837
        DURATION        : 02:38:22.117000000
        NUMBER_OF_FRAMES: 4856
        NUMBER_OF_BYTES : 46129351
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: hdmv_pgs_subtitle (pgssub), 1920x1080 (comment)
      Metadata:
        title           : English commentary
        BPS             : 74505
        DURATION        : 02:41:10.119000000
        NUMBER_OF_FRAMES: 6872
        NUMBER_OF_BYTES : 90059099
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x700d1432e340] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x700d143c6080] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 2 times
Output #0, image2, to '/tmp/jellyfin/d808535671894a0eb3df2a1ec46c612c/%08d.jpg':
  Metadata:
    title           : Example 2 (2018)
    encoder         : Lavf61.1.100
  Stream #0:0: Video: mjpeg, yuvj420p(pc, unknown/bt709/bt709, progressive), 320x180 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 0.10 fps, 0.10 tbn (default)
      Metadata:
        BPS             : 6949049
        DURATION        : 02:41:18.669000000
        NUMBER_OF_FRAMES: 232056
        NUMBER_OF_BYTES : 8407194335
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2023-02-01 13:56:06
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
        encoder         : Lavc61.3.100 mjpeg
      Side data:
        cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[image2 @ 0x59f0ca255500] Could not open file : /tmp/jellyfin/d808535671894a0eb3df2a1ec46c612c/00000001.jpg
[vost#0:0/mjpeg @ 0x59f0ca3346c0] Error submitting a packet to the muxer: Input/output error
    Last message repeated 1 times
[out#0/image2 @ 0x59f0ca241200] Error muxing a packet
[out#0/image2 @ 0x59f0ca241200] Task finished with error code: -5 (Input/output error)
[out#0/image2 @ 0x59f0ca241200] Terminating thread with return code -5 (Input/output error)
[out#0/image2 @ 0x59f0ca241200] video:1KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=    1 fps=0.0 q=4.0 Lsize=N/A time=00:00:10.00 bitrate=N/A speed=  62x
Conversion failed!
```

**Comment by gnattu** [comment]
If you don't use '/tmp' but jellyfin temp do you still see the IO error? It looks like your system really hates us to use the `/tmp`

> I don't think permissions are an issue though as Jellyfin has no trouble transcoding with hardware

Transcoding cache does not use system temp so it is irrelevant.

**Comment by gnattu** [comment]
I suspect your issue is related to #12937, if your /tmp/jellyfin has numerous files then it is probably that.

**Comment by gnattu** [comment]
Did you try `mkdir -p /var/cache/jellyfin/d808535671894a0eb3df2a1ec46c612c` ? That folder might not exist so you need to create it manually.

**Comment by gnattu** [comment]
And you should not need sudo right?

So sum it up:

- You need to use the `TMPDIR` env variable as your OS has strict requirements on system temp path that requires permission that Jellyfin does not have
- You will want to use the keyframe only option as some of your videos might took too long.

**Comment by IlanKD** [comment]
Hello, 
I have the same issue :/ After a week or so of generating, the trickplay generation fails and when I'm trying to run the same command in the docker console as jellyfin, it is issuing this error
`Could not open file : /tmp/jellyfin/5e45258b72fb4668a14d90ba5ceb9203/00000001.jpg`

When I create the directory beforehand it works but it runs without issue for 80% of my library, I don't understand how it could have created the folder successfully for 80% but not for the remaining 20%

Any idea ?

**Comment by IlanKD** [comment]
Any news ?
