### ISSUE TITLE
TMBD Failed To Retrieve Results

### ISSUE THREAD

**Issue by thinhlegolas** [jellyfin/jellyfin#12939]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

TMDB is not retrieving results. I'm able to ping api.themoviedb.org.

### Reproduction steps

1. Sign in to Jellyfin web portal.
2. Click on the movie
3. Choose Identify
4. Supply IMDB ID
5. The wheel keeps on spinning.

### What is the current _bug_ behavior?

The wheel keeps on spinning without returning results.

### What is the expected _correct_ behavior?

The metadata is retrieved from TMDB.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

- OS: Ubuntu
- Linux Kernel:
- Virtualization:
- Clients: Jellyfin
- Browser: Safari
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

[2024-11-02 03:02:39.490 +00:00] [ERR] [42] MediaBrowser.Providers.Manager.ProviderManager: Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.FindAsync(FindExternalSource source, String id, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.FindByExternalIdAsync(String externalId, FindExternalSource source, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

### Client / Browser logs

thinhlegolas@htnas:~$ ping -c 4 api.themoviedb.org
PING api.themoviedb.org (13.35.210.61) 56(84) bytes of data.
64 bytes from server-13-35-210-61.sin2.r.cloudfront.net (13.35.210.61): icmp_seq=1 ttl=247 time=1.81 ms
64 bytes from server-13-35-210-61.sin2.r.cloudfront.net (13.35.210.61): icmp_seq=2 ttl=247 time=1.68 ms
64 bytes from server-13-35-210-61.sin2.r.cloudfront.net (13.35.210.61): icmp_seq=3 ttl=247 time=1.82 ms
64 bytes from server-13-35-210-61.sin2.r.cloudfront.net (13.35.210.61): icmp_seq=4 ttl=247 time=1.81 ms

--- api.themoviedb.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 5397ms
rtt min/avg/max/mdev = 1.680/1.778/1.820/0.057 ms

thinhlegolas@htnas:~$ dig api.themoviedb.org

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> api.themoviedb.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24963
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;api.themoviedb.org.		IN	A

;; ANSWER SECTION:
api.themoviedb.org.	53	IN	A	13.35.210.61
api.themoviedb.org.	53	IN	A	13.35.210.129
api.themoviedb.org.	53	IN	A	13.35.210.98
api.themoviedb.org.	53	IN	A	13.35.210.14

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Nov 02 13:05:06 +08 2024
;; MSG SIZE  rcvd: 111

### Additional information

I'm using 1.1.1.1 DNS in pfsense router.

**Comment by benedikt257** [comment]
Hey, does this happen consistently with all movies or just specific ones? If so, could you provide a TMDB ID for testing / repro?

**Comment by felix920506** [comment]
What country / region are you physically located in?

**Comment by thinhlegolas** [comment]
Hi @benedikt257  @felix920506 

Thanks for replying.

I have done a bit of checking from my end. The issue is the domain api.themoviedb.org resolves to the below 4 IPs on my server.

;; ANSWER SECTION:
api.themoviedb.org. 53 IN A 13.35.210.61
api.themoviedb.org. 53 IN A 13.35.210.129
api.themoviedb.org. 53 IN A 13.35.210.98
api.themoviedb.org. 53 IN A 13.35.210.14

However when I did the same using nslookup.io. I got the below IP. 

	IPv4 address	Revalidate in
Hosted by Amazon.com, Inc.65.8.161.126	19s
Hosted by Amazon.com, Inc.65.8.161.111	19s
Hosted by Amazon.com, Inc.65.8.161.37	19s
Hosted by Amazon.com, Inc.65.8.161.83	19s

So for now I've created an entry in /etc/hosts for the IP 65.8.161.83; and it's working fine.

I'm located in Singapore.

**Comment by felix920506** [comment]
In closing it since it's an issue with either DNS or TMDB.

**Comment by amogusussy** [comment]
In case anyone comes across this issue again, it can be fixed by disabling IPv6 in your docker compose. Add these lines at the bottom of the docker-compose.yml:

```yml
networks:
  jellyfin-net:
    driver: bridge
    enable_ipv6: false
```
