### ISSUE TITLE
Can't manipulate playlist using API tokens with no web session attached (Guid can't be empty)

### ISSUE THREAD

**Issue by blacklight** [jellyfin/jellyfin#12999]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Some playlist operations seem to be possible only from a web-based interface, and they fail when no session is attached.

### Reproduction steps

1. Get two Jellyfin tokens - one is an API-only token and the other is a standard browser token
2. Test e.g. a playlist item move API call with both:

```bash
$ curl -v -XPOST 'https://{media.server}/Playlists/{playlist-id}/Items/{playlist-item-id}/Move/{new-pos}' \
    -H 'Authorization: MediaBrowser Client="My Client", Device="My Device", Token="'$TOKEN'"
```

### What is the current _bug_ behavior?

Response when using the API token:

```
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Type: text/plain
Date: Sat, 09 Nov 2024 15:04:56 GMT
Server: nginx
Transfer-Encoding: chunked
X-Response-Time-ms: 55.0382

Error processing request.
```

### What is the expected _correct_ behavior?

Response when using the browser token:

```
HTTP/1.1 204 No Content
Connection: keep-alive
Date: Sat, 09 Nov 2024 15:01:57 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Response-Time-ms: 77.4317
X-XSS-Protection: 1; mode=block
```

### Jellyfin Server version

10.10.0+

### Specify the build version

10.9.10

### Environment

```markdown
- OS: Manjaro Linux
- Linux Kernel: 5.15.165
- Virtualization: none (pacman package)
- Clients: Browser, API
- Browser: N/A
- FFmpeg Version: 7.0.2
- Playback Method: N/A
- Hardware Acceleration: none
- GPU Model: none
- Plugins: N/A
- Reverse Proxy: nginx
- Base URL: N/A
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[16:04:56] [ERR] Error processing request. URL POST /Playlists/{playlist-id}/Items/{playlist-item-id}/Move/{new-pos}.
System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Jellyfin.Server.Implementations.Users.UserManager.GetUserById(Guid id)
   at Emby.Server.Implementations.Playlists.PlaylistManager.GetPlaylists(Guid userId)
   at Emby.Server.Implementations.Playlists.PlaylistManager.GetPlaylistForUser(Guid playlistId, Guid userId)
   at Jellyfin.Api.Controllers.PlaylistsController.MoveItem(String playlistId, String itemId, Int32 newIndex)
   at lambda_method1813(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell

```

**Comment by blacklight** [comment]
Looks like a duplicate of [this discussion](https://github.com/jellyfin/jellyfin/discussions/12868).

**Comment by Shadowghost** [comment]
I looked into it and it's more complicated to implement than I expected it to be. If I find the time I'll implement it, but no promises.

**Comment by blacklight** [comment]
If possible I'd disable the stale bot on this issue.

A workaround is available (namely use a browser session token as the API token), but the issue is still there.
