### ISSUE TITLE
Transcoding issues after upgrading Jellyfin to 10.10.1

### ISSUE THREAD

**Issue by namankanakiya** [jellyfin/jellyfin#12995]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to version 10.10.1, I've been running into transcoding issues. Any time the server needs to transcode (as is usually the case when there are files with subtitles), the video has artifacts, doubled subtitles, sometimes freezes (while the audio continues to play), is out of sync, sometimes repeats the audio

### Reproduction steps

Play any video that causes transcoding

### What is the current _bug_ behavior?

 Video has artifacts, doubled subtitles, sometimes freezes (while the audio continues to play), is out of sync, sometimes repeats the audio

### What is the expected _correct_ behavior?

Plays smoothly

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

```markdown
- OS: Ubuntu 24.04.1
- Linux Kernel: 6.8.0-48-generic
- Virtualization: Proxmox
- Clients: All clients (web, Android TV, iOS)
- Browser: Chrome
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: tried with both none and with Intel QSV
- GPU Model: UHD 730
- Plugins: None other than install default
- Reverse Proxy: none
- Base URL: none
- Networking: N/A
- Storage: SMB share (TrueNAS)
```

### Jellyfin logs

```shell
[2024-11-08 20:04:42.379 -05:00] [INF] User policy for "(user)". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-11-08 20:04:42.778 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-11-08 20:04:42.780 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts  -i file:\"/mnt/data/media/tv/3 Body Problem (2024) [tvdbid-411959]/Season 01/3 Body Problem (2024) - S01E01 - Countdown [WEBDL-2160p][DV HDR10][EAC3 Atmos 5.1][h265]-HHWEB.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename \"371c693201e2c727a69d276d2b1cf6eb-1.mp4\" -start_number 0 -hls_segment_filename \"/var/cache/jellyfin/transcodes/371c693201e2c727a69d276d2b1cf6eb%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/cache/jellyfin/transcodes/371c693201e2c727a69d276d2b1cf6eb.m3u8\""
[2024-11-08 20:04:44.170 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/mnt/data/media/tv/3 Body Problem (2024) [tvdbid-411959]/Season 01/3 Body Problem (2024) - S01E01 - Countdown [WEBDL-2160p][DV HDR10][EAC3 Atmos 5.1][h265]-HHWEB.mkv\" -copyts -map 0:3 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/3/3c0ead19-c2fd-253f-f0f8-fb94f5f2a24e.srt\" -map 0:4 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/2/2c1a259d-71e5-5dc9-3910-980972a7be10.srt\" -map 0:5 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/8/873ed3f0-1b10-66e4-035d-d77a002ecb4a.srt\" -map 0:6 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/5/5cce7fca-c27d-9d79-4bb9-8b943bfc9fb6.srt\" -map 0:7 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/9/977d994c-dcba-3ba7-07cf-722e6bc788d8.srt\" -map 0:8 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/d0844e0f-4603-d5d7-7f61-7e07ada8cafa.srt\" -map 0:9 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/0/00c1b9bc-c689-4f02-0b41-84f896c51ade.srt\" -map 0:10 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/6/6895fb2b-c4ef-7d27-704f-22301a22b7c3.srt\" -map 0:11 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/8/8b7e199d-973e-cdcb-ff67-cea0c89ccd17.srt\" -map 0:12 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/b/b2fc371d-4ed7-01f2-e58e-282856d4e342.srt\" -map 0:13 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/5/53b1336e-a158-805c-50e2-c04c7eacc37d.srt\" -map 0:14 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/3/39cee074-eb89-8aa2-b6fb-055bef320ca9.srt\" -map 0:15 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/f/f78f9571-eb1a-ba30-d7c9-599ebb57e209.srt\" -map 0:16 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/d4c9251f-8f43-da5c-fd72-d4a358f516ac.srt\" -map 0:17 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/7/7891781b-5916-4993-8f98-aff4847562ee.srt\" -map 0:18 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/a/a483eabf-0266-0bf6-2e8e-5657da52a530.srt\" -map 0:19 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/0/0bb42cbc-00b6-4e59-d601-4f9e99d193e6.srt\" -map 0:20 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/6/68c2a79e-adc2-e9ce-d837-b96cc9dbcbc3.srt\" -map 0:21 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/db7831bf-7266-450c-6777-f5f4b0e4a45c.srt\" -map 0:22 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/8/80e43b72-afc4-7a46-21e6-d736e059e3af.srt\" -map 0:23 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/d164205b-8d96-4bc4-cac0-1d7f6277015a.srt\" -map 0:24 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/a/ad9ac1c7-f903-24cd-6d6e-1dccb1c3776c.srt\" -map 0:25 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/f/f5c42156-1c08-b442-e6f6-0a3eb4147851.srt\" -map 0:26 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/d25fb1dd-b49f-9f42-2cf1-f9b4204de2db.srt\" -map 0:27 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/4/4184f33a-5c48-d434-9d50-3ee5674e315e.srt\" -map 0:28 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/f/f6e77295-0d6f-dc39-c47b-03d282416d80.srt\" -map 0:29 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/1/16630b77-b7fb-6a12-07cf-545432311a54.srt\" -map 0:30 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/5/543a2726-cf92-722f-6351-590963bda8ae.srt\" -map 0:31 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/8/80a815d8-fc7f-56a3-723b-a54527296152.srt\" -map 0:32 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/f/f2373ca7-fc55-ebfc-b63c-40ac6ce847bd.srt\" -map 0:33 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/9/942ab57e-2bc8-dcdb-b4e4-18e3c17f50b2.srt\" -map 0:34 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/e/e62b21c8-fd13-c7ca-dd18-ba09cb3f43e2.srt\" -map 0:35 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/b/bebab278-1ee3-44a6-f09f-81e4ad9aaf57.srt\" -map 0:36 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/d21653be-cfbf-4280-3893-91d53e2fb6da.srt\" -map 0:37 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/d/dce69716-927c-a626-6abf-b8ea967c67ac.srt\" -map 0:38 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/a/a51952a6-28fc-ee3e-4396-f18de163b12c.srt\""
[2024-11-08 20:05:00.043 -05:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-11-08 20:05:00.043 -05:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-11-08 20:05:00.044 -05:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2024-11-08 20:05:18.186 -05:00] [WRN] WS "192.168.51.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-11-08 20:05:18.194 -05:00] [INF] WS "192.168.51.1" closed
[2024-11-08 20:05:18.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:19.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:20.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:21.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:22.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:23.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:24.228 -05:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 08b36646162cddbedd3c4f440ce52a0d not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2024-11-08 20:05:36.289 -05:00] [INF] WS "192.168.51.1" request
[2024-11-08 20:05:48.874 -05:00] [INF] Stopping ffmpeg process with q command for "/var/cache/jellyfin/transcodes/371c693201e2c727a69d276d2b1cf6eb.m3u8"
[2024-11-08 20:05:53.874 -05:00] [INF] Killing FFmpeg process for "/var/cache/jellyfin/transcodes/371c693201e2c727a69d276d2b1cf6eb.m3u8"
[2024-11-08 20:05:53.874 -05:00] [INF] Deleting partial stream file(s) "/var/cache/jellyfin/transcodes/371c693201e2c727a69d276d2b1cf6eb.m3u8"
[2024-11-08 20:05:53.876 -05:00] [ERR] FFmpeg exited with code 137
[2024-11-08 20:05:55.392 -05:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.10.1" playing "Countdown". Stopped at "64491" ms
```

### FFmpeg logs

```shell
attached
```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/fe51fed8-a75b-496d-b320-1d51f6e32a39)

### Additional information

[ffmpegLog.txt](https://github.com/user-attachments/files/17685470/ffmpegLog.txt)

**Comment by namankanakiya** [comment]
This ended up being an issue with the backing NAS - I noticed from the logs above:
`Element at 0x57e99ec ending at 0xe484722 exceeds containing master element ending at 0x58439c6`

Looking that up, it seemed like the file itself was corrupted. I did a a ffprobe to see if it was so:
`ffprobe -v error "filename"

This came back with the same errors that I saw in the log, confirming the theory.

My setup involved copying the file from one folder into the jellyfin folder - I noticed that I could play the original file with no issues, but the copied file had issues. Subsequently, I did a sha256 sum to check if both were the same - it turned out that copying the file was somehow corrupting the copied files - the hashes were different.

After debugging the NAS, applying some updates etc, got back to normal behavior!
