### ISSUE TITLE
SQLite Error 8: 'attempt to write a readonly database' after jellyfin-server restart

### ISSUE THREAD

**Issue by minoskt** [jellyfin/jellyfin#13001]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Every time I restart the server, jellyfin never comes back. The service is dead. The following error is stored in the logs:

```
[2024-11-09 19:55:06.506 +00:00] [FTL] Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
```

Server is back when I restart the OS (Raspberry Pi OS).

### Reproduction steps

1. Login to Jellyfin Web
2. Settings > Dashboard
3. Click on Restart

The bug is 100% reproducable on my device.

### What is the current _bug_ behavior?

Server never comes back.

### What is the expected _correct_ behavior?

Server should be back online

### Jellyfin Server version

10.10.0+

### Specify the build version

 10.10.1

### Environment

```markdown
- Device: Raspberry Pi 4
- OS: Raspbery Pi OS 11 (64 bit)
- Linux Kernel: 6.1.21-v8+
- Clients: Browser
- Browser: Safari
```

### Jellyfin logs

```shell
[2024-11-09 19:45:56.707 +00:00] [INF] WS "2.30.116.249" request
[2024-11-09 19:46:07.124 +00:00] [INF] PlaybackReportingActivityController Loaded
[2024-11-09 19:46:07.125 +00:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/playback_reporting.db" is "delete"
[2024-11-09 19:46:40.563 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2024-11-09 19:50:59.249 +00:00] [INF] PlaybackReportingActivityController Loaded
[2024-11-09 19:50:59.250 +00:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/playback_reporting.db" is "delete"
[2024-11-09 19:51:24.641 +00:00] [INF] Plugin "installed": "TheTVDB" "18.0.0.0"
[2024-11-09 19:51:24.660 +00:00] [INF] App needs to be restarted.
[2024-11-09 19:55:06.095 +00:00] [INF] Sending shutdown notifications
[2024-11-09 19:55:06.106 +00:00] [INF] WS "2.30.116.249" closed
[2024-11-09 19:55:06.131 +00:00] [INF] Stopping NAT discovery
[2024-11-09 19:55:06.164 +00:00] [INF] Running query planner optimizations in the database... This might take a while
[2024-11-09 19:55:06.235 +00:00] [INF] Stopping directory watching for path "/raid/Media/Movies"
[2024-11-09 19:55:06.239 +00:00] [INF] Stopping directory watching for path "/raid/Media/Shows"
[2024-11-09 19:55:06.261 +00:00] [INF] Disposing "CoreAppHost"
[2024-11-09 19:55:06.262 +00:00] [INF] Disposing "MusicBrainzArtistProvider"
[2024-11-09 19:55:06.263 +00:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2024-11-09 19:55:06.264 +00:00] [INF] Disposing "PluginManager"
[2024-11-09 19:55:06.273 +00:00] [INF] Setting cache path: "/raid/jellyfin/cache"
[2024-11-09 19:55:06.288 +00:00] [INF] Loading assemblies
[2024-11-09 19:55:06.293 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.ChapterSegments, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Chapter Segments Provider_3.0.0.0/Jellyfin.Plugin.ChapterSegments.dll"
[2024-11-09 19:55:06.298 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Fanart, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Fanart_12.0.0.0/Jellyfin.Plugin.Fanart.dll"
[2024-11-09 19:55:06.303 +00:00] [INF] Loaded assembly "InfuseSync, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/InfuseSync_1.5.0.0/InfuseSync.dll"
[2024-11-09 19:55:06.313 +00:00] [INF] Loaded assembly "IntroSkipper, Version=1.10.10.6, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Intro Skipper_1.10.10.6/IntroSkipper.dll"
[2024-11-09 19:55:06.319 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2024-11-09 19:55:06.323 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2024-11-09 19:55:06.329 +00:00] [INF] Loaded assembly "SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll"
[2024-11-09 19:55:06.348 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Tvdb, Version=18.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_18.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2024-11-09 19:55:06.381 +00:00] [INF] Loaded assembly "Tvdb.Sdk, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_18.0.0.0/Tvdb.Sdk.dll"
[2024-11-09 19:55:06.384 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll"
[2024-11-09 19:55:06.399 +00:00] [INF] Loaded assembly "Trakt, Version=26.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Trakt_26.0.0.0/Trakt.dll"
[2024-11-09 19:55:06.415 +00:00] [INF] Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-09 19:55:06.415 +00:00] [INF] Defined LAN exclusions: []
[2024-11-09 19:55:06.415 +00:00] [INF] Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-09 19:55:06.416 +00:00] [INF] Filtered interface addresses: ["127.0.0.1", "192.192.1.202", "::1", "fd85:e295:141c:9549:ab32:8c23:750f:a5b9", "fe80::3633:d962:cf4d:2d7b%2"]
[2024-11-09 19:55:06.416 +00:00] [INF] Bind Addresses ["::"]
[2024-11-09 19:55:06.416 +00:00] [INF] Remote IP filter is "Allowlist"
[2024-11-09 19:55:06.416 +00:00] [INF] Filtered subnets: []
[2024-11-09 19:55:06.506 +00:00] [FTL] Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-11-09 19:55:06.508 +00:00] [INF] Running query planner optimizations in the database... This might take a while
[2024-11-09 19:55:06.522 +00:00] [INF] Disposing "CoreAppHost"
[2024-11-09 19:55:06.522 +00:00] [INF] Disposing "PluginManager"
```

### FFmpeg logs

```shell

```

**Comment by gnattu** [comment]
I think it is the `Jellyfin.Plugin.PlaybackReporting` plugin misbehaving, can you remove it and try again?

**Comment by minoskt** [comment]
That was indeed the problem! Thank you!

**Comment by KingDigweed** [comment]
I just encountered this issue on my new Jellyfin server. Same symptoms, same fix. I can live without the playback reporting plugin, but does anyone know what's the actual fix if we do want to use it?

**Comment by minoskt** [comment]
Indeed, issue still exists

**Comment by felix920506** [comment]
Please report the issue here
https://github.com/jellyfin/jellyfin-plugin-playbackreporting

**Comment by KingDigweed** [comment]
Ah my bad. Just for reference, it looks like this issue will be fixed in the next release of the plugin. :)
https://github.com/jellyfin/jellyfin-plugin-playbackreporting/issues/96

**Comment by bparkin1283** [comment]
You have a Jellyfin Project Official Plugin that breaks the startup of the core application initiated from the admin dashboard web console since at least Jul 10, 2024.

I would say the issue should stay here and consider removal from the official plugin page if it cannot be maintained to the extent of critically breaking the product.
