### ISSUE TITLE
M4B files missing metadata (tracknumbers, multi-artists and genres)

### ISSUE THREAD

**Issue by tfranken90** [jellyfin/jellyfin#13004]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When refreshing metadata for m4b files the track numbers, additional artists and additional genres disappear. 

### Reproduction steps

1. Update Jellyfin
2. Refresh metadata for an album with m4b files

### What is the current _bug_ behavior?

M4B files are missing metadata.

### What is the expected _correct_ behavior?

M4B files should provide metadata. 

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10

### Environment

```markdown
- OS: Fedora Atomic 41
- Linux Kernel: 6.11.5
- Virtualization: Podman (ghcr.io/jellyfin/jellyfin:latest)
- Clients: Browser
- Browser: Firefox
```

### Jellyfin logs

```shell
[2024-11-10 01:36:00.167 +00:00] [ERR] [35] MediaBrowser.Providers.Manager.ProviderManager: "CoverArtArchiveImageProvider" failed in GetImageInfos for type "MusicAlbum" at "/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)"
MetaBrainz.Common.HttpError: No cover art found for release 55ed6df7-7666-4650-a212-41e057edd6d3
 ---> MetaBrainz.Common.HttpError: HTTP 404 (NotFound) 'NOT FOUND'
   at MetaBrainz.Common.HttpUtils.EnsureSuccessfulAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.PerformRequestAsync(HttpMethod method, String endPoint, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.PerformRequestAsync(HttpMethod method, String endPoint, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.FetchReleaseAsync(String entity, Guid mbid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.CoverArtArchive.CoverArtArchiveImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2024-11-10 01:36:00.780 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/05 Hospital Radio.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.096 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/19 Me vs Hayers.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.172 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/13 Lift Off Show-Wise.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.262 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/12 Glen Ponderosa Musician.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.332 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/30 Forward Solutions.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.419 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/04 Carol.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.493 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/17 Return to Norwich.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.555 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/28 Good Grief.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.574 +00:00] [ERR] [31] TVHeadEnd.HTSP.HTSConnectionAsync: [TVHclient] HTSConnectionAsync.open: exception caught
System.Net.Sockets.SocketException (111): Connection refused [::1]:9982
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at TVHeadEnd.HTSP.HTSConnectionAsync.open(String hostname, Int32 port)
[2024-11-10 01:36:01.629 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/21 Hayers Dead.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.693 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/33 Hanging Up the Headphones.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.797 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/07 Joining the BBC.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.861 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/22 Homelessnessness.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:01.928 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/10 My Own Show.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.071 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/16 Yule Be Sorry.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.184 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/20 Proof That the Public Loved Me.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.268 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/31 North Norfolk Digital.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.335 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/03 East Anglia Polytechnic.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.392 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/23 Swallow.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.451 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/24 Marching On Skirmish.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.505 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/08 A Mighty Big Fish for a Pond This Size.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.571 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/27 Bouncing Back.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.632 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/09 The Move to TV.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.688 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/15 Splitting for Carol.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.751 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/26 Chin Up.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.819 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/06 Local Commercial Radio.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.898 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/14 The Death of Forbes McAllister.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:02.957 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/25 My Drink and Drugs Heck.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.089 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/01 Beginnings.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.178 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/02 Scouts and Schooling.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.236 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/18 Linton Travel Tavern.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.298 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/32 A Sidekick.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.362 +00:00] [INF] [13] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/29 Classic House.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.428 +00:00] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)/11 Radio s Loss.m4b\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-10 01:36:03.577 +00:00] [ERR] [31] TVHeadEnd.HTSP.HTSConnectionAsync: [TVHclient] HTSConnectionAsync.open: exception caught
System.Net.Sockets.SocketException (111): Connection refused [::1]:9982
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at TVHeadEnd.HTSP.HTSConnectionAsync.open(String hostname, Int32 port)
[2024-11-10 01:36:03.628 +00:00] [ERR] [13] MediaBrowser.Providers.Manager.ProviderManager: "CoverArtArchiveImageProvider" failed in GetImageInfos for type "MusicAlbum" at "/media/audiobooks/I, Partridge_ We Need to Talk About Alan (2011)"
MetaBrainz.Common.HttpError: No cover art found for release 55ed6df7-7666-4650-a212-41e057edd6d3
 ---> MetaBrainz.Common.HttpError: HTTP 404 (NotFound) 'NOT FOUND'
   at MetaBrainz.Common.HttpUtils.EnsureSuccessfulAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.PerformRequestAsync(HttpMethod method, String endPoint, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.PerformRequestAsync(HttpMethod method, String endPoint, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.FetchReleaseAsync(String entity, Guid mbid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.CoverArtArchive.CoverArtArchiveImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)


### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
Does it happen if you rename the file to .m4a?

**Comment by tfranken90** [comment]
@felix920506 Yes, and when I change it I get none of the Musicbrainz IDs either.

**Comment by gnattu** [comment]
Picard tags those mp4 based container in a weird way that multi albums are in an additional field that is not picked up (and actually, impossible to identify if that additional field is actually artists) so that only the first one is picked up. But mp4 does not have official multi value tags iirc so we could have tons of nonstandard behaviors. This needs to be investigated llater.

The MP4 based containers has a standard atom filed `trkn` but that is being used as both "Track number" and "Total track number". Currently it is mapped to total track number and Jellyfin does not record that value at all, which caused the track number being lost.

**Comment by gnattu** [comment]
We need to work with upstream lib to handle this better with requires some time.
