### ISSUE TITLE
Extreme Buffering with outdated Metadata of Show or Movie

### ISSUE THREAD

**Issue by ToasterUwU** [jellyfin/jellyfin#13039]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Context needed:
- I use Tdarr for transcoding everything into something easy to play (h264 with nothing but aac), so files get added, but then after get changed.
- Jellyfin does have this little handy "Refresh Metadata" button on each show and movies 3 dot menu, that has the "Scan for new and changed files" type as its default value. 

Im not entirely sure how to explain this the most straightforward way, so bear with me. 
When my files get transcoded and change to a significant extend, I get extreme buffering in Jellyfin on any and all players. There is no bottleneck anywhere, no CPU or RAM or IO or Network restrictions that would make the video buffer. 
I tried to find an infrastructure issue for the last 2 hours, and realized now that it has nothing to do with my infrastructure.

The fix is using the refresh metadata button. For some reason I don't even remotely understand, that fixes the playback entirely. 
Some before and after numbers:

1. Time until Media Player UI opens fully (With seekbar, play button, etc)
  - Before: ~30s
  - After: ~2s
2. Time for the video to start playing the first few frames after the UI loaded
  - Before: ~30s
  - After: ~1s
3. Time until the first buffering happens (Web Player)
  - Before: ~15s
  - After: Never
4. Time the buffering takes before it can play again
  - Before: ~30s
  - After: NA

### Reproduction steps

1. Add a Movie or show that uses codecs other than h264 or is unreasonably big for its length
2. Transcode Files using handbrake (Which is what Tdarr does) into h264, with HQ preset for the correct resolution. (I am very very sure this would happen with any other method and program)
3. Play the file via Jellyfin without refreshing the Metadata at all
4. Stream should be either be in Direct Play or Remuxing mode
5. Video should buffer all the time, UI when starting playback should be sluggish. (UI load up times from description)
6. Close Playback
7. Use "Refresh Metadata" Button with default value
8. Wait for that to finish (I wait like 10 seconds)
9. Try Playback again
10. See no buffering without good reason

### What is the current _bug_ behavior?

Playback is extremely slow for no reasonable reason.

### What is the expected _correct_ behavior?

Playback should only buffer when any part of the Infrastructure (CPU, RAM, IO, Network) cant keep up.

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.1

### Specify the build version

10.10.1

### Environment

```markdown
- OS:NixOS 24.05
- Linux Kernel: 6.6.60
- Virtualization: Docker
- Clients: Browser, Linux Media Player, Android TV
- Browser: Firefox 132.0.1
- FFmpeg Version: Whatever comes with 10.10.1 Docker
- Playback Method: Direct Play, Remux
- Hardware Acceleration: none
- GPU Model: none
- Plugins: AudioDB, Chapter Segments Provider, LDAP-Auth MusicBrainz, OMDb, Open Subtitles, Studio Images, TMDb, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge via Docker
- Storage: Local, SMB for Media
```

### Jellyfin logs

```shell
[2024-11-16 01:19:28.033 +00:00] [INF] [30] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Aki". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
[2024-11-16 01:19:29.066 +00:00] [INF] [32] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-11-16 01:19:29.067 +00:00] [INF] [32] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts  -i file:\"/media/Shows/English/Log Horizon/Season 1/Log Horizon - S01E03 - The Depths of Palm Bluray-1080p.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:6 -map 0:0 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename \"9b752fbcc3292a7dbff0cc21d13c679f-1.mp4\" -start_number 0 -hls_segment_filename \"/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f.m3u8\""
[2024-11-16 01:19:31.941 +00:00] [INF] [38] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Shows/English/Log Horizon/Season 3/Log Horizon - S03E12 - Song of the Nightingales Bluray-1080p v2.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-11-16 01:19:32.888 +00:00] [INF] [16] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f.m3u8"
[2024-11-16 01:19:33.493 +00:00] [INF] [16] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-11-16 01:19:33.497 +00:00] [INF] [16] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-11-16 01:19:33.498 +00:00] [INF] [16] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -ss 00:02:24.511 -noaccurate_seek -fflags +genpts  -i file:\"/media/Shows/English/Log Horizon/Season 1/Log Horizon - S01E03 - The Depths of Palm Bluray-1080p.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:6 -map 0:0 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename \"9b752fbcc3292a7dbff0cc21d13c679f-1.mp4\" -start_number 24 -hls_segment_filename \"/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f.m3u8\""
[2024-11-16 01:19:59.342 +00:00] [INF] [32] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/cache/transcodes/9b752fbcc3292a7dbff0cc21d13c679f.m3u8"
[2024-11-16 01:20:00.524 +00:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.10.1" playing "The Depths of Palm". Stopped at "738" ms
```

### FFmpeg logs

```shell

```

### Additional information

I was hesitant to make this Issue, since I thought "Maybe there is just a scheduled task to do this", but I checked, and there either isn't one or there is one but its named in a way that I don't recognize as the same thing "Refresh Metadata - Scan for new and updated files" does.

**Comment by ToasterUwU** [comment]
Update: Only like 15 minutes after the refresh button and playback test, it is back to being extremely slow. I havent changed anything and it still is broken in the exact same way. Interestingly enough it keeps buffering at the exact same spot on the episode i tried watching. I assume thats because its cached and just replayed from cache or something, but i dont actually know. It loads forever when starting playback, plays the same 20 seconds fine each time, than starts the endless buffering.

When i try to play the exact same file directly from the exact same location (My NAS) via something like VLC, i have not even a single second load time and not a single buffering session. 

I have absolutely no idea why this issue is a thing. There is not a single restrictions in the hardware, otherwise i would see it in my system monitor software, and at the same time direct play via sshfs and vlc works flawlessly.

**Comment by ToasterUwU** [comment]
I just noticed that i have an error text next to the "Scan Media Library" Scheduled Task. I checked the log and found the following, not sure if its actually relevant and how i would fix it.

```
[2024-11-16 01:21:01.260 +00:00] [ERR] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(SqliteCommand command)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetPeople(InternalPeopleQuery query)
   at Emby.Server.Implementations.Library.LibraryManager.GetPeople(BaseItem item)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.TV.Series.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-11-16 01:21:01.267 +00:00] [INF] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 45 seconds
```

**Comment by ToasterUwU** [comment]
I fixed the .db file using this method: https://stackoverflow.com/a/5316540

The Scan Library task is taking forever, but without errors. It probably didnt run for a while without failing. 
I will go to bed for now, this seems to be a few hours process.

I will write another comment tommorow when i know if that fixed/changed anything.

**Comment by ToasterUwU** [comment]
Ok, i waited for that to finish and tried a lot of things after, but its always the same. Jellyfin buffers while nothing is bottlenecking it, while the same file can be played with VLC flawlessly.

**Comment by ToasterUwU** [comment]
Another note worthy thing is that it gets less bad with less load on the infrastructure, meaning if I turn everything off it still buffers, but only for like 2-3 seconds instead of 30 seconds. But like I also mentioned multiple times, not a single thing is utilized to 100% even remotely. 

Remuxing or even Direct Playing a Video with 3.5 Mbps and sending it over a mostly unused Gigabit ethernet cable shouldn't be an issue, even if the infrastructure was used to nearly 100%

**Comment by ToasterUwU** [comment]
Sorry guys, turns out my SSD Cache on my NAS was doing really really weird things, and my system monitoring tool didn't recognize that as system load, even though it is in the real world... 

My bad, sorry for the wall of text.
