### ISSUE TITLE
[EfJellyfin.db] Migration from 10.8.13 fails

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin#13049]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When trying to migrate from a database thats still on 10.8.13 up to 10.11 the migration fails

### Reproduction steps

Setup a 10.8.13 instance.
Skip 10.9 and install 10.11

### What is the current _bug_ behavior?

Migration fails with exception

### What is the expected _correct_ behavior?

does not fail

### Jellyfin Server version

Unstable

### Specify the build version

latest

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-11-15 09:08:47.609 -05:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"MigrateLibraryDbData"'
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: LUFS'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Emby.Server.Implementations.Data.SqliteExtensions.Query(SqliteConnection sqliteConnection, String commandText)+MoveNext() in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Emby.Server.Implementations\Data\SqliteExtensions.cs:line 63
   at Jellyfin.Server.Migrations.Routines.MigrateLibraryDb.Perform() in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\Routines\MigrateLibraryDb.cs:line 94
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\MigrationRunner.cs:line 132
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\MigrationRunner.cs:line 69
[2024-11-15 09:08:47.652 -05:00] [FTL] [1] Main: Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: LUFS'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Emby.Server.Implementations.Data.SqliteExtensions.Query(SqliteConnection sqliteConnection, String commandText)+MoveNext() in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Emby.Server.Implementations\Data\SqliteExtensions.cs:line 63
   at Jellyfin.Server.Migrations.Routines.MigrateLibraryDb.Perform() in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\Routines\MigrateLibraryDb.cs:line 94
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\MigrationRunner.cs:line 132
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Migrations\MigrationRunner.cs:line 69
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Jellyfin.Server\Program.cs:line 161
```

### FFmpeg logs

```shell

```

**Comment by TheMelmacian** [comment]
I had a look. The problem is that the TypedBaseItems table was created and updated in the [SqliteItemRepository.cs](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Data/SqliteItemRepository.cs) class.
You deleted the SqliteItemRepository.cs in your [branch](https://github.com/jellyfin/jellyfin/pull/12798/files) but there is no replacement for the table and column creation that was handled inside the class, including the addition of the `LUFS` column.

If the intention is to get rid of the SqliteItemRepository class, everything should be moved to separate migration routines.

**Comment by JPVenson** [comment]
There is an replacement:
https://github.com/jellyfin/jellyfin/pull/12798/files#diff-cecd04310e3c734033ce9d1f777919a2c1ffdd45ca321a3c32d0386110a17b47R105
Including migrations

**Comment by TheMelmacian** [comment]
I see table creation routines, but there is no migration that handles the changes of the TypedBaseItems table in the library.db from any starting point up to 10.10.z.
So any changes that were made between the initial database creation and 10.10.z are no longer applied. Other tables from the library.db could also affected by this.

Before the MigrateLibraryDB routine can be executed to move everything from the library.db to the jellyfin.db, you have to make sure the library.db is up to date and contains all expected columns.


One valid option could be:
- use `SELECT * FROM TypedBaseItems` instead of listing each column separately
- extend [SqliteExtensions.cs](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Data/SqliteExtensions.cs) with column name based TryGet... methods
- use column names instead of index in mapper method

But if a column type was changed, there is still a chance of an error. The older the JF install, the higher the risk.

**Comment by TheMelmacian** [comment]
@JPVenson Do you want any help with this? I could provide a new migration routine that brings the old library.db up to date from any starting point (like the SqliteItemRepository did till now). Or I could try to change the mapper so it can work with column names instead of indexes, as suggested above.

**Comment by JPVenson** [comment]
we have been discussing this internally. 
My current stance on the topic is that the current PR is designed to work off a 10.10 database, as this is a break in migrations and we have to go from a known point. We never supported jumping minor versions. I am not opposed to create a follow up PR that reintroduces a migration to bring the old library.db up to speed or bring it into a coherent state before the migration, but thats not part of the current PR. 

Please really dont missunderstand me, i have been working for 2 months more or less straight on that PR and my time to bring it in is very limited i can't keep expanding that PRs functionality otherwise it will never get done. I can't barely get any coherent reviews on it even in its current state due to size and complexity.

I'll currently tend towards: "Put it on the list of things to fix later".

**Comment by TheMelmacian** [comment]
Yeah, don't stress yourself. The "fix" doesn't need to be part of the current PR.
But my offer stands. I can prepare a migration locally and after the PR is merged I can open a new pull request.

**Comment by theguymadmax** [comment]
Note: 

Jellyfin will automatically backup ( #13754) the jellyfin.db when applying db migrations. But not before normal migrations.

Trying to restore from that backup will fail with the below message:
```
[09:22:13] [FTL] [1] Main: Error while starting server.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: u.EasyPassword'.
```
A user backup must be made prior to an attempted upgrade in order to rollback when the migration fails.

**Comment by felix920506** [comment]
@JPVenson says wontfix, users will have to upgrade to 10.10 before upgrading to 10.11

**Comment by nielsvanvelzen** [comment]
As mentioned in chat, even if we won't allow upgrading from 10.8 directly we should still make sure the logs are understandable when you try to. As far as I'm aware it currently is not (see logs in issue description). Therefor re-opening the issue.

**Comment by TheMelmacian** [comment]
You should reconsider this.
Without a migration file, the server needs to correctly identify if the database is ready, and if not don't touch it at all or roll back the changes (restore the backup), while stating in the log that the user has to install 10.10 first.

On a major version update this would be OK, but not for a "minor" version. IMHO that's bad design.
The update code is already present in the old `SqliteUserDataRepository.cs` and `SqliteItemRepository.cs` classes. It just needs to be adapted into migration files.

**Comment by JPVenson** [comment]
>  It just needs to be adapted into migration files.

Be my guest by all means

**Comment by TheMelmacian** [comment]
https://github.com/jellyfin/jellyfin/pull/14051

**Comment by theguymadmax** [comment]
Update:
In a failed upgrade attempt to 10.11 from 10.8.13, the jellyfin.db and library.db files remain intact. This allows users to continue using version 10.8.13 or perform incremental upgrades before attempting the 10.11 update again.

To recover, users need to:

1. Restore config/migrations.xml.backup (automatically backed up)
2. Delete config/network.xml
