### ISSUE TITLE
10.10.2 unable to start with read-only library (Migration fails)

### ISSUE THREAD

**Issue by Eisaichen** [jellyfin/jellyfin#13066]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Server keeps crashing after upgrading from 10.10.1 to 10.10.2, due to the following migration action related to music files:
```
[14:15:34] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'RemoveDuplicatePlaylistChildren'
[14:15:35] [WRN] [1] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path C:\media\music\Original CD\Catherine\Catherine Original Soundtrack by Shoji Meguro (2011)\CATHERINE Original Soundtrack (English).cue
[14:15:35] [WRN] [1] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path C:\media\music\Original CD\Catherine\Catherine Sound Disc by Shoji Meguro (2011)\CATHERINE Sound Disc (English).cue
[14:15:35] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'RemoveDuplicatePlaylistChildren'
System.UnauthorizedAccessException: Access to the path 'C:\media\music\Original CD\Catherine\Tracklist (English).m3u' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Emby.Server.Implementations.Playlists.PlaylistManager.SavePlaylistFile(Playlist item)
   at Jellyfin.Server.Migrations.Routines.RemoveDuplicatePlaylistChildren.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[14:15:35] [FTL] [1] Main: Error while starting server
System.UnauthorizedAccessException: Access to the path 'C:\media\music\Original CD\Catherine\Tracklist (English).m3u' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Emby.Server.Implementations.Playlists.PlaylistManager.SavePlaylistFile(Playlist item)
   at Jellyfin.Server.Migrations.Routines.RemoveDuplicatePlaylistChildren.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
```
The configuration remains the same, server works again if downgraded to 10.10.1.
Is mount a read-only library still supported?

### Reproduction steps

1. Mount a read-only music library.
2. Upgrade to 10.10.2
3. Run the server.

### What is the current _bug_ behavior?

Server crashes after launch.

### What is the expected _correct_ behavior?

Server is able to run.

### Jellyfin Server version

10.10.0+

### Specify commit id

be23f4eb0d94217f6e38a45c9a7343fbfd6886cd

### Specify version number

10.10.2

### Specify the build version

10.10.2

### Environment

```markdown
- OS: Windows 11
- Linux Kernel: None
- Virtualization: None
- Clients: N/A
- Browser: N/A
- FFmpeg Version: Integrated
- Playback Method: N/A
- Hardware Acceleration: NVENC
- Storage: SMB with read-only permissions
```

### Jellyfin logs

```shell
[14:15:23] [INF] [1] Main: Jellyfin version: 10.10.2
[14:15:23] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, c:\\data\\log]"]
[14:15:23] [INF] [1] Main: Arguments: ["C:\\jellyfin\\system\\jellyfin.dll", "-d", "c:\\data", "--service"]
[14:15:23] [INF] [1] Main: Operating system: Microsoft Windows 10.0.26100
[14:15:23] [INF] [1] Main: Architecture: X64
[14:15:23] [INF] [1] Main: 64-Bit Process: True
[14:15:23] [INF] [1] Main: User Interactive: False
[14:15:23] [INF] [1] Main: Processor count: 16
[14:15:23] [INF] [1] Main: Program data path: c:\data
[14:15:23] [INF] [1] Main: Log directory path: c:\data\log
[14:15:23] [INF] [1] Main: Config directory path: c:\data\config
[14:15:23] [INF] [1] Main: Cache path: c:\data\cache
[14:15:23] [INF] [1] Main: Temp directory path: C:\Users\ContainerAdministrator\AppData\Local\Temp\jellyfin
[14:15:23] [INF] [1] Main: Web resources path: C:\jellyfin\system\jellyfin-web
[14:15:23] [INF] [1] Main: Application directory: C:\jellyfin\system\
[14:15:23] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: c:\data\cache
[14:15:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniDB, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\AniDB_9.0.0.0\Jellyfin.Plugin.AniDB.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\DLNA_5.0.0.0\Jellyfin.Plugin.Dlna.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\DLNA_5.0.0.0\Jellyfin.Plugin.Dlna.Model.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\DLNA_5.0.0.0\Jellyfin.Plugin.Dlna.Playback.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Rssdp, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\DLNA_5.0.0.0\Rssdp.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly InfuseSync, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\InfuseSync_1.5.0.0\InfuseSync.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\Kodi Sync Queue_13.0.0.0\Jellyfin.Plugin.KodiSyncQueue.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LiteDB, Version=5.0.15.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from c:\data\plugins\Kodi Sync Queue_13.0.0.0\LiteDB.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\Session Cleaner_4.0.0.0\Jellyfin.Plugin.SessionCleaner.dll
[14:15:23] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from c:\data\plugins\Subtitle Extract_4.0.0.0\Jellyfin.Plugin.SubtitleExtract.dll
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.1.2", "127.0.0.1"]
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[14:15:23] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniDB 9.0.0.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: DLNA 5.0.0.0
[14:15:34] [INF] [1] InfuseSync.Plugin: InfuseSync is starting.
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: InfuseSync 1.5.0.0
[14:15:34] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.KodiSyncQueuePlugin: KodiSyncQueue is starting...
[14:15:34] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Kodi Sync Queue 13.0.0.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Session Cleaner 4.0.0.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Subtitle Extract 4.0.0.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.2.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.2.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.2.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.2.0
[14:15:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.2.0
[14:15:34] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'RemoveDuplicatePlaylistChildren'
[14:15:35] [WRN] [1] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path C:\media\music\Original CD\Catherine\Catherine Original Soundtrack by Shoji Meguro (2011)\CATHERINE Original Soundtrack (English).cue
[14:15:35] [WRN] [1] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path C:\media\music\Original CD\Catherine\Catherine Sound Disc by Shoji Meguro (2011)\CATHERINE Sound Disc (English).cue
[14:15:35] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'RemoveDuplicatePlaylistChildren'
System.UnauthorizedAccessException: Access to the path 'C:\media\music\Original CD\Catherine\Tracklist (English).m3u' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Emby.Server.Implementations.Playlists.PlaylistManager.SavePlaylistFile(Playlist item)
   at Jellyfin.Server.Migrations.Routines.RemoveDuplicatePlaylistChildren.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[14:15:35] [FTL] [1] Main: Error while starting server
System.UnauthorizedAccessException: Access to the path 'C:\media\music\Original CD\Catherine\Tracklist (English).m3u' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Emby.Server.Implementations.Playlists.PlaylistManager.SavePlaylistFile(Playlist item)
   at Jellyfin.Server.Migrations.Routines.RemoveDuplicatePlaylistChildren.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[14:15:35] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[14:15:35] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[14:15:35] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[14:15:35] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[14:15:35] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing KodiSyncQueuePlugin
[14:15:35] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
jellyfin exited with code 0
```

### FFmpeg logs

```shell

```

**Comment by dlucksinger** [comment]
Hello @Eisaichen I just got this same error, how do I fix it?

Thank you,

Derek

**Comment by Eisaichen** [comment]
@dlucksinger 
A temporary workaround is here: https://github.com/jellyfin/jellyfin/issues/13048#issuecomment-2481057319
Or wait for the next release, the fix is already merged.

**Comment by joshuaboniface** [comment]
10.10.3 was just released with this fix.

**Comment by dlucksinger** [comment]
Thank you @Eisaichen
