### ISSUE TITLE
Server crashed while scanning library

### ISSUE THREAD

**Issue by simon-kolkmann** [jellyfin/jellyfin#13096]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I was moving and renaming some files in my library while Jellyfin was scanning said library. Suddenly the server crashed completely.

### Reproduction steps

1. Run media library scan
2. Move some files around
3. ???
4. Crash

### What is the current _bug_ behavior?

The library scan failed spectacularly with a fatal error that brought the server down.

### What is the expected _correct_ behavior?

Jellyfin should probably not crash completely - maybe the item could be skipped, maybe the library scan should be aborted. But the server should stay online.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Linux
- Linux Kernel: 6.8.12-1
- Virtualization: I'm running the official docker image in kubernetes
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: 
- GPU Model: 
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: My media is mounted via NFS share
```

### Jellyfin logs

```shell
A lot of entries like this:

[2024-11-23 22:19:48.796 +00:00] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/series/foo/Season 4/barsub\" -threads 0 -v warning -print_format json -show_streams -show_format"

Then:

[2024-11-23 22:19:48.975 +00:00] [FTL] [8] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Controller.Entities.TV.Season.GetEpisodes(User user, DtoOptions options, Boolean shouldIncludeMissingEpisodes)
   at MediaBrowser.Controller.Entities.TV.Season.GetItemsInternal(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.FillUserDataDtoValues(UserItemDataDto dto, UserItemData userData, BaseItemDto itemDto, User user, DtoOptions fields)
   at Emby.Server.Implementations.Library.UserDataManager.GetUserDataDto(BaseItem item, User user)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.<>c__DisplayClass12_0.<GetUserDataChangeInfo>b__1(BaseItem i)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.GetUserDataChangeInfo(Guid userId, List`1 changedItems)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.<>c__DisplayClass11_0.<UpdateTimerCallback>b__0()
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToUserSessions[T](List`1 userIds, SessionMessageType name, Func`1 dataFn, CancellationToken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.UpdateTimerCallback(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

The next log lines show the server starting up again.
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
Please provide a complete list of plugins

**Comment by simon-kolkmann** [comment]
Sure!

- AudioDB, 10.10.3.0
- MusicBrainz, 10.10.3.0
- OMDb, 10.10.3.0
- Playback Reporting, 15.0.0.0
- Studio Images, 10.10.3.0
- TMDb, 10.10.3.0
- TheTVDB, 18.0.0.0 (<- I've installed this one recently)

**Comment by gnattu** [comment]
It appears that you are moving files around while the scan is still in progress, which could lead to undefined behaviors, including server crashes. Unfortunately, we can’t do much about this since the files are expected to remain constant throughout the entire scan process. You can add more files (might not get indexed if you do and may require start a scan task again), but you can’t move or delete any files. If the files are in the “to be processed” list and then removed, the server will definitely panic.

**Comment by simon-kolkmann** [comment]
> If the files are in the “to be processed” list and then removed, the server will definitely panic.

I thought that maybe the server could rather catch this kind of error instead of panicking. But if this is expected behaviour, feel free to close this issue.
