### ISSUE TITLE
Backdrops not visible for albums

### ISSUE THREAD

**Issue by przemek54** [jellyfin/jellyfin#13119]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Selecting a backdrop image for music albums specifically results in no backdrop image being displayed, despite the "enable backdrops" option being on. In the "edit images" tab, the backdrop appears as a blank rectangle that is impossible to delete (except through refreshing the album's metadata with the replace images option). Notably, this only seems to affect music albums. All other media types (movies, artists) function as expected.

There is a way to get a backdrop on an album's page, and that is to add a backdrop to its album artist. However, it means that it's currently impossible to assign different backdrops to different albums from the same artist. Interestingly, when any album artist in the library has a backdrop image, albums that I have uploaded backdrops to also share that same image, even if they don't belong to the same artist, and even when the image is totally different.

The uploaded backdrop does appear in the appropriate folder of the album as "backdrop.png" (or .jpg), so it doesn't seem to be an issue of sending the image to the correct location.

NOTE: Not sure how relevant it is, but refreshing the album's metadata (with the "replace all metadata" option and "replace existing images" checked on) also removes the backdrop of its album artist. Maybe it's an intended feature.

### Reproduction steps

1. Sign in to Jellyfin
2. Navigate to a library that contains music
3. Make sure that no artist has a backdrop image
4. Select the "Albums" tab on the top bar
5. Click any album
6. Under the three-dots menu, click "Edit images"
7. Click the "+" icon and select an image
8. Set the "image type" to "backdrop"
9. Click "upload"
10. Click off the "Edit images" menu and refresh. There is likely no backdrop visible
11. Open the "Edit images" menu again
12. You now should see a "Backdrops" section in the "edit images" menu. Click the trash bin icon on the element you uploaded and confirm by pressing "Delete"

### What is the current _bug_ behavior?

After uploading the image, it shows up as blank in the "Edit images" menu. After refreshing, there is no backdrop in the background. The deletion in step 11 does not take place.

### What is the expected _correct_ behavior?

After uploading the image, it correctly displays in the "Edit images" menu. After refreshing, there should be a backdrop. Clicking the trash bin should successfully delete the image.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients: Browser
- Browser: Firefox, Chrome
- FFmpeg Version: 7.0.2
- Hardware Acceleration: None
- GPU Model: NVIDIA GeForce GTX 1050 Ti
- Plugins: AudioDB, InfuseSync, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2024-11-27 20:15:39.008 -05:00] [INF] [1] Main: Jellyfin version: "10.10.3"
[2024-11-27 20:15:39.033 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\ProgramData\Jellyfin\Server\log]"]
[2024-11-27 20:15:39.040 -05:00] [INF] [1] Main: Arguments: ["D:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "D:\ProgramData\Jellyfin\Server"]
[2024-11-27 20:15:39.044 -05:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.19045"
[2024-11-27 20:15:39.046 -05:00] [INF] [1] Main: Architecture: X64
[2024-11-27 20:15:39.048 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-11-27 20:15:39.050 -05:00] [INF] [1] Main: User Interactive: True
[2024-11-27 20:15:39.051 -05:00] [INF] [1] Main: Processor count: 8
[2024-11-27 20:15:39.053 -05:00] [INF] [1] Main: Program data path: "D:\ProgramData\Jellyfin\Server"
[2024-11-27 20:15:39.055 -05:00] [INF] [1] Main: Log directory path: "D:\ProgramData\Jellyfin\Server\log"
[2024-11-27 20:15:39.057 -05:00] [INF] [1] Main: Config directory path: "D:\ProgramData\Jellyfin\Server\config"
[2024-11-27 20:15:39.059 -05:00] [INF] [1] Main: Cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2024-11-27 20:15:39.061 -05:00] [INF] [1] Main: Temp directory path: "C:\Users\Przemek prywatne\AppData\Local\Temp\jellyfin"
[2024-11-27 20:15:39.063 -05:00] [INF] [1] Main: Web resources path: "D:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-11-27 20:15:39.064 -05:00] [INF] [1] Main: Application directory: "D:\Program Files\Jellyfin\Server\"
[2024-11-27 20:15:39.189 -05:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2024-11-27 20:15:39.260 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-11-27 20:15:39.273 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "InfuseSync, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" from "D:\ProgramData\Jellyfin\Server\plugins\InfuseSync_1.5.0.0\InfuseSync.dll"
[2024-11-27 20:15:39.393 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-27 20:15:39.398 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-11-27 20:15:39.400 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-27 20:15:39.404 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.1.120", "127.0.0.1"]
[2024-11-27 20:15:39.406 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-11-27 20:15:39.409 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-11-27 20:15:39.410 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-11-27 20:15:44.623 -05:00] [INF] [1] InfuseSync.Plugin: InfuseSync is starting.
[2024-11-27 20:15:44.666 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "InfuseSync" "1.5.0.0"
[2024-11-27 20:15:44.670 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.10.3.0"
[2024-11-27 20:15:44.674 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.10.3.0"
[2024-11-27 20:15:44.676 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.10.3.0"
[2024-11-27 20:15:44.703 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.10.3.0"
[2024-11-27 20:15:44.707 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.10.3.0"
[2024-11-27 20:15:44.760 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"RemoveDuplicatePlaylistChildren"'
[2024-11-27 20:15:44.894 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"RemoveDuplicatePlaylistChildren"' applied successfully
[2024-11-27 20:15:44.948 -05:00] [INF] [1] Main: Kestrel is listening on "0.0.0.0"
[2024-11-27 20:15:45.532 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-11-27 20:15:45.533 -05:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library"
[2024-11-27 20:15:45.533 -05:00] [INF] [6] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Playlists"
[2024-11-27 20:15:45.535 -05:00] [INF] [1] InfuseSync.ScheduledTasks.HousekeepingTask: Infuse housekeeping task scheduled.
[2024-11-27 20:15:45.554 -05:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Remove Old Cached Data" set to fire at 2024-11-28 00:01:00.000 -05:00, which is 03:45:14.4460771 from now.
[2024-11-27 20:15:45.563 -05:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-11-28 03:00:00.000 -05:00, which is 06:44:14.4370003 from now.
[2024-11-27 20:15:45.570 -05:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-11-28 02:00:00.000 -05:00, which is 05:44:14.4297561 from now.
[2024-11-27 20:15:45.825 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "7.0.2"
[2024-11-27 20:15:45.882 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "ac4", "dca", "flac", "mp3", "truehd"]
[2024-11-27 20:15:45.947 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mjpeg_qsv", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-11-27 20:15:46.001 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["bwdif_cuda", "deinterlace_qsv", "hwupload_cuda", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemapx", "tonemap_cuda", "tonemap_opencl", "transpose_cuda", "transpose_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-11-27 20:15:46.188 -05:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2024-11-27 20:15:46.239 -05:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vulkan" with option "Action to take when encountering EOF from secondary input" is not available
[2024-11-27 20:15:46.315 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl", "d3d12va"]
[2024-11-27 20:15:47.849 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2024-11-27 20:15:47.852 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "5b07d6794f2a438488bd656636550e5e"
[2024-11-27 20:15:47.854 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-11-27 20:15:47.856 -05:00] [INF] [1] Main: Startup complete 0:00:09.0121544
[2024-11-27 20:15:48.590 -05:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean Transcode Directory" Completed after 0 minute(s) and 0 seconds
[2024-11-27 20:15:48.646 -05:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-11-27 20:15:49.453 -05:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2024-11-27 20:15:49.491 -05:00] [INF] [9] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-11-27 20:16:16.217 -05:00] [INF] [9] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2024-11-27 20:16:17.070 -05:00] [INF] [18] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-11-27 20:16:26.639 -05:00] [INF] [16] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating\01. Neilio - Captivating.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 20:17:09.285 -05:00] [INF] [22] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.126" request
[2024-11-27 20:17:16.109 -05:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.126" closed
[2024-11-27 20:17:16.424 -05:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.126" request
[2024-11-27 20:23:27.191 -05:00] [ERR] [30] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN8F98NSDQEC"", Request id ""0HN8F98NSDQEC:00000001"": An unhandled exception was thrown by the application.
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2024-11-27 20:25:45.820 -05:00] [INF] [57] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.126" closed
[2024-11-27 20:25:46.617 -05:00] [INF] [49] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.126" request
[2024-11-27 20:26:36.431 -05:00] [INF] [57] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Ephixa\Dubstep Killed Rock 'n' Roll\01. Ephixa - Dubstep Killed Rock 'n' Roll.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 20:28:18.154 -05:00] [INF] [56] Emby.Server.Implementations.IO.LibraryMonitor: "Neilio" ("D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio") will be refreshed.
[2024-11-27 20:28:18.655 -05:00] [ERR] [61] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\backdrop.png"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-11-27 20:28:18.788 -05:00] [INF] [59] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating\01. Neilio - Captivating.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 20:28:53.083 -05:00] [INF] [61] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:29:18.787 -05:00] [INF] [56] Emby.Server.Implementations.IO.LibraryMonitor: "Captivating" ("D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating") will be refreshed.
[2024-11-27 20:31:41.084 -05:00] [INF] [62] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:34:29.085 -05:00] [INF] [46] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:37:53.087 -05:00] [INF] [42] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:39:51.634 -05:00] [ERR] [38] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN8F98NSDQGO"", Request id ""0HN8F98NSDQGO:00000001"": An unhandled exception was thrown by the application.
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2024-11-27 20:40:41.072 -05:00] [INF] [28] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:43:29.075 -05:00] [INF] [35] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:46:53.083 -05:00] [INF] [40] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:47:17.098 -05:00] [INF] [21] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image "D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\backdrop.png"
[2024-11-27 20:49:41.086 -05:00] [INF] [49] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:52:29.072 -05:00] [INF] [42] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:55:53.072 -05:00] [INF] [24] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 20:58:41.079 -05:00] [INF] [61] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:01:29.080 -05:00] [INF] [59] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:03:41.090 -05:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Ephixa\Dubstep Killed Rock 'n' Roll\01. Ephixa - Dubstep Killed Rock 'n' Roll.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 21:04:30.363 -05:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Tim Berg\Seek Bromance\01. Tim Berg - Seek Bromance.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 21:04:41.090 -05:00] [INF] [51] Emby.Server.Implementations.IO.LibraryMonitor: "Dubstep Killed Rock 'n' Roll" ("D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Ephixa\Dubstep Killed Rock 'n' Roll") will be refreshed.
[2024-11-27 21:04:53.084 -05:00] [INF] [51] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:07:41.075 -05:00] [INF] [62] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:09:34.975 -05:00] [INF] [15] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Tim Berg\Seek Bromance\01. Tim Berg - Seek Bromance.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 21:10:29.071 -05:00] [INF] [8] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:17:14.428 -05:00] [ERR] [71] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "The process cannot access the file 'D:\ProgramData\Jellyfin\Server\log\log_20241127.log' because it is being used by another process". URL "GET" "/System/Logs/Log".
[2024-11-27 21:17:17.222 -05:00] [ERR] [71] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "The process cannot access the file 'D:\ProgramData\Jellyfin\Server\log\log_20241127.log' because it is being used by another process". URL "GET" "/System/Logs/Log".
[2024-11-27 21:17:19.241 -05:00] [INF] [71] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2024-11-27 21:17:19.447 -05:00] [INF] [71] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\ProgramData\Jellyfin\Server\cache"
[2024-11-27 21:17:19.451 -05:00] [INF] [70] Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
[2024-11-27 21:17:21.931 -05:00] [ERR] [70] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "The process cannot access the file 'D:\ProgramData\Jellyfin\Server\log\log_20241127.log' because it is being used by another process". URL "GET" "/System/Logs/Log".
[2024-11-27 21:22:22.865 -05:00] [INF] [71] Emby.Server.Implementations.IO.LibraryMonitor: "Captivating" ("D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating") will be refreshed.
[2024-11-27 21:24:53.075 -05:00] [INF] [67] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:26:20.743 -05:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating\01. Neilio - Captivating.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-11-27 21:26:51.843 -05:00] [ERR] [18] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "The process cannot access the file 'D:\ProgramData\Jellyfin\Server\log\log_20241127.log' because it is being used by another process". URL "GET" "/System/Logs/Log".
[2024-11-27 21:26:58.752 -05:00] [ERR] [76] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN8F98NSDQLR"", Request id ""0HN8F98NSDQLR:00000001"": An unhandled exception was thrown by the application.
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Jellyfin.Api.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2024-11-27 21:27:20.737 -05:00] [INF] [76] Emby.Server.Implementations.IO.LibraryMonitor: "Captivating" ("D:\[MOJE PLIKI]\[MUZYKA]\muzyka\Library\Neilio\Captivating") will be refreshed.
[2024-11-27 21:27:41.078 -05:00] [INF] [76] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:30:29.074 -05:00] [INF] [65] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:33:53.083 -05:00] [INF] [82] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:36:41.078 -05:00] [INF] [68] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:39:29.070 -05:00] [INF] [14] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:42:53.070 -05:00] [INF] [67] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-27 21:46:53.071 -05:00] [INF] [63] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

**What happens:**

![Image](https://github.com/user-attachments/assets/63e21463-f893-47c4-83b7-11c65f597b9d)
![Image](https://github.com/user-attachments/assets/c9d78dcd-3653-4808-a8e1-3a6be21bd57a)

**What should happen:**
_I'm using an album artist as an example._

![Image](https://github.com/user-attachments/assets/fac08387-2a4f-43b5-ab6f-39913172f7e6)
![Image](https://github.com/user-attachments/assets/08bcb6df-dea2-44d6-926b-79192e3d738c)

NOTE: I'm using a theme (which is why my Jellyfin looks different in the screenshots) but it is the same if no theme is selected.

### Additional information

This issue has been raised before ([here](https://github.com/jellyfin/jellyfin/issues/9520), [here](https://github.com/jellyfin/jellyfin-web/issues/5515)) but was closed due to inactivity. It has also been successfully reproduced by forum member TheDreadPirate [here](https://forum.jellyfin.org/t-backdrops-don-t-work-for-music-albums).

**Comment by solidsnake1298** [comment]
I was able to reproduce, as mentioned, with the steps provided.  Additionally, backdrop images located in the album folder also produces the same problem.

**Comment by Ronny12301** [comment]
I had the same issue, that's why I'm here, I hope there's a solution.

**Comment by rainer-geiger** [comment]
Same here

**Comment by KevGamesUltimate** [comment]
got the same issue

**Comment by felix920506** [comment]
*please use the thumbs up reaction instead of commenting "same" to avoid clutter, thanks*

**Comment by sinterdev** [comment]
Looks like the existing code was forcing the album backdrop to be the same as the artist backdrop. This should be fixed by #13317.

**Comment by hjpaul7** [comment]
Last activity was 4 months ago, https://github.com/jellyfin/jellyfin/pull/13317 hasn't been merged. Status?

**Comment by przemek54** [comment]
Currently I am not running Jellyfin as I'm moving places, but I haven't seen any indication in the changelogs that it had been fixed. Would appreciate if someone could verify. I would like it to be fixed eventually, so I'd like the issue to remain open if it still persists.

**Comment by hjpaul7** [comment]
> Currently I am not running Jellyfin as I'm moving places, but I haven't seen any indication in the changelogs that it had been fixed. Would appreciate if someone could verify. I would like it to be fixed eventually, so I'd like the issue to remain open if it still persists.

Yeah the issue still exists.

**Comment by dontlookherepls** [comment]
> > Currently I am not running Jellyfin as I'm moving places, but I haven't seen any indication in the changelogs that it had been fixed. Would appreciate if someone could verify. I would like it to be fixed eventually, so I'd like the issue to remain open if it still persists.
> 
> Yeah the issue still exists.

I'm also experiencing this issue

**Comment by missaustraliana** [comment]
bumping due to same issue. still exists on the latest release

**Comment by frozen-cdn** [comment]
My backdrops for music are not working either

**Comment by dontlookherepls** [comment]
why is this issue being overlooked?

**Comment by frozen-cdn** [comment]
The support for this project and the overlooking of dead simple basic UI/UX functionality is really mind boggling.  I stopped using Jellyfin and switched to something else,  as a result.  I did not donate, and have no plans to return to Jellyfin until they implement basic functionality like the ability to manually remove, define backdrops that doesn't require a university degree to figure out

**Comment by erikbucik** [comment]
> The support for this project and the overlooking of dead simple basic UI/UX functionality is really mind boggling. I stopped using Jellyfin and switched to something else, as a result. I did not donate, and have no plans to return to Jellyfin until they implement basic functionality like the ability to manually remove, define backdrops that doesn't require a university degree to figure out

Hi, please keep in mind that Jellyfin is a community project. The people working on it do so in their free time which is why the progress sometimes feels relatively slow. Unfortunately, we also have a lot of legacy code for the backend to rewrite before we can implement any major UX changes.
While we're sorry you had a bad experience with Jellyfin we hope that whatever you're using now works well for you, and are looking forward to seeing you again in the future, happy.

**Comment by dontlookherepls** [comment]
> The support for this project and the overlooking of dead simple basic UI/UX functionality is really mind boggling. I stopped using Jellyfin and switched to something else, as a result. I did not donate, and have no plans to return to Jellyfin until they implement basic functionality like the ability to manually remove, define backdrops that doesn't require a university degree to figure out

you're a jerk.

**Comment by fmrozvezev** [comment]
Hi! I encountered this same issue. As far as I understand, the solution described above didn't help. Does anyone know how to fix this or an estimated timeframe for a fix?

**Comment by HereForCodeThatsIt** [comment]
Yeah I'm still seeing this error too, when I upload a backdrop for the album, it doesn't add to the images page, but instead adds it to the "backdrops" of the artist themselves, not album specific. Jellyfin 10.11.3

**Comment by FasteryXD** [comment]
Has the PR already been integrated into the latest version? Because I am still experiencing this problem.

**Comment by dontlookherepls** [comment]
> Has the PR already been integrated into the latest version? Because I am still experiencing this problem.

me too

**Comment by AlanDunaway** [comment]
Happening in **Jellyfin Server v10.11.11**.
