### ISSUE TITLE
[EfJellyfin.db] New libraries do not perform a full metadata scan after adding

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#13114]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After adding a new library with EfJellyfin.db, the media entries are added successfully, but are lacking any metadata. Rescanning for new files does not add metadata; only a full replace scan will fetch and add the metadata.

Reported by @theguymadmax and confirmed by myself.

### Reproduction steps

1. Add new library.

### What is the current _bug_ behavior?

Library is not populated with metadata.

### What is the expected _correct_ behavior?

Library is populated with metadata.

### Jellyfin Server version

Master

### Specify the build version

EfJellyfin.db

### Environment

```markdown
Any
```

### Jellyfin logs

```shell
No noticeable log events are generated.
```

### FFmpeg logs

```shell

```

**Comment by theguymadmax** [comment]
Here are recent logs after Scanning all Libraries. Replace all metadata was done pior to this scan.
```
[2024-12-05 22:48:11.741 -05:00] [INF] [77] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.3" request
[2024-12-05 22:48:31.634 -05:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "J:\MediaJ\Movies"
[2024-12-05 22:48:31.634 -05:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "J:\MediaJ\AudioBook"
[2024-12-05 22:48:31.634 -05:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "G:\Music\Music"
[2024-12-05 22:48:31.639 -05:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\TV"
[2024-12-05 22:48:31.654 -05:00] [INF] [72] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-12-05 22:49:43.074 -05:00] [INF] [57] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2024-12-05 22:50:47.786 -05:00] [INF] [24] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.3" closed
[2024-12-05 22:54:25.553 -05:00] [ERR] [6] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.<>c.<Run>b__4_0(BaseItem x) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Emby.Server.Implementations\Library\SplashscreenPostScanTask.cs:line 46
   at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToList()
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Emby.Server.Implementations\Library\SplashscreenPostScanTask.cs:line 46
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1119
[2024-12-05 22:56:15.740 -05:00] [ERR] [6] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 22:56:16.327 -05:00] [ERR] [6] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 22:56:59.629 -05:00] [ERR] [6] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 22:57:00.154 -05:00] [ERR] [19] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 22:58:32.777 -05:00] [ERR] [88] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 22:58:33.289 -05:00] [ERR] [19] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 23:00:41.797 -05:00] [ERR] [70] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
[2024-12-05 23:00:42.362 -05:00] [ERR] [70] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String value)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCommonNodes(BaseItem item, XmlWriter writer, ILibraryManager libraryManager, IUserManager userManager, IUserDataManager userDataRepo, IServerConfigurationManager config) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 480
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 266
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.XbmcMetadata\Savers\BaseNfoSaver.cs:line 194
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in \\wsl.localhost\Ubuntu-24.04\home\Max\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 704
```

**Comment by gnattu** [comment]
I can not reproduce this on current master. Is this still the case?

**Comment by theguymadmax** [comment]
Yes, still an issue, my process.:
1. Create a new library on master branch
2. After initial scan, browse library, 
3. Notice there is no metadata for scanned in items. (You need to do a replace all metadata scan again to populate)

Logs after an initial scan. When it's almost done - it hangs at end. It took 25min to scan in  7 series in a new Shows library. 
```
[09:01:19] [INF] [48] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series Seinfeld
[09:01:19] [INF] [48] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season Unknown, Path: , Id: 6b531482-fadf-4fa1-ca74-5f0cd20c1a99
Exception thrown: 'System.InvalidOperationException' in System.Linq.dll
jellyfin.dll (22988): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.1\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[09:02:03] [ERR] [21] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.<>c.<Run>b__4_0(BaseItem x)
   at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToList()
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[09:11:52] [INF] [3] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.3 closed
[09:18:49] [INF] [51] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.3 request
[09:20:07] [INF] [42] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.3 closed
jellyfin.dll (22988): Loaded 'Microsoft.GeneratedCode'. 
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory F:\Movies
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory F:\Movies DVHDR
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory F:\TV
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory I:\Movies
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory I:\Movies DVHDR
[09:23:59] [INF] [39] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 25 minute(s) and 12 seconds
[09:23:59] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory I:\TV

```

**Comment by gnattu** [comment]
It is probably some metadata provider misbehaving, not the migration's fault.

**Comment by theguymadmax** [comment]
> I did exactly the same and cannot reproduce this. What is your folder structure, what plugins you have installed and what is your library options?

The last linked test was a clean installation with no plugins added. I then created a shows library and kept the default settings.

![Image](https://github.com/user-attachments/assets/aaf05149-0942-46cc-9e51-ad7cf721e221)

**Comment by gnattu** [comment]
https://github.com/user-attachments/assets/3bf8a62d-c0a2-4128-ab6e-2a314a4b4772

This is not what I'm seeing. It is really weird that you are having Season unknown out there. I think that might be yet another season handler issue instead of a EFCore issue

**Comment by theguymadmax** [comment]
Do you have NFOs or images in the directory? It will pick up some of that info.

**Comment by gnattu** [comment]
https://github.com/user-attachments/assets/b9d0579d-0e7d-462a-93af-e49399aedbd2

Another sample, using your exact library layout:

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/4aeef6f6-0528-4d63-becf-0bb2643c341c" />

And I'm not seeing this. I don't even have the unknown season.

**Comment by gnattu** [comment]
My current theory is that one of the metadata provider hits a bug on your system (as I cannot reproduce), can you try disable them in different way (for example disable A for everything and then disable all Seasons providers but keep all others enabled etc). Our current library scanning is quite fragile that one metadata misbehaving could lead to the whole scanning stopped at the incomplete state (which means no metadata is ever recorded).

**Comment by theguymadmax** [comment]
I tested each metadata provider independently for the shows' libraries, but it made no difference. This issue occurs not only with show and movie libraries but also with music libraries.

![Image](https://github.com/user-attachments/assets/e7889a72-de8a-415d-beea-2c2d212aaf84)

**Comment by gnattu** [comment]
The funniest part is that I cannot reproduce no matter how. Not even ffprobe has being run is really weird.

**Comment by theguymadmax** [comment]
I think I figured out why we're getting different results. I'm running it from VSCode as a folder, not from within the dev container. When I ran it from the dev container, I was able to reproduce your results, and the metadata worked on the initial scan. However, after building a Windows exe using the Jellyfin packaging repo and installing it, I'm getting the same results as when running it from the folder in VSCode—no metadata on the initial scan.
