### ISSUE TITLE
Warning : apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))

### ISSUE THREAD

**Issue by maximo1984** [jellyfin/jellyfin#13130]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I am unable to start jellyfin. After starting briefly it will stop immediately. When attempting to "sudo apt-get update" I received the thread title message. Reproduced here again.

"Warning : apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))"

### Reproduction steps

I have already tried uninstalling, purging and reinstalling and I get the same message. I have also noticed the "jellyfin-web" file is missing, though I am not sure if this has anything to do with this issue.

### What is the current _bug_ behavior?

Cannot update jellyfin, cannot start jellyfin.

### What is the expected _correct_ behavior?

Jellyfin system should start, and remain active, and web interface load.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10

### Environment

```markdown
- OS:
- Linux Kernel: 24.04
- Virtualization:
- Clients:
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Bookshelf, Fanart, Intros, Playback Reporting, Reports, Skin Manager, Theme Songs, TheTVDB, TVmaze
- Reverse Proxy:
- Base URL: http://localhost:8096
- Networking:
- Storage:
```

### Jellyfin logs

```shell
There is no log folder at "/var/lib/jellyfin/log/"
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/f1f4f590-e0c4-4f08-ab3d-ddff1457294b)

### Additional information

 sudo systemctl start jellyfin
lee@leedesktop:~$ sudo systemctl status jellyfin
○ jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
     Active: inactive (dead) since Sat 2024-11-30 10:41:11 EST; 3s ago
   Duration: 1.284s
    Process: 11106 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITIONAL_OPTS (code=exited, status=0/SUCCE>
   Main PID: 11106 (code=exited, status=0/SUCCESS)
        CPU: 1.295s

Nov 30 10:41:11 leedesktop jellyfin[11106]:    at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
Nov 30 10:41:11 leedesktop jellyfin[11106]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
Nov 30 10:41:11 leedesktop jellyfin[11106]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
Nov 30 10:41:11 leedesktop jellyfin[11106]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Nov 30 10:41:11 leedesktop jellyfin[11106]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Nov 30 10:41:11 leedesktop jellyfin[11106]: [10:41:11] [INF] Running query planner optimizations in the database... This might take a while
Nov 30 10:41:11 leedesktop jellyfin[11106]: [10:41:11] [INF] Disposing CoreAppHost
Nov 30 10:41:11 leedesktop jellyfin[11106]: [10:41:11] [INF] Disposing PluginManager
Nov 30 10:41:11 leedesktop systemd[1]: jellyfin.service: Deactivated successfully.
Nov 30 10:41:11 leedesktop systemd[1]: jellyfin.service: Consumed 1.295s CPU time.

**Comment by felix920506** [comment]
How and when did you install Jellyfin?

**Comment by joshuaboniface** [comment]
So, the first thing to note is that with `.deb`/repository installs, you can **not** just run `sudo -u jellyfin /usr/bin/jellyfin` or similar - it will be missing all the required configuration from `/etc/default/jellyfin` and look for things in incorrect places; it must be run with the service manager. The output of `journalctl -u jellyfin` or `/var/log/jellyfin` (rather than `/usr/lib/jellyfin/logs`) would be needed for more details.


As for the apt repo itself, I second Felix's question: when and how was it installed? Easiest way to confirm is to check whether you have an `/etc/apt/sources.list.d/jellyfin.list` or `/etc/apt/sources.list.d/jellyfin.sources`. It should be the latter. If it's not, the easiest fix is to re-run the installer script (`curl -s https://repo.jellyfin.org/install-debuntu.sh | sudo bash`) as it automatically fixes that up and ensures the repo config and signing key are correct and installed to the right places.

**Comment by maximo1984** [comment]
I have had it for over a year. 2 days ago, there was an ubuntu pop up , update message, I clicked ok, but it said there were errors on the update. Very well might have something to do with it. However, several hours ago, I uninstalled, purged, ran clean up, rebooted. Then reinstalled from repository, rebooted, and the issue persists.

Running manually was a possible solution from Grok, as I was trying everything to trouble shoot.

**Comment by maximo1984** [comment]
Ran your script, says it installed, but service remains inactive (dead), even after checking status![Image](https://github.com/user-attachments/assets/a52ea385-fdd8-4acc-9cea-e81849f3c8f6)

**Comment by joshuaboniface** [comment]
It looks like there's a traceback in the logs there. Can you post the log output from `sudo journalctl -u jellyfin -n 100`?

**Comment by maximo1984** [comment]
I can post the whole code in a text file, but this popped out as likely something
![Image](https://github.com/user-attachments/assets/0f292f81-8b91-48c9-a68a-9218f861ec17)

**Comment by joshuaboniface** [comment]
Please post the full logs yes, either directly or in a pastebin. That warning should be fine, those variables are expected to be unset.

**Comment by maximo1984** [comment]
[jellyfin.log](https://github.com/user-attachments/files/17966053/jellyfin.log)

I did run this script earlier when trouble shooting and that yellow text error was not in there at the time.

**Comment by maximo1984** [comment]
I updated permissions to the jellyfin.db itself, should I try the folder? Also, can't I copy out my collections/playlists, and copy into fresh install? I did run the fresh install though, so I am not sure what is the issue. Should I uninstall, purge, delete the user folder with the .db file, then install? 

I have not ran out of diskspace.

**Comment by joshuaboniface** [comment]
Yes try a `sudo chown -R jellyfin /var/lib/jellyfin`, and try starting it to see if it works. If the permissions (ownership) were anything but `jellyfin` that might account for the error.

You can I believe copy playlists out of the data folder (look for the `.m3u` playlist files) though I'm not sure off-hand where they are.

If you do have to wipe it all, yes best bet is `sudo apt remove jellyfin jellyfin-server jellyfin-web`, ensure `/etc/jellyfin` and `/var/lib/jellyfin` are removed/archived (I prefer renaming them to `.bak` so I can keep them around just in case), and then reinstall with the script.

**Comment by maximo1984** [comment]
Collections, Playlists, etc, are located in var/lib/jellyfin/data.

Thanks, I will do all of that and attempt to preserve and copy back into my collections, etc

**Comment by joshuaboniface** [comment]
Perfect. I'm not *entirely* sure if copying the files back is enough, but if not, I'd head over to [the forums](https://forum.jellyfn.org) to ask for help there as I've never done it myself.

**Comment by maximo1984** [comment]
/etc and /lib jellyfin folders are protected , what is the best way to remove them

**Comment by maximo1984** [comment]
nevermind, got it

**Comment by maximo1984** [comment]
Progress, but now won't connect, despite saying its running.

![Image](https://github.com/user-attachments/assets/45462f9e-77bd-4f9b-b3c7-84cb679787a4)

**Comment by joshuaboniface** [comment]
You may need to clear your browser cache and forcibly refresh it. Since this is effectively a new install now, you should be directed to the setup wizard and such.

**Comment by joshuaboniface** [comment]
Glad to help, good luck.
