### ISSUE TITLE
Jellyfin nginx reverse proxy and video playback not working

### ISSUE THREAD

**Issue by n1ete** [jellyfin/jellyfin#1314]
**Describe the bug**

videos are not playing, music streaming is working
reverse proxy address keeps showing me a black web UI

**To Reproduce**
1. Install clean Jellyfin on debian lxc container
2. make sure /var/lib/jellyfin has the correct permissions
3. configure jellyfin at localhost:8096 and setting up bind address to localhost for nginx reverse proxy
4. adding music and tv show library

5. music is streaming.... any movie/tv not working..
6. webui is working at "JELLYFINURL:8096"
6. at the reverse proxy address i just get a black webui screen....i get redirected to the dashboard site correctly though

**Expected behavior**
somehow playing videos isnt working and the webui isnt loading over the reverse proxy

**Logs**

nginx config
```
server {
  listen 80;
  listen [::]:80;

  server_name JELLYFIN.DOMAIN;

  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl http2;
  server_name JELLYFIN.DOMAINt;
  ssl_certificate /etc/ssl/private/fullchain.pem;
  ssl_certificate_key /etc/ssl/private/privkey.pem;

  location / {
    proxy_pass http://localhost:8096;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $remote_addr;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_redirect off;

    # Send websocket data to the backend aswell
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

the errors i getting everytime after a fresh deployment of jellyfin

<details>

```
Apr 25 19:24:22 jelly ntpd[59673]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Apr 25 19:26:18 jelly ntpd[59673]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Apr 25 19:29:55 jelly ntpd[59673]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Apr 25 19:35:11 jelly ntpd[59673]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Apr 25 19:38:26 jelly ntpd[59673]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Apr 25 19:38:44 jelly jellyfin[63384]: [19:38:44] [ERR] Error processing request
Apr 25 19:38:44 jelly jellyfin[63384]: System.Net.NetworkInformation.NetworkInformationException (2): An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more er
Apr 25 19:38:44 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 25 19:38:44 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
Apr 25 19:38:44 jelly jellyfin[63384]:    --- End of inner exception stack trace ---
Apr 25 19:38:44 jelly jellyfin[63384]: ---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.
Apr 25 19:38:44 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 25 19:38:44 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)<---
Apr 25 19:38:44 jelly jellyfin[63384]: ---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
Apr 25 19:38:44 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 25 19:38:44 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 25 19:38:44 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
...skipping...
Apr 26 13:42:07 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)<---
Apr 26 13:42:07 jelly jellyfin[63384]: ---> (Inner Exception #3) System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
Apr 26 13:42:07 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)<---
Apr 26 13:42:07 jelly jellyfin[63384]: ---> (Inner Exception #4) System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/lo/forwarding'.
Apr 26 13:42:07 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__1(String name, IpAddressInfo* ipAddr, UInt32* scopeId)<---
Apr 26 13:42:07 jelly jellyfin[63384]: ---> (Inner Exception #5) System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.
Apr 26 13:42:07 jelly jellyfin[63384]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.IO.File.ReadAllText(String path)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__1(String name, IpAddressInfo* ipAddr, UInt32* scopeId)<---
Apr 26 13:42:07 jelly jellyfin[63384]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
Apr 26 13:42:07 jelly jellyfin[63384]:    at Emby.Server.Implementations.Networking.NetworkManager.GetSubnets(String endpointFirstPart)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpaceAndLocalSubnet(String endpoint)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
Apr 26 13:42:07 jelly jellyfin[63384]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

</details>

**System (please complete the following information):**
 - OS: Debian Stretch
 - Browser: Firefox, Chromium
 - Jellyfin Version: 10.3.1.0
 - Reverse proxy: nginx

**Additional context**
i think  there are two separate problems since the webui isnt working trough the proxy but working without bind directly.

just checked that there is no codec selected in the jellyfin xml config.... will check if i can change something with video playback

**Comment by bugfixin** [comment]
Please see https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/ and ensure your configuration matches - I know others are working on some further nginx config changes that should simplify this for the future as well.

**Comment by saldru** [comment]
Hi @n1ete, did you checked the nginx logs ?

Please see my Nginx Server Block for Jellyfin :

```
server {
    listen IPV4_ADDRESS:80;
    listen [IPV6_ADDRESS]:80;
    server_name JELLYFIN.DOMAIN.TLD;

    return 301 https://$server_name$request_uri;
}

server {
    listen IPV4_ADDRESS ssl http2 default_server;
    listen [IPV6_ADDRESS]:443 ssl http2 default_server;
    server_name JELLYFIN.DOMAIN.TLD;

    include h5bp/basic.conf;
    include h5bp/ssl/certificate_files.conf;
    include h5bp/ssl/ssl_engine.conf;
    include h5bp/ssl/policy_modern.conf;
    include h5bp/ssl/ocsp_stapling.conf;

    include h5bp/security/strict-transport-security.conf;
    include h5bp/security/referrer-policy.conf;

    access_log /var/log/nginx/jellyfin.local.access.log combined;
    error_log /var/log/nginx/jellyfin.local.error.log;

    location / {
        # Proxy main Jellyfin traffic
        proxy_pass http://127.0.0.1:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
     }
     location /embywebsocket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://127.0.0.1:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
     }
}
```
I use the Nginx configuration of H5BP : https://github.com/h5bp/server-configs-nginx
So you can see the content of the H5BP files I include in my Server Block.
For my part it works well.

OS: Ubuntu Server 18.10 (QEMU)
Jellyfin: 10.3.1
Nginx: 1.15.9

If that can help you. :)

**Comment by n1ete** [comment]
hey @saldru thanks for your config, the nginx problem is already solved... i think there is just a dotnet problem left since it cant find the proper network config....its all in the logs ;)

music is working flawless but something is wrong with videoplayback

**Comment by bugfixin** [comment]
I'm having a hard time reproducing this but I do notice in your logs a lot of mentions of the forwarding settings from /proc/sys/net/ipv4/conf/ - are you running a kernel that doesn't populate those or are they otherwise inaccessible from the container?

**Comment by n1ete** [comment]
the directory is not present where dotnet is looking for.... 
I deactivated forwarding in the options though...

**Comment by sparky8251** [comment]
This is a bizarre backend bug... We already knew some settings were stupid and ignored and have been planning to remove them for awhile.

Do you know why you dont have anything at `/proc/sys/net/ipv4/conf/`? If so someone can at least look into replicating the issue on a system and testing fixes.

**Comment by hardhub** [comment]
Fedora 29

I cannot get it work at all. It says bad gateway. But I am sure all is correct.

**Comment by ddurdle** [comment]
I can't even login through reverse proxy using the recommended settings.

**Comment by dkanada** [comment]
If you guys have time to hop on our Matrix chat for some troubleshooting we might be able to figure out an issue. I don't think it's a bug though because we have lots of people running proxies successfully. It might be an edge case in the configuration we haven't seen yet but we would need more information to find out.
