### ISSUE TITLE
Live TV (hdhomerun) not working on jellyfin 10.3.1

### ISSUE THREAD

**Issue by bartekd123** [jellyfin/jellyfin#1316]
**Describe the bug**
When trying to watch live tv, it just spins and doesn't play

**To Reproduce**
1.) go to live tv
2.) Play any live channel
3.) I see spinning, and it never plays

**Expected behavior**
Being able to watch live channels

**Logs**
```
[2019-04-26 20:58:07.672 -04:00] [INF] Profile: "Unknown Profile", Path: "http://10.150.1.155", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-26 20:58:07.673 -04:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://10.150.1.155"
[2019-04-26 20:58:07.673 -04:00] [INF] Opening channel stream from "Emby", external channel Id: "hdhr_6.1"
[2019-04-26 20:58:07.673 -04:00] [INF] Streaming Channel hdhr_6.1
[2019-04-26 20:58:07.673 -04:00] [INF] Live stream "native_e6a5ee655c7e0ae736a968d5b2efee79_bb69a6ad82fbcf785353e5ba3213c870" consumer count is now 2
[2019-04-26 20:58:07.673 -04:00] [INF] Waiting 3000ms before probing the live stream
[2019-04-26 20:58:10.668 -04:00] [INF] "/usr/local/bin/ffprobe" "-analyzeduration 3000000 -i \"https://127.0.0.1:8920/LiveTv/LiveStreamFiles/c8a947af3b4d46dc977b8d94689bd405/stream.ts\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2019-04-26 20:58:10.706 -04:00] [ERR] Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LiveStreamHelper.AddMediaInfoWithProbe(MediaSourceInfo mediaSource, Boolean isAudio, String cacheKey, Boolean addProbeDelay, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)

```
**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Docker jellyfin/jellyfin
 - Browser: Chrome, firefox and safari. Log above was using safari on mac os
 - Jellyfin Version: 10.3.1 (also was same issue on 10.3.0)
 - Reverse proxy: NGINX reverse proxy, but same issue direct to the local IP

**Additional context**
I updated my hdhomerun to Firmware Version 20190417 at the same time as updating jellyfin, so don't know if that could be the issue.

I see the .ts file growing in the config/transcoding-temp directory while it is trying to play through jellyfin, so it appears to stream it and create the temp file that it is playing through, but it just can't play it.

**Comment by skug67** [comment]
Working fine for me, same firmware version, running on Debian behind apache reverse proxy

**Comment by bartekd123** [comment]
Thank you @skug67  for confirming.
I wonder if it is something else environmental. I can play live streams using the hdhomerun app, so I know that isn't the issue. It is able to communicate with hdhomerun because I can pull the guide data (and it is creating the ts file). I tried to give the transcoding temp 777 rights to see if that is the issue, but no go.

Ill keep playing around with it. If anyone else has anything I can try, let me know.

**Comment by bartekd123** [comment]
Hi I have resolved the issue so it can be closed. 

I ended up creating another jellyfin docker (to generate the folders). Then I deleted and replaced the config folder in my original jellyfin docker container so that it resets it back to original config. Then I was able to play live tv again.
