### ISSUE TITLE
Jellyfin can't fill metadata from TMDB

### ISSUE THREAD

**Issue by Tetrax-10** [jellyfin/jellyfin#13176]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When I add movie to my library folder it used to auto fill up metadata and images from TMDB. But for past few days it doesn't work so I tried the `identify` tool to manually search for the movie and select it. I can see many movies in the search page (so the API is working fine) when I click that nothing happens. It again didn't fill any metadata or images.

### Identify tool's search is working

![Image](https://github.com/user-attachments/assets/62f7a099-2c94-4d98-9779-399b81b432d5)

### Reproduction steps

1. Add a movie to you library folder
2. refresh/scan/wait for few minutes to Jellyfin to add it.

### What is the current _bug_ behavior?

Add a movie to the library folder and if you scan/refresh your library you will end up with a empty item like this:

![Image](https://github.com/user-attachments/assets/5d3302f8-f2b6-4c1e-aac0-bc3bc662f4a5)

![Image](https://github.com/user-attachments/assets/cd60c93e-d57b-4db6-bdbf-56e460b8499b)

### What is the expected _correct_ behavior?

All the metadata and images should be added automatically.

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.3

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox 133.0
- FFmpeg Version: ffmpeg version 2024-08-26-git-98610fe95f-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
```

### Jellyfin logs

```shell
[2024-12-08 00:28:08.388 +05:30] [ERR] [43] Namo.Plugin.InPlayerEpisodePreview.Api.InPlayerPreviewController: InPlayerEpisodePreviewPlugin: "Namo.Plugin.InPlayerEpisodePreview.Web.InPlayerPreview.js"
[2024-12-08 00:28:10.571 +05:30] [INF] [33] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-12-08 00:28:10.741 +05:30] [ERR] [33] Microsoft.EntityFrameworkCore.Database.Connection: An error occurred using the connection to database '"main"' on server '"D:\Apps\Jellyfin\Data\data\jellyfin.db"'.
[2024-12-08 00:28:10.845 +05:30] [ERR] [33] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Server.Implementations.JellyfinDbContext"'."
""Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked For more information on this error code see https://www.sqlite.org/rescode.html'.
   at Microsoft.Data.Sqlite.SqliteConnection.Deactivate()
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at System.Data.Common.DbConnection.CloseAsync()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked For more information on this error code see https://www.sqlite.org/rescode.html'.
   at Microsoft.Data.Sqlite.SqliteConnection.Deactivate()
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at System.Data.Common.DbConnection.CloseAsync()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Events.Consumers.Session.SessionStartedLogger.OnEvent(SessionStartedEventArgs eventArgs)
   at Jellyfin.Server.Implementations.Events.EventManager.PublishInternal[T](T eventArgs)
[2024-12-08 00:28:10.879 +05:30] [ERR] [33] Jellyfin.Server.Implementations.Events.EventManager: Uncaught exception in EventConsumer "Jellyfin.Server.Implementations.Events.Consumers.Session.SessionStartedLogger": 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked For more information on this error code see https://www.sqlite.org/rescode.html'.
   at Microsoft.Data.Sqlite.SqliteConnection.Deactivate()
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at System.Data.Common.DbConnection.CloseAsync()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CreateAsync(ActivityLog entry)
   at Jellyfin.Server.Implementations.Events.Consumers.Session.SessionStartedLogger.OnEvent(SessionStartedEventArgs eventArgs)
   at Jellyfin.Server.Implementations.Events.EventManager.PublishInternal[T](T eventArgs)
[2024-12-08 00:28:57.104 +05:30] [INF] [44] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "Intimacy", Path: "D:\Shared Files\Media\Media Server\Movies\Intimacy (2001)\Intimacy (2001).mkv", Id: a7a7a987-4e89-9122-bfb9-b462f12fcd44
[2024-12-08 00:29:00.173 +05:30] [INF] [44] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "John Wick", Path: "D:\Shared Files\Media\Media Server\Movies\John Wick (2014)\John Wick (2014).mkv", Id: 9659f82a-ef45-825d-acb3-9e18c1530274
[2024-12-08 00:29:00.184 +05:30] [INF] [44] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Movie", Name: "John Wick", Path: "D:\Shared Files\Media\Media Server\Movies\John Wick (2014)", Id: 9659f82a-ef45-825d-acb3-9e18c1530274
[2024-12-08 00:29:30.008 +05:30] [INF] [44] Emby.Server.Implementations.IO.LibraryMonitor: "Movies" ("D:\Shared Files\Media\Media Server\Movies") will be refreshed.
[2024-12-08 00:29:30.037 +05:30] [INF] [43] Emby.Server.Implementations.IO.LibraryMonitor: "Movies" ("D:\Shared Files\Media\Media Server\Movies") will be refreshed.
[2024-12-08 00:29:30.051 +05:30] [INF] [99] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "Kanguva", Path: "D:\Shared Files\Media\Media Server\Movies\Kanguva (2024)\Kanguva (2024).mkv", Id: e462b692-0443-e212-7fe2-552972bcd3fe
[2024-12-08 00:29:30.079 +05:30] [INF] [99] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "D:\Apps\Jellyfin\jellyfin-ffmpeg\ffprobe.exe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Shared Files\Media\Media Server\Movies\Kanguva (2024).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-08 00:29:30.080 +05:30] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "D:\Apps\Jellyfin\jellyfin-ffmpeg\ffprobe.exe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Shared Files\Media\Media Server\Movies\The Raid (2011)\The Raid (2011).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-08 00:29:30.572 +05:30] [ERR] [44] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2012-03-29 15:08:43 UTC. Path 'videos.results[0].published_at', line 1, position 78903.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
   at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetMovieAsync(String imdbId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetMovieAsync(Int32 movieId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetMovieAsync(Int32 tmdbId, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2024-12-08 00:29:30.585 +05:30] [ERR] [33] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2024-03-19 12:02:27 UTC. Path 'videos.results[0].published_at', line 1, position 22044.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
   at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetMovieAsync(String imdbId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetMovieAsync(Int32 movieId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetMovieAsync(Int32 tmdbId, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2024-12-08 00:29:30.610 +05:30] [INF] [38] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "D:\Apps\Jellyfin\jellyfin-ffmpeg\ffprobe.exe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Shared Files\Media\Media Server\Movies\Kanguva (2024).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-08 00:29:30.611 +05:30] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "D:\Apps\Jellyfin\jellyfin-ffmpeg\ffprobe.exe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Shared Files\Media\Media Server\Movies\The Raid (2011)\The Raid (2011).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-08 00:29:30.776 +05:30] [ERR] [33] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/5a245ce0-1a6c-4dc1-b21d-1dd0a6ba2a4b)

### Additional information

I don't have any file inside my movie folder except a mkv file.

eg: My movies/Love (2015)/Love (2015).mkv

I first reported it on discord but no response: https://discord.com/channels/772232779534172171/773650260903591946/1314698343191937045

Full log: https://justpaste.it/gww0p

**Comment by sjorge** [comment]
It's a tmdb issue https://www.themoviedb.org/talk/675427102a0e9c79f19b8d0e

It should be fixed and just need to wait a few hours for bad cache results to expire.

**Comment by Tetrax-10** [comment]
Oh thanks, you can close this issue if not needed.
