### ISSUE TITLE
people poster.png failed to be recreated in metadata folder after a reset of the install

### ISSUE THREAD

**Issue by prahal** [jellyfin/jellyfin#13184]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I cleared the data/, config/, log/, metadata/ and cache/ folders and did the setup anew because my installation gave me ordinal errors all over and seemed to be corrupted. But it seems the people poster.png which link has already been added to the jellyfin generated NFO for the movies (added to the NFO before I cleared the jellyfin folders) are not fetched anew when missing (because I cleared the jellyfin metadata folder). Only an error is logged for each one of them.
I am running jellyfin 10.10.3 in docker.

I get thousands of error like:
```
[02:57:46] [ERR] [46] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/M/Michael Mellinger/poster.jpg

System.IO.FileNotFoundException: File not found

File name: '/config/metadata/People/M/Michael Mellinger/poster.jpg'

  at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)

  at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(String path)

  at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)

  at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```
and the poster.png that errors out are not recreated in metadata/People/...

I believe the few metadata people poster I get are the one that were not already including into nfo files, though hard to confirm.

But I would like not to reset the whole media library NFO set. 

I opened a thread in the forum https://forum.jellyfin.org/t-people-poster-png-failed-to-be-recreated-in-metadata-folder and was told to try to run the "refresh people" task.
No change and I get this I get this success message about the refresh of people/
```
[22:04:37] [INF] [66] Emby.Server.Implementations.Library.LibraryManager: People validation complete

[22:04:37] [INF] [66] Emby.Server.Implementations.ScheduledTasks.TaskManager: Actualiser les acteurs Completed after 2 minute(s) and 0 seconds
```
One of the name I knew was missing is still missing. And the task completed very fast, it seems as if the task detected no change to be done.

I also try opening a movie page which most people pictures were missing and try refreshing refreshing metadata "for new and modified", for "missing metadata" and "replace all metadata" with or without replace existing images and none of the missing people pictures are recreated.

NB: when cleaning the old install, I just renamed the metadata folder and have the missing people poster.png in it.

### Reproduction steps

1. Setup a jellyfin install with a library with metadata format as NFO and a movie in it
2. Stop jellyfin and clear/move data/, config/, log/, metadata/ and cache/
3. redo the jellyfin setup wizard

### What is the current _bug_ behavior?

people poster.png are not generated when missing in metadata/ folder I believe because they are listed in the library NFOs

### What is the expected _correct_ behavior?

people poster.png are generated anew from internet when missing in metadata/ folder even though they are listed in the library NFOs

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.3

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Debian 12 / Armbian 24.11.2
- Linux Kernel: 6.12.1-edge-rockchip64
- Virtualization: Docker
- Clients: Browser + Android + LibreElec
- Browser: Firefox 132 (64 bits)
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[02:57:46] [ERR] [46] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/M/Michael Mellinger/poster.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/M/Michael Mellinger/poster.jpg'
  at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
  at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(String path)
  at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
  at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### FFmpeg logs

```shell

```

### Additional information

I believe the error in the log above is related to an attempt to generate thumbnails from the people poster.png. There is no error from the refresh people task. Only it does nothing for these posters.

**Comment by prahal** [comment]
Please reopen. This issue likely has not magically vanished. Sorry for not posting before the 3 weeks windows that triggers the automatic closing as "not planned" by the bot, was busy.
