### ISSUE TITLE
Unable to Regenerate Trickplay After Configuration Changes and Docker Setup Issue

### ISSUE THREAD

**Issue by AemonCao** [jellyfin/jellyfin#13196]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

1. When I first enabled the "Trickplay" feature, I generated Trickplay for the A media library, and everything worked fine.

2. Then, I set the configuration for the B media library, enabled "Trickplay", and manually ran the scheduled task to generate Trickplay. However, during the generation of each movie, I received the following error:

```log
[2024-12-07 18:59:50.500 +08:00] [ERR] [17] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.IO.IOException: Read-only file system : '/JF_MOVIES/Hancock_全民超人汉考克_-_Unrated_(2008)/全民超人汉考克_-_Unrated_(2008)_1080p_AC3.trickplay'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(IReadOnlyList`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
```

After some investigation, I discovered that the issue was caused by mapping the B media library path as "Read-only" when starting the Docker container.

3. I modified the B media library configuration and restarted the scheduled task to generate Trickplay. After this, the remaining movies that hadn't been skipped (except for those skipped in step 2 due to the incorrect setting) were generated normally.

4. After the scheduled task finished, I wanted to regenerate Trickplay for the movies that weren't generated in step 2, but I couldn't generate them no matter what I tried.

5. I attempted to rescan the media library ![Image](https://github.com/user-attachments/assets/73c58184-0e01-43b8-bceb-dc835285eed2), but this did not work.

6. Also, some Trickplay files that were already generated can no longer be used during playback. ![Image](https://github.com/user-attachments/assets/ba2abc38-b9fb-4afa-b0c5-3c02118e989e)
![Image](https://github.com/user-attachments/assets/c200f6bd-1d4a-4adb-9ec5-1bca89ded4ab)
![Image](https://github.com/user-attachments/assets/8d07d199-0ec7-4c37-b6f0-1601fa59a995)

Could you please guide me on how to delete all Trickplay files and regenerate them (I am willing to spend a few more days running the scheduled tasks again)?

### Reproduction steps

/

### What is the current _bug_ behavior?

/

### What is the expected _correct_ behavior?

/

### Jellyfin Server version

10.10.0+

### Specify the build version

241119

### Environment

```markdown
- OS: 6.1.79-Unraid
- Linux Kernel: Linux version 6.1.79-Unraid (root@Develop-612) (gcc (GCC) 12.2.0, GNU ld version 2.40-slack151) #1 SMP PREEMPT_DYNAMIC Fri Mar 29 13:34:03 PDT 2024
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: UHD Graphics 730
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[2024-12-07 18:59:50.500 +08:00] [ERR] [17] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
System.IO.IOException: Read-only file system : '/JF_MOVIES/Hancock_全民超人汉考克_-_Unrated_(2008)/全民超人汉考克_-_Unrated_(2008)_1080p_AC3.trickplay'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(IReadOnlyList`1 images, Int32 width, TrickplayOptions options, String outputDir)
   at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell

```

**Comment by AemonCao** [comment]
I’m wondering if Jellyfin uses an internal database to store Trickplay-related information, which corresponds to the Trickplay images generated in the media library?

If that’s the case, would it be possible to clear the database entries? I’m happy to manually delete the generated Trickplay images, but I’m unsure if running the scheduled task to regenerate the Trickplay afterward would work. Any guidance on this would be greatly appreciated.
