### ISSUE TITLE
IPluginServiceRegistrator.RegisterServices does not have an implementation

### ISSUE THREAD

**Issue by hexxone** [jellyfin/jellyfin#13191]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When trying to add an `IHostedService` as background service to my plugin, I was first struggling to find out how to do it, because it seems there is no docs at all for the public C# plugin interface, besides some [stuff in the "example plugin repo"  here ](https://github.com/jellyfin/jellyfin-plugin-template?tab=readme-ov-file#4b-use-plugin-aimed-interfaces-to-add-custom-functionality) .

There I found out I aooarently had to use the `IPluginServiceRegistrator`, which I promptly tried but cannot get to work. I always get the following, obscure error: " `TeleJellyServiceRegistrator.RegisterServices` does not have an implementation " (See logs below)

my class looks like this:

```csharp
using Jellyfin.Plugin.TeleJelly.Telegram;
using MediaBrowser.Controller;
using MediaBrowser.Controller.Plugins;
using Microsoft.Extensions.DependencyInjection;

namespace Jellyfin.Plugin.TeleJelly;

public class TeleJellyServiceRegistrator : IPluginServiceRegistrator
{
    public void RegisterServices(IServiceCollection serviceCollection, IServerApplicationHost applicationHost)
    {
        serviceCollection.AddHostedService<TelegramBackgroundService>();
    }
}
```

The `TelegramBackgroundService` class is also public and just looks like this (simplified):

```csharp
public class TelegramBackgroundService : IHostedService, IDisposable
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<TelegramBackgroundService> _logger;

    private IDisposable? _configChangeRegistration;
    private string _currentToken = string.Empty;

    private TelegramBotService? _botService;

    public TelegramBackgroundService(IServiceProvider serviceProvider, ILogger<TelegramBackgroundService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }
   
    // ...
}
```

Besides that there is nothing weird going on. I am just trying to add the background service similar to many other plugins.
E.g.:
- <https://github.com/jellyfin/jellyfin-plugin-trakt/blob/master/Trakt/PluginServiceRegistrator.cs>
- <https://github.com/jellyfin/jellyfin-plugin-tvdb/blob/master/Jellyfin.Plugin.Tvdb/TvdbPluginServiceRegistrator.cs>

I am sure its NOT a dependency problem with the Telegram.Bot dll because I can successfully use it to test if the bot token is valid, and get the bot user info successfully. 

It should also not be a problem with the DependencyInjection.Extensions dll not being found, because I can successfully Get Services from the IServiceCollection in a custom Controller I use.

So I'm wondering how can there be no implementation of the "RegisterServices" function, when the parent class implementes the correct interface and gets apparently found correctly?

### Reproduction steps

1. Create a new Plugin 
2. Create new `IHostedService` implementation
3. Create a `IPluginServiceRegistrator` implementation
4. Try to add the HostedService in `RegisterServices`

### What is the current _bug_ behavior?

AddHostedService() does not get called and the loading of the Plugin fails completely, causing the Plugin Assembly to stay unloaded 

### What is the expected _correct_ behavior?

AddHostedService() function should get found & called correctly, or give a more detailed error reason when it fails?

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm) (docker)
- Linux Kernel:
- Virtualization: docker image: latest <https://hub.docker.com/layers/jellyfin/jellyfin/latest/images/sha256-040461da121ebe7f5055a385d0f1fc8e8260509041ff0fbce54ec52da2b6bf60?context=explore>
- Plugins: TMDb, Studio Images, OMDb, MusicBrainz, AudioDB
- Reverse Proxy: Traefik v3
- Networking: bridge
- Storage: local
```

### Jellyfin logs

```shell
2024-12-08 23:44:52 [22:44:52] [INF] [4] Emby.Server.Implementations.ApplicationHost: Loading assemblies
2024-12-08 23:44:52 [22:44:52] [ERR] [4] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/TeleJelly/Jellyfin.Plugin.TeleJelly.dll. 
This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
2024-12-08 23:44:52 System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2024-12-08 23:44:52 Method 'RegisterServices' in type 'Jellyfin.Plugin.TeleJelly.TeleJellyServiceRegistrator' from assembly 
'Jellyfin.Plugin.TeleJelly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2024-12-08 23:44:52    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2024-12-08 23:44:52    at System.Reflection.RuntimeModule.GetTypes()
2024-12-08 23:44:52    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
2024-12-08 23:44:52 System.TypeLoadException: Method 'RegisterServices' in type 'Jellyfin.Plugin.TeleJelly.TeleJellyServiceRegistrator' 
from assembly 'Jellyfin.Plugin.TeleJelly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

### Additional information

I have not seen any issue reported on the exact same behaviour, althoug there are some issues with similar error logs contained, the issues usually dont resolve around this specific error.

For example:
- in this comment: <https://github.com/jellyfin/jellyfin-plugin-nextpvr/issues/46#issuecomment-2124004222>
- or here: <https://github.com/jwueller/jellyfin-plugin-onepace/issues/60#issuecomment-2316687852>
- or here: <https://github.com/jellyfin/jellyfin/issues/11702>
- etc. ... <https://github.com/search?q=+IPluginServiceRegistrator&type=issues>

The related plugin where the issue came up: <https://github.com/hexxone/TeleJelly/tree/dev>

**Comment by crobibero** [comment]
Please provide your full log, not just the error line
I don't see anything immediately wrong with what you have in the linked repo

**Comment by hexxone** [comment]
Ok, sure, here it is:

<details>
  <summary>Full Jellyfin Log</summary>
  
  ```
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Jellyfin version: 10.10.3
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Environment Variables: ["[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]"]
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Arguments: ["/jellyfin/jellyfin.dll"]
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Operating system: Debian GNU/Linux 12 (bookworm)
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Architecture: X64
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: 64-Bit Process: True
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: User Interactive: True
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Processor count: 32
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Program data path: /config
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Log directory path: /config/log
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Config directory path: /config/config
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Cache path: /cache
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Temp directory path: /tmp/jellyfin
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Web resources path: /jellyfin/jellyfin-web
2024-12-08 23:44:51 [22:44:51] [INF] [4] Main: Application directory: /jellyfin/
2024-12-08 23:44:51 [22:44:51] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration", "MigrateMusicBrainzTimeout", "MigrateNetworkConfiguration", "MigrateEncodingOptions"]
2024-12-08 23:44:51 [22:44:51] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-12-08 23:44:52 [22:44:52] [INF] [4] Emby.Server.Implementations.ApplicationHost: Loading assemblies
2024-12-08 23:44:52 [22:44:52] [ERR] [4] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/TeleJelly/Jellyfin.Plugin.TeleJelly.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
2024-12-08 23:44:52 System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2024-12-08 23:44:52 Method 'RegisterServices' in type 'Jellyfin.Plugin.TeleJelly.TeleJellyServiceRegistrator' from assembly 'Jellyfin.Plugin.TeleJelly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2024-12-08 23:44:52    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2024-12-08 23:44:52    at System.Reflection.RuntimeModule.GetTypes()
2024-12-08 23:44:52    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
2024-12-08 23:44:52 System.TypeLoadException: Method 'RegisterServices' in type 'Jellyfin.Plugin.TeleJelly.TeleJellyServiceRegistrator' from assembly 'Jellyfin.Plugin.TeleJelly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.18.0.3"]
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
2024-12-08 23:44:52 [22:44:52] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
2024-12-08 23:44:52 [22:44:52] [INF] [4] Emby.Server.Implementations.ApplicationHost: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'ImageInfos' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'ImageInfos' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Permissions' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Permissions' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Preferences' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Preferences' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Users' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [WRN] [4] Microsoft.EntityFrameworkCore.Migrations: An operation of type 'SqlOperation' will be attempted while a rebuild of table 'Users' is pending. The database may not be in an expected state. Review the SQL generated by this migration to help diagnose any failures. Consider moving these operations to a subsequent migration.
2024-12-08 23:44:52 [22:44:52] [INF] [4] Emby.Server.Implementations.ApplicationHost: EFCore migrations applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.3.0
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.3.0
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.3.0
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.3.0
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.3.0
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase", "FixPlaylistOwner", "MigrateRatingLevels", "FixAudioData", "RemoveDuplicatePlaylistChildren"]
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddDefaultPluginRepository'
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddDefaultPluginRepository' applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'ReaddDefaultPluginRepository'
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'ReaddDefaultPluginRepository' applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddDefaultCastReceivers'
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddDefaultCastReceivers' applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'UpdateDefaultPluginRepository10.9'
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'UpdateDefaultPluginRepository10.9' applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MoveTrickplayFiles'
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.Routines.MoveTrickplayFiles: Moved 0 items in 00:00:00.0417417
2024-12-08 23:44:53 [22:44:53] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'MoveTrickplayFiles' applied successfully
2024-12-08 23:44:53 [22:44:53] [INF] [4] Main: Kestrel is listening on 0.0.0.0
2024-12-08 23:44:53 [22:44:53] [WRN] [4] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {d65f9fb9-2768-4160-acee-e04a1649c4ee} may be persisted to storage in unencrypted form.
2024-12-08 23:44:53 [22:44:53] [WRN] [4] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: /wwwroot. Static files may be unavailable.
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.ApplicationHost: Running startup tasks
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Generate Trickplay Images set to fire at 2024-12-09 03:00:00.000 +00:00, which is 04:15:06.6741657 from now.
2024-12-08 23:44:53 [22:44:53] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2024-12-09 02:00:00.000 +00:00, which is 03:15:06.6728149 from now.
2024-12-08 23:44:53 [22:44:53] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 7.0.2
2024-12-08 23:44:53 [22:44:53] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "ac4", "dca", "flac", "mp3", "truehd"]
2024-12-08 23:44:53 [22:44:53] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
2024-12-08 23:44:53 [22:44:53] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["bwdif_cuda", "deinterlace_qsv", "deinterlace_vaapi", "flip_vulkan", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemapx", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "transpose_cuda", "transpose_opencl", "transpose_vaapi", "transpose_vulkan", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
2024-12-08 23:44:53 [22:44:53] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
2024-12-08 23:44:56 [22:44:56] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Transcode Directory Completed after 0 minute(s) and 0 seconds
2024-12-08 23:44:56 [22:44:56] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean up collections and playlists Completed after 0 minute(s) and 0 seconds
2024-12-08 23:44:57 [22:44:57] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
2024-12-08 23:45:00 [22:45:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
2024-12-08 23:45:00 [22:45:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: ServerId: 0a6470b59ab44fdaa70c3c2ab53747d2
2024-12-08 23:45:00 [22:45:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Core startup complete
2024-12-08 23:45:00 [22:45:00] [INF] [4] Main: Startup complete 0:00:09.1654162
2024-12-09 00:44:53 [23:44:53] [INF] [47] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Transcode Directory Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [49] Emby.Server.Implementations.ScheduledTasks.Tasks.OptimizeDatabaseTask: Optimizing and vacuuming jellyfin.db...
2024-12-09 00:44:53 [23:44:53] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Log Directory Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [51] Emby.Server.Implementations.Library.LibraryManager: Validating media library
2024-12-09 00:44:53 [23:44:53] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Cache Directory Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Audio Normalization Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Download missing subtitles Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [48] Emby.Server.Implementations.Library.LibraryManager: People validation complete
2024-12-09 00:44:53 [23:44:53] [INF] [48] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh People Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [54] Emby.Server.Implementations.ScheduledTasks.TaskManager: TasksRefreshChannels Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: Media Segment Scan Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [49] Emby.Server.Implementations.ScheduledTasks.Tasks.OptimizeDatabaseTask: jellyfin.db optimized successfully!
2024-12-09 00:44:53 [23:44:53] [INF] [49] Emby.Server.Implementations.ScheduledTasks.TaskManager: Optimize database Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: Download missing lyrics Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [WRN] [51] MediaBrowser.Controller.Entities.BaseItem: Library folder /config/data/playlists is inaccessible or empty, skipping
2024-12-09 00:44:53 [23:44:53] [WRN] [51] MediaBrowser.Controller.Entities.BaseItem: Library folder /config/data/playlists is inaccessible or empty, skipping
2024-12-09 00:44:53 [23:44:53] [INF] [53] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:53 [23:44:53] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
2024-12-09 00:44:56 [23:44:56] [INF] [54] Jellyfin.LiveTv.Guide.GuideManager: Refreshing guide with 7 days of guide data
2024-12-09 00:44:56 [23:44:56] [INF] [54] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 3 seconds
2024-12-09 01:27:04 [00:27:04] [INF] [95] Emby.Server.Implementations.Session.SessionManager: Sending shutdown notifications
2024-12-09 01:27:04 [00:27:04] [INF] [96] Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
2024-12-09 01:27:04 [00:27:04] [INF] [97] Main: Running query planner optimizations in the database... This might take a while
2024-12-09 01:27:04 [00:27:04] [INF] [97] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
2024-12-09 01:27:04 [00:27:04] [INF] [97] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
2024-12-09 01:27:04 [00:27:04] [INF] [97] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
2024-12-09 01:27:04 [00:27:04] [INF] [97] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager

  ```
</details>

You can also easily get the exact same logs if you run "docker compose up" in the repo subfolder. It will build the plugin, put it inside the jellyfin image and then launch it.

**Comment by hexxone** [comment]
Ok, it seems like simply removing the nuget package reference to `Microsoft.Extensions.DependencyInjection` magically fixed the problem.

I am pretty sure when not including this explicitly in older versions of jellyfin, the plugin failed to load for me because it couldnt find it, so maybe it was fixxed in the meantime or I made some different mistake.

Anyway, it works now, thanks for the help anyways 🙏
