### ISSUE TITLE
All library items deleted (again) if mount is offline

### ISSUE THREAD

**Issue by jellouser** [jellyfin/jellyfin#13204]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When library is located on network mount (rclone, Linux) and mount is temporarily offline Jellyfin decides to delete all library items.

### Reproduction steps

1. Add library based on network mount as volume on Docker
2. Mount goes offline (no internet on server for example)
3. Wait until Jellyfin decides to do something and....
4. Deletes all items of library

### What is the current _bug_ behavior?

All library items gone

### What is the expected _correct_ behavior?

Library items should not be gone if they are temporarily unavailable

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.1

### Specify the build version

Release

### Environment

```markdown
- OS: Linux
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-12-08 17:30:00.305 +00:00] [DBG] [18] Emby.Server.Implementations.IO.LibraryMonitor: New file refresher created for "/media/Shows/SomeShow"
... actually a TV recording, so it takes time to complete ...
[2024-12-08 19:09:03.435 +00:00] [DBG] [91] Emby.Server.Implementations.IO.LibraryMonitor: Timer stopped.
[2024-12-08 19:09:03.439 +00:00] [INF] [91] Emby.Server.Implementations.IO.LibraryMonitor: "Shows" ("/media/Shows") will be refreshed.
[2024-12-08 19:09:03.442 +00:00] [ERR] [140] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/media/Shows"
System.IO.IOException: Transport endpoint is not connected : '/media/Shows/SomeShow'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& fileP>
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2024-12-08 19:09:03.472 +00:00] [ERR] [140] MediaBrowser.Providers.Folders.FolderMetadataService: Error validating images for "/media/Shows"
System.IO.IOException: Transport endpoint is not connected : '/media/Shows/SomeShow'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& fileP>
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetFiles(BaseItem item, Boolean includeDirectories, IDirectoryService directoryService)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2024-12-08 19:09:03.474 +00:00] [DBG] [140] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 713c43a5b46865d111d02f643d1883d4
[2024-12-08 19:09:03.478 +00:00] [ERR] [140] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children from file system
System.IO.IOException: Transport endpoint is not connected : '/media/Shows/SomeShow'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& fileP>
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directorySe>
[2024-12-08 19:09:03.479 +00:00] [DBG] [140] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 713c43a5b46865d111d02f643d1883d4 5
[2024-12-08 19:09:03.482 +00:00] [DBG] [140] MediaBrowser.Controller.Entities.BaseItem: Removed item: "/media/Shows/AnotherShow"
[2024-12-08 19:09:03.482 +00:00] [INF] [140] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Series", Name: "AnotherShow", Path: "/media/Shows/AnotherShow", Id: 7b0c>
[2024-12-08 19:09:03.484 +00:00] [DBG] [140] Emby.Server.Implementations.Library.LibraryManager: Deleting metadata path, Type: "Series", Name: "AnotherShow", Path: "/config/metadata/library/fc/fca9e8565799f69b1886717>
... last three lines repeated for all library items ...
```

### FFmpeg logs

```shell

```

**Comment by joeposner** [comment]
See the issue I filed, #12785 for more details and a resolution to this.

Short version:
You want to disable the task that checks playlists on application start. The issue I filled also contains a discussion on why checking this at startup is inherently problematic.

**Comment by jellouser** [comment]
Thanks, somehow I've missed that specific task even though I tried to set up only minimal set to run automatically...

**Comment by gnattu** [comment]
Are you mounting the folder in a way that the server very hates like one subfolder per mount point under one library? Like each of the “Somehow” has its own mount point. The server is already intentionally skipping empty mount point at library root folder and that is already causing problems for some of other users like #12297. We cannot do more trade off for this use cases if your mount point behaves that weird that it still have folder structure but just inaccessible to affect more user’s normal operation.

**Comment by joeposner** [comment]
I don't think having a requirement that the folders be at root level is in line with how most people use external hard drives. Usually, it's one big drive for multiple things. So, for example, I have this on my drive:

```
/Volumes/MyDrive/
                         |--> SteamVideoGames
                         |--> iTunes
                         |--> JellyFin
                                     |-->Movies
                                     |-->MusicVideos
```

**Comment by gnattu** [comment]
That wont affect your usage because the Jellyfin folder will gone if the whole disk is gone.

The problem of OP's mount point is that the Subfolders still exists after the mount point is gone. Like the First move folder under the Movies folder is still there after MyDrive is gone.

**Comment by jellouser** [comment]
Sorry I was not specific enough in my original post and also confused some of my setup (I have remote only and mixed library paths). 

@gnattu you are correct this is more complex than an average setup. 

So what I have is a library root `/media/Shows` which is a local folder on Docker host and mounted as a Docker volume inside container. This folder contains both local and remote content as a folder per show. If show is remote it is actually a relative symbolic link to other volume folder inside Docker (/media/RemoteShows) which is rclone mount folder on host:

```
ls /media/Shows
.
..
'LocalShow1'
'LocalShow2'
'RemoteShow1' -> '../RemoteShows/RemoteShow1/'
```

When RemoteShows mount goes offline

a) ls /media/Shows -> still lists all directories both local and remote
b) ls /media/Shows/RemoteShow1 ->  ls: cannot access '/media/Shows/RemoteShow1' Transport endpoint is not connected
c) local shows still accessible

So it would be nice to know why this is causing all items deleted, also the local ones and if there are any ways to mitigate issue. I can also make code changes and build my own version for any testing if suggestions. Why I have symbolic links is for other reasons where I need to keep `/media/Shows` content organized like this.

**Comment by gnattu** [comment]
At this point I don't think there is anything we can do and you are responsible for supporting your use case. There is literally nothing we can do unless we code Jellyfin to never remove non-exist items. What caused your problem is probably similar to the reasons we are having in #13093 where some inaccessible items prevent the item list to even be created so that refresher just got an empty "valid item list", and therefore thinks everything is gone. This part is a bug but that is more or less a dotnet issue not a jellyfin issue.

**Comment by jellouser** [comment]
I agree that what at least should be fixed is that available items are not deleted. The code is flawed in a sense that any "unknown" exception thrown for single item results in deletion of all items.

Given that, what I am not sure about is the current logic that if an item cannot be accessed for any reason (error) should it be considered to be removed since we cannot know the real status of it e.g. if it still exists or not. I would choose failing playback instead removal from library if check failed as an error.

But I now have enough information to fix these issues for my own build.
