### ISSUE TITLE
Jellyfin [10.10.3] will not allow creation of playlists

### ISSUE THREAD

**Issue by jwcrawley** [jellyfin/jellyfin#13211]
**Describe The Bug**
On a newly built Debian Linux bare metal server, using the provided curl installer, Jellyfin will not create playlists.

 

**Steps To Reproduce**

1. Go to a piece of content
2. Add content to playlist
3. Name playlist a common shared name (public or not checkbox doesn't matter)
4. get growl saying "Error creating playlist"

**Expected Behavior**

Create a playlist with name, and add piece of content to it.

**Logs**

Initial logs shows

[2024-12-11 19:49:10.228 -05:00] [INF] Stopping directory watching for path "/nfs/video/Shows"
[2024-12-11 19:49:10.239 -05:00] [INF] Stopping directory watching for path "/nfs/video/Movies"
[2024-12-11 19:49:10.257 -05:00] [INF] Stopping directory watching for path "/nfs/video/recordings"
[2024-12-11 19:49:11.916 -05:00] [WRN] Library folder "/var/lib/jellyfin/data/playlists" is inaccessible or empty, skipping
[2024-12-11 19:49:11.983 -05:00] [INF] Validating media library
[2024-12-11 19:49:12.717 -05:00] [WRN] Library folder "/var/lib/jellyfin/data/playlists" is inaccessible or empty, skipping
[2024-12-11 19:49:12.768 -05:00] [WRN] Library folder "/var/lib/jellyfin/data/playlists" is inaccessible or empty, skipping

Now, i have no playlists at this point. I have yet to create them.

When I attempt to create a playlist, I get the following stack trace in the log:

[2024-12-11 19:55:36.537 -05:00] [ERR] Error processing request. URL "POST" "/Playlists".
System.ArgumentException: parentFolder
   at Emby.Server.Implementations.Playlists.PlaylistManager.CreatePlaylist(PlaylistCreationRequest request)
   at Jellyfin.Api.Controllers.PlaylistsController.CreatePlaylist(String name, IReadOnlyList`1 ids, Nullable`1 userId, Nullable`1 mediaType, CreatePlaylistDto createPlaylistRequest)
   at lambda_method2407(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

**Screenshots**

**System (please complete the following information):**
 - Platform: Debian Linux , bare metal install
 - Browser: firefox and chrome
 - Jellyfin Version: 10.10.3

**Additional Context**

![Image](https://github.com/user-attachments/assets/8ef8e223-5964-4a7d-a736-3811aaffa510)

I checked the permissions of the playlists directory. Its set to jellyfin:jellyfin and 755, just like collections are. Note, collections works fine.

**Comment by gnattu** [comment]
I cannot reproduce this using a fresh debian VM, the auto install script and adding a random video file with a new playlist. We need more concrete reproduction steps if it really happens with fresh install.

**Comment by jwcrawley** [comment]
Weirdly enough, restarting jellyfin through systemctl resolved the issue. 

Its good to be closed. Im going to chalk it up to "system weirdness"
