### ISSUE TITLE
Starting Error when upgrade from v10.9.11 to 10.10.3

### ISSUE THREAD

**Issue by SR996Programmer** [jellyfin/jellyfin#13216]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

after upgrade jellyfin server for windows from v10.9.11 to 10.10.3,when i start jellyfin,it ocurred a mistake,error log said
 "[2024-12-13 09:38:53.890 +08:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[2024-12-13 09:38:53.891 +08:00] [FTL] [1] Main: Error while starting server"

### Reproduction steps

upgrade from jellyfin server for windows v10.9.11 to v10.10.3

### What is the current _bug_ behavior?

jellyfin server can't start

### What is the expected _correct_ behavior?

jellyfin start correctly

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS:windows 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:chrome 131.0.6778.140
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-12-13 09:38:49.157 +08:00] [INF] [1] Main: Jellyfin version: "10.10.3"
[2024-12-13 09:38:49.198 +08:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-12-13 09:38:49.207 +08:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-12-13 09:38:49.213 +08:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.17763"
[2024-12-13 09:38:49.230 +08:00] [INF] [1] Main: Architecture: X64
[2024-12-13 09:38:49.236 +08:00] [INF] [1] Main: 64-Bit Process: True
[2024-12-13 09:38:49.239 +08:00] [INF] [1] Main: User Interactive: True
[2024-12-13 09:38:49.244 +08:00] [INF] [1] Main: Processor count: 12
[2024-12-13 09:38:49.248 +08:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-12-13 09:38:49.250 +08:00] [INF] [1] Main: Log directory path: "C:\ProgramData\Jellyfin\Server\log"
[2024-12-13 09:38:49.252 +08:00] [INF] [1] Main: Config directory path: "C:\ProgramData\Jellyfin\Server\config"
[2024-12-13 09:38:49.255 +08:00] [INF] [1] Main: Cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2024-12-13 09:38:49.257 +08:00] [INF] [1] Main: Temp directory path: "C:\Users\ChenNas\AppData\Local\Temp\jellyfin"
[2024-12-13 09:38:49.260 +08:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-12-13 09:38:49.263 +08:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-12-13 09:38:49.540 +08:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\Users\ChenNas\AppData\Local\Jellyfin\cache"
[2024-12-13 09:38:49.701 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-12-13 09:38:49.721 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Bangumi_1.6.2.0\AnitomySharp.dll"
[2024-12-13 09:38:49.724 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Bangumi_1.6.2.0\Fastenshtein.dll"
[2024-12-13 09:38:49.742 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Bangumi_1.6.2.0\Jellyfin.Plugin.Bangumi.dll"
[2024-12-13 09:38:49.752 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bookshelf, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Bookshelf_11.0.0.0\Jellyfin.Plugin.Bookshelf.dll"
[2024-12-13 09:38:49.758 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.IMVDb, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\IMVDb_4.0.0.0\Jellyfin.Plugin.IMVDb.dll"
[2024-12-13 09:38:49.762 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "0.1.7.0" of "Intro Skipper" 
[2024-12-13 09:38:49.764 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "2.0.0" of "MaxSubtitle" 
[2024-12-13 09:38:49.769 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.MeiamSub.Shooter, Version=1.0.10.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jellyfin.MeiamSub.Shooter_1.0.10.0\Jellyfin.MeiamSub.Shooter.dll"
[2024-12-13 09:38:49.773 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.MeiamSub.Thunder, Version=1.0.10.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jellyfin.MeiamSub.Thunder_1.0.10.0\Jellyfin.MeiamSub.Thunder.dll"
[2024-12-13 09:38:49.901 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.MetaShark, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\MetaShark_2.1.1.0\Jellyfin.Plugin.MetaShark.dll"
[2024-12-13 09:38:49.909 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MetaTube, Version=2024.612.210.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\MetaTube_2024.612.210.0\MetaTube.dll"
[2024-12-13 09:38:49.915 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Opds, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\OPDS_5.0.0.0\Jellyfin.Plugin.Opds.dll"
[2024-12-13 09:38:49.923 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles_20.0.0.0\Jellyfin.Plugin.OpenSubtitles.dll"
[2024-12-13 09:38:49.926 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "2.0.2.0" of "Skin Manager" 
[2024-12-13 09:38:49.932 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SubtitleExtract, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Subtitle Extract_4.0.0.0\Jellyfin.Plugin.SubtitleExtract.dll"
[2024-12-13 09:38:49.944 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_15.0.0.0\Jellyfin.Plugin.Tvdb.dll"
[2024-12-13 09:38:49.966 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Tvdb.Sdk, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_15.0.0.0\Tvdb.Sdk.dll"
[2024-12-13 09:38:49.971 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TranscodeKiller, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Transcode Killer_3.0.0.0\Jellyfin.Plugin.TranscodeKiller.dll"
[2024-12-13 09:38:50.113 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-13 09:38:50.116 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-12-13 09:38:50.118 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-13 09:38:50.123 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.0.100", "127.0.0.1"]
[2024-12-13 09:38:50.127 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-12-13 09:38:50.130 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-12-13 09:38:50.131 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-12-13 09:38:53.520 +08:00] [INF] [1] Jellyfin.MeiamSub.Shooter.ShooterProvider: MeiamSub.Shooter Init
[2024-12-13 09:38:53.522 +08:00] [INF] [1] Jellyfin.MeiamSub.Thunder.ThunderProvider: MeiamSub.Thunder Init
[2024-12-13 09:38:53.611 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bangumi" "1.6.2.0"
[2024-12-13 09:38:53.615 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bookshelf" "11.0.0.0"
[2024-12-13 09:38:53.619 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "IMVDb" "4.0.0.0"
[2024-12-13 09:38:53.622 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MeiamSub.Shooter" "1.0.10.0"
[2024-12-13 09:38:53.625 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MeiamSub.Thunder" "1.0.10.0"
[2024-12-13 09:38:53.627 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MetaShark" "2.1.1.0"
[2024-12-13 09:38:53.630 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MetaTube" "2024.612.210.0"
[2024-12-13 09:38:53.633 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OPDS Feed" "5.0.0.0"
[2024-12-13 09:38:53.644 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "20.0.0.0"
[2024-12-13 09:38:53.647 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Subtitle Extract" "4.0.0.0"
[2024-12-13 09:38:53.650 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "15.0.0.0"
[2024-12-13 09:38:53.653 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Transcode Killer" "3.0.0.0"
[2024-12-13 09:38:53.655 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.10.3.0"
[2024-12-13 09:38:53.657 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.10.3.0"
[2024-12-13 09:38:53.660 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.10.3.0"
[2024-12-13 09:38:53.690 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.10.3.0"
[2024-12-13 09:38:53.693 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.10.3.0"
[2024-12-13 09:38:53.890 +08:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[2024-12-13 09:38:53.891 +08:00] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-12-13 09:38:53.921 +08:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2024-12-13 09:38:53.948 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-12-13 09:38:53.950 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzArtistProvider"
[2024-12-13 09:38:53.954 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2024-12-13 09:38:53.956 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EpisodeProvider"
[2024-12-13 09:38:53.961 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "PluginManager"
```

### FFmpeg logs

```shell

```

**Comment by SR996Programmer** [comment]
And when i downgrade it from v10.10.3 back to v10.9.11,it will work

**Comment by gnattu** [comment]
Please remove the Jellyfin.Plugin.Bangumi plugin which is no longer compatible with 10.10

**Comment by SR996Programmer** [comment]
> Please remove the Jellyfin.Plugin.Bangumi plugin which is no longer compatible with 10.10

it works,thank you!
