### ISSUE TITLE
System.InvalidOperationException: There is an error in XML document (48, 36). ---> System.InvalidOperationException: Instance validation error: 'Game' is not a valid value for UnratedItem.

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#1325]
**Describe the bug**
After upgrading from 10.2.2 to 10.3.1 I got the following error trying to start jellyfin:

```
[2019-04-28 11:39:37.305 -04:00] [ERR] Error reading policy file: "/etc/jellyfin/users/1f178d1bcb62498a99e038c292afc4a0/policy.xml"
System.InvalidOperationException: There is an error in XML document (48, 36). ---> System.InvalidOperationException: Instance validation error: 'Game' is not a valid value for UnratedItem.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderUserPolicy.Read5_UnratedItem(String s)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderUserPolicy.Read6_UserPolicy(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderUserPolicy.Read7_UserPolicy()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Emby.Server.Implementations.Library.UserManager.GetUserPolicy(User user)
```

**System (please complete the following information):**
 - OS: Fedora 29
 - Browser: N/A
 - Jellyfin Version: 10.2.1
 - Reverse proxy: None

**Comment by anthonylavado** [comment]
Did you have Games in your library from an older Emby install?

**Comment by brianjmurrell** [comment]
My installation was indeed an "upgrade" from Emby to Jellyfin.

**Comment by anthonylavado** [comment]
We removed game support formally some time ago, but I don't know when that got rolled in to a release (I suspect at least the 10.2 era, as you are running that). 

It is also known that some library/database imports are prone to really, really breaking, due to the clunky nature of some paths and items being stored in those databases.

In this case, I don't know what the User Policy XML looks like off the top of my head, but I imagine that anything related to games in there will have to be removed. The interpreter in JF is tripping over itself trying to map those items out.
