### ISSUE TITLE
Library scans silently failing after OpenSubtitles API exceeded

### ISSUE THREAD

**Issue by caligari87** [jellyfin/jellyfin#13253]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin has been functioning normally for me on version 10.10.3. Tonight, I added 4 new movies to my media folder at approximately the same time.

1. I noted after some time that the first movie had imported correctly
2. The second movie only showed a "placeholder" element with the file name.
3. The third and fourth movies did not appear at all.

I made repeated library scans, restarted the server several times, checked file permissions, changed some settings, and could not force the remaining items to appear, or the placeholder item to gain proper metadata.

Reviewing the logs, the most recent entries were typical of the following pattern:
```
[2024-12-18 21:00:40.083 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:02:11.083 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:03:42.084 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:05:13.085 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:06:44.086 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:08:15.087 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:08:51.923 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/movie4.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 21:08:51.923 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/movie2.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 21:08:51.923 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/movie3.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 21:09:46.087 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:11:17.088 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:12:48.089 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 21:14:19.090 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```
No error messages.

On a hunch, I eventually decided to check the logs around `movie1.mkv` and noted the following:

```
[2024-12-18 18:53:46.455 -07:00] [INF] "Movies" ("/media/ExtMedia2/Movies") will be refreshed.
[2024-12-18 18:53:46.497 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/movie1.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 18:54:50.552 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:56:21.552 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:57:52.553 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:59:23.554 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:00:09.300 -07:00] [ERR] Login failed: TooManyRequests - "{
  \"message\":\"API rate limit exceeded\"
}"
[2024-12-18 19:00:09.301 -07:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Security.Authentication.AuthenticationException: Authentication to OpenSubtitles failed.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2024-12-18 19:00:12.676 -07:00] [ERR] Error in metadata saver
System.UnauthorizedAccessException: Access to the path '/media/ExtMedia2/Movies/movie1/movie.nfo' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-12-18 19:00:27.366 -07:00] [INF] WS "127.0.0.1" request
[2024-12-18 19:00:54.560 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```

I **disabled** the OpenSubtitles plugin, restarted the server, and the remaining three movies successfully loaded metadata immediately.

### Reproduction steps

1. Have the OpenSubtitles plugin installed, with a valid user account
2. Add new media.
3. Exceed the OpenSubtitles API ???
4. Note that subsequent media will not be recognized or metadata applied.
5. Disable OpenSubtitles plugin.
6. Restart server.
7. Subsequent media populates correctly.

### What is the current _bug_ behavior?

The plugin API failure seems to leave the metadata saver in a broken state.

### What is the expected _correct_ behavior?

Plugin API failures should gracefully fail without impacting the metadata system and allow new media to be added. The user interface should communicate the API failure.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Linux Mint 21.3 Cinnamon
- Linux Kernel: 6.8.0-49-generic
- Virtualization: none?
- Clients: Web, Google TV/Chromecast
- Browser: Firefox 133.0.3 (64 bit)
- FFmpeg Version: jellyfin-ffmpeg7 7.0.2-8-jammy
- Playback Method: Browser, Chromecast
- Hardware Acceleration: NVENC
- GPU Model: GeForce RTX 2060 SUPER
- Plugins: OpenSubtitles 20.0.0.0
- Reverse Proxy: ?
- Base URL: ?
- Networking: ?
- Storage: SATA HDD
```

### Jellyfin logs

```shell
[2024-12-18 18:52:25.853 -07:00] [INF] User policy for "jellyfin-admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-12-18 18:52:25.853 -07:00] [INF] RemoteClientBitrateLimit: 15000000, RemoteIP: "192.168.86.140", IsInLocalNetwork: True
[2024-12-18 18:53:19.551 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:53:46.455 -07:00] [INF] "Movies" ("/media/ExtMedia2/Movies") will be refreshed.
[2024-12-18 18:53:46.497 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/Legend.1985.THEATRICAL.iNTERNAL.1080p.BluRay.x264-PEGASUS/legend.1985.theatrical.1080p.bluray.x264-pegasus.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 18:54:50.552 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:56:21.552 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:57:52.553 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 18:59:23.554 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:00:09.300 -07:00] [ERR] Login failed: TooManyRequests - "{
  \"message\":\"API rate limit exceeded\"
}"
[2024-12-18 19:00:09.301 -07:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Security.Authentication.AuthenticationException: Authentication to OpenSubtitles failed.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2024-12-18 19:00:12.676 -07:00] [ERR] Error in metadata saver
System.UnauthorizedAccessException: Access to the path '/media/ExtMedia2/Movies/Legend.1985.THEATRICAL.iNTERNAL.1080p.BluRay.x264-PEGASUS/movie.nfo' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2024-12-18 19:00:27.366 -07:00] [INF] WS "127.0.0.1" request
[2024-12-18 19:00:54.560 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:02:25.555 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:03:56.557 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:05:27.557 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:05:58.127 -07:00] [INF] WS "127.0.0.1" closed
[2024-12-18 19:05:58.458 -07:00] [INF] WS "127.0.0.1" request
[2024-12-18 19:06:58.557 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:08:29.557 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:10:00.557 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:11:31.559 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:12:21.572 -07:00] [INF] Playback stopped reported by app "Android TV" "0.18.2" playing "Little Women". Stopped at "6900076" ms
[2024-12-18 19:13:02.558 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:14:13.902 -07:00] [ERR] Permission error for Directory watcher: "/media/ExtMedia2/Movies"
System.UnauthorizedAccessException: Access to the path '/media/ExtMedia2/Movies/Unfriended.2014.1080p.BluRay.x264-OFT__1ELP51' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2024-12-18 19:14:33.558 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:16:04.559 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:17:35.560 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:19:06.560 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:20:37.561 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:22:08.561 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:23:39.561 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:25:10.563 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:26:41.563 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:28:12.563 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:29:43.564 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:31:14.564 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:31:30.280 -07:00] [INF] User policy for "jellyfin-admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-12-18 19:31:30.281 -07:00] [INF] RemoteClientBitrateLimit: 15000000, RemoteIP: "192.168.86.140", IsInLocalNetwork: True
[2024-12-18 19:32:45.564 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:34:16.564 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:35:47.564 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:37:18.565 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:38:49.566 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:40:20.567 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:41:21.704 -07:00] [INF] "Movies" ("/media/ExtMedia2/Movies") will be refreshed.
[2024-12-18 19:41:21.967 -07:00] [INF] Removing item, Type: "Movie", Name: "Unfriended", Path: "/media/ExtMedia2/Movies/Unfriended.2014.1080p.BluRay.x264-OFT/Unfriended.2014.1080p.BluRay.x264-OFT.mkv", Id: 2b52c7c4-47e0-31b8-2fe5-49a0d96e6210
[2024-12-18 19:41:21.992 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/Dune.Part.Two.2024.UHD.BluRay.2160p.DDP.7.1.DV.HDR.x265-hallowed.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 19:41:21.994 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/Dune.2021.UHD.BluRay.2160p.DDP.7.1.DV.HDR.x265-hallowed.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 19:41:22.002 -07:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/ExtMedia2/Movies/Tron.Legacy.2010.Open.Matte.PROPER.HDR-X.DV.HDR10+.DTS-HD.MA.7.1-TEKNO3D/Tron.Legacy.2010.Open.Matte.PROPER.HDR-X.DV.HDR10+.DTS-HD.MA.7.1-TEKNO3D.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-18 19:41:51.566 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:43:22.566 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:44:53.566 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:46:24.567 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:47:55.567 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:49:26.567 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:50:57.567 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:52:28.568 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-18 19:53:59.569 -07:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
```

### FFmpeg logs

```shell

```

**Comment by AlexanderOlivares** [comment]
I just encountered this issue too on v10.10.3. Open Subtitles limits you to 20 downloads per day on their non-paid subscription. After being rate limited, all manual metadata refreshes I triggered stalled at this point: 

`[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with arg ...`

After disabling the OpenSubtitles plugin and restarting jellyfin container, the metadata refresh works as expected.
