### ISSUE TITLE
[Issue]: Clean Activity Log scheduled task continually fails when run

### ISSUE THREAD

**Issue by TimF0** [jellyfin/jellyfin#13270]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The JF scheduled task "clean activity log" perpetually says 'failed'. 

Running it manually executes code, but it finishes in under a second and still says 'failed'

Logs show an error.

This has been an issue for me for several versions now, but thought I should finally get around to logging it.

### Reproduction steps

1. Go to the JF dashboard
2. Select scheduled tasks
3. Go to the maintenance section and run the 'clean activity log' task
4. Job finishes in under a second and indicates 'failed' in red.

### What is the current _bug_ behavior?

The scheduled task fails.

No other tasks are affected (they all seem to work fine), and I've not noticed any adverse behaviour on JF (though it may not be apparent)

### What is the expected _correct_ behavior?

The scheduled task finishes correctly

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS:Unraid 6.12.14 (Jellyfin docker)
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:Firefox 133.0.3
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Direct
- Hardware Acceleration:
- GPU Model:
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: n/a
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-12-22 10:42:44.334 +00:00] [ERR] [25] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("7"ms) [Parameters=["@__startDate_0='?' (DbType = DateTime)"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"ActivityLogs\" AS \"a\"
WHERE \"a\".\"DateCreated\" <= @__startDate_0"
[2024-12-22 10:42:44.334 +00:00] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CleanAsync(DateTime startDate)
   at Jellyfin.Server.Implementations.Activity.ActivityManager.CleanAsync(DateTime startDate)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-12-22 10:42:44.334 +00:00] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean Activity Log" Failed after 0 minute(s) and 0 seconds
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/34e6c48f-470c-4335-9915-3aa37b87f7e3)

**Comment by felix920506** [comment]
> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.

Your database file is corrupted. There is nothing we can do about it.

**Comment by TimF0** [comment]
Apart from reinstalling JF, is there any way to clear this ?

**Comment by TimF0** [comment]
@felix920506 Hi, in relation to this issue (#13270) about the clean activity logs job failing with a 'database image malformed' issue, I logged into sqllite and cleared the activitylogs table manually - no errors in doing it. On restarting JF, the job no longer fails. Is it worth pursuing this any further, or just leave it ?

**Comment by felix920506** [comment]
Just leave it. It is not worth pursuing.
