### ISSUE TITLE
System.NullReferenceException raised during library scan

### ISSUE THREAD

**Issue by YanzheL** [jellyfin/jellyfin#1336]
**Describe the bug**

I use the Official Jellyfin docker image with docker compose.

```yaml
version: '3.6'
services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./netdisk:/media
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
    environment:
      - UID=0
      - GID=0
      - GIDLIST=1000,44
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    privileged: true
```
The server can be reached via hostname:8096 without problem.

During the library scan process, no matter how long I wait, the progress bar just sticks at 86.4%. Only one TV series was shown on the homepage.

The output of `docker-compose logs -f ` shows:

```
jellyfin_1  | [02:43:28] [INF] Jellyfin version: 10.3.1.0
jellyfin_1  | [02:43:28] [INF] Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/local/bin/ffmpeg"]
jellyfin_1  | [02:43:28] [INF] Operating system: Linux
jellyfin_1  | [02:43:28] [INF] Architecture: X64
jellyfin_1  | [02:43:28] [INF] 64-Bit Process: True
jellyfin_1  | [02:43:28] [INF] User Interactive: True
jellyfin_1  | [02:43:28] [INF] Processor count: 12
jellyfin_1  | [02:43:28] [INF] Program data path: /config
jellyfin_1  | [02:43:28] [INF] Web resources path: /jellyfin/jellyfin-web/src
jellyfin_1  | [02:43:28] [INF] Application directory: /jellyfin/
jellyfin_1  | [02:43:28] [INF] Setting cache path to /cache
jellyfin_1  | [02:43:28] [INF] Loading assemblies
jellyfin_1  | [02:43:28] [INF] Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/OpenSubtitlesHandler.dll
jellyfin_1  | [02:43:28] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
jellyfin_1  | [02:43:28] [INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting/Jellyfin.Plugin.PlaybackReporting.dll
jellyfin_1  | [02:43:28] [INF] Loaded assembly Jellyfin.Plugin.Anime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Anime/Jellyfin.Plugin.Anime.dll
jellyfin_1  | [02:43:28] [INF] Loaded assembly Jellyfin.Plugin.Reports, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Reports/Jellyfin.Plugin.Reports.dll
jellyfin_1  | [02:43:28] [INF] Sqlite version: 3.26.0
jellyfin_1  | [02:43:28] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
jellyfin_1  | [02:43:28] [INF] Default journal_mode for /config/data/users.db is wal
jellyfin_1  | [02:43:28] [INF] PRAGMA synchronous=1
jellyfin_1  | [02:43:28] [INF] Default journal_mode for /config/data/authentication.db is wal
jellyfin_1  | [02:43:28] [INF] PRAGMA synchronous=1
jellyfin_1  | [02:43:28] [INF] Default journal_mode for /config/data/activitylog.db is wal
jellyfin_1  | [02:43:28] [INF] PRAGMA synchronous=1
jellyfin_1  | [02:43:28] [INF] Default journal_mode for /config/data/displaypreferences.db is wal
jellyfin_1  | [02:43:28] [INF] PRAGMA synchronous=1
jellyfin_1  | [02:43:28] [INF] Default journal_mode for /config/data/library.db is wal
jellyfin_1  | [02:43:28] [INF] PRAGMA synchronous=1
jellyfin_1  | [02:43:28] [INF] UserActivityAPI Loaded
jellyfin_1  | [02:43:29] [INF] SkiaSharp version: 1.68.0.0
jellyfin_1  | [02:43:29] [INF] Running startup tasks
jellyfin_1  | [02:43:29] [INF] TaskCleanDb Loaded
jellyfin_1  | [02:43:29] [INF] TaskCleanDb Loaded
jellyfin_1  | [02:43:29] [INF] Daily trigger for Playback Reporting Trim Db set to fire at 05/02/2019 00:00, which is 21:16:30.7494963 from now.
jellyfin_1  | [02:43:29] [INF] Daily trigger for Chapter image extraction set to fire at 05/02/2019 02:00, which is 23:16:30.7462671 from now.
jellyfin_1  | [02:43:29] [INF] FFmpeg validation: Found ffmpeg version 4.0
jellyfin_1  | [02:43:29] [INF] FFmpeg validation: Found suitable ffmpeg version
jellyfin_1  | [02:43:29] [INF] Validating media encoder at /usr/local/bin/ffmpeg
jellyfin_1  | [02:43:29] [INF] Available decoders: ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
jellyfin_1  | [02:43:29] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
jellyfin_1  | [02:43:29] [INF] Encoder validation complete
jellyfin_1  | [02:43:29] [INF] FFmpeg: Custom: /usr/local/bin/ffmpeg
jellyfin_1  | [02:43:29] [INF] ServerId: 7b9cf4de473649818d64b6e96b88aa29
jellyfin_1  | [02:43:29] [INF] Executed all pre-startup entry points in 0:00:00.1090415
jellyfin_1  | [02:43:29] [INF] Core startup complete
jellyfin_1  | [02:43:29] [INF] EventMonitorEntryPoint Running
jellyfin_1  | [02:43:29] [INF] Sqlite version: 3.26.0
jellyfin_1  | [02:43:29] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
jellyfin_1  | [02:43:29] [INF] Default journal_mode for /config/data/playback_reporting.db is delete
jellyfin_1  | [02:43:29] [INF] Initialize PlaybackActivity Repository
jellyfin_1  | [02:43:29] [INF] PlaybackActivity table schema OK
jellyfin_1  | [02:43:29] [INF] Expected : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
jellyfin_1  | [02:43:29] [INF] Received : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
jellyfin_1  | [02:43:29] [INF] Watching directory /media/episodes
jellyfin_1  | [02:43:29] [INF] Executed all post-startup entry points in 0:00:00.1760986
jellyfin_1  | [02:43:29] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 10.200.197.2
jellyfin_1  | [02:43:32] [INF] StartupTrigger fired for task: Check for plugin updates
jellyfin_1  | [02:43:32] [INF] Queueing task PluginUpdateTask
jellyfin_1  | [02:43:32] [INF] Executing Check for plugin updates
jellyfin_1  | [02:43:32] [INF] HttpClientManager GET: https://repo.jellyfin.org/releases/plugin/manifest.json
jellyfin_1  | [02:43:39] [INF] Check for plugin updates Completed after 0 minute(s) and 7 seconds
jellyfin_1  | [02:43:39] [INF] ExecuteQueuedTasks
jellyfin_1  | [02:43:42] [INF] WS http://10.245.146.40:8096/embywebsocket?api_key=cc8b7ce7a2bb45f4807003c950c58384&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNzMuMC4zNjgzLjg2IFNhZmFyaS81MzcuMzZ8MTU1NjEwNzc0NzkxNA11. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
jellyfin_1  | [02:43:51] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:04.4737121. http://10.245.146.40:8096/emby/System/Info
jellyfin_1  | [02:43:55] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:04.3729564. http://10.245.146.40:8096/emby/System/Info
jellyfin_1  | [02:43:58] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:04.7329607. http://10.245.146.40:8096/emby/system/info/public
jellyfin_1  | [02:44:03] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:04.8731553. http://10.245.146.40:8096/emby/System/Info
jellyfin_1  | [02:44:03] [INF] WS http://10.245.146.40:8096/embywebsocket?api_key=cc8b7ce7a2bb45f4807003c950c58384&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNzMuMC4zNjgzLjg2IFNhZmFyaS81MzcuMzZ8MTU1NjEwNzc0NzkxNA11. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
jellyfin_1  | [02:44:08] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:05.4633358. http://10.245.146.40:8096/emby/System/Info
jellyfin_1  | [02:44:22] [INF] Creating image collage and saving to /cache/temp/9bae6df7529f4796a7b961708ee83aa9.png
jellyfin_1  | [02:44:22] [INF] Completed creation of image collage and saved to /cache/temp/9bae6df7529f4796a7b961708ee83aa9.png
jellyfin_1  | [02:44:23] [INF] Start Proxer... Searching(Narcos)
jellyfin_1  | [02:44:47] [INF] Start AniSearch... Searching(Narcos)
jellyfin_1  | [02:44:56] [WRN] HTTP Response 200 to 10.200.197.1. Time (slow): 0:00:04.3765521. http://10.245.146.40:8096/emby/System/Info
jellyfin_1  | [02:45:01] [INF] Start AniList... Searching(Narcos)
jellyfin_1  | [02:46:54] [ERR] Error in TheTVDB
jellyfin_1  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin_1  |    at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
jellyfin_1  |    at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
jellyfin_1  |    at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, SearchParameter parameter, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
jellyfin_1  | [02:46:54] [INF] HttpClientManager GET: https://api.themoviedb.org/3/tv/63351?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings&language=en&include_image_language=en,null
jellyfin_1  | [02:46:59] [INF] HttpClientManager GET: https://api.themoviedb.org/3/configuration?api_key=4219e299c89411838049ab0dab19ebd5
jellyfin_1  | [02:47:04] [INF] HttpClientManager GET: https://www.omdbapi.com?apikey=2c9d9507&i=tt2707408&plot=short&tomatoes=true&r=json
jellyfin_1  | [02:47:05] [INF] HttpClientManager GET: https://webservice.fanart.tv/v3/tv/282670?api_key=184e1a2b1fe3b94935365411f919f638
jellyfin_1  | [02:47:11] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/tvposter/narcos-55b8137ddafb2.jpg
jellyfin_1  | [02:47:21] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/hdclearart/narcos-55ec341099b59.png
jellyfin_1  | [02:47:34] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/tvbanner/narcos-5612a2d57ae02.jpg
jellyfin_1  | [02:47:42] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/hdtvlogo/narcos-55d867df26dd3.png
jellyfin_1  | [02:47:56] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/tvthumb/narcos-55d7e8d99c35c.jpg
jellyfin_1  | [02:48:13] [INF] HttpClientManager GET: https://assets.fanart.tv/fanart/tv/282670/showbackground/narcos-5ae0a531abf2c.jpg
jellyfin_1  | [02:49:59] [ERR] TvdbSeriesImageProvider failed in GetImageInfos for type Series
jellyfin_1  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin_1  |    at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
jellyfin_1  |    at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
jellyfin_1  |    at TvDbSharper.Clients.SeriesClient.GetImagesAsync(Int32 seriesId, ImagesQuery query, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin_1  |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
jellyfin_1  | [02:49:59] [INF] HttpClientManager GET: https://api.themoviedb.org/3/tv/63351?api_key=4219e299c89411838049ab0dab19ebd5&append_to_response=credits,images,keywords,external_ids,videos,content_ratings
[Log.txt](https://github.com/jellyfin/jellyfin/files/3133719/Log.txt)

```

It seems like network errors caused the `System.NullReferenceException`.

However, I can still see some new images show up on home page, which means that the container itself can reach the internet.

I changed the network option in `docker-compose.yml` from

```yaml
ports:
  - "8096:8096"
```

to 

```yaml
network_mode: host
```

Then this issue was solved. Library scanning works fine and finishes in time as expected. New images show up normally.

**To Reproduce**

1. Use the `docker-compose.yml` as shown.
    You can omit the `environment` and `devices` section because it is related to `nvidia-docker` support.
2. Start the container.
    `docker-compose up -d --build`
    I cleaned all contents in `cache` directory before starting the container
3. Go to Admin Dashboard page.
4. In Library section, click "scan library" and "Replace all metadata" and toggle `Replace existing images`.
3. Now you have a long day to wait for the library scan.
4. Errors can be seen by `docker-compose logs -f`. 

**Expected behavior**

Finish the library scan normally.

**Logs**

[Log.txt](https://github.com/jellyfin/jellyfin/files/3133720/Log.txt)

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker version: 18.09.3, build 774a1f4
 - Browser: Chrome
 - Jellyfin Version: 10.3.1.0
 - Reverse proxy: nginx

**Additional context**

I also tried to build the docker image byself according to [Offical Documentation](https://jellyfin.readthedocs.io/en/latest/administrator-docs/building/) with the current master head 61d7bed18145cd8b56b748a87b9398fb75332044

But it still shows the same error.

**Comment by icofans** [comment]
I meet this problem in Debian9, library scan Stuck in 86%，it looks doesn't work，I just can look many logs like：

[2019-09-14 20:24:26.718 +08:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2019-09-14 20:26:06.902 +08:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by icofans** [comment]
I meet this problem in Debian9, library scan Stuck in 86%，it looks doesn't work，I just can look many logs like：

```
[2019-09-14 20:24:26.718 +08:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2019-09-14 20:26:06.902 +08:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
