### ISSUE TITLE
Media controls not appearing

### ISSUE THREAD

**Issue by cashida** [jellyfin/jellyfin#1355]
When you start a movie, there aren't any media controls in the first few minutes. The movie is playing, but the loading animation is displayed.
The media controls appear after around 5 minutes.

**To Reproduce**

1. Select a movie
2. Click on play
3. See error

**Expected behavior**

Media controls should appear immediately, just like in Emby.

**Logs**

```[2019-05-06 00:18:50.383 +02:00] [INF] Transcoding kill timer stopped for JobId "54d05186e7e14ca8851807c474d1b6fd" PlaySessionId "3145dee4d2e6497c82006781f7102560". Killing transcoding
[2019-05-06 00:18:50.383 +02:00] [INF] Stopping ffmpeg process with q command for "/var/lib/jellyfin/transcoding-temp/e5c4fb5952f5098ab911f1b772d5ca9f.m3u8"
[2019-05-06 00:18:52.188 +02:00] [INF] FFMpeg exited with code 0
[2019-05-06 00:18:52.189 +02:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/e5c4fb5952f5098ab911f1b772d5ca9f.m3u8"
[2019-05-06 00:19:17.669 +02:00] [ERR] Could not find handler for "/embywebsocket"
[2019-05-06 00:20:08.041 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:00.5554626. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/23.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:20:17.876 +02:00] [ERR] Could not find handler for "/embywebsocket"
[2019-05-06 00:20:20.383 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:01.041. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/25.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:20:27.170 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:01.5054998. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/26.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:21:01.962 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:00.629728. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/32.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:21:42.279 +02:00] [WRN] Killing ffmpeg subtitle extraction process
[2019-05-06 00:21:42.284 +02:00] [WRN] Deleting extracted subtitle due to failure: "/var/lib/jellyfin/data/subtitles/a/a798b8b9-b1fd-2ddb-b920-34e6cacbdaee.srt"
[2019-05-06 00:21:42.291 +02:00] [ERR] ffmpeg subtitle extraction failed for file:"/media/gdrive_filme/Bumblebee.2018.IMAX.German.Dubbed.AC3.2160p.UHD.BluRay.HDR.x265-myHD/Bumblebee (2018).mkv" to /var/lib/jellyfin/data/subtitles/a/a798b8b9-b1fd-2ddb-b920-34e6cacbdaee.srt
[2019-05-06 00:21:42.302 +02:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for file:"/media/gdrive_filme/Bumblebee.2018.IMAX.German.Dubbed.AC3.2160p.UHD.BluRay.HDR.x265-myHD/Bumblebee (2018).mkv" to /var/lib/jellyfin/data/subtitles/a/a798b8b9-b1fd-2ddb-b920-34e6cacbdaee.srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-05-06 00:21:42.379 +02:00] [WRN] HTTP Response 500 to "<MYIP>". Time (slow): 0:05:00.1545893. "http://<MYDOMAIN>/emby/Videos/30398d68-5d84-2d12-3df7-b566472db8c5/30398d685d842d123df7b566472db8c5/Subtitles/2/0/Stream.vtt"
[2019-05-06 00:21:50.874 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:01.2777506. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/40.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:21:55.892 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:00.5322935. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/41.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:22:02.224 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:00.8619754. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/42.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:22:36.162 +02:00] [ERR] Could not find handler for "/embywebsocket"
[2019-05-06 00:22:57.976 +02:00] [WRN] HTTP Response 200 to "<MYIP>". Time (slow): 0:00:02.0108381. "http://<MYDOMAIN>/emby/videos/5b34a942-ba7a-56e9-e567-729c53429eec/hls1/main/51.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82Ni4wfDE1NTcwOTE5NjQ0MzE1&MediaSourceId=5b34a942ba7a56e9e567729c53429eec&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=42770853&AudioBitrate=640000&PlaySessionId=0590319fc36445df92cd603db1cc5b49&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=8a550db64552e55e691b2d45544f86c3&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-05-06 00:23:13.280 +02:00] [WRN] Killing ffmpeg subtitle extraction process
[2019-05-06 00:23:13.280 +02:00] [WRN] Deleting extracted subtitle due to failure: "/var/lib/jellyfin/data/subtitles/a/ab7e3e1a-64e1-bf07-c1ae-eefbfa845e54.srt"
[2019-05-06 00:23:13.282 +02:00] [ERR] ffmpeg subtitle extraction failed for file:"/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv" to /var/lib/jellyfin/data/subtitles/a/ab7e3e1a-64e1-bf07-c1ae-eefbfa845e54.srt
[2019-05-06 00:23:13.286 +02:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for file:"/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv" to /var/lib/jellyfin/data/subtitles/a/ab7e3e1a-64e1-bf07-c1ae-eefbfa845e54.srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-05-06 00:23:13.301 +02:00] [WRN] HTTP Response 500 to "<MYIP>". Time (slow): 0:05:00.2730703. "http://<MYDOMAIN>/emby/Videos/5b34a942-ba7a-56e9-e567-729c53429eec/5b34a942ba7a56e9e567729c53429eec/Subtitles/4/0/Stream.vtt"
[2019-05-06 00:23:13.735 +02:00] [INF] User policy for "<MYUSERNAME>". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-05-06 00:23:13.735 +02:00] [INF] Profile: "Unknown Profile", Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-05-06 00:23:13.735 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv"
[2019-05-06 00:23:13.736 +02:00] [INF] Profile: "Unknown Profile", Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-05-06 00:23:13.736 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv"
[2019-05-06 00:23:13.736 +02:00] [INF] Profile: "Unknown Profile", Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-05-06 00:23:13.736 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv"
[2019-05-06 00:23:14.427 +02:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/media/gdrive_filme/Thor.2011.German.DTSD.DL.1080p.BluRay.x264-MULTiPLEX/mp-thor-1080p.mkv\" -map 0:4 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/a/ab7e3e1a-64e1-bf07-c1ae-eefbfa845e54.srt\
```

**Screenshots**

https://i.imgur.com/wn8Y2a1.png
https://i.imgur.com/uOSyHuv.png

**System**
 - OS: Ubuntu 16.04
 - Browser: various
 - Jellyfin Version: 10.3.2
 - Reverse proxy: Apache2, however the issue also appears without reverse proxy

**Additional context**

The media controls appear instantly when you resume a movie.
It looks like something is slow. My media is mounted with rclone through G Suite.

**Comment by agilob** [comment]
I see this occasionally too, there is an exception in video playback JS code, some variable is undefined. I think I reported this right after jellyfin was created.
