### ISSUE TITLE
Unable to play video with external subtitles .ass format

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin#1388]
**Describe the bug**
The problem occurs when playing video with subtitles in .ass format

The issue has been tested through the DLNA client and the Android TV application. The web client works without problems and through the Android application, the subtitles lose style. The rest of the clients have not been tested.

To "solve this problem", it is necessary not to have selected any preferred subtitle language. In that case, play the video without problems.

**Logs**

```
[2019-07-13 16:51:16.766 +02:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-07-13 16:51:16.766 +02:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-07-13 16:51:16.766 +02:00] [INF] Profile: "Generic Device", Path: "\\192.168.1.7\Datos\Series\One Piece (1999)\Temporada 14\S14E35 - Â¡Empieza el entrenamiento de Luffy! Nos veremos dentro de dos aÃ±os, en el lugar pactado.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-07-13 16:51:16.769 +02:00] [ERR] Error processing request
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam(EncodingJobInfo state)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetOutputSizeParam(EncodingJobInfo state, EncodingOptions options, String outputVideoCodec, Boolean allowTimeStampCopy)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoArguments(EncodingJobInfo state, EncodingOptions encodingOptions, String videoCodec, String defaultH264Preset)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoFullCommandLine(EncodingJobInfo state, EncodingOptions encodingOptions, String outputPath, String defaultH264Preset)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian Buster
 - Jellyfin Version: 10.3.6
 - Reverse proxy: No

**Additional context**
Related bug #376

**Comment by 97carmine** [comment]
Maybe

```
[2019-06-26 10:45:16.938 +02:00] [INF] FFmpeg validation: Found ffmpeg version "4.0"
[2019-06-26 10:45:16.938 +02:00] [INF] FFmpeg validation: Found suitable ffmpeg version
[2019-06-26 10:45:16.949 +02:00] [INF] Validating media encoder at "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2019-06-26 10:45:16.975 +02:00] [INF] Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2019-06-26 10:45:16.997 +02:00] [INF] Available "encoders": ["libx264", "h264_nvenc", "h264_omx", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2019-06-26 10:45:16.997 +02:00] [INF] Encoder validation complete
```

**Comment by 97carmine** [comment]
When enabling debugging I have obtained the same error obtained in #1472.

In my case with external .ass subtitles, with internal .ass works well.

The subtitles .srt both internal and external also work without problems.
