### ISSUE TITLE
Request Index out of bounds

### ISSUE THREAD

**Issue by SuperSandro2000** [jellyfin/jellyfin#1390]
**Describe the bug**

**To Reproduce**

1. Go to my domain
**Expected behavior**

To show the login interface

**Logs**

````
[ERR] Error processing request
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Model.Cryptography.PasswordHash..ctor(String storageString)
   at Emby.Server.Implementations.Library.UserManager.GetLocalPasswordHash(User user)
   at Emby.Server.Implementations.Library.UserManager.GetUserDto(User user, String remoteEndPoint)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaBrowser.Api.UserService.Get(GetUsers request, Boolean filterByDevice, Boolean filterByNetwork)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
````

````
apiclientcore.js?v=10.3.3:58 GET https://jellyfin.example.de/emby/users/public 500
getFetchPromise @ apiclientcore.js?v=10.3.3:58
ApiClient.fetch @ apiclientcore.js?v=10.3.3:266
ApiClient.ajax @ apiclientcore.js?v=10.3.3:287
ApiClient.getPublicUsers @ apiclientcore.js?v=10.3.3:1086
handleConnectionResult @ appRouter.js?v=10.3.3:37
authenticate @ appRouter.js?v=10.3.3:382
handleRoute @ appRouter.js?v=10.3.3:93
(anonymous) @ appRouter.js?v=10.3.3:522
(anonymous) @ page.js?v=10.3.3:575
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
page.dispatch @ page.js?v=10.3.3:381
page.replace @ page.js?v=10.3.3:337
page.start @ page.js?v=10.3.3:192
page @ page.js?v=10.3.3:94
(anonymous) @ appRouter.js?v=10.3.3:340
Promise.then (async)
start @ appRouter.js?v=10.3.3:334
(anonymous) @ site.js?v=10.3.3:592
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:591
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
onAppReady @ site.js?v=10.3.3:574
(anonymous) @ site.js?v=10.3.3:525
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:524
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
onGlobalizeInit @ site.js?v=10.3.3:523
(anonymous) @ site.js?v=10.3.3:484
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:483
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:481
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:478
Promise.then (async)
init @ site.js?v=10.3.3:477
onWebComponentsReady @ site.js?v=10.3.3:670
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:1151
(anonymous) @ site.js?v=10.3.3:1152
Show 21 more frames
index.html#!/index.html:1 Uncaught (in promise) Response {type: "basic", url: "https://jellyfin.example.de/emby/users/public", redirected: false, status: 500, ok: false, …}
Promise.then (async)
handleConnectionResult @ appRouter.js?v=10.3.3:37
authenticate @ appRouter.js?v=10.3.3:382
handleRoute @ appRouter.js?v=10.3.3:93
(anonymous) @ appRouter.js?v=10.3.3:522
(anonymous) @ page.js?v=10.3.3:575
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
(anonymous) @ page.js?v=10.3.3:577
nextEnter @ page.js?v=10.3.3:375
page.dispatch @ page.js?v=10.3.3:381
page.replace @ page.js?v=10.3.3:337
page.start @ page.js?v=10.3.3:192
page @ page.js?v=10.3.3:94
(anonymous) @ appRouter.js?v=10.3.3:340
Promise.then (async)
start @ appRouter.js?v=10.3.3:334
(anonymous) @ site.js?v=10.3.3:592
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:591
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
onAppReady @ site.js?v=10.3.3:574
(anonymous) @ site.js?v=10.3.3:525
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:524
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
onGlobalizeInit @ site.js?v=10.3.3:523
(anonymous) @ site.js?v=10.3.3:484
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:483
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:481
Promise.then (async)
(anonymous) @ site.js?v=10.3.3:478
Promise.then (async)
init @ site.js?v=10.3.3:477
onWebComponentsReady @ site.js?v=10.3.3:670
execCb @ alameda.js?v=10.3.3:392
defineModule @ alameda.js?v=10.3.3:145
depFinished @ alameda.js?v=10.3.3:153
(anonymous) @ alameda.js?v=10.3.3:178
Promise.then (async)
waitForDep @ alameda.js?v=10.3.3:177
(anonymous) @ alameda.js?v=10.3.3:346
main @ alameda.js?v=10.3.3:344
(anonymous) @ alameda.js?v=10.3.3:100
Promise.then (async)
req @ alameda.js?v=10.3.3:99
(anonymous) @ site.js?v=10.3.3:1151
(anonymous) @ site.js?v=10.3.3:1152
Show 17 more frames
````

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome 74
 - Jellyfin Version: 10.3.3 
 - Reverse proxy: Traefik behind CLoudflare

**Additional context**

**Comment by Mercurial** [comment]
also had this issue, related to users. I had to delete delete my users.db and restart server , recreated my users

**Comment by joern-h** [comment]
Duplicate #1386
