### ISSUE TITLE
Chromecast Doesn't Work, Gives No Indication It Failed

### ISSUE THREAD

**Issue by XVicarious** [jellyfin/jellyfin#144]
I can use the Emby Android app to launch the Chromecast. Then I press play on an item and the following is what the logs give me. No more.

I guess the `Unknown Profile` is probably the telling thing here. I have tried this with multiple containers and encodings. None work on the Chromecast. I get no response out of the app that I clicked play at all. These same files play on the device itself when I'm not using the cast.

Is anyone else having an issue with Chromecast? I wiped my entire Emby config directory, so it's a clean install.

```
2018-12-13 04:36:17.873 Info HttpServer: HTTP POST http://192.168.0.32:8096/emby/Items/ca695b5cce247a5bf94987e10f3077b4/PlaybackInfo?UserId=d496eef0621e44d29ad0e967aaf095e7&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=509090909. UserAgent: Mozilla/5.0 (Linux; Android 9; Pixel 2 Build/PPR1.180610.009; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.98 Mobile Safari/537.36
2018-12-13 04:36:17.875 Debug App: GetPostedPlaybackInfo request: {"Id":"ca695b5cce247a5bf94987e10f3077b4","UserId":"d496eef0621e44d29ad0e967aaf095e7","MaxStreamingBitrate":509090909,"StartTimeTicks":0,"DeviceProfile":{"EnableAlbumArtInDidl":false,"EnableSingleAlbumArtLimit":false,"EnableSingleSubtitleLimit":false,"SupportedMediaTypes":"Audio,Photo,Video","MaxAlbumArtWidth":0,"MaxAlbumArtHeight":0,"MaxStreamingBitrate":200000000,"MaxStaticBitrate":200000000,"MusicStreamingTranscodingBitrate":192000,"TimelineOffsetSeconds":0,"RequiresPlainVideoItems":false,"RequiresPlainFolders":false,"EnableMSMediaReceiverRegistrar":false,"IgnoreTranscodeByteRangeRequests":false,"XmlRootAttributes":[],"DirectPlayProfiles":[{"Type":"Video"},{"Type":"Audio"}],"TranscodingProfiles":[{"Container":"ts","Type":"Video","VideoCodec":"h264,mpeg2video,hevc","AudioCodec":"ac3,mp3,aac","Protocol":"hls","EstimateContentLength":false,"EnableMpegtsM2TsMode":false,"TranscodeSeekInfo":"Auto","CopyTimestamps":false,"Context":"Streaming","EnableSubtitlesInManifest":false,"MaxAudioChannels":"6","MinSegments":1,"SegmentLength":3,"BreakOnNonKeyFrames":true},{"Container":"ts","Type":"Audio","AudioCodec":"aac","Protocol":"hls","EstimateContentLength":false,"EnableMpegtsM2TsMode":false,"TranscodeSeekInfo":"Auto","CopyTimestamps":false,"Context":"Streaming","EnableSubtitlesInManifest":false,"MinSegments":1,"SegmentLength":3,"BreakOnNonKeyFrames":true},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Protocol":"http","EstimateContentLength":false,"EnableMpegtsM2TsMode":false,"TranscodeSeekInfo":"Auto","CopyTimestamps":false,"Context":"Streaming","EnableSubtitlesInManifest":false,"MinSegments":0,"SegmentLength":0,"BreakOnNonKeyFrames":false}],"ContainerProfiles":[],"CodecProfiles":[],"ResponseProfiles":[],"SubtitleProfiles":[{"Format":"srt","Method":"External"},{"Format":"ssa","Method":"External"},{"Format":"ass","Method":"External"},{"Format":"srt","Method":"Embed"},{"Format":"subrip","Method":"Embed"},{"Format":"ass","Method":"Embed"},{"Format":"ssa","Method":"Embed"},{"Format":"dvb_teletext","Method":"Embed"},{"Format":"dvb_subtitle","Method":"Embed"},{"Format":"dvbsub","Method":"Embed"},{"Format":"pgs","Method":"Embed"},{"Format":"pgssub","Method":"Embed"},{"Format":"dvdsub","Method":"Embed"},{"Format":"vtt","Method":"Embed"},{"Format":"sub","Method":"Embed"},{"Format":"idx","Method":"Embed"},{"Format":"smi","Method":"Embed"}]},"EnableDirectPlay":true,"EnableDirectStream":true,"EnableTranscoding":true,"AllowVideoStreamCopy":true,"AllowAudioStreamCopy":true,"IsPlayback":false,"AutoOpenLiveStream":false,"DirectPlayProtocols":["Http"]} 
2018-12-13 04:36:17.876 Info App: User policy for xvicarious. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True 
2018-12-13 04:36:17.876 Info App: Profile: Unknown Profile, Path: /media/sonarr-is-bad/Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku o Ketsui Shimashitaâ€¤/Yuusha_ni_Narenakatta_Ore_wa_Shibushibu_Shuushoku_o_Ketsui_Shimashita_10_fc1a0baf.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-13 04:36:17.876 Info App: Profile: Unknown Profile, Path: /media/sonarr-is-bad/Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku o Ketsui Shimashitaâ€¤/Yuusha_ni_Narenakatta_Ore_wa_Shibushibu_Shuushoku_o_Ketsui_Shimashita_10_fc1a0baf.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-13 04:36:17.876 Info App: Profile: Unknown Profile, Path: /media/sonarr-is-bad/Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku o Ketsui Shimashitaâ€¤/Yuusha_ni_Narenakatta_Ore_wa_Shibushibu_Shuushoku_o_Ketsui_Shimashita_10_fc1a0baf.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-13 04:36:17.877 Info HttpServer: HTTP Response 200 to 192.168.0.3. Time: 4ms. http://192.168.0.32:8096/emby/Items/ca695b5cce247a5bf94987e10f3077b4/PlaybackInfo?UserId=d496eef0621e44d29ad0e967aaf095e7&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=509090909
```

**Comment by BnMcG** [comment]
#145 - Probably blocked on this issue.

**Comment by joshuaboniface** [comment]
Confirmed, fails in two different ways for me:

On a clean install when loading the media page I get:

```
2018-12-15 16:44:17.413 Info HttpServer: HTTP GET http://test5:8096/emby/Items/b7cb1491c4b60ee68fa0a4f8cf9df41f/ThemeMedia?UserId=f152b319f41544b0b179e3c9650baa0e&InheritFromParent=true&EnableThemeSongs=true&EnableThemeVideos=false. UserAgent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G930W8 Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36
2018-12-15 16:44:17.415 Info HttpServer: HTTP Response 200 to 10.X.X.X. Time: 1ms. http://test5:8096/emby/Items/b7cb1491c4b60ee68fa0a4f8cf9df41f/ThemeMedia?UserId=f152b319f41544b0b179e3c9650baa0e&InheritFromParent=true&EnableThemeSongs=true&EnableThemeVideos=false
2018-12-15 16:44:17.429 Info HttpServer: HTTP POST http://test5:8096/emby/Items/b7cb1491c4b60ee68fa0a4f8cf9df41f/PlaybackInfo?UserId=f152b319f41544b0b179e3c9650baa0e&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=430769231. UserAgent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G930W8 Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36
2018-12-15 16:44:17.433 Info App: User policy for jellyfin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2018-12-15 16:44:17.433 Info App: Profile: Unknown Profile, Path: /srv/media/Avatar.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-15 16:44:17.433 Info App: Profile: Unknown Profile, Path: /srv/media/Avatar.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-15 16:44:17.434 Info App: Profile: Unknown Profile, Path: /srv/media/Avatar.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
2018-12-15 16:44:17.434 Info HttpServer: HTTP Response 200 to 10.X.X.X. Time: 5ms. http://test5:8096/emby/Items/b7cb1491c4b60ee68fa0a4f8cf9df41f/PlaybackInfo?UserId=f152b319f41544b0b179e3c9650baa0e&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=430769231
2018-12-15 16:44:19.346 Error HttpServer: Error in SharpWebSocket: An exception has occurred while receiving a message.. Exception.Message: The header part of a frame cannot be read from the data source.
```

And sometimes I get this when I press the greyed-out play button; I get this sort of message every time on my Emby 3.4.1 -> Jellyfin server too:

```
018-12-15 16:48:50.107 Info HttpServer: HTTP GET http://10.Y.Y.Y:8096/emby/Playback/BitrateTest?Size=500000. UserAgent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G930W8 Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36                                                                               
2018-12-15 16:48:50.110 Error HttpServer: Error processing request                                                                                              
        *** Error Report ***                                                                                                                                                                                                                  
        Version: 3.5.2.0                             
        Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh
        Operating system: Unix 4.9.0.8                                                                                                                          
        64-Bit OS: True                                                                                                                                                                                                                        
        64-Bit Process: True                                                                                                
        User Interactive: True                                                                                                                                                                                                                 
        Processor count: 6                                                                                              
        Program data path: /var/lib/jellyfin                                                                                                                                                                                                  
        Application directory: /usr/lib/jellyfin/bin                                                                          
        System.NullReferenceException: Object reference not set to an instance of an object.                                                                                                                                         
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetHttpResult(IRequest requestContext, Byte[] content, String contentType, Boolean addCachePrevention, IDictionary`2 responseHeaders) in /repo/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 119                                                                                                                                                                                                
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92 
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96                                                                                                                                         
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660                                                                                                                                                                   
        System.NullReferenceException                                                                                                                                                                                                          
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetHttpResult(IRequest requestContext, Byte[] content, String contentType, Boolean addCachePrevention, IDictionary`2 responseHeaders) in /repo/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 119                                                                                                                                                                                                    
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179                            
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96                                                                                                                                                                                       
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660                                                                                                                                                                                                                 
      
2018-12-15 16:48:50.110 Info HttpServer: HTTP Response 500 to 10.X.X.X. Time: 3ms. http://10.Y.Y.Y:8096/emby/Playback/BitrateTest?Size=500000                                                                                           
```

**Comment by joshuaboniface** [comment]
#238 appears to fix this.
