### ISSUE TITLE
Play audio to any DLNA client completely broken in 10.3.x

### ISSUE THREAD

**Issue by nonplusnl** [jellyfin/jellyfin#1456]
Play audio to any DLNA client completely broken on 10.3.x

**To Reproduce**
1. Select DLNA playback client in Jellyfin webinterface
2. Select song and press play
3. Nothing happens - no audio, no playback info on webinterface.

**Expected behavior**
3. Song starts playing via DLNA client; Jellyfin webinterface shows playback info on-screen. 
**In fact, downgrading to 10.2.2 restores everything to normal.**

**Logs**
The below appears to be what is wrong:

[2019-06-10 15:31:15.739 +02:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: baseUrl
   at MediaBrowser.Model.Dlna.StreamInfo.ToUrl(String baseUrl, String accessToken)
   at Emby.Dlna.PlayTo.PlayToController.CreatePlaylistItem(BaseItem item, User user, Int64 startPostionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**System (please complete the following information):**
 - Ubuntu 18.04
 - Browser: Chrome
 - Jellyfin Version: 10.3.5
 - Reverse proxy: yes, Apache2

**Additional context**
* As said, downgrading to 10.2.2 "solves" the issue
* Appears related to #1246 (which also started with 10.3.x, and was no problem in 10.2.x)
* Have not tested video. My DLNA clients are an Onkyo receiver (audio only), and two locally hosted MPD instances with an UpMpdCli DLNA "head" (audio only too).

**Comment by 97carmine** [comment]
Same bug from the Android app.

https://github.com/jellyfin/jellyfin-android/issues/148

**Comment by nonplusnl** [comment]
Solved by #1464
