### ISSUE TITLE
Error in ffprobe

### ISSUE THREAD

**Issue by superwg1984** [jellyfin/jellyfin#1459]
```
[17:00:58] [INF] MovieDbProvider: Finding id for item: [DYGC.ORG]芳华
[17:00:58] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&language=zh
[17:00:59] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&language=en
[17:01:00] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E&language=zh
[17:01:02] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E&language=en
[17:01:03] [INF] HttpClientManager GET: https://www.omdbapi.com?apikey=2c9d9507&plot=full&r=json&t=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&type=movie
[17:01:04] [INF] Skipping image extraction due to missing DefaultVideoStreamIndex for /srv/dev-disk-by-label-data-2T/media/movie/芳华.Youth.2017.4K&1080P.WEB-DL.X265&X264.AAC.Mnadarin.CHS&ENG-DYGC/[DYGC.ORG]芳华 1080P.mp4.
[17:01:04] [ERR] Error in ffprobe
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[17:01:04] [INF] MovieDbProvider: Finding id for item: [DYGC.ORG]芳华
[17:01:04] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&language=zh
[17:01:05] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&language=en
[17:01:05] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E&language=zh
[17:01:06] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E&language=en
[17:01:07] [INF] HttpClientManager GET: https://www.omdbapi.com?apikey=2c9d9507&plot=full&r=json&t=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E&type=movie
[17:01:08] [INF] Skipping image extraction due to missing DefaultVideoStreamIndex for /srv/dev-disk-by-label-data-2T/media/movie/芳华.Youth.2017.4K&1080P.WEB-DL.X265&X264.AAC.Mnadarin.CHS&ENG-DYGC/[DYGC.ORG]芳华 1080P H265.mp4.
[17:01:08] [ERR] Error in ffprobe
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[17:01:08] [INF] MovieDbProvider: Finding id for item: [DYGC.ORG]芳华 4K
[17:01:08] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E+4K&language=zh
[17:01:09] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E+4K&language=en
[17:01:10] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E+4K&language=zh
[17:01:11] [INF] HttpClientManager GET: https://api.themoviedb.org/3/search/movie?api_key=4219e299c89411838049ab0dab19ebd5&query=%5BDYGC+ORG%5D%E8%8A%B3%E5%8D%8E+4K&language=en
[17:01:12] [INF] HttpClientManager GET: https://www.omdbapi.com?apikey=2c9d9507&plot=full&r=json&t=%5BDYGC.ORG%5D%E8%8A%B3%E5%8D%8E+4K&type=movie
[17:01:13] [INF] Skipping image extraction due to missing DefaultVideoStreamIndex for /srv/dev-disk-by-label-data-2T/media/movie/芳华.Youth.2017.4K&1080P.WEB-DL.X265&X264.AAC.Mnadarin.CHS&ENG-DYGC/[DYGC.ORG]芳华 4K.mp4.
[17:01:13] [ERR] Error in ffprobe
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[17:01:13] [INF] MovieDbProvider: Finding id for item: [DYGC.ORG]芳华 4K H265

```

**Comment by cvium** [comment]
Please don't ignore the issue template.

Are you sure ffprobe is installed and the path is configured in Jellyfin? My guess is that it isn't.

**Comment by sparky8251** [comment]
Are you still experiencing this issue? If so, can you edit the report to follow the template so we can better help? Thanks!
