### ISSUE TITLE
ASS Subtitles error

### ISSUE THREAD

**Issue by Amaery** [jellyfin/jellyfin#1466]
**Describe the bug**
So i have a video which i try to run, and it works fine, but the moment i turn on subtitles, i get this error. Also the video will not play until i disable the subtitles. Not sure if its something to do with the app or just me adding the subtitles incorrectly in the first place. 
The subtitles are .ASS format
Not even sure if its a bug or simply incompetence. 
Thanks for any help on this.

**Logs**
```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam(EncodingJobInfo state)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetOutputSizeParam(EncodingJobInfo state, EncodingOptions options, String outputVideoCodec, Boolean allowTimeStampCopy)
   at MediaBrowser.Api.Playback.Hls.DynamicHlsService.GetVideoArguments(StreamState state, EncodingOptions encodingOptions)
   at MediaBrowser.Api.Playback.Hls.DynamicHlsService.GetCommandLineArguments(String outputPath, EncodingOptions encodingOptions, StreamState state, Boolean isEncoding)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Hls.DynamicHlsService.GetMasterPlaylistInternal(StreamRequest request, String method)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 76.0.3809.25 beta
 - Jellyfin Version: 10.3.5

**Comment by Amaery** [comment]
It seems to have resolved itself after a while.

**Comment by erikfdev** [comment]
I think the problem is still valid.
I have it with an AVI file and corresponfding SRT file that is to be sent to a Sony BRAVIA KDL-40EX520 via DLNA.
Transcoding is required (subtiles to be included as separate track in video file).

Although I have it with Jellyfin version 10.2.2.0, it could pinpoint the cause in the current master branch:
In method MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam() line 576:
 return string.Format("subtitles=filename='{0}'{1}{2}{3}",
the {3} is out of bounds since only 3 further arguments are given.

**Comment by 97carmine** [comment]
In my case the video does not play if you select subtitles in .ass format via DLNA and the Android TV application.

#1388
