### ISSUE TITLE
unicode broken filename

### ISSUE THREAD

**Issue by taking** [jellyfin/jellyfin#1469]
**Describe the bug**

The metadata scan does not work properly.
Requires utf8 support.
An error occurs for the entire file.

There was no problem in version 10.2.*

### Could not find a part of the path
[2019-06-17 16:14:40.476 +00:00] [ERR] **Error validating images for** "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E02.160329.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: **Could not find a part of the path** '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.

**To Reproduce**

Just Library Metadata Scan.
 -> require 'not english filename'
my filename is korean

**Expected behavior**

**Logs**

```
[2019-06-17 16:14:39.957 +00:00] [ERR] Error refreshing owned items for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2019-06-17 16:14:40.471 +00:00] [ERR] Error refreshing owned items for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2019-06-17 16:14:40.473 +00:00] [ERR] Error refreshing owned items for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 2"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 2'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2019-06-17 16:14:40.475 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E01.160328.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-06-17 16:14:40.475 +00:00] [ERR] Error in "FFProbeProvider".HasChanged
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.AddExternalSubtitleStreams(List`1 streams, String folder, String videoPath, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleStreams(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2019-06-17 16:14:40.476 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E02.160329.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-06-17 16:14:40.477 +00:00] [ERR] Error in "FFProbeProvider".HasChanged
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.AddExternalSubtitleStreams(List`1 streams, String folder, String videoPath, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleStreams(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2019-06-17 16:14:40.477 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E03.160404.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-06-17 16:14:40.478 +00:00] [ERR] Error in "FFProbeProvider".HasChanged
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.AddExternalSubtitleStreams(List`1 streams, String folder, String videoPath, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleStreams(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2019-06-17 16:14:40.478 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E04.160405.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-06-17 16:14:40.479 +00:00] [ERR] Error in "FFProbeProvider".HasChanged
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.AddExternalSubtitleStreams(List`1 streams, String folder, String videoPath, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleStreams(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2019-06-17 16:14:40.479 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E05.160411.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-06-17 16:14:40.480 +00:00] [ERR] Error in "FFProbeProvider".HasChanged
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.AddExternalSubtitleStreams(List`1 streams, String folder, String videoPath, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleStreams(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.SubtitleResolver.GetExternalSubtitleFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2019-06-17 16:14:40.482 +00:00] [ERR] Error validating images for "/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1/동네변호사 조들호.S01E06.160412.HDTV.720p.H264-SoYoU.mp4"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/GoogleMedia/[한국 드라마]/KBS2/동네변호사 조들호 (My Lawyer, Mr. Joe)/Season 1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

**Screenshots**

**System (please complete the following information):**
 - OS:  CentOS 7
 - Browser: 
 - Jellyfin Version: 10.3.5
 - Reverse proxy: nginx

**Additional context**

**Comment by JustAMan** [comment]
@taking is this still happening in 10.4.0 release?

**Comment by taking** [comment]
@JustAMan
Sorry.  I'm not currently using jellyfin..

**Comment by jarkad** [comment]
Still happens on 10.7.7.

```
[2022-01-09 22:49:22.790 +02:00] [ERR] [20] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/home/u/movies/config/jellyfin/root/default/Ð¤Ð¸Ð»ÑŒÐ¼Ñ‹"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/u/movies/config/jellyfin/root/default/Ð¤Ð¸Ð»ÑŒÐ¼Ñ‹'.
```
