### ISSUE TITLE
SRT Subtitles error

### ISSUE THREAD

**Issue by erikfdev** [jellyfin/jellyfin#1472]
Although issue #1466 is closed, I think the problem is still valid today.
I have it with an AVI file and corresponfding SRT file that is to be sent to a Sony BRAVIA KDL-40EX520 via DLNA.
Transcoding is required (subtiles to be included as separate track in video file).

```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam(EncodingJobInfo state)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetOutputSizeParam(EncodingJobInfo state, EncodingOptions options, String outputVideoCodec, Boolean allowTimeStampCopy)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoArguments(EncodingJobInfo state, EncodingOptions encodingOptions, String videoCodec, String defaultH264Preset)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetProgressiveVideoFullCommandLine(EncodingJobInfo state, EncodingOptions encodingOptions, String outputPath, String defaultH264Preset)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Although I have it with Jellyfin version 10.2.2.0, it could pinpoint the cause in the current master branch:
In method MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam() line 576:
`return string.Format("subtitles=filename='{0}'{1}{2}{3}"`,
the {3} is out of bounds since only 3 further arguments are given.

**Comment by sparky8251** [comment]
Since you expressly say you have issues with JF 10.2.2, I would request you test on JF 10.3.5 before we can do anything for you.

Lots of things have changed since 10.2.2 and we will not be releasing a 10.2.3 to fix this issue under any circumstance. We will only be fixing issues in new versions, so if you could test and confirm this is still an issue on the latest that would be great!

**Comment by erikfdev** [comment]
I understand your point of view, but could you please check in method MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetTextSubtitleParam(), the following code fragment in the source of JF 10.3.5 (line 575):

                return string.Format("subtitles=filename='{0}'{1}{2}{3}",
                    _mediaEncoder.EscapeSubtitleFilterPath(subtitlePath),
                    charsetParam,
                    // fallbackFontParam,
                    setPtsParam);

In my humble opinion the format string '{0}'{1}{2}{3} has become invalid since the moment the parameter fallbackFontParam was commented out. This code will cause the exception when executed.

**Comment by sparky8251** [comment]
Hopefully it is as simple as removing that `{3}`, but since subtitles of other formats work I'm a bit skeptical.

Regardless, thanks for explaining the bit I missed in your original submission! Hopefully it is simple and the fix can be pushed fast.
