### ISSUE TITLE
Library Scan Error Resolving Path

### ISSUE THREAD

**Issue by trumblejoe** [jellyfin/jellyfin#1508]
**Describe the bug**
Unable to resolve Path while scanning media library. A single show is created but is empty of seasons/episodes. Re-running this will not create any further shows or add any additional progress to scanning a library.

**To Reproduce**
1. Add Media Library
2. Scan
3. See Scan end quickly, check library contents, see it is empty or has 1 empty shell of a tv show entry.
4. View Log for error

**Expected behavior**
Media library to be scanned in successfully without errors.

**Logs**
Small snippet here, repeated for each item in this directory.

```
[2019-07-04 11:26:14.453 -04:00] [WRN] HTTP Response 204 to "::1". Time (slow): 0:00:02.385266. "http://localhost:8096/emby/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=true&name=TV%20Shows"
[2019-07-04 11:26:14.462 -04:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2019-07-04 11:26:14.463 -04:00] [INF] Executing "Scan media library"
[2019-07-04 11:26:14.503 -04:00] [INF] Validating media library
[2019-07-04 11:26:15.479 -04:00] [ERR] Error resolving path "R:\Media\TV Shows\Caprica"
System.IO.FileNotFoundException: Could not find file 'R:\Media\TV Shows\Caprica'.
File name: 'R:\Media\TV Shows\Caprica'
   at System.IO.Enumeration.FileSystemEnumerator`1.GetData()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass82_0.<ResolveFileList>b__0(FileSystemMetadata f)
```

**System (please complete the following information):**
 - OS: Windows 7 64-bit.
 - Browser: Chrome
 - Jellyfin Version: 10.3.5, was not happening in 10.2

**Comment by tyhawk** [comment]
I'm having the same issue on my Jellyfin server on a small portion of my music directories.
```
[2019-09-24 10:07:02.376 +02:00] [ERR] Error resolving path "/media/Muziek/Albums/the Prodigy/1999 - The Dirtchamber Sessions, Volume One"
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c__DisplayClass6_0.<FileInfos>b__1(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.ShouldIncludeEntry(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass82_0.<ResolveFileList>b__0(FileSystemMetadata f)
```
**System:**
- OS: Ubuntu 18.04.3 (current patchlevel)
- Browser: Firefox 69.0.1 (64-bit)
- Jellyfin version: 10.3.7 (jellyfin/jellyfin docker image)
Every album with this error is not added to the library. Other folders in the same directory are scanned and indexed. Permissions on all folders are the same.

**Comment by Bond-009** [comment]
Both of these look like dotnet issues.

**Comment by tyhawk** [comment]
The issue has persisted, I'm still seeing it on 10.4.3 (docker image), but I think I figured out the cause:
```
ls -lah 1999\ -\ The\ Dirtchamber\ Sessions\ Volume\ One/                                                                                                                                   za 14 dec 2019 16:29:04 CET
total 119M
drwxr-xr-x 2 nobody users 4,0K 14 dec 16:27  ./
drwxr-xr-x 9 nobody users 4,0K 14 dec 16:11  ../
-rwxr-xr-x 1 nobody users  17M 14 dec 16:22 "01 Run-D.M.C. _ Rasmus _ Hardnoise _ The Chemical Brothers _ Ultramagnetic MC's _ Lightnin' Rod feat. Jalal _ Ultramagnetic MC's _ Time Zone - Section 1: Intro Beats _ Punk Shock _ Untitled _ Chemical Beats _ Kool Keith Housing Things _ Sport _ Give t.mp3"*
-rwxr-xr-x 1 nobody users  16M 14 dec 16:22 "02 Bomb the Bass _ Trouble Funk _ The Charlatans _ The Prodigy _ Jane's Addiction _ Tim Dog feat. KRS-One - Section 2: Bug Powder Dust _ Pump Me Up _ How High _ Poison _ Been Caught Stealing _ I Get Wrecked.mp3"*
-rwxr-xr-x 1 nobody users  14M 14 dec 16:22 '03 Babe Ruth _ The B-Boys _ The Chemical Brothers _ Word of Mouth - Section 3: The Mexican _ Rock the House _ The Best Part of Breaking Up _ King Kut.mp3'*
-rwxr-xr-x 1 nobody users  19M 14 dec 16:22 '04 DJ Mink _ The KLF _ Frankie Bones _ Frankie Bones _ Frankie Bones _ Meat Beat Manifesto _ Herbie Hancock _ The 45 King _ Propellerheads _ Beastie Boys - Section 4: Hey Can You Relate _ What Time Is Love _ Funky Acid Makossa _ Shafted Off _ And the.mp3'*
-rwxr-xr-x 1 nobody users  12M 14 dec 16:22 "05 Sex Pistols _ Fatboy Slim _ Medicine - Section 5: New York _ Punk to Funk _ I'm Sick.mp3"*
-rwxr-xr-x 1 nobody users  14M 14 dec 16:22 "06 D.ST _ J.V.C. F.O.R.C.E. _ Primal Scream _ Beastie Boys _ Barry White _ Public Enemy _ The J.B.'s _ T La Rock - Section 6: The Home of Hip-Hop _ Strong Island _ Kowalski _ Time to Get Ill _ I'm Gonna Love You a Little More Baby _ Public Enemy Numbe.mp3"*
-rwxr-xr-x 1 nobody users 9,3M 14 dec 16:22 '07 LL Cool J _ Digital Underground _ Uptown _ Coldcut - Section 7: Get Down _ Humpty Dance _ Dope On Plastic _ Beats and Pieces.mp3'*
-rwxr-xr-x 1 nobody users  20M 14 dec 16:22 "08 London Funk Allstars _ West Street Mob _ Hijack _ Renegade Soundwave _ The Beginning of the End _ The Jimmy Castor Bunch - Section 8: Sure Shot _ Breakdance Electric Boogie _ Doomsday of Rap _ Ozone Breakdown _ Funky Nassau _ It's Just Begun.mp3"*
```
The length of the filenames seem to be an issue for the scraper. The other the albums that throw the same error also have at least one track with a very very long filename in the directory (Turn Up The Bass 8 and 9).

This fixed it for me:
```
-rwxr-xr-x  1 nobody users 8,6M 14 dec 16:32 '01 Tyree _ Technotronic _ Twenty 4 Seven _ F.P.I. Project _ Tony Scott _ Mister Mixi & Skinny Scotty _ Technotronic - Turn Up the Bass "The Mix": Turn Up the Bass _ Pump Up the Jam _ I Can'\''t Stand It _ Going Back to My Roots _ Get Into It _ I Can Hand.ogg'*
```
Renamed the track to:
```
-rwxr-xr-x  1 nobody users 8,6M 14 dec 16:32 '01 Turn Up The Bass The Mix - Various Artists.ogg'*
```
and the scraper didn't choke on it anymore.
