### ISSUE TITLE
You can not get EPG from an xml

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin#1525]
**Describe the bug**
Since version 10.3.6, EPG can not be obtained using an xml.

**Logs**
```
[2019-07-07 21:36:21.314 +02:00] [INF] xmltv path: "https://raw.githubusercontent.com/HelmerLuzo/TDTChannels_EPG/master/TDTChannels_EPG.xml"
[2019-07-07 21:36:21.315 +02:00] [ERR] Error adding metadata
System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Emby.XmlTv.Classes.XmlTvReader.GetChannels()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, List`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian Buster
 - Browser: Firefox
 - Jellyfin Version: 10.3.6
 - Reverse proxy: No

**Comment by Bond-009** [comment]
I'm 90% sure #1522 fixes this.

**Comment by 97carmine** [comment]
Fixed in 10.3.7 beta 1

**Comment by 0ddb0d** [comment]
This might also close #1135

**Comment by sparky8251** [comment]
10.3.7 is now out. Closing this issue.
