### ISSUE TITLE
10.3.6 Breaks Playback in MrMC 3.8.1

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin#1535]
**Describe the bug**
Playback breaks in MrMC 3.8.1 with JellyFin 10.3.6.  Works when downgrading JellyFin to 10.3.1

**To Reproduce**

1. Log into JellyFin with MrMC using Emby login method
2. Playback media item

**Expected behavior**
Expect media item to playback as it does with JellyFin 10.3.1

**Logs**

```
[2019-07-13 17:58:22.793 +00:00] [ERR] Error processing request
System.FormatException: The format of value '<null>' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.AddRequestHeaders(HttpRequestMessage request, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.GetRequestMessage(HttpRequestOptions options, HttpMethod method)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.GetStaticRemoteStreamResult(StreamState state, Dictionary`2 responseHeaders, Boolean isHeadRequest, CancellationTokenSource cancellationTokenSource)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-07-13 17:58:22.942 +00:00] [INF] Playback stopped reported by app "MrMC" "3.8-1" playing "'Twas the Night Before Christmas". Stopped at "0" ms
```

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
Docker 
 - Browser: [e.g. Firefox, Chrome, Safari]
MrMC 3.8-1
 - Jellyfin Version: [e.g. 10.0.1]
10.3.6
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
No

**Additional context**

**Comment by joshuaboniface** [comment]
Just to be clear, did this work in 10.3.5? 10.3.1 to 10.3.6 was a big jump with many bugfixes between the versions.

**Comment by ddurdle** [comment]
I only made the jump up from 10.3.1.  I'll try 10.3.5 today.  After reading about all the issues in 10.3.6, here in the issue log, I assumed it might be tied with that change that broke a lot of stuff in 10.3.6.

**Comment by anthonylavado** [comment]
I just tested against the released 10.3.6, and all media types are working for me. This is using MrMC 3.8.1 on iOS.

What platform are you using @ddurdle?

**Comment by ddurdle** [comment]
Still broken in 10.3.7.

**Comment by ddurdle** [comment]
My MrMC is 3.9

**Comment by ddurdle** [comment]
Using docker containers

**Comment by anthonylavado** [comment]
I’ll have to try a STRM file because everything is working for me with 3.9 and 10.3.7. I’ve even signed out and in again to be sure.

And you’re using this locally?

**Comment by ddurdle** [comment]
Maybe I can give you access to my test server.  I do have to rebuild it since downgrading from 10.3.7 back to 10.3.1 seemed to break it.  I'm planning to rebuild today.

This is what I did as a test.  On 10.3.1, I did a playback test of some random STRM files loaded in the library on chrome PC + chrome mobile (on ios) which worked.  I then did a test using MrMC with "manual emby signon" method.  On both 3.8.1 and 3.9.0, I was able to playback random STRM files.

I then did a docker upgrade to 10.3.7.   chrome PC + chrome mobile (on ios) continued to work.  But when I tested the same STRM files on MrMC, I got a playback error.  

I'm using the official docker running on a Debian server.

**Comment by ddurdle** [comment]
[2019-09-07 19:10:59.454 +00:00] [ERR] Error processing request
System.FormatException: The format of value '<null>' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.AddRequestHeaders(HttpRequestMessage request, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.GetRequestMessage(HttpRequestOptions options, HttpMethod method)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.GetStaticRemoteStreamResult(StreamState state, Dictionary`2 responseHeaders, Boolean isHeadRequest, CancellationTokenSource cancellationTokenSource)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-09-07 19:10:59.709 +00:00] [INF] Playback stopped reported by app "MrMC" "3.9-0" playing "Tusk". Stopped at "0" ms

**Comment by anthonylavado** [comment]
Thanks for the steps. I don't have any STRM files right now, but I'll work on getting some to test with. If you did want to point me in the right direction, you can reach me directly through apps@jellyfin.org, or my e-mail on my profile.

**Comment by ddurdle** [comment]
I sent some sample STRM files to your email.

**Comment by anthonylavado** [comment]
Possible fix in #1723.

**Comment by ddurdle** [comment]
It'll be in the next nightly build?

**Comment by anthonylavado** [comment]
>It'll be in the next nightly build?

@ddurdle correct. I tested it and it’s good.

**Comment by ddurdle** [comment]
tried in the latest nightly and works.  Can be closed.
