### ISSUE TITLE
Help? Erro, no starting on 8096

### ISSUE THREAD

**Issue by PlayxPE** [jellyfin/jellyfin#1548]
**Describe the bug**
No speak good english , read log 
**To Reproduce**
*Logs*
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-54-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Jul 18 06:33:37 CEST 2019

  System load:  0.08               Processes:              97
  Usage of /:   29.0% of 18.18GB   Users logged in:        0
  Memory usage: 23%                IP address for eth0:      Swap usage:   0%                 IP address for docker0: 172.17.0.1

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

155 packages can be updated.
1 update is a security update.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Thu Jul 18 06:09:13 2019 from 189.110.212.16
root@AWI-252123:~# sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
root@AWI-252123:~# sudo apt update
Hit:1 http://it.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease
Hit:3 http://it.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://it.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
154 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@AWI-242123:~# sudo apt install at libsqlite3-0 libfontconfig1 libfreetype6 libssl1.0.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
at is already the newest version (3.1.20-3.1ubuntu2).
libfontconfig1 is already the newest version (2.12.6-0ubuntu2).
libfreetype6 is already the newest version (2.8.1-2ubuntu2).
libsqlite3-0 is already the newest version (3.22.0-1ubuntu0.1).
libssl1.0.0 is already the newest version (1.0.2n-1ubuntu5.3).
0 upgraded, 0 newly installed, 0 to remove and 154 not upgraded.
root@AWI-242123:~# sudo dpkg -i jellyfin_10.3.7-1_ubuntu-amd64.deb jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb
dpkg: error: cannot access archive 'jellyfin_10.3.7-1_ubuntu-amd64.deb': No such file or directory
root@AWI-242123:~# sudo dpkg -i jellyfin_10.3.7-1_amd64.deb jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb
(Reading database ... 85%
(Reading database ... 130049 files and directories currently installed.)Preparing to unpack jellyfin_10.3.7-1_amd64.deb ...
Stopping Jellyfin!
Unpacking jellyfin (10.3.7-1) over (10.3.7-1) ...

Preparing to unpack jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb ...
Unpacking jellyfin-ffmpeg (4.0.4-2-bionic) over (4.0.4-2-bionic) ...
Setting up jellyfin-ffmpeg (4.0.4-2-bionic) ...
Setting up jellyfin (10.3.7-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.19) ...
root@AWI-242123:~#
root@AWI-242123:~#
root@AWI-242123:~# jellyfin
[06:37:18] [INF] Jellyfin version: 10.3.7.0
[06:37:18] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[06:37:18] [INF] Operating system: Linux 4.15.0.54
[06:37:18] [INF] Architecture: X64
[06:37:18] [INF] 64-Bit Process: True
[06:37:18] [INF] User Interactive: True
[06:37:18] [INF] Processor count: 1
[06:37:18] [INF] Program data path: /root/.local/share/jellyfin
[06:37:18] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web/src                                            
[06:37:18] [INF] Application directory: /usr/lib/jellyfin/bin/
[06:37:19] [INF] Setting cache path to /root/.cache/jellyfin
[06:37:19] [INF] Loading assemblies
[06:37:19] [INF] Sqlite version: 3.26.0
[06:37:19] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[06:37:19] [INF] Default journal_mode for /root/.local/share/jellyfin/data/users.db is wal                             
[06:37:19] [INF] PRAGMA synchronous=1
[06:37:19] [INF] Default journal_mode for /root/.local/share/jellyfin/data/authentication.db is wal                    
[06:37:19] [INF] PRAGMA synchronous=1
s[06:37:19] [INF] Default journal_mode for /root/.local/share/jellyfin/data/activitylog.db is wal                      
[06:37:19] [INF] PRAGMA synchronous=1
[06:37:19] [INF] Default journal_mode for /root/.local/share/jellyfin/data/displaypreferences.db is wal                
[06:37:19] [INF] PRAGMA synchronous=1
[06:37:19] [INF] Default journal_mode for /root/.local/share/jellyfin/data/library.db is wal                           
[06:37:19] [INF] PRAGMA synchronous=1
[06:37:19] [INF] Calling ServiceStack AppHost.Init
[06:37:20] [INF] Disposing CoreAppHost
[06:37:20] [INF] Disposing ActivityLogWebSocketListener
[06:37:20] [INF] Disposing SessionInfoWebSocketListener
[06:37:20] [INF] Disposing ScheduledTasksWebSocketListener
[06:37:20] [INF] Disposing SessionWebSocketListener
[06:37:20] [INF] Disposing EmbyTV
[06:37:20] [FTL] Unhandled Exception
System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)    
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)                         
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()                                
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()                                
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---                                           
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)                     
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)                
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)                    
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)                      
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)
start
Aborted (core dumped)
root@AWI-242123:~# sstart

Command 'sstart' not found, did you mean:

  command 'kstart' from deb kde-runtime
  command 'rstart' from deb x11-session-utils
  command 'sstat' from deb slurm-client

Try: apt install <deb name>

root@AWI-242123:~# jellyfin start app
[06:37:57] [INF] Jellyfin version: 10.3.7.0
[06:37:57] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "start", "app"]                                     
[06:37:58] [INF] Operating system: Linux 4.15.0.54
[06:37:58] [INF] Architecture: X64
[06:37:58] [INF] 64-Bit Process: True
[06:37:58] [INF] User Interactive: True
[06:37:58] [INF] Processor count: 1
[06:37:58] [INF] Program data path: /root/.local/share/jellyfin
[06:37:58] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web/src                                            
[06:37:58] [INF] Application directory: /usr/lib/jellyfin/bin/
[06:37:58] [INF] Setting cache path to /root/.cache/jellyfin
[06:37:58] [INF] Loading assemblies
[06:37:58] [INF] Sqlite version: 3.26.0
[06:37:58] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[06:37:58] [INF] Default journal_mode for /root/.local/share/jellyfin/data/users.db is wal                             
[06:37:58] [INF] PRAGMA synchronous=1
[06:37:58] [INF] Default journal_mode for /root/.local/share/jellyfin/data/authentication.db is wal                    
[06:37:58] [INF] PRAGMA synchronous=1
[06:37:58] [INF] Default journal_mode for /root/.local/share/jellyfin/data/activitylog.db is wal                       
[06:37:58] [INF] PRAGMA synchronous=1
[06:37:58] [INF] Default journal_mode for /root/.local/share/jellyfin/data/displaypreferences.db is wal                
[06:37:58] [INF] PRAGMA synchronous=1
[06:37:58] [INF] Default journal_mode for /root/.local/share/jellyfin/data/library.db is wal                           
[06:37:58] [INF] PRAGMA synchronous=1
[06:37:59] [INF] Calling ServiceStack AppHost.Init
[06:38:00] [INF] Disposing CoreAppHost
[06:38:00] [INF] Disposing ActivityLogWebSocketListener
[06:38:00] [INF] Disposing SessionInfoWebSocketListener
[06:38:00] [INF] Disposing ScheduledTasksWebSocketListener
[06:38:00] [INF] Disposing SessionWebSocketListener
[06:38:00] [INF] Disposing EmbyTV
[06:38:00] [FTL] Unhandled Exception
System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)    
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)                         
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()                                
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()                                
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---                                           
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)                     
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)                
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)                    
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)                      
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)
Aborted (core dumped)
root@AWI-242123:~# sudo dpkg -i jellyfin_10.3.7-1_amd64.deb jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb
(Reading database ... 130049 files and directories currently installed.)Preparing to unpack jellyfin_10.3.7-1_amd64.deb ...
Stopping Jellyfin!
Unpacking jellyfin (10.3.7-1) over (10.3.7-1) ...
Preparing to unpack jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb ...
Unpacking jellyfin-ffmpeg (4.0.4-2-bionic) over (4.0.4-2-bionic) ...
Setting up jellyfin-ffmpeg (4.0.4-2-bionic) ...
Setting up jellyfin (10.3.7-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.19) ...
root@AWI-242123:~# sudo dpkg -i jellyfin_10.3.7-1_amd64.deb
(Reading database ... 130049 files and directories currently installed.)Preparing to unpack jellyfin_10.3.7-1_amd64.deb ...
Stopping Jellyfin!

Unpacking jellyfin (10.3.7-1) over (10.3.7-1) ...
Setting up jellyfin (10.3.7-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.19) ...
root@AWI-242123:~#
root@AWI-242123:~# sudo service jellyfin status
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Thu 2019-07-18 06:40:04 CEST; 38s ago
 Main PID: 26710 (jellyfin)
    Tasks: 14 (limit: 1110)
   CGroup: /system.slice/jellyfin.service
           └─26710 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/res
Jul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.RedireJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.HttpClJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] Check for pJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] ExecuteQueulines 1-20/20 (END)...skipping...
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Thu 2019-07-18 06:40:04 CEST; 38s ago
 Main PID: 26710 (jellyfin)
    Tasks: 14 (limit: 1110)
   CGroup: /system.slice/jellyfin.service
           └─26710 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/res
Jul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.RedireJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.HttpClJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.ImplementaJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] Check for pJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] ExecuteQueu~
~
~
~
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Thu 2019-07-18 06:40:04 CEST; 38s ago
 Main PID: 26710 (jellyfin)
    Tasks: 14 (limit: 1110)
   CGroup: /system.slice/jellyfin.service
           └─26710 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpe
Jul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request,Jul 18 06:40:12 AWI-242123 jellyfin[26710]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CJul 18 06:40:12 AWI-242123 jellyfin[26710]:    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecutJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] Check for plugin updates Failed after 0 minute(s) and 0 seJul 18 06:40:12 AWI-242123 jellyfin[26710]: [06:40:12] [INF] ExecuteQueuedTasks
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-20/20 (END)

My system is
Linux ubuntu 18.4
10.3.7-4

**Comment by dkanada** [comment]
What languages do you know? Some of us are multilingual :) but it looks like the port is already in use. Do you also run Emby on the same machine?

**Comment by PlayxPE** [comment]
Hello, how are you? I speak Portuguese! How strange, I do not use it. but how can I basically solve it? thank you

**Comment by PlayxPE** [comment]
Hi, resolved! Thanks you
