### ISSUE TITLE
My H.264 videos always transcode unless forbidden

### ISSUE THREAD

**Issue by Ken-g6** [jellyfin/jellyfin#1611]
I'm a new user of Jellyfin 10.3.7.  I set my server up with a lot of H.264 files I had previously encoded for other video players.  These videos should play on all the devices I'm using without transcoding.  In fact, if I go to a user profile and disable "Allow audio playback that requires transcoding" and "Allow video playback that requires transcoding", these videos *do* play back - although restarting them in the right place can be an issue.  That should be a separate issue, assuming I've made no major setup mistakes here.

The issue here is that, if transcoding is allowed, all these H.264 files are always transcoded, apparently unnecessarily.

Here's a snippet of the Jellyfin log:
```
[2019-07-30 18:55:13.721 -06:00] [INF] WS "http://192.168.0.2:8096/embywebsocket?api_key=6e44e0fdadd04f05b987015423b23894&deviceId=f8d3f1861fb0a4f2". UserAgent: "Mozilla/5.0 (Linux; Android 7.1.1; Moto E (4) Build/NDQS26.69-64-11-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.143 Mobile Safari/537.36"
[2019-07-30 18:55:14.610 -06:00] [WRN] "GetItemList" query time (slow): 187.7288. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,ExternalServiceId,IsInMixedFolder,Tags,TrailerTypes,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,ShowId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where playbackPositionTicks > 0 AND IsVirtualItem=@IsVirtualItem AND MediaType=@MediaTypes AND TopParentId in ('002859a9da28afe0467dc245d45dd265','6388e40bcf8f537ed170232b7e0f37a8') Group by PresentationUniqueKey ORDER BY LastPlayedDate DESC LIMIT 12"
[2019-07-30 18:55:14.610 -06:00] [WRN] "GetItemList" query time (slow): 152.6061. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-07-30 18:55:14.610 -06:00] [WRN] "GetItemList" query time (slow): 147.2404. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-07-30 18:55:55.327 -06:00] [INF] User policy for "Ken". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-07-30 18:55:55.351 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:55.383 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:55.383 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.024 -06:00] [INF] User policy for "Ken". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-07-30 18:55:57.025 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.025 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.025 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.244 -06:00] [INF] Setting range response values for "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v". RangeRequest: "bytes=0-" Content-Length: "81", Content-Range: "bytes 0-80/81"
[2019-07-30 18:55:57.251 -06:00] [ERR] Error processing request
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (131072 of 81).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpResponse.TransmitFile(String path, Int64 offset, Int64 count, FileShareMode fileShareMode, IFileSystem fileSystem, IStreamHelper streamHelper, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.FileWriter.WriteToAsync(IResponse response, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-07-30 18:55:57.406 -06:00] [INF] User policy for "Ken". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-07-30 18:55:57.406 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.407 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.407 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.460 -06:00] [INF] User policy for "Ken". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-07-30 18:55:57.460 -06:00] [INF] Profile: "Unknown Profile", Path: "/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-07-30 18:55:57.652 -06:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:02:37.102 -f mov,mp4,m4a,3gp,3g2,mj2 -i file:"/var/lib/plexmediaserver/Library/TV Shows/Nature/Nature - s34e03 - Big Birds Canâ€™t Fly.m4v" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 20 -maxrate 139839815 -bufsize 279679630 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libmp3lame -ac 2 -ab 160185  -y "/var/lib/jellyfin/transcoding-temp/114ab57919455e7f7ec64f5f90f08f44.mkv"
```

Here's the mediainfo for that file.  Note that I recently re-tagged it with AtomicParsley.
```
General
Complete name                            : Nature - s34e03 - Big Birds Can’t Fly.m4v
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/avc1/mp41)
File size                                : 747 MiB
Duration                                 : 52 min 3 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 006 kb/s
Collection                               : Nature
Season                                   : 34
Part                                     : 3
Track name                               : Big Birds Can’t Fly
Encoded date                             : UTC 2017-06-19 20:41:52
Tagged date                              : UTC 2019-07-30 16:02:58
Writing application                      : HandBrake 1.0.4 2017040900

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.2
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 52 min 3 s
Bit rate                                 : 1 832 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 59.940 (60000/1001) FPS
Minimum frame rate                       : 59.920 FPS
Maximum frame rate                       : 59.960 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.033
Stream size                              : 682 MiB (91%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=1 / ref=5 / deblock=1:1:1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.20 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=1 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=600 / keyint_min=60 / scenecut=40 / intra_refresh=0 / rc_lookahead=120 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2017-06-19 20:41:52
Tagged date                              : UTC 2017-06-19 20:41:52
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 52 min 3 s
Bit rate mode                            : Variable
Bit rate                                 : 160 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 59.6 MiB (8%)
Title                                    : Stereo / Stereo
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2017-06-19 20:41:52
Tagged date                              : UTC 2017-06-19 20:41:52
```

I don't appear to have the exact encoding log for that file, but here's a similar one:
[nature-20170621-1859-8 2017-09-09 18-05-31.log](https://github.com/jellyfin/jellyfin/files/3487932/nature-20170621-1859-8.2017-09-09.18-05-31.log)

**Comment by EraYaN** [comment]
What does the server give as the reason for transcoding (in the dashboard)?

**Comment by Ken-g6** [comment]
Reason for transcoding: ContainerBitrateExceedsLimit

Hm, I don't remember setting a bitrate limit anywhere.  The value at Playback -> Streaming is empty.  But that only applies outside my LAN (192.168.*.*), right?  If it's reading that as "0" I'd call that a bug.

**Comment by Ken-g6** [comment]
I tried a couple more things.  I set LAN IP addresses to "127.0.0.1,192.168.255.255", just in case that wasn't picked up.  I found on an Android client that I could set the assumed network speed, so I set it to 10Mbps.  Neither change helped.

**Comment by barolo** [comment]
@Ken-g6 What are you using as client? browser, app? Pretty much all of them behave erroneously in some way. If you can, use kodi with jellyfin addon, which not only behaves best but also gives you more control over transcoding [ e.g. it can be forced off ]

**Comment by onny** [comment]
Hey,
Are you using the Jellyfin web client to stream the video? I guess that Chrome/Firefox won't be able to play this kind of video+audio codec natively so it is correct that the server starts the transcoding process.

**Comment by barolo** [comment]
@onny You can see that he is trying to play h264/aac which are supported by both, this issue been going around for some time already

**Comment by Ken-g6** [comment]
I am using the official Android client from the Play Store.  I have also been using the Fire TV Stick client, jellyfin-androidtv_amazon_0.9.0.apk.

"kodi with jellyfin addon" looks like it needs a full guide.  What parts go on which devices?

**Comment by barolo** [comment]
I can only help you with Android one, @Ken-g6 
Do you have any experience with Kodi? It's customizability might be overwhelming in the beginning.
[Here](https://jellyfin.readthedocs.io/en/latest/clients/#jellyfin-for-kodi) you have instructions how to install it. [ the addon, kodi e.g. from play store or their site ]

**Comment by ddurdle** [comment]
I have the opposite behaviour on the fire stick tv app from amazon store.  It never transcodes and nor provides an option to transcode.  Always plays direct even if my connection cannot handle the bitrate (which is 99% of the time).  The android mobile apps work fine -- there is a quality selector and allows to select a quality to force transcode.

**Comment by Ken-g6** [comment]
I guess I should bring this up again.  I recently tried turning off all conversion options.  That led to videos not playing at all.  The "Allow video playback that requires conversion without re-encoding" option has to be enabled to get my videos to play.  Which leads to another bug I need to link in here...
