### ISSUE TITLE
Live TV guide images not displaying

### ISSUE THREAD

**Issue by flowlee** [jellyfin/jellyfin#1621]
**Describe the bug**
Images from EPG guide data in XML format do not show up in the web interface or in the Android app. The same XML file works with other applications.

**To Reproduce**
1. Import guide data from any XML file.
2. Click on Live TV in the web interface.
3. See only empty image frames.

**Expected behavior**
Images for TV guide items should show up.

**Logs**
Relevant bits:
```
[2019-08-13 01:00:13.732 +02:00] [WRN] "GetItemList" query time (slow): 153.8962. Query: "select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,ProviderIds,Images,TotalBitrate,ExtraType,ExternalId,OwnerId from TypedBaseItems A where type=@type AND CleanName=@Name"
[2019-08-13 01:00:14.455 +02:00] [WRN] HTTP Response 200 to "62.47.204.56". Time (slow): 0:00:00.5179999. "http://jellyfin.mydomain.org/emby/Items/aa4266e3c4be719e4f3895541607bcab/Images/Primary?maxHeight=223&maxWidth=223&tag=33942d4bcab1b7c53e07ba83e41847e0&quality=90"
[2019-08-13 01:00:14.483 +02:00] [WRN] HTTP Response 200 to "62.47.204.56". Time (slow): 0:00:00.5470782. "http://jellyfin.mydomain.org/emby/Items/216bccaaee202804642c5bdd9136d80f/Images/Primary?maxHeight=223&maxWidth=223&tag=25b628708e845c1b90793aa0f6bef19f&quality=90"
[2019-08-13 01:00:14.505 +02:00] [WRN] HTTP Response 200 to "62.47.204.56". Time (slow): 0:00:00.5687331. "http://jellyfin.mydomain.org/emby/Items/ca429c554daea926949272416207fd62/Images/Primary?maxHeight=223&maxWidth=223&tag=9c4a4c0ac987a9da4ae92fac65d890ae&quality=90"
[2019-08-13 01:00:15.887 +02:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: mimeType
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8594405/62908463-76e5af00-bd78-11e9-83db-3ff50fe30838.png)

**System (please complete the following information):**
 - OS: Ubuntu Server 18.04.2, Docker Container
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.3.7
 - Reverse proxy: nginx

**Comment by dannymichel** [comment]
I have the same issue
