### ISSUE TITLE
exception in linux related to sqlite

### ISSUE THREAD

**Issue by a0x3e8** [jellyfin/jellyfin#1626]
**Describe the bug**
compiled on debian linux, jellyfin fails to run with exception related to sqlite

**To Reproduce**

1. ./build linux-x64 all
2. extract archive in ../bin/linux-x64
3. ./jellyfin

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: debian 10
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: 10.3.7
 - Reverse proxy: [e.g. no, nginx, apache, etc.]

**Additional context**
```
[01:33:48] [FTL] Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Aborted
```

**Comment by anthonylavado** [comment]
Hi @a0x3e8, we are working on this right now. See #1625

**Comment by anthonylavado** [comment]
While we're here, I should advise you that following the master branch is a bad idea if you want stable software here. The master is used as a dev branch, and only the tags/release are guaranteed to be stable.

**Comment by dkanada** [comment]
@anthonylavado to be fair we have a nightly now that follows the master branch, although the same rule applies to nightly builds.

**Comment by a0x3e8** [comment]
Thank you. stable branch is working without any problems.
