### ISSUE TITLE
System.Exception: Error starting ffmpeg

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#165]
I am using the Debian repo, Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux

My ffmpeg exists under /usr/bin

Video details

```
 ENCODER         : Lavf58.20.100
  Duration: 00:05:14.89, start: 0.000000, bitrate: 557 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      DURATION        : 00:05:14.833000000
    Stream #0:1(eng): Audio: aac (LC), 44100 Hz, stereo, fltp (default)

```

```

2018-12-14 19:16:19.324 Info App: /usr/bin/ffmpeg -ss 00:01:54.000 -f matroska,webm -i file:"/media/MEDIA/XXX.mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p -preset medium -crf 14 -maxrate   1673658 -bufsize 3347316 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:                      if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -      start_at_zero -segment_time 3 -segment_time_delta -114 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 38 -segment_list "/media/DRIVE/    TMP/.cache/transcoding-temp/1ad5f08264c4b0a93cd204334725d6d8.m3u8" -y "/media/SYSTEMP/TMP/.cache/transcoding-temp/1ad5f08264c4b0a93cd204334725d6d8%d.ts"
  2018-12-14 19:16:19.335 Info HttpServer: HTTP Response 200 to 192.168.5.113. Time: 306ms. http://192.168.1.10:8096/emby/videos/29eebbd0b818b60f6e424e22f1e33052/hls1/main/11.ts?             DeviceId=920f1034d16f848442cedb33a92fcdc6c36ca9c5&MediaSourceId=29eebbd0b818b60f6e424e22f1e33052&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=19200  0&PlaySessionId=a88aad6494fd4cbe8dfe3c49a15399f0&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=0aac46c1ad2bc21d0fe181e64af54683&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=T  rue&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
  2018-12-14 19:16:19.514 Error HttpServer: Error processing request
      *** Error Report ***
      Version: 3.5.2.0
      Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh
      Operating system: Unix 4.18.0.2
      64-Bit OS: True
      64-Bit Process: True
      User Interactive: True
      Processor count: 8
      Program data path: /var/lib/jellyfin
      Application directory: /usr/lib/jellyfin/bin
      System.Exception: Error starting ffmpeg


      at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource                       cancellationTokenSource, Boolean acquireResources)
         at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)
         at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:    line 114
         at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName,        CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
         at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken                     cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
      System.Exception
         at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource                       cancellationTokenSource, Boolean acquireResources)
         at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)
         at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:    line 114
         at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName,        CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
         at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken                     cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
  
  2018-12-14 19:16:19.514 Info HttpServer: HTTP Response 500 to 192.168.5.113. Time: 320ms. http://192.168.1.10:8096/emby/videos/29eebbd0b818b60f6e424e22f1e33052/hls1/main/38.ts?             DeviceId=920f1034d16f848442cedb33a92fcdc6c36ca9c5&MediaSourceId=29eebbd0b818b60f6e424e22f1e33052&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=19200  0&PlaySessionId=a88aad6494fd4cbe8dfe3c49a15399f0&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=0aac46c1ad2bc21d0fe181e64af54683&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=T  rue&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
  2018-12-14 19:16:35.298 Info HttpServer: HTTP POST http://192.168.1.10:8096/emby/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
  2018-12-14 19:16:35.304 Info HttpServer: HTTP Response 204 to 192.168.5.113. Time: 6ms. http://192.168.1.10:8096/emby/Sessions/Playing/Progress

```

**Comment by joshuaboniface** [comment]
Definitely check out the latest build first, since we replaced the binary blob that handled `ffmpeg` with new code, but if it still reoccurs please let us know.

**Comment by XeonDead** [comment]
ffmpeg does not like the segment_time_delta being a negative number.
Here is the same error I get: 
`[segment muxer @ 0x561d39a81bc0] Value -882.000000 for parameter 'segment_time_delta' out of range [0 - 9.22337e+12]`

**Comment by XeonDead** [comment]
Actually a solution - this issue is connected with ffmpeg 4.1+ but everything works great with ffmpeg 4.0.
This is also connected with issues #191 and #260 as those are mostly same.

**Comment by JustAMan** [comment]
@gerroon can you check if it reproduces on latest release and with `ffmpeg 4.0.3` from [John van Sickle](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.0.3-64bit-static.tar.xz)?

**Comment by anthonylavado** [comment]
Hello all,
Is this still an issue for you with the latest release of Jellyfin (10.2.2)?
