### ISSUE TITLE
Server Crash on Library scan

### ISSUE THREAD

**Issue by Gr3q** [jellyfin/jellyfin#1664]
**Describe the bug**
Jellyfin Server starts up, media Library Scan is triggered (by looking at the logs) then crashes with Exception (see logs)

**To Reproduce**
I don't really know, maybe there is a problem with my network?

**Expected behavior**
Does not crash. duh.

**Logs**
From startup to Exception (not too long)
```
[2019-08-23 19:06:31.750 +01:00] [INF] Jellyfin version: "10.3.7.0"
[2019-08-23 19:06:31.843 +01:00] [INF] Arguments: ["/usr/lib/jellyfin/jellyfin.dll", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin", ""]
[2019-08-23 19:06:31.878 +01:00] [INF] Operating system: "Linux" "4.19.66.1"
[2019-08-23 19:06:31.878 +01:00] [INF] Architecture: Arm
[2019-08-23 19:06:31.888 +01:00] [INF] 64-Bit Process: False
[2019-08-23 19:06:31.888 +01:00] [INF] User Interactive: True
[2019-08-23 19:06:31.888 +01:00] [INF] Processor count: 4
[2019-08-23 19:06:31.889 +01:00] [INF] Program data path: "/var/lib/jellyfin"
[2019-08-23 19:06:31.890 +01:00] [INF] Web resources path: "/usr/lib/jellyfin/jellyfin-web/src"
[2019-08-23 19:06:31.890 +01:00] [INF] Application directory: "/usr/lib/jellyfin/"
[2019-08-23 19:06:32.489 +01:00] [INF] Setting cache path to /var/cache/jellyfin
[2019-08-23 19:06:32.592 +01:00] [INF] Loading assemblies
[2019-08-23 19:06:32.641 +01:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TMDb Box Sets/Jellyfin.Plugin.TMDbBoxSets.dll"
[2019-08-23 19:06:32.645 +01:00] [INF] Loaded assembly "Jellyfin.Plugin.Anime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Anime/Jellyfin.Plugin.Anime.dll"
[2019-08-23 19:06:32.958 +01:00] [INF] Sqlite version: 3.26.0
[2019-08-23 19:06:32.961 +01:00] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[2019-08-23 19:06:35.640 +01:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/users.db" is "wal"
[2019-08-23 19:06:35.656 +01:00] [INF] PRAGMA synchronous=1
[2019-08-23 19:06:36.223 +01:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/authentication.db" is "wal"
[2019-08-23 19:06:36.225 +01:00] [INF] PRAGMA synchronous=1
[2019-08-23 19:06:36.254 +01:00] [ERR] Error loading cert from "/home/gr3q/agreguss.p12"
Interop+Crypto+OpenSslCryptographicException: error:2006D002:BIO routines:BIO_new_file:system lib
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Emby.Server.Implementations.ApplicationHost.GetCertificate(CertificateInfo info) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/ApplicationHost.cs:line 964
[2019-08-23 19:06:36.428 +01:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/activitylog.db" is "wal"
[2019-08-23 19:06:36.430 +01:00] [INF] PRAGMA synchronous=1
[2019-08-23 19:06:36.438 +01:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/displaypreferences.db" is "wal"
[2019-08-23 19:06:36.439 +01:00] [INF] PRAGMA synchronous=1
[2019-08-23 19:06:36.744 +01:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/library.db" is "wal"
[2019-08-23 19:06:53.448 +01:00] [INF] PRAGMA synchronous=1
[2019-08-23 19:06:53.838 +01:00] [INF] Calling ServiceStack AppHost.Init
[2019-08-23 19:06:56.736 +01:00] [INF] SkiaSharp version: 1.68.0.0
[2019-08-23 19:06:56.752 +01:00] [INF] Running startup tasks
[2019-08-23 19:06:56.869 +01:00] [INF] Daily trigger for "Chapter image extraction" set to fire at 08/24/2019 02:00, which is 6:53:03.1307472 from now.
[2019-08-23 19:06:57.065 +01:00] [INF] FFmpeg validation: Found ffmpeg version "unknown"
[2019-08-23 19:06:57.066 +01:00] [WRN] FFmpeg validation: We recommend ffmpeg version "4.0"
[2019-08-23 19:06:57.066 +01:00] [WRN] FFmpeg: "Custom": Failed version check: "/usr/bin/ffmpeg"
[2019-08-23 19:06:57.097 +01:00] [INF] Validating media encoder at "/usr/bin/ffmpeg"
[2019-08-23 19:06:57.221 +01:00] [INF] Available "decoders": ["h264", "hevc", "mpeg2video", "aac", "ac3", "mp3"]
[2019-08-23 19:06:57.338 +01:00] [INF] Available "encoders": ["libx264", "h264_omx", "h264_vaapi", "libx265", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2019-08-23 19:06:57.338 +01:00] [INF] Encoder validation complete
[2019-08-23 19:06:57.341 +01:00] [INF] FFmpeg: "Custom": "/usr/bin/ffmpeg"
[2019-08-23 19:06:57.349 +01:00] [INF] ServerId: "0637bead2c2b4130b4519e8550feb3cc"
[2019-08-23 19:06:58.237 +01:00] [WRN] HTTP Response 503 to "192.168.0.100". Time (slow): 0:00:00.531722. "http://192.168.0.50:8096/web/index.html"
[2019-08-23 19:06:58.406 +01:00] [INF] Executed all pre-startup entry points in 0:00:00.9957126
[2019-08-23 19:06:58.406 +01:00] [INF] Core startup complete
[2019-08-23 19:06:58.762 +01:00] [ERR] HTTP request failed with message: ""
[2019-08-23 19:06:58.785 +01:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.0.50"
[2019-08-23 19:06:59.028 +01:00] [WRN] "GetItemList" query time (slow): 343.712. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-08-23 19:06:59.466 +01:00] [INF] Executed all post-startup entry points in 0:00:01.0594046
[2019-08-23 19:06:59.570 +01:00] [INF] Watching directory /HDD/Zene
[2019-08-23 19:06:59.573 +01:00] [INF] Watching directory /HDD/Sorozatok
[2019-08-23 19:06:59.861 +01:00] [INF] Watching directory /HDD/Filmek
[2019-08-23 19:06:59.899 +01:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2019-08-23 19:06:59.905 +01:00] [INF] Queueing task "PluginUpdateTask"
[2019-08-23 19:06:59.930 +01:00] [INF] Executing "Check for plugin updates"
[2019-08-23 19:07:01.430 +01:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 1 seconds
[2019-08-23 19:07:01.664 +01:00] [INF] ExecuteQueuedTasks
[2019-08-23 19:07:02.831 +01:00] [WRN] HTTP Response 200 to "192.168.0.100". Time (slow): 0:00:00.7134143. "http://192.168.0.50:8096/emby/System/Info"
[2019-08-23 19:07:02.913 +01:00] [INF] WS "http://192.168.0.50:8096/embywebsocket?api_key=d90d548824674825a36a92fd0689891a&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NTUyNDczOTY0NQ11". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[2019-08-23 19:07:03.385 +01:00] [WRN] HTTP Response 204 to "192.168.0.100". Time (slow): 0:00:00.5387865. "http://192.168.0.50:8096/emby/Sessions/Capabilities/Full"
[2019-08-23 19:07:18.318 +01:00] [INF] Deleting plugin directory "/var/lib/jellyfin/plugins/TMDb Box Sets"
[2019-08-23 19:07:18.322 +01:00] [INF] Saving system configuration
[2019-08-23 19:07:18.324 +01:00] [INF] Setting cache path to /var/cache/jellyfin
[2019-08-23 19:07:18.375 +01:00] [INF] App needs to be restarted.
[2019-08-23 19:07:56.883 +01:00] [INF] "IntervalTrigger" fired for task: "Scan media library"
[2019-08-23 19:07:56.885 +01:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2019-08-23 19:07:56.886 +01:00] [INF] Executing "Scan media library"
[2019-08-23 19:07:56.969 +01:00] [INF] Stopping directory watching for path "/HDD/Filmek"
[2019-08-23 19:07:56.974 +01:00] [INF] Stopping directory watching for path "/HDD/Zene"
[2019-08-23 19:07:56.975 +01:00] [INF] Stopping directory watching for path "/HDD/Sorozatok"
[2019-08-23 19:07:56.990 +01:00] [INF] Validating media library
[2019-08-23 19:08:00.198 +01:00] [WRN] "GetItemList" query time (slow): 130.7763. Query: "select type,data,EndDate,ChannelId,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-08-23 19:08:04.726 +01:00] [INF] WS "http://192.168.0.50:8096/embywebsocket?api_key=d90d548824674825a36a92fd0689891a&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NTUyNDczOTY0NQ11". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[2019-08-23 19:08:09.194 +01:00] [WRN] "GetItemList" query time (slow): 441.2461. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-08-23 19:08:10.243 +01:00] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**System (please complete the following information):**
 - OS: Arch Linux  - Raspberry Pi 4
 - Browser: N/A
 - Jellyfin Version: 10.3.7
 - Reverse proxy: No

**Additional context**
Server is running on Raspberry 4, with the jellyfin AUR package compiled from source.

**Comment by onny** [comment]
Hey,
for testing purpose could you please select a different media library folder for scanning and remove the old one?
Just to be sure that it does not crash because of specific media files.

Best regards,
Jonas

**Comment by Gr3q** [comment]
Ok, I've narrowed it down to my music folder

**Comment by onny** [comment]
@Gr3q That's really helpfull! Could you try to narrow it further down? So we could have the affecting file and try to better catch the error :)

**Comment by Gr3q** [comment]
I already moved the files out, I'll add them back folder by folder today to find the culprit

**Comment by petabyteboy** [comment]
https://github.com/jellyfin/jellyfin/issues/465

**Comment by Gr3q** [comment]
Here you go, first file I found what is causing a crash: ```Ágnes Vanilla - Óh Szív  Nyugodj .mp3```

- The file is added successfully to the library, and I can Scan the Music Library Individually with no problems _(Scan for new Files, Replace All metadata, Search For Missing Metadata working)_.
- I did not try to play the song.
- The Server Only crashes when I start a scan with "Scan All Libraries" button in Server->Libraries. _(or a Scan is triggered somehow in the background, guess its the same thing)_
- "Scan All Libraries" does not crash after the file is removed.

I guess I have more files what could make it crash, but I think this is enough to start pinpointing the bug. Tell me if you need the actual file, or to find more files crashing the server.

**Comment by Gr3q** [comment]
Sorry for the late reply.

> I feel like turning the support for this website off would be good. Can the OP see if this workarounds the issue?

Yes, it does. Tried it and the scan finished successfully

**Comment by mihawk90** [comment]
Can also confirm blocking theaudiodb makes it not crash anymore :ok_hand:

**Comment by mihawk90** [comment]
In 10.4.0 it doesn't crash anymore, though it does show a big stack trace when it's trying to get data from TheAudioDB

**Comment by JustAMan** [comment]
@Gr3q could you please re-check on 10.4.0 and report?

@mihawk90 is there an issue reported with that stack trace? If not, please create one :)

**Comment by Gr3q** [comment]
@JustAMan Yeah the server does not crash anymore, so that is good.

The above mentioned stack trace what is logged instead of the crash:
```
[2019-11-01 19:57:45.172 +00:00] [WRN] "GetItemList" query time (slow): 113.3502ms. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-11-01 19:57:46.424 +00:00] [WRN] "GetItemList" query time (slow): 13.3295ms. Query: "select type,data,EndDate,ChannelId,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-11-01 19:57:46.492 +00:00] [WRN] "GetItemList" query time (slow): 11.4583ms. Query: "select type,data,EndDate,ChannelId,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-11-01 19:57:47.353 +00:00] [WRN] "GetItemList" query time (slow): 18.0118ms. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId"
[2019-11-01 19:57:47.836 +00:00] [ERR] Error in "TheAudioDB"
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.4.0/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 265
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.4.0/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 171
   at MediaBrowser.Providers.Music.AudioDbAlbumProvider.DownloadInfo(String musicBrainzReleaseGroupId, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.4.0/MediaBrowser.Providers/Music/AudioDbAlbumProvider.cs:line 158
   at MediaBrowser.Providers.Music.AudioDbAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.4.0/MediaBrowser.Providers/Music/AudioDbAlbumProvider.cs:line 54
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

I think this is perfectly fine.

**Comment by JustAMan** [comment]
@Gr3q please ensure there is an open issue with above stacktrace (if there isn't one please create it), as this should eventually be fixed. I'm going to close this issue now as server is no longer crashing but properly logs the error.

**Comment by Gr3q** [comment]
I think there is one open for the actual root cause [here](https://github.com/jellyfin/jellyfin/issues/465) so I'm not going to open another one.

Thanks
