### ISSUE TITLE
Unable to authenticate into Jellyfin

### ISSUE THREAD

**Issue by pitah81** [jellyfin/jellyfin#1671]
Unable to login using the web interface. Devices already authenticated stays authenticated, however when signed out they're unable to login again. This happens both to web access and also the mobile app.

This is the entry in the log
`[23:37:49] [ERR] Error processing request
System.ArgumentException: Salt is not at least eight bytes.
Parameter name: salt
at System.Security.Cryptography.Rfc2898DeriveBytes..ctor(Byte[] password, Byte[] salt, Int32 iterations, HashAlgorithmName hashAlgorithm)
at Emby.Server.Implementations.Cryptography.CryptographyProvider.PBKDF2(String method, Byte[] bytes, Byte[] salt, Int32 iterations)
at Emby.Server.Implementations.Cryptography.CryptographyProvider.ComputeHash(PasswordHash hash)
at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.GetHashedString(User user, String str)
at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

![image](https://user-images.githubusercontent.com/1994575/63725703-71e62c80-c85b-11e9-8e62-37004df497a2.png)
"Connection failed. We were unable to establish connection to the selected server..."

Docker running jellyfin:latest on x86 server.
Any web browser
Latest Jellyfin (and also built from latest source, same problem)
Traefik reverse proxy

Can't tell for sure when this started. Noticed it when I got a new phone and was about to sign in to my Jellyfin instance and it failed.

**Comment by marius-luca-87** [comment]
I can reproduce the issue using a Visual Studio Debug build on Windows 10 1903.
Before starting the build I deleted the previous configuration in AppData Jellyfin folder.
After going through the setup wizard I am unable to login with the newly created user.
