### ISSUE TITLE
Can't get in the <IP>:8096

### ISSUE THREAD

**Issue by MuMu360121** [jellyfin/jellyfin#1679]
### First of all,I didn't install other media system.
Then, it can't get in because I have reinstall the jellyfin.
The OS is Ubuntu 18.04.

Type jellyfin in ssl ,it shows:
```
[18:43:07] [INF] Jellyfin version: 10.3.7.0
[18:43:08] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[18:43:08] [INF] Operating system: Linux 4.15.0.47
[18:43:08] [INF] Architecture: X64
[18:43:09] [INF] 64-Bit Process: True
[18:43:09] [INF] User Interactive: True
[18:43:09] [INF] Processor count: 1
[18:43:09] [INF] Program data path: /root/.local/share/jellyfin
[18:43:09] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web/src
[18:43:09] [INF] Application directory: /usr/lib/jellyfin/bin/
[18:43:09] [INF] Setting cache path to /root/.cache/jellyfin
[18:43:09] [INF] Loading assemblies
[18:43:10] [INF] Sqlite version: 3.26.0
[18:43:10] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FO                                                                                                             REIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS                                                                                                             5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[18:43:11] [INF] Default journal_mode for /root/.local/share/jellyfin/data/users                                                                                                             .db is delete
[18:43:11] [INF] PRAGMA synchronous=1
[18:43:11] [INF] Default journal_mode for /root/.local/share/jellyfin/data/authe                                                                                                             ntication.db is delete
[18:43:11] [INF] PRAGMA synchronous=1
[18:43:11] [INF] Default journal_mode for /root/.local/share/jellyfin/data/activ                                                                                                             itylog.db is delete
[18:43:11] [INF] PRAGMA synchronous=1
[18:43:11] [INF] Default journal_mode for /root/.local/share/jellyfin/data/displ                                                                                                             aypreferences.db is delete
[18:43:11] [INF] PRAGMA synchronous=1
[18:43:13] [INF] Default journal_mode for /root/.local/share/jellyfin/data/libra                                                                                                             ry.db is delete
[18:43:13] [INF] PRAGMA synchronous=1
[18:43:13] [INF] Saving system configuration
[18:43:13] [INF] Setting cache path to /root/.cache/jellyfin
[18:43:14] [INF] Calling ServiceStack AppHost.Init
[18:43:21] [INF] Disposing CoreAppHost
[18:43:21] [INF] Disposing ActivityLogWebSocketListener
[18:43:21] [INF] Disposing SessionInfoWebSocketListener
[18:43:21] [INF] Disposing ScheduledTasksWebSocketListener
[18:43:21] [INF] Disposing SessionWebSocketListener
[18:43:21] [INF] Disposing EmbyTV
[18:43:21] [FTL] Unhandled Exception
System.IO.IOException: Failed to bind to address http://[::]:8096: address alrea                                                                                                             dy in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address                                                                                                              already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(So                                                                                                             cketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress                                                                                                              socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.Bind                                                                                                             Async()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.Bind                                                                                                             Async()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21                                                                                                             _0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpoi                                                                                                             ntAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpoi                                                                                                             ntAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBi                                                                                                             ndContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(Addr                                                                                                             essBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsS                                                                                                             trategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(                                                                                                             IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger l                                                                                                             ogger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext                                                                                                             ](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken                                                                                                              cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection s                                                                                                             erviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: System.IO.IOException: Failed to bind to address http://[::                                                                                                             ]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInU                                                                                                             seException: Address already in use ---> System.Net.Sockets.SocketException: Add                                                                                                             ress already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(So                                                                                                             cketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress                                                                                                              socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.Bind                                                                                                             Async()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.Bind                                                                                                             Async()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21                                                                                                             _0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpoi                                                                                                             ntAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpoi                                                                                                             ntAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBi                                                                                                             ndContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(Addr                                                                                                             essBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsS                                                                                                             trategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(                                                                                                             IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger l                                                                                                             ogger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext                                                                                                             ](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken                                                                                                              cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection s                                                                                                             erviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.Main(String[] args)
   at Jellyfin.Server.Program.<Main>(String[] args)
Aborted (core dumped)
```
To scan the port 8096 ,it shows:
`root@ONEVPS190826191334:~# netstat -ap | grep 8096 tcp6 0 0 [::]:8096 [::]:* LISTEN 20470/jellyfin`
PLEASE Help

**Comment by MuMu360121** [comment]
`root@ONEVPS190826191334:~# sudo sysv-rc-conf
sudo: sysv-rc-conf: command not found
root@ONEVPS190826191334:~# systemctl status jellyfin.service
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset:
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Wed 2019-08-28 19:52:20 UTC; 18min ago
 Main PID: 1049 (jellyfin)
    Tasks: 16 (limit: 522)
   CGroup: /system.slice/jellyfin.service
           └─1049 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh -

Aug 28 19:52:27 ONEVPS190826191334 jellyfin[1049]: [19:52:27] [WRN] GetItemList
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [INF] Executed all
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [ERR] HTTP request
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [INF] Registering
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] StartupTrigg
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] Queueing tas
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] Executing Ch
Aug 28 19:52:30 ONEVPS190826191334 jellyfin[1049]: [19:52:30] [INF] Check for pl
Aug 28 19:52:30 ONEVPS190826191334 jellyfin[1049]: [19:52:30] [INF] ExecuteQueue
Aug 28 19:53:22 ONEVPS190826191334 jellyfin[1049]: [19:53:22] [INF] Watching dir
lines 1-20/20 (END)...skipping...
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Wed 2019-08-28 19:52:20 UTC; 18min ago
 Main PID: 1049 (jellyfin)
    Tasks: 16 (limit: 522)
   CGroup: /system.slice/jellyfin.service
           └─1049 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg

Aug 28 19:52:27 ONEVPS190826191334 jellyfin[1049]: [19:52:27] [WRN] GetItemList query time (slow): 238.1298. Query: select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitl
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [INF] Executed all post-startup entry points in 0:00:00.8570822
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [ERR] HTTP request failed with message:
Aug 28 19:52:28 ONEVPS190826191334 jellyfin[1049]: [19:52:28] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 185.171.121.234
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] StartupTrigger fired for task: Check for plugin updates
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] Queueing task PluginUpdateTask
Aug 28 19:52:29 ONEVPS190826191334 jellyfin[1049]: [19:52:29] [INF] Executing Check for plugin updates
Aug 28 19:52:30 ONEVPS190826191334 jellyfin[1049]: [19:52:30] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
Aug 28 19:52:30 ONEVPS190826191334 jellyfin[1049]: [19:52:30] [INF] ExecuteQueuedTasks
Aug 28 19:53:22 ONEVPS190826191334 jellyfin[1049]: [19:53:22] [INF] Watching directory /media/Moive
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-20/20 (END)
`

**Comment by MuMu360121** [comment]
ah~ so how can I slove it? The port 8096 is normally used by jellyfin. How can I get in the web app?

**Comment by MuMu360121** [comment]
I have no idea that what should do next.  how to format the code?

**Comment by MuMu360121** [comment]
The question is the first time when I installed，the web APP can load and get in.This pronlem is the second time.

I have tried the domainnae:8096,and ip:8096,both failed.

I think may be I have init two jellyfin service,the second time when I installed ,I Creat the second service, but I can't prove it or slove it.

If there is no way to slove it how can I uninstall it,and delete all the files the reinstall?

**Comment by MuMu360121** [comment]
What can I do now?

**Comment by onny** [comment]
As far as the main process/service is running, everything should be fine.
Check if it is still listening on port 8096:
```
netstat -tln | grep 9086
```
If it does, you could reach it locally, for example with:
```
curl http://127.0.0.1:9086
```
If you can not reach it from outside your sever, you might miss some firewall or routing rule.

**Comment by MuMu360121** [comment]
> As far as the main process/service is running, everything should be fine.
> Check if it is still listening on port 8096:
> 
> ```
> netstat -tln | grep 9086
> ```
> 
> If it does, you could reach it locally, for example with:
> 
> ```
> curl http://127.0.0.1:9086
> ```
> 
> If you can not reach it from outside your sever, you might miss some firewall or routing rule.


':~# netstat -tln | grep 8096
tcp6       0      0 :::8096                 :::*                    LISTEN'

**Comment by MuMu360121** [comment]
> As far as the main process/service is running, everything should be fine.
> Check if it is still listening on port 8096:
> 
> ```
> netstat -tln | grep 9086
> ```
> 
> If it does, you could reach it locally, for example with:
> 
> ```
> curl http://127.0.0.1:9086
> ```
> 
> If you can not reach it from outside your sever, you might miss some firewall or routing rule.

the fire wall is just okay,It begins from I install it the second time

**Comment by KerryRJ** [comment]
Your netstat says that it is listening on IPv6 only.
Can you get to Jellyfin from http://[::1]:8096/?
