### ISSUE TITLE
DLNA fails to load movie list

### ISSUE THREAD

**Issue by VMBindraban** [jellyfin/jellyfin#1697]
Using DLNA on my TV it keeps loading and the server throws an error.
Watching movies through web interface works fine.

Maybe related but my phone with the app "localcast" can see the DLNA server but also keeps loading but it doesn't generate any logs however..

It's a fresh install and i only imported my movies. (300-ish)

**Logs**
```
[2019-08-31 18:00:11.465 +01:00] [INF] No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:43PUS6501/12
Manufacturer:Philips
ManufacturerUrl:http://www.philips.com
ModelDescription:UPnP Media Renderer 1.0
ModelName:Philips TV DMR
ModelNumber:2k15MTK
ModelUrl:http://www.philips.com/
SerialNumber:12345

[2019-08-31 18:00:11.469 +01:00] [INF] DLNA Session created for "43PUS6501/12" - "Philips TV DMR"
[2019-08-31 18:00:12.485 +01:00] [ERR] HTTP request failed with message: "<html><body><h1>404 Not Found</h1></body></html>"
[2019-08-31 18:00:12.496 +01:00] [ERR] Error updating device info for "43PUS6501/12"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

**System (please complete the following information):**
 - OS: Raspbery PI debian buster
 - Jellyfin Version: 10.3.7

**Comment by anthonylavado** [comment]
Just to confirm, you are using the release version from the repo and not a nightly?

**Comment by gdm85** [comment]
This issue is still present with 10.4.3 (current stable).

Relevant: https://emby.media/community/index.php?/topic/34597-philips-tv-not-appearing-in-the-device-list-and-no-dlna-access/ (it's a long thread with no apparent solution)

I can confirm that Gerbera has no such issue. Possibly related: https://github.com/gerbera/gerbera/issues/485

Please remove the `stale` label.

**Comment by PrplHaz4** [comment]
Gerbera uses [libupnp](https://pupnp.sourceforge.io/) not static profiles. This may need a profile added or changed.

**Comment by gdm85** [comment]
> This may need a profile added or changed.

There is one attached here: https://emby.media/community/index.php?/topic/34597-philips-tv-not-appearing-in-the-device-list-and-no-dlna-access/page-2#entry332454

(did not try)

**Comment by PrplHaz4** [comment]
> 
> 
> > This may need a profile added or changed.
> 
> There is one attached here: https://emby.media/community/index.php?/topic/34597-philips-tv-not-appearing-in-the-device-list-and-no-dlna-access/page-2#entry332454
> 
> (did not try)

well unless someone else has the same device, no one will be able to test it for you...
may be some hints here on what the profile is missing: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/renderers/Philips-PUS.conf
