### ISSUE TITLE
Audio non-existent Chrome 76.0.3809.132 Android 9

### ISSUE THREAD

**Issue by visualblind** [jellyfin/jellyfin#1701]
**Media Info of the file**
```
VIDEO
Title720P H264
CodecH264
AVCYes
ProfileHigh
Level31
Resolution1280x536
Aspect ratio2.40:1
InterlacedNo
Framerate25
Bitrate876 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL4
AUDIO
TitleAAC stereo Default
CodecAAC
ProfileHE-AAC
Layoutstereo
Channels2 ch
Bitrate192 kbps
Sample rate48000 Hz
DefaultYes
SUBTITLE
Titlewww.300mbfilms.com & 300mbfilms.org @ nItRo - Undefined - Default
CodecSUBRIP
DefaultYes
ForcedNo
ExternalNo
SUBTITLE
TitleUndefined
CodecSRT
DefaultNo
ForcedNo
ExternalYes
Containermkv
Path\\freenas\p0ds0smb\video-movies\The Handmaiden (2016)\The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv
Size872 MB
```

**Logs**
```
[14:44:18] [INF] User policy for visualblind. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:44:18] [INF] Profile: Unknown Profile, Path: /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[14:44:18] [INF] Profile: Unknown Profile, Path: /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[14:44:18] [INF] Profile: Unknown Profile, Path: /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[14:44:18] [INF] Setting range response values for /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv. RangeRequest: bytes=81099-65699839 Content-Length: 65618741, Content-Range: bytes 81099-65699839/914343810
[14:44:18] [INF] Setting range response values for /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv. RangeRequest: bytes=81099-65699839 Content-Length: 65618741, Content-Range: bytes 81099-65699839/914343810
[14:44:18] [INF] /usr/local/bin/ffmpeg -i file:"\\freenas\p0ds0smb\video-movies\The Handmaiden (2016)\The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv" -map 0:2 -an -vn -c:s copy "/config/data/subtitles/8/80ba6784-39cf-bb0d-35b5-0b7c7d4c740c.srt"
[14:44:18] [INF] Setting range response values for /media/video-movies/The Handmaiden (2016)/The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv. RangeRequest: bytes=71008256-914259967 Content-Length: 843251712, Content-Range: bytes 71008256-914259967/914343810
ffmpeg version 4.0.3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gnutls --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-cuvid --enable-nvenc --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
file:\\freenas\p0ds0smb\video-movies\The Handmaiden (2016)\The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv: No such file or directory
[14:44:19] [ERR] ffmpeg subtitle extraction failed for file:"\\freenas\p0ds0smb\video-movies\The Handmaiden (2016)\The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv" to /config/data/subtitles/8/80ba6784-39cf-bb0d-35b5-0b7c7d4c740c.srt
[14:44:19] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for file:"\\freenas\p0ds0smb\video-movies\The Handmaiden (2016)\The.Handmaiden.2016.BluRay.720p.x264.875MB.nItRo.XpoZ.mkv" to /config/data/subtitles/8/80ba6784-39cf-bb0d-35b5-0b7c7d4c740c.srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[14:44:19] [WRN] HTTP Response 500 to <IP redacted>, <IP redacted>. Time (slow): 0:00:01.0654577. http://travisflix.com/emby/Videos/b35b75c5-7c99-fb2d-e25c-96a917dc4bc3/b35b75c57c99fb2de25c96a917dc4bc3/Subtitles/2/0/Stream.vtt
[14:44:19] [INF] Adding playback tracker : TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDk7IFNNLUc5NjBVMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc2LjAuMzgwOS4xMzIgTW9iaWxlIFNhZmFyaS81MzcuMzZ8MTU2NzM0ODQyNzEzNw11-97c81af7b0d54797b15cc2f6579d4532-b35b75c57c99fb2de25c96a917dc4bc3
[14:44:19] [INF] PlaybackTracker : Adding Start Event : 09/01/2019 14:44:19
[14:44:19] [INF] Creating StartPlaybackTimer Task
[14:44:19] [INF] StartPlaybackTimer : Entered
[14:44:20] [INF] Processing playback tracker : TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDk7IFNNLUc5NjBVMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc2LjAuMzgwOS4xMzIgTW9iaWxlIFNhZmFyaS81MzcuMzZ8MTU2NzM0ODQyNzEzNw11-97c81af7b0d54797b15cc2f6579d4532-b35b75c57c99fb2de25c96a917dc4bc3
[14:44:21] [WRN] GetItems query time (slow): 138.4833. Query:  select count (distinct PresentationUniqueKey) from TypedBaseItems A where type in ('MediaBrowser.Controller.Entities.Movies.Movie','MediaBrowser.Controller.Entities.TV.Episode') AND TopParentId in ('7e2e9b68bf3cfc605b27b784f942f2b8','52f8994bdd5c0574196f1ac5ea47d443','d53050bd78625f51796245b01da0d396','079adc1a98bd9618201c74c7dbf29c3b','63565542c4e47dc1c7276e6e1e0975b6')
[14:44:21] [WRN] GetItems query time (slow): 117.2241. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where type in ('MediaBrowser.Controller.Entities.Movies.Movie','MediaBrowser.Controller.Entities.TV.Episode') AND TopParentId in ('7e2e9b68bf3cfc605b27b784f942f2b8','52f8994bdd5c0574196f1ac5ea47d443','d53050bd78625f51796245b01da0d396','079adc1a98bd9618201c74c7dbf29c3b','63565542c4e47dc1c7276e6e1e0975b6')
[14:44:23] [WRN] HTTP Response 206 to <IP redacted>, <IP redacted>. Time (slow): 0:00:04.613538. http://travisflix.com/emby/Videos/b35b75c57c99fb2de25c96a917dc4bc3/stream.mkv?Static=true&mediaSourceId=b35b75c57c99fb2de25c96a917dc4bc3&deviceId=TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDk7IFNNLUc5NjBVMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc2LjAuMzgwOS4xMzIgTW9iaWxlIFNhZmFyaS81MzcuMzZ8MTU2NzM0ODQyNzEzNw11&Tag=22314e4ae6450a667f4c0454313e9fe8
[14:44:39] [INF] session.RemoteEndPoint : <IP redacted>, <IP redacted>
[14:44:39] [INF] StartPlaybackTimer : event_playing_id     = b35b75c57c99fb2de25c96a917dc4bc3
[14:44:39] [INF] StartPlaybackTimer : event_user_id        = 97c81af7b0d54797b15cc2f6579d4532
[14:44:39] [INF] StartPlaybackTimer : event_user_id_int    = 1
[14:44:39] [INF] StartPlaybackTimer : session_playing_id   = b35b75c57c99fb2de25c96a917dc4bc3
[14:44:39] [INF] StartPlaybackTimer : session_user_id      = 97c81af7b0d54797b15cc2f6579d4532
[14:44:39] [INF] StartPlaybackTimer : play_method          = DirectStream
[14:44:39] [INF] StartPlaybackTimer : e.ClientName         = Jellyfin Web
[14:44:39] [INF] StartPlaybackTimer : e.DeviceName         = Chrome Android
[14:44:39] [INF] StartPlaybackTimer : ItemName             = The Handmaiden
[14:44:39] [INF] StartPlaybackTimer : ItemId               = b35b75c57c99fb2de25c96a917dc4bc3
[14:44:39] [INF] StartPlaybackTimer : ItemType             = Movie
[14:44:39] [INF] StartPlaybackTimer : All matches, playback registered
[14:44:39] [INF] Playback tracker found, adding playback info : TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDk7IFNNLUc5NjBVMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc2LjAuMzgwOS4xMzIgTW9iaWxlIFNhZmFyaS81MzcuMzZ8MTU2NzM0ODQyNzEzNw11-97c81af7b0d54797b15cc2f6579d4532-b35b75c57c99fb2de25c96a917dc4bc3
[14:44:39] [INF] Saving playback tracking activity in DB
[14:44:39] [INF] StartPlaybackTimer : Exited
```

**Stats for Nerds Screenshots**

![image](https://user-images.githubusercontent.com/19721142/64078234-d30f6500-cc8c-11e9-84ab-ce5700f14111.png)

**Server System (please complete the following information):**
 - OS: Docker on Ubuntu 18.04.3 (My concern is client-side)
 - Jellyfin Version: 10.3.7
 - Hardware settings & device: VMWare ESXi 6.7
 - Reverse proxy: 2 reverse proxies, first one is Cloudflare, and I have NGINX also running on my side that proxies requests to the Jellyfin container
 - Other hardware notes: Media mounted RO via SMB3 protocol
 
**Client System (please complete the following information):**
 - Device: Samsung Galaxy S9 unlocked
 - OS: Android 9 Build PPR1.180610.011 (kernel 4.9)
 - Client: Android
 - Browser (if Web client): Chrome 76.0.3809.132
 - Client and Browser Version: Client is the browser...

I have verified audio does work in other browsers like the one the S9 comes with stock, as well as the Tor Browser.

**Comment by onny** [comment]
Hm can you determine what audio and video codec is used in web playback? Or maybe in Chrome the audio is somehow muted?

**Comment by ddurdle** [comment]
Have you tried forcing transcode (for change the quality) to determine if the transcode audio plays?  On Chrome and Chromium for Linux, I get the same issue -- plays direct, no audio, but if I force audio transcode by changing the quality, it plays with audio.  It is ok direct play with other chrome browsers such as the one for iOS.

**Comment by visualblind** [comment]
Sorry @onny and @ddurdle that it took me so long to respond. 
@onny I think I may just be a big enough idiot that it actually is muted audio, but as you can see from my attached screenshot, there is no audio controls in the mobile UI.

![image](https://user-images.githubusercontent.com/19721142/64728177-48e6ae00-d48f-11e9-8c8e-489039bcc698.png)


Please let me know how I can take control of the audio in the mobile web UI to rule out this sneaking suspicion.

**Comment by ddurdle** [comment]
Try clicking the bolt icon and then changing the quality to see if the audio appears.

**Comment by visualblind** [comment]
> Try clicking the bolt icon and then changing the quality to see if the audio appears.

That's a negative @ddurdle

**Comment by visualblind** [comment]
I got frustrated and removed Chrome as much as stock firmware allows, and audio works now. Although that may have been most people's first troubleshooting step, I really wanted to find out the root cause of why I was missing completely audio control in the mobile web UI. Oh well. Thanks you guys for the help anyways.
