### ISSUE TITLE
Killing an ffmpeg job that has barely started generates exception

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#1733]
**Describe the bug**
When resuming an ffmpeg is started for the first segment and immediately killed again.
This makes `WaitForExit` fail with an exception.

**To Reproduce**

1. Resume any media in the web UI
2. Observe the console window.

**Expected behavior**
The web UI shouldn't even request the first segment while resuming but if it happens anyway, the server should probably wait for ffmpeg to come up and THEN kill it. (Probably by using the progress reports from ffmpeg)

**Logs**
```
[16:29:08] [INF] Stopping ffmpeg process with q command for <path>\jellyfin\transcoding-temp\15bc6c9162a82af671f3bd844ad44506.m3u8
[16:29:08] [INF] FFMpeg exited with code 0
[16:29:08] [ERR] Error killing transcoding job for <path>\jellyfin\transcoding-temp\15bc6c9162a82af671f3bd844ad44506.m3u8
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at MediaBrowser.Api.Playback.BaseStreamingService.OnFfMpegProcessExited(Process process, TranscodingJob job, StreamState state) in <path>\jellyfin\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 359
   at MediaBrowser.Api.Playback.BaseStreamingService.<>c__DisplayClass63_0.<StartFfMpeg>b__0(Object sender, EventArgs args) in <path>\jellyfin\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 277
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)
   at MediaBrowser.Api.ApiEntryPoint.KillTranscodingJob(TranscodingJob job, Boolean closeLiveStream, Func`2 delete) in <path>\jellyfin\MediaBrowser.Api\ApiEntryPoint.cs:line 607
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.4.0 (master)
 - Reverse proxy: no

**Additional context**
Debug build in Visual Studio

**Comment by rmahtoa** [comment]
Maybe this can help
https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg
