### ISSUE TITLE
Core dump (unhandled exception) when syncing kodi Bug?

### ISSUE THREAD

**Issue by Uatschitchun** [jellyfin/jellyfin#1737]
Hi there. I get an unhandled exception and a crash of jellyfin when initially syncing kodi after installing jellyfin addon.

Here's the output:
```
[20:15:10] [FTL] Unhandled Exception

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
  at System.Net.Security.SslState.ThrowIfExceptional()
  at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
  at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
  at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
  at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
  at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
  at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
  at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
  at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
  at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
  at System.Net.Security.SslState.ThrowIfExceptional()
  at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
  at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
  at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
  at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
  at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
  at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
  at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
  at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
  at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

It's jellyfin 10.3.7 running in docker and jellyfin addon 0.2.1

**Comment by Uatschitchun** [comment]
Additional notes:
sync queue plugin is installed
fresh kodi, fesh install of jellyfin addon, first sync. 
After jellyin recovers and kodi is restarted, the sync goes on until the next crash
