### ISSUE TITLE
Server using network (smb) path on ffmpeg subtitle extraction

### ISSUE THREAD

**Issue by Gr3q** [jellyfin/jellyfin#1743]
**Describe the bug**
Playing a video what contains subtitles fails when played with said subtitles, because the server is trying to extract it using the smb:// path. 

(Also, the video is shown completed in the Web Client, and the Server continues to loop trying to transcode the video, then the subtitle extraction fails and it starts again. It continues until I restart the server)

**To Reproduce**
_Use ffmpeg with no smb support_
1. Start a Video with embedded subtitles in the Web client
2. Select subtitle
3. Wait a few seconds
4. Scroll down to '....'

**Screenshots**
![image](https://user-images.githubusercontent.com/22377521/64781444-27ef8d00-d563-11e9-8197-210f8679e562.png)
Showing the transcoding progress 4 hours after I closed the Web Client.

**Expected behavior**
 **Server should not use the network path with ffmpeg (tbh I don't know your standpoint on this)**
 _(Or at least the Web Client could handle failure a bit better)_

**Logs**
The Server Log on opening the video:
```
[2019-09-12 09:52:18.811 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-12 09:52:18.816 +01:00] [INF] Profile: "Unknown Profile", Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-12 09:52:18.817 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv"
[2019-09-12 09:52:18.818 +01:00] [INF] Profile: "Unknown Profile", Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-12 09:52:18.819 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv"
[2019-09-12 09:52:18.820 +01:00] [INF] Profile: "Unknown Profile", Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-12 09:52:18.821 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv"
[2019-09-12 09:52:19.413 +01:00] [INF] "/usr/bin/ffmpeg" "-i \"smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv\" -map 0:2 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass\""
[2019-09-12 09:52:19.546 +01:00] [ERR] ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
[2019-09-12 09:52:19.574 +01:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 648
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 542
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 252
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 181
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 138
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 234
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-09-12 09:52:20.933 +01:00] [INF] /usr/bin/ffmpeg -fflags +genpts -noaccurate_seek -i file:"/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 copy -copypriorss:a:0 0 -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6  -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcoding-temp/c9d7153ac2ed1f3429fdb77aadc92a90.m3u8" -y "/var/lib/jellyfin/transcoding-temp/c9d7153ac2ed1f3429fdb77aadc92a90%d.ts"
[2019-09-12 09:52:27.559 +01:00] [INF] returning "/var/lib/jellyfin/transcoding-temp/c9d7153ac2ed1f3429fdb77aadc92a900.ts"
[2019-09-12 09:52:27.637 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:06.718121. "http://jellyfin.attilagreguss.co.uk/emby/videos/9ea47f31-fb79-9d88-be5f-52a118cb1d67/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NzUyOTYwMjQ0Ng11&MediaSourceId=9ea47f31fb799d88be5f52a118cb1d67&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=9861860&AudioBitrate=192000&PlaySessionId=13950f60840b4fd2b77df48d4d085352&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=71979f26475379088f0972c44c94d403&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-09-12 09:52:36.981 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.0178184. "http://jellyfin.attilagreguss.co.uk/emby/videos/9ea47f31-fb79-9d88-be5f-52a118cb1d67/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NzUyOTYwMjQ0Ng11&MediaSourceId=9ea47f31fb799d88be5f52a118cb1d67&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=9861860&AudioBitrate=192000&PlaySessionId=13950f60840b4fd2b77df48d4d085352&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=71979f26475379088f0972c44c94d403&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51"
[2019-09-12 09:52:37.180 +01:00] [INF] WS "http://jellyfin.attilagreguss.co.uk/embywebsocket?api_key=88b37bed030f445f9717621bf8339852&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NzUyOTYwMjQ0Ng11". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
[2019-09-12 09:52:38.881 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.2759712. "http://jellyfin.attilagreguss.co.uk/web/bower_components/libjass/libjass.css?v=10.3.7"
[2019-09-12 09:52:38.886 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.2818023. "http://jellyfin.attilagreguss.co.uk/web/bower_components/libjass/libjass.min.js?v=10.3.7"
[2019-09-12 09:52:40.425 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:02.81889. "http://jellyfin.attilagreguss.co.uk/emby/Items/d04837e65ef4690950ca5b528c811d20/Images/Primary?tag=1ad8b425b375cec00f3196fc52d7be67&quality=90"
[2019-09-12 09:52:42.228 +01:00] [INF] "/usr/bin/ffmpeg" "-i \"smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv\" -map 0:2 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass\""
[2019-09-12 09:52:42.479 +01:00] [ERR] ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
[2019-09-12 09:52:42.512 +01:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 648
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 542
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 252
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 181
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 138
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 234
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-09-12 09:52:44.489 +01:00] [INF] "/usr/bin/ffmpeg" "-i \"smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv\" -map 0:2 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass\""
[2019-09-12 09:52:44.645 +01:00] [ERR] ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
[2019-09-12 09:52:44.650 +01:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" to /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 648
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 542
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 252
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 181
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 138
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 234
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /tmp/trizen-gr3q/jellyfin/src/jellyfin-10.3.7/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 576
[2019-09-12 09:52:45.445 +01:00] [INF] User policy for "Greg". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-12 09:52:45.445 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2019-09-12 09:52:45.446 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2019-09-12 09:52:45.446 +01:00] [INF] Profile: "Unknown Profile", Path: "/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2019-09-12 09:52:46.536 +01:00] [INF] Stopping ffmpeg process with q command for "/var/lib/jellyfin/transcoding-temp/c9d7153ac2ed1f3429fdb77aadc92a90.m3u8"
[2019-09-12 09:52:47.134 +01:00] [WRN] "GetItemList" query time (slow): 143.3472. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,ExternalServiceId,IsInMixedFolder,Tags,TrailerTypes,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,ShowId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND MediaType=@MediaTypes AND (TopParentId=@TopParentId) Group by PresentationUniqueKey ORDER BY DateCreated DESC LIMIT 80"
[2019-09-12 09:52:47.323 +01:00] [INF] FFMpeg exited with code 0
[2019-09-12 09:52:47.324 +01:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/c9d7153ac2ed1f3429fdb77aadc92a90.m3u8"
[2019-09-12 09:52:49.757 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.0306514. "http://jellyfin.attilagreguss.co.uk/web/components/emby-progressring/emby-progressring.template.html?v=10.3.7&r=0"
[2019-09-12 09:52:51.301 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.9714192. "http://jellyfin.attilagreguss.co.uk/emby/Items/9be08cd47e2b21ed208ac8b3e675cc67/Images/Primary?maxHeight=532&maxWidth=355&tag=c06a9592195790132fa7d68b3c37e48f&quality=90"
[2019-09-12 09:52:52.013 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:00.6836659. "http://jellyfin.attilagreguss.co.uk/web/controllers/dashboardpage.js?v=10.3.7"
[2019-09-12 09:52:55.144 +01:00] [WRN] HTTP Response 200 to "86.59.226.86". Time (slow): 0:00:01.7846042. "http://jellyfin.attilagreguss.co.uk/web/components/activitylog.js?v=10.3.7"
[2019-09-12 09:52:55.642 +01:00] [WRN] HTTP Response 204 to "86.59.226.86". Time (slow): 0:00:09.1820839. "http://jellyfin.attilagreguss.co.uk/emby/Videos/ActiveEncodings?deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2OC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY4LjB8MTU2NzUyOTYwMjQ0Ng11&PlaySessionId=13950f60840b4fd2b77df48d4d085352"
[2019-09-12 09:52:57.142 +01:00] [INF] /usr/bin/ffmpeg -i file:"/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_omx  -b:v 9861860 -maxrate 9861860 -bufsize 19723720 -force_key_frames "expr:gte(t,n_forced*3)" -copyts -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2,subtitles='/HDD/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv:si=0'" -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcoding-temp/44b6e774ff3b5a0b7d6b8284d315fe95.m3u8" -y "/var/lib/jellyfin/transcoding-temp/44b6e774ff3b5a0b7d6b8284d315fe95%d.ts"
```

ffmpeg output:
```
gr3q@gr3q-server ~> /usr/bin/ffmpeg -i "smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv" -map 0:2 -an -vn -c:s copy /var/lib/jellyfin/data/subtitles/2/2dc65845-80de-45cc-d9e4-0d25d97bd89b.ass
ffmpeg version n4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-mmal --enable-omx --enable-omx-rpi --enable-shared --enable-version3 --host-cflags='"-fPIC"'
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv: Protocol not found
Did you mean file:smb://192.168.0.50/hdd/Anime/One Punch Man/S1/S01E01 - One Punch Man[1080p].mkv?
```

**System:**
 - OS: Arch Linux armv7h (Raspberry Pi 4)
 - Browser: Firefox
 - Jellyfin Version: 10.3.7
 - Reverse proxy: No

**Additional context**
It does the same thing if I access the server from outside the local network or local network, or using reverse proxy.
 
Fresh install, not migrated

Using the local path with ffmpeg works correctly.

**Comment by mijofa** [comment]
I had the same problem, and have "solved" it by removing the network path, but I don't believe that is a viable solution as it means client devices can't use the network path to access the file either.
The Jellyfin server should not be using the network path when loading local files, **or** it should be using the network path for loading the video/audio stream as well not just the subtitles.

**Comment by Gr3q** [comment]
I can confirm that this issue is not present on 10.4.0 for me (has problems with some subtitle encodings, but that is another issue entirely)

**Comment by JustAMan** [comment]
From what I see in the source this is somewhat random, as the code takes first instance of media source in the list of sources. So if that first happens to be a network path this errors out.

**Comment by JustAMan** [comment]
I think this was supposed to be fixed in #1457, so that's likely the reason why you don't see it in 10.4.0 anymore.

**Comment by mijofa** [comment]
Can confirm this issue seems to be resolved, but now I have another issue where "binging" from one episode to the next, if I don't change the subtitle language on the next episode I get the subtitle track from the previous one.
This probably requires a new Github issue though, so I'll look into it a little more and make one.

**Comment by JustAMan** [comment]
@mijofa is this what you're seeing? https://github.com/jellyfin/jellyfin-web/issues/518

**Comment by mijofa** [comment]
On Thu, Oct 17, 2019 at 07:16:20AM -0700, Vasily wrote:
> @mijofa is this what you're seeing? https://github.com/jellyfin/jellyfin-web/issues/518

Yep, that sounds about right, I shall subscribe to that one

-- 
Mike Abrahall
