### ISSUE TITLE
LiveTV and DVR Recording not playing. Unknown profile?

### ISSUE THREAD

**Issue by jstorgaard** [jellyfin/jellyfin#1749]
LiveTV and DVR is not able to play/record. Using xTeve on PC 192.168.1.45.
No infomation about new connection attempted on xTeve server. 
Plex plays fine from same xTeve host.

**Logs**
```
[08:00:37] [WRN] HTTP Response 200 to 111.111.111.111. Time (slow): 0:00:00.6014826. https://jellyfin.myhostname.com:8920/emby/LiveTv/Programs
[08:00:49] [INF] User policy for Jep. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[08:00:49] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: 111.111.111.111, IsInLocalNetwork: False
[08:00:49] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 2000000
[08:00:49] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 2000000
[08:00:49] [INF] Profile: Unknown Profile, Path: http://192.168.1.45:34400/stream/23f85b189479ac1284b31460e98b1ae2, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[08:00:49] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: 111.111.111.111, IsInLocalNetwork: False
[08:00:49] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 2000000
[08:00:49] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 2000000
[08:00:49] [INF] Profile: Unknown Profile, Path: http://192.168.1.45:34400/stream/23f85b189479ac1284b31460e98b1ae2, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
```

**Server System (please complete the following information):**
 - OS: Windows 10 x64 1903
 - Jellyfin Version: 10.3.7
 - Hardware settings & device: AMD FX CPU, AMD Radeon R7 200 series
 - Reverse proxy: no
 - Other hardware notes: N/A
 
**Client System (please complete the following information):**
 - Device: Pixel 3 XL, Mac, PC
 - OS: Android, macOS, Windows
 - Client: Web/Browser,  Android
 - Browser (if Web client): Chrome, Pale Moon
 - Client and Browser Version: Jellyfin 10.3.7 (Android) and Chrome 76 (Mac), Pale Moon 28.7.1 (Windows)

**Comment by jstorgaard** [comment]
So, I testet Jellyfin 10.4.0. Stream is starting here, regardless of some of the same error messages. 
Playing from local machine (127.0.0.1). Problem may already be solved. Inserting logs here in case the other error messages would be of interest.

```
[12:43:40] [INF] User policy for jepsh. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[12:43:40] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: ::1, IsInLocalNetwork: True
[12:43:40] [INF] Profile: Unknown Profile, Path: http://192.168.1.20:34400/stream/b1dc5a119bec0000fc66484aca8f134b, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[12:43:40] [INF] Profile: Unknown Profile, No direct play profiles found for Path: http://192.168.1.20:34400/stream/b1dc5a119bec0000fc66484aca8f134b
[12:43:40] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: ::1, IsInLocalNetwork: True
[12:43:40] [INF] Profile: Unknown Profile, Path: http://192.168.1.20:34400/stream/b1dc5a119bec0000fc66484aca8f134b, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[12:43:40] [INF] Profile: Unknown Profile, No direct play profiles found for Path: http://192.168.1.20:34400/stream/b1dc5a119bec0000fc66484aca8f134b
[12:43:40] [INF] Opening channel stream from Emby, external channel Id: m3u_d32b6ea5a70fdb50f535ad1244b093ac3270d6d4484496f598bc83ef7b796235
[12:43:40] [INF] Streaming Channel m3u_d32b6ea5a70fdb50f535ad1244b093ac3270d6d4484496f598bc83ef7b796235
[12:43:40] [INF] Opening SharedHttpStream Live stream from http://192.168.1.20:34400/stream/b1dc5a119bec0000fc66484aca8f134b
[12:43:42] [INF] Beginning SharedHttpStream stream to D:\Temp\Jellyfin\transcodes\937ee3a6d65843ea8c3d6c5156b43253.ts
[12:43:42] [INF] Live stream opened after 1262.3316ms
[12:43:42] [INF] Returning mediasource streamId d3f493b9205d62de80f10291301caae0, mediaSource.Id d3f493b9205d62de80f10291301caae0, mediaSource.LiveStreamId null
[12:43:42] [INF] Waiting 3000ms before probing the live stream
[12:43:45] [INF] C:\Users\jepsh\AppData\Roaming\jellyfin\ffprobe.exe -analyzeduration 3000000 -i "https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts" -threads 0 -v warning -print_format json -show_streams -show_format
[12:43:45] [INF] Live tv media info probe took 3.6084446 seconds
[12:43:45] [INF] Live stream opened: {"Protocol":"Http","Id":"d3f493b9205d62de80f10291301caae0","Path":"https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts","Type":"Default","Container":"mpegts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_d3f493b9205d62de80f10291301caae0","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1/50","VideoRange":"SDR","DisplayTitle":"720I H264","NalLengthSize":"0","IsInterlaced":true,"BitRate":8000000,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":25,"RealFrameRate":50,"Profile":"Main","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":31,"IsAnamorphic":false},{"Codec":"mp2","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"MP2 stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":128000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":8128000,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"},"AnalyzeDurationMs":3000}
[12:43:45] [INF] User policy for jepsh. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[12:43:45] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: ::1, IsInLocalNetwork: True
[12:43:45] [INF] Profile: Unknown Profile, Path: https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[12:43:45] [INF] Profile: Unknown Profile, No direct play profiles found for Path: https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts
[12:43:45] [INF] RemoteClientBitrateLimit: 150000000, RemoteIp: ::1, IsInLocalNetwork: True
[12:43:45] [INF] Profile: Unknown Profile, Path: https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[12:43:45] [INF] Profile: Unknown Profile, No direct play profiles found for Path: https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts
[12:43:45] [WRN] HTTP Response 200 to ::1. Time (slow): 0:00:06.4236839. https://localhost:8920/Items/ee58f1505531027060c952a5b72b5bfd/PlaybackInfo?UserId=6dd7e0dbaf6c4f3f822a71edcf52d89a&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000
[12:43:46] [ERR] Could not find handler for /LiveStreams/MediaInfo
[12:43:46] [INF] C:\Users\jepsh\AppData\Roaming\jellyfin\ffmpeg.exe -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts+genpts -f mpegts -i "https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 copy -flags -global_header -vsync cfr -codec:a:0 aac -strict experimental -ac 2 -ab 128000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/31b2d4adead8d520cdc31dce0fa0a643/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "D:\Temp\Jellyfin\transcodes\31b2d4adead8d520cdc31dce0fa0a643.m3u8" -y "D:\Temp\Jellyfin\transcodes\31b2d4adead8d520cdc31dce0fa0a643%d.ts"
[12:43:47] [WRN] HTTP Response 200 to ::1. Time (slow): 0:00:00.5818029. https://localhost:8920/videos/ee58f150-5531-0270-60c9-52a5b72b5bfd/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjAuOSkgR2Vja28vMjAxMDAxMDEgR29hbm5hLzQuMiBGaXJlZm94LzYwLjkgUGFsZU1vb24vMjguNS4wfDE1NTc0MTg1MTE5NDg1&MediaSourceId=d3f493b9205d62de80f10291301caae0&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=-1&VideoBitrate=139872000&AudioBitrate=128000&PlaySessionId=376e04af976449e3b0a557511a295f0e&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_d3f493b9205d62de80f10291301caae0&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported
[12:44:12] [INF] Stopping ffmpeg process with q command for D:\Temp\Jellyfin\transcodes\31b2d4adead8d520cdc31dce0fa0a643.m3u8
[12:44:13] [INF] Getting image size for item LiveTvChannel C:\Users\jepsh\AppData\Local\jellyfin\metadata\livetv\55a140d72cc6832a45ff88b2fac443d9\metadata\poster.png
[12:44:13] [ERR] Failed to determine primary image aspect ratio for C:\Users\jepsh\AppData\Local\jellyfin\metadata\livetv\55a140d72cc6832a45ff88b2fac443d9\metadata\poster.png
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info, Boolean updateItem)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
[12:44:13] [INF] Getting image size for item LiveTvChannel C:\Users\jepsh\AppData\Local\jellyfin\metadata\livetv\97ac93c8ff4e84c1490a69946859913b\metadata\poster.png
[12:44:13] [ERR] Failed to determine primary image aspect ratio for C:\Users\jepsh\AppData\Local\jellyfin\metadata\livetv\97ac93c8ff4e84c1490a69946859913b\metadata\poster.png
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info, Boolean updateItem)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
[12:44:15] [INF] FFMpeg exited with code 0
[12:44:15] [ERR] Error killing transcoding job for D:\Temp\Jellyfin\transcodes\31b2d4adead8d520cdc31dce0fa0a643.m3u8
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at System.Diagnostics.Process.EnsureState(State state)
   at MediaBrowser.Api.Playback.BaseStreamingService.OnFfMpegProcessExited(Process process, TranscodingJob job, StreamState state)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at MediaBrowser.Api.ApiEntryPoint.KillTranscodingJob(TranscodingJob job, Boolean closeLiveStream, Func`2 delete)
[12:44:15] [WRN] HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:28.3471241. https://127.0.0.1:8920/LiveTv/LiveStreamFiles/937ee3a6d65843ea8c3d6c5156b43253/stream.ts
[12:44:15] [INF] Deleting partial stream file(s) D:\Temp\Jellyfin\transcodes\31b2d4adead8d520cdc31dce0fa0a643.m3u8
[12:44:16] [INF] Playback stopped reported by app Jellyfin Web 10.3.6 playing DR K HD DK. Stopped at 19728 ms
[12:44:16] [INF] Live stream d3f493b9205d62de80f10291301caae0 consumer count is now 0
[12:44:16] [INF] Closing live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_d3f493b9205d62de80f10291301caae0
[12:44:16] [INF] Closing SharedHttpStream
[12:44:16] [INF] Live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_d3f493b9205d62de80f10291301caae0 closed successfully
[12:44:16] [WRN] HTTP Response 204 to ::1. Time (slow): 0:00:03.7246926. https://localhost:8920/Sessions/Playing/Stopped
[12:44:16] [INF] Deleting temp files ["D:\\Temp\\Jellyfin\\transcodes\\937ee3a6d65843ea8c3d6c5156b43253.ts"]
[12:44:35] [WRN] GetItemList query time (slow): 17.5654ms. Query: select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where type=@type AND TopParentId in ('348b43103076ce43746224f8773a6ac5','d6bada0385d6803a0341525b78279ebe','5437867233b8b813426065e9221c4a88','afa8bb44f525b8ece41c6717df924903','37311a15d2e03989ef0ecf5f9861bc37','7c7b048b7bd86133612198cac12d9668','023cc590fa0334f4ae5cff831a333c26') Group by SeriesPresentationUniqueKey ORDER BY MAX(LastPlayedDate) DESC
[12:44:35] [WRN] GetItemList query time (slow): 12.5965ms. Query: select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,ExternalServiceId,IsInMixedFolder,Tags,TrailerTypes,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,ShowId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where playbackPositionTicks > 0 AND IsVirtualItem=@IsVirtualItem AND MediaType=@MediaTypes AND TopParentId in ('348b43103076ce43746224f8773a6ac5','d6bada0385d6803a0341525b78279ebe','7c7b048b7bd86133612198cac12d9668','2b2bca16aacc8a14d53a11bb829eafa5','5437867233b8b813426065e9221c4a88','afa8bb44f525b8ece41c6717df924903','37311a15d2e03989ef0ecf5f9861bc37','023cc590fa0334f4ae5cff831a333c26') Group by PresentationUniqueKey ORDER BY LastPlayedDate DESC LIMIT 12

```

**Comment by marcosteam** [comment]
same.
log:
`[2019-09-16 02:26:21.315 +00:00] [INF] Live stream opened: {"Protocol":"Http","Id":"e4c1e549776d2d4f4af43f62639a84c6","Path":"http://httpdvb.slave.homed.hrtn.net/playurl?playtype=live&amp;protocol=hls&amp;accesstoken=R5D22D2B7U309E0093K7735BBEDIAC2DC601PBM3187915V10453Z6B7EDWE3620470C71&amp;&amp;playtoken=&amp;programid=4200000196.m3u8","Type":"Default","Container":"hls,applehttp","Size":614,"IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_e4c1e549776d2d4f4af43f62639a84c6","RequiresLooping":true,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1/50","VideoRange":"SDR","DisplayTitle":"1080P H264","NalLengthSize":"0","IsInterlaced":false,"BitRate":20000000,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":25,"RealFrameRate":25,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":41,"IsAnamorphic":false},{"Codec":"aac","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"AAC stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"LC","Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":20192000,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"},"AnalyzeDurationMs":3000}
[2019-09-16 02:26:21.324 +00:00] [INF] User policy for "marcosteam". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-09-16 02:26:21.326 +00:00] [INF] Profile: "Unknown Profile", Path: "http://httpdvb.slave.homed.hrtn.net/playurl?playtype=live&amp;protocol=hls&amp;accesstoken=R5D22D2B7U309E0093K7735BBEDIAC2DC601PBM3187915V10453Z6B7EDWE3620470C71&amp;&amp;playtoken=&amp;programid=4200000196.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-09-16 02:26:21.327 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://httpdvb.slave.homed.hrtn.net/playurl?playtype=live&amp;protocol=hls&amp;accesstoken=R5D22D2B7U309E0093K7735BBEDIAC2DC601PBM3187915V10453Z6B7EDWE3620470C71&amp;&amp;playtoken=&amp;programid=4200000196.m3u8"
[2019-09-16 02:26:21.360 +00:00] [WRN] HTTP Response 200 to "172.17.0.1". Time (slow): 0:00:02.9082005. "http://my.nas:8096/emby/Items/3add8fcee17a248d317c10fa931fcebe/PlaybackInfo?UserId=a3bbae40a7b84ddd857e0a53c50e8935&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
[2019-09-16 02:26:22.188 +00:00] [INF] /usr/local/bin/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts+genpts -stream_loop -1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -i "http://httpdvb.slave.homed.hrtn.net/playurl?playtype=live&amp;protocol=hls&amp;accesstoken=R5D22D2B7U309E0093K7735BBEDIAC2DC601PBM3187915V10453Z6B7EDWE3620470C71&amp;&amp;playtoken=&amp;programid=4200000196.m3u8" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 copy -flags -global_header -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/39758dc9a3964710cdeb334d43cd3015/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/config/transcoding-temp/39758dc9a3964710cdeb334d43cd3015.m3u8" -y "/config/transcoding-temp/39758dc9a3964710cdeb334d43cd3015%d.ts"`

**Comment by marcosteam** [comment]
Now I have to use xTeVe to replace m3u tunner.
Weird,xTeve can pass the address to jellyfin to play normailly,but jellyfin cannot play m3u8 link directly.

**Comment by ddurdle** [comment]
I don't think the unknown profile is an error.  It is quite common showing up in both emby and jellyfin.
You are using TS links inside your m3u8 file right?

**Comment by dannymichel** [comment]
im having the same issue in 10.4.3

**Comment by donmega** [comment]
I am also having the same error. Can't play IPTV or Recod. Running Windows 10 with the latest JellyFin Nightly:

[2020-02-22 17:17:37.693 +01:00] [INF] [33] App: User policy for "admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-02-22 17:17:37.695 +01:00] [INF] [33] App: Profile: "Unknown Profile", Path: "http://(MASKED)", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-02-22 17:17:37.697 +01:00] [INF] [33] App: Profile: "Unknown Profile", No direct play profiles found for Path: "http://(MASKED)"

I've Masked the URL to the M3U8 file for privacy.
