### ISSUE TITLE
TVDB Error in DummySeasonProvider

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#1771]
_Originally posted by @tyhawk in https://github.com/jellyfin/jellyfin/issues/1356#issuecomment-533037346_

----

I've got the same error as @enomam, but on 10.3.7 (also running docker).
```
[2019-09-19 10:53:49.716 +02:00] [ERR] Error in DummySeasonProvider
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```
Scanning my libraries since today is extremely slow. Haven't touched any settings. Not sure what's going on.

----

Created new issue to follow.

**Comment by tyhawk** [comment]
The problem is actually pretty serious. Jellyfin stopped indexing new movies and series.
Possibly related errors:
```
[2019-09-24 11:21:45.632 +02:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
   
[2019-09-24 13:30:32.204 +02:00] [ERR] "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass15_0.<GetImagesAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```
After only a few minutes, Jellyfin cancels indexing all together.
```
[2019-09-24 17:13:28.251 +02:00] [INF] "Scan media library" Cancelled after 6 minute(s) and 5 seconds
```
Tried to enable debug logging, but when I tick the checkbox in the expert settings for logging, it doesn't seem to change this setting or even keep it once I leave the page.

I'm trying to find a workaround, but nothing worked so far. Even a fresh install had trouble indexing most of the recent new files. The file are ripped/converted with the same method I've been using of years and the versions of the software used (or the settings I use) haven't changed. The files play fine in VLC and are 'ordinary H264 files.

**Specs:**
OS: Ubuntu 18.04.3 (latest version)
Jellyfin version: 10.3.7
Running on docker (swarm) with the jellyfin/jellyfin image.

**Comment by joshuaboniface** [comment]
This sounds like some sort of database corruption issue.

```
System.NullReferenceException: Object reference not set to an instance of an object.
```

I've seen this when the Library has bad (or corrupt) entries in it, and JF reads out a NULL object (or equivalent) that the later functions die on.

I don't think we have any workarounds right now short of redoing the library database, or searching for the bad entry and deleting it (if you can find out exactly what show it's searching for, but the DB is a complex mess so finding the entry might be harder).

**Comment by tyhawk** [comment]
@joshuaboniface Is there an easy way to *only* remove the database and keep other stuff, like users and settings? Like only removing the library.db files?

**Comment by tyhawk** [comment]
I removed all the library.db files (library.db, library.db-shm, library.db-wal). I did not remove any metadata files or cache, only those three and restarted the docker container.

Now indexing works again, but extremely slow and not very good. At least it doesn't get cancelled after a few minutes. But with slow I mean over 12 hours while it normally would take less than 5-10 minutes for the same files. And loads of these errors in my logs:
```
[2019-09-26 10:18:22.711 +02:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass12_0.<GetSeriesByImdbIdAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2019-09-26 10:20:03.636 +02:00] [ERR] Error in DummySeasonProvider
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```
So the workaround @joshuaboniface suggested solved part of the problem, but it is still something that needs to be solved. If I am the only one with this issue, I assume it is some sort of settings-issue, but I wonder what it is.

**Comment by tyhawk** [comment]
As another test, I created a container with a fresh install (no previous config) with the linuxserver/jellyfin:3.10.7 container. I have the same issues as with the jellyfin/jellyfin:3.10.7 container:
- Indexing / scanning TV shows is slow and a lot of data isn't matched or downloaded
- Indexing / scanning Movies doesn't seem to work at all
- Indexing / scanning of music, home videos and photo's is working fine

Strangely enough, indexing / scanning of movies and tv shows worked fine about a month ago. Perhaps something changed in the API of the sites that are scraped for data (TheTVDB, TheMovieDB, etc)?

I'm also curious if anyone else had this issue or if I am the only one. In that case, it must be something in my infrastructure that is causing this issue. All my volumes are NFS volumes by the way. I'm not experiencing any issues with other containers using some of the same websites to scrape data (Plex, Radarr, Sonarr).

**Comment by tyhawk** [comment]
I did some further troubleshooting with version 10.4.1 (fresh install, no data or config from a previous install used), but renaming my TV show files to different conventions (including those that the Jellyfin docs suggest) don't resolve this issue. In fact, during a library scan, I don't even see Jellyfin performing a DNS query for any thetvdb.com URL.
I tried the same for movies, but again, different naming conventions don't fix the problem with indexing either. Here I also notice no DNS query towards themoviedb.com, which is strange. It does try to match a movie, but just gives up after a few minutes.
```
[23:42:05] [INF] Validating media library,
[23:42:05] [INF] Stopping directory watching for path /media/Speelfilm/Animatie,
[23:42:08] [INF] MovieDbProvider: Finding id for item: Aladdin,
[23:43:48] [INF] Scan media library Cancelled after 1 minute(s) and 43 seconds,
[23:42:05] [INF] Executing Scan media library,
[23:43:48] [INF] Watching directory /media/Speelfilm/Animatie,
[23:43:48] [INF] ExecuteQueuedTasks
```
I've set the preferred languages for my libraries to English/United States, used all the defaults Jellyfin gives me at library creation, but no luck.

I still have no idea why this doesn't work for me and looking at the bug reports, it seems I am the only one with this issue. Which sucks, because I would love to ditch Plex in favor of a 100% open source product. When it worked fine (a few months ago) it was definitely way better (and faster) then Plex. I really really still hope someone can help me track down the issue.

**Comment by Ainto** [comment]
> 作为另一个测试，我创建了一个容器，该容器具有新的安装（没有以前的配置），使用 linuxserver/jellyfin：3.10.7 容器。我有同样的问题与果冻/果冻：3.10.7 容器：
> 
> * 索引/扫描电视节目速度很慢，大量数据不匹配或无法下载
> * 索引/扫描影片似乎根本不工作
> * 索引/扫描音乐，家庭视频和照片的工作很好
> 
> 奇怪的是，索引/扫描电影和电视节目工作正常约一个月前。也许被刮取数据的站点的 API 中发生了一些变化（TVDB、MovieDB 等）？
> 
> 我也好奇，如果其他人有这个问题，或者如果我是唯一一个。在这种情况下，一定是我的基础结构中导致此问题的原因。顺便说一下，我的所有卷都是 NFS 卷。我没有任何问题与其他容器使用一些相同的网站刮数据（Plex，雷达，Sonarr）。



> As another test, I created a container with a fresh install (no previous config) with the linuxserver/jellyfin:3.10.7 container. I have the same issues as with the jellyfin/jellyfin:3.10.7 container:
> 
> * Indexing / scanning TV shows is slow and a lot of data isn't matched or downloaded
> * Indexing / scanning Movies doesn't seem to work at all
> * Indexing / scanning of music, home videos and photo's is working fine
> 
> Strangely enough, indexing / scanning of movies and tv shows worked fine about a month ago. Perhaps something changed in the API of the sites that are scraped for data (TheTVDB, TheMovieDB, etc)?
> 
> I'm also curious if anyone else had this issue or if I am the only one. In that case, it must be something in my infrastructure that is causing this issue. All my volumes are NFS volumes by the way. I'm not experiencing any issues with other containers using some of the same websites to scrape data (Plex, Radarr, Sonarr).

I have the same problem as you. Can you open the tvdb site? My can't opened it

**Comment by telans** [comment]
I'm also having the same issue as @tyhawk here, although this isn't explicitly related to TVDB, as TMDD also fails (but without any Null error). 

Their logs are almost identical to what I'm experiencing.
My scans get cancelled and if any media is to be added to the library it's only a couple episodes at best. Fresh install on Unraid with the 10.4.2 docker.

**Comment by tyhawk** [comment]
@Ainto I can't "Identify" a TV series, Jellyfin doesn't seem to even connect to TheTVDB (according to my Pi-Hole DNS logs), even if I search based on the ID number of the series.

**Comment by tyhawk** [comment]
It took me a while to figure out (but persisting paid off), but after making sure to stick to the file layout of TV shows exactly as documented for Jellyfin, this issue is resolved for me.
TV shows are indexed perfectly and all meta data is downloaded from TheTVdb.

Just to be clear, I am currectly using the following way to layout my files:
```Showname/Season xx/Showname - s01e01 - Name episode.mkv```
If the year is relevant to the show, I use
```Showname (Year)/Season xx/Showname (Year) - s01e01 - Name episode.mkv```

It seems the scraper is very, very rigid and really requires your media to be in this format. It is unfortunate that logging doesn't clearly pick up on alternate (yet similar) ways of organizing this data and either is able to handle the difference (like Plex does) or at least throw an error indicating the format needs to be changed.

This is on version 10.4.3, using the official Jellyfin Docker image on Ubuntu 18.04.3.
On a side note, given the extend of my TV series collection, "Rename My TV Series" saved my a whole lot of time and effort.

**Comment by Ainto** [comment]
> It took me a while to figure out (but persisting paid off), but after making sure to stick to the file layout of TV shows exactly as documented for Jellyfin, this issue is resolved for me.
> TV shows are indexed perfectly and all meta data is downloaded from TheTVdb.
> 
> Just to be clear, I am currectly using the following way to layout my files:
> `Showname/Season xx/Showname - s01e01 - Name episode.mkv`
> If the year is relevant to the show, I use
> `Showname (Year)/Season xx/Showname (Year) - s01e01 - Name episode.mkv`
> 
> It seems the scraper is very, very rigid and really requires your media to be in this format. It is unfortunate that logging doesn't clearly pick up on alternate (yet similar) ways of organizing this data and either is able to handle the difference (like Plex does) or at least throw an error indicating the format needs to be changed.
> 
> This is on version 10.4.3, using the official Jellyfin Docker image on Ubuntu 18.04.3.
> On a side note, given the extend of my TV series collection, "Rename My TV Series" saved my a whole lot of time and effort.

It's not the problem of scraper. It's that my network can't access tvdb. Even if I don't check use tvdb, jellyfin still uses it and doesn't automatically timeout (or the timeout is too long)

**Comment by anthonylavado** [comment]
> It seems the scraper is very, very rigid and really requires your media to be in this format. It is unfortunate that logging doesn't clearly pick up on alternate (yet similar) ways of organizing this data and either is able to handle the difference (like Plex does) or at least throw an error indicating the format needs to be changed.

@tyhawk  Reporting a better error is planned. There was also a Regex change that went "under the radar" which caused loads of headaches with library scans. I didn't think it was linked at the time. We have fixed it in 10.4.3.

**Comment by anthonylavado** [comment]
@Ainto If you are in China, it's my understanding that TheTVDB is blocked. It's not supposed to be reached if you disabled it, but that might be a different issue.

**Comment by tyhawk** [comment]
@anthonylavado Thanks for the response. Once I get scraping movies working, I'm very close to ditching Plex entirely and using Jellyfin for all my media needs. But that is another issue I've commented on in another issue report, so I won't go into it here.

**Comment by HristoKolev** [comment]
This may be partly my fault. 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)

```

This error here happens on some network errors. My original idea was to catch it and extract the response in order to get more information on what went wrong. This backfired, because for some type of errors the response in the exception is null, triggering NullReferenceException and hiding the original error. 

I just released a new version of the library that among other things replaces the HTTP layer with the the newer HttpClient that Microsoft insists it's the right API for HTTP requests.

My suggestions is to try and update TvDbSharper to v3 and you should be getting more descriptive errors.
