### ISSUE TITLE
Chromecast doesn't show pictures (videos an music are working)

### ISSUE THREAD

**Issue by jakobroehrl** [jellyfin/jellyfin#1796]
First of all: This system is incredible, thank you all! 🥇 

I can cast my Audio and my Video, only Photos won't show. 
I get this message:
![grafik](https://user-images.githubusercontent.com/24530680/65625845-e46a3980-dfcc-11e9-95cd-d35b016b0730.png)

**Comment by symos** [comment]
I also have the same problem.

The error in the logs is:

```
[2019-10-11 23:07:08.079 +03:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (1936876886): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (1936876886): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)

```

**Comment by Kejszijo** [comment]
I also have the same problem.

**Comment by JamesObZ** [comment]
Yep, same for me.  While a media server such as this is mainly for movies/tv showes and music etc - there are many of us that would also like to cast our photos to the TV.

Please fix this functionallity.  I dont want to have to go back to Plex!

**Comment by dkanada** [comment]
I'm guessing it might not be implemented for the Chromecast client, unless someone can confirm it was working in a previous release? Regardless, there are currently no maintainers for Chromecast, so unless you guys know someone interested in picking up that client you might have to wait a while for the solution.

**Comment by symos** [comment]
This issue is still present on the Android app.

I don't know if something has changed regarding the fact there were no Chromecast maintainers to look into it.

**Comment by NoRelect** [comment]
I also have this problem.

For me, the issue happens both in the Android App and the Web-App (Google Chrome) when trying to cast an image to the chromecast.

**Comment by lanmand** [comment]
Also having this issue (Error: MessageChromecastConnectionError), using docker image jellyfin/jellyfin:latest
and android app
