### ISSUE TITLE
I'm unable to play m3u Live TV

### ISSUE THREAD

**Issue by TiraelSedai** [jellyfin/jellyfin#1823]
I have a more or less simple M3U live tv playlist, that works perfectly in VLC. However, I can't seem to make it work in Jellyfin.

**To Reproduce**
1. Go to Live TV in dashboard, add M3U tuner
2. Go to Live TV and try to watch any channel

**Expected behavior**
OK

**Logs**
There are two more or less common exceptions:
```

[2019-10-01 06:12:53.889 +00:00] [ERR] HTTP request failed with message: "�      퐱
1D{�X�Q��iD���/Hn�$Yzo�'�����̾V�r�z:Q�jUB��W�%�2ۀHIɗ��3R�6� ��9f^w7
u
�S*�Z��7�*J�v�UC�\H�OO6z��w��`�bCrP2`�	��LB�x�g�J ��u��X�/� �z
4  "
[2019-10-01 06:12:53.893 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-10-01 06:12:59.614 +00:00] [INF] User policy for "Tirael". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-10-01 06:12:59.614 +00:00] [INF] Profile: "Unknown Profile", Path: "http://stream.novouralsk-news.ru/echotv24/live.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-10-01 06:12:59.614 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://stream.novouralsk-news.ru/echotv24/live.m3u8"
[2019-10-01 06:12:59.615 +00:00] [INF] Opening channel stream from "Emby", external channel Id: "m3u_a5cb684e7b52bd68b55a1342e1e566d205b1a804efeb7b6d9d690a2367dd6ebc"
[2019-10-01 06:12:59.615 +00:00] [INF] Streaming Channel m3u_a5cb684e7b52bd68b55a1342e1e566d205b1a804efeb7b6d9d690a2367dd6ebc
[2019-10-01 06:12:59.619 +00:00] [INF] Live stream opened after 0.1241ms
[2019-10-01 06:12:59.619 +00:00] [INF] Returning mediasource streamId "05b1a804efeb7b6d9d690a2367dd6ebc", mediaSource.Id "05b1a804efeb7b6d9d690a2367dd6ebc", mediaSource.LiveStreamId null
[2019-10-01 06:12:59.628 +00:00] [INF] Waiting 3000ms before probing the live stream
[2019-10-01 06:13:02.634 +00:00] [INF] "/usr/local/bin/ffprobe" "-analyzeduration 3000000 -i \"http://stream.novouralsk-news.ru/echotv24/live.m3u8\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2019-10-01 06:13:03.194 +00:00] [INF] Live tv media info probe took "3.5678484" seconds
[2019-10-01 06:13:03.196 +00:00] [INF] Live stream opened: {"Protocol":"Http","Id":"05b1a804efeb7b6d9d690a2367dd6ebc","Path":"http://stream.novouralsk-news.ru/echotv24/live.m3u8","Type":"Default","Container":"hls,applehttp","Size":819,"IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_05b1a804efeb7b6d9d690a2367dd6ebc","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1/50","VideoRange":"SDR","DisplayTitle":"480P H264","NalLengthSize":"0","IsInterlaced":false,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":480,"Width":640,"AverageFrameRate":25,"RealFrameRate":25,"Profile":"Constrained Baseline","Type":"Video","AspectRatio":"4:3","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":30,"IsAnamorphic":false},{"Codec":"aac","TimeBase":"1/90000","CodecTimeBase":"1/44100","DisplayTitle":"AAC stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":44100,"IsDefault":false,"IsForced":false,"Profile":"LC","Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":192000,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"},"AnalyzeDurationMs":3000}
[2019-10-01 06:13:03.203 +00:00] [INF] User policy for "Tirael". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-10-01 06:13:03.203 +00:00] [INF] Profile: "Unknown Profile", Path: "http://stream.novouralsk-news.ru/echotv24/live.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-10-01 06:13:03.203 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://stream.novouralsk-news.ru/echotv24/live.m3u8"
[2019-10-01 06:13:03.209 +00:00] [WRN] HTTP Response 200 to "172.20.0.1". Time (slow): 0:00:03.6150803. "http://jellyfin.evgen.duckdns.org:443/emby/Items/449848471c2ddd96f63688561b792acb/PlaybackInfo?UserId=4974f593d52e457e8d3cb63f31dc511d&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"

```

And the second one:

```
[2019-10-01 06:06:45.301 +00:00] [INF] User policy for "Tirael". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-10-01 06:06:45.315 +00:00] [INF] Profile: "Unknown Profile", Path: "Unknown path", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-10-01 06:06:45.324 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "Unknown path"
[2019-10-01 06:06:45.353 +00:00] [INF] Profile: "Unknown Profile", Path: "Unknown path", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-10-01 06:06:45.353 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "Unknown path"
[2019-10-01 06:06:45.354 +00:00] [INF] Profile: "Unknown Profile", Path: "Unknown path", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-10-01 06:06:45.354 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "Unknown path"
[2019-10-01 06:06:45.388 +00:00] [INF] Opening channel stream from "Emby", external channel Id: "m3u_a5cb684e7b52bd68b55a1342e1e566d2f4111f42bd0c07ddf8397dc4e548428e"
[2019-10-01 06:06:45.392 +00:00] [INF] Streaming Channel m3u_a5cb684e7b52bd68b55a1342e1e566d2f4111f42bd0c07ddf8397dc4e548428e
[2019-10-01 06:06:45.399 +00:00] [ERR] Error processing request
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.MediaInfoService.OpenMediaSource(OpenMediaSource request)
   at MediaBrowser.Api.Playback.MediaInfoService.GetPlaybackInfo(GetPostedPlaybackInfo request)
   at MediaBrowser.Api.Playback.MediaInfoService.Post(GetPostedPlaybackInfo request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-10-01 06:06:46.868 +00:00] [ERR] Could not find handler for "/embywebsocket"
[2019-10-01 06:07:18.338 +00:00] [ERR] Could not find handler for "/embywebsocket"
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: 10.3.7

**Additional context**
You can try it yourself with this m3u:
```
#EXTM3U
#EXTINF:-1 group-title="Без группы" tvg-logo="http://cdn.limehd.tv/images/playlist_exo24tv.png",Эхо 24 (Новоуральск)
#EXTVLCOPT:http-user-agent=Dalvik/2.1.0 (Linux; U; Android 6.0.1;)
http://stream.novouralsk-news.ru/echotv24/live.m3u8
```

P.S. In case someone worries it's some pirated content and whatnot, the link to the stream is from the TV channel here: http://novouralsk-news.ru/%d1%8d%d1%85%d0%be-%d1%82%d0%b2-24/ at the bottom of the page

**Comment by TiraelSedai** [comment]
I think the exact moment of the stream start narrows down to this exception:


```
[2019-10-06 19:26:09.369 +00:00] [ERR] Error getting media sources
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelMediaSources(BaseItem item, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.GetMediaSourcesInternal(BaseItem item, ActiveRecordingInfo activeRecordingInfo, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetDynamicMediaSources(BaseItem item, IMediaSourceProvider provider, CancellationToken cancellationToken)
```

**Comment by JustAMan** [comment]
@TiraelSedai why did you close the issue? Is it fixed in 10.4.0?

**Comment by TiraelSedai** [comment]
No. There are shitton of separate issues that are preventing proper LiveTV from working flawlessly. When I'm trying to put my head into the logs, there are just insane amount of exceptions. I cannot see how it's useful to report that.

Best I got is my M3U work now for some time, and than randomly they don't until I reboot docker. I've tried Windows build, but it's even worse here (not LiveTV, just overall).

**Comment by abunasar** [comment]
Getting the same error here too:

`        *** Error Report ***
        Version: 4.2.1.0
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
        Operating system: Unix 4.15.0.70
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 4
        Program data path: /var/lib/emby
        Application directory: /opt/emby-server/system
        MediaBrowser.Controller.LiveTv.LiveTvConflictException: MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
           at Emby.LiveTV.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
           at Emby.LiveTV.EmbyTV.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, CancellationToken cancellationToken)
           at Emby.LiveTV.LiveTvManager.GetChannelStream(String id, String mediaSourceId, CancellationToken cancellationToken)
           at Emby.LiveTV.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, CancellationToken cancellationToken)
           at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
           at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
           at Emby.Server.MediaEncoding.Api.MediaInfoService.OpenMediaSource(OpenMediaSource request)
           at Emby.Server.MediaEncoding.Api.MediaInfoService.Post(OpenMediaSource request)
           at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 host, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
        Source: Emby.LiveTV
        TargetSite: Void MoveNext()

2019-11-17 22:53:33.891 Info HttpServer: HTTP Response 500 to 10.0.0.27. Time: 16ms. http://10.0.0.3:8096/emby/LiveStreams/Open?UserId=5f7206d01bbf4cf2b275780e2188b081&itemid=109154&maxstreamingbitrate=110000000&playsessionid=8477e204eba846c88db860f6f8189a5b&starttimeticks=00000000
2019-11-17 22:53:34.213 Info HttpServer: HTTP POST http://10.0.0.3:8096/emby/Sessions/Playing/Stopped. UserAgent: Roku/DVP-9.20 (509.20E04131A)
2019-11-17 22:53:34.215 Info HttpServer: HTTP GET http://10.0.0.3:8096/emby/Sessions?deviceId=4efabac8-574e-5008-b052-f3e5d0555e5a. UserAgent: Roku/DVP-9.20 (509.20E04131A)
2019-11-17 22:53:34.216 Info HttpServer: HTTP Response 204 to 10.0.0.27. Time: 2ms. http://10.0.0.3:8096/emby/Sessions/Playing/Stopped
2019-11-17 22:53:34.217 Info HttpServer: HTTP Response 200 to 10.0.0.27. Time: 2ms. http://10.0.0.3:8096/emby/Sessions?deviceId=4efabac8-574e-5008-b052-f3e5d0555e5a`

**Comment by JustAMan** [comment]
@abunasar are you _really_ sure you're replying to a correct issue (or with a correct copy)? Because what you sent us is an excerpt from **Emby** logs, not Jellyfin :)

**Comment by lologhi** [comment]
Jellyfin has a few `Emby` classes, like [`Emby.Server.Implementations`](https://github.com/jellyfin/jellyfin/tree/master/Emby.Server.Implementations), that's why it's throwing these errors. I also have similar error and logs with a Freebox IPTV .m3u file :

```
[2020-04-08 19:27:03.116 +02:00] [ERR] Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LiveStreamHelper.AddMediaInfoWithProbe(MediaSourceInfo mediaSource, Boolean isAudio, String cacheKey, Boolean addProbeDelay, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
[2020-04-08 19:27:03.124 +02:00] [INF] Live stream opened: {"Protocol":"Rtsp","Id":"e6654d6860f5b8e2d3901762326a4c99","Path":"rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld","Type":"Default","IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_e6654d6860f5b8e2d3901762326a4c99","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"VideoRange":"SDR","DisplayTitle":"","IsInterlaced":true,"BitRate":20000000,"IsDefault":false,"IsForced":false,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"DisplayTitle":"","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"MediaAttachments":[],"Formats":[],"Bitrate":20000000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}
[2020-04-08 19:27:03.245 +02:00] [INF] User policy for "laurent". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-04-08 19:27:03.246 +02:00] [INF] Profile: "Unknown Profile", Path: "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-04-08 19:27:03.247 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld"
[2020-04-08 19:27:03.248 +02:00] [INF] Profile: "Unknown Profile", Path: "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-04-08 19:27:03.249 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld"
[2020-04-08 19:27:03.269 +02:00] [WRN] HTTP Response 200 to "192.168.0.17". Time (slow): 0:00:04.0492792. "http://192.168.0.24:8096/Items/3b2b5a11e8d5f2337f7a1e997d6cc314/PlaybackInfo?UserId=8b0eccd1a96c4dccb6e107e4454c23b5&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
[2020-04-08 19:27:04.790 +02:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -rtsp_transport tcp -rtsp_transport udp -rtsp_flags prefer_tcp -fflags +igndts -i "rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 20000000 -bufsize 40000000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "yadif=0:-1:0,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/108c70314736d485d6e87da8b2ad6815/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcodes/108c70314736d485d6e87da8b2ad6815.m3u8" -y "/var/lib/jellyfin/transcodes/108c70314736d485d6e87da8b2ad6815%d.ts"
```

**Comment by JustAMan** [comment]
@lologhi thanks, I know that. I touched more than one point in the server code.

The reason I said "emby logs" was 
```
        Version: 4.2.1.0
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
```
Our version is 10.x, and our binary isn't named `EmbyServer.dll`.

**Comment by kopax** [comment]
@lologhi did you manage to use iptv with your freebox and jellyfin? I am testing all sort of extension (tvheadend) but nothing help. I can't even get the TV guide. Do you know why this could fail with jellyfin and if it can work with anything else ?

**Comment by lologhi** [comment]
> @lologhi did you manage to use iptv with your freebox and jellyfin? I am testing all sort of extension (tvheadend) but nothing help. I can't even get the TV guide. Do you know why this could fail with jellyfin and if it can work with anything else ?

Nope, I've stop trying, and stoped using Jellyfin.

**Comment by kopax** [comment]
@lologhi I managed to get all the channel from the freebox and others without tvheadend. I just can't get a proper xmltv up to date guide. It was fairly simple, edit the m3u file [here](http://mafreebox.freebox.fr/freeboxtv/playlist.m3u) to be like [this](https://gist.githubusercontent.com/kopax/02274770e4dc0582f7202fbdf95a5343/raw/44a22125eb19c46afff5b67f2d06bcc32425dc18/freetv.m3u), basically you must do:


```diff
- rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd
+ http://192.168.1.254:52424/freeboxtv/mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd
```

Why did you stop using jellyfin, what are you using now? If  you need help let me know.

**Comment by lologhi** [comment]
@kopax Soft was great, but I've chosen to stop stealing and storing movies. I buy blu-ray when I really want to watch something ;-)

**Comment by kopax** [comment]
@lologhi It's bad to steal, I'm glad you stopped. I personnaly use jellyfin to watch the tv using the freebox `.m3u` channels provided by free.fr so it can work from any of my devices and outside my LAN. Jellyfin is still good at that job.

**Comment by TheSleepySlee** [comment]
Seems fixed. Tried directly with this [file](http://mafreebox.freebox.fr/freeboxtv/playlist.m3u) and it's working
