### ISSUE TITLE
PIN login not working after 10.4.0 update

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin#1850]
**Describe the bug**

Loging in using PIN in local network is not working after 10.4.0 update. Tried from the same subnet as the server, with and without local network setting filed. Password works fine. 

**To Reproduce**

1. Update to 10.4.0.
2. Create user, set PIN and allow to use PIN in local network.
3. Try to login using PIN from local network.

**Expected behavior**

PIN login should be working in local subnets set in settings.

**Logs**
``` 
[2019-10-07 15:13:46.730 +02:00] [ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2019-10-07 15:13:46.733 +02:00] [INF] Authentication request for "User" "has been denied".
[2019-10-07 15:13:46.779 +02:00] [ERR] [IP] Invalid user or password entered.
```
**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Firefox
 - Jellyfin Version: 10.4.0
 - Reverse proxy: nginx

**Comment by Ky-0** [comment]
Yep same issue here, since update PIN not working no more, p/w works fine:
OS: Debian
Browser: Edge Beta (Chrome)
JF: 10.4.0

**Comment by anthonylavado** [comment]
Okay, interesting question here. What version were you both running prior to this?

There was some migration code that we had to update passwords to a newer format internally, and I’m wondering if you got “missed” by skipping a version.

**Comment by drikqlis** [comment]
I was at 10.3.7, updated by apt.

**Comment by Ky-0** [comment]
Same here

**Comment by thornbill** [comment]
When testing this, I received the following in the server logs:
```
jellyfin_1       | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin_1       |    at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
jellyfin_1       |    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
jellyfin_1       |    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
jellyfin_1       |    at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
jellyfin_1       |    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
jellyfin_1       |    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
jellyfin_1       |    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
jellyfin_1       |    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
jellyfin_1       |    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
jellyfin_1       |    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by anthonylavado** [comment]
It looks like this PR changed something about this which is causing the issue: #1677

**Comment by anthonylavado** [comment]
Specifically, this line no longer returns a true result: https://github.com/jellyfin/jellyfin/blob/aa9d7d7f04e72f71e1ccaabc3035b86ac0d0b8c0/Emby.Server.Implementations/Library/UserManager.cs

So that’s probably a good place to start looking.
