### ISSUE TITLE
Can't start Jellyfin 10.4.0 with LocalNetworkAddress and Docker

### ISSUE THREAD

**Issue by deltabweb** [jellyfin/jellyfin#1875]
**Describe the bug**
I have updated to the new version of Jellyfin recently and I can't get it to start and work properly. I am using Jellyfin with Docker and Jellyfin keeps restarting in the docker container.

**Logs**
```
[12:31:11] [INF] Processor count: 6


[12:31:11] [INF] Program data path: /config/data


[12:31:11] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web


[12:31:11] [INF] Application directory: /usr/lib/jellyfin/bin/


[12:31:12] [INF] Setting cache path to /config/cache


[12:31:12] [INF] Loading assemblies


[12:31:12] [INF] Loaded assembly LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from /config/data/plugins/Kodi Sync Queue/LiteDB.dll


[12:31:12] [INF] Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Kodi Sync Queue/Jellyfin.Plugin.KodiSyncQueue.dll


[12:31:15] [INF] Jellyfin.Plugin.KodiSyncQueue IS NOW STARTING!!!


[12:31:15] [INF] Creating DB Repository...


[12:31:15] [INF] SyncAPI Created and Listening at "/Jellyfin.Plugin.KodiSyncQueue/{UserID}/GetItems?LastUpdateDT={LastUpdateDT}&format=json" - {LastUpdateDT} must be a UTC DateTime formatted as yyyy-MM-ddTHH:mm:ssZ


[12:31:15] [INF] The following parameters also exist to filter the results:


[12:31:15] [INF] filter=movies,tvshows,music,musicvideos,boxsets


[12:31:15] [INF] Results will be included by default and only filtered if added to the filter query...


[12:31:15] [INF] the filter query must be lowercase in both the name and the items...


[12:31:17] [INF] Kestrel listening on 192.168.1.10


[12:31:17] [ERR] Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in system.xml and try again.


[12:31:17] [FTL] Error while starting server.


System.Net.Sockets.SocketException (99): Cannot assign requested address


   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)


   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)


   at System.Net.Sockets.Socket.Bind(EndPoint localEP)


   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()


   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)


   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)


   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)


   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)


   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)


   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)


   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)


   at Jellyfin.Server.Program.StartApp(StartupOptions options)


[12:31:17] [INF] Disposing CoreAppHost


[12:31:17] [INF] Disposing ActivityLogWebSocketListener


[12:31:17] [INF] Disposing SessionInfoWebSocketListener


[12:31:17] [INF] Disposing ScheduledTasksWebSocketListener


[12:31:17] [INF] Disposing SessionWebSocketListener


[12:31:17] [INF] Disposing EmbyTV


[12:31:17] [INF] Received a SIGTERM signal, shutting down
```

**system.xml**
```
<?xml version="1.0"?>
<ServerConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LogFileRetentionDays>3</LogFileRetentionDays>
  <IsStartupWizardCompleted>true</IsStartupWizardCompleted>
  <EnableUPnP>false</EnableUPnP>
  <PublicPort>8096</PublicPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <HttpServerPortNumber>8096</HttpServerPortNumber>
  <HttpsPortNumber>8920</HttpsPortNumber>
  <EnableHttps>true</EnableHttps>
  <EnableNormalizedItemByNameIds>true</EnableNormalizedItemByNameIds>
  <IsPortAuthorized>true</IsPortAuthorized>
  <AutoRunWebApp>true</AutoRunWebApp>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <CameraUploadUpgraded>true</CameraUploadUpgraded>
  <CollectionsUpgraded>true</CollectionsUpgraded>
  <EnableCaseSensitiveItemIds>true</EnableCaseSensitiveItemIds>
  <DisableLiveTvChannelUserDataName>true</DisableLiveTvChannelUserDataName>
  <PreferredMetadataLanguage>en</PreferredMetadataLanguage>
  <MetadataCountryCode>US</MetadataCountryCode>
  <SortReplaceCharacters>
    <string>.</string>
    <string>+</string>
    <string>%</string>
  </SortReplaceCharacters>
  <SortRemoveCharacters>
    <string>,</string>
    <string>&amp;</string>
    <string>-</string>
    <string>{</string>
    <string>}</string>
    <string>'</string>
  </SortRemoveCharacters>
  <SortRemoveWords>
    <string>the</string>
    <string>a</string>
    <string>an</string>
  </SortRemoveWords>
  <MinResumePct>5</MinResumePct>
  <MaxResumePct>90</MaxResumePct>
  <MinResumeDurationSeconds>300</MinResumeDurationSeconds>
  <LibraryMonitorDelay>60</LibraryMonitorDelay>
  <EnableDashboardResponseCaching>true</EnableDashboardResponseCaching>
  <ImageSavingConvention>Compatible</ImageSavingConvention>
  <MetadataOptions>
    <MetadataOptions>
      <ItemType>Book</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers />
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>Movie</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers />
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>MusicVideo</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>The Open Movie Database</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers>
        <string>The Open Movie Database</string>
        <string>FanArt</string>
      </DisabledImageFetchers>
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>Series</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheMovieDb</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers>
        <string>TheMovieDb</string>
      </DisabledImageFetchers>
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>MusicAlbum</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheAudioDB</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>MusicArtist</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheAudioDB</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>BoxSet</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers />
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>Season</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheMovieDb</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers>
        <string>FanArt</string>
      </DisabledImageFetchers>
      <ImageFetcherOrder />
    </MetadataOptions>
    <MetadataOptions>
      <ItemType>Episode</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>The Open Movie Database</string>
        <string>TheMovieDb</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers>
        <string>The Open Movie Database</string>
        <string>TheMovieDb</string>
      </DisabledImageFetchers>
      <ImageFetcherOrder />
    </MetadataOptions>
  </MetadataOptions>
  <EnableAutomaticRestart>true</EnableAutomaticRestart>
  <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
  <BaseUrl>jellyfin</BaseUrl>
  <UICulture>en-US</UICulture>
  <SaveMetadataHidden>false</SaveMetadataHidden>
  <ContentTypes />
  <RemoteClientBitrateLimit>0</RemoteClientBitrateLimit>
  <EnableFolderView>false</EnableFolderView>
  <EnableGroupingIntoCollections>false</EnableGroupingIntoCollections>
  <DisplaySpecialsWithinSeasons>true</DisplaySpecialsWithinSeasons>
  <LocalNetworkSubnets>
    <string>192.168.1.0/24</string>
  </LocalNetworkSubnets>
  <LocalNetworkAddresses>
    <string>192.168.1.10</string>
  </LocalNetworkAddresses>
  <CodecsUsed />
  <IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
  <EnableExternalContentInSuggestions>false</EnableExternalContentInSuggestions>
  <RequireHttps>false</RequireHttps>
  <IsBehindProxy>true</IsBehindProxy>
  <EnableNewOmdbSupport>true</EnableNewOmdbSupport>
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>true</IsRemoteIPFilterBlacklist>
  <ImageExtractionTimeoutMs>0</ImageExtractionTimeoutMs>
  <PathSubstitutions />
  <EnableSimpleArtistDetection>true</EnableSimpleArtistDetection>
  <UninstalledPlugins />
</ServerConfiguration>
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.0
 - Reverse proxy: direct connection

**Additional context**
I reckon my problem is due to this pull request: https://github.com/jellyfin/jellyfin/pull/1811/files
I tried the following values for `LocalNetworkAddresses` in `system.xml`:
```
<LocalNetworkAddresses />
```
and
```
<LocalNetworkAddresses>
  <string>0.0.0.0</string>
</LocalNetworkAddresses>
```
These values allow me to start Jellyfin but then I can't access the server with it's IP address anymore. When I connect to `http://192.168.1.10:8096/` I get `Invalid host` displayed in my browser and no error in logs.

**Comment by justinvoelker** [comment]
Is there any work around for this? As it stands right now, I am unable to get 10.4.0 running in Docker.

**Comment by skaro13** [comment]
Changing LocalNetworkAddresses to 0.0.0.0 in system.xml fixed it for me.

**Comment by justinvoelker** [comment]
Not sure what other settings I had been changing or trying but clearing the "Bind to local network address" setting allowed me to upgrade to 10.4.0. Thanks.

**Comment by deltabweb** [comment]
If I clear the "Bind to local network address" setting, I can start Jellyfin but I get some weird behaviour like empty settings:
![image](https://user-images.githubusercontent.com/20023887/67053681-92b56900-f19e-11e9-96f5-0c12ffa9f8e7.png)
And (more importantly), Kodi can't connect to the Jellyfin server anymore

**Comment by deltabweb** [comment]
I was (and still am) using the docker image from Linux server and I am now able to run one of their newer versions (v10.4.0-ls23).
I reckon the old image from Linux server was part of the problem.
I also changed LocalNetworkAddresses to 0.0.0.0 like @skaro13 suggested.
Problem fixed from my point of view.
