### ISSUE TITLE
Fresh install - "connection failure" after setup, on first login

### ISSUE THREAD

**Issue by DavidCWGA** [jellyfin/jellyfin#1920]
**Describe the bug**
When attempting to login to the web UI for the first time, I get "Connection Failure".

**To Reproduce**
1. Install Jellyfin on Debian 10 inside an LXC container. (In my case, on proxmox.)
2. Run through setup successfully, add a couple of libraries. (In my case, Movies and TV Shows.)
3. After setup is complete, attempt to login for the first time.

**Logs**
```
[2019-10-20 05:47:08.031 +00:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: resolvedUser
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian 10 LXC container on proxmox
 - Browser: Safari 13.0.2 on macOS 10.15
 - Jellyfin Version: 10.4.0-1 
 - Reverse proxy: no

**Comment by JustAMan** [comment]
@joshuaboniface @anthonylavado I think one of you guys said you found something funky in our code about setting up authentication providers, does this ring a bell?

**Comment by anthonylavado** [comment]
@JustAMan Yeah, this looks like what I was seeing in https://github.com/jellyfin/jellyfin/issues/1797.

**Comment by vdepagter** [comment]
Had the same issue just now on Windows.
Didn't set up a username/password during install. Added some libraries.
After that, can't login. (Found default credential main / luma somewhere)
Not after restart of service either.

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin-web/issues/591
