### ISSUE TITLE
[M3U TUNNER] IPTV Stream NOT WORK STOPPING AFTER 15sec ( HTTP1/1 500 Internal Service Error )

### ISSUE THREAD

**Issue by sdnatcher-librecloud** [jellyfin/jellyfin#1927]
Hello,

Since 2 days I try to run the TunerM3U part in livestream. Indeed, it works only for 15 to 20sec then the stream is intergraded. I tried version 10.3.5 to the last 10.4 and I also change the version ffmeg ... until the last stable and untable ... Nothing changes.

The transcoding part and the classic media part work very well. Whether I am internally or externally the problem is whole. I also install the Windows version or on linux (Ubunu Bionic) nothing changes the sympthome is identical ....

The log does not give me an error and no error transcoding ffmeg ... FYI, the flow works very well via VLC, I perform a dump to put the same User Agent ...

So, I dump via Wireshark and I notice that the flow is getting worse when I see an HTTP1 / 1 500 Internal Error packet coming from the Server to my client!

Someone would have a track because suddenly, I have to separate from JellyFin for IPTV part?

Hoping a solution because in the current state, it is unworkable ...

**To Reproduce**
1. Go to 'TV Direct'
2. Click on 'Add TunerM3U'
3. And play stream 

**Logs**
```
[2019-10-21 02:48:27.895 +02:00] [ERR] Could not find handler for "/LiveStreams/MediaInfo"
[2019-10-21 02:48:30.457 +02:00] [WRN] HTTP Response 200 to "192.168.229.100". Time (slow): 0:00:02.5725149. "http://192.168.229.242:8096/videos/eb3d670c-435c-1b75-6bc8-2f3762b00f48/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjkuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82OS4wfDE1NzE1OTM4NDMyNjA1&MediaSourceId=65a466850c9ca6dfc34127d1df0ab6b6&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=-1&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=c5d5979f1a6647aa90e3377a3bfcfa7d&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_65a466850c9ca6dfc34127d1df0ab6b6&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported"
[2019-10-21 02:48:30.799 +02:00] [ERR] Error processing request
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, IReadOnlyCollection`1 enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-10-21 02:48:30.799 +02:00] [ERR] Error processing request
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, IReadOnlyCollection`1 enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-10-21 02:48:31.567 +02:00] [ERR] Could not find handler for "/LiveStreams/MediaInfo"
[2019-10-21 02:48:40.872 +02:00] [INF] FFMpeg exited with code 0
[2019-10-21 02:49:01.599 +02:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcoding-temp/transcodes/88ac76c5e3ce171f4614180e7f2675ee.m3u8"
[2019-10-21 02:49:01.663 +02:00] [ERR] Error processing request
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, IReadOnlyCollection`1 enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-10-21 02:49:03.102 +02:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.4.0" playing "FR:BFM TV". Stopped at "30024" ms
[2019-10-21 02:49:03.111 +02:00] [INF] Live stream "65a466850c9ca6dfc34127d1df0ab6b6" consumer count is now 0
[2019-10-21 02:49:03.111 +02:00] [INF] Closing live stream "a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_65a466850c9ca6dfc34127d1df0ab6b6"
[2019-10-21 02:49:03.111 +02:00] [INF] Closing "LiveStream"
[2019-10-21 02:49:03.111 +02:00] [INF] Live stream "a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_65a466850c9ca6dfc34127d1df0ab6b6" closed successfully
[2019-10-21 02:49:03.111 +02:00] [WRN] HTTP Response 204 to "192.168.229.100". Time (slow): 0:00:01.5123464. "http://192.168.229.242:8096/Sessions/Playing/Stopped"

```
**TCPDUMP**

Packet Rest from Stream ... 

```
10823	46.281284410	163.XX.XX.XX	192.168.229.242	TCP	60	80 → 46797 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
0000   08 00 27 78 be f6 00 0d b9 43 0e 05 08 00 45 00  ..'x.....C....E.
0010   00 28 dc 90 40 00 33 06 f0 9e a3 ac 30 59 c0 a8  .(..@.3.....0Y..
0020   e5 f2 00 50 b6 cd 00 00 00 00 7b b0 ed 08 50 14  ...P......{...P.
0030   00 00 15 59 00 00 00 00 00 00 00 00              ...Y........
```

Packet Stopping stream ... (.242 is my Jellyfin Server) .100 is Webclient. 
```

10824	46.285258325	192.168.229.242	192.168.229.100	HTTP	300	HTTP/1.1 500 Internal Server Error  (text/html)
0000   00 0d b9 3f 71 6a 08 00 27 78 be f6 08 00 45 00  ...?qj..'x....E.
0010   01 1e 9b 6d 40 00 40 06 51 c4 c0 a8 e5 f2 c0 a8  ...m@.@.Q.......
0020   e5 64 1f a0 8d 92 e5 05 3a 5d ac 82 07 b3 50 18  .d......:]....P.
0030   f8 7c 4d b9 00 00 48 54 54 50 2f 31 2e 31 20 35  .|M...HTTP/1.1 5
0040   30 30 20 49 6e 74 65 72 6e 61 6c 20 53 65 72 76  00 Internal Serv
0050   65 72 20 45 72 72 6f 72 0d 0a 44 61 74 65 3a 20  er Error..Date: 
0060   4d 6f 6e 2c 20 32 31 20 4f 63 74 20 32 30 31 39  Mon, 21 Oct 2019
0070   20 30 30 3a 34 39 3a 30 31 20 47 4d 54 0d 0a 43   00:49:01 GMT..C
0080   6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78  ontent-Type: tex
0090   74 2f 68 74 6d 6c 0d 0a 53 65 72 76 65 72 3a 20  t/html..Server: 
00a0   4b 65 73 74 72 65 6c 0d 0a 54 72 61 6e 73 66 65  Kestrel..Transfe
00b0   72 2d 45 6e 63 6f 64 69 6e 67 3a 20 63 68 75 6e  r-Encoding: chun
00c0   6b 65 64 0d 0a 43 6f 6e 74 65 6e 74 2d 45 6e 63  ked..Content-Enc
00d0   6f 64 69 6e 67 3a 20 67 7a 69 70 0d 0a 56 61 72  oding: gzip..Var
00e0   79 3a 20 41 63 63 65 70 74 2d 45 6e 63 6f 64 69  y: Accept-Encodi
00f0   6e 67 0d 0a 0d 0a 61 0d 0a 1f 8b 08 00 00 00 00  ng....a.........
0100   00 04 03 0d 0a 31 63 0d 0a 73 ce cf cb 4b 4d 2e  .....1c..s...KM.
0110   c9 cc cf 53 28 4a 4d 2b 2d 4e 4d 01 00 53 63 ef  ...S(JM+-NM..Sc.
0120   a3 12 00 00 00 0d 0a 30 0d 0a 0d 0a              .......0....
```

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS x64 and Windows 7 SP1 x86
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.3.5 and 10.4
 - Reverse proxy: no

**Additional context**

**Comment by PAPAMICA** [comment]
Hello, i have same error, have you a fix for this error ?

**Comment by krevoit** [comment]
Same issue, any fix?

**Comment by hostho** [comment]
This was a network issue related to multicast for me: Check the IGMP statistics on your network devices (router/switches) and you probably see your client being removed from the group. Once I changed the IGMP proxy on my switch from v3 to v2 the router's IGMPv2 Membership Queries got to the client and the Group Membership Reports were answered correctly.
hope that helps
