### ISSUE TITLE
Error creating UserRootFolder e9d5075a-555c-1cbc-394e-ec4cef295274

### ISSUE THREAD

**Issue by anthonws** [jellyfin/jellyfin#1947]
**Describe the bug**
Cannot start JF service.

**To Reproduce**
Installed latest nighlty build.
Try starting JellyFin service.

**Expected behavior**

**Logs**

```
[2019-10-27 18:22:16.473 +00:00] [INF] Disposing "CoreAppHost"
[2019-10-27 18:22:16.490 +00:00] [INF] Received a SIGTERM signal, shutting down
[2019-10-27 18:23:20.846 +00:00] [INF] Jellyfin version: "10.4.0"
[2019-10-27 18:23:20.864 +00:00] [INF] Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2019-10-27 18:23:20.871 +00:00] [INF] Operating system: "Windows"
[2019-10-27 18:23:20.872 +00:00] [INF] Architecture: X64
[2019-10-27 18:23:20.874 +00:00] [INF] 64-Bit Process: True
[2019-10-27 18:23:20.874 +00:00] [INF] User Interactive: True
[2019-10-27 18:23:20.875 +00:00] [INF] Processor count: 8
[2019-10-27 18:23:20.876 +00:00] [INF] Program data path: "C:\ProgramData\Jellyfin\Server"
[2019-10-27 18:23:20.877 +00:00] [INF] Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2019-10-27 18:23:20.877 +00:00] [INF] Application directory: "C:\Program Files\Jellyfin\Server\"
[2019-10-27 18:23:20.987 +00:00] [INF] Setting cache path to C:\ProgramData\Jellyfin\Server\cache
[2019-10-27 18:23:21.008 +00:00] [INF] Loading assemblies
[2019-10-27 18:23:21.266 +00:00] [ERR] Error creating UserRootFolder e9d5075a-555c-1cbc-394e-ec4cef295274
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder()
[2019-10-27 18:23:21.281 +00:00] [FTL] Error while starting server.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder()
   at System.Text.Json.JsonPropertyInfoCommon`4.GetValueAsObject(Object obj)
   at System.Text.Json.JsonSerializer.HandleObject(JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreBytes(Object value, Type type, JsonSerializerOptions options)
   at Emby.Server.Implementations.Data.SqliteUserRepository.CreateUser(User user)
   at Emby.Server.Implementations.Library.UserManager.LoadUsers()
   at Emby.Server.Implementations.Library.UserManager.Initialize()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2019-10-27 18:23:21.288 +00:00] [INF] Disposing "CoreAppHost"
[2019-10-27 18:23:21.303 +00:00] [INF] Received a SIGTERM signal, shutting down
```

**System (please complete the following information):**
 - OS: Windows x64
 - Jellyfin Version: Nightlie version (27/10/2019)

**Comment by JustAMan** [comment]
@anthonws I've beautified the formatting slightly.
Also please try and check if you see same issue using latest release (10.4.1 for now I think), we made some fixes which might turn out to be related to this issue.

**Comment by anthonylavado** [comment]
@anthonws So it’s a permission error. The service account cannot write to the ProgramData folder, so it will fail and crash.

Try adding “NetworkService” to the “C:\ProgranData\Jellyfin” folder permissions.

**Comment by flashkiller999** [comment]
Hello,
I am encountering the same problem when installing jellyfin-nightly on an "Ubuntu Server 18.04 LTS".
The installation is completely new and up to date.

Here is the log of the startup of the jellyfin-service:

`Dec 01 16:48:22 srv007 systemd[1]: Started Jellyfin Media Server.
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Jellyfin version: 10.4.0
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Operating system: Linux
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Architecture: X64
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] 64-Bit Process: True
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] User Interactive: True
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Processor count: 6
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Program data path: /var/lib/jellyfin
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Application directory: /usr/lib/jellyfin/bin/
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Setting cache path to /var/cache/jellyfin
Dec 01 16:48:23 srv007 jellyfin[7919]: [16:48:23] [INF] Loading assemblies
Dec 01 16:48:24 srv007 jellyfin[7919]: [16:48:24] [ERR] Error creating UserRootFolder e9d5075a-555c-1cbc-394e-ec4cef295274
Dec 01 16:48:24 srv007 jellyfin[7919]: System.NullReferenceException: Object reference not set to an instance of an object.
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder()
Dec 01 16:48:24 srv007 jellyfin[7919]: [16:48:24] [FTL] Error while starting server.
Dec 01 16:48:24 srv007 jellyfin[7919]: System.ArgumentNullException: Value cannot be null.
Dec 01 16:48:24 srv007 jellyfin[7919]: Parameter name: source
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder()
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonPropertyInfoCommon`4.GetValueAsObject(Object obj)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.HandleObject(JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at System.Text.Json.JsonSerializer.WriteCoreBytes(Object value, Type type, JsonSerializerOptions options)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Data.SqliteUserRepository.CreateUser(User user)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.UserManager.LoadUsers()
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.Library.UserManager.Initialize()
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
Dec 01 16:48:24 srv007 jellyfin[7919]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Dec 01 16:48:24 srv007 jellyfin[7919]: [16:48:24] [INF] Disposing CoreAppHost
Dec 01 16:48:24 srv007 jellyfin[7919]: [16:48:24] [INF] Received a SIGTERM signal, shutting down
Dec 01 16:48:24 srv007 systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
Dec 01 16:48:24 srv007 systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Dec 01 16:48:24 srv007 systemd[1]: jellyfin.service: Service hold-off time over, scheduling restart.
Dec 01 16:48:24 srv007 systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1.
Dec 01 16:48:24 srv007 systemd[1]: Stopped Jellyfin Media Server.
Dec 01 16:48:24 srv007 systemd[1]: Started Jellyfin Media Server.
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Jellyfin version: 10.4.0
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Operating system: Linux
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Architecture: X64
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] 64-Bit Process: True
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] User Interactive: True
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Processor count: 6
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Program data path: /var/lib/jellyfin
Dec 01 16:48:25 srv007 jellyfin[8055]: [16:48:25] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web`

**Comment by anthonylavado** [comment]
@flashkiller999 Hey there 👋

I really don’t recommend using the Nightlies unless you are ok with things breaking or changing quickly. It’s only for testing, it is not stable.

Could you please try again with the stable install?
Do you know if the user `Jellyfin` can write to `/var/lib/Jellyfin`?

**Comment by flashkiller999** [comment]
Hi,
thanks for your reply. I understand that nightly can be broken just wanted to try it.
And thought I'd report it here.
Yes, the stable version works without a problem.
I did not create a Jellyfin-user, so if the installation is not doing this itself, the problem could be because of this.
