### ISSUE TITLE
[Request] Arch Linux Arm support

### ISSUE THREAD

**Issue by lavanoid** [jellyfin/jellyfin#1956]
Is there the possibility of having official .tar.xz packages for Arch Linux (and Arch Linux Arm)? Currently we have to bodge the .deb files and convert them into Arch-compatible ones.

I've tried doing this on an Odroid HC2 using debtap and I just get a bunch of dependency errors, and when I did manage to get Jellyfin to install once (by modifying the AUR Jellyfin package, cannot remember the exact steps I took), I kept getting coredumps/crashes related to .NET (?).

My point is, having official releases for Arch Linux would save so much hassle for those of us who don't use Debian-based systems.

**Comment by dkanada** [comment]
This program should be available on the AUR for stable and git, are those not working?

**Comment by lavanoid** [comment]
When trying to install, this is what I get:

```
lava@LHC2:~ $ yay -S jellyfin
:: There are 2 providers available for jellyfin:
:: Repository AUR
    1) jellyfin 2) jellyfin-git 

Enter a number (default=1): 1
:: There are 2 providers available for libbluray.so=2-32:
:: Repository extra
    1) libbluray 
:: Repository alarm
    2) libbluray-kodi-rbp 

Enter a number (default=1): 1
:: There are 4 providers available for dotnet-runtime:
:: Repository AUR
    1) dotnet-runtime-2.1 2) dotnet-runtime-bin 3) dotnet-runtime-preview 4) dotnet-runtime-rc 

Enter a number (default=1): 2
:: There are 4 providers available for dotnet-sdk:
:: Repository AUR
    1) dotnet-sdk-2.1 2) dotnet-sdk-bin 3) dotnet-sdk-preview 4) dotnet-sdk-rc 

Enter a number (default=1): 2
:: There are 3 providers available for dotnet-host>=3.0.0:
:: Repository AUR
    1) dotnet-host-bin 2) dotnet-host-preview 3) dotnet-host-rc 

Enter a number (default=1): 1
==> Error: Could not find all required packages:
    numactl (Wanted by: jellyfin -> dotnet-runtime-bin -> dotnet-host-bin -> lttng-ust)
```

**Comment by lavanoid** [comment]
When it tries to make the Jellyfin package, I keep getting this error:

```
MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.	
```
After trying to install Jellyfin again, the output was this:

```
Entrypoint main [big] = bundle.js
 [3] ./bundle.js 928 bytes {0} [built]
[21] ../node_modules/swiper/dist/js/swiper.esm.bundle.js + 2 modules 265 KiB {0} [built]
     |    3 modules
    + 20 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (881 KiB)
  components/themes/purple-haze/bg.jpg (293 KiB)
  components/themes/blueradiance/bg.jpg (933 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (881 KiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Done in 76.58s.
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by lavanoid** [comment]
MSBuild_pid-8389_101ab3aa6aff4365ad393b8f97d1056c.failure.txt 
```
UNHANDLED EXCEPTIONS FROM PROCESS 8389:
=====================
10/30/2019 01:24:29
System.AggregateException: One or more errors occurred. (Connection reset by peer)
 ---> System.IO.IOException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Build.Internal.CommunicationsUtilities.ReadAsync(Stream stream, Byte[] buffer, Int32 bytesToRead)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```
MSBuild_pid-8374_1eb41e2c9945438e856f717ed1475c80.failure.txt
```
UNHANDLED EXCEPTIONS FROM PROCESS 8374:
=====================
10/30/2019 01:24:29
System.AggregateException: One or more errors occurred. (Connection reset by peer)
 ---> System.IO.IOException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Build.Internal.CommunicationsUtilities.ReadAsync(Stream stream, Byte[] buffer, Int32 bytesToRead)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================

```

**Comment by dkanada** [comment]
@zentu is the Arch packager, he might know if it's our issue or not. I'm not sure the regular package will support ARM though, which might be the issue.

**Comment by z3ntu** [comment]
No idea, sorry.

**Comment by JustAMan** [comment]
@lavanoid 
As stated above, Arch is community-supported (actually @z3ntu-supported).
So unless they're willing to add ARM I don't think it could be done right now, we're too limited in our resources.

You're more than welcome to help build that package, though :)
