### ISSUE TITLE
 Error in TheTVDB System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#1971]
This exception is logged many times while rescanning library
```
[08:26:15] [ERR] Error in TheTVDB
System.FormatException: Input string was not in a correct format.
at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
at System.Convert.ToDouble(String value)
at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage)
at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by bugsyb** [comment]
+1 - found same logs on fresh install (docker)

**Comment by Ashyni** [comment]
Having a lot of this too. (docker 10.4.3)
May be related to:
https://github.com/dotnet/docs/issues/14455
number work without space inside curly braces {0}

**Comment by Bond-009** [comment]
Can you find out what item causes the error?

**Comment by agilob** [comment]
I cant reproduce it right now.

**Comment by JustAMan** [comment]
My wild guess is TVDB was returning some error message which we tried to parse as a non-error stuff.

**Comment by rchovan** [comment]
Same issue, 

```
[2021-04-10 00:02:40.366 +02:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"MigrateDisplayPreferencesDatabase"'                                                     
System.FormatException: Input string was not in a correct format.                                                                                                                                          
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)                                                                                                                    
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()                                                                                                                            
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)                                                                                                       
[2021-04-10 00:02:40.371 +02:00] [FTL] [1] Main: Error while starting server.                                                                                                                              
System.FormatException: Input string was not in a correct format.                                                                                                                                          
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)                                                                                                                    
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()                                                                                                                            
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)                                                                                                       
   at Jellyfin.Server.Program.StartApp(StartupOptions options)                        
```

**Comment by Bond-009** [comment]
@rchovan Looks unrelated, please open a new issue
