### ISSUE TITLE
Server unavailable, invalid response, too many open files in system

### ISSUE THREAD

**Issue by n-peugnet** [jellyfin/jellyfin#1982]
**Describe the bug**

Impossible to connect to Jellyfin while the application is still running.

**To Reproduce**
I don't really know how or when the problem appeared

**Expected behavior**

The app should be accessible

**Logs**

```
[2019-11-05 19:24:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:25:13.781 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:25:14.840 +01:00] [ERR] Error decoding device response
System.Net.Http.HttpRequestException: Too many open files in system ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.GetServicesList()
   at Mono.Nat.UpnpSearcher.Handle(IPAddress localAddress, UpnpDeviceInfo deviceInfo, IPEndPoint endpoint)
[2019-11-05 19:26:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:27:13.779 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:28:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:29:13.779 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:30:13.784 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:31:13.779 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:32:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:33:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:34:13.784 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:35:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:35:14.844 +01:00] [ERR] Error decoding device response
System.Net.Http.HttpRequestException: Too many open files in system ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.GetServicesList()
   at Mono.Nat.UpnpSearcher.Handle(IPAddress localAddress, UpnpDeviceInfo deviceInfo, IPEndPoint endpoint)
[2019-11-05 19:36:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
[2019-11-05 19:37:13.783 +01:00] [ERR] Failed to bind to port 1900: "Too many open files in system". DLNA will be unavailable
```
Full log: <https://public.club1.fr/other/jellyfin_011.log> (the too many open files error starts appearing at line 12391)

**Screenshots**

![apache-error](https://user-images.githubusercontent.com/23519418/68237656-d6fe9100-0007-11ea-8067-4ff8b39e41e6.png)
![jellyfin-error](https://user-images.githubusercontent.com/23519418/68237106-d6192f80-0006-11ea-8756-c58c255e09fb.png)

**System (please complete the following information):**
 - OS: Ubuntu server
 - Browser: Any
 - Jellyfin Version: 10.4.0.0
 - Reverse proxy: apache

**Additional context**

**Comment by JustAMan** [comment]
When this thing happens next time please try to see which files are opened by Jellyfin server (e.g. by `ls -l /proc/JELLYFIN_PID/fd` where `JELLYFIN_PID` is the PID of Jellyfin server).

**Comment by zeldatp151** [comment]
I am also having this issue, it restarting the server temporarily fixes it for a few hours. 
Here is a paste of the output requested https://pastebin.com/U4yiJw7c

**Comment by JustAMan** [comment]
So it'd loads of sockets left open... now I wonder what sockets are those. @cvium @Bond-009 do you have any ideas?

**Comment by PrplHaz4** [comment]
Bonkers - if you disable the DLNA server and Automatic Port Mapping (Networking) does it still happen?  Is there anything interesting in the logs prior to the Failed to bind to port 1900 error?

Looks like it might be trying to find an announce port but can't get one for whatever reason...

**Comment by PrplHaz4** [comment]
Bonkers - if you disable the DLNA server and Automatic Port Mapping (Networking) does it still happen?  Is there anything interesting in the logs prior to the Failed to bind to port 1900 error?

Looks like it might be trying to find an announce port but can't get one for whatever reason...

**Comment by Bond-009** [comment]
@JustAMan Well we keep every HttpClient we ever use...

**Comment by JustAMan** [comment]
So what 
```
lsof -P -p `pidof jellyfin`
``` 
shows when it has so many handles open?

**Comment by zeldatp151** [comment]
I am currently away from home on travel, but I will try to get the requested information as soon as possible.

**Comment by zeldatp151** [comment]
> So what
> 
> ```
> lsof -P -p `pidof jellyfin`
> ```
> 
> shows when it has so many handles open?

COMMAND  PID     USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
jellyfin 873 jellyfin  cwd   unknown                      /proc/873/cwd (readlink: Permission denied)
jellyfin 873 jellyfin  rtd   unknown                      /proc/873/root (readlink: Permission denied)
jellyfin 873 jellyfin  txt   unknown                      /proc/873/exe (readlink: Permission denied)
jellyfin 873 jellyfin NOFD                                /proc/873/fd (opendir: Permission denied)


Also, I want to mention that the issue is getting worse, I increased my open file limit originally to 500k, and it worked ok for about 3 days, then I restarted the server, and it was broken within a day, that is when I made my first post here about it. after that I increased my limit to 999999, and it worked fine for a week, and now it works for a few hours after a reboot.

**Comment by JustAMan** [comment]
This `lsof` doesn't showing what I expected...
Try this:
```
for pid in `pidof jellyfin`; do sudo lsof -P -p $pid; done
```

**Comment by zeldatp151** [comment]
Here is the pastebin for that output, I have sanitized my username and system names.
https://pastebin.com/HGEWk2Dj

**Comment by JustAMan** [comment]
There seem to be slightly less than 500 files open, and nothing that stands out, which is strange.
Can you let it grind to "too many open files", then gather same `lsof` thingy?..

**Comment by zeldatp151** [comment]
OK, So pastebin wouldn't let me paste this becaues it was too large, and it broke justpasteme, os here it is on privatebin, just know that this will expire in 23 hours, and it takes a minute to load
https://privatebin.net/?ce604df1ed866350#9F4ZMhCeJtwFQjnsSpRUKpRDG3gVUedYH4mL3XLRcMXk

**Comment by JustAMan** [comment]
Is it possible for you to uninstall Anime plugin? I guess some of those issues might be related to that.

**Comment by zeldatp151** [comment]
I could, but I would really prefer not to, a large portion of my library gets it's metadata via the anime plugin, as the material is either not on tvdb, or it is wrong on tvdb.

**Comment by JustAMan** [comment]
Let's try uninstalling it temporarily and see if it's related to that. If it is, we're closing at pinpointing the issue.

**Comment by AnotherDevlop** [comment]
Same problem here. Although it doesn't seems directly related to aniDB, since I have open a lot of socket files to a unknown ip too. However, I will disable aniDB and see if happen, and report here in a couple of days.

Logs

Problem seems to be on line 2008, "System.IO.IOException: Function not implemented" can be ignored safely since the fs, where movies are, is readonly.
[jellyfin_log_sanitized.txt](https://github.com/jellyfin/jellyfin/files/4467644/jellyfin_log_sanitized.txt)
[jellyfin_ls_fd_log.txt](https://github.com/jellyfin/jellyfin/files/4467645/jellyfin_ls_fd_log.txt)
[jellyfin_lsof_log.txt](https://github.com/jellyfin/jellyfin/files/4467646/jellyfin_lsof_log.txt)

System:

    OS: Ubuntu server 18.04
    Browser: Firefox
    Jellyfin Version: 10.4.3.0
    Reverse proxy: apache

**Comment by zeldatp151** [comment]
I should add that mine stopped having the issue with the anime plugin update a few weeks ago.
Or it has at least stopped crashing, I should check the open files to see if anything weird is going on still.
 
 
  On Sun, Apr 12, 2020 at 10:06 PM, AnotherDevlop<notifications@github.com> wrote:   


Same problem here. Although it doesn't seems directly related to aniDB, since I have open a lot of socket files to a unknown ip too. However, I will disable aniDB and see if happen, and report here in a couple of days.

Logs

Problem seems to be on line 2008, "System.IO.IOException: Function not implemented" can be ignored safely since the fs, where movies are, is readonly.
jellyfin_log_sanitized.txt
jellyfin_ls_fd_log.txt
jellyfin_lsof_log.txt

System:
OS: Ubuntu server 18.04
Browser: Firefox
Jellyfin Version: 10.4.3.0
Reverse proxy: apache

**Comment by JustAMan** [comment]
> Problem seems to be on line 2008, "System.IO.IOException: Function not implemented" can be ignored safely since the fs, where movies are, is readonly.
> [jellyfin_log_sanitized.txt](https://github.com/jellyfin/jellyfin/files/4467644/jellyfin_log_sanitized.txt)
> [jellyfin_ls_fd_log.txt](https://github.com/jellyfin/jellyfin/files/4467645/jellyfin_ls_fd_log.txt)
> [jellyfin_lsof_log.txt](https://github.com/jellyfin/jellyfin/files/4467646/jellyfin_lsof_log.txt)

This indeed seems the Anime plugin problem
@jellyfin/backend can we have a look at it and see if it's not properly disposing connections? There's hundreds of those in `CLOSE_WAIT` state there.

**Comment by AnotherDevlop** [comment]
Like I said, there is the report without anime plugin. Still happens, now the culprit is opensubtitles plugin. 

Logs
[jellyfin_log_2_sanitized.txt](https://github.com/jellyfin/jellyfin/files/4472958/jellyfin_log_2_sanitized.txt)
[jellyfin_ls_fd_log_2.txt](https://github.com/jellyfin/jellyfin/files/4472959/jellyfin_ls_fd_log_2.txt)
[jellyfin_lsof_log_2.txt](https://github.com/jellyfin/jellyfin/files/4472960/jellyfin_lsof_log_2.txt)
