### ISSUE TITLE
Cannot set a schedule for the trakt tasks

### ISSUE THREAD

**Issue by henryford** [jellyfin/jellyfin#1995]
When trying to set a schedule for any of the Tasks the Trakt Plugin offers (Import Playstates from Trakt and Sync library to trakt.tv) it does not work. Neither does the triggering of the "Import Playstates from Trakt"-Task work from library scans. Manually running the tasks does work.

**To Reproduce**

1. Go to 'Settings' -> 'Scheduled Tasks' (with the Trakt plugin enabled)
2. Click on either the Task "Import Playstates from Trakt" or "Sync library to trakt.tv"
3. Set any schedule for the task
4. Save

**Expected behavior**
Scheduled task should be configued according to the settings set in the config screen.

**Logs**
```
[2019-11-08 21:43:00.256 +01:00] [ERR] Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: Task not found
   at MediaBrowser.Api.ScheduledTasks.ScheduledTaskService.Post(UpdateScheduledTaskTriggers request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
**System (please complete the following information):**
 - OS: Docker (on Debian 10.1)
 - Browser: Chrome, Firefox
 - Jellyfin Version: 10.4.0
 - Reverse proxy: nginx

**Additional context**
Reinstalled the plugin to confirm that this is not from a borked install.

**Comment by cvium** [comment]
Many changes have been since this was opened, so I think it's fixed.
