### ISSUE TITLE
User cant login

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#1997]
I just upgraded jellyfin (It was from 10.3 something) and now my user cant login.  The password is just numbers.

Debian Buster,  Jellyfin 10.4.1-1

Here is the log when the user tries to login

```

Nov 08 21:17:07 PC jellyfin[29416]: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    --- End of inner exception stack trace ---
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Threading.Tasks.ValueTask`1.get_Result()
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Threading.Tasks.ValueTask`1.get_Result()
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Threading.Tasks.ValueTask`1.get_Result()
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Nov 08 21:17:07 PC jellyfin[29416]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
Nov 08 21:17:07 PC jellyfin[29416]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
Nov 08 21:17:07 PC jellyfin[29416]:    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
Nov 08 21:17:07 PC jellyfin[29416]:    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetTmdbSettings(CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at MediaBrowser.Providers.Tmdb.Movies.TmdbSearch.GetSearchResults(ItemLookupInfo idInfo, String searchType, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
Nov 08 21:17:07 PC jellyfin[29416]:    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
Nov 08 21:17:10 PC jellyfin[29416]: [21:17:10] [ERR] Error processing request
Nov 08 21:17:10 PC jellyfin[29416]: System.ArgumentException: String doesn't contain enough segments
Nov 08 21:17:10 PC jellyfin[29416]: Parameter name: storageString
Nov 08 21:17:10 PC jellyfin[29416]:    at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
Nov 08 21:17:10 PC jellyfin[29416]:    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
Nov 08 21:17:10 PC jellyfin[29416]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

```

**Comment by Derkades** [comment]
Are you logging in through the web interface or through a different client?

**Comment by gerroon** [comment]
I was logging in through the web interface. I wonder if the whole password being just numbers was the issue?

**Comment by nwithan8** [comment]
It appears the API was remapped with the latest server update, but client apps have not been updated accordingly. The web interface works, but client apps are at the moment unable to connect.

**Comment by JustAMan** [comment]
Looks related to what is described here: https://github.com/jellyfin/jellyfin/issues/1858#issuecomment-557504563

**Comment by charithjayasanka** [comment]
Facing the same issue over here.
