### ISSUE TITLE
Jellyfin not starting with windows startup

### ISSUE THREAD

**Issue by torrentguy** [jellyfin/jellyfin#2002]
Ive even tried to put a shortcut in the startup programs folder of windows but it still doesn't start automatically

**To Reproduce**

1. install jellyfin as a service

**Expected behavior**

It's expected to start the tray icon and start the service itself

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.4.1

**Comment by anthonylavado** [comment]
If you install Jellyfin as a service, it runs automatically when the computer is on. You don’t have to open it manually.

**Comment by anthonylavado** [comment]
Are you sure you set it up as a service? You can check in the Services console(Start>Run> services.msc ) and look for “JellyfinServer”.

**Comment by anthonylavado** [comment]
Also, though the tray icon can indeed start/stop the service, I haven’t tested that functionality completely yet. This is why it doesn’t make shortcuts for you when you’ve selected “Service”.

**Comment by torrentguy** [comment]
Can't find it in services.msc, gonna try reinstall it as a service

**Comment by torrentguy** [comment]
and btw, i just love what you guys did, fuck emby with their premium shit :D

**Comment by torrentguy** [comment]
if i run the installer again it won't give me the option to install it as a service, if i deinstall it will i keep my settings? or where are all my settings saved?

**Comment by torrentguy** [comment]
I installed it as a service and it still doesn't start with windows

**Comment by torrentguy** [comment]
Even when i click "start" on the service it doesn't work

**Comment by anthonylavado** [comment]
Could you pull up the logs? Usually when something like this happens, it’s because there’s two copies of Jellyfin trying to run at the same time

**Comment by torrentguy** [comment]
This is the most recent log
[log_20191113.log](https://github.com/jellyfin/jellyfin/files/3839974/log_20191113.log)

**Comment by anthonylavado** [comment]
@torrentguy Okay, it looks like it's having an error reading the database, probably because something else is trying to use it.

Let's just make sure we're clear here, review this:
* In the services list, look for "JellyfinServer"
* If the service is running, please stop it
* If the tray app is open, right click it and uncheck "Autostart"
* Close the tray app
* Check for any other copy of Jellyfin.exe running (either by yourself, or from a start-up shortcut, use Task Manager to check and end them)

Once that's all set:
* Start the JellyfinServer service

If it works, then whatever else was starting it is the problem. If you still have startup shortcuts, please delete them. If the tray app comes back on your next restart, please disable it as I mentioned above.

There's a reason I don't make a shortcut for the tray app when you install it as a service, and that's because I haven't tested that yet 🙂

**Comment by torrentguy** [comment]
still doesn't work, i did all your steps and then tried to run the service but it seems to not be active since i can't connect.

**Comment by PrplHaz4** [comment]
@torrentguy 
Here's the relevant part of the log.  Sounds like you're going to have to dig in a bit to find out why it's having trouble accessing the sqlite dbs.
- Make sure you have plenty of free disk space on this drive
- Make sure you have free RAM
- Check database sizes in `"C:\ProgramData\Jellyfin\Server\config\data"` to see if any are blowing up
- Double check which user the service is running as

```
[2019-11-13 00:55:18.121 +01:00] [FTL] Error while starting server.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Comment by mobamoba** [comment]
Jellyfin Tray won't start on my system either (console works fine). Here's the error from Event Viewer:

Description: A .NET Core application failed.
Application: JellyfinTray.exe
Path: C:\Program Files\Jellyfin\Server\JellyfinTray.exe
Message: Error:
  An assembly specified in the application dependencies manifest (JellyfinTray.deps.json) was not found:
    package: 'System.Management', version: '4.6.0'
    path: 'runtimes/win/lib/netcoreapp2.0/System.Management.dll'

**Comment by torrentguy** [comment]
All i did to kinda fix it was, create a shortcut of the jelyfin.exe file and put it in your startup folder, itll always have a command prompt open but that doesn't matter to me since im using a server pc anyway.

**Comment by PlanetSmasher** [comment]
I have also problems at installing Jellyfin 10.4.1.
My Problem exists on Windows 10 (10.0.17763.805) and on Windows Server 2012 R2.

I can install Jellyfin as normal Basic Install without any trouble, but as I want the Windows Service via Installer, there are errors.
As I think the Issue might be nssm.exe as It creates a Windows service without errors but as it wants to change the user to Network Service it wont work.

Maybe it is because I got a German Language Pack installed, so my Network Service can be selected via UI as "Netzwerkdienst".


I got the screenshots attachted.

![screenshot1](https://user-images.githubusercontent.com/10109247/69225767-48e5e700-0b7f-11ea-9996-a1a87aba5234.png)
![screenshot2](https://user-images.githubusercontent.com/10109247/69225769-48e5e700-0b7f-11ea-8e32-93aca591d53b.png)

Further Information:
On Windows Server 2012R2 was no Jellyfin ever installed.
I tried this as a proof that this is not caused due to some misconfiguration on my main "streaming" PC

I also got no entry in the Application Eventlog as the Error occurs.

**Comment by anthonylavado** [comment]
> Maybe it is because I got a German Language Pack installed, so my Network Service can be selected via UI as "Netzwerkdienst".

@PlanetSmasher This is probably it. We want to re-do the service install to be "native" in future to avoid issues like this. I think you can manually set it in services.msc for the meanwhile though.
