### ISSUE TITLE
Error in "TheTVDB" System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#2006]
**Describe the bug**
Discovered the error in the issue Title in my log.

**To Reproduce**
Unsure.  Perhaps there was a network/DNS outage at the time.

**Expected behavior**
Not get NREs in the log

**Logs**
```
[2019-11-12 10:39:32.641 -05:00] [ERR] Error in "TheTVDB"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2019-11-12 10:39:42.662 -05:00] [ERR] "TvdbEpisodeImageProvider" failed in GetImageInfos for type "Episode"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2019-11-12 10:39:48.795 -05:00] [INF] Starting Library Sync...
[2019-11-12 10:39:48.795 -05:00] [INF] "LIBRARYSYNC" Added 0 items:  ""
[2019-11-12 10:39:48.970 -05:00] [INF] "LIBRARYSYNC" Updated 1 items:  "ba129f5094eff1d83119c186f07be62c"
[2019-11-12 10:39:48.970 -05:00] [INF] "LIBRARYSYNC" Removed 0 items:  ""
[2019-11-12 10:39:48.970 -05:00] [INF] Finished Library Sync Taking "00:00:00.1750222"

```
**System (please complete the following information):**
 - OS: Fedora 31
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by tyhawk** [comment]
I've been having the same issue for a while now (issue #1771) and have not been able to fix or workaround it... or even find the cause of it.

**Comment by brianjmurrell** [comment]
Maybe something to do with looking up episodes of shows that don't have data on TheTVDB?

**Comment by tyhawk** [comment]
@brianjmurrell I've kind of ruled that out. One of the tests I did was (on a fresh install) set language to English and country to US. Same for the metadata of the library. In the library I put only one or two shows, both of which had English metadata. I got the same error. Even renaming the files to the exact specifications for series in the Jellyfin documentation and doing the same, again on a fresh install, gave me the same error.

**Comment by brianjmurrell** [comment]
Well, ultimately, these kinds of exceptions and stack traces in the log indicate _unhandled_ error conditions.  The first step in resolving this kind of thing is to add code to expect and handle the error condition and provide some useful information about what was being done and what failed to happen, etc.

Same goes for the numerous _Connection Refused_ unhandled exceptions I see in the log.

**Comment by tyhawk** [comment]
@brianjmurrell Hopefully, error handling is extended soon so we can figure out what is going wrong. I don't even see DNS queries from Jellyfin to TheTVDB and TheMovieDB in my Pihole logs when I'm running a library scan or identifying manually.

**Comment by telans** [comment]
On a fresh jellyfin install, I'm coming across this exact error. Unraid docker, 10.4.2

The media library scans fail at this and eventually become "cancelled". Each scan I invoke will only find a few episodes of a random show and stop (not even a whole season).

I am seeing `[INF] Creating virtual missing/unaired episode` in the logs before `[ERR] Error in TheTVDB`, yet "Display missing episodes within seasons" is not enabled. Are those two linked or am I misenterpreting what it is doing?

On a side note - should I be seeing what files are being scanned in the logs too? I see no reference to what is being scanned, each scan just hangs for a few minutes before terminating.

**Comment by tyhawk** [comment]
@telans I found a solution for this and posted it in issue #1771. Perhaps it will solve your issues as well. Could you test this and report back?
