### ISSUE TITLE
After 10.4.1 can't add custom images

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin#2009]
**Describe the bug**
I have 10.4.1 and using baseurl = /jellyfin and also nginx to redirect to www.domain.com/jellyfin from the internet.

Since the upgrade I can't add custom images (from disk) to any tvshows (I assume is for movies as well). For example if JF can't find a thumb of a tvshow and I would like to add one from disk JF it's just spinning and doesn't complete the process: (tvshow / edit images ). 

If I remove the baseurl it works and I can add the custom images.

**To Reproduce**
Go to a TV-Show.
Click on edit images
Click on the "+" and chose a image file from disk

**Expected behavior**
Image from disk is picked up from disk and upload it into JF.
**Logs**
```
[2019-11-13 13:28:21.883 +00:00] [ERR] Error processing request
System.ArgumentException: Requested value 'Images' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at MediaBrowser.Api.Images.ImageService.Post(PostItemImage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.4.1
 - Reverse proxy: nginx

**Additional context**
If I remove the baseurl it works and I can add the custom images. This was working on 10.4.0.

**Comment by cesalo** [comment]
@Bond-009 Can this be the same reason of: https://github.com/jellyfin/jellyfin/issues/1994

and also just had a similar issue: Installed the plugin: TMDb Box Sets and tried to change the min # of movies in settings of the plugin and it didn't save and was just spinning. In order to change this I had to remove the baseurl and restart.

Is is possible all these 3 issues have the same root cause?

**Comment by Bond-009** [comment]
I’m not sure, but a fix for this issue was merged, so you can test it with the nightly version.

**Comment by cesalo** [comment]
@Bond-009 sorry if this is a silly question but how can i test this with docker .. was trying to check using the tags but all of them are from 18 days ago: https://hub.docker.com/r/jellyfin/jellyfin/tags
Any advice is appreciate it.
Thanks.

**Comment by JustAMan** [comment]
ping @nvllsvm

**Comment by cesalo** [comment]
This is not fixed. I couldn't test in 10.4.2 but the issue persist in 10.4.3.

**Comment by anthonylavado** [comment]
I've just tested in 10.4.2 and 10.4.3 with a movie and this worked. Testing TV Shows right now...

**Comment by anthonylavado** [comment]
Yeah, just worked with a TV Show. Are you still getting an error? Could you share the logs around this?

**Comment by cesalo** [comment]
Apologies @anthonylavado you're right it seems is fixed. Not sure why it failed when I tested previously.
I've tested 2 different tvshows with baseurl /jellyfin and it worked fine.

**Comment by dkanada** [comment]
oops
