### ISSUE TITLE
jellyfin 500 photo amount limitation?

### ISSUE THREAD

**Issue by theoldnewb** [jellyfin/jellyfin#2036]
**Describe the bug**
Hello everybody,

This is my first online bug report,  I hope this isn't a RTFM issue and I haven't screwed it up completely.
jellyfin only seems to show/browse excatly 500 (0-499) photos. More then 500 photos will show photo 0. To clarify, The thumbnail preview in the browser shows all photos, If you scroll a while and click on photo > 499 then the first photo (0) is displayed.

**To Reproduce**
1. Use a fresh empty clean jellyfin with no other libraries etc.
2. Take more then 500 photos and put them in "the" only photo library. You can also quickly generate the images with ImageMagick like so:
#!/bin/bash
for i in {0..1023}; do
   echo generating $i...
   convert -size 1024x1024 -pointsize 72 xc:black -gravity center  -background orange -splice 0x100 -annotate +0+2 "BAM $i" image-$i.jpg
done
3. Use the folder that contains the images in jellyfin as a photo library.
4. Let jellyfin process the library.
5. Go to the photo library to view the images.
6. Click on the thumbnail for picture 499 and picture 499 should show up.
7. Click on the thumbnail for picture 500 and you will find that picture 0 is displayed.

**Expected behavior**
I kind of expect to be able to see all photos. Not just 500.

**Logs**
The logs are filled with the following, but the timestamp is not correlated to my clicking on the images.
[2019-11-21 22:14:35.368 +01:00] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options) in /home/xyz/build/jellyfin/src/jellyfin-10.4.1/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 332
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod) in /home/xyz/build/jellyfin/src/jellyfin-10.4.1/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 272
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod) in /home/xyz/build/jellyfin/src/jellyfin-10.4.1/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 171
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping) in /home/xyz/build/jellyfin/src/jellyfin-10.4.1/Mono.Nat/Upnp/UpnpNatDevice.cs:line 230
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device) in /home/xyz/build/jellyfin/src/jellyfin-10.4.1/Emby.Server.Implementations/EntryPoints/ExternalPortForwarding.cs:line 248

**Screenshots**

![capture_1](https://user-images.githubusercontent.com/58051505/69380176-2d2f2d80-0cb2-11ea-9571-9be7b95de949.png)
![capture_2](https://user-images.githubusercontent.com/58051505/69380188-302a1e00-0cb2-11ea-868a-96d21e344a31.png)

**System (please complete the following information):**
 - OS: [Server is Arch Linux, https://aur.archlinux.org/packages/jellyfin/]
 - Browser: [Windows 10 Firefox, Samsung Galaxytab]
 - Jellyfin Version: [e.g. 10.4.1-1]
 - Reverse proxy: [no reverse proxy or ssl or anything just plain http]

**Additional context**

**Comment by anthonylavado** [comment]
@theoldnewb First off - this is a spectacular write up. **Thank you.**

Second - I don't think we've had anyone report this yet, and we certainly weren't aware of it. We'll look into it!

**Comment by theoldnewb** [comment]
Thank you very much @anthonylavado.
I wish I could be of more help. But my C# knowledge is almost non existent.
However, grepping through the source code for the magic "500" revealed:
jellyfin-web-10.4.1/src/components/playback/playbackmanager.js: Limit: 500
Increasing that number to 5000 made the other images show up as well :-)
This kind of works for me. It would be nice to have it neatly configurable.
Sadly, I wouldn't even know where to begin hacking that in.
However, I am very pleased with my tweaked jellyfin.
As far as I am concerned, this issue could be closed.

**Comment by Bond-009** [comment]
Seems like this is a jellyfin-web issue
