### ISSUE TITLE
dlna bug

### ISSUE THREAD

**Issue by Herbertzz** [jellyfin/jellyfin#2053]
**Logs**
```
[2019-11-25 09:36:41.036 +00:00] [ERR] Error processing request
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Emby.Dlna.Api.DlnaServerService.GetPathValue(Int32 index)
   at Emby.Dlna.Api.DlnaServerService.PostAsync(Stream requestStream, IUpnpService service)
   at Emby.Dlna.Api.DlnaServerService.Post(ProcessContentDirectoryControlRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.2
 - Reverse proxy: no

**Comment by PrplHaz4** [comment]
I'm no longer seeing this issue after updating to 10.4.3
