### ISSUE TITLE
Scan media library getting stuck at 38.4% maxing out 1 cpu 100%

### ISSUE THREAD

**Issue by fastjp** [jellyfin/jellyfin#2059]
Started after last update on linuxserver.io docker on unraid
When try to stop scan stay's on stopping scan with 1 cpu 100% no change
Error in log: `[ERR] Error processing request: A task was canceled.`

<details><summary>Jellyfin log</summary>

```
[21:55:48] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[21:55:48] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[21:55:50] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[21:55:50] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[21:56:23] [INF] Creating virtual missing/unaired episode Burden of Truth 3x1
[21:56:23] [INF] Creating Season Season 3 entry for Burden of Truth
[21:56:23] [ERR] No metadata found for 3
MediaBrowser.Model.Net.HttpException: Not Found
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
```

</details>

**Comment by telans** [comment]
I think a lot of people are having issues with scans currently.

See #1771, #2006, #2047

**Comment by dustin-Optfit** [comment]
Also having library scan issues
https://www.reddit.com/r/jellyfin/comments/e1o4sw/library_scan_not_working_after_update/

**Comment by scurrvy2020** [comment]
yeah, this makes it unusable.  rolling back to 10.4.1 seems like the best option for now.

**Comment by JustAMan** [comment]
@Bond-009 @cvium does this ring a bell for you?

**Comment by telans** [comment]
Started coming across the exact issue.

Unraid 10.4.2 Docker

```
%CPU  %MEM     TIME+ COMMAND                                                                    
100.0   4.0   7:02.20 dotnet
```

**Comment by fastjp** [comment]
There has been 1 update since, it has NOT fixed the library scan freeze issue.

**Comment by chuckofthenorth** [comment]
Not piling on, but in case it is helpful...   I can confirm I am seeing this same issue on version 10.4.2 running on Linux Docker:
**Host:** Kernel: 5.0.0-36-generic x86_64 bits (Peppermint 10)
**Docker version** 19.03.5, build 633a0ea838
**Image:** jellyfin/jellyfin:latest Digest: sha256:dce24426c4a2ea7770ad9a662482f21f606f0bce4ea50cf4bc4ac8f14d7eed78

I can confirm that trimming multiple space characters in all filenames helped it get further, but something else is still causing the issue. I also tried setting TVdb to the lowest priority in the tracker config, but it still stalls.  I don't see anything specific in the logs to help, but I'm still staring at them so if I do, I'll update.

**Comment by telans** [comment]
The fix for the pinned core/stuck search issue seems to be downgrade to 10.4.1

**Comment by aswathraja** [comment]
I am using the macOS wrapper running the Server App but i get the same issue even after downgrading to 10.4.1 or even 10.4 on macOS Catalina (10.15.1). Any help or do i need to do something differently?

**Comment by Barborica-Alexandru** [comment]
Downgrading to 10.4.0 and then upgrading to 10.4.1 leads to clients no longer connecting to the server (debian package). Only web interface works. Downgrading back to 10.4.0 solves both issues for now.

**Comment by viggy96** [comment]
I have similar issue on Docker version 10.4.2. Downgrading to 10.4.1 solves the library scan issue.

**Comment by chuckofthenorth** [comment]
To add to my earlier post.  Just starting out with Jellyfin after years of Plex, so I have a large library.  

While 10.4.2 has the issue described above, as suggested, I pulled 10.4.1 and ran it on a clean library, I noticed it was not as accurate at scraping image clipart from TVdb and needed many manual identify assists.  I'm going to stick with 10.4.1 for now (cause it doesn't pooch the CPU), but there is obviously some good code in 10.4.2 to not abandon.  If I can be of any help in testing/diagnosing, please ask and I'll run the test-case for you.

**Comment by gllyrjones** [comment]
I have the same issue, scan hangs at 72% I'm running docker Ubuntu 18

**Comment by JustAMan** [comment]
Can anyone try if the issue persists if you roll back https://github.com/jellyfin/jellyfin/pull/1929?

**Comment by supercore23** [comment]
I'm using the linuxserver Jellyfin docker on unRaid. I tried process of elimination to pinpoint what directory was causing the issue. I separated my anime folders from standard shows and tried scanning them separately. Standard shows processed fine but the anime directory did not. I pulled all the folders out of the anime directory and added them back in one at a time until it hung again. After testing one folder at a time, my folder for Ghost in the Shell: Standalone Complex hung. None of the other folders did. 

I then added back in all of the TV shows, anime, and movies and ran a library scan again. This time everything processed cleanly and there were no hangs. 

Next step was to inspect the contents of the Ghost in the Shell folder. Turns out, there was a "Bonus features" folder included that contained music files, artwork, etc... I removed this folder and added the episodes back to the main Anime folder one at a time running the library scan each time. 50+ episodes later and everything is imported. I ran another media library scan to see if it would hang and it did not. 

I would recommend everyone having this issue check their folders to make sure there are no extra files in there that might be throwing the media scan for a loop because they're not the file type JF is expecting to be there.

**Comment by dustin-Optfit** [comment]
@supercore23 In my case it was Mixed Content libraries that was causing issues.

**Comment by cvium** [comment]
@supercore23 can you paste the entire file tree of the extras?

**Comment by supercore23** [comment]
@cvium I'm not sure how to paste the file tree. The filetypes are:  mp4, nfo, bif, jpg, and mp3. There were some bif and mp3 files in the original season folders as well but I did not copy them back into the final folder. It's possible those files in the season folder may have been the culprit as well but I didn't think to test that separately.

**Comment by gllyrjones** [comment]
I've rolled back to 10.4.1 and its fine.

**Comment by lord-carlos** [comment]
Seems to have fixed it for me.
Thank you @cvium :-* 💋

**Comment by chuckofthenorth** [comment]
10.4.3 resolved it for me too.

**Comment by WWWesten** [comment]
Scans stuck on non-ASCII characters and spaces in library_name in Jellyfin\Server\root\default\library_name
Quick and dirty solution: rename all library names to respective ASCII names for example English names.

**Comment by dkanada** [comment]
What's interesting is that unicode characters are fine in music tags, so it must just be a file thing.

**Comment by JustAMan** [comment]
@WWWesten did you make a separate issue about non-ASCII chars?
