### ISSUE TITLE
MacOS Install - Can't Access Web UI 

### ISSUE THREAD

**Issue by brandonjones24** [jellyfin/jellyfin#2100]
I followed the steps to install jellyfin on two of my Macs, and both are exhibiting the same issue. I believe this is different from issue 1553 as I am not using docker.

Upon launching the app, I see the icon in the menu bar and can access the menu. I receive an error (not found) when attempting to access the Web UI via localhost or IP. I've opened the port on my network as well, and have tested with the mac firewall disabled and On with Jellyfin allowed.

Most interesting, I am unable to access logs or configuration files. My suspicion is that neither exist.

**Comment by JustAMan** [comment]
ping @anthonylavado

**Comment by anthonylavado** [comment]
Whoops - sorry I missed this.

@brandonjones24 What version of macOS are you using?

When you launch the .app and the icon appears in the menu bar, does `Jellyfin` show up in Activity Monitor?

**Comment by brandonjones24** [comment]
Thanks for your response!

MacOS Catalina 10.15, Ive also tested on another machine running the 10.15 Beta.

All I see in activity monitor is the jellyfin.org process: https://www.screencast.com/t/aoRFJ4Zy71Z6

**Comment by anthonylavado** [comment]
Hrm that’s the website in a browser if you JF it open. We don’t have anything else names Jellyfin.org...

Sounds like it’s not starting up for you for some wild reason.  I just uploaded the newest version today, thought it _shouldn’t_ be different, could you try it out?

Thanks 🙏

**Comment by brandonjones24** [comment]
Sorry for the delay! As you suspected, installed and same issue. Whats strange is it wouldnt let me replace the application file until I "quit" from the menu. That worked.

**Comment by anthonylavado** [comment]
Ah okay. You’ll want to use the portable version until the port of the new app wrapper is completed then. You’ll have a terminal window on the screen when you run it, but you can minimize it or hide it with the Window menu.

So:
- download ZIP: https://repo.jellyfin.org/releases/server/macos/stable/
- Extract to a folder
- Find “Jellyfin” inside
- Double Click, and terminal window will appear, the app will start

**Comment by anthonylavado** [comment]
Also - thank you so much for trying! The current wrapper was the first few lines of Swift I’ve ever written, and I’m not a programmer by trade. The new thing adapts some existing code, so it’ll be much better in the end.

**Comment by jonohewitt** [comment]
I'm getting the same issue here, running Catalina 10.15.2 and Jellyfin 10.4.3. I tried the portable installation instructions above but ran into a system block saying Jellyfin can't be opened as the developer cannot be verified. I tried going around it with a right click open but then get another block saying “System.Private.CoreLib.dll” cannot be opened because the developer cannot be verified. 

I managed to get it to run by disabling the protections altogether, using 'sudo spctl --master-disable', and re-enabled them straight away afterwards with 'sudo spctl --master-enable'. 

I also tried doing this with the 10.5.0 Nightly from this morning but got the following error:

Error whilst attempting to create folder
System.IO.IOException: The file '/Applications/jellyfin_10.5.0/jellyfin' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)

**Comment by anthonylavado** [comment]
The nightly is super broken right now so I don’t recommend it. That’s why it’s a nightly :-)

You shouldn’t have to have the protections off for this to work though. I wonder why this keeps failing... I’ve got a system here that I don’t use for development, just strictly regular use - and it runs there with little intereference. I had to right click>open, and that was it...

**Comment by anthonylavado** [comment]
@jonohewitt Did you try the .app, or only the portable version? The app should be signed, as I’ve mentioned before.

**Comment by jonohewitt** [comment]
I tried the .app from the 10.4.3 .dmg installer which opens without any permissions issues and I get the logo in the menu bar but like the original post, I can't connect to the Web UI and nothing seems to be running in the background.

**Comment by philn** [comment]
Where are the DMGs? The binaries provided by tarballs don't run here, due to Catalina's security "manager"

**Comment by JustAMan** [comment]
@philn should eventually be produced from this repo: https://github.com/jellyfin/jellyfin-server-macos

**Comment by philn** [comment]
Ah, I see! Will binaries be provided by the project maintainers at some point? Thanks and sorry for hijacking this issue.

**Comment by zdarin** [comment]
Hello, i installed on mac mini 2012 i7 on macOS Catalina latest update i cant access web ui and even logs maybe some fixes possible?
