### ISSUE TITLE
XMLTV access error

### ISSUE THREAD

**Issue by BobOkisama** [jellyfin/jellyfin#212]
Ubuntu and Windows versions. If you try to load a xmltv listing, no matter the file or the area it is located in (or permissions as this is currently run as admin too and file is full for everyone) app states There was an error accessing the xmltv file.

**Comment by BobOkisama** [comment]
Here is a log snip best I can see:
`2018-12-17 16:05:13.270 Info HttpServer: HTTP POST http://192.168.0.161:8096/emby/LiveTv/ListingProviders?ValidateListings=true. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
2018-12-17 16:05:13.275 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.15.0.34
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 32
	Program data path: /config
	Application directory: /jellyfin
	MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	MediaBrowser.Common.Extensions.ResourceNotFoundException
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660`

**Comment by bfayers** [comment]
Related to my issue at #110 maybe?

**Comment by BobOkisama** [comment]
No, this is a different error completely. I already have mine in host mode and I get the template to show up. Once I apply the path to my xml file and hit save, it errors saying it does not have access to the file. I tried this on both windows and my ubuntu box and both give same error. Error persists even when I give the file EVERYONE full permissions or chmod 777.

**Comment by BobOkisama** [comment]
Correct, same error. I get that same error no matter what the file is, where, or the permissions on it for both windows and ubuntu.

**Comment by bfayers** [comment]
@BobOkisama Agreed. clearly an issue in how XmlTV Is handled.

**Comment by J0hnKol** [comment]
Same to me..

**Comment by linedpaper** [comment]
Same issue for me in Docker.  Using xteve and it's an accessible http location internally, but still receive the error.

**Comment by bfayers** [comment]
Looks like the errors occur here: https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Api/LiveTv/LiveTvService.cs#L870

as a result of being called from here: https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/LiveTvManager.cs#L2393

**Comment by BobOkisama** [comment]
Tried again with latest...
2018-12-28 12:01:20.402 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.15.0.34
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 32
	Program data path: /config
	Application directory: /jellyfin
	MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	MediaBrowser.Common.Extensions.ResourceNotFoundException
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660

**Comment by BobOkisama** [comment]
Latest update and xmltv still not working, saying it cannot access file still. Heres log:
2018-12-30 11:10:25.687 Info HttpServer: HTTP GET http://192.168.0.161:8096/emby/System/Configuration/livetv. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2018-12-30 11:10:25.689 Info HttpServer: HTTP Response 200 to 192.168.0.118. Time: 2ms. http://192.168.0.161:8096/emby/System/Configuration/livetv 
2018-12-30 11:10:25.695 Info HttpServer: HTTP POST http://192.168.0.161:8096/emby/LiveTv/ListingProviders?ValidateListings=true. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2018-12-30 11:10:25.724 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.15.0.34
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 32
	Program data path: /config
	Application directory: /jellyfin
	MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	MediaBrowser.Common.Extensions.ResourceNotFoundException
	   at Emby.Server.Implementations.LiveTv.LiveTvManager.SaveListingProvider(ListingsProviderInfo info, Boolean validateLogin, Boolean validateListings)
	   at MediaBrowser.Api.LiveTv.LiveTvService.Post(AddListingProvider request) in /repo/MediaBrowser.Api/LiveTv/LiveTvService.cs:line 870
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	
2018-12-30 11:10:25.724 Info HttpServer: HTTP Response 404 to 192.168.0.118. Time: 29ms. http://192.168.0.161:8096/emby/LiveTv/ListingProviders?ValidateListings=true

**Comment by BobOkisama** [comment]
If you can point me to a quick how to to apply this to a docker, I will have it done asap.

**Comment by Bond-009** [comment]
There are build institutions in the wiki: https://github.com/jellyfin/jellyfin/wiki/Building-from-Source

**Comment by bfayers** [comment]
Now building the docker image myself for testing.

If anyone wants a copy/paste instruction for doing that here:

```
git clone https://github.com/jellyfin/jellyfin.git && cd jellyfin
git submodule update --init
git fetch origin pull/330/head:bondxmltv
git checkout bondxmltv

docker build . -t $USERNAME/jellyfin
```

then just run it as a normal docker container but with $USERNAME/jellyfin as image name
