### ISSUE TITLE
DLNA Playback error

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin#2123]
**Describe the bug**
I have a Yahama R-N602 and when I try to access Jellyfin through DLNA I get No Content on the screen. This is clearly wrong as I have lots of music in Jellyfin. Jellyfin can detect the device as it appears in the Play on device menu. However if it is selected and the user tries to play music to it, nothing happens and an error is found in the log.

**To Reproduce**

1. Turn on R-N602 and switch input to Server to see No content
2. Connect to it using Play on device menu
3. Try to play a song
4. Nothing happens and see error in log.

**Expected behavior**
I should be able to browse the music on the server directly on the device and the play on device feature should play music on the device.

**Logs**
```
[2019-12-08 11:20:35.245 +00:00] [INF] No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:Device
Manufacturer:Yamaha Corporation
ManufacturerUrl:http://www.yamaha.com/
ModelDescription:MusicCast
ModelName:R-N602
ModelNumber:N602
ModelUrl:http://www.yamaha.com/
SerialNumber:

[2019-12-08 11:20:35.245 +00:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: baseUrl
   at MediaBrowser.Model.Dlna.StreamInfo.ToUrl(String baseUrl, String accessToken)
   at Emby.Dlna.PlayTo.PlayToController.CreatePlaylistItem(BaseItem item, User user, Int64 startPostionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/56267607/70390731-88a52f00-19c5-11ea-8906-306873ede065.png)

**System (please complete the following information):**
 - OS: macOS 10.15.1
 - Browser: N/A
 - Jellyfin Version: 10.4.3

**Additional context**
DLNA has never worked for me on Jellyfin since I switched about a year ago but it has worked fine on Emby with the same device (R-N602) which I used before Jellyfin.

**Comment by TheNamelessWonderer** [comment]
Here is the full log: [log.txt](https://github.com/jellyfin/jellyfin/files/3936484/log.txt)

**Comment by TheNamelessWonderer** [comment]
Full log with debugging enabled:
[logwithdebug.txt](https://github.com/jellyfin/jellyfin/files/3936501/logwithdebug.txt)

**Comment by TheNamelessWonderer** [comment]
Setting Secure Connection Mode to disabled allowed the ping request to work correctly and DLNA to work correctly.
