### ISSUE TITLE
DLNA stream m3u8 failing

### ISSUE THREAD

**Issue by PrplHaz4** [jellyfin/jellyfin#2132]
**Describe the bug**
Attempting to play a LiveTV/m3u8 source via DLNA fails when selecting a specific item to watch.  Browsing and traversing folders works fine.  Choosing an item from a Movie or Recording library will play the content as normal.

**To Reproduce**

1. Go to Jellyfin on Samsung TV (or VLC)
2. Click on 'LiveTV' ([m3u8 source](https://raw.githubusercontent.com/notanewbie/LegalStream/master/packages/news/live.m3u8))
3. Select "ABC News Digital"
4. See error on TV ("An Unexpected Error has occurred")

**Expected behavior**
Video content should play on TV via DLNA

**Logs**
```
[02:29:57] [DBG] Found matching device profile: Samsung Smart TV
[02:29:57] [DBG] Control request. Headers: Connection=close, Content-Type=text/xml; charset="utf-8", Accept=*/*, Host=192.168.1.161:8096, User-Agent=DLNADOC/1.50 SEC_HHP_[TV] Samsung 6 Series (65)/1.0 UPnP/1.0, Content-Length=476, SOAPACTION="urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
[02:29:57] [DBG] Received control request Browse
[02:29:57] [DBG] MediaSources: [{"Protocol":"Http","Id":"613fb0d111b90e02708fd87a9672753e","Path":"https://abclive1-lh.akamaihd.net/i/abc_live01@423395/master.m3u8","Type":"Default","IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":true,"OpenToken":"LiveTvChannel_6e3807fb6bb40d45f68ca9315eb6b434_613fb0d111b90e02708fd87a9672753e","RequiresClosing":true,"BufferMs":1500,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"VideoRange":"SDR","DisplayTitle":"","IsInterlaced":true,"IsDefault":false,"IsForced":false,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"DisplayTitle":"","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"Formats":[],"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"}}]
[02:29:57] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: mediaSource
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.AttachMediaSourceInfo(EncodingJobInfo state, MediaSourceInfo mediaSource, String requestedUrl)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[02:29:57] [DBG] Control response. Headers: EXT=
[02:29:57] [DBG] Found matching device profile: Samsung Smart TV
[02:29:57] [DBG] Control request. Headers: Connection=close, Content-Type=text/xml; charset="utf-8", Accept=*/*, Host=192.168.1.161:8096, User-Agent=DLNADOC/1.50 SEC_HHP_[TV] Samsung 6 Series (65)/1.0 UPnP/1.0, Content-Length=484, SOAPACTION="urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
[02:29:57] [DBG] Received control request Browse
[02:29:57] [INF] Profile: Samsung Smart TV, Path: Unknown path, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[02:29:57] [INF] Profile: Samsung Smart TV, No direct play profiles found for Path: Unknown path
```

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: DLNA Samsung KU6300
 - Jellyfin Version: 10.4.3
 - Installed Plugins: LazyMan, ServerWMC
 - Reverse proxy: Traefik

**Additional context**
- Same stream works fine in browser
- Other movie and video content work fine using DLNA

**Related**
#866 #585 #1181

**Comment by Bond-009** [comment]
Since this is not fixed yet, only the exception, I'd suggest opening a new issue with new logs.

**Comment by PrplHaz4** [comment]
@Bond-009 I've already opened #2164 to address the missing listing - unfortunately there doesn't seem to be much interesting to go on...
