### ISSUE TITLE
Open Subtitles erroe

### ISSUE THREAD

**Issue by g9420** [jellyfin/jellyfin#2156]
**Describe the bug**
Error using Open Subtitles

**Logs**

[2019-12-14 03:09:16.211 +00:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()

**Screenshots**

![image](https://user-images.githubusercontent.com/41284829/70847303-14bfc680-1e9e-11ea-9457-e30fb70b5fc2.png)

**System (please complete the following information):**
 - OS: [Docker]
 - Browser: [Chrome]
 - Jellyfin Version: [e.g. 10.4.3]
 - Installed Plugins: [Open Subtitles.]
 - Reverse proxy: [nginx]

**Comment by g9420** [comment]
Open Subtitles version 7.0.0.0

**Comment by JustAMan** [comment]
What Jellyfin version you're running, I assume it's 10.4.3?

**Comment by g9420** [comment]
@JustAMan 10.4.3
