### ISSUE TITLE
Getting errors in log then no webgui

### ISSUE THREAD

**Issue by davidjmorin** [jellyfin/jellyfin#2173]
This seems to be a continuous issue.  It will work fine for a while but then just stop working.  Whats weird is from my ipad and android phone i can still stream using the app.  But from a computer the GUI fails to load.

```
Dec 19 23:30:31 raspberrypi dhcpcd[410]: wlan0: deleting route to 192.168.1.0/24
Dec 19 23:30:31 raspberrypi dhcpcd[410]: wlan0: deleting default route via 192.168.1.1
Dec 19 23:30:31 raspberrypi avahi-daemon[371]: Interface wlan0.IPv4 no longer relevant for mDNS.
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: carrier acquired
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: IAID 32:1f:4d:e3
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: adding address fe80::55de:aeb9:c6ed:ef6c
Dec 19 23:30:32 raspberrypi avahi-daemon[371]: Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::55de:aeb9:c6ed:ef6c.
Dec 19 23:30:32 raspberrypi avahi-daemon[371]: New relevant interface wlan0.IPv6 for mDNS.
Dec 19 23:30:32 raspberrypi avahi-daemon[371]: Registering new address record for fe80::55de:aeb9:c6ed:ef6c on wlan0.*.
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: rebinding lease of 192.168.1.185
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: probing address 192.168.1.185/24
Dec 19 23:30:32 raspberrypi dhcpcd[410]: wlan0: soliciting an IPv6 router
Dec 19 23:30:38 raspberrypi dhcpcd[410]: wlan0: leased 192.168.1.185 for 86400 seconds
Dec 19 23:30:38 raspberrypi avahi-daemon[371]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.1.185.
Dec 19 23:30:38 raspberrypi avahi-daemon[371]: New relevant interface wlan0.IPv4 for mDNS.
Dec 19 23:30:38 raspberrypi dhcpcd[410]: wlan0: adding route to 192.168.1.0/24
Dec 19 23:30:38 raspberrypi avahi-daemon[371]: Registering new address record for 192.168.1.185 on wlan0.IPv4.
Dec 19 23:30:38 raspberrypi dhcpcd[410]: wlan0: adding default route via 192.168.1.1
Dec 19 23:30:40 raspberrypi jellyfin[480]: [23:30:40] [ERR] Error processing request: The operation was canceled.
Dec 19 23:30:40 raspberrypi jellyfin[480]: [23:30:40] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:09.4029316. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:30:45 raspberrypi dhcpcd[410]: wlan0: no IPv6 Routers available
Dec 19 23:31:02 raspberrypi jellyfin[480]: [23:31:02] [ERR] Error processing request: The operation was canceled.
Dec 19 23:31:02 raspberrypi jellyfin[480]: [23:31:02] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.3658373. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:31:19 raspberrypi jellyfin[480]: [23:31:19] [ERR] Error processing request: The operation was canceled.
Dec 19 23:31:19 raspberrypi jellyfin[480]: [23:31:19] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:00.9715894. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:31:36 raspberrypi jellyfin[480]: [23:31:36] [ERR] Error processing request: The operation was canceled.
Dec 19 23:31:36 raspberrypi jellyfin[480]: [23:31:36] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:00.9755171. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:31:50 raspberrypi jellyfin[480]: [23:31:50] [ERR] Error processing request: The operation was canceled.
Dec 19 23:31:50 raspberrypi jellyfin[480]: [23:31:50] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.2138015. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:32:06 raspberrypi jellyfin[480]: [23:32:06] [ERR] Error processing request: The operation was canceled.
Dec 19 23:32:06 raspberrypi jellyfin[480]: [23:32:06] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.4826229. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:32:25 raspberrypi jellyfin[480]: [23:32:25] [ERR] Error processing request: The operation was canceled.
Dec 19 23:32:25 raspberrypi jellyfin[480]: [23:32:25] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.6465276. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:32:42 raspberrypi jellyfin[480]: [23:32:42] [ERR] Error processing request: The operation was canceled.
Dec 19 23:32:42 raspberrypi jellyfin[480]: [23:32:42] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:02.0849819. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:33:02 raspberrypi jellyfin[480]: [23:33:02] [ERR] Error processing request: The operation was canceled.
Dec 19 23:33:02 raspberrypi jellyfin[480]: [23:33:02] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.1459956. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:33:19 raspberrypi jellyfin[480]: [23:33:19] [ERR] Error processing request: The operation was canceled.
Dec 19 23:33:19 raspberrypi jellyfin[480]: [23:33:19] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:02.6082942. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:33:36 raspberrypi jellyfin[480]: [23:33:36] [ERR] Error processing request: The operation was canceled.
Dec 19 23:33:36 raspberrypi jellyfin[480]: [23:33:36] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:00.9908891. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:33:58 raspberrypi jellyfin[480]: [23:33:58] [ERR] Error processing request: The operation was canceled.
Dec 19 23:33:58 raspberrypi jellyfin[480]: [23:33:58] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:00.8857585. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:34:12 raspberrypi jellyfin[480]: [23:34:12] [ERR] AcceptWebSocketAsync error
Dec 19 23:34:12 raspberrypi jellyfin[480]: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.So
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureCl
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken
Dec 19 23:34:12 raspberrypi jellyfin[480]:    at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
Dec 19 23:34:20 raspberrypi jellyfin[480]: [23:34:20] [ERR] Error processing request: The operation was canceled.
Dec 19 23:34:20 raspberrypi jellyfin[480]: [23:34:20] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:00.8821466. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:34:42 raspberrypi jellyfin[480]: [23:34:42] [ERR] Error processing request: The operation was canceled.
Dec 19 23:34:42 raspberrypi jellyfin[480]: [23:34:42] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:02.0065271. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?St
Dec 19 23:34:58 raspberrypi jellyfin[480]: [23:34:58] [ERR] Error processing request: The operation was canceled.
Dec 19 23:34:58 raspberrypi jellyfin[480]: [23:34:58] [WRN] HTTP Response 206 to 192.168.1.161. Time (slow): 0:00:01.019914. http://192.168.1.185:8096/Videos/04cd2c79f8b68862f23125d19f93f338/stream.mp4?Sta
lines 2418-2487/2487 (END)
```

**Comment by JustAMan** [comment]
Am I right from the log above that this happens when your RPi refreshes an address via DHCP?
