### ISSUE TITLE
Stopping jellyfin container may result in sqlite DB remaining locked

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#218]
After stopping my jellyfin container using `docker-compose stop jellyfin`, pulling the latest image and running it using `docker-compose run -d jellyfin` I discovered that the container wasn't starting correctly but instead continually restarting.

The error message JF shows on startup is the following:
 ```
UnhandledException
Busy: database is locked
SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.CreateConnection(Boolean isReadOnly) in /repo/Emby.Server.Implementations/Data/BaseSqliteRepository.cs:line 113
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager) in /repo/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 125
   at Emby.Server.Implementations.ApplicationHost.RegisterResources() in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 856
   at Emby.Server.Implementations.ApplicationHost.Init() in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 817
   at MediaBrowser.Server.Mono.MainClass.RunApplication(ServerApplicationPaths appPaths, ILogManager logManager, StartupOptions options)
   at MediaBrowser.Server.Mono.MainClass.Main(String[] args)
SQLitePCL.pretty.SQLiteException
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.CreateConnection(Boolean isReadOnly) in /repo/Emby.Server.Implementations/Data/BaseSqliteRepository.cs:line 113
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager) in /repo/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 125
   at Emby.Server.Implementations.ApplicationHost.RegisterResources() in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 856
   at Emby.Server.Implementations.ApplicationHost.Init() in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 817
   at MediaBrowser.Server.Mono.MainClass.RunApplication(ServerApplicationPaths appPaths, ILogManager logManager, StartupOptions options)
   at MediaBrowser.Server.Mono.MainClass.Main(String[] args)
```

To me this looks like the SQLite DB wasn't unlocked properly when Jellyfin was shutdown.

I'm still investigating whether this issue could be caused by something on my setup in particular (e.g. file permissions, although unlikely) but it could also very well be an rare race condition that happens whenever jellyfin is shutdown during a DB write.

**Comment by Azuraell** [comment]
Hi, I'm sorry if my issue is not the same as this one, I am a noob at pretty much everything but especially docker...
My container is always starting, getting SIGTERM signal, then starting again. It started doing that a few days after I first set it up I think, but it happened while I was not using it.

Here is a tiny part of my log which is a loop.
`[18:41:15] [INF] [1] App: Disposing CoreAppHost
[18:41:15] [INF] [2] Main: Received a SIGTERM signal, shutting down
[18:41:28] [INF] [1] Main: Jellyfin version: 10.5.3
[18:41:28] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/local/bin/ffmpeg"]
[18:41:28] [INF] [1] Main: Operating system: Linux
[18:41:28] [INF] [1] Main: Architecture: X64
[18:41:28] [INF] [1] Main: 64-Bit Process: True
[18:41:28] [INF] [1] Main: User Interactive: True
[18:41:28] [INF] [1] Main: Processor count: 6
[18:41:28] [INF] [1] Main: Program data path: /config
[18:41:28] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[18:41:28] [INF] [1] Main: Application directory: /jellyfin/
[18:41:29] [INF] [1] ServerConfigurationManager: Setting cache path: /cache
[18:41:29] [INF] [1] App: Loading assemblies
[18:41:29] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Anime/Jellyfin.Plugin.Anime.dll
[18:41:29] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Fanart/Jellyfin.Plugin.Fanart.dll
[18:41:29] [INF] [1] App: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/OpenSubtitlesHandler.dll
[18:41:29] [INF] [1] App: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
[18:41:29] [FTL] [1] Main: Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[18:41:29] [INF] [1] App: Disposing CoreAppHost
[18:41:29] [INF] [2] Main: Received a SIGTERM signal, shutting down
[18:41:55] [INF] [1] Main: Jellyfin version: 10.5.3
[18:41:55] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/local/bin/ffmpeg"]
[18:41:55] [INF] [1] Main: Operating system: Linux
[18:41:55] [INF] [1] Main: Architecture: X64
[18:41:55] [INF] [1] Main: 64-Bit Process: True
[18:41:55] [INF] [1] Main: User Interactive: True
[18:41:55] [INF] [1] Main: Processor count: 6
[18:41:55] [INF] [1] Main: Program data path: /config
[18:41:55] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[18:41:55] [INF] [1] Main: Application directory: /jellyfin/
[18:41:55] [INF] [1] ServerConfigurationManager: Setting cache path: /cache
[18:41:55] [INF] [1] App: Loading assemblies
[18:41:55] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Anime/Jellyfin.Plugin.Anime.dll
[18:41:55] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Fanart/Jellyfin.Plugin.Fanart.dll
[18:41:55] [INF] [1] App: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/OpenSubtitlesHandler.dll
[18:41:55] [INF] [1] App: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
[18:41:55] [FTL] [1] Main: Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[18:41:55] [INF] [1] App: Disposing CoreAppHost
[18:41:55] [INF] [2] Main: Received a SIGTERM signal, shutting down
`

**Comment by MuhammadAhsanDonuts** [comment]
@Azuraell, Have you found out the solution for this problem?

**Comment by vgambier** [comment]
@MuhammadAhsanDonuts As some other forums indicated, my issue was caused by another instance of jellyfin being run on a different server. I honestly don't know how this happened (it happened after an upgrade). Just check `docker ps` on any other servers and use `docker kill jellyfin`.
