### ISSUE TITLE
Error downloading subtitles from "Open Subtitles"

### ISSUE THREAD

**Issue by g9420** [jellyfin/jellyfin#2183]
[2019-12-22 12:01:27.500 +00:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()

**Comment by JustAMan** [comment]
@dkanada any ideas?

**Comment by dkanada** [comment]
My involvement with the plugin only went so far as fixing a few outstanding issues and splitting it out from the core server, so unfortunately I can't be of assistance. I don't even use it myself.

**Comment by g9420** [comment]
Ok thank you for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dkanada"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 凌晨2:27
收件人: "jellyfin/jellyfin"<jellyfin@noreply.github.com&gt;; 
抄送: "嵩"<942075508@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jellyfin/jellyfin] Error downloading subtitles from &quot;Open Subtitles&quot; (#2183)




My involvement with the plugin only went so far as fixing a few outstanding issues and splitting it out from the core server, so unfortunately I can't be of assistance. I don't even use it myself.
 
&mdash;
