### ISSUE TITLE
Random Crashing upon Media Addition

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2197]
**Describe the bug**

Server will randomly receive Unhandled Exceptions and restart. More noticeable during streaming since it will produce a black screen and stop the video. 
**To Reproduce**

Hard to reproduce, adding media and actively using the server tends to cause it more often.
**Expected behavior**

Not crash.
**Logs**

```
[20:47:23] [FTL] Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
Unhandled exception. System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows] Docker
 - Browser: [e.g. Firefox, Chrome, Safari] Firefox
 - Jellyfin Version: [e.g. 10.0.1] Master
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] Playback Reporting, TMDb Box Sets
 - Reverse proxy: [e.g. no, nginx, apache, etc.] Traefik

**Additional context**

**Comment by Bond-009** [comment]
This is an issue with thE TMDB boxsets plugin: https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/6

**Comment by dannymichel** [comment]
I still ave the same issue and I have/had no TMDB boxsets plugin

**Comment by JustAMan** [comment]
@dannymichel if you have similar issue please post it in a new one, callstacks in this particular one clearly originate from TMDB boxset.
