### ISSUE TITLE
No Episode metadata is being downloaded for any files

### ISSUE THREAD

**Issue by ioogithub** [jellyfin/jellyfin#2205]
**Describe the bug**
A media scan is not downloading any data from the Internet database providers for TV Shows.

**To Reproduce**
1. Under Dashboard-> Library, click on three dots and select "Scan Library"
2. When the scan finished, no data was pulled in.
3. Repeat test changing databases- TheTVDb, TheMovieDb, TheOpenMovieDatabase. None of them download any data. 

**Expected behavior**
Jellyfin will contact the Internet databases and download data.

**Logs**
```
[2019-12-28 21:32:02.271 +00:00] [ERR] No series results found for "Popular TV Show Title"
TvDbSharper.TvDbServerException: No records are found that match your query; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, SearchParameter parameter, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FindSeriesInternal(String name, String language, **CancellationToken cancellationToken**)
```

```
2019-12-28 21:47:17.039 +00:00] [ERR] Error in "ffprobe"
System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetPrimaryPlaylistVobFiles(String path, IIsoMount isoMount, Nullable`1 titleNumber)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.FetchFromDvdLib(Video item)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```
`2019-12-28 21:33:56.005 +00:00] [INF] MovieDbProvider: Finding id for item: Popular Tv Show - Season 1`

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox 68.2.0esr
 - Jellyfin Version: :latest
 - Installed Plugins: None
 - Reverse proxy: None

**Additional context**
Multiple data sets were tried, all of them fail to return any data.

**Comment by anthonylavado** [comment]
One of the errors in there is FFprobe can’t be found? That shouldn’t be the case... I believe there’s an FFmpeg package that includes this but I don’t know enough about our Docker setup...

**Comment by JustAMan** [comment]
This looks more like an issue with parsing `.VOB` files from a DVD copy, could you please check `ffmpeg` version in your docker container? Also paging @Bond-009 in case this looks familiar to him.

**Comment by Bond-009** [comment]
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs#L85
This will always fail with an exception
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L857

**Comment by JustAMan** [comment]
This probably means we don't currently support DVD videos copied as folders.
