### ISSUE TITLE
No subtitles when transcoding

### ISSUE THREAD

**Issue by KaXaSA** [jellyfin/jellyfin#2211]
The subtitles work fine when I open the video on MPV, VLC... and using Jellyfin (web - firefox) I have no issues with other videos when they are not transcoding. When transcode kick in the audio and video are fine but the subtitles are missing.

I also extracted the subtitles using mkvextract just to see if it would fix anything (having .ASS with the same name as the MKV file both on the same folder) but it didn't work.

**Media Info of the file**
MKV, AVC (High 10@L4.1), FLAC, ASS
(let me know if you need any other information)

**Logs**

log

```
[18:48:08] [ERR] Error in ffprobe
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.streams[0].start_pts | LineNumber: 28 | BytePositionInLine: 26.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[18:48:08] [INF] User policy for Teste. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[18:48:08] [INF] Profile: Unknown Profile, Path: D:\N 02 (BD 1080p Hi10 x264 FLAC).mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[18:48:08] [INF] Profile: Unknown Profile, No direct play profiles found for Path: D:\N 02 (BD 1080p Hi10 x264 FLAC).mkv
[18:48:10] [WRN] HTTP Response 200 to 192.168.1.100. Time (slow): 0:00:01.5122794. http://192.168.1.100:8096/videos/86850340-908f-5dea-0af4-4da586557d32/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjkuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82OS4wfDE1NzE5MzUxMjU2NDM1&MediaSourceId=86850340908f5dea0af44da586557d32&VideoCodec=h264&AudioCodec=aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=388ed563dd8f41e8ae3bfa4c0d8b3b4c&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=911d2980bd46a5c730ac909c4ce1e108&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported
```

-------

ffmpeg log
I added some '...' here and there to remove some of the text to make the log shorter (probably irrelevant information)

```
http://192.168.1.100:8096/videos/86850340-908f-5dea-0af4-4da586557d32/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjkuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82OS4wfDE1NzE5MzUxMjU2NDM1&MediaSourceId=86850340908f5dea0af44da586557d32&VideoCodec=h264&AudioCodec=aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=388ed563dd8f41e8ae3bfa4c0d8b3b4c&api_key=158bd2f815fc4789bb15f2230c22ffee&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=911d2980bd46a5c730ac909c4ce1e108&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported

{"Protocol":"File","Id":"86850340908f5dea0af44da586557d32","Path":"D:\\N 02 (BD 1080p Hi10 x264 FLAC).mkv","Type":"Default","Container":"mkv","Name":"N 02 (BD 1080p Hi10 x264 FLAC) [0EDC53E4]","IsRemote":false,"ETag":"911d2980bd46a5c730ac909c4ce1e108","ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{}}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -i file:"D:\N 02 (BD 1080p Hi10 x264 FLAC).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 139808000 -bufsize 279616000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/52fadf274ea30d9b6cbd848aedbd8b81/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b81.m3u8" -y "C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b81%d.ts"


ffmpeg version N-95234-g35a63a9127 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsvtav1 --enable-librtmp --enable-gnutls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --shlibdir=/local64/bin-video
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, matroska,webm, from 'file:D:\N 02 (BD 1080p Hi10 x264 FLAC).mkv':
  Metadata:
    title           : Melting Into Spring
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2018-03-18T14:25:17.000000Z
  Duration: 00:24:00.11, start: 0.000000, bitrate: 8892 kb/s
    Chapter #0:0: start 0.000000, end 91.023344
    Metadata:
      title           : Opening
    Chapter #0:1: start 91.023344, end 734.074111
    Metadata:
      title           : Part A
    Chapter #0:2: start 734.074111, end 1326.073844
    Metadata:
      title           : Part B
    Chapter #0:3: start 1326.073844, end 1416.097111
    Metadata:
      title           : Ending
    Chapter #0:4: start 1416.097111, end 1440.106000
    Metadata:
      title           : Preview
    Stream #0:0(jpn): Video: h264 (High 10), yuv420p10le(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 8242984
      BPS-eng         : 8242984
      DURATION        : 00:24:00.106000000
      DURATION-eng    : 00:24:00.106000000
      NUMBER_OF_FRAMES: 34528
      NUMBER_OF_FRAMES-eng: 34528
      NUMBER_OF_BYTES : 1483846409
      NUMBER_OF_BYTES-eng: 1483846409
      _STATISTICS_WRITING_APP: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2018-03-18 14:25:17
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-03-18 14:25:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      BPS             : 644385
      BPS-eng         : 644385
      DURATION        : 00:24:00.105000000
      DURATION-eng    : 00:24:00.105000000
      NUMBER_OF_FRAMES: 16877
      NUMBER_OF_FRAMES-eng: 16877
      NUMBER_OF_BYTES : 115997888
      NUMBER_OF_BYTES-eng: 115997888
      _STATISTICS_WRITING_APP: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2018-03-18 14:25:17
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-03-18 14:25:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : (Modified) tlacatlc6
      BPS             : 754
      BPS-eng         : 754
      DURATION        : 00:23:49.640000000
      DURATION-eng    : 00:23:49.640000000
      NUMBER_OF_FRAMES: 919
      NUMBER_OF_FRAMES-eng: 919
      NUMBER_OF_BYTES : 134838
      NUMBER_OF_BYTES-eng: 134838
      _STATISTICS_WRITING_APP: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.7.1 ('Pandemonium') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2018-03-18 14:25:17
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-03-18 14:25:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3: Attachment: ttf
    Metadata:
      filename        : BAARS___.TTF
      mimetype        : application/x-truetype-font
...

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 00000258ff8ce5c0] using SAR=1/1
[libx264 @ 00000258ff8ce5c0] VBV bitrate (139808) > level limit (50000)
[libx264 @ 00000258ff8ce5c0] VBV buffer (279616) > level limit (62500)
[libx264 @ 00000258ff8ce5c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000258ff8ce5c0] profile Main, level 4.1, 4:2:0, 8-bit
[segment @ 00000258ff998e40] Opening 'C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b810.ts' for writing
Output #0, segment, to 'C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b81%d.ts':
  Metadata:
    encoder         : Lavf58.33.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.59.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 139808000/0/0 buffer size: 279616000 vbv_delay: N/A
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (16 bit), 192 kb/s (default)
    Metadata:
      encoder         : Lavc58.59.101 aac
frame=   32 fps=0.0 q=28.0 size=N/A time=00:00:01.49 bitrate=N/A speed=2.96x    
frame=   70 fps= 69 q=28.0 size=N/A time=00:00:03.19 bitrate=N/A speed=3.17x    
[segment @ 00000258ff998e40] Opening 'C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b81.m3u8.tmp' for writing
[segment @ 00000258ff998e40] Opening 'C:\Users\UserName\AppData\Local\jellyfin\transcodes\52fadf274ea30d9b6cbd848aedbd8b811.ts' for writing
...

video:73608kB audio:10254kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 00000258ff8ce5c0] frame I:245   Avg QP:17.21  size:105824
[libx264 @ 00000258ff8ce5c0] frame P:3126  Avg QP:20.15  size: 11673
[libx264 @ 00000258ff8ce5c0] frame B:7085  Avg QP:23.76  size:  1829
[libx264 @ 00000258ff8ce5c0] consecutive B-frames:  6.7%  6.9%  5.9% 80.6%
[libx264 @ 00000258ff8ce5c0] mb I  I16..4: 47.4%  0.0% 52.6%
[libx264 @ 00000258ff8ce5c0] mb P  I16..4: 13.7%  0.0%  0.0%  P16..4: 17.9%  0.0%  0.0%  0.0%  0.0%    skip:68.4%
[libx264 @ 00000258ff8ce5c0] mb B  I16..4:  1.2%  0.0%  0.0%  B16..8:  4.4%  0.0%  0.0%  direct: 1.9%  skip:92.5%  L0:42.8% L1:48.7% BI: 8.4%
[libx264 @ 00000258ff8ce5c0] coded y,uvDC,uvAC intra: 40.7% 31.7% 9.7% inter: 2.1% 2.8% 0.0%
[libx264 @ 00000258ff8ce5c0] i16 v,h,dc,p: 43% 25% 16% 17%
[libx264 @ 00000258ff8ce5c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 20% 12%  9%  7%  6%  6%  6%  7%
[libx264 @ 00000258ff8ce5c0] i8c dc,h,v,p: 57% 19% 18%  6%
[libx264 @ 00000258ff8ce5c0] Weighted P-Frames: Y:2.9% UV:1.8%
[libx264 @ 00000258ff8ce5c0] kb/s:1382.69
[aac @ 00000258ff99ef00] Qavg: 407.602
```

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/6237603/71566822-79cc0c80-2a99-11ea-85b2-95696943f103.png)

**Server System (please complete the following information):**
 - OS: Windows 10  Pro 64-bit
 - Jellyfin Version: 10.5.0
 - Hardware settings & device: RX480 / i5 4670k Hardware Acceleration: AMD AMF -I also tested both Intel QS and NONE and (un)check  'Allow subtitle extraction on the fly' but I still could not see the subtitles-
 - Reverse proxy: no
 
 
**Client System (please complete the following information):**
I'm testing this on the PC that is running Jellyfin
 - Browser (if Web client): Firefox 
 - Client and Browser Version: 10.5.0 and 71.0

Thanks and Happy New Year! :D

**Comment by cryptobank** [comment]
I can confirm subtitles playback on 10.5.0 is broken. Also downloading subtitles via the opensubtitles plugin doesn't work.

**Comment by JustAMan** [comment]
Seems you're running off master, not off some release. Could you please update, as there were a few fixes merged that might potentially be relevant?

**Comment by KaXaSA** [comment]
> Seems you're running off master, not off some release. Could you please update, as there were a few fixes merged that might potentially be relevant?

I was actually using 10.4.3 (stable) and had the same issue, then I updated it to the nightly release 10.5.0 (20191223) from [here](https://repo.jellyfin.org/releases/server/windows/versions/nightly/20191223/)

I will try to update to the [latest nightly release (20200114) ](https://repo.jellyfin.org/releases/server/windows/versions/nightly/20200114/), if want me to try to update to other version let me know, thanks. 👍
