### ISSUE TITLE
Video playback stops after a few minutes, with an exception

### ISSUE THREAD

**Issue by dcbaker** [jellyfin/jellyfin#2215]
My setup is as follows:
freenas running samba
a second machine running just jellyfin, using cifs from the freenas machine.
a front end running an android tv nvidia shield
all of this is connected via 1gb wired connections

I've (attempted) to disable all transcoding to the shield device, as it's quite capable of playing all of my media natively.

There are no errors showing up in samba on the the freenas side, or in dmesg or similar logs on the machine running jellyfin

**Reproduce**

Watch any video for ~3 minutes, it will stop and ask if the video finished

**logs**

```
Dec 31 12:04:02 videostar dotnet[965]: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketExcepti
on: Connection reset by peer                                                                                                                                                    
Dec 31 12:04:02 videostar dotnet[965]:    --- End of inner exception stack trace ---
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)                                         Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.ThrowIfExceptional()
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)         
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)           Dec 31 12:04:02 videostar dotnet[965]: --- End of stack trace from previous location where exception was thrown ---                                                             Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)          
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Dec 31 12:04:02 videostar dotnet[965]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Dec 31 12:04:02 videostar dotnet[965]: --- End of stack trace from previous location where exception was thrown ---                    
Dec 31 12:04:02 videostar dotnet[965]:    at System.Threading.ThreadPoolWorkQueue.Disp
```

**System (please complete the following information):**
 - OS: Archlinux (installed via aur)
 - Browser: N/A
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: none

**Comment by Bond-009** [comment]
Same exception as #465, should get fixed with 10.5
