### ISSUE TITLE
White screen on refresh

### ISSUE THREAD

**Issue by batu-one** [jellyfin/jellyfin#2228]
**Describe the bug**
If while I'm playing media, I hit the refresh button, I get a white page saying:
```
Value cannot be null.
Parameter name: path
```

**To Reproduce**

1. Open up any video
2. Hit refresh button, F5, Cmd/Ctrl-R, whatever
3. See error

**Expected behavior**
I'd expect the video the appear again.

**Logs**```

[2020-01-04 23:11:31.051 +01:00] [INF] Profile: "Unknown Profile", Path: "***removed***", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-01-04 23:11:31.051 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "***removed***"
[2020-01-04 23:11:35.141 +01:00] [INF] WS "http://***removed***/socket?api_key=c15784b2d3a54434927f7336621c3de9&deviceId=TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2OjcxLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNzEuMHwxNTc2ODU0MjA0NDMy". UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
[2020-01-04 23:11:35.831 +01:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at MediaBrowser.Model.Net.MimeTypes.GetMimeType(String path, Boolean enableStreamDefault)
   at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-01-04 23:11:47.412 +01:00] [INF] StartPlaybackTimer : session Not Found
[2020-01-04 23:11:47.413 +01:00] [INF] StartPlaybackTimer : Exited
[2020-01-04 23:12:43.328 +01:00] [INF] FFMpeg exited with code 0
```

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox, not tested in other browsers
 - Jellyfin Version: tested with 10.4.1 and 10.4.3
 - Installed Plugins: OpenSubtitles, Playback reports, Trakt
 - Reverse proxy: Nginx

**Additional context**
N/A

**Comment by JustAMan** [comment]
Well, it should be leading you back to home screen (which is a known limitation).
Not sure why it's broken like that, can you check on other browsers? Firefox had recently an uptake of issues specific to it...
