### ISSUE TITLE
Cannot log using jellyfin 10.4.3

### ISSUE THREAD

**Issue by cmoulliard** [jellyfin/jellyfin#2244]
## Issue

I cannot log to the UI Web interface using `admin` or `jellyfin` user. The log reports this error
```
./jellyfin
[22:44:33] [INF] Jellyfin version: 10.4.3
[22:44:33] [INF] Arguments: ["/Users/dabou/Downloads/jellyfin_10.4.3/jellyfin.dll"]
[22:44:33] [INF] Operating system: macOS
[22:44:33] [INF] Architecture: X64
[22:44:33] [INF] 64-Bit Process: True
[22:44:33] [INF] User Interactive: True
[22:44:33] [INF] Processor count: 8
[22:44:33] [INF] Program data path: /Users/dabou/.local/share/jellyfin
[22:44:33] [INF] Web resources path: /Users/dabou/Downloads/jellyfin_10.4.3/jellyfin-web
[22:44:33] [INF] Application directory: /Users/dabou/Downloads/jellyfin_10.4.3/
[22:44:33] [INF] Setting cache path to /Users/dabou/.cache/jellyfin
[22:44:33] [INF] Loading assemblies
[22:44:34] [INF] Kestrel listening on all interfaces
[22:44:34] [INF] Running startup tasks
[22:44:34] [INF] Daily trigger for Chapter image extraction set to fire at 01/09/2020 02:00, which is 3:15:25.023753 from now.
[22:44:35] [INF] Found ffmpeg version 4.2.2
[22:44:35] [INF] Available decoders: ["h264", "hevc", "mpeg2video", "aac", "ac3", "mp3"]
[22:44:35] [INF] Available encoders: ["libx264", "libx265", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[22:44:35] [INF] FFmpeg: System: /usr/local/bin/ffmpeg
[22:44:35] [INF] ServerId: 5614ec616c1e473e8ca2e04ed9651146
[22:44:35] [INF] Executed all pre-startup entry points in 0:00:00.24126
[22:44:35] [INF] Core startup complete
[22:44:35] [INF] Executed all post-startup entry points in 0:00:00.3416435
[22:44:36] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 127.0.0.1
[22:44:36] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.1.3
[22:44:38] [INF] StartupTrigger fired for task: Check for plugin updates
[22:44:38] [INF] Queueing task PluginUpdateTask
[22:44:38] [INF] Executing Check for plugin updates
[22:44:38] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
[22:44:38] [INF] ExecuteQueuedTasks
[22:44:41] [INF] No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:Volumio
Manufacturer:Volumio
ManufacturerUrl:https://volumio.org
ModelDescription:The Audiophile Music Player
ModelName:Volumio
ModelNumber:1.0
ModelUrl:https://volumio.org
SerialNumber:42

[22:44:41] [INF] DLNA Session created for Volumio - Volumio
[22:45:02] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: resolvedUser
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[22:47:29] [ERR] Error processing request
``` 

and I got this message from the UI

<img width="1193" alt="Screenshot 2020-01-08 22 47 44" src="https://user-images.githubusercontent.com/463790/72018988-0b413880-3269-11ea-9391-9ae2e19af3fe.png">

**Comment by anthonylavado** [comment]
Try resetting your password with the "Forgot Password" button.

**Comment by cmoulliard** [comment]
That was failing too. I finally resolved the issue after cleating the cache folder.

**Comment by demeere** [comment]
> That was failing too. I finally resolved the issue after cleating the cache folder.
hello 
where can I find said cache folder?

**Comment by demeere** [comment]
I'm having the same issue right after setting it up also unable to reset the password giving the same message that it is unable to reach the server
where can I find that cache folder under linux?
@cmoulliard 
@anthonylavado
