### ISSUE TITLE
All 10.5.0 nighly portable give error 500 in all Browsers

### ISSUE THREAD

**Issue by AxiomTheorie** [jellyfin/jellyfin#2255]
**Describe the bug**
All 10.5.0 nighly portable give error 500 in all Browsers
Tested in Win 10 and LibreELEC
both Server is started and give a Log without errors

10.4.3 is Working without Problems

**To Reproduce**

1. Load all Nightly from jellyfin-nightly_20191201.tar.gz to jellyfin-nightly_20200109.tar.gz 
2. start Server
3. open Browser go to http://:8096/

**Expected behavior**
See the Webinterface

**Logs**
Log Windows as Server:
```
[2020-01-11 01:31:21.933 +01:00] [INF] Jellyfin version: "10.5.0"
[2020-01-11 01:31:22.338 +01:00] [INF] Arguments: ["C:\Users\Axiom\Downloads\jellyfin-nightly_20200109\jellyfin_10.5.0\jellyfin.dll"]
[2020-01-11 01:31:22.649 +01:00] [INF] Operating system: "Windows"
[2020-01-11 01:31:22.693 +01:00] [INF] Architecture: X64
[2020-01-11 01:31:22.728 +01:00] [INF] 64-Bit Process: True
[2020-01-11 01:31:22.748 +01:00] [INF] User Interactive: True
[2020-01-11 01:31:22.768 +01:00] [INF] Processor count: 2
[2020-01-11 01:31:22.792 +01:00] [INF] Program data path: "C:\Users\Axiom\AppData\Local\jellyfin"
[2020-01-11 01:31:22.810 +01:00] [INF] Web resources path: "C:\Users\Axiom\Downloads\jellyfin-nightly_20200109\jellyfin_10.5.0\jellyfin-web"
[2020-01-11 01:31:22.828 +01:00] [INF] Application directory: "C:\Users\Axiom\Downloads\jellyfin-nightly_20200109\jellyfin_10.5.0\"
[2020-01-11 01:31:24.300 +01:00] [INF] Setting cache path: "C:\Users\Axiom\AppData\Local\jellyfin\cache"
[2020-01-11 01:31:24.454 +01:00] [INF] Loading assemblies
[2020-01-11 01:31:25.527 +01:00] [WRN] No users, creating one with username "Axiom"
[2020-01-11 01:31:26.612 +01:00] [INF] Saving system configuration
[2020-01-11 01:31:26.618 +01:00] [INF] Setting cache path: "C:\Users\Axiom\AppData\Local\jellyfin\cache"
[2020-01-11 01:31:29.358 +01:00] [INF] Kestrel listening on all interfaces
[2020-01-11 01:31:30.231 +01:00] [INF] Running startup tasks
[2020-01-11 01:31:30.393 +01:00] [INF] Daily trigger for "Chapter image extraction" set to fire at 01/11/2020 02:00, which is 0:28:29.6066779 from now.
[2020-01-11 01:31:30.564 +01:00] [INF] FFmpeg: NotFound: ""
[2020-01-11 01:31:30.606 +01:00] [INF] ServerId: "3fc0c2d60d974a1fb01d18b90d6b6dbe"
[2020-01-11 01:31:32.191 +01:00] [INF] Executed all pre-startup entry points in 0:00:01.5541701
[2020-01-11 01:31:32.508 +01:00] [INF] Core startup complete
[2020-01-11 01:31:33.495 +01:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2020-01-11 01:31:34.075 +01:00] [INF] Queueing task "PluginUpdateTask"
[2020-01-11 01:31:34.568 +01:00] [INF] Executing "Check for plugin updates"
[2020-01-11 01:31:35.653 +01:00] [INF] Executed all post-startup entry points in 0:00:03.1384908
[2020-01-11 01:31:36.617 +01:00] [INF] Startup complete 0:00:16.0961693
[2020-01-11 01:31:37.862 +01:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 3 seconds
[2020-01-11 01:31:42.144 +01:00] [INF] ExecuteQueuedTasks
```

Log LibreELEC as Server:
```
[2020-01-11 01:40:39.949 +01:00] [INF] Jellyfin version: "10.5.0"
[2020-01-11 01:40:40.034 +01:00] [INF] Arguments: ["/storage/.kodi/addons/service.jellyfin/jellyfin/jellyfin.dll", "-ffmpeg", "/storage/.kodi/addons/service.jellyfin/lib/jellyfin-ffmpeg/ffmpeg", "-configdir", "/storage/.kodi/userdata/addon_data/service.jellyfin/config", "-cachedir", "/storage/.kodi/userdata/addon_data/service.jellyfin/cache", "-logdir", "/storage/.kodi/userdata/addon_data/service.jellyfin/log", "-datadir", "/storage/.kodi/userdata/addon_data/service.jellyfin/data"]
[2020-01-11 01:40:40.053 +01:00] [INF] Operating system: "Linux"
[2020-01-11 01:40:40.054 +01:00] [INF] Architecture: Arm
[2020-01-11 01:40:40.057 +01:00] [INF] 64-Bit Process: False
[2020-01-11 01:40:40.058 +01:00] [INF] User Interactive: True
[2020-01-11 01:40:40.058 +01:00] [INF] Processor count: 4
[2020-01-11 01:40:40.058 +01:00] [INF] Program data path: "/storage/.kodi/userdata/addon_data/service.jellyfin/data"
[2020-01-11 01:40:40.058 +01:00] [INF] Web resources path: "/storage/.kodi/addons/service.jellyfin/jellyfin/jellyfin-web"
[2020-01-11 01:40:40.059 +01:00] [INF] Application directory: "/storage/.kodi/addons/service.jellyfin/jellyfin/"
[2020-01-11 01:40:40.896 +01:00] [INF] Setting cache path: "/storage/.kodi/userdata/addon_data/service.jellyfin/cache"
[2020-01-11 01:40:41.566 +01:00] [INF] Loading assemblies
[2020-01-11 01:40:48.697 +01:00] [WRN] No users, creating one with username "root"
[2020-01-11 01:40:55.167 +01:00] [INF] Saving system configuration
[2020-01-11 01:40:55.172 +01:00] [INF] Setting cache path: "/storage/.kodi/userdata/addon_data/service.jellyfin/cache"
[2020-01-11 01:40:57.692 +01:00] [INF] Kestrel listening on all interfaces
[2020-01-11 01:40:58.486 +01:00] [INF] Running startup tasks
[2020-01-11 01:40:58.523 +01:00] [INF] Daily trigger for "Chapter image extraction" set to fire at 01/11/2020 02:00, which is 0:19:01.4771778 from now.
[2020-01-11 01:40:59.109 +01:00] [INF] Found ffmpeg version "4.2.1"
[2020-01-11 01:40:59.765 +01:00] [INF] Available "decoders": ["h264", "h264_mmal", "hevc", "mpeg2video", "mpeg2_mmal", "mpeg4_mmal", "vc1_mmal", "aac", "ac3", "mp3"]
[2020-01-11 01:40:59.812 +01:00] [INF] Available "encoders": ["libx264", "h264_omx", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-01-11 01:40:59.814 +01:00] [INF] FFmpeg: SetByArgument: "/storage/.kodi/addons/service.jellyfin/lib/jellyfin-ffmpeg/ffmpeg"
[2020-01-11 01:40:59.819 +01:00] [INF] ServerId: "5ed06d5436594f9fab153bba1fd612f1"
[2020-01-11 01:41:00.535 +01:00] [INF] Executed all pre-startup entry points in 0:00:00.6839203
[2020-01-11 01:41:00.535 +01:00] [INF] Core startup complete
[2020-01-11 01:41:01.433 +01:00] [INF] Executed all post-startup entry points in 0:00:00.8975934
[2020-01-11 01:41:01.433 +01:00] [INF] Startup complete 0:00:22.4917951
[2020-01-11 01:41:01.542 +01:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2020-01-11 01:41:01.548 +01:00] [INF] Queueing task "PluginUpdateTask"
[2020-01-11 01:41:01.571 +01:00] [INF] Executing "Check for plugin updates"
[2020-01-11 01:41:02.939 +01:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 1 seconds
[2020-01-11 01:41:03.077 +01:00] [INF] ExecuteQueuedTasks
```

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
 - Browser: [All]
 - Jellyfin Version: [all 10.5.0 Portable]
 - Installed Plugins: [None]
 - Reverse proxy: [no]

**Additional context**

**Comment by JustAMan** [comment]
Those logs don't show any errors, can you post those that do?

**Comment by AxiomTheorie** [comment]
that's the strange thing. There are no errors in all the logs

**Comment by PrplHaz4** [comment]
> that's the strange thing. There are no errors in all the logs

Ffmpeg shows not found

**Comment by AxiomTheorie** [comment]
ffmpeg doesn't matter
the error comes with and without ffmpeg

**Comment by Tolriq** [comment]
This is still broken.
Nothing in the logs.
Curl result:
```
*   Trying 192.168.1.80...
* TCP_NODELAY set
* Connected to 192.168.1.80 (192.168.1.80) port 8096 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.80:8096
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Wed, 22 Jan 2020 08:56:11 GMT
< Server: Kestrel
< Content-Length: 0
<
* Connection #0 to host 192.168.1.80 left intact
```

The exact same error whatever the url used including wrong ones that should 404.

**Comment by dkanada** [comment]
@Tolriq is this only the portable nightly? I have been using the ubuntu nightly for weeks without issues, and I have also used the arch installation as well.

**Comment by Tolriq** [comment]
Only tested the Windows X64 nightly as I need to support tons of different versions in my app so only use portable ones.

**Comment by barolo** [comment]
Same with portable for Linux, not going to install Net.Core for one app, sorry

**Comment by Matt07211** [comment]
I've spent a few hours trying to debug this issue without much luck. Although I did notice when running with debug logging I got this error on a nightlie
```
[23:04:34] [DBG] [12] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: False
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
```

Wheres if I was running stable I would get
```
[23:07:09] [DBG] [] PortMapper: Starting NAT discovery
...
[23:07:09] [DBG] [] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: True
```
My two guesses are it could be the change to .NET 3.1 After the stable release that causes this bug, or it could be this commit https://github.com/jellyfin/jellyfin/commit/599432890311c9255cb376bbeb6f5f4f673fbf1b#diff-afc7d23eb25589b4f37d3a06dd30175b as it was added after stable was built and modifies a function that `IsIpAddressValidAsync` makes use of.

And for the sake of it, here are what ports are opened by jellyfin when running stable or nightlie.

Stable 10.4.3
```
$ sudo lsof -i :8096
Password: 
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
firefox   1213 matt  283u  IPv4 516316      0t0  TCP localhost:55034->localhost:8096 (ESTABLISHED)
firefox   1213 matt  297u  IPv4 510626      0t0  TCP localhost:55036->localhost:8096 (ESTABLISHED)
firefox   1213 matt  304u  IPv4 509888      0t0  TCP localhost:55046->localhost:8096 (ESTABLISHED)
firefox   1213 matt  307u  IPv4 510631      0t0  TCP localhost:55040->localhost:8096 (ESTABLISHED)
firefox   1213 matt  331u  IPv4 510632      0t0  TCP localhost:55042->localhost:8096 (ESTABLISHED)
firefox   1213 matt  332u  IPv4 510633      0t0  TCP localhost:55044->localhost:8096 (ESTABLISHED)
firefox   1213 matt  333u  IPv4 511895      0t0  TCP localhost:55052->localhost:8096 (ESTABLISHED)
jellyfin 24068 matt  230u  IPv6 511839      0t0  TCP *:8096 (LISTEN)
jellyfin 24068 matt  243u  IPv4 511874      0t0  TCP thonkpad.local:43927->thonkpad.local:8096 (ESTABLISHED)
jellyfin 24068 matt  246u  IPv6 509855      0t0  TCP thonkpad.local:8096->thonkpad.local:43927 (ESTABLISHED)
jellyfin 24068 matt  262u  IPv6 513758      0t0  TCP localhost:8096->localhost:55034 (ESTABLISHED)
jellyfin 24068 matt  263u  IPv6 510627      0t0  TCP localhost:8096->localhost:55036 (ESTABLISHED)
jellyfin 24068 matt  267u  IPv6 516327      0t0  TCP localhost:8096->localhost:55052 (ESTABLISHED)
jellyfin 24068 matt  268u  IPv6 516318      0t0  TCP localhost:8096->localhost:55046 (ESTABLISHED)
jellyfin 24068 matt  270u  IPv6 511890      0t0  TCP localhost:8096->localhost:55040 (ESTABLISHED)
jellyfin 24068 matt  271u  IPv6 511891      0t0  TCP localhost:8096->localhost:55042 (ESTABLISHED)
jellyfin 24068 matt  274u  IPv6 511892      0t0  TCP localhost:8096->localhost:55044 (ESTABLISHED)
```

Nightlie 10.5.0
```
$ sudo lsof -i :8096
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
firefox   1213 matt  301u  IPv4 512736      0t0  TCP localhost:55064->localhost:8096 (ESTABLISHED)
firefox   1213 matt  309u  IPv4 515715      0t0  TCP localhost:55066->localhost:8096 (ESTABLISHED)
jellyfin 24171 matt  257u  IPv6 517348      0t0  TCP *:8096 (LISTEN)
jellyfin 24171 matt  271u  IPv4 517383      0t0  TCP thonkpad.local:50918->thonkpad.local:8096 (ESTABLISHED)
jellyfin 24171 matt  274u  IPv6 515709      0t0  TCP thonkpad.local:8096->thonkpad.local:50918 (ESTABLISHED)
jellyfin 24171 matt  288u  IPv6 516519      0t0  TCP localhost:8096->localhost:55064 (ESTABLISHED)
jellyfin 24171 matt  289u  IPv6 523346      0t0  TCP localhost:8096->localhost:55066 (ESTABLISHED)
```

**Comment by Matt07211** [comment]
Okay, so I think the problem may lie with the build command, I haven't narrowed it down why as out it, but it looks promising.

So If I run a nightlie, or build with docker or directly run the build command `dotnet publish --configuration Release --self-contained --runtime linux-x64 --output ../out/jellyfin_10.5.0/ "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none;UseAppHost=true"`
Then I cant access jellyfin and I will have the following error
```
[23:04:34] [DBG] [12] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: False
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
```

Now, if I build with  `dotnet ~/.local/lib/dotnet/sdk/3.1.101/MSBuild.dll MediaBrowser.sln '-p:Configuration=Debug;OutDir=../out/Debug/'` and run the resulting program, it works and I see the following in the logs.
```
...
[23:29:44] [DBG] [11] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: True
...
```

I tried running the last command with but with `Release` swapped in instead of `Debug` but the build fails with  701 Errors so I am unable to test how the resulting program works

**Comment by Bond-009** [comment]
@2277 What about this: `dotnet publish --configuration Release --self-contained true --runtime linux-x64 --output /dist/jellyfin_${version}/ "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none"` ?

**Comment by Matt07211** [comment]
Nope, the change in the build command that you suggested doesnt work, and it spits out the following errors during compile.
```csharp
/home/matt/.local/lib/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/matt/Projects/Jellyfin/jellyfin/tests/Jellyfin.Common.Tests/Jellyfin.Common.Tests.csproj]
/home/matt/.local/lib/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/matt/Projects/Jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Tests/Jellyfin.MediaEncoding.Tests.csproj]
/home/matt/.local/lib/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/matt/Projects/Jellyfin/jellyfin/tests/Jellyfin.Naming.Tests/Jellyfin.Naming.Tests.csproj]
/home/matt/.local/lib/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/matt/Projects/Jellyfin/jellyfin/tests/Jellyfin.Api.Tests/Jellyfin.Api.Tests.csproj]
  DvdLib -> /home/matt/Projects/Jellyfin/jellyfin/DvdLib/bin/Release/netstandard2.0/DvdLib.dll
  MediaBrowser.Common -> /home/matt/Projects/Jellyfin/jellyfin/MediaBrowser.Common/bin/Release/netstandard2.1/linux-x64/MediaBrowser.Common.dll
  MediaBrowser.Common -> /home/matt/Projects/Jellyfin/out/jellyfin_10.5.0/
  MediaBrowser.Common -> /home/matt/Projects/Jellyfin/jellyfin/MediaBrowser.Common/bin/Release/netstandard2.1/MediaBrowser.Common.dll
/home/matt/.local/lib/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/matt/Projects/Jellyfin/jellyfin/tests/Jellyfin.Server.Implementations.Tests/Jellyfin.Server.Implementations.Tests.csproj]
  Emby.Naming -> /home/matt/Projects/Jellyfin/jellyfin/Emby.Naming/bin/Release/netstandard2.1/linux-x64/Emby.Naming.dll
```

**Comment by Matt07211** [comment]
@PrplHaz4 suggested a modified command, with the change being adding `Jellyfin.Server` between publish and all the command line flags. So you go from the orignal build command which is
```
dotnet publish --configuration Release --self-contained true --runtime linux-x64 --output /dist/jellyfin_${version}/ "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none;UseAppHost=true"
```
And we get this in the jellyfin logs
```
[14:32:55] [DBG] [4] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: False
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
```

But when we tweak the build command slightly and add `Jellyfin.Server`,  it works.
```
dotnet publish jellyfin.Server --configuration Release --self-contained true --runtime linux-x64 --output /dist/jellyfin_${version}/ "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none;UseAppHost=true"
```

We see this in the jellyfin logs after building with the above command.
```
[14:34:09] [DBG] [10] App: Ping test result to http://10.105.233.3:8096/system/ping. Success: True
```
And we are able to access everything as we should.

I'll go create a pull request, but I wonder what is breaking where to cause this problem.

@Bond-009

**Comment by Matt07211** [comment]
Just expanding on my idea,  I had a look at the versions of different nugets in my `.nuget` folder and in each folder there is usally is at least two different versions of the software there. 

I feel like this really solidifies my hunch that its a dependency issue. 

For reference, until I tried working on this bug/issue, I had not had dotnet installed, nor compiled Jellyfin or any .NET Project. I had stuck to the one commit hash and not done a git pull during the entirety of me working/attempting to work on this issue. 

The  only difference during the process was compiling the app different ways, which again, for reference was via the docker build system, `dotnet publish` command (copied from the docker build script), `dotnet msbuild` command, and the build function in Rider (which uses `dotnet msbuild` under the hood, and it also parse the files and grabs the nugets ahead of time). 

**Note:** `dotnet publish` calls `dotnet msbuild` under the hood, but the way it evaluates dependency's differ.

Below I attached 2 screenshots to illustrate the example, keep in mind there are a decent amount of nugets in my `.nuget/` folder with **2** *or more versions* available in each respective folder. This folder contains only Jellyfins dependency's and the dependency's dependency's at this point in time as this is the only .NET project I have compiled on this machine.

So my line of thought continues as such, what happens if a breaking ABI/API change has occurred between versions (this is especially likely since .NET Core was updated 3.1.1 around the exact time this issue started occurring, this upgrade has a decent amount of breaking changes, as listed [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1) ), and where one library has updated its ABI/API but another thing that uses that ABI/API hasn't been updated to support this change (because lets say the dotnet publish command selected the older version). This seems like an entirely plausible scenario to me, in my honest opinion.
![Example-1](https://user-images.githubusercontent.com/12839977/73432241-308e0780-433a-11ea-9dc5-cd31821b63dd.png)
![Example-2](https://user-images.githubusercontent.com/12839977/73432242-308e0780-433a-11ea-9fc2-31fa81427a9c.png)

My suggestion is being more explicit on dependency versions to eliminate this kind of hidden bugs. The following page has a section of how you can be explicit on what versions you want.
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by Matt07211** [comment]
I'm against closing it (or maybe better to create a new issue).

The core problem is the evaluation of dependencys used (I believe in my opinion) and that we should be a bit more explicit on what versions of a dependency can be used
