### ISSUE TITLE
 I can't start my Jellyfin in my Raspberry Pi 3B+

### ISSUE THREAD

**Issue by nonewind** [jellyfin/jellyfin#2267]
system ： Raspbain 10 Buster 
Jellyfin version: 10.4.3

I also tried to modify  "LocalNetworkAddresses" to 0.0.0.0 in “system.xml”  ，but not work.
what can I do？
:(
Startup log：

```
root@raspberrypi:~/.config/jellyfin# jellyfin
[09:51:04] [INF] Jellyfin version: 10.4.3
[09:51:04] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[09:51:04] [INF] Operating system: Linux
[09:51:04] [INF] Architecture: Arm
[09:51:04] [INF] 64-Bit Process: False
[09:51:04] [INF] User Interactive: True
[09:51:04] [INF] Processor count: 4
[09:51:04] [INF] Program data path: /root/.local/share/jellyfin
[09:51:04] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[09:51:04] [INF] Application directory: /usr/lib/jellyfin/bin/
[09:51:05] [INF] Setting cache path to /root/.cache/jellyfin
[09:51:05] [INF] Loading assemblies
[09:51:14] [INF] Kestrel listening on all interfaces
[09:51:15] [ERR] Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in system.xml and try again.
[09:51:15] [FTL] Error while starting server.
System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[09:51:15] [INF] Disposing CoreAppHost
[09:51:15] [INF] Disposing ActivityLogWebSocketListener
[09:51:15] [INF] Disposing SessionInfoWebSocketListener
[09:51:15] [INF] Disposing ScheduledTasksWebSocketListener
[09:51:15] [INF] Disposing SessionWebSocketListener
[09:51:15] [INF] Disposing EmbyTV
[09:51:15] [INF] Received a SIGTERM signal, shutting down
```

**Comment by PrplHaz4** [comment]
It looks like something is already using port  8096. Make sure no other instances of jf or envy are running and kill all dotnet processes then restart Jellyfin.

**Comment by nonewind** [comment]
I try use "netstat -tunlp |grep 8096" , but print nothing. Maybe  8096 port not using?

**Comment by gnattu** [comment]
> netstat -tunlp |grep 8096

Did you run it as root? This will not show port used by other uses if you run it as normal user

**Comment by nonewind** [comment]
Yes .I run as root

**Comment by Artiume** [comment]
Method of install? Installing from repository didn't give me issues for my Rpi4.

**Comment by nonewind** [comment]
Run as root;
"""
echo "deb [arch=armhf] https://repo.jellyfin.org/debian $( lsb_release -c -s ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
apt install jellyfin -y
"""
No problems during installation

**Comment by JustAMan** [comment]
@nonewind try clearing the `LocalNetworkAddresses` value completely in your `system.xml` instead of putting `0.0.0.0` there, I believe it should help, see https://github.com/jellyfin/jellyfin/issues/1875 for more.

**Comment by nonewind** [comment]
> @nonewind尝试`LocalNetworkAddresses`完全清除您的值，`system.xml`而不是放在`0.0.0.0`那里，我认为它会有所帮助，请参阅[＃1875](https://github.com/jellyfin/jellyfin/issues/1875)了解更多信息。

I try [＃1875](https://github.com/jellyfin/jellyfin/issues/1875) His method.
modify "LocalNetworkAddresses" to 0.0.0.0 in “system.xml”  and modify “<LocalNetworkAddresses / >”

**Comment by nonewind** [comment]
> > @nonewind尝试`LocalNetworkAddresses`完全清除您的值，`system.xml`而不是放在`0.0.0.0`那里，我认为它会有所帮助，请参阅[＃1875](https://github.com/jellyfin/jellyfin/issues/1875)了解更多信息。
> 
> I try [＃1875](https://github.com/jellyfin/jellyfin/issues/1875) His method.
> modify "LocalNetworkAddresses" to 0.0.0.0 in “system.xml” and modify “<LocalNetworkAddresses / >”

Nothing worked

**Comment by Artiume** [comment]
So let's assume a ghost program is in fact binding to 8096. No amount of adjusting the config would overcome that.


Try `sudo lsof -i :8096`

If that doesn't work, try 
`sudo apt install psmisc`
`sudo fuser 8096/tcp`

ss is also a newer version of netstat, it might find something. 

`sudo ss -ltnp | grep -w ':8096'`

**Comment by Artiume** [comment]
I successfully got Jellyfin running on my Pi 3B+

**Comment by nonewind** [comment]
Thanks, I successfully got Jellyfin running.
