### ISSUE TITLE
Password reset not working with "No Users found [...]"

### ISSUE THREAD

**Issue by mihawk90** [jellyfin/jellyfin#2282]
**Describe the bug**
Today started my jellyfin server for once in a long time because I wanted to test something out. Can't login, seems I forgot my password (or maybe I didn't from some issues I found?), and I can't reset it.
Entering my user name works fine, even creates the json file with the PIN in it. Problem is: when entering that PIN into the next input box I receive a `ResourceNotFoundException`.

**To Reproduce**
1. Start the server and hit "Forgot Password"
2. Enter username, get the file and the contained PIN
3. Click "Got It" and enter said PIN into the Input Box
4. Hit "Submit", watch the console, see the Exception
5. Check the file again (it's gone :scream: )

**Expected behavior**
1. If the user does not exist, display a proper error message (currently it says `Please try again within your home network to initiate the password reset process.` ???)
2. If the user does exist, either give me an input field for a new password or log me straight in, I'm not sure how it's technically supposed to work :)

**Logs**
```
[tarulia@localhost ~]$ jellyfin
[20:59:48] [INF] Jellyfin version: 10.4.3
[20:59:48] [INF] Arguments: ["/usr/lib64/jellyfin/jellyfin.dll"]
[20:59:48] [INF] Operating system: Linux
[20:59:48] [INF] Architecture: X64
[20:59:48] [INF] 64-Bit Process: True
[20:59:48] [INF] User Interactive: True
[20:59:48] [INF] Processor count: 16
[20:59:48] [INF] Program data path: /home/tarulia/.local/share/jellyfin
[20:59:48] [INF] Web resources path: /usr/lib64/jellyfin/jellyfin-web
[20:59:48] [INF] Application directory: /usr/lib64/jellyfin/
[20:59:48] [INF] Setting cache path to /home/tarulia/.cache/jellyfin
[20:59:48] [INF] Loading assemblies
[20:59:50] [INF] Kestrel listening on all interfaces
[20:59:50] [INF] Running startup tasks
[20:59:50] [INF] Daily trigger for Chapter image extraction set to fire at 01/15/2020 02:00, which is 5:00:09.5893136 from now.
[20:59:50] [INF] Found ffmpeg version 4.2.2
[20:59:50] [INF] Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[20:59:50] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[20:59:50] [INF] FFmpeg: System: /usr/bin/ffmpeg
[20:59:50] [INF] ServerId: 78fd4491de7d4032ab1ac96f617ce54b
[20:59:50] [INF] Executed all pre-startup entry points in 0:00:00.2489205
[20:59:50] [INF] Core startup complete
[20:59:51] [INF] Watching directory /home/tarulia/Music/Muse
[20:59:51] [INF] Watching directory /home/tarulia/Videos/TV Shows
[20:59:51] [INF] Watching directory /home/tarulia/Music/Soundtrack
[20:59:51] [INF] Executed all post-startup entry points in 0:00:00.3295278
[20:59:53] [INF] StartupTrigger fired for task: Check for plugin updates
[20:59:53] [INF] Queueing task PluginUpdateTask
[20:59:53] [INF] Executing Check for plugin updates
[20:59:54] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
[20:59:54] [INF] ExecuteQueuedTasks
[21:00:17] [ERR] Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: No Users found with a password reset request matching pin 14-BA-49-27
   at Emby.Server.Implementations.Library.DefaultPasswordResetProvider.RedeemPasswordResetPin(String pin)
   at Emby.Server.Implementations.Library.UserManager.RedeemPasswordResetPin(String pin)
   at MediaBrowser.Api.UserService.Post(ForgotPasswordPin request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**

**System (please complete the following information):**
 - OS: Fedora 31
 - Browser: Vivaldi/Chromium
 - Jellyfin Version: 10.4.3 from fedora repo (see log)
 - Installed Plugins: not sure, I only did a basic installation and haven't played with it much just yet
 - Reverse proxy: none

**Additional context**
I checked whether the user actually exists in the users.db, and it is there with proper capitalisation.
This is also the only account on it, and it is admin.

**Comment by mihawk90** [comment]
Still happening on 10.5.5:

```
[tarulia@localhost ~]$ jellyfin
[09:39:09] [INF] Jellyfin version: 10.5.5
[09:39:09] [INF] Arguments: ["/usr/lib64/jellyfin/jellyfin.dll"]
[09:39:09] [INF] Operating system: Linux
[09:39:09] [INF] Architecture: X64
[09:39:09] [INF] 64-Bit Process: True
[09:39:09] [INF] User Interactive: True
[09:39:09] [INF] Processor count: 16
[09:39:09] [INF] Program data path: /home/tarulia/.local/share/jellyfin
[09:39:09] [INF] Web resources path: /usr/lib64/jellyfin/jellyfin-web
[09:39:09] [INF] Application directory: /usr/lib64/jellyfin/
[09:39:10] [INF] Setting cache path: /home/tarulia/.cache/jellyfin
[09:39:10] [INF] Loading assemblies
[09:39:10] [INF] Loaded assembly Jellyfin.Plugin.Fanart, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /home/tarulia/.local/share/jellyfin/plugins/Fanart/Jellyfin.Plugin.Fanart.dll                                               
[09:39:11] [INF] Applying migration 'DisableTranscodingThrottling'
[09:39:11] [INF] Disabling transcoding throttling during migration
[09:39:11] [INF] Migration 'DisableTranscodingThrottling' applied successfully
[09:39:11] [INF] Applying migration 'CreateLoggingConfigHeirarchy'
[09:39:11] [INF] Migration 'CreateLoggingConfigHeirarchy' applied successfully
[09:39:11] [INF] Kestrel listening on all interfaces
[09:39:11] [WRN] No XML encryptor configured. Key {ae113ae6-fb74-4d9e-a97f-059f442e2841} may be persisted to storage in unencrypted form.                                                                                                       
[09:39:11] [INF] Running startup tasks
[09:39:11] [INF] Daily trigger for Extract Chapter Images set to fire at 05/16/2020 02:00, which is 16:20:48.5080568 from now.                                                                                                                  
[09:39:11] [INF] Found ffmpeg version 4.2.2
[09:39:11] [INF] Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[09:39:11] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[09:39:11] [INF] FFmpeg: System: /usr/bin/ffmpeg
[09:39:11] [INF] ServerId: 012be99df0264230b9556d30ab38847e
[09:39:11] [INF] Executed all pre-startup entry points in 0:00:00.1892021
[09:39:11] [INF] Core startup complete
[09:39:11] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.0.13
[09:39:12] [INF] Watching directory /home/tarulia/Videos/TV Shows
[09:39:12] [INF] Watching directory /home/tarulia/Music/Soundtrack
[09:39:12] [INF] Executed all post-startup entry points in 0:00:00.2006969
[09:39:12] [INF] Startup complete 0:00:02.4198991
[09:39:14] [INF] StartupTrigger fired for task: Update Plugins
[09:39:14] [INF] Queueing task PluginUpdateTask
[09:39:14] [INF] Executing Update Plugins
[09:39:15] [INF] Plugin updated: Fanart 4.0.0.0 Release
[09:39:15] [INF] App needs to be restarted.
[09:39:15] [INF] Update Plugins Completed after 0 minute(s) and 1 seconds
[09:39:15] [INF] ExecuteQueuedTasks
[09:39:32] [INF] WS http://localhost:8096/socket?api_key=255ed50e9acb4d0a8da2a70bb182c5f0&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNzYuMC4zODA5LjExMCBTYWZhcmkvNTM3LjM2IFZpdmFsZGkvMi43LjE2MjguMjF8MTU2NTk5ODEwNzUzNA11. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.132 Safari/537.36
[09:39:32] [INF] Getting image size for item CollectionFolder /home/tarulia/.local/share/jellyfin/metadata/library/7e/7e64e319657a9516ec78490da03edccb/poster.png
[09:39:38] [INF] Logging out access token 255ed50e9acb4d0a8da2a70bb182c5f0
[09:40:31] [ERR] Error processing request. URL: http://localhost:8096/Users/ForgotPassword/Pin
MediaBrowser.Common.Extensions.ResourceNotFoundException: No Users found with a password reset request matching pin B1-1C-01-A9
   at Emby.Server.Implementations.Library.DefaultPasswordResetProvider.RedeemPasswordResetPin(String pin)
   at Emby.Server.Implementations.Library.UserManager.RedeemPasswordResetPin(String pin)
   at MediaBrowser.Api.UserService.Post(ForgotPasswordPin request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by dkanada** [comment]
Password resets have been broken for an extremely long time, but #3100 makes some minor improvements. After it gets merged I'll be doing a pass to fix bugs as well, which should resolve this issue as well.

**Comment by mihawk90** [comment]
Tested in 10.6.4 and it worked fine.
Only issue being that the popup did not show the path, the reset itself worked however.
