### ISSUE TITLE
Restarting from the dashboard button results in UnhandledException

### ISSUE THREAD

**Issue by aferpa94** [jellyfin/jellyfin#229]
As the title say, when clicking the restart button, the process fails:
- Ubuntu 18.04, freshly installed Jellyfin.

`2018-12-19 18:08:57.287 Error Main: UnhandledException
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh 
	Operating system: Unix 4.15.0.42
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 2
	Program data path: /var/lib/jellyfin
	Application directory: /usr/lib/jellyfin/bin
	System.ComponentModel.Win32Exception (13): Permission denied
	   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
	   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start()
	   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
	   at MediaBrowser.Server.Mono.MainClass.StartNewInstance(StartupOptions startupOptions)
	   at MediaBrowser.Server.Mono.MainClass.Main(String[] args)
	System.ComponentModel.Win32Exception
	   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
	   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start()
	   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
	   at MediaBrowser.Server.Mono.MainClass.StartNewInstance(StartupOptions startupOptions)
	   at MediaBrowser.Server.Mono.MainClass.Main(String[] args)`

**Comment by nvllsvm** [comment]
What's the point of this functionality anyway? I'm considering removing it instead of fixing it.

**Comment by PrplHaz4** [comment]
My guess is it's there to assist with applying updates while the server is running.

**Comment by joshuaboniface** [comment]
Yea it allows aa restart from the GUI. Frankly I don't like how it does it at all, but I think the functionality is worthwhile.

**Comment by brianjmurrell** [comment]
Yeah, I think it's worth keeping.  It's just one of those "finishing touch" things that elevate something from a piece of software that runs on a computer into something complete and can be called an appliance.
