### ISSUE TITLE
plugin page network request  500 error

### ISSUE THREAD

**Issue by moeinrahimi** [jellyfin/jellyfin#2312]
**Describe the bug**
plugin page on dashboard sends request to http://localhost:8096/emby/Packages?TargetSystems=MBClassic&IsAdult=false&IsAppStoreSafe=true&PackageType=UserInstalled
and response messsage is No such host is known No such host is known.

my logs
```
[20:51:54] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: No such host is known No such host is known ---> System.Net.WebException: No such host is known No such host is known ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod) in T:\jellyfin-master\Emby.Server.Implementations\HttpClientManager\HttpClientManager.cs:line 447
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod) in T:\jellyfin-master\Emby.Server.Implementations\HttpClientManager\HttpClientManager.cs:line 275
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackagesWithoutRegistrationInfo(CancellationToken cancellationToken) in T:\jellyfin-master\Emby.Server.Implementations\Updates\InstallationManager.cs:line 213
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken, Boolean withRegistration, String packageType, Version applicationVersion) in T:\jellyfin-master\Emby.Server.Implementations\Updates\InstallationManager.cs:line 200
   at MediaBrowser.Api.PackageService.Get(GetPackages request) in T:\jellyfin-master\MediaBrowser.Api\PackageService.cs:line 157
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in T:\jellyfin-master\Emby.Server.Implementations\Services\ServiceExec.cs:line 114
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in T:\jellyfin-master\Emby.Server.Implementations\Services\ServiceHandler.cs:line 96
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in T:\jellyfin-master\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 654
```

**Comment by anthonylavado** [comment]
@moeinrahimi Can you show us the link you’re clicking on? I don’t see it here...

**Comment by dkanada** [comment]
I remember seeing a few issues like this when the DNS resolution stopped working for the plugin repository, but I thought the DO migration fixed that.

**Comment by anthonylavado** [comment]
@dkanada I’m more interested in finding out what element makes this link

**Comment by dkanada** [comment]
probably something around [here](https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/dashboard/plugins/available.js#L6)

**Comment by moeinrahimi** [comment]
![image](https://user-images.githubusercontent.com/13715024/72922377-2f6d4100-3d62-11ea-9e60-b3b653a155e2.png)
both option in plugin select box result in 500 error

**Comment by anthonylavado** [comment]
@moeinrahimi What version are you running? That option shouldn’t exist anymore

**Comment by moeinrahimi** [comment]
I'm using 10.0.1 on windows, since there is no way to update jellyfin without losing data I stayed on the old version

**Comment by cvium** [comment]
You can't reasonably expect us to support 10.0.1. The latest version is 10.4.3.
