### ISSUE TITLE
TVDB Failed to retrieve episode with id null, series id "XXX"

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2329]
**Describe the bug**
Episodes in season 0 of a DVD ordered series are querying TVDB with wrong IDs.
TVDB for Series is set correctly in JF 72306. But using null as episode ID and episode id instead of series id in query to TVDB.

I tested a aired order special in a different series (Doctor Who (2005)) and it pulled metadata with no errors.

**To Reproduce**

1. Go to Series Special Season
2. Select example episode
3. Click on Refresh Metadata
4. view log

Example
Venture Bros 0x03 - From the Ladle to the Grave: The Shallow Gravy Story
TVDBId = 4148034

**Expected behavior**

Proper IDs should be passed to TVDB.

**Logs**

```
[2020-01-22 16:51:40.273 -06:00] [ERR] Failed to retrieve episode with id null, series id "4148034"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[DVD_episodenumber:3 DVD_season:0]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome,
 - Jellyfin Version: 10.4.1
 - Installed Plugins: Fanart
 - Reverse proxy: no

**Comment by SenorSmartyPants** [comment]
There is no DVD season 0. When dvd order is selected and there is no DVD ordered season, JF should default to pulling from Aired order season.

Not all series have different ordering in all seasons.

**Comment by SenorSmartyPants** [comment]
TVDB Episode Image provider has no issues finding and downloading images.

![image](https://user-images.githubusercontent.com/991618/73005695-fdde8f00-3dce-11ea-9f31-2d772ad7fc85.png)
