### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2333]
**Describe the bug**

Logging the details for SSL bug that I can't track down. 
```
[2020-01-24 12:39:26.748 +00:00] [ERR] Error in "TheMovieDb"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.FetchMainResult(String id, Boolean isTmdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.DownloadMovieInfo(String id, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
This log error is with TheMovieDb. It is also occurring with The Open Movie Database, TmdbImageProvider and so on. It is also preventing livetv Playback from occurring.

I think this is the log for livetv playback failure, it doesn't match the SSL error so perhaps it's unrelated.
```
[2020-01-24 13:03:31.001 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://redacted"
[2020-01-24 13:03:31.001 +00:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.Playback.MediaInfoService.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean forceDirectPlayRemoteMediaSource, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy)
   at MediaBrowser.Api.Playback.MediaInfoService.SetDeviceSpecificData(Guid itemId, PlaybackInfoResponse result, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, Guid userId, Boolean enableDirectPlay, Boolean forceDirectPlayRemoteMediaSource, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy)
   at MediaBrowser.Api.Playback.MediaInfoService.GetPlaybackInfo(GetPostedPlaybackInfo request)
   at MediaBrowser.Api.Playback.MediaInfoService.Post(GetPostedPlaybackInfo request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
**To Reproduce**

I'm seeing this in docker, bridge and host_mode. That being said, I only run nightlies on docker so it might be nightlies related and not docker related. Requires further testing to isolate the issue.

**Comment by PrplHaz4** [comment]
The SSL failure could be related to an untrusted root cert - is it happening on the ARM docker image that uses an older debian version (that may not have the same trusted certs)?

**Comment by Artiume** [comment]
x86 and arm are both affected. I did a local build for arm that I need to spin up and test so I can rule out docker

**Comment by Artiume** [comment]
https://stackoverflow.com/questions/9983265/the-remote-certificate-is-invalid-according-to-the-validation-procedure

**Comment by PrplHaz4** [comment]
> 
> 
> x86 and arm are both affected. I did a local build for arm that I need to spin up and test so I can rule out docker

From this issue it sounds like the SSL behavior changed btw .net core 2 and 3:
https://github.com/dotnet/corefx/issues/40538

**Comment by Artiume** [comment]
Looking now, I'll see if changing the CipherString helps

**Comment by Artiume** [comment]
SSL errors appear to be gone. I'll run a few more tests this weekend when I have time but it looks good so far. LiveTV is still broken for me so I suspect it's my custom patch causing the liveTV issue.

**Comment by Artiume** [comment]
I'll also test adding this to the dockerfile and see how it behaves when i get a chance.

`RUN sed -i "s|DEFAULT@SECLEVEL=2|DEFAULT@SECLEVEL=1|g" /etc/ssl/openssl.cnf`

**Comment by PrplHaz4** [comment]
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

**Level 0**
    Everything is permitted. This retains compatibility with previous versions of OpenSSL.

**Level 1**
    The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export cipher suites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any cipher suite using MD5 for the MAC is also prohibited.

**Level 2**
    Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited. In addition to the level 1 exclusions any cipher suite using RC4 is also prohibited. SSL version 3 is also not allowed. Compression is disabled.

**Level 3**
    Security level set to 128 bits of security. As a result RSA, DSA and DH keys shorter than 3072 bits and ECC keys shorter than 256 bits are prohibited. In addition to the level 2 exclusions cipher suites not offering forward secrecy are prohibited. TLS versions below 1.1 are not permitted. Session tickets are disabled.

**Level 4**
    Security level set to 192 bits of security. As a result RSA, DSA and DH keys shorter than 7680 bits and ECC keys shorter than 384 bits are prohibited. Cipher suites using SHA1 for the MAC are prohibited. TLS versions below 1.2 are not permitted.

**Level 5**
    Security level set to 256 bits of security. As a result RSA, DSA and DH keys shorter than 15360 bits and ECC keys shorter than 512 bits are prohibited.
```

**Comment by Artiume** [comment]
`Level 5` Break the internet lol. Also curious as to why Sha1 isn't disabled until level 4

**Comment by Artiume** [comment]
So I tried adding `RUN sed -i "s|DEFAULT@SECLEVEL=2|DEFAULT@SECLEVEL=1|g" /etc/ssl/openssl.cnf` to the end of the Dockerfile, I'm still receiving the SSL messages. I'm not sure what's different with my setup.

**Comment by Artiume** [comment]
Trying this
https://github.com/dotnet/SqlClient/issues/222#issuecomment-535941637

**Comment by Artiume** [comment]
Error still occurring with
```
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf
```

There's other options in that ticket to try

**Comment by Artiume** [comment]
Here's the default that is causing the issue.
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```
 Changing it to TLSv1 and Sec level to 1 appeared to work on one host but not another. I believe I might have added a dependency before I had fixed it the first time, then I lost the dependency when I rebuilt the container.

**Comment by Artiume** [comment]
https://www.sslsupportdesk.com/details-digital-certificate-mean/

I can reproduce the SSL issue on nightly by rebooting the server and it attempting to connect to the plugin URL @ https://repo.jellyfin.org/releases/plugin/manifest.json

Pulling up its cert. It doesn't look wrong. Only thing I notice is that the cert is for build.jellyfin.org, but repo.jellyfin.org is a valid SAN so that should be good to go.

**Comment by Artiume** [comment]
.env TZ is supported in jellyfin/jellyfin, who knew. Also, TZ is not the issue.

**Comment by steelersfan7** [comment]
As discussed in the matrix dev chat. Here is the yml files as requested
(main.yml) https://pastebin.com/kwZf1Gqb
(settings.yml) https://pastebin.com/xyvHdBER

**Comment by Artiume** [comment]
Spun up linuxserver/jellyfin nightly, no SSL certs. Makes me believe it's limited to the docker build environment.

**Comment by Artiume** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio

**Comment by Artiume** [comment]
Server1 has been up for 36 hours, SSL errors have cleared itself. Last recorded SSL error was at 2137 last night. Server up time ~14 hours when it cleared itself.

**Comment by Artiume** [comment]
I wonder if this could be the cause of the black screen issue on Mac and windows.
