### ISSUE TITLE
M3U Tuner's custom user-agent can't contain UTF-8

### ISSUE THREAD

**Issue by inexist3nce** [jellyfin/jellyfin#2341]
The M3U Tuner found on the Live TV Tuner Setup has the ability to accept a custom `User-agent` HTTP header, but it can only contain ASCII characters. If one adds UTF-8 characters to it, video playback is not possible, resulting in the web ui being stuck loading forever.

After looking at the jellyfin logs and searching online, I found that the HTTP client can't take UTF-8 without encoding it first. [This comment](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/552#issuecomment-530151502) gives me a hint, but I didn't submit a patch because base64 encoding feels like the wrong approach.

**To Reproduce**
1. Go to jellyfin's web ui, log in as an admin.
2. Go to the dashboard, click on Live TV.
3. Add a new Tuner Device, type "M3U Tuner".
4. Add whatever `.m3u` url, use a custom `user-agent` header with UTF-8 characters on it.
6. Save.
7. Go to the channel list in the Live TV section.
8. Click on any channel of the freshly added `.m3u` list. It will never load.

**Expected behavior**
Video playback when a custom `user-agent` is provided.

**Logs**
```
[2020-01-26 20:40:17.654 -03:00] [INF] Opening channel stream from "Emby", external channel Id: "m3u_5daf83d90bb...75b2675904db353"
[2020-01-26 20:40:17.654 -03:00] [INF] Streaming Channel m3u_5daf83d90bb...75b2675904db353
[2020-01-26 20:40:17.654 -03:00] [INF] Opening SharedHttpStream Live stream from "http://i-cant-share-this/stream.ts"
[2020-01-26 20:40:17.913 -03:00] [ERR] Error opening tuner
System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.Open(CancellationToken openCancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
[2020-01-26 20:40:17.920 -03:00] [ERR] Error processing request
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.MediaInfoService.OpenMediaSource(OpenMediaSource request)
   at MediaBrowser.Api.Playback.MediaInfoService.GetPlaybackInfo(GetPostedPlaybackInfo request)
   at MediaBrowser.Api.Playback.MediaInfoService.Post(GetPostedPlaybackInfo request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System:**
 - OS: Ubuntu 18.04.3
 - Browser: Chromium 75
 - Jellyfin Version: 10.4.1
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**
The character in particular thats giving me trouble is a no-break space (`&nbsp;`, `\u00A0`).

**Comment by Bond-009** [comment]
IMO the ideal solution is validating that the input is ASCII only both in the client and the server.

**Comment by cvium** [comment]
.NET 5 now allows UTF8 encoding https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.requestheaderencodingselector?view=net-5.0
