### ISSUE TITLE
Security: Clarify Failed Login Message

### ISSUE THREAD

**Issue by soultoyo** [jellyfin/jellyfin#2351]
**Describe the bug**

When logging into the webui with correct credentials using username and password, I get an connection failure error. This has also happened to me when leaving the password field empty.

**Logs**
```
[16:33:44] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: resolvedUser
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Ubuntu 18.03 Bionic
 - Browser: Firefox/Chrome
 - Jellyfin Version: 10.4.3.0
 - Installed Plugins: none
 - Reverse proxy: no

**Comment by soultoyo** [comment]
Ok so it turned out to be that the user didn't exist so now I can log in, but the issue is that, I got an connection failure error box which lead to me believing that there was something wrong with the server rather than a user not existing within the database.

So in order to recreate the bug, just put anything within the username field when logging into the webui but make sure the user does not exist, then the server will display the above error.

**Comment by JustAMan** [comment]
That's actually a security-recommended way of doing things - don't disclose if a user doesn't exist or password didn't match or whatever on the frontend, just display "cannot login", so hackers won't be able to brute force easily.

I'm inclined to say that this stuff is working as intended here, at best we could potentially change the message to "Invalid username or password provided".

**Comment by soultoyo** [comment]
Ah right ok, I do think having a seperate message or changing the message to indicate that there is a login error is much better than having a connection failure error as that came across to me that something went wrong with the server.

Also it didn't help that when looking at the server logs that an programming error was spat out, it would of been better from a log point as well to indicate that something went wrong with regards to the login validation than throwing a Null exception.

Maybe the solution is to keep the existing message on the front end but to have more detail from the server logs instead? That way it could then meet the security recommendation whislt also mentioning in the sever log that something went wrong with the entered user credentials (but without indicating whether the username or password was wrong).

**Comment by Artiume** [comment]
Should we rename the title to Security: Clarify Failed Login Message or something to that nature?

**Comment by soultoyo** [comment]
I'll change the title to that instead :)

**Comment by Bond-009** [comment]
I'm pretty sure this has been changed in master

**Comment by Artiume** [comment]
Yep, it just says wrong username or password now. Close now or upon 10.5?

**Comment by Bond-009** [comment]
No need to keep it open

**Comment by Artiume** [comment]
I had the old warning on Android. I don't know if that's because I have android stable or that it needs to be patched as well

**Comment by anthonylavado** [comment]
@Artiume it’s because you have Android stable. It packages a version of -web when it’s released.

**Comment by Artiume** [comment]
@anthonylavado thanks for clarifying :) I figured that's how it worked but just wanted to make sure
