### ISSUE TITLE
Can't download or stream untranscoded media if the media store is a symlinked file

### ISSUE THREAD

**Issue by mijofa** [jellyfin/jellyfin#2354]
**Media Info of the file**
Not relevant, it is however a symlink to the real file which is in another location, both of which are accessible to the Jellyfin service

**Logs**
```
Jan 30 19:00:34 avian jellyfin[23804]: [19:00:34] [INF] User policy for mike. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
Jan 30 19:00:34 avian jellyfin[23804]: [19:00:34] [INF] Profile: Unknown Profile, Path: /FILENAME/REDACTED.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
Jan 30 19:00:34 avian jellyfin[23804]: [19:00:34] [ERR] Error processing request
Jan 30 19:00:34 avian jellyfin[23804]: System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (131072 of 138).
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory'1 data, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Emby.Server.Implementations.HttpServer.FileWriter.TransmitFile(Stream stream, String path, Int64 offset, Int64 count, FileShareMode fileShareMode, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Emby.Server.Implementations.HttpServer.FileWriter.WriteToAsync(HttpResponse response, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
Jan 30 19:00:34 avian jellyfin[23804]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Note the '138' number changes depending on the media file being loaded, I have determined that is in fact the path the symlink is pointing to.
Example: a symlink to "../../Media/foobar.baz" would be 22 while "../../Media/blah-blah-blah.blah" would be 31

**FFmpeg Logs**
Not relevant, transcoding isn't happening during failure

**Stats for Nerds Screenshots**
Not available in the places this problem is reproducable

**Server System (please complete the following information):**
 - OS: Linux/Debian 10
 - Jellyfin Version: 10.4.2
 - Hardware settings & device: VM running headless so I've not enabled any hardware decoding
 - Reverse proxy: Apache
 - Other hardware notes: Media is mounted via NFS from the host OS
 
**Client System (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 Pro, & my low-end gaming desktop (Nvidia GPU)
 - OS: Android LineageOS 15.1, & Debian 10
 - Client: org.jellyfin.mobile, Chromecast, jellyfin-mpv-shim, and Google Chrome
 - Browser (if Web client): Google Chrome when relevant.
 - Client and Browser Version: org.jellyfin.mobile 0.9.7 & Google Chrome 79.0.3945.117 (Official Build) (64-bit)

**Comment by Artiume** [comment]
Try a VM with nightly running, there's been a lot of work fixing chromecast and playback issues.

**Comment by mijofa** [comment]
Just upgraded to nightly now, no change in behaviour. Although now the logs are saying "isEligibleForDirectPlay: True, isEligibleForDirectStream: True" for **everything** even when it's actually running ffmpeg to transcode them, so I suspect the log message is lying now.

I'm pretty sure the issue is there in the "Response Content-Length mismatch: too many bytes written" message, but I'm not finding anything relavant when Googling around for that.

**Comment by Artiume** [comment]
isEligibleForDirectPlay is the server verifying that your user is allowed to directplay, not that ffmpeg wants to do that.

@anthonylavado @Bond-009 either of yall know what the too many bytes is about?

**Comment by mijofa** [comment]
I've come across jellyfin-mpv-shim and given that a go, yet I'm getting the exact same issue with that one.
Although with the mpv-shim I'm getting it for every video file. Seems to me like Jellyfin's web server is not properly respecting the Content-Length header and trying to send the whole file at once which some other part is getting mad about. Out of curiosity I got Apache to strip that request header out entirely but things fell apart much earlier when I did that.

**Comment by Artiume** [comment]
So I'm thinking you have a config issue somehow or another. No one else has mpv shim issues that I'm aware of

**Comment by mijofa** [comment]
I've barely done anything to the Jellyfin config, and I'm getting no change in symptoms even if I skip my reverse proxy and go to the Jellyfin VM's URL directly.
Jellyfin is simply not able to send untranscoded files, I've just noticed that even in the web browser, everything is being transcoded even files I expected the browser should be able to play natively. Not sure if that's by design or if that's maybe also related, although I'm not getting the same error in the logs.

I'll jump into the Jellyfin Matrix channel when I've got some time in the next few days and see what kind of help I can get there. If it is a config issue, there really need to be some better error messages or something

**Comment by Artiume** [comment]
Just to make sure, you aren't using docker, correct?

Maybe it's your apache proxy. I don't know it but yeah, a few people in the chat should be able to help ya

**Comment by mijofa** [comment]
> Just to make sure, you aren't using docker, correct?

Correct, not using Docker.
I am running a VM using libvirt & qemu though. However that should be effectively invisible to Jellyfin aside from perhaps a lack of hardware accelaration (which I've confirmed never got turned on anyway)

> Maybe it's your apache proxy. I don't know it but yeah, a few people in the chat should be able to help ya

I suspected that but even bypassing Apache I'm still having the problem

**Comment by Artiume** [comment]
Anything in your network settings? Oh, what about that? In your network settings, change it from handled by reverse proxy to disabled.

**Comment by mijofa** [comment]
Have tried all 4 options there and it doesn't make any difference to this.
I actually have that on "disabled" though, because "handled by reverse proxy" was causing an unrelated issue with the reverse proxy

**Comment by Artiume** [comment]
Yeah, leave it as Disabled. That said, you have to reboot the jellyfin service to enable any changes.

Here's the issues I documented with the setting. 
https://github.com/jellyfin/jellyfin/issues/2259 

Not sure if there's anything else that could be causing it. The mismatched bytes still occurring?

**Comment by mijofa** [comment]
Ah, I was seeing difference before restarting the service, have tried them all again with a service restart and no difference though.
Yeah, the mismatched bytes are still occuring.

**Comment by mijofa** [comment]
I jumped into the Matrix channel (via IRC) last night and got some help with this, think I've narrowed down the cause to being symlinks. Edit/update to the issue itself pending, here's a dump of the relevant Matrix/IRC chat though.

```
[17:47:33] <mijofa> Hey, so I'm getting this error in my Jellyfin logs every time I try to stream a movie via Chromecast or jellyfin-mpv-shim that doesn't require transcoding: "System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (131072 of 140)"
[17:48:52] <mijofa> Anyone able to give me some pointers?     The 140 number changes depending on what media file I'm loading, but the 131072 does not.    There's more lines after that but it's mostly just tracing the codepath, so the first one that's relevant would probably be this one: "at Emby.Server.Implementations.HttpServer.FileWriter.TransmitFile(Stream stream, String path, Int64 offset, Int64 count, FileShare 
[17:48:58] <mijofa> fileShare, CancellationToken cancellationToken)"
[17:51:42] <dkanada[m]> might be related to the fact that no one has touched the chromecast client in like eight months
[17:53:34] <mijofa> dkanada[m]: I suspect that was the case and hoped jellyfin-mpv-shim would go better, but still having the problem there
[17:54:02] <dkanada[m]> oh I didn't read the message correctly, doesn't sound like a chromecast issue then
[17:54:21] <dkanada[m]> if there's not an issue open in the server repo feel free to open one, sounds like a backend issue
[17:56:09] <mijofa> I opened #2354 before I tried jellyfin-mpv-shim, but I think I named it badly and it's not gotten much attention.  Not sure if it's a normal amount of attention or not though as I'm not to this project/community/etc so not really sure what to expect
[17:58:26] <mijofa> Err, *I'm new to this project
[17:59:01] <mijofa> Just got home from work, brain has turned off
[18:00:27] <dkanada[m]> it's not uncommon to get few or no comments on an issue depending on who is available at the moment
[18:00:49] <dkanada[m]> we are all volunteers so it just depends on who wants to spend their free time debugging issues
[18:02:48] <JustAMan[m]> mijofa: edit your issue and add relevant info like mpv-shim failures there
[18:03:21] <JustAMan[m]> Also try enabling debug logging and see if something surfaces up
[18:03:31] <mijofa> Yeah, all good, didn't expect otherwise. Is why I made sure to get the issue created before the weekend
[18:03:45] <mijofa> JustAMan[m]: Debug logging didn't give me any extra info
[18:03:59] <mijofa> JustAMan[m]: Will edit the issue, I keep forgetting I can just edit an issue on Github
[18:04:05] <JustAMan[m]> That's unfortunate :(
[18:04:23] <JustAMan[m]> That there's no debug logs with more info
[18:05:23] <iwalton3[m]> There are also the client logs on the mpv shim you can access via the tray icon. It’ll probably tell you what call is causing the error.
[18:07:01] <JustAMan[m]> That would be useful
[18:08:17] <JustAMan[m]> My suspect is that server prepared to send a chunk of file but something errored during the call, so server set the length of the response to length of error message but still sent the chunk
[18:08:37] <mijofa> Ah yes, there was no helpful errors there, but I did determine that it's hanging at the 'self._player.wait_for_property("duration")' line, so I believe mpv is not reporting any failure back, even though it is failing
[18:09:22] <mijofa> JustAMan[m]: That makes sense, is there somewhere else that error might've ended up if not the debug log?
[18:09:50] <iwalton3[m]> Yes that means it is able to get the video URL but it is dying within MPV.
[18:10:55] <iwalton3[m]> It is possible to tell MPV to print the logs, but I don’t have a config file for it. Could also run MPV externally (which allows it to print errors), but that’s kind of annoying to do.
[18:11:18] <iwalton3[m]> * It is possible to tell MPV to print the logs, but I don’t have a config file setting for it. Could also run MPV externally (which allows it to print errors), but that’s kind of annoying to do.
[18:12:13] <iwalton3[m]> I think there is an option to copy the video URL from the web interface. Maybe the error still occurs if you merely download the video.
[18:12:39] <dkanada[m]> there is on chrome, doesn't work on firefox yet
[18:12:43] <mijofa> Yep, just got jellyfin-mpv to print the stream url and tried just doing a curl request to that URL and it gives me a HTTP 500 response with "Response Content-Length mismatch: too many bytes written (131072 of 140)." in the body
[18:13:25] <mijofa> Ah, yes, the download button in Chrome has the exact same response (it's the same URL by the looks of things)
[18:13:56] <mijofa> Interesting the download button has an api_key in URL rather than doing the auth via cookies there
[18:14:34] <mijofa> Ah, not quite the same URL
[18:14:53] <JustAMan[m]> Is your user admin?
[18:15:00] <iwalton3[m]> That makes sense since those URLs usually end up in media player that aren’t good at handling cookies.
[18:15:09] <mijofa> JustAMan[m]: Yes
[18:15:33] <dkanada[m]> <mijofa "Interesting the download button "> chromecast, DLNA, and other players can't do auth based on a token so we have to include it in the url stream
[18:15:39] <JustAMan[m]> Also where the media file is stored, can your storage be misbehaving?
[18:16:12] <mijofa> Same issue with a non-admin user
[18:16:18] <JustAMan[m]> Like it reports a file is there but fails to read it
[18:17:44] <mijofa> The storage for the media file is an NFS mountpoint, so it's always a possibility, however I can watch the media just fine if I watch it in Chrome. It seems to be *always* transcoding when I do it that way though, which I suspect is the main difference
[18:21:37] <JustAMan[m]> If this reproduces regularly, maybe someone would be able to cook a special build with way more logging, so we can at least have a clue what's going on
[18:21:59] <JustAMan[m]> Also, I haven't read your ticket yet, but did you try latest nightly?
[18:22:11] <iwalton3[m]> If you want to eliminate the filesystem as a possibility, you could   probably move the file to the local drive and symlink is back into the NFS drive.
[18:22:35] <iwalton3[m]> * If you want to eliminate the filesystem as a possibility, you could probably move the file to the local drive and symlink is back into the NFS drive.
[18:24:35] <mijofa> JustAMan[m]: I've upgraded to nightly, yes.    This is very regular I can't stream with jellyfin-mpv-shim without running into this issue
[18:25:00] <mijofa> iwalton3[m]: I didn't even consider symlinking it back, it's so obvsious, trying now
[18:25:28] <iwalton3[m]> If you want a quick work-around, you can also configure jellyfin mpv shim to always transcode. This is obvious not ideal though.
[18:25:29] <mijofa> I was trying to figure out how to eliminate NFS without messing about with a whole extra Jellyfin library
[18:29:22] <mijofa> Have just confirmed that setting it to always transcode does work for jellyfin-mpv-shim, but yeah, certainly not ideal
[18:31:29] <mijofa> Same issue when not coming from an NFS share
[23:21:33] <mcarlton[m]> mijofa: artiume I think was running into the same issue the other day.  not sure if anybody tracked it down yet
[23:23:11] <mijofa> mcarlton[m]: My issue from earlier? Artiume is the one who's responded to my Github issue, so perhaps related.    I'll edit that issue with some updates in the morning, I think I've gotten much closer, with some help from here
[23:24:01] <mijofa> I've been getting a little lost with my lack of C# knowledge for diagnosing this one
[23:51:47] <mijofa> So I had an epiphany after going to bed and had to fire up SSH on my phone to test my theory... It was the symlinks!!!
[23:52:43] <artiume[m]> <mijofa "So I had an epiphany after going"> Not using hard links? Lol
[23:52:47] <mijofa> My JF media directory is currently a bunch of symlinks to the files in my old system, something in the file sending stack of JF is failing to send the file
[23:53:41] <mijofa> artiume[m]: Nope, because they're harder to keep track of logically
[23:54:35] <mijofa> Can switch to hardlinks temporarily, but I'd definitely say not being able to deal with symlinks on a Linux OS is a bug
[23:55:01] <mijofa> So relieved to have this on figured out though, it's been bugging me for *weeks*
[23:55:44] <mijofa> Back to bed for me, thanks for all your help/input/advice/etc everyone!! Will update the Github issue with my findings tomorrow
[03:26:17] <JustAMan[m]> <mijofa "So I had an epiphany after going"> Pls state this in the bug
[03:45:51] <JustAMan[m]> I wonder if this is relevant: https://github.com/dotnet/runtime/issues/24271
```

**Comment by mijofa** [comment]
My temporary work around for this is to use bindfs like so
```
sudo mv /srv/media/jellyfin-media /srv/media/jellyfin-symlinks
sudo install -o jellyfin -g media -m 0770 /srv/media/jellyfin-media
printf 'This is space intentionally left blank.\nThis is an empty directory meant only as a mountpoint for bindfs, ref https://github.com/jellyfin/jellyfin/issues/2354\n' >jellyfin-media/README.txt
```

Then tacked this onto the end of /etc/fstab in the VM:
```
bindfs#/srv/media/jellyfin-symlinks /srv/media/jellyfin-media    fuse  rw,resolve-symlinks,resolved-symlink-deletion=symlink-only  0  3
```

**Comment by tuonglan** [comment]
Having the same issue on Jellyfin 10.5.5 when trying to download movies from symlinks.
Here's a snippet of the server log:
`[2020-05-20 23:36:08.682 +09:00] [ERR] [81] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://127.0.0.1:9001/Items/14ec2f0bc8d9ce0ee532e647e55cf4c7/Download"
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (**131072** of **112**).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
`
131072 = 128KiB and 112 is **exactly equal** to the size of the symlink so I guess the server was trying to request a 128KiB block of the the original file but instead ended up with the symlink itself. 
Is there any temporary workaround on this on Ubuntu Docker?

**Comment by Ken-g6** [comment]
This looks relevant: https://stackoverflow.com/questions/2302416/how-to-obtain-the-target-of-a-symbolic-link-or-reparse-point-using-net#33487494

Then the problem is to find where Jellyfin is trying to determine the content length in the first place.

**Comment by mijofa** [comment]
My _workaround_ was to stop Jellyfin's service, move my directory of symlinks to a different directory, then use bindfs to make the original symlink location look like a directory full of files, then start the Jellyfin service back up. This way Jellyfin never needed to rescan and regenerate the database, and everything started working.
Theoretically you should be able to configure Docker to use a bindfs mount point for the media store. Otherwise you might need to do bindfs at a lower layer there depending on your system setup.

I don't know any C# myself, so am not comfortable making my own pull request for this issue, but it looks like it should be a fairly easy one to fix. Symlinks are pretty standard, should almost just be a matter of setting a certain option when opening the file handle.

**Comment by Artiume** [comment]
For linux, wouldn't hard linking work?

**Comment by Ken-g6** [comment]
Hard linking would work, unless you cross filesystems, which I do.  (Soft links are on SSD; actual files are on two HDDs.)

I wrote a patch for this that might fix it; it even compiles; but I haven't tested it yet.
```
diff --git a/Emby.Server.Implementations/IO/ManagedFileSystem.cs b/Emby.Server.Implementations/IO/ManagedFileSystem.cs
index 7461ec4f1..8b75e8c70 100644
--- a/Emby.Server.Implementations/IO/ManagedFileSystem.cs
+++ b/Emby.Server.Implementations/IO/ManagedFileSystem.cs
@@ -245,6 +245,16 @@ namespace Emby.Server.Implementations.IO
                 if (info is FileInfo fileInfo)
                 {
                     result.Length = fileInfo.Length;
+
+                    // Issue #2354 get the size of files behind symbolic links
+                    if(fileInfo.Attributes.HasFlag(FileAttributes.ReparsePoint))
+                    {
+                        using (Stream thisFileStream = File.OpenRead(fileInfo.ToString()))
+                        {
+                            result.Length = thisFileStream.Length;
+                        }
+                    }
+
                     result.DirectoryName = fileInfo.DirectoryName;
                 }
 ```

**Comment by Artiume** [comment]
Awesome. Hopefully that's the fix!

For unions of hdd's, I use mergerfs. It's quite versatile. You could do similar things with your ssd/hdd hybrid.

https://jellyfin.org/docs/general/server/storage.html#mergerfs

**Comment by tuonglan** [comment]
@Ken-g6 does your patch work? I'm not familiar with C# so it could take me ton of time to compile and run.
My second guess for the root cause of both download & playback comes from the exception stack:

`5231    at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
5232    at Emby.Server.Implementations.HttpServer.FileWriter.TransmitFile(Stream stream, String path, Int64 offset, Int64 count, FileShare fileShare, CancellationToken cancellationToken)
5233    at Emby.Server.Implementations.HttpServer.FileWriter.WriteToAsync(HttpResponse response, CancellationToken cancellationToken)
5234    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
5235    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
5236 [2020-05-22 10:44:26.470 +09:00] [DBG] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to "http://127.0.0.1:9001/Items/14ec2f0bc8d9ce0ee532e647e55cf4c7/Download"
`
The function **_TransmitFile_** in https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/HttpServer/FileWriter.cs can't work with symlink so it ends up with ffmpeg being kicked off or download error.
For the comparison, Emby use a different response to deal with the transmission (the IResponse::TransmitFile) https://github.com/MediaBrowser/Emby/blob/master/Emby.Server.Implementations/HttpServer/FileWriter.cs

**Comment by mijofa** [comment]
@Artiume, yes, I've confirmed that hardlinks work. They weren't suitable for my system where I need to be able to trace a link back to the original file name easily, but if it works in your use-case go for it.

@Ken-g6, it looks like your patch is only changing the code that checks the file size. I believe there's more to this issue and it needs to be fixed when opening the file for any reason (except deleting, original file should not be deleted when symlinks are deleted).
Perhaps worth making a pull request for it to get some attention from reviewers though and go from there.

**Comment by JustAMan** [comment]
@Ken-g6 I played with your idea a bit, and it _might_ solve the issue. I don't want to steal your glory, would you mind making a PR with that? The only correction I'd suggest is doing `File.OpenRead(fileInfo.FullName)` instead of `.ToString()`.

**Comment by iotku** [comment]
Any progress on this?

I've recently switched to a pretty elaborate symlink setup to get media paths into structures that scan more properly (as I can't modify my source media), but I'm getting bit by this issue.

Currently, on 10.6.0 (Nightly): Streaming of Videos seems fine (on Web at least), but Music doesn't stream at all if symlinked ("This client isn't compatible with the media and the server isn't sending a compatible media format.") nor does download work. 

The `bindfs --resolve-symlinks` workaround mentioned here https://github.com/iwalton3/jellyfin-mpv-shim/issues/79#issuecomment-646978198 seems to work, however it's adding yet another layer of abstraction for me to deal with (sshfs -> symlinks -> bindfs), so it's not ideal.

**Comment by mijofa** [comment]
Not been fixed yet, my workaround has been to use bindfs's resolve symlinks option (as described in my /etc/fstab snippet above) I don't like it in the long-term, but it works well until we get a proper fix in the jellyfin codebase.

If you're using sshfs, you might be able to get away with the '-o follow_symlinks' option. If the symlinks are on the remote server you can mount them locally such that you don't see them as symlinks.

**Comment by noctux** [comment]
@Ken-g6 @JustAMan Just applied the patch (using the suggested `.FullName`) against jellyfin-10.5.5 and it fixed my problems when trying to play movies using jellyfin-kodi without transcoding for symlinked mediafiles. So I would be really grateful if you could wrap that up into a proper PR so that it might be fixed permanently with the next release?

**Comment by Ken-g6** [comment]
OK, I finally posted a PR.  I never did manage to compile the full Jellyfin system for testing.  For why I didn't use .FullName see the PR.

**Comment by noctux** [comment]
Hey, thanks for posting the PR! At least on my system, it did compile using FullName... But I'm sure the devs will know best in the end :)

**Comment by Ken-g6** [comment]
This issue is back in 10.7.0. I left my configuration at not transcoding anything, and now nothing soft-linked plays.  I don't have time right now to go diagnose it.

**Comment by iotku** [comment]
Yeah same here, haven't really had time to dig into proper repro steps but it's been an issue for at least the last couple RCs where certain symlinked files I can't stream and I'll get a HTTP 500 error if I try to play from a stream url/download

and I get

> System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (16384 of 78).
in my jellyfin.log

The if I su into the jellyfin user I can use mediainfo to access the files so I don't think it's a permissions issue.

**Comment by iotku** [comment]
At a quick glance, the most defining difference between the files that work and the ones that don't is that the filenames have spaces in them, but that could just be happenstance.

**Comment by iotku** [comment]
Just noticed 10.7.0 proper was released so I'll verify there. (Although it might be the same as RC4?)

**Comment by mijofa** [comment]
I've so far still not seen this issue resolved in any stable release (I don't track the RC releases) and have stuck with the bindfs workaround. I'm not happy about it, but I've largely just assumed the PR hasn't made it through.
Although given the issue is closed, it seems someone thinks it has gotten through?

**Comment by Damme** [comment]
I have had this issue for ages, never put much thought into it since I stated using chrome cast instead, that gave me other problems with not being able to play sources without transcoding. 4k HDR was my biggest issue. I do not want to transcode HDR.

I started searching and testing, and my issue was soft links, (ln -s) .. hard link (ln -P) and it worked directly...
doing a curl on the url with softlinkes gives me :
curl: (18) transfer closed with 96 bytes remaining to read
while hard link just works...

If I only found this issue earlier would have saved me much headakes... This issue should not be closed since it is not resolved. version running atm: 10.7.5

**Comment by crobibero** [comment]
See https://github.com/jellyfin/jellyfin/issues/5521 for further information. This is an upstream issue.

**Comment by neingeist** [comment]
I also have this problem using 10.7.7

**Comment by neingeist** [comment]
> I also have this problem using 10.7.7

Running unstable fixes this problem, "Download" and  playing a stream using VLC (using "Copy stream URL") work fine. I guess it is #6541 and from the looks of it it's going to be in 10.8.0 🤞
