### ISSUE TITLE
Jellyfin Fails to start if using a plugin (docker)

### ISSUE THREAD

**Issue by plessbd** [jellyfin/jellyfin#2360]
When using the jellyfin Docker (either jellyfin/jellyfin:[latest|nightly] or linuxserver/jellyfish) and trying to install a plugin I get the attached errors.
Deleteing the plugin allows startup

**To Reproduce**

1. Start docker
2. Run Wizard
3. Install Plugin (Specifically tried kodi sync queue and auto box set)

**Expected behavior**
Expect plguin to be installed and work

**Logs**

```
04:47:10] [FTL] Error while starting server.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[04:47:10] [INF] Disposing CoreAppHost
[04:47:10] [FTL] Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```
**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: n/a
 - Jellyfin Version: latest and nightly
 - Installed Plugins: This s the problem
 - Reverse proxy: none

**Additional context**

**Comment by Artiume** [comment]
This should now be fixed with https://github.com/jellyfin/jellyfin/issues/2333

**Comment by plessbd** [comment]
This did not seem to work for me.

Started docker without plugins
ran docker exec -it container /bin/bash
installed ca-certificates
when to install plugin got the follow:

```
03:20:42] [FTL] Unhandled Exception
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__249_0(String x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Out of memory.
```

when trying to then start the docker again got the following:
```
03:20:42] [FTL] Unhandled Exception
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__249_0(String x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Out of memory.
```

If there is anything else I can do or more debugging please let me know

**Comment by Artiume** [comment]
That's unusual. Do you mind using something like Glances to watch for host issues? How much ram do you have? Are you limiting memory to the container? I haven't received an OOM before

**Comment by plessbd** [comment]
32gigs of ram, not limiting the container any.  I have not heard of glances, but I have no objection to using it assuming it is this: https://nicolargo.github.io/glances/

Anything specific you want me to look for / at?


actually, I may have found something.
I am using mergerFS for my file system and was trying t put the configs on that.  Found this on their page https://github.com/trapexit/mergerfs#plex-doesnt-work-with-mergerfs

Seems like moving away from the merged filesystem seems to have fixed my issue.  But if it is not related to a sqlite issue I will still try to debug if you want.

**Comment by Artiume** [comment]
Ok, yeah that would do it. I recommend only using mergerfs for media storage not the database.

**Comment by plessbd** [comment]
Yeah that is what I am seeing as well, this is the first time I have used mergerfs, I am liking it, just not used to it.  Thank you for the time and working though this with me.
