### ISSUE TITLE
Musicbrainz error?

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2386]
**Describe the bug**

I dont know if this is normal or not, but it's happening when I scan music.
**To Reproduce**

1. Scan music library

**Logs**

```
[2020-02-07 00:41:06.690 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "01 - Tuistos Herz.flac"
[2020-02-07 00:41:06.691 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "02 - Der Tod Wuotans.flac"
[2020-02-07 00:41:06.691 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "03 - Ansuzgardaraiw�.flac"
[2020-02-07 00:41:06.692 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "04 - Die Liebe Ner�us'.flac"
[2020-02-07 00:41:06.693 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "05 - Frij�s Einsames Trauern.flac"
[2020-02-07 00:41:06.694 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "06 - Einf�hlungsverm�gen.flac"
[2020-02-07 00:41:06.694 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "07 - Frij�s Goldene Tr�nen.flac"
[2020-02-07 00:41:06.695 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "08 - Der Weinende Hadnur.flac"
[2020-02-07 00:41:06.700 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:07.480 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetMetadata(ArtistInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:08.723 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:09.412 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "Burzum - 02 - Belus' D�d.flac"
[2020-02-07 00:41:09.416 +00:00] [WRN] [47] BaseItem: Unable to find linked item at path "Burzum - 07 - Morgenr�de.flac"
[2020-02-07 00:41:09.427 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:11.838 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:12.533 +00:00] [ERR] [47] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetMetadata(ArtistInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:15.519 +00:00] [ERR] [35] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:16.271 +00:00] [ERR] [35] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetMetadata(ArtistInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:18.982 +00:00] [ERR] [35] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:19.673 +00:00] [ERR] [35] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetMetadata(ArtistInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:22.292 +00:00] [ERR] [46] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResultByArtistName(String albumName, String artistName, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-02-07 00:41:22.965 +00:00] [ERR] [46] App: Error in "MusicBrainz"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetMetadata(ArtistInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
**System (please complete the following information):**
 - OS: Docker ubuntu 18
 - Browser: Chrome
 - Jellyfin Version: 10.5
 - Installed Plugins: trakt,tmdb box sets,opensubtitles
 - Reverse proxy: nginx

**Comment by dkanada** [comment]
resolved by #2436
