### ISSUE TITLE
Photo album does not open

### ISSUE THREAD

**Issue by dmitrylyzo** [jellyfin/jellyfin#2387]
**Describe the bug**
When I try to open photo album from library I get error `500` with response:
```
The JSON property name for 'MediaBrowser.Controller.Entities.Photo.Width' collides with another property.
```

**To Reproduce**
1. Go to Photo Library
2. Click on some album
3. See endless "loading"

**Expected behavior**
Photo album should open normally.

**Logs**
```
[2020-02-07 11:04:48.929 +03:00] [ERR] Error processing request
System.InvalidOperationException: The JSON property name for 'MediaBrowser.Controller.Entities.Photo.Width' collides with another property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(JsonClassInfo jsonClassInfo, JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(IReadOnlyList`1 reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Boolean hasServiceName, Boolean queryHasStartDate, Boolean hasTrailerTypes, Boolean hasArtistFields, Boolean hasSeriesFields)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren()
   at MediaBrowser.Controller.Entities.Folder.LoadChildren()
   at MediaBrowser.Controller.Entities.Folder.GetEligibleChildrenForRecursiveChildren(User user)
   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren)
   at MediaBrowser.Controller.Entities.Folder.GetItemsInternal(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildCount(User user)
   at Emby.Server.Implementations.Dto.DtoService.GetChildCount(Folder folder, User user)
   at Emby.Server.Implementations.Dto.DtoService.AttachUserSpecificInfo(BaseItemDto dto, BaseItem item, User user, DtoOptions options)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at MediaBrowser.Api.UserLibrary.UserLibraryService.Get(GetItem request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

```

**System (please complete the following information):**
 - OS: server on Ubuntu 18.04 64bit, client on Kubuntu 19.04 64bit
 - Browser: Chrome 79, Firefox 72
 - Jellyfin Version: nightly-20200206
 - Installed Plugins: none
 - Reverse proxy: no

**Additional context**
jellyfin-nightly from deb-package.

**Comment by JustAMan** [comment]
cc @Bond-009 as I think it has something to do with some of your JSON PRs...

**Comment by Bond-009** [comment]
This is a dotnet issue: https://github.com/dotnet/runtime/issues/30964
