### ISSUE TITLE
Library scanning is aborted if doesn't have permission in any of subfolders

### ISSUE THREAD

**Issue by davispuh** [jellyfin/jellyfin#2402]
**Describe the bug**

Added library `/mnt/Movies` but scanning stopped because access to `/mnt/Movies/Private` was denied even if there's a lot of other folders and files with allowed permissions.

**To Reproduce**
1. Add folder without permissions
2. Check log

**Expected behavior**
Library scanning should still continue with other folders/files.

**Logs**
````
[2020-02-13 07:19:45.476 +02:00] [INF] "StartupTrigger" fired for task: "Check for plugin updates"
[2020-02-13 07:19:45.478 +02:00] [INF] Queueing task "PluginUpdateTask"
[2020-02-13 07:19:45.484 +02:00] [INF] Executing "Check for plugin updates"
[2020-02-13 07:19:45.819 +02:00] [ERR] Error in Directory watcher for: "/mnt/Movies"
System.UnauthorizedAccessException: Access to the path '/mnt/Movies/Private' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2020-02-13 07:19:45.819 +02:00] [INF] Stopping directory watching for path "/mnt/Movies"
[2020-02-13 07:19:46.210 +02:00] [INF] Watching directory /mnt/Music
[2020-02-13 07:19:46.453 +02:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 0 seconds
[2020-02-13 07:19:46.484 +02:00] [INF] ExecuteQueuedTasks
[2020-02-13 07:19:49.505 +02:00] [INF] Watching directory /mnt/Movies
[2020-02-13 07:19:57.944 +02:00] [ERR] Error processing request: "A task was canceled."
````

**System (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: nginx

Also is there any way where I could see library scanning progress?

**Comment by davispuh** [comment]
Maybe this is kinda related to #792 but for me it didn't crash.

**Comment by davispuh** [comment]
Hmm, maybe this isn't bug. I thought that after adding library it will automatically scan whole folder which didn't happen. But now when I went to Scheduled Tasks and manually pressed to Scan Media Library it's scanning it and ignoring any permission errors which is exactly what I needed.

**Comment by davispuh** [comment]
It's still issue, with latest v10.5.5 can see in log

```
[2020-06-13 02:11:23.412 +03:00] [INF] [111] TaskManager: Executing "Scan Media Library"
[2020-06-13 02:11:23.412 +03:00] [INF] [111] LibraryMonitor: Stopping directory watching for path "/mnt/Books"
[2020-06-13 02:11:23.415 +03:00] [INF] [111] LibraryMonitor: Stopping directory watching for path "/mnt/Music"
[2020-06-13 02:11:23.437 +03:00] [INF] [111] LibraryManager: Validating media library
[2020-06-13 02:11:23.573 +03:00] [ERR] [111] LibraryManager: Error resolving path "/mnt/Movies/test"
System.UnauthorizedAccessException: Access to the path '/mnt/Movies/test' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive) in /mnt/AUR/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 644
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Providers/DirectoryService.cs:line 33
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts) in /mnt/AUR/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/IO/FileData.cs:line 56
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions) in /mnt/AUR/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Library/LibraryManager.cs:line 614
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass85_0.<ResolveFileList>b__0(FileSystemMetadata f) in /mnt/AUR/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Library/LibraryManager.cs:line 714
```

**Comment by davispuh** [comment]
Hmm actually it might be working correctly
Later in log

```
[2020-06-13 02:16:30.753 +03:00] [INF] [103] TaskManager: "Scan Media Library" Completed after 5 minute(s) and 7 seconds
[2020-06-13 02:16:30.755 +03:00] [INF] [103] TaskManager: ExecuteQueuedTasks
[2020-06-13 02:16:30.918 +03:00] [INF] [110] LibraryMonitor: Watching directory /mnt/Music
[2020-06-13 02:16:30.942 +03:00] [ERR] [114] LibraryMonitor: Error in Directory watcher for: "/mnt/Movies"
System.UnauthorizedAccessException: Access to the path '/mnt/Movies/test' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2020-06-13 02:16:30.942 +03:00] [INF] [114] LibraryMonitor: Stopping directory watching for path "/mnt/Movies"
[2020-06-13 02:16:30.943 +03:00] [INF] [114] LibraryMonitor: Watching directory /mnt/Movies
[2020-06-13 02:16:30.950 +03:00] [INF] [109] LibraryMonitor: Watching directory /mnt/Books
```
