### ISSUE TITLE
[Bug] Issue when importing big libraries (Folder with many files)

### ISSUE THREAD

**Issue by CyberPoison** [jellyfin/jellyfin#2470]
**Describe the bug**
Still with the progress icon at 5% and nothing appears on the logs (Check logs bellow)

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser, Android, Fire Stick, etc.
 - Browser: Firefox,Chrome
 - Jellyfin Version: nightly
 - Storage: [Gsuite]

**To Reproduce**

1. Go to Libraries
2. Click on Import Libraries (With many files/sub folders on the same folder)
3. Scroll down to Movies 
4. See Logs and Progressbar

**Expected behavior**

Scanning the Libraries from the folders selected
**Logs**
```
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: Architecture: X64
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: 64-Bit Process: True
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: User Interactive: True
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: Processor count: 12
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: Program data path: "/config/data"
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web"
[2020-02-26 14:26:34.903 +00:00] [INF] [4] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2020-02-26 14:26:34.984 +00:00] [INF] [4] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:26:35.000 +00:00] [INF] [4] App: Loading assemblies
[2020-02-26 14:26:35.212 +00:00] [WRN] [4] Emby.Server.Implementations.Library.UserManager: No users, creating one with username "abc"
[2020-02-26 14:26:35.485 +00:00] [INF] [4] ServerConfigurationManager: Saving system configuration
[2020-02-26 14:26:35.485 +00:00] [INF] [4] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:26:35.859 +00:00] [INF] [4] Main: Kestrel listening on all interfaces
[2020-02-26 14:26:35.940 +00:00] [INF] [4] App: Running startup tasks
[2020-02-26 14:26:35.946 +00:00] [INF] [4] TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 02/27/2020 02:00, which is 11:33:24.0534483 from now.
[2020-02-26 14:26:35.974 +00:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.2.1"
[2020-02-26 14:26:35.994 +00:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2020-02-26 14:26:36.004 +00:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_omx", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-02-26 14:26:36.005 +00:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2020-02-26 14:26:36.006 +00:00] [INF] [4] App: ServerId: "b2ecac931eb548cbb9c878899f5c52ab"
[2020-02-26 14:26:36.124 +00:00] [INF] [11] App: Executed all pre-startup entry points in 0:00:00.1128546
[2020-02-26 14:26:36.125 +00:00] [INF] [11] App: Core startup complete
[2020-02-26 14:26:36.185 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.185 +00:00] [ERR] [7] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.185 +00:00] [ERR] [8] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.185 +00:00] [ERR] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.185 +00:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.282 +00:00] [INF] [11] App: Executed all post-startup entry points in 0:00:00.1570946
[2020-02-26 14:26:36.282 +00:00] [INF] [11] Main: Startup complete 0:00:01.5219025
[2020-02-26 14:26:36.331 +00:00] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.332 +00:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.332 +00:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.332 +00:00] [ERR] [7] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.332 +00:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.333 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.362 +00:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.398 +00:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.398 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.398 +00:00] [ERR] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.398 +00:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.399 +00:00] [ERR] [14] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.402 +00:00] [ERR] [14] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.434 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.438 +00:00] [ERR] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.438 +00:00] [ERR] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.438 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.438 +00:00] [ERR] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.438 +00:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.472 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.518 +00:00] [ERR] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.519 +00:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.522 +00:00] [ERR] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.522 +00:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:36.522 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:37.736 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:37.751 +00:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:37.760 +00:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:37.766 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:37.790 +00:00] [INF] [5] App: WS "http://ip:9096/socket?api_key=6f5a72f40545455e81dfde66c125694c&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83My4wfDE1ODI2NTIyMDk0NjY1". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
[2020-02-26 14:26:38.947 +00:00] [INF] [21] TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-02-26 14:26:38.949 +00:00] [INF] [21] TaskManager: Queueing task "PluginUpdateTask"
[2020-02-26 14:26:38.953 +00:00] [INF] [19] TaskManager: Executing "Update Plugins"
[2020-02-26 14:26:39.656 +00:00] [INF] [21] TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2020-02-26 14:26:39.685 +00:00] [INF] [21] TaskManager: ExecuteQueuedTasks
[2020-02-26 14:26:42.587 +00:00] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:42.595 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:43.181 +00:00] [ERR] [15] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "A task was canceled."
[2020-02-26 14:26:46.949 +00:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:46.958 +00:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-02-26 14:26:46.982 +00:00] [ERR] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:26:52.238 +00:00] [INF] [5] ServerConfigurationManager: Saving system configuration
[2020-02-26 14:26:52.239 +00:00] [INF] [5] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:27:21.744 +00:00] [WRN] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:00.7542128. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FFR%2FFilms%5BFR%5D"
[2020-02-26 14:27:42.838 +00:00] [WRN] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.067922. "http://ip:9096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Films%20-%20%5BFR%5D"
[2020-02-26 14:28:22.266 +00:00] [WRN] [14] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0075179. "http://ip:9096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Films%20-%20%5B4K-FR%5D"
[2020-02-26 14:28:40.531 +00:00] [WRN] [14] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:00.9648336. "http://ip:9096/Environment/Drives"
[2020-02-26 14:29:12.345 +00:00] [WRN] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0105098. "http://ip:9096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Filmes%20-%20%5B4K-PT-EN%5D"
[2020-02-26 14:29:43.430 +00:00] [WRN] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:01.215904. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FEN%2FMovies%5BEN%5D"
[2020-02-26 14:30:17.620 +00:00] [WRN] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0061671. "http://ip:9096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Filmes%20-%20%5BPT-EN%5D"
[2020-02-26 14:30:55.701 +00:00] [WRN] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:00.6877931. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FFR%2FFilms%5BFR%5D"
[2020-02-26 14:31:24.069 +00:00] [WRN] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0033335. "http://ip:9096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=S%C3%A9ries%20T%C2%B4%C2%B4el%C3%A9%20-%20%5BFR%5D"
[2020-02-26 14:32:23.498 +00:00] [WRN] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0076417. "http://ip:9096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=S%C3%A9ries%20T%C3%A9l%C3%A9%20-%20%5B4K-FR%5D"
[2020-02-26 14:32:47.962 +00:00] [WRN] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:01.0640852. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FFR%2FSeries%5BFR%5D"
[2020-02-26 14:34:34.275 +00:00] [WRN] [39] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:00.5491628. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FEN%2FTVShows%5BEN%5D"
[2020-02-26 14:35:07.778 +00:00] [WRN] [34] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.3880418. "http://ip:9096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=S%C3%A9ries%20TV%20-%20%5BPT-EN%5D"
[2020-02-26 14:36:12.613 +00:00] [WRN] [47] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "ip". Time (slow): 0:00:03.819605. "http://ip:9096/Environment/DirectoryContents?includeDirectories=true&path=%2Fmnt%2Ftcrypt%2FFR"
[2020-02-26 14:36:36.501 +00:00] [WRN] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.4356834. "http://ip:9096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Adult%20-%20%5B4K-HD%5D"
[2020-02-26 14:37:29.033 +00:00] [WRN] [45] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:00.9998173. "http://ip:9096/Library/VirtualFolders?refreshLibrary=false&name=YouTube%20-%20%5BMulti%5D"
[2020-02-26 14:38:12.013 +00:00] [WRN] [43] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0034418. "http://ip:9096/Library/VirtualFolders?refreshLibrary=false&name=Twitch%20-%20%5BMulti%5D"
[2020-02-26 14:39:00.085 +00:00] [WRN] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:00.9998273. "http://ip:9096/Library/VirtualFolders?refreshLibrary=false&name=Sport%20-%20%5BMulti%5D"
[2020-02-26 14:40:29.646 +00:00] [WRN] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "ip". Time (slow): 0:00:01.0004283. "http://ip:9096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=S%C3%A9ries%20TV%20-%20%5B4K-PT-EN%5D"
[2020-02-26 14:40:54.775 +00:00] [INF] [50] ServerConfigurationManager: Saving system configuration
[2020-02-26 14:40:54.776 +00:00] [INF] [50] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:41:04.230 +00:00] [INF] [48] ServerConfigurationManager: Saving system configuration
[2020-02-26 14:41:04.231 +00:00] [INF] [48] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:41:06.138 +00:00] [INF] [48] ServerConfigurationManager: Saving system configuration
[2020-02-26 14:41:06.139 +00:00] [INF] [48] ServerConfigurationManager: Setting cache path: "/config/cache"
[2020-02-26 14:41:06.144 +00:00] [INF] [50] TaskManager: Queueing task "RefreshMediaLibraryTask"
[2020-02-26 14:41:06.144 +00:00] [INF] [48] TaskManager: Executing "Scan Media Library"
[2020-02-26 14:41:06.151 +00:00] [INF] [48] LibraryManager: Validating media library
[2020-02-26 14:41:08.316 +00:00] [ERR] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:41:08.316 +00:00] [ERR] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-02-26 14:41:08.317 +00:00] [ERR] [57] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-02-26 14:41:19.569 +00:00] [INF] [30] Emby.Server.Implementations.Library.UserManager: Authentication request for "root" "has succeeded".
[2020-02-26 14:41:19.571 +00:00] [INF] [30] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 40676cb4-c4dc-4039-ac23-be8ba6a83d60
[2020-02-26 14:41:19.730 +00:00] [INF] [57] App: WS "http://ip:9096/socket?api_key=77a68263e29448dd8aeed11a14050f93&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83My4wfDE1ODI2NTIyMDk0NjY1". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

**Screenshots**

**My library appears empty**
![image](https://user-images.githubusercontent.com/60718477/75356736-a2615e80-58b0-11ea-9b77-d81284adceb8.png)

The progress bar appears but nothing on logs and on the library...
![image](https://user-images.githubusercontent.com/60718477/75356846-c45ae100-58b0-11ea-9ab2-0438aabcd7ea.png)

**Additional context**

Number of Elements should be imported (4000~aprox.) 

I have waited for 24Hours to be sure than this is not importing and i'm now be sure now than it's not import folders with many subfolder / files inside.

**Comment by CyberPoison** [comment]
Things already tried,

Reboot server, (result at the same issue)
Remove the config directory and recreate the server again. 
.................................................................................................................................

**Comment by Artiume** [comment]
Have you been able to have any more success with importing?

**Comment by CyberPoison** [comment]
@Artiume no, the only way i have found to get it working it's to re-delete the /config directory and re-import everything. 

Kind regards

**Comment by JustAMan** [comment]
Please update to 10.5.0, retry and report back.
