### ISSUE TITLE
[ERR] Error getting exported types from BlurayMounter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by stevleibelt** [jellyfin/jellyfin#2493]
**Describe the bug**
Non of the three available [arch linux aur](https://aur.archlinux.org/packages/?O=0&K=jellyfin) packages will start.
All resulting in the same error.

**System:**
 - OS: Arch Linux 5.4.22-1-lts
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse Proxy: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Install one of the available aur packages (jellyfin, jellyfin-bin, jellyfin-git)
2. sudo journal -xfn &
3. sudo systemctl start jellyfin.service

**Expected behavior**
Service should start.

**Logs**
```
Mar 01 22:22:33 <hostname> jellyfin[33623]: [22:22:33] [INF] Loaded assembly BlurayMounter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/BlurayMounter.dll
Mar 01 22:22:34 <hostname> jellyfin[33623]: [22:22:33] [ERR] Error getting exported types from BlurayMounter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Mar 01 22:22:34 <hostname> jellyfin[33623]: System.TypeLoadException: Could not load type 'MediaBrowser.Model.IO.IMediaMounter' from assembly 'MediaBrowser.Model, Version=10.4.3.0, Culture=neutral, PublicKeyToken=null'.
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
Mar 01 22:22:34 <hostname> jellyfin[33623]: [22:22:34] [INF] Loaded assembly Emby.PortMapper, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Emby.PortMapper.dll
Mar 01 22:22:34 <hostname> jellyfin[33623]: [22:22:34] [ERR] Error getting exported types from Emby.PortMapper, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null
Mar 01 22:22:34 <hostname> jellyfin[33623]: System.TypeLoadException: Method 'RunAsync' in type 'Emby.PortMapper.ExternalPortForwarding' from assembly 'Emby.PortMapper, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
Mar 01 22:22:34 <hostname> jellyfin[33623]: [22:22:34] [INF] Loaded assembly Emby.Server.CinemaMode, Version=1.0.30.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Emby.Server.CinemaMode.dll
Mar 01 22:22:34 <hostname> jellyfin[33623]: [22:22:34] [ERR] Error getting exported types from Emby.Server.CinemaMode, Version=1.0.30.0, Culture=neutral, PublicKeyToken=null
Mar 01 22:22:34 <hostname> jellyfin[33623]: System.TypeLoadException: Method 'RunAsync' in type 'Emby.Security.PluginSecurityManager' from assembly 'Emby.Server.CinemaMode, Version=1.0.30.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Mar 01 22:22:34 <hostname> jellyfin[33623]:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
```

**Additional context**
Initially, the system had an emby installation but I've removed it as much as possible.

**Comment by stevleibelt** [comment]
I could solve it my removing any directory with the name `jellyfi*` on my filesystem after uninstalling it and using the `jellyfin-bin` aur package.
