### ISSUE TITLE
Error in TheTVDB

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2510]
Is this a standard error?

```
[2020-03-04 04:21:25.788 -05:00] [ERR] [] App: Error in "TheTVDB"
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
``

**Comment by jcvara** [comment]
Confirming this issue and adding a bit more context:

Jellyfin v10.4.3.

Added a new series to a library, metadata wasn't grabbed automatically, so I 'Identified' the series by IMDB ID and selected to change all images. This is the log:

```
[11:24:19] [WRN] HTTP Response 200 to 89.187.178.13. Time (slow): 0:00:25.4922427. http://media.singleboard.live/Items/RemoteSearch/Series

[11:24:31] [INF] Setting provider id's to item 33e0e3e9-c00f-0187-5e7d-70c7fd8c962f-Ah! My Goddess: {"Imdb":"tt0872301"}

[11:24:32] [ERR] Error in TheTVDB
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

[11:24:39] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)

[11:24:49] [ERR] Error in TheTVDB
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

[11:25:06] [ERR] Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:1 EpisodeNumber:24]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)

[11:25:06] [ERR] Failed to retrieve episode images for series null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:1 EpisodeNumber:24]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
```

Note that I left the TheTVDB field empty as I've always done.
