### ISSUE TITLE
Can't open plug-in center

### ISSUE THREAD

**Issue by helloxz** [jellyfin/jellyfin#2531]
**Describe the bug**

I can't open the jellyfin plug-in center with the error:The SSL connection could not be established, see inner exception.
![image](https://user-images.githubusercontent.com/7276531/76137646-6bdacf00-607a-11ea-95d8-9b48104e0422.png)

**System (please complete the following information):**
 - OS: CentOS 7
 - Virtualization: Physical machine
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.4.3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: /Packages?PackageType=UserInstalled
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

```
[2020-03-07 13:33:08.297 +08:00] [ERR] Error processing request
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackagesWithoutRegistrationInfo(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken, Boolean withRegistration, String packageType, Version applicationVersion)
   at MediaBrowser.Api.PackageService.Get(GetPackages request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-07 13:33:08.303 +08:00] [WRN] HTTP Response 500 to "192.168.50.107". Time (slow): 0:00:01.3115719. "http://192.168.50.3:8096/Packages?PackageType=UserInstalled"
```
**Screenshots**

**Additional context**

Before I could open plug-in hub, since last night, plug-in hub could not open, and updating the automatic update plug-in also failed.

**Comment by helloxz** [comment]
Mar  7 14:12:27 zhanmei jellyfin: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by helloxz** [comment]
This is my bag data.
```bash
15:17:19.142423 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [S], seq 863560409, win 64240, options [mss 1460,sackOK,TS val 2201914409 ecr 0,nop,wscale 7], length 0
15:17:19.415911 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [S.], seq 1837498050, ack 863560410, win 65160, options [mss 1452,sackOK,TS val 14431087 ecr 2201914409,nop,wscale 7], length 0
15:17:19.415989 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [.], ack 1, win 502, options [nop,nop,TS val 2201914683 ecr 14431087], length 0
15:17:19.416806 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [P.], seq 1:364, ack 1, win 502, options [nop,nop,TS val 2201914684 ecr 14431087], length 363
15:17:19.691161 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [P.], seq 1:3181, ack 364, win 507, options [nop,nop,TS val 14431363 ecr 2201914684], length 3180
15:17:19.691239 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [.], ack 3181, win 493, options [nop,nop,TS val 2201914958 ecr 14431363], length 0
15:17:19.693185 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [P.], seq 364:490, ack 3181, win 501, options [nop,nop,TS val 2201914960 ecr 14431363], length 126
15:17:19.965109 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [P.], seq 3181:3232, ack 490, win 507, options [nop,nop,TS val 14431637 ecr 2201914960], length 51
15:17:19.965182 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [.], ack 3232, win 501, options [nop,nop,TS val 2201915232 ecr 14431637], length 0
15:17:20.413379 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [F.], seq 490, ack 3232, win 501, options [nop,nop,TS val 2201915680 ecr 14431637], length 0
15:17:20.684911 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [P.], seq 3232:3448, ack 491, win 507, options [nop,nop,TS val 14432357 ecr 2201915680], length 216
15:17:20.684931 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [P.], seq 3448:3479, ack 491, win 507, options [nop,nop,TS val 14432357 ecr 2201915680], length 31
15:17:20.685008 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [R], seq 863560900, win 0, length 0
15:17:20.685038 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [R], seq 863560900, win 0, length 0
15:17:20.685262 IP elb1.jellyfin.org.https > zhanmei.42323: Flags [F.], seq 3479, ack 491, win 507, options [nop,nop,TS val 14432357 ecr 2201915680], length 0
15:17:20.685297 IP zhanmei.42323 > elb1.jellyfin.org.https: Flags [R], seq 863560900, win 0, length 0
```

**Comment by helloxz** [comment]
logs:
```
The SSL connection could not be established, see inner exception. at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) at System.Threading.Tasks.ValueTask`1.get_Result() at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Threading.Tasks.ValueTask`1.get_Result() at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask) at System.Threading.Tasks.ValueTask`1.get_Result() at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod) at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod) at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackagesWithoutRegistrationInfo(CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(Version applicationVersion, Boolean withAutoUpdateEnabled, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by JustAMan** [comment]
cc @joshuaboniface

**Comment by hvbird** [comment]
I got the same problem in my Debian 9 server, the scraper cannot work too.
I think it may be caused by OpenSSL(maybe not): a few days ago I upgrade to OpenSSL 1.1.1g for TLS 1.3.

I don't' know why, after that, every HTTP/HTTPS request failed, so I have to disable SSL check and now it's work again:

jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs

61             if (!_httpClients.TryGetValue(key, out var client))
62             {
63                 var httpClientHandler = new HttpClientHandler();
64                 httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
65
66                 client = new HttpClient(httpClientHandler)
67                 {
68                     BaseAddress = new Uri(url)
69                 };
