### ISSUE TITLE
Easy Pin with LAN Networks option not working

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin#2537]
**Describe the bug**
When setting the LAN network setting the easy pin option does not work.  I have my jellyfin server at 192.168.10.30 and my laptop is currently on 192.168.1.0/24.  Easy pin is denied with error:

```
[2020-03-08 03:04:36.695 -04:00] [ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-03-08 03:04:36.697 -04:00] [INF] Authentication request for "TestUser" "has been denied".
[2020-03-08 03:04:36.769 -04:00] [ERR] [192.168.1.139] Invalid user or password entered.
```

**System (please complete the following information):**
 - OS: Ubuntu 19.10
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Firefox 73.0.1
 - Jellyfin Version: 10.4.0
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: Host
 - Storage: NFS

**To Reproduce**
1.  Set up LAN Networking under Dashboard > Networking > LAN Networks
2.  Enter an IP address and/or IP/subnet.  I used `192.168.1.0/24`
3.  Set up easy pin for user and enable easy pin on local network
4.  Attempt sign-in via private window using pin.

**Expected behavior**
User on configured LAN network is authenticated using their easy pin.

**Logs**
```
[2020-03-08 03:04:36.695 -04:00] [ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-03-08 03:04:36.697 -04:00] [INF] Authentication request for "TestUser" "has been denied".
[2020-03-08 03:04:36.769 -04:00] [ERR] [192.168.1.139] Invalid user or password entered.
```

**Additional context**
Authenticating using the user's normal username and password works fine.  It's just the easy pin that doesn't work when the client is on a different subnet.

**Comment by cvium** [comment]
We don't support old versions. Upgrade to 10.4.3.

**Comment by uchagani** [comment]
@cvium i used the latest from the Ubuntu Eoan repo (installed a couple days ago). Could it be the repo hasn't been updated?

**Comment by JustAMan** [comment]
paging @joshuaboniface

**Comment by dkanada** [comment]
This should have been fixed shortly after this comment.
