### ISSUE TITLE
Can not log into Jellyfin anymore

### ISSUE THREAD

**Issue by moelrobi** [jellyfin/jellyfin#2539]
When i try to log into Jellyfin Docker (v.10.4.3) i am getting this error:

```jellyfin_1  | System.ArgumentNullException: Value cannot be null.
jellyfin_1  | Parameter name: resolvedUser
jellyfin_1  |    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
jellyfin_1  |    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
jellyfin_1  |    at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
jellyfin_1  |    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
jellyfin_1  |    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
jellyfin_1  |    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
jellyfin_1  |    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
jellyfin_1  |    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
jellyfin_1  |    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
jellyfin_1  | [18:22:34] [ERR] Error creating http port map
jellyfin_1  | MediaBrowser.Model.Net.HttpException: Internal Server Error
jellyfin_1  |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin_1  |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin_1  |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin_1  |    at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
jellyfin_1  |    at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)```

**Comment by moelrobi** [comment]
Bug is fixed after Update to 10.5.0 :)
