### ISSUE TITLE
SRT subtitles not working

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin#254]
As a non native english speaker we enjoy the original sound with subtitles based on the SRT format.

Currently jellyfin is not able to display the subtitles. When enabling a subtitle in the web app, the network analyzer shows a 500 http error code immediately.

I noticed this on the earlier versions too, but I though it might be caused by the migrated emby 3.5.3 database I used. Retried this with a new jellyfin database and current docker image.

jellyfin log:
```
[...]
2018-12-21 10:28:14.803 Info HttpServer: HTTP GET http://example.com:8096/emby/Videos/43d37ad42dcebfc89a5fbde518b84277/43d37ad42dcebfc89a5fbde518b84277/Subtitles/3/0/Stream.vtt. Host=example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) 
2018-12-21 10:28:14.817 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.9.0.8
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 2
	Program data path: /config
	Application directory: /jellyfin
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131
	   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	System.NullReferenceException
	   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131
	   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
2018-12-21 10:28:14.817 Info HttpServer: HTTP Response 500 to 10.79.64.42. Time: 14ms. http://example.com:8096/emby/Videos/43d37ad42dcebfc89a5fbde518b84277/43d37ad42dcebfc89a5fbde518b84277/Subtitles/3/0/Stream.vtt 
[...]
```

**Comment by rtg27** [comment]
Same here, SRT not getting displayed. Installed from AUR in Manjaro

**Comment by balasankarc** [comment]
This is the log that server.txt has, related to subtitles
```
        *** Error Report ***                                                                                                                                                                                                                                                               
        Version: 3.5.2.0                                                                                                                                                                                                                                                                   
        Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh                                                                                                                                                          
        Operating system: Unix 4.9.0.8                                                                                                                                                                                                                                                     
        64-Bit OS: True                                                                                                                                                                                                                                                                    
        64-Bit Process: True                                                                                                                                                                                                                                                               
        User Interactive: True                                                                                                                                                                                                                                                             
        Processor count: 2                                                                                                                                                                                                                                                                 
        Program data path: /var/lib/jellyfin                                                                                                                                                                                                                                               
        Application directory: /usr/lib/jellyfin/bin                                                                                                                                                                                                                                       
        System.NullReferenceException: Object reference not set to an instance of an object.                                                                                                                                                                                               
           at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOrigi
nalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131                                                                                                                                                              
           at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228                                                                                                                                          
           at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114                                                                                                                       
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandle
r.cs:line 96                                                                                                                                                                                                                                                                               
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660              
        System.NullReferenceException                                                                                                                                                                                                                                                      
           at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOrigi
nalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131                                                                                                                                                              
           at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228                                                                                                                                          
           at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114                                                                                                                       
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandle
r.cs:line 96                                                                                                                                                                                                                                                                               
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660              
                                           
```

**Comment by balasankarc** [comment]
@joshuaboniface Not sure how priorities are handled by Jellyfin devs, but I would like to recommend this to be a priority item if that's ok. :)

**Comment by JustAMan** [comment]
Vote for first entry in this issue with "thumbs up" to express your opinion. We'll be checking this stuff I think.

**Comment by sauerj** [comment]
Just saw this in the web console:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data: plugin.js:302:29
fetchSubtitles/</xhr.onload
```

This appears immediately when choosing a subtitle in a running stream.

**Comment by sauerj** [comment]
I am trying to track down the commit which introduced this bug by doing a bisect.

I am not sure which commit is a good one, because the last commit from the Emby Repo is 50b88c5ac0e5a633d2d9aa01b446b252a6b0cb10 directly followed by 2bd04e3c84733bcf0a4218907bff03fdd755c025 which seems to squash one year of work into one commit.

Building the docker image from 50b88c5ac0e5a633d2d9aa01b446b252a6b0cb10 fails due to missing files in the Emby.Releases repo.

I then tried building 2bd04e3c84733bcf0a4218907bff03fdd755c025 with current Dockerfile but it fails because of missing project files:
```
MediaBrowser.Model
MediaBrowser.Common
MediaBrowser.Controller
```

I tried copying these folders from the current master commit, but then it fails with `No overload for method 'ToArray' takes 1 arguments` and other incompatibilities.

@JustAMan can you hint me which versions of MediaBrowser.Model, Common and Controller are needed for building 2bd04e3c84733bcf0a4218907bff03fdd755c025?

**Comment by balasankarc** [comment]
Can someone else re-check if this is fixed with 10.0.0? I am not seeing subtitles. :thinking:

**Comment by sauerj** [comment]
> Can someone else re-check if this is fixed with 10.0.0? I am not seeing subtitles. thinking

I can confirm this, same for me.

I do not see a 500 error but 400 now:

```
[2019-01-07 06:37:54.565 +00:00] [ERR] Error processing request
System.ArgumentException: 'windows1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at Emby.Server.Implementations.TextEncoding.TextEncoding.GetEncodingFromCharset(String charset) in /repo/Emby.Server.Implementations/TextEncoding/TextEncoding.cs:line 179
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, String language, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 211
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 194
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 149
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 229
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 654
[2019-01-07 06:37:54.568 +00:00] [INF] HTTP Response 400 to "10.79.64.25". Time: "69""ms". "http://jellyfin.example.com:8096/emby/Videos/c3dd5bfb-3c3b-d4e1-0724-4bc57f5eeada/c3dd5bfb3c3bd4e107244bc57f5eeada/Subtitles/3/0/Stream.vtt" ""
```

**Comment by balasankarc** [comment]
@joshuaboniface Could you reopen the issue, please? :)

**Comment by cvium** [comment]
Regression? https://emby.media/community/index.php?/topic/52098-systemargumentexception-windows1252-is-not-a-supported-encoding-name-is-thrown-when-playing-with-hungarian-subtitles/

**Comment by balasankarc** [comment]
In Linux, I didn't see any errors in server.txt or jellyfin.txt files (I will check again and confirm later). But subtitles are not shown.

**Comment by pw-h** [comment]
srt subs showing fine now in ver 10.0.0.0 ! (docker container). Sample srt file included.
[Bron.S03E05.SWEDISH.720p.BluRay.x264-GNiSTOR.zip](https://github.com/jellyfin/jellyfin/files/2733770/Bron.S03E05.SWEDISH.720p.BluRay.x264-GNiSTOR.zip)

**Comment by balasankarc** [comment]
I stand corrected regarding "I didn't see any errors in Linux". I looked again and I am seeing similar errors to @sauerj 

```
System.ArgumentException: 'windows1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.                                                                                                  
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at Emby.Server.Implementations.TextEncoding.TextEncoding.GetEncodingFromCharset(String charset) in /repo/Emby.Server.Implementations/TextEncoding/TextEncoding.cs:line 179                                                                                                             
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, String language, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 211                
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 194                                      
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 149
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 229
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114                                                                                                                              
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 654                     
[2019-01-08 00:52:47.489 +05:30] [ERR] Error running postscan task
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Logging.ILogger' from assembly 'MediaBrowser.Model, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.                                                                                                            
   at AutoBoxSets.Plugin.CreateAllBoxSets(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AutoBoxSets.Plugin.CreateAllBoxSets(IProgress`1 progress, CancellationToken cancellationToken)
   at AutoBoxSets.Tasks.CreateBoxSetsTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 1141  
```

**Comment by sauerj** [comment]
> srt subs showing fine now in ver 10.0.0.0 ! (docker container). Sample srt file included.
> [Bron.S03E05.SWEDISH.720p.BluRay.x264-GNiSTOR.zip](https://github.com/jellyfin/jellyfin/files/2733770/Bron.S03E05.SWEDISH.720p.BluRay.x264-GNiSTOR.zip)

@pw-h I am running jellyfin 10.0.0.0 in docker. Imported your sample subtitle to one of my movies. I can not see them, but it seems with your subtitle the "windows1252" error does not appear.
It is a quite strange behavior.

**Comment by alokhan** [comment]
I have got the same error message when trying to play a movie with subtitles. 
On Unbuntu 18.10 with Jellyfin 10.0.2.0

`[2019-01-18 22:35:31.244 +01:00] [ERR] Error processing request
System.ArgumentException: 'windows1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProv
ider method.
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at Emby.Server.Implementations.TextEncoding.TextEncoding.GetEncodingFromCharset(String charset) in /repo/Emby.Server.Implementations/TextEncoding/TextEncoding.cs:line 179
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, String language, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 211
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 194
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 149
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 229
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/Ser`

**Comment by joshuaboniface** [comment]
Is anyone from this thread able to assist in testing https://github.com/jellyfin/jellyfin/pull/598 to see if it helps?

**Comment by alokhan** [comment]
I didn't compile the project yet but I could test it, if I find some time to setup everything.

**Comment by sauerj** [comment]
> Is anyone from this thread able to assist in testing #598 to see if it helps?

Merged #598 on latest `dev` and build the docker image. The `windows1252` error described above is no longer there, no HTTP errors.

Unfortunately subtitles are still not appearing...

**Comment by cvium** [comment]
@sauerj If you're feeling adventurous, the subtitle issue has been fixed in #629

**Comment by sauerj** [comment]
@cvium quick tried both prs and it looks quite good. Sadly I did not had the time to do more testing. Hopefully I will have the time tomorrow.

**Comment by alokhan** [comment]
Ok compiled and tested, seems to work as well :) (but fetching subtitles from open subtitles does not work yet)
