### ISSUE TITLE
User creation and saving profiles broken for authentication providers

### ISSUE THREAD

**Issue by hukoeth** [jellyfin/jellyfin#2540]
I've just installed Jellyfin nightly on my Raspi 4 (armhf, debian package) and found the following issues:

- When trying to create a new user (setting is enabled in LDAP), error "Login failed" is displayed
- When saving profiles (in admin dashboard as well as logged in as the user) I also get "Login Failed". Changes are still saved

If you need more information please let me know

**Comment by joshuaboniface** [comment]
Logs when this happens:

```
Mar 08 15:19:50 jf1.i.net jellyfin[2095]: [15:19:50] [ERR] Error processing request: [10.x.0.y] Invalid user or password entered.
```

I would expect this to check the auth provider and that create the user, but instead it just dies.

As a test, I'm reverting #2363 to see if this improves things.

**Comment by joshuaboniface** [comment]
It's not #2363 but something else. Needs further investigation CC @Bond-009 @dkanada.

**Comment by joshuaboniface** [comment]
For now this isn't really a blocker for 10.5.0 - @hukoeth as a workaround, you could create the user then manually set its authentication provider to the LDAP one in order to auth there.

**Comment by dkanada** [comment]
Hmm I assumed it would be my pull request.

**Comment by sauerj** [comment]
> For now this isn't really a blocker for 10.5.0 - @hukoeth as a workaround, you could create the user then manually set its authentication provider to the LDAP one in order to auth there.

I tried this but the login fails with this error:

```
[2020-03-13 14:44:04.725 +00:00] [ERR] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by joshuaboniface** [comment]
Looks like the issue was introduced in #2146 - trying to find the ideal solution.

**Comment by Mflixit** [comment]
Does anyone have a working Jellyfin + LDAP setup working? Which version of Jellyfin and which version of LDAP plug work together? Thanks. Are there any updates on this issue? Where can I read more about it?
