### ISSUE TITLE
Local external subtitle files with STRM videos don't work

### ISSUE THREAD

**Issue by sachk** [jellyfin/jellyfin#2543]
**Describe the bug**
Playing locally stored external subtitles along with a STRM video causes Stream.js to return a 400, and an error (in logs) as the response.

In my case, the file structure looks like this

```
user@vps:/drive/files/mov/MOVIE_NAME (YEAR)$ ls
MOVIE_NAME.YEAR.BluRay.1080p.x264-RELEASEGROUP.mp4.en.srt
MOVIE_NAME.YEAR.BluRay.1080p.x264-RELEASEGROUP.mp4.strm
```

The video plays just fine, but without any subtitles.

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Chromium 81
 - Jellyfin Version: 10.5.0
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Bridge
 - Storage: STRM files, local subtitles

**To Reproduce**
1. Put a locally stored external subtitle in the same folder as an STRM file
2. Playback the STRM file with the external subtitle selected

**Expected behavior**
The subtitles are read and display properly

**Logs**
```
[2020-03-09 14:20:13.255 +11:00] [ERR] Error processing request
System.ArgumentException: Only 'http' and 'https' schemes are allowed. (Parameter 'value')
   at System.Net.Http.HttpClient.CheckBaseAddress(Uri baseAddress, String parameterName)
   at System.Net.Http.HttpClient.set_BaseAddress(Uri value)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.GetHttpClient(String url)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.Get(HttpRequestOptions options)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
**Additional context**
I assume this is to do with Jellyfin assuming the external subtitles are also an STRM file. 

This usage functions fine on Emby. However, emby and jellyfin both don't recognise srt filenames formatted by Bazarr when used with STRM files. .mp4 or whatever the file extension prior to .strm in the STRM file name needs to be included before .en in the subtitle file's name for detection to work. There are several other bugs with STRM files, such as irratic chromecast functionality and skipping around the video not working properly on Android TV. I'll retest some things and make some more reports if anyone's actually interested in fixing these bugs, since it is a pretty niche usecase.

**Comment by Artiume** [comment]
So does jellyfin have native support for strm files or are you using kodi? I've read about them, but never tried them out.

Looking over your details, can you try Host mode for your docker network? 

Another detail I think you could try is going to network settings and setting  secure mode to Disabled, this requires a restart of the service. From the context of the logs, I don't think this is the issue but I've seen issues with Secure by Reverse Proxy and chromecasting.

Could the missing subtitles be due to this? 
https://github.com/jellyfin/jellyfin/issues/2507 

`skipping around the video not working properly on Android TV `
Could this be related to 
https://github.com/jellyfin/jellyfin-androidtv/issues/277
There's a couple playback tickets if you want to check through them and see if there's a commonality.

**Comment by sachk** [comment]
> So does jellyfin have native support for strm files or are you using kodi? I've read about them, but never tried them out.
> 
> Looking over your details, can you try Host mode for your docker network?
> 
> Another detail I think you could try is going to network settings and setting secure mode to Disabled, this requires a restart of the service. From the context of the logs, I don't think this is the issue but I've seen issues with Secure by Reverse Proxy and chromecasting.
> 
> Could the missing subtitles be due to this?
> #2507
> 
> `skipping around the video not working properly on Android TV `
> Could this be related to
> [jellyfin/jellyfin-androidtv#277](https://github.com/jellyfin/jellyfin-androidtv/issues/277)
> There's a couple playback tickets if you want to check through them and see if there's a commonality.

Jellyfin has native STRM file support, as does Emby. This feature has been in Emby for ages, and was brought over from there. I'm not using Kodi. This isn't a network issue, it's an internal issue with how Jellyfin handles STRM files.

The issue isn't with just playing STRM files, it's with playing external, locally stored subtitles along with STRM files and it also happens on 10.4.3. I'm 99% sure that there's a bug within one of the MediaEncoding classes that treats the locally stored subtitles as remote STRM files when the main video file is an STRM. The AndroidTV issue happens with faststart muxed MP4s not MKVs, and it doesn't stutter or stop playing normally, but skipping forward or backwards causes it to exit after 10s or so.

I have Emby running on the same machine configured identically and none of these problems exist.

**Comment by sachk** [comment]
I can confirm this still happens. I'm pretty much 100% sure the issue is that when you play an STRM file in Jellyfin it also assumes any external files are STRM files as well.

**Comment by Artiume** [comment]
Can you bring up the browser console and see if any errors appear when you try and enable subtitles?
