### ISSUE TITLE
(iPad)iOS safari not loading video

### ISSUE THREAD

**Issue by Smdytb1** [jellyfin/jellyfin#2546]
**Describe the bug**

iOS safari is unable to load the video under any circumstances, I try direct and it fails. 720p and fails. 10.4.3 it was still working. Compatibility got shot for safari 
**System (please complete the following information):**
 - OS: IPad IOS 10.3.3
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: IOS 
 - Browser: IPad Safari
 - Jellyfin Version: 10.5.0
 - Playback: All
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: /
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1. Go on safari for iOS 
2. Click on any video to play
3. Wait for the play icon to get a line through
4. Video doesn't load

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by Motophan** [comment]
I am also having this bug, is there a mechanism for me to submit sanitized logs, or unredacted logs privately?

**Comment by Bond-009** [comment]
@Motophan dm a dev on matrix

**Comment by ViXXoR** [comment]
I'm experiencing the same issue, running latest Jellyfin (10.5.0) and latest iOS app (iPhone X).

I noticed that the dashboard says the video is being played Direct. However, when I check the log directory, I see a large number of ffmpeg-transcode logs appear:
![2020-03-10 13_57_46-Window](https://user-images.githubusercontent.com/151035/76344327-c329ab00-62d7-11ea-9bd1-d8b5118c261b.png)

The contents of one of these files looks like this:
```
http://10.10.10.28/videos/68ac9bad-85b2-ca21-a9f6-8a99b310e6b7/hls1/main/332.ts?DeviceId=TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxM18zIGxpa2UgTWFjIE9TIFgpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgQ3JpT1MvODAuMC4zOTg3Ljk1IE1vYmlsZS8xNUUxNDggU2FmYXJpLzYwNC4xfDE1ODM3OTA3ODQ3NTI1&MediaSourceId=68ac9bad85b2ca21a9f68a99b310e6b7&VideoCodec=h264&AudioCodec=ac3,eac3,mp3,aac&AudioStreamIndex=1&VideoBitrate=687856&AudioBitrate=112144&PlaySessionId=4a9bf1da66f743b18a6aeba832ccb1d0&api_key=366a1f2b112a4e68a3dfa191217c2a54&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=ce3722d96c874e24f8b8aee28cb3d3f1&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerBitrateExceedsLimit

{"Protocol":"File","Id":"68ac9bad85b2ca21a9f68a99b310e6b7","Path":"/media/TV/redacted.mp4","Type":"Default","Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":179581824,"Name":"redacted","IsRemote":false,"ETag":"ce3722d96c874e24f8b8aee28cb3d3f1","RunTimeTicks":11925233664,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"und","TimeBase":"1/24000","CodecTimeBase":"1001/48000","VideoRange":"SDR","DisplayTitle":"480P H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":1088490,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":404,"Width":720,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":31},{"Codec":"aac","CodecTag":"mp4a","Language":"und","TimeBase":"1/48000","CodecTimeBase":"1/48000","DisplayTitle":"Und AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":112144,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":1204718,"RequiredHttpHeaders":{}}

 -ss 00:16:36.000 -noaccurate_seek -f mov,mp4,m4a,3gp,3g2,mj2 -i file:"/media/TV/redacted.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 687856 -bufsize 1375712 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,996+n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,640)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 ac3 -ac 2 -ab 112144  -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 332 -hls_segment_filename "/config/transcodes/672172e16d96c45b5f46ab40c4faaef9%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/672172e16d96c45b5f46ab40c4faaef9.m3u8"
```

Here's a sanitized log, everything before line 1658 may be relevant:
[log_20200309.log](https://github.com/jellyfin/jellyfin/files/4314057/log_20200309.log)


As a guess, I'm thinking it has to do with these parts of the log:
```
[2020-03-09 17:51:13.414 -04:00] [INF] [10] App: User policy for "SomeUser". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-03-09 17:51:13.462 -04:00] [INF] [10] App: Bitrate exceeds DirectStream limit: media bitrate: 1038964, max bitrate: 800000
[2020-03-09 17:51:13.463 -04:00] [INF] [10] App: Profile: "Unknown Profile", Path: "/media/redacted
[2020-03-09 17:51:13.493 -04:00] [INF] [10] App: Profile: "Unknown Profile", No direct play profiles found for Path: "/media/redacted
[2020-03-09 17:51:13.593 -04:00] [INF] [10] App: Bitrate exceeds DirectStream limit: media bitrate: 1038964, max bitrate: 800000
[2020-03-09 17:51:13.593 -04:00] [INF] [10] App: Profile: "Unknown Profile", Path: "/media/redacted
[2020-03-09 17:51:13.594 -04:00] [INF] [10] App: Profile: "Unknown Profile", No direct play profiles found for Path: "/media/redacted
[2020-03-09 17:51:13.594 -04:00] [INF] [10] App: Bitrate exceeds DirectStream limit: media bitrate: 1038964, max bitrate: 800000
[2020-03-09 17:51:13.594 -04:00] [INF] [10] App: Profile: "Unknown Profile", Path: "/media/redacted
[2020-03-09 17:51:13.595 -04:00] [INF] [10] App: Profile: "Unknown Profile", No direct play profiles found for Path: "/media/redacted
[2020-03-09 17:51:13.672 -04:00] [WRN] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "10.10.10.185". Time (slow): 0:00:00.5481365. "http://10.10.10.28/Items/6976fced0f01c384c7fbe8d24e2b479b/PlaybackInfo?UserId=79173540f2e04b9c8c9075b77ad3b8db&StartTimeTicks=8448940461&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=800000"
[2020-03-09 17:51:14.757 -04:00] [INF] [33] App: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2020-03-09 17:51:14.818 -04:00] [INF] [33] App:  -f matroska,webm -i file:"/media/redacted
[2020-03-09 17:51:14.822 -04:00] [ERR] [33] App: Error starting ffmpeg
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at MediaBrowser.Api.Playback.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, String workingDirectory)
[2020-03-09 17:51:14.837 -04:00] [ERR] [33] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at MediaBrowser.Api.Playback.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at MediaBrowser.Api.Playback.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

You'll see the `Error starting ffmpeg` spammed in there quite a bit for each attempt to play.
I also see there is no direct play profile, yet those files play perfectly fine on any other device (android TV, Android phone, web player).

If I can offer anything else to help, please let me know.

**Comment by Bond-009** [comment]
@ViXXoR jellyfin can't find your ffmpeg `MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: NotFound: ""`

**Comment by ViXXoR** [comment]
I'm running jellyfin in docker, on an RPi4. I don't have anything special setup for ffmpeg, as I didn't think I'd need to be transcoding anything. Why would video need to be transcoded for playback on iOS? I assume the RPi4 doesn't have the horsepower to do real-time transcoding anyway.

**Comment by ViXXoR** [comment]
Just as a reference for anyone else who ends up here, I went and browsed around in the container and found where ffmpeg was. I added it to the "FFMPEG Path" in "Playback" settings and everything appears to work now.

The path was "/usr/lib/jellyfin-ffmpeg/ffmpeg".

Thanks @Bond-009 for pointing that out.

**Comment by GuildDarts** [comment]
i got the same issue, using Safari i don't get any errors but using chrome i get this
![image](https://user-images.githubusercontent.com/12391692/77215871-e1cd4480-6b16-11ea-8177-7536d4131c82.png)

**Comment by JustAMan** [comment]
@GuildDarts this might be a different issue, why don't you create a new one?
@ViXXoR seems the original issue was your install somehow corrupted in a sense that it didn't use ffmpeg. I don't think this is a bug in JF, if you agree could you please close this issue?

**Comment by ViXXoR** [comment]
To me it sounds like @GuildDarts issues might be related to #2424, but that's just my guess.

Now, while I may not agree that my install somehow corrupted, it seems that even basic playback doesn't work on many devices without ffmpeg. Would it not be worth investigating possibly verifying the ffmpeg path, and falling back to the default (in docker installs anyways) path if that check fails?

**Comment by JustAMan** [comment]
There is already a check for ffmpeg. It might be worth not starting if ffmpeg is not found, though...

**Comment by ajlowndes** [comment]
Every time this happens on my ipad, a new log file shows up, like the one attached titled "ffmpeg-directstream..."
[ffmpeg-directstream-51cdc070-c7de-4b8b-9e97-de343e04b57e.txt.txt](https://github.com/jellyfin/jellyfin/files/4928402/ffmpeg-directstream-51cdc070-c7de-4b8b-9e97-de343e04b57e.txt.txt)

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-web/pull/1893
