### ISSUE TITLE
LiveTV with HDHR tuner not working since upgrading to 10.5.0

### ISSUE THREAD

**Issue by casasfernando** [jellyfin/jellyfin#2568]
Since upgrading to Jellyfin 10.5.0 LiveTV playback is not working anymore.
ffmpeg is logging the following error:
```
[tls @ 0x55dbc64cfd00] An unexpected TLS packet was received.
```
Streaming never starts (black screen with the spinning colored wheel) but the stream from the tuner remains open and Jellyfin needs to be restarted in order to release the tuner.
I suspect that this problem may be related to ffmpeg using https protocol to connect to Jellyfins http port (8096) instead of https port (8920)?

 - OS: Debian 10 (Buster)
 - Virtualization: KVM
 - Clients: Browser, Android, Fire Stick, etc.
 - Browser: Firefox 73.0.1
 - Jellyfin Version: 10.5.0
 - Playback: Transcode]
 - Reverse Proxy: none
 - Base URL: none

**To Reproduce**

1. Go to LiveTV
2. Select any channel
3. Start playback

**Expected behavior**
LiveTV playback works.

**Logs**

Jellyfin log:

```
[2020-03-10 21:44:04.485 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 192000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a,m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma,webm", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "VP8", Type: Video }, DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "VP9", Type: Video }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2020-03-10 21:44:04.615 +01:00] [INF] User policy for "Fernando". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-03-10 21:44:04.629 +01:00] [INF] Profile: "Unknown Profile", Path: "http://192.168.7.14", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-10 21:44:04.638 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "http://192.168.7.14"
[2020-03-10 21:44:04.688 +01:00] [INF] Opening channel stream from "Emby", external channel Id: "hdhr_5056"
[2020-03-10 21:44:04.691 +01:00] [INF] Streaming Channel hdhr_5056
[2020-03-10 21:44:04.698 +01:00] [INF] GetChannelStream: channel id: "hdhr_5056". stream id: "native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c" profile: "native"
[2020-03-10 21:44:04.703 +01:00] [INF] Opening SharedHttpStream Live stream from "http://192.168.7.14:5004/auto/v5056"
[2020-03-10 21:44:05.208 +01:00] [INF] Beginning "SharedHttpStream" stream to "/var/lib/jellyfin/transcodes/612ac597c4e54c108cf63b07c67c16ff.ts"
[2020-03-10 21:44:05.229 +01:00] [INF] Live stream opened after 529.689ms
[2020-03-10 21:44:05.230 +01:00] [INF] Returning mediasource streamId "native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c", mediaSource.Id "native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c", mediaSource.LiveStreamId null
[2020-03-10 21:44:05.242 +01:00] [INF] Waiting 3000ms before probing the live stream
[2020-03-10 21:44:08.255 +01:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 3000000 -i \"https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2020-03-10 21:44:09.037 +01:00] [ERR] Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LiveStreamHelper.AddMediaInfoWithProbe(MediaSourceInfo mediaSource, Boolean isAudio, String cacheKey, Boolean addProbeDelay, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
[2020-03-10 21:44:09.073 +01:00] [INF] Live stream opened: {"Protocol":"Http","Id":"native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c","Path":"https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts","Type":"Default","Container":"ts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c","BufferMs":0,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mpeg2video","VideoRange":"SDR","DisplayTitle":"MPEG2VIDEO","IsInterlaced":true,"BitRate":2000000,"IsDefault":false,"IsForced":false,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"Codec":"MPEG","DisplayTitle":"MPEG","IsInterlaced":false,"BitRate":192000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"MediaAttachments":[],"Formats":[],"Bitrate":2192000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}
[2020-03-10 21:44:09.112 +01:00] [INF] User policy for "Fernando". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-03-10 21:44:09.112 +01:00] [INF] Profile: "Unknown Profile", Path: "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-10 21:44:09.113 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts"
[2020-03-10 21:44:09.113 +01:00] [INF] Profile: "Unknown Profile", Path: "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-10 21:44:09.113 +01:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts"
[2020-03-10 21:44:09.119 +01:00] [WRN] HTTP Response 200 to "192.168.7.44". Time (slow): 0:00:04.6676933. "https://jellyfin01:8920/Items/f619dc6d9410bc500312bd9194c4217a/PlaybackInfo?UserId=7859effa38cd4a1c93a4b40a041a56a4&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
[2020-03-10 21:44:09.587 +01:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -fflags +igndts -f mpegts -i "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 5000000 -bufsize 10000000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "yadif=0:-1:0,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync cfr -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/30945088c8bdb14e846a4bdac324e7f0/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcodes/30945088c8bdb14e846a4bdac324e7f0.m3u8" -y "/var/lib/jellyfin/transcodes/30945088c8bdb14e846a4bdac324e7f0%d.ts"
[2020-03-10 21:44:09.877 +01:00] [ERR] FFMpeg exited with code 1
```

FFMPEG log:

```
https://jellyfin01:8920/videos/f619dc6d-9410-bc50-0312-bd9194c4217a/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2OjY0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNjQuMHwxNTQ3NTk3MzUzODkx&MediaSourceId=native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=-1&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=53303c7f3fc74a7d9107d4dfc8a89249&api_key=fe1b2873100a430ba84834eca94d10f7&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

{"Protocol":"Http","Id":"native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c","Path":"https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts","Type":"Default","Container":"ts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_8b2bbb230b23b64fea7cba9a146769de_d6aa108e8cce3615994c44f351de336c","BufferMs":0,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mpeg2video","VideoRange":"SDR","DisplayTitle":"MPEG2VIDEO","IsInterlaced":true,"BitRate":2000000,"IsDefault":false,"IsForced":false,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"Codec":"MPEG","DisplayTitle":"MPEG","IsInterlaced":false,"BitRate":192000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"MediaAttachments":[],"Formats":[],"Bitrate":2192000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -fflags +igndts -f mpegts -i "https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 5000000 -bufsize 10000000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "yadif=0:-1:0,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync cfr -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/30945088c8bdb14e846a4bdac324e7f0/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcodes/30945088c8bdb14e846a4bdac324e7f0.m3u8" -y "/var/lib/jellyfin/transcodes/30945088c8bdb14e846a4bdac324e7f0%d.ts"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec --enable-amf
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tls @ 0x55dbc64cfd00] An unexpected TLS packet was received.
https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts: Input/output error
```

**Comment by jrbski** [comment]
I saw the same issue. One thing I did notice is that my HDhomerun setting defaulted to hardware transcoding (which I don't think my HDHR prime suports). When I disabled it, I still see the 'No;direct play profile' in the logs, and I see the same result. I rolled back to 10.4.3

**Comment by Artiume** [comment]
What is secure connection mode set to in your network settings?

**Comment by casasfernando** [comment]
It's set to: "Preferred, but not required"

**Comment by Artiume** [comment]
Change it to Disabled. Your current setting is causing it most likely 

https://github.com/jellyfin/jellyfin/issues/2259

**Comment by jrbski** [comment]
I just tested the docker image, and it is working fine,so I am only seeing the issue with a direct install on lubuntu.

**Comment by Artiume** [comment]
Can I get your sanitized sys logs and ffmpeg logs?

**Comment by casasfernando** [comment]
Changing it to "Disabled" indeed fixed the LiveTV issue but created another problem for me.
With this configuration, Jellyfin will **only** listen on port 8096, so no https connection can be done to the server, so I can't leave like that.

I changed the configuration again and set it as "Required for all remote connections".
Now Jellyfin is listening for both http (8096) and https (8920) connections but, LiveTV is broken again with the same error I initially reported and I'm sorry to insist but I think the problem is that when Jellyfin is starting ffmpeg to do the transcoding is passing it the wrong protocol/port combination.
As you can see in the logs Jellyfin is telling ffmpeg to connect to port 8096 which is the http port, but using https instead so when ffmpeg try to initiate the TLS connection it fails (as expected since port 8096 is not for TLS connections).

This was working fine in 10.4.3.

**Comment by Artiume** [comment]
Are you using a reverse proxy or using SSL?

**Comment by casasfernando** [comment]
I'm connecting directly to the server using SSL, no proxy in the middle.

**Comment by ManfredRichthofen** [comment]
do you a have a simultaneous stream limit set i just noticed my live tv doesnt work unless its set to 0

**Comment by jrbski** [comment]
I agree that changing secure connection mode corrects the issue. I am using a reverse proxy (nginx), but I had an ssl cert that I had been using prior to setting up the reverse proxy.

A 'direct' http and/or https though the proxy are working for me now... thanks Artiume!

**Comment by casasfernando** [comment]
I'm sorry guys but changing the connection mode to 'Disabled' is not a valid workaround for this bug in my case. I want to keep https enabled in my network.

**Comment by Artiume** [comment]
@ManfredRichthofen I do use the set limit, I don't have any issues with it, if you can't figure out what's up, open up a new ticket :)

@casasfernando see my linked issue. The RP setting tries to enforce local https instead of http. This means you can't do SSL + hdhr at the moment. You have to use a reverse proxy if you want to use the server remotely securely

**Comment by casasfernando** [comment]
@Artiume I read the linked issue but I honestly believe is a different issue.
As far as I understand ffmpeg is a client to Jellyfin and Jellyfin is a client to HDHR. Please correct me if I’m wrong.

The secure connection mode only affects connections between Jellyfin clients (ie: browser or in this case ffmpeg?) and the Jellyfin server. It has no effect on the connection from Jellyfin to HDHR. In that case the protocol is set in the Tuner config in Jellyfin. So in my case the connection from Jellyfin to HDHR will always be http. Is this correct?

What I still don’t understand is why, when invoking ffmpeg, Jellyfin is passing the wrong protocol+port combination to it when SSL is required? If Jellyfin is telling ffmpeg to use http (secure connection mode = disabled) it must also tell it to use port 8096 (and this is the case as I was able to confirm) but the problem is that when secure connection mode is set prefer or require a secure connection Jellyfin is correctly telling ffmpeg to use https but **incorrectly** telling it to use port 8096. This is the bug. In this scenario Jellyfin needs to tell ffmpeg to use https on port 8920.

Another indication that this bug maybe in Jellyfins ffmpeg invocation code is that any other content (music, tv shows, movies) is streaming correctly to the clients without changing the secure connection mode and using https.

Sorry for the long comment but I felt that either I was not explaining myself correctly or I’m missing something here.

Thanks

**Comment by Artiume** [comment]
`As far as I understand ffmpeg is a client to Jellyfin and Jellyfin is a client to HDHR`

We wrap commands around ffmpeg to build the proper stream. Part of building the stream, there's html headers attached to the url chain, this can be stuff like audio or video is not supported, client ID, api key, and so on. Once that's ready, the network logic is checked and specifies a port. The reason that ffmpeg can do https with music, movies and other media is because ffmpeg is inside that special wrapper. With the hdhr, it's not internal. I believe you'd have to setup ssl on the hdhr and load these certs into JF to make this work correctly. 

The network settings are a lot more primitive than you'd think. Just toggle these values to directly configure your network. It's just setting secure mode or not and specifying the port. 
Here they are 
https://github.com/jellyfin/jellyfin/blob/e0381c88544e214d9c4ed328b550d938818a7357/MediaBrowser.Model/Configuration/ServerConfiguration.cs#L247

The hdhr is on your internal network so http should be fine, maybe I'm confused by your network?

The preferred setting is based on the old Emby proxy. You could use the proxy with https and if it failed, you would fallback to http. It currently doesn't do anything except have bad logic in JF afaik

**Comment by PrplHaz4** [comment]
Pretty sure this is a bug. We saw this behavior with DLNA too, which I thought led to removing “preferred” as the secure connection mode default. 

Jellyfin is telling FFmpeg that the file is here, but https and port 8096 should never be together. Protocol and port should be both secure or both insecure not a mixture. 

`https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts`

**Comment by casasfernando** [comment]
@Artiume: both Jellyfin and hdhr are in my local network and yet I use https for every service that supports it in my local network. Unfortunately afaik hdhr doesn’t support https.

Having said that I totally agree with @PrplHaz4 and his comment. Protocol and port should be both secure or both insecure not a mixture.

For the time being I will rollback to 10.4.3 which was working as expected and when I find some time I will take a look at the code to try to pinpoint the bug.

**Comment by jrbski** [comment]
Based on the discussion in 
#827

Better https support: is in the roadmap, since the inherited Emby support wasn't that great. As a result, I set-up an nginx reverse proxy with Let's Encrypt. nginx is pretty light. I'm running it on a $35 atomicpi along with the Jellyfin server, and I see no issues with all 3 tuner's streaming.

It may be better in the long run to use a reverse proxy...

**Comment by casasfernando** [comment]
Setup a reverse proxy even for LAN connections in order to have https working?
I think is overkill.
For now staying in 10.4.3 is enough for me until this bug is fixed.

**Comment by jrbski** [comment]
If your really worried about security, a reverse proxy using nginx is likely a better option. nginx would get more security review than jellyfin. The team working on this project has been doing a great job adding features and improvements for core functionality. From my perspective relying on  a reverse proxy like nginx or apache is a better option than relying on jellyfin for security.

**Comment by Artiume** [comment]
As the Unix philosophy goes: do one thing and do it well. I believe it applies here. No matter how much security focus we give, our main focus is media. Nginx has more review and focus for security than we will ever be capable of and I trust their security more than ours.

We need to look at what's going on with the port mapping to try and fix it but at the end of the day, I personally don't like using Required secure mode as the only means of security and trust a reverse proxy to better secure my system.

**Comment by PrplHaz4** [comment]
> 
> 
> If your really worried about security, a reverse proxy using nginx is likely a better option. nginx would get more security review than jellyfin. The team working on this project has been doing a great job adding features and improvements for core functionality. From my perspective relying on a reverse proxy like nginx or apache is a better option than relying on jellyfin for security.

This issue was opened to address a server on the local network only.

A reverse proxy doesn't just give you security.  You also need to also secure access to the proxy, the server, and the pipe between them at the network level (get your CCNA ready) for it to make a difference.

If nothing else, a functional HTTPS server prevents your network from blasting plaintext passwords all over the place (to be scooped up by all manner of IoT devices).

**Comment by Artiume** [comment]
Haha yeah, nothing is secure without proper authentication and isolation. I can't wait until proper OIDC authentication built into the client's. Nothing is really secure until then. I personally don't care about proper piping on the internal network level because if I'm compromised to the point where someone can sniff my internal http traffic, I have way bigger issues than my Media server. 

My major concern is when a server is publicly exposed and people use `Required` to protect themselves believing it provides security. At least with a proxy, you can mitigate some xss injection.

https://www.acunetix.com/blog/articles/a-fresh-look-on-reverse-proxy-related-attacks/

> get your CCNA ready

I'm more focused on getting my CEH and CISSP 😉

**Comment by JustAMan** [comment]
> Pretty sure this is a bug. We saw this behavior with DLNA too, which I thought led to removing “preferred” as the secure connection mode default.
> 
> Jellyfin is telling FFmpeg that the file is here, but https and port 8096 should never be together. Protocol and port should be both secure or both insecure not a mixture.
> 
> `https://127.0.0.1:8096/LiveTv/LiveStreamFiles/612ac597c4e54c108cf63b07c67c16ff/stream.ts`

Great find! See the fix here: https://github.com/jellyfin/jellyfin/pull/2740

**Comment by casasfernando** [comment]
Great news, hopefully this will be merged in the next release.

Thanks everyone for taking the time to look into this and comment.
