### ISSUE TITLE
libSkiaSharp throwing errors

### ISSUE THREAD

**Issue by SchnozzleCat** [jellyfin/jellyfin#2572]
libSkiaSharp is throwing a lot of errors in my Jellyfin log file, and some features do not work. 
For example, if I try to change a library's banner image, nothing happens when I click the image, and the logfile prints this trace:

System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkiaApi.sk_refcnt_safe_unref(IntPtr refcnt)
   at SkiaSharp.SKObjectExtensions.SafeUnRef(ISKReferenceCounted obj)
   at SkiaSharp.SKObject.GetObject[TSkiaObject,TSkiaImplementation](IntPtr handle, Boolean owns, Boolean unrefExisting, Boolean refNew)
   at SkiaSharp.SKObject.GetObject[TSkiaObject](IntPtr handle, Boolean owns, Boolean unrefExisting, Boolean refNew)
   at SkiaSharp.SKImageInfoNative.ToManaged(SKImageInfoNative& native)
   at SkiaSharp.SKCodec.get_Info()
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info, Boolean updateItem)
   at MediaBrowser.Api.Images.ImageService.GetImageInfo(BaseItem item, ItemImageInfo info, Nullable`1 imageIndex)

 - OS: Ubuntu Server 18.04.4 LTS
 - Virtualization: None
 - Clients: Any
 - Browser: Any
 - Jellyfin Version: 10.5.0
 - Playback: N/A
 - Installed Plugins: AudioDB, MusicBrainz
 - Reverse Proxy: None
 - Networking: Host
 - Storage: DAS

Complete Logfile: https://hastebin.com/ufifiqatep.hs
You can see it throws multiple libSkiaSharp errors.
This is on a fresh Jellyfin install.

**Comment by SchnozzleCat** [comment]
See https://github.com/jellyfin/jellyfin/issues/2471
