### ISSUE TITLE
FanArt Plugin Causing Crashing On 10.5.0

### ISSUE THREAD

**Issue by grravity** [jellyfin/jellyfin#2574]
**Describe the bug**
So, I updated Jellyfin the other night from 10.4.3 to 10.5.0. I am running it on Windows 10. So, it seems to be crashing randomly, sometimes it may stay up for a bit, other times it keeps going down 10-20min between restarts. It's very random. I do see some stuff within the logs. Note my addons may be out of date, I don't think this would cause Jellyfin to crash like this, so I figured I'd solve this first before doing addon updates. It's a PITA to update the addons in Windows currently tbh because of it needing to be done manually.

So the first time it crashed, I saw the following in the log.
```
System.MissingMethodException: Method not found: 'System.IO.Stream MediaBrowser.Model.IO.IFileSystem.GetFileStream(System.String, MediaBrowser.Model.IO.FileOpenMode, MediaBrowser.Model.IO.FileAccessMode, MediaBrowser.Model.IO.FileShareMode, Boolean)'.
   at Jellyfin.Plugin.Fanart.Providers.MovieProvider.DownloadMovieJson(String id, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Fanart.Providers.MovieProvider.DownloadMovieJson(String id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.MovieProvider.EnsureMovieJson(String id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.MovieProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2020-03-09 19:54:30.198 -04:00] [FTL] [88] Main: Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
```
Talked to @anthonylavado and he said a few plugins need updates, and top of the stack trace says FanArt so that might be it he stated. Or he said it might be the migration failing. He wasn't sure. Again, I can't exactly see why out of date plugins might cause this, but if anyone else thinks that is probably causing the issue, please state and I will try updating them.

Anyways, it was working fine for a few hours on 10.5.0 I watched like an hour of shows, then went to bed. I woke up, and it was crashed again. I originally though it might be related to navigating stuff on the Web GUI but, I was using AndroidTV before I went to bed. Then when I woke up the next day, I started Jellyfin backup, and within 10 minutes it crashed again. Note I didn't even open the webgui. I checked the logs again, and the following was in it at the bottom:
```
MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
[2020-03-10 11:05:21.583 -04:00] [FTL] [16] Main: Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
So for now I downgraded back down to 10.4.3, and all has been stable the past two days, no issues, no crashes. So it seems to definitely be an issue with 10.5.0, as the issue isn't happening on the previous version.
I should note, that upon downgrading, the installer did give me a bunch of errors for .dll files, but I mentioned this to Ant and he seemed not worried. I figured these were just files added in 10.5.0, that were deleted from the downgrade, but just took note in case.

Also to be clear, when I stated "crashed" above, it Jellyfin Tray still remains in Windows 10 tray, it just crashes and the option to "Stop server" changes grey and I have to restart the server by clicking "Start server", and that's what I mean by "crashed" and "restarted", just to be clear.

**System (please complete the following information):**
 - OS: WIndows 10
 - Virtualization: None
 - Clients: Android TV, Android, Web GUI (Firefox ESR)
 - Browser: Firefox ESR
 - Jellyfin Version: 10.4.3 and 10.5.0
 - Playback: N/A?
 - Installed Plugins: Anime 4.0, Bookshelf 1.0.0.0, Fanart 3.0, Open Subtitles 7.0, Playback Reporting 4.0, TMDb Box Sets 4.0, Trakt 7.0, [Jellyfin JAV 0.3.0](https://github.com/imaginary-upside/JellyfinJav)
 - Reverse Proxy: Caddy
 - Base URL: N/A?
 - Networking: N/A?
 - Storage: Local

**Comment by Artiume** [comment]
Could you rename this to FanArt Plugin Causes Crashes

**Comment by grravity** [comment]
> 
> 
> Could you rename this to FanArt Plugin Causes Crashes

This hasn't been fixed in 5.1/5.2 yet correct?

**Comment by bwaddington** [comment]
doesnt seem to be working in 10.5.2

**Comment by Artiume** [comment]
Once it's been fixed, it should work for >10.5.0, not just a specific JF version.

**Comment by grravity** [comment]
> 
> 
> Once it's been fixed, it should work for >10.5.0, not just a specific JF version.

Ah, so it's a plugin specific bug, not a Jellyfin bug? On Windows, the plugins don't get auto-updates, so I assume I am reliant on manually updating the FanArt plugin to get it working whenever it gets fixed?

**Comment by samwathegreat** [comment]
I would be interested in knowing how to disable automatic updates.  This has happened to me twice.  First, when jellyfin auto-updated the Auto organize plugin.  I ended up having to uninstall it.   Now it has happened again with this plugin.  It seems like if a plugin has a problem, it should fail gracefully and not prevent the whole program from running.

Anyways, the error I received for BOTH plugins that caused jellyfin to not start are identical -- the reference to MediaBrowser.Common :

![image](https://user-images.githubusercontent.com/4813336/78104302-0352e980-73bd-11ea-9c6b-21586c2c4063.png)

**Comment by anthonylavado** [comment]
Well #2730 fixes the crashing issue for the next version, and automatic plug-in updates should be a scheduled task that you can turn off. It'll be in the Admin Dashboard, towards the bottom of the options on the left.

**Comment by grravity** [comment]
Good to hear, I'll checkout 10.5.3 when it releases and see if I still have any issues

**Comment by JustAMan** [comment]
@grravity FYI, 10.5.3 was released on April 5, so you can try and check.

**Comment by grravity** [comment]
@JustAMan Yeah I've been busy and probably won't be able to check until about a week for now, will report back when I can, thank you!

**Comment by grravity** [comment]
Hm, so it was fine earlier, I played some stuff for a few hours. Came back to my computer and saw Jellyfin seemed to have stopped, as I check in the task tray and it shows the option to start it. In the log the last few lines were:
```
MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[2020-04-12 19:45:42.531 -04:00] [INF] Killing ffmpeg process
[2020-04-12 19:45:42.532 -04:00] [ERR] ffmpeg image extraction failed for file:"H:\Hard Drive\Movies\MovieName (20xx)\MovieFile.mkv"
[2020-04-12 19:45:42.536 -04:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:H:\Hard Drive\Movies\MovieName (20xx)\MovieFile.mkv""
System.Exception: ffmpeg image extraction failed for file:"H:\Hard Drive\Movies\MovieName (20xx)\MovieFile.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
```

On a sidenote, I also see above that a lot (going up the entire log) of "CloudflareSolverRe" lines, what uses Cloudflare? o.O
Anyways, it seems to have been doing some sort of metadata scan or refresh idk. But I still don't see why this crashed. Nothing notable from what I am seeing? 
I did try to install TMDbBoxSets from catalog hours ago when I first updated, to see if I can update a plugin without deleting it manually first. It was just lingering loading, I backed out and it showed it on the old version still, I left it for then. And the server was working fine for hours. So unless that gotd elayed and crashed or something idk. 
Idk what happened. I will play with it a bit more over the next few days, if you see anything in those last few lines, or have any suggestions lmk.

**Comment by JustAMan** [comment]
I don't see any error messages in the logs. Can you check Windows error reporting? It might be crashing somewhere in the native code which isn't handled by .NET error handling thus no logs.

**Comment by grravity** [comment]
By Windows error reporting, do you mean check in Event Viewer? Never had to do this before

**Comment by grravity** [comment]
```
[2020-04-14 19:05:42.634 -04:00] [INF] User policy for "USERCENSORED". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-04-14 19:05:42.670 -04:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 12247467, max bitrate: 1500000
[2020-04-14 19:05:42.677 -04:00] [INF] Profile: "Unknown Profile", Path: "MOVIEDIRECTORY.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-14 19:05:42.704 -04:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "MOVIEDIR.MKV"
[2020-04-14 19:05:42.760 -04:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 12247467, max bitrate: 1500000
[2020-04-14 19:05:42.762 -04:00] [INF] Profile: "Unknown Profile", Path: "MOVIEDIR.MKV", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-14 19:05:42.764 -04:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "MOVIEDIR.MKV"
[2020-04-14 19:05:42.765 -04:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 12247467, max bitrate: 1500000
[2020-04-14 19:05:42.767 -04:00] [INF] Profile: "Unknown Profile", Path: "MOVIEDIR.MKV", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-14 19:05:42.768 -04:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "MOVIEDIR.MKV"
[2020-04-14 19:05:42.810 -04:00] [WRN] HTTP Response 200 to "192.168.5.4". Time (slow): 0:00:02.6601125. "MYDOMAIN AND USER ID =&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=1500000"
[2020-04-14 19:05:58.023 -04:00] [FTL] Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[2020-04-14 19:06:37.808 -04:00] [INF] Jellyfin version: "10.5.4"
[2020-04-14 19:06:37.830 -04:00] [INF] Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\Users\name\AppData\Local\Jellyfin"]
[2020-04-14 19:06:37.836 -04:00] [INF] Operating system: "Windows"
[2020-04-14 19:06:37.837 -04:00] [INF] Architecture: X64
[2020-04-14 19:06:37.838 -04:00] [INF] 64-Bit Process: True
[2020-04-14 19:06:37.838 -04:00] [INF] User Interactive: True
[2020-04-14 19:06:37.839 -04:00] [INF] Processor count: 8
```
Here's a new log, I upgraded to 5.4, I went to "Identify" a movie to fix the version it pulled for metadata, and then it seemed to crash. Idk if that was what caused it to crash or not, it could've just been the timing. I only launched Jellyfin like 2 minutes before that. The above were the last few lines from before it crashed and I started it. I know I should've grabbed the log before I started it back up, that was my bad mistake and I did out of habit. Censored some stuff in the log like names, domains and users.

**Comment by grravity** [comment]
```
[2020-04-15 16:36:57.720 -04:00] [ERR] Error in "AniDB"
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Jellyfin.Plugin.Anime.Providers.AniDB.Identity.AniDbTitleDownloader.DownloadTitles_static(String titlesFile)
   at Jellyfin.Plugin.Anime.Providers.AniDB.Identity.AniDbTitleDownloader.Load_static(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Anime.Providers.Equals_check.Fast_xml_search(String a, String b, CancellationToken cancellationToken, Boolean return_AniDBid, Int32 x_)
   at Jellyfin.Plugin.Anime.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-04-15 16:36:58.164 -04:00] [INF] Start Proxer... Searching("South Park")
[2020-04-15 16:36:58.896 -04:00] [FTL] Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
More crashes, will go and try to update all my plugins right now I think they're kinda out of date.
But just wanted to post this. All was working fine for hours, and it just randomly crashed.

**Comment by JustAMan** [comment]
It seems that you got an outdated TMDbBoxSet plugin.

**Comment by JustAMan** [comment]
@jellyfin/backend thoughts on adding our own [UnhandledException handler](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=netcore-3.1) to _not_ crash the app on `MissingMethodException`?

**Comment by grravity** [comment]
> 
> 
> It seems that you got an outdated TMDbBoxSet plugin.

Yeah just updated everything, so I will see how things go from here.
