### ISSUE TITLE
trakt plugin not syncing watch states

### ISSUE THREAD

**Issue by Hoodah** [jellyfin/jellyfin#2575]
**Describe the bug**
trakt plugin not syncing watch states

**System (please complete the following information):**
 - OS: Debian
 - Jellyfin Version: 10.5.0

**To Reproduce**
run trakt "Import Playstates" scheduled task

**Expected behavior**
to import playstates...

**Logs**
[2020-03-11 13:44:05.057 -07:00] [ERR] Error syncing trakt data for user "Hoodah"
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
[2020-03-11 13:44:05.058 -07:00] [INF] "Import playstates from Trakt.tv" Completed after 0 minute(s) and 0 seconds
[2020-03-11 13:44:05.061 -07:00] [INF] ExecuteQueuedTasks

**Comment by jconnop** [comment]
Trakt plugin version 7 was built against jellyfin 10.4. When trying to use it on 10.5 it has this issue because the type of OrderBy property was changed.

Using any build of the plugin >= 8 should resolve this issue.

**Comment by Hoodah** [comment]
Gotcha. That info lead me to learn about the plugin update mechanism, which I see is a Scheduled Task. However that task is running into an error as well, which is probably why I'm still using ver 7.0 of the trakt plugin.
```
[2020-03-12 19:45:11.085 -07:00] [INF] Executing "Update Plugins"
[2020-03-12 19:45:12.132 -07:00] [ERR] Package installation failed
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken)
[2020-03-12 19:45:12.166 -07:00] [ERR] Error downloading "Trakt"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
[2020-03-12 19:45:12.174 -07:00] [INF] "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2020-03-12 19:45:12.344 -07:00] [INF] ExecuteQueuedTasks
```

**Comment by Hoodah** [comment]
seems to have resolved itself magically overnight.

**Comment by jconnop** [comment]
@Hoodah oh yeah should have bumped this sorry - someone fixed the plugin update system :)
