### ISSUE TITLE
Unable to install the trakt plugin using the plugin catalog (Not found)

### ISSUE THREAD

**Issue by miracle152005** [jellyfin/jellyfin#2584]
Hi,
I am unable to install the trakt plugin using the plugin catalog.
Everytime I am trying to install I get an installation failed message.
In the message detail a "not found" is displayed.

Could you please take a look.
Thanks.

Best regards
miracle152005

The logfiles contain the following entry:
```
[2020-03-12 22:47:24.208 +01:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken)
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: ubuntu 18.04
 - Clients: Browser
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.0
 - Installed Plugins: None

**Comment by jconnop** [comment]
Looks like the build system has started to extend version numbers in plugins to 4 components (i.e. 8.0.0.0), but the manifest is pointing clients at urls assuming 2 components (i.e. 8.0).

tmdb boxsets plugin looks to be the other one affected at the moment

![repo_trakt](https://user-images.githubusercontent.com/375060/76572072-ecd41380-651d-11ea-8aa4-17de5c3deb80.PNG)

![repo_tmdb](https://user-images.githubusercontent.com/375060/76572081-f198c780-651d-11ea-97c8-3306bfbb511b.PNG)

**Comment by dkanada** [comment]
cc @joshuaboniface

**Comment by StableNarwhal** [comment]
Yep, same here.

**Comment by joshuaboniface** [comment]
Should be fixed now, I've manually fixed up the manifest and @oddstr13's PR fixes up the code for any new ones.

**Comment by joshuaboniface** [comment]
You'll have to restart Jellyfin too or local caching will prevent it from recognizing the update.
