### ISSUE TITLE
Can no longer get a login screen on 10.3.3 after upgrade

### ISSUE THREAD

**Issue by usstattik** [jellyfin/jellyfin#2586]
**Describe the bug**
I was running 10.2.2 in Docker and upgraded to 10.4.3 Docker.  When I try to connect via web, I get a black screen.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 72.0.2, Vivaldi 2.1.1337.36
 - Jellyfin Version: [10.3.3,]
 - Playback: [NA] 
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Bridge]
 - Storage: [cifs]

**To Reproduce**

1. Start jellyfin 10.4.2.2 docker
2. Go to browser http://192.168.1.254:8096
3. Get black screen
4. Go to jellyfin logs (sudo docker logs jellyfin)

**Expected behavior**
I expect to be presented with a choice of accounts to login with,

**Logs**
This was the error in the logs.

```
System.ArgumentException: String doesn't contain enough segments
Parameter name: storageString
   at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.GetEasyPasswordHash(User user)
   at Emby.Server.Implementations.Library.UserManager.GetUserDto(User user, String remoteEndPoint)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaBrowser.Api.UserService.Get(GetUsers request, Boolean filterByDevice, Boolean filterByNetwork)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

I reverted back to 10.2.2 and was able to log again.  I decided to incrementally upgrade and was successfull up to 10.3.2.  At 10.3.3 I got the same error message.  Looking at the changelog, I thought it might be related to #1372(Fix broken pin in 10.3.z)?  I tried clearing all PINs and that did not help.  Setting the PIN code and enabling in-network sign-in changed the error to what's below:
```

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Model.Cryptography.PasswordHash..ctor(String storageString)
   at Emby.Server.Implementations.Library.UserManager.GetLocalPasswordHash(User user)
   at Emby.Server.Implementations.Library.UserManager.GetUserDto(User user, String remoteEndPoint)
   at MediaBrowser.Api.UserService.Get(GetUser request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Additional context**
PINs were between 4 and 6 digits.  All accounts have passwords.  I've also tried 10.4.1 and a recent nightly of 10.5. 

I looked at #1858 which is still open and looked similar but it doesn't match the new error I'm getting.
Any help would be greatly appreciated.

**Comment by dkanada** [comment]
We can't really support such an old installation. The version you were on came out over a year ago and we have exactly zero time to check that jumping major versions will work 100% of the time, although we have made improvements recently that will help with this. I would suggest a new installation.

**Comment by usstattik** [comment]
Okay.  Is there any way to save the watch history or custom art?  I don't save the art in media folders.

**Comment by Artiume** [comment]
Is the directory structure the same? I thought there were changes during the 10.3 version. I suggest making a new setup in a different folder and once it's configured, do a comparison. Maybe everything is missing due to being shifted around.

**Comment by usstattik** [comment]
I had two accounts that were originally setup without passwords.  It caused problems and I eventually set them up with passwords and they worked fine on 10.4.2.  I deleted the accounts and was able to successfully update to 10.4.3.  I plan to test 10.5. in the near future.  Thanks for your suggestions.

**Comment by usstattik** [comment]
I had two accounts that were originally setup without passwords.  It caused problems and I eventually set them up with passwords and they worked fine on 10.4.2.  I deleted the accounts and was able to successfully update to 10.4.3.  I plan to test 10.5. in the near future.  Thanks for your suggestions.
