### ISSUE TITLE
[10.5.0] New series not getting recognized (TheTVDB)

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin#2597]
**Describe the bug**

New series not getting recognized

**System (please complete the following information):**
 - OS: Ubuntu bionic
 - Virtualization: KVM
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.5.0
 - Playback: N/A
 - Installed Plugins:
Anime
4.0.0.0
AudioDB
10.5.0.0
Bookshelf
2.0.0.0
Fanart
3.0.0.0
Kodi Sync Queue
3.0.0.0
MusicBrainz
10.5.0.0
Playback Reporting
4.0.0.0
Reports
4.0.0.0
TMDb Box Sets
5.0.0.0
Trakt
8.0.0.0
YTDLMetadata
1.0.0.0
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: Standard single NAT
 - Storage: unionfs over cifs

**To Reproduce**

Add new show

**Expected behavior**

**Logs**

```
[2020-03-15 00:43:30.576 +00:00] [ERR] Error in DummySeasonProvider
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2020-03-15 00:43:46.261 +00:00] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The REST API returned an unkown error.
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2020-03-15 00:43:46.578 +00:00] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The REST API returned an unkown error.
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```
**Screenshots**

**Additional context**

Also reported on Reddit; https://old.reddit.com/r/jellyfin/comments/fig1ba/linux_library_not_being_scanned_fully/

**Comment by csyperski** [comment]
I'm seeing the same error on my end as well.

**Comment by Vitorvlv** [comment]
+1. Also, don't know if it is related or not. But scans are taking forever to complete.

**Comment by emilweth** [comment]
+1, same issue here.

**Comment by Bidley** [comment]
Same issue here. Scans for TV Shows keep cancelling. I'm able to complete a scan if I purge my data, run a clean image of Jellyfin and untick all theTVDB options in the setup process.

**Comment by Shadowghost** [comment]
Maybe there wer changes to the API (didn't find any announcements though). Seems like Filebot can't fetch metadata from thetvdb too.
Does anyone know if jellyfin uses v1 or v2 of the API?

**Comment by drikqlis** [comment]
This may be related #2613

**Comment by JustAMan** [comment]
@Bond-009 @cvium thoughts?

**Comment by pc-v2** [comment]
i have this issue too

**Comment by Bond-009** [comment]
This should be fixed, can anyone confirm?
