### ISSUE TITLE
Can't download all metadata images

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin#2613]
**Describe the bug**

After update to 10.5.0 downloading of metadata and images is not working correctly for TV shows.

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Virtualization: Hyper-V
 - Clients: Chromium
 - Browser: Chromium 80
 - Jellyfin Version: 10.5.0
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Storage: SMB

**To Reproduce**

1. Add new TV show.
2. Try to download all metadata.
3. Only some images are downloaded.

**Expected behavior**

All images should download, they are present on providers.

**Logs**

```
[2020-03-16 11:01:57.813 +01:00] [ERR] No metadata found for 0
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
[2020-03-16 11:01:57.992 +01:00] [ERR] "TmdbSeasonImageProvider" failed in GetImageInfos for type "Season"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonImageProvider.FetchImages(Season item, String tmdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2020-03-16 11:02:19.865 +01:00] [ERR] "TmdbEpisodeImageProvider" failed in GetImageInfos for type "Episode"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.FetchMainResult(String urlPattern, String id, Int32 seasonNumber, Int32 episodeNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.DownloadEpisodeInfo(String id, Int32 seasonNumber, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.GetEpisodeInfo(String seriesTmdbId, Int32 season, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2020-03-16 11:02:20.897 +01:00] [ERR] "TmdbEpisodeImageProvider" failed in GetImageInfos for type "Episode"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.FetchMainResult(String urlPattern, String id, Int32 seasonNumber, Int32 episodeNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.DownloadEpisodeInfo(String id, Int32 seasonNumber, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.GetEpisodeInfo(String seriesTmdbId, Int32 season, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```
**Screenshots**

Images for newly added show:
![obraz](https://user-images.githubusercontent.com/19647553/76747308-3e2c0f00-6779-11ea-95a5-8d13b4f78fa5.png)

Images for show added in previous version:
![obraz](https://user-images.githubusercontent.com/19647553/76747276-30768980-6779-11ea-8c1f-a758cb0cc3cd.png)

**Additional context**

I had my main metadata provider set as The Movie Database, changed the order to TVDB but nothing changed. I had Fanart plugin installed but I removed it and nothing changed. My metadata settings:
![obraz](https://user-images.githubusercontent.com/19647553/76747552-9d8a1f00-6779-11ea-9c09-a192149b25ef.png)
![obraz](https://user-images.githubusercontent.com/19647553/76747592-b0045880-6779-11ea-82e2-ccf89958c040.png)
![obraz](https://user-images.githubusercontent.com/19647553/76747411-5f8cfb00-6779-11ea-8fe3-16d1b1a9517d.png)
![obraz](https://user-images.githubusercontent.com/19647553/76747623-bb578400-6779-11ea-9cdd-6aaa1d83082a.png)

In fetcher settings for series there is only primary and banner tick available:
![obraz](https://user-images.githubusercontent.com/19647553/76747456-74698e80-6779-11ea-9b2f-04d280286da3.png)

**Comment by Vitorvlv** [comment]
The banner, icon and logo I believe are downloaded from fanarttv, which is not working on 10.5.0. There is a [pr](https://github.com/jellyfin/jellyfin-plugin-fanart/pull/15) making it work on the new version, but it hasn't been accepted so far.

**Comment by JustAMan** [comment]
@drikqlis @Vitorvlv seeing that fanart PR was accepted and that plugin is probably released, could you please recheck?

**Comment by drikqlis** [comment]
I reinstalled fanart plugin and it seems to be working now, thanks.

**Comment by sensei73** [comment]
Hi, I have the same problem with everything up to date!
```
[2020-04-29 06:58:19.534 +02:00] [ERR] [23] ProviderManager: "TmdbSeasonImageProvider" failed in GetImageInfos for type "Season"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```
