### ISSUE TITLE
DLNA no working in 10.5.1

### ISSUE THREAD

**Issue by txutxifel** [jellyfin/jellyfin#2623]
First, 
My congratuletion for your job, I think you are making a very good job.

I've just installed the app, all functions are working perfectly except DLNA,  I checked this error:
 #2377 BaseURL breakers DLNA (and probably more)
but my BaserURL is empty. I use port forwarding by ports.

I use http  and https (with let's encript) to get outside. In my TV, I got an error in the file.

The log is:
```
[2020-03-17 10:43:11.285 +01:00] [INF] "USERSYNC" User "2bcfd1d9fb3b43c688eeb4c0ef0f7f02"("MIUSER") posted 2 Updates: "9f4000db2d197478761c23235dd65d7d,ab26142a9690fa4147497428aab210dc"
[2020-03-17 10:43:11.287 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0661571"
[2020-03-17 10:43:12.072 +01:00] [ERR] Error processing request: "The operation was canceled."
[2020-03-17 10:43:12.106 +01:00] [WRN] HTTP Response 206 to "192.168.1.200". Time (slow): 0:00:03.2587784. "http://192.168.1.250:8096/Videos/9f4000db2d197478761c23235dd65d7d/stream.mp4?Static=true&mediaSourceId=9f4000db2d197478761c23235dd65d7d&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo3My4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzczLjB8MTU4NDIwNDQyMjk4NQ11&Tag=95f2b36bb51e9aed960ffe8fb83165b0"
[2020-03-17 10:43:12.114 +01:00] [INF] Profile: "[LG] SMART TV LH570V", Path: "/home/osmc/Peliculas/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (2019)XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.2019.720p.WEBRip.x264-[YTS.LT].mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-17 10:43:12.263 +01:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.5.1" playing "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX". Stopped at "2013" ms
[2020-03-17 10:43:12.589 +01:00] [INF] Starting Library Sync...
[2020-03-17 10:43:12.590 +01:00] [INF] "LIBRARYSYNC" Added 0 items:  ""
[2020-03-17 10:43:12.621 +01:00] [INF] "LIBRARYSYNC" Updated 1 items:  "659e9ceb75d06450d1a18648a7af40a9"
[2020-03-17 10:43:12.621 +01:00] [INF] "LIBRARYSYNC" Removed 0 items:  ""
[2020-03-17 10:43:12.622 +01:00] [INF] Finished Library Sync Taking "00:00:00.0318208"
[2020-03-17 10:43:12.674 +01:00] [ERR] HTTP request failed with message: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><errorCode>501</errorCode><errorDescription>Action Failed</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
[2020-03-17 10:43:12.861 +01:00] [INF] Starting User Changes Sync...
[2020-03-17 10:43:12.875 +01:00] [INF] "USERSYNC" User "2bcfd1d9fb3b43c688eeb4c0ef0f7f02"("MIUSER") posted 2 Updates: "9f4000db2d197478761c23235dd65d7d,ab26142a9690fa4147497428aab210dc"
[2020-03-17 10:43:12.876 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0133713"
[2020-03-17 10:43:40.332 +01:00] [INF] Getting image size for item "CollectionFolder" "/var/lib/jellyfin/root/default/Peliculas/poster.jpg"
[2020-03-17 10:43:40.335 +01:00] [ERR] Failed to determine primary image aspect ratio for "/var/lib/jellyfin/root/default/Peliculas/poster.jpg"
System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.
```

I hope this be able to help u.

Cheers!!!!!!

**Comment by PrplHaz4** [comment]
1. Did this work in any previous version?
2. Can you play the same file in the web client?
3. DLNA only works on the local network - is the TV on the same network as your Jellyfin server?
4. Is there an FFMPEG log generated?
5. Can you turn on DLNA Debug Logging and try again then see if anything new is in the log?

**Comment by Artiume** [comment]
> but my BaserURL is empty. I use port forwarding by ports.

What do you mean by forwarding ports? Dlna only works in the same subnet

**Comment by txutxifel** [comment]
Hi
First, thanks for answering so fast

- Did this work in any previous version?
I installed jellyfin 3 days ago. I can speak about previous versions.

- Can you play the same file in the web client?
Yes, I don't have problems. DLNA fails in andoid app, in firefox and chromium. I stopped firewalld in de PC (i use linux) and jellyfin It

DLNA only works on the local network 
I didnt now   but I tried from local and outside IP

is the TV on the same network as your Jellyfin server?
Yes, and 
I tried from my ip local -> http:/192.168.1.250:8096  -> fails
I tried from https:/mydomain.com:port, but  I didn't know that it doesn't work


Is there an FFMPEG log generated?
No

Can you turn on DLNA Debug Logging and try again then see if anything new is in the log?
I did it. it is what i got

Also:
I have stopped firewalld in the test in the PC (i use Opensuse) 
I have installed jellyfin in a Rapsberry PI 3. 
I use DLNA in LG TV with other apps without problems.



Checking the logs,  there is two difenrent errors:


.....
2020-03-17 22:07:01.679 +01:00] [INF] DLNA Session created for "Kodi (PC001)" - "Kodi"
[2020-03-17 22:07:01.791 +01:00] [INF] DLNA Session created for "[LG] SMART TV LH570V" - "LG TV"
[2020-03-17 22:07:01.903 +01:00] [INF] DLNA Session created for "osmc" - "Kodi"
[2020-03-17 22:07:09.543 +01:00] [INF] Profile: "[LG] SMART TV LH570V", Path: "/home/osmc/Series/XXXXXX/Season 05/XXX.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-17 22:07:09.683 +01:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null. (Parameter 'baseUrl')
   at MediaBrowser.Model.Dlna.StreamInfo.ToUrl(String baseUrl, String accessToken)
   at Emby.Dlna.PlayTo.PlayToController.CreatePlaylistItem(BaseItem item, User user, Int64 startPostionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-17 22:07:18.974 +01:00] [WRN] HTTP Response 200 to "192.168.1.200". Time (slow): 0:00:11.3210799. "http://192.168.1.250:8096/web/controllers/itemdetailpage.js?v=10.5.1"
[2020-03-17 22:07:18.991 +01:00] [WRN] HTTP Response 400 to "192.168.1.200". Time (slow): 0:00:09.9464294. "http://192.168.1.250:8096/Sessions/a4575fd1216a36d1d5dc6d7ca30b2877/Playing?ItemIds=517c52e3fa33833a8d1e1124bbf9fed0&PlayCommand=PlayNow"
[2020-03-17 22:07:20.553 +01:00] [WRN] HTTP Response 200 to "192.168.1.200". Time (slow): 0:00:01.5792488. "http://192.168.1.250:8096/web/components/itemcontextmenu.js?v=10.5.1"
[2020-03-17 22:07:20.732 +01:00] [WRN] HTTP Response 200 to "192.168.1.200". Time (slow): 0:00:01.7650293. "http://192.168.1.250:8096/web/controllers/dashboard/dashboard.js?v=10.5.1"
[2020-03-17 22:07:21.136 +01:00] [INF] Getting image size for item "CollectionFolder" "/var/lib/jellyfin/root/default/Peliculas/poster.jpg"
.....




[2020-03-17 22:12:44.404 +01:00] [INF] Profile: "LG Smart TV", Path: "/media/XXXX/Season 01/XXXXXXX.720p.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-03-17 22:12:45.661 +01:00] [ERR] HTTP request failed with message: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><errorCode>501</errorCode><errorDescription>Action Failed</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
[2020-03-17 22:12:45.685 +01:00] [WRN] HTTP Response 204 to "IP". Time (slow): 0:00:01.304335. "https:/domain:port/Sessions/c1c449594ea57fdc5bcfbed3af978fd9/Playing?ItemIds=ee61305982c03001f20ff279a00acf15&PlayCommand=PlayNow"
[2020-03-17 22:13:10.837 +01:00] [ERR] Error encoding image
System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkiaApi.sk_refcnt_safe_unref(IntPtr refcnt)
   at SkiaSharp.SKObjectExtensions.SafeUnRef(ISKReferenceCounted obj)
   at SkiaSharp.SKObject.GetObject[TSkiaObject,TSkiaImplementation](IntPtr handle, Boolean owns, Boolean unrefExisting, Boolean refNew)
   at SkiaSharp.SKImageInfoNative.ToManaged(SKImageInfoNative& native)
   at SkiaSharp.SKCodec.get_Info()
   at SkiaSharp.SKBitmap.Decode(SKCodec codec)
   at SkiaSharp.SKBitmap.Decode(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, Nullable`1 orientation, SKEncodedOrigin& origin)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetBitmap(String path, Boolean cropWhitespace, Boolean forceAnalyzeBitmap, Nullable`1 orientation, SKEncodedOrigin& origin)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetBitmap(String path, Boolean cropWhitespace, Boolean autoOrient, Nullable`1 orientation)
   at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)

**Comment by Artiume** [comment]
> [2020-03-17 22:13:10.837 +01:00] [ERR] Error encoding image

This one is the screen Grabber failing, known issue. What's your method of install?

> [2020-03-17 22:07:09.683 +01:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null. (Parameter 'baseUrl')

Weird. Try entering a base url then removing it.

On the networking page, what is Secure Connection Mode set to? Try Disabled. It requires a restart.

**Comment by txutxifel** [comment]
Thanks, it get it working

- This one is the screen Grabber failing, known issue. What's your method of install?
sorry, I don't understand the question

Weird. Try entering a base url then removing it.
I tried, and It continued failing

On the networking page, what is Secure Connection Mode set to? Try Disabled. It requires a restart.
Required in remote connections, with a let's encript SSL certificate.
I disabled it and dlna started working!!!!!! Is could be a bug?
I configurated my local network -> 192.168.1.0/24 without sucess.

Thanks for your help!!

**Comment by Artiume** [comment]
How did you install jellyfin?

See this issue for connection mode issues https://github.com/jellyfin/jellyfin/issues/2259

**Comment by txutxifel** [comment]
- How did you install jellyfin?
I used this repo:
deb [arch=armhf] https://repo.jellyfin.org/debian stretch main

- See this issue for connection mode issues #2259
I disabled Secure Mode, and used Nginx as a reverse proxy. 
Now DLNA works.

However, I am not sure what it the best option.

Thanks anyway!!!!!!!

**Comment by Artiume** [comment]
Disabled and Required are the two primary modes. It is better to use Disabled + nginx over required. While jellyfin can use certs, I find it best to leave security to a reverse proxy.

**Comment by txutxifel** [comment]
Ok, then
Thanks for anwering so fast and yout explanations.

**Comment by JustAMan** [comment]
Can we close the issue then @txutxifel ?

**Comment by txutxifel** [comment]
Yes, I have update to 10.5.2. Now, Subtitles are showed correctly.

Cheers!!
