### ISSUE TITLE
Error updating device info for "65OLED854/12" MediaBrowser.Model.Net.HttpException: Not Found

### ISSUE THREAD

**Issue by micceo** [jellyfin/jellyfin#2644]
**Describe the bug**

DLNA doesn't looks like it works on my OLED Philips.

[2020-03-22 06:39:39.457 +01:00] [INF] [39] Dlna: DLNA Session created for "65OLED854/12" - "Philips TV DMR"
[2020-03-22 06:39:40.472 +01:00] [ERR] [39] Emby.Server.Implementations.HttpClientManager.HttpClientManager: HTTP request failed with message: "<html><body><h1>404 Not Found</h1></body></html>"
[2020-03-22 06:39:40.475 +01:00] [ERR] [39] Dlna: Error updating device info for "65OLED854/12"
MediaBrowser.Model.Net.HttpException: Not Found
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: No
 - Clients: 65OLED854/12 Philips
 - Browser: Nopp
 - Jellyfin Version: 10.5.0.0 
 - Playback: not reaching this info
 - Installed Plugins: Open Subtitles 7.0.0.0
 - Reverse Proxy: no
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. Use a 65OLED854/12 Philips OLED TV.
2. See error

**Logs**
```
[2020-03-22 06:39:39.457 +01:00] [INF] [39] Dlna: DLNA Session created for "65OLED854/12" - "Philips TV DMR"
[2020-03-22 06:39:40.472 +01:00] [ERR] [39] Emby.Server.Implementations.HttpClientManager.HttpClientManager: HTTP request failed with message: "<html><body><h1>404 Not Found</h1></body></html>"
[2020-03-22 06:39:40.475 +01:00] [ERR] [39] Dlna: Error updating device info for "65OLED854/12"
MediaBrowser.Model.Net.HttpException: Not Found
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

**Screenshots**
no

**Additional context**
I've posted this here also, didn't really knew where to go.
https://forum.jellyfin.org/t/65oled854-12-generate-this-in-the-log/1024/9

Brgs,

**Comment by micceo** [comment]
Sorry don't have much experience on github or c#  but is looks like this is the culprit.
 jellyfin/Emby.Dlna/PlayTo/Device.cs "Error updating device info ", row 478

I can't figure much from what I'm seeing here.
Does DLNA debug logs help out anything here?

**Comment by Bond-009** [comment]
Your tv is returning a 404, is DLNA enabled in the settings? Another possibility is that it isn’t happy with the request we send.

**Comment by micceo** [comment]
Ah, didn't figure out that it was the return from TV, but that's rather obvious now when explained. DLNA, to my understanding, is enabled as it works with VLC from Windows and Android devices.

**Comment by micceo** [comment]
Just a question. The Philips TV mention this in the manual.
_Media server (DMS) which is supported: DLNA V1.5-certified media server software (DMS-Class)_

So does Jellyfin comply to this?

**Comment by BaronGreenback** [comment]
I see you are running under windows. Instal the "Developer Tools for UPnP™ Technology" suite.

It will allow you to probe the tv and see the responses.

If you have the capabilities - download PR#3257 and enable debugging. This is a network re-write which includes more debug informaton. It should show you what Jellyfin is sending out and what it's receiving.
