### ISSUE TITLE
Meta Data Doesn't update.

### ISSUE THREAD

**Issue by shaynethiessen** [jellyfin/jellyfin#2649]
I can't update meta data for movies/tv shows.

If i try to manually identify the movie, it always returns zero results.

 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Firefox
 - Jellyfin Version: 10.5.0

```
[2020-03-23 08:20:58.827 -05:00] [WRN] [142] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "172.17.0.1". Time (slow): 0:00:00.5121974. "http://localhost:8096/Auth/Keys"
[2020-03-23 08:21:08.733 -05:00] [ERR] [60] App: Error in "TheMovieDb"
System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetTmdbSettings(CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbSearch.GetSearchResults(ItemLookupInfo idInfo, String searchType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService2.ExecuteRemoteProviders(MetadataResult1 temp, String logName, TIdType id, IEnumerable1 providers, CancellationToken cancellationToken)
```

**Comment by Bond-009** [comment]
Looks like TheMovieDb was/is down/unreachable?

**Comment by shaynethiessen** [comment]
> Looks like TheMovieDb was/is down/unreachable?

FYI I get the same problem when using "The Open Movie Database". So it's either an issue with jellyfin, or my configuration, but I have no idea what it could be. Any suggestions?

`[2020-03-23 11:06:54.745 -05:00] [WRN] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "172.17.0.1". Time (slow): 0:00:10.0136699. "http://localhost:8096/Items/ae6a371e2759c48aa9663308679ad761/Images/Primary?tag=7a9c3b20e9e82cf448402e796cd0304f&quality=90"
[2020-03-23 11:06:56.306 -05:00] [ERR] [111] App: Error in "The Open Movie Database"
System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Omdb.OmdbItemProvider.GetSearchResultsInternal(ItemLookupInfo searchInfo, String type, Boolean isSearch, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Omdb.OmdbItemProvider.GetMovieImdbId(ItemLookupInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Omdb.OmdbItemProvider.GetMovieResult[T](ItemLookupInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService2.ExecuteRemoteProviders(MetadataResult1 temp, String logName, TIdType id, IEnumerable1 providers, CancellationToken cancellationToken)`

**Comment by shaynethiessen** [comment]
Okay. I fixed this. If anyone else ever encounters the same issue, check your hosts /etc/resolv.conf file. Make sure it's pointing to your dns server. If it's not, change it, and then restart your docker container.

**Comment by ltove** [comment]
but when i click the actor, jellyfin is always loading ,plz help me ,ok?thanks !!!

[2020-10-20 14:51:58.577 +00:00] [WRN] [38] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "172.17.0.1". Time (slow): 0:01:40.0280566.
