### ISSUE TITLE
Exception when starting 10.5.2 with 10.4.3 configuration

### ISSUE THREAD

**Issue by bialad** [jellyfin/jellyfin#2651]
**Describe the bug**
After updating my docker image from 10.4.3 to 10.5.2 jellyfin fails to start with my /config mounted. If I don't mount /config it starts. Can't find anything related to my config in the logs, so need help to troubleshoot.

**System:**
 - OS: debian and k3os
 - Virtualization: Docker
 - Jellyfin Version: 10.5.2
 - Installed Plugins: Open Subtitles
 - Storage: NFS

**Logs**
15:52:23] [INF] Jellyfin version: 10.5.2
[15:52:23] [INF] Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/local/bin/ffmpeg"]
[15:52:23] [INF] Operating system: Linux
[15:52:23] [INF] Architecture: X64
[15:52:23] [INF] 64-Bit Process: True
[15:52:23] [INF] User Interactive: True
[15:52:23] [INF] Processor count: 8
[15:52:23] [INF] Program data path: /config
[15:52:23] [INF] Web resources path: /jellyfin/jellyfin-web
[15:52:23] [INF] Application directory: /jellyfin/
[15:52:23] [INF] Setting cache path: /cache
[15:52:23] [INF] Loading assemblies
[15:52:23] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
[15:52:23] [INF] Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/OpenSubtitlesHandler.dll
[15:52:26] [INF] Kestrel listening on all interfaces
[15:52:27] [WRN] No XML encryptor configured. Key {5ee48b4f-6344-4ac7-abde-8abfe962093b} may be persisted to storage in unencrypted form.
[15:52:27] [INF] Running startup tasks
[15:52:27] [INF] Daily trigger for Extract Chapter Images set to fire at 03/24/2020 02:00, which is 10:07:32.8965516 from now.
[15:52:27] [INF] Found ffmpeg version 4.2.1
[15:52:27] [INF] Available decoders: ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[15:52:27] [INF] Available encoders: ["libx264", "h264_nvenc", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[15:52:27] [INF] FFmpeg: Custom: /usr/local/bin/ffmpeg
[15:52:27] [INF] ServerId: c44e2470141549b68ada29119db14e6d
[15:52:27] [INF] Executed all pre-startup entry points in 0:00:00.2663861
[15:52:27] [INF] Core startup complete
[15:52:27] [WRN] Connection shutdown abnormally.
System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.WebUtilities, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.WebUtilities, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases.CreateStatusBytes(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases..cctor()

   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases.ToStatusBytes(Int32 statusCode, String reasonPhrase)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.WriteResponseHeadersInternal(BufferWriter`1& writer, Int32 statusCode, String reasonPhrase, HttpResponseHeaders responseHeaders, Boolean autoChunk)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.WriteResponseHeaders(Int32 statusCode, String reasonPhrase, HttpResponseHeaders responseHeaders, Boolean autoChunk, Boolean appComplete)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceEnd()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
[15:52:27] [INF] Skipping realtime monitor for /media/Barn because the path does not exist
[15:52:27] [INF] Skipping realtime monitor for /media/HD because the path does not exist
[15:52:27] [INF] Skipping realtime monitor for /media/tv because the path does not exist
[15:52:27] [FTL] Error while starting server.
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Nat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6c9468a3c21bc6d1'. The system cannot find the file specified.

File name: 'Mono.Nat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6c9468a3c21bc6d1'
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.Start()
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.RunAsync()
   at Emby.Server.Implementations.ApplicationHost.StartEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup)+MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[15:52:27] [INF] Disposing CoreAppHost
[15:52:27] [INF] Disposing ActivityLogWebSocketListener
[15:52:27] [INF] Disposing SessionInfoWebSocketListener
[15:52:27] [INF] Disposing ScheduledTasksWebSocketListener
[15:52:27] [INF] Disposing SessionWebSocketListener
[15:52:27] [INF] Disposing EmbyTV
[15:52:27] [INF] Disposing ApiEntryPoint
[15:52:27] [INF] Disposing ServerEntryPoint
[15:52:27] [INF] Disposing EntryPoint
[15:52:27] [INF] Disposing DeviceAccessEntryPoint
[15:52:27] [INF] Disposing LibraryMonitorStartup
[15:52:27] [INF] Disposing ExternalPortForwarding
[15:52:27] [ERR] Error disposing ExternalPortForwarding
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Nat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6c9468a3c21bc6d1'. The system cannot find the file specified.

File name: 'Mono.Nat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6c9468a3c21bc6d1'
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.Stop()
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.Dispose(Boolean dispose)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.Dispose()
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)

[15:52:27] [INF] Disposing LibraryChangedNotifier
[15:52:27] [INF] Disposing RecordingNotifier
[15:52:27] [INF] Disposing ServerEventNotifier
[15:52:27] [INF] Disposing StartupWizard
[15:52:27] [INF] Disposing UdpServerEntryPoint
[15:52:27] [ERR] Error disposing UdpServerEntryPoint
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.EntryPoints.UdpServerEntryPoint.Dispose()
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
[15:52:27] [INF] Disposing UserDataChangeNotifier
[15:52:27] [INF] Disposing DeviceManagerEntryPoint
[15:52:27] [INF] Disposing CollectionManagerEntryPoint
[15:52:27] [INF] Disposing ActivityLogEntryPoint
[15:52:27] [INF] Disposing DlnaEntryPoint
[15:52:27] [INF] Disposing SsdpDevicePublisher
[15:52:27] [INF] Disposing PlayToManager
[15:52:27] [INF] Disposing DeviceDiscovery
[15:52:27] [INF] Disposing SsdpCommunicationsServer
[15:52:27] [INF] SsdpCommunicationsServer disposing _BroadcastListenSocket
[15:52:27] [INF] Disposing NotificationEntryPoint
[15:52:27] [INF] Disposing EntryPoint
[15:52:27] [INF] Received a SIGTERM signal, shutting down

**Comment by bialad** [comment]
Solved it myself after goinf through the config file one by one. The issue was solved by moving by transcoding directory from /jellyfin to /cache.

What would be the "offical" supported directory for having transcoing out of the /config directory?

**Comment by dkanada** [comment]
I think you can place it anywhere, but some people like using RAM if they have enough for the speed.

**Comment by bialad** [comment]
@dkanada Thank for the tip, I did that and it works! :)
