### ISSUE TITLE
Local PIN is authenticated from public network

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin#2671]
**Describe the bug**
If you set a pin to allow easy access from local networks the pin will work from public networks also.  I verified this by using my cell phone data connection.  The log shows an `Error authenticating with provider "Default"` error but the user is authenticated anyway.

**System (please complete the following information):**
 - OS: Ubuntu 19.10
 - Virtualization: N/A
 - Clients: iPhone Safari Browser
 - Browser: iOS 13.4
 - Jellyfin Version: 10.5.2
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: HAProxy
 - Base URL: None
 - Networking: Host
 - Storage: N/A

**To Reproduce**
1.  Set LAN networks under Dashboard > Networking.  I have the following: `192.168.1.0/24, 192.168.10.0/24`
2.  Ensure `Allow remote connections to this Jellyfin server` is checked
3.  Set EasyPIN code
4.  Ensure `Enable in-network sign in with my easy pin code` is checked
5.  Login to jellyfin from a remote connection (cell phone data connection is one way to verify this).

**Expected behavior**
User is not allowed to authenticated using their easy pin code because they are not on the local network.

**Logs**

```
[2020-03-25 23:29:59.699 -04:00] [ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-03-25 23:29:59.772 -04:00] [INF] Authentication request for "SomeUser" "has succeeded".
[2020-03-25 23:29:59.773 -04:00] [INF] Creating new access token for user 62D6D8DA-D5F1-4EF4-9968-7BF27BE11446
[2020-03-25 23:30:00.105 -04:00] [INF] WS "http://xxx.xxxxxxx.xxxxxxx/socket?api_key=some_long_ass_api_key". UserAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1"
```

**Additional context**
I verified this multiple times and it renders pin code useless as it becomes a huge security issue.

**Comment by mcarlton00** [comment]
I can't replicate this.  Double check your reverse proxy settings.  If you're not forwarding the public IP address back to Jellyfin, then it looks as if all connections to your server are originating at your haproxy instance.  In that case, all traffic does match your LAN rules and will allow pin login.

**Comment by anthonylavado** [comment]
I concur with @mcarlton00’a findings. I am not using a reverse proxy and can not replicate this. (I VPN back to my home when I need to access Jellyfin.)

**Comment by uchagani** [comment]
I will double check this again tonight. You guys might be right as I
remember seeing my reverse proxy IP address in the Jellyfin UI and thought
it was odd. Will verify and close this if that is the case.

**Comment by uchagani** [comment]
@mcarlton00 @anthonylavado both correct.  was an issue with my reverse proxy.  closing the issue.  thank you.

**Comment by anthonylavado** [comment]
@uchagani No worries. Thanks for following up!
