### ISSUE TITLE
Users/AuthenticateByName returns 500 code when passing invalid credentials

### ISSUE THREAD

**Issue by villagra** [jellyfin/jellyfin#2675]
**Describe the bug**
Users/AuthenticateByName returns a 500 error code when passing invalid credentials instead of a standard 401 (“Unauthorized”)
The content of the response contains the following message: "Object reference not set to an instance of an object." So an unhandled exception is happening

**System (please complete the following information):**
 - OS: Qnap linux os
 - Virtualization: Docker
 - Clients: API
 - Jellyfin Version: 10.5.0
 - Base URL: http://ip:port/Users/AuthenticateByName

**To Reproduce**
1. Authenticate with invalid credentials in the portal or call the api Users/AuthenticateByName
2. See error

**Expected behavior**
A standard 401 (“Unauthorized”) code response should be returned with an appropriate message in the content

**Comment by JustAMan** [comment]
Could you please provide server logs? We request following a template for a reason.

**Comment by villagra** [comment]
`[2020-04-08 08:06:01.557 +00:00] [ERR] [35] Emby.Server.Implementations.Library.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-04-08 08:06:02.016 +00:00] [INF] [35] Emby.Server.Implementations.Library.UserManager: Authentication request for "admin" "has been denied".
[2020-04-08 08:06:02.050 +00:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.SessionManager.GetAuthorizationToken(User user, String deviceId, String app, String appVersion, String deviceName)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-04-08 08:06:02.083 +00:00] [WRN] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "192.168.1.231". Time (slow): 0:00:00.8353684. "http://192.168.1.230:32770/Users/AuthenticateByName"
[2020-04-08 08:06:03.121 +00:00] [ERR] [35] Emby.Server.Implementations.Library.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-04-08 08:06:03.131 +00:00] [INF] [35] Emby.Server.Implementations.Library.UserManager: Authentication request for "admin" "has been denied".
[2020-04-08 08:06:03.135 +00:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.SessionManager.GetAuthorizationToken(User user, String deviceId, String app, String appVersion, String deviceName)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by JustAMan** [comment]
@Bond-009 @joshuaboniface rings a bell?

**Comment by crobibero** [comment]
We now return a 401 on on invalid username or password
