### ISSUE TITLE
Busy: Database is locked

### ISSUE THREAD

**Issue by Lilja** [jellyfin/jellyfin#2679]
**Describe the bug**
Starting a docker container from linuxserver/jellyfin creates a `busy: Database is locked`

**System (please complete the following information):**
 - OS: Ubuntu 18
 - Virtualization: Docker
 - Jellyfin Version: 10.5.2
 - Networking: Docker network
 - Storage: NFS

**To Reproduce**

**Expected behavior**

**Logs**
<details>

<summary>Click to expand</summary>

```
lilja@devnode:~/htpc$ docker-compose up jellyfin
Starting jellyfin ...
Starting jellyfin ... done
Attaching to jellyfin
jellyfin    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jellyfin    | [s6-init] ensuring user provided files have correct perms...exited 0.
jellyfin    | [fix-attrs.d] applying ownership & permissions fixes...
jellyfin    | [fix-attrs.d] done.
jellyfin    | [cont-init.d] executing container initialization scripts...
jellyfin    | [cont-init.d] 01-envfile: executing...
jellyfin    | [cont-init.d] 01-envfile: exited 0.
jellyfin    | [cont-init.d] 10-adduser: executing...
jellyfin    | usermod: no changes
jellyfin    |
jellyfin    | -------------------------------------
jellyfin    |           _         ()
jellyfin    |          | |  ___   _    __
jellyfin    |          | | / __| | |  /  \
jellyfin    |          | | \__ \ | | | () |
jellyfin    |          |_| |___/ |_|  \__/
jellyfin    |
jellyfin    |
jellyfin    | Brought to you by linuxserver.io
jellyfin    | We gratefully accept donations at:
jellyfin    | https://www.linuxserver.io/donate/
jellyfin    | -------------------------------------
jellyfin    | GID/UID
jellyfin    | -------------------------------------
jellyfin    |
jellyfin    | User uid:    1000
jellyfin    | User gid:    1000
jellyfin    | -------------------------------------
jellyfin    |
jellyfin    | [cont-init.d] 10-adduser: exited 0.
jellyfin    | [cont-init.d] 30-config: executing...
jellyfin    | [cont-init.d] 30-config: exited 0.
jellyfin    | [cont-init.d] 40-gid-video: executing...
jellyfin    | [cont-init.d] 40-gid-video: exited 0.
jellyfin    | [cont-init.d] 99-custom-scripts: executing...
jellyfin    | [custom-init] no custom files found exiting...
jellyfin    | [cont-init.d] 99-custom-scripts: exited 0.
jellyfin    | [cont-init.d] done.
jellyfin    | [services.d] starting services
jellyfin    | [services.d] done.
jellyfin    | [20:35:34] [INF] [1] Main: Jellyfin version: 10.5.2
jellyfin    | [20:35:34] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
jellyfin    | [20:35:34] [INF] [1] Main: Operating system: Linux
jellyfin    | [20:35:34] [INF] [1] Main: Architecture: X64
jellyfin    | [20:35:34] [INF] [1] Main: 64-Bit Process: True
jellyfin    | [20:35:34] [INF] [1] Main: User Interactive: True
jellyfin    | [20:35:34] [INF] [1] Main: Processor count: 1
jellyfin    | [20:35:34] [INF] [1] Main: Program data path: /config/data
jellyfin    | [20:35:34] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
jellyfin    | [20:35:34] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
jellyfin    | [20:35:34] [INF] [1] ServerConfigurationManager: Setting cache path: /config/cache
jellyfin    | [20:35:34] [INF] [1] App: Loading assemblies
jellyfin    | [20:35:34] [FTL] [1] Main: Error while starting server.
jellyfin    | Busy: SQLitePCL.pretty.SQLiteException: database is locked
jellyfin    |    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.StatementImpl.MoveNext()
jellyfin    |    at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
jellyfin    |    at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
jellyfin    |    at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    | [20:35:34] [INF] [1] App: Disposing CoreAppHost
jellyfin    | [20:35:34] [INF] [2] Main: Received a SIGTERM signal, shutting down
jellyfin    | [20:35:35] [INF] [1] Main: Jellyfin version: 10.5.2
jellyfin    | [20:35:35] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
jellyfin    | [20:35:35] [INF] [1] Main: Operating system: Linux
jellyfin    | [20:35:35] [INF] [1] Main: Architecture: X64
jellyfin    | [20:35:35] [INF] [1] Main: 64-Bit Process: True
jellyfin    | [20:35:35] [INF] [1] Main: User Interactive: True
jellyfin    | [20:35:35] [INF] [1] Main: Processor count: 1
jellyfin    | [20:35:35] [INF] [1] Main: Program data path: /config/data
jellyfin    | [20:35:35] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
jellyfin    | [20:35:35] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
jellyfin    | [20:35:35] [INF] [1] ServerConfigurationManager: Setting cache path: /config/cache
jellyfin    | [20:35:35] [INF] [1] App: Loading assemblies
jellyfin    | [20:35:35] [FTL] [1] Main: Error while starting server.
jellyfin    | Busy: SQLitePCL.pretty.SQLiteException: database is locked
jellyfin    |    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.StatementImpl.MoveNext()
jellyfin    |    at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
jellyfin    |    at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
jellyfin    |    at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    | [20:35:35] [INF] [1] App: Disposing CoreAppHost
jellyfin    | [20:35:35] [INF] [2] Main: Received a SIGTERM signal, shutting down
jellyfin    | [20:35:36] [INF] [1] Main: Jellyfin version: 10.5.2
jellyfin    | [20:35:36] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
jellyfin    | [20:35:36] [INF] [1] Main: Operating system: Linux
jellyfin    | [20:35:36] [INF] [1] Main: Architecture: X64
jellyfin    | [20:35:36] [INF] [1] Main: 64-Bit Process: True
jellyfin    | [20:35:36] [INF] [1] Main: User Interactive: True
jellyfin    | [20:35:36] [INF] [1] Main: Processor count: 1
jellyfin    | [20:35:36] [INF] [1] Main: Program data path: /config/data
jellyfin    | [20:35:36] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
jellyfin    | [20:35:36] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
jellyfin    | [20:35:36] [INF] [1] ServerConfigurationManager: Setting cache path: /config/cache
jellyfin    | [20:35:36] [INF] [1] App: Loading assemblies
jellyfin    | [20:35:36] [FTL] [1] Main: Error while starting server.
jellyfin    | Busy: SQLitePCL.pretty.SQLiteException: database is locked
jellyfin    |    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
jellyfin    |    at SQLitePCL.pretty.StatementImpl.MoveNext()
jellyfin    |    at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
jellyfin    |    at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
jellyfin    |    at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    | [20:35:36] [INF] [1] App: Disposing CoreAppHost
jellyfin    | [20:35:36] [INF] [2] Main: Received a SIGTERM signal, shutting down
^CGracefully stopping... (press Ctrl+C again to force)
Stopping jellyfin ... done


```

</details>

**Additional context**
Docker-compose
```
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${JELLYFIN}/config:/config # plex database
      - ${TV_SERIES}:/data/tvshows # tvshows
      - ${MOVIES}:/data/movies # tvshows
```

.env file
```
JELLYFIN=/mnt/Software/Linux/htpc/jellyfin
TV_SERIES=/mnt/TV Shows
MOVIES=/mnt/Movies


PUID=1000
PGID=1000
TZ=Europe/Stockholm

```

**Comment by Lilja** [comment]
`/mnt/Software` is a SMB share from my NAS. Mounted on the host.

Switched to a local path for the drive and it seems to work. 

I had the same issue for running a postgres container and it turned out a similar issue.

**Comment by Artiume** [comment]
You shouldn't attempt to run a sqlite database over a network. That's gonna cause a bad day.

**Comment by Lilja** [comment]
Well, I like the thought that the config is persisted somewhere so if the VM dies it's actually saved somewhere else. 
How can I achieve that without writing cronjobs with something like rsync to run every x hours?

**Comment by Artiume** [comment]
@joshuaboniface you have any ideas?

**Comment by dkanada** [comment]
> How can I achieve that without writing cronjobs with something like rsync to run every X hours?

This is the generally accepted way to handle backups, so I feel like that is what Josh will suggest. We could potentially move the database to another location in the future so you can avoid that in the remote mount but I don't expect this any time soon. I'll close this issue for now though, since the issue itself has been resolved.
