### ISSUE TITLE
Jellyfin crashes on startup when TVHeadend or Kodi Sync Queue are installed and enabled

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin#2685]
**Describe the bug**
After the last nightly upgrade the server keeps crashing when TVHeadend or Kodi Sync Queue Plugins are installed.

**System:**
 - OS: Debian10 x86_64
 - Virtualization: none
 - Jellyfin Version: 10.5.x, nightly 20200326
 - Installed Plugins: Kody Sync Queue, TVHeadend

**To Reproduce**
1. Install TVHeadend or Kodi Sync Queue from Plugin Catalogue
2. Restart Server (sometimes it crashes by itself without restart)
3. Server crashes with the errors below

**Expected behavior**
Server to not crash when using official Plugins. Would be better if it just disables them when not compatible or throws a useful error.

**Logs**
```
 App: Loading assemblies
 App: Loaded assembly TVHeadEnd, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TVHeadend/TVHeadEnd.dll
 Error while starting server.
 System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
 File name: 'MediaBrowser.Controller, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
    at System.Reflection.RuntimeAssembly.GetExportedTypes()
    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection, IConfiguration startupConfig)
    at Jellyfin.Server.Program.StartApp(StartupOptions options)
App: Disposing CoreAppHost
Main: Received a SIGTERM signal, shutting down
systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
```

**Comment by eltiel** [comment]
This is now happening with Anime, Fanarts and Reports plugin as well. This basically happens with all plugins which were updated to run on 10.5.2.

I suspect the plugins look for a component which is specific to 10.5.2 but the nightly is still labeled as 10.5.0, so it crashes the server upon startup.

Error:
` File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null' `

**Comment by Sp4rky001** [comment]
> This is now happening with Anime, Fanarts and Reports plugin as well. This basically happens with all plugins which were updated to run on 10.5.2.
> 
> I suspect the plugins look for a component which is specific to 10.5.2 but the nightly is still labeled as 10.5.0, so it crashes the server upon startup.
> 
> Error:
> `File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'`

I can confirm that this is the solution to the problem with the plugins.  I cloned the repository and did a search/replace all 10.5.0 with 10.5.2 and now, with my own compile, Kodi Sync Queue is working for me.

**Comment by fengapappit** [comment]
I want to add that it also happens for me on latest 10.5.2, so not just nightly.

**Comment by Jon12345** [comment]
Not sure if this is related as I'm on Windows, but after installing Kodi Sync Queue I get this error when starting Jellyfin:

Error: The type initializer for 'System.Marvin' threw an exception.
Couldn't load configuration. The application will now close.

Log shows:
[2020-06-04 21:32:00.185 +10:00] [INF] [1] Main: Jellyfin version: "10.5.5"
....
[2020-06-04 21:36:05.356 +10:00] [INF] [1] App: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Kodi Sync Queue\Jellyfin.Plugin.KodiSyncQueue.dll"
[2020-06-04 21:36:05.364 +10:00] [INF] [1] App: Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "C:\ProgramData\Jellyfin\Server\plugins\Kodi Sync Queue\LiteDB.dll"

**Comment by crobibero** [comment]
Plugins no longer crash jellyfin if they fail to load.
