### ISSUE TITLE
EEROR:There was an error processing the request. Please try again later.

### ISSUE THREAD

**Issue by uniartisan** [jellyfin/jellyfin#2694]
**Describe the bug**

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] UNRAID 6.8.1
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] 
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Chrome 80, 79
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] latest,nightly 20200327
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] none
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] no proxy
 - Base URL: [e.g. none, yes: /example] http://192.168.31.176:8096/
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]local

**To Reproduce**

1. Go to 'general'
2. Click on 'language'
3. Scroll down to 'chinese'
![image](https://user-images.githubusercontent.com/31544054/77815224-e1731180-70f3-11ea-9a11-88c38f81a6b1.png)

**Expected behavior**

it seems to be websocket error, and when i chose other oponion such as transcoding it comes to the same error.
**Logs**

```
[2020-03-28 13:20:27.253 +08:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-28 13:20:27.254 +08:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-28 13:20:27.260 +08:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-28 13:20:33.785 +08:00] [INF] [8] Emby.Server.Implementations.Library.UserManager: Authentication request for "lizhiyuan" "has succeeded".
[2020-03-28 13:20:33.788 +08:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 56d3e7a7-b600-43f2-a2f9-92e41225e61c
[2020-03-28 13:20:34.046 +08:00] [INF] [13] App: WS "http://192.168.31.176:8096/socket?api_key=e5cbb62524124d88b9783a5e99f84d2e&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgwLjAuMzk4Ny4xNDkgU2FmYXJpLzUzNy4zNiBFZGcvODAuMC4zNjEuNjl8MTU4NTM2NzUxMTI2NA11". UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 Edg/80.0.361.69"
[2020-03-28 13:20:39.380 +08:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "/config/metadata does not exist."
[2020-03-28 13:21:11.379 +08:00] [ERR] [4] TaskManager: Error
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+MoveNext()
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2020-03-28 13:21:11.393 +08:00] [INF] [4] TaskManager: "Update Plugins" Failed after 1 minute(s) and 37 seconds
[2020-03-28 13:21:11.439 +08:00] [INF] [4] TaskManager: ExecuteQueuedTasks
···
**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by yhsrzbg** [comment]
I also encountered this problem

Synology DS918+   docker

**Comment by now163** [comment]
> I also encountered this problem
> 
> Synology DS918+ docker

me too...

**Comment by uniartisan** [comment]
I have also tried  another docker : linuxserver/jellyfin ,the same quwstion.

**Comment by gyshier** [comment]
Create a new folder metadata，C:\Users\*\AppData\Local\jellyfin\metadata

**Comment by coreflake1** [comment]
Same issue here. running on docker on debian.
Can't enable hardware transcoding.

**Comment by uniartisan** [comment]
It works! thank you a lot

> Create a new folder metadata，C:\Users*\AppData\Local\jellyfin\metadata

**Comment by JustAMan** [comment]
Most likely duplicate of https://github.com/jellyfin/jellyfin/issues/2677

**Comment by xibuka** [comment]
The error is because below dir is not exist!
![image](https://user-images.githubusercontent.com/21263862/80112241-d8bf0f80-85bb-11ea-942c-3aacb56d0079.png)

So go inside the container and create the folder, then you should save the changes.

**Comment by alienwaredream** [comment]
> The error is because below dir is not exist!
> ![image](https://user-images.githubusercontent.com/21263862/80112241-d8bf0f80-85bb-11ea-942c-3aacb56d0079.png)
> 
> So go inside the container and create the folder, then you should save the changes.

It works! thank you a lot

**Comment by tonightsentertainmentinfo-gif** [comment]
I get this same error when I try to get past making a password for the admin. I have tried these steps and it still doesn't work. Am I doing something wrong
