### ISSUE TITLE
Access token is invalid or expired

### ISSUE THREAD

**Issue by yqused** [jellyfin/jellyfin#2704]
[2020-03-29 17:14:01.384 +08:00] [INF] [4] Main: Jellyfin version: "10.5.2"
[2020-03-29 17:14:01.446 +08:00] [INF] [4] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/local/bin/ffmpeg"]
[2020-03-29 17:14:01.594 +08:00] [INF] [4] Main: Operating system: "Linux"
[2020-03-29 17:14:01.594 +08:00] [INF] [4] Main: Architecture: X64
[2020-03-29 17:14:01.595 +08:00] [INF] [4] Main: 64-Bit Process: True
[2020-03-29 17:14:01.596 +08:00] [INF] [4] Main: User Interactive: True
[2020-03-29 17:14:01.596 +08:00] [INF] [4] Main: Processor count: 4
[2020-03-29 17:14:01.596 +08:00] [INF] [4] Main: Program data path: "/config"
[2020-03-29 17:14:01.596 +08:00] [INF] [4] Main: Web resources path: "/jellyfin/jellyfin-web"
[2020-03-29 17:14:01.597 +08:00] [INF] [4] Main: Application directory: "/jellyfin/"
[2020-03-29 17:14:02.363 +08:00] [INF] [4] ServerConfigurationManager: Setting cache path: "/cache"
[2020-03-29 17:14:02.399 +08:00] [INF] [4] App: Loading assemblies
[2020-03-29 17:14:03.478 +08:00] [WRN] [4] Emby.Server.Implementations.Library.UserManager: No users, creating one with username "root"
[2020-03-29 17:14:05.253 +08:00] [INF] [4] ServerConfigurationManager: Saving system configuration
[2020-03-29 17:14:05.256 +08:00] [INF] [4] ServerConfigurationManager: Setting cache path: "/cache"
[2020-03-29 17:14:05.962 +08:00] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking all known migrations as applied because this is a fresh install
[2020-03-29 17:14:06.013 +08:00] [INF] [4] Main: Kestrel listening on all interfaces
[2020-03-29 17:14:06.829 +08:00] [INF] [4] App: Running startup tasks
[2020-03-29 17:14:06.842 +08:00] [INF] [4] TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 03/30/2020 02:00, which is 8:45:53.1579202 from now.
[2020-03-29 17:14:09.116 +08:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.2.1"
[2020-03-29 17:14:09.180 +08:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2020-03-29 17:14:09.199 +08:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_nvenc", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-03-29 17:14:09.200 +08:00] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: "/usr/local/bin/ffmpeg"
[2020-03-29 17:14:09.202 +08:00] [INF] [4] App: ServerId: "71858c9d72614e69869dc33310c22f2e"
[2020-03-29 17:14:09.797 +08:00] [INF] [7] App: Executed all pre-startup entry points in 0:00:00.5650408
[2020-03-29 17:14:09.798 +08:00] [INF] [7] App: Core startup complete
[2020-03-29 17:14:09.831 +08:00] [INF] [11] Dlna: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "172.17.0.4"
[2020-03-29 17:14:09.850 +08:00] [INF] [4] TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-03-29 17:14:09.852 +08:00] [INF] [4] TaskManager: Queueing task "PluginUpdateTask"
[2020-03-29 17:14:09.858 +08:00] [INF] [4] TaskManager: Executing "Update Plugins"
[2020-03-29 17:14:10.239 +08:00] [INF] [7] App: Executed all post-startup entry points in 0:00:00.4399774
[2020-03-29 17:14:10.240 +08:00] [INF] [7] Main: Startup complete 0:00:10.5807424
[2020-03-29 17:14:11.249 +08:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-29 17:14:13.153 +08:00] [INF] [4] TaskManager: "Update Plugins" Completed after 0 minute(s) and 3 seconds
[2020-03-29 17:14:13.202 +08:00] [INF] [4] TaskManager: ExecuteQueuedTasks
[2020-03-29 17:14:15.414 +08:00] [ERR] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-29 17:14:15.427 +08:00] [ERR] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-29 17:14:15.443 +08:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-03-29 17:14:15.614 +08:00] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Access token is invalid or expired."
[2020-03-29 17:14:16.093 +08:00] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-03-29 17:14:20.730 +08:00] [INF] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Access token is invalid or expired."
[2020-03-29 17:14:20.770 +08:00] [INF] [7] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Access token is invalid or expired."

**Comment by JustAMan** [comment]
Could you please follow issue template? At least describe what is the problem you're seeing, and what's the expected behaviour.

Just showing the log without any explanation doesn't enable us to act in any way.
