### ISSUE TITLE
DLNA stream of LiveTV not working

### ISSUE THREAD

**Issue by frasty** [jellyfin/jellyfin#2737]
Playing LiveTV channels via DLNA fails. Only channels browsing does work.
Movies and other videos play without problems via DLNA.

**System**

 - OS: Fedora Linux 31
 - Virtualization: no
 - Clients: BubbleUPNP, VLC, deoVR on android, kodi..
 - Jellyfin Version: 10.5.2
 - Installed Plugins: audiodb, fanart, kodi sync queue, musicbrainz, TVHeadend
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**Steps to reproduce:**

1. From a DLNA control point (i.e. gupnp-av-cp) select LiveTV, then select a channel to view
2. click on a DLNA renderer on the network
3. nothing happens

**Expected behavior**

LiveTV channel should play on any DLNA renderer.

**Logs**
```
2020-04-02 06:03:32.744 +02:00] [INF] [25] Dlna: Profile: "Generic Device", Path: "Unknown path", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-04-02 06:03:32.876 +02:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-04-02 06:03:32.882 +02:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-04-02 06:03:32.894 +02:00] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-04-02 06:03:32.900 +02:00] [ERR] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.Playback.BaseStreamingService.GetOutputFilePath(StreamState state, EncodingOptions encodingOptions, String outputFileExtension)
   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

```
Wireshark decoded http conversation:
```
GET /videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=test&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true HTTP/1.1
Host: 192.168.9.5:8096
User-Agent: Kodi/18.6 (X11; Linux x86_64) Fedora/31 App_Bitness/64 Version/18.6-Git:20200304-nogitfound
Accept: */*
Accept-Encoding: deflate, gzip, br
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
Accept-Charset: UTF-8,*;q=0.8

HTTP/1.1 500 Internal Server Error
Connection: close
Date: Thu, 02 Apr 2020 04:08:53 GMT
Content-Type: text/plain
Server: Kestrel
Transfer-Encoding: chunked
Content-Encoding: br
Vary: Accept-Encoding
```

**Additional context**
Playing LiveTV from jellyfin web application works fine.

**Comment by PrplHaz4** [comment]
Have you tried both PlayTo as well as browsing to the media item directly?  Have you tried multiple renderers/videos?  It may be a problem with the profile you're using or something in the content.  Also, I see HTTP2 - guessing this is on nightly, not 10.5.2?

**Comment by frasty** [comment]
I recently tried PlayTo to kodi (coreelec and fedora) and VLC both SD and HD LiveTV channels to no avail. Playing local video files via PlayTo and on jellyfin itself works fine. LiveTV Channels works only if I play them on jellyfin.

This is the log snippet generated by kodi when playing a LiveTV channel via PlayTo/DLNA cp:
```
2020-04-07 22:07:11.776 T:140120507826048  NOTICE: VideoPlayer::OpenFile: http://192.168.9.5:8096/videos/e83ac942-8eaa-de04-693a-6000849347ab/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=e83ac9428eaade04693a6000849347ab&Static=true&dlnaheaders=true
2020-04-07 22:07:11.788 T:140120507826048   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://192.168.9.5:8096/videos/e83ac942-8eaa-de04-693a-6000849347ab/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=e83ac9428eaade04693a6000849347ab&Static=true&dlnaheaders=true
2020-04-07 22:07:11.789 T:140120210937600  NOTICE: Creating InputStream
2020-04-07 22:07:11.797 T:140120210937600   ERROR: CCurlFile::Open failed with code 500 for http://192.168.9.5:8096/videos/e83ac942-8eaa-de04-693a-6000849347ab/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=e83ac9428eaade04693a6000849347ab&Static=true&dlnaheaders=true:
                                            Object reference not set to an instance of an object.
2020-04-07 22:07:11.808 T:140120210937600   ERROR: Previous line repeats 1 times.
2020-04-07 22:07:11.808 T:140120210937600   ERROR: Open - failed to open source <http://192.168.9.5:8096/videos/e83ac942-8eaa-de04-693a-6000849347ab/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=e83ac9428eaade04693a6000849347ab&Static=true&dlnaheaders=true>
2020-04-07 22:07:11.808 T:140120210937600   ERROR: CVideoPlayer::OpenInputStream - error opening [http://192.168.9.5:8096/videos/e83ac942-8eaa-de04-693a-6000849347ab/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=e83ac9428eaade04693a6000849347ab&Static=true&dlnaheaders=true]
```

jellyfin version is 10.5.2:
# rpm -q jellyfin
jellyfin-10.5.2-1.fc31.x86_64

**Comment by PrplHaz4** [comment]
@frasty Is secure connection mode set to "Disabled"?

**Comment by frasty** [comment]
Yes, jellyfin listens only on port 8096.

**Comment by lyonzy** [comment]
I had this too and it looks like extension is null in GetOutputFilePath. I can confirm setting it to "" when it's null fixed live streaming to DLNA for me (I had the same stack trace posted above).

**Comment by frasty** [comment]
Still having the same problem after upgrading to latest jellyfin 10.5.5.0 running as a docker container, albeit the error message is different:

```
2020-04-30T06:15:48.410093408Z [06:15:48] [INF] [104] Dlna: No matching device profile found. The default will need to be used.,
2020-04-30T06:15:48.410133209Z DeviceDescription:,
2020-04-30T06:15:48.410145949Z FriendlyName:darkgoo,
2020-04-30T06:15:48.410156270Z Manufacturer:XBMC Foundation,
2020-04-30T06:15:48.410166360Z ManufacturerUrl:http://kodi.tv/,
2020-04-30T06:15:48.410176120Z ModelDescription:Kodi - Media Renderer,
2020-04-30T06:15:48.410185610Z ModelName:Kodi,
2020-04-30T06:15:48.410194910Z ModelNumber:18.6 Git:20200304-nogitfound,
2020-04-30T06:15:48.410204201Z ModelUrl:http://kodi.tv/,
2020-04-30T06:15:48.410212251Z SerialNumber:,
2020-04-30T06:15:48.410220111Z ,
2020-04-30T06:15:48.410227761Z [06:15:48] [INF] [104] Dlna: Profile: Generic Device, Path: Unknown path, isEligibleForDirectPlay: True, isEligibleForDirectStream: True,
2020-04-30T06:15:48.488949010Z [06:15:48] [ERR] [112] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.9.50:8096/videos/ef3084f7-8833-91f9-c9a3-c9d32268effb/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=ef3084f7883391f9c9a3c9d32268effb&Static=true&dlnaheaders=true,
2020-04-30T06:15:48.488988141Z System.ArgumentNullException: Value cannot be null. (Parameter 'path'),
2020-04-30T06:15:48.488997121Z    at MediaBrowser.Model.Net.MimeTypes.GetMimeType(String path, Boolean enableStreamDefault),
2020-04-30T06:15:48.489004731Z    at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest),
2020-04-30T06:15:48.489012271Z    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task),
2020-04-30T06:15:48.489019461Z    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken),
2020-04-30T06:15:48.489027492Z    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken),
```
