### ISSUE TITLE
Error sending content to TV via DLNA

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin#2752]
**Describe the bug**
I have used the Jellyfin application to send content to the TV, but it does not play anything, let's say it does absolutely nothing, it only shows the error in the log

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: LXC
 - Clients: Jellyfin Android app
 - Jellyfin Version: 10.5.2
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: Nginx
 - Base URL: no
 - Networking: Bridge
 - Storage: Local

**Logs**

With a audio: 

```
[2020-04-03 15:27:09.832 +02:00] [ERR] HTTP request failed with message: "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">
<errorCode>714</errorCode>
<errorDescription>Illegal mime type</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>"
[2020-04-03 15:27:09.837 +02:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean logRequest, String header)
   at Emby.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

With a video: 

```
[2020-04-03 17:47:30.494 +02:00] [ERR] HTTP request failed with message: "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">
<errorCode>705</errorCode>
<errorDescription>Transport locked</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>"
[2020-04-03 17:47:30.495 +02:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean logRequest, String header)
   at Emby.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by JustAMan** [comment]
Turn on debug logging, I think it should be possible to log DLNA stuff, right @PrplHaz4 ?

**Comment by PrplHaz4** [comment]
> Turn on debug logging, I think it should be possible to log DLNA stuff, right @PrplHaz4 ?

1. Enable Debug Logging: https://jellyfin.org/docs/general/administration/troubleshooting.html#debug-logging
2. Jellyfin Admin Dashboard -> DLNA -> Enable DLNA Debug Logging
3. Restart Jellyfin

**Comment by 97carmine** [comment]
I enclose the log, because perhaps I may miss something while reviewing.

[jellyfin.log](https://github.com/jellyfin/jellyfin/files/4456135/jellyfin.log)

**Comment by PrplHaz4** [comment]
> 
> 
> I enclose the log, because perhaps I may miss something while reviewing.
> 
> [jellyfin.log](https://github.com/jellyfin/jellyfin/files/4456135/jellyfin.log)

For the audio issue - it seems like your tv may not support FLAC.  You can try creating a  custom DLNA Profile for it so that FLAC files will be transcoded instead... https://www.displayspecifications.com/en/model/a500abb

For the video, you may want to check it with MediaInfo to make sure it's supported or try different videos to see if just this type is giving issues:

```
[2020-04-09 14:16:13.015 +02:00] [INF] User policy for "Axel Gabriel Calle Granda". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-04-09 14:16:13.016 +02:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 4278589, max bitrate: 1500000
[2020-04-09 14:16:13.016 +02:00] [INF] Profile: "Unknown Profile", Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-09 14:16:13.016 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv"
[2020-04-09 14:16:13.017 +02:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 4278589, max bitrate: 1500000
[2020-04-09 14:16:13.017 +02:00] [INF] Profile: "Unknown Profile", Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-09 14:16:13.017 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv"
[2020-04-09 14:16:13.017 +02:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 4278589, max bitrate: 1500000
[2020-04-09 14:16:13.018 +02:00] [INF] Profile: "Unknown Profile", Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2020-04-09 14:16:13.018 +02:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/Cine/Feliz Navidad (2005)/Feliz Navidad.mkv"
```

**Comment by 97carmine** [comment]
The state doing several tests, avoided the incompatible formats.

Every time I want to access the DLNA server from the TV, the TV screen turns completely black. It doesn't show or hear absolutely anything.

Now from the Android Jellyfin app the first file is a .mp3 song, after that H264 video files go.

The .mp3 song doesn't seem to show any errors, but the aforementioned happens, the screen turns completely black, it doesn't show or hear absolutely nothing.
The state doing several tests, avoided the incompatible formats.

Every time I want to access the DLNA server from the TV, the TV screen turns completely black. It doesn't show or hear absolutely anything.

Now from the Android Jellyfin app the first file is a .mp3 song, after that H264 video files go.

The .mp3 song doesn't seem to show any errors, but the aforementioned happens, the screen turns completely black, it doesn't show or hear absolutely nothing.

Regarding H264 videos, it has been tested with videos whose bitrate exceeds the DirectStream limit. In this case it directly does nothing.
With a video that does not exceed the limit, just like before, the screen turns completely black and shows absolutely nothing. But in both cases it shows the following error:

```
[2020-04-18 18:32:37.913 +02:00] [INF] [21] Dlna: Profile: "Generic Device", Path: "/mnt/Series/Violet Evergarden (2018)/Temporada 00/S00E01 - Especial.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-04-18 18:32:37.914 +02:00] [DBG] [21] Dlna: "55PUS6162/12" - Playlist created
[2020-04-18 18:32:37.915 +02:00] [DBG] [21] Dlna: "55PUS6162/12" - Playing 14 items
[2020-04-18 18:32:37.915 +02:00] [DBG] [21] Dlna: "55PUS6162/12" - SetAvTransport Uri: "http://192.168.1.6:8096/videos/240b0caf-3c32-3b01-8ee2-ce24c314050a/stream.mkv?DeviceId=uuid:1415f452-aa33-1bb3-a3c6-70af240101a8&amp;MediaSourceId=240b0caf3c323b018ee2ce24c314050a&amp;Static=true&amp;AudioStreamIndex=1&amp;SubtitleStreamIndex=10&amp;SubtitleMethod=Embed&amp;Tag=0b9ee0cb7f5a72cc1c8a9137078cbb47&amp;dlnaheaders=true" DlnaHeaders: "DLNA.ORG_PN=MATROSKA;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000"
[2020-04-18 18:32:37.923 +02:00] [ERR] [27] Emby.Server.Implementations.HttpClientManager.HttpClientManager: HTTP request failed with message: "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">
<errorCode>705</errorCode>
<errorDescription>Transport locked</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>"
[2020-04-18 18:32:37.925 +02:00] [ERR] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.6:8096/Sessions/ef998df94edbf02f9c3c4dbb28470565/Playing?ItemIds=240b0caf3c323b018ee2ce24c314050a&PlayCommand=PlayNow&MediaSourceId=240b0caf3c323b018ee2ce24c314050a&AudioStreamIndex=1&SubtitleStreamIndex=10"
MediaBrowser.Model.Net.HttpException: Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean logRequest, String header)
   at Emby.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-04-18 18:32:37.928 +02:00] [DBG] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to "http://192.168.1.6:8096/Sessions/ef998df94edbf02f9c3c4dbb28470565/Playing?ItemIds=240b0caf3c323b018ee2ce24c314050a&
```

I have tried another miniDLNA server and it works perfectly, I can access it from the TV and play the compatible files.
