### ISSUE TITLE
poster image not provided in tvdb

### ISSUE THREAD

**Issue by Alice-Schuberg** [jellyfin/jellyfin#2777]
**Describe the bug**

poster image not provided in tvdb

**System (please complete the following information):**
 - OS: [synology]
 - Virtualization: [Docker]
 - Jellyfin Version: [10.5.3]
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Host]
 - Storage: [local]

**Screenshots**

Pictured for easy understanding
[https://imgur.com/R7kfutj](https://imgur.com/R7kfutj)

**Additional context**

Bugs missing in 10.4.3
tvdb often has bugs
Is this also a tvdb problem?

**Comment by Alice-Schuberg** [comment]
[2020-04-06 05:28:22.144 +00:00] [ERR] [21] MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:1 EpisodeNumber:13]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2020-04-06 05:28:22.180 +00:00] [ERR] [21] ProviderManager: "TmdbEpisodeImageProvider" failed in GetImageInfos for type "Episode"
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.FetchMainResult(String urlPattern, String id, Int32 seasonNumber, Int32 episodeNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.DownloadEpisodeInfo(String id, Int32 seasonNumber, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeProviderBase.GetEpisodeInfo(String seriesTmdbId, Int32 season, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.TV.TmdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)

**Comment by JustAMan** [comment]
cc @Bond-009 @cvium
