### ISSUE TITLE
10.5.3 - Randomly Authentication crash with Connection Failure

### ISSUE THREAD

**Issue by saldru** [jellyfin/jellyfin#2820]
Hi everyone,

First of all, thank you for all the great job you did and you do ! 

**Describe the bug**
Since I upgraded my Jellyfin instance to 10.5.3, I get randomly disconnections from the server and the authentification system don't work anymore until I restart the jellyfin service. I happened to me 4 times now. 3 times while I was watching a video and 1 time without anyone connected on the server.

**System (please complete the following information):**
 - OS: Debian 10.3
 - Virtualization: KVM (Proxmox 6.1)
 - Clients: Web Browser
 - Browser: Firefox 75.0
 - Jellyfin Version: 10.5.3 (Based on a fresh install of 10.5.0, updated to 10.5.2 then 10.5.3)
 - Playback: Transcode HEVC to H.264 via jellyfin-ffmpeg
 - Installed Plugins: Fanart 4.0.0.0
 - Reverse Proxy: Nginx 1.17.9
 - Base URL: yes
 - Networking: Host
 - Storage: NFSv4.2

**To Reproduce**
1. Watch a video on Jellyfin via the Web Browser
2. Wait until the video stop loading
3. Refresh the page and see that you get disconnected
4. Try to sign in and see the error message : Connection Failure

**Expected behavior**
To work properly and not crash.

**Logs**
```
[2020-04-10 13:11:12.506 +02:00] [ERR] FFMpeg exited with code 1
[2020-04-10 13:11:12.902 +02:00] [ERR] Error processing request
Error: SQLitePCL.pretty.SQLiteException: cannot rollback - no transaction is active
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.RollbackTransaction(IDatabaseConnection This)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteUserDataRepository.PersistUserData(Int64 internalUserId, String key, UserItemData userData, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Data.SqliteUserDataRepository.Save
```

Thank you in advance for your time for helping to debug this issue.

**Comment by dkanada** [comment]
I don't see any reason in your installation that would cause this, but it's a database issue. We have no way of knowing why it's trying to rollback, but there isn't really a solution for this other than recreating the database right now. I haven't seen this issue before, but you can recreate the database by removing all configuration folders from your machine.

**Comment by telans** [comment]
I'm also getting this error, but noticed I was running out of disk space. I'd check that you aren't running out due to transcodes too.

**Comment by saldru** [comment]
Hi,
Actually it didn't happen again. As @telans said, it can be that. My transcoding folder is still on the root partition and this partition is only of 10GB. I updated my jellyfin instance to 10.5.4 and 10.5.5 and I don't see no issue anymore. So I think the issue was what @telans said. Thank you for your help.
