### ISSUE TITLE
Playback Error with 10.5.3

### ISSUE THREAD

**Issue by turin331** [jellyfin/jellyfin#2827]
Any video gives playback error: 
There was an issue with the client profiling and the server isn't sending a compatible media format.

Docker image through OMV Version 10.5.3
Debian Stretch with Armbian Linux 4.19.63-mvebu

```
Logs:

[2020-04-11 10:03:24.605 +00:00] [ERR] [14] App: Error in "ffprobe"
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-04-11 10:03:24.613 +00:00] [INF] [14] App: Skipping image extraction due to missing DefaultVideoStreamIndex for "/media/MoviesSeries/Movies/Comedy/Everything You Always Wanted To Know About Sex (Woody Allen 1972) XviD DVDRip.avi".
[2020-04-11 10:03:24.691 +00:00] [ERR] [14] App: Error in "ffprobe"
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Emby.Server.Implementations.Diagnostics.CommonProcess.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

```

Seems that ffmpeg path is not seen properly. ffmpeg or ffprobe binaries are not visible although there.

**Comment by turin331** [comment]
Additionally running a clean image library scanning pretty much fails and only recognized a few of the hundreds of files in the media libraries. Something seems to be wrong all the container paths.

**Comment by walkero-gr** [comment]
@turin331 I had the same problem. I fixed it by installing ffmpeg inside the container with 
`apt update && apt install ffmpeg`
Then I had to go at the configuration of Jellyfin and set the path of ffmpeg at /web/index.html#!/encodingsettings.html
ffmpeg path should be `/usr/bin/ffmpeg`

hope it helps

**Comment by turin331** [comment]
Thank you. 

That would indeed help with the playback issue. But the fact that generally the docker cannot communicate with the outside folder is a general issues. Caching for example is not done as well

**Comment by turin331** [comment]
Tried the latest version of the Docker and the issues seemed to be fixed
