### ISSUE TITLE
Firejail (Sandboxed) Browser - Cannot login to Jellyfin server

### ISSUE THREAD

**Issue by kaypeter87** [jellyfin/jellyfin#2836]
**Describe the bug**
When using a sandbox browser (firejail), I am not able to log in to the jellyfin server and receive an error: Connection Failure: We're unable to connect to the selected server right now. Please ensure it is running and try again. Judging by the logs, it doesn't seem to pass credentials properly.

 - OS: [Arch Linux]
 - Virtualization: [Proxmox KVM/Qemu]
 - Clients: [Browser - Firefox (Firejail Sandbox)]
 - Browser: [Firefox 75.0-1]
 - Jellyfin Version: [10.5.3-1]
 - Reverse Proxy: [haproxy]
 - Networking: [Host]
 - Storage: [local for server, CIFS for libraries]

**To Reproduce**
1. Install firejail
2. Launch browser sand-boxed with firejail
3. Go to jellyfin webaddress and attempt to login
4. See error (Connection Failure: We're unable to connect to the selected server right now. Please ensure it is running and try again.)

**Expected behavior**
Able to login with user.

**Logs**

From browser console:
```
error opening web socket: Error: Cannot open web socket without access token. apiclientcore.js:363:21
    ensureWebSocket https://jelly.local.theengineeringbay.com/web/libraries/apiclient/apiclientcore.js?v=10.5.2:363
    onAppResume https://jelly.local.theengineeringbay.com/web/components/appRouter.js?v=10.5.2:320
    trigger https://jelly.local.theengineeringbay.com/web/libraries/apiclient/events.js?v=10.5.2:26
    trigger https://jelly.local.theengineeringbay.com/web/libraries/apiclient/events.js?v=10.5.2:25
    onAppVisible https://jelly.local.theengineeringbay.com/web/components/apphost.js?v=10.5.2:198
```

From the server logs:
```
[2020-04-11 13:26:53.370 -04:00] [ERR] [39] Emby.Server.Implementations.Library.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2020-04-11 13:26:53.377 -04:00] [INF] [39] Emby.Server.Implementations.Library.UserManager: Authentication request for "Peter" "has been denied".
[2020-04-11 13:26:53.377 -04:00] [ERR] [39] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Session.SessionManager.GetAuthorizationToken(User user, String deviceId, String app, String appVersion, String deviceName)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by kaypeter87** [comment]
Disregard, closing this as it is not anything to do with the sandbox browser. Apologize for the confusion!
