### ISSUE TITLE
10.4.3-->10.5.4，Crash every time when scanning the media library

### ISSUE THREAD

**Issue by siyiye** [jellyfin/jellyfin#2853]
![QQ图片20200413191808](https://user-images.githubusercontent.com/35824760/79116830-0fc34300-7dbc-11ea-932b-80ecc36267d7.png)
Original version 10.4.3, now upgraded to 10.5.4.
Crash every time when scanning the media library
Where can I get the error log, I can post it to help you fix the error

**Comment by ferferga** [comment]
@siyiye What if you remove the TMDBBoxSet plugin?

This seems more a plugin issue than a server one to me. @jellyfin/triage can you move this?

**Comment by siyiye** [comment]
[2020-04-14 16:44:00.285 +08:00] [INF] Jellyfin version: "10.5.4"
[2020-04-14 16:44:00.307 +08:00] [INF] Arguments: ["*******\jellyfin\jellyfin.dll"]
[2020-04-14 16:44:00.314 +08:00] [INF] Operating system: "Windows"
[2020-04-14 16:44:00.315 +08:00] [INF] Architecture: X64
[2020-04-14 16:44:00.316 +08:00] [INF] 64-Bit Process: True
[2020-04-14 16:44:00.317 +08:00] [INF] User Interactive: True
[2020-04-14 16:44:00.317 +08:00] [INF] Processor count: 8
[2020-04-14 16:44:00.318 +08:00] [INF] Program data path: "*******\AppData\Local\jellyfin"
[2020-04-14 16:44:00.319 +08:00] [INF] Web resources path: "*******\jellyfin\jellyfin-web"
[2020-04-14 16:44:00.320 +08:00] [INF] Application directory: "*******\jellyfin\"
[2020-04-14 16:44:00.491 +08:00] [INF] Setting cache path: "*******\AppData\Local\jellyfin\cache"
[2020-04-14 16:44:00.515 +08:00] [INF] Loading assemblies
[2020-04-14 16:44:00.528 +08:00] [INF] Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "*******\Local\jellyfin\plugins\Kodi Sync Queue\Jellyfin.Plugin.KodiSyncQueue.dll"
[2020-04-14 16:44:00.531 +08:00] [INF] Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee401*******f27" from "*******\Local\jellyfin\plugins\Kodi Sync Queue\LiteDB.dll"
[2020-04-14 16:44:00.534 +08:00] [INF] Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "*******\Local\jellyfin\plugins\TMDb Box Sets\Jellyfin.Plugin.TMDbBoxSets.dll"
[2020-04-14 16:44:05.190 +08:00] [INF] Jellyfin.Plugin.KodiSyncQueue IS NOW STARTING!!!
[2020-04-14 16:44:05.192 +08:00] [INF] Creating DB Repository...
[2020-04-14 16:44:05.201 +08:00] [INF] SyncAPI Created and Listening at "/Jellyfin.Plugin.KodiSyncQueue/{UserID}/GetItems?LastUpdateDT={LastUpdateDT}&format=json" - {LastUpdateDT} must be a UTC DateTime formatted as yyyy-MM-ddTHH:mm:ssZ
[2020-04-14 16:44:05.203 +08:00] [INF] The following parameters also exist to filter the results:
[2020-04-14 16:44:05.204 +08:00] [INF] filter=movies,tvshows,music,musicvideos,boxsets
[2020-04-14 16:44:05.205 +08:00] [INF] Results will be included by default and only filtered if added to the filter query...
[2020-04-14 16:44:05.205 +08:00] [INF] the filter query must be lowercase in both the name and the items...
[2020-04-14 16:44:05.655 +08:00] [INF] Kestrel listening on all interfaces
[2020-04-14 16:44:05.760 +08:00] [INF] Running startup tasks
[2020-04-14 16:44:05.761 +08:00] [INF] Retention Task Scheduled!
[2020-04-14 16:44:05.802 +08:00] [INF] Daily trigger for "Remove Old Sync Data" set to fire at 04/15/2020 00:01, which is 7:16:54.1976327 from now.
[2020-04-14 16:44:05.808 +08:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 04/15/2020 02:00, which is 9:15:54.1917734 from now.
[2020-04-14 16:44:05.829 +08:00] [INF] Daily trigger for "Clean Transcode Directory" set to fire at 04/15/2020 03:00, which is 10:15:54.170289 from now.
[2020-04-14 16:44:05.977 +08:00] [INF] Found ffmpeg version "4.2.1"
[2020-04-14 16:44:06.134 +08:00] [INF] Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[2020-04-14 16:44:06.294 +08:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-04-14 16:44:06.302 +08:00] [INF] FFmpeg: Custom: "*******\jellyfin\ffmpeg.exe"
[2020-04-14 16:44:06.304 +08:00] [INF] ServerId: "aa55459f0e*******59d3f92"
[2020-04-14 16:44:06.402 +08:00] [INF] Executed all pre-startup entry points in 0:00:00.0888311
[2020-04-14 16:44:06.403 +08:00] [INF] Core startup complete
[2020-04-14 16:44:06.405 +08:00] [INF] LibrarySyncNotification Startup...
[2020-04-14 16:44:06.406 +08:00] [INF] UserSyncNotification Startup...
[2020-04-14 16:44:06.635 +08:00] [INF] Executed all post-startup entry points in 0:00:00.2301229
[2020-04-14 16:44:06.636 +08:00] [INF] Startup complete 0:00:06.5534328
[2020-04-14 16:44:08.822 +08:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2020-04-14 16:44:08.824 +08:00] [INF] Queueing task "PluginUpdateTask"
[2020-04-14 16:44:08.828 +08:00] [INF] Executing "Update Plugins"
[2020-04-14 16:44:09.247 +08:00] [INF] WS "http://****************************"
[2020-04-14 16:44:30.401 +08:00] [INF] Starting Library Sync...
[2020-04-14 16:44:30.418 +08:00] [INF] "LIBRARYSYNC" Added 0 items:  ""
[2020-04-14 16:44:30.441 +08:00] [FTL] Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by Artiume** [comment]
Uninstall your plugins

**Comment by dkanada** [comment]
Has this been resolved on the latest version?
