### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'resolvedUser')

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin#2884]
**Describe the bug**
After updating to Windows 10 version 1909 and two reboots, Jellyfin complains that it cannot contact the server when trying to login. 

**System (please complete the following information):**
 - OS: Win 10 Pro, version 1909, OS build 18363.778
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.3 (upgrade från 10.5.2), problem persisted upon upgrading to 10.5.4
 - Playback: N/A
 - Installed Plugins: Playback Reporting, Slack Notifications
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local for all intents and purposes: normal directories, rar2fs-mounted directories and sshfs mounted directories, all presensting as local directories to Windows

**To Reproduce**
Don't know how to reproduce

**Expected behavior**
Jellyfin surviving reboots

**Logs**
```
[2020-04-15 15:45:52.733 +02:00] [ERR] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
[2020-04-15 15:45:56.738 +02:00] [ERR] [33] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.ArgumentNullException: Value cannot be null. (Parameter 'resolvedUser')
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**
Missed screenshotting the web ui error message upon login, but something along the line "Cannot contact the Jellyfin server"

**Additional context**
- Stopping Jellyfin from tray and starting jellyfin.exe manually prompted new installation wizard, upon which I was able to recreate the admin user and login. Trying to set the Jellyfin server name from the admin dashboard\General presented error that it was unable to save settings, try again later. 
- Upon closing jellyfin.exe and starting via tray again, same error message and problem persisted.
- Upgraded to 10.5.4 in hopes to solve the problem, problem persisted
- Ran uninstaller and chose not to retain data, reinstalled, problem persisted
- Ran uninstaller and chose not to retain data, noticed folders and files in %appdata%\local\jellyfin were still there. Manually deleted these and installed 10.5.4. Was able to go through installation wizard without problem and confirmed being able to login after stopping and starting Jellyfin again from tray.
- Problem with being unable to save Jellyfin server name persisted, logs stated
`[2020-04-15 15:59:26.717 +02:00] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "C:\Users\magnu\AppData\Local\Jellyfin\metadata does not exist". URL: "http://home.direktoratet.se:8096/System/Configuration"`
- Upon creating the metadata directory manually I was able to save the Jellyfin server name and now everything seems working again. 

I posted a not-so-different bug report a couple of days ago regarding Jellyfins ability to retain directory access and/or removing old directories completely when uninstalling (https://github.com/jellyfin/jellyfin-server-windows/issues/21).

**Comment by Bond-009** [comment]
Did you clear your browser cache?

**Comment by Thijzer** [comment]
Same here.

UI message
```
Connection Failure
We're unable to connect to the selected server right now. Please ensure it is running and try again.
```

logs 
```
[07:27:59] [WRN] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 78.47.169.191. Time (slow): 0:00:09.446365. http://xxx/web/bundle.js?v=10.5.4
[07:28:36] [ERR] [34] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://xxx/Users/authenticatebyname
System.ArgumentNullException: Value cannot be null. (Parameter 'resolvedUser')

```

This happens during first time login for me after the wizard.

I'm running on a pi4

**Comment by Thijzer** [comment]
I'm gonna guess here, the calls are forced http in the logs, while I'm on https.
That looks like an issue to me.
I'll try to open the port and connect locally

**Comment by Thijzer** [comment]
nope, same error locally on http, I did a fresh install and now my issue is gone

**Comment by Spilarix** [comment]
Probably related to issue #2941

**Comment by Stampede10343** [comment]
I saw this same issue when updating from 10.5 to 10.6, then reverting to 10.5.

On linux (docker). Sounds like some kind of migration issue, sticking with 10.6 for now works fine.

**Comment by icksky** [comment]
@Stampede10343 I have the same problem with you. Because I can not install `KodiSyncQueue` so I chose to downgrade to 10.5.5.
I solved this by removing `old` from file name which file's name with `old` in `/path to jellyfin/config/data/data`. such as rename `config/data/data/users.db.old` to `config/data/data/users.db`. **maybe you should backup `config/data/data/users.db` first**.
don't forget move `logging.old.json` to `logging.default.json` in `/path to jellyfin/config`
After this process you may encounter some problems, such as you can't enter the `console`. Just clear browser cache and refresh.
