### ISSUE TITLE
Unable to connect to local and remote access

### ISSUE THREAD

**Issue by gotton** [jellyfin/jellyfin#2905]
**Describe the bug**
Jellyfin server doesn't work anymore. Worked perfectly for one week. Everything was set up.
When i tried to access on 192.168.1.**:8096 the webpage stay blank and refuse to charge jellyfin.

But this is not the same as i restart the service because then the webpage says that the page couldn't be found.

Looking at the log it's as to do with some user ID.
No client can identified or connect to the server. I tried with multiple account to connect but it can't find the server.

**System (please complete the following information):**
 - OS: Ubuntu Server
 - Clients: Firefox, android
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: last 
 - Installed Plugins: opensubtitles
 - Reverse Proxy: apache reverse proxy
 - Storage: local

**Logs**

[2020-04-17` 17:14:58.944 +02:00] [INF] UserSyncNotification Startup...
[2020-04-17 17:14:59.070 +02:00] [ERR] Connection id ""0HLV2S8C0S2PG"", Request id ""0HLV2S8C0S2PG:00000001"": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean cre$
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Emby.Server.Implementations.ApplicationHost.ExecuteWebsocketHandlerAsync(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 `application)`

thanks for the help.

EDIT :
Any time i tried to connect to the local or remote server (refreshing the page on firefox for exemple) i get the same error : 

`[2020-04-17 18:49:02.552 +02:00] [ERR] Connection id ""0HLV2TI1DF4H8"", Request id ""0HLV2TI1DF4H8:00000002"": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean cre$
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)`

Except for the connection ID and the request ID that change

**Comment by Artiume** [comment]
What browser are you using and have you tried clearing the browser cache?

**Comment by gotton** [comment]
I'm using firefox, safari or chrome. None of them work.
I cleared the cache yes. But still the same.

**Comment by Artiume** [comment]
So it shouldn't be the problem but try removing the subtitles plugin

**Comment by gotton** [comment]
How can i do it without accessing the web interface ?
I must also say that i'm using kodi sync queue.

**Comment by Artiume** [comment]
in your jellyfin rootfolder, there should be a `plugins` folder. The dll's for the plugins should be in there

**Comment by Artiume** [comment]
> And it was working fine with both the addons this week...

weird.

> The route template separator character '/' cannot appear consecutively.

@MrTimscampi What do you think of this?

**Comment by gotton** [comment]
I googled my issue and i found this : 
[https://github.com/IdentityServer/IdentityServer4/issues/2124](url)

We were using our own Implementation for LDAP Authentication ... and we had to set the 'SecurityStamp' property on the 'IdentityUser' ..
That seems to fixed the issue for us.

Don't know if it speaking to you...

**Comment by gotton** [comment]
Ok we can close this bug as i removed and purged jellyfin and reinstall it completely.

I've no longer this issue for now.

**Comment by gh7531** [comment]
As far as I can tell I have got the same error on my instance today.

`jellyfin      | [19:44:48] [ERR] [13] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLVKA5MIF5GU", Request id "0HLVKA5MIF5GU:00000002": An unhandled exception was thrown by the application.
jellyfin      | Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
jellyfin      |    at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
jellyfin      |    at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
jellyfin      |    at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean createInertEndpoints)
jellyfin      |    at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
jellyfin      |    at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
jellyfin      |    at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
jellyfin      |    at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
jellyfin      |    at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
jellyfin      |    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
jellyfin      |    at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
jellyfin      |    at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
jellyfin      |    at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
jellyfin      |    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
jellyfin      |    at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
jellyfin      |    at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
jellyfin      |    at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
jellyfin      |    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
jellyfin      | --- End of stack trace from previous location where exception was thrown ---
jellyfin      |    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
jellyfin      |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin      |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin      |    at Emby.Server.Implementations.ApplicationHost.ExecuteWebsocketHandlerAsync(HttpContext context, Func`1 next)
jellyfin      |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfin      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`

I used the fix by @gotton and also purged everything than it worked again.

**Comment by gotton** [comment]
ok its not really a fix... ahah.

i have think to another fixe but as i dont have this issue anymore : 

try to remove the httpclient folder that mat je confusing jellyfin. I reinstall evrything After i backed UP all important things from jellyfin and i got an issue with this folder. 

i just removed it and its worked fine.

for the next one...
