### ISSUE TITLE
SSDP log spam from SsdpCommunicationsServer.SendFromSocket

### ISSUE THREAD

**Issue by Zopieux** [jellyfin/jellyfin#2907]
**Describe the bug**

Looking at the 159 MB (!) daily logs produced by my Jellyfin, 99% of them are non-actionable SSDP errors:

```
[2020-04-16 00:05:48.205 +02:00] [ERR] Error sending socket message from "10.42.0.10" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

Where `10.42.0.010` is an internal IP address exposed by my [Wireguard](https://www.wireguard.com/) virtual network iface:

```
7: wg: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.42.0.10/24 scope global wg
       valid_lft forever preferred_lft forever
```

**System (please complete the following information):**
 - OS: NixOS (Linux)
 - Virtualization: none
 - Jellyfin Version: 10.4.3
 - Networking: host (no virt)

**To Reproduce**

DLNA settings (SSDP is part of the DLNA stack): 
![image](https://user-images.githubusercontent.com/81353/79624951-b04f9500-8125-11ea-8daa-ffc2412ac8f6.png)

**Expected behavior**
SSDP works (it does!) without spamming 159 MB of error messages to the logs.

**Logs**
```
[2020-04-16 00:05:48.205 +02:00] [ERR] Error sending socket message from "10.42.0.10" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (0xFFFFFFFF): Unknown error -1
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

**Comment by PrplHaz4** [comment]
Sounds like Jellyfin is attempting to send on all available interfaces and its failing because wg is there. If you bind to a single ip do you get the same log ?

**Comment by BaronGreenback** [comment]
Changes on #2986 may help if it's accepted

**Comment by BaronGreenback** [comment]
From 10.6 you should be able to exclude the interface by enclosing its IP address in [] in the LAN settings. eg. [10.42.0.10] will tell the system to ignore that interface.
