### ISSUE TITLE
Main page does not opening

### ISSUE THREAD

**Issue by boingo-00** [jellyfin/jellyfin#3003]
**Describe the bug**
I don't know why, but i can't even open main page. Nothing is updated, nothing changed since it worked fine

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: no
 - Clients: any
 - Browser: any
 - Jellyfin Version:10.5.4
 - Reverse Proxy: nginx, but direct access also not working
 - Base URL: none
 - Networking: LAN
 - Storage: local

**To Reproduce**
1. open instance

**Expected behavior**
Main page

**Logs**
While i try to open main page:
```[16:42:58] [ERR] Error processing request. URL: http://192.168.88.10:8096/users/public
System.ArgumentException: netmask
   at System.Net.IPNetwork.InternalParse(Boolean tryParse, String ipaddress, String netmask, IPNetwork& ipnetwork)
   at System.Net.IPNetwork.InternalParse(Boolean tryParse, String network, ICidrGuess cidrGuess, IPNetwork& ipnetwork)
   at Emby.Server.Implementations.Networking.NetworkManager.IsAddressInSubnets(IPAddress address, String addressString, String[] subnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInLocalNetworkInternal(String endpoint, Boolean resolveHost)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInLocalNetwork(String endpoint)
   at MediaBrowser.Api.UserService.Get(GetUsers request, Boolean filterByDevice, Boolean filterByNetwork)
   at MediaBrowser.Api.UserService.Get(GetPublicUsers request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)```

**Comment by boingo-00** [comment]
Updated to 10.5.5-1, nothing changed

**Comment by Artiume** [comment]
Can you try 10.5.0 and 10.4.3 to see if it's a regression issue

**Comment by boingo-00** [comment]
I can't, because in repo only last version
I tried to remove package and install deb from site, but…
```[16:35:38] [FTL] Error while starting server.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[16:35:38] [INF] Disposing CoreAppHost
[16:35:38] [FTL] Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)```

**Comment by boingo-00** [comment]
Fixed by reinstalling with config purging
