### ISSUE TITLE
Metadata and Catalog

### ISSUE THREAD

**Issue by Jose197n** [jellyfin/jellyfin#3005]
Hello,
I have installed Jellyfin on Centos 7.7, Ubuntu 18.04 and 19.04 several times and it still doesn't work well. It does not download metadata and the plugin catalog never loads. I think it is a bug.

When I activate the metadata download it is never downloaded. Also the second thing I saw is that when activating the advanced option of dividing a movie into chapters, it also gets corrupted and in the movie menu only one movie appears and the others disappear.

A year ago I was able to use Jellyfin correctly and did not have these problems.
I am reinstalling again. Then I take photos of the logs if needed.

I would like to confirm if this is a bug with you. At the time of installation I tried with docker, repository and rpm. Installed all updates and .net core.

Among the errors in the operand parser I saw that it said there was an error with the key. There was also another one for the security certificate. Also in the index.html it gave an error on line 1 <! DOCTYPE html>

By any chance you know of a stable version of Jellyfin maybe old but that does not have these errors. The one I used at the time did not save the version.

Thank you for reading.

**Comment by Jose197n** [comment]
[2020-04-28 19:38:46.777 -07:00] [INF] Jellyfin version: "10.5.5"
[2020-04-28 19:38:46.913 -07:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2020-04-28 19:38:46.921 -07:00] [INF] Operating system: "Linux"
[2020-04-28 19:38:46.922 -07:00] [INF] Architecture: X64
[2020-04-28 19:38:46.923 -07:00] [INF] 64-Bit Process: True
[2020-04-28 19:38:46.923 -07:00] [INF] User Interactive: True
[2020-04-28 19:38:46.923 -07:00] [INF] Processor count: 4
[2020-04-28 19:38:46.923 -07:00] [INF] Program data path: "/var/lib/jellyfin"
[2020-04-28 19:38:46.923 -07:00] [INF] Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web"
[2020-04-28 19:38:46.923 -07:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2020-04-28 19:38:47.165 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:38:47.220 -07:00] [INF] Loading assemblies
[2020-04-28 19:38:49.721 -07:00] [WRN] No users, creating one with username "jellyfin"
[2020-04-28 19:38:50.827 -07:00] [INF] Saving system configuration
[2020-04-28 19:38:50.833 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:38:51.743 -07:00] [INF] Marking all known migrations as applied because this is a fresh install
[2020-04-28 19:38:51.776 -07:00] [INF] Kestrel listening on all interfaces
[2020-04-28 19:38:51.945 -07:00] [WRN] No XML encryptor configured. Key {5418ffdb-2957-4b45-a371-4a852af037da} may be persisted to storage in unencrypted form.
[2020-04-28 19:38:52.008 -07:00] [INF] Running startup tasks
[2020-04-28 19:38:52.023 -07:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 04/29/2020 02:00, which is 6:21:07.9765171 from now.
[2020-04-28 19:38:52.144 -07:00] [INF] Found ffmpeg version "4.2.1"
[2020-04-28 19:38:52.185 -07:00] [INF] Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
[2020-04-28 19:38:52.207 -07:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-04-28 19:38:52.208 -07:00] [INF] FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2020-04-28 19:38:52.210 -07:00] [INF] ServerId: "e8d755f010f647e6adc0f1c4ec7e707c"
[2020-04-28 19:38:52.516 -07:00] [INF] Executed all pre-startup entry points in 0:00:00.2904438
[2020-04-28 19:38:52.516 -07:00] [INF] Core startup complete
[2020-04-28 19:38:52.665 -07:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "69.30.234.44"
[2020-04-28 19:38:53.038 -07:00] [INF] Executed all post-startup entry points in 0:00:00.5217975
[2020-04-28 19:38:53.039 -07:00] [INF] Startup complete 0:00:06.9754821
[2020-04-28 19:38:55.036 -07:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2020-04-28 19:38:55.043 -07:00] [INF] Queueing task "PluginUpdateTask"
[2020-04-28 19:38:55.058 -07:00] [INF] Executing "Update Plugins"
[2020-04-28 19:40:35.241 -07:00] [INF] "Update Plugins" Cancelled after 1 minute(s) and 40 seconds
[2020-04-28 19:40:35.335 -07:00] [INF] ExecuteQueuedTasks
[2020-04-28 19:40:38.739 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:15.0648496. "http://69.30.234.44:8096/web/bundle.js?v=10.5.5"
[2020-04-28 19:40:41.295 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:40:57.329 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:40:57.520 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:40:57.570 -07:00] [INF] Saving system configuration
[2020-04-28 19:40:57.571 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:40:58.154 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:41:07.413 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:00.5389189. "http://69.30.234.44:8096/web/components/playback/playbackmanager.js?v=10.5.5"
[2020-04-28 19:41:21.461 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:17.2143156. "http://69.30.234.44:8096/web/bundle.js?v=10.5.5"
[2020-04-28 19:41:24.750 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:00.474 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:07.680 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:00.8894272. "http://69.30.234.44:8096/web/6d1baa4104fc303c312def13f9cf7d12.woff2"
[2020-04-28 19:42:26.936 -07:00] [WRN] HTTP Response 204 to "45.239.123.11". Time (slow): 0:00:01.1969718. "http://69.30.234.44:8096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Pel%C3%ADculas"
[2020-04-28 19:42:29.518 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:49.174 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:49.373 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:49.385 -07:00] [INF] Saving system configuration
[2020-04-28 19:42:49.394 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:42:51.880 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:51.896 -07:00] [INF] Saving system configuration
[2020-04-28 19:42:51.899 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:42:53.890 -07:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Access token is required."
[2020-04-28 19:42:53.893 -07:00] [INF] Saving system configuration
[2020-04-28 19:42:53.902 -07:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-04-28 19:42:53.905 -07:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2020-04-28 19:42:53.906 -07:00] [INF] Executing "Scan Media Library"
[2020-04-28 19:42:53.919 -07:00] [INF] Validating media library
[2020-04-28 19:42:55.307 -07:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 1 seconds
[2020-04-28 19:42:55.309 -07:00] [INF] ExecuteQueuedTasks
[2020-04-28 19:42:55.339 -07:00] [INF] Watching directory /media
[2020-04-28 19:42:57.485 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:00.7117658. "http://69.30.234.44:8096/web/libraries/apiclient/apiclientcore.js?v=10.5.5"
[2020-04-28 19:42:59.172 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:00.7206875. "http://69.30.234.44:8096/web/components/playback/playbackmanager.js?v=10.5.5"
[2020-04-28 19:43:13.486 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:17.8731644. "http://69.30.234.44:8096/web/bundle.js?v=10.5.5"
[2020-04-28 19:44:18.692 -07:00] [INF] Authentication request for "admin" "has succeeded".
[2020-04-28 19:44:18.734 -07:00] [INF] Creating new access token for user e19ac86a-a830-4c79-97ea-dde66dcd4af5
[2020-04-28 19:44:19.200 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:01.0570489. "http://69.30.234.44:8096/Users/authenticatebyname"
[2020-04-28 19:44:19.587 -07:00] [INF] WS "http://69.30.234.44:8096/socket?api_key=0630b2a40ecd4f0e815ace7475591e37&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvODAuMC4zOTg3LjE2MyBTYWZhcmkvNTM3LjM2IE9QUi82Ny4wLjM1NzUuMTM3fDE1ODgxMjgwMjA0MjQ1". UserAgent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137"
[2020-04-28 19:44:30.124 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:04.3031834. "http://69.30.234.44:8096/Playback/BitrateTest?Size=500000"
[2020-04-28 19:44:32.476 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:06.4469382. "http://69.30.234.44:8096/Playback/BitrateTest?Size=1000000"
[2020-04-28 19:44:35.345 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:09.0350033. "http://69.30.234.44:8096/Playback/BitrateTest?Size=3000000"
[2020-04-28 19:47:40.631 -07:00] [INF] Executing "Scan Media Library"
[2020-04-28 19:47:40.641 -07:00] [INF] Stopping directory watching for path "/media"
[2020-04-28 19:47:40.643 -07:00] [INF] Validating media library
[2020-04-28 19:47:42.035 -07:00] [ERR] ffmpeg image extraction failed for file:"/media/Shin Chan El pequeÃ±o samurÃ¡i/Shin Chan El pequeÃ±o samurÃ¡i.mkv"
[2020-04-28 19:47:42.037 -07:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/media/Shin Chan El pequeÃ±o samurÃ¡i/Shin Chan El pequeÃ±o samurÃ¡i.mkv\""
System.Exception: ffmpeg image extraction failed for file:"/media/Shin Chan El pequeÃ±o samurÃ¡i/Shin Chan El pequeÃ±o samurÃ¡i.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
[2020-04-28 19:47:42.226 -07:00] [ERR] ffmpeg image extraction failed for file:"/media/Shin Chan El pequeÃ±o samurÃ¡i/Shin Chan El pequeÃ±o samurÃ¡i.mkv"
[2020-04-28 19:47:42.228 -07:00] [ERR] Error in "Screen Grabber"
System.Exception: ffmpeg image extraction failed for file:"/media/Shin Chan El pequeÃ±o samurÃ¡i/Shin Chan El pequeÃ±o samurÃ¡i.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.VideoImageProvider.GetVideoImage(Video item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, LibraryOptions libraryOptions, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
[2020-04-28 19:48:54.335 -07:00] [INF] Logging out access token "0630b2a40ecd4f0e815ace7475591e37"
[2020-04-28 19:48:56.592 -07:00] [ERR] Error processing request: "Access token is required". URL: "http://69.30.234.44:8096/ScheduledTasks?IsEnabled=true"
[2020-04-28 19:48:58.035 -07:00] [INF] Authentication request for "admin" "has succeeded".
[2020-04-28 19:48:58.036 -07:00] [INF] Creating new access token for user e19ac86a-a830-4c79-97ea-dde66dcd4af5
[2020-04-28 19:48:58.721 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:01.7448305. "http://69.30.234.44:8096/Users/authenticatebyname"
[2020-04-28 19:48:58.841 -07:00] [ERR] Error processing request: "Access token is required". URL: "http://69.30.234.44:8096/ScheduledTasks?IsEnabled=true"
[2020-04-28 19:48:59.020 -07:00] [ERR] Error processing request: "Access token is required". URL: "http://69.30.234.44:8096/ScheduledTasks?IsEnabled=true"
[2020-04-28 19:48:59.094 -07:00] [INF] WS "http://69.30.234.44:8096/socket?api_key=78770e178f6741da83d3a36aa6a40e43&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvODAuMC4zOTg3LjE2MyBTYWZhcmkvNTM3LjM2IE9QUi82Ny4wLjM1NzUuMTM3fDE1ODgxMjgwMjA0MjQ1". UserAgent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137"
[2020-04-28 19:49:12.246 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:00.7277846. "http://69.30.234.44:8096/web/controllers/itemdetailpage.js?v=10.5.5"
[2020-04-28 19:49:13.567 -07:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 192000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "mp3,aac,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a,m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma,webm", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "VP8", Type: Video }, DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "VP9", Type: Video }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "mp3,aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "mp3,aac,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline|high 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2020-04-28 19:49:14.295 -07:00] [ERR] ffmpeg image extraction failed for file:"/media/Shin Chan y el chuletÃ³n imposible/Shin Chan y el chuletÃ³n imposible.mkv"
[2020-04-28 19:49:14.295 -07:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/media/Shin Chan y el chuletÃ³n imposible/Shin Chan y el chuletÃ³n imposible.mkv\""
System.Exception: ffmpeg image extraction failed for file:"/media/Shin Chan y el chuletÃ³n imposible/Shin Chan y el chuletÃ³n imposible.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
[2020-04-28 19:49:14.416 -07:00] [ERR] ffmpeg image extraction failed for file:"/media/Shin Chan y el chuletÃ³n imposible/Shin Chan y el chuletÃ³n imposible.mkv"
[2020-04-28 19:49:14.417 -07:00] [ERR] Error in "Screen Grabber"
System.Exception: ffmpeg image extraction failed for file:"/media/Shin Chan y el chuletÃ³n imposible/Shin Chan y el chuletÃ³n imposible.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.VideoImageProvider.GetVideoImage(Video item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, LibraryOptions libraryOptions, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
[2020-04-28 19:49:22.903 -07:00] [INF] "Scan Media Library" Cancelled after 1 minute(s) and 42 seconds
[2020-04-28 19:49:22.905 -07:00] [INF] Watching directory /media
[2020-04-28 19:49:22.917 -07:00] [INF] ExecuteQueuedTasks
[2020-04-28 19:49:23.635 -07:00] [WRN] HTTP Response 200 to "45.239.123.11". Time (slow): 0:00:01.0899726. "http://69.30.234.44:8096/web/6d1baa4104fc303c312def13f9cf7d12.woff2"
[2020-04-28 19:49:46.049 -07:00] [ERR] Error processing request: "The operation was canceled". URL: "http://69.30.234.44:8096/Packages?PackageType=UserInstalled"
[2020-04-28 19:49:46.050 -07:00] [WRN] HTTP Response 500 to "45.239.123.11". Time (slow): 0:01:40.0048826. "http://69.30.234.44:8096/Packages?PackageType=UserInstalled"
[2020-04-28 19:50:19.444 -07:00] [INF] Executing "Scan Media Library"
[2020-04-28 19:50:19.445 -07:00] [INF] Stopping directory watching for path "/media"
[2020-04-28 19:50:19.446 -07:00] [INF] Validating media library
[2020-04-28 19:50:55.096 -07:00] [ERR] Error processing request: "The operation was canceled". URL: "http://69.30.234.44:8096/Items/2509af76bcbeb47a252a770b658764ca/PlaybackInfo?UserId=e19ac86aa8304c7997eadde66dcd4af5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=1500000"
[2020-04-28 19:50:55.097 -07:00] [WRN] HTTP Response 500 to "45.239.123.11". Time (slow): 0:01:41.562485. "http://69.30.234.44:8096/Items/2509af76bcbeb47a252a770b658764ca/PlaybackInfo?UserId=e19ac86aa8304c7997eadde66dcd4af5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=1500000"
[2020-04-28 19:52:00.599 -07:00] [INF] Watching directory /media
[2020-04-28 19:52:00.599 -07:00] [INF] "Scan Media Library" Cancelled after 1 minute(s) and 41 seconds
[2020-04-28 19:52:00.603 -07:00] [INF] ExecuteQueuedTasks

**Comment by blackjack4494** [comment]
I am having similar Issues but I am on Win10. The last item I could successfully add where metadata is downloaded (at all!) was on the 12th this month. But for some reason it won't pull any metadata at all anymore. Is there some problems with apis?
