### ISSUE TITLE
Latest Github - Clean install startup wizard fails

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3012]
Deleted jellyfin profile and started app.

Hangs on setting up Jellyfin setup wizard. No items in the drop down box - with the waiting swirl.

Traced to 
AuthServices.cs IsExemptFromRoles is failing as AllowBeforeStartupWizard (ConfigurationServices.cs) is not true.

**Comment by Bond-009** [comment]
Pretty sure this got fixed, can you test again?

**Comment by BaronGreenback** [comment]
Wiped and started again. Drop down box worked the first time.

Wiped and started it a second time, and nothing was populated. Reopening the browser does the same thing.

1st error is on UserViewManager.cs line 53 - User Id specified doesn't exist.

Query Parameter is

◢ | query | {MediaBrowser.Model.Library.UserViewQuery} | MediaBrowser.Model.Library.UserViewQuery
  | IncludeExternalContent | true | bool
  | IncludeHidden | false | bool
  | PresetViews | {string[0x00000000]} | string[]
  | ▶ UserId | {9217174e-fd5c-4dbf-acc6-e3b69f6455d1} | System.Guid

Then it fails with:

System.ArgumentException
  HResult=0x80070057
  Message=User Id specified in the query does not exist. (Parameter 'query')
  Source=Emby.Server.Implementations
  StackTrace:
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query) in C:\code\Jellyfin\Emby.Server.Implementations\Library\UserViewManager.cs:line 56
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request) in C:\code\Jellyfin\MediaBrowser.Api\UserLibrary\UserViewsService.cs:line 98
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 97
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceController.cs:line 189
   at Emby.Server.Implementations.Services.ServiceHandler.<ProcessRequestAsync>d__6.MoveNext() in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    Emby.Server.Implementations.Library.UserViewManager.GetUserViews(MediaBrowser.Model.Library.UserViewQuery) in UserViewManager.cs
    MediaBrowser.Api.UserLibrary.UserViewsService.Get(MediaBrowser.Api.UserLibrary.GetUserViews) in UserViewsService.cs
    Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(System.Type, MediaBrowser.Model.Services.IRequest, object, object, string) in ServiceExec.cs
    Emby.Server.Implementations.Services.ServiceController.Execute(Emby.Server.Implementations.HttpServer.HttpListenerHost, object, MediaBrowser.Model.Services.IRequest) in ServiceController.cs
    Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(Emby.Server.Implementations.HttpServer.HttpListenerHost, MediaBrowser.Model.Services.IRequest, Microsoft.AspNetCore.Http.HttpResponse, Microsoft.Extensions.Logging.ILogger, System.Threading.CancellationToken) in ServiceHandler.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by BaronGreenback** [comment]
Also when I refresh on the page the url becomes extended

http://localhost:8096/web/index.html?start=wizard#!/wizardstart.html?start=wizard?start=wizard?start=wizard?start=wizard?start=wizard

**Comment by BaronGreenback** [comment]
Logs

[2020-06-24 15:37:19.789 +01:00] [ERR] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:37:20.014 +01:00] [ERR] [21] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
MediaBrowser.Controller.Authentication.AuthenticationException: Access token is invalid or expired.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 238
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 61
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 50
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in C:\code\Jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 45
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2020-06-24 15:37:20.085 +01:00] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:37:20.406 +01:00] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1/Views"
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query) in C:\code\Jellyfin\Emby.Server.Implementations\Library\UserViewManager.cs:line 56
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request) in C:\code\Jellyfin\MediaBrowser.Api\UserLibrary\UserViewsService.cs:line 98
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 97
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceController.cs:line 189
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 82
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 489
[2020-06-24 15:37:20.411 +01:00] [WRN] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 400 to "::1". Time (slow): 0:00:00.7807405. "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1/Views"
[2020-06-24 15:37:20.631 +01:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-06-24 15:37:20.635 +01:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "PluginUpdateTask"
[2020-06-24 15:37:20.644 +01:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2020-06-24 15:37:24.512 +01:00] [INF] [18] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:Sharp_TV (74:72:b0:76:e2:a9)
Manufacturer:MStar
ManufacturerUrl:www.mstarsemi.com
ModelDescription:MStar Digital Media Renderer
ModelName:MStarDMR
ModelNumber:0.0
ModelUrl:www.mstarsemi.com
SerialNumber:000000

[2020-06-24 15:37:24.532 +01:00] [INF] [18] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "Sharp_TV (74:72:b0:76:e2:a9)" - "MStarDMR"
[2020-06-24 15:37:25.197 +01:00] [INF] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::1" request
[2020-06-24 15:37:25.208 +01:00] [WRN] [27] Emby.Server.Implementations.Session.SessionWebSocketListener: Unable to determine session based on query string: ["[api_key, 857c4bfc0e4f47f8b8c0c5835530e1a2]", "[deviceId, TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvODEuMC40MDQ0LjExMyBTYWZhcmkvNTM3LjM2fDE1ODcxMzkwODkyNTA1]"]
[2020-06-24 15:37:37.753 +01:00] [INF] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::1" closed
[2020-06-24 15:37:37.828 +01:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 17 seconds
[2020-06-24 15:37:37.931 +01:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2020-06-24 15:37:38.720 +01:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:37:38.935 +01:00] [ERR] [30] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
MediaBrowser.Controller.Authentication.AuthenticationException: Access token is invalid or expired.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 238
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 61
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 50
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in C:\code\Jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 45
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2020-06-24 15:37:38.969 +01:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1/Views"
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query) in C:\code\Jellyfin\Emby.Server.Implementations\Library\UserViewManager.cs:line 56
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request) in C:\code\Jellyfin\MediaBrowser.Api\UserLibrary\UserViewsService.cs:line 98
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 97
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceController.cs:line 189
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 82
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 489
[2020-06-24 15:37:39.039 +01:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:37:51.234 +01:00] [INF] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::1" request
[2020-06-24 15:37:51.240 +01:00] [WRN] [5] Emby.Server.Implementations.Session.SessionWebSocketListener: Unable to determine session based on query string: ["[api_key, 857c4bfc0e4f47f8b8c0c5835530e1a2]", "[deviceId, TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvODEuMC40MDQ0LjExMyBTYWZhcmkvNTM3LjM2fDE1ODcxMzkwODkyNTA1]"]
[2020-06-24 15:37:58.130 +01:00] [ERR] [10] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
MediaBrowser.Controller.Authentication.AuthenticationException: Access token is invalid or expired.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 238
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 61
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 50
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in C:\code\Jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 45
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2020-06-24 15:38:06.139 +01:00] [INF] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::1" closed
[2020-06-24 15:38:07.257 +01:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:38:07.383 +01:00] [ERR] [27] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
MediaBrowser.Controller.Authentication.AuthenticationException: Access token is invalid or expired.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 238
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 61
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 50
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in C:\code\Jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 45
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[2020-06-24 15:38:07.468 +01:00] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired". URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1"
[2020-06-24 15:38:07.476 +01:00] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/Users/9217174efd5c4dbfacc6e3b69f6455d1/Views"
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query) in C:\code\Jellyfin\Emby.Server.Implementations\Library\UserViewManager.cs:line 56
   at MediaBrowser.Api.UserLibrary.UserViewsService.Get(GetUserViews request) in C:\code\Jellyfin\MediaBrowser.Api\UserLibrary\UserViewsService.cs:line 98
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 97
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceController.cs:line 189
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 82
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 489

**Comment by BaronGreenback** [comment]
Browser is chrome.

Looking at the network responses from chrome,

Options has a list of languages

Configuration has 

MediaBrowser.Controller.Authentication.AuthenticationException: Access token is required.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 222
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 61
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes) in C:\code\Jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 50
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in C:\code\Jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 45
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by BaronGreenback** [comment]
Javascript is reporting an error 500 (Internal Server error) from http://127.0.0.1:8096/Startup/Configuration

**Comment by BaronGreenback** [comment]
rebase and recompiled latest web and issue resolved
