### ISSUE TITLE
[bug] TypeLoadException in PluginSecurityManager after upgrade from 10.5.2 to 10.5.3+

### ISSUE THREAD

**Issue by UnrealKazu** [jellyfin/jellyfin#3025]
**Describe the bug**
When I upgrade my Jellyfin instance from version 10.5.2 to 10.5.3 or later, I get a fatal exception during startup of the application. I've tested again in version 10.5.5, but the same exception is present.

I can consistently reproduce it by upgrading to 10.5.3 or later. Whenever I downgrade back to 10.5.2 everything is running again, so something in the .3 version broke my setup.

I've tested whether the issue is bound to my config by starting a clean version of Jellyfin (i.e. no config folder) at version 10.5.2, boot it, shut it down, upgrade to 10.5.3 and boot it again. This works, so no exception here. So it is clear that there is something in my specific configuration that triggers the exception, so please let me know if I can include some extra data that would make it possible for you to reproduce the bug.

Also, I could not find a way to turn on debug logging of any kind. So unfortunately I only have the info logging plus fatal logging.

**System (please complete the following information):**
 - OS: Ubuntu Server 18.04.4
 - Virtualization: Docker 19.03.5, build 633a0ea838
 - Clients: Only browsers
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.3+
 - Playback: Direct Play
 - Installed Plugins: AudioDB, MusicBrainz (I cannot seem to uninstall these in 10.5.2, btw)
 - Reverse Proxy: Traefik 2.2.0
 - Base URL: none
 - Networking: bridge
 - Storage: local

**To Reproduce**
1. Have a running container with image `jellyfin/jellyfin:10.5.2`
2. Shut down the container
3. Pull image `jellyfin/jellyfin:10.5.3` or `jellyfin/jellyfin:latest`
4. Start the container

**Expected behavior**
A proper startup sequence with a working instance of Jellyfin

**Actual behavior**
A fatal exception is logged, and the application shuts down

**Logs**
```
[12:22:46] [INF] [1] Main: Jellyfin version: 10.5.5
[12:22:46] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[12:22:46] [INF] [1] Main: Operating system: Linux
[12:22:46] [INF] [1] Main: Architecture: X64
[12:22:46] [INF] [1] Main: 64-Bit Process: True
[12:22:46] [INF] [1] Main: User Interactive: True
[12:22:46] [INF] [1] Main: Processor count: 4
[12:22:46] [INF] [1] Main: Program data path: /config
[12:22:46] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[12:22:46] [INF] [1] Main: Application directory: /jellyfin/
[12:22:46] [INF] [1] ServerConfigurationManager: Setting cache path: /cache
[12:22:46] [INF] [1] App: Loading assemblies
[12:22:46] [INF] [1] App: Loaded assembly Emby.Server.CinemaMode, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.Server.CinemaMode.dll
[12:22:46] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Method 'RunAsync' in type 'Emby.Security.PluginSecurityManager' from assembly 'Emby.Server.CinemaMode, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[12:22:46] [INF] [1] App: Disposing CoreAppHost
[12:22:46] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by crobibero** [comment]
It looks like you have an emby plugin installed. Does removing `Emby.Server.CinemaMode` fix startup?

**Comment by UnrealKazu** [comment]
The `Emby.Server.CinemaMode` plugin was not listed under `Dashboard` > `Plugins`. However, I did find a `emby.server.cinemamode.dll` file in the `plugins` folder. Deleting that and upgrading to 10.5.5 indeed fixed the issue.

I've been running Jellyfin since before it was forked, so I'm guessing this was a relict of the Emby instance after migration? It looks like I'm the only one, so I'm closing this issue. Thanks for the reply :)
