### ISSUE TITLE
DLNA stream of LiveTV still not working

### ISSUE THREAD

**Issue by frasty** [jellyfin/jellyfin#3029]
#2849 does not seem to resolve issue #2737.
This is relevant log while streaming livetv channel to a remote device via DLNA on latest jellyfin 10.5.5 running from docker container (streaming a movie via DLNA does work):
```
[06:15:48] [INF] [104] Dlna: No matching device profile found. The default will need to be used.,
 DeviceDescription:,
 FriendlyName:darkgoo,
 Manufacturer:XBMC Foundation,
 ManufacturerUrl:http://kodi.tv/,
 ModelDescription:Kodi - Media Renderer,
 ModelName:Kodi,
 ModelNumber:18.6 Git:20200304-nogitfound,
 ModelUrl:http://kodi.tv/,
 SerialNumber:,
 ,
 [06:15:48] [INF] [104] Dlna: Profile: Generic Device, Path: Unknown path, isEligibleForDirectPlay: True, isEligibleForDirectStream: True,
 [06:15:48] [ERR] [112] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.9.50:8096/videos/ef3084f7-8833-91f9-c9a3-c9d32268effb/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=ef3084f7883391f9c9a3c9d32268effb&Static=true&dlnaheaders=true,
 System.ArgumentNullException: Value cannot be null. (Parameter 'path'),
    at MediaBrowser.Model.Net.MimeTypes.GetMimeType(String path, Boolean enableStreamDefault),
    at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest),
    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task),
    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken),
    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken),

```
System

OS: Fedora Linux 31
Virtualization: no
Clients: BubbleUPNP, VLC, deoVR on android, kodi..
Jellyfin Version: 10.5.5
Installed Plugins: TVHeadend
Reverse Proxy: none
Base URL: none
Networking: Host
Storage: local
Steps to reproduce:

Expected behavior

LiveTV channel should play on any DLNA renderer.

**Comment by Artiume** [comment]
You want to turn on Force Live TV Transcoding and see if that works at all?

**Comment by frasty** [comment]
I enabled "Force transcoding of remote media sources (like LiveTV)" but I still get the same errors:

```
[2020-05-02 23:40:43.952 +00:00] [INF] [85] Dlna: No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:darkgoo
Manufacturer:XBMC Foundation
ManufacturerUrl:http://kodi.tv/
ModelDescription:Kodi - Media Renderer
ModelName:Kodi
ModelNumber:18.6 Git:20200426-nogitfound
ModelUrl:http://kodi.tv/
SerialNumber:

[2020-05-02 23:40:43.953 +00:00] [INF] [85] Dlna: Profile: "Generic Device", Path: "Unknown path", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-05-02 23:40:44.036 +00:00] [ERR] [104] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true"
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at MediaBrowser.Model.Net.MimeTypes.GetMimeType(String path, Boolean enableStreamDefault)
   at MediaBrowser.Controller.MediaEncoding.EncodingJobInfo.GetMimeType(String outputPath, Boolean enableStreamDefault)
   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by frasty** [comment]
This is the log from kodi, if it could be of any help:
```
2020-05-03 02:41:07.495 T:140134266933696  NOTICE: VideoPlayer::OpenFile: http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true
2020-05-03 02:41:07.507 T:140134266933696   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true
2020-05-03 02:41:07.507 T:140133751834368  NOTICE: Creating InputStream
2020-05-03 02:41:07.515 T:140133751834368   ERROR: CCurlFile::Open failed with code 400 for http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true:
                                            Value cannot be null. (Parameter 'path')
2020-05-03 02:41:07.522 T:140133751834368   ERROR: Previous line repeats 1 times.
2020-05-03 02:41:07.522 T:140133751834368   ERROR: Open - failed to open source <http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true>
2020-05-03 02:41:07.522 T:140133751834368   ERROR: CVideoPlayer::OpenInputStream - error opening [http://192.168.9.50:8096/videos/9c337f70-85be-213e-b91e-42d5f4717f84/stream?DeviceId=uuid:6d7a5a3b-5c9d-386e-723b-11029f151b78&MediaSourceId=9c337f7085be213eb91e42d5f4717f84&Static=true&dlnaheaders=true]
2020-05-03 02:41:07.522 T:140133751834368  NOTICE: CVideoPlayer::OnExit()
2020-05-03 02:41:07.612 T:140134266933696  NOTICE: CVideoPlayer::CloseFile()
2020-05-03 02:41:07.612 T:140134266933696  NOTICE: VideoPlayer: waiting for threads to exit
2020-05-03 02:41:07.612 T:140134266933696  NOTICE: VideoPlayer: finished waiting
```
