### ISSUE TITLE
DLNA/Chromecast failure 2.0

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#303]
Chromecasting from current master fails:

```
2018-12-28 18:20:21.294 Error HttpServer: Error processing request
        *** Error Report ***
        Version: 3.5.2.0
        Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh
        Operating system: Unix 4.9.0.8
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 6
        Program data path: /var/lib/jellyfin
        Application directory: /usr/lib/jellyfin/bin
        System.NullReferenceException: Object reference not set to an instance of an object.
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetHttpResult(IRequest requestContext, Byte[] content, String contentType, Boolean addCachePrevention, IDictionary`2 responseHeaders) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 119
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
        System.NullReferenceException
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetHttpResult(IRequest requestContext, Byte[] content, String contentType, Boolean addCachePrevention, IDictionary`2 responseHeaders) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 119
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /var/home/joshua/Projects/Emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
```

**Comment by joshuaboniface** [comment]
This is a major regression in master from build 4, so should have some top priority.

**Comment by joshuaboniface** [comment]
So this just... started working again? On the same build, for the same file. I don't understand, but OK...

**Comment by joshuaboniface** [comment]
Confirmed through further testing that I cannot replicate this any longer. #314 cleans up the NullPointerExceptions however.

**Comment by SenorSmartyPants** [comment]
Browsing from VLC works but I still can't play anything.

```
2018-12-31 13:28:42.427 Info HttpServer: HTTP GET http://192.168.1.1:8096/videos/0f176dde-055b-a74a-f694-e4763f2c51ee/stream.mkv?id=0f176dde-055b-a74a-f694-e4763f2c51ee&DeviceId=test&MediaSourceId=0f176dde055ba74af694e4763f2c51ee&Static=true&AudioStreamIndex=1&Tag=ba514e083d482ba1e31bdb1f6679e932&dlnaheaders=true. Host=192.168.1.1:8096, Connection=keep-alive, Upgrade-Insecure-Requests=1, User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, DNT=1, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8, Accept-Encoding=gzip, deflate, Accept-Language=en-US,en;q=0.9
2018-12-31 13:28:42.467 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.14.70.0
	64-Bit OS: False
	64-Bit Process: False
	User Interactive: True
	Processor count: 2
	Program data path: /config
	Application directory: /jellyfin
	System.ArgumentNullException: Value cannot be null.
	Parameter name: id
	   at Emby.Server.Implementations.Library.UserManager.GetUserById(Guid id) in /repo/Emby.Server.Implementations/Library/UserManager.cs:line 167
	   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken) in /repo/MediaBrowser.Api/Playback/BaseStreamingService.cs:line 690
	   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest) in /repo/MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs:line 121
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	System.ArgumentNullException
	   at Emby.Server.Implementations.Library.UserManager.GetUserById(Guid id) in /repo/Emby.Server.Implementations/Library/UserManager.cs:line 167
	   at MediaBrowser.Api.Playback.BaseStreamingService.GetState(StreamRequest request, CancellationToken cancellationToken) in /repo/MediaBrowser.Api/Playback/BaseStreamingService.cs:line 690
	   at MediaBrowser.Api.Playback.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest) in /repo/MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs:line 121
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
```

**Comment by LeoVerto** [comment]
Can someone test whether #378 has fixed this?

**Comment by BobOkisama** [comment]
Mine plays to my ccu, but nothing happens if you try to hit the shuffle button while connected to ccu. Disconnect from ccu and shuffle works fine.

**Comment by SenorSmartyPants** [comment]
VLC and BubbleUPNP are playing videos via DLNA in version 10.0.0

**Comment by skug67** [comment]
Weird.  It's not working for me in VLC on either Android or iOS (or BubbleUPNP or any other DLNA client I can find).  For what it's worth, I can browse the DLNA server just fine -- but when I select a show and try to play it I get nothing (see my earlier post on now closed #223 ([
https://github.com/jellyfin/jellyfin/issues/223#issuecomment-449669581](url)).  Nothing seems to have changed on my end since then.

**Comment by anthonylavado** [comment]
Okay - Chromecast is going to be working again soon (we have a fix and are working on implementation).

DLNA should then be the focus here for @skug67.

@skug67 Could you tell me what client you're using on iOS? Is it VLC then? I can try to replicate here against the latest branches.

**Comment by anthonylavado** [comment]
Update:

I've tested VLC and Infuse, both against the regularly shipping 10.0.1 release, as well as the latest dev releases, and both are working 100%.

These tests were done running on a Debian server, and running on macOS. Not using Docker, just the direct packages.

----
To everyone here:

- How do you have your system setup?
- What system is it running on?
- What version are you using? _(I recommend using the latest)._

**Comment by skug67** [comment]
Very peculiar.  I'm running the latest Debian package installed w/th apt from the repository.  I wonder if the problem may somehow relate to originally migrated from Emby back when this project went live.  I've got another virtual machine on the LAN where I can do a clean install.  And if that works then I'll apt-get purge, delete everything and reinstall.  Will let you know....

**Comment by skug67** [comment]
So... installing it on a different virtual machine in the DMZ of my LAN works fine.  But if I reinstall completely clean on the original machine.  DLNA still fails.  There were a bunch of errors like this:

[2019-01-12 12:00:26.650 -05:00] [ERR] Error in BeginListeningForBroadcasts
System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Emby.Server.Implementations.Net.UdpSocket..ctor(Socket socket, Int32 localPort, IPAddress ip) in /repo/Emby.Server.Implementation$
   at Emby.Server.Implementations.Net.SocketFactory.CreateUdpMulticastSocket(String ipAddress, Int32 multicastTimeToLive, Int32 localPo$
   at Rssdp.Infrastructure.SsdpCommunicationsServer.ListenForBroadcastsAsync() in /repo/RSSDP/SsdpCommunicationsServer.cs:line 350
   at Rssdp.Infrastructure.SsdpCommunicationsServer.BeginListeningForBroadcasts() in /repo/RSSDP/SsdpCommunicationsServer.cs:line 126

I guessed/assumed that was a port collision so first I created a dedicated interface for jellyfin to run on, then I disabled everything else using UDP 1900 even on the original interface.  That got the error listed above to disappear.  But then jellyfin just stopped appearing in any DLNA browser at all.  For now I'm running two jellyfin instances -- one on the new virtual machine (with less processing power) with DLNA enabled so local machines (TVs) can find it, and the old one (without DLNA) accessible via web (and with more processors so that smooth transcoding is possible).  I've got no idea at all what it is about other programs or my networking setup that makes the original machine fail w/DLNA.  But it's a manageable (if kludgy) workaround so I'm not too worried.

**Comment by skug67** [comment]
Interestingly.  When I went back to the new virtual machine a couple of days later DLNA once again failed to play.  While it's a "nice to have" feature in my network, I can make do with the web interface for laptops/iPads, the android Emby app via an Amazon Fire for one TV (although finishing the Jellyfin android app would be great so the Premiere nags can disappear), and Roku app for two more TVs.  Only posting here so people can be aware that on at least some network configurations it's not working quite right.....

**Comment by LeoVerto** [comment]
@skug67 DLNA relies heavily on UDP multicast for device discovery. Even if all the required ports have been forwarded, your VM networking may not support multicast forwarding properly.

When using docker, enabling host networking is pretty much required for DLNA to work, you may have to do something similar with your VM setup.

**Comment by skug67** [comment]
FWIW, my virtual hosts are KVM/QEMU with virtualized NICs.  DLNA did work fine under Emby prior to migrating to Jellyfin.  But I don't miss it enough to return to the land of paywalls and nag screens.
