### ISSUE TITLE
Mixed Content classifies any movie ending in a number as a TV show with one episode

### ISSUE THREAD

**Issue by ToxicFrog** [jellyfin/jellyfin#3074]
**Describe the bug**
If you create a Mixed Content library, it classifies most things as Movies, if they have appropriate metadata, or as raw video files, if they do not; however, any movie with a name ending in a number is instead classified as a TV series with one episode, even if it has an associated NFO file with a `<movie>` entry.

**System (please complete the following information):**
 - OS: NixOS
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.4
 - Playback: N/A
 - Installed Plugins: AudioDB, Open Subtitles, Kodi Sync Queue
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: host
 - Storage: local zfs

**To Reproduce**
Create a suitable folder structure with correctly tagged movies (i.e. if you import them into a Movie library they should show up properly), e.g.
```
Test Library/
  Kung Fu Panda/
    Kung Fu Panda (2008)/*
    Kung Fu Panda 2 (2011)/*
    Kung Fu Panda 3 (2016)/*
```
Import it as Mixed Content and browse to `Test Library` -> `Kung Fu Panda`.

Observe that KFP 2 and 3 are listed as one-episode TV shows, while KFP1 shows up properly.

**Expected behavior**
All three movies are listed as movies.

**Additional context**
"Just use library type Movies" is not a useful workaround because of #3073

**Comment by ToxicFrog** [comment]
It has been pointed out on IRC that automatically detecting whether something is a movie or a TV show is actually pretty hard, in the general case; this is true, but all of these have NFO files with proper `<movie>` blocks. I think a decent compromise would be for it to load the NFO files where present and treat anything else it finds as a plain video file without trying to do any sort of remote metadata fetch.

**Comment by ToxicFrog** [comment]
I haven't tested this on recent releases, but only because I've switched to using Photos for "bucket of video file" libraries, which isn't great.

**Comment by panguin6010** [comment]
this issue still exists :/

**Comment by DuvelCorp** [comment]
This is issue is also turning me mad. I've got a library defined as "OTHER" where I put everything that is not a Movie or a classical Show, but rather anything else that was aired on TV, or released in DVD.

Most of the things there are : 
Documentaries (ex Citizenfour, Inside Job, WW2 stuff, etc...) or funny shows (ex : monty python), oneman shows, funny hidden camera footage, etc.... It just perfectly logical to me to have a library like this.
 
This "OTHER" just doesnt work.
For most of the things that is  classified as TV on tvdb or themoviedb, it works fine. But for everything that is classified as "movie", it doesn't want to update, because it only look at series IDs and nevermovies.

SO I really dont see the point of this "Other" lib type in the actual state.
I am not asking it to find all the contain automatically, I understand this is complicated with a mixed lib content, what I am asking is that it let me Identify any content manually, and for this the very first thing to do, would be to let us specify if a specific content is categorized as MOVIE or TV in the TVDB/themoviedb 
And everything would be fine!

This is what I have on my "Other" lib identify options right now : 
![image](https://user-images.githubusercontent.com/33682764/152701256-ff3752c3-f0e7-4274-bd72-a8af26533bf0.png)
and this is the core of the problem.

**Comment by DuvelCorp** [comment]
Still struggling with this.
I removed my library
I have carefully named each folder with **{Title} (Year)**
![image](https://user-images.githubusercontent.com/33682764/152875082-94621da6-864c-4d46-b3b4-cbbc42e64d6a.png)
I have deleted all metadata previously DLed by Jellyfin in each folder.
I have  finally recreated the library with "Other" content type.
In other words, I started it all over from scratch.

Got some highly illogical things all over the place.

For instance :

> **This is it (2009)**

https://www.imdb.com/title/tt1477715/?ref_=fn_al_tt_1
https://thetvdb.com/movies/this-is-it
https://www.themoviedb.org/movie/13576-this-is-it
Can't be more acccurate. And all 3 dbs are categorizng this as "movie". 

But nevertheless, it results in this horror
![image](https://user-images.githubusercontent.com/33682764/152875605-7150bc98-c528-4409-b47d-75a72053cf01.png)

Why? Because it dumbly consider this as a **serie**. On which criteria? I don't know. 

Proof is below. When I try to force the correct imdb ID with "Identify" function, I got this :

```
[2022-02-07 22:14:11.063 +01:00] [ERR] Failed to retrieve series with remote id "tt1477715"
TvDbSharper.TvDbServerException: No records are found that match your query; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, String parameterKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
[2022-02-07 22:14:11.096 +01:00] [ERR] Failed to retrieve series with id null
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 0 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesSearchResult(SeriesInfo seriesInfo, CancellationToken cancellationToken)
[2022-02-07 22:14:11.675 +01:00] [INF] Processing playback tracker : "d8ffe7df3fd68afb57b5be4049d664c2c8ffaa3c-42efbf614c794ad58c2d483708298346-b72b47003585ecdd60f1cd0c39ca8d13"
[2022-02-07 22:14:12.143 +01:00] [WRN] Slow HTTP Response from "http://xxxx.com/xxxx/Items/RemoteSearch/Series" to "192.168.2.10" in 0:00:01.2817392 with Status Code 200
[2022-02-07 22:14:14.427 +01:00] [INF] Setting provider id's to item cbbedd97-183b-815f-3e1b-42e55ac2064a-"This Is It": "{\"Imdb\":\"tt1477715\"}"
[2022-02-07 22:14:14.461 +01:00] [ERR] Failed to retrieve series with remote id "tt1477715"
TvDbSharper.TvDbServerException: No records are found that match your query; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, String parameterKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
[2022-02-07 22:14:14.493 +01:00] [ERR] Failed to retrieve series with id null
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 0 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2022-02-07 22:14:14.499 +01:00] [INF] Processing playback tracker : "04750f94cce335b429c575ff74fc1cbb81637292-fc1db9c7bf3b444ebf0bcf61e03ac1e0-92e0eac5c31a841399c96385ee6e9d0e"
[2022-02-07 22:14:15.111 +01:00] [ERR] "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/media/plex/docus/This Is It (2009)"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2022-02-07 22:14:15.681 +01:00] [ERR] Failed to retrieve series with remote id "tt1477715"
TvDbSharper.TvDbServerException: No records are found that match your query; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, String parameterKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
[2022-02-07 22:14:15.714 +01:00] [ERR] Failed to retrieve series with id null
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 0 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2022-02-07 22:14:15.753 +01:00] [ERR] "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/media/plex/docus/This Is It (2009)"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

So it is crystal clear what the error is. 

And I have the feeling that this is something extremely easy to fix, **if only I could tell him that he has to search for a movie and not a serie** my issue would be solved right away!  But I can't, its nowhere in the interface.
 And it keep trying to grab, and failing. Even if I delete everything and try again, it keep doing the same thing. Even if edit the NFO and specify `<movie>` with correct imdb/tmdb/tvd IDs,  it keep replacing my NFO with the serie  garbage it has decided to grab :(

But the weird thing is : 
![image](https://user-images.githubusercontent.com/33682764/152877169-6a726979-a7b1-4ce0-b55a-37b5abad586f.png)
This stuff is in **Same library**, it has different content, and it match perfectly. The War series are correctly designed as a serie, and Amy is as a movie.

That's really frustrating

**Comment by ToxicFrog** [comment]
My best guess here, based on observed behaviour, is that whatever part of the Other library tries to infer tv-vs-movie happens before scraping occurs. So (based on some arcane ritual) it decides that "This is It" is a TV show, and _only then_ does it query TVDB for it, with predictably unfortunate results.

IIRC the Other library type has some scraper options, but they don't actually work for turning off scraping entirely, or prioritizing local metadata over scrape results -- the process always seems to be guess if TV or movie based on filename or something -> scrape based on that assumption -> use scrape results only and ignore local metadata.

If you just want A Bucket Of Videos without the scraper getting in the way, the Photos library type is, well, actually not that good for this, but it's _less bad_ than any other library type I've tried -- it handles both stills and videos and doesn't try to scrape anything, but doesn't seem to understand NFOs either, and it doesn't support other file types that are notionally understood by Jellyfin like audio recordings.

If you want a mixed-content library that supports both movies and TV episodes in the same library, with scraping and/or rich metadata support, Jellyfin doesn't currently have anything that fills that niche, and no-one (including me) appears to have the intersection of desire, knowledge, and free time needed to fix it. If lack of this feature is a dealbreaker for you and you can't make do with the Photos library, you may need to look into alternatives like Plex, Airsonic, or Kodi. :/

**Comment by felix920506** [comment]
According to testing by @theguymadmax this was not able to be reproduced on 10.10.6

**Comment by microfx** [comment]
Hello? Why is this not possible? This breaks so much and actually stole already countless hours of probably not only my life.
