### ISSUE TITLE
Connection Failure Following Reboot After 10.5.5 Install on Windows 7

### ISSUE THREAD

**Issue by nebulous999** [jellyfin/jellyfin#3091]
**Bug description**
Did a fresh install of Jellyfin 10.5.5, and ran the first time setup.
Everything is working as expected until the reboot.
Following the reboot, when I click Sign In, I see the error:

> ### Connection Failure
> We're unable to connect to the selected
> server right now.  Please ensure it is
> running and try again
![ConnectionFailure](https://user-images.githubusercontent.com/6912896/81513414-939e1b80-92e5-11ea-9a91-ededc583bb7c.png)

Re-installing Jellyfin corrected the issue, but then it occurred again, following the next reboot.

**System (please complete the following information):**
 - OS: Windows 7 Ultimate SP1, 64-bit
 - Virtualization: None
 - Clients: Browser, Android
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.5
 - Playback: N/A
 - Installed Plugins: ServerWMC
 - Reverse Proxy: None
 - Base URL: /web/index.html
 - Networking: localhost, Windows Firewall disabled
 - Storage: Local

**To Reproduce**

1. Download https://repo.jellyfin.org/releases/server/windows/versions/10.5.5/jellyfin_v10.5.5-x64.exe
2. Install Jellyfin as a Windows service
3. Open Jellyfin in a browser and complete the first time setup
4. Create a user
5. Set up libraries (1 with mixed content) and install plugins (ServerWMC)
6. Verify media libraries and streaming are working
7. Reboot the machine
8. Open Jellyfin, enter username/pass, and click Sign In

**Expected behavior**
The Jellyfin home page will appear following the sign in.

**Logs**
Exception from Jellyfin log:
> [2020-05-07 08:44:41.233 -06:00] [INF] [6] Dlna: DLNA Session created for "DVR (AMS Renderer)" - "ASUS Media Streamer DMR"
> [2020-05-07 08:45:43.466 -06:00] [ERR] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.111:8096/Users/authenticatebyname"
> System.ArgumentNullException: Value cannot be null. (Parameter 'resolvedUser')
>    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
>    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
>    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
>    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
> [2020-05-07 08:46:03.309 -06:00] [INF] [44] Main: Ctrl+C, shutting down

Jellyfin log file:
[log_20200507.log](https://github.com/jellyfin/jellyfin/files/4606940/log_20200507.log)

HAR file showing HTTP response 400 (Bad Request), when Sign In was clicked:
[192.168.1.111_Archive [20-05-07 08-47-35].har.txt](https://github.com/jellyfin/jellyfin/files/4606950/192.168.1.111_Archive.20-05-07.08-47-35.har.txt)

**EDIT:** I'm not sure whether this issue is valid.  I was finally able to create my own Jellyfin build.
After copying my EXEs over the official 10.5.5 build and attaching the debugger, I was able to see that the password for my new user was 'null'.  I can't remember, but I believe this was seen somewhere inside DefaultAuthenticationProvider.Authenticate().

In hindsight, I think what had happened was that during the initial setup, after I set up a user and a _large_ media library and plugins, the Jellyfin server appeared to become unresponsive for quite a while.  I probably got tired of waiting for it and canceled it by refreshing the page or something.  This must have left my Jellyfin instance in some kind of bad state without a saved password.

I worked around this by doing a clean reinstall, and then running the initial setup _without_ setting up a media library or installing plugins.  Once I confirmed that I was able to login using my new user, I then set up the media libraries and plugins.  Now my server is functioning as expected.

**Comment by nebulous999** [comment]
Sorry, I didn't mean to close it.  I think it might be worth someone else attempting to reproduce this by interrupting the initial setup, to see if something can be done to prevent the bad state with the login issues afterward.
