### ISSUE TITLE
NULL-deref at startup of Jellyfin on Alpine Linux

### ISSUE THREAD

**Issue by jvoisin** [jellyfin/jellyfin#3114]
I'm getting a segfault when running Jellyfin 10.4.3 stable under Alpine linux, and it looks like a NULL pointer dereference:

```nasm
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /opt/jellyfin/jellyfin_10.4.3/jellyfin 

Program received signal SIGSEGV, Segmentation fault.
0x00000000000a1ba6 in ?? ()
(gdb) bt
#0  0x00000000000a1ba6 in ?? ()
#1  0x00007ffff75fb4e8 in CorUnix::InternalCreateThread(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, unsigned int, unsigned int (*)(void*), void*, unsigned int, CorUnix::PalThreadType, unsigned long*, void**) () from /opt/jellyfin/jellyfin_10.4.3/libcoreclr.so
#2  0x00007ffff75f0a52 in CorUnix::CPalSynchronizationManager::StartWorker(CorUnix::CPalThread*) () from /opt/jellyfin/jellyfin_10.4.3/libcoreclr.so
#3  0x00007ffff75d2bff in Initialize(int, char const* const*, unsigned int) () from /opt/jellyfin/jellyfin_10.4.3/libcoreclr.so
#4  0x00007ffff75d2e42 in PAL_InitializeCoreCLR () from /opt/jellyfin/jellyfin_10.4.3/libcoreclr.so
#5  0x00007ffff721d673 in coreclr_initialize () from /opt/jellyfin/jellyfin_10.4.3/libcoreclr.so
#6  0x00007ffff7915ebf in ?? () from /opt/jellyfin/jellyfin_10.4.3/libhostpolicy.so
#7  0x00007ffff79222d3 in ?? () from /opt/jellyfin/jellyfin_10.4.3/libhostpolicy.so
#8  0x00007ffff7921d72 in corehost_main () from /opt/jellyfin/jellyfin_10.4.3/libhostpolicy.so
#9  0x00007ffff7b86ecc in ?? () from /opt/jellyfin/jellyfin_10.4.3/libhostfxr.so
#10 0x00007ffff7b85a63 in ?? () from /opt/jellyfin/jellyfin_10.4.3/libhostfxr.so
#11 0x00007ffff7b80ab3 in hostfxr_main_startupinfo () from /opt/jellyfin/jellyfin_10.4.3/libhostfxr.so
#12 0x000000000040eba6 in ?? ()
#13 0x000000000040f1fe in ?? ()
#14 0x00007ffff7f851f5 in ?? () from /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7f851ce in ?? () from /lib64/ld-linux-x86-64.so.2
#16 0x00007fffffffea20 in ?? ()
#17 0x0000000000000000 in ?? ()
(gdb) info reg
rax            0x0                 0
rbx            0x687ce0            6847712
rcx            0x7ffff7faceac      140737353797292
rdx            0x7fffffffe030      140737488347184
rsi            0x80                128
rdi            0x7fffffffe0b8      140737488347320
rbp            0x7fffffffe120      0x7fffffffe120
rsp            0x7fffffffe008      0x7fffffffe008
r8             0x101010101010101   72340172838076673
r9             0x7fffffffdfb8      140737488347064
r10            0x5ebd757d          1589474685
r11            0x202               514
r12            0x7ffff75f31b0      140737343599024
r13            0x54f               1359
r14            0x679660            6788704
r15            0x0                 0
rip            0xa1ba6             0xa1ba6
eflags         0x10246             [ PF ZF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
(gdb) 
```

On `Linux jellyfin 5.3.18-2-pve #1 SMP PVE 5.3.18-2 (Sat, 15 Feb 2020 15:11:52 +0100) x86_64 Linux`, alpine edge, in an LXC jail.

**Comment by Artiume** [comment]
Can you try 10.5.5, 10.4.3 is old

**Comment by jvoisin** [comment]
Same result:

```nasm
(gdb) r
Starting program: /opt/jellyfin/jellyfin_10.5.5/jellyfin 

Program received signal SIGSEGV, Segmentation fault.
0x00000000000a1ba6 in ?? ()
(gdb) bt
#0  0x00000000000a1ba6 in ?? ()
#1  0x00007ffff75fb4e8 in CorUnix::InternalCreateThread(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, unsigned int, unsigned int (*)(void*), void*, unsigned int, CorUnix::PalThreadType, unsigned long*, void**) () from /opt/jellyfin/jellyfin_10.5.5/libcoreclr.so
#2  0x00007ffff75f0a52 in CorUnix::CPalSynchronizationManager::StartWorker(CorUnix::CPalThread*) () from /opt/jellyfin/jellyfin_10.5.5/libcoreclr.so
#3  0x00007ffff75d2bff in Initialize(int, char const* const*, unsigned int) () from /opt/jellyfin/jellyfin_10.5.5/libcoreclr.so
#4  0x00007ffff75d2e42 in PAL_InitializeCoreCLR () from /opt/jellyfin/jellyfin_10.5.5/libcoreclr.so
#5  0x00007ffff721d673 in coreclr_initialize () from /opt/jellyfin/jellyfin_10.5.5/libcoreclr.so
#6  0x00007ffff7915ebf in ?? () from /opt/jellyfin/jellyfin_10.5.5/libhostpolicy.so
#7  0x00007ffff79222d3 in ?? () from /opt/jellyfin/jellyfin_10.5.5/libhostpolicy.so
#8  0x00007ffff7921d72 in corehost_main () from /opt/jellyfin/jellyfin_10.5.5/libhostpolicy.so
#9  0x00007ffff7b86ecc in ?? () from /opt/jellyfin/jellyfin_10.5.5/libhostfxr.so
#10 0x00007ffff7b85a63 in ?? () from /opt/jellyfin/jellyfin_10.5.5/libhostfxr.so
#11 0x00007ffff7b80ab3 in hostfxr_main_startupinfo () from /opt/jellyfin/jellyfin_10.5.5/libhostfxr.so
#12 0x000000000040eba6 in ?? ()
#13 0x000000000040f1fe in ?? ()
#14 0x00007ffff7f851f5 in ?? () from /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7f851ce in ?? () from /lib64/ld-linux-x86-64.so.2
#16 0x00007fffffffea40 in ?? ()
#17 0x0000000000000000 in ?? ()
(gdb) info reg
rax            0x0                 0
rbx            0x687ce0            6847712
rcx            0x7ffff7faceac      140737353797292
rdx            0x7fffffffe050      140737488347216
rsi            0x80                128
rdi            0x7fffffffe0d8      140737488347352
rbp            0x7fffffffe140      0x7fffffffe140
rsp            0x7fffffffe028      0x7fffffffe028
r8             0x101010101010101   72340172838076673
r9             0x7fffffffdfd8      140737488347096
r10            0x5ebd8107          1589477639
r11            0x202               514
r12            0x7ffff75f31b0      140737343599024
r13            0x54f               1359
r14            0x679660            6788704
r15            0x0                 0
rip            0xa1ba6             0xa1ba6
eflags         0x10246             [ PF ZF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
(gdb) 
```

**Comment by jvoisin** [comment]
Since this is an *exotic* operating system, I don't expect anyone to dive into Mono's runtime just for the sake of fixing this issue.

I've switched to debian for jellyfin, and it just works™

**Comment by Bond-009** [comment]
This seems like a dotnet issue not a Jellyfin issue
