### ISSUE TITLE
Jellyfin on windows tray icon doesn't work

### ISSUE THREAD

**Issue by itsyecoder** [jellyfin/jellyfin#3119]
I can get Jellyfin to work through the "view console" app, but when I try the tray icon, it does nothing. Also added caddy and set it up with jellyfin. Here is my view console log. Any help would be greatly appreciated. 

```
[23:18:44] [INF] [1] Main: Jellyfin version: 10.5.5
[23:18:44] [INF] [1] Main: Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll", "--datadir", "C:\\ProgramData\\Jellyfin\\Server"]
[23:18:44] [INF] [1] Main: Operating system: Windows
[23:18:44] [INF] [1] Main: Architecture: X64
[23:18:44] [INF] [1] Main: 64-Bit Process: True
[23:18:44] [INF] [1] Main: User Interactive: True
[23:18:44] [INF] [1] Main: Processor count: 2
[23:18:44] [INF] [1] Main: Program data path: C:\ProgramData\Jellyfin\Server
[23:18:44] [INF] [1] Main: Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[23:18:44] [INF] [1] Main: Application directory: C:\Program Files\Jellyfin\Server\
[23:18:45] [INF] [1] ServerConfigurationManager: Setting cache path: C:\ProgramData\Jellyfin\Server\cache
[23:18:45] [INF] [1] App: Loading assemblies
[23:18:51] [INF] [1] Main: Kestrel listening on all interfaces
[23:18:51] [INF] [1] App: Running startup tasks
[23:18:51] [INF] [1] TaskManager: Daily trigger for Extract Chapter Images set to fire at 05/15/2020 02:00, which is 2:41:08.2411633 from now.
[23:18:51] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version unknown
[23:18:51] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: Failed version check: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[23:18:52] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[23:18:52] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[23:18:52] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[23:18:52] [INF] [1] App: ServerId: 7e44cd33efed41cba3642ea25fa95799
[23:18:52] [INF] [1] App: Executed all pre-startup entry points in 0:00:00.3182282
[23:18:52] [INF] [1] App: Core startup complete
[23:18:52] [INF] [10] LibraryMonitor: Watching directory A:\Oh Yeah
[23:18:52] [INF] [4] LibraryMonitor: Watching directory D:\Music
[23:18:52] [INF] [8] LibraryMonitor: Watching directory D:\Photos
[23:18:53] [INF] [1] App: Executed all post-startup entry points in 0:00:00.848977
[23:18:53] [INF] [1] Main: Startup complete 0:00:09.9003245
[23:18:54] [INF] [4] TaskManager: StartupTrigger fired for task: Update Plugins
[23:18:54] [INF] [4] TaskManager: Queueing task PluginUpdateTask
[23:18:54] [INF] [4] TaskManager: Executing Update Plugins
[23:18:55] [ERR] [5] TaskManager: Error
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+MoveNext()
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[23:18:55] [INF] [5] TaskManager: Update Plugins Failed after 0 minute(s) and 0 seconds
[23:18:55] [INF] [5] TaskManager: ExecuteQueuedTasks
```

**Comment by itsyecoder** [comment]
I believe this is the problem here, which there is a solution for on docker, but not windows.

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

**Comment by pusta** [comment]
Try this:

Navigate to %temp%\.net and delete the Jellyfin folder in there.  Restart the Tray app.  This just happened to me after the latest .Net update on Tuesday.

**Comment by itsyecoder** [comment]
> Try this:
> 
> 
> 
> Navigate to %temp%\.net and delete the Jellyfin folder in there.  Restart the Tray app.  This just happened to me after the latest .Net update on Tuesday. 

Would that just be found in file explorer or do I run that in the run prompt

**Comment by pusta** [comment]
Sorry, I missed a slash in there. Go to start->run and type `%temp%\.net` and hit enter. You should see a folder called Jellyfin

**Comment by itsyecoder** [comment]
Yep that fixed it. Thanks a million!
