### ISSUE TITLE
Stuck on Wizard: Could not find handler for /config ?

### ISSUE THREAD

**Issue by FaZeBase** [jellyfin/jellyfin#3132]
**Bug description**
Stuck on setup: I cannot choose a prefered language and it seems stuck on loading.

**System:**
 - OS: Ubuntu 18.04 LTS x64
 - Virtualization: Docker on FreeNAS bhyve
 - Clients: Browser
 - Browser: Firefox 76.0.1
 - Jellyfin Version: git clone from 16/05/2020
 - Playback: none 
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: jelly.example.com
 - Networking: Bridge (except Docker)
 - Storage: local

**To Reproduce**
1. Install the container (fzbasescu/jellyfin-cloudron) with Cloudron : a Docker "frontend"
2. Go to the configured subdomain (from Cloudron)
3. "enjoy"

**Expected behavior**
I should be able to begin my configuration from the wizard
**Logs**
```
May 16 22:36:05 [20:36:05] [INF] [1] Main: Application directory: /app/code/jellyfin/
May 16 22:36:05 [20:36:05] [INF] [1] ServerConfigurationManager: Setting cache path: /run
May 16 22:36:05 [20:36:05] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
May 16 22:36:06 [20:36:06] [WRN] [1] Emby.Server.Implementations.Library.UserManager: No users, creating one with username root
May 16 22:36:07 [20:36:07] [INF] [1] ServerConfigurationManager: Saving system configuration
May 16 22:36:07 [20:36:07] [INF] [1] ServerConfigurationManager: Setting cache path: /run
May 16 22:36:07 [20:36:07] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 16 22:36:08 [20:36:08] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking all known migrations as applied because this is a fresh install
May 16 22:36:09 [20:36:09] [INF] [1] Main: Kestrel listening on all interfaces
May 16 22:36:09 [20:36:09] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
May 16 22:36:09 [20:36:09] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
May 16 22:36:09 [20:36:09] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {474eafc6-809f-4b5e-828a-3a95e1ff2435} may be persisted to storage in unencrypted form.
May 16 22:36:09 [20:36:09] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
May 16 22:36:09 [20:36:09] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 05/17/2020 02:00, which is 5:23:50.7714077 from now.
May 16 22:36:09 [20:36:09] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: NotFound:
May 16 22:36:09 [20:36:09] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: fab869792ee44bc69e62ce5ce86eaea0
May 16 22:36:09 [20:36:09] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.3079801
May 16 22:36:09 [20:36:09] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
May 16 22:36:09 [20:36:09] [INF] [4] Dlna: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.18.0.10
May 16 22:36:10 [20:36:10] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.4958524
May 16 22:36:10 [20:36:10] [INF] [1] Main: Startup complete 0:00:05.2708137
May 16 22:36:12 [20:36:12] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
May 16 22:36:12 [20:36:12] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
May 16 22:36:12 [20:36:12] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
May 16 22:36:13 [20:36:13] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
May 16 22:36:13 [20:36:13] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
May 16 22:36:39 [20:36:39] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config
May 16 22:36:39 [20:36:39] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jelly.example.com/config.json?nocache=360
May 16 22:36:39 [20:36:39] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config.template
May 16 22:36:39 [20:36:39] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jelly.example.com/config.template.json
May 16 22:36:40 [20:36:40] [ERR] [6] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLVPR322J5HC", Request id "0HLVPR322J5HC:00000001": An unhandled exception was thrown by the application.
May 16 22:36:40 System.Security.Authentication.AuthenticationException: Access token is required.
May 16 22:36:40 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token)
May 16 22:36:40 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues)
May 16 22:36:40 at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes)
May 16 22:36:40 at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
May 16 22:36:40 at Microsoft.AspNetCore.Authentication.AuthenticationHandler1.AuthenticateAsync()
May 16 22:36:40 at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
May 16 22:36:40 at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
May 16 22:36:40 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 16 22:36:40 at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 16 22:36:40 at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 16 22:36:40 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
May 16 22:36:40 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
May 16 22:39:26 [20:39:26] [ERR] [15] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLVPR322J5I5", Request id "0HLVPR322J5I5:00000001": An unhandled exception was thrown by the application.
May 16 22:39:26 System.Security.Authentication.AuthenticationException: Access token is required.
May 16 22:39:26 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token)
May 16 22:39:26 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues)
May 16 22:39:26 at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes)
May 16 22:39:26 at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
May 16 22:39:26 at Microsoft.AspNetCore.Authentication.AuthenticationHandler1.AuthenticateAsync()
May 16 22:39:26 at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
May 16 22:39:26 at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
May 16 22:39:26 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 16 22:39:26 at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 16 22:39:26 at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 16 22:39:26 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
May 16 22:39:26 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication 1 application)
```
**Some context**

I am trying to port Jellyfin over to Cloudron. It installs different services on Docker. I thought it was pretty easy to port but I am stuck here. I will also report this issue to Cloudron just in case.

**Comment by FaZeBase** [comment]
Testing at the moment. I'll tell you if it works.

**Comment by FaZeBase** [comment]
It still doesn't work. It seems to be the same issue.

```
May 17 17:54:37 [15:54:37] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /tmp/log]", "[JELLYFIN_CACHE_DIR, /run]", "[JELLYFIN_CONFIG_DIR, /app/data/config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_DATA_DIR, /app/data/media]"]
May 17 17:54:37 [15:54:37] [INF] [1] Main: Arguments: ["/app/code/jellyfin/jellyfin.dll"]
May 17 17:54:37 [15:54:37] [INF] [1] Main: Operating system: Linux
May 17 17:54:37 [15:54:37] [INF] [1] Main: Architecture: X64
May 17 17:54:37 [15:54:37] [INF] [1] Main: 64-Bit Process: True
May 17 17:54:37 [15:54:37] [INF] [1] Main: User Interactive: True
May 17 17:54:37 [15:54:37] [INF] [1] Main: Processor count: 1
May 17 17:54:37 [15:54:37] [INF] [1] Main: Program data path: /app/data/media
May 17 17:54:37 [15:54:37] [INF] [1] Main: Web resources path: /app/code/jellyfin/jellyfin-web
May 17 17:54:37 [15:54:37] [INF] [1] Main: Application directory: /app/code/jellyfin/
May 17 17:54:37 [15:54:37] [INF] [1] ServerConfigurationManager: Setting cache path: /run
May 17 17:54:37 [15:54:37] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
May 17 17:54:38 [15:54:38] [WRN] [1] Emby.Server.Implementations.Library.UserManager: No users, creating one with username root
May 17 17:54:39 [15:54:39] [INF] [1] ServerConfigurationManager: Saving system configuration
May 17 17:54:39 [15:54:39] [INF] [1] ServerConfigurationManager: Setting cache path: /run
May 17 17:54:40 [15:54:40] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 17 17:54:41 [15:54:41] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Marking all known migrations as applied because this is a fresh install
May 17 17:54:41 [15:54:41] [INF] [1] Main: Kestrel listening on all interfaces
May 17 17:54:41 [15:54:41] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
May 17 17:54:41 [15:54:41] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
May 17 17:54:41 [15:54:41] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {14f397bc-0ec5-4b92-9f48-c88d8dd3dd78} may be persisted to storage in unencrypted form.
May 17 17:54:41 [15:54:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
May 17 17:54:41 [15:54:41] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 05/18/2020 02:00, which is 10:05:18.3082735 from now.
May 17 17:54:41 [15:54:41] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: NotFound:
May 17 17:54:41 [15:54:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 1701212803ab4472aef247d0ac952121
May 17 17:54:42 [15:54:42] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.3065524
May 17 17:54:42 [15:54:42] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
May 17 17:54:42 [15:54:42] [INF] [6] Dlna: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.18.0.11
May 17 17:54:42 [15:54:42] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.5808529
May 17 17:54:42 [15:54:42] [INF] [1] Main: Startup complete 0:00:05.4755325
May 17 17:54:44 [15:54:44] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
May 17 17:54:44 [15:54:44] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
May 17 17:54:44 [15:54:44] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
May 17 17:54:45 [15:54:45] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
May 17 17:54:45 [15:54:45] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
May 17 17:55:11 [15:55:11] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config
May 17 17:55:11 [15:55:11] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jellyedge.aweed.ml/config.json?nocache=866
May 17 17:55:11 [15:55:11] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config.template
May 17 17:55:11 [15:55:11] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jellyedge.aweed.ml/config.template.json
May 17 17:55:12 [15:55:12] [ERR] [18] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLVQFAECO0R4", Request id "0HLVQFAECO0R4:00000001": An unhandled exception was thrown by the application.
May 17 17:55:12 System.Security.Authentication.AuthenticationException: Access token is required.
May 17 17:55:12 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token)
May 17 17:55:12 at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues)
May 17 17:55:12 at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes)
May 17 17:55:12 at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
May 17 17:55:12 at Microsoft.AspNetCore.Authentication.AuthenticationHandler(`)1.AuthenticateAsync()
May 17 17:55:12 at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
May 17 17:55:12 at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
May 17 17:55:12 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 17 17:55:12 at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 17 17:55:12 at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 17 17:55:12 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
May 17 17:55:12 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication(`)1 application)
```

**Comment by FaZeBase** [comment]
I said it before. It still doesn't solve the issue.
