### ISSUE TITLE
HTTP 500 Error With Localhost or 127.0.0.1

### ISSUE THREAD

**Issue by JudoFreak** [jellyfin/jellyfin#3136]
**Describe the bug**
When trying to open the log-in screen after running a few times I get HTTP 500 and can't seem to get to the login page. 

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.5
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Go to "Jellyfin Tray"
2. Click on 'Open Jellyfin"
4. See error -- HTTP 500

**Expected behavior**
Prompt login screen

**Logs**
```
[2020-05-17 09:31:31.533 -05:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-17 09:31:31.576 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-17 09:31:31.591 -05:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-17 09:31:31.594 -05:00] [INF] [1] Main: Architecture: X64
[2020-05-17 09:31:31.599 -05:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-17 09:31:31.600 -05:00] [INF] [1] Main: User Interactive: True
[2020-05-17 09:31:31.602 -05:00] [INF] [1] Main: Processor count: 4
[2020-05-17 09:31:31.604 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-17 09:31:31.607 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-17 09:31:31.609 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-17 09:31:32.678 -05:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-17 09:31:32.792 -05:00] [INF] [1] App: Loading assemblies
[2020-05-17 09:31:39.282 -05:00] [INF] [1] Main: Kestrel listening on all interfaces
[2020-05-17 09:31:40.649 -05:00] [INF] [1] App: Running startup tasks
[2020-05-17 09:31:40.762 -05:00] [INF] [1] TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 05/18/2020 02:00, which is 16:28:19.2376568 from now.
[2020-05-17 09:31:40.906 -05:00] [ERR] [10] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HLVQDS1S4B9J"", Request id ""0HLVQDS1S4B9J:00000001"": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean createInertEndpoints)
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Emby.Server.Implementations.ApplicationHost.ExecuteWebsocketHandlerAsync(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2020-05-17 09:31:43.511 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "unknown"
[2020-05-17 09:31:43.521 -05:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: Failed version check: "C:\Program Files\Jellyfin\Server\ffmpeg.exe"
[2020-05-17 09:31:43.714 -05:00] [ERR] [4] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HLVQDS1S4B9J"", Request id ""0HLVQDS1S4B9J:00000002"": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean createInertEndpoints)
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Emby.Server.Implementations.ApplicationHost.ExecuteWebsocketHandlerAsync(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2020-05-17 09:31:43.939 -05:00] [INF] [12] TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-05-17 09:31:43.942 -05:00] [INF] [12] TaskManager: Queueing task "PluginUpdateTask"
[2020-05-17 09:31:43.955 -05:00] [INF] [4] TaskManager: Executing "Update Plugins"
[2020-05-17 09:31:44.023 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "vc1_qsv", "aac", "ac3", "mp3"]
[2020-05-17 09:31:44.222 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-05-17 09:31:44.231 -05:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: "C:\Program Files\Jellyfin\Server\ffmpeg.exe"
[2020-05-17 09:31:44.236 -05:00] [INF] [1] App: ServerId: "0427c6c2971347578544222e2be00a93"
[2020-05-17 09:31:45.372 -05:00] [INF] [8] TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2020-05-17 09:31:45.437 -05:00] [INF] [8] TaskManager: ExecuteQueuedTasks
[2020-05-17 09:31:45.733 -05:00] [ERR] [12] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HLVQDS1S4B9L"", Request id ""0HLVQDS1S4B9L:00000001"": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean createInertEndpoints)
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Emby.Server.Implementations.ApplicationHost.ExecuteWebsocketHandlerAsync(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2020-05-17 09:31:45.734 -05:00] [INF] [1] App: Executed all pre-startup entry points in 0:00:01.4828016
[2020-05-17 09:31:45.743 -05:00] [INF] [1] App: Core startup complete
[2020-05-17 09:31:46.895 -05:00] [INF] [1] App: Executed all post-startup entry points in 0:00:01.1503604
[2020-05-17 09:31:46.898 -05:00] [INF] [1] Main: Startup complete 0:00:17.0526077

```
Happy to provide any further clarification! Thanks in advance!

**Comment by BaronGreenback** [comment]
Seems to be the same as https://github.com/jellyfin/jellyfin/issues/2905

Potential work around in #2905

**Comment by JudoFreak** [comment]
> Seems to be the same as #2905
> 
> Potential work around suggested - "try to remove the httpclient folder that mat je confusing jellyfin. I reinstall evrything After i backed UP all important things from jellyfin and i got an issue with this folder.
> 
> i just removed it and its worked fine."

Hmm, deleting "httpclient" folder didn't seem to make any difference. Still getting the error after re-installs.

**Comment by keniji** [comment]
I also encounter this issue with my very new incident in docker... As I can remembered, I have change the network settings before this issue, so I go to config/system.xml and remove the line:
```"<BaseUrl>*****</BaseUrl>"
Reboot the container and then I am able to access the web interface now... It's weird since I have another Jellyfin incident which has the same configuration...
