### ISSUE TITLE
Attempt to write a readonly database with 777 permissions

### ISSUE THREAD

**Issue by PopeRigby** [jellyfin/jellyfin#3151]
**Describe the bug**

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 76.0.1
 - Jellyfin Version: 28.04.20
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: Caddy
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Screw up your Jellyfin installation by removing all media and putting it backup
2. Get this error: 
```
There was an issue with the client profiling and the server isn't sending a compatible media format.
```
3. Create a new Jellyfin container
4. Copy the old config folder over to the new container so you don't lose all your user and meta data
5. Give the config directory 777 permissions just in case

**Expected behavior**

Jellyfin works

**Actual Behavior**
Jellyfin talks about attempting to write a readonly database

**Logs**

```
ReadOnly: SQLitePCL.pretty.SQLiteException: attempt to write a readonly database
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[00:00:44] [INF] [1] App: Disposing CoreAppHost
[00:00:44] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by Artiume** [comment]
this looks applicable https://stackoverflow.com/questions/3319112/sqlite-error-attempt-to-write-a-readonly-database-during-insert

**Comment by PopeRigby** [comment]
So do you think I should also give the folder where `config` is located 777 permissions?

**Comment by crobibero** [comment]
You should give the parent folder proper permissions, 777 isn't required.

**Comment by PopeRigby** [comment]
I gave my Jellyfin user rwx permissions using ACL, and I'm still getting the error
```
# file: jellyfin/
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
default:user::rwx
default:user:jellyfin:rwx
default:group::r-x
default:mask::rwx
default:other::r-x
```

**Comment by Artiume** [comment]
Change the owner of the folder, it's currently root

**Comment by PopeRigby** [comment]
It's now owned by my Jellyfin user and I'm still getting the error:
```
# file: jellyfin/
# owner: jellyfin
# group: jellyfin
user::rwx
group::r-x
other::r-x
default:user::rwx
default:user:jellyfin:rwx
default:group::r-x
default:mask::rwx
default:other::r-x
```

**Comment by skalle** [comment]
I've got something similar going: 

[12:55:49] [INF] [1] Main: Jellyfin version: 10.5.5
[12:55:49] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[12:55:49] [INF] [1] Main: Operating system: Linux
[12:55:49] [INF] [1] Main: Architecture: X64
[12:55:49] [INF] [1] Main: 64-Bit Process: True
[12:55:49] [INF] [1] Main: User Interactive: True
[12:55:49] [INF] [1] Main: Processor count: 24
[12:55:49] [INF] [1] Main: Program data path: /config
[12:55:49] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[12:55:49] [INF] [1] Main: Application directory: /jellyfin/
[12:55:49] [INF] [1] ServerConfigurationManager: Setting cache path: /cache
[12:55:49] [INF] [1] App: Loading assemblies
[12:55:49] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Anime/Jellyfin.Plugin.Anime.dll
[12:55:49] [INF] [1] App: Loaded assembly Emby.AutoOrganize, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Auto Organize/Emby.AutoOrganize.dll
[12:55:49] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Fanart/Jellyfin.Plugin.Fanart.dll
[12:55:49] [INF] [1] App: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TMDb Box Sets/Jellyfin.Plugin.TMDbBoxSets.dll
[12:55:49] [FTL] [1] Main: Error while starting server.
ReadOnly: SQLitePCL.pretty.SQLiteException: attempt to write a readonly database
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[12:55:49] [INF] [1] App: Disposing CoreAppHost
[12:55:49] [INF] [2] Main: Received a SIGTERM signal, shutting down


This after copying the configuration from an old jellyfin install to a new one.

**Comment by skalle** [comment]
Folder looks like follows:

❯ cd data
❯ ls -ltr
total 55140
-rw-rw-rw- 1 emby emby_ldap       35 Apr 30 23:09 device.txt
drwxrwxrwx 1 emby emby_ldap        0 Apr 30 23:09 playlists
drwxrwxrwx 1 emby emby_ldap     5016 May  1 20:45 collections
drwxrwxrwx 1 emby emby_ldap      858 May  1 20:52 ScheduledTasks
-rw-rw-rw- 1 emby emby_ldap    28672 May  2 11:35 fileorganization.db
drwxrwxrwx 1 emby emby_ldap      384 May 13 20:38 devices
-rw-rw-rw- 1 emby emby_ldap        0 May 20 13:15 displaypreferences.db-journal
-rw-rw-rw- 1 emby emby_ldap    12288 May 20 13:15 displaypreferences.db
drwxrwxrwx 1 emby emby_ldap       20 Jun 18 14:46 subtitles
-rw-rw-rw- 1 emby emby_ldap     8192 Jun 25 18:40 users.db
-rw-rw-rw- 1 emby emby_ldap        0 Jun 25 18:40 users.db-journal
-rw-rw-rw- 1 emby emby_ldap        0 Jun 26 11:50 activitylog.db-journal
-rw-rw-rw- 1 emby emby_ldap   118784 Jun 26 11:50 activitylog.db
-rw-rw-rw- 1 emby emby_ldap        0 Jun 26 11:50 authentication.db-journal
-rw-rw-rw- 1 emby emby_ldap    28672 Jun 26 11:50 authentication.db
-rw-rw-rw- 1 emby emby_ldap        0 Jun 26 16:09 library.db-journal
-rw-rw-rw- 1 emby emby_ldap 56262656 Jun 26 16:09 library.db
❯ ls -ld .
drwxrwxrwx 1 emby emby_ldap 518 Jun 26 21:16 .

The jellyfin Docker container runs as the emby:emby_ldap user and group.

**Comment by ankenyr** [comment]
Looks like I just hit this error tonight doing a similar thing. Was upgrading to a new version in docker. Updated but forgot to mount one of the paths. When I mounted the new path and restarted I am getting this error. Anyone get any new information on this?

**Comment by ankenyr** [comment]
Just to update I did not actually hit it. I may have some of the docker terminology wrong but @PopeRigby maybe check your docker config? Somehow I accidentally flipped the volume mount to RO. The host file system was still readable but when it got mounted inside of the container it would be RO no matter what.

**Comment by PopeRigby** [comment]
Unfortunately I won't be able to test this anymore because I just created a new instance of Jellyfin.

**Comment by Jayotis** [comment]
> It's now owned by my Jellyfin user and I'm still getting the error:
> 
> ```
> # file: jellyfin/
> # owner: jellyfin
> # group: jellyfin
> user::rwx
> group::r-x
> other::r-x
> default:user::rwx
> default:user:jellyfin:rwx
> default:group::r-x
> default:mask::rwx
> default:other::r-x
> ```
I don't use docker but it shows your group only has read access so maybe that was the issue.  

I was able to change permissions and cleared the error and jellyfin loaded but then I was not able to access web interface or thru app. No errors in journal file.  I choose a bad time to work this so ya, new instance.

**Comment by C-Fu** [comment]
I'm getting something similar, but what I did was I rsync -a the jellyfin folder to a SSD, and changed the appropriate docker bind to the new ssd location. using UnRaid.

**Comment by fdfytr** [comment]
> This after copying the configuration from an old jellyfin install to a new one.

same error after copied jellyfin config folder to a new machine
chmod 755 + correct chown for puid and pguid

**Comment by boomam** [comment]
Same issue here, with one of the recent updates.
Checked the permissions and tested ownership of both the Jellyfin user, & standard user for an LSIO container (abc) - same issue either way. 
I'd rather not lose my database if at all possible...

**Comment by bornav** [comment]
there is something weird going on, but to add what fixed it in my case, externally changing the ownership/permissions did not change the behavior, however if you manage to spin up the server, running it on the data folder inside the container when running magically managed to unlock the database
