### ISSUE TITLE
Unable to start server on Windows 10

### ISSUE THREAD

**Issue by ivancuric** [jellyfin/jellyfin#3170]
**Describe the bug**
The server isn't running on Windows 10. Tray app runs fine.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None

**Logs**
```
[2020-05-25 00:31:29.089 +02:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-25 00:31:29.104 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-25 00:31:29.110 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-25 00:31:29.112 +02:00] [INF] [1] Main: Architecture: X64
[2020-05-25 00:31:29.115 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-25 00:31:29.116 +02:00] [INF] [1] Main: User Interactive: True
[2020-05-25 00:31:29.117 +02:00] [INF] [1] Main: Processor count: 4
[2020-05-25 00:31:29.119 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-25 00:31:29.121 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-25 00:31:29.123 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-25 00:31:29.362 +02:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-25 00:31:29.411 +02:00] [INF] [1] App: Loading assemblies
[2020-05-25 00:31:29.991 +02:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtension3' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.HttpServiceCollectionExtensions.AddHttpContextAccessor(IServiceCollection services)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-05-25 00:31:30.023 +02:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-05-25 00:31:30.032 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2020-05-25 00:31:56.544 +02:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-25 00:31:56.559 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-25 00:31:56.566 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-25 00:31:56.568 +02:00] [INF] [1] Main: Architecture: X64
[2020-05-25 00:31:56.570 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-25 00:31:56.572 +02:00] [INF] [1] Main: User Interactive: True
[2020-05-25 00:31:56.574 +02:00] [INF] [1] Main: Processor count: 4
[2020-05-25 00:31:56.575 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-25 00:31:56.577 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-25 00:31:56.579 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-25 00:31:56.721 +02:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-25 00:31:56.741 +02:00] [INF] [1] App: Loading assemblies
[2020-05-25 00:31:56.988 +02:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtension3' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.HttpServiceCollectionExtensions.AddHttpContextAccessor(IServiceCollection services)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-05-25 00:31:57.003 +02:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-05-25 00:31:57.009 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2020-05-25 00:32:02.986 +02:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-25 00:32:03.000 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-25 00:32:03.006 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-25 00:32:03.007 +02:00] [INF] [1] Main: Architecture: X64
[2020-05-25 00:32:03.008 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-25 00:32:03.009 +02:00] [INF] [1] Main: User Interactive: True
[2020-05-25 00:32:03.010 +02:00] [INF] [1] Main: Processor count: 4
[2020-05-25 00:32:03.012 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-25 00:32:03.013 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-25 00:32:03.014 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-25 00:32:03.156 +02:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-25 00:32:03.174 +02:00] [INF] [1] App: Loading assemblies
[2020-05-25 00:32:03.444 +02:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtension3' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.HttpServiceCollectionExtensions.AddHttpContextAccessor(IServiceCollection services)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-05-25 00:32:03.458 +02:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-05-25 00:32:03.465 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2020-05-25 00:32:37.519 +02:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-25 00:32:37.535 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-25 00:32:37.542 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-25 00:32:37.551 +02:00] [INF] [1] Main: Architecture: X64
[2020-05-25 00:32:37.553 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-25 00:32:37.555 +02:00] [INF] [1] Main: User Interactive: True
[2020-05-25 00:32:37.557 +02:00] [INF] [1] Main: Processor count: 4
[2020-05-25 00:32:37.559 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-25 00:32:37.560 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-25 00:32:37.562 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-25 00:32:37.710 +02:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-25 00:32:37.729 +02:00] [INF] [1] App: Loading assemblies
[2020-05-25 00:32:37.982 +02:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtension3' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.HttpServiceCollectionExtensions.AddHttpContextAccessor(IServiceCollection services)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-05-25 00:32:37.998 +02:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-05-25 00:32:38.005 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2020-05-25 00:33:10.142 +02:00] [INF] [1] Main: Jellyfin version: "10.5.5"
[2020-05-25 00:33:10.156 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-05-25 00:33:10.162 +02:00] [INF] [1] Main: Operating system: "Windows"
[2020-05-25 00:33:10.164 +02:00] [INF] [1] Main: Architecture: X64
[2020-05-25 00:33:10.165 +02:00] [INF] [1] Main: 64-Bit Process: True
[2020-05-25 00:33:10.166 +02:00] [INF] [1] Main: User Interactive: True
[2020-05-25 00:33:10.167 +02:00] [INF] [1] Main: Processor count: 4
[2020-05-25 00:33:10.168 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-05-25 00:33:10.169 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-05-25 00:33:10.170 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-05-25 00:33:10.317 +02:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-05-25 00:33:10.337 +02:00] [INF] [1] App: Loading assemblies
[2020-05-25 00:33:10.603 +02:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtension3' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.HttpServiceCollectionExtensions.AddHttpContextAccessor(IServiceCollection services)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-05-25 00:33:10.619 +02:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-05-25 00:33:10.626 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by Darkwolf1515** [comment]
I have the reverse issue, tray app no longer works (Just stopped one day), but the show console one works just fine
