### ISSUE TITLE
Jellyfin server seems unable to bind to network and crashes

### ISSUE THREAD

**Issue by ioweb-gr** [jellyfin/jellyfin#3177]
**Describe the bug**
I'm trying to start jellyfin.exe and it's immediately stopping execution. 

**System (please complete the following information):**
 - Windows 10 x64
 - Virtualization: None
 - Clients: Android
 - Browser: Firefox
 - Jellyfin Version: 10.5.5 installed via chocolatey
 - Installed Plugins: Anime
 - Networking: 2 network cards in the system
 - Storage: local

**To Reproduce**

1. I go to services and try to restart the service. The service starts and immediately exit
2. Run jellyfin.exe and it exits immediately

**Expected behavior**
The server runs correctly as a service or via the exe. 

**Logs**
```
C:\WINDOWS\system32>"C:\Program Files\Jellyfin\Server\jellyfin.exe "
[20:00:13] [INF] [1] Main: Jellyfin version: 10.5.5
[20:00:13] [INF] [1] Main: Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll"]
[20:00:13] [INF] [1] Main: Operating system: Windows
[20:00:13] [INF] [1] Main: Architecture: X64
[20:00:13] [INF] [1] Main: 64-Bit Process: True
[20:00:13] [INF] [1] Main: User Interactive: True
[20:00:13] [INF] [1] Main: Processor count: 16
[20:00:13] [INF] [1] Main: Program data path: C:\Users\gabtz\AppData\Local\jellyfin
[20:00:13] [INF] [1] Main: Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[20:00:13] [INF] [1] Main: Application directory: C:\Program Files\Jellyfin\Server\
[20:00:14] [INF] [1] ServerConfigurationManager: Setting cache path: C:\Users\gabtz\AppData\Local\jellyfin\cache
[20:00:14] [INF] [1] App: Loading assemblies
[20:00:15] [INF] [1] Main: Kestrel listening on all interfaces
[20:00:15] [FTL] [1] Microsoft.AspNetCore.Server.Kestrel: Unable to start Kestrel.
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[20:00:15] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in system.xml and try again.
[20:00:15] [FTL] [1] Main: Error while starting server.
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[20:00:15] [INF] [1] App: Disposing CoreAppHost
[20:00:15] [INF] [1] App: Disposing ActivityLogWebSocketListener
[20:00:15] [INF] [1] App: Disposing SessionInfoWebSocketListener
[20:00:15] [INF] [1] App: Disposing ScheduledTasksWebSocketListener
[20:00:15] [INF] [1] App: Disposing SessionWebSocketListener
[20:00:15] [INF] [1] App: Disposing EmbyTV
[20:00:15] [INF] [2] Main: Received a SIGTERM signal, shutting down

```

--update--
Restarting the system and quickly opening jellyfin seems to allow it to work. However the port 8096 was not used by any other process when it was unable to start.

**Comment by Artiume** [comment]
Do you have DLNA on and could port 1900 udp being used by something else/.

**Comment by ioweb-gr** [comment]
Let's see. 
I had DLNA on. 
As for port 1900 it's always used by svchost.exe as soon as the PC starts by the SSDP service. 

Unfortunately my PC rebooted for an update and now jellyfin works so it's hard to reproduce again.  
Would it be possible to improve logging in such cases though so that the port that jellyfin is trying to access is logged and we can troubleshoot more easily?

**Comment by KoboDev** [comment]
Sorry to dig this out of the grave, but I found the solution, as how stupid it may sound.
Try restarting your Binbows 7 os.
I also forward 4 ports.
There functionality are as followed:
8096/tcp is used by default for HTTP traffic. You can change this in the dashboard.
8920/tcp is used by default for HTTPS traffic. You can change this in the dashboard.
1900/udp is used for service auto-discovery. This is not configurable.
7359/udp is also used for auto-discovery. This is not configurable.

Any of them can be TCP/UDP combo configurations in your router.
