### ISSUE TITLE
Unable to merge artists in music library

### ISSUE THREAD

**Issue by lameslime** [jellyfin/jellyfin#3178]
**Describe the bug**

When trying to merge artists (any number) using the 'Group Versions' option the loading circle stays and no merging happens. Tested with Chrome and Android app.

**System (please complete the following information):**
 - OS: Windws 10
 - Virtualization: None
 - Clients: Browser, Android
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.5 
 - Installed Plugins: Anime, AudioDB, Bookself, Fanart, IPTV, MusicBrainz, Next Pvr, Open Subtitles, Playback reporting, Reports, TVHeadend, Trakt
 - Reverse Proxy: None
 - Base URL: yes
 - Networking: Static IP thru a VPN
 - Storage: Local

**To Reproduce**

1. Select any amount of artists under a music library
2. Click on 'Group Versions'
3. Error

**Expected behavior**

Merge 3OH!3; 3OH!3, Jesse Cronan; 3OH!3, Kesha into 3OH!3

**Logs**

```
[21:03:57] [ERR] [100] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: https://nyanyan.cc:4142/nyanyan.cc/Videos/MergeVersions?Ids=d3438d481675a4b844e9a0fda44ffb1d%2C18b1a8608afb7a76ca4f0ed2075bb1f9%2C47209b2f3c4dd54b0fc0b04b897b0871%2C863c2b6e26541a89ff05e050f0088d36
System.ArgumentException: Please supply at least two videos to merge.
   at MediaBrowser.Api.VideosService.Post(MergeVersions request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**

https://imgur.com/a/PAWiNfC

**Additional context**

Jellyfin split them up, music is in Drive\Music\Artist\Album so I'm trying to get them back as they should be. It also seems to expect video files. Is the 'Group Versions' option listed in a wrong place, and is it not possible to merge items, same as in Emby?

**Comment by esmondmissen** [comment]
Can confirm this happens on Debian 10.6.2 as well.

**Comment by Gamegenorator** [comment]
Still an issue on Windows 10 hosts.

**Comment by rubendibattista** [comment]
+1

**Comment by billyinferno** [comment]
Still occurs, already try to identify and refresh metadata to ensure all data is correct but still got error when merging.

`System.ArgumentException: Please supply at least two videos to merge.
   at MediaBrowser.Api.VideosService.Post(MergeVersions request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by emes81** [comment]
I'm experiencing this on 10.7.7, Debian (Open Media Vault) host on Docker.

**Comment by Ge082** [comment]
I'm having the issue on 10.10.7 with no error found in logs, I have no idea why it fails
