### ISSUE TITLE
Error when creating a user on the latest nightly

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin#3199]
**Describe the bug**

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Linux Server Docker
 - Clients: Web client
 - Browser: `Chromium 83.0.4103.61 snap`
 - Jellyfin Version: `nightly20200528`
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: AudioDB, MusicBrainz, Open Subtitles, Playback Reporting, Trakt
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: jellyfin container <-> traefik <-> router (NAT) <-> internet
 - Storage: local, docker volume mount

**To Reproduce**

1. Navigate to `/usernew.html`
2. Enter a name and a password
3. Click "Save"
4. `There was an error processing the request. Please try again later.` is thrown at the user.

**Expected behavior**

A new user is created.

**Logs**
(the request doesn't send any data)
Browser response (`text/plain`):
```
Value cannot be null. (Parameter 'name')
```

Server:
```
[2020-05-28 13:18:57.491 +03:00] [ERR] [69] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://REDACTED/Users/New"
System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at Emby.Server.Implementations.Library.UserManager.CreateUser(String name)
   at MediaBrowser.Api.UserService.Post(CreateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**

**Additional context**

**Comment by Artiume** [comment]
issue is being tracked here 
https://github.com/jellyfin/jellyfin/issues/3191

**Comment by KristupasSavickas** [comment]
> issue is being tracked here
> #3191

The issue doesn't seem to be related, the error is completely different and I seemed to have triaged the reason which is in not related to Mac OS.

**Comment by Artiume** [comment]
#3195 did not fix the issue so you may be right, reopening until we figure it out

**Comment by KristupasSavickas** [comment]
[This](https://github.com/jellyfin/jellyfin-apiclient-javascript/commit/c4cac4116725821fe4c72818c10401e8582ea336) might have fixed it. Will report back once I have the chance to test it.

**Comment by wasupman2** [comment]
Having the same issue with the latest nightly docker image jellyfin/jellyfin:nightly-20200605

    [2020-06-05 07:45:36.638 +00:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://127.0.0.1:8096/Users/New"
    System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'CreateUserByName', got string starting with: Name=user&Password=mypassword
       at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 56
       at ServiceStack.Text.Common.DeserializeType`1.StringToTypeContext.DeserializeJson(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeType.cs:line 58
       at ServiceStack.Text.Json.JsonReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Json\JsonReader.Generic.cs:line 18
       at ServiceStack.Text.JsonSerializer.DeserializeFromString(String value, Type type) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 67
       at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromStreamAsync(Stream stream, Type type)
       at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
       at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
       at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by KristupasSavickas** [comment]
Looking at the logs it does look to be different, so my original explanation doesn't apply. The fix mentioned above does fix my issue tho.

**Comment by telans** [comment]
This no longer appears to be an issue
