### ISSUE TITLE
InvalidCastException during server startup in processing UserRootFolder

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#320]
Log
```
Info App: Loading live tv data from ./config/data/livetv/timers
Error App: Error creating recording folders
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /develop/jellyfin/jellyfin.build/jellyfin.dll -programdata ./config
	Operating system: Unix 18.2.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: ./config
	Application directory: /develop/jellyfin/jellyfin.build
	System.InvalidCastException: Unable to cast object of type 'MediaBrowser.Controller.Entities.Folder' to type 'MediaBrowser.Controller.Entities.UserRootFolder'.
	   at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 802
	   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders(Boolean includeRefreshState)
	   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.CreateRecordingFolders() in /develop/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 141
	System.InvalidCastException
	   at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 802
	   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders(Boolean includeRefreshState)
	   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.CreateRecordingFolders() in /develop/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 141
	
Info App: Entry point completed: Emby.Server.Implementations.LiveTv.EmbyTV.EntryPoint. Duration: 0.062496 seconds
Info App: Starting entry point Emby.Server.Implementations.Library.DeviceAccessEntryPoint
Info App: Entry point completed: Emby.Server.Implementations.Library.DeviceAccessEntryPoint. Duration: 0.000823 seconds
Info App: Starting entry point Emby.Server.Implementations.IO.LibraryMonitorStartup
Error App: Error in Emby.Server.Implementations.IO.LibraryMonitorStartup
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /develop/jellyfin/jellyfin.build/jellyfin.dll -programdata ./config
	Operating system: Unix 18.2.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: ./config
	Application directory: /develop/jellyfin/jellyfin.build
	System.InvalidCastException: Unable to cast object of type 'MediaBrowser.Controller.Entities.Folder' to type 'MediaBrowser.Controller.Entities.AggregateFolder'.
	   at Emby.Server.Implementations.Library.LibraryManager.CreateRootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 733
	   at Emby.Server.Implementations.Library.LibraryManager.get_RootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 239
	   at Emby.Server.Implementations.IO.LibraryMonitor.Start() in /develop/jellyfin/Emby.Server.Implementations/IO/LibraryMonitor.cs:line 199
	   at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup) in /develop/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 759
	System.InvalidCastException
	   at Emby.Server.Implementations.Library.LibraryManager.CreateRootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 733
	   at Emby.Server.Implementations.Library.LibraryManager.get_RootFolder() in /develop/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 239
	   at Emby.Server.Implementations.IO.LibraryMonitor.Start() in /develop/jellyfin/Emby.Server.Implementations/IO/LibraryMonitor.cs:line 199
	   at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup) in /develop/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 759
```

There is no existing conversion between Folder and UserRootFolder. 
I'm adding a deep copy BaseItem extension method.

But really ResolvePath, should just return a different structure.

**Comment by JustAMan** [comment]
Did you add an issue about properly fixing ResolvePath?

**Comment by EraYaN** [comment]
No. I've been thinking about that too. It's not weird it returns a `Folder`, just inconvenient. Also no real idea of how to do it either, since `ResolvePath` isn't even the one that determines the type. It's classes in the EntityResolvers.
