### ISSUE TITLE
Unable to scan all libraries

### ISSUE THREAD

**Issue by leaty** [jellyfin/jellyfin#3240]
**Describe the bug**
Suddenly unable to scan all libraries, both automatically and manually. My assumption is that somehow somewhere it managed to store an invalid date in the database. If so I need some help finding out where.

**System (please complete the following information):**
 - OS: archlinux
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.5.5
 - Playback:
 - Installed Plugins: AudioDB, MusicBrainz
 - Reverse Proxy: nginx
 - Base URL: /jellyfin
 - Networking: Host
 - Storage: local

**To Reproduce**
Automatic and manual "Scan All Libraries".

**Expected behavior**
To fully complete.

**Logs**
```
String '2019%11-26 22:14:18Z' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String[] formats, IFormatProvider provider, DateTimeStyles style)
   at Emby.Server.Implementations.Data.SqliteExtensions.ReadDateTime(IResultSetValue result) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Data/SqliteExtensions.cs:line 92
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(IReadOnlyList`1 reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Boolean hasServiceName, Boolean queryHasStartDate, Boolean hasTrailerTypes, Boolean hasArtistFields, Boolean hasSeriesFields) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 1898
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 2656
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren() in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 577
   at MediaBrowser.Controller.Entities.Folder.LoadChildren() in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 209
   at MediaBrowser.Controller.Entities.Folder.GetActualChildrenDictionary() in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 237
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 326
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 286
   at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 549
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 408
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 286
   at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 549
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 408
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/Folder.cs:line 286
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/MediaBrowser.Controller/Entities/AggregateFolder.cs:line 160
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Library/LibraryManager.cs:line 1087
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/Library/LibraryManager.cs:line 1039
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in /home/dragon/.cache/yay/jellyfin/src/jellyfin-10.5.5/Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 411
```

**Screenshots**

**Additional context**
1. It's always the same error.
2. Running time of the scan varies from 2-14 seconds before above error stops it.

**Comment by leaty** [comment]
Manually fixed by:
```sql
REINDEX idx_TypeTopParentId8;
REINDEX idx_TypeTopParentId9;
UPDATE TypedBaseItems SET DateCreated = '2019-11-26 22:14:18Z' WHERE DateCreated like '2019\%11-26 22:14:18Z' ESCAPE '\';
```

Not sure how that % ended up in the database though.
