### ISSUE TITLE
Photo library scan gets cancelled at specific photos - no file corruption noticeable

### ISSUE THREAD

**Issue by bigcookie** [jellyfin/jellyfin#3264]
**Describe the bug**
Scanning photos make the scan process stop.

**System (please complete the following information):**
Host: Using docker on QNAP NAS for running Jellyfin in host mode. Local storage used. Media folder is connected read only.
Client: Client is a Macbook Pro 13'', MacOS Mojave 10.14.6
Browser: Safari 13.1.1
Jellyfin: 10.5.5
Plugins: Kodi plugin installed, not yet used
Proxy etc: running in local network without proxy, direct access to server via IP-address using IP:8096

**To Reproduce**

1. Goto admin mode, libraries
2. Pick picture library and select "scan library"
3. Wait
4. Check log files: scan was cancelled

Alternatively:
1. Goto admin mode, scheduled tasks
2. Start library scan
3. Check results

**Expected behavior**
- Clear error message when scanning single libraries again to understand if t was successful or not
- scan to run through properly without gettng cancelled, but a report, which files could not be scanned

**Logs**
```
[2020-06-07 13:10:42.849 +00:00] [DBG] [15] App: Running "PhotoProvider" for "/media/Bilder/0001 - Kita Elia/Fotos/20180315_094530 IMG_6978.jpg" [2020-06-07 13:10:42.861 +00:00] [ERR] [15] ProviderManager: Error refreshing item Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg) at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc) at SQLitePCL.pretty.StatementImpl.MoveNext() at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List1 values, IDatabaseConnection db)
at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List1 values, IDatabaseConnection db) at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, IEnumerable1 tuples)
at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.b__0(IDatabaseConnection db)
at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func2 f, TransactionMode mode) at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action1 action, TransactionMode mode)
at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable1 items, CancellationToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(IEnumerable1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.MetadataService2.SaveItem(MetadataResult1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.MetadataService2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2020-06-07 13:10:45.181 +00:00] [DBG] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Websocket message received: "ScheduledTasksInfoStop"
```

**Screenshots**
not applicable

**Additional context**
I checked the photos. Interestingly the metadata (exif) etc is the same as other photos which passed the scan. I couldnt see any problem in reading the data. In this case I used Apple Preview app to read the Exif data or general data.

**Comment by bigcookie** [comment]
As the picture includes other people, I can do analysis on request - dont want to upload it to Github (sorry)

**Comment by bob503** [comment]
I'm also having this problem.

The files getting logged appear fine (I fix one, then rescan to fine another). Using perl file::type, I get the correct file type regardless of extension.  Using jhead on linux shows a valid exif section.  What I have noticed, however, is that all files thus far with a problem have adobe xml inserted in the exif data (need to use the -v option with jhead to see this).  I've not seen this data reported in any image viewer, probably because it's not a standard field.  Removing the exif section completely (jhead -purejpeg) removes the error in jellyfin's processing of the file and it gets inserted to the library.

Expectations:
1)  This is a non-fatal error.  Jellyfin should log the error with the filename (there should be no need for the user to have to google how to turn on debug logging)  This is pertinent information for the user to correct an issue, not debugging level output.
2)  The scan should skip the "bad" file and continue rather than stop. 
3)  The event in the Dashboard should be a Warning, not a failure

**Comment by bigcookie** [comment]
I added some other findings prior to filing this bug here: https://github.com/jellyfin/jellyfin/issues/1173
Might be relevant (mor log files) - please check  latest comments.

**Comment by bigcookie** [comment]
Issue still there. For me - as I use photos a lot - a bit annoying... i hoped this is more a quicker fix.
Anybody can support here?

**Comment by cvium** [comment]
Can you upload an image that triggers this bug?

**Comment by bigcookie** [comment]
Any image with a rotation flag in exif data which indicates a rotation of 90,180 or 270 degrees is affected.
I will create one if required. The ones with my family members i will not provide :-). Give me one or two days for the picture. Thanks!

**Comment by cvium** [comment]
It would definitely make it easier for us

**Comment by bigcookie** [comment]
:-). Attached two photos of a wall... I photographed them as vertical image (long side on the right/left). The thumbnail is then generated as rotated image as it doesnt respect the rotation flag of the exif information.
Picture was taken with an iPhone 7. iPhone 8 as well as Nikon D610 pictures are showing the same isse.

Setup:
Folder "Bilder" is the root for the picture library.
Below "Bilder", there are album folder like "20200914 NAME", and under this folder are all pictures

I created 
/Bilder/test/
and put the two attached photos in it.

After scanning the library the according thumbnail is generated and can be seen as wrongly oriented.
For completeness: 
I couldnt check the overarching image for the picture library (which is composed of three thumbnails). I assume that this one might also suffer from wrong orientation. Probably worth a check, but it is not that obvious as the single images which are being combined for the thumbnail are smaller in size...

![IMG_4937](https://user-images.githubusercontent.com/2866102/96031709-021b7280-0e5e-11eb-8a9d-f6bbd5a08ce3.JPG)
![IMG_4938](https://user-images.githubusercontent.com/2866102/96031762-13647f00-0e5e-11eb-8369-d987c3142b94.JPG)

**Comment by bigcookie** [comment]
Sorry for the picture size. I didnt want alter anything on them and leave them as original...

**Comment by cvium** [comment]
This is what I'm getting on the latest master:
![image](https://user-images.githubusercontent.com/675118/96089701-82c28900-0ec7-11eb-9bce-6704d6b28f44.png)

**Comment by bigcookie** [comment]
Interesting, I get the picture as attached.

My system:
Server: QNAP TS-653B
Version: 10.6.2
Operating System: Linux
Architecture: X64

<img width="252" alt="Screenshot 2020-10-15 at 10 49 52" src="https://user-images.githubusercontent.com/2866102/96100181-5eb97480-0ed4-11eb-8005-b4301da6ccbf.png">

**Comment by bigcookie** [comment]
Sorry, I just noted that I answered to the wrong bug on pictures. Please forget my answers.

At the moment with the latest build, I will initiate a new scan and check. Sorry for me mixing up things...!!!

**Comment by bigcookie** [comment]
Now the correct item... Sorry again.

I dont see anymore stops at a specific image in the scan. Nevertheless the scan still doesnt complete.
1. attempt stopped at an additional video file (.mov) where image extraction failed.
```
[2020-10-15 09:28:27.446 +00:00] [ERR] [137] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for file:"/media/Bilder/0001 - Kita Elia/Videos/Video 19-02-27 11-38-21 1152.mov"
[2020-10-15 09:28:27.447 +00:00] [ERR] [137] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: I-frame image extraction failed, will attempt standard way. Input: "file:\"/media/Bilder/0001 - Kita Elia/Videos/Video 19-02-27 11-38-21 1152.mov\""
System.Exception: ffmpeg image extraction failed for file:"/media/Bilder/0001 - Kita Elia/Videos/Video 19-02-27 11-38-21 1152.mov"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
[2020-10-15 09:28:57.269 +00:00] [INF] [43] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "f84654583da86db68d7903e00507c3de"
[2020-10-15 09:28:57.337 +00:00] [ERR] [43] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(IEnumerable`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItem(MetadataResult`1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

2. I dont know where why one failed:
```
[2020-10-15 09:32:16.169 +00:00] [ERR] [71] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(IEnumerable`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItem(MetadataResult`1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

**Comment by bigcookie** [comment]
The issue I noticed is another one. The original one seems to be fixed.
I am closing this ticket therefore
