### ISSUE TITLE
Start wizard doesn't show languages on Jellyfin nightly

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin#3328]
**Describe the bug**
Wizard can't be completed if someone install Jellyfin from scratch using Nightly or built from source.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox and Vivaldi. Edge didn't even show anything, it just load a black page.
 - Jellyfin Version: 10.6.0 nightly built yesterday.
 - Playback: 
 - Installed Plugins:
 - Reverse Proxy: nope
 - Base URL: nope
 - Networking:
 - Storage:

**To Reproduce**

1. Install Jellyfin nightly fresh.
2. Start Jellyfin.
3. Enter local IP.
4. Wizard wont load completely.

**Expected behavior**

Be able to pick a language.

**Logs**
There is nothing on the log.

**Screenshots**

![firefox_2020-06-12_20-50-25](https://user-images.githubusercontent.com/9301204/84557175-79919780-acee-11ea-89c0-31388c814d75.png)

It shows that loading animation forever, and the language list doesn't show anything either.

**Comment by coltstrgj** [comment]
I am also having this issue with the nightly docker and an empty config folder.

**Comment by ManfredRichthofen** [comment]
Same Issue also with the nightly docker

**Comment by LSchallot** [comment]
It looks like the application is looking for the wrong endpoint.  When navigating to "<HOST>/web/index.html", the resources are attempting to be loaded from "<HOST>/jellyfin" which returns a 404.

A specific example would be the GetUTCTime endpoint.
My server's address:  http://unstable.lab:8096/web/index.html
GetUTCTime request (returns 404):  http://unstable.lab:8096/jellyfin/GetUTCTime

**Comment by dmitrylyzo** [comment]
I cleared `/etc/jellyfin` and `/var/lib/jellyfin`.
Wizard is still broken.

Server: nightly-20200620 Ubuntu 18.04
Client: web jellyfin/jellyfin-web@bef977062e7cde96716efa23a98d06c4285e8f28
```
GET http://IP:8096/Startup/Configuration net::ERR_ABORTED 500 (Internal Server Error)
```
```
[2020-06-20 11:48:47.924 +03:00] [ERR] [5] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HM0KUQ88MDVO"", Request id ""0HM0KUQ88MDVO:00000033"": An unhandled exception was thrown by the application.
MediaBrowser.Controller.Authentication.AuthenticationException: Access token is required.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateSecurityToken(IRequest request, String token)
   at Emby.Server.Implementations.HttpServer.Security.AuthService.ValidateUser(IRequest request, IAuthenticationAttributes authAttribtues)
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request, IAuthenticationAttributes authAttributes)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Ullmie02** [comment]
I think I found the problem. This specific API controller uses the new ASP.NET WebApi endpoint. But the authorization code tries to authorize using the old authorization attributes.
The controller is working in the `api-migration` branch because of #3357 by @crobibero. I think we would need to implement changes similar to the ones in the PR. I'll work on that.

**Comment by nati-mask** [comment]
I've **exactly** the same issue now with the first startup wizard when building from source (I need not to make a screenshot, it's the same as above) also loader is showing forever.

I just built the server from source at [v10.6.4](https://github.com/jellyfin/jellyfin/tree/v10.6.4) using `dotnet build ..`
I've built the **jellyfin-web** files from source at [v10.6.4](https://github.com/jellyfin/jellyfin-web/tree/v10.6.4) on a different system and copied the files into `jellyfin-web` directory in the jellyfin server binary directory.

Output of console at web client side (updated chromium 86.0):
```
Begin ConnectionManager constructor
11:29:02.427 credentials.js:8 credentials initialized with: {}
11:29:02.586 connectionManager.js:836 Begin connect
11:29:02.586 connectionManager.js:494 Begin getAvailableServers
11:29:02.587 > site.js:610 serviceWorker unsupported
11:29:02.594 connectionManager.js:558 Begin connectToServers, with 0 servers
11:29:02.663 > start.js:37 Uncaught ReferenceError: ApiClient is not defined
    at HTMLDivElement.<anonymous> (start.js:37)
    at onViewChange (viewManager.js:62)
    at viewManager.js:151
```

There are **no network error** status codes at chrome dev-tools network panel. Only 200 or 304.

Output of the running server:
```
[11:22:47] [INF] [4] Main: Jellyfin version: 10.6.4
[11:22:48] [INF] [4] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/alarm/.local/share/jellyfin/log]"]
[11:22:48] [INF] [4] Main: Arguments: ["/home/alarm/bin/jellyfin-v10.6.4/jellyfin.dll"]
[11:22:48] [INF] [4] Main: Operating system: Linux
[11:22:48] [INF] [4] Main: Architecture: Arm
[11:22:48] [INF] [4] Main: 64-Bit Process: False
[11:22:48] [INF] [4] Main: User Interactive: True
[11:22:48] [INF] [4] Main: Processor count: 4
[11:22:48] [INF] [4] Main: Program data path: /home/alarm/.local/share/jellyfin
[11:22:48] [INF] [4] Main: Web resources path: /home/alarm/bin/jellyfin-v10.6.4/jellyfin-web
[11:22:48] [INF] [4] Main: Application directory: /home/alarm/bin/jellyfin-v10.6.4/
[11:22:49] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/alarm/.cache/jellyfin
[11:22:49] [INF] [4] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[11:23:06] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[11:23:06] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/alarm/.cache/jellyfin
[11:23:13] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Marking all known migrations as applied because this is a fresh install
[11:23:13] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddDefaultPluginRepository'
[11:23:13] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[11:23:13] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/alarm/.cache/jellyfin
[11:23:13] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddDefaultPluginRepository' applied successfully
[11:23:13] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'ReaddDefaultPluginRepository'
[11:23:13] [INF] [4] Jellyfin.Server.Migrations.MigrationRunner: Migration 'ReaddDefaultPluginRepository' applied successfully
[11:23:13] [INF] [4] Main: Kestrel listening on all interfaces
[11:23:14] [INF] [4] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[11:23:15] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 11/02/2020 02:00, which is 14:36:44.9061332 from now.
[11:23:15] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1
[11:23:15] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "hevc", "mpeg2video", "mpeg4", "msmpeg4", "aac", "ac3", "mp3"]
[11:23:16] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_omx", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[11:23:16] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "vaapi", "drm"]
[11:23:16] [INF] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: /usr/bin/ffmpeg
[11:23:16] [INF] [4] Emby.Server.Implementations.ApplicationHost: ServerId: 9ef6340a2d74443da208a94c2b71ca9a
[11:23:18] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[11:23:18] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
[11:23:18] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[11:23:19] [INF] [11] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.2.9
[11:23:20] [INF] [11] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:03.3365708
[11:23:20] [INF] [11] Emby.Server.Implementations.ApplicationHost: Core startup complete
[11:23:22] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 4 seconds
[11:23:24] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[11:23:24] [INF] [11] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:04.4489983
[11:23:24] [INF] [11] Main: Startup complete 0:00:38.8111326
[11:24:42] [WRN] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 192.168.2.12. Time (slow): 0:00:01.8062783. http://192.168.2.9:8096/web/bundle.js?v=1
```

Doing the same workflow on the same infrastructure workd **good** (first setup wizard + watching movie) with **10.5.5** version.

Thank you guys for all of the hard work! Amazing

**Comment by nati-mask** [comment]
Tried also with versions from master branch. Same problem.
master versions doesn't send me directly to the wizard, I had to paste the wizard url, and then same problem appears. No languages, infinite spinner, can't do "next"

**Comment by crowforged** [comment]
still an issue

**Comment by felix920506** [comment]
Please open a new report.

**Comment by felix920506** [comment]
Please open a new report.
