### ISSUE TITLE
Failed to bind to address http://[::]:8096: address already in use(how do we solve this error)

### ISSUE THREAD

**Issue by azim254** [jellyfin/jellyfin#3370]
```
$ jellyfin
[11:54:21] [INF] [1] Main: Jellyfin version: 10.5.5
[11:54:21] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[11:54:21] [INF] [1] Main: Operating system: Linux
[11:54:21] [INF] [1] Main: Architecture: X64
[11:54:21] [INF] [1] Main: 64-Bit Process: True
[11:54:21] [INF] [1] Main: User Interactive: True
[11:54:21] [INF] [1] Main: Processor count: 4
[11:54:21] [INF] [1] Main: Program data path: /root/.local/share/jellyfin
[11:54:21] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[11:54:21] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[11:54:22] [INF] [1] ServerConfigurationManager: Setting cache path: /root/.cache/jellyfin
[11:54:22] [INF] [1] App: Loading assemblies
[11:54:23] [INF] [1] Main: Kestrel listening on all interfaces
[11:54:23] [FTL] [1] Microsoft.AspNetCore.Server.Kestrel: Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[11:54:23] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in system.xml and try again.
[11:54:23] [FTL] [1] Main: Error while starting server.
System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[11:54:23] [INF] [1] App: Disposing CoreAppHost
[11:54:23] [INF] [1] App: Disposing ActivityLogWebSocketListener
[11:54:23] [INF] [1] App: Disposing SessionInfoWebSocketListener
[11:54:23] [INF] [1] App: Disposing ScheduledTasksWebSocketListener
[11:54:23] [INF] [1] App: Disposing SessionWebSocketListener
[11:54:23] [INF] [1] App: Disposing EmbyTV
[11:54:23] [INF] [2] Main: Received a SIGTERM signal, shutting down


```

**Comment by anthonylavado** [comment]
This means that Jellyfin or Emby (or something else) is already using that port.

If you installed on Linux, are you sure it's not already running as a service?

**Comment by azim254** [comment]
> This means that Jellyfin or Emby (or something else) is already using that port.
> 
> If you installed on Linux, are you sure it's not already running as a service?

its interesting that when I check what's running on the port is jellyfin
