### ISSUE TITLE
JF doesn't show/load all genres

### ISSUE THREAD

**Issue by internetfreak** [jellyfin/jellyfin#3408]
**Describe the bug**
I have recently reworked all tagging for my music library and added it to JF again to let it pick up the metadata. However, when I check the "Genre" page for my music, I notice that there are some things missing. For example, I have a few albums which I tagged with genre "Trance" and while JF shows it on the media page, when I click on it, it loads indefinitely and the genre also never appears on the genre collection

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: KVM
 - Clients: Web
 - Browser: Firefox 77.0.1
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: Anime, Fanart, default Plugins
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridging
 - Storage: local mounted virtual disks

**To Reproduce**
1. Tag a file with genre "Trance"
2. Upload it to a music lib on JF
3. Wait for it to be indexed, then click on it
4. See that JF says it's trance, now click on the genre
5. It should load indefinitely, if you check the genre page, it should not appear

**Expected behavior**
All genres get picked up and displayed

**Logs**
None, but if there's any, I will supply

**Screenshots**
None

**Additional context**
None

EDIT 11:49pm: Other genres are affected as well, no matter if made-up or officially included in ID3. More examples of affected tags: Acoustic, Electronic Dance Music (this one I assigned to various albums by myself as they weren't easy to tag due to their various genres)

**Comment by stewood** [comment]
I have just run into the same issue with genre page just spinning forever.

The browser is getting a 500 error from http://my.server.address/Users/2334def46f234a87bed68041c80bf287/Items/b107bfeafd04ed7af2fa79703bf63661 (Where b107bfeafd04ed7af2fa79703bf63661 is the genre id)

The Jellyfin log shows:

`[2020-07-18 15:16:51.467 +00:00] [ERR] [128] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://my.server.address/Users/2334def46f234a87bed68041c80bf287/Items/b107bfeafd04ed7af2fa79703bf63661"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at MediaBrowser.Api.UserLibrary.UserLibraryService.Get(GetItem request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by OdinGitDat** [comment]
I'm having the same issue. This is my log after clicking on the genre.

```
[22:34:02] [ERR] [37] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://domain.com/Users/a384073bbcc14dca946b60790fb530a7/Items/9854f1caebf5a98af7a6e712cb808ccd
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at MediaBrowser.Api.UserLibrary.UserLibraryService.Get(GetItem request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[22:34:02] [DBG] [37] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to http://jellyfin.odin.space/Users/a384073bbcc14dca946b60790fb530a7/Items/9854f1caebf5a98af7a6e712cb808ccd
```

**Comment by itsthejoker** [comment]
I am also seeing this issue on 10.6.3 in Docker. Same error message as @OdinGitDat.

**Comment by dannymichel** [comment]
> I am also seeing this issue on 10.6.3 in Docker. Same error message as @OdinGitDat.

Any idea if this has been addressed?
