### ISSUE TITLE
[10.6] Unstable: ResourceFileManager.GetResourcePath: Null Pointer exception

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3497]
Put a typo in the url - and got this

[2020-07-03 20:14:09.573 +01:00] [ERR] [99] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.5:8096/web/"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ResourceFileManager.GetResourcePath(String basePath, String virtualPath) in C:\code\jellyfin\Emby.Server.Implementations\ResourceFileManager.cs:line 25
   at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request) in C:\code\jellyfin\MediaBrowser.WebDashboard\Api\DashboardService.cs:line 337
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in C:\code\jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) in C:\code\jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 82
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\code\jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 495
[2020-07-03 20:14:23.972 +01:00] [ERR] [130] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for "/config"
[2020-07-03 20:14:23.972 +01:00] [ERR] [130] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Unable to find the specified file". URL: "http://192.168.1.5:8096/config.json?nocache=236"

Looks to be either with basePath or virtualPath being null.

public string GetResourcePath(string basePath, string virtualPath)
{
    var fullPath = Path.Combine(basePath, virtualPath.Replace('/', Path.DirectorySeparatorChar));

**Comment by BaronGreenback** [comment]
PR #3571
