### ISSUE TITLE
[10.6] Unstable: Emby.dnla.PlayTo.Device - Null pointer

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3498]
Root cause:
line 726:  var trackUri = trackUriElem == null ? **null** : trackUriElem.Value;

this is passed as the 2nd param on CreateUBaseObject (line 783) which is assigned to return object if url is null.

var url = container.GetValue(uPnpNamespaces.Res); (line 832)

Fast forward to the exception: 
[2020-07-03 20:37:44.059 +01:00] [ERR] [113] Emby.Dlna.Main.DlnaEntryPoint: Error reporting playback stopped
System.ArgumentNullException: Value cannot be null. (Parameter 'url')
   at Emby.Dlna.PlayTo.PlayToController.StreamParams.ParseFromUrl(String url, ILibraryManager libraryManager, IMediaSourceManager mediaSourceManager) in C:\code\jellyfin\Emby.Dlna\PlayTo\PlayToController.cs:line 855
   at Emby.Dlna.PlayTo.PlayToController.OnDevicePlaybackStopped(Object sender, PlaybackStoppedEventArgs e) in C:\code\jellyfin\Emby.Dlna\PlayTo\PlayToController.cs:line 177

Looks to be the result of an invalid xml response from the tv.

Will do more testing and put in a PR.

**Comment by BaronGreenback** [comment]
Rewritten code
