### ISSUE TITLE
500 error on Devices page

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#352]
Hi,
When trying to view the Devices page, it does not load and the server instead throws an exception:
```
2019-01-01 14:48:18.308 Info HttpServer: HTTP GET http://<emby>:8096/Devices. UserAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2019-01-01 14:48:18.312 Error HttpServer: Error processing request
        *** Error Report ***
        Version: 3.5.2.0
        Command line: /usr/lib/jellyfin/bin/jellyfin.dll -programdata /var/lib/jellyfin -restartpath /usr/lib/jellyfin/restart.sh
        Operating system: Unix 4.13.0.1
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 8
        Program data path: /var/lib/jellyfin
        Application directory: /usr/lib/jellyfin/bin
        System.NullReferenceException: Object reference not set to an instance of an object.
           at Emby.Server.Implementations.Devices.DeviceManager.GetDevices(DeviceQuery query) in /repo/Emby.Server.Implementations/Devices/DeviceManager.cs:line 153
           at lambda_method(Closure , Object , Object )
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
        System.NullReferenceException
           at Emby.Server.Implementations.Devices.DeviceManager.GetDevices(DeviceQuery query) in /repo/Emby.Server.Implementations/Devices/DeviceManager.cs:line 153
           at lambda_method(Closure , Object , Object )
           at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 92
           at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /repo/Emby.Server.Implementations/Services/ServiceController.cs:line 179
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660

2019-01-01 14:48:18.312 Info HttpServer: HTTP Response 500 to <client-ip>. Time: 4ms. http://<emby>:8096/Devices
```

this is with the jellyfin 3.5.2-5 debian package:
```
dpkg -l | grep jelly
ii  jellyfin                          3.5.2-5                           amd64        Jellyfin is a home media server.
```

There are some more of these snags that I'm trying to sniff out because it would be really nice to get the fork fully functional as intended :)

This also affects the Users->user->Access page, and as a result I think an admin needs to sign in on any new device to authenticate the device so other users can then sign in.. It looks a bit like this:

POST https://<emby>/Users/authenticatebyname -> 401 / User is not allowed access from this device.

This goes away after an admin signs in on that device and I think this will be more debuggable when the error above is resolved :)
I have double checked now, and the user needs to be allowed to manage the server in order to have the server accept the new device

**Comment by hawken93** [comment]
Same as #339, this is what causes the symptom. At least in my experience..

**Comment by alashow** [comment]
Could it be related to 404 errors in "Download & Sync" page?
The page requests https://server.com/emby/Sync/Jobs?UserId=<myid> and it fails with 404.

**Comment by cvium** [comment]
Download & Sync is a closed source module, which we don't have, so it's unrelated

**Comment by hawken93** [comment]
I have recompiled 3.5.2-5 and tried again with that, still errors on line 153. I'm currently compiling dev to check if the bugfix above does anything for this bug :)

**Comment by hawken93** [comment]
OK, somehow it works now with the dev branch. So that bugfix somehow fixed it. Cool! I think this can be closed now. I also checked that the user->access page works. I think this can be closed unless someone else should test as well

**Comment by hawken93** [comment]
I'm just going to go ahead and... *click*
