### ISSUE TITLE
Error on library scan

### ISSUE THREAD

**Issue by Pikoh** [jellyfin/jellyfin#3531]
First of all, I'm new to JellyFin and I want to thank all the people working in this great project.

I'm experiencing some problems, I think when the system tries to scan some music folders in my collection. It starts ok, but at some point it stucks (now at 33% for example).

Diving through the logs, I see this exception:

```
[2020-07-11 12:14:11.489 +02:00] [INF] Starting Library Sync...
[2020-07-11 12:15:16.497 +02:00] [ERR] Error processing request. URL: "http://192.168.1.40:8096/Users/83d28c821a3748ed99729d7f02b66063/Items?Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&Ids=0b3f5d074416ba0201931cbe748e46f2%2C378642437fbc6ed01cfe3977a8aa2c5d%2Cf2ee882d718ea25557e66176fbdb0ecc%2C906ac09144b04d3986ae6f51810970a2%2C3f4a9f06822a5e360d1a956e073467e2%2C3fb4516adf8cba78c243ec45d79746e4%2Cae8598464b56b0f32310d4b5fa724053%2Ca3a8e13faad95de07892ac400f2ed97a"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Controller.Entities.Folder.SortItemsByRequest(InternalItemsQuery query, IReadOnlyList`1 items)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
I'm sorry if this has been already reported, i've searched but didn't found this error anywhere else.

**Comment by oddstr13** [comment]
I saw this error on Kodi incremental startup sync

jellyfin-server 20200730.2-unstable

```python
2020-08-06 02:09:46.253 T:31939    INFO <general>: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:123 500 Server Error: Internal Server Error for url: http://{jellyfin-server}/Users/7b2664944327497a9e2b200138f22671/Items?Ids=4e5b93a45fe336878a72a2ba03ac59d0%2C8fdaf7f895dc682a08ac03c874f20296%2C577ef9d4e2ea7a6812636e2bd89a39d0%2C4448e446f80c78863862e78cd0621120%2C893b70c7e9d6d2afbbb69a41e1567049%2C967648fe92438d95c1ac79a84f34e749%2C6315f631c8cec5aaf24d0f6ff4feba0a%2C886023c169ef74edc84601cd9726c26a%2C483c893105f243a2dd5c9ad0ce7974e8%2C7ede35f9a7ff3dc912a9d2b2276aa9b5%2Cd211faaac13b6428df3b7fd623e79cf1%2C88e879a350687e80a90cc3beea0db621%2C32e909334cc05a330bbe37f80a57c47f%2Ca3e12aaacfe06afd45486ce32e952fc7%2C60574c1ca6753f5c43365644eab9c2b7&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio
2020-08-06 02:09:46.254 T:31939    INFO <general>: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:138 --[ 500 response ] 500 Server Error: Internal Server Error for url: http://{jellyfin-server}/Users/7b2664944327497a9e2b200138f22671/Items?Ids=4e5b93a45fe336878a72a2ba03ac59d0%2C8fdaf7f895dc682a08ac03c874f20296%2C577ef9d4e2ea7a6812636e2bd89a39d0%2C4448e446f80c78863862e78cd0621120%2C893b70c7e9d6d2afbbb69a41e1567049%2C967648fe92438d95c1ac79a84f34e749%2C6315f631c8cec5aaf24d0f6ff4feba0a%2C886023c169ef74edc84601cd9726c26a%2C483c893105f243a2dd5c9ad0ce7974e8%2C7ede35f9a7ff3dc912a9d2b2276aa9b5%2Cd211faaac13b6428df3b7fd623e79cf1%2C88e879a350687e80a90cc3beea0db621%2C32e909334cc05a330bbe37f80a57c47f%2Ca3e12aaacfe06afd45486ce32e952fc7%2C60574c1ca6753f5c43365644eab9c2b7&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio
2020-08-06 02:09:46.255 T:31939    INFO <general>: JELLYFIN.downloader -> ERROR::jellyfin_kodi/downloader.py:367 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/downloader.py", line 354, in run
                                                       for item in result['Items']:
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   
```
```csharp
[2020-08-06 00:09:45.949 +00:00] [ERR] [852] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://{jellyfin-server}/Users/7b2664944327497a9e2b200138f22671/Items?Ids=4e5b93a45fe336878a72a2ba03ac59d0%2C8fdaf7f895dc682a08ac03c874f20296%2C577ef9d4e2ea7a6812636e2bd89a39d0%2C4448e446f80c78863862e78cd0621120%2C893b70c7e9d6d2afbbb69a41e1567049%2C967648fe92438d95c1ac79a84f34e749%2C6315f631c8cec5aaf24d0f6ff4feba0a%2C886023c169ef74edc84601cd9726c26a%2C483c893105f243a2dd5c9ad0ce7974e8%2C7ede35f9a7ff3dc912a9d2b2276aa9b5%2Cd211faaac13b6428df3b7fd623e79cf1%2C88e879a350687e80a90cc3beea0db621%2C32e909334cc05a330bbe37f80a57c47f%2Ca3e12aaacfe06afd45486ce32e952fc7%2C60574c1ca6753f5c43365644eab9c2b7&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio"
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Controller.Entities.Folder.SortItemsByRequest(InternalItemsQuery query, IReadOnlyList`1 items)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by Pikoh** [comment]
Could be @oddstr13. I have kodi installed in the same machine with the jellyfin plugin.

**Comment by JagexDark** [comment]
Getting this issue after upgrading to 10.8.1 from 10.7.7. Stack trace is pretty similar, same error occurring in SortItemsByRequest from a /Users/blah/Items request
