### ISSUE TITLE
Getting LibraryManager error in the log about a missing JSON file

### ISSUE THREAD

**Issue by tphillip913** [jellyfin/jellyfin#3568]
**Describe the bug**
When the LibraryManager goes to validate the medial library it hits a movie (Bollywood in nature) is spits out the following in the log (See below). The directory specified in the path for the .json file does not exist at all but many others do.

**System (please complete the following information):**
 - OS: unRAID
 - Virtualization: Docker
 - Clients: Web browser (Pick your preferred vendor)
 - Browser: For this log view MS Edge
 - Jellyfin Version: 10.5.5
 - Playback: N/A
 - Installed Plugins: Anime, AudioDB, Auto Organize, Email Notifications, MusicBrainz, Open Subtitles, Reports, YoutubeMetadata
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: local JBOD/unRAID

**To Reproduce**
In this case I'm doing nothing. the LibraryManager seems to run on a set schedule within Jellyfin and the directory and movie file follow proper Jellyfin naming schemes

**Expected behavior**
I would expect it to treat the movie as any other and continue on. It doesn't (See logs)

**Logs**
[2020-07-15 16:27:09.528 -04:00] [INF] [10] LibraryManager: Validating media library
...many movies later...
[2020-07-15 16:32:00.805 -04:00] [ERR] [11] App: Error in "TheMovieDb"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/cache/tmdb-movies2/682725/all-en.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Emby.Server.Implementations.Serialization.JsonSerializer.OpenFile(String path)
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
   at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Screenshots**
N/A

**Additional context**
This is a Bollywood movie, but not my only one. This has the earmarks of a bug as its the only movie this is happening to, but if there's steps I should try I'll give it a shot.

**Comment by BaronGreenback** [comment]
Bug: GenericTmdbMovieInfo.cs [104] calls EnsureMovieInfo, which in turn can call DownloadMovieInfo if the file doesn't exist.
If fetchMainResult fails it returns null no file is ever created, but line [107] makes the assumption that the file is present which it where it crashes.

To ensure this 100% can you send me the name of the movie so i can try and replicate here.

Also, are there any other errors prior to this one?

**Comment by tphillip913** [comment]
The movie is Commando 3 (https://www.imdb.com/title/tt8983168/?ref_=nv_sr_srsg_0), it is the only error, and it's the last one (No other movie lists an error of any type during this process). The filename is "Commando 3 (2019).mkv"
