### ISSUE TITLE
Update plugins failed, blocking application startup

### ISSUE THREAD

**Issue by kifeo** [jellyfin/jellyfin#3572]
**Describe the bug**
The update plugins task fails for 'Resource temporarily unavailable' reason, and blocks application startup
From the firewall logs, no external connection attempt was made.
Also no url displayed in the log.

**System (please complete the following information):**
 - Virtualization: Docker / kubernetes
 - Jellyfin Version: 10.5.5, 10.6.0
 - Installed Plugins: organize media

**Expected behavior**
The failure of connection to an upgrade check of a plugin should not block the application startup

**Logs**
```
[13:56:02] [INF] [11] TaskManager: StartupTrigger fired for task: Update Plugins
[13:56:02] [INF] [11] TaskManager: Queueing task PluginUpdateTask
[13:56:02] [INF] [10] TaskManager: Executing Update Plugins
[13:56:22] [ERR] [11] TaskManager: Error
System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackages(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+MoveNext()
   at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[13:56:22] [INF] [11] TaskManager: Update Plugins Failed after 0 minute(s) and 20 seconds
[13:56:22] [INF] [11] TaskManager: ExecuteQueuedTasks
```

**Additional context**
This happened after the install of the (only) 'organize media' plugin

**Comment by kifeo** [comment]
also if one of you does have a method to uninstall the plugin without the running application as a workaround, it would be very nice from you :D

**Comment by crobibero** [comment]
> 
> 
> also if one of you does have a method to uninstall the plugin without the running application as a workaround, it would be very nice from you :D

You can just remove the offending plugin from the plugins directory

**Comment by kifeo** [comment]
thanks @crobibero , weird I do not have a plugin directory :

> 0 drwxr-xr-x 2 1001 1002    0 Jul 16 16:29 cache
> 0 drwxr-xr-x 6 1001 1002    4 Jul 16 16:29 data
> 0 drwxr-xr-x 4 1001 1002    2 Jul 16 16:29 dlna
> 1 -rw-r--r-- 1 1001 1002  933 Jul 16 16:39 encoding.xml
> 0 drwxr-xr-x 2 1001 1002    1 Jul 16 16:29 log
> 2 -rw-r--r-- 1 1001 1002 1362 Jul 16 16:29 logging.default.json
> 2 -rw-r--r-- 1 1001 1002 1166 Jul 16 16:39 migrations.xml
> 7 -rw-r--r-- 1 1001 1002 6162 Jul 16 16:39 system.xml
> 0 drwxr-xr-x 3 1001 1002    1 Jul 16 16:29 users

**Comment by crobibero** [comment]
the plugin directory is one folder back from where you are searching (`../plugins`)

**Comment by kifeo** [comment]
thanks, with the helm chart I use, the plugin directory is not mounted to docker ... I will check this.
