### ISSUE TITLE
Usernames can't be changed if only capitals differ

### ISSUE THREAD

**Issue by DrunkenToast** [jellyfin/jellyfin#3600]
Jellyfin version 10.6.0

Issue: you can't change your username when it's the same or capitals have changed. There is no error handling so the app will just have an infinite loading icon.

Reproduce/example: username "toast" -> "Toast".

Log: System.ArgumentException: The new and old names must be different.

Workaround: "toast" -> "gneirsgnse" -> "Toast"

**Comment by oddstr13** [comment]
Server responds with 400, and web gets stuck on the processing indicator, loading forever in stead of displaying the error about usernames having to be different.

```
[2020-07-20 01:54:45.055 +00:00] [ERR] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://10.79.0.125:8096/Users/8351ccc72e6d43d3a3b03d389cb0d818"
System.ArgumentException: The new and old names must be different.
   at Jellyfin.Server.Implementations.Users.UserManager.RenameUser(User user, String newName)
   at MediaBrowser.Api.UserService.Post(UpdateUser request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
