### ISSUE TITLE
10.6 on Windows Failing to Launch Without Error

### ISSUE THREAD

**Issue by tommytarts** [jellyfin/jellyfin#3607]
**Describe the bug**
Jellyfin upgraded to 10.6, unable to access at all. No other changes made. 

Upon launching, server throws mass errors, and you can't access the server or the web client. Gives "Error Processing Request" message.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: n/a
 - Clients: All
 - Browser: All/Firefox
 - Jellyfin Version: 10.6 Stable
 - Playback: n/a
 - Installed Plugins: n/a
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**
Upgrade Server
Launch Sever

**Expected behavior**
Server opens without issue like it would any other day.

**Logs**
<details>
<summary>Logs from system (click to expand)</summary>

```
[2020-07-20 02:25:05.601 -04:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"RemoveDuplicateExtras"' applied successfully
[2020-07-20 02:25:05.608 -04:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddDefaultPluginRepository"'
[2020-07-20 02:25:05.610 -04:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[2020-07-20 02:25:05.616 -04:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\Jellyfin\cache"
[2020-07-20 02:25:05.618 -04:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"AddDefaultPluginRepository"' applied successfully
[2020-07-20 02:25:05.624 -04:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"MigrateUserDatabase"'
[2020-07-20 02:25:05.628 -04:00] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateUserDb: Migrating the user database may take a while, do not stop Jellyfin.
[2020-07-20 02:25:06.121 -04:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"MigrateUserDatabase"' applied successfully
[2020-07-20 02:25:06.133 -04:00] [INF] [1] Main: Kestrel listening on "192.168.1.29"
[2020-07-20 02:25:06.135 -04:00] [INF] [1] Main: Kestrel listening on "127.0.0.1"
[2020-07-20 02:25:06.214 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2020-07-20 02:25:06.249 -04:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 07/21/2020 02:00, which is 23:34:53.7509998 from now.
[2020-07-20 02:25:06.304 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.1"
[2020-07-20 02:25:06.353 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-07-20 02:25:06.396 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-07-20 02:25:06.429 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2020-07-20 02:25:06.432 -04:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: "C:\Program Files\Jellyfin\Server\ffmpeg.exe"
[2020-07-20 02:25:06.434 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "98a315458c8f4369819f5c1c2951b900"
[2020-07-20 02:25:06.511 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0690601
[2020-07-20 02:25:06.512 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2020-07-20 02:25:06.557 -04:00] [INF] [1] Emby.Server.Implementations.Library.LibraryManager: Resetting user root folder path to "C:\Users\Tom\AppData\Local\jellyfin\root\default"
[2020-07-20 02:25:06.608 -04:00] [INF] [1] Emby.Server.Implementations.Library.LibraryManager: Resetting root folder path to "C:\Users\Tom\AppData\Local\jellyfin\root"
[2020-07-20 02:25:06.658 -04:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory S:\Tom's Rips
[2020-07-20 02:25:06.658 -04:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory C:\Users\Tom\AppData\Local\jellyfin\data\collections
[2020-07-20 02:25:06.658 -04:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory S:\Howard Stern
[2020-07-20 02:25:06.860 -04:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.3461843
[2020-07-20 02:25:06.861 -04:00] [INF] [1] Main: Startup complete 0:00:19.2401411
[2020-07-20 02:25:07.396 -04:00] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/index.html"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:07.468 -04:00] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/favicon.ico"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:09.124 -04:00] [ERR] [5] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/components/serviceworker/notifications.js"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:09.124 -04:00] [ERR] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/serviceworker.js"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:09.264 -04:00] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-07-20 02:25:09.266 -04:00] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "PluginUpdateTask"
[2020-07-20 02:25:09.269 -04:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2020-07-20 02:25:09.489 -04:00] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2020-07-20 02:25:09.728 -04:00] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2020-07-20 02:25:30.680 -04:00] [ERR] [4] Emby.Dlna.Main.DlnaEntryPoint: Error creating PlayTo device.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.CreateuPnpDeviceAsync(Uri url, IHttpClient httpClient, IServerConfigurationManager config, ILogger logger, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToManager.AddDevice(UpnpDeviceInfo info, String location, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToManager.OnDeviceDiscoveryDeviceDiscovered(Object sender, GenericEventArgs`1 e)
[2020-07-20 02:25:30.720 -04:00] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/system/ping"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:30.736 -04:00] [INF] [19] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
DeviceDescription:
FriendlyName:RX-V481 DC7F56
Manufacturer:Yamaha Corporation
ManufacturerUrl:http://www.yamaha.com/
ModelDescription:AV Receiver
ModelName:RX-V481
ModelNumber:V481
ModelUrl:http://www.yamaha.com/
SerialNumber:0CF67483

[2020-07-20 02:25:30.751 -04:00] [INF] [19] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "RX-V481 DC7F56" - "RX-V481"
[2020-07-20 02:25:52.758 -04:00] [ERR] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/index.html"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:52.804 -04:00] [ERR] [24] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/favicon.ico"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:53.769 -04:00] [ERR] [31] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/components/serviceworker/notifications.js"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:25:53.770 -04:00] [ERR] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web/serviceworker.js"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:06.266 -04:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Update Plugins"
[2020-07-20 02:26:06.268 -04:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "PluginUpdateTask"
[2020-07-20 02:26:06.269 -04:00] [INF] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2020-07-20 02:26:06.273 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2020-07-20 02:26:06.365 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2020-07-20 02:26:59.549 -04:00] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/system/info/public"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:59.579 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/system/info/public"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:59.596 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/Users/970ffa8c4d4c46ae93fdde22cb67a593"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:59.596 -04:00] [ERR] [15] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/system/info/public"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:59.609 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/Users/970ffa8c4d4c46ae93fdde22cb67a593"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:26:59.622 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/Users/970ffa8c4d4c46ae93fdde22cb67a593/Views"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:27:20.846 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/Users/970ffa8c4d4c46ae93fdde22cb67a593/Views"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 02:27:20.910 -04:00] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.29:8096/favicon.ico"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
</details>

**Comment by mindcombatant** [comment]
I am encountering a similar issue on an Ubuntu 20.04 host, installed and updated via repository.
every time i try to load any page, i get only ```Error processing request.``` on an otherwise blank page, and this in logs:
```
[2020-07-20 00:02:47.496 -07:00] [ERR] Error processing request. URL: "http://localhost:8096/favicon.ico"
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
Issues only started after update to ```Jellyfin.Server 10.6.0.0```, Android client also can't connect.

**Comment by jasimancas** [comment]
Same here in Debian 10 "An invalid IP address was specified."

**Comment by tommytarts** [comment]
Don't do anything too crazy. Rolled back to 10.5.5, replaced my old data, and now I lost all of my users. Only thing that remains is watch status for my account and metadata.

**Comment by jasimancas** [comment]
Fixed:
In /config/system.xml
I have:
  <LocalNetworkAddresses>
    <string>0.0.0.0</string>
  </LocalNetworkAddresses>

Deleted:
<LocalNetworkAddresses>
    <string>0.0.0.0</string>

only have </LocalNetworkAddresses>
Save, reboot Jelly and work.
@mindcombatant try this, duplicate system.xml first.

**Comment by Nazar78** [comment]
It's the LocalNetworkAddresses string in the system.xml which is causing the issue:
~/.config/jellyfin/system.xml
Replace:
```
  <LocalNetworkAddresses>
    <string>192.168.1.6</string>
  </LocalNetworkAddresses>
```
To:
```
  <LocalNetworkAddresses />
```
Then restart now everything ok but the IP binding is broken.

**Comment by mirolm** [comment]
I can confirm this. In 10.5.5 binding to 127.0.0.1 (i use nginx) worked for me without issues. In 10.6 it fails and the workaround is to remove the setting like @Nazar78 posted

**Comment by BaronGreenback** [comment]
It seems to be crashing at IPAddress.Parse(endpoint) where endpoint is the host name extracted from the request.

(Line 317 @ https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs also introduces a problem, in that if the host happens to be null, the ip parsing will still fail).

**Comment by PabloGrok** [comment]
> It's the LocalNetworkAddresses string in the system.xml which is causing the issue:
> ~/.config/jellyfin/system.xml

Where's that file in Windows?

**Comment by BaronGreenback** [comment]
from memory it's %appdata%\local\jellyfin\data\ for the user.

or c:\programdata\jellyfin\data if it's running as a service.

**Comment by PabloGrok** [comment]
> from memory it's %appdata%\local\jellyfin\data\ for the user.
> 
> or c:\programdata\jellyfin\data if it's running as a service.

I've found it in C:\ProgramData\Jellyfin\Server\config

Thanks!
