### ISSUE TITLE
Error when trying to get image dimensions, Non-success codec result: Unimplemented

### ISSUE THREAD

**Issue by olskar** [jellyfin/jellyfin#3611]
**Describe the bug**
Error thrown when trying to get image dimensions for fanart

**System (please complete the following information):**
 - OS: Ubuntu
 - Jellyfin Version: 20200720.8-unstable 
 - Storage: Local

**Logs**
[DBG] Getting image size for item "Movie" "/media/usb/movies/Falling Down (1993)/fanart.jpg"
[2020-07-20 12:45:07.092 +02:00] [ERR] Cannnot get image dimensions for "/media/usb/movies/Falling Down (1993)/fanart.jpg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate)

Perhaps this is related to https://github.com/jellyfin/jellyfin/issues/3432 but not sure

**Comment by crobibero** [comment]
Can you post the contents of `cat "/media/usb/movies/Falling Down (1993)/fanart.jpg"`

**Comment by doubleplusthink** [comment]
How large is that file? 
ls -alh /media/usb/movies/Falling Down (1993)/fanart.jpg | grep fanart.jpg

I had that same error today and it looks like one of my files was corrupted.  Not sure how it got corrupted, but it was 2.3G in size.  It was nearly impossible to open, but when I finally did get something to be able to view part of it, the file contained this over and over: 
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

Maybe it's a binary file.  I have no clue. Seems pretty sketchy to me.  Please let me know what you find.

**Comment by olskar** [comment]
Hm content of the file seems to be html rather than jpg.

cat gives: <h1>Not Found</h1>

I have remove the file and problem is gone. Should i close this or should jellyfin be handling this some other way?

**Comment by crobibero** [comment]
Depends where the image came from- if Jellyfin created it we should not be downloading an image that isn't a real image.

**Comment by davispuh** [comment]
I'm very getting similar error with 10.6.0

```
[2020-07-24 20:16:25.847 +03:00] [ERR] [27] Emby.Server.Implementations.Library.LibraryManager: Cannnot get image dimensions for "/mnt/Photo/nnn-004.TIF"
Non-success codec result: InvalidInput
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaHelper.cs:line 21
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaEncoder.cs:line 223
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/Library/LibraryManager.cs:line 1909
[2020-07-24 20:16:25.890 +03:00] [ERR] [27] Emby.Server.Implementations.Library.LibraryManager: Cannnot get image dimensions for "/mnt/Photo/nnn-008.TIF"
Non-success codec result: InvalidInput
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaHelper.cs:line 21
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaEncoder.cs:line 223
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/Library/LibraryManager.cs:line 1909
```

**Comment by davispuh** [comment]
For some files also getting same error

```
[2020-07-28 02:34:42.120 +03:00] [ERR] [22] Emby.Server.Implementations.Library.LibraryManager: Cannnot get image dimensions for "/mnt/Photo/P123456.ORF"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaHelper.cs:line 21
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Jellyfin.Drawing.Skia/SkiaEncoder.cs:line 223
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Drawing/ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/Library/LibraryManager.cs:line 1909
```

The files itself are fine
```
$ magick identify /mnt/RAID/Bildes/Bildes/P3070225.ORF
/mnt/Photo/P123456.ORF ORF 3088x2310 3088x2310+0+0 16-bit sRGB 10.2793MiB 0.000u 0:00.001
```

**Comment by the-r0cket06** [comment]
I am seeing this as well on the latest nightly, but not on 10.6.2

Here is the original file I am uploading.
![poster](https://user-images.githubusercontent.com/33729921/89914143-f942c200-dbca-11ea-92dc-f3c311b13f90.jpg)

Here is the file that sits on my server, which when trying to open gives an unsupported or corrupted file
![poster](https://user-images.githubusercontent.com/33729921/89914170-0364c080-dbcb-11ea-9c02-b2195d193bf4.jpg)

This is what I see when uploading a file
![image](https://user-images.githubusercontent.com/33729921/89914315-37d87c80-dbcb-11ea-9e4a-ec4dd55a9981.png)

Then this is what I see after clicking on upload.
![image](https://user-images.githubusercontent.com/33729921/89914386-53dc1e00-dbcb-11ea-9f55-843d305b0781.png)

Here are some logs after enabling debugging.
[2020-08-11 12:09:26.037 -03:00] [DBG] Saving image to "/var/lib/jellyfin/metadata/library/48/48d9a1f817ebde6f14f785c952b892bc/poster.jpg"
[2020-08-11 12:09:26.108 -03:00] [DBG] Getting image size for item "Movie" "/var/lib/jellyfin/metadata/library/48/48d9a1f817ebde6f14f785c952b892bc/poster.jpg"
[2020-08-11 12:09:26.162 -03:00] [ERR] Cannnot get image dimensions for "/var/lib/jellyfin/metadata/library/48/48d9a1f817ebde6f14f785c952b892bc/poster.jpg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate)
[2020-08-11 12:09:26.752 -03:00] [WRN] Slow HTTP Response from "http://10.10.20.65:8096/Items/48d9a1f8-17eb-de6f-14f7-85c952b892bc/Images/Primary" to "::ffff:10.100.10.6" in 0:00:03.2185709 with Status Code 204
[2020-08-11 12:09:27.059 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:27.070 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:28.001 -03:00] [WRN] Slow HTTP Response from "http://10.10.20.65:8096/Users/118ca991-4bb0-485b-910d-6bdd4784fd18/Items/48d9a1f8-17eb-de6f-14f7-85c952b892bc" to "::ffff:10.100.10.6" in 0:00:00.9965582 with Status Code 200
[2020-08-11 12:09:28.134 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:28.157 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:28.361 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:28.362 -03:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-08-11 12:09:28.409 -03:00] [DBG] Getting image size for item "Movie" "/var/lib/jellyfin/metadata/library/48/48d9a1f817ebde6f14f785c952b892bc/poster.jpg"
[2020-08-11 12:09:28.411 -03:00] [ERR] Cannnot get image dimensions for "/var/lib/jellyfin/metadata/library/48/48d9a1f817ebde6f14f785c952b892bc/poster.jpg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate)

**Comment by nyanmisaka** [comment]
Close in https://github.com/jellyfin/jellyfin/pull/4794
