### ISSUE TITLE
Server Seems to Crash When Trying to Use EPUB Reader

### ISSUE THREAD

**Issue by Saamoz** [jellyfin/jellyfin#3617]
**Describe the bug**
Server seemed to crash after an indeterminate amount of time when reading a book on the new 10.6 epub viewer.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: 
 - Clients: Browser
 - Browser: Edge 83.0.478.64
 - Jellyfin Version: 10.6.0
 - Playback: Direct Play for EPUB
 - Installed Plugins: Bookshelf
 - Reverse Proxy: caddy
 - Base URL: none
 - Networking: 
 - Storage: local

**To Reproduce**
1. Open EPUB file with new brower based EPUB reader in Jellyfin 10.6.0
2. Enjoy reading for some time
3. After some time, it will stop responding and the server has crashed

**Expected behavior**
To be able to read the book without crashing

**Logs**
```
[2020-07-20 10:41:23.616 -04:00] [ERR] [62] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for "/socket"
[2020-07-20 10:41:23.621 -04:00] [ERR] [62] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Unable to find the specified file". URL: "http://streaming.saamoz.duckdns.org/socket?deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgzLjAuNDEwMy42MSBTYWZhcmkvNTM3LjM2IEVkZy84My4wLjQ3OC4zN3wxNTkwNjk0NDkyMDA3"
[2020-07-20 10:42:12.396 -04:00] [INF] [62] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.6.0" playing "Rationality". Stopped at "200" ms
[2020-07-20 10:42:12.536 -04:00] [FTL] [62] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'type')
   at Jellyfin.Data.Entities.ActivityLog..ctor(String name, String type, Guid userId)
   at Emby.Server.Implementations.Activity.ActivityLogEntryPoint.OnPlaybackStopped(Object sender, PlaybackStopEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Although it says `unable to find the specified file`, the book does open and I am able to read it for a little while. The crash happens later, in that case it happened at 10:42

**Comment by dkanada** [comment]
cc @barronpm since this could be a database issue

**Comment by cvium** [comment]
We just need a new notification type https://github.com/jellyfin/jellyfin/blob/15aea76523d1ad36ac4a1c8850bd099882c6325d/Emby.Server.Implementations/Activity/ActivityLogEntryPoint.cs#L231-L244

**Comment by dkanada** [comment]
I wonder if we even need media-specific playback notifications.
