### ISSUE TITLE
[10.6] - Reports and Reporting playback plug-ins not working

### ISSUE THREAD

**Issue by the-r0cket06** [jellyfin/jellyfin#3618]
**Describe the bug**
Reports and Playback Reporting plugins not working.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Virtualization: Hyper-V
 - Clients: Browser
 - Browser: Firefox 78.0.2
 - Jellyfin Version: 10.6.0
 - Playback: N/A
 - Installed Plugins: Reports. Playback Reporting
 - Reverse Proxy: Apache
 - Base URL: None
 - Networking: Host
 - Storage: NFS

**To Reproduce**
1 - Go to either Reports or Playback Reporting.
2 - Nothing appears
3 - Check logs and see below exceptions.

Reports
```
[2020-07-20 12:27:41.582 -03:00] [ERR] Error processing request. URL: "http://10.10.20.50:8096/Reports/Items?StartIndex=0&Limit=100&IncludeItemTypes=MusicAlbum&HasQueryLimit=true&GroupBy=None&ReportView=ReportData&DisplayType=Screen&UserId=2185cb1ba9ed4ee5bbab170bb9089dc4&SortOrder=Ascending"
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Entities.User' from assembly 'MediaBrowser.Controller, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
```
Reporting Playback
```
[2020-07-20 12:36:52.314 -03:00] [ERR] Error processing request. URL: "http://10.10.20.50:8096/user_usage_stats/user_activity?days=28&end_date=2020-07-20&stamp=1595259412125"
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Entities.User' from assembly 'MediaBrowser.Controller, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at Jellyfin.Plugin.PlaybackReporting.Api.UserActivityAPI.Get(GetUserReport request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
**Expected behavior**
Plugins should display requested information

**Logs**
See above

**Comment by anthonylavado** [comment]
@the-r0cket06 Have you updated the plugins since installing? They'll need to be updated. You can either do it manually, or it should check with a scheduled task around midnight server time.

**Comment by the-r0cket06** [comment]
Alerts is showing both plugins updated early this morning to version 7.0.0.0 at 1:01am.

When I check the plugins page, both are still showing a version of 6.0.0.0.

**Comment by the-r0cket06** [comment]
Just realized Jellyfin hadn't been restarted since the update last night. All is working as expected with the plugins now.
