### ISSUE TITLE
Database error while starting server

### ISSUE THREAD

**Issue by lazybookwyrm** [jellyfin/jellyfin#3667]
**Describe the bug**
I pulled the new image for Jellyfin to update to 10.6.0 and encountered the error listed in the logs. Deleting the image or creating a new container does not seem to help. I'm assuming a database file may have become corrupted, but am not sure which one. I do have plenty of space on my drive.

**System (please complete the following information):**
 - OS: OMV
 - Virtualization: Docker
 - Jellyfin Version: 10.6.0-2
 - Installed Plugins: none

**Expected behavior**
Server to start

**Logs**
[19:25:54] [INF] [1] Main: Jellyfin version: 10.6.0,
[19:25:54] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CACHE_DIR, /config/cache]"],
[19:25:54] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"],
[19:25:54] [INF] [1] Main: Operating system: Linux,
[19:25:54] [INF] [1] Main: Architecture: X64,
[19:25:54] [INF] [1] Main: 64-Bit Process: True,
[19:25:54] [INF] [1] Main: User Interactive: True,
[19:25:54] [INF] [1] Main: Processor count: 4,
[19:25:54] [INF] [1] Main: Program data path: /config/data,
[19:25:54] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web,
[19:25:54] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/,
[19:25:54] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache,
[19:25:54] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.,
[19:25:55] [ERR] [1] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30'],
SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';,
[19:25:55] [FTL] [1] Main: Error while starting server.,
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.,
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db),
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext(),
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext(),
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult(),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(),
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar(),
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject),
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists(),
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration),
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade),
   at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider),
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions),
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope),
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType),
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType),
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider),
   at Emby.Server.Implementations.ApplicationHost.Resolve[T](),
   at Emby.Server.Implementations.ApplicationHost.InitializeServices(),
   at Jellyfin.Server.Program.StartApp(StartupOptions options),
[19:25:55] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost,
[19:25:55] [INF] [2] Main: Received a SIGTERM signal, shutting down,

**Comment by BaronGreenback** [comment]
Possible cause:- database journal file (ending in -journal) is not writable

**Comment by lazybookwyrm** [comment]
Did further testing, loading 10.5.5 fixes the problem, reloading 10.6.0 reintroduces the problem. Deleting all files in the config file and allowing Jellyfin to recreate them does not fix the problem.

**Comment by xyx208** [comment]
> Did further testing, loading 10.5.5 fixes the problem, reloading 10.6.0 reintroduces the problem. Deleting all files in the config file and allowing Jellyfin to recreate them does not fix the problem.

where is the config file in? thank you!

**Comment by BaronGreenback** [comment]
/config/data
from the look of your setup it's found above.
    On Monday, 27 July 2020, 07:18:19 BST, xyx208 <notifications@github.com> wrote:  
 
 



Did further testing, loading 10.5.5 fixes the problem, reloading 10.6.0 reintroduces the problem. Deleting all files in the config file and allowing Jellyfin to recreate them does not fix the problem.


where is the config file in? thank you!

**Comment by xyx208** [comment]
> Did further testing, loading 10.5.5 fixes the problem, reloading 10.6.0 reintroduces the problem. Deleting all files in the config file and allowing Jellyfin to recreate them does not fix the problem.

thanks!

**Comment by BaronGreenback** [comment]
https://stackoverflow.com/questions/55812960/ioerr-10-message-system-data-sqlite-sqliteexception-0x800007ff-disk-i-o

hints it occurs during high IO operations - but doesn't give any solutions. It does point to multiple other references where this is occurring.

Has your disk got sufficient free space?

**Comment by joe-poff** [comment]
I had the same issue with the same setup:

System:
    OS: OMV
    Virtualization: Docker
    Jellyfin Version: 10.6.0-2
    Installed Plugins: none

my /config was on a CIFS share, when I created a new container with the /config off of the CIFS share it worked.  Having /config on a CIFS worked on jellyfin 10.5.5.

**Comment by lazybookwyrm** [comment]
> I had the same issue with the same setup:
> 
> System:
> OS: OMV
> Virtualization: Docker
> Jellyfin Version: 10.6.0-2
> Installed Plugins: none
> 
> my /config was on a CIFS share, when I created a new container with the /config off of the CIFS share it worked. Having /config on a CIFS worked on jellyfin 10.5.5.

Interesting, mine was on a share too though I don't remember if it was a CIFS share.

I eventually solved the problem by manually creating the new database and then running Jellyfin. The database Jellyfin was creating seemed to be corrupted for some reason

**Comment by vtzompov** [comment]
Getting same issue:
Directly running on Windows 7 64 bit.
Worked for 1 day OK. No changes, PC put to sleep, after wake up, got "jellyfin stopped working...."  And since it will not start.

> [2020-08-30 11:05:36.256 +01:00] [INF] [1] Main: Jellyfin version: "10.6.3"
> [2020-08-30 11:05:36.279 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
> [2020-08-30 11:05:36.285 +01:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
> [2020-08-30 11:05:36.287 +01:00] [INF] [1] Main: Operating system: "Windows"
> [2020-08-30 11:05:36.287 +01:00] [INF] [1] Main: Architecture: X64
> [2020-08-30 11:05:36.289 +01:00] [INF] [1] Main: 64-Bit Process: True
> [2020-08-30 11:05:36.289 +01:00] [INF] [1] Main: User Interactive: True
> [2020-08-30 11:05:36.290 +01:00] [INF] [1] Main: Processor count: 4
> [2020-08-30 11:05:36.291 +01:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
> [2020-08-30 11:05:36.291 +01:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
> [2020-08-30 11:05:36.292 +01:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
> [2020-08-30 11:05:36.514 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
> [2020-08-30 11:05:36.524 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
> [2020-08-30 11:06:18.575 +01:00] [FTL] [1] Main: Error while starting server.
> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

**Comment by BaronGreenback** [comment]
Suspect there is a lock file left over in the database folder.

**Comment by vtzompov** [comment]
what's the C:\ProgramData\Jellyfin\Server\data\jellyfin.db-shm file? After removing it now it's starting again.

**Comment by BaronGreenback** [comment]
Taken from https://stackoverflow.com/questions/7778723/what-are-the-db-shm-and-db-wal-extensions-in-sqlite-databases

As per the SQLite docs, the DB-SHM file is a Shared Memory file, only present when SQLite it running in WAL (Write-Ahead Log) mode. This is because in WAL mode, db connections sharing the same db file must all update the same memory location used as index for the WAL file, to prevent conflicts.

As for WAL file, as hinted above, it is a write log/journal, useful for commits/rollback purposes. If the DB is not running, it is perfectly OK to delete this file, and in fact it would be automatically deleted when restarting the DB if one exists (since it's only useful when the DB is actively writing/committing data).

**Comment by meulop** [comment]
I also had this issue, and the underlying cause was having /config stored on a mergerfs filesystem with cache.files=off (or direct_io set) in the mount options - having this set means the filesystem doesn't support mmap-ed files

**Comment by pciavald** [comment]
i'm having this issue too now, data is stored on a LVM volume on ext4

**Comment by Wastus** [comment]
I was having the same issue as @meulop had. Seeing this thread, maybe it would be worthwhile to integrate this somehow into a troubleshooting section.

**Comment by Gopikrishna19** [comment]
tagging #6129 as the problem still exists. I also use OMV with NFS mounts, and getting the same Disk IO error

**Comment by Kotarou0** [comment]
I had the same problem for almost 2 weeks. I solved it by freeing some space in my disk. 
Thanks @BaronGreenback.
> Has your disk got sufficient free space?

**Comment by ceesios** [comment]
I've worked around this by mounting the nfs share on the host and referring to the local path in docker.
Would be nice to see external database support.

**Comment by std4453** [comment]
Met this case all of a sudden with (seemingly) no obvious trigger event.

A restart did my case, all disks are functional and not full.

Logs directly before the first error:

```
[2022-02-13 17:36:08.379 +08:00] [INF] [68] Emby.Server.Implementations.IO.LibraryMonitor: "Vlad Love" ("/media/anime/Vlad Love") will be refreshed.
[2022-02-13 17:36:08.443 +08:00] [INF] [26] Emby.Server.Implementations.IO.LibraryMonitor: "ç¬¬ 1 å­£" ("/media/anime/Vlad Love/Season 1") will be refreshed.
[2022-02-13 17:36:08.598 +08:00] [ERR] [104] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
Error: SQLitePCL.pretty.SQLiteException: cannot rollback - no transaction is active
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.RollbackTransaction(IDatabaseConnection This)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveImages(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass59_0.<<RefreshChildMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2022-02-13 17:36:08.722 +08:00] [ERR] [104] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(IStatement statement)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter)
   at MediaBrowser.Controller.Entities.Folder.GetRecursiveChildren(Func`2 filter, Boolean includeLinkedChildren)
   at MediaBrowser.Providers.Manager.MetadataService`2.BeforeSaveInternal(TItemType item, Boolean isFullRefresh, ItemUpdateType updateType)
   at MediaBrowser.Providers.Manager.MetadataService`2.BeforeSave(TItemType item, Boolean isFullRefresh, ItemUpdateType currentUpdateType)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2022-02-13 17:36:08.823 +08:00] [ERR] [140] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
```

**Comment by maxs98** [comment]
2022-02-17T14:24:34.008270234Z [22:24:34] [FTL] [1] Main: Error while starting server.
2022-02-17T14:24:34.008304089Z IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
2022-02-17T14:24:34.008323518Z    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
2022-02-17T14:24:34.008338089Z    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
2022-02-17T14:24:34.008342868Z    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
2022-02-17T14:24:34.008347406Z    at SQLitePCL.pretty.StatementImpl.MoveNext()
2022-02-17T14:24:34.008351896Z    at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
2022-02-17T14:24:34.008356524Z    at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
2022-02-17T14:24:34.008361172Z    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
2022-02-17T14:24:34.008366044Z    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
2022-02-17T14:24:34.008385745Z    at Jellyfin.Server.Program.StartApp(StartupOptions options)
2022-02-17T14:24:34.011730793Z [22:24:34] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
2022-02-17T14:24:34.011763778Z [22:24:34] [INF] [2] Main: Received a SIGTERM signal, shutting down
2022-02-17T14:24:34.371171993Z [22:24:34] [INF] [1] Main: Jellyfin version: 10.7.7
2022-02-17T14:24:34.377555050Z [22:24:34] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_PublishedServerUrl, 10.10.10.197]", "[JELLYFIN_LOG_DIR, /config/log]"]
2022-02-17T14:24:34.377637940Z [22:24:34] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
2022-02-17T14:24:34.378329037Z [22:24:34] [INF] [1] Main: Operating system: Linux
2022-02-17T14:24:34.379572648Z [22:24:34] [INF] [1] Main: Architecture: X64
2022-02-17T14:24:34.379597361Z [22:24:34] [INF] [1] Main: 64-Bit Process: True
2022-02-17T14:24:34.379603208Z [22:24:34] [INF] [1] Main: User Interactive: True
2022-02-17T14:24:34.379607647Z [22:24:34] [INF] [1] Main: Processor count: 4
2022-02-17T14:24:34.379611987Z [22:24:34] [INF] [1] Main: Program data path: /config/data
2022-02-17T14:24:34.379617758Z [22:24:34] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
2022-02-17T14:24:34.379622372Z [22:24:34] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
2022-02-17T14:24:34.513296639Z [22:24:34] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
2022-02-17T14:24:34.544942823Z [22:24:34] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2022-02-17T14:24:34.544971789Z [22:24:34] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
2022-02-17T14:24:34.545563411Z [22:24:34] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2022-02-17T14:24:34.551634873Z [22:24:34] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
2022-02-17T14:24:34.551661381Z [22:24:34] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
2022-02-17T14:24:34.566762756Z [22:24:34] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies

**Comment by tyokyo320** [comment]
I had the same problem. I solved the problem by deleting the config file under `/library`

**Comment by RobertS6A** [comment]
@tyokyo320 where is the library at and which config is it?

**Comment by Y0ngg4n** [comment]
I have the same issue on an NFS Share

**Comment by StoryHack** [comment]
I get the same issue in my log. The media all sits on an nfs share, but the config data is on the same machine docker is running on, and has tons of free space.

**Comment by Y0ngg4n** [comment]
@StoryHack exact same setup

**Comment by n8jadams** [comment]
I was mounting `library.db` and `library.db-journal` from a different path in my Dockerized Jellyfin server setup. 

I ran into this error and adjusting permissions fixed it for me.  `chmod 644`'ing the`library.db` and `library.db-journal` files in my case.

**Comment by TheGloriousDuck** [comment]
I had this error on Windows and I fixed it by moving all of the DB files out, and moving each one (jellyfin.db, then library.db, then infuse-sync.db) and replacing the old ones and somehow that did the trick

**Comment by xinmans** [comment]
i change cifs pvc to longhorn pvc to fix it.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin bug. This is a general I/O error thrown by the DB handler when it cannot access the DB on the storage correctly. The actual underlying causes are many. If anyone still experiences this, please visit our support communities on the forums or our Matrix/Discord server with help troubleshooting the underlying issue.
