### ISSUE TITLE
Provided username is not valid (spaces in system username)

### ISSUE THREAD

**Issue by LLBlumire** [jellyfin/jellyfin#3694]
**Describe the bug**
When installing Jellyfin on a windows machine (basic installation, or as a service), and attempting to access the "tell us about yourself" page of the server setup process, an error is thrown if the local username on the windows system contains spaces.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: N/A
 - Browser: N/A (but it's Firefox 78)
 - Jellyfin Version: 10.6 stable
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Local
 - Storage: Local

**To Reproduce**

1. Create a local (not microsoft) account on windows 10
2. Attempt to set up Jellyfin for the first time from this account

**Expected behavior**
The setup should be able to accept inputs and progress beyond the "Tell us about yourself" page.

**Logs**
```
[01:59:31] [INF] [5] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid user
[01:59:31] [WRN] [5] Jellyfin.Server.Implementations.Users.UserManager: No users, creating one with username Lucille L Blumire
[01:59:31] [ERR] [5] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM1G6NPIL3II", Request id "0HM1G6NPIL3II:0000001C": An unhandled exception was thrown by the application.
System.ArgumentException: Provided username is not valid! (Parameter 'Lucille L Blumire')
   at Jellyfin.Server.Implementations.Users.UserManager.Initialize()
   at Jellyfin.Api.Controllers.StartupController.GetFirstUser()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[02:00:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: DailyTrigger fired for task: Extract Chapter Images
[02:00:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task ChapterImagesTask
[02:00:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Extract Chapter Images
[02:00:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Extract Chapter Images Completed after 0 minute(s) and 0 seconds
[02:00:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[02:00:01] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 07/26/2020 02:00, which is 23:59:58.9787481 from now.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6872380/88445534-34976f80-ce1b-11ea-927c-802adf9f1f6b.png)

**Comment by LLBlumire** [comment]
Workaround: change username to one without spaces (https://codeburst.io/changing-a-profile-name-in-windows-9da6c02234e4)
