### ISSUE TITLE
Updating plugins: "Directory not empty"

### ISSUE THREAD

**Issue by tyhawk** [jellyfin/jellyfin#3700]
**Describe the bug**
Plugins aren't installed automatically or manually.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker
-  Container: jellyfin/jellyfin
 - Clients: Browser
 - Browser: Firefox 78.0.2
 - Jellyfin Version: 10.6.0
 - Installed Plugins: Playback Reporting, Reports
 - Reverse Proxy: Traefik 2.2.7
 - Base URL: [e.g. none, yes: /example]
 - Networking: NAT / ingress
 - Storage: NFS

**To Reproduce**
1. Go to 'Scheduled Tasks'
2. Click on 'Update Plugins'

**Expected behavior**
The plugin should be updated.

**Logs**
```
[13:10:59] [INF] [57] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[13:11:00] [WRN] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 10.255.0.2. Time (slow): 0:00:00.5082862. http://cinethuis.huizegerritse.net/ScheduledTasks?isHidden=false
[13:11:02] [ERR] [51] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.IOException: Directory not empty
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[13:11:04] [ERR] [51] Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask: Error updating Reports
System.IO.IOException: Directory not empty
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
[13:11:04] [INF] [51] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 4 seconds
[13:11:04] [INF] [51] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```
**Workaround**
Delete the plugins manually, restart the Jellyfin container, reinstall the plugins manually.

**Additional context**
I've seen this issue since version 10.3,x which was when I started using Jellyfin.
Jellyfin has fully read/write access and proper permissions on the plugins folder.

**Comment by BaronGreenback** [comment]
From what i understand plugin file locks aren't released when the plugins are unloaded (.net issue).

https://github.com/jellyfin/jellyfin/pull/3401 introduces versioning to plugin installations, which should get around the issue.

**Comment by tyhawk** [comment]
Good to know the issue is known and in the process of being fixed. Thanks for the quick reply.
