### ISSUE TITLE
can't  download subtitles

### ISSUE THREAD

**Issue by ssyangchn** [jellyfin/jellyfin#3709]
**Describe the bug**
can't  download subtitles from opensubtitles

**System (please complete the following information):**
 - OS: windows
 - Virtualization: none
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.0
 - Playback: [Direct Play] 
 - Installed Plugins: [Fanart, Anime, OpenSubtitle.]
 - Storage: cloud

**To Reproduce**

can't  download subtitles from opensubtitles

**Logs**

```
[17:16:59] [ERR] [29] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from Open Subtitles
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Entities.ProviderIdsExtensions.GetProviderId(MediaBrowser.Model.Entities.IHasProviderIds, MediaBrowser.Model.Entities.MetadataProviders)'.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
```

**Additional context**
full log on start
 
```
17:15:40] [INF] [1] Main: Jellyfin version: 10.6.0
[17:15:40] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\\ProgramData\\Jellyfin\\Server\\log]"]
[17:15:40] [INF] [1] Main: Arguments: ["D:\\Program Files\\Jellyfin\\Server\\jellyfin.dll", "--datadir", "D:\\ProgramData\\Jellyfin\\Server"]
[17:15:40] [INF] [1] Main: Operating system: Windows
[17:15:40] [INF] [1] Main: Architecture: X64
[17:15:40] [INF] [1] Main: 64-Bit Process: True
[17:15:40] [INF] [1] Main: User Interactive: True
[17:15:40] [INF] [1] Main: Processor count: 8
[17:15:40] [INF] [1] Main: Program data path: D:\ProgramData\Jellyfin\Server
[17:15:40] [INF] [1] Main: Web resources path: D:\Program Files\Jellyfin\Server\jellyfin-web
[17:15:40] [INF] [1] Main: Application directory: D:\Program Files\Jellyfin\Server\
[17:15:43] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: D:\ProgramData\Jellyfin\Server\cache
[17:15:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Anime\Jellyfin.Plugin.Anime.dll
[17:15:44] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null.
System.TypeLoadException: Method 'get_ProviderName' in type 'Jellyfin.Plugin.Anime.Providers.AniSearch.AniSearchExternalId' from assembly 'Jellyfin.Plugin.Anime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.Douban, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Douban\Jellyfin.Plugin.Douban.dll
[17:15:44] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.Douban, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null.
System.TypeLoadException: Method 'get_ProviderName' in type 'Jellyfin.Plugin.Douban.DoubanExternalId' from assembly 'Jellyfin.Plugin.Douban, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Fanart\Jellyfin.Plugin.Fanart.dll
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Kodi Sync Queue\Jellyfin.Plugin.KodiSyncQueue.dll
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from D:\ProgramData\Jellyfin\Server\plugins\Kodi Sync Queue\LiteDB.dll
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Open Subtitles\Jellyfin.Plugin.OpenSubtitles.dll
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\Open Subtitles\OpenSubtitlesHandler.dll
[17:15:44] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from D:\ProgramData\Jellyfin\Server\plugins\TMDb Box Sets\Jellyfin.Plugin.TMDbBoxSets.dll
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:15:46] [WRN] [1] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[17:16:15] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.KodiSyncQueue.Plugin
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.Plugin'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:17] [INF] [1] Main: Kestrel listening on all interfaces
[17:16:18] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[17:16:18] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.FireRetentionTask
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.FireRetentionTask'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:18] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:18] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for 提取剧集图片 set to fire at 07/27/2020 02:00, which is 8:43:41.1680732 from now.
[17:16:19] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1
[17:16:19] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[17:16:19] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[17:16:19] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[17:16:19] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: D:\Program Files\Jellyfin\Server\ffmpeg.exe
[17:16:19] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: e4bcab8bbc5b4b9f99a7f837aace1236
[17:16:19] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:19] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:19] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[17:16:20] [INF] [4] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.7543366
[17:16:20] [INF] [4] Emby.Server.Implementations.ApplicationHost: Core startup complete
[17:16:20] [INF] [4] Emby.Server.Implementations.Library.LibraryManager: Resetting user root folder path to D:\ProgramData\Jellyfin\Server\root\default
[17:16:20] [INF] [4] Emby.Server.Implementations.Library.LibraryManager: Resetting root folder path to D:\ProgramData\Jellyfin\Server\root
[17:16:20] [INF] [4] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Starting NAT discovery
[17:16:21] [INF] [4] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.6671697
[17:16:21] [INF] [4] Main: Startup complete 0:00:42.3700178
[17:16:21] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: 更新插件
[17:16:21] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
[17:16:21] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing 更新插件
[17:16:24] [INF] [13] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::1 request
[17:16:27] [WRN] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to ::1. Time (slow): 0:00:02.2781645. http://localhost:8096/Sessions/Capabilities/Full
[17:16:27] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:02.2673915. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2
[17:16:27] [WRN] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:02.3642883. http://localhost:8096/DisplayPreferences/usersettings?userId=46201ec502c54df4b0434eabe0e506c2&client=emby
[17:16:28] [WRN] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.5996594. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
[17:16:28] [ERR] [9] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.UnauthorizedAccessException: Access to the path 'Jellyfin.Plugin.Fanart.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[17:16:28] [ERR] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.UnauthorizedAccessException: Access to the path 'Jellyfin.Plugin.Fanart.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[17:16:29] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: 更新插件 Failed after 0 minute(s) and 7 seconds
[17:16:29] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[17:16:29] [WRN] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.4659647. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
[17:16:29] [WRN] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.456052. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9a63b0643a0b5e4f2cd3e747c56fffbe
[17:16:29] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.4729044. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=3227ce1e069754c594af25ea66d69fc7
[17:16:29] [WRN] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.3614567. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=68359da5a60d69e1d910ff466daa2c9d
[17:16:29] [WRN] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.889587. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=1c474c9c4d728d1a2f621adad0f221ae
[17:16:31] [WRN] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:03.5582447. http://localhost:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=46201ec502c54df4b0434eabe0e506c2&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false
[17:16:37] [WRN] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.2689956. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
[17:16:38] [WRN] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.3534843. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
[17:16:38] [WRN] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.3609416. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9a63b0643a0b5e4f2cd3e747c56fffbe
[17:16:38] [WRN] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.0882871. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=1c474c9c4d728d1a2f621adad0f221ae
[17:16:38] [WRN] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.4033772. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=68359da5a60d69e1d910ff466daa2c9d
[17:16:38] [WRN] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.6796569. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9b05b41b94963c3c90288a5b4c481217
[17:16:38] [WRN] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.5879567. http://localhost:8096/Users/46201ec502c54df4b0434eabe0e506c2/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=da0181623c4da84fdbecdaad12494d4f
[17:16:40] [WRN] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:03.8352739. http://localhost:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=46201ec502c54df4b0434eabe0e506c2&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false
[17:16:50] [ERR] [32] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The process cannot access the file 'D:\ProgramData\Jellyfin\Server\cache\images\resized-images\8\872785f2-dabb-eabe-17b4-adac2796ee98.webp' because it is being used by another process. URL: http://localhost:8096/Items/f85d688b44197d069fd64f30bffa7011/Images/Backdrop/0?maxWidth=1920&tag=9fc2a86a26e1b3f68143e527a5503849&quality=80
[17:16:50] [WRN] [32] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to ::1. Time (slow): 0:00:00.6425838. http://localhost:8096/Items/f85d688b44197d069fd64f30bffa7011/Images/Backdrop/0?maxWidth=1920&tag=9fc2a86a26e1b3f68143e527a5503849&quality=80
[17:16:50] [WRN] [6] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.6535549. http://localhost:8096/Items/f85d688b44197d069fd64f30bffa7011/Images/Backdrop/0?tag=9fc2a86a26e1b3f68143e527a5503849&maxWidth=1920&quality=80
[17:16:50] [WRN] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:00.6210527. http://localhost:8096/Items/f85d688b44197d069fd64f30bffa7011/Images/Primary?maxHeight=1440&maxWidth=960&tag=f6d8c450a49233ecffe91bc3288510c9&quality=90
[17:16:59] [ERR] [29] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from Open Subtitles
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Entities.ProviderIdsExtensions.GetProviderId(MediaBrowser.Model.Entities.IHasProviderIds, MediaBrowser.Model.Entities.MetadataProviders)'.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
[17:17:45] [INF] [32] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:127.0.0.1 request
[17:20:36] [WRN] [38] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:00.5016456. http://localhost:8097/LiveTv/Recordings?UserId=46201ec502c54df4b0434eabe0e506c2&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop
[17:20:36] [WRN] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:00.6679432. http://localhost:8097/Sessions?ActiveWithinSeconds=960
```

**Comment by crobibero** [comment]
It looks like your plugins are out of date. Can you update them all and try again?
If you're missing the plugin repository: https://repo.jellyfin.org/releases/plugin/manifest-stable.json

**Comment by ssyangchn** [comment]
> It looks like your plugins are out of date. Can you update them all and try again?
> If you're missing the plugin repository: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
All right after upgrading the plugin, 3KS
