### ISSUE TITLE
Dangling file symlinks in library folders breaks polling for media files.

### ISSUE THREAD

**Issue by Aterfax** [jellyfin/jellyfin#3741]
**Describe the bug**
I had some dangling  file symlinks (not folder) in my TV and Movies folders - when scanning for media nothing would be found and while in the add folder menu for each library navigation of the file system would show no sub folders in these folders while dangling symlinks were present.

**System (please complete the following information):**
 - OS: Unraid current
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox, Chrome
 - Jellyfin Version:  Main: Jellyfin version: 10.6.1
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
Add a dangling file symlink in a new library folder with media, hit scan, watch nothing get added / see the GUI unable to show you subfolders in the selected folder.

**Expected behavior**
Media to get added, gracious non-blocking failure on a dangled symlink.

**Logs**
Couldn't find anything in the logs which is why this was such an enormous pain in the ass to diagnose - errors are seen for dangling folder symlinks but I didn't see anything for file symlinks.

Dangling folder output:

```System.IO.FileNotFoundException: Could not find file '/tv/bbc'.
File name: '/tv/bbc'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
[2020-07-29 01:25:06.092 +01:00] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://x.x.x.x:8096/web/touchicon.png"
[2020-07-29 01:25:06.215 +01:00] [ERR] [19] Emby.Server.Implementations.Library.LibraryManager: Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False```

**Screenshots**
N/A

**Comment by jonweed** [comment]
I think this is the same.  Below is dangling symlink on Debian 10, Jellyfin 10.6.3.  Fresh install, library did not find any media until I removed dangling symlink.

>System.IO.FileNotFoundException: Could not find file '/opt/media/movies/John Wick Chapter 3 (2019) - 1080P.mkv'.
File name: '/opt/media/movies/John Wick Chapter 3 (2019) - 1080P.mkv'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)

**Comment by alxleroux** [comment]
Same here

debian 10
Jellyfin.Server 10.6.4.0

**Comment by hatl** [comment]
I have a symlink which is only valid outside the docker image that I use for Jellyfin.
Can't use my existing folder as a library...
Please fix this - thanks!
