### ISSUE TITLE
Endless log entries for Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin#3756]
**Describe the bug**
Reviewing my logs from the past few days, I see endless entries as follows:

```
[2020-07-30 17:58:47.565 +00:00] [ERR] [26] Emby.Server.Implementations.Library.LibraryManager: Cannnot get image dimensions for "/tv_sd/M"
System.IO.FileNotFoundException: File not found
File name: '/tv_sd/M'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate)
```

**System (please complete the following information):**
 - OS: Synology DSM 6
 - Virtualization: Docker
 - Jellyfin Version: 10.6.1
 - Installed Plugins: InfuseSync
 - Reverse Proxy: na
 - Storage: local (on NAS)

**To Reproduce**
No user interaction required (or at least known). This seems to be a server function.

**Expected behavior**
There is no TV show called "M". There are only two series starting with M I suspect the issue is the handling of asterisks in the series "M*A*S*H"

But beyond that issue, I wouldn't expect JF to continually test the same folder/file for days on end.

**Logs**
See above

**Comment by accountForIssues** [comment]
I can confirm the same issue with paths containing asterisks. If jellyfin has just started, then the media with '*' in it's path is not available. By that I mean, I can see the entry but cannot play them. After sometime, they appear and everything seems normal. However, the logs still have entries such as shown above.

**Comment by classicjazz** [comment]
Please note that this is still an issue with 10.7.0

**Comment by classicjazz** [comment]
This is still an issue with Version: 10.7.6

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Bond-009** [comment]
We use both * and | as delimiters in the DB and I'm assuming that's the underlying issue
