### ISSUE TITLE
Error processing request - System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by SosthenG** [jellyfin/jellyfin#3762]
**Describe the bug**
I have this issue only on one of my movies, when I try to start it either from the begining or from the last saved tick, it doesn't work.

When launching on AndroidTV, the "play" and "resume" buttons just doesn't work (no message, no loader).
When launching with a web browser, there is a loader but it never ends for both buttons.

I can successfully launch the movie by selecting a chapter, but it seems to be the only way.

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker, official Jellyfin image
 - Clients: Firefox, AndroidTV, but it's working fine on Android.
 - Browser: Firefox 79.0
 - Jellyfin Version: 10.6.1
 - Playback: Transcode VAAPI
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles, Playback reporting, TMDb box sets, TheTVDB
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
I can only reproduce on only one of my movies, so I guess you won't be able to reproduce.
But for this content, just trying do play the movie doesn't work.

**Expected behavior**
The movie starts from the begining or resume depending on which button pressed.

**Logs**

```
[2020-07-31 10:45:06.543 +02:00] [ERR] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://myserver/Items/4d7df47de6712f61234bcc5859a40e8c/PlaybackInfo?UserId=02e01dc29c1744d2bdf0a284djdd0cdc&StartTimeTicks=54162040000&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=Infinity"
System.FormatException: Input string was not in a correct format.
   at ServiceStack.Text.SignedInteger`1.ParseInt64(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 869
   at ServiceStack.Text.SignedInteger`1.ParseObject(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 803
   at ServiceStack.Text.SignedInteger`1.ParseNullableObject(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 786
   at ServiceStack.Text.Common.JsReader`1.<>c__DisplayClass4_0`1.<GetCoreParseStringSpanFn>b__3(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\JsReader.cs:line 70
   at ServiceStack.Text.Jsv.JsvReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Jsv\JsvReader.Generic.cs:line 18
   at Emby.Server.Implementations.Services.StringMapTypeDeserializer.PopulateFromMap(Object instance, IDictionary`2 keyValuePairs)
   at Emby.Server.Implementations.Services.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(IRequest httpReq, RestPath restPath, Dictionary`2 requestParams, Object requestDto)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Please fill out the full issue template.

**Comment by SosthenG** [comment]
> 
> 
> Please fill out the full issue template.

Sorry I hadn't seen them, I just edited my issue.
