### ISSUE TITLE
Missing music

### ISSUE THREAD

**Issue by kevinm416** [jellyfin/jellyfin#3777]
**Describe the bug**
Some of my media is missing in the UI. Most of it works fine, but some is just missing. I see relevant stack traces in the logs, but they don't have quite enough info for me to figure out what the problem is. If anyone could help me, I would appreciate it! 

**System (please complete the following information):**
 - OS: Alpine (It's the jellyfin/jellyfin docker container)
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.6.0
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: None
 - Networking: ?
 - Storage: local

**To Reproduce**
1. Go home
2. Click on the search button
3. Search for Tame Impala
4. It doesn't return results
5. I also can't find the music by looking for the artist or albums

**Expected behavior**
The music that's on disk shows up

**Logs**
I started a library scan while I was tailing the docker logs.

```
[21:48:54] [INF] [15] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item Tame Impala type: Folder path: /microcenter/Music/Music/Tame Impala
[21:48:54] [INF] [15] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Folder, Name: Tame Impala, Path: /microcenter/Music/Music/Tame Impala, Id: 4cd285bc-bf9f-b796-e527-e7c17ba30b46
...
[09:56:17] [ERR] [60] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /microcenter/Music/Tame Impala
System.IO.DirectoryNotFoundException: Could not find a part of the path '/microcenter/Music/Tame Impala'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[09:56:17] [ERR] [60] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /microcenter/Music/Tame Impala/Currents
System.IO.DirectoryNotFoundException: Could not find a part of the path '/microcenter/Music/Tame Impala/Currents'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[09:56:17] [ERR] [60] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /microcenter/Music/Tame Impala/Innerspeaker
System.IO.DirectoryNotFoundException: Could not find a part of the path '/microcenter/Music/Tame Impala/Innerspeaker'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[09:56:17] [ERR] [60] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /microcenter/Music/Tame Impala/Lonerism
System.IO.DirectoryNotFoundException: Could not find a part of the path '/microcenter/Music/Tame Impala/Lonerism'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
...
[16:23:05] [INF] [74] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Folder, Name: Tame Impala, Path: /microcenter/Music/Tame Impala, Id: 1c3f483b-0bdc-ecb5-3fdc-b5f691d062dc
```

Those directories do seem to exist, for example:
```
kevin@pihost:~$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                 PORTS                                                                                                     NAMES
827c2cd87f29        jellyfin/jellyfin                        "/jellyfin/jellyfin"     44 hours ago        Up 5 hours                                                                                                                       personal_jellyfin_1
kevin@pihost:~$ docker exec  -it 827c2cd87f29 bash
root@pihost:/# ls /microcenter/Music/Tame\ Impala/
Currents  Innerspeaker	Lonerism
root@pihost:/# ls /microcenter/Music/Tame\ Impala/*
'/microcenter/Music/Tame Impala/Currents':
01.Let_It_Happen.mp3  04.Yes_I’m_Changing.mp3  07.The_Less_I_Know_the_Better.mp3  10.’Cause_I’m_a_Man.mp3   13.New_Person,_Same_Old_Mistakes.mp3
02.Nangs.mp3	      05.Eventually.mp3        08.Past_Life.mp3			  11.Reality_in_Motion.mp3  cover.jpg
03.The_Moment.mp3     06.Gossip.mp3	       09.Disciples.mp3			  12.LoveParanoia.mp3

'/microcenter/Music/Tame Impala/Innerspeaker':
01.It_Isnt_Meant_to_Be.mp3  04.Lucidity.mp3			   07.Jeremys_Storm.mp3		  10.Runway,_Houses,_City,_Clouds.mp3
02.Desire_Be_Desire_Go.mp3  05.Why_Wont_You_Make_Up_Your_Mind.mp3  08.Expectation.mp3		  11.I_Dont_Really_Mind.mp3
03.Alter_Ego.mp3	    06.Solitude_Is_Bliss.mp3		   09.The_Bold_Arrow_of_Time.mp3  cover.jpg

'/microcenter/Music/Tame Impala/Lonerism':
01.Be_Above_It.mp3	  04.Mind_Mischief.mp3		   07.Feels_Like_We_Only_Go_Backwards.mp3  10.She_Just_Wont_Believe_Me.mp3   cover.jpg
02.Endors_Toi.mp3	  05.Music_to_Walk_Home_By.mp3	   08.Keep_on_Lying.mp3			   11.Nothing_That_Has_Happened.mp3
03.Apocalypse_Dreams.mp3  06.Why_Wont_They_Talk_to_Me.mp3  09.Elephant.mp3			   12.Suns_Coming_Up.mp3
```

**Comment by kevinm416** [comment]
Nevermind, of course the music shows up as soon as I file the ticket. Idk what changed - I had previously re-scanned the library a couple times.
