### ISSUE TITLE
MigrateDisplayPreferencesDatabase migration error

### ISSUE THREAD

**Issue by alashow** [jellyfin/jellyfin#3785]
**Describe the bug**
My installation of Jellyfin stopped working today after it got auto-updated to the [latest](https://hub.docker.com/layers/jellyfin/jellyfin/20200801.15-unstable/images/sha256-67a2e6a7defd43cfd17f118da40f7e6492ab82f3da1b007eeb14080ccc24d708?context=explore) unstable build. Probably related to #3578.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Jellyfin Version: `jellyfin/jellyfin:20200801.15-unstable`
 - Reverse Proxy: nginx

**To Reproduce**

1. Jellyfin fails to start

**Logs**
```
Runner: Could not apply migration 'MigrateDisplayPreferencesDatabase'
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[01:17:08] [FTL] [1] Main: Error while starting server.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Comment by BaronGreenback** [comment]
I got exactly the same error, so it looks like there was a bug previously.

Had to go in and delete the duplicate userid from the database manually.

**Comment by sparky8251** [comment]
From which table @BaronGreenback ?

Thats a rather important detail.

**Comment by BaronGreenback** [comment]
userdisplaypreferences in the displaypreferences.db database

duplicate userId

At the amazon tv androidtv clients had the same id. - nuked them and so i only had one left and the process ran through

**Comment by normanu** [comment]
I have the same error and it seems also duplicates in the displaypreferences.db, but how do I delete the dubs?

**Comment by BaronGreenback** [comment]
backup the file first.

Install something like db browser for sql lite - open the db, and view the table.
Look at the second field across (from memory it's userid i think) and delete any duplicates records.

I don't have this file anymore as i think it gets migrated afterwards so i can't fully check.

**Comment by valentine** [comment]
I just ran into the same problem trying the unstable build for the first time. Both my `id` and `userid` columns are populated with weird characters (see image) — is this normal behaviour?

<img width="442" alt="Screenshot 2020-08-17 at 2 13 48 AM" src="https://user-images.githubusercontent.com/676061/90341114-6fae4c80-e02f-11ea-84e7-c1c80fefd586.png">

**Comment by autoteelar** [comment]
how do i delete the shits?
