### ISSUE TITLE
IPTV Recording problem 

### ISSUE THREAD

**Issue by buchu** [jellyfin/jellyfin#3870]
**Describe the bug**
Impossible to record IPTV, i can see on the interface the media but when i want to read it, i have a reading error. 

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Safari 13.1.2
 - Jellyfin Version: 10.6.2
 - Storage: NFS

**To Reproduce**
Go to the guide and record a channel.

**Expected behavior**
Record IPTV

**Logs**
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Beginning recording. Will record for 16.992107163333333 minutes.
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Writing file to path: /media/Record/Bande de sportifs/Season 2/Bande de sportifs S02E07 Le plongeon.ts
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Triggering refresh on /media/Record/Bande de sportifs/Season 2/Bande de sportifs S02E07 Le plongeon.ts
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Refreshing recording parent /media/Record/Bande de sportifs/Season 2
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Copying recording stream to file /media/Record/Bande de sportifs/Season 2/Bande de sportifs S02E07 Le plongeon.ts
[12:33:00] [ERR] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error recording to /media/Record/Bande de sportifs/Season 2/Bande de sportifs S02E07 Le plongeon.ts
System.IO.FileNotFoundException: Could not find file '/config/transcodes/c88cd1d9baf74815988deafc2c349f84.ts'.
File name: '/config/transcodes/c88cd1d9baf74815988deafc2c349f84.ts'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.GetInputStream(String path, Boolean allowAsyncFileRead)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyFile(String path, Boolean seekFile, Int32 emptyReadLimit, Boolean allowAsync, Stream stream, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyToAsync(Stream stream, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.DirectRecorder.RecordFromDirectStreamProvider(IDirectStreamProvider directStreamProvider, String targetFile, TimeSpan duration, Action onStarted, CancellationToken
 cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo)
[12:33:00] [INF] [4] Emby.Server.Implementations.Library.MediaSourceManager: Live stream 1737fd9a3d6bb6b4e632ba167606560e consumer count is now 0
[12:33:00] [INF] [4] Emby.Server.Implementations.Library.MediaSourceManager: Closing live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_1737fd9a3d6bb6b4e632ba167606560e
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Closing SharedHttpStream 
[12:33:00] [INF] [4] Emby.Server.Implementations.Library.MediaSourceManager: Live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_1737fd9a3d6bb6b4e632ba167606560e closed successfully
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Triggering refresh on /media/Record/Bande de sportifs/Season 2/Bande de sportifs S02E07 Le plongeon.ts
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Refreshing recording parent /media/Record/Bande de sportifs/Season 2
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Retrying recording in 60 seconds.
[12:33:00] [INF] [4] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Creating recording timer for 63fb689eb1e1463e8a133e7342c6aa37, Bande de sportifs. Timer will fire in 0.9999950816666666 minutes

**Comment by fishtek** [comment]
Hey can reopen this issue? On the latest RC 1 I'm having this issue as well.

**Comment by boredness** [comment]
Having this exact issue on Jellyfin 10.7.7 on Arch

Log: https://0x0.st/oH0B.txt
