### ISSUE TITLE
Library refresh fails to find TV Show, throw exceptions

### ISSUE THREAD

**Issue by Legogris** [jellyfin/jellyfin#3882]
When doing a full refresh metadata of an existing TV Series:

```
15:31:55] [ERR] [12] MediaBrowser.Providers.Manager.ProviderManager: TvdbSeriesImageProvider failed in GetImageInfos for type Series
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[15:31:55] [INF] [26] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 503f41639a0f9e3e653c772fc2f2507d
[15:31:55] [INF] [26] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart db93c1f2d78f8cc6e5586a40ec195e4e
[15:31:55] [INF] [26] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete db93c1f2d78f8cc6e5586a40ec195e4e
[15:31:55] [ERR] [12] MediaBrowser.Providers.Manager.ProviderManager: TvdbSeriesImageProvider failed in GetImageInfos for type Series
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[15:31:55] [ERR] [12] MediaBrowser.Providers.Manager.ProviderManager: TvdbSeasonImageProvider failed in GetImageInfos for type Season
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[15:31:58] [ERR] [33] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:00] [ERR] [26] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:02] [ERR] [29] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:04] [ERR] [29] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:06] [ERR] [29] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:09] [ERR] [12] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:11] [ERR] [12] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:13] [ERR] [33] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:15] [ERR] [12] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:18] [ERR] [12] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:20] [ERR] [33] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[15:32:21] [ERR] [33] MediaBrowser.Providers.Manager.ProviderManager: TvdbSeriesImageProvider failed in GetImageInfos for type Series
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[15:32:21] [INF] [33] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete 503f41639a0f9e3e653c772fc2f2507d
[15:32:53] [INF] [46] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart aedd2e19168afe0916a57af3f7b600f8
[15:32:53] [INF] [46] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart 8f32759d02be738397a1c0f04f0c6430
[15:32:53] [INF] [46] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete 8f32759d02be738397a1c0f04f0c6430
[15:33:07] [INF] [48] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete aedd2e19168afe0916a57af3f7b600f8
```

Assigned (and verified correct) IDs are IMDb, TheMovieDb, TheTVDb.

Jellyfin version 10.6.2 - I do not thin I ever saw this with 10.5.5, where the same series existed (though I did note that it never assigned an image for the Series)

**Comment by ssyangchn** [comment]
same issues in 10.6.3

**Comment by Legogris** [comment]
I don't have this anymore on 0.6.3. I *think* wiping the plugin directory after the last upgrade and reinstalling each to latest was what did it.
