### ISSUE TITLE
Live tv recodings with Umlaut in name fails: Exit code 137

### ISSUE THREAD

**Issue by myxor** [jellyfin/jellyfin#3884]
**Describe the bug**

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Linux Ubuntu
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] Browser
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Chromium, Firefox
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] 10.6.2
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] nginx
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT] host
 - Storage: [e.g. local, NFS, cloud] local

**To Reproduce**

1. Record livetv (maybe with a german Umlaut in the name/path?) 
2. See error in log and recording failed

**Expected behavior**

Recoding to be successful

**Logs**

[21:48:10] [ERR] [99] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error recording to /media/usb0//video/recordings/Aktenzeichen XY... ungelöst/Aktenzeichen XY... ungelöst 2020_08_12_20_15_00.ts
System.Exception: Recording for /media/usb0/video/recodings/Aktenzeichen XY... ungelöst/Aktenzeichen XY... ungelöst 2020_08_12_20_15_00.ts failed. Exit code 137
   at Emby.Server.Implementations.LiveTv.EmbyTV.EncodedRecorder.Record(IDirectStreamProvider directStreamProvider, MediaSourceInfo mediaSource, String targetFile, TimeSpan duration, Action onStarted, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo)
`

**Screenshots**

**Additional context**

I guess the bug happens because of the german Umlaut letters in the name: "ö" as other recodings without this letter in the name are working.

**Comment by myxor** [comment]
If it helps here is another log from a different recording:

> [01:45:20] [ERR] [107] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error recording to /media/usb0/NAS_backup/video/Aufnahmen/Ungezähmtes Albanien/Ungezähmtes Albanien 2020_08_20_01_40_00.ts
System.ArgumentNullException: Value cannot be null. (Parameter 'item')
   at Emby.Server.Implementations.Library.MediaSourceManager.GetStaticMediaSources(BaseItem item, Boolean enablePathSubstitution, User user)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetPlaybackMediaSources(BaseItem item, User user, Boolean allowMediaProbe, Boolean enablePathSubstitution, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo)

**Comment by myxor** [comment]
Issue is still present with most recent docker image.

**Comment by crobibero** [comment]
> 
> 
> Issue is still present with most recent docker image.

What does "most recent docker image" mean?

**Comment by cvium** [comment]
Not enough information to go on. We need the full ffmpeg logs
