### ISSUE TITLE
certain films and tv wont play

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin#3911]
since 10.6 some films and tv shows dont work on firefox web, phone app and firestick but do work on kodi

Server: Jellyfin
Version: 10.6.3
Operating System: Linux
Architecture: X64
docker

[11:31:30] [INF]  -f avi -i file:"/media/Films1/The.Book.of.Eli.(2010)/The.Book.of.Eli.(2010).avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 3005865 -bufsize 6011730 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/c5fce4e5241f0f9714621851c1354e0c%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/c5fce4e5241f0f9714621851c1354e0c.m3u8"

[11:31:30] [ERR] Error starting ffmpeg

System.InvalidOperationException: Cannot start process because a file name has not been provided.

   at System.Diagnostics.Process.Start()

   at MediaBrowser.Api.Playback.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, String workingDirectory)

[11:31:30] [ERR] Error processing request. URL: http://jellyfin.******.duckdns.org/videos/10052431-2683-8201-44cc-f7faec5203f3/hls1/main/0.ts?DeviceId=ad07b4610635a0d4&MediaSourceId=100524312683820144ccf7faec5203f3&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=1&VideoBitrate=48106913&AudioBitrate=448000&PlaySessionId=47df1df1bcef423aa5755dfb65bbc749&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=f933f21e30c7caaac6ed928beccd904c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

System.InvalidOperationException: Cannot start process because a file name has not been provided.

   at System.Diagnostics.Process.Start()

   at MediaBrowser.Api.Playback.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, String workingDirectory)

   at MediaBrowser.Api.Playback.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String segmentId)

   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)

   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)

   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by cvium** [comment]
Sounds to me like your ffmpeg path isn't set correctly in jellyfin's config.

**Comment by bwaddington** [comment]
thank you for quick response you are right it looks like it has no path set. not had to do this before so not sure what needs to be in there and where it need to lead
any help would be appreciated

**Comment by bwaddington** [comment]
ok i think i found what i need to do set the path to 

/usr/lib/jellyfin-ffmpeg
