### ISSUE TITLE
Creating a SyncPlay group while casting breaks it for all users.

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin#3931]
**Describe the bug**
If you open the web client and cast to another player, creating a group from that web client will break SyncPlay group listing for all users until the offending client terminates SyncPlay.

**System (please complete the following information):**
 - OS: Debian Stable
 - Virtualization: None
 - Clients: Jellyfin-Web, MPV Shim
 - Browser: Firefox ESR (Affects all browsers)
 - Jellyfin Version: 10.6.3
 - Playback: None
 - Installed Plugins: None
 - Reverse Proxy: Nginx
 - Base URL: None
 - Networking: Local Network
 - Storage: Local

**To Reproduce**
1. Open the Jellyfin Web client.
2. Cast to MPV Shim or a web client running in another browser.
3. Click the SyncPlay menu.
4. Create a group.
5. Open Jellyfin Web in another browser.
6. Click the SyncPlay menu.
7. You cannot see any active SyncPlay groups. The screenshot and server log message apply.

**Expected behavior**
Creating a group would either fail or create a group on the controlled client, not create an invalid group. 

**Logs**
```
[2020-08-18 09:24:43.359 -04:00] [ERR] Error processing request. URL: "http://[domain]/SyncPlay/List"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.SyncPlay.SyncPlayController.GetPlayingItemId()
   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.<>c__DisplayClass21_0.<ListGroups>b__2(ISyncPlayController group)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.ListGroups(SessionInfo session, Guid filterItemId)
   at MediaBrowser.Api.SyncPlay.SyncPlayService.Get(SyncPlayList request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Screenshots**
This is shown when trying to list the groups in the web client while the bad client has a SyncPlay group:
![image](https://user-images.githubusercontent.com/8078788/90538187-33bcd980-e14c-11ea-9c2c-53fe56e10ee1.png)

**Additional context**
SyncPlay will continue to be broken for all users until the offending client either leaves the group they created or closes the browser window.

Related to https://github.com/jellyfin/jellyfin/issues/3855
MPV Shim Issue: https://github.com/iwalton3/jellyfin-mpv-shim/issues/107

**Comment by nielsvanvelzen** [comment]
I'm not sure if you saw this one @OancaAndrei. It might already be fixed with #3194 or another one.

**Comment by OancaAndrei** [comment]
> I'm not sure if you saw this one @OancaAndrei. It might already be fixed with #3194 or another one.

Saw it back in the days but forgot about it. I'll have a look so we're sure.

**Comment by OancaAndrei** [comment]
It should indeed be fixed as the approach to groups changed a lot. That was an ugly check to "ensure" that all sessions would play the same thing.

**Comment by nielsvanvelzen** [comment]
That's good to hear. @iwalton3 can you also confirm that it behaves as you expect?

**Comment by iwalton3** [comment]
I can confirm this specific issue is not present anymore. I will need to re-work SyncPlay support, but that is out of the scope of this issue.
