### ISSUE TITLE
Upgrade from 10.5 to 10.6 fails  : `<UserConfiguration xmlns=''> was not expected`

### ISSUE THREAD

**Issue by arnaudsm** [jellyfin/jellyfin#3934]
**Describe the bug**
I'm trying to migrate from 10.5.5 to 10.6.3, but the `MigrateUserDatabase` migration fails and logs : 
`<UserConfiguration xmlns=''> was not expected.`

Then Jellyfin shuts down. I have the same problem when migrating to 10.6.0.

What can I do to circumvent this problem ? Thanks a lot for your help.

**System :**
 - OS: Ubuntu Server 20.04
 - Virtualization: Docker
 - Jellyfin Version: 10.6.3
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Storage: local

**Expected behavior**
Jellyfin should migrate properly and start.

**Full log**
```[11:56:45] [INF] [1] Main: Jellyfin version: 10.6.3
[11:56:45] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_MEDIA_DIR, /media]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]"]
[11:56:45] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[11:56:45] [INF] [1] Main: Operating system: Linux
[11:56:45] [INF] [1] Main: Architecture: X64
[11:56:45] [INF] [1] Main: 64-Bit Process: True
[11:56:45] [INF] [1] Main: User Interactive: True
[11:56:45] [INF] [1] Main: Processor count: 16
[11:56:45] [INF] [1] Main: Program data path: /config
[11:56:45] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[11:56:45] [INF] [1] Main: Application directory: /jellyfin/
[11:56:45] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[11:56:45] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[11:56:49] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateUserDatabase'
[11:56:49] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateUserDb: Migrating the user database may take a while, do not stop Jellyfin.
[11:56:50] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateUserDatabase'
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <UserConfiguration xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderUserPolicy.Read8_UserPolicy()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.Routines.MigrateUserDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[11:56:50] [FTL] [1] Main: Error while starting server.
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <UserConfiguration xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderUserPolicy.Read8_UserPolicy()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.Routines.MigrateUserDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing ActivityLogWebSocketListener
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing SessionInfoWebSocketListener
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing ScheduledTasksWebSocketListener
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing SessionWebSocketListener
[11:56:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[11:56:50] [INF] [2] Main: Received a SIGTERM signal, shutting down```

**Comment by arnaudsm** [comment]
Problem solved, I had a corrupted file in `/config/users/**some_user**/policy.xml`
I replace the main `UserConfiguration` tag by `UserPolicy`, and now 10.6.4 boots flawlessly.
