### ISSUE TITLE
Unstable: API Error

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3985]
Getting the following on startup.

```
[18:01:32] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Sessions/Capabilities/Full.
System.NotSupportedException: Collection was of a fixed size.
   at System.Array.System.Collections.IList.Add(Object value)
   at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Boolean setPropertyDirectly)
   at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
```

**Comment by crobibero** [comment]
Fixed with https://github.com/jellyfin/jellyfin/pull/3984/
