### ISSUE TITLE
Music -  Failed to indentify new artist or albums

### ISSUE THREAD

**Issue by groenator** [jellyfin/jellyfin#4014]
**Describe the bug**

When I try to identify a new album or artist using the Identify button, I am getting this error:

```
NOT NULL constraint failed: ItemValues.Type at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc) at SQLitePCL.pretty.StatementImpl.MoveNext()
at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, IEnumerable`1 tuples) at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.b__0(IDatabaseConnection db)
at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(IEnumerable`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.MetadataService`2.SaveItem(MetadataResult`1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken)
at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

Jellyfin is not able to find anything, I get an empty search. At first, I thought that I add the wrong ID, but this wasn't the case. I used MusicBrains and TheAudioDb, both behave the same. 

**System (please complete the following information):**
 - OS: Ubuntu 18.4
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 85
 - Jellyfin Version: 10.6.3

**Screenshots**
- I am using the MusicBrainz ID: 443bf970-9955-4ca2-b883-6b2e165c1b2c 
<img width="1422" alt="Screenshot 2020-08-30 at 17 40 11" src="https://user-images.githubusercontent.com/5445030/91664580-1c84d100-eae8-11ea-9408-4aa1ca0a20c9.png">

- 
In jellyfin I am using the identify tool to search for a new album, I add my id and clicked on search
<img width="1241" alt="Screenshot 2020-08-30 at 17 39 48" src="https://user-images.githubusercontent.com/5445030/91664598-40481700-eae8-11ea-9c4a-636bcd868cf5.png">

-
<img width="1014" alt="Screenshot 2020-08-30 at 17 39 57" src="https://user-images.githubusercontent.com/5445030/91664617-56ee6e00-eae8-11ea-8fc2-3b0d67c74f46.png">

The results are empty.

**Additional context**
How can I fix this issue? Is this something that needs to be fixed inside Jellyfin or on my end?

**Comment by bigc0127** [comment]
I'm also having the same issue with music. and the identifying feature seems to also not work for movies or shows either... search results are always empty... the issue is new and my guess is started around 10.6.1

**Comment by miker2049** [comment]
Can also say I am having this problem, can identify things just fine in video libraries, but I get no results in exactly the same way for identifying artists.

**Comment by jeneral** [comment]
I just installed Jellyfin 10.6.4. All my music is tagged with Picard and most artists and albums have NFOs exported from Kodi. Any artist missing an NFO has the same issue the in the original post.  

In addition to the aforementioned problem, a few oddities also appear. Artists with ampersands, slashes or other stylized punctuation do not get imported (ie. AC/DC, R.E.M. , Huey Lewis & The News, etc..). This is despite having NFOs in the artist folder. I zipped up a few NFOs in a similar folder structure to how they appear on my server and attached them to this ticket.
[NFO.zip](https://github.com/jellyfin/jellyfin/files/5256909/NFO.zip)

**Comment by benpro** [comment]
Same issue...
Request like /Items/RemoteSearch/MusicArtist return nothing.

**Comment by benpro** [comment]
Found the issue?! In Plugin, MusicBrainz settings, tick "Enable this provider for metadata searches on artists and albums.".
![Screenshot_20200924_012022](https://user-images.githubusercontent.com/1057913/94040633-25757380-fe04-11ea-88b6-f2078afc9d95.png)

Shouldn't be enabled by default?

**Comment by jeneral** [comment]
Good catch! I had noticed that and ticked it but hadn't tried it afterwards. It does fix the search issue but it only grabs the artwork. In my case AC/DC didn't show up. AC/DC has a Bio on the page as well. Since most of my artists and albums have NFOs, I can manually fix the few that are missing.

**Comment by mihawk90** [comment]
Yeah that should probably be set by default...

I'm also not sure if this is related, but after checking that checkbox and then manually refreshing metadata on an artist (with replacing all metadata and overwriting images), now the "Musicbrainz Artist ID" is also filled, which was previously empty. Which is also weird because most of my files (and definitely the ones I checked) have the musicbrainz artist ID in the file tags... might just be that it is an older field name though, not sure.
