### ISSUE TITLE
FileStreamResponseHelpers.GetTranscodedFile Issue

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4105]
https://github.com/jellyfin/jellyfin/pull/4063 was issues to solve an OOM on large stream.

The change was to:-
```
 await new ProgressiveFileCopier(outputPath, job, transcodingJobHelper, CancellationToken.None)
                    .WriteToAsync(httpContext.Response.Body, CancellationToken.None).ConfigureAwait(false);
 return new FileStreamResult(httpContext.Response.Body, contentType);
```

It replicated code elsewhere in JF (VideoController.cs line 467, 506), AudioHelper.cs (line 166)

Today - I encountered - which i traced to my piece of code.

```
[2020-09-08 12:18:29.743 +01:00] [ERR] [13] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HM2JT29BP4AE"", Request id ""0HM2JT29BP4AE:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetContentType(ActionContext context, FileResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetHeadersAndLog(ActionContext context, FileResult result, Nullable`1 fileLength, Boolean enableRangeProcessing, Nullable`1 lastModified, EntityTagHeaderValue etag)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager) in C:\code\jellyfin\Jellyfin.Server\Middleware\ServerStartupMessageMiddleware.cs:line 39
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager) in C:\code\jellyfin\Jellyfin.Server\Middleware\WebSocketHandlerMiddleware.cs:line 33
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager) in C:\code\jellyfin\Jellyfin.Server\Middleware\IpBasedAccessValidationMiddleware.cs:line 80
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager) in C:\code\jellyfin\Jellyfin.Server\Middleware\LanFilteringMiddleware.cs:line 61
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context) in C:\code\jellyfin\Jellyfin.Server\Middleware\ResponseTimeMiddleware.cs:line 62
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in C:\code\jellyfin\Jellyfin.Server\Middleware\ExceptionMiddleware.cs:line 55
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in C:\code\jellyfin\Jellyfin.Server\Middleware\ExceptionMiddleware.cs:line 62
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Which indicates that the writeAsync is happening before the FileStreamResult.

**Comment by BaronGreenback** [comment]
I have subsequently been testing the function FileCallbackresult (from https://github.com/StephenClearyExamples/AsyncDynamicZip/tree/core-ziparchive) as an alternative.

```
return new FileCallbackResult(new MediaTypeHeaderValue(contentType), async (outputStream, _) =>
{
  await new ProgressiveFileCopier(outputPath, job, transcodingJobHelper, CancellationToken.None)
                   .WriteToAsync(outputStream, CancellationToken.None).ConfigureAwait(false);
});
```
