### ISSUE TITLE
Emby Reference for trakt.tv 

### ISSUE THREAD

**Issue by Fiala06** [jellyfin/jellyfin#4240]
**Describe the bug**
Seems track.tv failed to sync this morning and noticed it referenced Emby instead of Jellyfin. 

**System (please complete the following information):**
Unraid

**Additional context**
Sync library to trakt.tv failed

Timeout
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.Get(HttpRequestOptions options)
   at Trakt.Api.TraktApi.<>c__DisplayClass30_0.<<GetFromTrakt>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Trakt.Api.TraktApi.Retry[T](Func`1 function)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetCollectedShowsRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncShows(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by crobibero** [comment]
This isn't a bug, the project is called `Emby.Server.Implementations`.
