### ISSUE TITLE
Unstable: Exception when Plugins access their configuration in the constructor.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4241]
The following error is created because the plugin's assembly settings are not set until after their construction.

The solution would be to move the majority of the code from ApplicationHost.cs /LoadPlugin() into the basePlugin constructor.

```
[2020-09-30 19:01:22.699 +01:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Test"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at MediaBrowser.Common.Plugins.BasePlugin`1.get_ConfigurationFilePath() in C:\code\jellyfin\MediaBrowser.Common\Plugins\BasePlugin.cs:line 205
   at MediaBrowser.Common.Plugins.BasePlugin`1.LoadConfiguration() in C:\code\jellyfin\MediaBrowser.Common\Plugins\BasePlugin.cs:line 222
   at MediaBrowser.Common.Plugins.BasePlugin`1.get_Configuration() in C:\code\jellyfin\MediaBrowser.Common\Plugins\BasePlugin.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 375
```

**Comment by BaronGreenback** [comment]
Fix https://github.com/jellyfin/jellyfin/pull/4254
