### ISSUE TITLE
Many TV shows are missed in scanning/metadata not being pulled

### ISSUE THREAD

**Issue by Ezzahhh** [jellyfin/jellyfin#4307]
**Describe the bug**

I just installed Jellyfin completely stock. I tried scanning in my TV library, which has about 4000 shows, but the scan finishes (bar disappears in dashboard) with only around 750 shows scanned in according to going to the TV shows library and getting the number at the top. If I keep scanning the library (after it finishes by itself), it will start adding more shows to the library. I realised that sometimes it would get stuck on one or something and I would need to manually identify it before it keeps on going.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.4
 - Playback: N/A
 - Installed Plugins: Anime
 - Reverse Proxy: nginx-proxy
 - Base URL: none
 - Networking: Docker
 - Storage: local

**To Reproduce**
1. Begin scanning TV shows
2. Let it finish (if it does) otherwise it may hang
3. Begin another scan

**Expected behavior**
All shows should be scanned in with metadata pulled.

**Logs**
```
[02:43:29] [ERR] [79] MediaBrowser.Providers.Manager.ProviderManager: TmdbEpisodeImageProvider failed in GetImageInfos for type Episode
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProviderBase.FetchMainResult(String urlPattern, String id, Int32 seasonNumber, Int32 episodeNumber, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProviderBase.DownloadEpisodeInfo(String id, Int32 seasonNumber, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProviderBase.GetEpisodeInfo(String seriesTmdbId, Int32 season, Int32 episodeNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```

**Screenshots**

**Additional context**
I've tried reinstalling Jellyfin from scratch multiple times and scanning, but it always gets to 500-700 shows before it stops scanning more shows in. If I search for shows that don't show up in the library, they have been sorta added (no poster and clicking into them it's just empty) and forcing an identify generally gets them added in.

**Comment by d-matt** [comment]
I believe I suffer from the same problem. The only shows that are correctly identified are those with only one word (e.g. Seinfeld) but I use "_" as white space separator in names and those with underscores does not get identified (e.g. Curb_Your_Enthusiasm).
I use TMDB as a metadata provider.

**Comment by cvium** [comment]
Please re-test with 10.7.1

**Comment by mjpieters** [comment]
I'm seeing this too. Specifically, in my music library all paths with a space in the name fail scanning:

```
[2021-09-05 19:43:40.414 +01:00] [ERR] Cannot get image dimensions for "/media/drobo/music/Heroes & Zeros/Ghostly Kisses/cover.jpg"
Non-success codec result: InternalError
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

The space is in the path are the common element between all missing entries.

**Comment by mjpieters** [comment]
I gave the Jellyfin server process write permissions to those paths, and that resolved the issue for me.

The image files were not written to but the directory modified time stamps were updated. It looks like SkiaCodec is using the directory as a cache of some sort.

**Comment by Dracozny** [comment]
I'm noticing a similar issue for shows where a Hyphen is used in place of a colon. Batman- the Animated Series, or Avatar- The Last Air Bender. Seems like it will recognize the first episode but then deletes all the others. I'm pretty sure this worked fine in 10.7.7 prior to switching to 10.8.0 Beta. However I needed to Switch to this version because of the "no decoder surfaces" bug  that seemed persistent in 10.7.7.
Anyways reasons aside, I do see that upon a library scan  I get:
`[2022-04-24 15:42:24.241 -07:00] [INF] Creating virtual episode "Batman: The Animated Series" 1x15
[2022-04-24 15:42:24.248 -07:00] [INF] Removing item, Type: "Episode", Name: "On Leather Wings", Path: "/media/TVShows/Batman- The Animated Series/Batman- The Animated Series - S01E02 - On Leather Wings SDTV.xvid", Id: c753bdf1-56eb-1c9c-6a3c-c82328ae2b8c`

which persists for every single episode in the directory except for the first. or in the case of Airbender it happened to be S00E01 that was spared. neither episode shows in the log.

**Comment by Dracozny** [comment]
Apparently not exclusive to hyphen named shows. I discovered many more and the solution was still the same. All shows needed season folders.
