### ISSUE TITLE
Jellyfin custom ffmpeg location causes crash

### ISSUE THREAD

**Issue by jeffreyulatan** [jellyfin/jellyfin#4333]
**Describe the bug**
When enabling ffmpeg custom directory Jellyfin will crash when starting up. 

**System (please complete the following information):**
 - OS: Windows Server 2019 x64
 - Virtualization: HyperV
 - Clients: Tray
 - Browser: 
 - Jellyfin Version: 10.6.4 [Stable]
 - Playback: Transcode
 - Installed Plugins: Opensubtitles, NextPVR
 - Reverse Proxy: none
 - Base URL: none, local
 - Networking: NAT
 - Storage: local

**To Reproduce**
Set custom ffmpeg location **C:/Windows/System32/ffmpeg**
Jellyfin will throw an error saying ffmpeg.exe not found if pointed to **C:/Windows/System32/ffmpeg/bin** where ffmpeg.exe is located at. Will only accepted **C:/Windows/System32/ffmpeg**
 Restarting the server will cause it to not startup until I put ffmpeg.exe directly inside the root directory C:\ProgramData\Jellyfin\Server\

**Logs**
```
[2020-10-14 21:44:08.754 +10:00] [INF] [1] Main: Jellyfin version: "10.6.4"
[2020-10-14 21:44:08.771 +10:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2020-10-14 21:44:08.790 +10:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--noautorunwebapp", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-10-14 21:44:08.792 +10:00] [INF] [1] Main: Operating system: "Windows"
[2020-10-14 21:44:08.793 +10:00] [INF] [1] Main: Architecture: X64
[2020-10-14 21:44:08.794 +10:00] [INF] [1] Main: 64-Bit Process: True
[2020-10-14 21:44:08.795 +10:00] [INF] [1] Main: User Interactive: True
[2020-10-14 21:44:08.796 +10:00] [INF] [1] Main: Processor count: 12
[2020-10-14 21:44:08.796 +10:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-10-14 21:44:08.797 +10:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-10-14 21:44:08.798 +10:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-10-14 21:44:09.350 +10:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-10-14 21:44:09.395 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-10-14 21:44:09.862 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "NextPvr, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\NextPVR\NextPvr.dll"
[2020-10-14 21:44:09.894 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles\Jellyfin.Plugin.OpenSubtitles.dll"
[2020-10-14 21:44:09.930 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles\OpenSubtitlesHandler.dll"
[2020-10-14 21:44:13.576 +10:00] [INF] [1] Main: Kestrel listening on "192.168.1.137"
[2020-10-14 21:44:13.578 +10:00] [INF] [1] Main: Kestrel listening on "127.0.0.1"
[2020-10-14 21:44:13.929 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2020-10-14 21:44:13.991 +10:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 10/15/2020 02:00, which is 4:15:46.00847 from now.
[2020-10-14 21:44:14.450 +10:00] [FTL] [1] Main: Error while starting server.
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetFFmpegVersion(String output)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersionInternal(String versionOutput)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ValidatePath(String path, FFmpegLocation location)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.SetFFmpegPath()
   at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-10-14 21:44:14.527 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2020-10-14 21:44:14.529 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "ActivityLogWebSocketListener"
[2020-10-14 21:44:14.530 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SessionInfoWebSocketListener"
[2020-10-14 21:44:14.532 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "ScheduledTasksWebSocketListener"
[2020-10-14 21:44:14.533 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SessionWebSocketListener"
[2020-10-14 21:44:14.535 +10:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2020-10-14 21:44:14.536 +10:00] [INF] [2] Main: Received a SIGTERM signal, shutting down

```

**Comment by Artiume** [comment]
Can you try a non-systems folder? I imagine it's a permissions issue.
