### ISSUE TITLE
Error in ffprobe

### ISSUE THREAD

**Issue by BlackRoom** [jellyfin/jellyfin#4354]
**Media Info of the file**

**Logs**

[2020-10-21 13:27:21.633 +08:00] [ERR] Error in "ffprobe"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

Playing disk video is wrong and cannot be recognized

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [e.g. ubuntu 4.15.0-118-generic]
 - Jellyfin Version: [e.g. 10.6.4]
 - Hardware settings & device: [e.g.  Intel(R) Celeron(R) CPU J3455 @ 1.50GHz]
 - Reverse proxy: [e.g. no, nginx.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. mac book pro ]
 - OS: [e.g. macOS 10.15.7]
 - Client: [e.g. Web/Browser]
 - Browser (if Web client): [e.g. Safari]
 - Client and Browser Version: [e.g. 10.15.7]

**Comment by backerman** [comment]
Same error message. Playback happens, just really slowly and forces a transcode. 

Server: Ubuntu 20.04.1 LTS on an RPi 4 (aarch64), 20210118.1-unstable, no RP, media mounted by NFS and I can confirm the jellyfin user has full rwx permissions. VAAPI enabled per directions on Jellyfin website.

Client: Dell XPS 17, Windows 20H2 retail build 19042.746, Edgium 89.0.760.0 (Official build) dev (64-bit)

Jellyfin log:

```
[2021-01-18 01:28:15.464 +00:00] [INF] Executed all post-startup entry points in 0:00:00.6431701
[2021-01-18 01:28:15.465 +00:00] [INF] Startup complete 0:00:23.1632254
[2021-01-18 01:28:15.685 +00:00] [INF] Watching directory /jfdata/movies
[2021-01-18 01:28:15.691 +00:00] [INF] Watching directory /jfdata/shows
[2021-01-18 01:28:16.517 +00:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2021-01-18 01:28:16.521 +00:00] [INF] Queuing task "PluginUpdateTask"
[2021-01-18 01:28:16.532 +00:00] [INF] Executing "Update Plugins"
[2021-01-18 01:28:17.679 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2021-01-18 01:28:17.747 +00:00] [INF] ExecuteQueuedTasks
[2021-01-18 01:31:56.039 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/.well-known/security.txt" to "<<client ip>>" in 0:00:00.6493137 with Status Code 404
[2021-01-18 01:31:56.039 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/humans.txt" to "<<client ip>>" in 0:00:00.6493202 with Status Code 404
[2021-01-18 01:31:56.139 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/System/Info/Public" to "<<client ip>>" in 0:00:00.5815638 with Status Code 200
[2021-01-18 01:31:56.634 +00:00] [INF] WS "<<client ip>>" request
[2021-01-18 01:31:57.444 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/DisplayPreferences/usersettings?userId=e185ab618ecc41fc8ce2727d21a20398&client=emby" to "<<client ip>>" in 0:00:00.9301895 with Status Code 200
[2021-01-18 01:31:57.959 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Sessions/Capabilities/Full" to "<<client ip>>" in 0:00:01.4483755 with Status Code 204
[2021-01-18 01:31:58.132 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Users/e185ab618ecc41fc8ce2727d21a20398/Views" to "<<client ip>>" in 0:00:00.6412201 with Status Code 200
[2021-01-18 01:32:11.467 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Items/6a7f5361eaf148e31366cbd4e142d6fe/Images/Primary?maxHeight=700&maxWidth=466&tag=8491bcedf89728af99ab30bcddcdf972&quality=90" to "<<client ip>>" in 0:00:00.5360677 with Status Code 200
[2021-01-18 01:32:11.467 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Items/1277e0b69eb910f4db9cc99bee4e082d/Images/Primary?maxWidth=466&tag=5f086026050efc6fcba355aafe330f29&quality=90" to "<<client ip>>" in 0:00:00.5780537 with Status Code 200
[2021-01-18 01:32:11.639 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Items/652d79a41b840603883cc6357a06f5c3/Images/Primary?maxHeight=1182&maxWidth=789&tag=fbd7969b63a31de0f62bdc60b5bf5c8f&quality=90" to "<<client ip>>" in 0:00:00.9566775 with Status Code 200
[2021-01-18 01:32:11.682 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Items/652d79a41b840603883cc6357a06f5c3/Images/Backdrop/0?maxWidth=2880&tag=e4b43bbfbc719403f1dd3480d92c00d1&quality=80" to "<<client ip>>" in 0:00:01.0115698 with Status Code 200
[2021-01-18 01:32:15.193 +00:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,ac3,eac3,opus,flac,vorbis", VideoCodec: "h264,hevc,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mkv", AudioCodec: "aac,mp3,ac3,eac3,opus,flac,vorbis", VideoCodec: "h264,hevc,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,ac3,eac3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mkv", Type: Video, VideoCodec: "h264,hevc,vp8,vp9,av1", AudioCodec: "aac,mp3,ac3,eac3,opus,flac,vorbis", Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: True, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,ac3,eac3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline|high 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main|main 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "183", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-01-18 01:32:28.378 +00:00] [ERR] Error in "ffprobe"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-01-18 01:32:42.733 +00:00] [INF] User policy for "jfadmin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-01-18 01:32:42.785 +00:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 10000000
[2021-01-18 01:32:42.786 +00:00] [INF] Profile: "Unknown Profile", Path: "<<media path>>", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2021-01-18 01:32:42.821 +00:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "<<media path>>" with codec "Unknown codec"
[2021-01-18 01:32:42.917 +00:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 10000000
[2021-01-18 01:32:42.918 +00:00] [INF] Profile: "Unknown Profile", Path: "<<media path>>", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2021-01-18 01:32:42.918 +00:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "<<media path>>" with codec "Unknown codec"
[2021-01-18 01:32:43.016 +00:00] [WRN] Slow HTTP Response from "https://<<server hostname>>:8920/Items/652d79a41b840603883cc6357a06f5c3/PlaybackInfo?UserId=e185ab618ecc41fc8ce2727d21a20398&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=10000000" to "<<client ip>>" in 0:00:28.0982717 with Status Code 200
[2021-01-18 01:32:43.646 +00:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -i bluray:"<<media path>>" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/4baa39b44cdfa2a302ab68cefb2dc1c8/" -hls_playlist_type event -hls_segment_filename "/var/lib/jellyfin/transcodes/4baa39b44cdfa2a302ab68cefb2dc1c8%d.ts" -y "/var/lib/jellyfin/transcodes/4baa39b44cdfa2a302ab68cefb2dc1c8.m3u8"
```

**Comment by abienz** [comment]
I have very similar issues, also installed on a RPi 4 but with DietPi, and my drives are from a networked NFS share, mounted locally to my /mnt/ folder
