### ISSUE TITLE
WebSocket returns 500 error!

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin#4441]
**Describe the bug**

Websocket connection result in a 500 error

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: 
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.7.0
 - Playback: 
 - Installed Plugins: 
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to 'Fresh install of v10.7'
2. Setup
3. Try to access after setup

**Expected behavior**

Work as intended
**Logs**

```

[2020-11-08 19:17:32.040 +06:00] [ERR] Error sending socket message from "x.x.155.233" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2020-11-08 19:17:32.141 +06:00] [ERR] Error sending socket message from "0.0.0.0" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2020-11-08 19:17:32.141 +06:00] [ERR] Error sending socket message from "x.x.155.233" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2020-11-08 19:17:32.241 +06:00] [ERR] Error sending socket message from "0.0.0.0" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2020-11-08 19:17:32.242 +06:00] [ERR] Error sending socket message from "x.x.155.233" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)


```
**Screenshots**

![Screenshot_20201108_190825](https://user-images.githubusercontent.com/16373480/98465998-f3bf3d00-21f6-11eb-9209-4c9260c8d919.png)

**Additional context**

**Comment by crobibero** [comment]
I can't replicate this, can you try pulling latest unstable and testing again?

**Comment by Anan5a** [comment]
This was the latest unstable release available in Debian repository

**Comment by BaronGreenback** [comment]
The messages in the system log are  caused by the dlna ssdp sub-system not having sufficient permissions to broadcast. Check the permissons of the account that JF runs under. Some work has been done around this with the latest network PR.

The firefox msg, although referring to sockets - is another issue.
As a first port of call i'd check https://jellyfin.org/docs/general/administration/installing.html
