### ISSUE TITLE
Trakt.tv plugin failure while Sync

### ISSUE THREAD

**Issue by thisis-mental** [jellyfin/jellyfin#4459]
**Describe the bug**
The sync from Jellyfin to Trakt is failing

**System (please complete the following information):**
 - OS: Linux Synology
 - Virtualization: Docker
 - Clients: KODI addon / Web
 - Jellyfin Version: 10.6.4
 - Installed Plugins: Trakt
 - Reverse Proxy: none
 - Base URL: none

**To Reproduce**

1. Go to Scheduled Tasks
2. Click on Sync Library To Trakt

**Expected behavior**
Finish with success and trakt is up to date 

**Logs**
````Sync library to trakt.tv failed 
 Internal Server Error
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.Get(HttpRequestOptions options)
   at Trakt.Api.TraktApi.<>c__DisplayClass30_0.<<GetFromTrakt>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Trakt.Api.TraktApi.Retry[T](Func`1 function)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)``` `

**Comment by cvium** [comment]
As the top of the error states, there's some server issues at Trakt right now. There's nothing we can do.

**Comment by thisis-mental** [comment]
Trakt services are working fine for me and this error last for weeks!
