### ISSUE TITLE
Lot's of NullReferenceException during initial scan

### ISSUE THREAD

**Issue by kvaster** [jellyfin/jellyfin#4495]
**Describe the bug**

I've created simple media folder. It consists of 6 seasons of following movie: https://thetvdb.com/series/luntik
I've enabled all metadata providers (advanced settings) in media folder settings.
During scan I can see lot's of NullReferenceException.

**System (please complete the following information):**
 - OS: Gentoo
 - Virtualization: linux
 - Jellyfin Version: 10.6.4
 - Installed Plugins: none
 - Storage: local

**Logs**

```
[2020-11-16 22:02:20.046 +03:00] [ERR] [52] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "The Open Movie Database"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs:line 139
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Omdb/OmdbEpisodeProvider.cs:line 78
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-11-16 22:02:20.103 +03:00] [ERR] [52] MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "121411"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:5 EpisodeNumber:61]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 296
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 222
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeImageProvider.cs:line 95
[2020-11-16 22:02:21.690 +03:00] [ERR] [42] MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:5 EpisodeNumber:62]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 296
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 222
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeProvider.cs:line 125
[2020-11-16 22:02:21.934 +03:00] [ERR] [42] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "The Open Movie Database"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.cs:line 139
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken) in /var/tmp/portage/media-tv/jellyfin-10.6.4/work/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Omdb/OmdbEpisodeProvider.cs:line 78
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by BaronGreenback** [comment]
Fixed in #4527
