### ISSUE TITLE
ffmpeg is killed - but its simply not very fast.

### ISSUE THREAD

**Issue by IngwiePhoenix** [jellyfin/jellyfin#4547]
**Describe the bug**
Although it takes a bit of time, ffmpeg does eventually finish. It just takes a hot minute - maybe not as fast as on a more modern, faster server.

```
[2020-11-22 16:10:40.899 +00:00] [INF] Killing ffmpeg process
[2020-11-22 16:10:42.108 +00:00] [ERR] ffmpeg image extraction failed for file:"/var/lib/jellyfin/mounts/seafile_ingwie2000/Anime/TV/Cardcaptor Sakura/Season 2/Cardcaptor Sakura S2E45.mp4"
[2020-11-22 16:10:42.190 +00:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/var/lib/jellyfin/mounts/seafile_ingwie2000/Anime/TV/Cardcaptor Sakura/Season 2/Cardcaptor Sakura S2E45.mp4\""
System.Exception: ffmpeg image extraction failed for file:"/var/lib/jellyfin/mounts/seafile_ingwie2000/Anime/TV/Cardcaptor Sakura/Season 2/Cardcaptor Sakura S2E45.mp4"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
```

A configurable timeout would solve this.

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: None
 - Clients: Browser
 - Browser: Opera GX
 - Jellyfin Version: 10.6.4 as reported by the dashboard
 - Playback: Not related 
 - Installed Plugins: Anime
 - Reverse Proxy: NGINX
 - Base URL: none
 - Networking: Host
 - Storage: Seafile's SeaDrive FUSE, mounted as/for the jellyfin user.

**To Reproduce**
1. Install and set up Seafile
2. Obtain the Seadrive binary from the Seafile website
3. Mount your Seafile account as the jellyfin user. Might require installing the `fuse` package.
4. Add a library from your Seadrive mount
5. Watch the logs. If your I/O is fast enough, `ffmpeg` will pass. Otherwise, it won't and get killed instead.

**Expected behavior**
Expected to have episode previews generated. I still get them through metadata sources, but `ffmpeg` would've been the prefered solution, as metadata retrival is surprisingly slow.

**Logs**
Above. 

**Screenshots**
Logs.

**Additional context**
None I could think of. Ask, if there is something I missed :)

**Comment by ferferga** [comment]
@IngwiePhoenix Can you enable Debug logging, reproduce this and run the ffprobe command that it's failing yourself? It's giving any error?

Can you also try using unstable please?

**Comment by ferferga** [comment]
@IngwiePhoenix Any news about this?

**Comment by rmahtoa** [comment]
Maybe this can help
https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg
