### ISSUE TITLE
ArgumentOutOfRangeException on scanning folders

### ISSUE THREAD

**Issue by robsob91** [jellyfin/jellyfin#4558]
**Describe the bug**
Upon performing any scan of my main media directory, it fails silently in the frontend, and the log is filled with ArgumentOutOfRangeExceptions. See below for exact error, each one is the same one.

**System (please complete the following information):**
 - OS: Debian bullseye/sid
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 83
 - Jellyfin Version: 20201123.3-unstable
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: local

**To Reproduce**
Do any operation to scan, such as a library refresh, or metadata refresh from the metadata manager

**Expected behavior**
Proper scanning of the directory and the addition of the folder/file to the library

**Logs**
```
[2020-11-22 02:25:34.319 -08:00] [ERR] Error retrieving children folder
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Emby.Naming.Video.VideoListResolver.IsEligibleForMultiVersion(String folderName, String testFilename)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Naming.Video.VideoListResolver.GetVideosGroupedByVersion(List`1 videos)
   at Emby.Naming.Video.VideoListResolver.Resolve(List`1 files, Boolean supportMultiVersion)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveVideos[T](Folder parent, IEnumerable`1 fileSystemEntries, IDirectoryService directoryService, Boolean suppportMultiEditions, String collectionType, Boolean >
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveMultipleInternal(Folder parent, List`1 files, String collectionType, IDirectoryService directoryService)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveMultiple(Folder parent, List`1 files, String collectionType, IDirectoryService directoryService)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, String collectionType, IItemResolver[] resolvers)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, String collectionType)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService>
```

**Additional context**
Here's the structure of one of the failing directories:
```
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/poster.jpg
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/Subs
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/Subs/2_English.srt
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG.mp4
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/fanart.jpg
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG.nfo
Harry.Potter.And.The.Sorcerers.Stone.2001.EXTENDED.1080p.BluRay.x265-RARBG/RARBG.txt
```

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/4551

**Comment by robsob91** [comment]
Sweet, thanks
