### ISSUE TITLE
System.NullReferenceException in Emby.Server.Implementations.ResourceFileManager.GetResourcePath

### ISSUE THREAD

**Issue by AstraLuma** [jellyfin/jellyfin#4559]
**Describe the bug**
Working on organizing my media, when suddenly the web app stopped serving.

**System (please complete the following information):**
 - OS: Debian on arm64 (odroid hc4)
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.6.4-1
 - Playback: na
 - Installed Plugins: a bunch, but not sure how to get a list without the UI
 - Reverse Proxy: none
 - Base URL: none
 - Networking: local only
 - Storage: local

**To Reproduce**
 Not sure

**Expected behavior**
No errors

**Logs**
```
[2020-11-23 04:19:43.460 +00:00] [ERR] Error processing request. URL: "http://toaster:8096/web"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ResourceFileManager.GetResourcePath(String basePath, String virtualPath)
   at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Additional context**
Sorry, I don't have a lot to go on here.

**Comment by BaronGreenback** [comment]
Code removed in 10.7.0
