### ISSUE TITLE
Playback breaks after a minute, breaks again after restart (FireTV, Docker)

### ISSUE THREAD

**Issue by totti4ever** [jellyfin/jellyfin#4584]
**Describe the bug**
Playback breaks after like 1 minute. Restarting playback is okay, but then it's breaking again after a minute

**System (please complete the following information):**
 - OS: Host is Ubuntu 18.04
 - Virtualization: Docker
 - Clients: FireTV 4k
 - Browser: Jellyfin app
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: traefik
 - Base URL: none
 - Networking: ?
 - Storage: local

**To Reproduce**
Play episode

**Expected behavior**
no error

**Logs**
```
[21:31:08] [WRN] [18] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS ::ffff:172.16.0.10 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[21:31:08] [INF] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 closed
[21:31:08] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The operation was canceled. URL: http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:31:08] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to 192.168.192.197. Time (slow): 0:01:44.4826207. http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:31:11] [INF] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:31:11] [INF] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:31:12] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://tv.home/Items/2b2bca16aacc8a14d53a11bb829eafa5/Images/Primary?MaxHeight=300&EnableImageEnhancers=true
MediaBrowser.Common.Extensions.ResourceNotFoundException: Live TV does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

```
[21:35:22] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The operation was canceled. URL: http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:35:22] [WRN] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to 192.168.192.197. Time (slow): 0:01:16.615702. http://tv.home/Videos/c004b074eafcb041417c86f6b4a583e6/stream.mkv?DeviceId=d8dff4875dd17dbb&MediaSourceId=c004b074eafcb041417c86f6b4a583e6&Static=true&Tag=01f56d5d40a4fbe0072f8c3140631bd3
[21:35:25] [INF] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:35:25] [INF] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:172.16.0.10 request
[21:35:26] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://tv.home/Items/2b2bca16aacc8a14d53a11bb829eafa5/Images/Primary?MaxHeight=300&EnableImageEnhancers=true
MediaBrowser.Common.Extensions.ResourceNotFoundException: Live TV does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by totti4ever** [comment]
Doesn't happen when transcoding!

**Comment by Artiume** [comment]
is this live tv content?

**Comment by totti4ever** [comment]
Nope, mkv files from local disk

**Comment by Artiume** [comment]
@thornbill you have any ideas? might need to transfer this to atv as well

**Comment by nielsvanvelzen** [comment]
Might be related to jellyfin/jellyfin-androidtv#614 / jellyfin/jellyfin-androidtv#606. Need app logs to fix though.

**Comment by totti4ever** [comment]
What do you mean by app logs? More than above or other?

**Comment by nielsvanvelzen** [comment]
The logs in your post are from the server, we can't fix any issues in the app with those. We need the logs the app produces.

This page explains a bit about how to extract logs: https://wiki.lineageos.org/logcat.html

**Comment by LogicalPhallacy** [comment]
I'm hitting this problem on the AndroidTV app too, I'll try and get logs soon here.

**Comment by totti4ever** [comment]
> The logs in your post are from the server, we can't fix any issues in the app with those. We need the logs the app produces.
> 
> This page explains a bit about how to extract logs: [wiki.lineageos.org/logcat.html](https://wiki.lineageos.org/logcat.html)

Thanks for clarifying - I'll also try to get it soon. Home Assistant is connected to the FireTV via adb, therefore I should hopefully be able to get the logs.
_Problem is, that my wife isn't happy to go the breaking way when watching_ :-D
