### ISSUE TITLE
Removing a version of a movie breaks collections the movie was part of

### ISSUE THREAD

**Issue by ne0phyte** [jellyfin/jellyfin#4601]
**Describe the bug**
I had several versions of movies (1080p and 2160p) which were part of collections. After removing the 1080p version, Jellyfin picked up the change (only 2160p showing up in the library) but also removed them from the collections.
It's now impossible to re-add those movies to the collections. Trying to do so gives a confirmation "Items added" but doesn't do anything.

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 86
 - Jellyfin Version: 10.6.4
 - Playback: n/a
 - Installed Plugins: Kodi Sync Queue, TMDb Box Sets
 - Reverse Proxy: traefik
 - Base URL: none
 - Networking: NAT
 - Storage: docker r/o bind mount for media, rw bind mount for config/cache

**To Reproduce**
1. Add a movie with two version (e.g. 1080p, 2160p)
2. Add the movie to a collection
3. Delete the 1080p version file
4. Wait for Jellyfin to pick up the change or run a library scan
5. The 1080p version is gone from the library and the movie doesn't show up in the collection anymore
6. Try to add the movie from the library via context menu to the collection
7. Jellyfin confirms the action
8. Check the collection, the movie does not show up

**Expected behavior**
Removing a version of a movie should not remove it from the collection in the first place. But if there is no other way, remove all references of the movie from the collection so it can be added again.

**Logs**
I get many entries like this, all of them seem to be movies that are affected by this bug:
`[2020-11-27 23:39:45.368 +00:00] [WRN] [39] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path "/media/Video/Movies/Shaun of the Dead (2004)/Shaun of the Dead (2004) - 1080p.mkv"`

**Comment by hawken93** [comment]
possibly related.

If you have a library with a path: /media/music
change it to: /media/music/artists by removing the old folder and adding the new
scan: fails
remove library
scan: fails

```
[00:59:21] [ERR] [384] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.ArgumentNullException: Value cannot be null. (Parameter 'g')
   at System.Guid..ctor(String g)
   at MediaBrowser.Common.Json.Converters.JsonGuidConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& valu
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(IReadOnlyList`1 reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Bo
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter)
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter)
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter)
   at MediaBrowser.Controller.Entities.Folder.GetRecursiveChildren(Func`2 filter, Boolean includeLinkedChildren)
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, BaseItem parent, Boolean notifyParentItem)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, Met
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, Meta
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetad
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by ne0phyte** [comment]
I checked the library.db and can see that the 1080p version is definitely still referenced. 
Furthermore, every time I try to re-add a movie it seems to create an element in the `LinkedChildren`. I now have several collections that have 5-10 linked children items of the same 2160p movie referenced but fail to show even one, probably due to the orphaned 1080p version reference.

**Comment by ne0phyte** [comment]
I removed all movies from the broken collections and deleted the collections. 
After running the TMDb Box Sets scan again, the collections have been recreated but they were still missing movies.

What seems to fix it is, clearing the `TheMovieDb Box Set Id`  in the movies meta data. 
After doing that I was able to add the affected movies to the new collection again.

**Comment by ferferga** [comment]
@ne0phyte Can you confirm this is the same as #1907?

You can add more details if it's similar but not exactly the same so we can close duplicates.

**Comment by ne0phyte** [comment]
@ferferga I'm not 100% sure, yet, but might be.

I just tried moving a movie back and forth in a way that Jellyfin could still identify it and now after scanning I get a
` MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path`
line for each time I moved it.

**However**, I am able to re-add the movie to the collection. 
This is something that is not working at all when I delete/move just a version of a movie as described above.

It looks like this is the same underlying issue, though, just with slightly different effects for movies with multiple versions.

**Comment by oitdmser** [comment]
I can confirm I have the same issue. Messing with different files/versions of files will often break a movie's ability to be added to collections.

**Comment by oitdmser** [comment]
Note that if I go to Menu -> Metadata, select the problem title, edit nothing, click 'Save', then add it to the collection from there it adds successfully.

**Comment by JonahKr** [comment]
This issue is sadly still a thing.

**Comment by webysther** [comment]
Insane great app dont be able to keep track or give a option to keep track the movie and collection.

**Comment by hdkmike** [comment]
I'm having the same issue and tried the workarounds suggested. No luck for me. Jellyfin Version: 10.8.10. I'm setting up collections manually and am not using the auto collections plugin.

**Comment by theguymadmax** [comment]
Closing in favor of #11736
