### ISSUE TITLE
Possible to get into a bad state after moving library root, then deleting the library

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#4602]
**Describe the bug**
On master, it's possible to end up with System.ArgumentException that breaks the scanning job, getting the server into trouble.

**System (please complete the following information):**
 - OS: debian
 - Virtualization: docker
 - Clients: web
 - Browser: firefox
 - Jellyfin Version: master
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: kubernetes
 - Storage: ceph rbd

**To Reproduce**
1. In library settings, pick a library and remove the root folder
   * removed: /media/music
   * added: /media/music/artists
2. Add some other root folder to replace it. I added a subdirectory
3. Try to scan the library. It fails
4. Delete the library and scan again. It fails

**Expected behavior**
* step 3: reindex the library based on the new path. Delete files no longer in scope etc.
* step 4: Simply delete the library

**Logs**
master dev build trace:
```
[02:40:49] [INF] [28] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Folder, Name: music, Path: /media/music, Id: cc7e13db-3fa0-bede-b991-44e11664c3a4
[02:40:49] [ERR] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.ArgumentNullException: Value cannot be null. (Parameter 'g')
   at System.Guid..ctor(String g)
   at MediaBrowser.Common.Json.Converters.JsonGuidConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /builds/docker/jellyfin/src/MediaBrowser.Common/Json/Converters/JsonGuidConverter.cs:line 14
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(IReadOnlyList`1 reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Boolean hasServiceName, Boolean queryHasStartDate, Boolean hasTrailerTypes, Boolean hasArtistFields, Boolean hasSeriesFields) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 1266
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 2688
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren() in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 590
   at MediaBrowser.Controller.Entities.Folder.LoadChildren() in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 221
   at MediaBrowser.Controller.Entities.Folder.get_Children() in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 175
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 1358
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 1370
   at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 1370
   at MediaBrowser.Controller.Entities.Folder.GetRecursiveChildren(Func`2 filter, Boolean includeLinkedChildren) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 1348
   at MediaBrowser.Controller.Entities.Folder.GetRecursiveChildren(Boolean includeLinkedChildren) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 1336
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, BaseItem parent, Boolean notifyParentItem) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Library/LibraryManager.cs:line 367
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 379
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/Folder.cs:line 299
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /builds/docker/jellyfin/src/MediaBrowser.Controller/Entities/AggregateFolder.cs:line 160
   at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Library/LibraryManager.cs:line 1068
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Library/LibraryManager.cs:line 1093
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) in /builds/docker/jellyfin/src/Emby.Server.Implementations/Library/LibraryManager.cs:line 1054
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in /builds/docker/jellyfin/src/Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 418
```

**Screenshots**
upon request

**Additional context**
This is a kinda shitty bug because now you probably have to edit the database to remove the broken library.

Possibly but not necessarily related to #4601

**Comment by hawken93** [comment]
This is what's happening in the traceback:
* The library scanner concludes it needs to delete the old path.
* All items from the old path are recursively being retrieved from the database (SqliteItemRepository)
* It encounters a json blob in the repository where the guid is null.

Somehow a guid null got written to the database. Investigating...

**Comment by hawken93** [comment]
The 10.6.4 version where I didn't delete the library looks like it's doing better. The library looks like it's properly indexed now.

**Comment by hawken93** [comment]
master instance is still sad

**Comment by hawken93** [comment]
Found a couple of instances of this:
```
UserId None
OwnerUserId None
```

**Comment by hawken93** [comment]
Is it just me, or are we serializing guid empty -> null, but expecting valid guid on read?
I'm gonna make a patch for this.

```csharp
namespace MediaBrowser.Common.Json.Converters
{
    /// <summary>
    /// Converts a GUID object or value to/from JSON.
    /// </summary>
    public class JsonGuidConverter : JsonConverter<Guid>
    {
        /// <inheritdoc />
        public override Guid Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => new Guid(reader.GetString());

        /// <inheritdoc />
        public override void Write(Utf8JsonWriter writer, Guid value, JsonSerializerOptions options)
        {
            if (value == Guid.Empty)
            {
                writer.WriteNullValue();
            }
            else
            {
                writer.WriteStringValue(value);
            }
        }
    }
}
```
