### ISSUE TITLE
CustomAuthentication was not authenticated. Failure message: Invalid token.

### ISSUE THREAD

**Issue by nyanmisaka** [jellyfin/jellyfin#4627]
**Describe the bug**
Bunch of `Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.` in the log.

**System (please complete the following information):**
 - OS: Debian, Windows
 - Clients: Browser
 - Browser: Chrome, Safari
 - Jellyfin Version: 10.7.0, unstable 20201130
 - Playback: Direct Play, Remux, Direct Stream, Transcode
 - Storage: local

**To Reproduce**
1. Start Jellyfin
2. Login
3. Go to dashboard->logs

**Expected behavior**
This failure info should be in debug mode.

**Logs**
`Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.`

**Comment by Ninnteen** [comment]
Same problem here.

**Comment by Ninnteen** [comment]
Just before i'm starting a new issue, is it linked to the fact that i can't play anything? Or is it an other bug that needs it's own issue?

**Comment by nyanmisaka** [comment]
> Just before i'm starting a new issue, is it linked to the fact that i can't play anything? Or is it an other bug that needs it's own issue?

It's irrelevant to this failure message. The 20201130 build is broken which should be fixed in https://github.com/jellyfin/jellyfin-web/pull/2150

**Comment by woodspire** [comment]
Having the same problem on version 20210123.

**Comment by dessalines** [comment]
I had to clear cookies AND local storage to get past this issue.

**Comment by woeisme** [comment]
@dessalines could you elaborate, where did you need to clear them from exactly?

**Comment by dessalines** [comment]
Look up how to do that for your browser.

**Comment by zyzyx159** [comment]
Try opening the page in a private window. If that works you need to look up how to clear cache and cookies for your browser.

**Comment by C0untZero** [comment]
I just had the same issue trigger my spidey sense - luckily I figured it out quickly.

I've added Jellyfin to Heimdall, but didn't provide Heimdall with an API key.

So whenever I opened a new tab which defaulted to Heimdall the widget was trying to grab metadata from Jellyfin and failing authentication, even though when you edit the app from Heimdall and click test with no API key it passes.

**Comment by RTUnit** [comment]
I faced the error `CustomAuthentication was not authenticated` in Jellyfin server console when I typed hostname and port in the Add Server dialog.
![image](https://user-images.githubusercontent.com/41525963/212562418-4944f634-a4e7-4fd4-a4ce-a31671ef60c7.png)
I noticed the SSL error in DevTools console:
![image](https://user-images.githubusercontent.com/41525963/212562443-497caeb6-b440-4fde-a87d-8e4e45a84f92.png)

I could not figure out how to reset the tokens. or find some way how to workaround this problem.

Luckily I run Jellyfin on Docker, so I just had to delete container, and create again. I have a few settings listed which I need to repeat every time I do this. Libraries and other configuration (like CSS) remained the same (they are stored in files, which I pass as --volume to container).

Just recently I configured union directory (mount overlay) which I am passing in --volume to Jellyfin container. Also checked "Nfo" and "Save artwork..." for each library, and now all posters and metadata is stored in separate directory structure.

**Comment by RTUnit** [comment]
I am still facing this error once in a week with 10.8.8 and now with 10.8.9. I cannot login from neither of my devices - it does not let me to get to the login screen. I just delete Jellyfin docker container and re-create it from command line. Then I need to make some of the configuration which was reset to defaults. It works for a week or so.

```
[2023-01-30 12:39:57.939 +00:00] [INF] [98] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
[2023-01-30 12:39:57.944 +00:00] [INF] [98] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
```

Is there any diagram where I can learn which components (source code) are involved with authentication? Maybe I can figure out where is the problem... but just where to start I wonder.

**Comment by RTUnit** [comment]
One weird thing I notice that below following URLs return HTTP **503 Service Unavailable** with response message: **Jellyfin Server is loading. Please try again shortly.**

- http://server:8096/System/Info/Public
- http://server:8096/Branding/Css
- http://server:8096/system/info/public

As far I checked this response message comes from Jellyfin.Server\Middleware\**ServerStartupMessageMiddleware.cs**
```
        public async Task Invoke(
            HttpContext httpContext,
            IServerApplicationHost serverApplicationHost,
            ILocalizationManager localizationManager)
        {
            if (serverApplicationHost.CoreStartupHasCompleted
                || httpContext.Request.Path.Equals("/system/ping", StringComparison.OrdinalIgnoreCase))
            {
                await _next(httpContext).ConfigureAwait(false);
                return;
            }

            var message = localizationManager.GetLocalizedString("StartupEmbyServerIsLoading");
            httpContext.Response.StatusCode = StatusCodes.Status503ServiceUnavailable;
            httpContext.Response.ContentType = MediaTypeNames.Text.Html;
            await httpContext.Response.WriteAsync(message, httpContext.RequestAborted).ConfigureAwait(false);
        }
```
The actual message is in dictionary: Emby.Server.Implementations\Localization\Core\**en-GB.json**
```
"StartupEmbyServerIsLoading": "Jellyfin Server is loading. Please try again shortly."
```

Does it mean that middleware is busy with some kind of task and therefore does not want to respond to front-end?!

**Comment by RTUnit** [comment]
After enabling all Debug logs on server, there are more messages now in the log file. Not sure if the same was logged for @nyanmisaka or I have a different problem (with same symptoms).

```
[2023-01-30 20:34:49.970 +00:00] [INF] [19] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://server:8096/System/Info/Public - -
[2023-01-30 20:34:49.970 +00:00] [DBG] [19] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "/System/Info/Public" does not match a supported file type
[2023-01-30 20:34:49.970 +00:00] [DBG] [19] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:49.970 +00:00] [DBG] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2023-01-30 20:34:49.970 +00:00] [DBG] [19] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:49.970 +00:00] [DBG] [19] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:49.971 +00:00] [DBG] [19] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: 1 candidate(s) found for the request path '"/System/Info/Public"'
[2023-01-30 20:34:49.971 +00:00] [DBG] [19] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Endpoint '"Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo (Jellyfin.Api)"' with route pattern '"System/Info/Public"' is valid for the request path '"/System/Info/Public"'
[2023-01-30 20:34:49.971 +00:00] [DBG] [19] Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Request matched endpoint '"Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo (Jellyfin.Api)"'
[2023-01-30 20:34:49.971 +00:00] [DBG] [19] Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: The response will be compressed with '"gzip"'.
[2023-01-30 20:34:49.971 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAH"" completed keep alive response.
[2023-01-30 20:34:49.971 +00:00] [INF] [19] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://server:8096/System/Info/Public - - - 503 - text/html 1.4504ms
[2023-01-30 20:34:56.211 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAJ"" accepted.
[2023-01-30 20:34:56.211 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAJ"" started.
[2023-01-30 20:34:56.212 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.BadRequests: Connection id ""0HMO305L0OKAJ"" bad request data: ""Detected a TLS handshake to an endpoint that does not have TLS enabled.""
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Detected a TLS handshake to an endpoint that does not have TLS enabled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethodLength(ReadOnlySpan`1 span)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySpan`1 requestLine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
[2023-01-30 20:34:56.214 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAJ"" disconnecting.
[2023-01-30 20:34:56.214 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAJ"" stopped.
[2023-01-30 20:34:56.215 +00:00] [DBG] [14] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id ""0HMO305L0OKAJ"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
[2023-01-30 20:34:56.221 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAK"" accepted.
[2023-01-30 20:34:56.221 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAK"" started.
[2023-01-30 20:34:56.221 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.BadRequests: Connection id ""0HMO305L0OKAK"" bad request data: ""Detected a TLS handshake to an endpoint that does not have TLS enabled.""
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Detected a TLS handshake to an endpoint that does not have TLS enabled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethodLength(ReadOnlySpan`1 span)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySpan`1 requestLine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
[2023-01-30 20:34:56.222 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAK"" disconnecting.
[2023-01-30 20:34:56.222 +00:00] [DBG] [19] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAK"" stopped.
[2023-01-30 20:34:56.222 +00:00] [DBG] [11] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id ""0HMO305L0OKAK"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
[2023-01-30 20:34:56.335 +00:00] [INF] [13] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://server:8096/system/info/public - -
[2023-01-30 20:34:56.335 +00:00] [DBG] [13] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "/system/info/public" does not match a supported file type
[2023-01-30 20:34:56.336 +00:00] [DBG] [13] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:56.336 +00:00] [DBG] [13] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2023-01-30 20:34:56.336 +00:00] [DBG] [13] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:56.336 +00:00] [DBG] [13] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2023-01-30 20:34:56.338 +00:00] [DBG] [13] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: 1 candidate(s) found for the request path '"/system/info/public"'
[2023-01-30 20:34:56.338 +00:00] [DBG] [13] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Endpoint '"Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo (Jellyfin.Api)"' with route pattern '"System/Info/Public"' is valid for the request path '"/system/info/public"'
[2023-01-30 20:34:56.338 +00:00] [DBG] [13] Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Request matched endpoint '"Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo (Jellyfin.Api)"'
[2023-01-30 20:34:56.339 +00:00] [DBG] [13] Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: The response will be compressed with '"gzip"'.
[2023-01-30 20:34:56.339 +00:00] [DBG] [13] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMO305L0OKAH"" completed keep alive response.
[2023-01-30 20:34:56.339 +00:00] [INF] [13] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://server:8096/system/info/public - - - 503 - text/html 3.6934ms
```

My observations:

- I do not have TSL / SSL / HTTPS enabled (**EnableHttps** is **false** in **network.xml**).
- I also tried accessing the server with IP address instead of hostname.
- Tried to change **IsStartupWizardCompleted** to **false** and back to **true** in **system.xml** and restarted Jellyfin before and after.
- Tried to set env variable **JELLYFIN_PublishedServerUrl** in Jellyfin server (found suggested in some post)

Can the problem be concerning web server internal request to Jellyfin.Api? Request from browser to API: **http://server:8096/jellyfin/System/Info?ai_key=cd91e93fc88e4148b376d772a4b4c340** results in a blank page with text:
```
Jellyfin Server is loading. Please try again shortly.
```

I have no clue what can be wrong, and I am out of options what can I try. Will re-create container and backup sqlite db files, perhaps I will be able to workaround this problem by restoring working db files.

**Comment by RTUnit** [comment]
I feel so stupid. The problem was caused by my own workaround script which cleans up transcoding directory, running in background every time when FFMPEG is launched. Seems that the background process was causing irresponsiveness of the server **during startup**. If I disable the script and let Jellyfin start then I can enable the script and Jellyfin works like a Swiss clock.

Have updated [my original post](https://github.com/jellyfin/jellyfin/issues/3929#issuecomment-1370299811) with a warning.
