### ISSUE TITLE
MusicBrainz XMLException: Data at the root level is invalid

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#4631]
**Describe the bug**
This stacktrace appears during music scans:

```
[2020-12-01 14:48:44.045 +00:00] [ERR] [17] MediaBrowser.Providers.Music.AlbumMetadataService: Error in "MusicBrainz"
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.ReleaseResult.Parse(XmlReader reader)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResult(String albumName, String artistId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResult(String albumName, String artistId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: Docker
 - Jellyfin Version: 10.7, unstable 20201130.24]
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: HDD

**To Reproduce**

##### First way
1. Make sure you have a music library with MusicBrainz as a provider.
2. Scan your library using the scheduled task or the button in the main dashboard page.

##### Second way
1. Dashboard > Libraries.
2. Locate a library that contains music and click on "Scan library" in the context menu.
3. Choose "Search for missing tags"

**Expected behavior**
MusicBrainz working and no exception appears in the log.

**Comment by BaronGreenback** [comment]
This might be of use. https://github.com/BaronGreenback/Jellyfin-DLNA-PlayTo/blob/master/PlayTo/Model/XMLUtilities.cs

I had to write a "loose" parser as not all dlna devices return properly formatted xml.

**Comment by ferferga** [comment]
@BaronGreenback Let's see if @crobibero PR fixes it and I'll report back
