### ISSUE TITLE
Crash on Music scan

### ISSUE THREAD

**Issue by bobberb** [jellyfin/jellyfin#465]
**Version**: Since the GPL cleanup, on master commit= f8a720d3d8adbdb1f092a42e592dae37ba3f25bb or dev commit= 12f29ebaf7a3ec3ad304ef9a9a27dfec142edfec
**Platform**: Arch Linux x64 - fully updated as of 31/12/2019 - packages built using either regular AUR package or AUR package with added `#branch=dev` 

**Expected behavior**: ID and integration of album into database, proper display
**Results**: Jellyfin crashes (e.g. searching Janelle Monae), artist view is limited to one artist. Albums remain named as the folder name and not the id3 tag. 

> [2019-01-06 18:23:20.963 -05:00] [INF] HttpClientManager "GET": "https://www.musicbrainz.org/ws/2/release/?query="Dirty+Computer" AND artist:"Janelle+Mon%C3%A1e"$
[2019-01-06 18:23:22.105 -05:00] [INF] HttpClientManager "GET": "https://www.theaudiodb.com/api/v1/json/49jhsf8248yfahka89724011/album-mb.php?i=c3b6435c-2698-4909-98$
9-d80439e180fe"
[2019-01-06 18:23:22.679 -05:00] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

screenshots:
[Screenshot of Artist view](https://matrix.org/_matrix/media/v1/download/matrix.org/uxhMLhUqjSeTeGGcmtEPsitb)
[Screenshot of successful scrape](https://matrix.org/_matrix/media/v1/download/matrix.org/qLyoopiodAoWYTsZJJbeUppn)

notes:
#257 - Could be related.

**Crash after GET call to theaudiodb**

**Comment by bobberb** [comment]
Per flowlee in the chat, note the trailing $ for the query.

**Comment by joshuaboniface** [comment]
Likely a missing `using MediaBrowser.Model.Extensions;` as found in chat. CC @Bond-009

**Comment by anthonylavado** [comment]
Alright, to get some traction on this, I will look at this tonight, and finally add music to my test library.

**Comment by bobberb** [comment]
Notes from dev chat:

It also seems the Music library continues to scrape metadata from theaudiodb despite not ticking the box.

**Comment by anthonylavado** [comment]
Okay, so I've just started testing this. I picked a couple of artists I expected would break it:
- Maxïmo Park
- Ke$ha
- Cow'p
- !!!

They all got identified and play fine, no errors in the logs.

Things still left to investigate:
- Try with an artist that has a different accent (like Janelle Monáe)
- Why are album track counts off?
- Test disabling theaudiodb on library creation
- Test disabling theaudiodb _after_ library creation

**Comment by bobberb** [comment]
Actually,

   - Maxïmo Park
   - Ke$ha
   - Cow'p
   - !!!

Are all part of ASCII up to 255! Not unicode :P

(Could be off-base with the whole premise but those above don't rule out
immediately)

**Comment by bobberb** [comment]
Keeping a close eye on this for the interesting cases you might separately encounter.

**Comment by anthonylavado** [comment]
**Track Counts**
Haven't "tracked" this down yet, but I have observed that the track count in my library is always:
`Total Number of Tracks + 6`

This is consistent, even when deleting or adding tracks/albums.

**Janelle Monáe, the accent issue**
I went out and tried Janelle Monáe. Couldn't reproduce this still. It works.

**Comment by bobberb** [comment]
Addendum: á is ASCII (extended) as well - scratch the above.

**Comment by anthonylavado** [comment]
Lines from my log:

```
[2019-01-11 02:19:53.976 -05:00] [INF] HttpClientManager "GET": "https://www.musicbrainz.org/ws/2/release/?query=\"Dirty+Computer\" AND artist:\"Janelle+Mon%C3%A1e\""
```
```
[2019-01-11 02:19:54.949 -05:00] [INF] HttpClientManager "GET": "https://www.theaudiodb.com/api/v1/json/49jhsf8248yfahka89724011/album-mb.php?i=c3b6435c-2698-4909-9879-d80439e180fe"
```

**Comment by bobberb** [comment]
```
[2019-01-11 02:37:15.260 -05:00] [INF] HttpClientManager "GET": "https://www.theaudiodb.com/api/v1/json/49jhsf8248yfahka89724011/album-mb.php?i=81dc4274-a559-3ce9-b5e9-73292c4773d7"
[2019-01-11 02:37:15.960 -05:00] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by anthonylavado** [comment]
**Number of Tracks**

It's the total number of items in your library. I have six other items in my library, hence the `+6` all the time.

**Comment by bobberb** [comment]
@anthonylavado  

I've been able to bring in my albums into the library (with art and ID for artist) (with some major slowdowns) by disabling all the checkboxes for theaudiodb, however, even when the checkboxes are disabled, the service still crashes every 2 minutes when the machine GETS 
`https://www.theaudiodb.com/api/v1/json/49jhsf8248yfahka89724011/artist-mb.php?i=baddd933-bd01-42d3-a370-d858b7ed37f3` on each boot. 

returns `{"artists":null}`

**Comment by anthonylavado** [comment]
@bobberb I just tried search that ID in Musicbrainz and it brings up this: https://musicbrainz.org/artist/baddd933-bd01-42d3-a370-d858b7ed37f3

**Comment by anthonylavado** [comment]
Either way, we should handle the null gracefully. We essentially have an I caught exception there

**Comment by bobberb** [comment]
@anthonylavado 

a temporary hack,  not 100%, at https://github.com/bobberb/jellyfin/commit/799fd866ca4d68fa499414b6491f8fcf8fc15996

You can see a small diff  commenting out the default disabled array. 

Despite commenting out those lines, JF will STILL make a call to theaudiodb on requesting of a "Metadata Refresh" and crash all the same. 

Most prominent of the user-facing issues is the lack of respect for the checkbox -- if jellyfin can be made to actually respect the user selection to disable this provider my issue will be addressed. Secondary is my personal crashing on calling audiodb, which I have yet to see anyone confirm 😢

**Comment by bobberb** [comment]
@anthonylavado  running fresh build clean DB head of 10.1.0 -- still crashing. Found this:

https://github.com/dotnet/corefx/issues/30691

**Comment by cvium** [comment]
Jellyfin uses a custom HTTP and Socket listener though.

**Comment by bobberb** [comment]
This persists in 10.1.0 now in master eb8c04f023e4db086910aed91cfc9d8e0f97106e . Same error:

``[2019-01-22 18:35:13.097 -05:00] [INF] HttpClientManager "GET": "https://www.theaudiodb.com/api/v1/json/195003/album-mb.php?i=81dc4274-a559-3ce9-b5e9-73292c4773d7"
[2019-01-22 18:35:13.798 -05:00] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[2019-01-22 18:35:14.998 -05:00] [INF] Jellyfin version: "10.1.0.0"

[2019-01-22 18:35:15.022 -05:00] [INF] Arguments: ["/usr/lib/jellyfin/jellyfin.dll", "-programdata", "/var/lib/jellyfin", ""]

[2019-01-22 18:35:15.028 -05:00] [INF] Operating system: "Linux" "4.19.15.1 "

[2019-01-22 18:35:15.028 -05:00] [INF] Architecture: X64``

**Comment by anthonylavado** [comment]
@bobberb - I forget if we said this might be the result of porting over the library? If it's set up fresh for Music, does this persist?

**Comment by bobberb** [comment]
Yup. Still occurs on clean install.

**Comment by Matt07211** [comment]
Also getting this problem, disabling audiodb and it doesn't crash

**Comment by bobberb** [comment]
Good to see all my issues confirmed @matt07211, thanks.

**Comment by Matt07211** [comment]
That was on the 10.1.0 release, I'll be trying it again on current master (as of yesterday) and I'll report back if the results are different

**Comment by daniel-widrick** [comment]
So This still appears to be an issue...

The linux-x64 release version of Jellyfin crashes.
Building from source on master crashes.

I was able to build from source (running inside visual studio) in windows 10 and could not replicate the error:

[05:09:19] [INF] HttpClientManager GET: https://www.theaudiodb.com/api/v1/json/195003/album-mb.php?i=8fd32554-02a7-3788-a761-7012e0e75e55
[05:09:20] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted

**Comment by daniel-widrick** [comment]
As far as I have been able to dig so far, this APPEARS to be related to the ssl handshake. (Can't get any exceptions to trigger before then so far).

For the time being I have added the following to my server as a REALLY hacky stop gap:
```
iptables -A OUTPUT -m tcp -p tcp --dport 443 -d www.theaudiodb.com -j REJECT
```

**Comment by JustAMan** [comment]
For you guys who have it failing - does it fail only on some non-ASCII names, or does it fail on anything?
Assuming you're using latest release, so we're on the same page.

**Comment by daniel-widrick** [comment]
I believe it's failing on almost any request to theaudiodb if not every request. I wouldn't expect the names to play a role as the query doesn't appear to include any names:

**Comment by bobberb** [comment]
My original ASCII - Unicode theory was bunk. It is the SSL handshake itself
that is failing.

Very likely could be their fault:

https://www.ssllabs.com/ssltest/analyze.html?d=theaudiodb.com

They don't support modern crypto! Look at all those handshake failures
(despite TLS 1.2 being present)

**Comment by bobberb** [comment]
Pardon, lack of renegotiation**

**Comment by daniel-widrick** [comment]
It's certainly something non-ideal on their end but it would be nice to catch the exception and not kill all of jellyfin because they can't play nice with modern crypto. 

I haven't been able to track down where in the code such a catch could be placed(haven't had a ton of time to work on it), and potentially it still is a bug in .NET Core on linux that will need an upstream fix?

**Comment by daniel-widrick** [comment]
https://github.com/jellyfin/jellyfin/pull/1080

Still appears to have the crash

```
[22:27:41] [INF] HttpClientManager GET: https://www.musicbrainz.org/ws/2/release/?query="Garage+Inc+Cd+2" AND arid:65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab
[22:27:42] [INF] HttpClientManager GET: https://webservice.fanart.tv/v3.1/music/65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab?api_key=184e1a2b1fe3b94935365411f919f638
[22:27:44] [INF] HttpClientManager GET: https://www.theaudiodb.com/api/v1/json/195003/artist-mb.php?i=65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab
[22:27:45] [FTL] Unhandled Exception
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted
```

**Comment by 0ddb0d** [comment]
This issue also affected Emby on Linux see: [https://emby.media/community/index.php?/topic/61243-server-crashing-within-minutes/](url) Unfortunately this doesn't help resolving it as the fix was made after the server source went private :(

**Comment by DrPandemic** [comment]
My 2 cents on the subject, .NET Core 3.0 will let us catch that exception https://github.com/dotnet/corefx/pull/34089. I think that as long as we use their HTTPClient we won't be able to catch that error before 3.0.

**Comment by bobberb** [comment]
#1193  still active on a fresh install of 10.3.1

**Comment by anthonylavado** [comment]
This is going to keep shifting unless we can figure out a way to handle it.

@DrPandemic Are you saying we're probably best waiting for 3.0 on this?

**Comment by DrPandemic** [comment]
I think it's the safest and easiest solution, but the one that we will need to wait the longest. I see 3 options

- Wait for 3.0 and refactor the code to catch the new exception.
- Change which http client library we use. This would be a lot of work.
- Use a version of .NET Core which is not on the default release branch. https://github.com/dotnet/corefx/pull/34089 was applied last year so, I'm sure it's part of some release somewhere. I'm not the biggest fan of not using the default releases.

**Comment by anthonylavado** [comment]
This issue has been reported again by another user in our Matrix Chat. The logs they provided are here:
https://pastebin.com/mMPTyaCK

**Comment by bobberb** [comment]
@DrPandemic @anthonylavado just in time for corefx 3.0! 💃 

https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview7.md

we're very close to release on that with the merge.

**Comment by anthonylavado** [comment]
Arrgh. I'd like to see this get resolved in the new version, but I don't know the effort involved.

**Comment by bobberb** [comment]
@anthonylavado @cvium  @JustAMan 

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/?WT.mc_id=social-twitter-marouill

**Comment by leaty** [comment]
Has this been patched with the move to .NET Core 3.1?

**Comment by Bond-009** [comment]
Possibly

**Comment by bobberb** [comment]
~1 year later, I am beyond happy to see that the .NET Core 3.1 bump has finally fixed this SSL error.

**Comment by bobberb** [comment]
@anthonylavado @Bond-009 @JustAMan @ all those who helped:

Thank you!!

**Comment by drgnomage** [comment]
Awesome news, thank you to everyone involved.

**Comment by JustAMan** [comment]
Why did you reopen that? If it's fixed please close it :)

**Comment by bobberb** [comment]
It wasn't me, I swear! 😢
