### ISSUE TITLE
Jellyfin cannot play ipv6 m3u address

### ISSUE THREAD

**Issue by rty813** [jellyfin/jellyfin#4656]
**Describe the bug**

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Windows
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] Browser
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Edge 87.0.664.52
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1.  Add M3U Tuner 
[TV-EDU-LZU.zip](https://github.com/jellyfin/jellyfin/files/5642152/TV-EDU-LZU.zip)
Note that this m3u tuner can only be used in IPv6.
2. Play <CCTV1> Channel

**Expected behavior**

Play <CCTV1> Channel.
But it keeps loading.

**Logs**

    [2020-12-04 08:39:03.657 +00:00] [INF] [28] MediaBrowser.Api.Playback.MediaInfoService: User policy for "rty813". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
    [2020-12-04 08:39:03.657 +00:00] [INF] [28] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", Path: "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
    [2020-12-04 08:39:03.657 +00:00] [INF] [28] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", No direct play profiles found for Path: "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8"
    [2020-12-04 08:39:03.657 +00:00] [INF] [28] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", Path: "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
    [2020-12-04 08:39:03.657 +00:00] [INF] [28] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", No direct play profiles found for Path: "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8"
    [2020-12-04 08:39:03.666 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.LiveTvManager: Opening channel stream from "Emby", external channel Id: "m3u_f003dc0f6d2358a7314f85143805117f665b3fe311c4b807ee5fbf19e58015aa"
    [2020-12-04 08:39:03.671 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Streaming Channel m3u_f003dc0f6d2358a7314f85143805117f665b3fe311c4b807ee5fbf19e58015aa
    [2020-12-04 08:39:03.680 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Live stream opened after 0.0884ms
    [2020-12-04 08:39:03.681 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Returning mediasource streamId "f9d4327d0024ce6c0b69a46abf4ab9ae", mediaSource.Id "f9d4327d0024ce6c0b69a46abf4ab9ae", mediaSource.LiveStreamId null
    [2020-12-04 08:39:03.690 +00:00] [INF] [28] Emby.Server.Implementations.Library.MediaSourceManager: Waiting 3000ms before probing the live stream
    [2020-12-04 08:39:06.694 +00:00] [INF] [63] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 3000000 -i \"http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8\" -threads 0 -v warning -print_format json -show_streams -show_format"
    [2020-12-04 08:39:15.097 +00:00] [INF] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:127.0.0.1" closed
    [2020-12-04 08:39:16.145 +00:00] [ERR] [21] Emby.Server.Implementations.Library.MediaSourceManager: Error probing live tv stream
    System.Exception: ffprobe failed - streams and format are both null.
    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
    at Emby.Server.Implementations.Library.LiveStreamHelper.AddMediaInfoWithProbe(MediaSourceInfo mediaSource, Boolean isAudio, String cacheKey, Boolean addProbeDelay, CancellationToken cancellationToken)
    at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)

**Screenshots**

**Additional context**

I can play this m3u file from my PC which is in the same LAN network as the docker.
So, why cannot jellyfin play ipv6 m3u tuner?

**Comment by nyanmisaka** [comment]
Could you run this command and paste the output here?
```
/usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 3000000 -i "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8" -threads 0 -v warning -print_format json -show_streams -show_format
```

**Comment by rty813** [comment]
In1:  `/usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 3000000 -i "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8" -threads 0 -v warning -print_format json -show_streams -show_format`
Out1: 
```
{
[http @ 0x55b6e11260c0] HTTP error 503 Service Unavailable
http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8: Server returned 5XX Server Error reply
}
```

In2:  `ping6 hdtv.lzu6.edu.cn`
Out2:  
```
PING hdtv.lzu6.edu.cn(cernet2.net (2001:da8:c000:1201:f816:3eff:fe09:940e)) 56 data bytes
64 bytes from cernet2.net (2001:da8:c000:1201:f816:3eff:fe09:940e): icmp_seq=1 ttl=52 time=102 ms
64 bytes from cernet2.net (2001:da8:c000:1201:f816:3eff:fe09:940e): icmp_seq=3 ttl=52 time=105 ms
64 bytes from cernet2.net (2001:da8:c000:1201:f816:3eff:fe09:940e): icmp_seq=4 ttl=52 time=98.5 ms
```

And I tried to play this m3u8 from potplayer, and it succeed.

**Comment by nyanmisaka** [comment]
That's weird. ffmpeg/ffprobe get a 503 error that result in the failure of probing stream info.
I haven't tried IPv6 streams in ffmpeg but I think it should be supported.

Can you install the ffplay from repo and try to play the source with it?
`ffplay -i "http://hdtv.lzu6.edu.cn/hls/cctv1hd.m3u8"`

**Comment by rty813** [comment]
Probably due to docker.
![Snipaste_2020-12-04_20-25-48](https://user-images.githubusercontent.com/22488813/101163750-04849680-366f-11eb-980c-ff0c760a8f71.png)
I cannot figure out why....

**Comment by rty813** [comment]
![微信图片_20201204204833](https://user-images.githubusercontent.com/22488813/101165823-419e5800-3672-11eb-9ef3-52e51af758b1.png)
This is my jellyfin docker inspect. It uses host network instead of bridge network, and I can ping ipv6 address in docker.

**Comment by rty813** [comment]
Oh I know. Its because I set proxy in docker.... 
Sorry to bother,,
