### ISSUE TITLE
3 or more digits in episode title is used as epsiode number

### ISSUE THREAD

**Issue by blooregardskotch** [jellyfin/jellyfin#4666]
**Describe the bug**
Filenames that contains 3 or more digits for the episode title gets used for the episode number.

30 Rock/Season 5/5x20 100 (Part 1) -> Season 5 Episode 100
30 Rock/Season 5/5x21 100 (Part 2) -> Season 5 Episode 100
The Munsters/Season 2/2x06 Happy 100th Anniversary -> Season 2 Episode 100
Bob Burgers/Season 6/6x11 House of 1000 Bounces -> Season 6 Episode 100
Futurama/Season 1/1x01 Space Pilot 3000 -> Season 1 Episode 300

 - OS: Arch
 - Virtualization: bhyve
 - Clients: Browser, Android, Emby on LGTV
 - Browser: Firefox 68.1.2 ESR
 - Jellyfin Version: 10.6.4
 - Playback: NA
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Bridged
 - Storage: Local/FreeNAS

**To Reproduce**
Name any media file to the one of the above and scan

**Expected behaviour**
Only use the number after the x or E for episode number.

**Logs**
Upon Request

**Screenshots**
![image](https://user-images.githubusercontent.com/16447708/101234007-0576f180-368a-11eb-9a57-b5128ffe4cb8.png)
![image](https://user-images.githubusercontent.com/16447708/101234009-0871e200-368a-11eb-8e3f-6d95e7cba014.png)
![image](https://user-images.githubusercontent.com/16447708/101234010-0a3ba580-368a-11eb-9fd3-25a43bf8d05b.png)
![image](https://user-images.githubusercontent.com/16447708/101234011-0c056900-368a-11eb-9db1-fda02894eb2c.png)

**Additional context**
Thought it may be related it issue #4429 but the Season number does not change and a 4 digit number is truncated to 3 digit episode number.

**Comment by blooregardskotch** [comment]
From /var/lib/jellyfin/log when I attempted to re-add "1x01 Space Pilot 3000". Looks like TheTVDB plugin attempts to pull the epsidoe information but Season 1 Episode 300 does not exist. Please let me know if there is a different log file to look at. (ignore the time

Moved the file off the server and refresh the season
<pre>[2020-12-05 00:05:53.101 -05:00] [INF] [55] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "1x01 Space Pilot 3000", Path: "/media/Video/TV Shows/Futurama/Season 1/1x01 Space Pilot 3000.avi", Id: b8ae559b-7791-883d-bddc-7dee4786a2bd</pre>

Moved the file back to the server and refresh the season
<pre>[2020-12-05 00:09:03.145 -05:00] [INF] [38] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "a71db6026e2eb966fb610297b4620f6c"
[2020-12-05 00:09:03.966 -05:00] [ERR] [34] MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:1 EpisodeNumber:300]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 296
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 218
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeProvider.cs:line 103
[2020-12-05 00:09:04.000 -05:00] [ERR] [34] MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "73871"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:1 EpisodeNumber:300]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 296
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbClientManager.cs:line 218
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken) in /home/jellyfin/jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeImageProvider.cs:line 65
[2020-12-05 00:09:04.599 -05:00] [INF] [59] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "a71db6026e2eb966fb610297b4620f6c"</pre>

**Comment by blooregardskotch** [comment]
I performed a fresh install of 10.7.0 and this issue persist. 1x01 Space Pilot 3000.
"1x01 Space Pilot 3000" returns as season 1 episode 300.
As a test I renamed "1x01 Space Pilot 3000" to "Space Pilot 3000 1x01" which returned expected season 1 episode 1.

I started digging around and found the regex defined in jellyfin/Emby.Naming/Common/NamingOptions.cs
I manually tested each expression and could not find a match for "1x01 Space Pilot 3000"
I found a match for "Space Pilot 3000 1x01" - [\\\\/\\._ \\[\\(-]([0-9]+)x([0-9]+(?:(?:[a-i]|\\.[1-9])(?![0-9]))?)([^\\\\/]*)$
Interesting as the comments reference Kodi and it worked in Kodi (many versions ago, can't say if it matches now)

Currently playing around as I am not familiar with .net regex. In PHP it would be something like .*?[Ss]?(\d+)[EeXx]?(\d+).*
- Zero or More Anything (not greedy)
- Zero or One S or s
- All digits is first capture (season)
- Zero or One E or e or X or x
- All digits is second capture (episode)
- Zero or More anything else

**Comment by cvium** [comment]
Not strictly a duplicate but it's the same issue https://github.com/jellyfin/jellyfin/issues/1180
