### ISSUE TITLE
Using unknown field when requesting similar items

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#4695]
**Describe the bug**
When loading similar entries in the item detail page this error is thrown in the server:
```
[2020-12-06 13:23:21.578 +01:00] [WRN] [72] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: UserData is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'UserData' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
```

It indicated that the `Fields` parameter contains an unknown value (`UserData`).

Server Version: 10.7.0~rc1
Reproduce: Open item detail page and watch server logs.

Note: The server still returns data so this is a low priority issue.

**Comment by crobibero** [comment]
This is an issue on the client side as it’s sending an invalid Enum value.

I should probably make the error message more descriptive...

**Comment by nielsvanvelzen** [comment]
Lol this issue was meant for jellyfin-web. My bad
