### ISSUE TITLE
SQLite exception - cannot rollback: Triggered during playback

### ISSUE THREAD

**Issue by MidnightSnowleopard** [jellyfin/jellyfin#4714]
**Describe the bug**
Playback ceases without input.  It does not seem to be affected by the type of media though perhaps transcoding plays a role in it.  It has happened with audio and video files both.  Issue does not seem to be present in same exact situation on.  Final error message about SQLite rollback failure.  Time before the issue manifests is variable with sometimes 2-5 minutes and sometimes up to 50 minutes.

**System (please complete the following information):**
 - OS: Centos 7
 - Virtualization: Docker/Kubernetes
 - Clients: Browser and Android
 - Browser: Firefox 84, Chromium 78, Chromium 84
 - Jellyfin Version: stable-rc
 - Playback: Transcode
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: NFS

**To Reproduce**
1. Begin playback of media file.
2. Wait for error to manifest

**Expected behavior**
Continue playback without error or interruption

**Logs**
```
[2020-12-07 02:27:11.440 +00:00] [WRN] [105] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5920.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.9158941 with Status Code 200
[2020-12-07 02:27:22.711 +00:00] [WRN] [105] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5924.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.1832975 with Status Code 200
[2020-12-07 02:27:36.978 +00:00] [WRN] [101] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5929.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.5407632 with Status Code 200
[2020-12-07 02:28:28.047 +00:00] [WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5946.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.515055 with Status Code 200
[2020-12-07 02:29:05.178 +00:00] [WRN] [115] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5958.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.6837611 with Status Code 200
[2020-12-07 02:29:07.506 +00:00] [WRN] [102] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5959.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.0083688 with Status Code 200
[2020-12-07 02:29:13.014 +00:00] [WRN] [115] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5961.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.5114978 with Status Code 200
[2020-12-07 02:30:43.331 +00:00] [WRN] [102] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5969.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.5241957 with Status Code 200
[2020-12-07 02:30:46.573 +00:00] [WRN] [111] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5970.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.7636641 with Status Code 200
[2020-12-07 02:30:49.931 +00:00] [WRN] [105] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5971.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.1168174 with Status Code 200
[2020-12-07 02:30:59.292 +00:00] [WRN] [112] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5974.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.5552329 with Status Code 200
[2020-12-07 02:31:02.309 +00:00] [WRN] [115] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5975.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:01.5697311 with Status Code 200
[2020-12-07 02:31:04.309 +00:00] [WRN] [112] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5976.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.5651192 with Status Code 200
[2020-12-07 02:34:21.870 +00:00] [WRN] [109] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/5983.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.6369452 with Status Code 200
[2020-12-07 02:35:51.914 +00:00] [WRN] [111] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6013.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.7013624 with Status Code 200
[2020-12-07 02:35:57.752 +00:00] [WRN] [89] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6015.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.6306389 with Status Code 200
[2020-12-07 02:36:15.734 +00:00] [WRN] [103] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6021.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.577563 with Status Code 200
[2020-12-07 02:36:33.874 +00:00] [WRN] [103] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6027.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.696053 with Status Code 200
[2020-12-07 02:37:27.847 +00:00] [WRN] [104] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://jellyfin-unstable.midnightsnow.tech/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6045.ts?UserId=e73e4fcc-a3fc-4665-81b6-c226d63b47ca&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NC4wfDE2MDY4NzI4ODU3MTg1&MaxStreamingBitrate=140000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=4ecf2eec33304895b88e1340f7556d80&PlaySessionId=1607307406880&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=ts&TranscodeReasons=ContainerNotSupported,AudioCodecNotSupported" to "192.168.2.27" in 0:00:00.6557462 with Status Code 200
[2020-12-07 02:37:33.222 +00:00] [ERR] [90] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Audio/8a83fab8-19ac-c9f6-1444-4e76f43ce950/hls1/main/6047.ts".
Error: SQLitePCL.pretty.SQLiteException: cannot rollback - no transaction is active
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.RollbackTransaction(IDatabaseConnection This)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Get(AuthenticationInfoQuery query)
   at Emby.Server.Implementations.HttpServer.Security.AuthorizationContext.GetAuthorizationInfoFromDictionary(Dictionary`2& auth, IHeaderDictionary& headers, IQueryCollection& queryString)
   at Emby.Server.Implementations.HttpServer.Security.AuthorizationContext.GetAuthorizationInfo(HttpRequest requestContext)
   at Jellyfin.Api.Helpers.StreamingHelpers.GetStreamingState(StreamingRequestDto streamingRequest, HttpRequest httpRequest, IAuthorizationContext authorizationContext, IMediaSourceManager mediaSourceManager, IUserManager userManager, ILibraryManager libraryManager, IServerConfigurationManager serverConfigurationManager, IMediaEncoder mediaEncoder, IFileSystem fileSystem, ISubtitleEncoder subtitleEncoder, IConfiguration configuration, IDlnaManager dlnaManager, IDeviceManager deviceManager, TranscodingJobHelper transcodingJobHelper, TranscodingJobType transcodingJobType, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsAudioSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 maxStreamingBitrate, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, SubtitleDeliveryMethod subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, EncodingContext context, Dictionary`2 streamOptions)
   at lambda_method853(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by MidnightSnowleopard** [comment]
Unable to reproduce after clean installed and updates
