### ISSUE TITLE
No plugin folder, can't install plugins from the Catalogue

### ISSUE THREAD

**Issue by stokkumrmv** [jellyfin/jellyfin#4727]
**Jellyfin Version**: 10.6.4, fresh install 

**OS**: Windows 7

**Install Method**: From the official setup.

**Configs** I used everthing out of the box, no custom configurations. 

**Describe the bug**
When I try to install a plugin, such as the Open Subtitle one from the Catalogue in the Dashboard,  the 'waiting' circle pops up. Nothing happens. No plugin is installed. Also no 'plugin' folder to be found. 

**Expected behaviour**
Install a plugin or have a 'plugin' folder in %AppData% or %ProgramData% folders 

**Logs**

```
        [2020-12-06 20:34:57.899 +01:00] [ERR] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/Packages/Installed/Open Subtitles?AssemblyGuid=4b9ed42f-5185-48b5-9803-6ff2989014c4&version=10.0.0.0"
        MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Open Subtitles
           at MediaBrowser.Api.PackageService.Post(InstallPackage request)
           at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
**Further context and attempts**
Going into %Appdata%/Local/jellyfin/, to find no plugin folder is to be found. Other folders are there, 'cache', 'config' etc. 
Same for %ProgramData%/Jellyfin/Server, no plugin folder.

I made a 'plugin' folder manually, and added the files (through dotnet --> publish) of the Open Subtitle plugin git repo manually, but no cigar. 
From [the man page on Plugins ](https://jellyfin.org/docs/general/server/plugins/index.html)it seems a configuration xml should be present, but since I lack the folder to begin with, I have no clue how to tell Jellyfin there is a plugin, or what files I need to add manually to get everything in order.

Tried uninstalling and reinstalling, tried several plugins, no luck. 

I also tried installing 10.5.5, upgrading to 10.6.0 and so on. This was [suggested to me on the reddit](https://www.reddit.com/r/jellyfin/comments/k80jtl/cant_install_plugins_cant_find_plugins_folder/gevfb5m?utm_source=share&utm_medium=web2x&context=3) but the repo on the jellyfin [site is empty](https://repo.jellyfin.org/archive/windows/stable/10.5.5/jellyfin_v10.5.5-x64.exe). 
Installing 10.6.0 is also filled with problems, for example the setup Wizard for setting up bricks at the first page. 

Any help would be appreciated!

**Comment by BaronGreenback** [comment]
Could you upload your entire log file, as something is going wrong somewhere else?

**Comment by lkerck** [comment]
I have the same Problem, both on Windows 2012r2 and on Debian in Docker.
Both are fresh installs of 10.6.4 with only one Library folder added. In both cases I tried to install the LDAP plugin via the GUI.
I was unable to find any folder named Plugins on both server.

At first I thought it was Windows being Windows but then I got the same error when trying to setup on Debian. So this seems to be Platform independent.

Below the full logs for both servers.

Docker Logs:
```
[2020-12-08 01:06:21.530 +01:00] [INF] [1] Main: Jellyfin version: "10.6.4"
[2020-12-08 01:06:21.670 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CACHE_DIR, /config/cache]"]
[2020-12-08 01:06:21.686 +01:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
[2020-12-08 01:06:21.689 +01:00] [INF] [1] Main: Operating system: "Linux"
[2020-12-08 01:06:21.695 +01:00] [INF] [1] Main: Architecture: X64
[2020-12-08 01:06:21.697 +01:00] [INF] [1] Main: 64-Bit Process: True
[2020-12-08 01:06:21.697 +01:00] [INF] [1] Main: User Interactive: True
[2020-12-08 01:06:21.698 +01:00] [INF] [1] Main: Processor count: 3
[2020-12-08 01:06:21.698 +01:00] [INF] [1] Main: Program data path: "/config/data"
[2020-12-08 01:06:21.699 +01:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2020-12-08 01:06:21.700 +01:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2020-12-08 01:06:22.358 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/config/cache"
[2020-12-08 01:06:22.381 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-12-08 01:06:32.677 +01:00] [INF] [1] Main: Kestrel listening on all interfaces
[2020-12-08 01:06:33.194 +01:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[2020-12-08 01:06:33.222 +01:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[2020-12-08 01:06:33.294 +01:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {xxxxx} may be persisted to storage in unencrypted form.
[2020-12-08 01:06:33.412 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2020-12-08 01:06:33.696 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 12/08/2020 02:00, which is 0:53:26.3044454 from now.
[2020-12-08 01:06:34.593 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.1"
[2020-12-08 01:06:34.690 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-12-08 01:06:34.747 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-12-08 01:06:34.790 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2020-12-08 01:06:34.793 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2020-12-08 01:06:34.835 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "XXXXX"
[2020-12-08 01:06:35.747 +01:00] [INF] [10] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "10.42.157.67"
[2020-12-08 01:06:35.853 +01:00] [INF] [10] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.9750037
[2020-12-08 01:06:35.866 +01:00] [INF] [10] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2020-12-08 01:06:36.684 +01:00] [INF] [10] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.8168046
[2020-12-08 01:06:36.687 +01:00] [INF] [10] Main: Startup complete 0:00:15.851081
[2020-12-08 01:06:36.940 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-12-08 01:06:36.950 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "PluginUpdateTask"
[2020-12-08 01:06:36.963 +01:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2020-12-08 01:06:37.109 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2020-12-08 01:06:38.438 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2020-12-08 01:06:39.039 +01:00] [INF] [5] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /data/media
[2020-12-08 01:07:19.146 +01:00] [INF] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.42.194.83" request
[2020-12-08 01:07:24.762 +01:00] [INF] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.42.194.83" closed
[2020-12-08 01:07:26.647 +01:00] [INF] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.42.194.83" request
[2020-12-08 01:07:28.128 +01:00] [ERR] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/Packages/Installed/LDAP Authentication?AssemblyGuid=958aad66-3784-4d2a-b89a-a7b6fab6e25c&version=10.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: LDAP Authentication
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)     at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Windows Logs:
```
[2020-12-08 01:10:21.106 +01:00] [INF] [1] Main: Jellyfin version: "10.6.4"
[2020-12-08 01:10:21.146 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\Jellyfin\log]"]
[2020-12-08 01:10:21.160 +01:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--service", "--datadir", "D:\Jellyfin"]
[2020-12-08 01:10:21.164 +01:00] [INF] [1] Main: Operating system: "Windows"
[2020-12-08 01:10:21.166 +01:00] [INF] [1] Main: Architecture: X64
[2020-12-08 01:10:21.169 +01:00] [INF] [1] Main: 64-Bit Process: True
[2020-12-08 01:10:21.170 +01:00] [INF] [1] Main: User Interactive: True
[2020-12-08 01:10:21.172 +01:00] [INF] [1] Main: Processor count: 4
[2020-12-08 01:10:21.173 +01:00] [INF] [1] Main: Program data path: "D:\Jellyfin"
[2020-12-08 01:10:21.174 +01:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-12-08 01:10:21.176 +01:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-12-08 01:10:21.521 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\Jellyfin\cache"
[2020-12-08 01:10:21.532 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-12-08 01:10:30.524 +01:00] [INF] [1] Main: Kestrel listening on all interfaces
[2020-12-08 01:10:30.879 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2020-12-08 01:10:31.020 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 12/08/2020 02:00, which is 0:49:28.9795701 from now.
[2020-12-08 01:10:31.172 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.1"
[2020-12-08 01:10:31.309 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-12-08 01:10:31.417 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-12-08 01:10:31.483 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2020-12-08 01:10:31.491 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: "C:\Program Files\Jellyfin\Server\ffmpeg.exe"
[2020-12-08 01:10:31.497 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "XXXX"
[2020-12-08 01:10:32.432 +01:00] [INF] [5] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "10.10.0.20"
[2020-12-08 01:10:32.510 +01:00] [INF] [5] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.9719995
[2020-12-08 01:10:32.514 +01:00] [INF] [5] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2020-12-08 01:10:33.121 +01:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory E:\Media\Videos\TV
[2020-12-08 01:10:33.152 +01:00] [INF] [5] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.6351071
[2020-12-08 01:10:33.157 +01:00] [INF] [5] Main: Startup complete 0:00:12.3452333
[2020-12-08 01:10:34.033 +01:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2020-12-08 01:10:34.040 +01:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "PluginUpdateTask"
[2020-12-08 01:10:34.052 +01:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2020-12-08 01:10:35.473 +01:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2020-12-08 01:10:36.952 +01:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2020-12-08 01:16:49.352 +01:00] [INF] [41] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.10.0.1" request
[2020-12-08 01:18:17.423 +01:00] [INF] [45] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.10.0.1" closed
[2020-12-08 01:18:20.017 +01:00] [INF] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:10.10.0.1" request
[2020-12-08 01:18:21.007 +01:00] [WRN] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "84.115.203.25". Time (slow): 0:00:00.633002. "http://10.10.0.20:8096/Packages/Slack Notifications?AssemblyGuid=94fb77c3-55ad-4c50-bf4e-4e5497467b79"
[2020-12-08 01:18:38.969 +01:00] [ERR] [39] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://10.10.0.20:8096/Packages/Installed/LDAP Authentication?AssemblyGuid=958aad66-3784-4d2a-b89a-a7b6fab6e25c&version=10.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: LDAP Authentication
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
@lkerck Try installing v9, v10 is for Jellyfin 10.7.

**Comment by lkerck** [comment]
I'll be damned, thats exactly what went wrong. 
Sadly the GUI gave no indication that v10 is only for Jellyfin 10.7. 
Now it worked. Thanks for your help.
