### ISSUE TITLE
10.7 cannot read HDHomeRun channel lineup (regression)

### ISSUE THREAD

**Issue by mooninite** [jellyfin/jellyfin#4759]
**Describe the bug**

Adding a HDHomeRun tuner results in no channels being displayed. The logs show that Jellyfin is unable to parse the channel lineup JSON.

**System (please complete the following information):**
 - OS: Fedora 33 x86_64
 - Virtualization: None
 - Clients: Firefox on Fedora, Chrome on Android
 - Browser: Firefox 83, Chrome 87
 - Jellyfin Version: 10.7.0-rc1
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: N/A

**To Reproduce**

1. Go to LiveTV in the admin Dashboard
2. Click on the "+" next to Tuner Devices
3. Either method of automatic discovery or manually entering IP address
4. Server logs an error, no channels are listed if I go to "Live TV" on the home page.

**Expected behavior**

Channels from the tuner should be listed in "Live TV"

**Logs**

<pre>
[09:51:10] [INF] [53] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Discovered tuner device HD Homerun at http://<redacted IP>
[09:51:10] [ERR] [40] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error getting channel list
System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $[0].Favorite | LineNumber: 0 | BytePositionInLine: 99.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a boolean.
   at System.Text.Json.Utf8JsonReader.GetBoolean()
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelsInternal(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(TunerHostInfo tuner, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(Boolean enableCache, CancellationToken cancellationToken)
[09:51:10] [INF] [40] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[09:51:10] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 3 seconds
[09:51:10] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[09:51:17] [ERR] [53] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error getting channel list
System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $[0].Favorite | LineNumber: 0 | BytePositionInLine: 99.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a boolean.
   at System.Text.Json.Utf8JsonReader.GetBoolean()
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelsInternal(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(TunerHostInfo tuner, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(Boolean enableCache, CancellationToken cancellationToken)
[09:51:17] [INF] [53] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: /media/michael/xmltv.xml
</pre>

**Screenshots**

**Additional context**

Live TV works in 10.6.x

**Comment by crobibero** [comment]
This has been fixed by https://github.com/jellyfin/jellyfin/pull/4715

**Comment by Bond-009** [comment]
It was fixed by #4741, but whatever :p

**Comment by mooninite** [comment]
Sorry for the duplicate. I searched for hdhomerun issues. Didn't see that one as it didn't have hdhomerun in the text.
