### ISSUE TITLE
Can't create new playlist when adding a song

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin#4760]
**Describe the bug**

Can't add songs/create a playlist when selecting 'New...' playlist.

**System (please complete the following information):**
 - OS:  Ubuntu 20.01
 - Virtualization: Docker
 - Clients: Browser
 - Browser:  Firefox Nightly 85.0a1 (2020-12-10) (64-bit)
 - Jellyfin Version:10.7 stable-rc
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: Traefik
 - Base URL:  none
 - Networking: Bridge
 - Storage: NFS

**To Reproduce**

1. Go to Music > Artist > go in an album
2. Choose a song
3. Select the 3 dots menu
4. Add to playlist
5. Select New...
6. Enter a name
7. Press 'Add'

**Expected behavior**
The playlist should be created and the song added to it

**Logs**

Server log:
```[11:04:47] [WRN] [105] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: UserData is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'UserData' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[11:04:47] [WRN] [98] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: AudioInfo is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'AudioInfo' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[11:04:47] [WRN] [98] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: AudioInfo is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'AudioInfo' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[11:04:48] [WRN] [94] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: UserData is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'UserData' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
```

**Client side:**

Request:
```
https://mydomain.com/Playlists?Name=My%20best%20of%20-%20eRa&Ids=ac072ce8-0d05-8781-2803-f8fa667dbf23&userId=cd3eef25704645a39f561e25407a57ae
```

Response:
```
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.13","title":"Unsupported Media Type","status":415,"traceId":"00-8208aa6c6aa2694fbb8ce05cf7a10f10-29bf768a118d6a4c-00"}
```

Console error:
```
Uncaught (in promise) 
    Response
    ​body: ReadableStream
    ​​locked: false
    ​​<prototype>: ReadableStream.prototype { … }
    ​bodyUsed: false
    ​headers: Headers {  }
    ​ok: false
    ​redirected: false
    ​status: 415
    ​statusText: "Unsupported Media Type"
    ​type: "basic"
    ​url: "https://mydomain.com/Playlists?Name=My%20best%20of%20-%2…81-2803-f8fa667dbf23&userId=cd3eef25704645a39f561e25407a57ae"
    ​<prototype>: ResponsePrototype { clone: clone(), arrayBuffer: arrayBuffer(), blob: blob(), … }
```

**Additional context**
I can `heart` the song, I can play it, I can also add it to an existing playlist, but I cannot add it to a playlist that doesn't exists yet.
The UI becomes non responsive and a refresh is required.

**Comment by Extarys** [comment]
Might be related to #4748 ?
