### ISSUE TITLE
Package Not Found, ResourceNotFoundException

### ISSUE THREAD

**Issue by snakyjake1** [jellyfin/jellyfin#4776]
**Describe the bug**

I am trying to install the plugin "Auto Organize".
The UI will just spin the multi-colored circle indefinitely without showing errors/info to user.
Looked at the logs and found "ResourceNotFoundException".

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.6.4 (Server)

**Logs**

[2020-12-12 09:13:04.668 -08:00] [ERR] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.5:8096/Packages/Installed/Auto Organize?AssemblyGuid=70b7b43b-471b-4159-b4be-56750c795499&version=9.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Auto Organize
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-12-12 09:13:05.565 -08:00] [WRN] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 404 to "192.168.1.17". Time (slow): 0:00:01.0851461. "http://192.168.1.5:8096/Packages/Installed/Auto Organize?AssemblyGuid=70b7b43b-471b-4159-b4be-56750c795499&version=9.0.0.0"

**Comment by crobibero** [comment]
Caused by this https://github.com/jellyfin/jellyfin/issues/4688
Just select an older version.
