### ISSUE TITLE
Live TV on Android TV (10.7)

### ISSUE THREAD

**Issue by morbificagent** [jellyfin/jellyfin#4813]
Hi together,

testing the actual version of 10.7 compiled from git and have the following problem:
Live-TV is working in the Browser (Chrome) and in the normal Android-App too. But the Android-TV App doesnt play the Live TV.

**Working log with playing it over browser:**
```
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8" with codec "h264"
[2020-12-17 08:18:43.679 +01:00] [INF] RemoteClientBitrateLimit: 8000000, RemoteIp: "168.119.170.33", IsInLocalNetwork: False
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "https://XXX.xxx..de/nginx-hls/live_hd1080.m3u8" with **codec "h264"**
[2020-12-17 08:18:44.080 +01:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
```
**Log when trying to play via Android TV (don't work)**
```
[2020-12-17 08:06:59.294 +01:00] [INF] Profile: "Android-Exo", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:06:59.294 +01:00] [INF] Profile: "Android-Exo", No video direct play profiles found for "https://XXX.xxx.de/nginx-hls/live_hd1080.m3u8" with codec "Unknown codec"
[2020-12-17 08:06:59.294 +01:00] [INF] RemoteClientBitrateLimit: 8000000, RemoteIp: "168.119.170.33", IsInLocalNetwork: False
[2020-12-17 08:06:59.294 +01:00] [INF] Profile: "Android-Exo", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:06:59.294 +01:00] [INF] Profile: "Android-Exo", No video direct play profiles found for "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8" with codec **"Unknown codec"**
**[2020-12-17 08:06:59.435 +01:00] [ERR] Error processing request. URL "POST" "/LiveStreams/Open".
System.ArgumentException: Key can't be empty. (Parameter 'key')**
   at Emby.Server.Implementations.Library.MediaSourceManager.GetProvider(String key)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.OpenMediaSource(HttpRequest httpRequest, LiveStreamRequest request)
   at Jellyfin.Api.Controllers.MediaInfoController.OpenLiveStream(String openToken, Nullable`1 userId, String playSessionId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, Nullable`1 itemId, OpenLiveStreamDto openLiveStreamDto, Boolean enableDirectPlay, Boolean enableDirectStream)
   at lambda_method1052(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2020-12-17 08:07:46.666 +01:00] [INF] Stopping ffmpeg process with q command for "/var/lib/jellyfin/transcodes/626b5fe6df8df5fbf080be4b09b7e3f4.m3u8"
[2020-12-17 08:07:46.743 +01:00] [WRN] Error converting value.
System.FormatException: SeriesInfo is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'SeriesInfo' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
**[2020-12-17 08:07:49.940 +01:00] [INF] FFmpeg exited with code 0**
```

**Comment by morbificagent** [comment]
Same Stream in the Browser produces:
So 

[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8" with codec "h264"
[2020-12-17 08:18:43.679 +01:00] [INF] RemoteClientBitrateLimit: 8000000, RemoteIp: "168.119.170.33", IsInLocalNetwork: False
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", Path: "https://xxx.xxx.de/nginx-hls/live_hd1080.m3u8", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-12-17 08:18:43.679 +01:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "https://meet.bit-link.de/nginx-hls/live_hd1080.m3u8" with **codec "h264"**
[2020-12-17 08:18:44.080 +01:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)

**Comment by morbificagent** [comment]
Hmmm am I the only one with this problem?
Or is everyone in Christmas already? ;)
