### ISSUE TITLE
Email Plugin Install

### ISSUE THREAD

**Issue by manjotsc** [jellyfin/jellyfin#4814]
I am not able to install Email Plugin 9.0.0.0 on jellyfin, when I click install it keeps loading infinitively. 

Jellyfin (10.6.4-1) Ubuntu command line

```
[2020-12-17 09:18:49.671 +00:00] [WRN] HTTP Response 200 to "192.168.40.11". Time (slow): 0:00:00.6669697. "https://jellyfin.manjot.net:8920/Packages?PackageType=UserInstalled"
[2020-12-17 09:18:54.558 +00:00] [ERR] Error processing request. URL: "https://jellyfin.manjot.net:8920/Packages/Installed/Email?AssemblyGuid=cfa0f7f4-4155-4d71-849b-d6598dc4c5bb&version=9.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Email
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-12-17 09:19:03.242 +00:00] [INF] WS "192.168.40.11" request

```
![Screenshot 2020-12-17 040828](https://user-images.githubusercontent.com/51430971/102466744-6f45b280-401d-11eb-987b-ac4491348371.png)

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/4688
Just select a lower plugin version.
