### ISSUE TITLE
Scraping errors

### ISSUE THREAD

**Issue by ajd4096** [jellyfin/jellyfin#4837]
**Describe the bug**
Scraping errors from The Open Movie Database

**System (please complete the following information):**
 - OS: Raspbian
 - Virtualization: Docker jellyfin/jellyfin/stable-rc
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.7.0-rc1
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking:  host
 - Storage: rclone mount on "/mnt/media"

**To Reproduce**
1. Fresh docker install
2. Added Movies library with default options
3. Started library scan

**Expected behavior**
Scan completes as per 10.6.4

**Logs**
(Many instances like this)
```
[2020-12-21 12:15:32.949 +11:00] [ERR] [76] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "The Open Movie Database"
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'RootObject', got string starting with: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
   at ServiceStack.Text.Common.DeserializeType`1.StringToTypeContext.DeserializeJson(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeType.cs:line 58
   at ServiceStack.Text.Json.JsonReader.<>c__DisplayClass3_0.<GetParseSpanFn>b__0(ReadOnlySpan`1 v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Json\JsonReader.Generic.cs:line 20
   at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
   at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 189
   at ServiceStack.Memory.NetCoreMemory.DeserializeAsync(Stream stream, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 169
   at ServiceStack.Text.JsonSerializer.DeserializeFromStreamAsync[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 207
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureItemInfo(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureItemInfo(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetRootObject(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.Fetch[T](MetadataResult`1 itemResult, String imdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetMovieResult[T](ItemLookupInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

```

**Comment by ajd4096** [comment]
I suspect this is cloudflare's captcha page which starts with:

> <!DOCTYPE html>
> 
>
