### ISSUE TITLE
Jellyfin doesn't detect any videos from https://jell.yfish.us/

### ISSUE THREAD

**Issue by lhorace** [jellyfin/jellyfin#4865]
**Describe the bug**

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 Ubuntu 20.04.1 LTS
 - Virtualization: [e.g. Docker, KVM, LXC]
 Unpreviledge LXC
 - Clients: [Browser, Android, Fire Stick, etc.]
 Firefox
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]
 CIFS

**To Reproduce**

1. Go to https://jell.yfish.us/
2. Click on 4k video
3. Click scan library
4. No video show up in library

**Expected behavior**
4K video show up

**Logs**
```
[2020-12-25 02:00:00.003 +00:00] [INF] "DailyTrigger" fired for task: "Extract Chapter Images"
[2020-12-25 02:00:00.004 +00:00] [INF] Queueing task "ChapterImagesTask"
[2020-12-25 02:00:00.005 +00:00] [INF] Executing "Extract Chapter Images"
[2020-12-25 02:00:00.045 +00:00] [INF] "Extract Chapter Images" Completed after 0 minute(s) and 0 seconds
[2020-12-25 02:00:00.067 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 02:00:01.004 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 12/26/2020 02:00, which is 23:59:58.9954782 from now.
[2020-12-25 02:58:56.609 +00:00] [INF] WS "::ffff:192.168.0.1" closed
[2020-12-25 09:58:58.968 +00:00] [INF] "IntervalTrigger" fired for task: "Update Plugins"
[2020-12-25 09:58:58.968 +00:00] [INF] Queueing task "PluginUpdateTask"
[2020-12-25 09:58:58.969 +00:00] [INF] Executing "Update Plugins"
[2020-12-25 09:58:59.921 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2020-12-25 09:58:59.950 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:19.446 +00:00] [INF] "IntervalTrigger" fired for task: "Download missing subtitles"
[2020-12-25 11:21:19.446 +00:00] [INF] Queueing task "SubtitleScheduledTask"
[2020-12-25 11:21:19.447 +00:00] [INF] Executing "Download missing subtitles"
[2020-12-25 11:21:19.448 +00:00] [INF] "Download missing subtitles" Completed after 0 minute(s) and 0 seconds
[2020-12-25 11:21:19.474 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:19.592 +00:00] [INF] "IntervalTrigger" fired for task: "Scan Media Library"
[2020-12-25 11:21:19.592 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2020-12-25 11:21:19.592 +00:00] [INF] Executing "Scan Media Library"
[2020-12-25 11:21:19.592 +00:00] [INF] Stopping directory watching for path "/mnt/media/TV Shows"
[2020-12-25 11:21:19.593 +00:00] [INF] Validating media library
[2020-12-25 11:21:19.606 +00:00] [INF] "IntervalTrigger" fired for task: "Clean Log Directory"
[2020-12-25 11:21:19.606 +00:00] [INF] Queueing task "DeleteLogFileTask"
[2020-12-25 11:21:19.606 +00:00] [INF] Executing "Clean Log Directory"
[2020-12-25 11:21:19.607 +00:00] [INF] "Clean Log Directory" Completed after 0 minute(s) and 0 seconds
[2020-12-25 11:21:19.611 +00:00] [INF] "IntervalTrigger" fired for task: "Clean Cache Directory"
[2020-12-25 11:21:19.611 +00:00] [INF] Queueing task "DeleteCacheFileTask"
[2020-12-25 11:21:19.612 +00:00] [INF] Executing "Clean Cache Directory"
[2020-12-25 11:21:19.617 +00:00] [INF] "Clean Cache Directory" Completed after 0 minute(s) and 0 seconds
[2020-12-25 11:21:19.626 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:19.689 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:19.779 +00:00] [INF] "IntervalTrigger" fired for task: "TasksRefreshChannels"
[2020-12-25 11:21:19.779 +00:00] [INF] Queueing task "RefreshChannelsScheduledTask"
[2020-12-25 11:21:19.780 +00:00] [INF] Executing "TasksRefreshChannels"
[2020-12-25 11:21:19.781 +00:00] [INF] "TasksRefreshChannels" Completed after 0 minute(s) and 0 seconds
[2020-12-25 11:21:19.782 +00:00] [INF] OnRefreshStart "f27caa37e5142225cceded48f6553502"
[2020-12-25 11:21:19.801 +00:00] [INF] OnRefreshStart "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 11:21:19.804 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:19.918 +00:00] [INF] OnRefreshStart "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 11:21:19.942 +00:00] [INF] OnRefreshStart "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 11:21:19.955 +00:00] [INF] OnRefreshComplete "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 11:21:19.956 +00:00] [INF] OnRefreshComplete "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 11:21:19.956 +00:00] [INF] OnRefreshStart "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 11:21:19.979 +00:00] [INF] OnRefreshStart "17287f8650c062c79445300269ff950c"
[2020-12-25 11:21:19.991 +00:00] [INF] OnRefreshComplete "17287f8650c062c79445300269ff950c"
[2020-12-25 11:21:19.991 +00:00] [INF] OnRefreshComplete "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 11:21:19.992 +00:00] [INF] OnRefreshComplete "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 11:21:20.025 +00:00] [INF] OnRefreshStart "1071671e7bffa0532e930debee501d2e"
[2020-12-25 11:21:20.042 +00:00] [INF] OnRefreshComplete "1071671e7bffa0532e930debee501d2e"
[2020-12-25 11:21:20.834 +00:00] [INF] OnRefreshComplete "f27caa37e5142225cceded48f6553502"
[2020-12-25 11:21:20.847 +00:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 1 seconds
[2020-12-25 11:21:20.869 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 11:21:20.927 +00:00] [INF] Watching directory /mnt/media/TV Shows
[2020-12-25 12:21:20.588 +00:00] [INF] "IntervalTrigger" fired for task: "Refresh Guide"
[2020-12-25 12:21:20.588 +00:00] [INF] Queueing task "RefreshChannelsScheduledTask"
[2020-12-25 12:21:20.589 +00:00] [INF] Executing "Refresh Guide"
[2020-12-25 12:21:23.593 +00:00] [INF] Refreshing guide with 7 days of guide data
[2020-12-25 12:21:23.595 +00:00] [INF] "Refresh Guide" Completed after 0 minute(s) and 3 seconds
[2020-12-25 12:21:23.617 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 18:34:11.153 +00:00] [INF] Authentication request for "lhorace" has succeeded.
[2020-12-25 18:34:11.155 +00:00] [INF] Creating new access token for user 87b7e1d7-3acb-4892-a2ee-1ab49d824b97
[2020-12-25 18:34:11.513 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.6037424. "http://jellyfinmedia-server.ct:8096/Users/authenticatebyname"
[2020-12-25 18:34:11.535 +00:00] [INF] WS "::ffff:192.168.0.1" request
[2020-12-25 18:34:12.493 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.6698153. "http://jellyfinmedia-server.ct:8096/Items/e4eb14faf50379c104f2ab444566fee2/Images/Backdrop/0?tag=a3b1d1a2db06fdc46a7eeb7dc38bd687&maxWidth=2560&quality=80"
[2020-12-25 18:35:21.436 +00:00] [INF] Stopping directory watching for path "/mnt/media/TV Shows"
[2020-12-25 18:35:22.189 +00:00] [WRN] HTTP Response 204 to "192.168.0.1". Time (slow): 0:00:00.776201. "http://jellyfinmedia-server.ct:8096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=true&name=TV%20Shows"
[2020-12-25 18:35:22.190 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2020-12-25 18:35:22.190 +00:00] [INF] Executing "Scan Media Library"
[2020-12-25 18:35:22.207 +00:00] [INF] Validating media library
[2020-12-25 18:35:22.409 +00:00] [INF] OnRefreshStart "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:35:22.448 +00:00] [INF] OnRefreshStart "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:35:22.526 +00:00] [INF] OnRefreshStart "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:35:22.549 +00:00] [INF] OnRefreshStart "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:35:22.567 +00:00] [INF] OnRefreshComplete "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:35:22.567 +00:00] [INF] OnRefreshComplete "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:35:22.567 +00:00] [INF] OnRefreshStart "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:35:22.591 +00:00] [INF] OnRefreshStart "17287f8650c062c79445300269ff950c"
[2020-12-25 18:35:22.606 +00:00] [INF] OnRefreshComplete "17287f8650c062c79445300269ff950c"
[2020-12-25 18:35:22.606 +00:00] [INF] OnRefreshComplete "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:35:22.606 +00:00] [INF] OnRefreshComplete "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:35:22.639 +00:00] [INF] OnRefreshStart "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:35:22.798 +00:00] [INF] OnRefreshComplete "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:35:22.869 +00:00] [INF] OnRefreshStart "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:35:22.893 +00:00] [INF] OnRefreshComplete "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:35:26.787 +00:00] [INF] OnRefreshComplete "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:35:26.805 +00:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 4 seconds
[2020-12-25 18:35:26.807 +00:00] [INF] Watching directory /mnt/media/Jellyfin Test
[2020-12-25 18:35:26.828 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 18:35:26.896 +00:00] [INF] Watching directory /mnt/media/TV Shows
[2020-12-25 18:38:11.102 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.5697147. "http://jellyfinmedia-server.ct:8096/LiveTv/Recordings?UserId=87b7e1d73acb4892a2ee1ab49d824b97&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop"
[2020-12-25 18:38:11.129 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.5964556. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A38%3A10.482Z&hasUserId=true"
[2020-12-25 18:38:11.242 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7091538. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A38%3A10.482Z&hasUserId=false"
[2020-12-25 18:38:11.330 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7976374. "http://jellyfinmedia-server.ct:8096/ScheduledTasks"
[2020-12-25 18:42:09.608 +00:00] [INF] Stopping directory watching for path "/mnt/media/Jellyfin Test"
[2020-12-25 18:42:09.609 +00:00] [INF] Stopping directory watching for path "/mnt/media/TV Shows"
[2020-12-25 18:42:09.816 +00:00] [INF] Removing item, Type: "Folder", Name: "Jellyfin Test", Path: "/mnt/media/Jellyfin Test", Id: 6fffe188-dadb-abc0-750c-78732cfe56f3
[2020-12-25 18:42:10.164 +00:00] [INF] Removing item, Type: "CollectionFolder", Name: "TV Shows1", Path: "/var/lib/jellyfin/root/default/TV Shows1", Id: 1febdb62-4c38-ca3a-53bc-37a0419d535e
[2020-12-25 18:42:10.320 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2020-12-25 18:42:10.320 +00:00] [WRN] HTTP Response 204 to "192.168.0.1". Time (slow): 0:00:01.0078786. "http://jellyfinmedia-server.ct:8096/Library/VirtualFolders?refreshLibrary=true&name=TV%20Shows1"
[2020-12-25 18:42:10.321 +00:00] [INF] Executing "Scan Media Library"
[2020-12-25 18:42:10.322 +00:00] [INF] Validating media library
[2020-12-25 18:42:10.481 +00:00] [INF] OnRefreshStart "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:42:10.500 +00:00] [INF] OnRefreshStart "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:42:10.567 +00:00] [INF] OnRefreshStart "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:42:10.588 +00:00] [INF] OnRefreshStart "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:42:10.602 +00:00] [INF] OnRefreshComplete "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:42:10.602 +00:00] [INF] OnRefreshComplete "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:42:10.602 +00:00] [INF] OnRefreshStart "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:42:10.625 +00:00] [INF] OnRefreshStart "17287f8650c062c79445300269ff950c"
[2020-12-25 18:42:10.637 +00:00] [INF] OnRefreshComplete "17287f8650c062c79445300269ff950c"
[2020-12-25 18:42:10.637 +00:00] [INF] OnRefreshComplete "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:42:10.637 +00:00] [INF] OnRefreshComplete "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:42:10.675 +00:00] [INF] OnRefreshStart "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:42:10.692 +00:00] [INF] OnRefreshComplete "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:42:10.782 +00:00] [INF] OnRefreshComplete "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:42:10.792 +00:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 0 seconds
[2020-12-25 18:42:10.810 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 18:42:10.885 +00:00] [INF] Watching directory /mnt/media/TV Shows
[2020-12-25 18:43:13.147 +00:00] [INF] Stopping directory watching for path "/mnt/media/TV Shows"
[2020-12-25 18:43:13.887 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2020-12-25 18:43:13.888 +00:00] [WRN] HTTP Response 204 to "192.168.0.1". Time (slow): 0:00:00.7630426. "http://jellyfinmedia-server.ct:8096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=true&name=Jellyfin%202"
[2020-12-25 18:43:13.888 +00:00] [INF] Executing "Scan Media Library"
[2020-12-25 18:43:13.889 +00:00] [INF] Validating media library
[2020-12-25 18:43:14.101 +00:00] [INF] OnRefreshStart "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:43:14.138 +00:00] [INF] OnRefreshStart "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:43:14.307 +00:00] [INF] OnRefreshComplete "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:43:14.344 +00:00] [INF] OnRefreshStart "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:43:14.416 +00:00] [INF] OnRefreshStart "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:43:14.438 +00:00] [INF] OnRefreshStart "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:43:14.454 +00:00] [INF] OnRefreshComplete "e959b8e7b5c9fa9efad9368c32102b5a"
[2020-12-25 18:43:14.454 +00:00] [INF] OnRefreshComplete "e4eb14faf50379c104f2ab444566fee2"
[2020-12-25 18:43:14.454 +00:00] [INF] OnRefreshStart "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:43:14.478 +00:00] [INF] OnRefreshStart "17287f8650c062c79445300269ff950c"
[2020-12-25 18:43:14.490 +00:00] [INF] OnRefreshComplete "17287f8650c062c79445300269ff950c"
[2020-12-25 18:43:14.490 +00:00] [INF] OnRefreshComplete "b27d8a452bf5a97ae389359c3fb47ebb"
[2020-12-25 18:43:14.490 +00:00] [INF] OnRefreshComplete "abc79223b00b5ab5f5ebed3574ce119f"
[2020-12-25 18:43:14.539 +00:00] [INF] OnRefreshStart "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:43:14.557 +00:00] [INF] OnRefreshComplete "1071671e7bffa0532e930debee501d2e"
[2020-12-25 18:43:17.917 +00:00] [INF] OnRefreshComplete "f27caa37e5142225cceded48f6553502"
[2020-12-25 18:43:17.927 +00:00] [INF] "Scan Media Library" Completed after 0 minute(s) and 4 seconds
[2020-12-25 18:43:17.937 +00:00] [INF] Watching directory /mnt/media/Jellyfin Test
[2020-12-25 18:43:17.945 +00:00] [INF] ExecuteQueuedTasks
[2020-12-25 18:43:18.037 +00:00] [INF] Watching directory /mnt/media/TV Shows
[2020-12-25 18:44:35.858 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.5613731. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A44%3A35.241Z&hasUserId=false"
[2020-12-25 18:51:19.679 +00:00] [INF] OnRefreshStart "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:51:20.429 +00:00] [INF] OnRefreshComplete "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:53:49.785 +00:00] [INF] OnRefreshStart "6fffe188dadbabc0750c78732cfe56f3"
[2020-12-25 18:54:01.318 +00:00] [INF] Killing ffmpeg process
[2020-12-25 18:54:01.429 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:07.1243943. "http://jellyfinmedia-server.ct:8096/ScheduledTasks"
[2020-12-25 18:54:02.061 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:07.7857001. "http://jellyfinmedia-server.ct:8096/Sessions?ActiveWithinSeconds=960"
[2020-12-25 18:54:02.833 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:08.5441. "http://jellyfinmedia-server.ct:8096/System/Info"
[2020-12-25 18:54:02.852 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:08.5617043. "http://jellyfinmedia-server.ct:8096/LiveTv/Recordings?UserId=87b7e1d73acb4892a2ee1ab49d824b97&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop"
[2020-12-25 18:54:03.834 +00:00] [ERR] ffmpeg image extraction failed for file:"/mnt/media/Jellyfin Test/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv"
[2020-12-25 18:54:04.974 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:03.4181591. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A53%3A58.905Z&hasUserId=false"
[2020-12-25 18:54:04.974 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:10.6845123. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A53%3A53.996Z&hasUserId=false"
[2020-12-25 18:54:04.974 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:02.1383773. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A53%3A59.394Z&hasUserId=false"
[2020-12-25 18:54:05.012 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:08.9839422. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=4&minDate=2020-12-18T18%3A53%3A56.001Z&hasUserId=false"
[2020-12-25 18:54:05.129 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:03.0665666. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A53%3A59.393Z&hasUserId=true"
[2020-12-25 18:54:05.129 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:02.25543. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A53%3A59.658Z&hasUserId=true"
[2020-12-25 18:54:05.138 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:10.8495781. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A53%3A53.995Z&hasUserId=true"
[2020-12-25 18:54:05.141 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:06.2072878. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A53%3A58.905Z&hasUserId=true"
[2020-12-25 18:54:05.171 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:09.1437839. "http://jellyfinmedia-server.ct:8096/System/ActivityLog/Entries?startIndex=0&limit=7&minDate=2020-12-24T18%3A53%3A56.001Z&hasUserId=true"
[2020-12-25 18:54:05.883 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7429102. "http://jellyfinmedia-server.ct:8096/System/Info"
[2020-12-25 18:54:05.900 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7286489. "http://jellyfinmedia-server.ct:8096/ScheduledTasks"
[2020-12-25 18:54:05.900 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7221628. "http://jellyfinmedia-server.ct:8096/System/Info"
[2020-12-25 18:54:05.903 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.726236. "http://jellyfinmedia-server.ct:8096/Sessions?ActiveWithinSeconds=960"
[2020-12-25 18:54:05.925 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.7576557. "http://jellyfinmedia-server.ct:8096/ScheduledTasks"
[2020-12-25 18:54:05.928 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.74968. "http://jellyfinmedia-server.ct:8096/Sessions?ActiveWithinSeconds=960"
[2020-12-25 18:54:06.171 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:01.019827. "http://jellyfinmedia-server.ct:8096/LiveTv/Recordings?UserId=87b7e1d73acb4892a2ee1ab49d824b97&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop"
[2020-12-25 18:54:06.527 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.6481838. "http://jellyfinmedia-server.ct:8096/web/controllers/dashboard/users/userprofilespage.js?v=25"
[2020-12-25 18:54:06.616 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:00.6914311. "http://jellyfinmedia-server.ct:8096/web/controllers/dashboard/general.js?v=25"
[2020-12-25 18:54:07.839 +00:00] [WRN] HTTP Response 200 to "192.168.0.1". Time (slow): 0:00:01.165217. "http://jellyfinmedia-server.ct:8096/users"
[2020-12-25 18:54:04.366 +00:00] [ERR] I-frame image extraction failed, will attempt standard way. Input: "file:\"/mnt/media/Jellyfin Test/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv\""
System.Exception: ffmpeg image extraction failed for file:"/mnt/media/Jellyfin Test/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
[2020-12-25 18:54:15.209 +00:00] [INF] Killing ffmpeg process
[2020-12-25 18:54:15.209 +00:00] [ERR] ffmpeg image extraction failed for file:"/mnt/media/Jellyfin Test/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv"
[2020-12-25 18:54:15.290 +00:00] [ERR] Error in "Screen Grabber"
System.Exception: ffmpeg image extraction failed for file:"/mnt/media/Jellyfin Test/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.VideoImageProvider.GetVideoImage(Video item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, LibraryOptions libraryOptions, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
[2020-12-25 18:54:16.505 +00:00] [INF] OnRefreshComplete "6fffe188dadbabc0750c78732cfe56f3"
```

**Screenshots**

**Additional context**
Wanted to test 4K video encoding

**Comment by nyanmisaka** [comment]
I am on Jellyfin 10.7
![image](https://user-images.githubusercontent.com/14953024/103140948-42358600-4728-11eb-9979-d193ad578115.png)

**Comment by Bond-009** [comment]
Can you give the full Jellyfin logs, more specifically the first 100 lines after startup?

**Comment by lhorace** [comment]
Sure.

**Comment by lhorace** [comment]
I'm  going to close this ticket, my interest in getting this solve has dissolve. Insofar. It works.
