### ISSUE TITLE
ResourceNotFoundException: Configuration with key cinemamode not found.

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#4867]
**Describe the bug**

Chromecast nightly crashes when trying to play a video.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Clients: Android
 - Browser: Chrome 87
 - Jellyfin Version: 10.6.4
 - Playback: n/a (video does not get to play)
 - Installed Plugins: none
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. Change Chromecast to Nightly
2. Connect to Chromecast (succeeds)
3. Play a video (fails; first Chromecast crashes and goes back to home screen, then the app crashes)

**Expected behavior**

Video should play on Chromecast.

**Logs**

```
[ERR] Error processing request. URL: "http://127.0.0.1/System/Configuration/cinemamode"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key cinemamode not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass42_0.<GetConfiguration>b__0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Api.ConfigurationService.Get(GetNamedConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by bille747** [comment]
I'm having the same issue but while trying to change my user's playback settings from "Auto" to "4K 120Mbps". Same setup as @mholt except I don't use a reverse proxy.

**Comment by BaronGreenback** [comment]
Cinemamode issue seems to be here. 

https://github.com/jellyfin/jellyfin-web/blob/a027ba71433807fbc16916e37d171ad9a200ca4d/src/components/playbackSettings/playbackSettings.js#L160

**Comment by bille747** [comment]
Any suggestions for a possible workaround? Is there a way to manually update the user configuration outside of the UI?

**Comment by BaronGreenback** [comment]
edit the system.xml and/or network.xml files.

**Comment by jacobmischka** [comment]
Sorry, how do I add cinemamode? I tried going through the code to figure out where to put it, but there are so many levels of indirection that I got lost.

I tried creating a cinemamode.xml in the configuration directory, because of the GetConfigurationFile call, but that didn't seem to help. It seems I need to also add it to the configuration stores, but I'm not sure where or how to do that. I don't actually want to use it, I just want to stop this error from breaking chromecast playback.

**Comment by BaronGreenback** [comment]
Just checked the code - there is no named config code for _Cinemamode_ in the JF server code, so there isn't a user workaround at the moment.

**Comment by pannal** [comment]
Isee this in my log:
```
[2021-12-04 04:06:27.103 +01:00] [ERR] [54] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/System/Configuration/cinemamode".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key cinemamode not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass43_0.<GetConfiguration>b__0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at lambda_method1000(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
