### ISSUE TITLE
Scanning of library folder fails if a file gets it's permission denied

### ISSUE THREAD

**Issue by nojusr** [jellyfin/jellyfin#4882]
This is similar to #2402, with the difference being that it also applies to individual files.

Info:
Version: 10.7.0
Operating System: Linux
Architecture: X64
Distro: Ubuntu 18.04.5 LTS

Logs/Backtrace:
```
[2020-12-29 16:17:35.163 +00:00] [INF] Queuing task "RefreshMediaLibraryTask"
[2020-12-29 16:17:35.163 +00:00] [INF] Executing "Scan Media Library"
[2020-12-29 16:17:35.165 +00:00] [INF] Validating media library
[2020-12-29 16:17:35.478 +00:00] [ERR] Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
[2020-12-29 16:17:35.701 +00:00] [ERR] Error refreshing owned items for "/home/bendras/torrentai"
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2020-12-29 16:17:35.703 +00:00] [ERR] Error validating images for "/home/bendras/torrentai"
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetFiles(BaseItem item, Boolean includeDirectories, IDirectoryService directoryService)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ItemImageProvider.<>c__DisplayClass5_0.<ValidateImages>b__0(ILocalImageProvider i)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2020-12-29 16:17:37.641 +00:00] [ERR] Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
[2020-12-29 16:17:37.652 +00:00] [ERR] Error retrieving children folder
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2020-12-29 16:17:40.212 +00:00] [INF] Authentication request for "nojus" has succeeded.
[2020-12-29 16:17:40.212 +00:00] [INF] Current/Max sessions for user "nojus": 0/0
[2020-12-29 16:17:40.217 +00:00] [INF] Creating new access token for user cb96c013-d822-4bef-8f19-c58c6b4362aa
[2020-12-29 16:17:40.616 +00:00] [WRN] Slow HTTP Response from "http://192.168.1.130:8096/Users/authenticatebyname" to "192.168.1.244" in 0:00:00.6907511 with Status Code 200
[2020-12-29 16:17:42.392 +00:00] [INF] WS "192.168.1.244" request
[2020-12-29 16:17:47.811 +00:00] [ERR] Error refreshing owned items for "/home/bendras/torrentai"
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2020-12-29 16:17:47.812 +00:00] [ERR] Error validating images for "/home/bendras/torrentai"
System.UnauthorizedAccessException: Access to the path '/home/bendras/torrentai/WALL-E.2008.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetFiles(BaseItem item, Boolean includeDirectories, IDirectoryService directoryService)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ItemImageProvider.<>c__DisplayClass5_0.<ValidateImages>b__0(ILocalImageProvider i)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

I don't recall if I installed the latest build so if this has already been fixed, feel free to close this issue.
Scanning other folders with files that have proper permissions doesn't cause any problems.

I can provide full configuration and log files upon request.

**Comment by MartenBE** [comment]
10.6.4 also errors while scanning if there is a soft linked file in the library folder (I soft linked a python script for cleanup maintenance e.g. delete nfo files and such). Perhaps this could also be solved with the PR?
