### ISSUE TITLE
Error in TheMovieDb

### ISSUE THREAD

**Issue by gfxlight55** [jellyfin/jellyfin#4885]
This error looks like it's related to: https://github.com/jellyfin/jellyfin/issues/3568 but the issue doesn't seem to have been fixed. I started out with one. Now I'm getting 2 of these errors in the log.

Version: 10.6.4
Operating System: Windows
Architecture: X64

```
[21:30:40] [ERR] [30] MediaBrowser.Providers.Movies.MovieMetadataService: Error in TheMovieDb
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Jellyfin\Server\cache\tmdb-movies2\690373\all-en.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Emby.Server.Implementations.Serialization.JsonSerializer.OpenFile(String path)
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

[21:30:43] [ERR] [30] MediaBrowser.Providers.Movies.MovieMetadataService: Error in TheMovieDb
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Jellyfin\Server\cache\tmdb-movies2\744157\all-en.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Emby.Server.Implementations.Serialization.JsonSerializer.OpenFile(String path)
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by davispuh** [comment]
I've this same issue. Log is full spammed with these

```
[2021-01-06 22:00:20.682 +02:00] [ERR] [37] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/cache/jellyfin/tmdb-movies2/683148/all-lv.json'.
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptionsoptions)
at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file) in jellyfin/src/jellyfin-10.6.4/Emby.Server.Implementations/Serialization/JsonSerializer.cs:line 145
at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken) in jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Tmdb/Movies/GenericTmdbMovieInfo.cs:line 116
at MediaBrowser.Providers.Plugins.Tmdb.Movies.GenericTmdbMovieInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken) in jellyfin/src/jellyfin-10.6.4/MediaBrowser.Providers/Plugins/Tmdb/Movies/GenericTmdbMovieInfo.cs:line 67
at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by cvium** [comment]
We're no longer using the old cache for tmdb.
