### ISSUE TITLE
M3U tuner not working in Live TV

### ISSUE THREAD

**Issue by arnab8820** [jellyfin/jellyfin#4886]
I am unable to play any live tv stream on my jellyfin server. I have attached the log below.

- Fresh install Version: 10.6.4
- Operating System: Ubuntu 20.04
- Architecture: X64
- Installed on Docker

Log entry:

```
[2020-12-30 06:04:27.706 +00:00] [INF] [24] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Opening SharedHttpStream Live stream from "https://botallen.live/t/96/master.m3u8?signature=e6b4321b770a2b723941ad03b085ccc70f933ed1&unique=9b1e5ef494b24a1e331a2219bbf6ea4f"
[2020-12-30 06:04:27.913 +00:00] [ERR] [11] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
MediaBrowser.Model.Net.HttpException: Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.Open(CancellationToken openCancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
[2020-12-30 06:04:27.939 +00:00] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.0.9:8096/Items/a8d1dab723f95a989b81b970b977652b/PlaybackInfo?UserId=2db556b2eab147bea8f68ef717c42d43&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
MediaBrowser.Controller.LiveTv.LiveTvConflictException: Exception of type 'MediaBrowser.Controller.LiveTv.LiveTvConflictException' was thrown.
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelStreamWithDirectStreamProvider(String channelId, String streamId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelStream(String id, String mediaSourceId, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.OpenMediaSource(String openToken, List`1 currentLiveStreams, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStream(LiveStreamRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Api.Playback.MediaInfoService.OpenMediaSource(OpenMediaSource request)
   at MediaBrowser.Api.Playback.MediaInfoService.GetPlaybackInfo(GetPostedPlaybackInfo request)
   at MediaBrowser.Api.Playback.MediaInfoService.Post(GetPostedPlaybackInfo request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-12-30 06:04:27.947 +00:00] [WRN] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "192.168.0.102". Time (slow): 0:00:01.8437973. "http://192.168.0.9:8096/Items/a8d1dab723f95a989b81b970b977652b/PlaybackInfo?UserId=2db556b2eab147bea8f68ef717c42d43&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
```

**Comment by arnab8820** [comment]
After some debugging I have found this line:
`[ERR] [11] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner MediaBrowser.Model.Net.HttpException: Found at`
here upon receving 302 response, this exception is thrown. I believe this is a bug.

**Comment by crobibero** [comment]
10.7 should properly follow redirects, if possible can you pleas give it a try?

**Comment by arnab8820** [comment]
Today I have installed 10.7. So far it is working. Hopefully it will be fixed in this version
