### ISSUE TITLE
Broken symlinks interrupt library scan

### ISSUE THREAD

**Issue by leonrjg** [jellyfin/jellyfin#4934]
**Describe the bug**
Hi, it seems that when Jellyfin scans a folder, finding a broken symlink causes an exception that ends the scan. I confirmed that after deleting the symlink that Jellyfin complained about in logs, the scan started working again.
If possible, I think it'd be better if it just ignored these.

**System (please complete the following information):**
 - OS: Debian (Proxmox 5)
 - Virtualization: KVM
 - Clients: Not relevant
 - Browser: Not relevant
 - Jellyfin Version: Jellyfin.Server 10.6.4.0
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: None
 - Base URL: /
 - Networking: N/A
 - Storage: local

**To Reproduce**
1. Create a symlink in the directory Jellyfin scans
2. Remove the file the symlink points to
3. Run a library scan

**Expected behavior**
I think the library scan should disregard this kind of files.

**Logs**
```
[2021-01-03 08:57:30.899 +09:00] [ERR] Error refreshing owned items for "/mnt/data"
System.IO.FileNotFoundException: Could not find file '/mnt/data/é­”æ³•ç§‘é«˜æ ¡ã®åŠ£ç­‰ç”Ÿ æ¥è¨ªè€…ç·¨_6_MBSæ¯Žæ—¥æ”¾é€.ts'.
File name: '/mnt/data/é­”æ³•ç§‘é«˜æ ¡ã®åŠ£ç­‰ç”Ÿ æ¥è¨ªè€…ç·¨_6_MBSæ¯Žæ—¥æ”¾é€.ts'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```
**Screenshots**
N/A

**Additional context**
N/A

**Comment by crobibero** [comment]
This might be fixed by https://github.com/jellyfin/jellyfin/pull/4906

**Comment by leonrjg** [comment]
FYI, still having the issue in Jellyfin 10.7.1:
[2021-04-03 13:36:27.365 +09:00] [INF] Jellyfin version: "10.7.1"
--
[2021-04-03 13:37:31.437 +09:00] [ERR] Error validating images for "/mnt/data"
System.IO.FileNotFoundException: Could not find file '/mnt/data/Re:ã‚¼ãƒ­ã‹ã‚‰å§‹ã‚ã‚‹ç•°ä¸–ç•Œç”Ÿæ´» æ°·çµã®çµ†_202101012300_KBSäº¬éƒ½.ts'.
File name: '/mnt/ts/mif/Re:ã‚¼ãƒ­ã‹ã‚‰å§‹ã‚ã‚‹ç•°ä¸–ç•Œç”Ÿæ´» æ°·çµã®çµ†_202101012300_KBSäº¬éƒ½.ts'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.OpenRead(String path)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetFiles(BaseItem item, Boolean includeDirectories, IDirectoryService directoryService)
   at MediaBrowser.LocalMetadata.Images.LocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ItemImageProvider.<>c__DisplayClass5_0.<ValidateImages>b__0(ILocalImageProvider i)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)

---

Removing the broken symlinks is easy enough and it's the user's fault that they're there in the first place so I'm not sure if you'd want to add code to ignore them, but I'm reporting just in case. Thanks

**Comment by Gronis** [comment]
This is still an issue to this day. My jellyfin library has been broken for over a year because of this bug.
