### ISSUE TITLE
Can't recreate an user with the same name

### ISSUE THREAD

**Issue by thisis-mental** [jellyfin/jellyfin#4939]
**Describe the bug**
I had to delete an user for several reasons and now I want to recreate it with the same credentials.

**System (please complete the following information):**
 - OS: Synology
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 
 - Jellyfin Version: 10.6 (latest - LSIO)
 
**To Reproduce**
1. Delete user abc
2. Create user abc

**Expected behavior**
User is created successfully from scratch

**Logs**
```
[10:16:56] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://10.1.1.10:8097/Users/New
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: Users.MaxActiveSessions'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---```

**Comment by crobibero** [comment]
`MaxActiveSessions` wasn't a part of 10.6. Did you update to unstable, then go back to 10.6?

**Comment by da-anda** [comment]
he most likely did. Had the same issue and could not easily "fix" the DB, so I moved back to 10.7 nightly

**Comment by thisis-mental** [comment]
Yes I did but I had too much issue with my plugins so I have reverted it.
How can I fix this?
Thanks a lot

**Comment by da-anda** [comment]
You would have to revert the according database migrations, but don't ask me how this is working (I'm new to jellyfin myself). I ended up by simply switching back to 10.7 and added my users there.

**Comment by crobibero** [comment]
We don't support downgrading.
Always make sure to back up your database before upgrading (especially to unstable / rc)
