### ISSUE TITLE
Unable to update docker container with the image stable-rc

### ISSUE THREAD

**Issue by nzlov** [jellyfin/jellyfin#4946]
**Describe the bug**

**System (please complete the following information):**
 - OS: [ArchLinux]
 - Virtualization: [Docker]
 - Clients: [Browser]
 - Browser: [Chrome 80]
 - Old Image Version: [jellyfin/jellyfin:unstable 2020-12-16 03:45:56]
 - New Image Version: [jellyfin/jellyfin:stable-rc]
 
**To Reproduce**

1. Pull `jellyfin/jellyfin:stable-rc`
2. Restart docker container.

**Expected behavior**

Start

**Logs**

```
[15:59:21] [INF] [1] Main: Jellyfin version: 10.7.0
[15:59:21] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_PublishedServerUrl, https://xxx.com:]"]
[15:59:21] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[15:59:21] [INF] [1] Main: Operating system: Linux
[15:59:21] [INF] [1] Main: Architecture: X64
[15:59:21] [INF] [1] Main: 64-Bit Process: True
[15:59:21] [INF] [1] Main: User Interactive: True
[15:59:21] [INF] [1] Main: Processor count: 4
[15:59:21] [INF] [1] Main: Program data path: /config
[15:59:21] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[15:59:21] [INF] [1] Main: Application directory: /jellyfin/
[15:59:21] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[15:59:21] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[15:59:21] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[15:59:21] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[15:59:21] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[15:59:21] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[15:59:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[15:59:21] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturnVoid' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.Init()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[15:59:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[15:59:21] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Comment by nzlov** [comment]
#4913
