### ISSUE TITLE
Jellyfin 10.7.0~rc2 not downloading images found from metadata sources

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin#4977]
**Describe the bug**
When adding a new show to Jellyfin (Seems to happen most with anime), Jellyfin will identify the show properly, but not download any images. You then have to manually "edit images" and search for them and download them. This was not happening with rc1.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: [No
 - Clients: Browser
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - Jellyfin Version: 10.7.0~rc2
 - Playback: N/A
 - Installed Plugins: TheTVDB v2 (With own API key), Trakt v11
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Cloud

**To Reproduce**
1) Add new folder to storage directory for new series
2) Scan media library in Jellyfin

**Expected behavior**
Jellyfin will identify and download all pertinent metadata

**Logs**
Logs show these:

```
[13:25:44] [INF] [56] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
[13:25:44] [INF] [56] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[13:25:47] [WRN] [67] Emby.Server.Implementations.Library.LibraryManager: Cannot get image index for https://www.thetvdb.com/banners/episodes/72553/7331259.jpg
[13:25:53] [INF] [46] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 2 in series Cells at Work!
[13:25:53] [INF] [46] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 2, Path: , Id: 498fa7ac-1352-41db-6c83-f34071b4641c
[13:25:57] [INF] [52] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 2 in series Laid-Back Camp
[13:25:57] [INF] [52] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 2, Path: , Id: d31cdc01-24c7-68dd-b053-799fcc806a2c
[13:25:58] [ERR] [55] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: Failed to retrieve actors for series 392212
TvDbSharper.TvDbServerException: The given series ID does not exist; not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetActorsAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[13:25:58] [ERR] [70] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: Failed to retrieve actors for series 389227
TvDbSharper.TvDbServerException: The given series ID does not exist; not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetActorsAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[13:26:08] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 23 seconds
```

**Screenshots**
![Jellyfin 1](https://user-images.githubusercontent.com/19889486/103937619-a1af7080-50ee-11eb-9418-13629bbd07e2.PNG)

![Jellyfin 2](https://user-images.githubusercontent.com/19889486/103937629-a411ca80-50ee-11eb-9ca1-73b481cf6300.PNG)

![Jellyfin 3](https://user-images.githubusercontent.com/19889486/103937633-a6742480-50ee-11eb-965b-4be01d82cd92.PNG)

**Comment by Darkwolf1515** [comment]
Check your plugins, make sure that you have provider plugins installed, im on rc2, and images download fine. (although, logos download but no longer show, even on my older shows.)

**Comment by Jinxyface** [comment]
I have the standard plugins installed, plus TVDB. When I search for images, they show up. So it's able to search metadata just fine. It's just that it won't do it after adding a show by itself. I have to manually download metadata. Even if I "refresh metadata" and "replace all images" nothing happens.

**Comment by eqpaisley** [comment]
Also have this same issue.  Show is identified correctly, metadata (text) is pulled correctly, but the poster and season art is not pulled.

**Comment by dennisstorm-lab** [comment]
I'm on 10.7 rc-2, and I'm running into the exact same issue. Movies and shows don't get a TVDB id, and can't get their artwork.

When I manually enter the TVDB id in the metadata editor it finds them fine. A full metadata refresh doesn't fix it, it requires a manual action from my part (searching the ID on TVDB, entering it in the metadata field, and searching for images then)

**Comment by ggogel** [comment]
Running 10.7-rc2 and I have this issue with actors. For instance when i open a movie view, it only shows the blue default picture for each actor. Only when after loaded the page for the actor once, it will display correctly in the future. All my other metadata comes from files and nfo, meaning they are already downloaded, so I can't reproduce it there.

I'm not sure if this is related though. Does this apply for actors for you too?

**Comment by dennisstorm-lab** [comment]
Actor images load fine on my setup, for Series and Movies alike. The IMDB id gets filled in properly during a scan of new content. The Fanart id doesn't (yes, I have an API key entered in the plugin). When it's filled everything works nicely, it's just not automatic anymore.

**Comment by hot22shot** [comment]
I've got the same issue, tested with 10.6.4 and 10.70.0~RC2 on a Docker installation hosted on a NAS.

**Comment by dennisstorm-lab** [comment]
I managed to resolve the issue. I've disabled the OpenSubtitles plugin, and then the detection started working again. Looks like somethings breaking during a scan with OpenSubtitles enabled.

**Comment by Jinxyface** [comment]
I don't have the OpenSubtitles plugin installed so that's not the issue for me.

**Comment by Jinxyface** [comment]
Issue still seems present in 10.7.0 rc3. This only seems to happen with my Anime library. New TV shows and movies are identified and have stuff downloaded immediately. But with Anime, I always have to "edit images" and then manually search, and add things that way.

The most recent is Yatogame-chan Kansatsu Nikki. If I "edit metadata" of the series, everything is added, even the proper series IDs on multiple sites

![image](https://user-images.githubusercontent.com/19889486/105892480-88a42c00-5fd7-11eb-94cf-b4325bcc9c9a.png)

Clicking the TVDB link opens up the page to TVDB, which has banner/background/series poster art

![image](https://user-images.githubusercontent.com/19889486/105892559-a5406400-5fd7-11eb-815e-59901e53f26b.png)


However in Jellyfin, these aren't downloaded, even if I refresh metadata and check "replace existing images" nothing happens. I do see this in the log when I hit "refresh metadata" though

```
[2021-01-26 13:18:24.347 -06:00] [ERR] [102] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: Failed to retrieve series with id null
TvDbSharper.TvDbServerException: The given series ID does not exist; {"Error":"ID: 0 not found"}
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
```

**Comment by cvium** [comment]
I can't reproduce the crash.

Blame the lack of posters on tvdb's terrible API. Their images endpoint doesn't return the poster, only the default series endpoint does, but we don't use the images from that endpoint when refreshing metadata.

We _could_ fallback to checking the series endpoint if the images endpoint doesn't have a poster. But that's a feature request that belongs in https://github.com/jellyfin/jellyfin-plugin-tvdb/

**Comment by ocervell** [comment]
I have the same issue and it persists on `10.8.0-beta1`

**Comment by fitsou** [comment]
Same issue, only with Anime in 10.8.1 stable.

**Comment by ArtisanByteCrafter** [comment]
Also same issue, 10.8.1 with all newly added tv shows.

**Comment by bvoo** [comment]
Running into this on all new shows as of 10.8.1. Updated from 10.7.7 which didn't have this issue.

**Comment by YourSandwich** [comment]
Sama issue on 10.8.4-1

**Comment by Aetherinox** [comment]
This is a long term issue. I am also getting this.
