### ISSUE TITLE
Metadata will not refresh

### ISSUE THREAD

**Issue by Qiangong2** [jellyfin/jellyfin#4987]
**Describe the bug**

Unable to refresh metadata

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Portable
 - Clients: browser
 - Browser: edge
 - Jellyfin Version: Jellyfin 10.6.4
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. Go to show.
2. Click "refresh metadata"
3. Error occurs

**Expected behavior**
Metadata gets refreshed

**Logs**
```
[16:35:40] [ERR] [16] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in The Open Movie Database
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
This is likely already fixed on the unstable branch

**Comment by Qiangong2** [comment]
Any ETA on the stable branch then? Or will that be a few months?

It isn't a big issue, just annoying

**Comment by crobibero** [comment]
We recently release 10.7.0~rc2, so in the coming weeks barring any major roadblocks

**Comment by rayures** [comment]
i also have this error in docker jellyfin:unstable d936f1816cb3 (2021-01-10)

**Comment by cvium** [comment]
Reading through the code I don't see how this can happen anymore. If you have a similar error, then please open a new issue and include the logs.
