### ISSUE TITLE
crash in start up while validating ffmpeg

### ISSUE THREAD

**Issue by bodonkerhoderos** [jellyfin/jellyfin#4993]
**Describe the bug**
the program is crashing in start up while (so far as i can tell) trying to parse the versions of ffmpeg components

**System:**
 - OS: ubuntu
 - i should note this is on a rockpro64 and i had to grab the raspberry pi files to run this
 - Jellyfin Version: 10.6.4
 - Storage: local

**Expected behavior**
normal start up.

**Logs**
the first crash that started the loop was
```
Jan 09 12:32:42 rockpro64 systemd[1]: jellyfin.service: Main process exited, code=killed, status=11/SEGV
Jan 09 12:32:42 rockpro64 systemd[1]: jellyfin.service: Failed with result 'signal'.
Jan 09 12:32:42 rockpro64 systemd[1]: jellyfin.service: Service hold-off time over, scheduling restart.
Jan 09 12:32:42 rockpro64 systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1.
Jan 09 12:32:42 rockpro64 systemd[1]: Stopped Jellyfin Media Server.
```
snippet of logs this repeats indefinitely
```
Jan 09 12:32:42 rockpro64 systemd[1]: Started Jellyfin Media Server.
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Jellyfin version: 10.6.4
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Environment Variables: ["[JELLYFIN_USER, jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYF
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restar
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Operating system: Linux
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Architecture: Arm
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] 64-Bit Process: False
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] User Interactive: True
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Processor count: 6
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Program data path: /var/lib/jellyfin
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Web resources path: /usr/share/jellyfin/web
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Application directory: /usr/lib/jellyfin/bin/
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Setting cache path: /var/cache/jellyfin
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Loading assemblies
Jan 09 12:32:44 rockpro64 jellyfin[29847]: [12:32:44] [INF] Loaded assembly Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null f
Jan 09 12:32:53 rockpro64 jellyfin[29847]: [12:32:53] [INF] Kestrel listening on all interfaces
Jan 09 12:32:53 rockpro64 jellyfin[29847]: [12:32:53] [INF] Running startup tasks
Jan 09 12:32:53 rockpro64 jellyfin[29847]: [12:32:53] [INF] Daily trigger for Extract Chapter Images set to fire at 01/10/2021 02:00, which is 13:27:06.374
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [FTL] Error while starting server.
Jan 09 12:32:54 rockpro64 jellyfin[29847]: System.FormatException: Input string was not in a correct format.
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, I
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Version.Parse(String input)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at System.Version..ctor(String version)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetFFmpegVersion(String output)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersionInternal(String versionOutput)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ValidatePath(String path, FFmpegLocation location)
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.SetFFmpegPath()
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
Jan 09 12:32:54 rockpro64 jellyfin[29847]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing CoreAppHost
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing ActivityLogWebSocketListener
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing SessionInfoWebSocketListener
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing ScheduledTasksWebSocketListener
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing SessionWebSocketListener
Jan 09 12:32:54 rockpro64 jellyfin[29847]: [12:32:54] [INF] Disposing EmbyTV
Jan 09 12:32:55 rockpro64 jellyfin[29847]: [12:32:55] [INF] Received a SIGTERM signal, shutting down
Jan 09 12:32:55 rockpro64 systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
Jan 09 12:32:55 rockpro64 systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jan 09 12:32:55 rockpro64 systemd[1]: jellyfin.service: Service hold-off time over, scheduling restart.
Jan 09 12:32:55 rockpro64 systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 2.
Jan 09 12:32:55 rockpro64 systemd[1]: Stopped Jellyfin Media Server.
```

the output of `/usr/lib/jellyfin-ffmpeg/ffmpeg -version`
```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --toolchain=hardened --enable-cross-compile --enable-omx --enable-omx-rpi --enable-mmal --arch=armhf --cross-prefix=/usr/bin/arm-linux-gnueabihf-
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Additional context**
it's probably unrelated but the last error before this crashloop happened was failing to compute a blurhash for a file that didn't exist (likely an artifact of this library previously being used with emby) but that was 2 hours before the crashloop happened.

**Comment by BaronGreenback** [comment]
The ffmpeg detection routine has been totally re-written for 10.7, and we use TryParse throughout.

If you wish to stay on 10.6.4, you could try manually editing the encoding.xml setting file and updating the <EncoderAppPath> property to see if that will get you past this issue.

**Comment by cvium** [comment]
Re-open if it's still a problem in 10.7
