### ISSUE TITLE
unstable/master: log error: Error deserializing /config/data/ScheduledTasks/

### ISSUE THREAD

**Issue by rayures** [jellyfin/jellyfin#5000]
**Describe the bug**

error in log. (see log section)

i think it is related to scheduled task 'scan media library' never runs. but not sure. 

**System (please complete the following information):**
 - OS: debian 10
 - Virtualization: docker
 - Clients: 
 - Browser: 
 - Jellyfin Version: unstable 2021-01-10
 - Installed Plugins: 
 - Reverse Proxy: 
 - Base URL: 
 - Networking: 
 - Storage: local

**To Reproduce**

1. Go to 'open log'

**Expected behavior**

**Logs**

log states:

```
[11:50:18] [ERR] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error deserializing /config/data/ScheduledTasks/a27c5425-9520-b2e5-c509-def68c8f4c45.js
System.Text.Json.JsonException: '}' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 213.
 ---> System.Text.Json.JsonReaderException: '}' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 213.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.get_LastExecutionResult()
```

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
Can you please paste the contents of 
`/config/data/ScheduledTasks/a27c5425-9520-b2e5-c509-def68c8f4c45.js`

**Comment by rayures** [comment]
`I have no name!@8a52e97e152e:/config/data/ScheduledTasks$ cat a27c5425-9520-b2e5-c509-def68c8f4c45.js`

`{"StartTimeUtc":"2021-01-07T14:59:04.173563Z","EndTimeUtc":"2021-01-07T14:59:04.2263936Z","Status":"Completed","Name":"TasksRefreshChannels","Key":"RefreshInternetChannels","Id":"a27c54259520b2e5c509def68c8f4c45"}}`

one to many } ?
