### ISSUE TITLE
Jellyfin 10.7 on Ubuntu - service won't start after install

### ISSUE THREAD

**Issue by eqpaisley** [jellyfin/jellyfin#5032]
**Describe the bug**

**System (please complete the following information):**
 - OS: Ubuntu 18.4.5
 - Virtualization: KVM VPS
 - Clients: n/a
 - Browser: n/a
 - Jellyfin Version: 10.7
 - Playback: n/a
 - Installed Plugins: n/a
 - Reverse Proxy:caddy
 - Base URL: n/a
 - Networking: n/a
 - Storage: n/a

**To Reproduce**

sudo service jellyfin status

**Expected behavior**
running

**Logs**
```
Active: failed (Result: exit-code) since Sat 2021-01-16 22:58:56 UTC; 5min ago
  Process: 1733 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} (code=exited, status=143)
 Main PID: 1733 (code=exited, status=143)

Jan 16 22:58:56 Fermi-Plex systemd[1]: jellyfin.service: Service hold-off time over, scheduling restart.
Jan 16 22:58:56 Fermi-Plex systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Jan 16 22:58:56 Fermi-Plex systemd[1]: Stopped Jellyfin Media Server.
Jan 16 22:58:56 Fermi-Plex systemd[1]: jellyfin.service: Start request repeated too quickly.
Jan 16 22:58:56 Fermi-Plex systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jan 16 22:58:56 Fermi-Plex systemd[1]: Failed to start Jellyfin Media Server.
```
`

Installed over 10.6

**Comment by crobibero** [comment]
You're likely hitting this issue- https://github.com/jellyfin/jellyfin/issues/4690
The logs you posted aren't from Jellyfin, so please post the correct ones to confirm.

**Comment by eqpaisley** [comment]
Sorry to ask because I'm sure this info is out there somewhere but I can't find it.  Where are my logs located? (Ubuntu 18.04.05 LTS) by default?

**Comment by crobibero** [comment]
If you haven't configured it, it's likely under `/var/log/jellyfin`

**Comment by eqpaisley** [comment]
Hmmm. So I did find logs there and the log named for today doesn't seem to have ANY entries since the attempted install.  
```

[2021-01-16 02:00:00.001 +00:00] [INF] "DailyTrigger" fired for task: "Extract Chapter Images"
[2021-01-16 02:00:00.003 +00:00] [INF] Queueing task "ChapterImagesTask"
[2021-01-16 02:00:00.004 +00:00] [INF] Executing "Extract Chapter Images"
[2021-01-16 02:00:00.259 +00:00] [INF] "Extract Chapter Images" Completed after 0 minute(s) and 0 seconds
[2021-01-16 02:00:00.288 +00:00] [INF] ExecuteQueuedTasks
[2021-01-16 02:00:01.000 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 01/17/2021 02:00, which is 23:59:58.9992347 from now.
[2021-01-16 03:23:39.868 +00:00] [INF] "IntervalTrigger" fired for task: "Scan Media Library"
[2021-01-16 03:23:39.868 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2021-01-16 03:23:39.869 +00:00] [INF] Executing "Scan Media Library"
[2021-01-16 03:23:39.870 +00:00] [INF] Stopping directory watching for path "/media/Plex/PMS/TV"
[2021-01-16 03:23:39.871 +00:00] [INF] Stopping directory watching for path "/media/Plex/PMS/Movies"
[2021-01-16 03:23:39.871 +00:00] [INF] Validating media library
[2021-01-16 03:23:39.886 +00:00] [ERR] Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/dropbox/dbmount/EBooks Converted'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemRes$
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, $
[2021-01-16 03:23:39.888 +00:00] [ERR] Error in "PlaylistResolver" resolving "/media/dropbox/dbmount/EBooks Converted"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/dropbox/dbmount/EBooks Converted'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.Library.Resolvers.PlaylistResolver.Resolve(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.Resolvers.ItemResolver`1.MediaBrowser.Controller.Resolvers.IItemResolver.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
```

**Comment by eqpaisley** [comment]
To follow up, I rolled back my Ubuntu server, sudo apt purge-d jellyfin, rebooted and tried to install 10.7 again.  Same fail pt.   But at least this time there's a proper log:
```

[2021-01-17 00:04:27.281 +00:00] [INF] Jellyfin version: "10.7.0"
[2021-01-17 00:04:27.332 +00:00] [INF] Environment Variables: ["[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/l$
[2021-01-17 00:04:27.336 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin$
[2021-01-17 00:04:27.337 +00:00] [INF] Operating system: "Linux"
[2021-01-17 00:04:27.337 +00:00] [INF] Architecture: X64
[2021-01-17 00:04:27.338 +00:00] [INF] 64-Bit Process: True
[2021-01-17 00:04:27.339 +00:00] [INF] User Interactive: True
[2021-01-17 00:04:27.339 +00:00] [INF] Processor count: 8
[2021-01-17 00:04:27.339 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-01-17 00:04:27.339 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-01-17 00:04:27.339 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-01-17 00:04:27.672 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-01-17 00:04:27.767 +00:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-01-17 00:04:27.767 +00:00] [INF] Defined LAN exclusions : "[]"
[2021-01-17 00:04:27.768 +00:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-01-17 00:04:27.770 +00:00] [INF] Using bind addresses: "[]"
[2021-01-17 00:04:27.770 +00:00] [INF] Using bind exclusions: "[]"
[2021-01-17 00:04:27.845 +00:00] [FTL] Error while starting server.
System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/share/je$
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-01-17 00:04:27.854 +00:00] [INF] Disposing "CoreAppHost"
[2021-01-17 00:04:27.855 +00:00] [INF] Received a SIGTERM signal, shutting down
[2021-01-17 00:04:28.524 +00:00] [INF] Jellyfin version: "10.7.0"
[2021-01-17 00:04:28.558 +00:00] [INF] Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_WEB_OPT, --we$
[2021-01-17 00:04:28.563 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin$
[2021-01-17 00:04:28.564 +00:00] [INF] Operating system: "Linux"
[2021-01-17 00:04:28.564 +00:00] [INF] Architecture: X64
[2021-01-17 00:04:28.566 +00:00] [INF] 64-Bit Process: True
[2021-01-17 00:04:28.566 +00:00] [INF] User Interactive: True
[2021-01-17 00:04:28.566 +00:00] [INF] Processor count: 8
[2021-01-17 00:04:28.566 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-01-17 00:04:28.566 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-01-17 00:04:28.566 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-01-17 00:04:28.883 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-01-17 00:04:28.954 +00:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-01-17 00:04:28.954 +00:00] [INF] Defined LAN exclusions : "[]"
[2021-01-17 00:04:28.955 +00:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-01-17 00:04:28.956 +00:00] [INF] Using bind addresses: "[]"
[2021-01-17 00:04:28.956 +00:00] [INF] Using bind exclusions: "[]"
[2021-01-17 00:04:29.014 +00:00] [FTL] Error while starting server.
System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/share/je$
```

**Comment by crobibero** [comment]
That error is because it's missing `jellyfin-web`

**Comment by eqpaisley** [comment]
I assume that's not installed with the RC but it is with the release? Because I've never installed it separately before.   Maybe I'm not your target beta tester, my skill set isn't robust  LOL

**Comment by crobibero** [comment]
It was changed with 10.6 (https://jellyfin.org/posts/packaging-updates/)
I'm not sure why `jellyfin-web` wasn't installed automatically, but it should have been.

**Comment by eqpaisley** [comment]
installed web, still can get the service running. Rebooted the server, tried to restart the service.

Logs don't show anything new but the service won't start.

**Comment by eqpaisley** [comment]
There were some serious problems with my python environment. Thanks to some help from a friendly JF user, I was able to get this sorted.

**Comment by MasterCATZ** [comment]
how did you fix the python issues ?
