### ISSUE TITLE
Scanning throws errors if special characters are in the root path of a library - no real time monitoring seems possible

### ISSUE THREAD

**Issue by bigcookie** [jellyfin/jellyfin#5038]
Situation:
Jellyfin in docker on QNAP NAS. Updated to 10.6.4.
Initiated scan manually.

EDIT:
Removed statement that scan fails. The scan failing seems to be another reason, nevertheless realtime monitoring fails:
Scan log throws errors when scanning Audio files in subfolders of a root path added to the library which contains special characters. The issue doesnt appear if the special characters are in subfolders or subsubfolders. The weird printout below is a browser issue. Checking the log files directly showed on locale issue - at least none I could see...

Here is the trace from the log:

System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/HÃ¶rbÃ¼cher Kinder'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2021-01-17 11:43:43.135 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "c80471561a0490520d20004656b4de8d"
[2021-01-17 11:43:43.187 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "5d3b999e3627d3188a58ca4a0f8e7f07"
[2021-01-17 11:43:43.242 +00:00] [ERR] [27] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/HÃ¶rbÃ¼cher'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2021-01-17 11:43:43.243 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "5d3b999e3627d3188a58ca4a0f8e7f07"
[2021-01-17 11:43:43.299 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "17b4a55f90c74f4ed3ce16a59e53ab6c"
[2021-01-17 11:43:43.354 +00:00] [ERR] [27] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/HÃ¶rspiele'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2021-01-17 11:43:43.355 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "17b4a55f90c74f4ed3ce16a59e53ab6c"
[2021-01-17 11:43:43.410 +00:00] [INF] [27] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "0794da35eeff186d69efc95c80c3936b"
[2021-01-17 11:43:43.465 +00:00] [ERR] [27] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/HÃ¶rspiele Kinder'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)

**Comment by bigcookie** [comment]
Also found this:
[2021-01-17 11:35:17.689 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Skipping realtime monitor for "/media/Audio/HÃ¶rbÃ¼cher" because the path does not exist
[2021-01-17 11:35:17.690 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Skipping realtime monitor for "/media/Audio/HÃ¶rbÃ¼cher Kinder" because the path does not exist
[2021-01-17 11:35:17.691 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Skipping realtime monitor for "/media/Audio/HÃ¶rspiele" because the path does not exist
[2021-01-17 11:35:17.691 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Skipping realtime monitor for "/media/Audio/HÃ¶rspiele Kinder" because the path does not exist

**Comment by bigcookie** [comment]
Another node - it works for movies. If there are special characters in the file path.

**Comment by BaronGreenback** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.text.normalizationform?view=net-5.0 ??

**Comment by bigcookie** [comment]
As stated below, it works for other paths with special characters. deleting the library and rescanning, the same error shows, but the special characters are printed out correctly. Characterset of the storage is correct. 

I noticed that the according audio files appear in the library, though the error is present in the logs. 

E.g. this still appears in the logs:
[2021-01-17 12:30:18.779 +00:00] [ERR] [73] Emby.Server.Implementations.Library.LibraryManager: Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/Hörbücher Kinder'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
[2021-01-17 12:30:18.780 +00:00] [ERR] [73] Emby.Server.Implementations.Library.LibraryManager: Error in "PlaylistResolver" resolving "/media/Audio/Hörbücher Kinder"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Audio/Hörbücher Kinder'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.Library.Resolvers.PlaylistResolver.Resolve(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.Resolvers.ItemResolver`1.MediaBrowser.Controller.Resolvers.IItemResolver.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
[2021-01-17 12:30:18.781 +00:00] [ERR] [73] Emby.Server.Implementations.Library.LibraryManager: Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)

**Comment by bigcookie** [comment]
As all appears in the library, I dont think it is the locale. But @BaronGreenback - now can I set the locale in Jellyfin in Docker? In the UI, "Metadata" language is set to German.

**Comment by BaronGreenback** [comment]
That would seem to point to an api function. Thanks for the extra info - will take a look.

**Comment by BaronGreenback** [comment]
Could you enable debug logging - and post anything else that appears in the logs please?

Have checked the api and it all looks ok.

**Comment by bigcookie** [comment]
Ok, I checked. There is no issue with the special characters as it seems. I am sorry for the additional work created by me.
BUT I found that the error is connected to the photos library. When I remove it, the scan runs properly and finishes.
I am testing more. I assume closing this issue makes sense - I will open another one in case I could dig more deep into the issue and have more leads. The error message is still the same.

**Comment by bigcookie** [comment]
@BaronGreenback , I didnt find a clue for the issue, here is the debug log. Can you point me in a further direction for debugging?

```
[2021-01-21 16:29:17.110 +00:00] [DBG] [45] MediaBrowser.Providers.Photos.PhotoMetadataService: Running "PhotoProvider" for "/media/Bilder/0001 - Kita Elia/Fotos/20180606_093801 IMG_0988.JPG"
[2021-01-21 16:29:17.118 +00:00] [DBG] [45] Emby.Drawing.ImageProcessor: Getting image size for item "Photo" "/media/Bilder/0001 - Kita Elia/Fotos/20180606_093801 IMG_0988.JPG"
[2021-01-21 16:29:17.231 +00:00] [DBG] [45] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "f27caa37e5142225cceded48f6553502" 98.66188927545001
[2021-01-21 16:29:17.232 +00:00] [DBG] [45] MediaBrowser.Providers.Photos.PhotoMetadataService: Running "PhotoProvider" for "/media/Bilder/0001 - Kita Elia/Fotos/20181029_095738.jpg"
[2021-01-21 16:29:17.234 +00:00] [DBG] [45] Emby.Drawing.ImageProcessor: Getting image size for item "Photo" "/media/Bilder/0001 - Kita Elia/Fotos/20181029_095738.jpg"
[2021-01-21 16:29:17.425 +00:00] [DBG] [45] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "f27caa37e5142225cceded48f6553502" 98.66207835425806
[2021-01-21 16:29:17.426 +00:00] [DBG] [45] MediaBrowser.Providers.Photos.PhotoMetadataService: Running "PhotoProvider" for "/media/Bilder/0001 - Kita Elia/Fotos/20180215_095824 IMG_6431.jpg"
[2021-01-21 16:29:17.434 +00:00] [DBG] [45] Emby.Drawing.ImageProcessor: Getting image size for item "Photo" "/media/Bilder/0001 - Kita Elia/Fotos/20180215_095824 IMG_6431.jpg"
[2021-01-21 16:29:17.504 +00:00] [INF] [45] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "f27caa37e5142225cceded48f6553502"
[2021-01-21 16:29:17.513 +00:00] [INF] [43] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Hoerspiele
[2021-01-21 16:29:17.516 +00:00] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Hoerbuecher Kinder
[2021-01-21 16:29:17.517 +00:00] [INF] [48] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Podcasts
[2021-01-21 16:29:17.518 +00:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Bilder/0001 - Kita Elia
[2021-01-21 16:29:17.522 +00:00] [INF] [38] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Humor
[2021-01-21 16:29:17.526 +00:00] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Hoerspiele Kinder
[2021-01-21 16:29:17.532 +00:00] [INF] [30] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Audio/Hoerbuecher
[2021-01-21 16:29:17.538 +00:00] [ERR] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(IEnumerable`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItem(MetadataResult`1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshMetadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-01-21 16:29:17.545 +00:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Bilder/1999 - Thailandjahr
[2021-01-21 16:29:17.547 +00:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scanne alle Bibliotheken" Failed after 1 minute(s) and 46 seconds
```

I dont know why it failed or where... Do you have an idea? Otherwise I would need to delete the whole libraries, the Jellyfin files and try to start again...

**Comment by BaronGreenback** [comment]
did you rename your audio folder - as it's now showing as /media/Audio/Hoerspiele?

**Comment by bigcookie** [comment]
Yes, I renamed it, but I checked also prior with ö/ä no difference. So I ruled this out...
[log_20210121.log](https://github.com/jellyfin/jellyfin/files/5850984/log_20210121.log)

In the log above I enabled debug logging. HEre is the full log. I stopped docker, cleaned the config and cache directories completely and restarted freshly. I only added the folder as a library I am suspicious about...
I cannot fully read, if the last JPG image might be causing the issue. I would wonder as I checked all files with jpeginfo -c and appear correct, but you never know...

**Comment by BaronGreenback** [comment]
It looks like the metadata isn't returning a required field - and so is crashing the refresh.

Just noticed that you're running 10.6.4. 10.7 is due to be released imminently which has a massive of fixes, including a faster library refresh. I'd personally try that before trying anything else.

**Comment by bigcookie** [comment]
It seems to be connected to the JPG files. I couldnt really find a pattern here as there are multiple pictures from the same camera... Nevertheless I moved the pictures appearing before the error pops up in the log and created a library out of those.
The scan fails immediately. As other folders with photos run through, I assume it is the JPG file...
I can provide a photo:

Pass: E8LwP7mW
link: https://cloud.andrekuhn.net/index.php/s/sJcJc6tPMdE9RDX 
Link is valid until tomorrow.

Will try 10.7 (I assume unstable is what I need to go for)

**Comment by bigcookie** [comment]
Ok, 10.7 nightly tells me that the scan completed in the UI, but the log shows errors like "cannot find part of the path"...
[log_20210121.log](https://github.com/jellyfin/jellyfin/files/5851172/log_20210121.log)

Advice on this is highly welcome...

**Comment by bigcookie** [comment]
Now I installed 10.7 correctly. Scanning still fails, but debug log contains more information.
[log_20210121.log](https://github.com/jellyfin/jellyfin/files/5851230/log_20210121.log)

**Comment by BaronGreenback** [comment]
Looks to be some corruption in the database.

Could you rename you database folder - then re-start JF. Re-add just the problem folder, and see if it parses correctly.
If it doesn't, are you able to compile PR's?

**Comment by bigcookie** [comment]
OK, I used the nightly from yesterday:

Server: d7822e6e37ee
Version: 10.7.0
Operating System: Linux
Architecture: X64

Setup everything newly (simply backed up the config folder and emptied it).
Result it the same. The picture folder now only contains 5 images (3x jpg, 2x cr2) and one video (1x mov).
[log_20210122.log](https://github.com/jellyfin/jellyfin/files/5855015/log_20210122.log)
Log attached.

Regarding PR - I am sorry, I can download a repo, I can change files and I can patch code. I dont have an IDE setup, allowing me to compile things.
I do have git installed for simple purposes (mainly backing up my configs and scripts), but with a short guide, I can most likley operate it.
Not sure if this helps...

**Comment by bigcookie** [comment]
Does it help, if I upload the DB? jellyfin.db and library.db are <200kb :-)

**Comment by BaronGreenback** [comment]
That would be great if you could - as i could do with reproducing your issue on my rigg to find out what's going wrong

**Comment by bigcookie** [comment]
Here you go. jellyfin.db and library.db 
[archive.zip](https://github.com/jellyfin/jellyfin/files/5857621/archive.zip)

I have the second config available and can test anytime.

**Comment by BaronGreenback** [comment]
Reproduced without your db.

create the directory with then edit the path for a library.
Exception thrown @ GetFileSystemEntries line 628

System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'F:\HÃ¶rbÃ¼cher Kinder'.
  Source=System.IO.FileSystem
  StackTrace:
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive) in C:\Code\jellyfin\Emby.Server.Implementations\IO\ManagedFileSystem.cs:line 628

**Comment by bigcookie** [comment]
Wow that's weird as I didnt create the library with the "Hörbücher Kinder" folder... Did I do something wrong? Anyway. Could you explain better what I should do? This "create the directory with then edit the path for a library." I dont get fully...

**Comment by BaronGreenback** [comment]
'directoryInfo.EnumerateDirectories("*", enumerationOptions)' threw an exception of type 'System.IO.DirectoryNotFoundException'

"Could not find a part of the path 'F:\\HÃ¶rbÃ¼cher Kinder'."

Folder exists definitely exists - and not permission issues.

**Comment by BaronGreenback** [comment]
the error occurred just browsing the folder structure - didn't have to change anything. 

Will let you know the outcome later tonight. (UK)

**Comment by bigcookie** [comment]
THanks a lot. Weirdly I encountered the issue while defining the library to be only including the folder "/media/Bilder/0001 - Kita Elia/bkp".
At least this is what I put into the library definition in the UI (in the one you downloaded).
The path with the special characters wasnt part of the library definition...

Probably my mistake? Will check again...

Let me know - happy to try it out. Thanks for following up that thoroughly here. I need to learn coding, so I can help better (at least this is my wish)

**Comment by bigcookie** [comment]
Could you find anything? Do you need more info? Files, setup, logs?
Sorry, just curious. I am happy, that you took the topic to take a closer look!!!!

**Comment by BaronGreenback** [comment]
Your log is showing that the jellyfin.db contains user info that's not in the authentication.db - that's the cause of the 
```
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
```

The second error seems to be the BOM in the CR2 image files cannot be read. Are these files valid, as in can you open them and view the contents?

**Comment by BaronGreenback** [comment]
So looking into the code - there is a work around for cr2 files due to them hanging the system. That is the cause of the 
```
[2021-01-22 10:01:00.577 +00:00] [ERR] [195] Emby.Photos.PhotoProvider: Image Provider - Error reading image tag for "/media/Bilder/0001 - Kita Elia/bkp/20200625_095620.cr2"
TagLib.CorruptFileException: Unknown Byte Order
   at TagLib.Tiff.BaseTiffFile.ReadHeader()
   at TagLib.Tiff.Cr2.File.ReadFile()
   at TagLib.Tiff.Cr2.File.Read(ReadStyle propertiesStyle)
   at TagLib.Tiff.Cr2.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at Emby.Photos.PhotoProvider.FetchAsync(Photo item, MetadataRefreshOptions options, CancellationToken cancellationToken)
```

If your cr2 files are valid - could you check to see if they have any meta tags - or zip and post one here?

**Comment by bigcookie** [comment]
The cr2 files I can open without problems (using xnview). The IPTC/XMP metadata is empty. GPS metadat contains 0,0 as location. This error i noticed as well, but it didnt abort the scan.

Attached again log file and DB. I completely setup Jellyfin freshly - the folder only contains only JPG and one png, one subfolder with JPG. Scan fails immediately. no special characters are in the path... It is now the full folder, but without the cr2 files.

[config.zip](https://github.com/jellyfin/jellyfin/files/5869321/config.zip)
I attached now my full config folder zipped.

**Comment by bigcookie** [comment]
I created just one folder with one jpg in it and made a library out of it. Attached the log (it is the one from previous post with additional runs)
Sorry in the last config, I forgot to enable debug logging. Here is the log with debug logging. Only one jpg in the folder. The jpg is shown correctly, thumbnails have been created, but the scan is still marked as failed...

If I pick another folder, it works fine... The picture I put in there is part of the archive I shared above, named "20180215_095824 IMG_6431.jpg"

The only difference is the pathname and the folder content.

Failed:
/share/Multimedia/Bilder/0001 - Kita Elia/bkp/
or
/share/Multimedia/Bilder/0001 - Kita Elia/

Worked:
/share/Multimedia/Bilder/0000 - Diverse/

It is not connected to cr2 files nor authentication as it seems.

**Comment by bigcookie** [comment]
Please let me know when you downloaded the image. I would like to remove the link at least afterwards.

**Comment by BaronGreenback** [comment]
removed it for you.

You've uncovered a few issues. I'll start submitting PR's this evening.

**Comment by bigcookie** [comment]
Cool - If I was able to help, I am happy. It would be great, if you can send some info at the end. I am a trained engineer and I am curious - also to learn a bit :-).

**Comment by bigcookie** [comment]
Is this fixed? Or more information required?

**Comment by axeluhl** [comment]
Same issue here:
[15:25:20] [ERR] [44] Emby.Server.Implementations.Library.LibraryManager: Error resolving path /media2/Wolfgang Ambros/Ambros Tauchen F�lbl - Watzmann live (1991) (2CD) by Rhoudini
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media2/Wolfgang Ambros/Ambros Tauchen F�lbl - Watzmann live (1991) (2CD) by Rhoudini'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass88_0.<ResolveFileList>b__0(FileSystemMetadata f)

**Comment by axeluhl** [comment]
The docker image I'm using is jellyfin/jellyfin (0aa773b67433). The volume that jelly

**Comment by bigcookie** [comment]
@BaronGreenback - sorry to push this topic... Was anything found? Anything I can still help with?
