### ISSUE TITLE
[bug] DVD/Absolutue order uses Aired order season structure

### ISSUE THREAD

**Issue by corntank** [jellyfin/jellyfin#5042]
**Describe the bug**
Jellyfin only seems to use the Aired order structure from TheTVDB even when choosing DVD or Absolute order. 

**System**
OS: Windows 10
Clients: Web
Browser: Chrome 87
Jellyfin Version: 10.6.4 stable
Plugins: AudioDB, Fanart, MusicBrainz, OMDb, TheTVDB
Storage: Synology NAS

**To Reproduce**
1. Create a new test libary.
2. Create a folder "Monogatari" (TheTVDBID 102261) in the new library.
3. Scan the library.
4. Change the series Display order to DVD.
5. Enable "Display missing episodes within seasons" for the library so that Jellyfin attempts to build all of the seasons. Ensure this is enabled in your user profile as well.
6. Scan an replace all metadata.
7. Inspect Season 3. Metadata up to episode 4 correctly pulls according to the DVD order, however, Jellyfin continues to attempt to pull episode data for 5-23 which only exists for Season 3 Aired order, not DVD order. Same behavior for Seasons 4/5. Seasons 6-11 are not pulled at all, which do exist for DVD order.
7. Create a "Season 06" folder to the "Monogatari" series folder. Create a text file in the "Season 06" folder and rename it entirely with extension to "S06E01.mkv".
8. Scan an replace all metadata. Jellyfin correctly pulls metadata for Season 6 Episode 1. This indicates Jellyfin sees the correct episode data depeding on the Display order selected, but the season structure still pulls based on the Aired order. Note, Jellyfin will not find the metadata for S6E1 if Aired order is selected.

**Logs**
Logs are filled with entries like this:

```
[2021-01-17 11:14:10.378 -05:00] [INF] [28] MediaBrowser.Providers.TV.SeriesMetadataService: Creating virtual missing/unaired episode "Monogatari" 3x5
[2021-01-17 11:14:10.642 -05:00] [ERR] [33] MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[DVD_episodenumber:5 DVD_season:3]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
```

**Expected behavior**
Jellyfin should pull the seasons order structure along with the episode metadata when DVD/Absolute orders are selected. I've experienced the same behavior with other shows like Attack on Titan and Black Lagoon.

**Comment by exterrestris** [comment]
Same thing happens with Firefly (The Movie DB (1437) in 10.7.1. Desired sort order was working in 10.6.4
