### ISSUE TITLE
Cannot compute blurhash (10.7 RC-2)

### ISSUE THREAD

**Issue by paranoyed** [jellyfin/jellyfin#5071]
**Describe the bug**
Since I Switched to the RC candidate I am getting errors from the Emby.Server.Implementations.Library.LibraryManager

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Browser
 - Browser: any
 - Jellyfin Version: 10.7.0 stable-rc tag
 - Playback: N/A
 - Reverse Proxy: caddy, same with ha_proxy
 - Base URL: none
 - Networking: reverse proxy
 - Storage: Docker Volume for config, transcodes, metadata, media is cifs and NFS (Read only mapped to the container)

**To Reproduce**

1. Go to Admin
2. Initiate a Library scan with replace all Metadata
3. Watch container logs.

**Expected behavior**
I expect the metadata to be downloaded and no errors in the logs.

**Logs**
````
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/library/05/0559d291e3c79945dc5a92faca720304/backdrop1.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[10:44:45] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: ********(/********) will be refreshed.
[10:44:47] [INF] [29] Emby.Server.Implementations.IO.LibraryMonitor: ********(/********) will be refreshed.
[10:44:53] [ERR] [48] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/metadata/library/56/564db9086ef1f8edf1cb5c3e53732a58/backdrop1.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/library/56/564db9086ef1f8edf1cb5c3e53732a58/backdrop1.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[10:44:53] [INF] [44] Emby.Server.Implementations.IO.LibraryMonitor: ********(/********) will be refreshed.
[10:44:56] [ERR] [42] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/metadata/library/5c/5c7dcc6124b6062abdace3f4f32b7fc7/backdrop1.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/library/5c/5c7dcc6124b6062abdace3f4f32b7fc7/backdrop1.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[10:44:59] [INF] [47] Emby.Server.Implementations.IO.LibraryMonitor: ********(/********) will be refreshed.
````
As alwas I have replaced some sensitive information with `********`

**Additional context**

I noticed that on newly added Media that for libraries of type movie people are no longer displayed. 
For previously added media they are still there.

edit: spelling

**Comment by paranoyed** [comment]
I just deleted a Library and added it again, the error persists. Even for folders not mapped read only to the container.

**Comment by BaronGreenback** [comment]
Just asking the obvious - but /config/metadata/library/5c/5c7dcc6124b6062abdace3f4f32b7fc7/backdrop1.jpg does exist???

**Comment by BaronGreenback** [comment]
Could you also check the logs to see if it's picking up the location of ffmpeg (known bug) ?

**Comment by paranoyed** [comment]
> Just asking the obvious - but /config/metadata/library/5c/5c7dcc6124b6062abdace3f4f32b7fc7/backdrop1.jpg does exist???
Yes and No, 
It did not after a few times forcing the update of the metadata it seems to have created it. 
I started a scan again and let it run overnight. I checked it again today, and it did not log the error messages again. 
I don't know what caused the error, but it looks like to have resolved itself.
