### ISSUE TITLE
Anime Plugin Broken in RC2

### ISSUE THREAD

**Issue by kaysond** [jellyfin/jellyfin#5075]
**Describe the bug**

If I install the anime plugin, RC2 doesn't launch

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Firefox 72
 - Jellyfin Version: 10.7 rc2
 - Installed Plugins: anime
 - Reverse Proxy: apache
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. install rc2 container
2. install anime plugin
3. restart jellyfin container

**Expected behavior**
container starts

**Logs**
```
[14:52:49] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Method 'GetImageResponse' in type 'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider' from assembly 'Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.Init()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Additional context**
I am upgrading from 10.6.4. Already saw #4913. I removed the plugins and restarted, and can launch 10.7rc2 just fine. Then I installed the plugin from within 10.7rc2's dashboard, and restarted the container. Then I get the error again.

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-anime/issues/94
