### ISSUE TITLE
Kodi Sync Queue package cannot be found

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin#5089]
**Describe the bug**

Via the webUI Dashboard > Plugins > Catalogue, install Kodi Sync Queue. 

What happens: the loading animation starts and will never finish. 

What the log says:
```
5:14.576 +01:00] [ERR] [77] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://o.belix:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Kodi Sync Queue
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2021-01-23 23:07:21.929 +01:00] [ERR] [76] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://o.belix:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Kodi Sync Queue
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Ubuntu 20.10
 - Virtualization: Docker
 - Clients: ShieldTV with Kodi on it (I only use Kodi because the JellyFin AndroidTV client has blocking issues, like not being able to select audio 
 - Browser: Firefox 78
 - Jellyfin Version: 
 - Playback: non-native, add-on mode in Kodi
 - Installed Plugins: OpenSubtitles, Trakt
 - Reverse Proxy: none
 - Base URL: 192.168.88.2:8096
 - Networking: local router
 - Storage: local, on the server itself

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/4688

Select a lower plugin version.
