### ISSUE TITLE
Can't install OpenSubtitles V10.0 plugin from the catalog.

### ISSUE THREAD

**Issue by fatraaij** [jellyfin/jellyfin#5129]
**System:**

- OS: Ubuntu Server 20.04.1 LTS
- Virtualization: LXC
- Jellyfin Version: 10.6.4

**Logs**
`[2021-01-29 17:39:46.560 +00:00] [ERR] Error processing request. URL: "https://xxxxxxxxxx:8920/Packages/Installed/Open Subtitles?AssemblyGuid=4b9ed42f-5185-48b5-9803-6ff2989014c4&version=10.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Open Subtitles
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
`

**Additional Text**
It seems to me that it can't find the opensubtitles package.
There are no issues downloading and installing V9.0 from the catalog.

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/4688

v10 is for Jellyfin 10.7

**Comment by fatraaij** [comment]
Then don't make it available for 10.6.
Now every time my plugins want to update I get errors.

**Comment by raychengx** [comment]
jellyfin 安装完成后  OpenSubtitle plugin  11.000  失效， 删除重新安装失败。
随后 卸载 11版本 安装10 版本，可以配置，但是重启后 11版本自动安装 并且 10版本失效
请教 什么原因
