### ISSUE TITLE
Server Fails to Start with Invalid Plugin (TypeLoadException)

### ISSUE THREAD

**Issue by tgardner851** [jellyfin/jellyfin#5146]
**Describe the bug**
Error in plugin load causes server to sometimes not start.

**System (please complete the following information):**
 - OS: Windows 10, Windows Server 2016
 - Virtualization: N/A
 - Clients: Browser (Firefox)
 - Browser: Firefox 85.0
 - Jellyfin Version: 10.7.0
 - Playback: N/A
 - Installed Plugins: Anime (install of this alone causes issue)
 - Reverse Proxy: N/A
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Install server or run development server
2. Install Anime plugin
3. Restart application
4. Fail to start with a log message

**Expected behavior**
Server starts and disables or inactivates plugin

**Logs**
```
[2021-02-01 13:09:53.149 -06:00] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Method 'GetImageResponse' in type 'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider' from assembly 'Jellyfin.Plugin.Anime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext() in C:\repos\jellyfin\Emby.Server.Implementations\Plugins\PluginManager.cs:line 117
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext() in C:\repos\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 1037
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext() in C:\repos\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 852
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes() in C:\repos\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 847
   at Emby.Server.Implementations.ApplicationHost.Init() in C:\repos\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 551
   at Jellyfin.Server.Program.StartApp(StartupOptions options) in C:\repos\jellyfin\Jellyfin.Server\Program.cs:line 186
```

**Screenshots**
N/A

**Additional context**
N/A

**Other Notes**
I intend to fix this issue myself, a catch is made on FileLoadException, but not for TypeLoadException, which is what is being thrown.

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/5090
