### ISSUE TITLE
Not fetching data from theTVDB.com

### ISSUE THREAD

**Issue by sfenwick** [jellyfin/jellyfin#5149]
Jellyfin (10.6.4, running on MacOS 10.13.6) is no longer downloading data from theTVDB. This is happening on a lot of shows. All are found by entering the data directly at theTVDB.com website. Typical log entry:

   ```
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2021-02-01 18:29:58.784 -08:00] [WRN] [57] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.2". Time (slow): 0:00:00.5918799. "http://192.168.1.27:8096/Items/RemoteSearch/Series"
[2021-02-01 18:30:03.210 -08:00] [INF] [26] MediaBrowser.Api.ItemLookupService: Setting provider id's to item 1a32f2ee-7b85-3460-1714-3d7de33723e6-"Churchill's First World War": "{\"Tvdb\":\"120876\"}"
[2021-02-01 18:30:03.250 -08:00] [ERR] [26] MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider: Failed to retrieve series with id "120876"
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 120876 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2021-02-01 18:30:03.491 -08:00] [ERR] [26] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2021-02-01 18:30:03.560 -08:00] [ERR] [26] MediaBrowser.Providers.TV.SeriesMetadataService: Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2021-02-01 18:30:03.561 -08:00] [INF] [26] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "1a32f2ee7b85346017143d7de33723e6"
[2021-02-01 18:30:03.596 -08:00] [ERR] [57] MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider: Failed to retrieve series with id "120876"
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 120876 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2021-02-01 18:30:03.709 -08:00] [ERR] [26] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2021-02-01 18:30:03.778 -08:00] [ERR] [26] MediaBrowser.Providers.TV.SeriesMetadataService: Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2021-02-01 18:30:03.871 -08:00] [ERR] [57] MediaBrowser.Providers.Manager.ProviderManager: "TvdbEpisodeImageProvider" failed in GetImageInfos for type "Episode"
System.InvalidOperationException: Nullable object must have a value.
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2021-02-01 18:30:04.309 -08:00] [ERR] [38] MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider: Failed to retrieve series with id "120876"
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 120876 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2021-02-01 18:30:04.426 -08:00] [ERR] [38] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
[2021-02-01 18:30:04.472 -08:00] [ERR] [38] MediaBrowser.Providers.TV.SeriesMetadataService: Error in DummySeasonProvider
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2021-02-01 18:30:04.473 -08:00] [INF] [38] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "1a32f2ee7b85346017143d7de33723e6"
[2021-02-01 18:30:04.473 -08:00] [WRN] [38] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.1.2". Time (slow): 0:00:01.2747722. "http://192.168.1.27:8096/Items/RemoteSearch/Apply/1a32f2ee7b85346017143d7de33723e6?ReplaceAllImages=true"
[2021-02-01 18:37:09.222 -08:00] [ERR] [78] MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider: Failed to retrieve series with id "120876"
TvDbSharper.TvDbServerException: The given series ID does not exist; {"Error":"ID: 120876 not found"}
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2021-02-01 18:37:09.617 -08:00] [WRN] [78] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.2". Time (slow): 0:00:00.6143723. "http://192.168.1.27:8096/Items/RemoteSearch/Series"
[2021-02-01 18:37:45.525 -08:00] [ERR] [58] MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider: Failed to retrieve series with id "120876"
TvDbSharper.TvDbServerException: The given series ID does not exist; {"Error":"ID: 120876 not found"}
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.Plugins.TheTvdb.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
```

**Comment by zynexiz** [comment]
Have the same issue to on CentOS, have to manually add metadata to most shows.

**Comment by Ulrar** [comment]
Getting the same issue

**Comment by bradgy** [comment]
I also have this, or a similar issue, for one of my shows.

This is the log I get when I try to "Identify" a mis-identified TV show (Narrative Telephone) with the correct Series ID (Critical Role): 

```
[2021-04-11 08:21:41.333 +10:00] [WRN] Slow HTTP Response from "https://jellyfin.$DOMAINNAME.com/Items/RemoteSearch/Series" to "122.199.45.222" in 0:00:01.1156667 with Status Code 200
[2021-04-11 08:21:44.020 +10:00] [INF] Setting provider id's to item e9ac49d3-2dfa-8460-bff6-ab9cc636dbd1-"Narrative Telephone": "{\"Tvdb\":\"296861\"}"
[2021-04-11 08:21:48.005 +10:00] [ERR] Failed to retrieve episode with id null, series id "390572"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:2 EpisodeNumber:67]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2021-04-11 08:21:48.062 +10:00] [ERR] Failed to retrieve episode images for series "390572"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:2 EpisodeNumber:67]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2021-04-11 08:21:49.115 +10:00] [ERR] Failed to retrieve episode with id null, series id "390572"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:2 EpisodeNumber:68]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```
That output continues for every episode in the folder.

Jellyfin Version: 10.7.1

Operating System: Linux

Architecture: X64

TVDB paid subscription with legacy API key saved in plugin.

**Comment by cvium** [comment]
Issues with thetvdb should be opened at https://github.com/jellyfin/jellyfin-plugin-tvdb.

The OP's issue is that the id is not a series, but a tv movie. I think they recently made this change on the site and in the API. We do not currently support tv movies.

@bradgy You should open a new issue in the tvdb plugin repo.
