### ISSUE TITLE
[10.7.0 RC3] Not able to fetch Shows metadata because of an issue with images fetching (I suppose ?)

### ISSUE THREAD

**Issue by RoroTiti** [jellyfin/jellyfin#5161]
**Describe the bug**
Jellyfin is not able to fetch Shows metadata, at least from TheMovieDB (no details nor images).

https://i.imgur.com/HKBs1oe.png

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: Hyper-V VM
 - Clients: na
 - Browser: na
 - Jellyfin Version: 10.7.0 RC3
 - Playback: na
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: na
 - Storage: local

**Expected behavior**
Correct metadata fetching from TheMovieDB, data and images (right now having none).

**Logs**
Only a piece since all lines are identical for all Shows.

```
[09:20:31] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Altered Carbon (2018)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:33] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Black Mirror (2011)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:33] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\The Mandalorian (2019)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:35] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Stranger Things (2016)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:35] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Umbrella Academy (2019)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:36] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Rick and Morty (2013)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:37] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\She-Ra and the Princesses of Power (2018)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:39] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\BoJack Horseman (2014)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**EDIT 1:** After unchecking all fetch images options for my Show library, Jellyfin is now able to fetch Shows detailds and metadata, without images so.

**EDIT 2:** After numerous testings, I came to a conclusion: the issue happens ONLY if the library DOESN'T have yet images or metadata AT ALL. When I started to add manually metadata and then retried to fetch auto metadata, it finally worked for everything. And the issue is only on TheMovieDB fetcher.

**Comment by luspi** [comment]
This issue seems to be back, it is happening to me now with JellyFin 10.7.5 on Ubuntu Server 20.04. Some extracts of my log:

```[2021-05-09 21:03:41.462 +02:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/path/to/folder"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-05-09 21:03:42.122 +02:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/path/to/folder"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-05-09 21:03:42.689 +02:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/path/to/folder"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-05-09 21:03:43.252 +02:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/path/to/folder"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-05-09 21:03:43.785 +02:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/path/to/folder"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)```

**Comment by yesimanoob** [comment]
This seems to be back. It's been reproing for me for many weeks now.

```[2021-06-28 22:07:14.253 +09:00] [ERR] [19] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/sharedfolders/videos/tv/[SHOWNAME]"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)```

**Comment by daullmer** [comment]
Could you please post your logs without the redacted path?
I have tried to reproduce this but I can not. The path to my TV show looks like this: `/media/TV/Game of Thrones`

**Comment by daullmer** [comment]
Did fetching the rest of the infos (description, actors, ...) work for these shows? Do they have a TMDb id set? (You can see this by going to the show, clicking the three dots and selecting 'Edit metadata')
It should look something like this:
<img width="793" alt="Bildschirmfoto 2021-08-13 um 16 11 28" src="https://user-images.githubusercontent.com/16425113/129370401-1193673a-c853-47df-9ef3-b13a03958d65.png">

**Comment by stevearbon15** [comment]
Here's a full path
```
[08:22:38] [ERR] [44] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at /data/media/TV Shows/Insecure
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

For your second post: I did get a good chunk of the metadata surrounding the show. Just no images. I checked the series I had this issue on, and none of them had TMDB Id set. They only had the IMDB Id set. If I try without TMDB Id, the error appears. If I manually insert the Id and refresh metadata, I get images.

**Comment by daullmer** [comment]
Thanks! Do you have NFO files for the shows? I suspect the info you have is from the nfo file and it somehow results in no TMDb id.
If yes, would you mind to post the content of one of the nfo files here?

**Comment by stevearbon15** [comment]
It appears I do not have NFO files enabled for my TV Shows library, which is exhibiting the behavior
![Screenshot_20210813-102038](https://user-images.githubusercontent.com/7492717/129389652-2fc5809a-0ffa-4bf4-9193-d77b66f21c16.png)

**Comment by daullmer** [comment]
This checkbox only controls nfo saving. If there are nfo files in the directory of the tv show, they will always be read, regardless of this checkbox

**Comment by stevearbon15** [comment]
Ah I see. There are no NFO files in either the series folder or the season folders. The only thing it has was the IMDB Id, so I wonder if it was able to pull metadata from there, but it tried to get images from the movie db but couldn't because there was no Id for it.

**Comment by pulsemod** [comment]
I am having the same issue.
```
[2021-08-16 00:47:47.527 +00:00] [ERR] [206] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/home/username/files/TV/Stepping Selection Videos"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```
However, this is only for this particular 'shows' library. I have another shows-type library located at `/home/username/files/Anime/` that has no issues at all retrieving images. This is a fresh install of Jellyfin 10.7.6, both libraries created today. The rest of the metadata seems to be complete, with overview text, episode descriptions, IMDb ID, etc. though no TheMovieDb Series Id is saved.
