### ISSUE TITLE
Local external subtitle files with STRM videos don't work again

### ISSUE THREAD

**Issue by rexio8** [jellyfin/jellyfin#5168]
**Describe the bug**
Playing locally stored external subtitles along with a STRM video causes Stream.js to return a 400, and an error (in logs) as the response.
In my case, the file structure looks like this (inside a folder with the movie name)
`MOVIE_NAME.ger.srt`
`MOVIE_NAME.strm`

The video plays just fine, but without any subtitles. This is a very similar issue to #2543. Please see the Additional context section.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: Browser
 - Browser: 88.0.4324.150
 - Jellyfin Version: jellyfin_20210205.2-unstable
 - Playback: Direct Play 
 - Installed Plugins: Open Subtitles 10.0.0.0
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Bridge
 - Storage: STRM files, local subtitles

**To Reproduce**
Put a locally stored external subtitle in the same folder as an STRM file
Playback the STRM file with the external subtitle selected

**Expected behavior**
The subtitles are read and display properly

**Logs**

```
[09:54:31] [ERR] [10] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Videos/1088642a-c2fe-136b-1788-21c33560b769/1088642ac2fe136b178821c33560b769/Subtitles/2/0/Stream.js.
System.ArgumentException: Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri')
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpClient.CreateRequestMessage(HttpMethod method, Uri uri)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetStream(String path, MediaProtocol protocol, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.GetSubtitle(Guid itemId, String mediaSourceId, Int32 index, String format, Nullable`1 endPositionTicks, Boolean copyTimestamps, Boolean addVttTimeMap, Int64 startPositionTicks)
   at lambda_method962(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
**Additional context**
The issue is probably due to a bug in [https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs](url), in the `GetSubtitleStream` method. The local variable named `protocol` is assigned but never used and therefore the protocol is selected from the strm file, and not treated as a local subtitle file. Changing the line `var stream = await GetSubtitleStream(fileInfo.Path, fileInfo.Protocol, fileInfo.IsExternal, cancellationToken).ConfigureAwait(false);` to `var stream = await GetSubtitleStream(fileInfo.Path, protocol, fileInfo.IsExternal, cancellationToken).ConfigureAwait(false);` seems to fix it, but as I'm not sure if this breaks anything, please have some jellyfin developer check this and issue a pull request.

**Comment by BaronGreenback** [comment]
From looking at #2543 it looks like the code got reverted at some point.

Are you able to test PRs?

**Comment by BaronGreenback** [comment]
PR https://github.com/jellyfin/jellyfin/pull/5278

**Comment by rexio8** [comment]
> From looking at #2543 it looks like the code got reverted at some point.
> 
> Are you able to test PRs?

Tested with the current master branch. External subtitles work with strm content like a charm. Thank you @BaronGreenback very much for all your work.

**Comment by whiteowl3** [comment]
Please reopen.
One of these subtitle files is a .srt file with the extension .srt, the deliveryurl is the servers local path, clients get 404 for all subtitles after requesting https://server.tld/servers/local/path/isnt/served.srt
The other subtitle is a strm file with the extension .srt which resolves to a real srt file.  the deliveryurl is also the servers local path, clients get 404 for all subtitles after requesting https://server.tld/servers/local/path/isnt/served.srt
Seems like at least one of the two configurations ought to work?
![Screenshot from 2021-12-19 00-42-20](https://user-images.githubusercontent.com/71030468/146719059-2139367e-bcbc-4400-852f-9006cdbaecd2.png)
