### ISSUE TITLE
Music metadata not properly parsed

### ISSUE THREAD

**Issue by echapon** [jellyfin/jellyfin#5172]
**Describe the bug**
Jellyfin fails to properly organise my music into artists or albums, for some fraction of the music.

**System (please complete the following information):**
 - OS: Debian (Raspberry Pi 4, arm7l)
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 85
 - Jellyfin Version: 10.6.4 (Yunohost)
 - Playback: irrelevant
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: none
 - Base URL: ?
 - Networking: server is hosted at home
 - Storage: local SSD (ext4)

**To Reproduce**
Importing the music, but not sure what makes some music badly handled while the majority of the collection is fine. My collection is quite large (180GB) so I have not yet been able list the problematic artists / albums / tracks and why they were problematic.

**Expected behavior**
I expect each album to be properly presented as such.

**Logs**
```
[2021-02-06 19:29:23.209 +01:00] [WRN] HTTP Response 200 to "2001:861:3d03:a70:89d:d990:860a:9725". Time (slow): 0:00:00.5804573. "http://echapon.ynh.fr/jellyfin/Users/43cbac02afcb4d2aaf91d527a61bb042/Items/3f31a37c1a7bb65cf5d701043b9dfb89"
[2021-02-06 19:29:24.105 +01:00] [WRN] HTTP Response 200 to "2001:861:3d03:a70:89d:d990:860a:9725". Time (slow): 0:00:00.7419248. "http://echapon.ynh.fr/jellyfin/Users/43cbac02afcb4d2aaf91d527a61bb042/Items?IncludeItemTypes=MusicAlbum&Recursive=true&ExcludeItemIds=3f31a37c1a7bb65cf5d701043b9dfb89&SortBy=ProductionYear%2CSortName&SortOrder=Descending&ContributingArtistIds=3f31a37c1a7bb65cf5d701043b9dfb89"
[2021-02-06 19:29:24.131 +01:00] [WRN] HTTP Response 200 to "2001:861:3d03:a70:89d:d990:860a:9725". Time (slow): 0:00:00.7680399. "http://echapon.ynh.fr/jellyfin/Items/3f31a37c1a7bb65cf5d701043b9dfb89/Similar?userId=43cbac02afcb4d2aaf91d527a61bb042&limit=12&fields=PrimaryImageAspectRatio%2CUserData%2CCanDelete"
[2021-02-06 19:29:24.285 +01:00] [WRN] HTTP Response 200 to "2001:861:3d03:a70:89d:d990:860a:9725". Time (slow): 0:00:00.9089866. "http://echapon.ynh.fr/jellyfin/Users/43cbac02afcb4d2aaf91d527a61bb042/Items?SortOrder=Descending&IncludeItemTypes=MusicAlbum&Recursive=true&Fields=AudioInfo%2CSeriesInfo%2CParentId%2CPrimaryImageAspectRatio%2CBasicSyncInfo%2CAudioInfo%2CSeriesInfo%2CParentId%2CPrimaryImageAspectRatio%2CBasicSyncInfo&Limit=100&StartIndex=0&CollapseBoxSetItems=false&AlbumArtistIds=3f31a37c1a7bb65cf5d701043b9dfb89&SortBy=ProductionYear%2CSortname"
[2021-02-06 19:29:25.387 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:25.522 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:25.642 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:25.770 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:25.920 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.042 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.172 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.299 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.419 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.548 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.718 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.831 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:26.956 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2021-02-06 19:29:27.082 +01:00] [ERR] Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5276688/107126979-5c2fc000-68b3-11eb-89b7-4e55b461a43a.png)
![image](https://user-images.githubusercontent.com/5276688/107126988-723d8080-68b3-11eb-91f7-0fbfa77886ce.png)
![image](https://user-images.githubusercontent.com/5276688/107127080-f859c700-68b3-11eb-8315-edf1531a87da.png)

**Additional context**
For information, here is what music I have for artist "Revolution Void":
```
$ ls Revolution\ Void/
 _arcthumb  'Increase the Dosage'  'Let 1,000 Flowers Bloom'  'Like A Secret Dream'   Revolution_Void_-_Oldskool_Breaks_Mix_vbr.mp3  'The Politics of Desire'  'Thread Soul'
```
i.e. I would expect 5 albums, where only 1 shows up ("The Politics of Desire"), also containing together the tracks of the other 4. Interestingly, the metadata of the other albums of this artist does seem to be parsed properly (see screenshot for track 1 of "Like a Secret Dream"), except those for "Let 1,000 Flowers Bloom" which are not parsed at all. Additional information: among the 5 albums listed for this particular artist, "Increase The Dosage" is in FLAC, "Let 1,000 Flowers Bloom", "The Politics of Desire", and "Thread Soul" are in Vorbis, and "Like A Secret Dream" in mp3, so it does not seem to be connected with the format.

**Comment by fungos** [comment]
Version: 10.7.5

Operating System: Linux Manjaro

Architecture: X64

AUR jellyfin 10.7.5-1

I have the same issue.

**Comment by srcrist** [comment]
Closing this issue as stale. There is simply not enough information here to present any sort of actionable issue. If you still experience this issue, please visit our support channels either on the forums or on the Matrix/Discord server so someone can look over your directory structure and naming and such to help troubleshoot matching issues.
