### ISSUE TITLE
Sudden restart during usage "Unhandled exception"

### ISSUE THREAD

**Issue by mindfuucker** [jellyfin/jellyfin#5173]
**Describe the bug**
I was watching a show and the application just restarted. I was also adding some new shows to the directory.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Clients: Browser
 - Browser: Chrome 88.0
 - Jellyfin Version: 10.6.4
 - Playback: not sure
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: local

**To Reproduce**
I'm not sure

**Expected behavior**
Not crashing application

**Logs**
```
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Core startup complete
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Executed all pre-startup entry points in 0:00:00.3528401
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.23.0.1
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.19.0.1
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.178.30
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] ServerId: 44c566abb43f4f7c9f49b290a2fa1d9e
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] FFmpeg: Custom: /usr/lib/jellyfin-ffmpeg/ffmpeg
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Found ffmpeg version 4.3.1
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Daily trigger for Extract Chapter Images set to fire at 02/07/2021 02:00, which is 5:39:50.5509321 from now.
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Running startup tasks
feb 06 20:20:09 roy-SERVER jellyfin[332953]: [20:20:09] [INF] Kestrel listening on all interfaces
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Loading assemblies
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Setting cache path: /var/cache/jellyfin
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Application directory: /usr/lib/jellyfin/bin/
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Web resources path: /usr/share/jellyfin/web
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Program data path: /var/lib/jellyfin
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Processor count: 8
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] User Interactive: True
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] 64-Bit Process: True
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Architecture: X64
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Operating system: Linux
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Environment Variables: ["[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib jellyfin/restart.sh]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]"]
feb 06 20:20:07 roy-SERVER jellyfin[332953]: [20:20:07] [INF] Jellyfin version: 10.6.4
feb 06 20:20:06 roy-SERVER systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 2.
feb 06 20:20:06 roy-SERVER systemd[1]: jellyfin.service: Failed with result 'signal'.
feb 06 20:20:06 roy-SERVER systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueue.FireNextTimers()
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
feb 06 20:20:06 roy-SERVER jellyfin[112447]: Unhandled exception. System.Net.NetworkInformation.NetworkInformationException (0x80004005): An error was encountered while querying information from the operating system.
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueue.FireNextTimers()
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
feb 06 20:20:06 roy-SERVER jellyfin[112447]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
feb 06 20:20:06 roy-SERVER jellyfin[112447]: System.Net.NetworkInformation.NetworkInformationException (0x80004005): An error was encountered while querying information from the operating system.
feb 06 20:20:06 roy-SERVER jellyfin[112447]: [20:20:06] [FTL] Unhandled Exception
feb 06 20:19:58 roy-SERVER jellyfin[112447]: [20:19:58] [INF] OnRefreshComplete 69dcec088f166710c55e7160ac199d04
feb 06 20:19:58 roy-SERVER jellyfin[112447]: [20:19:58] [INF] OnRefreshStart 69dcec088f166710c55e7160ac199d04
```

**Screenshots**
Some Nginx error 505

**Additional context**

**Comment by cvium** [comment]
Looks similar to #5454
