### ISSUE TITLE
The input does not contain any JSON tokens

### ISSUE THREAD

**Issue by rasmuslos** [jellyfin/jellyfin#5184]
**Describe the bug**
When I start the server I get the following error without any further information and the start aborts

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Safari 14.1
 - Jellyfin Version: 10.7.0
 - Playback: Transcode
 - Installed Plugins: Open Subtitles
 - Reverse Proxy: traefik
 - Base URL: /
 - Networking: bridge
 - Storage: local (volume)

**To Reproduce**

1. Edit a scheduler
2. Reboot

**Expected behavior**
The server starts

**Logs**
```

[07:41:46] [INF] [1] Main: Kestrel listening on Any IP4 Address

[07:41:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks

[07:41:46] [FTL] [1] Main: Error while starting server.

System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)

   at System.Text.Json.Utf8JsonReader.Read()

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   --- End of inner exception stack trace ---

   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)

   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)

   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.LoadTriggerSettings()

   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.LoadTriggers()

   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.InitTriggerEvents()

   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker..ctor(IScheduledTask scheduledTask, IApplicationPaths applicationPaths, ITaskManager taskManager, ILogger logger)

   at Emby.Server.Implementations.ScheduledTasks.TaskManager.<AddTasks>b__23_0(IScheduledTask t)

   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()

   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)

   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)

   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at Emby.Server.Implementations.ScheduledTasks.TaskManager.AddTasks(IEnumerable`1 tasks)

   at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()

   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[07:41:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost

[07:41:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV

[07:41:46] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Edit:**
I removed `/config/ScheduledTasks` and now the startup completes

**Comment by cvium** [comment]
Looks similar to https://github.com/jellyfin/jellyfin/issues/5000

**Comment by cvium** [comment]
> Edit a scheduler

Edit how? What was the contents of your scheduledtasks config?

**Comment by rasmuslos** [comment]
Its the same but i didn't get a stack trace so i didn't find the issue. Go to Settings -> Tasks and add a new trigger

**Comment by cvium** [comment]
Figured it by coincidence... there was an async call that wasn't being awaited. I am guessing that sometimes the file stream would be disposed before it could write and when the async task isn't awaited we're not informed of any exceptions occurring.

**Comment by VigibotDev** [comment]
I get similar errror on the "seatch for keyframe" task, and premature end to [Failed] :
Debug log don't help (I want to know the recent added video name make this problem)
```
[2024-10-05 18:33:28.019 +02:00] [ERR] Error executing Scheduled Task
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at Jellyfin.MediaEncoding.Hls.ScheduledTasks.KeyframeExtractionScheduledTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-10-05 18:33:28.019 +02:00] [INF] "Extracteur d'images clés" Failed after 0 minute(s) and 2 seconds
```

**Comment by VigibotDev** [comment]
I solved my own case with :
find /var/lib/jellyfin/data/keyframes -type f -mtime -2 -name '*.json' -execdir ls -- '{}' \;
Because problem appeared AFTER two day ago.
This removed the corrupted JSON file, and the task work success now.

**Comment by birwin88** [comment]
I believe I'm having a similar issue as @ServeurpersoCom but this has been ongoing for a long time so I'm not sure how to track down the corrupt json file.  Logs look almost identical.  Is there any way this log can be enhanced to show what keyframe specifically is causing the issue?  

As of right now, my plan is to delete folders in the data/keyframes location and re-run the task which appears to be working.  Still failing but taking much longer to get to a failed state.
