### ISSUE TITLE
MediaEncoder.ConvertImage  NotImplementedException

### ISSUE THREAD

**Issue by cfl520** [jellyfin/jellyfin#5196]
-----------------------------------------------------------------------------
this is my error:

[23:29:06] [ERR] [28] Emby.Drawing.ImageProcessor: Image conversion failed for C:\jellyfin_10.6.4\config_info\metadata\library\e9\e9729af2a019640c44b53591149f2d3d\poster.json
System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
   at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
------------------------------------------------------------------------------
this is MediaEncoder  src :

   /// <inheritdoc />
        public Task ConvertImage(string inputPath, string outputPath)
        {
            throw new NotImplementedException();
        }
-------------------------------------------------------------------------------
 How can I prevent it from throwing an exception ？

**Comment by cfl520** [comment]
> **PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**
> 
> **Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**
> 
> ## However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.
> this is my error:
> 
> ## [23:29:06] [ERR] [28] Emby.Drawing.ImageProcessor: Image conversion failed for C:\jellyfin_10.6.4\config_info\metadata\library\e9\e9729af2a019640c44b53591149f2d3d\poster.json
> System.NotImplementedException: The method or operation is not implemented.
> at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
> at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
> this is MediaEncoder src :
> 
> ## ///
> public Task ConvertImage(string inputPath, string outputPath)
> {
> throw new NotImplementedException();
> }
> How can I prevent it from throwing an exception ？

**Comment by cfl520** [comment]
> **PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**
> 
> **Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**
> 
> ## However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.
> this is my error:
> 
> ## [23:29:06] [ERR] [28] Emby.Drawing.ImageProcessor: Image conversion failed for C:\jellyfin_10.6.4\config_info\metadata\library\e9\e9729af2a019640c44b53591149f2d3d\poster.json
> System.NotImplementedException: The method or operation is not implemented.
> at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
> at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
> this is MediaEncoder src :
> 
> ## ///
> public Task ConvertImage(string inputPath, string outputPath)
> {
> throw new NotImplementedException();
> }
> How can I prevent it from throwing an exception ？



> **PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**
> 
> **Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**
> 
> ## However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.
> this is my error:
> 
> ## [23:29:06] [ERR] [28] Emby.Drawing.ImageProcessor: Image conversion failed for C:\jellyfin_10.6.4\config_info\metadata\library\e9\e9729af2a019640c44b53591149f2d3d\poster.json
> System.NotImplementedException: The method or operation is not implemented.
> at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
> at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
> this is MediaEncoder src :
> 
> ## ///
> public Task ConvertImage(string inputPath, string outputPath)
> {
> throw new NotImplementedException();
> }
> How can I prevent it from throwing an exception ？
