### ISSUE TITLE
Can't download content anymore in chrome

### ISSUE THREAD

**Issue by Celludriel** [jellyfin/jellyfin#5265]
**Describe the bug**
In the current release candidate 10.7 RC3 I can't download any content anymore on the chrome webbrowser

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.7 RC3 
 - Playback: Not Applicable
 - Installed Plugins:
```
 [20:11:20] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[20:11:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles_10.0.0.0\Jellyfin.Plugin.OpenSubtitles.dll
[20:11:20] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from C:\ProgramData\Jellyfin\Server\plugins\Open Subtitles_10.0.0.0\OpenSubtitlesHandler.dll
[20:11:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Open Subtitles 10.0.0.0
[20:11:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.0.0
[20:11:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.0.0
[20:11:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.0.0
```
 - Reverse Proxy: none,
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to any movie
2. Click on 'Download'

**Expected behavior**
Movie downloads to my desktop

**Logs**
```
[07:45:02] [ERR] [251] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/3b0f7e4025ea564bca10fd2b3e6cad8b/Download.
System.MissingMethodException: Method not found: 'Void Jellyfin.Data.Entities.ActivityLog..ctor(System.String, System.String, System.Guid, Microsoft.Extensions.Logging.LogLevel)'.
   at Jellyfin.Api.Controllers.LibraryController.LogDownloadAsync(BaseItem item, User user, AuthorizationInfo auth)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Api.Controllers.LibraryController.LogDownloadAsync(BaseItem item, User user, AuthorizationInfo auth)
   at Jellyfin.Api.Controllers.LibraryController.GetDownload(Guid itemId)
   at lambda_method1030(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by crobibero** [comment]
I can't replicate this on my instance of rc3.

On the master branch the ctor was changed, but on the 10.7 branch it's being called correctly. Where is your release sourced from?
https://github.com/jellyfin/jellyfin/blob/release-10.7.z/Jellyfin.Api/Controllers/LibraryController.cs#L905:L908

**Comment by Celludriel** [comment]
I have this release https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc3 just from the release page, but now I do recall having to add a fix so videos would play on android and Iphone

https://github.com/jellyfin/jellyfin/issues/3815#issuecomment-768417098

maybe this dll brought in a bug, fixing on thing breaking another.

**Comment by Celludriel** [comment]
I installed the latest stable version and the issue has been fixed
