### ISSUE TITLE
After updating from 10.6.4 to 10.7.0 RC3, images are not displayed.

### ISSUE THREAD

**Issue by faizpuru** [jellyfin/jellyfin#5303]
**Describe the bug**
After updating from 10.6.4 to 10.7.0 RC3, images are not displayed. No problem on 10.6.4.
**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Brave 1.19.90
 - Jellyfin Version: 10.7.0 RC3
 - Playback: X
 - Installed Plugins: I removed all the plugin for the upgrade
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: ?
 - Storage: local

**To Reproduce**
Upgrade jellyfin from 10.6.4 to 10.7.0 RC3
Go to the Client
Images are not displayed (only blurhash)
**Expected behavior**
Images should be displayed
**Logs**
Plenty of this kind of logs :
```
[10:28:26] [ERR] [19] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/af9d74c0c02a6e0cedfe5a447772c560/Images/Primary.
System.NotSupportedException: Path '"/config/cache"/images/resized-images/f/f287e4a1-26d5-8c98-f5e3-55b5e02f8eb4.png' was not rooted.
at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.WriteFileAsync(ActionContext context, PhysicalFileResult result, RangeItemHeaderValue range, Int64 rangeLength)
at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.ExecuteAsync(ActionContext context, PhysicalFileResult result)
at Microsoft.AspNetCore.Mvc.PhysicalFileResult.ExecuteResultAsync(ActionContext context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[10:28:26] [ERR] [27] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/767bffe4f11c93ef34b805451a696a4e/Images/Primary.
System.NotSupportedException: Path '"/config/cache"/images/resized-images/2/2093c4f7-3c61-f0d9-03f3-cbe674eeed79.png' was not rooted.
```

**Screenshots**
X

**Additional context**
X

**Comment by krutburken** [comment]
"/config/cache"/images/resized-images/f/f287e4a1-26d5-8c98-f5e3-55b5e02f8eb4.png

Looks like there's an extra quotation in the path? Don't know whether or not it's an issue, just an observation.

**Comment by faizpuru** [comment]
Nice catch ! I had some quotes on my docker compose file. I remove it and it's working now.
