### ISSUE TITLE
Error creating "Jellyfin.Plugin.KodiSyncQueue.Plugin"

### ISSUE THREAD

**Issue by gldl137** [jellyfin/jellyfin#5308]
[2021-02-26 03:08:07.102 +00:00] [INF] [1] Main: Jellyfin version: "10.7.0"
[2021-02-26 03:08:07.117 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /cache]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_LOG_DIR, /config/log]"]
[2021-02-26 03:08:07.119 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2021-02-26 03:08:07.120 +00:00] [INF] [1] Main: Operating system: "Linux"
[2021-02-26 03:08:07.120 +00:00] [INF] [1] Main: Architecture: X64
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: 64-Bit Process: True
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: User Interactive: True
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: Processor count: 4
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: Program data path: "/config"
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2021-02-26 03:08:07.121 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2021-02-26 03:08:07.238 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/config/cache"
[2021-02-26 03:08:07.269 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-02-26 03:08:07.269 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-02-26 03:08:07.269 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-02-26 03:08:07.273 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-02-26 03:08:07.273 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-02-26 03:08:07.295 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error deserializing "﻿{

[2021-02-26 03:08:07.299 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error deserializing "﻿{
  \"category\": \"General\",
  \"changelog\": \"changelog\n\",
  \"description\": \"This plugin will track all media changes while Kodi clients are offline to decrease sync times.\",
  \"guid\": \"771e19d6-5385-4caf-b35c-28a0e865cf63\",
  \"name\": \"Kodi Sync Queue\",
  \"overview\": \"Sync all media changes with Kodi clients\",
  \"owner\": \"jellyfin\",
  \"targetAbi\": \"10.7.0.0\",
  \"timestamp\": \"2020-12-05T22:10:37.0000000Z\",
  \"version\": \"6.0.0.0\",
  \"status\": \"Malfunctioned\",
  \"autoUpdate\": true

[2021-02-26 03:08:08.481 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating "Jellyfin.Plugin.KodiSyncQueue.Plugin"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)

**Comment by crobibero** [comment]
Is this from linuxserver’s container? The plugin is only built for 10.7 explicitly

**Comment by gldl137** [comment]
> 这是来自linuxserver的夜间容器吗？该插件仅针对10.7显式构建


This is from "docker," docker pull jellyfin/ jellyfin:unstable

**Comment by gldl137** [comment]
> 这是来自linuxserver的夜间容器吗？该插件仅针对10.7显式构建


This is from "docker," docker pull jellyfin/ jellyfin:unstable

**Comment by crobibero** [comment]
Use `jellyfin/jellyfin:stable-rc`, the plugin isn’t currently built for `unstable `
