### ISSUE TITLE
Multiple dll's in plugins folder may cause an exception on rare occations

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#5353]
Seen this on two separate occasions now - (thought it was my setup at first). (This is 10.8 dlna plugins, but core plugin code hasn't changed)

```
[2021-03-02 23:42:41.840 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.DlnaPlayTo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.DlnaPlayTo_1.0.0.0\Jellyfin.Plugin.DlnaPlayTo.dll"
[2021-03-02 23:42:41.849 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Ssdp, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.DlnaPlayTo_1.0.0.0\Jellyfin.Plugin.Ssdp.dll"
[2021-03-02 23:42:41.921 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.DlnaServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.DlnaServer_1.0.0.0\Jellyfin.Plugin.DlnaServer.dll"
[2021-03-02 23:42:41.996 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.DlnaServer_1.0.0.0\Jellyfin.Plugin.Ssdp.dll". Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext() in C:\Code\jellyfin\Emby.Server.Implementations\Plugins\PluginManager.cs:line 132
[2021-03-02 23:42:42.109 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.UPnP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.UPnP_1.0.0.0\Jellyfin.Plugin.UPnP.dll"
[2021-03-02 23:42:42.148 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Mono.Nat, Version=3.0.0.0, Culture=neutral, PublicKeyToken=6c9468a3c21bc6d1" from "C:\ProgramData\Jellyfin\Server\plugins\Jelly.Plugin.UPnP_1.0.0.0\Mono.Nat.dll"
[2021-03-02 23:42:48.515 +00:00] [DBG] [1] Jellyfin.Plugin.DlnaPlayTo.DlnaPlayTo: DLNA PlayTo: Starting Device Discovery.
```

The folder C:\ProgramData\Jellyfin\Server\plugins contains two dll's, one plugin and one supporting dll.

![image](https://user-images.githubusercontent.com/22121540/109730797-fbde2680-7bb1-11eb-8213-b00e771e3af7.png)

Somewhere in the code it looks like the plugin dll is being loaded twice, resulting in the plugin protection routine being triggered and the plugin being disabled on the next startup.

**Comment by BaronGreenback** [comment]
VS 2019 again!
