### ISSUE TITLE
DLNA/UPnP cannot be disabled (leaking information/log spam)

### ISSUE THREAD

**Issue by nodiscc** [jellyfin/jellyfin#5401]
**Describe the bug**

**System:**
 - OS: Debian 10
 - Virtualization: KVM
 - Clients: not relevant
 - Browser: not relevant
 - Jellyfin Version: 10.6.4
 - Playback: not relevant
 - Installed Plugins: None
 - Reverse Proxy: Apache
 - Base URL: /
 - Networking: Private LAN, no NAT
 - Storage: local

**To Reproduce**

1. Setup a firewall with default outgoing policy DENY (I use [firehol](https://firehol.org/))
2. Install Jellyfin from Debian packages
3. Login as admin, go to `Administration > Dashboard > DLNA`, disable all DLNA related functionality
4. Watch server logs. Every minute the following messages are logged:

```
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 10.0.0.21 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 kernel: [  799.490885] [firehol]DROP UNMATCHED OUT-uIN= OUT=ens3 SRC=10.0.0.21 DST=239.255.255.250 LEN=174 TOS=0x00 PREC=0x00 TTL=4 ID=24389 DF PROTO=UDP SPT=52859 DPT=1900 LEN=154 
Mar  7 13:44:17 demo1 kernel: [  799.491549] [firehol]DROP UNMATCHED OUT-uIN= OUT=ens3 SRC=10.0.0.21 DST=239.255.255.250 LEN=174 TOS=0x00 PREC=0x00 TTL=4 ID=24390 DF PROTO=UDP SPT=35216 DPT=1900 LEN=154 
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 kernel: [  799.597375] [firehol]DROP UNMATCHED OUT-uIN= OUT=ens3 SRC=10.0.0.21 DST=239.255.255.250 LEN=174 TOS=0x00 PREC=0x00 TTL=4 ID=24407 DF PROTO=UDP SPT=52859 DPT=1900 LEN=154 
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 10.0.0.21 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 kernel: [  799.600556] [firehol]DROP UNMATCHED OUT-uIN= OUT=ens3 SRC=10.0.0.21 DST=239.255.255.250 LEN=174 TOS=0x00 PREC=0x00 TTL=4 ID=24408 DF PROTO=UDP SPT=35216 DPT=1900 LEN=154 
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]: [13:44:17] [ERR] Error sending socket message from 10.0.0.21 to 239.255.255.250:1900
Mar  7 13:44:17 demo1 jellyfin[593]: System.Net.Sockets.SocketException (13): Permission denied
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Mar  7 13:44:17 demo1 jellyfin[593]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 jellyfin[593]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
Mar  7 13:44:17 demo1 kernel: [  799.703121] [firehol]DROP UNMATCHED OUT-uIN= OUT=ens3 SRC=10.0.0.21 DST=239.255.255.250 LEN=174 TOS=0x00 PREC=0x00 TTL=4 ID=24422 DF PROTO=UDP SPT=52859 DPT=1900 LEN=154 
```

**Expected behavior**

Jellyfin should not send multicast/DLNA-related packets when DLNA is disabled in settings. Currently:
- multicast packets are sent over the network when no restrictive firewall is in place, possibly to untrusted networks (eg. VPS sharing the same LAN)
- when a restrictive firewall is in place, log spam

I don't know if those packets are sent for discovery of other DLNA devices, or to announce Jellyfin to other devices. Regardless this traffic should not be sent. Or is there another setting to disable DLNA/UPnP completely?

**Comment by cvium** [comment]
UPnP can already be disabled. DLNA can be disabled in 10.7.
![image](https://user-images.githubusercontent.com/675118/110241046-1536f800-7f4f-11eb-88fa-bf0a1a92080b.png)

**Comment by nodiscc** [comment]
@cvium As I said above it is disabled in my settings:

![image](https://user-images.githubusercontent.com/3950390/110241128-211ebc00-7f47-11eb-840c-adda81d914f7.png)

> DLNA can be disabled in 10.7.

Do you mean the checkbox is there in 10.6.4, but has no effect, and that it is fixed in 10.7?

**Comment by cvium** [comment]
The checkbox doesn't disable it completely in 10.6.

**Comment by nodiscc** [comment]
@cvium can this issue be reopened? The problem is still present on 10.7.2:

```bash
$ grep 'Error sending socket message' /var/log/syslog
.....
Apr 25 14:52:41 demo1 jellyfin[19065]: [14:52:41] [ERR] Error sending socket message from 10.0.0.21 to 239.255.255.250:1900
Apr 25 14:52:41 demo1 jellyfin[19065]: [14:52:41] [ERR] Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
Apr 25 14:52:41 demo1 jellyfin[19065]: [14:52:41] [ERR] Error sending socket message from 10.0.0.21 to 239.255.255.250:1900

$ apt policy jellyfin
jellyfin:
  Installed: 10.7.2-1
  Candidate: 10.7.2-1
  Version table:
 *** 10.7.2-1 500
        500 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

```

All DLNA-related settings are disabled `/web/index.html#!/dlnasettings.html`

**Comment by cvium** [comment]
Can you upload a screenshot of your settings?

**Comment by nodiscc** [comment]
> screenshot of your settings?

![image](https://user-images.githubusercontent.com/3950390/116006124-70a17000-a5f9-11eb-939e-7adfef096d1b.png)

> And have you disabled autodiscovery?

No. How? I can't find this setting in the web UI, am not sure how to proceed after rereading https://jellyfin.org/docs/general/administration/configuration.html. Should I modify `/etc/jellyfin/network.xml?` `/etc/jellyfin/system.xml`? Pass an environment variable on startup?

Thanks

**Comment by nodiscc** [comment]
Setting `<AutoDiscovery>false</AutoDiscovery>` in `/etc/jellyfin/network.xml` seems to fix the problem. Thanks
