### ISSUE TITLE
since 20210307.2-unstable jellyfin doesnt load the homescreen and is unable to play content

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5408]
**Describe the bug**
I just updated from 20210303.1-unstable to the latest unstable build (20210308.4-unstable) and my homescreen doesn't show up anymore.
I tried the unstable version just after 20210303.1 which is 20210307.2 and it also had this problem.
Going back to 20210303.1 makes jellyfin useable again.
the logs show a null reference error when trying to load the homescreen,I posted them down below.

In another issue I posted what my "latest Movies" URL looked like, and I just copied it and that shows up normally.
When clicking on the movies in the "Latest Movies" URL I get these errors and content doesn't play:
```
[10:27:17] [INF] [44] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[10:27:17] [INF] [44] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[10:27:17] [INF] [44] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```
I only have basic password authentication, no extras.

I have tried logging out and back in, even with different accounts, but nothing changed

**System (please complete the following information):**
 - OS: UnRaid
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Chrome
 - Jellyfin Version: since 20210307.2
 - Playback: -
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: Jellyfin.domain.com
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. Save the URL of a library so you can access it later
2. Update to latest unstable
3. Go to the homescreen
4. See that it doesn't load
5. go to the saved URL of your library
6. try to play a movie
7. See that it doesn't load and authentication errors in the logs

**Logs**
```
[10:15:51] [ERR] [16] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/a0ecedc672bc44e2b3e0ba9aa00c6246/Views.

System.NullReferenceException: Object reference not set to an instance of an object.
at Emby.Server.Implementations.Library.PathExtensions.TryReplaceSubPath(String path, String subPath, String newSubPath, String& newPath)
at Emby.Server.Implementations.Library.LibraryManager.GetPathAfterNetworkSubstitution(String path, BaseItem ownerItem)
at Emby.Server.Implementations.Dto.DtoService.GetMappedPath(BaseItem item, BaseItem ownerItem)
at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options)
at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
at Jellyfin.Api.Controllers.UserViewsController.<>c__DisplayClass6_0.<GetUserViews>b__0(Folder i)
at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
at lambda_method783(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9083045/110300662-6bf80c80-7ff7-11eb-82dd-704d93443c65.png)

**Comment by litris** [comment]
Final version 10.7.0 and same black screen problem both in IOS app

I used the default option at Ubuntu server to keep “config.json”

![0C8E5DFA-AC11-4284-A1D7-2B723812FBE8](https://user-images.githubusercontent.com/2809283/110435857-d1113800-80b3-11eb-9953-68a5ae30b867.png)
![FEA5DA51-691D-4797-9EDE-D94F119EA1B3](https://user-images.githubusercontent.com/2809283/110435863-d2426500-80b3-11eb-9304-81c9343560a0.jpeg)

and in Windows with firefox and on macos safari.

**Comment by ikomhoog** [comment]
This is now fixed in master
