### ISSUE TITLE
10.8.0 (current master) - Crash when trying to access server

### ISSUE THREAD

**Issue by atomheartother** [jellyfin/jellyfin#5432]
**Describe the bug**
After upgrading just now, trying to open my jellyfin server causes a series of errors, the server is stuck on loading forever. I've tried the Home screen and a library screen i had bookmarked, both fail.

**System (please complete the following information):**
 - OS: [Dockerized Ubuntu](https://docs.linuxserver.io/images/docker-jellyfin) (Ubuntu host).
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 86.0
 - Jellyfin Version: 10.8.0
 - Playback: None (I can't reach an item to play) 
 - Installed Plugins: None
 - Reverse Proxy: Traefik
 - Base URL: /
 - Networking: 
 - Storage:

**To Reproduce**
1. Upgrade to `1.8.0` from `1.7.0`
2. Open the jellyfin server
3. That's it, you're now stuck on a loading screen

**Expected behavior**
The server's content is displayed.

<details>
<summary>Logs</summary>

```
jellyfin    | [12:16:24] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/3d04089c13514690b0c56dd48effca2f/Items/1cb0956c20e8865d9ba81e596b121be2.
jellyfin    | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin    |    at Emby.Server.Implementations.Library.PathExtensions.TryReplaceSubPath(String path, String subPath, String newSubPath, String& newPath)
jellyfin    |    at Emby.Server.Implementations.Library.LibraryManager.GetPathAfterNetworkSubstitution(String path, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetMappedPath(BaseItem item, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
jellyfin    |    at lambda_method787(Closure , Object )
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfin    |    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin    |    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin    |    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
jellyfin    |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin    | [12:16:24] [ERR] [30] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/3d04089c13514690b0c56dd48effca2f/Views.
jellyfin    | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin    |    at Emby.Server.Implementations.Library.PathExtensions.TryReplaceSubPath(String path, String subPath, String newSubPath, String& newPath)
jellyfin    |    at Emby.Server.Implementations.Library.LibraryManager.GetPathAfterNetworkSubstitution(String path, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetMappedPath(BaseItem item, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.<>c__DisplayClass6_0.<GetUserViews>b__0(Folder i)
jellyfin    |    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
jellyfin    |    at lambda_method783(Closure , Object , Object[] )
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfin    |    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin    |    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin    |    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin    | [12:16:24] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
jellyfin    | [12:16:24] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
jellyfin    | [12:16:24] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
jellyfin    | [12:16:24] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
jellyfin    | [12:16:24] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
jellyfin    | [12:16:43] [INF] [30] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for Guest has succeeded.
jellyfin    | [12:16:43] [INF] [30] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user Guest: 0/0
jellyfin    | [12:16:43] [INF] [30] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 997580b2-4faf-4d9e-9713-b1206f75bada
jellyfin    | [12:16:44] [INF] [24] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 5.158.252.189 request
jellyfin    | [12:16:44] [ERR] [30] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/997580b24faf4d9e9713b1206f75bada/Views.
jellyfin    | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin    |    at Emby.Server.Implementations.Library.PathExtensions.TryReplaceSubPath(String path, String subPath, String newSubPath, String& newPath)
jellyfin    |    at Emby.Server.Implementations.Library.LibraryManager.GetPathAfterNetworkSubstitution(String path, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetMappedPath(BaseItem item, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.<>c__DisplayClass6_0.<GetUserViews>b__0(Folder i)
jellyfin    |    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
jellyfin    |    at lambda_method783(Closure , Object , Object[] )
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfin    |    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin    |    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin    |    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin    | [12:16:44] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/997580b24faf4d9e9713b1206f75bada/Views.
jellyfin    | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin    |    at Emby.Server.Implementations.Library.PathExtensions.TryReplaceSubPath(String path, String subPath, String newSubPath, String& newPath)
jellyfin    |    at Emby.Server.Implementations.Library.LibraryManager.GetPathAfterNetworkSubstitution(String path, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetMappedPath(BaseItem item, BaseItem ownerItem)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.<>c__DisplayClass6_0.<GetUserViews>b__0(Folder i)
jellyfin    |    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
jellyfin    |    at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
jellyfin    |    at lambda_method783(Closure , Object , Object[] )
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin    | --- End of stack trace from previous location ---
jellyfin    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfin    |    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin    |    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin    |    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin    |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin    |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
jellyfin    |    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

```
</details>

**Screenshots**
NaN

**Additional context**
This is an upgrade from a previous nightly build to this latest one. Going back to stable fixes this, so it is likely caused by whatever's changed between 10.7.0 and 10.8.0.

**Comment by cvium** [comment]
Duplicate https://github.com/jellyfin/jellyfin/issues/5408
