### ISSUE TITLE
Unable to update TV guide in 10.7.0 with TVHeadEnd 4.3.8-36

### ISSUE THREAD

**Issue by cooljimy84** [jellyfin/jellyfin#5436]
**Describe the bug**

Fresh install of Jellyfin 10.7.0 ubuntu 20.04 (as a container in proxmox) when trying the refresh guide data from my TVHeadEnd 4.2.8-36 i get errors about expected whitespace but got /

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: LXC
 - Clients: Browser
 - Browser: Firefox 86
 - Jellyfin Version: 10.7.0
 - Playback: N/A
 - Installed Plugins: TVHeadEnd
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridged eth0
 - Storage: local

**To Reproduce**

1. Go to 'Live TV'
2. Add TV Guide Data Providers (XMLTV)
3. enter http://user:12345@192.168.1.25:9981/xmltv/channels, and then click save
4. Click on 'Refresh TV Guide'
5. wait for progress bar
6. check logs for the error

**Expected behavior**
The TV guide to be updated

**Logs**
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1191\" tvg-id=\"23ad8375cb5a275e45e7876b1ff1aaec\",LBC News"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1141\" tvg-id=\"c24a256f8375ae50e28bc9b39c6d0232\",Browse Shop"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1142\" tvg-id=\"3fe6286e234580cd80c1c61f38c5ddab\",Reset your PIN"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1143\" tvg-id=\"498a1de871d7df26c5d299a87c0d0222\",My Account"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1144\" tvg-id=\"927a4280f804ba180ec4d479e01f3968\",Get Sky Products"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1145\" tvg-id=\"38b997936e9befae68617803f5e57f2b\",Help and Support"
[2021-03-09 12:14:03.892 +00:00] [INF] Found m3u channel: "-1 logo=\"http://192.168.1.25:9981/imagecache/1146\" tvg-id=\"dd48ed3e54fd827adbcc376d2ae6408d\",Program Your Remote"
[2021-03-09 12:14:03.910 +00:00] [INF] xmltv path: "http://user:12345@192.168.1.25:9981/xmltv/channels"
[2021-03-09 12:14:03.912 +00:00] [ERR] Error adding metadata
System.Xml.XmlException: '>' is an unexpected token. Expecting whitespace. Line 1, position 50.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(Int32 pos)
   at System.Xml.XmlTextReaderImpl.SkipDtd()
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Jellyfin.XmlTv.XmlTvReader.GetChannels()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)

**Screenshots**

**Additional context**

I have not included the full logs as the error just repeats for every channel.

**Comment by cooljimy84** [comment]
Just installed jellyfin-server_20210307.3-unstable_amd64.deb and jellyfin-web_20210307.3-unstable_all.deb reports as (10.8.0) and it seems to work fine.
