### ISSUE TITLE
No Web Interface after upgrading to 10.7.0-1

### ISSUE THREAD

**Issue by pravardhanreddy** [jellyfin/jellyfin#5440]
**Issue:**
I upgraded to jellyfin (10.7.0-1) and now I cannot view the web interface. I uninstalled everything related to jellyfin and then tried to reinstall but the problem persists.

**System:**
 - OS: Debian Buster
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.7.0-1
 - Base URL: none
 - Hardware: Rpi 4 (2GB)
 - Networking: on the same local network

**To Reproduce**

1. Install jellyfin from `deb [arch=armhf] https://repo.jellyfin.org/debian buster main` via `sudo apt install jellyfin`
2. Go to IP_ADDRESS:8096

**Expected behavior**
Should take me to the login page or the dashboard

**Logs**
`[2021-03-09 19:48:20.090 +05:30] [DBG] [23] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with "CustomAuthenticationHandler" MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()

[2021-03-09 19:48:20.118 +05:30] [DBG] [23] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.

[2021-03-09 19:48:20.848 +05:30] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.29.10:8096/dlna/42ce5b9607d6416fa3dac18c8415a434/description.xml" to "192.168.29.10" in 0:00:00.8226185 with Status Code 200`

**Screenshots**

[What I see](https://imgur.com/Qmcc4eG)

**Additional context**

The jellyfin logo briefly appears and then I get the above screen. Every time I hit a refresh I get the same logs. I tried clearing all cookies and tried incognito as well.

**Comment by crobibero** [comment]
See the following issues:
https://github.com/jellyfin/jellyfin-web/issues/2494
https://github.com/jellyfin/jellyfin-web/issues/2493
