### ISSUE TITLE
[10.7.0] Unable to login: Error authenticating with "CustomAuthenticationHandler"

### ISSUE THREAD

**Issue by Larvitar** [jellyfin/jellyfin#5443]
**Describe the bug**
After updating straight from 10.6.4 to 10.7.0 I'm unable to login from any client (web / android). WebGUI starts empty either from an already logged in browser or in private mode.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: None
 - Clients: Android / WEB
 - Browser: Android / Brave
 - Jellyfin Version: 10.7.0
 - Reverse Proxy: nginx

**To Reproduce**
Update from 10.6.4 to 10.7.0

**Logs**
```
[2021-03-09 16:46:13.865 +01:00] [DBG] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with "CustomAuthenticationHandler"
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[2021-03-09 16:46:13.865 +01:00] [DBG] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2021-03-09 16:46:13.866 +01:00] [DBG] [34] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[2021-03-09 16:46:13.866 +01:00] [DBG] [34] Jellyfin.Networking.Manager.NetworkManager: "192.168.1.1/32": GetBindInterface: Has source, matched best internal interface on range. "192.168.1.80"
```

**Additional context**
It does work with locally hosted VUE client for some reason.

**Comment by Larvitar** [comment]
Eh, nevermind. I clicked not to replace `/usr/share/jellyfin/web/config.json` during update. Works fine after manually updating although error logs from `CustomAuthenticationHandler` still occur.
