### ISSUE TITLE
Jellyfin 10.7.0 not start before upgrade

### ISSUE THREAD

**Issue by Teutates3000** [jellyfin/jellyfin#5445]
Hello, 

I have Jellyfin installed on my NAS in Debian 10.8 (OMV 5.6.2-1) since several years and I upgrade versions simply with :
apt-get update
apt-get upgrade

so far all the version changes went very well but for this version 10.7.0, I encounter the following error in the logs and I don't have access to the Jellyfin web interface anymore.
Here is what I have in my jellyfin20210309.log :
```
2021-03-09 14:30:10.903 +01:00] [ERR] An error occurred while reading the key ring.
System.Xml.XmlException: Invalid character in the given encoding. Line 2, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.EatWhitespaces(StringBuilder sb)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList [TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService.StartAsync(CancellationToken token)
2021-03-09 14:30:10.942 +01:00] [INF] Running startup tasks
2021-03-09 14:30:10.944 +01:00] [INF] TaskCleanDb Loaded
```

I tried to check my configuration files but nothing has changed for a while.

Thanks

**Comment by Tanfav** [comment]
I had the exact same behavior (debian 10)
I have fully un-installed and install it back.. same issue : no access to web interface...

**Comment by barukh27** [comment]
Hi there!

Have a look at: https://github.com/jellyfin/jellyfin/issues/5442

**Comment by Teutates3000** [comment]
I've just tried the manipulation and the interface seems to be back but I don't have any "Play" button anymore and it's impossible to play the videos.

**Comment by sum01** [comment]
@Teutates3000 I had that issue when I tried to use the config from Github.
Doing this https://github.com/jellyfin/jellyfin-web/issues/2493#issuecomment-793230115 worked for me.

**Comment by Teutates3000** [comment]
I had already deleted the "web" folder of /usr/share/jellyfin/ and reinstalled the package "jellyfin-web_10.7.0-1_all.deb" but I had no config.json file or config.json.dpkg-dist but by using this one : 
[https://raw.githubusercontent.com/jellyfin/jellyfin-web/master/src/config.json](https://raw.githubusercontent.com/jellyfin/jellyfin-web/master/src/config.json) 
and by making a "`dos2unix config.json`" I finally made everything work again.

Thanks a lot
