### ISSUE TITLE
MigrateDisplayPreferencesDb.cs Fails to migrate

### ISSUE THREAD

**Issue by drixtol** [jellyfin/jellyfin#5473]
**Describe the bug**
When loading up 10.7 for the first time it fails on this migration. It proceeds to shutdown jellyfin and will have the same effect each time. 

**System (please complete the following information):**
 - OS: Windows 10
 - Jellyfin Version: 10.6.4 > 10.7 | Manual install

**To Reproduce**

Take 10.6.4 install and apply 10.7 files on top
Start Jellyfin 
Watch log and wait for errors

**Expected behavior**
Migration to occur

**Logs**
[2021-03-10 09:52:01.167 -08:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"MigrateDisplayPreferencesDatabase"'
[2021-03-10 09:52:01.359 -08:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"MigrateDisplayPreferencesDatabase"'
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: CustomItemDisplayPreferences.UserId, CustomItemDisplayPreferences.ItemId, CustomItemDisplayPreferences.Client, CustomItemDisplayPreferences.Key'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-03-10 09:52:01.411 -08:00] [FTL] [1] Main: Error while starting server.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: CustomItemDisplayPreferences.UserId, CustomItemDisplayPreferences.ItemId, CustomItemDisplayPreferences.Client, CustomItemDisplayPreferences.Key'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2021-03-10 09:52:01.418 -08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2021-03-10 09:52:01.419 -08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2021-03-10 09:52:01.421 -08:00] [INF] [2] Main: Received a SIGTERM signal, shutting down

**Additional context**
Database values (some of the json trimmed/truncated to remove PII and cut extraneous data)
Blob values werent pretty, so only including generic numbers for help identifying constraint issues

id | userId | client | data
-- | -- | -- | --
1 | 1 | ATV | {"Id":"b5627eae",CUT"Client":"ATV"}
2 | 1 | ATV | {"Id":"e2f6536",CUT"Client":"ATV"}
3 | 2 | emby | {"Id":"3ce5bc",CUT,"Client":"emby"}
3 | 1 | emby | {"Id":"3ce5bc",CUT,"Client":"emby"}

I tried removing a couple combinations of these rows and running migration again and it always seems to find issue. I'm decent with sql but CS is out of my league for debugging which values its finding issues with. 

I succeeded in migration by removing all rows. 

When deleted - log
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateDisplayPreferencesDatabase'
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration 'MigrateDisplayPreferencesDatabase' applied successfully

**Comment by rchovan** [comment]
Same issue, after upgrade from 10.6.4 to 10.7.1
```
[2021-04-10 00:00:52.842 +02:00] [INF] [1] Main: Jellyfin version: "10.7.1"                                                                                                                                
[2021-04-10 00:00:52.919 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_FFMPEG, /
usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_MEDIA_DIR, /media]"]                
[2021-04-10 00:00:52.939 +02:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]                                                                                                                     
[2021-04-10 00:00:52.941 +02:00] [INF] [1] Main: Operating system: "Linux"                                                                                                                                 
[2021-04-10 00:00:52.949 +02:00] [INF] [1] Main: Architecture: X64                                                                                                                                         
[2021-04-10 00:00:52.950 +02:00] [INF] [1] Main: 64-Bit Process: True                                                                                                                                      
[2021-04-10 00:00:52.950 +02:00] [INF] [1] Main: User Interactive: True                                                                                                                                    
[2021-04-10 00:00:52.950 +02:00] [INF] [1] Main: Processor count: 2                                                                                                                                        
[2021-04-10 00:00:52.951 +02:00] [INF] [1] Main: Program data path: "/config"                                                                                                                              
[2021-04-10 00:00:52.951 +02:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"                                                                                                              
[2021-04-10 00:00:52.951 +02:00] [INF] [1] Main: Application directory: "/jellyfin/"                                                                                                                       
[2021-04-10 00:00:53.573 +02:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"                                                                      
[2021-04-10 00:00:53.692 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[192.168.2.0/24,127.0.0.1/8]"                                                              
[2021-04-10 00:00:53.692 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"                                                                                       
[2021-04-10 00:00:53.696 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[192.168.2.0/24,127.0.0.1/8]"                                                                 
[2021-04-10 00:00:53.703 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"                                                                                          
[2021-04-10 00:00:53.703 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"                                                                                         
[2021-04-10 00:00:53.821 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies                                                                                                 
[2021-04-10 00:00:53.849 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "8.0.0.0" of "Auto Organize"                                                        
[2021-04-10 00:00:53.852 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "6.0.0.0" of "IPTV"                                                                 
[2021-04-10 00:00:53.852 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "9.0.0.0" of "Open Subtitles"                                                       
[2021-04-10 00:01:10.376 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.7.1.0"                                                                             
[2021-04-10 00:01:10.378 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.7.1.0"                                                                      
[2021-04-10 00:01:10.379 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.7.1.0"                                                                          
[2021-04-10 00:01:10.561 +02:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"MigrateDisplayPreferencesDatabase"'                                                            
[2021-04-10 00:01:10.896 +02:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"MigrateDisplayPreferencesDatabase"'                                                     
System.FormatException: Input string was not in a correct format.                                                                                                                                          
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)                                                                                                                    
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()                                                                                                                            
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)                                                                                                       
[2021-04-10 00:01:10.902 +02:00] [FTL] [1] Main: Error while starting server.                                                                                                                              
System.FormatException: Input string was not in a correct format.                                                                                                                                          
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)                                                                                                                    
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()                                                                                                                            
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)                                                                                                       
   at Jellyfin.Server.Program.StartApp(StartupOptions options)                                                                                                                                             
[2021-04-10 00:01:10.910 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"                                                                                            
[2021-04-10 00:01:10.913 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"                                                                                                 
[2021-04-10 00:01:10.917 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down                                                                                                                  
[2021-04-10 00:01:11.924 +02:00] [INF] [1] Main: Jellyfin version: "10.7.1"                                                                                                                                
[2021-04-10 00:01:11.983 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFI
N_DATA_DIR, /config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_CONFIG_DIR, /config/config]"]                
[2021-04-10 00:01:11.987 +02:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]                                                                                                                     
[2021-04-10 00:01:11.988 +02:00] [INF] [1] Main: Operating system: "Linux"                                                                                                                                 
[2021-04-10 00:01:11.989 +02:00] [INF] [1] Main: Architecture: X64                                                                                                                                         
[2021-04-10 00:01:11.997 +02:00] [INF] [1] Main: 64-Bit Process: True                                        
```

**Comment by rchovan** [comment]
Attaching displaypreferences.db with journal file. 
[jlf.zip](https://github.com/jellyfin/jellyfin/files/6299325/jlf.zip)
