### ISSUE TITLE
AddPeopleQueryIndex.cs fails - indexes already exist

### ISSUE THREAD

**Issue by drixtol** [jellyfin/jellyfin#5474]
**Describe the bug**
When the migration script runs to create the indexes it fails because they already exist

**System (please complete the following information):**
 - OS: Windows 10
 - Jellyfin Version:  10.6.4 > 10.7 (No RC clients installed)

**To Reproduce**
Take 10.6.4 install and apply 10.7 files on top
Start Jellyfin
Watch log and wait for errors

**Expected behavior**
Migration Occurs

**Logs**

```
[10:12:36] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddPeopleQueryIndex'
[10:12:36] [INF] [1] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[10:12:36] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'AddPeopleQueryIndex'
Error: SQLitePCL.pretty.SQLiteException: index idx_TypedBaseItemsUserDataKeyType already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[10:12:36] [FTL] [1] Main: Error while starting server.
Error: SQLitePCL.pretty.SQLiteException: index idx_TypedBaseItemsUserDataKeyType already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[10:12:36] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[10:12:36] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[10:12:36] [INF] [2] Main: Received a SIGTERM signal, shutting down

Error: SQLitePCL.pretty.SQLiteException: index idx_PeopleNameListOrder already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[10:14:37] [FTL] [1] Main: Error while starting server.
Error: SQLitePCL.pretty.SQLiteException: index idx_PeopleNameListOrder already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Screenshots**
This is the structure that exists before running the upgrade
![image](https://user-images.githubusercontent.com/20601906/110677335-e8baf000-8189-11eb-9c6a-763226b7e920.png)

**Additional context**
If i delete the indexes from the 10.6.4 database and run the upgrade it proceeds without issue. 

```
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddPeopleQueryIndex'
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_PeopleNameListOrder
[10:22:31] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddPeopleQueryIndex' applied successfully
```

**Comment by tanfav2** [comment]
Hello,

Same issue here, upgrade 10.7.0 to 10.7.1 (installed on a debian, but whatever...)

logs:
[2021-03-22 10:43:38.288 +01:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"AddPeopleQueryIndex"'
[2021-03-22 10:43:38.289 +01:00] [INF] [1] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[2021-03-22 10:43:38.290 +01:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"AddPeopleQueryIndex"'
Error: SQLitePCL.pretty.SQLiteException: index idx_TypedBaseItemsUserDataKeyType already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[2021-03-22 10:43:38.295 +01:00] [FTL] [1] Main: Error while starting server.
Error: SQLitePCL.pretty.SQLiteException: index idx_TypedBaseItemsUserDataKeyType already exists
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

**Comment by tanfav2** [comment]
Well, despite my effort, i'm unable to connect to JellyFin database to remove those index (i'm on a debian system, and i don't found any procedure to connect to the jellyfin database from cli...)
so, i'm stuck... i would either need a fix (i mean, an updated version that handle correctly the upgrade process, and mainly this db issue...) or some guidance to connect to jellyfin db on a linux system...

**Comment by Tanfav** [comment]
Well, never better served than by yourself...
if someone have the same issue:
I had to install SQlite3..
Then open /var/lib/jellyfin/data/library.db, and DROP INDEX idx_TypedBaseItemsUserDataKeyType; as explained by Drixtol (thx !!)
If the db is locked, simply copy/paste ....
a reboot, and everything runs fine...

**Comment by cvium** [comment]
I don't understand how this happened. The migrations are only run once. Did you remove the `migrations.xml` file or something?

**Comment by Tanfav** [comment]
Hi,  nothing done, really.
I simply updated using apt-get update / dist-upgrade
Didn't touch anything else .... 
hmm, except that 2 weeks ago, for migration to 10.7.0, i had to manually re-install the webserver files as described here:
https://github.com/jellyfin/jellyfin/issues/5511#issuecomment-798487305
but it doesn't seem related...

**Comment by drixtol** [comment]
My upgrade path has always been to dump the latest release on top of the older one; use the server/web file zip folder. There shouldnt any removal of files at all from what i did.

**Comment by andrewzah** [comment]
Same issue for me. Updated through apt, and this error pops up even if I manually drop idx_TypedBaseItemsUserDataKeyType.

**Comment by cvium** [comment]
Can you upload your migrations.xml file?

**Comment by andrewzah** [comment]
$ cat /etc/jellyfin/migrations.xml 
<?xml version="1.0" encoding="utf-8"?>
<MigrationOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Applied>
    <ValueTupleOfGuidString>
      <Item1>4124c2cd-e939-4ffb-9be9-9b311c413638</Item1>
      <Item2>DisableTranscodingThrottling</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>ef103419-8451-40d8-9f34-d1a8e93a1679</Item1>
      <Item2>CreateLoggingConfigHeirarchy</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>3793eb59-bc8c-456c-8b9f-bd5a62a42978</Item1>
      <Item2>MigrateActivityLogDatabase</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>acbe17b7-8435-4a83-8b64-6fcf162cb9bd</Item1>
      <Item2>RemoveDuplicateExtras</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>5c4b82a2-f053-4009-bd05-b6fcad82f14c</Item1>
      <Item2>MigrateUserDatabase</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>eb58ebee-9514-4b9b-8225-12e1a40020df</Item1>
      <Item2>AddDefaultPluginRepository</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>5f86e7f6-d966-4c77-849d-7a7b40b68c4e</Item1>
      <Item2>ReaddDefaultPluginRepository</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>06387815-c3cc-421f-a888-fb5f9992bea8</Item1>
      <Item2>MigrateDisplayPreferencesDatabase</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>a81f75e0-8f43-416f-a5e8-516ccab4d8cc</Item1>
      <Item2>RemoveDownloadImagesInAdvance</Item2>
    </ValueTupleOfGuidString>
    <ValueTupleOfGuidString>
      <Item1>de009b59-baae-428d-a810-f67762dc05b8</Item1>
      <Item2>AddPeopleQueryIndex</Item2>
    </ValueTupleOfGuidString>
  </Applied>

**Comment by cvium** [comment]
@andrewzah is that before or after you removed the indexes?

**Comment by andrewzah** [comment]
After.

**Comment by cvium** [comment]
Dang. I need a pre-fix migrations.xml
