### ISSUE TITLE
unable to load ssl certificate on 10.7.0 (password error but password correct)

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#5494]
**Describe the bug**
Since my uprade to 10.7.0 my PFX cert wont load causing no https access to my instance

**System (please complete the following information):**
 - OS: debian
 - Virtualization: docker
 - Jellyfin Version: 10.7.0
 - Reverse Proxy: none
 - Base URL: nas.domain.tld
 - Networking: bridge

**To Reproduce**

1: create a PFX certificate with an easy password to make no mistakes
2. load it in jellyfin
3. reboot to make sure it's loaded (or at lease tried to)

**Expected behavior**
The certificate is loaded correctly and 'm enjoying safe browsing on my local network :-)

**Logs**
```
[2021-03-11 20:18:03.900 +01:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading cert from "/config/config/cert/cert.pfx"
System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: A certificate referenced a private key which was already referenced, or could not be loaded.
   at Internal.Cryptography.Pal.UnixPkcs12Reader.BuildCertsWithKeys(CertBagAsn[] certBags, AttributeAsn[][] certBagAttrs, CertAndKey[] certs, Int32 certBagIdx, SafeBagAsn[] keyBags, RentedSubjectPublicKeyInfo[] publicKeyInfos, AsymmetricAlgorithm[] keys, Int32 keyBagIdx)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Emby.Server.Implementations.ApplicationHost.GetCertificate(CertificateInfo info)

```

**Additional context**
Yeah, i know - the error says incorrect password but:
1:It was working fine with previous stable version
2: i tried to recreate the pfx with another password and adapting config accordingly without success
3: exported the PFX and loaded it in sslhopper - was able to open it with the supplied password.

My guess is that there's something wrong in the way jellyfin get or/and use the PFX password.

Thanks for the great work for this update indeed !

Regards - JS

**Comment by BaronGreenback** [comment]
Does this help, it seems to be a .NET 5 change? 

https://github.com/dotnet/runtime/issues/44535

**Comment by antipiot** [comment]
> 
> 
> Does this help, it seems to be a .NET 5 change?
> 
> [dotnet/runtime#44535](https://github.com/dotnet/runtime/issues/44535)

You're the man! Many thanks! found my solution in there:
i was generating my pfx using: 
`openssl pkcs12 -export -passout pass:hackme -out /etc/ssl/imported/cert.pfx -inkey /etc/ssl/imported/private.key -in /etc/ssl/imported/cert.crt -certfile /etc/ssl/imported/cert.crt`
as explained in your link - changed for:
`openssl pkcs12 -export -passout pass:hackme-out /etc/ssl/imported/cert.pfx -inkey /etc/ssl/imported/private.key -in /etc/ssl/imported/cert.crt
`
Loaded the cert again - rebooted jellyfin - and ssl fired up !
Regards
