### ISSUE TITLE
My jellyfin service fail to startup after update 10.7.0 via apt

### ISSUE THREAD

**Issue by byteword** [jellyfin/jellyfin#5545]
**Describe the bug**
My jellyfin service on Ubuntu system has been fail to startup after update.
I did update today using command "apt full-upgrade" and it ended with successfully.
While updating, I choose Yes for update migrated configuration.

Error occured with network initailise and it is a not handled exception about index in collection.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-33-generic x86_64)
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.7.0 with apt ( deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main )
 - Playback: N/A
 - Installed Plugins: 
 - Reverse Proxy:  Apache
 - Base URL: /jellyfin
 - Networking: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15) ( 192.168../24 ) / Wireless lan without configured ( Intel Corporation Dual Band Wireless-AC 3168NGW [Stone Peak] (rev 10))
 - Storage: SSD for system, HDD for media
 - APU :  [AMD] Ryzen PRO 4650G
 - VGA support : amdgpu-pro

**Expected behavior**
It installed on my linux system and worked well.
I'm using systemd to start the service automatically.

**Logs**

 - log with just remove my informations with *
== log ==
[2021-03-15 23:56:28.887 +09:00] [INF] Jellyfin version: "10.7.0"
[2021-03-15 23:56:28.901 +09:00] [INF] Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_USER, jellyfin]"]
[2021-03-15 23:56:28.903 +09:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2021-03-15 23:56:28.904 +09:00] [INF] Operating system: "Linux"
[2021-03-15 23:56:28.904 +09:00] [INF] Architecture: X64
[2021-03-15 23:56:28.904 +09:00] [INF] 64-Bit Process: True
[2021-03-15 23:56:28.904 +09:00] [INF] User Interactive: True
[2021-03-15 23:56:28.904 +09:00] [INF] Processor count: 12
[2021-03-15 23:56:28.904 +09:00] [INF] Program data path: "/var/lib/jellyfin"
[2021-03-15 23:56:28.904 +09:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2021-03-15 23:56:28.904 +09:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2021-03-15 23:56:29.018 +09:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2021-03-15 23:56:29.040 +09:00] [DBG] Refreshing interfaces.
[2021-03-15 23:56:29.044 +09:00] [DBG] Discovered 1 interfaces.
[2021-03-15 23:56:29.044 +09:00] [DBG] Interfaces addresses : "[192.168.***.***/24]"
[2021-03-15 23:56:29.045 +09:00] [DBG] Refreshing LAN information.
[2021-03-15 23:56:29.049 +09:00] [FTL] Unhandled Exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Common.Net.IPObject.NetworkAddressOf(IPAddress address, Byte prefixLength)
   at MediaBrowser.Common.Net.IPNetAddress.CalculateNetworkAddress()
   at MediaBrowser.Common.Net.IPObject.get_NetworkAddress()
   at MediaBrowser.Common.Net.IPNetAddress.Contains(IPObject address)
   at MediaBrowser.Common.Net.NetworkExtensions.ContainsAddress(Collection`1 source, IPObject item)
   at MediaBrowser.Common.Net.NetworkExtensions.AddItem(Collection`1 source, IPObject item)
   at Jellyfin.Networking.Manager.NetworkManager.InitialiseLAN(NetworkConfiguration config)
   at Jellyfin.Networking.Manager.NetworkManager.UpdateSettings(Object configuration)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
========

**Comment by byteword** [comment]
I solved the problem.
I think It occured because of LocalNetworkSubnets in Network.xml

I just remove a line : "<string>192.168.1.1/255</string>".
Its obviously wrong value becuase of the network mask.

**Comment by BaronGreenback** [comment]
still shouldn't have crashed - but removed the ip address with a warning. I'll fix it.

**Comment by sevenrats** [comment]
this stale issue references an old version. please open a new issue if you experience this.
