### ISSUE TITLE
Jellyfin not starting - DLNA Error

### ISSUE THREAD

**Issue by JopoJP** [jellyfin/jellyfin#5560]
**Describe the bug**
Jellyfin 10.7.0 final is not cleaning transcode directory, leading to gigabytes of accumulate data that must be cleared daily.

**System (please complete the following information):**

OS: Windows 10 Home
Virtualization: NO
Clients: ALL
Browser: ALL
Jellyfin Version: 10.7.0
Playback: ALL
Installed Plugins: default
Reverse Proxy: nginx
Base URL: none
Networking: host
Storage: local
To Reproduce: Have many DLNA Devices

**Expected behavior**
Jellyfin won't boot.

[18:01:57] [INF] [1] Main: Jellyfin version: 10.7.0
[18:01:58] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\\ProgramData\\Jellyfin\\Server\\log]"]
[18:01:58] [INF] [1] Main: Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll", "--datadir", "C:\\ProgramData\\Jellyfin\\Server"]
[18:01:58] [INF] [1] Main: Operating system: Windows
[18:01:58] [INF] [1] Main: Architecture: X64
[18:01:58] [INF] [1] Main: 64-Bit Process: True
[18:01:58] [INF] [1] Main: User Interactive: True
[18:01:58] [INF] [1] Main: Processor count: 4
[18:01:58] [INF] [1] Main: Program data path: C:\ProgramData\Jellyfin\Server
[18:01:58] [INF] [1] Main: Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[18:01:58] [INF] [1] Main: Application directory: C:\Program Files\Jellyfin\Server\
[18:01:58] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: C:\ProgramData\Jellyfin\Server\cache
[18:01:58] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[18:01:58] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[18:01:58] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[18:01:58] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[18:01:58] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[18:01:59] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[18:02:02] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.0.0
[18:02:02] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.0.0
[18:02:02] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.0.0
[18:02:03] [INF] [1] Main: Kestrel listening on Any IP4 Address
[18:02:04] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[18:02:04] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 03/18/2021 02:00, which is 7:57:55.8680533 from now.
[18:02:04] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1
[18:02:04] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[18:02:04] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[18:02:04] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[18:02:04] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[18:02:04] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 57e109b8784b4c26bc1317ec582d9767
[18:02:05] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.178.32/24
[18:02:05] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.3394528
[18:02:05] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[18:02:05] [INF] [1] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Starting NAT discovery
[18:02:05] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.54604
[18:02:05] [INF] [1] Main: Startup complete 0:00:08.3066268
[18:02:07] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[18:02:07] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[18:02:07] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[18:02:08] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
[18:02:08] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[18:02:11] [INF] [24] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
FriendlyName:192.168.178.43 - SYMFONISK Bookshelf Wohnzimmer
Manufacturer:Sonos, Inc.
ManufacturerUrl:http://www.sonos.com
ModelDescription:SYMFONISK Bookshelf
ModelName:SYMFONISK Bookshelf
ModelNumber:S21
ModelUrl:http://www.sonos.com/products/zoneplayers/S21
SerialNumber:

[18:02:11] [INF] [24] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for 192.168.178.43 - SYMFONISK Bookshelf Wohnzimmer - SYMFONISK Bookshelf
[18:02:11] [INF] [5] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
FriendlyName:192.168.178.66 - SYMFONISK Table lamp Musikzimmer
Manufacturer:Sonos, Inc.
ManufacturerUrl:http://www.sonos.com
ModelDescription:SYMFONISK Table lamp
ModelName:SYMFONISK Table lamp
ModelNumber:S20
ModelUrl:http://www.sonos.com/products/zoneplayers/S20
SerialNumber:

[18:02:11] [INF] [5] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for 192.168.178.66 - SYMFONISK Table lamp Musikzimmer - SYMFONISK Table lamp
[18:02:15] [INF] [5] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
FriendlyName:Nikolas TV
Manufacturer:TCL
ManufacturerUrl:http://www.tcl.com
ModelDescription:Media Renderer device
ModelName:DMR
ModelNumber:001
ModelUrl:http://www.tcl.com
SerialNumber:001

[18:02:15] [INF] [5] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for Nikolas TV - DMR
[18:02:17] [ERR] [24] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for Nikolas TV
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)

**Comment by BaronGreenback** [comment]
Can you test #5596 ?
