### ISSUE TITLE
Docker image won't update plugins

### ISSUE THREAD

**Issue by burny0202** [jellyfin/jellyfin#5563]
I get an error like this when trying to update plugin versions. 
Old versions do install; 
I can also manually download the .dll & json and place them in the plugin folder; though they are not detected correctly.

Tried with sync queue, TVHeadEnd, TheTVDB.

Tried with new config/cache. I am using the latest docker image

`[2021-03-18 14:38:21.440 +00:00] [ERR] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://server:8096/Packages/Installed/TheTVDB?AssemblyGuid=a677c0da-fac5-4cde-941a-7134223f14c8&version=3.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: TheTVDB
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
`

**Comment by crobibero** [comment]
This sounds like a duplicate of https://github.com/jellyfin/jellyfin/issues/4688, but since you didn’t provide the version of Jellyfin that you’re running we can’t be sure.

**Comment by burny0202** [comment]
Version is 10.6.4

**Comment by dkanada** [comment]
It is indeed a duplicate of #4688 and we probably won't be fixing it on that server version.

**Comment by burny0202** [comment]
Great; Thanks for the swift replies. I'll just grab the latest docker image when available
