### ISSUE TITLE
after upgraded to 10.7.0, failed to load web console

### ISSUE THREAD

**Issue by francis707** [jellyfin/jellyfin#5567]
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Clients: Browser
 - Browser: Firefox 86.0.1 (64-bit)
 - Jellyfin Version: 10.7.0
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. right click jellyfin tray icon, choose "stop jellyfin"
2. double click "jellyfin_10.7.0_windows-x64.exe" to upgrade to 10.7.0 from 10.6.4
3. right click jellyfin tray icon, found jellyfin is started, and choose "open jellyfin"
4. http://localhost:8096/web/index.html#!/home.html opened
5. but it's loading forever, open left sidebar, all libraries are gone, and click user icon, choose "profile" to open profile page, it's empty too
6. restart jellyfin server, still the same

**Expected behavior**
Jellyfin should open with all the data before upgrade.

**Logs**
```
[2021-03-19 11:57:53.235 +08:00] [ERR] [75] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/28921b40aeae4147839b3066f13552e1/Views".
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
   at lambda_method52(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2021-03-19 11:57:53.235 +08:00] [INF] [77] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-03-19 11:59:34.470 +08:00] [INF] [105] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-03-19 11:59:34.473 +08:00] [INF] [105] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2021-03-19 11:59:34.475 +08:00] [WRN] [105] Emby.Server.Implementations.Session.SessionWebSocketListener: Unable to determine session based on query string: ["[api_key, 7ea513fb934b47358fg029d23a2c8c13]", "[deviceId, TW96aWewYS81LjAgKFdxxxRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODUuMCkhR2Vja67vMjAxMDAxMDEgRmlyZWZveC84NS4wfDE2MTQ3Nzg2MTI5NTE1]"]
[2021-03-19 12:07:10.962 +08:00] [INF] [179] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-03-19 12:07:10.963 +08:00] [INF] [179] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-03-19 12:07:10.965 +08:00] [INF] [179] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
```

**Screenshots**
![20210319120735](https://user-images.githubusercontent.com/35424113/111730763-0afcee00-88ad-11eb-94da-9917ea74332c.png)
![20210319121435](https://user-images.githubusercontent.com/35424113/111730768-0e907500-88ad-11eb-99c1-eadc3a292388.png)

**Additional context**

**Comment by crobibero** [comment]
Have you tried opening Jellyfin in incognito/private browsing?

**Comment by francis707** [comment]
@crobibero 
After uninstalled 10.7.0, I found an old data folder in `C:\ProgramData\Jellyfin\` , probably generated by previous installation, my current data folder is in `E:\ProgramData\Jellyfin`, and I deleted this old data folder.
then I tried to reproduce the problem(install 10.6.4 -> add a small library(only 10 movies) -> upgrade to 10.7.0), but this time the homepage loads normally, with no login needed, only a bit slower than before, then I deleted all "localhost" cookies and logged in, the home page loads much quicker now.
