### ISSUE TITLE
HDhome tv broken in 10.7

### ISSUE THREAD

**Issue by redshift2** [jellyfin/jellyfin#5568]
The hdhomerun no longer functions in jellyfin 10.7. I tried deleting the setup and starting from begining. Jellyfin creates the folder with JPEG and nfo file. However it does not save the steam. Here is a cut from the log. 
Ubuntu sever running native jellyfin. Everything worked great in 10.6

`[2021-03-18 22:38:41.721 -04:00] [INF] Beginning recording. Will record for "23.304639851666668" minutes.
[2021-03-18 22:38:41.721 -04:00] [INF] Writing file to path: /var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1/Clarice S01E02 Ghosts of Highway 20.ts
[2021-03-18 22:38:41.730 -04:00] [INF] Triggering refresh on "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1/Clarice S01E02 Ghosts of Highway 20.ts"
[2021-03-18 22:38:41.731 -04:00] [INF] Refreshing recording parent "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1"
[2021-03-18 22:38:41.731 -04:00] [INF] Copying recording stream to file "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1/Clarice S01E02 Ghosts of Highway 20.ts"
[2021-03-18 22:38:41.731 -04:00] [ERR] Error recording to "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1/Clarice S01E02 Ghosts of Highway 20.ts"
System.IO.IOException: The process cannot access the file '/mnt/docker/Jellyfin/transcode/058f83dee168499dbe2e98329fd3fb33.ts' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.GetInputStream(String path, Boolean allowAsyncFileRead)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyFile(String path, Boolean seekFile, Int32 emptyReadLimit, Boolean allowAsync, Stream stream, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyToAsync(Stream stream, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.DirectRecorder.RecordFromDirectStreamProvider(IDirectStreamProvider directStreamProvider, String targetFile, TimeSpan duration, Action onStarted, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo)
[2021-03-18 22:38:41.731 -04:00] [INF] Live stream "native_b23ebc9442ec90ed5f591ef1683972b1_81ee80d68af0dd10b2eca270e1956101" consumer count is now 1
[2021-03-18 22:38:41.731 -04:00] [INF] Triggering refresh on "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1/Clarice S01E02 Ghosts of Highway 20.ts"
[2021-03-18 22:38:41.732 -04:00] [INF] Refreshing recording parent "/var/lib/jellyfin/data/livetv/recordings/Clarice/Season 1"
`

**Comment by cvium** [comment]
Please use the search function(s).

https://github.com/jellyfin/jellyfin/issues?q=is%3Aissue+sort%3Aupdated-desc+live+tv+is%3Aclosed
