### ISSUE TITLE
Jellyfin 10.7 crashes on startup if it can't access /proc/net/route

### ISSUE THREAD

**Issue by uumas** [jellyfin/jellyfin#5571]
**Describe the bug**
If the user isn't allowed to read `/proc/net/route`, jellyfin crashes on startup. This didn't happen with 10.6.4

**System (please complete the following information):**
 - OS: Linux x86_64
 - Jellyfin Version: 10.7.0, also occurs on 10.7.0~rc1

**To Reproduce**
1. Don't be root
1. `# chmod o-r /proc/net/route` (well, be root for this)
1. Try to start jellyfin
1. Get an error

**Logs**
```
uumas@oreo ~/jellyfin> jellyfin-server_10.7.0/jellyfin --nowebclient
[17:33:32] [INF] [1] Main: Jellyfin version: 10.7.0
[17:33:32] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/uumas/.local/share/jellyfin/log]"]
[17:33:32] [INF] [1] Main: Arguments: ["/home/uumas/jellyfin/jellyfin-server_10.7.0/jellyfin.dll", "--nowebclient"]
[17:33:32] [INF] [1] Main: Operating system: Linux
[17:33:32] [INF] [1] Main: Architecture: X64
[17:33:32] [INF] [1] Main: 64-Bit Process: True
[17:33:32] [INF] [1] Main: User Interactive: True
[17:33:32] [INF] [1] Main: Processor count: 4
[17:33:32] [INF] [1] Main: Program data path: /home/uumas/.local/share/jellyfin
[17:33:32] [INF] [1] Main: Web resources path: /home/uumas/jellyfin/jellyfin-server_10.7.0/jellyfin-web
[17:33:32] [INF] [1] Main: Application directory: /home/uumas/jellyfin/jellyfin-server_10.7.0/
[17:33:32] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/uumas/.cache/jellyfin
[17:33:32] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path '/proc/net/route' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.LinuxNetworkInterfaceSystemProperties..ctor()
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at Jellyfin.Networking.Manager.NetworkManager.InitialiseInterfaces()
   at Jellyfin.Networking.Manager.NetworkManager.UpdateSettings(Object configuration)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/proc/net/route' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.LinuxNetworkInterfaceSystemProperties..ctor()
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at Jellyfin.Networking.Manager.NetworkManager.InitialiseInterfaces()
   at Jellyfin.Networking.Manager.NetworkManager.UpdateSettings(Object configuration)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
fish: “jellyfin-server_10.7.0/jellyfin…” terminated by signal SIGABRT (Abort)
uumas@oreo ~/jellyfin> sudo chmod +r /proc/net/route
uumas@oreo ~/jellyfin> jellyfin-server_10.7.0/jellyfin --nowebclient
... starts normally
```

**Additional context**
In my case it's inaccessible due to a security focused grsec kernel but just changing the file permissions normally causes the same result.

**Comment by BaronGreenback** [comment]
Jellyfin uses the standard dotnet functionality to enumerate the network interfaces in order to decide which interfaces to listen to/use.

Looks like GetLinuxNetworkInterfaces (core dotnet functionality) is the cause. I know from a previous issue that it attempts to look at the routes for some reason.

Issue seems to be at https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L23

I would recommend you log a issue with them, as this is something beyond our control.

**Comment by uumas** [comment]
Okay, thanks for linking that. It seems they check if the file exists but not if they are allowed to read it. That makes hiding the file's existence a viable workaround. This was achieved by starting jellyfin in the background and immediately removing read permissions from it's /proc/net (conveniently every process has it's own copy so I own the folder). This is the script in case anyone else stumbles upon this:

```
#!/bin/bash
JELLYFINDIR="$HOME/jellyfin"
FFMPEGDIR="$JELLYFINDIR/ffmpeg"

$JELLYFINDIR/jellyfin/jellyfin --service --nowebclient \
-d $JELLYFINDIR/data \
-C $JELLYFINDIR/cache \
-c $JELLYFINDIR/config \
-l $JELLYFINDIR/log \
--ffmpeg $FFMPEGDIR/ffmpeg &

chmod 222 "/proc/$!/net"
wait $!
```

I'll submit an upstream issue if one doesn't exist already
