### ISSUE TITLE
Error when stopping DLNA Playback

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#560]
I am able to successfully playback videos over DLNA to VLC on iOS. This was tested so far with:
- Jellyfin/dev as of 6084ca1
- Jellyfin-web/dev as of 02918d0  

When I stop playback, I get this:

```
[03:22:39] [INF] HTTP POST http://localhost:8096/emby/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
[03:22:39] [INF] HTTP Response 204 to ::1. Time: 3ms. http://localhost:8096/emby/Sessions/Playing/Progress 
[03:23:03] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value) in /Users/anthonylavado/repos/jellyfin/SocketHttpListener/Net/HttpListenerResponse.cs:line 99
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text) in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 735
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage) in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 266
```

**Comment by cvium** [comment]
I've noticed a similar stack trace when starting a stream. It's caused by a Broken Pipe exception and then it tries to write this error to the http response, but it has already been sent, so it crashes.

The joys of a custom http listener 🙄
