### ISSUE TITLE
Setup Wizard Page is not present after a fresh install

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin#5645]
**Describe the bug**
Hello, I recently had to format my docker config drive containing jellyfin config folder. I recreated the app and everything loaded but when I open my Jellyfin web it just goes to index Page which keeps loading. I thought this was just a docker issue but I wanted to confirm it so I also did a fesh install of Jellyfin on my Win10 computer but the same thing happend and now I can't use Jellyfin. The logs are identical and attached below

**System (please complete the following information):**
 - OS: The Raspberry Pi OS and Windows
 - Virtualization: Docker/none(Win10)
 - Clients: Browser
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.1
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: ipv4
 - Storage: local

**To Reproduce**
 Do a fresh install of Jellyfin 10.7.1 and load jellyfin web

**Expected behavior**
It will be stuck on index Page or login page

**Logs**
Win10

```
[12:27:39] [INF] [1] Main: Jellyfin version: 10.7.1
[12:27:39] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\\ProgramData\\Jellyfin\\Server\\log]"]
[12:27:39] [INF] [1] Main: Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll", "--datadir", "C:\\ProgramData\\Jellyfin\\Server"]
[12:27:39] [INF] [1] Main: Operating system: Windows
[12:27:39] [INF] [1] Main: Architecture: X64
[12:27:39] [INF] [1] Main: 64-Bit Process: True
[12:27:39] [INF] [1] Main: User Interactive: True
[12:27:39] [INF] [1] Main: Processor count: 8
[12:27:39] [INF] [1] Main: Program data path: C:\ProgramData\Jellyfin\Server
[12:27:39] [INF] [1] Main: Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[12:27:39] [INF] [1] Main: Application directory: C:\Program Files\Jellyfin\Server\
[12:27:39] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: C:\ProgramData\Jellyfin\Server\cache
[12:27:40] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[12:27:40] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[12:27:40] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[12:27:40] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[12:27:40] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[12:27:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[12:27:42] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.1.0
[12:27:42] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.1.0
[12:27:42] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.1.0
[12:27:42] [INF] [1] Main: Kestrel listening on Any IP4 Address
[12:27:42] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[12:27:42] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 03/30/2021 02:00, which is 13:32:17.4319641 from now.
[12:27:42] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1
[12:27:42] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[12:27:42] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[12:27:43] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[12:27:43] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: C:\Program Files\Jellyfin\Server\ffmpeg.exe
[12:27:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 15055004dd4d44db88beb324ee2273b6
[12:27:43] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.56.1/24
[12:27:43] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.29.135/24
[12:27:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1666288
[12:27:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[12:27:43] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1661388
[12:27:43] [INF] [1] Main: Startup complete 0:00:04.1446059
[12:27:45] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[12:27:45] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[12:27:45] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[12:27:47] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
[12:27:47] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[12:27:48] [INF] [5] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for [TV] Samsung - UA50F6800
[12:27:49] [INF] [5] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used
[12:27:58] [INF] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [19] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[12:27:58] [ERR] [19] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/25513800f87c480f8da0f280eea18c79/Views.
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
   at lambda_method71(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[12:27:58] [INF] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [ERR] [18] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/25513800f87c480f8da0f280eea18c79/Views.
System.ArgumentException: User Id specified in the query does not exist. (Parameter 'query')
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
   at lambda_method71(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[12:27:58] [INF] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[12:27:58] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:27:58] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```
RPi4

```

[12:35:45] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.,
[12:30:52] [INF] [1] Main: Jellyfin version: 10.7.1,
[12:30:52] [INF] [1] Main: Environment Variables: ["[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_LOG_DIR, /config/log]"],
[12:30:52] [INF] [1] Main: Architecture: Arm,
[12:30:52] [INF] [1] Main: Operating system: Linux,
[12:30:52] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"],
[12:30:52] [INF] [1] Main: 64-Bit Process: False,
[12:30:52] [INF] [1] Main: User Interactive: True,
[12:30:52] [INF] [1] Main: Processor count: 4,
[12:30:52] [INF] [1] Main: Program data path: /config,
[12:30:52] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web,
[12:30:52] [INF] [1] Main: Application directory: /jellyfin/,
[12:30:53] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache,
[12:30:53] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16],
[12:30:58] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.1.0,
[12:30:53] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: [],
[12:30:53] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : [],
[12:30:53] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: [],
[12:30:53] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16],
[12:30:53] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies,
[12:30:58] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.1.0,
[12:30:58] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.1.0,
[12:30:58] [INF] [1] Main: Kestrel listening on Any IP4 Address,
[12:31:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks,
[12:31:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 03/30/2021 02:00, which is 13:28:59.7924093 from now.,
[12:31:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1,
[12:31:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_mmal", "hevc", "mpeg2video", "mpeg2_mmal", "mpeg4", "mpeg4_mmal", "msmpeg4", "vc1_mmal", "aac", "ac3", "flac", "mp3"],
[12:31:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_omx", "h264_v4l2m2m", "libx265", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"],
[12:31:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "drm"],
[12:31:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: /usr/lib/jellyfin-ffmpeg/ffmpeg,
[12:31:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 4cb71c99a1be40cc95e1d50592239e0a,
[12:31:01] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete,
[12:31:01] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.20.0.3/28,
[12:31:01] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.4106458,
[12:31:01] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.3824004,
[12:31:01] [INF] [1] Main: Startup complete 0:00:09.6692824,
[12:31:03] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins,
[12:31:03] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask,
[12:31:03] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins,
[12:31:05] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds,
[12:31:06] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks,
[12:31:12] [INF] [17] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.,
[12:35:44] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.29.60:8096/System/Info/Public to 192.168.29.135 in 0:00:00.7563166 with Status Code 200,
[12:35:45] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.,
[12:35:45] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.,
[12:35:45] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```

**Comment by nielsvanvelzen** [comment]
Try clearing your cookies, it looks like your browser still remembers a session from a previous install.

**Comment by prayag17** [comment]
Thanks it worked
