### ISSUE TITLE
System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0

### ISSUE THREAD

**Issue by dextertd** [jellyfin/jellyfin#5682]
**Describe the bug**

With the use of [this Reddit post](https://old.reddit.com/r/seedboxes/comments/gtl0fx/tutorial_how_to_install_jellyfin_on_feral_hosting/) I've installed Jellyfin on my FeralHosting instance, but I can't seem to set it up so that I can access Jellyfin web.

**System (please complete the following information):**
 - OS: Debian
 - Clients: Web
 - Browser: N/A
 - Jellyfin Version: 10.4.3
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: https://server.feralhosting.com/username/jellyfin
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: NFS

**To Reproduce**

1. Install Jellyfin on FeralHosting instance.
2. Execute jellyfin.

**Expected behavior**

Jellyfin launches and displays the URL by which I can access the web version.

**Logs**

```
[ERR] Failed to start UDP Server
System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)                                                        
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)                                                                                                
   at Emby.Server.Implementations.Net.UdpSocket..ctor(Socket socket, Int32 localPort, IPAddress ip)                                                   
   at Emby.Server.Implementations.Net.SocketFactory.CreateUdpSocket(Int32 localPort)                                                                  
   at Emby.Server.Implementations.Udp.UdpServer.Start(Int32 port)                                                                                     
   at Emby.Server.Implementations.EntryPoints.UdpServerEntryPoint.RunAsync()
```

Following occurs 2x 
```
Error decoding device response
System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.                                                                                                                                        
Parameter name: hostName                                                                                                                              
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)                                                                                                                                             
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)                                     
   at System.Net.Sockets.MultipleConnectAsync.StartConnectAsync(SocketAsyncEventArgs args, DnsEndPoint endPoint)                                      
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)                                
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)                                        
   --- End of inner exception stack trace ---                                                                                                         
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)                                        
   at System.Threading.Tasks.ValueTask`1.get_Result()                                                                                                 
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)                       
   at System.Threading.Tasks.ValueTask`1.get_Result()                                                                                                 
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)                                                      
   at System.Threading.Tasks.ValueTask`1.get_Result()                                                                                                 
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)   
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)                                      
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)                                                                                                                                                    
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)            
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)                    
   at Mono.Nat.Upnp.UpnpNatDevice.GetServicesList()                                                                                                   
   at Mono.Nat.UpnpSearcher.Handle(IPAddress localAddress, UpnpDeviceInfo deviceInfo, IPEndPoint endpoint)                                            
```

**Screenshots**

**Additional context**

0.0.0.0 should be accessible to Jellyfin from my instance.

**Comment by crobibero** [comment]
Are you really running 10.4.3?

**Comment by dextertd** [comment]
Yes, it's the latest binary I could find as a tar.gz. With my hosting provider I am unable to install it as a .deb and building it threw missing dependencies I'm unable to install myself.

**Comment by cvium** [comment]
There's a portable version... https://repo.jellyfin.org/releases/server/portable/stable/

**Comment by dextertd** [comment]
Thank you so much, I'll try that. I believe I missed that link because the link to it on the [docs](https://jellyfin.org/docs/general/administration/installing.html#portable-dll), which contains [this link](https://jellyfin.org/downloads/#portable), does not scroll down to the correct header. Should have noticed that of course, I just dismissed it at the time and didn't look further.

**Comment by dextertd** [comment]
I extracted the tar.gz and executed `jellyfin` but received
```
A fatal error occurred. The required library libhostfxr.so could not be found.
```

**Comment by crobibero** [comment]
I found this command that might help
`export DOTNET_ROOT=$(dirname $(readlink $(command -v dotnet))) `

**Comment by dextertd** [comment]
I'm trying to run it self-contained, not with dotnet framework

**Comment by dextertd** [comment]
Closing this as I got the original issue fixed (it was working all along, jellyfin spitting out errors confused me so I assumed something was broken).
