### ISSUE TITLE
Information on compilation of plugins needed

### ISSUE THREAD

**Issue by ninnghazad** [jellyfin/jellyfin#572]
How would one compile and install plugins under linux (debian)?
Building jellyfin using the supplied scripts works.
I can build non-working DLLs of jellyfin-plugin-* using
`dotnet build`
which will show up with errors in jellyfin's log.
What is the proposed procedure to actually use those plugins?
Or arent these ready to be used yet?

log grep:
```
[2019-01-13 06:45:59.596 +01:00] [ERR] Error creating "Emby.AutoOrganize.Core.OrganizerScheduledTask"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Logging.ILogger' from assembly 'MediaBrowser.Model, Version=10.0.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at SimpleInjector.Advanced.AdvancedExtensions.Verify(IDependencyInjectionBehavior behavior, ConstructorInfo constructor)
   at SimpleInjector.ContainerOptions.IsConstructableType(Type implementationType, String& errorMessage)
   at SimpleInjector.Container.TryBuildInstanceProducerForConcreteUnregisteredType(Type type, InjectionConsumerInfo context)
   at SimpleInjector.Container.GetInstanceProducerForType(Type serviceType, InjectionConsumerInfo consumer, Func`1 buildInstanceProducer)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Tuple`2 typeInfo) in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 520
```

**Comment by hawken93** [comment]
https://github.com/jellyfin/jellyfin/issues/30

**Comment by anthonylavado** [comment]
Closing this as the require Nuget Packages are now available: https://www.nuget.org/profiles/Jellyfin

Also quite a few Jellyfin plug-ins are all in some state of being ported, or are done.
