### ISSUE TITLE
Unstable: New install. Scanning errors due to missing images

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#5754]
Running on a slightly older version of unstable - so will remerge and check this again.

Windows 10.
Blank db - scanning media

Getting hundreds of 

```
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in F:\Code\Jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1929
[2021-04-10 11:46:40.687 +01:00] [ERR] [10] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "C:\ProgramData\Jellyfin\Server\metadata\People\S\Shannyn Sossamon\poster.jpg"
System.IO.FileNotFoundException: File not found
File name: 'C:\ProgramData\Jellyfin\Server\metadata\People\S\Shannyn Sossamon\poster.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in F:\Code\Jellyfin\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 181
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in F:\Code\Jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1929
[2021-04-10 11:46:40.718 +01:00] [ERR] [6] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "C:\ProgramData\Jellyfin\Server\metadata\People\G\Gregory Peck\poster.jpg"
System.IO.FileNotFoundException: File not found
File name: 'C:\ProgramData\Jellyfin\Server\metadata\People\G\Gregory Peck\poster.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in F:\Code\Jellyfin\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 181
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in F:\Code\Jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1929
[2021-04-10 11:46:40.793 +01:00] [ERR] [7] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "C:\ProgramData\Jellyfin\Server\metadata\People\J\John Howard Davies\poster.jpg"
System.IO.FileNotFoundException: File not found
File name: 'C:\ProgramData\Jellyfin\Server\metadata\People\J\John Howard Davies\poster.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) in F:\Code\Jellyfin\Jellyfin.Drawing.Skia\SkiaEncoder.cs:line 181
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 316
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) in F:\Code\Jellyfin\Emby.Drawing\ImageProcessor.cs:line 307
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate) in F:\Code\Jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1929
```

the _people_ image are all **folder.jpg** on my system

**Comment by BaronGreenback** [comment]
UpdateImagesAsync.

Item has a primaryImagePath for a folder/file that does not exist.

**Comment by mjpieters** [comment]
I have the same error. It only happens for paths with spaces in them; paths without spaces work without issue.

**Comment by mjpieters** [comment]
I gave the Jellyfin server process write permissions to those paths, and that resolved the issue.

The image files were not written to but the directory modified time stamps *were* updated. It looks like SkiaCodec is using the directory as a cache of some sort.
