### ISSUE TITLE
Jellyfin fails to start with immutable configuration files.

### ISSUE THREAD

**Issue by kevincox** [jellyfin/jellyfin#5756]
**Describe the bug**
If you start Jellyfin with read-only configuration it crashes. This appears to be because [it tries to re-write the system.xml file if it isn't byte-for-byte identical](https://github.com/jellyfin/jellyfin/blob/480dd66428e2a8bf76c0747256f2e99b15aae212/Emby.Server.Implementations/AppBase/ConfigurationHelper.cs#L42-L63). This appears to happen due to new properties being added or because of formatting differences.

**System (please complete the following information):**
 - OS: NixOS
 - Virtualization: None
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.7.1
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: N/A
 - Base URL: /
 - Networking: Host
 - Storage: local

**To Reproduce**

1. `echo >>/var/lib/jellyfin/config/system.xml`
2. `chmod 444 /var/lib/jellyfin/config/system.xml`

**Expected behavior**

Jellyfin starts

**Logs**

```
[INF] Jellyfin version: 10.7.1
[INF] Environment Variables: ["[JELLYFIN_hostwebclient, false]", "[JELLYFIN_kestrel__socketPath, /run/jellyfin/sock]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_DefaultRedirectPath, web/]", "[JELLYFIN_kestrel__socket, true]"]
[INF] Arguments: ["/nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin.dll", "--ffmpeg", "/nix/store/rv7fjxcx143vlq3hbpqb9b02p51ivi3a-ffmpeg-4.3.2-bin/bin/ffmpeg", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin"]
[INF] Operating system: Linux
[INF] Architecture: X64
[INF] 64-Bit Process: True
[INF] User Interactive: True
[INF] Processor count: 4
[INF] Program data path: /var/lib/jellyfin
[INF] Web resources path: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin-web
[INF] Application directory: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/
[FTL] Unhandled Exception
System.UnauthorizedAccessException: Access to the path '/var/lib/jellyfin/config/system.xml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Emby.Server.Implementations.AppBase.ConfigurationHelper.GetXmlConfiguration(Type type, String path, IXmlSerializer xmlSerializer)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.get_CommonConfiguration()
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.UpdateCachePath()
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager..ctor(IApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IXmlSerializer xmlSerializer, IFileSystem fileSystem)
   at Emby.Server.Implementations.Configuration.ServerConfigurationManager..ctor(IApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IXmlSerializer xmlSerializer, IFileSystem fileSystem)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/var/lib/jellyfin/config/system.xml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Emby.Server.Implementations.AppBase.ConfigurationHelper.GetXmlConfiguration(Type type, String path, IXmlSerializer xmlSerializer)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.get_CommonConfiguration()
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.UpdateCachePath()
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager..ctor(IApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IXmlSerializer xmlSerializer, IFileSystem fileSystem)
   at Emby.Server.Implementations.Configuration.ServerConfigurationManager..ctor(IApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IXmlSerializer xmlSerializer, IFileSystem fileSystem)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

**Additional context**

Jellyfin writes the config out but doesn't use it until the next start this appears to be mostly unnecessary. In my case it is just adjusting the formatting which isn't necessary. One possible reason that this is important is so that over time new fields are added such that they can be assumed to be there in future versions. However I would suggest that this is avoided anyways because it means that the config file needs to specify every value. It also means that skipping versions will cause breakage.

This could likely be resolved by just catching the error and emitting a warning.

A workaround is to put all of your config files into another directory (eg: `jellyfin-config`) and install the files before Jellyfin boots (eg: `install -Dt /var/lib/jellyfin/config -m 600 jellyfin-config/*`. This way Jellyfin can happily overwrite them, but the golden configs will be restored when the service is restarted.

**Comment by kevincox** [comment]
go away

**Comment by Bond-009** [comment]
This is a feature request, those belong here: https://features.jellyfin.org/
