### ISSUE TITLE
System.IndexOutOfRangeException if IPv6 prefix length is > 32 and not a multiple of 8

### ISSUE THREAD

**Issue by jrb0001** [jellyfin/jellyfin#5815]
**Describe the bug**
IPv4 prefixes with any length and IPv6 prefixes up to /32 seem to work correctly. IPv6 prefixes longer than /32 seem to work only if the length is a multiple of 8.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: LXC
 - Jellyfin Version: Jellyfin.Server 10.7.2.0 (.deb amd64 10.7.2-1)
 - Base URL: none
 - Networking: multiple veth interfaces
 - Storage: local

**To Reproduce**
1. Add prefix from list below to `<LocalNetworkSubnets>` in network.xml.
2. Start jellyfin.
3. Check if it crashed.
4. Try next prefix.

- 2001:db8::/31 works.
- 2001:db8::/32 works.
- 2001:db8::/33 doesn't work.
- 2001:db8::/40 works.
- 2001:db8::/52 doesn't work.
- 2001:db8::/120 works.
- 2001:db8::/122 doesn't work.

**Expected behavior**
All (valid) prefixes work correctly.

**Logs**
```
[19:31:58] [FTL] Unhandled Exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Common.Net.IPObject.NetworkAddressOf(IPAddress address, Byte prefixLength)
   at MediaBrowser.Common.Net.IPNetAddress.Contains(IPObject address)
   at MediaBrowser.Common.Net.NetworkExtensions.ContainsAddress(Collection`1 source, IPObject item)
   at Jellyfin.Networking.Manager.NetworkManager.IsInLocalNetwork(IPObject address)
   at Jellyfin.Networking.Manager.NetworkManager.<InitialiseLAN>b__80_1(IPObject i)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Jellyfin.Networking.Manager.NetworkManager.CreateCollection(IEnumerable`1 source)
   at Jellyfin.Networking.Manager.NetworkManager.InitialiseLAN(NetworkConfiguration config)
   at Jellyfin.Networking.Manager.NetworkManager.UpdateSettings(Object configuration)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection serviceCollection)
   at Jellyfin.Server.CoreAppHost..ctor(IServerApplicationPaths applicationPaths, ILoggerFactory loggerFactory, IStartupOptions options, IConfiguration startupConfig, IFileSystem fileSystem, IServiceCollection collection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by BaronGreenback** [comment]
Fixed: It's the prefix error fixed in https://github.com/jellyfin/jellyfin/pull/5595.

**Comment by theguymadmax** [comment]
This should have been fixed by https://github.com/jellyfin/jellyfin/pull/8147
