### ISSUE TITLE
/system/info/public failing authentication

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#5827]
Unstable: Windows 10
```
[2021-04-15 19:30:40.479 +01:00] [DBG] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with "CustomAuthenticationHandler"
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token. /system/info/public
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request) in F:\Code\BaronGreenback\jellyfin\Emby.Server.Implementations\HttpServer\Security\AuthService.cs:line 27
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in F:\Code\BaronGreenback\jellyfin\Jellyfin.Api\Auth\CustomAuthenticationHandler.cs:line 47
[2021-04-15 19:30:40.479 +01:00] [DBG] [9] Jellyfin.Networking.Manager.NetworkManager: "127.0.0.1/32": GetBindInterface: Has source, matched best internal interface on range. "127.0.0.1"
[2021-04-15 19:30:40.483 +01:00] [DBG] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2021-04-15 19:30:40.502 +01:00] [DBG] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2021-04-15 19:30:40.485 +01:00] [DBG] [10] Jellyfin.Networking.Manager.NetworkManager: "127.0.0.1/32": GetBindInterface: Has source, matched best internal interface on range. "127.0.0.1"
[2021-04-15 19:30:40.486 +01:00] [DBG] [12] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[2021-04-15 19:30:40.586 +01:00] [DBG] [12] Jellyfin.Networking.Manager.NetworkManager: "127.0.0.1/32": GetBindInterface: Has source, matched best internal interface on range. "127.0.0.1"
[2021-04-15 19:30:40.537 +01:00] [DBG] [8] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[2021-04-15 19:30:40.534 +01:00] [DBG] [4] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
```
Getting this at startup Looks like the request is coming from the local machine (web and vlc both open). 

Looks like whatever is causing this resulted in some race condition. as I've had pages of this in the logs.

**Comment by jacobslusser** [comment]
I would like to reopen this task and fix it. The cause is a first-chance exception being caught and logged in `CustomAuthenticationHandler.HandleAuthenticateAsync`. I would characterize this as "using exceptions for flow control". It doesn't effect the user experience, but it does flood the logs needlessly with the above exception for every public endpoint.

In addition to the log files, it also floods the Visual Studio debugger -- making it hard to troubleshoot other errors.

I can provide a PR with a fix.

CC: @BaronGreenback

**Comment by crobibero** [comment]
This was added intentionally. Normal use isn’t to run Jellyfin with debug logging enabled.

**Comment by BaronGreenback** [comment]
or if you wish to run with debug - add a custom filter to logging.js.on for "Jellyfin.Api.Auth.CustomAuthenticationHandler" and set it to "Error"
