### ISSUE TITLE
Manually identifying media and metadata is never downloaded.

### ISSUE THREAD

**Issue by angelfor3v3r** [jellyfin/jellyfin#5850]
**Describe the bug**
When I manually identify media the metadata is never downloaded.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: All
 - Browser: Firefox 87
 - Jellyfin Version: 10.7.2
 - Playback: All
 - Installed Plugins: AniDB, Anime (Not supported on 10.7.2?)
 - Reverse Proxy: HAProxy
 - Base URL: none
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. Go to any Media
2. Right click media and Identify.
3. Notice no metadata/images are grabbed.

**Expected behavior**

**Logs**

```[2021-04-18 07:47:16.633 +00:00] [ERR] [71] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/TV Shows/Hannibal"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-04-18 07:47:16.639 +00:00] [ERR] [155] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/TV Shows/Chernobyl"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-04-18 07:47:16.655 +00:00] [ERR] [75] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/TV Shows/Band.of.Brothers"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-04-18 07:47:16.656 +00:00] [ERR] [67] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/TV Shows/The Sopranos"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2021-04-18 07:47:16.656 +00:00] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/TV Shows/Breaking Bad"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Screenshots**
N/A

**Additional context**
This seems to happen no matter what providers I chose for metadata.

**Comment by minoskt** [comment]
Same for me, installed on a Raspberry Pi 4B.

**Comment by angelfor3v3r** [comment]
Can anyone else provide info or a solution to this? Still happening to me on 10.7.5.

**Comment by angelfor3v3r** [comment]
I've updated to 10.7.6 and it still seems to show me the same error:
[code]
[2021-06-27 19:06:33.924 +00:00] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/Foobar"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[/code]

**Comment by justinfenn** [comment]
Seems to be the same as #6039 (fixed by #5806), but I'm still seeing this in 10.7.7.
