### ISSUE TITLE
"CustomAuthentication" was not authenticated. Failure message: "Invalid token."

### ISSUE THREAD

**Issue by jamesmurphy746** [jellyfin/jellyfin#5862]
**Describe the bug**
Updated from 10.6.x to 10.7,2 a couple of days ago, since then Jellyfin has been very unstable. At first I thought it might have been old clients but after updating the clients I checked the logs from a period when nobody was connecting and the errors still occur. Tried many google searches but keep drawing blanks. At times the server stops responding for both jellyfin clients and web access.. usually springs back to life after about 5 minutes.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.7.2
 - Playback: N/A
 - Installed Plugins: None\Default
 - Reverse Proxy: apache [unchanged since 10.6]
 - Base URL: N/A
 - Networking: Host
 - Storage: N/A

**To Reproduce**

1. Go to 'admin'
2. Click on 'logs'
3. Scroll down to 'anywhere'

**Expected behavior**
Not these errors?

**Logs**
I'll save you from the full thing and just put a little snippet..

[2021-04-19 05:31:54.901 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:31:54.901 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:31:54.901 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:32:09.896 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:09.896 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:09.896 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:32:24.932 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:24.932 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:24.932 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:32:39.988 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:39.988 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:39.988 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:32:55.028 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:55.028 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:32:55.029 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:33:10.034 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:10.035 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:10.035 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:33:25.048 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:25.048 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:25.048 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:33:40.087 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:40.087 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:40.087 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:33:55.147 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:55.147 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:33:55.147 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2021-04-19 05:34:10.141 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:34:10.141 +02:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2021-04-19 05:34:10.141 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.

these repeat every few seconds.. ALL DAY

Please.. any help?

**Comment by bpepple** [comment]
I was hit with this also, and it has made it impossible to run the initial start-up wizard.  This pull request is supposed to fix it, but it doesn't seem to be a high priority for the devs to review.  https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/187

**Comment by electrona** [comment]
I am currently having this issue and now my whole jellyfin instance is broken.

**Comment by bpepple** [comment]
> I am currently having this issue and now my whole jellyfin instance is broken.

Are you attempting to access it thru the web-ui, and if so, have you tried clearing your browser cache? That should remove any sign-in references and hopefully allow you to sign-in.

**Comment by reloadfast** [comment]
> > I am currently having this issue and now my whole jellyfin instance is broken.
> 
> Are you attempting to access it thru the web-ui, and if so, have you tried clearing your browser cache? That should remove any sign-in references and hopefully allow you to sign-in.

I have wasted the better part of two hours trying to figure out what the f*ck was happening. Google, reddit, unraid... nothing. The answer was right where the action happens.

Thank you so much!

**Comment by Ezzahhh** [comment]
I have tried clearing cache and cookies on multiple browsers but still get this error. On 10.7.2 new installation with default plugins. Only thing I did after installation was to begin scanning in libraries. Makes navigation very slow.

**Comment by electrona** [comment]
> > I am currently having this issue and now my whole jellyfin instance is broken.
> 
> Are you attempting to access it thru the web-ui, and if so, have you tried clearing your browser cache? That should remove any sign-in references and hopefully allow you to sign-in.

That was it! Thank you so much.

**Comment by the-lazy-fox** [comment]
> 
> 
> I have tried clearing cache and cookies on multiple browsers but still get this error. On 10.7.2 new installation with default plugins. Only thing I did after installation was to begin scanning in libraries. Makes navigation very slow.

Same for me, I've cleared the cache, changed browser, used private browsing, used a new device, still spammed with these logs..

**Comment by 3nprob** [comment]
Just started getting this on an instance which has previously been working fine. Using LDAP (plugin version 11). No new sign-ins possible, neither for LDAP users nor those using the built-in auth. There was one existing session which could access Jellyfin and play everything just fine - no new sign-ins possible, though. 

Browser session guaranteed fresh.

Jellyvfin v10.7.7 (upgraded from 10.7.6 where this issue started occurring)

Logs:
```
[00:55:01] [DBG] [33] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[00:55:01] [DBG] [33] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[00:55:01] [DBG] [33] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[00:55:01] [DBG] [33] Jellyfin.Networking.Manager.NetworkManager: 192.168.2.158/32: GetBindInterface: Matched first internal interface. 172.26.72.95
```

**Comment by RogueGhost93** [comment]
Same problem here. Tried all kinds of stuff, re-pulling image, purging everything jellyfin related and the issue still persists. Nothing but the inital setup is done. Created username, added library, and the logs start spamming, only 1 show is scanned out of 1000.


[13:09:01] [INF] [35] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[13:09:01] [INF] [35] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[13:09:02] [INF] [36] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[13:09:02] [ERR] [36] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid token. URL GET /socket.

Tried different browsers, same thing. 
On a fresh install of ubuntu it appears to work fine, however i wanna get it going on my main machine where jellyfin was working just fine before until it stopped scanning in new tv shows for whatever reason, which made me reinstall it and ever since it is not scanning anything. Thanks to anyone with any kind of idea what could be wrong or what to do. Maybe there are some cache files that should be erased? Not sure.

**Comment by ToXinE** [comment]
same here after moving the vm hosting docker on a new server
