### ISSUE TITLE
NullReferenceException when deleting item through `/Items/{IteemID}`

### ISSUE THREAD

**Issue by vedhavyas** [jellyfin/jellyfin#5875]
**Describe the bug**

I'm seeing the following error when I make a delete API call for a given item
```
[17:00:02] [ERR] [77] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL DELETE /Items/473368f376706a1054da6fd1eaad2f6b.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Controller.Entities.BaseItem.IsAuthorizedToDelete(User user, List`1 allCollectionFolders)
   at Jellyfin.Api.Controllers.LibraryController.DeleteItem(Guid itemId)
   at lambda_method1261(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: API
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: 10.7.2
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: Caddy [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: Bridge
 - Storage: cloud

**Expected behavior**

To delete the item

**Logs**

see above

**Comment by vedhavyas** [comment]
looks like it is related to this https://github.com/jellyfin/jellyfin/issues/2246

**Comment by vedhavyas** [comment]
After debugging more, It looks like access tokens were not created properly, The UserID in all the created access tokens is "00000000000000000000000". Here is an example response when I fetched all the access token

```
	{
         "AppName" : "test",
         "DeviceId" : "xxxx",
         "DateCreated" : "2021-04-20T18:39:28.4794731Z",
         "DateLastActivity" : "0001-01-01T00:00:00.0000000Z",
         "AppVersion" : "10.7.2",
         "IsActive" : false,
         "DeviceName" : "xxx",
         "AccessToken" : "xxxxx",
         "UserId" : "00000000000000000000000000000000",
         "Id" : xx
      }
```

For anyone who is facing this issue, clear all your access tokens and then create a new one.

Is it possible that usrID is empty when I create access token from the Webapp ?

**Comment by nburns** [comment]
This broke for me, and sure enough the UserId is empty on my access token. How you create a token with a user id @vedhavyas?

**Comment by nburns** [comment]
For anyone else who gets here, I manually updated the database with the right userid for my key:
load the db: `sudo sqlite3 /var/lib/jellyfin/data/authentication.db`
find your token: `select * from Tokens`
update the token's user id: `update Tokens set UserId = '9e828ed72a1d4137a2395666f832416b' where Id = 'f35dcf8e1b9b47fdaa056eac3a57bef8'`
