### ISSUE TITLE
LiveTV and HDhomerun Dual not functioning.

### ISSUE THREAD

**Issue by starblazr** [jellyfin/jellyfin#5906]
Debian Buster
Jellyfin 10.7.2

Live TV does not for for HDhomerun dual, but works fine for an extend.  Tried playing with the options in LiveTV (transcoding, etc) with no luck.

```
[2021-04-24 19:17:01.142 -05:00] [ERR] Error getting channel list
System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(String requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelsInternal(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(TunerHostInfo tuner, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(Boolean enableCache, CancellationToken cancellationToken)
[2021-04-24 19:17:01.154 -05:00] [INF] Refreshing guide with 7 days of guide data
```

Setting debug doesn't give me any more info, like, the url it's trying to go after.  I've tried setting the URL as http://(ip), (ip), http://(ip)/, no luck.

No weird port issues, I can access the tuner just fine via tvheadend.  ideas?

**Comment by BaronGreenback** [comment]
Add "Emby.Server.Implementations.LiveTv.EmbyTV" : "Debug" to your default.logging.json and restart - you should start getting debug messages which might help.

**Comment by starblazr** [comment]
Nothing

````
[2021-04-26 19:01:31.694 -05:00] [DBG] [30] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide from "Emby"
[2021-04-26 19:01:31.701 -05:00] [ERR] [20] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error getting channel list
System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(String requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelsInternal(TunerHostInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(TunerHostInfo tuner, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(Boolean enableCache, CancellationToken cancellationToken)
[2021-04-26 19:01:31.704 -05:00] [INF] [20] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[2021-04-26 19:01:31.705 -05:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Refresh Guide" Completed after 0 minute(s) and 3 seconds
[2021-04-26 19:01:31.706 -05:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-04-26 19:01:33.538 -05:00] [DBG] [26] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
````

**Comment by BaronGreenback** [comment]
Could you try adding "Emby.Server.Implementations.LiveTv.TunerHosts" : "Debug" to the same file and restart please?

**Comment by starblazr** [comment]
Alright, progress.

Apparently Debian you have to make the changes in /etc/jellyfin/logging.json.  I set EVERYTHING to Debug, so, I've cut out what I think is worthless and gave you what I think is useful.

````
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [DBG] [31] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide from Emby
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [31] System.Net.Http.HttpClient.Default.LogicalHandler: Start processing HTTP request GET http://10.10.10.100/discover.json
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [31] System.Net.Http.HttpClient.Default.ClientHandler: Sending HTTP request GET http://10.10.10.100/discover.json
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [20] System.Net.Http.HttpClient.Default.ClientHandler: Received HTTP response headers after 6.1354ms - 200
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [20] System.Net.Http.HttpClient.Default.LogicalHandler: End processing HTTP request after 7.098ms - 200
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [ERR] [20] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Error getting channel list
Apr 29 12:02:49 jellyfin jellyfin[17756]: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at System.Net.Http.HttpClient.GetAsync(String requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetLineup(TunerHostInfo info, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost.GetChannelsInternal(TunerHostInfo info, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(TunerHostInfo tuner, Boolean enableCache, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]:    at Emby.Server.Implementations.LiveTv.TunerHosts.BaseTunerHost.GetChannels(Boolean enableCache, CancellationToken cancellationToken)
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [20] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 3 seconds
Apr 29 12:02:49 jellyfin jellyfin[17756]: [12:02:49] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
Apr 29 12:02:50 jellyfin jellyfin[17756]: [12:02:50] [DBG] [20] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
````

Content of discovery.json
````
{"FriendlyName":"HDHomeRun DUAL","ModelNumber":"HDHR3-US","Legacy":1,"FirmwareName":"hdhomerun3_atsc","FirmwareVersion":"20200225","DeviceID":"10xxxxx5","TunerCount":2,"BaseURL":"http://10.10.10.100:80"}
````
content of discovery.json on a unit that works
````
{"FriendlyName":"HDHomeRun EXTEND","ModelNumber":"HDTC-2US","FirmwareName":"hdhomeruntc_atsc","FirmwareVersion":"20210404beta1","DeviceID":"10xxxxA","DeviceAuth":"oxxxxufni_dRxxxxxx0epo","BaseURL":"http://192.1xxxxx115:80","LineupURL":"http://192.1xxxxx15:80/lineup.json","TunerCount":2}
````

**Comment by BaronGreenback** [comment]
it's the lineupURL that's missing - that's the cause of the missing URI

**Comment by BaronGreenback** [comment]
doesn't look like it uses baseURL at all in this section of the code.

**Comment by starblazr** [comment]
https://emby.media/community/index.php?/topic/45783-legacy-hdhomerun-setup/ is the fix.

**Comment by Bond-009** [comment]
@starblazr can you test https://github.com/jellyfin/jellyfin/pull/5999 ?

**Comment by Bond-009** [comment]
Should be fixed

**Comment by atpage** [comment]
> https://emby.media/community/index.php?/topic/45783-legacy-hdhomerun-setup/ is the fix.

For completeness here, since I just had to do this, the workaround described at that link boils down to:

1. Run a channel scan in the HDHomeRun Setup application (in Windows!).
1. Once it's done and you see a channel list, hit "Apply".

This does some magic to update your channel lineup at `https://ipv4-api.hdhomerun.com/api/lineup`, which is where Jellyfin seems to be looking for it.
