### ISSUE TITLE
Missing folders in media librairies

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#5949]
**Describe the bug**
Some folders just don't appear in a Movies type media library.

The bigger issue is I can't find anything special to the missing folder I have identified.
It seats next to other folders that are detected, has the same permissions, is viewable from the Jellyfin container.

All errors I can see in the logs are for unrelated folders like:
```
[2021-05-01 16:03:03.923 +00:00] [ERR] [69] Emby.Server.Implementations.Library.LibraryManager: Error in "MovieResolver" resolving "/media/Directors/France/Ocelot, Michel"
System.IO.IOException: Too many levels of symbolic links
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.<>c__DisplayClass16_0`1.<GetMultiDiscMovie>b__1(String i)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.GetMultiDiscMovie[T](List`1 multiDiscFolders, IDirectoryService directoryService)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.FindMovie[T](ItemResolveArgs args, String path, Folder parent, List`1 fileSystemEntries, IDirectoryService directoryService, String collectionType, Boolean parseName)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.Resolve(ItemResolveArgs args)
   at MediaBrowser.Controller.Resolvers.ItemResolver`1.MediaBrowser.Controller.Resolvers.IItemResolver.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
   ```
which doesn't make sense to me because there are no symlinks in these.
Moreover, even with this error, these folders at least appear in the movie library, even though they are empty.

But the missing ones are just... missing! 
And so I just don't know how to help reproduce.

Hopefully this is a dummy problem.

**System (please complete the following information):**
 - OS: Ubuntu (virtualized on TrueNas, Freebsd)
 - Virtualization: Docker
 - Jellyfin Version: **10.7.2**
 - Storage: NFS

** Screenshots ** 
https://imgur.com/a/GR5wHUV
Not very helpful, just underlined 2 missing top-level folders I've detected. 
Just shows the permissions are identical to other folders.

**Comment by nodje** [comment]
I still can't solve this issue and I realize there's actually lots of folder missing here and there.
Jellyfin is latest stable 10.7.7, running in docker with the media are mounted as an NFS mount in the container.

There's no issue in the logs, and navigating the folder hierarchy with the docker container or actually within Add Media Library, I can fully navigate the hierarchy of folder.

But within a Library that has a top folder selected, some sub-folder just aren't found.

This sounds like a serious issue to me, I can't figure out what could possibly be wrong.

I'm not sure how I could help reproduce this as it's working for some sub-folders but not for others.

**Comment by nodje** [comment]
See issue #6828
