### ISSUE TITLE
Can't login or access display settings page

### ISSUE THREAD

**Issue by stskyblade** [jellyfin/jellyfin#5953]
**Describe the bug**
Login page is always loading. 
`http://localhost:8096/DisplayPreferences/usersettings?userId=<...>&client=emby` returns 500.

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: [e.g. Chrome 80]

**Logs**
```
May 02 09:48:56 X450VC jellyfin[3361235]: [09:48:56] [INF] WS 127.0.0.1 closed                                                                                                                
May 02 09:48:56 X450VC jellyfin[3361235]: [09:48:56] [INF] WS 127.0.0.1 request                                                                                                               
May 02 09:48:56 X450VC jellyfin[3361235]: [09:48:56] [ERR] An exception occurred while iterating over the results of a query for context type 'Jellyfin.Server.Implementations.JellyfinDb'.   
May 02 09:48:56 X450VC jellyfin[3361235]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.   
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)                                                                              
May 02 09:48:56 X450VC jellyfin[3361235]:    at lambda_method663(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )                                       
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()                                                 
May 02 09:48:56 X450VC jellyfin[3361235]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.   
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)                                                                              
May 02 09:48:56 X450VC jellyfin[3361235]:    at lambda_method663(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )                                       
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()                                                 
May 02 09:48:56 X450VC jellyfin[3361235]: [09:48:56] [ERR] Error processing request. URL GET /DisplayPreferences/usersettings.                                                                
May 02 09:48:56 X450VC jellyfin[3361235]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.   
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)                                                                              
May 02 09:48:56 X450VC jellyfin[3361235]:    at lambda_method663(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )                                       
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()                                                 
May 02 09:48:56 X450VC jellyfin[3361235]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer
`1 comparer)                                                                                                                                                                                  
May 02 09:48:56 X450VC jellyfin[3361235]:    at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)          
May 02 09:48:56 X450VC jellyfin[3361235]:    at lambda_method503(Closure , Object , Object[] )                                                                                                
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExec
utor executor, Object controller, Object[] arguments)                                                                                                                                         
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()                                                  
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()          
May 02 09:48:56 X450VC jellyfin[3361235]: --- End of stack trace from previous location ---                                                                                                   
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)                                  May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()                                            
May 02 09:48:56 X450VC jellyfin[3361235]: --- End of stack trace from previous location ---   
May 02 09:48:56 X450VC jellyfin[3361235]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**I have tried:**
apt remove and install jellyfin
I think some data file is reserved when reinstall. How can I fully remove jellyfin and reinstall ?

**Comment by stskyblade** [comment]
This issue has been solved.

```
sudo apt remove jellyfin
sudo apt autoremove
# maybe need sudo
locate jellyfin | grep -v "apt" | grep -v "Trash" | xargs rm -rf
sudo apt install jellyfin
```
