### ISSUE TITLE
Images will not upload for certain films or persons.

### ISSUE THREAD

**Issue by hermanWinters** [jellyfin/jellyfin#5991]
**Describe the bug**

**System (please complete the following information):**
 - Linux Mint 20.1
 - Clients: [Browser]
 - Browser: [Brave 1.23.75]
 - Jellyfin Version: [10.7.2]
 - Playback: [Direct Play] 
 - Installed Plugins: [Anidb, Audiodb, Coverart, ISOmounter Musicbrainz, Omdb, Opensubtitles]
 - Reverse Proxy: [ none]
 - Base URL: [http://127.0.0.1:8096]
 - Networking: []
 - Storage: [local]

**To Reproduce**

1. Go to particular movie page, displaying actors
2. Click on 'actor hamburger and select edit picture'
3. Click on picture + and select browse. then select picture and click OK
4. Then click "upload"

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
Please provide logs.

**Comment by hermanWinters** [comment]
[2021-05-06 00:00:37.385 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=31400b8d1847661ac425847860120c35" to "127.0.0.1" in 0:00:00.6650785 with Status Code 200
[2021-05-06 00:00:37.400 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=3148cf0701708325a446ec1751b2b64e" to "127.0.0.1" in 0:00:00.6909605 with Status Code 200
[2021-05-06 00:00:37.432 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=73fabcebd2c44d5081f771d2dc46f63b&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=true" to "127.0.0.1" in 0:00:00.7230799 with Status Code 200
[2021-05-06 00:00:37.593 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9f3ad26dbfee0df8fd587b153f76c8c8" to "127.0.0.1" in 0:00:00.8833108 with Status Code 200
[2021-05-06 00:07:18.653 +02:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:18.653 +02:00] [INF] Defined LAN exclusions : "[]"
[2021-05-06 00:07:18.654 +02:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:20.674 +02:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:20.675 +02:00] [INF] Defined LAN exclusions : "[]"
[2021-05-06 00:07:20.675 +02:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:22.687 +02:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:22.687 +02:00] [INF] Defined LAN exclusions : "[]"
[2021-05-06 00:07:22.687 +02:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:24.696 +02:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:07:24.696 +02:00] [INF] Defined LAN exclusions : "[]"
[2021-05-06 00:07:24.696 +02:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-06 00:16:41.984 +02:00] [INF] WS "127.0.0.1" closed
[2021-05-06 00:17:08.172 +02:00] [INF] WS "127.0.0.1" request
[2021-05-06 00:17:09.290 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=3148cf0701708325a446ec1751b2b64e" to "127.0.0.1" in 0:00:00.5139867 with Status Code 200
[2021-05-06 00:17:09.325 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=73fabcebd2c44d5081f771d2dc46f63b&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=true" to "127.0.0.1" in 0:00:00.5494776 with Status Code 200
[2021-05-06 00:17:09.519 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9f3ad26dbfee0df8fd587b153f76c8c8" to "127.0.0.1" in 0:00:00.7429225 with Status Code 200
[2021-05-06 00:20:01.325 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=31400b8d1847661ac425847860120c35" to "127.0.0.1" in 0:00:00.5134721 with Status Code 200
[2021-05-06 00:20:01.341 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=3148cf0701708325a446ec1751b2b64e" to "127.0.0.1" in 0:00:00.5399859 with Status Code 200
[2021-05-06 00:20:01.381 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=73fabcebd2c44d5081f771d2dc46f63b&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=true" to "127.0.0.1" in 0:00:00.5801465 with Status Code 200
[2021-05-06 00:20:01.542 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Users/73fabcebd2c44d5081f771d2dc46f63b/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=9f3ad26dbfee0df8fd587b153f76c8c8" to "127.0.0.1" in 0:00:00.7415508 with Status Code 200
[2021-05-06 00:20:12.206 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/bf7aa4a2b81f558e928148e173824c92/Images/Primary?fillHeight=461&fillWidth=307&tag=dbdc61985da6840639e9ab705e8159dc&quality=90" to "127.0.0.1" in 0:00:07.1147037 with Status Code 200
[2021-05-06 00:20:12.243 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/c0647d5ac52273c960518bf84ff6c898/Images/Primary?fillHeight=461&fillWidth=307&tag=86cb49303f754cdb8a0a264a9f1ce9c1&quality=90" to "127.0.0.1" in 0:00:07.1521857 with Status Code 200
[2021-05-06 00:20:12.246 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/41534e1a0b664f1917b41428161d07ab/Images/Primary?fillHeight=461&fillWidth=307&tag=150aafa3cb34d7717fbe190d4e810b10&quality=90" to "127.0.0.1" in 0:00:07.1550474 with Status Code 200
[2021-05-06 00:20:12.246 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/3b09d1e51d3813097b0bcd1f463baa61/Images/Primary?fillHeight=461&fillWidth=307&tag=ce1529c368e6eaee67c2c5dfd82b3eaa&quality=90" to "127.0.0.1" in 0:00:07.1548237 with Status Code 200
[2021-05-06 00:20:12.265 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/06690d9957b4f714aeb082bf273d3994/Images/Primary?fillHeight=461&fillWidth=307&tag=6182c114d92f1833a27322f9264d291c&quality=90" to "127.0.0.1" in 0:00:07.1734101 with Status Code 200
[2021-05-06 00:20:12.274 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/73b1e88c0da8655208de7b38d807e270/Images/Primary?fillHeight=461&fillWidth=307&tag=bef0e2bc70115d5df39ccd0c7c4a103e&quality=90" to "127.0.0.1" in 0:00:07.1844029 with Status Code 200
[2021-05-06 00:20:19.497 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/86da094e5b1d33db311b05f47c9cd65f/Images/Primary?fillHeight=461&fillWidth=307&tag=f51ab85be0654136bfa3f2f177584099&quality=90" to "127.0.0.1" in 0:00:07.0992199 with Status Code 200
[2021-05-06 00:20:19.502 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/f222a8994e8390b175b36df5c43f1475/Images/Primary?fillHeight=461&fillWidth=307&tag=954ea8d95817f3ca8ce83440b16416cf&quality=90" to "127.0.0.1" in 0:00:07.0946126 with Status Code 200
[2021-05-06 00:20:19.525 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/157ccf394b3f6c784db72164ddc83797/Images/Primary?fillHeight=461&fillWidth=307&tag=0cc72933698b366cf32a0533cea0df0e&quality=90" to "127.0.0.1" in 0:00:07.1176916 with Status Code 200
[2021-05-06 00:20:19.525 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/d712750c01fb39e4626aaee90da60e70/Images/Primary?fillHeight=461&fillWidth=307&tag=741a9f1eab3e2a67b64da2fe7056fa86&quality=90" to "127.0.0.1" in 0:00:07.1179181 with Status Code 200
[2021-05-06 00:20:29.903 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/9907a2e5f9f60dfe2b14607a56511b23/Images/Primary?fillHeight=461&fillWidth=307&tag=2aa31660abbe2050c75719c6d7fe760e&quality=90" to "127.0.0.1" in 0:00:17.4922933 with Status Code 200
[2021-05-06 00:20:29.916 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/118169f8e3d34c1282e64dfee37101ef/Images/Primary?fillHeight=461&fillWidth=307&tag=c82a8d4b9708210ce01d68db9f83997b&quality=90" to "127.0.0.1" in 0:00:10.4129483 with Status Code 200
[2021-05-06 00:20:29.961 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/5031f04d1748a6573025d496000d6f8a/Images/Primary?fillHeight=461&fillWidth=307&tag=0c2e47928158468f8bc3d77daf7a5648&quality=90" to "127.0.0.1" in 0:00:17.5540879 with Status Code 200
[2021-05-06 00:20:29.995 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/9b3f254a3f68c96a90d0ad8ea7b9fce2/Images/Primary?fillHeight=534&fillWidth=356&tag=f81b1ed9a92d00022ea6ba4c74cfdbc4&quality=90" to "127.0.0.1" in 0:00:02.9688472 with Status Code 200
[2021-05-06 00:20:30.029 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/dd2ccf7b92543f635e54812f546ff1ba/Images/Primary?fillHeight=534&fillWidth=356&tag=ec20729426553c6419fbc7989ab0dd8d&quality=90" to "127.0.0.1" in 0:00:02.9969159 with Status Code 200
[2021-05-06 00:20:30.122 +02:00] [WRN] Slow HTTP Response from "http://127.0.0.1:8096/Items/435d19f44dbbc7afd9a41a99be728a05/Images/Primary?fillHeight=534&fillWidth=356&tag=de53e076b32ab6cb3493cca4480552be&quality=90" to "127.0.0.1" in 0:00:03.090014 with Status Code 200
[2021-05-06 00:22:06.113 +02:00] [ERR] Cannot compute blurhash for "/mnt/HDDRIVE2GO/MetaData/People/S/Sharon Stone/poster.jpg"
System.IO.FileNotFoundException: File not found
File name: '/mnt/HDDRIVE2GO/MetaData/People/S/Sharon Stone/poster.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2021-05-06 00:30:01.331 +02:00] [ERR] IOException saving to "/mnt/HDDRIVE2GO/MetaData/People/S/Sharon Stone/poster.jpg". Will retry saving to "/mnt/HDDRIVE2GO/MetaData/library/01/01d075b55f50b727252c846f72568788/folder.jpg"
System.IO.IOException: Bad message
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, String retryPath, CancellationToken cancellationToken)
[2021-05-06 00:30:01.334 +02:00] [INF] Deleting previous image "/mnt/HDDRIVE2GO/MetaData/People/S/Sharon Stone/poster.jpg"
[2021-05-06 00:30:01.361 +02:00] [ERR] Error processing request: "Bad message". URL "POST" "/Items/01d075b55f50b727252c846f72568788/Images/Primary".

**Comment by hermanWinters** [comment]
I took part of the log which I think deals with the problem, you can see some remarks around the failure at the bottom of the log.

Thank you for your reply
