### ISSUE TITLE
Authentication issues after 10.7.5

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#6003]
**Describe the bug**
Maybe more of a question than a bug, but I'm having a lot of authentication issues after upgrade to 10.7.5. It seems like the token times out, and a new login is required (not needed previously). It's becoming quite annoying. If I look in Devices, items seem to be removed from there automatically, and all the old Devices I had were gone after the upgrade. I've cleared caches on all the devices but that doesn't seem to help. The Kodi addon has the problem too, and keeps prompting me to log in after a while.

**System (please complete the following information):**
 - OS: CentOS
 - Virtualization: Docker
 - Clients: Browser, Kodi, Android app, iOS app
 - Jellyfin Version: 10.7.5
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: bridge

**To Reproduce**
Upgrade to 10.7.5, log in and wait, I guess...

**Expected behavior**
Re-logins should not be necessary, at least not this frequently.

**Logs**
A lot of
```
Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
```

And also this (from using the latest beta Android app, so might be a bug):
```
[2021-05-07 09:08:07.099 +00:00] [ERR] [73] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Users/authenticatebyname".
System.ArgumentNullException: Value cannot be null. (Parameter 'appName')
   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
   at lambda_method22341(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by krutburken** [comment]
I've reverted to 10.7.1 for now as this is making Jellyfin very annoying to use.

**Comment by krutburken** [comment]
I just tried a new upgrade on a fresh backup, but instead went 10.7.1 > 10.7.2 >10.7.5, and now I had no authentication issues at all. No idea what's going here on but there weren't any instructions that this was necessary. Anyways, posted this here if others run into similar issues.

**Comment by rondadon** [comment]
I have the same issue (Desktop Client, WebUI and Android App) . 
But it started today while using 1.7.5 Docker Container the last weeks without any Problems.
But as of today, without any changes on the server side it started to ask me frequently for the Login Credentials The only thing changed is that I updated The Android Jellyfin Apps on my Android Devices from the 2.2.X Versions to the new 2.3.0 beta1.


Need to see how I can resolve this.

**Comment by krutburken** [comment]
> I have the same issue (Desktop Client, WebUI and Android App) .
> But it started today while using 1.7.5 Docker Container the last weeks without any Problems.
> But as of today, without any changes on the server side it started to ask me frequently for the Login Credentials The only thing changed is that I updated The Android Jellyfin Apps on my Android Devices from the 2.2.X Versions to the new 2.3.0 beta1.
> 
> Need to see how I can resolve this.

I just now realized that the android beta app is to blame for this. I decided to try it again, and all my devices + api keys got wiped right after I try to connect (and the error is logged). I'll make a new issue there instead.
