### ISSUE TITLE
Can't login to Jellyfin since upgrade to 10.7.2-1

### ISSUE THREAD

**Issue by nodiscc** [jellyfin/jellyfin#6012]
**Describe the bug**

Since upgrading to 10.7.2-1 (automatic upgrade thorugh `unattended-upgrades`) I can't login anymore to my jellyfin instance. After clicking the `Sign in` button a spinner appears and spins indefinitely. 

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: KVM
 - Clients: Browser
 - Browser: Firefox 78
 - Jellyfin Version: 10.7.2.1 (Debian package)
 - Playback: not relevant
 - Installed Plugins: LDAP
 - Reverse Proxy: apache
 - Base URL: /
 - Networking: NAT
 - Storage: local

**To Reproduce**

1. Access the jellyfin instance login page
2. Enter admin username/password, click Sign In
3. Spinner appears but spins indefinitely

**Expected behavior**

The jellyfin Home dashboard should appear

**Logs**
When loading the login form/page:

```
May  8 00:03:09 home jellyfin[23543]: [00:03:09] [ERR] An exception occurred while iterating over the results of a query for context type 'Jellyfin.Server.Implementations.JellyfinDb'.
May  8 00:03:09 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:03:09 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:03:09 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:03:09 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:03:09 home jellyfin[23543]: [00:03:09] [ERR] Error processing request. URL GET /DisplayPreferences/usersettings.
May  8 00:03:09 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:03:09 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:03:09 home jellyfin[23543]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
May  8 00:03:09 home jellyfin[23543]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Implementations.Users.DisplayPreferencesManager.ListCustomItemDisplayPreferences(Guid userId, Guid itemId, String client)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)
May  8 00:03:09 home jellyfin[23543]:    at lambda_method501(Closure , Object , Object[] )
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
May  8 00:03:09 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
May  8 00:03:09 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May  8 00:03:09 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May  8 00:03:09 home jellyfin[23543]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May  8 00:03:09 home jellyfin[23543]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May  8 00:03:09 home jellyfin[23543]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May  8 00:03:09 home jellyfin[23543]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
May  8 00:03:09 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

When clicking `Sign In`:

```
May  8 00:07:07 home jellyfin[23543]: [00:07:07] [INF] Authentication request for XYZ has succeeded.
May  8 00:07:07 home jellyfin[23543]: [00:07:07] [INF] Current/Max sessions for user XYZ: 1/0
May  8 00:07:07 home jellyfin[23543]: [00:07:07] [INF] Reissuing access token: fe5f72ead115456cbbe3f47bb3d1febf
May  8 00:07:07 home jellyfin[23543]: [00:07:07] [ERR] An exception occurred while iterating over the results of a query for context type 'Jellyfin.Server.Implementations.JellyfinDb'.
May  8 00:07:07 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:07:07 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:07:07 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:07:07 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:07:07 home jellyfin[23543]: [00:07:07] [ERR] Error processing request. URL GET /DisplayPreferences/usersettings.
May  8 00:07:07 home jellyfin[23543]: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
May  8 00:07:07 home jellyfin[23543]:    at lambda_method661(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  8 00:07:07 home jellyfin[23543]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
May  8 00:07:07 home jellyfin[23543]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Implementations.Users.DisplayPreferencesManager.ListCustomItemDisplayPreferences(Guid userId, Guid itemId, String client)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)
May  8 00:07:07 home jellyfin[23543]:    at lambda_method501(Closure , Object , Object[] )
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
May  8 00:07:07 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
May  8 00:07:07 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May  8 00:07:07 home jellyfin[23543]: --- End of stack trace from previous location ---
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May  8 00:07:07 home jellyfin[23543]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May  8 00:07:07 home jellyfin[23543]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May  8 00:07:07 home jellyfin[23543]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May  8 00:07:07 home jellyfin[23543]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
May  8 00:07:07 home jellyfin[23543]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/3950390/117513175-b73f8480-af80-11eb-86d3-62aa91c2e7fd.png)

**Additional context**

**Comment by lyz-code** [comment]
You can try the patches suggested in [#2507](https://github.com/jellyfin/jellyfin-web/issues/2507) until it's fixed

**Comment by nodiscc** [comment]
I worked around it by uninstalling jellyfin, removing the data/db directory, reinstalling and re-doing my library setup (configuration lost but it needed a cleanup anyway)
