### ISSUE TITLE
Unstable: PlayListFolder not in Enum BaseItemKind. 

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#6016]
**Might not be the latest unstable**

Caused by a library update.

```
System.ArgumentException
  HResult=0x80070057
  Message=Requested value 'PlaylistsFolder' was not found.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse[TEnum](String value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.Parse[TEnum](String value, Boolean ignoreCase)
   at System.Enum.Parse[TEnum](String value)
   at MediaBrowser.Controller.Entities.BaseItem.GetBaseItemKind() in F:\Code\Jellyfin\MediaBrowser.Controller\Entities\BaseItem.cs:line 2003
   at Emby.Server.Implementations.Dto.DtoService.AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, DtoOptions options) in F:\Code\Jellyfin\Emby.Server.Implementations\Dto\DtoService.cs:line 907
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner) in F:\Code\Jellyfin\Emby.Server.Implementations\Dto\DtoService.cs:line 227
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner) in F:\Code\Jellyfin\Emby.Server.Implementations\Dto\DtoService.cs:line 132
   at Jellyfin.Api.Controllers.LibraryController.<>c__DisplayClass22_0.<GetMediaFolders>b__2(BaseItem i) in F:\Code\Jellyfin\Jellyfin.Api\Controllers\LibraryController.cs:line 512
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Jellyfin.Api.Controllers.LibraryController.GetMediaFolders(Nullable`1 isHidden) in F:\Code\Jellyfin\Jellyfin.Api\Controllers\LibraryController.cs:line 509
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by BaronGreenback** [comment]
Updated unstable - fixed issue.
