### ISSUE TITLE
JF 10.7.5 Changed Library Path and now library scan fails

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin#6035]
**Describe the bug**
Changed library path from X:\Media\xxxxxx to P:\Media\xxxxx and scanned library, scan fails

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: No
 - Clients: Browser
 - Browser: Chrome 90 Stable
 - Jellyfin Version: 10.7.2-10.7.5
 - Playback: N/A
 - Installed Plugins: TVDB, Trakt
 - Reverse Proxy: None
 - Base URL: None
 - Networking: N/A
 - Storage: from rclone mounted GDrive (X:) to unraid local SMB share (P:)

**To Reproduce**

1. Go to Settings -> Dashboard -> Libraries
2. Click on "Manage Library"
3. Change library folder path 
4. Scan library, have it fail

**Expected behavior**
Jellyfin should update the database with the new location and scan and remove files as needed

**Logs**
```
00] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2021-05-12 08:43:26.053 -05:00] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Stopping 
directory watching for path "P:\Movies"
[2021-05-12 08:43:26.056 -05:00] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Stopping 
directory watching for path "P:\Anime"
[2021-05-12 08:43:26.062 -05:00] [INF] [25] Emby.Server.Implementations.Library.LibraryManager: 
Validating media library
[2021-05-12 08:44:16.717 -05:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching 
directory P:\Anime
[2021-05-12 08:44:16.717 -05:00] [ERR] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: 
Error
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: 
map[AiredSeason:2]
at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, 
CancellationToken cancellationToken)
at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, 
Object key, Func`2 factory)
at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.GetAllEpisodes(Int32 tvdbId, String 
acceptedLanguage, EpisodeQuery episodeQuery)
at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.HandleSeason(Season season)
at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnProviderManagerRefreshComplete(Object 
sender, GenericEventArgs`1 genericEventArgs)
at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshComplete(BaseItem item)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, 
CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, 
CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, 
CancellationToken cancellationToken)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken 
cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, 
IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, 
CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, 
MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, 
CancellationToken cancellationToken)
at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, 
CancellationToken cancellationToken)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-05-12 08:44:16.720 -05:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching 
directory P:\Movies
[2021-05-12 08:44:16.734 -05:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: 
"Scan Media Library" Failed after 0 minute(s) and 50 seconds
[2021-05-12 08:44:16.738 -05:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: 
ExecuteQueuedTasks
```

**Screenshots**

**Additional context**
Libraries were working fine when set to X: drive (rclone mounted GDrive), but recently created a new NAS and wanted JF reading media from a local drive, so I went in and added the P: drive and removed the X: drive from all the library paths, and when I tried to scan, the scan would get to about 34% and then just stop. Logs attached. It doesn't seem to be a NAS issue as I can open up my share in File Explorer and paths and files open and play without issue. I also booted up Emby and Plex installs and all seems to be working well there too, so it seems isolated to Jellyfin in particular.

**Comment by Jinxyface** [comment]
Slgith update. After tinkering around and not being able to fix it. I decided to nuke my server and start over (thankfully had my watch history sync'd to Trakt), and I was able to add my P: drive folders no problem, and subsequent library updates after adding new media works too.

Not sure what the issue is. I can close this issue if you want unless you want to investigate.
