### ISSUE TITLE
Images don't load when in "Edit Images" window

### ISSUE THREAD

**Issue by AjayACST** [jellyfin/jellyfin#6039]
When clicking on Edit Images and then search no images load. Also when using Identify media and selecting "Replace existing images" no images get added for the media.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Clients: Browser
 - Browser: Edge 90
 - Jellyfin Version: 10.7.5 stable
 - Playback: N/A
 - Installed Plugins: AudioDB 10.7.5.0, MusicBrainz 10.7.5.0, OMDb 10.7.5.0
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. Click the 3 dots on any type of media
2. Click edit images
3. Click search
4. No images appear to select from

**Expected behavior**
Images appear that can be selected from.

**Logs**
```
[2021-05-12 20:24:07.534 +00:00] [ERR] "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/home/arrow/TV-Shows/Saturday-Night-Live"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable
```
![image](https://user-images.githubusercontent.com/35202521/118040220-6935e100-b3c5-11eb-9a23-3ac8486cc468.png)

**Comment by Bond-009** [comment]
Should be fixed by #5806
