### ISSUE TITLE
Errors loading EPG for LiveTV

### ISSUE THREAD

**Issue by MOPO3KO** [jellyfin/jellyfin#6085]
Errors loading EPG for LiveTV.
it takes a very long time to load the EPG this is probably for mistakes

 - OS: synology DSM
 - Virtualization: Docker
 - Jellyfin Version: 10.7.5 latest
 - Installed Plugins: none

viewing the log

**Logs**
```
[2021-05-21 04:00:03.376 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 04:00:03.376 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Downloading xmltv listings from "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 04:00:03.514 +00:00] [ERR] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-4.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 04:00:06.586 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Found epg channel in "XmlTV" null "2x2 +2" "2na2-pl2"
[2021-05-21 04:00:06.586 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Found epg channel in "XmlTV" null "2x2 +4" "2na2-pl4"

..............

System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 04:02:17.945 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 04:02:17.946 +00:00] [ERR] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-4.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 04:02:27.901 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 04:02:27.927 +00:00] [ERR] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-4.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 04:02:37.818 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 04:02:37.819 +00:00] [ERR] [52] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-4.xml"

....................

[2021-05-21 05:19:39.754 +00:00] [INF] [45] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 05:19:39.754 +00:00] [ERR] [45] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-5.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 05:19:48.651 +00:00] [ERR] [45] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "РўСЂРѕС„РµР№ HD"
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at MediaBrowser.Common.Extensions.BaseExtensions.GetMD5(String str)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetProgramInfo(XmlTvProgram program, ListingsProviderInfo info)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[2021-05-21 05:19:48.653 +00:00] [INF] [45] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://192.168.13.150:8085/epg.xml.gz"
[2021-05-21 05:19:48.654 +00:00] [ERR] [45] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file "/cache/xmltv/141-5.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
[2021-05-21 05:19:57.517 +00:00] [ERR] [45] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "РЈРЅРёР°РЅ HD PREMIUM+"
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at MediaBrowser.Common.Extensions.BaseExtensions.GetMD5(String str)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetProgramInfo(XmlTvProgram program, ListingsProviderInfo info)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
```
Added my EPG file
[epg.xml.gz](https://github.com/jellyfin/jellyfin/files/6622718/epg.xml.gz)

**Comment by c4tz** [comment]
Can confirm this, I have the same problem with [this EPG file](http://ricxepg.nl/epg_data/rytecDE_Basic.gz): 

```
jellyfin       | [12:53:36] [INF] [90] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: http://ricxepg.nl/epg_data/rytecDE_Basic.gz
jellyfin       | [12:53:36] [ERR] [90] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Error extracting from gz file /cache/xmltv/157-12.xml
jellyfin       | System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
jellyfin       |    at System.IO.Path.Combine(String path1, String path2)
jellyfin       |    at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
jellyfin       |    at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
jellyfin       |    at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
jellyfin       |    at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
```

Maybe it happens because the XML file inside the `.gz` archive has no extension?

When I download it myself, extract the file, add `.xml` to the filename and give Jellyfin the local path, it seems to work flawlessly.

**Comment by alexlo0** [comment]
The same here!

Records in log are
```
[2021-09-20 22:49:26.000 +03:00] [INF] xmltv path: "http://programtv.ru/xmltv.xml.gz"
[2021-09-20 22:49:26.002 +03:00] [ERR] Error extracting from gz file "/var/cache/jellyfin/xmltv/263-19.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(String originalUrl, String file)
```
repeating a dozens of times.

The file at "/var/cache/jellyfin/xmltv/263-19.xml" is actually gzipped:
```
# file /var/cache/jellyfin/xmltv/263-19.xml
/var/cache/jellyfin/xmltv/263-19.xml: gzip compressed data, max compression, from Unix, original size 14217241

# less /var/cache/jellyfin/xmltv/263-19.xml
"/var/cache/jellyfin/xmltv/263-19.xml" may be a binary file.  See it anyway?

# zcat /var/cache/jellyfin/xmltv/263-19.xml | head
<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE tv SYSTEM "http://programtv.ru/xmltv.dtd">
    <tv generator-info-name="PHP7" generator-info-url="http://programtv.ru/">
    <channel id="146">
      <display-name>Первый</display-name>
      <icon src="http://avatars.mds.yandex.net/get-tv-channel-logos/70787/2a000001600801d5c4aa045cec97f5f97429/orig" />
      </channel>
      <channel id="711">
      <display-name>Россия 1</display-name>
      <icon src="http://avatars.mds.yandex.net/get-tv-channel-logos/69315/2a000001600802e50cac6946ca740c0e44f2/orig" />
      </channel>
```

**Comment by Bond-009** [comment]
Upstream issue

https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Common/ExtractionMethods.cs#L38-L39

https://github.com/adamhathcock/sharpcompress/issues/443
https://github.com/adamhathcock/sharpcompress/issues/475

**Comment by bonswouar** [comment]
@cvium @Bond-009 As it doesn't seem to be on the course of being fixed upstream, as shown in this quote:
> The WriteEntryToDirectory type methods are extensions to make common scenarios easy but it doesn't handle everything

Wouldn't it be possible to re-use what's working from `ExtractFirstFileFromGz`:
```c#
                reader.WriteEntryToFile(Path.Combine(targetPath, filename));
```
By simply looping on `reader.MoveToNextEntry()`, and generate some filename if needed?

Or even get rid of this library? (https://stackoverflow.com/questions/24138373/unzip-gz-file-using-c-sharp)

_FYI I'm using the XMLs from https://github.com/iptv-org/epg, which seems to be one of the most popular free EPG source (?). As you can see ([here](https://github.com/iptv-org/epg/blob/master/scripts/commands/guides/update.js#L38)) those gz are created automatically, each containing one XML file, with a couple of very basic JS lines using npm-gzip library._

**Comment by SimonPhoenix96** [comment]
regarding the m3u files provided by [iptv-org](https://github.com/iptv-org/iptv), they seem to have some guide data included in the m3u file under the **x-tvg-url** tag located at the top of the m3u file

is there anyway to change the parsing of those files to use that instead of manually finding and adding the guides?
