### ISSUE TITLE
GET /users/public -> 500, User.HasPermissions "Sequence contains no matching element" crash

### ISSUE THREAD

**Issue by chadmiller** [jellyfin/jellyfin#6109]
Starting a stopped Jellyfin instance in an up-to-date docker image from official "jellyfin/jellyfin" docker repo on Ubuntu 20.04-ish.

Initial log-in-screen asks to select server. (That's unlike first start!) Upon clicking on the only choice, and redirected to `/web/index.html`, the we page doesn't render anything. Opening browser tools shows network listing. The only error item is HTTP 500 from `/users/public`.

No unusual request headers are sent. Response is empty document after HTTP 500.

Log says `Jellyfin version: 10.7.5` ... 

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Data.Entities.User.HasPermission(PermissionKind kind)
   at Jellyfin.Api.Controllers.UserController.<>c__DisplayClass23_0.<Get>b__0(User i)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   ...
```

**Comment by chadmiller** [comment]
Don't be a punk, 'bot.

**Comment by cvium** [comment]
Did you put the /data folder in a volume or bind mount?

**Comment by chadmiller** [comment]
My docker-compose, using image "jellyfin/jellyfin" has volumes for `/media` (ro) , `/config` , and `/cache` .

Beneath the volume for `/config/` , there is a `data/` directory. data itself isn't unusual or named anywhere.

**Comment by chadmiller** [comment]
Note, this doesn't happen presently. I suspect it has something to do with name resolution (browser to mdns-advertized name?) or a failure cascading off of that.

I am reporting this because there's probably a test higher that could avoid the crashing code path, like an emptiness test before first() .

**Comment by covertneko** [comment]
Just adding that this happens to me almost every time I update my jellyfin docker container. No idea what's going on, but clearing my cache, trying different browsers, different machines, and connecting via IP all yield the same result until I roll back.

**Comment by Salamandar** [comment]
Trying to use 10.8.0-alpha5 triggered this issue. I could not solve this.

**Comment by marine1988** [comment]
i have same problem now i cant get back to stable version :(

**Comment by chadmiller** [comment]
@marine1988 , sounds like you have a reproducible case! Do you mind taking a snapshot of your data so we can give it to devs to debug? I can help with reducing it and preparing it. Upload a zip or tar file somewhere?

**Comment by Koritha** [comment]
> Trying to use 10.8.0-alpha5 triggered this issue. I could not solve this.

I'm having this exact same issue. I'm unable to solve it, besides a total wipe of my jellyfin docker install.

**Comment by Koritha** [comment]
I had a backup of my database also. But I'm unable to use the 10.8.0 alpha at all. I'm hoping this won't be an issue come the final release, or I'll need to wipe my jellyfin install and start from scratch.

**Comment by ocervell** [comment]
same here, stuck on 10.8.0-alpha5, cannot revert back to 10.7.

**Comment by 1337joe** [comment]
Looks like #7505 duplicates this, is anyone affected able to see if #7506 fixes it for them?

**Comment by Salamandar** [comment]
@1337joe is there any way to provide me a prebuilt .deb or executable with the patch ? :s

**Comment by 1337joe** [comment]
That's not something I know how to do (I run either from Docker or my dev environment), but now that it's merged the next beta release should bundle it for distribution.

**Comment by Salamandar** [comment]
Thanks, I will try to find some time and test it when the moment comes.

**Comment by Salamandar** [comment]
I just tested the 10.8.0-beta2 and it seems to work. I got some error in the logs I've never seen, but I can log in and watch videos.


Here's the weird log FYI : 
```
May 02 10:26:31 salamandar.fr jellyfin[2103885]: [10:26:31] [ERR] [10] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 10.10.10.0 to 239.255.255.250:1900
May 02 10:26:31 salamandar.fr jellyfin[2103885]: System.Net.Sockets.SocketException (0xFFFDFFFE): Unknown socket error
May 02 10:26:31 salamandar.fr jellyfin[2103885]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddres>
May 02 10:26:31 salamandar.fr jellyfin[2103885]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
May 02 10:26:31 salamandar.fr jellyfin[2103885]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
May 02 10:26:31 salamandar.fr jellyfin[2103885]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

**Comment by Salamandar** [comment]
Still doesn't work with 10.8.0-beta2.

I was still connected and it failed with this :

```
May 02 10:37:04 salamandar.fr jellyfin[2112612]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:25 salamandar.fr jellyfin[2112612]: [10:37:25] [WRN] [20] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
May 02 10:37:26 salamandar.fr jellyfin[2112612]: [10:37:26] [ERR] [31] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/etc/jellyfin/users/salamandar/profile.png'. URL GET /Users/245e4ae3ead8421ba7c7395d346d797b/Images/Primary.
May 02 10:37:34 salamandar.fr jellyfin[2112612]: [10:37:34] [ERR] [29] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/245e4ae3ead8421ba7c7395d346d797b/Views.
May 02 10:37:34 salamandar.fr jellyfin[2112612]: System.InvalidOperationException: Sequence contains no matching element
```

So I disconnected from my account and then this occurred (again):

```
May 02 10:38:42 salamandar.fr jellyfin[2112612]: [10:38:42] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /users/public.
May 02 10:38:42 salamandar.fr jellyfin[2112612]: System.InvalidOperationException: Sequence contains no matching element
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.ThrowHelper.ThrowNoMatchException()
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Data.Entities.User.HasPermission(PermissionKind kind)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Api.Controllers.UserController.<>c__DisplayClass25_0.<Get>b__0(User i)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
May 02 10:38:42 salamandar.fr jellyfin[2112612]: --- End of stack trace from previous location ---
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
May 02 10:38:42 salamandar.fr jellyfin[2112612]: --- End of stack trace from previous location ---
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
May 02 10:38:42 salamandar.fr jellyfin[2112612]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by crobibero** [comment]
@Salamandar Can you please send me your jellyfin.db? I'm having difficulty recreating this issue.
I'm `_cody#4113` on discord, `@codeh:matrix.org` on matrix.

**Comment by korewaChino** [comment]
I'm also having this issue trying to upgrade from 10.8.0-beta2 to 10.8.4.

**Comment by korewaChino** [comment]
not stale

**Comment by TTcheng** [comment]
I'm also having this issue trying to upgrade from 10.8.0 to 10.8.13,To avoid it, I have to downgrade it back to 10.8.1

**Comment by KOPElan** [comment]
have the same issue, repo: keep volume binding and recreate container.  unless delete the folder ‘/config/data’
