### ISSUE TITLE
Jellyfin 10.8.0.0 unstable - Startup fail due to DB crash

### ISSUE THREAD

**Issue by peperunas** [jellyfin/jellyfin#6112]
**Describe the bug**
Jellyfin 10.8.0.0 unstable does not start due to the SQLite database being queried with an invalid query.

**System (please complete the following information):**
 - OS: Gentoo
 - Virtualization: Docker
 - Clients: None
 - Browser: None
 - Jellyfin Version: 10.8.0.0
 - Playback: None
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: traefik
 - Base URL: None
 - Networking: NAT
 - Storage: Local

**To Reproduce**
Start-up the official unstable docker container.

**Expected behavior**
Jellyfin starts up correctly.

**Server Logs**

```
jellyfin              | [18:12:48] [INF] [1] Main: Jellyfin version: 10.8.0
jellyfin              | [18:12:48] [INF] [1] Main: Environment Variables: ["[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_DATA_DIR, /config]"]
jellyfin              | [18:12:48] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
jellyfin              | [18:12:48] [INF] [1] Main: Operating system: Linux
jellyfin              | [18:12:48] [INF] [1] Main: Architecture: X64
jellyfin              | [18:12:48] [INF] [1] Main: 64-Bit Process: True
jellyfin              | [18:12:48] [INF] [1] Main: User Interactive: True
jellyfin              | [18:12:48] [INF] [1] Main: Processor count: 4
jellyfin              | [18:12:48] [INF] [1] Main: Program data path: /config
jellyfin              | [18:12:48] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
jellyfin              | [18:12:48] [INF] [1] Main: Application directory: /jellyfin/
jellyfin              | [18:12:48] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
jellyfin              | [18:12:48] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
jellyfin              | [18:12:48] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles_10.0.0.0/OpenSubtitlesHandler.dll
jellyfin              | [18:12:49] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles_10.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
jellyfin              | [18:12:49] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
jellyfin              | [18:12:49] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
jellyfin              | [18:12:49] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
jellyfin              | [18:12:49] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
jellyfin              | [18:12:49] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
jellyfin              | [18:12:51] [FTL] [1] Main: Error while starting server.
jellyfin              | Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Preferences.UserId, Preferences.Kind'.
jellyfin              |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
jellyfin              |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
jellyfin              |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
jellyfin              |    at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider, IApplicationPaths appPaths)
jellyfin              |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
jellyfin              |    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
jellyfin              |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
jellyfin              |    at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
jellyfin              |    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
jellyfin              |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin              | [18:12:51] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
jellyfin              | [18:12:51] [FTL] [1] Main: Unhandled Exception
jellyfin              | Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Preferences.UserId, Preferences.Kind'.
jellyfin              |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
jellyfin              |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
jellyfin              |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
jellyfin              |    at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider, IApplicationPaths appPaths)
jellyfin              |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin              |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin              | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Preferences.UserId, Preferences.Kind'.
jellyfin              |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
jellyfin              |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
jellyfin              |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
jellyfin              |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
jellyfin              |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
jellyfin              |    at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider, IApplicationPaths appPaths)
jellyfin              |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin              |    at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by crobibero** [comment]
Was this an upgrade from stable (10.7.5) or a fresh install?

**Comment by peperunas** [comment]
I would say unstable to unstable. This setup was working properly until the image was stopped, updated and restarted.

**Comment by kevincaradant** [comment]
Hi

from 10.7.5 unstable to 10.8.0 unstable, I got the same issue, and I don't know what should I do.
I confirm it worked well before to stop and update the docker image.

Regards

**Comment by Gopikrishna19** [comment]
I would like to tag #6129 here. There is a problem with SQLite versions, I am still looking for an answer. If you are using NFS, don't. It was working for me as well, but not anymore.

**Comment by Lyky35** [comment]
From looks as its again the case that upgrade process still doesn't utilize "drop/alter if exists", and fails to upgrade the sqlite...

If you are looking for solution you need to look up (compare) clean 10.8 sqlite files, and your own; then using sqlite file editor and alter their columns to what it expects to be.

**Comment by dmitrylyzo** [comment]
I had the same issue one day: multiple `RowVersion` of the same *Guid+Kind.
I had to apply this SQL to `jellyfin.db`:
```sql
DELETE FROM Preferences WHERE Id NOT IN (SELECT Id FROM (SELECT Id, Preference_Preferences_Guid, Kind, MAX(RowVersion) FROM Preferences GROUP BY Preference_Preferences_Guid, Kind));
DELETE FROM Permissions WHERE Id NOT IN (SELECT Id FROM (SELECT Id, Permission_Permissions_Guid, Kind, MAX(RowVersion) FROM Permissions GROUP BY Permission_Permissions_Guid, Kind));
```
_Stop Jellyfin server and backup `jellyfin.db` first_

**Comment by kevincaradant** [comment]
@dmitrylyzo thank you for this answer, simple to apply :)

Just to help guys, who are not used SQL every day

1st step: backup your jellyfin.db file

2sd step: install the lib sqlite3 like `apt get install sqlite3` under Ubuntu

3th step: Execute each command mentioned before like that  `sqlite3 jellyfin.db "DELETE FROM Permissions WHERE Id NOT IN (SELECT Id FROM (SELECT Id, Permission_Permissions_Guid, Kind, MAX(RowVersion) FROM Permissions GROUP BY Permission_Permissions_Guid, Kind));"`  

3

**Comment by sevenrats** [comment]
close stale issue for obsolete unstable version.
