### ISSUE TITLE
Transcoding does not stop due to HTTP 500 error - latest master

### ISSUE THREAD

**Issue by acvigue** [jellyfin/jellyfin#6141]
**Describe the bug**
Title

**System (please complete the following information):**
 - OS: Ununtu 20.04
 - Virtualization: Docker
 - Clients: N/A - occurs on any tested
 - Browser: N/A
 - Jellyfin Version: latest master 1e1e9dbb587c35acd17a81117114b356d5dcc8a1
 - Playback: Transcodes
 - Installed Plugins: Default set - none added
 - Reverse Proxy: Nginx w/ SSL
 - Base URL: none
 - Networking: host
 - Storage: local bind

**To Reproduce**
play item
watch item
try to stop item
(if item is transcoding, the .ts files are still generated and not deleted at this point, the /Sessions/Playing/Stopped endpoint returns 500 in browser console)

**Expected behavior**
Playback stops and transcoded files are deleted just like in latest stable

**Server Logs**
```
[2021-06-02 18:25:16.526 +00:00] [ERR] [36] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/Playing/Stopped".
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at Jellyfin.Api.Helpers.TranscodingJobHelper.KillTranscodingJob(TranscodingJobDto job, Boolean closeLiveStream, Func`2 delete)
   at Jellyfin.Api.Controllers.PlaystateController.ReportPlaybackStopped(PlaybackStopInfo playbackStopInfo)
   at lambda_method1148(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2021-06-02 18:25:25.901 +00:00] [ERR] [26] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/config/data/metadata/People/J/Joe Taslim/folder.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2021-06-02 18:25:57.726 +00:00] [WRN] [36] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://zeus:8097/Users/1d45ac459e2242008906cb48d46d366f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio" to "192.168.0.224" in 0:00:00.5237464 with Status Code 200
[2021-06-02 18:25:57.728 +00:00] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://zeus:8097/Users/1d45ac459e2242008906cb48d46d366f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book" to "192.168.0.224" in 0:00:00.5255393 with Status Code 200
[2021-06-02 18:26:00.973 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://zeus:8097/Users/1d45ac459e2242008906cb48d46d366f/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805" to "192.168.0.224" in 0:00:03.7708286 with Status Code 200
[2021-06-02 18:26:01.529 +00:00] [WRN] [40] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://zeus:8097/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath&UserId=1d45ac459e2242008906cb48d46d366f&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=true" to "192.168.0.224" in 0:00:00.6336972 with Status Code 200
[2021-06-02 18:26:17.086 +00:00] [INF] [38] Jellyfin.Api.Helpers.TranscodingJobHelper: Transcoding kill timer stopped for JobId "b7696b0acf6e4d498c9d064ab6d91e17" PlaySessionId "d7a8876b79924403998766ba062581e8". Killing transcoding
[2021-06-02 18:26:17.087 +00:00] [FTL] [17] Main: Unhandled Exception
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at Jellyfin.Api.Helpers.TranscodingJobHelper.KillTranscodingJob(TranscodingJobDto job, Boolean closeLiveStream, Func`2 delete)
   at Jellyfin.Api.Helpers.TranscodingJobHelper.OnTranscodeKillTimerStopped(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**FFmpeg Logs**
https://pastebin.com/raw/Dryxnhxa

**Browser Console Logs**
<img width="1295" alt="Screen Shot 2021-06-02 at 2 25 38 PM" src="https://user-images.githubusercontent.com/34462061/120533123-6881e080-c3ae-11eb-82f2-cce1058f0cb1.png">
request body for this:
```
{"VolumeLevel":100,"IsMuted":false,"IsPaused":true,"RepeatMode":"RepeatNone","ShuffleMode":"Sorted","MaxStreamingBitrate":140000000,"PositionTicks":54420658,"PlaybackStartTimeTicks":16226582977870000,"AudioStreamIndex":1,"BufferedRanges":[],"PlayMethod":"Transcode","PlaySessionId":"d7a8876b79924403998766ba062581e8","PlaylistItemId":"playlistItem0","MediaSourceId":"13dc26ba80201c5ebf7e630efbae0d80","CanSeek":true,"ItemId":"13dc26ba80201c5ebf7e630efbae0d80","NowPlayingQueue":[{"Id":"13dc26ba80201c5ebf7e630efbae0d80","PlaylistItemId":"playlistItem0"}]}
```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by acvigue** [comment]
confirmed fixed
