### ISSUE TITLE
Cant deserialize "The Open Movie Database" and cant write to cache json

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [jellyfin/jellyfin#6157]
**Describe the bug**
After rescanning the libary these errors come up. In the cache folders the the jsons are located there are just 0 byte files. It probaly has something todo with the .net premissions bug that was already a problem in: https://github.com/jellyfin/jellyfin/pull/5106 The other thing is some kind of problem with the json api of "The Movie Database". Maybe the API changed?

**System (please complete the following information):**
 - OS: Ubuntu Server
 - Virtualization: Docker
 - Clients: Browser
 - Jellyfin Version: 10.7.5
 - Reverse Proxy:  nginx
 - Storage: samba

**To Reproduce**
Rescan libaries

**Server Logs**
```
[2021-06-06 17:19:17.150 +00:00] [ERR] [27] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "The Open Movie Database"
System.ArgumentNullException: Value cannot be null. (Parameter 'text')
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromString[T](String text)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetRootObject(String imdbId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.Fetch[T](MetadataResult`1 itemResult, String imdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetMovieResult[T](ItemLookupInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

```
[2021-06-06 16:58:53.604 +00:00] [ERR] [22] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "The Open Movie Database"
System.UnauthorizedAccessException: Access to the path '/cache/omdb/tt1628033_season_17.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at Emby.Server.Implementations.Serialization.JsonSerializer.SerializeToFile(Object obj, String file)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetSeasonRootObject(String imdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by srcrist** [comment]
Closing this issue as stale. It appears to have been abandoned by submitter.
