### ISSUE TITLE
Custom Genres for TV/Film not working properly

### ISSUE THREAD

**Issue by moosepolice** [jellyfin/jellyfin#6164]
**Describe the bug**
Adding a custom genre will show it on the TV/Movie description page but are not being displayed in the Genre section. Clicking on the custom genre will take you to a new page with an endless loading icon. Custom genres are displayed in the Library filter and show content if the filter is selected. Affects both TV and Movies.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Linux (no docker)
 - Clients: Browser, Android
 - Browser: Firefox 89
 - Jellyfin Version: 10.7.5
 - Installed Plugins: AniDB, AudioDB, Fanart, OMDb, Open Subtitles, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Storage: local

**To Reproduce**
1. Go to a movie or a tv show and click edit Metadata
2. Add a new custom genre like Superhero or Cyberpunk, then save
3. Click on the new genre in the show or movie description page, this will trigger endless loading gif
4. Go to TV show or movie main library, select Genre in the top menu. You will not find the new custom genre
5. Select the library filter, you will be able to see the new custom genre and clicking on it will show items with said genre
6. The issue is apparent with both web client as well as the Android app.
7. For some reason, adding "Anime" as a new custom genre work, but nothing else I have tried.

**Expected behavior**
A new custom genre should act as the default genres fetched from metadata sources. It should appear in the Genre page and clicking on it on an item's description page should take you to the Genre page.

**Server Logs**
This appears in the logs when you click on the custom genre in a tv show or movie description page:

```
[2021-06-08 12:23:30.618 -04:00] [ERR] Error processing request. URL "GET" "/Users/36d6516a40f84dbbb84b1c6819e80270/Items/3419b6d0a34b7dd604f2e44ad086c9a9".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method937(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Screenshots**
Clicking the custom genre "Superhero" in the TV/Movie description page...
![G52Ed8a](https://user-images.githubusercontent.com/85576297/121226940-0ff08e80-c859-11eb-9171-69f49714f080.png)

Takes you to this, and it just keeps spinning:
![wdWWwYH](https://user-images.githubusercontent.com/85576297/121227035-2565b880-c859-11eb-9c0a-67772919f508.png)

The new custom genre also does not appear here:
![jpI20eB](https://user-images.githubusercontent.com/85576297/121227132-40382d00-c859-11eb-9178-3569220a004f.png)

But is does show up in the library filter:
![image](https://user-images.githubusercontent.com/85576297/121227255-5cd46500-c859-11eb-833e-5ee4336ef68b.png)

**Additional context**
For some reason, adding "Anime" as a new custom genre work, but nothing else I have tried.

**Comment by neilsb** [comment]
I've confirmed the same thing happening on Docker Nightly, right down to Anime working and others not.

On the "Endless Looping Icon", what I observe is that this eventually clears but it looks like all media on the server is displayed (TV Episodes, Movies, Music, etc etc) on the single page.

**Comment by mattryanmtl** [comment]
I am getting the exact same isssue, down to the same error in the logs.

**Comment by cosmiccoincidence** [comment]
I'm new to Jellyfin (using it for about a week now) and am having this issue myself currently.

It also appears it may be related to #3408

**Comment by waltlawsmacd** [comment]
I am seeing the same bug (same behavior and logs)

**Comment by Bond-009** [comment]
The nullref is fixed in master, but the infinite loading isn't

**Comment by Ay1tsMe** [comment]
Experience same thing with certain genres for songs. I have an album that has multiple genre tags. The tag "Hard Rock" works but "Glam Rock" leads to infinite loading screen

**Comment by theguymadmax** [comment]
Tested on the master branch of the web repo, and the issue is resolved.
