### ISSUE TITLE
Plexdrive and Jellyfin cannot find new files

### ISSUE THREAD

**Issue by herodev1337** [jellyfin/jellyfin#6212]
_Crosspost from https://github.com/plexdrive/plexdrive/issues/398 hoping somebody can help me._

Hey,
I'm using plexdrive in combination with jellyfin. It works perfectly besides that it cant find new files I (as it turns out only for movies) added while plexdrive is mounted.

Jellyfin logs says:
```
[ERR] [103] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.IOException: Input/output error
at System.IO.Enumeration.FileSystemEnumerator1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength) at System.IO.Enumeration.FileSystemEnumerator1.MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator2.MoveNext() at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items) at System.Collections.Generic.SparseArrayBuilder1.ReserveOrAdd(IEnumerable1 items) at System.Linq.Enumerable.Concat2Iterator1.ToArray()
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
```
My mount command: ./plexdrive mount -c /root/.plexdrive -o allow_other -v 4 --drive-id=XXX -v 4 /media

My workaround is:
1. kill plexdrive and start an rclone mount
2. Start a jellyfin Libary scan
3. When complete, end rclone mount, delete cache.bolt and then restart plexdrive

I'm using the newest plexdrive and the newest jellyfin (10.7.6)

Thanks for your help

**Comment by srcrist** [comment]
Closing issue as it does not contain an actual Jellyfin bug. Your log shows that Jellyfin is having trouble accessing the storage you've provided.
