### ISSUE TITLE
move folders in music library detected but error on processing 

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#6229]
**Describe the bug**

On changing the folder structure for a 4 disc piece of music to the recommended structure, i.e. from

Album name CD1
Album name CD2
Album name CD3
Album name CD4

To 
Album name \ Disc 1
Album name \ Disc 2
Album name \ Disc 3
Album name \ Disc 4

I carried out the change of structure by renaming folders and moving files

An error occurred in the log, and the music/folders are no longer showing in Jellyfin

Tried scan library, and the issue is not resolved
Restarted Jellyfin, scan libraries, album still does not appear

**System (please complete the following information):**
 - OS: Ubunto 18.04 LTS
 - Virtualization: None
 - Clients: Android
 - Browser: Firefox 89.0.1
 - Jellyfin Version: 10.7.6
 - Playback:  N/A - Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: simple LAN
 - Storage: Software raid, BTRFS

**To Reproduce**
see bug description above

**Expected behavior**
The album should appear in the library and show as disc 1 ... 4, instead of 4 separate albums 

**Server Logs**
```
[2021-06-26 10:14:57.318 +01:00] [WRN] Slow HTTP Response from "http://XXX.XXX.XXX.20:8096/Users/c004d95e46cf44acb8ffaf31926ae1b9/Items?SortBy=IsFavoriteOrLiked%2CRandom&IncludeItemTypes=Movie%2CSeries%2CMusicArtist&Limit=20&Recursive=true&ImageTypeLimit=0&EnableImages=false&ParentId=7e64e319657a9516ec78490da03edccb&EnableTotalRecordCount=false" to "192.168.2.52" in 0:00:03.0861974 with Status Code 200
[2021-06-26 10:16:27.217 +01:00] [INF] WS "XXX.XXX.XXX.52" closed
[2021-06-26 10:16:27.917 +01:00] [INF] WS "XXX.XXX.XXX.52" request
[2021-06-26 10:16:28.529 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 3/Folder.jpg'". URL "GET" "/Items/0610c43b4127402b50a529828f12488a/Images/Primary".
[2021-06-26 10:16:28.529 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 2/Folder.png'". URL "GET" "/Items/9a5bc6bc66b6fccb47234895702b7419/Images/Primary".
[2021-06-26 10:16:28.530 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 4/Folder.jpg'". URL "GET" "/Items/0fd374d353212543f05b14712241b696/Images/Primary".
[2021-06-26 10:16:58.287 +01:00] [INF] WS "XXX.XXX.XXX.52" request
[2021-06-26 10:17:04.086 +01:00] [INF] WS "XXX.XXX.XXX.52" closed
[2021-06-26 10:17:04.976 +01:00] [INF] WS "XXX.XXX.XXX.52" request
[2021-06-26 10:17:05.472 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 3/Folder.jpg'". URL "GET" "/Items/0610c43b4127402b50a529828f12488a/Images/Primary".
[2021-06-26 10:17:05.475 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 2/Folder.png'". URL "GET" "/Items/9a5bc6bc66b6fccb47234895702b7419/Images/Primary".
[2021-06-26 10:17:05.480 +01:00] [ERR] Error processing request: "Could not find file '/mnt/mediastore/music/John Barry/Disc 4/Folder.jpg'". URL "GET" "/Items/0fd374d353212543f05b14712241b696/Images/Primary".
[2021-06-26 10:17:11.436 +01:00] [INF] "John Barry" ("/mnt/mediastore/music/John Barry") will be refreshed.
[2021-06-26 10:17:11.623 +01:00] [INF] Removing item, Type: "MusicAlbum", Name: "John Barry: The Collection: 40 Years of Film Music", Path: "/mnt/mediastore/music/John Barry/The Collection - 40 Years of Film Music CD1", Id: 2449aaf7-7239-0788-621b-b57e88f23ac2
[2021-06-26 10:17:11.782 +01:00] [INF] Removing item, Type: "MusicAlbum", Name: "John Barry: The Collection: 40 Years of Film Music", Path: "/mnt/mediastore/music/John Barry/Disc 3", Id: 0610c43b-4127-402b-50a5-29828f12488a
[2021-06-26 10:17:11.911 +01:00] [INF] Removing item, Type: "MusicAlbum", Name: "John Barry: The Collection: 40 Years of Film Music", Path: "/mnt/mediastore/music/John Barry/Disc 4", Id: 0fd374d3-5321-2543-f05b-14712241b696
[2021-06-26 10:17:12.039 +01:00] [INF] Removing item, Type: "MusicAlbum", Name: "John Barry: The Collection: 40 Years of Film Music", Path: "/mnt/mediastore/music/John Barry/Disc 2", Id: 9a5bc6bc-66b6-fccb-4723-4895702b7419
[2021-06-26 10:17:13.367 +01:00] [ERR] Error refreshing item
System.Exception: Cannot update refresh progress of item 'Folder' (4c04a1a131d6fb765e75528543456120) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass61_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2021-06-26 10:17:25.641 +01:00] [INF] WS "XXX.XXX.XXX.52" request
[2021-06-26 10:17:45.723 +01:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
```
**FFmpeg Logs**
n/a

**Browser Console Logs**
n/a

**Screenshots**
n/a

**Additional context**
The server hardware is quite old and generally I receive slow response warnings, but with 200 OK status. The server however streams movies/music perfectly

**Comment by daves00** [comment]
Solved by Restart Jellyfin, and Scan All Libraries
