### ISSUE TITLE
Pushbullet Plugin (7.2102.903.15 from repository Jellyfin Plugins Unstable) Error creating Pushbullet.Notifier

### ISSUE THREAD

**Issue by KaXaSA** [jellyfin/jellyfin#6232]
**Describe the bug**
After installing Pushbullet Plugin (7.2102.903.15 from repository Jellyfin Plugins Unstable) I get this error:

```
Emby.Server.Implementations.ApplicationHost: Error creating Pushbullet.Notifier
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Json.JsonDefaults' from assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
...
```

**System (please complete the following information):**
 - OS: Windows 10 Pro 20H2 19042.1081
 - Clients: [Jellyfin Media Player]
 - Jellyfin Version: 10.8.0
 - Storage: local
 - Plugins Repositories: https://repo.jellyfin.org/releases/plugin/manifest-unstable.json

**To Reproduce**
1. Open Jellyfin
2. Install Pushbullet (7.2102.903.15 from repository Jellyfin Plugins Unstable) 
3. Restart the server
4. You should see the error in the server prompt

**Server Logs**
```
[17:56:51] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Pushbullet.Notifier
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Json.JsonDefaults' from assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at Pushbullet.Notifier..ctor(ILogger`1 logger, IHttpClientFactory httpClientFactory)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by crobibero** [comment]
Plugins are not built targeting unstable Jellyfin.

**Comment by crobibero** [comment]
Additionally, the pushbullet plugin has been archived.
https://github.com/jellyfin-archive/jellyfin-plugin-pushbullet

**Comment by KaXaSA** [comment]
Oh, I actually tested with the stable (6.0.0.0) first and the error was pretty much the same, that's why I tried the unstable version.

```
[20:59:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Pushbullet Notifications 6.0.0.0
...
[20:59:02] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Pushbullet.Notifier
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Json.JsonDefaults' from assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at Pushbullet.Notifier..ctor(ILogger`1 logger, IHttpClientFactory httpClientFactory)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

When the plugin is archived, what does that means?
I read the [GitHub page](https://github.com/jellyfin-archive) description "Archived repositories from the Jellyfin project - anything that hasn't or can't have improvements done"
but it was not clear if I should still report issues with archived plugins or not.

**Comment by crobibero** [comment]
Archived plugin means it has been deprecated and will no longer be developed.
You're running Jellyfin v10.8, which is the unstable version. Plugins don't normally work on the unstable version of Jellyfin.
