### ISSUE TITLE
Fisrt start language menu empty

### ISSUE THREAD

**Issue by jerome-diver** [jellyfin/jellyfin#6250]
**Describe the bug**
At first start, language menu is empty, consequence: i can never start.

**System (please complete the following information):**
 - OS: Fedora 34
 - Virtualization: no, installed from source file, follow the official guide describing how to process (jellyfin-web installed inside and npm start inside)
 - Clients: flatpack com.github.iwalton3.jellyfin-media-player (web browser show an empty page at 127.0.0.1:8096, on http, https show an error about too long ssl...)
 - Browser: Firefox or Chromium the same, so i use a application client to be able to access the first page
 - Jellyfin Version:10.7.6
 - Playback: i am not at this step...

**To Reproduce**

1. from Fedora 34
2. Follow exactly the official installation guide with source file jellyfin-server version 10.7.6 (the latest)
3. install jellyfin-web inside jellyfin directory (even if you are not under debian, you have to install it, description in official documentation is dirty with that, it is unclear at all), and npm install
4. inform the config file
5. start jellyfin-web from his directory with npm start &
6.  open a browser, so you can see there is no way to access anything else
7. install jellyfin-media-player from flatpak package manager
8. run the client (last installed there)
9. inform localhost:8096 new server (then click connect)
10. after to see that you can not login because there is no user created, close the application
11. re run the application and you would access the "first start page"
12. as you can see, the language menu is empty... you are done again !

**Expected behavior**
What everybody should expect: to be able to see languages appear on the menu, maybe to be able to acces from a web browser, and so on...

**Server Logs**

jellyfin-web@10.8.0 start
> npm run serve

> jellyfin-web@10.8.0 serve
> webpack serve --config webpack.dev.js

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from
❯
❯ cd ../..
❯ ./jellyfin.sh
[13:31:38] [INF] [1] Main: Jellyfin version: 10.7.6
[13:31:38] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /opt/jellyfin/log]"]
[13:31:38] [INF] [1] Main: Arguments: ["/opt/jellyfin/jellyfin-server_10.7.6/jellyfin.dll", "-d", "/opt/jellyfin/data", "-C", "/opt/jellyfin/cache", "-c", "/opt/jellyfin/config", "-l", "/opt/jellyfin/log"]
[13:31:38] [INF] [1] Main: Operating system: Linux
[13:31:38] [INF] [1] Main: Architecture: X64
[13:31:38] [INF] [1] Main: 64-Bit Process: True
[13:31:38] [INF] [1] Main: User Interactive: True
[13:31:38] [INF] [1] Main: Processor count: 8
[13:31:38] [INF] [1] Main: Program data path: /opt/jellyfin/data
[13:31:38] [INF] [1] Main: Web resources path: /opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web
[13:31:38] [INF] [1] Main: Application directory: /opt/jellyfin/jellyfin-server_10.7.6/
[13:31:38] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /opt/jellyfin/cache
[13:31:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:31:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:31:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:31:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[13:31:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[13:31:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[13:31:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.6.0
[13:31:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.6.0
[13:31:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.6.0
[13:31:39] [INF] [1] Main: Kestrel listening on Any IP4 Address
[13:31:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[13:31:39] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 07/03/2021 02:00, which is 12:28:20.3299461 from now.
[13:31:39] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.4
[13:31:39] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[13:31:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[13:31:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[13:31:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: /usr/bin/ffmpeg
[13:31:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 8216e8d6d25f486990e6469df0668c43
[13:31:40] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.2.32/24
[13:31:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0724754
[13:31:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[13:31:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.077405
[13:31:40] [INF] [1] Main: Startup complete 0:00:02.1491098
[13:31:42] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[13:31:42] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[13:31:42] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[13:31:44] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
[13:31:44] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
⚠ ｢wdm｣: assets by chunk 27.6 MiB (auxiliary id hint: vendors) 903 assets
assets by path *.js 20.5 MiB
  assets by chunk 5.36 MiB (id hint: vendors) 14 assets
assets by path assets/ 732 KiB 43 assets
assets by path libraries/ 8.55 MiB 11 assets
assets by path themes/ 1.15 MiB 8 assets
assets by chunk 500 KiB (auxiliary name: main) 4 assets
assets by path *.json 2.39 KiB 3 assets
assets by path *.ico 13.3 KiB
  asset bc8d51405ec040305a87.ico 6.67 KiB [emitted] [immutable] [from: favicon.ico]
  asset favicon.ico 6.67 KiB [emitted] [from: favicon.ico] [copied]
assets by path *.svg 2.2 KiB
  asset cb6e840e08726299bf8f968fe08d7ead.svg 1.39 KiB [emitted] [immutable] [from: assets/img/fresh.svg]
  asset 0d2b37694d352e7e4c591afc205984ff.svg 833 bytes [emitted] [immutable] [from: assets/img/rotten.svg]
54 assets
orphan modules 762 KiB [orphan] 386 modules
runtime modules 24.3 KiB 12 modules
modules by path ../ 6.46 MiB 1832 modules
modules by path ./ 8.82 MiB
  javascript modules 5.09 MiB
    cacheable modules 5.09 MiB 518 modules
    modules by path ./controllers/ lazy ^/.// 320 bytes 2 modules
    modules by path ./components/tvproviders/ lazy ^/.// 320 bytes 2 modules
  json modules 3.74 MiB 68 modules
canvas (ignored) 15 bytes [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
zlib (ignored) 15 bytes [optional] [built] [code generated]
http (ignored) 15 bytes [built] [code generated]
https (ignored) 15 bytes [built] [code generated]
url (ignored) 15 bytes [built] [code generated]

WARNING in ../node_modules/epubjs/src/section.js 118:23-39
export 'XMLDOMParser' (imported as 'XMLDOMSerializer') was not found in 'xmldom' (possible exports: DOMImplementation, DOMParser, XMLSerializer)
 @ ../node_modules/epubjs/src/spine.js 14:0-32 123:24-31
 @ ../node_modules/epubjs/src/book.js 23:0-28 140:21-26
 @ ../node_modules/epubjs/src/index.js 1:0-26 8:0-54
 @ ./plugins/bookPlayer/plugin.js 298:8-24
 @ ./plugins/ lazy ^\.\/.*$ chunkName: [request] namespace object ./bookPlayer/plugin.js ./bookPlayer/plugin
 @ ./components/pluginManager.js 138:23-140:49
 @ ./scripts/site.js 34:0-60 140:14-27 157:13-37

WARNING in ./components/apphost.js 46:76-87
Should not import the named export 'version' (imported as '_appVersion') from default-exporting module (only default export is available soon)
 @ ./scripts/site.js 32:0-48 142:9-25 204:6-22 209:7-23

WARNING in ./components/apphost.js 380:74-85
Should not import the named export 'version' (imported as '_appVersion') from default-exporting module (only default export is available soon)
 @ ./scripts/site.js 32:0-48 142:9-25 204:6-22 209:7-23

WARNING in ../node_modules/blurhash/dist/base83.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/base83.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/base83.ts'
 @ ../node_modules/blurhash/dist/decode.js 3:15-34
 @ ../node_modules/blurhash/dist/index.js 6:15-34
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

WARNING in ../node_modules/blurhash/dist/decode.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/decode.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/decode.ts'
 @ ../node_modules/blurhash/dist/index.js 6:15-34
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

WARNING in ../node_modules/blurhash/dist/encode.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/encode.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/encode.ts'
 @ ../node_modules/blurhash/dist/index.js 9:15-34
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

WARNING in ../node_modules/blurhash/dist/error.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/error.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/error.ts'
 @ ../node_modules/blurhash/dist/index.js 11:9-27
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

WARNING in ../node_modules/blurhash/dist/index.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/index.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/index.ts'
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

WARNING in ../node_modules/blurhash/dist/utils.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/utils.ts' file: Error: ENOENT: no such file or directory, open '/opt/jellyfin/jellyfin-server_10.7.6/jellyfin-web/node_modules/blurhash/src/utils.ts'
 @ ../node_modules/blurhash/dist/decode.js 4:14-32
 @ ../node_modules/blurhash/dist/index.js 6:15-34
 @ ./components/images/imageLoader.js 20:0-51 35:6-21 44:15-21
 @ ./scripts/libraryMenu.js 96:2-44
 @ ./scripts/site.js 39:0-23

6 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.39.0 compiled with 9 warnings in 50953 ms
ℹ ｢wdm｣: Compiled with warnings.
[13:33:05] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:33:05] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:33:05] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:33:07] [INF] [30] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:33:07] [INF] [30] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:33:07] [INF] [30] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:36:11] [ERR] [67] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[13:36:11] [INF] [67] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for jerome has been denied (IP: 127.0.0.1).
[13:36:11] [ERR] [67] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
[13:38:25] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:25] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:38:25] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:27] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:27] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:38:27] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:29] [INF] [38] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:29] [INF] [38] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:38:29] [INF] [38] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:31] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:38:31] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:38:31] [INF] [42] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]

**Screenshots**

![jellyfin_stupid_first_start](https://user-images.githubusercontent.com/11176132/124233480-1236c780-db3d-11eb-8961-a13588fb41a6.gif)

**Additional context**
from desktop "Awesome" and also from desktop "Gnome", the same.

**Comment by crobibero** [comment]
My guess is that there’s an issue with the unstable version of jellyfin-web that you’re running, and not with the stable server.

**Comment by jerome-diver** [comment]
@crobibero thank you for your help. 
And... what am i supposed to know and so, to do with that ?
Is there an indication somewhere about: "where is the stable version of jellyfin-web to git checkout in ?"

**Comment by jerome-diver** [comment]
[i post a bug report there](https://github.com/jellyfin/jellyfin-web/issues/2780)

I hope to get an information to read about: "what is the stable version to use for jellyfin-web".
And when i will have this crucial information, i will report it there. Maybe it will be reported in the README.md file to...

**Comment by crobibero** [comment]
The stable version is currently the `release10.7.z` branch, but running directly from the branch is not recommended and not supported. I recommend either using the version in the fedora repo, or downloading the release

**Comment by jerome-diver** [comment]
@crobibero i did try the 10.7.z version, and it failed the same way.
I just download from your link the targ.gz file and install it in the jellyfin server directory (with yarn as explain in the Readme file), then rename the directory to jellyfn-web (as attempted by jellyfin server).
It does failed with the same problem.

Maybe i did something wrong or miss-understand the process to make it running fine ?
in the README file there is a process to get starting: 1/ 2 / 3 /4. It looks like steps to go, but after to install (process number 2), i think i do not have to run the local development with yarn serve command... (in fact, i'm thinking that it is not a step process to get it running, but i may be wrong). And same for step 4... i didn't run it.
Should i run the process 3 and  4 ? I think it is not clearly explained (to my point of view). I miss understand.

**Comment by jerome-diver** [comment]
ok, i looking inside the package.json file and because i can develop in javascript and know webpack and node a bit, i understand that the README.md file has a bad explain of process to go with.
It is not a step by step process to apply, and there is no need to run yarn serve, because thje package.json file show that npm start do this command for the user (so it means that user should have installed yarn, and it is also not explained).
instead of 1 / 2 / 3 / 4 as wrote in the readme file, it should be more clear to get condition points instead.
I know it is not easy to write a readme file the way everybody can understand, so then it can be improve on this point.

also, this doesn't fix the problem i have, and doesn't add any clue to resolve it.
It looks like an empty choice from a kind of combo box can be an empty database records (if choices are in a database... sqlite maybe ? i see some .db files around, do you have an idea about that ?).
So... is there a process to initiate the database at first time running that someone dev forget to explain ?

**Comment by jerome-diver** [comment]
@crobibero also, please, do not close un unresolved bug report without any reason, it doesn't add value and doesn't fix the problem.
Also, there is no jellyfin inside fedora-34 repo, ether inside any un-official existin g one that i know about. So i can not use jellyfin from Fedora-34 repo or any other one. But if you know one Fedora-34 repo that has it, thank you for share.
