### ISSUE TITLE
LD_LIBRARY_PATH should be passed to ffprobe on metadata scan

### ISSUE THREAD

**Issue by cyberia-ng** [jellyfin/jellyfin#6351]
**Describe the bug**

Related to https://github.com/jellyfin/jellyfin-ffmpeg/issues/32

When invoking `ffprobe` to scan a file for metadata resolution, the `LD_LIBRARY_PATH` environment variable should be threaded through.

My quite specific use case:

- I am running Jellyfin in a Docker container on a Raspberry Pi, and the guest OS is Debian buster.
- `jellyfin-ffmpeg` is built for armhf assuming that certain RPi firmware libraries will be available (see https://github.com/jellyfin/jellyfin-ffmpeg/issues/32), but in the guest OS they are not.
- I work around this by mounting the host's `/opt/vc/lib` directory into the container and setting `LD_LIBRARY_PATH=/opt/vc/lib`.
- This works when invoking `/usr/lib/jellyfin-ffmpeg/ffprobe` from a shell, but does not work when Jellyfin invokes `ffprobe` internally as part of its metadata scan.

**System (please complete the following information):**
 - OS: Debian buster
 - Virtualization: Docker
 - Clients: Browser
 - Browser: N/A
 - Jellyfin Version: 10.7.6 (Debian buster armhf build)
 - Playback: N/A
 - Hardware Acceleration: none
 - Installed Plugins: none
 - Reverse Proxy: caddy
 - Base URL: none
 - Networking: Docker internal
 - Storage: local

**To Reproduce**
1. Set up Jellyfin in a Docker container on a Raspberry Pi
2. Mount the host `/opt/vc/lib` directory into the guest filesystem
3. Set `LD_LIBRARY_PATH=/opt/vc/lib`
4. Run Jellyfin
5. Run a metadata scan
6. Observe ffprobe error in logs `/usr/lib/jellyfin-ffmpeg/ffprobe: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory`

**Expected behavior**
`ffprobe` correctly finds and links to `/opt/vc/lib/libmmal_core.so`.

**Server Logs**
```
/usr/lib/jellyfin-ffmpeg/ffprobe: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
[10:49:33] [ERR] [65] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Additional context**

You can workaround this by using the system ffmpeg.

**Comment by nyanmisaka** [comment]
The deprecated MMAL has been removed from jellyfin-ffmpeg5.
