### ISSUE TITLE
JF server error in log

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#6367]
**Describe the bug**
error in log file, Suspect it stops scan of music library.  scan library => search for missing metadata.

UI shows scan of library stopped at 58%

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Virtualization: None
 - Clients: Firefox 
 - Browser: Firefox 90.0.02
 - Jellyfin Version: 10.7.6
 - Playback: Direct Play/ N/A
 - Hardware Acceleration: Intel QuickSync
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: Default
 - Networking: Simple (Flat) LAN
 - Storage: Local, BTRFS, Raid 1

**To Reproduce**
scan library => search for missing metadata.

**Expected behavior**
Scan of library to reach 100%

**Server Logs**
```
[2021-08-01 13:06:50.333 +01:00] [INF] Creating image collage and saving to "/var/cache/jellyfin/temp/d7971310a20e40a7bb4073459eee3212.png"
[2021-08-01 13:06:50.448 +01:00] [INF] Completed creation of image collage and saved to "/var/cache/jellyfin/temp/d7971310a20e40a7bb4073459eee3212.png"
[2021-08-01 13:11:42.294 +01:00] [ERR] Error in "TheAudioDB"
System.ArgumentException: Unable to determine image file extension from mime type text/html
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Was the scan marked as "failed"? Everywhere that I see this message being logged it shouldn't stop scan. 
The original error is because TheAudioDB returned html when we were expecting an image.

**Comment by daves00** [comment]
There was no failed message, however i believe it it crashing the scan - no further scans could be initiated without a restart. I also move the offending file from the server, restarted JF, and carried out another scan of the same type and reached a higher percentage (but not 100%) with a similar crash message but regards a different file.

**Comment by srcrist** [comment]
Closing this issue as stale. The absence of other reports suggests that it was an isolated AudioDB issue. If anyone experiences issues that crash the scanner, or prevent it from working, please open another issue.
