### ISSUE TITLE
Issue in MKV causes error

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#6370]
**Describe the bug**
issue in error log stops video library scan. 

Suggest adjust error handling so that other library files are scan even when some video files contain this error.

**System (please complete the following information):**
 - OS: Ubuntu 18.04LTS
 - Virtualization: None
 - Clients: Firefox
 - Browser: Firefox 90.0.2
 - Jellyfin Version: 10.7.6
 - Playback: Direct Play
 - Hardware Acceleration: Intel Quick Sync
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: Default
 - Networking: Simple (Flat) LAN
 - Storage: Local

**To Reproduce**
Sacn video library

**Expected behavior**
Scan to continue library scan of remaining files after ignoring this error

**Server Logs**
Completed creation of image collage and saved to "/var/cache/jellyfin/temp/9aa770b3ffad4674ab682f86e4a7abae.png"
[2021-08-01 13:45:45.776 +01:00] [INF] Stopping chapter extraction for "Star Trek Into Darkness" because a chapter was found with a position greater than the runtime.
[2021-08-01 13:46:06.878 +01:00] [ERR] Error in "ffprobe"
System.ArgumentException: Second path fragment must not be a drive or UNC name. (Parameter 'expression')
   at System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(String& directory, String& expression, MatchType matchType)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at DvdLib.Ifo.Dvd..ctor(String path)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.FetchFromDvdLib(Video item)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by daves00** [comment]
I deleted and re-ripped the MKV file so am unfortuantely unable to test this.

**Comment by eppesuig** [comment]
Hello, I found this issue closed, but I am experiencing the same error. It appears a few times while reindexing the video library.
I am using Jellyfin 10.8.13 on Linux.

One example:

```
gen 21 12:12:56 mantide jellyfin[1230641]: [12:12:56] [ERR] Error in ffprobe
gen 21 12:12:56 mantide jellyfin[1230641]: System.ArgumentException: Second path fragment must not be a drive or UNC name. (Parameter 'expression')
gen 21 12:12:56 mantide jellyfin[1230641]:    at System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(String& directory, String& expression, MatchType matchType)
gen 21 12:12:56 mantide jellyfin[1230641]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
gen 21 12:12:56 mantide jellyfin[1230641]:    at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
gen 21 12:12:56 mantide jellyfin[1230641]:    at DvdLib.Ifo.Dvd..ctor(String path)
gen 21 12:12:56 mantide jellyfin[1230641]:    at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.FetchFromDvdLib(Video item)
gen 21 12:12:56 mantide jellyfin[1230641]:    at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
gen 21 12:12:56 mantide jellyfin[1230641]:    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

I don't know what file triggers the problem.

**Comment by eppesuig** [comment]
I think the problem is related to a directory that contains a backup of a DVD. The error seems related to enumerating files in the VIDEO_TS directory.

**Comment by felix920506** [comment]
@eppesuig please open a new issue.
