### ISSUE TITLE
Guide data not pulling reliably, error from log included, manual refresh worked.

### ISSUE THREAD

**Issue by NeverEnoughTime** [jellyfin/jellyfin#6378]
**Describe the bug**

Guide data didn't pull last night, or the week before, I had to manually refresh each time to get it. I'm not sure how long the issue may have been going on, I haven't been watching live TV but since the Olympics just started I had to tag that to record for my partner.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 90.0.2
 - Jellyfin Version: 10.7.6
 - Playback: N/A
 - Hardware Acceleration: N/A
 - Installed Plugins: AudioDB 10.7.6, Bookshelf 5.0, Fanart 6.0, Kody Sync Queue 6.0, Music Brainz 10.7.6, OMDB 10.7.6, Playback Reporting 10.0, Reports 12.0
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local
 - Tuner: HDHomeRun CONNECT DUO
 - 
**To Reproduce**

I'm not sure about reproducing it, I'm just waiting for the next refresh cycle at this point, I'm assuming every 7 days, or is it more often?

**Expected behavior**
I expected it to connect to Schedules Direct (subscription active, login/password confirmed) to pull the guide data for the next 7 days, automatically. Manual refresh did work.

**Server Logs**
[2021-08-01 23:10:24.649 -06:00] [INF] "IntervalTrigger" fired for task: "Refresh Guide"
[2021-08-01 23:10:24.650 -06:00] [INF] Queuing task "RefreshChannelsScheduledTask"
[2021-08-01 23:10:24.650 -06:00] [INF] Executing "Refresh Guide"
[2021-08-01 23:10:27.652 -06:00] [INF] Discovered tuner device "HD Homerun" at "http://192.168.101.109"
[2021-08-01 23:10:28.254 -06:00] [INF] Authenticated with Schedules Direct token: c5eec5087bebce312d4e00b0279f38e4
[2021-08-01 23:10:28.398 -06:00] [INF] Found 38 channels on the lineup on ScheduleDirect
[2021-08-01 23:10:28.398 -06:00] [INF] Mapping Stations to Channel
[2021-08-01 23:10:28.398 -06:00] [INF] Found epg channel in "Schedules Direct" "USA-OTA-57701" "KOTADT (KOTA-DT)" "44026"

I trimmed out all but the first and last channels, if you really want all of them I can repost it, the error is the same for all of them.

[2021-08-01 23:10:28.399 -06:00] [INF] Found epg channel in "Schedules Direct" "USA-OTA-57701" "KRPCLD5 (KRPC-LD5)" "106366"
[2021-08-01 23:10:28.399 -06:00] [INF] Refreshing guide with 7 days of guide data
[2021-08-01 23:10:28.399 -06:00] [INF] Channel Station ID is: "98368"
[2021-08-01 23:10:28.749 -06:00] [ERR] Error getting programs for channel "ABC-HD"
System.Net.Http.HttpRequestException: Request failed: Internal Server Error
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetProgramsAsync(ListingsProviderInfo info, String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetProgramsAsync(ListingsProviderInfo info, String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)

Same exact error for every channel, trimmed them out for space.

[2021-08-01 23:10:35.205 -06:00] [INF] Channel Station ID is: "106366"
[2021-08-01 23:10:35.489 -06:00] [ERR] Error getting programs for channel "FAMILY"
System.Net.Http.HttpRequestException: Request failed: Internal Server Error
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetProgramsAsync(ListingsProviderInfo info, String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetProgramsAsync(ListingsProviderInfo info, String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[2021-08-01 23:11:40.197 -06:00] [INF] "Refresh Guide" Completed after 1 minute(s) and 15 seconds

**Additional context**

I used the "restart" option on the dashboard hoping it would just reload and the data would be there but when it wasn't I went into the Live TV section and clicked Refresh Guide Data, which worked as expected, no errors reported in the log.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!
