### ISSUE TITLE
System.ObjectDisposedException: Cannot access a closed Stream.

### ISSUE THREAD

**Issue by jeremyjjbrown** [jellyfin/jellyfin#6415]
**Describe the bug**
In progress OTA Recording does not start on FF or Chrome WebClients.

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: Docker
 - Clients: Firefox, Chrome (on MacOS) 
 - Browser: firefox 90, chrome 92
 - Jellyfin Version: jellyfin/jellyfin:10.7.6
 - Playback: OTA TV recording playback
 - Hardware Acceleration: unknown
 - Installed Plugins: none
 - Reverse Proxy: none
 - Networking: host
 - Storage: disk

**To Reproduce**

1. schedule a dvr
2. play the in progress dvr
4. UI hangs, play never starts, errors in server log

**Expected behavior**
The video should play

**Server Logs**
[02:45:22] [ERR] [136] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /LiveTv/LiveRecordings/2f01c22a8fdf4d4881546f6cbc4172d1/stream.
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[02:45:22] [WRN] [136] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://127.0.0.1:8096/LiveTv/LiveRecordings/2f01c22a8fdf4d4881546f6cbc4172d1/stream to 127.0.0.1 in 0:00:02.3709661 with Status Code 500
[02:45:22] [ERR] [42] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[02:45:43] [INF] [146] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.92 closed
[02:45:43] [INF] [136] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.92 request
[02:47:39] [INF] [88] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.92 closed
[02:47:40] [INF] [103] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.92 request
[02:48:15] [INF] [5] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for jeremy has succeeded.
[02:48:15] [INF] [5] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user jeremy: 2/0
[02:48:15] [INF] [5] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 71ee0c60-645e-470d-9d5a-1808f706dc97
[02:48:15] [INF] [137] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.92 request

**Comment by Protektor-Desura** [comment]
I would like to be able to pause Live TV and rewind Live TV back to 30 minutes or when you started on that channel which is less. Also you should be able to pause for 10 minutes then be able to fast forward 5-10 minutes through commercials to catch up to current live. This is not possible/support currently.
