### ISSUE TITLE
Media info not correctly loaded on .mkv

### ISSUE THREAD

**Issue by Tthecreator** [jellyfin/jellyfin#654]
**Describe the bug**
Whenever I try to look at the information page of a .mkv file there is no information. This worked in 10.0.1.0, but isn't working in 2.0.
Because of this a few things happen:
- no subtitles availalbe
- I can select a video quality up to 4K 120mbs when this is not applicable.

**To Reproduce**
1. Add any .mkv file
2. Add it to jellyfin
3. Go the the itemdetails page of a single video file

**Expected behavior**
I expect to see all the streams inside my mkv container.

**Logs**
Please paste any log errors.

**System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.0.2.0

**Additional context**
I'll try to find more info on this bug soon.

**Comment by Tthecreator** [comment]
The error log I'm getting on 'Scan All Libraries' is:
```
[21:03:36] [ERR] Error
Busy: database is locked
SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.ExecuteWithSingleParam(IDatabaseConnection db, String query, Byte[] value) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Data\SqliteItemRepository.cs:line 5228
   at Emby.Server.Implementations.Data.SqliteItemRepository.<>c__DisplayClass89_0.<DeleteItem>b__0(IDatabaseConnection db) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Data\SqliteItemRepository.cs:line 5201
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.ManagedConnection.RunInTransaction(Action`1 action, TransactionMode mode) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Data\ManagedConnection.cs:line 48
   at Emby.Server.Implementations.Data.SqliteItemRepository.DeleteItem(Guid id, CancellationToken cancellationToken) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Data\SqliteItemRepository.cs:line 5196
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, BaseItem parent, Boolean notifyParentItem) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 440
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 428
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 346
   at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 608
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 467
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\Folder.cs:line 346
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in C:\projects\jellyfin\jellyfin\MediaBrowser.Controller\Entities\AggregateFolder.cs:line 175
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1091
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 1050
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in C:\projects\jellyfin\jellyfin\Emby.Server.Implementations\ScheduledTasks\ScheduledTaskWorker.cs:line 428
```

Is this an issue with jellyfin or did I somehow screw up my database? (Or Jellyfin screwed up my database)
