### ISSUE TITLE
Windows - Unable to launch Jellyfin since update to 10.7.7

### ISSUE THREAD

**Issue by rutskiuk** [jellyfin/jellyfin#6542]
Hi,

Since I installed the latest version of Jellyfin on Windows the service fails to start and returns an I/O error in the logs.
The file system is readable and the hard drive has plenty of space.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: Firefox, NVidia Shield
 - Browser: Firefox 92
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: Packaged with installer
 - Playback: Unable to launch
 - Hardware Acceleration: n/a
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. Start Jellyfin Service
2. Jellyfin Service Stops

**Expected behavior**
Jellyfin service starting

**Server Logs**
[2021-09-11 02:18:51.783 +01:00] [FTL] [1] Main: Error while starting server.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

**FFmpeg Logs**
n/a

**Browser Console Logs**
n/a

**Screenshots**
n/a

**Additional context**
I have tried removing jellyfin.db and library.db but it makes no difference.
I have tried reinstalling 10.7.6 but I get the same
I have tried running jellyfin.exe as admin and restarting the server, no change but the terminal window has multiple errors which read "Operation is not valid due to the current state of the object."
Am I going to have to completely wipe the installation and try again or is there any way to salvage this?

**Comment by rutskiuk** [comment]
Fixed this myself by opening an admin command prompt, navigating to the path of nssm, doing nssm edit jellyfinserver then changing the properties of the service to log on as local system account and allow service to interact with the desktop
The service in the installer had been set up with some other account. Hope this helps someone.
