### ISSUE TITLE
Jellyfin fails to update plugins since upgrading to 10.8.0: `Directory does not exist to extract to`

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin#6560]
**Describe the bug**
Since upgrading to jellyfin 10.8.0 (docker `jellyfin/jellyfin:unstable`), plugin updates fail with `Directory does not exist to extract to`

**System (please complete the following information):**
 - OS:  Ubuntu Server 21.04
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 92
 - Jellyfin Version: 10.8.0 (`jellyfin/jellyfin:unstable@sha256:b476a2e817200326c8dc10a3434e26a8c4d5193defe2f94b4abd8fde5fc2ef81`)
 - FFmpeg Version: [e.g. 4.3.2-Jellyfin]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Hardware Acceleration: [e.g. none, VAAPI, NVENC, etc.]
 - Installed Plugins: `Anilist, AudioDB, Bookshelf, Cover Art Archive, MusicBrainz, OMDb, TMDb, TheTVDB`
 - Reverse Proxy: nginx
 - Base URL: none (`/` redirects to `/web`, setup like in the jellyfin-nginx example)
 - Networking: host
 - Storage: local

**To Reproduce**
1. create server with a lower jellyfin version than 10.8.0
2. install plugins (in my case `Anilist` (version 2.0.0)
3. stop server
4. upgrade to jellyfin to 10.8.0
5. observer logs

**Expected behavior**
Updates to not fail

**Server Logs**

<details>
<summary>The log part that is about the issue</summary>

```txt
[2021-09-17 14:33:05.904 +00:00] [INF] [1] Main: Startup complete 0:00:03.3366366
[2021-09-17 14:33:08.318 +00:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2021-09-17 14:33:08.321 +00:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2021-09-17 14:33:08.328 +00:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2021-09-17 14:33:09.948 +00:00] [ERR] [16] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
SharpCompress.Common.ExtractionException: Directory does not exist to extract to: /config/plugins/AniList_3.0.0.0/
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromZip(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[2021-09-17 14:33:10.077 +00:00] [ERR] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
SharpCompress.Common.ExtractionException: Directory does not exist to extract to: /config/plugins/AniList_3.0.0.0/
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromZip(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-09-17 14:33:10.078 +00:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Failed after 0 minute(s) and 1 seconds
```

</details>

Full Log File: [jellyfin.log](https://github.com/jellyfin/jellyfin/files/7186590/jellyfin.log)

Note: i mounted some libraries read-only, because i am still trying jellyfin out (without re-creating my media library) (not using jellyfin yet, because of [this feature request](https://features.jellyfin.org/posts/1266/ability-to-disable-a-specific-metadata-provider-for-a-show-movie))

**Additional context**
In my case, the upgrade from `Anilist 2.0.0` to `Anilist 3.0.0` is failing with `Directory does not exist to extract to: /config/plugins/AniList_3.0.0.0/`

i have already confirmed that `/config/plugins` exists and is writable

Docker Volumes:

| Host/volume | Path in container |
| :---: | :---: |
| jellyfin-config | /config |
| /btrfsraid/data/Book_Library | /media/Books |
| /btrfsraid/data/Videos/Filme | /media/Movies |
| /btrfsraid/data/Music | /media/Music |
| /btrfsraid/data/Pictures | /media/Pictures |
| jellyfin-cache | /cache |
| /btrfsraid/data/Calibre Library | /media/Calibre |
| /btrfsraid/data/Videos | /media/Movies_test |
| /btrfsraid/data/Videos/Serien | /media/Shows |
| 69f9b231e8d99ade575e364a45d70402ab921f41aa09ead683616005b752b3e2 | /media |

---

PS: sorry if this is a plugin-specific issue, i dont know enough about the process jellyfin does for updating (if this is the case, please transfer this issue over to `jellyfin/jellyfin-plugin-anilist`)

**Comment by kenchrcum** [comment]
I have the same problem with other plugins, so it doesn't seem to be plugin-specific.
I could bypass the problem by extracting the plugin zip file directly to the config/plugins folder and then restart the container. But it doesn't work with every plugin. I could install TheTVDB Addon this way but not the Kodi Sync Queue.

**Comment by Bundesferkel** [comment]
Same problem here:
Installation of a plugin is not possible (Kodi Sync Queue). Update of LDAP not working too, removal of a plugin (like Session Cleaner) too.
Running as SYSTEM (Service) - accessing via browser from intranet and internet.

[2021-09-20 23:09:23.052 +02:00] [ERR] [38] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
SharpCompress.Common.ExtractionException: Directory does not exist to extract to: C:\ProgramData\jellyfin\server\plugins\Kodi Sync Queue_6.0.0.0\
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromZip(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[2021-09-20 23:09:23.073 +02:00] [ERR] [38] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Packages/Installed/Kodi%20Sync%20Queue".
SharpCompress.Common.ExtractionException: Directory does not exist to extract to: C:\ProgramData\jellyfin\server\plugins\Kodi Sync Queue_6.0.0.0\
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromZip(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
   at lambda_method1719(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

If i create the "non existing folder" it will be deleted immediately after trying to install the plugin.

**Comment by Artiume** [comment]
https://repo.jellyfin.org/releases/plugin/manifest-unstable.json

did you use the unstable manifest? Plugins and Unstable have always had issues so it's not surprising that they would be broken. Typically plugins are the last on the list of stuff to be checked before we make a release

**Comment by hasezoey** [comment]
@Artiume no, at least for me it was the default jellyfin stable manifests (that come with the versions, i did not change it)
