### ISSUE TITLE
PluginManager can't read a single .dll of some plugins

### ISSUE THREAD

**Issue by LPkkjHD** [jellyfin/jellyfin#6598]
The OpenSubtiltes and Webhook plugins both have an issue on installation. I do believe it is relevant to open the issue here as the behavior suggests this being a jellyfin issue rather than a plugin issue. Both fail to load a `.dll` file from the disk (relevant log entries under ServerLogs section further down).

Manually looking into the folders stated, however, shows that the 'missing' file is actually present and permissions don't seem to be a problem either.
```
root@605b8e3a1520:/# ls -lah /config/plugins/Webhook_4.0.0.0/
total 5.1M
drwxr-xr-x 2 root root 4.0K Sep 22 06:49 .
drwxr-xr-x 9 1002 1002 4.0K Sep 22 06:50 ..
-rw-r--r-- 1 root root 2.8M Sep 22 06:49 BouncyCastle.Crypto.dll
-rw-r--r-- 1 root root 261K Sep 22 06:49 Handlebars.dll
-rw-r--r-- 1 root root 123K Sep 22 06:49 Jellyfin.Plugin.Webhook.dll
-rw-r--r-- 1 root root 101K Sep 22 07:05 jellyfin-plugin-webhook.png
-rw-r--r-- 1 root root 827K Sep 22 06:49 MailKit.dll
-rw-r--r-- 1 root root 1.2K Sep 22 07:05 meta.json
-rw-r--r-- 1 root root 999K Sep 22 06:49 MimeKit.dll

root@605b8e3a1520:/# ls -lah /config/plugins/Open\ Subtitles_11.0.0.0/
total 108K
drwxr-xr-x 2 root root 4.0K Aug 29 14:37 .
drwxr-xr-x 9 1002 1002 4.0K Sep 22 06:50 ..
-rw-r--r-- 1 root root  33K Aug 29 14:37 Jellyfin.Plugin.OpenSubtitles.dll
-rw-r--r-- 1 root root  26K Sep 22 07:05 jellyfin-plugin-opensubtitles.png
-rw-r--r-- 1 root root 1.1K Sep 22 07:05 meta.json
-rw-r--r-- 1 root root  30K Aug 29 14:37 OpenSubtitlesHandler.dll
```

**System:**
 - OS: Ubuntu
 - Virtualization: docker/dokku
 - Jellyfin Version: 10.7.5
 - Installed Plugins: AudioDB, Bookshelf, Open Subtitles, Webhook, OMDb
 - Storage: local

**To Reproduce**
No Idea how to replicate this. I did a fresh install and the same issue appeared

**Expected behavior**
Plugin gets enabled

**Server Logs**
```
[2021-09-22 07:05:28.313 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Open Subtitles_11.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll". Unknown exception was thrown. Disabling plugin.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()

[...]

[2021-09-22 07:05:28.410 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Webhook_4.0.0.0/Jellyfin.Plugin.Webhook.dll". Unknown exception was thrown. Disabling plugin.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
```

**Additional context**

**Comment by crobibero** [comment]
This is not a bug, the plugins were built for Jellyfin 10.7.7. Future plugin releases have this version correctly set.
