### ISSUE TITLE
System.IO.IOException: Read-only file system

### ISSUE THREAD

**Issue by ggeorgovassilis** [jellyfin/jellyfin#6605]
**Describe the bug**

The following error shows up in the dockerised version:
```
[06:51:01] [ERR] [67] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: Read-only file system
```
**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker 19.03
 - Clients: Browser
 - Browser: Various
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: 
 - Playback: Direct Playback 
 - Hardware none
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Open Subtittles
 - Reverse Proxy: none
 - Base URL: none
 - Networking: default docker
 - Storage: local, mount media volume as read-only

**To Reproduce**

> docker logs jellyfin

**Expected behavior**
No errors

**Server Logs**
```
[06:51:01] [ERR] [67] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.IO.IOException: Read-only file system
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
```

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**
The media volume is indeed mounted as read-only, saving artwork into media folders is disabled.

**Comment by Artiume** [comment]
what about nfo's? do you have those enabled?

**Comment by ggeorgovassilis** [comment]
Admin Dashboard -> Libraries -> Metadata savers -> Nfo is checked.
I assume that should be disabled. After disabling it the errors went away. Thank you for the hint.

**Comment by Artiume** [comment]
no problem, glad i could help 👍
