### ISSUE TITLE
ssl broken??

### ISSUE THREAD

**Issue by devlin016** [jellyfin/jellyfin#6650]
ssl seems to be broken or something on latest version on ubuntuserver. jellyfin serves ssl https just fine it just seems to not be able to connect to plugin repos. my log reports this error.

```
[2021-10-02 14:36:10.407 -04:00] [ERR] An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
```

**Comment by Harteex** [comment]
Likely because of the [DST Root CA X3 expiration (30 september)](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).
For example, with an old OpenSSL it tries to verify using the expired DST Root CA X3, but my browser correctly uses the ISRG Root X1.

**Comment by crobibero** [comment]
Please try updating your certificates.
Sample command: `sudo apt update ca-certificates`

**Comment by devlin016** [comment]
I thought that was my issue but there is no update for ca certificates. i did the usual apt-get upgrade/update then a sudo update-ca-certificates. still same problem. what could it be? im running xenial lts.

**Comment by Harteex** [comment]
The problem is a combination of two things.
1) repo.jellyfin.org is still sending out the old expired DST Root CA X3 as an alternative
2) Your system looks at the old expired root and not the new ISRG root

So for this to work, either repo.jellyfin.org should be configured to stop sending out the DST Root, or you should upgrade your openssl version (I believe that's what you have to do at least.)
A quick package search for Xenial shows that it has 1.0.2g, but you need 1.1.0 or later.

When using an outdated OpenSSL, I get the following from repo.jellyfin.org:
```
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
```

While on a server with Let's Encrypt that doesn't send out the DST Root:
```
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = REDACTED
verify return:1
```

**Comment by devlin016** [comment]
im already running OpenSSL 1.1.1l  24 Aug 2021.

**Comment by timholl** [comment]
A good day to you, sir.

You may have run into a similar issue like I did, where

 * Jellyfin failed to check for updates on repo.jellyfin.org
 * I was able to connect via TLS in my browser, but
 * not on my iOS mobile application (certificate reported as expired around 29.09.2021)

This definitively has to do with the DST Root CA X3 expiration on 30.09.2021.

The trick in my case was (thanks to [a reddit post](https://www.reddit.com/r/jellyfin/comments/pybpau/lets_encrypt_users_take_note/) linked [in another issue](https://github.com/jellyfin/jellyfin/issues/6634)) deleting all `.pfx` files in `/var/lib/jellyfin/.dotnet/corefx/cryptography/x509stores/ca/` (do not forget stopping the `jellyfin` service before and restarting it afterwards).

However, I disagree with the [person in #6634 saying it would be "not a Jellyfin issue"](https://github.com/jellyfin/jellyfin/issues/6634#issuecomment-931283068).
I feeded my Jellyfin instance with a valid `.pfx` bundle and it continued serving outdated ones, as the reddit poster confirms
> For some reason, even though the `.pfx` file that contains my private key has the full correct certificate chain, one of the old `.pfx` files in that directory had the expired R3 Let's Encrypt intermediate certificate, so that's what Jellyfin served up as the next link in the cert. chain instead of the modern R3 cert. which won't expire until 2025.

In the near future I will therefore change my setup and let the TLS be handled by a proper Nginx reverse proxy.
This has the additional benefit that it is more stable, secure, is not affected by these obscure caching problems, and it does not require me to create a PKCS12-bundle-thing out of my Let's Encrypt key material on every renewal.

I hope this helped you.

**Comment by tjharman** [comment]
THANK YOU @timholl 

I spent 2 hours debugging this tonight - I knew I had my right intermediate certs etc but Jellyfin was still always serving up the wrong information.  I never would have thought to do what you suggested.

I tried running Jellyfin behind a reverse proxy but then found that Chromecast wouldn't work properly - never finished debugging why though.

Anyway, thanks very much. You've saved me a lot of grief!

**Comment by devlin016** [comment]
why dont the repo admins do wordaround #3 listed on https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ . I doubt anything that old is running a jellyfin server.

**Comment by devlin016** [comment]
still no solution found yet, I searched my machine for pfx bundles found some left over from emby installation deleted them still not connecting to jellyfin repos. im running updated openssl and no system updates or ca-updates. is there updated pfx bundles I could drop in /var/lib/jellyfin/.dotnet/corefx/cryptography/x509stores/ca/ ? im afraid im going to loose metadata scraping soon.

**Comment by brianjmurrell** [comment]
> This has the additional benefit that it is more stable

I disagree.  Adding an otherwise useless reverse proxy is just increasing overall fragility by adding yet another moving part that needs to be maintained and can break.  By definition, more things == more things that can break.

**Comment by brianjmurrell** [comment]
This problem of certificate caching in `/var/lib/jellyfin/.dotnet/corefx/cryptography/x509stores/ca/` is also causing Chrome on Android to report invalid certificates for Let's Encrypt certs.

I had to [re-]move `/var/lib/jellyfin/.dotnet/corefx/cryptography/x509stores/ca/*.pfx` before my new LE cert would stop making Chrome on Android complain.

**Comment by taylor-schneider** [comment]
Hello. Can this issue be reopened? I am running on CentOS 7.9 and seeing the same error in my logs:
```
Oct 24 18:57:20 63ef50e5eec0 jellyfin[2704]: [18:57:20] [ERR] [28] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: http://repo.jellyfin.org/releases/plugin/manifest-stable.json
Oct 24 18:57:20 63ef50e5eec0 jellyfin[2704]: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Oct 24 18:57:20 63ef50e5eec0 jellyfin[2704]: ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
```

My server does not have a /var/lib/jellyfin/.dotnet directory so I cannot delete the .pfx files.

@sevenrats ?

**Comment by sevenrats** [comment]
> Hello. Can this issue be reopened?
No. There is no reason to reopen this bug, as it is concerned with a root expiration that occurred 3 years ago.  Its unlikely that you are experiencing this bug, and even if you are, its so out of date that its still not appropriate to reopen.
