### ISSUE TITLE
Method not found: 'Void MediaBrowser.Controller.Entities.Folder.AddChild(MediaBrowser.Controller.Entities.BaseItem, System.Threading.CancellationToken)'

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin#6703]
**Describe the bug**
Scanning Libraries fails (scheduled task)

**System (please complete the following information):**
 - OS: Ubuntu Server 21.04 (Jellyfin server), Manjaro 21.1.5 Firefox (Client)
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 93
 - Jellyfin Version: Jellyfin Docker 10.8.0 (`jellyfin/jellyfin:unstable@sha256:a2fcaeef196b3f27b3e93600776516b6e68b89fc9dabf161c2e6c08eeac23acb`)
 - FFmpeg Version: Whatever is in the docker by default
 - Playback: Not applicable to this issue
 - Hardware Acceleration: Not applicable to this issue
 - Installed Plugins: MusicBrainz
 - Reverse Proxy: nginx
 - Base URL: yes, Not applicable to this issue
 - Networking: Docker (Host)
 - Storage: Local (Docker bind mount)

**To Reproduce**
Sorry, but i dont know

**Expected behavior**
Scheduled task to not fail and to not have a error in the logs

**Server Logs**

<details>
<summary>Server Logs</summary>

```txt
[2021-10-15 23:28:39.732 +00:00] [INF] [1] Main: Jellyfin version: "10.8.0"
[2021-10-15 23:28:39.747 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]"]
[2021-10-15 23:28:39.749 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2021-10-15 23:28:39.750 +00:00] [INF] [1] Main: Operating system: "Linux"
[2021-10-15 23:28:39.750 +00:00] [INF] [1] Main: Architecture: X64
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: 64-Bit Process: True
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: User Interactive: True
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: Processor count: 8
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: Program data path: "/config"
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2021-10-15 23:28:39.751 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2021-10-15 23:28:39.965 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2021-10-15 23:28:40.033 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2021-10-15 23:28:40.053 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/AniList_4.0.0.0/Jellyfin.Plugin.AniList.dll"
[2021-10-15 23:28:40.054 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.CoverArtArchive, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Cover Art Archive_3.0.0.0/Jellyfin.Plugin.CoverArtArchive.dll"
[2021-10-15 23:28:40.054 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TheTVDB_6.0.0.0/TvDbSharper.dll"
[2021-10-15 23:28:40.055 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TheTVDB_6.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2021-10-15 23:28:40.143 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-10-15 23:28:40.143 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-10-15 23:28:40.144 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-10-15 23:28:40.152 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-10-15 23:28:40.152 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-10-15 23:28:40.153 +00:00] [ERR] [1] Jellyfin.Networking.Manager.NetworkManager: Unable to parse bind override: "https://jellyfin.sylvi"
[2021-10-15 23:28:43.466 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "4.0.0.0"
[2021-10-15 23:28:43.467 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Cover Art Archive" "3.0.0.0"
[2021-10-15 23:28:43.468 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "6.0.0.0"
[2021-10-15 23:28:43.469 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.0.0"
[2021-10-15 23:28:43.470 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.0.0"
[2021-10-15 23:28:43.470 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.0.0"
[2021-10-15 23:28:43.471 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.0.0"
[2021-10-15 23:28:43.555 +00:00] [INF] [1] Main: Kestrel listening on "All Addresses"
[2021-10-15 23:28:43.830 +00:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {9660f0a8-da68-46bb-bbbd-1c8deab31c6d} may be persisted to storage in unencrypted form.
[2021-10-15 23:28:43.846 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2021-10-15 23:28:43.868 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2021-10-16 02:00:00.000 +00:00, which is 02:31:16.1311914 from now.
[2021-10-15 23:28:44.110 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.2"
[2021-10-15 23:28:44.144 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2021-10-15 23:28:44.159 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2021-10-15 23:28:44.171 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["hwupload_cuda", "overlay_cuda", "scale_cuda", "tonemap_opencl", "tonemap_vaapi", "yadif_cuda"]
[2021-10-15 23:28:44.196 +00:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "tonemap_cuda" with option "GPU accelerated HDR to SDR tonemapping" is not available
[2021-10-15 23:28:44.217 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2021-10-15 23:28:44.229 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2021-10-15 23:28:44.230 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "0411b444f3724b91bc87f05bbbb2b883"
[2021-10-15 23:28:44.323 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0789268
[2021-10-15 23:28:44.323 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2021-10-15 23:28:44.467 +00:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Shows
[2021-10-15 23:28:44.467 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Pictures
[2021-10-15 23:28:44.467 +00:00] [INF] [1] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Starting NAT discovery
[2021-10-15 23:28:44.469 +00:00] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Music
[2021-10-15 23:28:44.508 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1843582
[2021-10-15 23:28:44.508 +00:00] [INF] [1] Main: Startup complete 0:00:04.9579167
[2021-10-15 23:28:45.579 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.8" request
[2021-10-15 23:28:46.442 +00:00] [WRN] [18] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://jellyfin.sylvi/Sessions/Capabilities/Full" to "192.168.2.8" in 0:00:00.87742 with Status Code 204
[2021-10-15 23:28:46.871 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2021-10-15 23:28:46.871 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2021-10-15 23:28:46.873 +00:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2021-10-15 23:28:48.257 +00:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2021-10-15 23:28:48.265 +00:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-10-15 23:28:53.528 +00:00] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2021-10-15 23:28:53.538 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Shows"
[2021-10-15 23:28:53.541 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Music"
[2021-10-15 23:28:53.541 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Pictures"
[2021-10-15 23:28:53.544 +00:00] [INF] [24] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2021-10-15 23:28:55.561 +00:00] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Pictures
[2021-10-15 23:28:55.562 +00:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Shows
[2021-10-15 23:28:55.559 +00:00] [ERR] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.Folder.AddChild(MediaBrowser.Controller.Entities.BaseItem, System.Threading.CancellationToken)'.
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.AddVirtualSeason(Int32 season, Series series)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.AddMissingSeasons(Series series, List`1 existingSeasons, IReadOnlyList`1 allSeasons)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.ConcatIterator`1.ToList()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.HandleSeries(Series series)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnProviderManagerRefreshComplete(Object sender, GenericEventArgs`1 genericEventArgs)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshComplete(BaseItem item)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass71_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass71_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-10-15 23:28:55.563 +00:00] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 2 seconds
[2021-10-15 23:28:55.563 +00:00] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Music
[2021-10-15 23:28:55.564 +00:00] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

</details>

**FFmpeg Logs**
Not applicable to this issue

**Browser Console Logs**
Not applicable to this issue

**Screenshots**
![Screenshot_20211016_013302](https://user-images.githubusercontent.com/10911626/137564377-a440bb1b-e6c3-4372-83e7-4dc7ac2c0d6b.png)

**Additional context**

**Comment by crobibero** [comment]
This isn’t a bug. Plugins aren’t updated to support  unstable Jellyfin releases.

**Comment by hasezoey** [comment]
> This isn’t a bug. Plugins aren’t updated to support unstable Jellyfin releases.

sorry, didnt notice this was a plugins issue

---

even though its a plugin issue, should the "Scan All Libraries" really fail because of a plugin error? (from what i can tell, it aborts the whole scan)

**Comment by gazhay** [comment]
I'm using stable jellyfin and the yvdb plugin causes this and you cannot uninstall it.
Well, you can uninstall it, but it is still active and reinstalls itself if you restart the server.

Currently have an empty library because of the issue.
