### ISSUE TITLE
Unable to parse XML from XMLTV-EPG

### ISSUE THREAD

**Issue by battkajs** [jellyfin/jellyfin#6730]
**Describe the bug**
Unable to retrieve EPG data from XMLTV source. XML-reader throws errors parsing XML

**System (please complete the following information):**
 - OS: Unraid 6.9.2
 - Virtualization: Docker
 - Clients: Server
 - Browser: Fireox 93
 - Jellyfin Version: 10.7.7
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: none
 - Networking: Bridge
 - Storage: Local
  
**To Reproduce**

1. Settings
2. Live-Tv
3. Add EPG & EPG-link
4. sync

**Expected behavior**
Retrieve EPG data from provider

**Server Logs**
```
> [2021-10-24 15:31:29.846 +02:00] [INF] [129] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "https://www.xtream-editor.com/en/get/epg/... "
> [2021-10-24 15:31:29.846 +02:00] [ERR] [129] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel ... "
> System.Xml.XmlException: Root element is missing.
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
>    at System.Xml.XmlReader.ReadToDescendant(String name)
>    at Jellyfin.XmlTv.XmlTvReader.GetChannels()
>    at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /tmp/makepkg/jellyfin/src/jellyfin-10.7.7/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs:line 283
>    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /tmp/makepkg/jellyfin/src/jellyfin-10.7.7/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 397
>    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannelFromTunerChannel(IListingsProvider provider, ListingsProviderInfo info, ChannelInfo tunerChannel, CancellationToken cancellationToken) in /tmp/makepkg/jellyfin/src/jellyfin-10.7.7/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 416
>    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken) in /tmp/makepkg/jellyfin/src/jellyfin-10.7.7/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 917
>    at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken) in /tmp/makepkg/jellyfin/src/jellyfin-10.7.7/Emby.Server.Implementations/LiveTv/LiveTvManager.cs:line 1180
> [2021-10-24 15:31:29.847 +02:00] [INF] [129] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Refresh Guide" Completed after 0 minute(s) and 40 seconds
> [2021-10-24 15:31:29.848 +02:00] [INF] [129] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

**FFmpeg Logs**
N/A

**Browser Console Logs**
N/A

**Screenshots**
N/A
**Additional context**
Happens to all channels. Tried EPG data from both IPTV-provider and xtream-editor. Same error. Tried clean /cache/xmltv

**Comment by crobibero** [comment]
I can't reproduce this in 10.8 (current master), so the issue may be fixed.

Tested with:
playlist: https://iptv-org.github.io/iptv/countries/uk.m3u
epg: https://iptv-org.github.io/epg/guides/uk/ontvtonight.com.epg.xml
