### ISSUE TITLE
Cannot get image dimensions

### ISSUE THREAD

**Issue by subzero355** [jellyfin/jellyfin#6755]
Seeing this on the logs and images appear blank on Jellyfin

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Mobile iOS
 - Browser: Firefox 93
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: 
 - Playback: Direct play
 - Hardware Acceleration: none
 - Installed Plugins: none
 - Reverse Proxy: nginx(swag)
 - Base URL: /
 - Networking: Bridge
 - Storage: Cloud

**Server Logs**
```
[12:19:40] [ERR] [157] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /gp/media/all/IMG_0677.JPG
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[12:19:54] [ERR] [159] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for /config/data/metadata/library/ef/ef203e311bb9b43dca5891a7758fa703/folder.jpg
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
[12:19:54] [ERR] [159] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for /config/data/metadata/library/69/690fd522bdbfbc2da77ec289d8daf7a8/folder.jpg
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
[12:19:54] [ERR] [159] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for /config/data/metadata/library/ac/ac7efeb53b6081605d36c50ae85a9ecd/folder.jpg
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
[12:19:54] [ERR] [159] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for /config/data/metadata/library/fd/fd8953985dfb09ba81d9b441f27f9995/folder.jpg
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)

```

**Browser Console Logs**
no errors

**Comment by deric** [comment]
I've seen similar errors when parsing an empty image file. Maybe skipping files with `size == 0` could help, or more sophisticated MIME header check before trying to get image dimensions might fix this.

**Comment by dannymichel** [comment]
> I've seen similar errors when parsing an empty image file. Maybe skipping files with `size == 0` could help, or more sophisticated MIME header check before trying to get image dimensions might fix this.

i agree
