### ISSUE TITLE
10.8.0 NFO read error

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin#6773]
**Describe the bug**
For compatibility, I always choose "Kodi / Xbmc < 16" as the NFO format in the tinyMediaManager.
10.7.7 reads the NFO(<16) format smoothly, but 10.8.0 cannot read the format.
If I choose a newer NFO format, 10.8.0 can read it.
It seems that 10.8.0 has modified the method of reading fields and generated errors.

**System (please complete the following information):**
 - Jellyfin Version: [10.8.0 nightly or alpha]
 
**Server Logs**

[2021-11-04 02:47:39.314 +00:00] [ERR] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Nfo"
System.InvalidOperationException: The ReadElementContentAsString method is not supported on node type None. Line 0, position 0.
   at System.Xml.XmlReader.SetupReadElementContentAsXxx(String methodName)
   at System.Xml.XmlReader.ReadElementContentAsString()
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.FetchThumbNode(XmlReader reader, MetadataResult`1 itemResult)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.FetchDataFromXmlNode(XmlReader reader, MetadataResult`1 itemResult)
   at MediaBrowser.XbmcMetadata.Parsers.MovieNfoParser.FetchDataFromXmlNode(XmlReader reader, MetadataResult`1 itemResult)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(MetadataResult`1 item, String metadataFile, XmlReaderSettings settings, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(MetadataResult`1 item, String metadataFile, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Providers.BaseVideoNfoProvider`1.Fetch(MetadataResult`1 result, String path, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Providers.BaseNfoProvider`1.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)

**Comment by cvium** [comment]
Please include a minimal NFO that triggers the issue.

**Comment by shaino** [comment]
The NFO that triggers the issue. I renamed the nfo to txt.
[Training.Day.2001.1080p.BluRay.x265.10bit.DD.5.1-PTH.txt](https://github.com/jellyfin/jellyfin/files/7473997/Training.Day.2001.1080p.BluRay.x265.10bit.DD.5.1-PTH.txt)

**Comment by cvium** [comment]
The issue is the `fanart` tag. We only support this format:
```
<fanart>
    <thumb preview=""></thumb>
</fanart>
```

But I have stopped it from crashing, but you will have to wait for a new release (or change the NFO format).

**Comment by shaino** [comment]
Great job ！Thanks.
