### ISSUE TITLE
[Issue]: Error extracting DLNA profiles.

### ISSUE THREAD

**Issue by marius-luca-87** [jellyfin/jellyfin#6878]
### Please describe your bug

When starting Jellyfin 10.8.0 Alpha 2 with old DLNA system profiles an exception is thrown and all DLNA profiles stop from loading.

### Jellyfin Version

Other

### if other:

10.8.0 Alpha 2

### Environment

```markdown
- OS: Windows 11/Official Docker Image
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Emby.Dlna.DlnaManager: Error extracting DLNA profiles.
System.IO.IOException: The file 'C:\Users\Marius\AppData\Local\jellyfin\config\dlna\system\Sony Bravia (2010).xml' already exists.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at Emby.Dlna.DlnaManager.ExtractSystemProfilesAsync() in e:\OpenSource\jellyfin\Emby.Dlna\DlnaManager.cs:line 355
   at Emby.Dlna.DlnaManager.InitProfilesAsync() in e:\OpenSource\jellyfin\Emby.Dlna\DlnaManager.cs:line 64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marius-luca-87** [comment]
[Sony Bravia (2010).zip](https://github.com/jellyfin/jellyfin/files/7574780/Sony.Bravia.2010.zip)

**Comment by marius-luca-87** [comment]
Just erasing the existing DLNA system profiles and restarting the server solves the issue.
