### ISSUE TITLE
[Issue]: V4L2 MFC Transcoding Broken on 10.8

### ISSUE THREAD

**Issue by neo-neo1** [jellyfin/jellyfin#6931]
### Bug

Exynos V4L2 MFC Transcoding works fine on 10.7.7 but broken on 10.8 branch. Tested back-to-back on freshly installed 10.7.7 and 10.8 Alpha 2 with default settings using same 4.3.1 ffmpeg version for both (also tried ffmpeg 4.3.2). On an Exynos SoC (ODROID-HC2).

Transcoding on 10.8.0 Alpha 2 failing with:
```
Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/bd4201f1-9586-e05f-b8b5-ec2b9e412848/hls1/main/0.ts".
System.ArgumentException: Requested value 'h264_v4l2m2m' was not found.
```

Info:
```
[INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.1"
[INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_mmal", "hevc", "mpeg2video", "mpeg2_mmal", "mpeg4", "mpeg4_mmal", "msmpeg4", "vc1_mmal", "aac", "ac3", "flac", "mp3"]
[INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_omx", "h264_v4l2m2m", "libx265", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "drm"]
```

### Environment

```markdown
- Jellyfin: 10.8.0 Alpha 2
- Device: ODROID-HC2 (Samsung Exynos 5422 SoC)
- OS: Armbian 21.08.3 Buster
- Kernel: Linux 5.4.151-odroidxu4
- Virtualization: Docker 20.10.10
- Docker Image: linuxserver/jellyfin:nightly & jellyfin/jellyfin:unstable (see blow for details)
- Browser: FireFox 94.0.2 (64-bit)
- FFmpeg Version: 4.3.1 & 4.3.2 (tried both)
- Playback Method: FireFox 94.0.2 (64-bit) on macOS 10.14.6 
- Hardware Acceleration: V4L2 MFC
- Plugins: None
```
### Docker Images
```markdown
Working:
- jellyfin/jellyfin:latest (10.7.7 with ffmpeg 4.3.2) 
- linuxserver/jellyfin:latest (10.7.7 with ffmpeg 4.3.1)

Error:
- jellyfin/jellyfin:unstable (10.8.0 Alpha 2 with ffmpeg 4.3.2) 
- linuxserver/jellyfin:nightly (10.8.0 Alpha 2 with ffmpeg 4.3.1)


```

Again, only variable I changed is Jellyfin version and suddenly transcoding fails, crippling Jellyfin.
If additional info needed, just ask. Thanks in advance.

**Comment by nyanmisaka** [comment]
Please share the full ffmpeg transcoding log.

**Comment by neo-neo1** [comment]
> Please share the full ffmpeg transcoding log.

If hardware acceleration is turned on, no ffmpeg transcode log gets created. [Here's a full main log](https://0bin.net/paste/FB8LymSK#hIWELUm52B8K4s7HaW+ft4QIc9oC0lVGNEDXD4Cp+pN). From boot to attempted video plays that fail.

**Comment by nyanmisaka** [comment]
```
System.ArgumentException: Requested value 'h264_v4l2m2m' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Jellyfin.Api.Helpers.TranscodingJobHelper.ReportTranscodingProgress(TranscodingJobDto job, StreamState state, Nullable`1 transcodingPosition, Nullable`1 framerate, Nullable`1 percentComplete, Nullable`1 bytesTranscoded, Nullable`1 bitRate)
   at Jellyfin.Api.Helpers.TranscodingJobHelper.OnTranscodeBeginning(String path, String playSessionId, String liveStreamId, String transcodingJobId, TranscodingJobType type, Process process, String deviceId, StreamState state, CancellationTokenSource cancellationTokenSource)
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
```

The PR https://github.com/jellyfin/jellyfin/pull/6258 and https://github.com/jellyfin/jellyfin-web/pull/2776 introduced in 10.8 alpha could be the cause.

The name of V4L2 was hardcoded to `h264_v4l2m2m` in [jellyfin-web](https://github.com/jellyfin/jellyfin-web/blob/b6d6a368cb3a5075d5949cb4d0ad9dced0d9ffc3/src/controllers/dashboard/encodingsettings.html#L21)

I will try to fix it by the way in my upcoming PR.
