### ISSUE TITLE
[Issue]: Change port to 80 causes Jellyfin to fail.

### ISSUE THREAD

**Issue by NephtonLabs** [jellyfin/jellyfin#6987]
### Please describe your bug

Changed port number under Home > Admin > Dashboard > Advanced > Networking
Set local HTTP port number to 80. 
Saved, opened the port in firewall-cmd and restarted Jellyfin. Jellyfin disappeared from port 8096, did not start on port 80. 
Logs show it's an invalid port. I have no idea why the would be the case. Providing the logs from /var/log/ 
I can recreate this if you need more logs. Just tell me which files to pull. 

Really love the project.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Rocky Linux (RHEL8)
- Virtualization: ESXi 5.5
- Clients: Web
- Browser: Firefox, Edge
- FFmpeg Version: 4.2.5
- Playback Method: Web
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: http://172.16.0.20:8096
- Networking: LAN
- Storage: mix of local and nas
```

### Jellyfin logs

```shell
/var/log/jellyfin/log_[blah].log exerp:
[2021-12-12 17:32:34.916 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2021-12-12 17:32:34.917 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2021-12-12 17:32:34.921 -05:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2021-12-12 17:32:35.682 -05:00] [INF] [1] Main: Jellyfin version: "10.7.7"
[2021-12-12 17:32:35.721 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/libexec/jellyfin/restart.sh]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin-web]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]"]
[2021-12-12 17:32:35.726 -05:00] [INF] [1] Main: Arguments: ["/usr/lib64/jellyfin/jellyfin.dll", "--webdir=/usr/share/jellyfin-web", "--restartpath=/usr/libexec/jellyfin/restart.sh"]
[2021-12-12 17:32:35.727 -05:00] [INF] [1] Main: Operating system: "Linux"
[2021-12-12 17:32:35.727 -05:00] [INF] [1] Main: Architecture: X64
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: 64-Bit Process: True
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: User Interactive: True
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: Processor count: 2
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: Program data path: "/var/lib/jellyfin"
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin-web"
[2021-12-12 17:32:35.729 -05:00] [INF] [1] Main: Application directory: "/usr/lib64/jellyfin/"
[2021-12-12 17:32:36.014 -05:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/var/cache/jellyfin"
[2021-12-12 17:32:36.088 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-12-12 17:32:36.088 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-12-12 17:32:36.089 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-12-12 17:32:36.101 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-12-12 17:32:36.101 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-12-12 17:32:36.129 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2021-12-12 17:32:38.600 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.7.7.0"
[2021-12-12 17:32:38.601 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.7.7.0"
[2021-12-12 17:32:38.602 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.7.7.0"
[2021-12-12 17:32:38.713 -05:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2021-12-12 17:32:39.299 -05:00] [FTL] [1] Microsoft.AspNetCore.Server.Kestrel: Unable to start Kestrel.
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
[2021-12-12 17:32:39.309 -05:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again.
[2021-12-12 17:32:39.309 -05:00] [FTL] [1] Main: Error while starting server.
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Ports under 1024 are reserved by the OS. This is not a bug in Jellyfin.

**Comment by NephtonLabs** [comment]
Oop, missed the obvious. For anyone who comes across this: root is required to run services on ports 1024 and lower. I'm guessing adding the ability to satisfy this requirement securely is more effort than it was worth. Work around would be to run nginx as a reverse proxy and point that to Jellyfin. There are probably also security benefits to doing it that way.

**Comment by GregTheHun** [comment]
I think eventually this should be changed, but I understand the effort it would take.

**Comment by NephtonLabs** [comment]
Oh, follow up on this I came across on another project
sudo setcap cap_net_bind_service=+ep /usr/share/jellyfin
sudo setcap cap_net_bind_service=+ep /usr/share/jellyfin-web
I haven't tested this, but it should allow the web interface to run on port 80

**Comment by tefod-zz** [comment]
In Alpine Linux following does work for binding to port 80: 

- apk add libcap-setcap
- setcap cap_net_bind_service=+ep $(which jellyfin)

**Comment by martin-kuenzel** [comment]
> In Alpine Linux following does work for binding to port 80:
> 
> * apk add libcap-setcap
> * setcap cap_net_bind_service=+ep $(which jellyfin)

actually I needed to rewrite the second command as follows:

```setcap cap_net_bind_service=+ep $(realpath $(which jellyfin))```
