### ISSUE TITLE
[Issue]: Fresh 10.8-alpha3 docker install cannot start

### ISSUE THREAD

**Issue by richardbrodie** [jellyfin/jellyfin#6995]
### Please describe your bug

A basic docker install of 10.8-a3 is unable to start and complains about a missing config file.

This install is essentially a duplicate of an already working 10.7 docker install. I created a new empty config directory. I get the following error:

```
jellyfin_new     | Unhandled exception. [09:10:50] [FTL] [1] Main: Unhandled Exception
jellyfin_new     | System.IO.FileNotFoundException: Could not find file '/config/config/migrations.xml'.
jellyfin_new     | File name: '/config/config/migrations.xml'
jellyfin_new     |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.File.OpenRead(String path)
jellyfin_new     |    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
jellyfin_new     |    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
jellyfin_new     |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin_new     |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin_new     | System.IO.FileNotFoundException: Could not find file '/config/config/migrations.xml'.
jellyfin_new     | File name: '/config/config/migrations.xml'
jellyfin_new     |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.File.OpenRead(String path)
jellyfin_new     |    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
jellyfin_new     |    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
jellyfin_new     |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin_new     |    at Jellyfin.Server.Program.<Main>(String[] args)
```

docker-compose.yml
```yaml
version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.0-alpha3
    container_name: jellyfin_new
    user: uid:gid
    ports:
      - "8096:8096"
    volumes:
      - /opt/appdata/jellyfin_new:/config
      - /tmp/jellyfin_new:/cache
      - /mnt/media:/media
    restart: "unless-stopped"
```

### Jellyfin Version

Other

### if other:

10.8.0-alpha3

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
jellyfin_new     | Unhandled exception. [09:10:50] [FTL] [1] Main: Unhandled Exception
jellyfin_new     | System.IO.FileNotFoundException: Could not find file '/config/config/migrations.xml'.
jellyfin_new     | File name: '/config/config/migrations.xml'
jellyfin_new     |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.File.OpenRead(String path)
jellyfin_new     |    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
jellyfin_new     |    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
jellyfin_new     |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin_new     |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin_new     | System.IO.FileNotFoundException: Could not find file '/config/config/migrations.xml'.
jellyfin_new     | File name: '/config/config/migrations.xml'
jellyfin_new     |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_new     |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_new     |    at System.IO.File.OpenRead(String path)
jellyfin_new     |    at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
jellyfin_new     |    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
jellyfin_new     |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin_new     |    at Jellyfin.Server.Program.<Main>(String[] args)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by richardbrodie** [comment]
Seems like it's a duplicate of #6992
