### ISSUE TITLE
[Issue]: Unable to determine image file extension from mime type image/jpg for comic book cover extraction.

### ISSUE THREAD

**Issue by marius-luca-87** [jellyfin/jellyfin#7097]
### Please describe your bug

When replacing all metadata including existing images (from the refresh metadata menu) for CBZ comic books (ZIP files with jpg images inside) an exception is thrown by the "Comic Book Zip Archive Cover Extractor".

The exception is thrown by
https://github.com/jellyfin/jellyfin/blob/37061e5b6b3116ef46ca2cd9362ba9c11c76b6a7/MediaBrowser.Providers/Manager/ImageSaver.cs#L365
stating
`Unable to determine image file extension from mime type image/jpg`

My initial guess would be that the _extensionLookup dictionary from MimeTypes.cs is missing an entry for image/jpg like it exists for image/jpeg.
https://github.com/jellyfin/jellyfin/blob/37061e5b6b3116ef46ca2cd9362ba9c11c76b6a7/MediaBrowser.Model/Net/MimeTypes.cs#L119

### Jellyfin Version

Other

### if other:

unstable based on 37061e5b6b3116ef46ca2cd9362ba9c11c76b6a7

### Environment

```markdown
- Virtualization:Docker
```

### Jellyfin logs

```shell
[ERR] [132] MediaBrowser.Providers.Books.BookMetadataService: Error in "Comic Book Zip Archive Cover Extractor"
System.ArgumentException: Unable to determine image file extension from mime type image/jpg
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marius-luca-87** [comment]
A change might be required at
https://github.com/jellyfin/jellyfin/blob/e51777fe4ba9ee14975d9b425cb18810819ff179/MediaBrowser.Providers/Manager/ItemImageProvider.cs#L200
to make sure that the correct mime type is provided.
