### ISSUE TITLE
[Issue]: Scan Library fails in 10.8.0-alpha3 and 20220104.4-unstable

### ISSUE THREAD

**Issue by heitbaum** [jellyfin/jellyfin#7100]
### Please describe your bug

Fresh install of jellyfin_10.8.0-alpha3 / and tested with update to jellyfin_20220104.4-unstable. 
The Libraries are not scannable.

I noticed this a few days ago when I upgraded the 2.7.6 database to 2.8 and was unable to add a new movie. But didn't think any more of it. In an attempt to do the scan - I cleared away the "migrated 2.7.6 --> 2,8" configuration and started from scratch.

I even simplified the Movies to a single folder `/var/media/A-K/Movies`

### Jellyfin Version

Other

### if other:

jellyfin_20220104.4-unstable

### Environment

```markdown
- OS: LibreELEC 11
- Virtualization: No
- Clients: N/A
- Browser: Edge 96.0.1054.62
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
Running a `Scan Library` the following errors display

[19:41:55] [DBG] [27] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[19:42:05] [DBG] [11] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: CollectionFolderImageProvider reports change to /storage/.kodi/userdata/addon_data/service.jellyfin/root/default/Movies
[19:42:05] [DBG] [11] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Running CollectionFolderImageProvider for /storage/.kodi/userdata/addon_data/service.jellyfin/root/default/Movies
[19:42:05] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart e3f7e2abc015d126948889493552500d
[19:42:05] [ERR] [11] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at DiscUtils.Udf.ImplementationUseExtendedAttributeRecord.ReadFrom(Byte[] buffer, Int32 offset)
   at DiscUtils.Udf.FileEntry.ReadExtendedAttributes(Byte[] eaData)
   at DiscUtils.Udf.FileEntry.ReadFrom(Byte[] buffer, Int32 offset)
   at DiscUtils.Streams.EndianUtilities.ToStruct[T](Byte[] buffer, Int32 offset)
   at DiscUtils.Udf.File.FromDescriptor(UdfContext context, LongAllocationDescriptor icb)
   at DiscUtils.Udf.UdfReader.VfsUdfReader.Initialize()
   at DiscUtils.Udf.UdfReader.VfsUdfReader..ctor(Stream data)
   at DiscUtils.Udf.UdfReader..ctor(Stream data)
   at Emby.Server.Implementations.Library.Resolvers.BaseVideoResolver`1.SetIsoType(Video video)
   at Emby.Server.Implementations.Library.Resolvers.BaseVideoResolver`1.SetVideoType(Video video, VideoFileInfo videoInfo)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveVideos[T](Folder parent, IEnumerable`1 fileSystemEntries, Boolean supportMultiEditions, String collectionType, Boolean parseName)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveMultipleInternal(Folder parent, List`1 files, String collectionType)
   at Emby.Server.Implementations.Library.Resolvers.Movies.MovieResolver.ResolveMultiple(Folder parent, List`1 files, String collectionType, IDirectoryService directoryService)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, String collectionType, IItemResolver[] resolvers)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, String collectionType)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
[19:42:05] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete e3f7e2abc015d126948889493552500d
[19:42:07] [DBG] [17] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[19:42:19] [DBG] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[19:42:19] [INF] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stanionascu** [comment]
Looks like an issue with opening and reading the UDF/ISO images. Needs a try/catch around this [block](https://github.com/jellyfin/jellyfin/blob/923720c988ce62ce5c57337252cf981ceeef9a23/Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs#L160) to allow it to go forward. Is that an Joliet ISO 9660 image?

**Comment by heitbaum** [comment]
> Looks like an issue with opening and reading the UDF/ISO images. Needs a try/catch around this [block](https://github.com/jellyfin/jellyfin/blob/923720c988ce62ce5c57337252cf981ceeef9a23/Emby.Server.Implementations/Library/Resolvers/BaseVideoResolver.cs#L160) to allow it to go forward. Is that a Joliet ISO 9660 image?

👍 Yes .iso in that directory
