### ISSUE TITLE
[Issue]: Plugins wont install after upgrading to latest  10.8.0-alpha-5

### ISSUE THREAD

**Issue by NotExpectedYet** [jellyfin/jellyfin#7122]
### Please describe your bug

After upgrading to 10.8.0 some of my plugins failed to upgrade with it. 

I have just tried uninstalling one of them and re-installing but to no avail. Get the same issue. 

Effected Plugins Already Installed: 
KodiSyncQueue
Bookshelf

Just tried installing Trakt to test as I've never installed that and I'm getting the same.

### Jellyfin Version

Other

### if other:

10.8.0-alpha-5

### Environment

```markdown
- OS: Linux / UnRaid
- Virtualization: Docker
- Clients: Web/Kodi
- Browser: Firefox / Chrome
- FFmpeg Version: 4.4.1-Jellyfin
- Playback Method: Web
- Hardware Acceleration: 
- Plugins: AudioDB, Bookshelf, Cover Art Archive, Fanart, Merge Version, MusicBrainz, OMDB, Open Subs, Playback reporting, Reports, Skin Manager, Studio Imagtes, TMDB, TMDB Box sets, TVDB, Youtube Metadata
- Reverse Proxy:  nginx
- Base URL: none
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[11:58:30] [ERR] [21] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing Kodi Sync Queue, expected: e52d995ff1121e4a29b9d15868ab5b44, got: F05514132B36C8BC84BC182BEC65D1D3
[11:58:30] [ERR] [21] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SigHunter** [comment]
happens to me too with alpha5 and trakt plugin

`[11:35:11] [INF] [272] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Aktualisiere Plugins
[11:35:13] [ERR] [250] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing Trakt, expected: c4ce367cfe8637a4af15e204311a0c77, got: C1ACCFA9739711A980131012250BBE82
[11:35:13] [ERR] [250] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[11:35:13] [ERR] [250] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[11:35:13] [INF] [250] Emby.Server.Implementations.ScheduledTasks.TaskManager: Aktualisiere Plugins Failed after 0 minute(s) and 1 seconds`

**Comment by badabing2** [comment]
Same checksum error on Windows 10 trying to install Open Subtitles (Dashboard>Plugins>Catalog). Clean 10.7.7 install with 10.8.0alpha5 update.

**Comment by Shadowghost** [comment]
The plugin publishing broke when 10.8-alpha5 was published resulting in bad files and checksums in the stable repo.
It's currently being worked on fixing this.

**Comment by crobibero** [comment]
This has been fixed

**Comment by NotExpectedYet** [comment]
> This has been fixed

And how do we use the fix as I'm still getting this

```
[05:51:46] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
today at 05:51:46[05:51:46] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Packages/Installed/Kodi%20Sync%20Queue.
today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
today at 05:51:46   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
today at 05:51:46   at lambda_method1017(Closure , Object )
today at 05:51:46   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

**Comment by SigHunter** [comment]
> This has been fixed

thanks, works for me, had to do nothing on my end

**Comment by crobibero** [comment]
> 

Which plugin are yout having issues with?

> > This has been fixed
> 
> And how do we use the fix as I'm still getting this
> 
> ```
> [05:51:46] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
> today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> today at 05:51:46[05:51:46] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Packages/Installed/Kodi%20Sync%20Queue.
> today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> today at 05:51:46   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
> today at 05:51:46   at lambda_method1017(Closure , Object )
> today at 05:51:46   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> ```

Which plugin and version are you having issues with?

**Comment by NotExpectedYet** [comment]
> > 
> 
> Which plugin are yout having issues with?
> 
> > > This has been fixed
> > 
> > 
> > And how do we use the fix as I'm still getting this
> > ```
> > [05:51:46] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
> > today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> > today at 05:51:46[05:51:46] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Packages/Installed/Kodi%20Sync%20Queue.
> > today at 05:51:46System.IO.InvalidDataException: The checksum of the received data doesn't match.
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> > today at 05:51:46   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
> > today at 05:51:46   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
> > today at 05:51:46   at lambda_method1017(Closure , Object )
> > today at 05:51:46   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> > ```
> 
> Which plugin and version are you having issues with?

KodiSync queue won't re-install and none of my current ones will upgrade to their latests on the plugin upgrade task. 

```
[13:07:51] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing Bookshelf, expected: 93affe332486f5ad334ff7c1446cafa7, got: 9E07983548B40FEF9ABB764F4DB95B6A
[13:07:51] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[13:07:51] [ERR] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.InvalidDataException: The checksum of the received data doesn't match.
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[13:07:51] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Failed after 0 minute(s) and 14 seconds
[13:07:51] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[13:07:51] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing Bookshelf, expected: 93affe332486f5ad334ff7c1446cafa7, got: 9E07983548B40FEF9ABB764F4DB95B6A
[13:07:51] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[13:07:51] [ERR] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.IO.InvalidDataException: The checksum of the received data doesn't match.
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[13:07:51] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Failed after 0 minute(s) and 14 seconds
[13:07:51] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

So still seems to be all of them for me. I've just tried installing LDAP plugin and it gave the same error. Never before been installed.

**Comment by NotExpectedYet** [comment]
Trakt worked

**Comment by NotExpectedYet** [comment]
Of my previously installed plugins these wouldn't install. 

- [ ] Bookshelf 
- [ ] Kodi Sync Queue
- [ ] Playback Reporting
- [ ] Open Subtitles

Extra I tried:
- [ ] LDAP

Everything else seemed to work although I haven't tried installing every single plugin

**Comment by harsh0596** [comment]
@NotExpectedYet same here

**Comment by crobibero** [comment]
We're not sure what the root cause of the manifest updating, but I've refreshed the manifest to have the proper hash for the latest version of each plugin

**Comment by NotExpectedYet** [comment]
> We're not sure what the root cause of the manifest updating, but I've refreshed the manifest to have the proper hash for the latest version of each plugin

That got it! Thanks :dancers:
