### ISSUE TITLE
[Issue]: Movie not moving to collection

### ISSUE THREAD

**Issue by jshwrner** [jellyfin/jellyfin#7177]
I'm unable to get a movie to show up in a collection. I have a series of 5 and all but the first show in the collection. I've tried updating the Box Set ID and manually "Add to Collection" but nothing helps. I've gone to the extent of Identifying the movie as something else, stripping all metadata, adding to other collections and I get the same results. Every other movie I've tried adding to collections works perfect, there's just something wrong with this single instance. 

Any recommendations as to where I can continue troubleshooting? Did something in the database get screwed up? I also tried deleting the `/var/jellyfin/data/collections/[movie_title]` directory and it just gets automatically generated again with no new results.

I couldn't find many relevant logs but posted an exception that occurred around the time I was trying to move the file to a collection. It may or may not be relevant as it's surrounding by thousands of logs that say "Unable to find linked item at path"

Steps to reproduce:
No idea as it's only happening with this single movie. I can't replicate it with any other film.

Thanks!

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Raspbian GNU/Linux 10 (buster)
- Virtualization: 
- Clients: Browser
- Browser: Firefox 95.0.2
- FFmpeg Version: 4.1.8-0+deb10u1+rpt1
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: AutoOrganize (v9.0.0.0), OMDB (v10.7.7.0), TMDb Box Sets (7.0.0.0)
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Api.Controllers.ItemsController.GetItems(Nullable`1 userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, String[] excludeItemTypes, String[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, String[] mediaTypes, ImageType[] imageTypes, String[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
   at Jellyfin.Api.Controllers.ItemsController.GetItemsByUserId(Guid userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, String[] excludeItemTypes, String[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, String[] mediaTypes, ImageType[] imageTypes, String[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
   at lambda_method344(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MRDJellyfin** [comment]
I don't know if this can help you, I had a similar problem in Windows 10 64 and what I did was uninstall AutoOrganize, disable the option to create collections automatically (which is in the control panel, libraries and in the library specifies in which there are your movies, in the three points (bottom right) you look for manage library, and there you look for the option to include automatically in collections and disable it if it is (as you already have the TMDb Box Sets complement you don't need it anymore) , then in the movie that you want to include, you enter the metadata configuration and look for the option that says: TheMovieDb Box Set id: and there you put the ID that is in the other movies of the collection in which you have a problem, close the session and restart the server, when you restart the session you look for the movie in question and try to add it to the collection you want or, you go to the control panel, to scheduled tasks (normally it is until the end) and there at the end it is There is the option for TheMovieDb Box Set to scan for new files or collections (in my case in practice it does it automatically and I didn't have to do anything else, since the movie I had problems with had already been added to the corresponding collection ). If this works for you, I would recommend that you do not install AutoOrganize again, since if so, there is something that is affecting said movie, good luck.

**Comment by jshwrner** [comment]
Thanks for the suggest, although the problem still persists... Any other thoughts?

**Comment by MRDJellyfin** [comment]
Take note of the number assigned by TMDb Box Sets to the movies and uninstall the Plugin (TMDb Box Sets), also YOU ​​MUST NOT HAVE THE OPTION ENABLED TO CREATE COLLECTIONS AUTOMATICALLY (which is very different from the option to group by collections in the movies folder ), AS I INDICATED YOU BEFORE (it seems to me that you did not disable it because it is the only way in which the collections are created automatically if you have uninstalled the TMDb Box Sets plugin at least in Windows 10 and one way in What you can verify, is if your collections have the word - Collection added, it is that you remove it from any collection (but I would recommend that it be the collection in question so as not to affect the others) and see if it adds it again (if it already you have uninstalled the TMDb Box Sets plugin), surprise, you still have the option to create collections automatically enabled) AND YOU MUST HAVE THE AutoOrganize PLUGIN UNINSTALLED), log out, and close Jellyfin, delete the folder of the particular collection that has the problem that is inside collections, check the .nfo file of the movie in question so that it has included that it is part of a collection and its number, if it does not have it, you need to modify the nfo file and add it in the same place where the other movies have it, with that you will ensure that it is also part of said collection (if you can't, it doesn't matter, you will do it later). Restart jellyfin, create a collection with the same name assigned to it by TMDb Box Sets and include all the movies you want to be in it, in theory the problem movie should already be in the collection you created, check the metadata (of the collection you created) that the number assigned by TMDb Box Sets is there and in each of the movies (and especially to the movie in question and to the collection itself), you will be able to install the TMDb Box Sets plugin again (don't go enable the option to create collections automatically). If everything is correct, you can install the AutoOrganize Plugin and see if it doesn't delete the movie in question, if it does you know what to do and start over and don't install it. I forgot to point out, that before you close the Jellyfin session you have to clear the cache (it's in control panel until the end at least in Windows), also after you close Jellyfin, I don't know if you can clear the cache in general (from the browser, the operating system, etc.). Good Luck

**Comment by jshwrner** [comment]
ended up upgrading and re-importing everything, which ultimately solved the issue. Not entirely sure the cause but it's not longer a problem.
