### ISSUE TITLE
Cannot get image dimensions 

### ISSUE THREAD

**Issue by stylab** [jellyfin/jellyfin#7201]
Hi

I just moved to jellyfin from emby, and i see a lot of this in my log

[2022-01-16 21:36:58.802 +00:00] [ERR] [57] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "PATH-REMOVED/clearart.png"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)

I am running Version: 10.7.7

i did try to do a full refresh of meta data but that only replaced some of the images so still get a lot of this

The images are fine did test them

**Comment by stylab** [comment]
This is still a problem any progress here?
