### ISSUE TITLE
[Issue]:  sql took too much time

### ISSUE THREAD

**Issue by FamliarMan** [jellyfin/jellyfin#7206]
### Please describe your bug

Sometims the sql took so much time,like this:

```
Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 4678.2418ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
```

This happens after I imported many many pictures into a picture library. 

More logs are as following:

```
[11:49:36] [DBG] [31] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:49:39] [WRN] [31] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:49:39] [DBG] [31] Emby.Server.Implementations.Session.WebSocketController: Removing websocket from session e936c3a126152533762745167e255c94
[11:49:39] [DBG] [31] Emby.Server.Implementations.Session.SessionManager: Disposing session controller WebSocketController
[11:49:39] [INF] [31] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.0.104 closed
[11:51:08] [DBG] [45] Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware: Normalizing an URL at /
[11:51:08] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[11:51:08] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[11:51:08] [DBG] [21] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[11:51:08] [DBG] [21] Jellyfin.Networking.Manager.NetworkManager: 192.168.0.104/32: GetBindInterface: Has found matching interface. 192.168.0.104
[11:51:08] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[11:51:08] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[11:51:08] [DBG] [6] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[11:51:08] [DBG] [6] Jellyfin.Networking.Manager.NetworkManager: 192.168.0.104/32: GetBindInterface: Has found matching interface. 192.168.0.104
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [6] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[11:51:08] [DBG] [6] Jellyfin.Networking.Manager.NetworkManager: 192.168.0.104/32: GetBindInterface: Has found matching interface. 192.168.0.104
[11:51:08] [DBG] [98] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [98] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [45] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.0.104 request
[11:51:08] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [60] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:08] [DBG] [60] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [45] Emby.Server.Implementations.Session.SessionManager: Creating new WebSocketController
[11:51:09] [DBG] [45] Emby.Server.Implementations.Session.WebSocketController: Adding websocket to session e936c3a126152533762745167e255c94
[11:51:09] [DBG] [45] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:51:09] [DBG] [60] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:51:09] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [60] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [60] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItemList query time (slow): 18.3662ms. Query: select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,ExternalServiceId,IsInMixedFolder,Tags,TrailerTypes,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,ShowId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND MediaType=@MediaTypes AND (TopParentId=@TopParentId) Group by PresentationUniqueKey ORDER BY DateCreated DESC LIMIT 80
[11:51:09] [DBG] [60] Emby.Server.Implementations.Data.SqliteItemRepository: GetItemList query time (slow): 24.0533ms. Query: select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where type=@type AND TopParentId in ('8679d10569ec12981200c4116da3e90b','2a0548c209bcf2be01c33d1ce4afdc6b') Group by SeriesPresentationUniqueKey ORDER BY MAX(LastPlayedDate) DESC
[11:51:09] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:09] [DBG] [6] Emby.Server.Implementations.Data.SqliteItemRepository: GetItemList query time (slow): 15.9214ms. Query: select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,ExternalServiceId,IsInMixedFolder,Tags,TrailerTypes,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,ShowId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND MediaType=@MediaTypes AND (TopParentId=@TopParentId) Group by PresentationUniqueKey ORDER BY DateCreated DESC LIMIT 80
[11:51:10] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:10] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:10] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:10] [DBG] [87] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:10] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 157.5778ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:10] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 22.5891ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:14] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:14] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:15] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 4694.7348ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:15] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 120.4066ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:15] [DBG] [87] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 39.0738ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:15] [WRN] [87] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://www.jianglei.cool:8096/Users/fdb49e38f67d4a538c63127be963aefa/Items?Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=a42e37beb1c1ee76ebd0540bd666f4cf&SortBy=IsFolder%2CSortName&SortOrder=Ascending to 192.168.0.104 in 0:00:05.0504117 with Status Code 200
[11:51:21] [DBG] [21] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:51:28] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:28] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:28] [DBG] [96] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:28] [DBG] [96] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[11:51:29] [DBG] [96] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 159.6457ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:29] [DBG] [96] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 21.4258ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:33] [DBG] [6] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:51:33] [DBG] [96] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 4683.2209ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:33] [DBG] [96] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 120.3699ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:33] [DBG] [96] Emby.Server.Implementations.Data.SqliteItemRepository: GetItems query time (slow): 39.1181ms. Query:  select count (distinct PresentationUniqueKey),UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where IsFolder=@IsFolder AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND Guid in (select itemId from AncestorIds where AncestorId=@AncestorId)
[11:51:33] [WRN] [96] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://www.jianglei.cool:8096/Users/fdb49e38f67d4a538c63127be963aefa/Items?Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=a42e37beb1c1ee76ebd0540bd666f4cf&SortBy=IsFolder%2CSortName&SortOrder=Ascending to 192.168.0.104 in 0:00:05.0395579 with Status Code 200
[11:51:40] [DBG] [21] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:51:45] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:51:57] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:52:09] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:52:10] [DBG] [87] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:52:21] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:52:33] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:52:40] [DBG] [87] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:52:45] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:52:57] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:53:09] [DBG] [5] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:53:10] [DBG] [22] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 received message: {"MessageType": "KeepAlive", "MessageId": "00000000-0000-0000-0000-000000000000", "ServerId": null, "Data": null, "$type": "WebSocketMessage`1"}
[11:53:21] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:53:33] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[11:53:40] [WRN] [87] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.0.104 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:53:40] [DBG] [87] Emby.Server.Implementations.Session.WebSocketController: Removing websocket from session e936c3a126152533762745167e255c94
[11:53:40] [DBG] [87] Emby.Server.Implementations.Session.SessionManager: Disposing session controller WebSocketController
[11:53:40] [DBG] [87] Emby.Server.Implementations.Session.SessionWebSocketListener: WebSocket Emby.Server.Implementations.HttpServer.WebSocketConnection is closed.
[11:53:40] [INF] [87] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.0.104 closed
[11:53:45] [DBG] [8] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 0 WebSockets.
```

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: 
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by licamla** [comment]
I import a lot of items into a library. this make scanning library take very long time. sql take too much time when jellyfin scanning library.
the library.db be stored in HHD. i find  that IO is busy when scanning library. i guess sqlite locked the  library.db  file when it updating data.
so i modify `Emby.Server.Implementations/Data/BaseSqliteRepository.cs`  file with
```
protected virtual SynchronousMode? Synchronous => 0;
```
and rebuild jellyfin.
make sqlite using asynchronous mode.
it can work well if you don't care about the very small probability of library data corruption.now the size of library.db is 809M. jellyfin finish scanning library for new items within a short time  and i can normal watch video when jellyfin scanning library.
jellyfin might consider making `Synchronous => 0` as default or configuration option.

**Comment by brettpetch** [comment]
I recently had similar issues with sqlite db not keeping up. Have done the following to help the db live in memory a little more. 

Overall performance went from 30s search to about 4s on a RAID-0 NVMe config. 

```
sqlite3 library.db

PRAGMA main.page_size = 4096;
PRAGMA main.cache_size=10000;
PRAGMA main.locking_mode=EXCLUSIVE;
PRAGMA main.synchronous=NORMAL;
PRAGMA main.journal_mode=WAL;
PRAGMA main.cache_size=5000;
PRAGMA main.temp_store = MEMORY;
.quit
```
