### ISSUE TITLE
[Issue]: Unable to delete files

### ISSUE THREAD

**Issue by nburns** [jellyfin/jellyfin#7270]
### Please describe your bug

When I try an delete a file via the API I get an error `System.UnauthorizedAccessException: Access to the path` in the logs, and an error from curl, see repro below.

I'd expect the file to be deleted, and have been able to login to my linux box with the `su jellyfin` and delete files, so I'm wondering why the webserver can't delete these files.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization: None?
- Clients: REST API
- Browser: None
- FFmpeg Version: ffmpeg version 4.4-6ubuntu5
- Playback Method: NA
- Hardware Acceleration: AMD AMF
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: LAN
- Storage: local
```

### Jellyfin logs

```shell
[2022-02-03 18:19:01.007 -08:00] [INF] Removing item, Type: "Movie", Name: "Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'Hara)", Path: "/mnt/media/youtube/Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'Hara).mkv", Id: fc7cd480-762d-3a62-dde9-8e4e140e78b5
[2022-02-03 18:19:01.008 -08:00] [INF] Deleting item path, Type: "Movie", Name: "Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'Hara)", Path: "/mnt/media/youtube/Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'Hara).mkv", Id: fc7cd480-762d-3a62-dde9-8e4e140e78b5
[2022-02-03 18:19:01.009 -08:00] [ERR] Error processing request. URL "DELETE" "/Items/fc7cd480762d3a62dde98e4e140e78b5".
System.UnauthorizedAccessException: Access to the path '/mnt/media/youtube/Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'Hara).mkv' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, BaseItem parent, Boolean notifyParentItem)
   at Emby.Server.Implementations.Library.LibraryManager.DeleteItem(BaseItem item, DeleteOptions options, Boolean notifyParentItem)
   at Jellyfin.Api.Controllers.LibraryController.DeleteItem(Guid itemId)
   at lambda_method839(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any browser or client logs here

Repro in curl:
```
> curl -v -X DELETE -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 0' -H 'User-Agent: python-requests/2.26.0' -H 'X-Emby-Authorization: Mediabrowser Token=f35dcf8e1b9b47fdaa056eac3a57bef8' http://nas.local:8096/Items/fc7cd480762d3a62dde98e4e140e78b5
*   Trying fe80::b63a:5808:c0b3:3106:8096...
* connect to fe80::b63a:5808:c0b3:3106 port 8096 failed: Connection refused
*   Trying 192.168.2.172:8096...
* Connected to nas.local (192.168.2.172) port 8096 (#0)
> DELETE /Items/fc7cd480762d3a62dde98e4e140e78b5 HTTP/1.1
> Host: nas.local:8096
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Content-Length: 0
> User-Agent: python-requests/2.26.0
> X-Emby-Authorization: Mediabrowser Token=f35dcf8e1b9b47fdaa056eac3a57bef8
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 04 Feb 2022 02:23:13 GMT
< Content-Type: text/plain
< Server: Kestrel
< Transfer-Encoding: chunked
< X-Response-Time-ms: 2
<
* Connection #0 to host nas.local left intact
Error processing request.⏎
```

jellyfin groups:
```
> groups jellyfin
jellyfin : jellyfin media
```

```
> ll /mnt/media
drwxrwsr-x  2 nick media  16K Feb  3 18:14  youtube/
```

```
> ll /mnt/media/youtube/
total 23G
-rw-rwsr-- 1 nick media  407M Feb  2 01:26 'Drachinifel-Operation Torch - Invading France in Africa to beat Germany (with Vince O'\''Hara).mkv'*
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nburns** [comment]
changed the perms on /mnt/media/youtube to `drwxrwsrwx` and its all fine now
