### ISSUE TITLE
[Issue]: DLNA Logs even though DLNA is disabled?

### ISSUE THREAD

**Issue by SlothCroissant** [jellyfin/jellyfin#7279]
### Please describe your bug

I run JellyFin in Docker Swarm mode via this compose file (see attached environment details for compose.yml).

I've got all the DLNA options disabled in JellyFin, yet it is still attempting very often to reach my network broadcast address on port 1900 with logs as such: `Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "10.0.0.128" to "239.255.255.250:1900"`

I'm not worried that it's being blocked as permission denied - this is what I'd expect as my docker container does not have broadcast ability. I'm more concerned that DLNA is still trying to do its thing even though I've got it completely disabled.

Is there a way to fully remove DLNA? Is it a plugin, etc that can be killed? I personally have no use for it so would prefer it to just be gone if possible. Else I'd love if the service would see that I have it disabled in settings and not keep trying :)

### Jellyfin Version

10.7.7

### Environment

```markdown
yaml
version: "3.8"

services:
  app:
    image: linuxserver/jellyfin
    ports:
      - 8096:8096
    volumes:
      - /mnt/zfs/docker/jellyfin:/config
      - /tmp:/transcode
      - /mnt/user/NAS/:/nas
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    deploy:
      mode: global
      placement:
        constraints: [node.hostname == docker02.lan]
    networks:
      - jellyfin_network

networks:
  jellyfin_network:
    driver: overlay
    attachable: true
```
```


### Jellyfin logs

```shell
[2022-02-06 10:47:20.491 -06:00] [ERR] [5] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "10.0.0.128" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2022-02-06 10:47:20.591 -06:00] [ERR] [67] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "10.0.0.128" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[2022-02-06 10:47:20.939 -06:00] [ERR] [17] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "10.0.0.128" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

### Please attach any screenshots here

<img width="868" alt="Screen Shot 2022-02-06 at 10 53 27" src="https://user-images.githubusercontent.com/5846854/152691758-449f5162-070b-4c40-8c2a-01442f4102ff.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Virtlink** [comment]
I also have the same problem, with Jellyfin running as a container in Docker Swarm, with DLNA disabled, getting the same stack trace:
```
[2022-06-29 06:59:26.535 +00:00] [ERR] [57] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from "172.16.0.119" to "239.255.255.250:1900"
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendToAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 bytes, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendMessageIfSocketNotDisposed(Byte[] messageData, IPEndPoint destination, IPAddress fromLocalIpAddress, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendMulticastMessage(String message, Int32 sendCount, IPAddress fromLocalIpAddress, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at Emby.Server.Implementations.Net.UdpSocket.<>c__DisplayClass21_0.<SendToAsync>b__0(IAsyncResult callbackResult)
--- End of stack trace from previous location ---
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

**Comment by andreclemente** [comment]
Same here

**Comment by MetaBliss** [comment]
same here

**Comment by linkarzu** [comment]
I have the same issue trying to run jellyfin in a docker swarm, were you guys able to do it?

**Comment by Shadowghost** [comment]
Port `1900` is the autodiscovery port. Autodiscovery is handled by the DLNA subsystem. Disable autodiscovery and you won*t get the errors.

**Comment by linkarzu** [comment]
@Shadowghost , how do you disable autodiscovery?

I'm not exposing port 1900 in my swarm stack file, I'm also running the container as root. The issue is that due to the error, the container doesn't even start in the swarm . When I run the container as a regular docker-compose file, without the node being in a swarm, it works just fine. Not sure if I need to run traefik in front of the container or what 🤷 

Here's my swarm stack file
```yaml
version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:20230807.8-unstable
    # user: 1000:8546
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1000M
      # placement:
      #   constraints: [node.labels.deploy == adguard]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

    ports:
      - "8096:8096/tcp"
    #  - "7359:7359/udp"
    #  - "1900:1900/udp"

    volumes:
      - '/mnt/mygluster/dockdata/jellyfin/config:/config'
      - '/mnt/mygluster/dockdata/jellyfin/cache:/cache'
      - '/mnt/mygluster/dockdata/samba/shared/not-backed-up/Movies:/movies'

```

&emsp;

And here's the error I get
```bash
[19:22:06] [ERR] [14] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 10.0.0.58 to 239.255.255.250:1900
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendToAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(Socket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(Socket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.<>c__DisplayClass33_0.<SendMessageIfSocketNotDisposed>b__1(Socket s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendMessageIfSocketNotDisposed(Byte[] messageData, IPEndPoint destination, IPAddress fromlocalIPAddress, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendMulticastMessage(String message, Int32 sendCount, IPAddress fromlocalIPAddress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Shadowghost** [comment]
I think it is not possible to change it in the UI and I don't know if it's possible via ENV, but you can disable it by setting `AutoDiscovery` to `false` in `network.xml` and restarting Jellyfin afterwards.

**Comment by linkarzu** [comment]
Thanks for the answer @Shadowghost , so the official jellyfin/jellyfin image never worked in docker swarm, I instead switched to the **linuxserver/jellyfin:10.8.10** and everything's working as expected in docker swarm.
