### ISSUE TITLE
[Issue]: unstable - Some plugins won't load (Status: NotSupported)

### ISSUE THREAD

**Issue by nputman** [jellyfin/jellyfin#7351]
### Please describe your bug

After update (20220221.10), some plugins suddenly state "NotSupported". Logs say:

Method 'ExecuteAsync' in type 'Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask' from assembly 'Jellyfin.Plugin.TMDbBoxSets, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Please advise.
Thanks!!

### Jellyfin Version

Other

### if other:

20220221.10-unstable

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Virtualization: Proxmox (LXC)
```

### Jellyfin logs

```shell
Feb 22 18:13:38 jellyfin systemd[1]: Started Jellyfin Media Server.
Feb 22 18:13:39 jellyfin jellyfin[8929]: [18:13:39] [ERR] Failed to load assembly /var/lib/jellyfin/plugins/Kodi Sync Queue_7.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
Feb 22 18:13:39 jellyfin jellyfin[8929]: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Feb 22 18:13:39 jellyfin jellyfin[8929]: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask' from assembly 'Jellyfin.Plugin.KodiSyncQueue, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at System.Reflection.Assembly.GetTypes()
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
Feb 22 18:13:39 jellyfin jellyfin[8929]: System.TypeLoadException: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask' from assembly 'Jellyfin.Plugin.KodiSyncQueue, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Feb 22 18:13:39 jellyfin jellyfin[8929]: [18:13:39] [ERR] Failed to load assembly /var/lib/jellyfin/plugins/TMDb Box Sets_9.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
Feb 22 18:13:39 jellyfin jellyfin[8929]: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Feb 22 18:13:39 jellyfin jellyfin[8929]: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask' from assembly 'Jellyfin.Plugin.TMDbBoxSets, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at System.Reflection.Assembly.GetTypes()
Feb 22 18:13:39 jellyfin jellyfin[8929]:    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
Feb 22 18:13:39 jellyfin jellyfin[8929]: System.TypeLoadException: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask' from assembly 'Jellyfin.Plugin.TMDbBoxSets, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/8997460/155238527-032f11e9-180b-4261-9316-a110740309c2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Plugins don't target unstable. This will be fixed when the next Jellyfin version is released.

**Comment by SigHunter** [comment]
> Plugins don't target unstable. This will be fixed when the next Jellyfin version is released.

so running unstable generally does not guarantee plugins work and if the worked until now it was by luck?
