### ISSUE TITLE
[Issue]: Error in "ffprobe", out of bounds for an Int32

### ISSUE THREAD

**Issue by gm666q** [jellyfin/jellyfin#7355]
### Please describe your bug

Looks like ffprobe parser fails to parse 64 bit chapter ids. I attached the output of ffprobe when run manually.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Arch Linux
- FFmpeg Version: 5.0
- Storage: local
```

### Jellyfin logs

```shell
[2022-02-23 19:59:06.107 +00:00] [DBG] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-i file:\"/mnt/hdd/Multimedia/Movies/Harry Potter and the Prisoner of Azkaban (2004)/Harry Potter and the Prisoner of Azkaban (2004) - vp9.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-02-23 19:59:06.162 +00:00] [ERR] [28] MediaBrowser.Providers.Videos.VideoMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.chapters[0].id | LineNumber: 267 | BytePositionInLine: 36.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
{
    "streams": [
        {
            "index": 0,
            "codec_name": "vp9",
            "codec_long_name": "Google VP9",
            "profile": "Profile 0",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1920,
            "height": 798,
            "coded_width": 1920,
            "coded_height": 798,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "320:133",
            "pix_fmt": "yuv420p",
            "level": -99,
            "color_range": "tv",
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/1000",
            "start_pts": 42,
            "start_time": "0.042000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "ENCODER": "Lavc59.18.100 libvpx-vp9",
                "DURATION": "02:21:42.202000000"
            }
        },
        {
            "index": 1,
            "codec_name": "opus",
            "codec_long_name": "Opus (Opus Interactive Audio Codec)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 1989,
            "start_time": "1.989000",
            "extradata_size": 27,
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "Surround 5.1",
                "ENCODER": "Lavc59.18.100 libopus",
                "DURATION": "02:21:42.995000000"
            }
        },
        {
            "index": 2,
            "codec_name": "flac",
            "codec_long_name": "FLAC (Free Lossless Audio Codec)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "s16",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1(side)",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "16",
            "extradata_size": 34,
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "Surround 5.1",
                "ENCODER": "Lavc59.18.100 flac",
                "DURATION": "02:21:42.995000000"
            }
        },
        {
            "index": 3,
            "codec_name": "opus",
            "codec_long_name": "Opus (Opus Interactive Audio Codec)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 1989,
            "start_time": "1.989000",
            "extradata_size": 19,
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 1,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "Stereo",
                "ENCODER": "Lavc59.18.100 libopus",
                "DURATION": "02:21:43.155000000"
            }
        },
        {
            "index": 4,
            "codec_name": "webvtt",
            "codec_long_name": "WebVTT subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 8503155,
            "duration": "8503.155000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 1,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "DURATION": "02:21:40.950000000"
            }
        },
        {
            "index": 5,
            "codec_name": "webvtt",
            "codec_long_name": "WebVTT subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 8503155,
            "duration": "8503.155000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 1,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 1,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 1,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "DURATION": "02:21:40.950000000"
            }
        }
    ],
    "chapters": [
        {
            "id": 251446668167383985,
            "time_base": "1/1000000000",
            "start": 0,
            "start_time": "0.000000",
            "end": 99766333333,
            "end_time": "99.766333"
        },
        {
            "id": 2316244367912562658,
            "time_base": "1/1000000000",
            "start": 99766333333,
            "start_time": "99.766333",
            "end": 395978916666,
            "end_time": "395.978917"
        },
        {
            "id": 6476941639275423745,
            "time_base": "1/1000000000",
            "start": 395978916666,
            "start_time": "395.978917",
            "end": 765806708333,
            "end_time": "765.806708"
        },
        {
            "id": 4248475294161720032,
            "time_base": "1/1000000000",
            "start": 765806708333,
            "start_time": "765.806708",
            "end": 892308083333,
            "end_time": "892.308083"
        },
        {
            "id": -981443365853180271,
            "time_base": "1/1000000000",
            "start": 892308083333,
            "start_time": "892.308083",
            "end": 972304666666,
            "end_time": "972.304667"
        },
        {
            "id": 7506223206384137194,
            "time_base": "1/1000000000",
            "start": 972304666666,
            "start_time": "972.304667",
            "end": 1136135000000,
            "end_time": "1136.135000"
        },
        {
            "id": -667733797883897816,
            "time_base": "1/1000000000",
            "start": 1136135000000,
            "start_time": "1136.135000",
            "end": 1430178750000,
            "end_time": "1430.178750"
        },
        {
            "id": -8512915258081321997,
            "time_base": "1/1000000000",
            "start": 1430178750000,
            "start_time": "1430.178750",
            "end": 1730395333333,
            "end_time": "1730.395333"
        },
        {
            "id": 1347624914676985900,
            "time_base": "1/1000000000",
            "start": 1730395333333,
            "start_time": "1730.395333",
            "end": 1881671458333,
            "end_time": "1881.671458"
        },
        {
            "id": -1129884039428994179,
            "time_base": "1/1000000000",
            "start": 1881671458333,
            "start_time": "1881.671458",
            "end": 2329910916666,
            "end_time": "2329.910917"
        },
        {
            "id": -5033545088129683729,
            "time_base": "1/1000000000",
            "start": 2329910916666,
            "start_time": "2329.910917",
            "end": 2685641291666,
            "end_time": "2685.641292"
        },
        {
            "id": -6204589750953175909,
            "time_base": "1/1000000000",
            "start": 2685641291666,
            "start_time": "2685.641292",
            "end": 2857521333333,
            "end_time": "2857.521333"
        },
        {
            "id": -4471732985331576850,
            "time_base": "1/1000000000",
            "start": 2857521333333,
            "start_time": "2857.521333",
            "end": 2979685041666,
            "end_time": "2979.685042"
        },
        {
            "id": 3535018245773609989,
            "time_base": "1/1000000000",
            "start": 2979685041666,
            "start_time": "2979.685042",
            "end": 3223220000000,
            "end_time": "3223.220000"
        },
        {
            "id": 7046436400761097860,
            "time_base": "1/1000000000",
            "start": 3223220000000,
            "start_time": "3223.220000",
            "end": 3448153041666,
            "end_time": "3448.153042"
        },
        {
            "id": -2529659618959355109,
            "time_base": "1/1000000000",
            "start": 3448153041666,
            "start_time": "3448.153042",
            "end": 3683638291666,
            "end_time": "3683.638292"
        },
        {
            "id": 1445056499609586315,
            "time_base": "1/1000000000",
            "start": 3683638291666,
            "start_time": "3683.638292",
            "end": 3803591458333,
            "end_time": "3803.591458"
        },
        {
            "id": 3523354247933779847,
            "time_base": "1/1000000000",
            "start": 3803591458333,
            "start_time": "3803.591458",
            "end": 4030693333333,
            "end_time": "4030.693333"
        },
        {
            "id": -6455948278478626004,
            "time_base": "1/1000000000",
            "start": 4030693333333,
            "start_time": "4030.693333",
            "end": 4313350708333,
            "end_time": "4313.350708"
        },
        {
            "id": 5600731828236122979,
            "time_base": "1/1000000000",
            "start": 4313350708333,
            "start_time": "4313.350708",
            "end": 4749911833333,
            "end_time": "4749.911833"
        },
        {
            "id": -7266576591169734591,
            "time_base": "1/1000000000",
            "start": 4749911833333,
            "start_time": "4749.911833",
            "end": 4949819875000,
            "end_time": "4949.819875"
        },
        {
            "id": -4619914180121426518,
            "time_base": "1/1000000000",
            "start": 4949819875000,
            "start_time": "4949.819875",
            "end": 5249118875000,
            "end_time": "5249.118875"
        },
        {
            "id": -2561274996075747235,
            "time_base": "1/1000000000",
            "start": 5249118875000,
            "start_time": "5249.118875",
            "end": 5413157750000,
            "end_time": "5413.157750"
        },
        {
            "id": -391750554015531088,
            "time_base": "1/1000000000",
            "start": 5413157750000,
            "start_time": "5413.157750",
            "end": 5658861541666,
            "end_time": "5658.861542"
        },
        {
            "id": 3770518853281652791,
            "time_base": "1/1000000000",
            "start": 5658861541666,
            "start_time": "5658.861542",
            "end": 5816602458333,
            "end_time": "5816.602458"
        },
        {
            "id": 1509634435380771955,
            "time_base": "1/1000000000",
            "start": 5816602458333,
            "start_time": "5816.602458",
            "end": 6144304833333,
            "end_time": "6144.304833"
        },
        {
            "id": -8585097199533014765,
            "time_base": "1/1000000000",
            "start": 6144304833333,
            "start_time": "6144.304833",
            "end": 6340250583333,
            "end_time": "6340.250583"
        },
        {
            "id": 4433450186006798168,
            "time_base": "1/1000000000",
            "start": 6340250583333,
            "start_time": "6340.250583",
            "end": 6603513583333,
            "end_time": "6603.513583"
        },
        {
            "id": 6285028340723708041,
            "time_base": "1/1000000000",
            "start": 6603513583333,
            "start_time": "6603.513583",
            "end": 6933176250000,
            "end_time": "6933.176250"
        },
        {
            "id": 7530228834927499722,
            "time_base": "1/1000000000",
            "start": 6933176250000,
            "start_time": "6933.176250",
            "end": 7207283416666,
            "end_time": "7207.283417"
        },
        {
            "id": 3358141405480088103,
            "time_base": "1/1000000000",
            "start": 7207283416666,
            "start_time": "7207.283417",
            "end": 7395846791666,
            "end_time": "7395.846792"
        },
        {
            "id": 2464203447154712382,
            "time_base": "1/1000000000",
            "start": 7395846791666,
            "start_time": "7395.846792",
            "end": 7562388166666,
            "end_time": "7562.388167"
        },
        {
            "id": -4095904904934283184,
            "time_base": "1/1000000000",
            "start": 7562388166666,
            "start_time": "7562.388167",
            "end": 7722798416666,
            "end_time": "7722.798417"
        },
        {
            "id": -3385025169343424481,
            "time_base": "1/1000000000",
            "start": 7722798416666,
            "start_time": "7722.798417",
            "end": 7787029250000,
            "end_time": "7787.029250"
        },
        {
            "id": -585786957992786398,
            "time_base": "1/1000000000",
            "start": 7787029250000,
            "start_time": "7787.029250",
            "end": 8503154000000,
            "end_time": "8503.154000"
        }
    ],
    "format": {
        "filename": "file:/mnt/hdd/Multimedia/Movies/Harry Potter and the Prisoner of Azkaban (2004)/Harry Potter and the Prisoner of Azkaban (2004) - vp9.mkv",
        "nb_streams": 6,
        "nb_programs": 0,
        "format_name": "matroska,webm",
        "format_long_name": "Matroska / WebM",
        "start_time": "0.000000",
        "duration": "8503.155000",
        "size": "3765768481",
        "bit_rate": "3542937",
        "probe_score": 100,
        "tags": {
            "title": "Harry Potter and the Prisoner of Azkaban",
            "ENCODER": "Lavf59.16.100"
        }
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hugotrsd** [comment]
I have the same issue. The change comes from ffmpeg v5.0, where they fixed a bunch of integer overflow bugs. Integers are now unsigned 64 bits ones.
As a workaround, downgrading ffmpeg to v4.4 fixes the issue.

**Comment by Shadowghost** [comment]
I looked into the matroska spec because of this error and it's a bit weirdly specified.
The [IETF Draft](https://tools.ietf.org/id/draft-lhomme-cellar-matroska-04.html) specifies `uinteger` for `ChapterUID` while the [matroska element spec](https://www.matroska.org/technical/elements.html) just says that is must be `not 0`.

I suppose FFmpeg assumend that it would be an integer but if you check your files with mediainfo or mkvtoolnix you'd see that the `ChapterUID` would be a number greater than the maximum of an unisgned integer. In the ffmpeg output the negative chapter ids suggest an integer overflow on the internal handling of that attribute in ffmpeg.

**Comment by gm666q** [comment]
I mean the file was crated with the same version of ffmpeg so it's entirely possible that there is a flaw with ffmpeg implementation.

**Comment by 1337joe** [comment]
I didn't chase it into the upstream to see why ffmpeg is producing values out of int range, but since the only problem we're having is parsing ffmpeg output and we don't ever use/store the chapter id in Jellyfin it's a simple change to handle it (linked pull request) and low impact to revert later if it starts producing ints again.
