### ISSUE TITLE
Under/overflow when browsing photos makes web interface non-functional

### ISSUE THREAD

**Issue by lbeltrame** [jellyfin/jellyfin#741]
**Describe the bug**
This happens with the latest state of git master. After trying to browse my photo collection, an error was logged (overflow or underflow; see below for the log) and then, the following error appeared in the browser, on first reload:

```
Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
```

After that, there's no way to access the server anymore, not even with restarts. See the excerpt of the logs further below. The error seems to be triggered by another error when processing the thumbnails of one of my photo media galleries (see below as well):

**Logs**

The original error when browsing the photo gallery, which occurs at the time of extracting image sizes:

```
gen 27 19:11:24 palver.lan dotnet[23375]: [19:11:24] [ERR] Error processing request
gen 27 19:11:24 palver.lan dotnet[23375]: System.OverflowException: Value was either too large or too small for an Int32.
gen 27 19:11:24 palver.lan dotnet[23375]:    at System.Convert.ToInt32(Double value)
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Controller.Drawing.ImageHelper.GetSizeEstimate(ImageProcessingOptions options) in /home/emby/jellyfin/MediaBrowser.Controller/Drawing/ImageHelper.cs:line 38
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Controller.Drawing.ImageHelper.GetNewImageSize(ImageProcessingOptions options, Nullable`1 originalImageSize) in /home/emby/jellyfin/MediaBrowser.Controller/Drawing/ImageHelper.cs:line 19
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options) in /home/emby/jellyfin/Emby.Drawing/ImageProcessor.cs:line 233
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest) in /home/emby/jellyfin/MediaBrowser.Api/Images/ImageService.cs:line 639
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 112
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
gen 27 19:11:24 palver.lan dotnet[23375]: [19:11:24] [INF] HTTP Response 500 to REDACTED. Time: 101ms. http://REDACTED:8096/emby/Items/3c337a14bc987275566ead39377b399f/Images/Primary?maxHeight=317&maxWidth=317&tag=c7f3004a26ba76bc70ec2313d2effe0b&quality=90
```

Subsequent attempts to load the service, no matter which address, result in this then:

```
gen 27 19:03:55 palver.lan dotnet[23375]: [19:03:55] [ERR] Error processing request
gen 27 19:03:55 palver.lan dotnet[23375]: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid..ctor(String g)
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetStaticResult(IRequest requestContext, StaticResultOptions options) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 538
gen 27 19:03:55 palver.lan dotnet[23375]:    at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request) in /home/emby/jellyfin/MediaBrowser.WebDashboard/Api/DashboardService.cs:line 353
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 112
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
gen 27 19:03:58 palver.lan dotnet[23375]: [19:03:58] [INF] HTTP GET http://REDACTED:8096/dlna/9d59fec0f5b14ca6b0d88bbc120af30b/description.xml. UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
gen 27 19:03:58 palver.lan dotnet[23375]: [19:03:58] [INF] HTTP Response 200 to REDACTED. Time: 82ms. http://REDACTED:8096/dlna/9d59fec0f5b14ca6b0d88bbc120af30b/description.xml
```

*

**System (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser: Firefox
 - Jellyfin Version: latest master

**Comment by lbeltrame** [comment]
I suspect https://github.com/jellyfin/jellyfin/pull/721, but I'm unable to test (can't do a simple revert, too many things have changed).

**Comment by Bond-009** [comment]
#727
Should have fixed the first error afaik.

**Comment by lbeltrame** [comment]
I wiped clean everything, I'll check in a few if it works now.

**Comment by lbeltrame** [comment]
It doesn't. I added my photos folder and immediately the second error (the one referring to Guid) appeared.

**Comment by lbeltrame** [comment]
I'll wipe again tonight and see if I can find a minimal test case to reproduce this.

**Comment by lbeltrame** [comment]
As stated in #757 cleaning the cache has fixed it after applying that PR. I could still dig back in the log and try to find the request if need be.

**Comment by lbeltrame** [comment]
I broke it again this trying trying to add (for fun) a m3u live stream:

```
gen 29 07:39:56 palver.lan dotnet[31360]: [07:39:56] [INF] HTTP GET http://INSTANCENAME:8096/web/favicon.ico. UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0                                       
gen 29 07:39:56 palver.lan dotnet[31360]: [07:39:56] [INF] HTTP Response 200 to XXXXX. Time: 62ms. http://jellyfin.internal.heavensinferno.net:8096/web/favicon.ico                                                                                     
gen 29 07:39:56 palver.lan dotnet[31360]: [07:39:56] [ERR] Error processing request                                                                                                                                                                         
gen 29 07:39:56 palver.lan dotnet[31360]: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).                                                                                                        
gen 29 07:39:56 palver.lan dotnet[31360]:    at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)

**Comment by cvium** [comment]
I still can't reproduce it. Can you give me the header of the request? You can find it in the Network tab in your browser's developer tools.

**Comment by lbeltrame** [comment]
It looks it has to do with caching. Accessing it from a different machine is fine unless I "trigger" it, then it occurs every time.

Typical header of the request:

```
Host: HOSTNAME
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: it
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Upgrade-Insecure-Requests: 1
If-None-Match: W/2a88870098c431cdafc902a166730932
Cache-Control: max-age=0
TE: Trailers
```
Note that this error is hit in different paths depending on the time I reload.

![screenshot_20190129_090359](https://user-images.githubusercontent.com/25192/51893326-d532dd80-23a4-11e9-9e38-e41e862f5b37.png)

![screenshot_20190129_090324](https://user-images.githubusercontent.com/25192/51893292-c0564a00-23a4-11e9-8579-d636166b398d.png)

**Comment by lbeltrame** [comment]
That's interesting. It only occurs *if it's reverse proxied*, it seems (I disabled external connections so I checked on the machine remotely).

**Comment by cvium** [comment]
It's the `W/`. I'll fix it when I have time.

**Comment by lbeltrame** [comment]
I was able to workaround this by tweaking a bit the reverse proxy and reloading individually all the components that were giving 500s.

**Comment by lbeltrame** [comment]
@cvium Safe enough to strip the `W/` from the header? So I can workaround it for the moment.

**Comment by cvium** [comment]
Yes. It's just a flag for the server to use the weak algorithm for ETags, but we only have one.
