### ISSUE TITLE
[Issue]: NullReferenceException when trying to access through Unix socket

### ISSUE THREAD

**Issue by LinAGKar** [jellyfin/jellyfin#7414]
### Please describe your bug

I'm trying to set up nginx as a reverse proxy in front of Jellyfin, through a Unix socket, which I've enabled with JELLYFIN_kestrel__socket=true and JELLYFIN_kestrel__socketPath=/jellyfin-sock/jellyfin.sock. It works fine when I access Jellyfin directly through TCP port 8096 (not through the reverse proxy), and I can load the page itself (HTML, Javascript, CSS, etc) through the reverse proxy. However, when it tries to load /System/Info/Public through the reverse proxy I get an error 500.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: openSUSE Leap 15.3
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox 97
- Hardware Acceleration: none
- Plugins: AudioDB 10.7.7.0, MusicBrainz 10.7.7.0, OMDb 10.7.7.0
- Reverse Proxy: Nginx
- Base URL: none
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[09:57:19] [ERR] [244] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Info/Public.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Common.Extensions.HttpContextExtensions.IsLocal(HttpContext context)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any screenshots here

![Screenshot_20220306_202218](https://user-images.githubusercontent.com/3390621/156939263-b4efc04b-6daf-47f9-9cc0-deeb144d7a23.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LinAGKar** [comment]
Looks like this is the issue discussed in #5757. It seems to work better in 10.8.0-alpha5
