### ISSUE TITLE
ffprobe of strm files fails on playback

### ISSUE THREAD

**Issue by whiteowl3** [jellyfin/jellyfin#7438]
running ```"/usr/lib/jellyfin-ffmpeg/ffprobe -i http://localhost:8080/ipfs/QmVZskJx8iFUhWKFCksQtaQeRCUqnCMgPdDuCvFbCwM15T\ -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"``` 
from the jellyfin container (lsio/nightly) returns the json response as expected, but the server can't seem to pull it off
```[2022-03-10 01:20:08.232 +00:00] [DBG] [71] MediaBrowser.Providers.Movies.MovieMetadataService: Running "FFProbeProvider" for "/mnt/share/Movies/C/Crouching Tiger, Hidden Dragon (2000)/Crouching Tiger, Hidden Dragon (2000) SDTV.strm"
[2022-03-10 01:20:08.232 +00:00] [INF] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-i \"http://localhost:8080/ipfs/QmVZskJx8iFUhWKFCksQtaQeRCUqnCMgPdDuCvFbCwM15T\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-03-10 01:20:08.232 +00:00] [DBG] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-i \"http://localhost:8080/ipfs/QmVZskJx8iFUhWKFCksQtaQeRCUqnCMgPdDuCvFbCwM15T\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-03-10 01:20:08.364 +00:00] [DBG] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-i file:\"/mnt/share/Movies/C/Crouching Tiger, Hidden Dragon (2000)/Crouching Tiger, Hidden Dragon (2000) SDTV.es.srt\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2022-03-10 01:20:08.364 +00:00] [DBG] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-i file:\"/mnt/share/Movies/C/Crouching Tiger, Hidden Dragon (2000)/Crouching Tiger, Hidden Dragon (2000) SDTV.es.srt\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2022-03-10 01:20:08.402 +00:00] [DBG] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-i file:\"/mnt/share/Movies/C/Crouching Tiger, Hidden Dragon (2000)/Crouching Tiger, Hidden Dragon (2000) SDTV.strm\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2022-03-10 01:20:08.402 +00:00] [DBG] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-i file:\"/mnt/share/Movies/C/Crouching Tiger, Hidden Dragon (2000)/Crouching Tiger, Hidden Dragon (2000) SDTV.strm\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2022-03-10 01:20:08.433 +00:00] [ERR] [71] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalAudioAsync(Video video, List`1 currentStreams, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.Fetch(Video video, CancellationToken cancellationToken, MediaInfo mediaInfo, BlurayDiscInfo blurayInfo, MetadataRefreshOptions options)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Comment by whiteowl3** [comment]
so after rigging the mediaencoder to dump the ffprobe process, it is clear that ffprobe actually is returning valid data:
```[2022-03-10 20:18:33.553 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-i \"http://localhost:8080/ipfs/QmVZskJx8iFUhWKFCksQtaQeRCUqnCMgPdDuCvFbCwM15T\" -threads 0 -v fatal -print_format json -show_streams -show_chapters -show_format"
[2022-03-10 20:18:33.671 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "{"
[2022-03-10 20:18:33.672 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "    \"streams\": ["
[2022-03-10 20:18:33.672 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "        {"
[2022-03-10 20:18:33.672 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"index\": 0,"
[2022-03-10 20:18:33.672 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_name\": \"h264\","
[2022-03-10 20:18:33.673 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\","
[2022-03-10 20:18:33.673 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"profile\": \"High\","
[2022-03-10 20:18:33.673 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_type\": \"video\","
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag_string\": \"[0][0][0][0]\","
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag\": \"0x0000\","
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"width\": 1920,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"height\": 800,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"coded_width\": 1920,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"coded_height\": 800,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"closed_captions\": 0,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"has_b_frames\": 2,"
[2022-03-10 20:18:33.674 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"sample_aspect_ratio\": \"1:1\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"display_aspect_ratio\": \"12:5\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"pix_fmt\": \"yuv420p\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"level\": 40,"
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"chroma_location\": \"left\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"field_order\": \"progressive\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"refs\": 1,"
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"is_avc\": \"false\","
[2022-03-10 20:18:33.675 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"nal_length_size\": \"0\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"r_frame_rate\": \"24000/1001\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"avg_frame_rate\": \"24000/1001\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"time_base\": \"1/1000\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_pts\": 0,"
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_time\": \"0.000000\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"bits_per_raw_sample\": \"8\","
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"disposition\": {"
[2022-03-10 20:18:33.676 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"default\": 1,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"dub\": 0,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"original\": 0,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"comment\": 0,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"lyrics\": 0,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"karaoke\": 0,"
[2022-03-10 20:18:33.677 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"forced\": 0,"
[2022-03-10 20:18:33.678 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"hearing_impaired\": 0,"
[2022-03-10 20:18:33.678 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"visual_impaired\": 0,"
[2022-03-10 20:18:33.678 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"clean_effects\": 0,"
[2022-03-10 20:18:33.678 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"attached_pic\": 0,"
[2022-03-10 20:18:33.679 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"timed_thumbnails\": 0"
[2022-03-10 20:18:33.679 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            },"
[2022-03-10 20:18:33.679 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"tags\": {"
[2022-03-10 20:18:33.680 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"language\": \"eng\","
[2022-03-10 20:18:33.680 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"title\": \"Crouching Tiger,  Hidden Dragon\""
[2022-03-10 20:18:33.680 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            }"
[2022-03-10 20:18:33.683 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "        },"
[2022-03-10 20:18:33.683 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "        {"
[2022-03-10 20:18:33.683 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"index\": 1,"
[2022-03-10 20:18:33.683 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_name\": \"aac\","
[2022-03-10 20:18:33.683 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_long_name\": \"AAC (Advanced Audio Coding)\","
[2022-03-10 20:18:33.684 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"profile\": \"HE-AAC\","
[2022-03-10 20:18:33.684 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_type\": \"audio\","
[2022-03-10 20:18:33.684 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag_string\": \"[0][0][0][0]\","
[2022-03-10 20:18:33.684 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag\": \"0x0000\","
[2022-03-10 20:18:33.684 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"sample_fmt\": \"fltp\","
[2022-03-10 20:18:33.685 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"sample_rate\": \"48000\","
[2022-03-10 20:18:33.685 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"channels\": 6,"
[2022-03-10 20:18:33.685 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"channel_layout\": \"5.1\","
[2022-03-10 20:18:33.685 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"bits_per_sample\": 0,"
[2022-03-10 20:18:33.685 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"r_frame_rate\": \"0/0\","
[2022-03-10 20:18:33.686 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"avg_frame_rate\": \"0/0\","
[2022-03-10 20:18:33.686 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"time_base\": \"1/1000\","
[2022-03-10 20:18:33.686 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_pts\": 1000,"
[2022-03-10 20:18:33.686 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_time\": \"1.000000\","
[2022-03-10 20:18:33.686 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"disposition\": {"
[2022-03-10 20:18:33.687 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"default\": 1,"
[2022-03-10 20:18:33.687 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"dub\": 0,"
[2022-03-10 20:18:33.687 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"original\": 0,"
[2022-03-10 20:18:33.688 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"comment\": 0,"
[2022-03-10 20:18:33.688 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"lyrics\": 0,"
[2022-03-10 20:18:33.688 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"karaoke\": 0,"
[2022-03-10 20:18:33.688 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"forced\": 0,"
[2022-03-10 20:18:33.689 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"hearing_impaired\": 0,"
[2022-03-10 20:18:33.689 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"visual_impaired\": 0,"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"clean_effects\": 0,"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"attached_pic\": 0,"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"timed_thumbnails\": 0"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            },"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"tags\": {"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"language\": \"eng\","
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "                \"title\": \"Crouching Tiger,  Hidden Dragon\""
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            }"
[2022-03-10 20:18:33.690 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "        },"
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "        {"
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"index\": 2,"
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_name\": \"aac\","
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_long_name\": \"AAC (Advanced Audio Coding)\","
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"profile\": \"HE-AAC\","
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_type\": \"audio\","
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag_string\": \"[0][0][0][0]\","
[2022-03-10 20:18:33.691 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"codec_tag\": \"0x0000\","
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"sample_fmt\": \"fltp\","
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"sample_rate\": \"48000\","
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"channels\": 6,"
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"channel_layout\": \"5.1\","
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"bits_per_sample\": 0,"
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"r_frame_rate\": \"0/0\","
[2022-03-10 20:18:33.692 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"avg_frame_rate\": \"0/0\","
[2022-03-10 20:18:33.693 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"time_base\": \"1/1000\","
[2022-03-10 20:18:33.693 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_pts\": 1000,"
[2022-03-10 20:18:33.693 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"start_time\": \"1.000000\","
[2022-03-10 20:18:33.693 +00:00] [DBG] [14] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "            \"disposition\": {"
[2022-03-10 20:18:33.699 +00:00] [ERR] [14] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"```
