### ISSUE TITLE
[Issue]: Startup Loop - System.FormatException: Dashes are in the wrong position for GUID parsing.

### ISSUE THREAD

**Issue by akolomitz** [jellyfin/jellyfin#7442]
### Please describe your bug

I have had this instance of Jellyfin on a Rocky Linux KVM VM for roughly 8 months with no issues. I only turn my server on a few times per week. Turned it on last week and shut it down the same night with no changes/updates/etc. I powered it on tonight and the jellyfin systemd service starts for about 3-5 seconds, crashes, and then restarts infinitely without ever reaching a full startup.

The main error appears to be "System.FormatException: Dashes are in the wrong position for GUID parsing." However, I cannot seem to find much information about that anywhere. Any help would be appreciated, as I am truly at a loss considering there is nothing that should have changed to my knowledge. I have posted debug logs below.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Rocky Linux 8.5
- Virtualization: KVM/Libvirt/QEMU
- Clients: Browser, Android
- Browser: Chrome
- FFmpeg Version: 4.2.5
- Playback Method: Direct PLay
- Hardware Acceleration: None
- Plugins: Fanart 6, Fanart 7
- Reverse Proxy: nginx
- Base URL: None
- Storage: Local
```

### Jellyfin logs

```shell
[INF] [1] Main: Jellyfin version: 10.7.7
[INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/libexec/jellyfin/restart.sh]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin-web]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]"]
[19:27:57] [INF] [1] Main: Arguments: ["/usr/lib64/jellyfin/jellyfin.dll", "--webdir=/usr/share/jellyfin-web", "--restartpath=/usr/libexec/jellyfin/restart.sh"]
[INF] [1] Main: Operating system: Linux
[INF] [1] Main: Architecture: X64
[INF] [1] Main: 64-Bit Process: True
[INF] [1] Main: User Interactive: True
[INF] [1] Main: Processor count: 2
[INF] [1] Main: Program data path: /var/lib/jellyfin
[INF] [1] Main: Web resources path: /usr/share/jellyfin-web
[INF] [1] Main: Application directory: /usr/lib64/jellyfin/
[INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /var/cache/jellyfin
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Refreshing interfaces.
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Discovered 1 interfaces.
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Interfaces addresses : [192.168.2.8/24]
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Refreshing LAN information.
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN interface addresses as user provided no LAN details.
[INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[DBG] [1] Jellyfin.Networking.Manager.NetworkManager: Invalid or unknown object vEthernet*.
[INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Fanart_7.0.0.0/Jellyfin.Plugin.Fanart.dll
[DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider
[DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider
[DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Jellyfin.Server.Implementations.Users.InvalidAuthProvider
[FTL] [1] Main: Error while starting server.
System.FormatException: Dashes are in the wrong position for GUID parsing.
at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
at System.Guid..ctor(String g)
at Microsoft.Data.Sqlite.SqliteValueReader.GetGuid(Int32 ordinal)
at Microsoft.Data.Sqlite.SqliteDataReader.GetGuid(Int32 ordinal)
at lambda_method28(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|60_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass60_0`2& )
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
at lambda_method41(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
at Emby.Server.Implementations.ApplicationHost.InitializeServices()
at Jellyfin.Server.Program.StartApp(StartupOptions options)
[INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akolomitz** [comment]
Since all the clues were pointing towards database corruption, I dumped jellyfin.db and library.db to new files and everything started up just fine. No data loss as far as I can tell either. And now I have a cron job that will make regular backups of these files. Sorry for potentially wasting anyone's time, I'm all set!

**Comment by KodeToad** [comment]
> I dumped jellyfin.db and library.db to new files

What do you mean you dumped them to new files? How can that help?
This is similar to an issue I'm having upgrading.
