### ISSUE TITLE
[Issue]: roblem with URI

### ISSUE THREAD

**Issue by bibitocarlos** [jellyfin/jellyfin#7455]
### Please describe your bug

Hi,

With Alpha 5, i cant connect to my jellyfin server using the URI, just using the IP works, as shown in the log.

### Jellyfin Version

Other

### if other:

10.8.Alpha5

### Environment

```markdown
- OS:archlinux
- Virtualization:
- Clients:firefox
- Browser:firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
458552Mar 13 09:54:21 bibiserveur dotnet[581905]: [09:54:21] [INF] [20] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Middleware/ExceptionMiddleware.cs:line 55
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs:lin>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Middleware/LegacyEmbyRoute>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Middleware/RobotsRedirectionMid>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Middleware/QueryStringDecodin>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager) in /home/bibi/.>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Ser>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager) in /hom>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar 13 09:54:19 bibiserveur dotnet[581905]: --- End of stack trace from previous location ---
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean >
Mar 13 09:54:19 bibiserveur dotnet[581905]: --- End of stack trace from previous location ---
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Mar 13 09:54:19 bibiserveur dotnet[581905]: --- End of stack trace from previous location ---
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] >
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at lambda_method312(Closure , Object , Object[] )
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo() in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Api/Controllers/SystemController.cs:line 80
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Emby.Server.Implementations.ApplicationHost.GetPublicSystemInfo(HttpRequest request) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:li>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Emby.Server.Implementations.ApplicationHost.GetSmartApiUrl(HttpRequest request) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Emby.Server.Implementations/ApplicationHost.cs:line 10>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at Emby.Server.Implementations.ApplicationHost.GetLocalApiUrl(String hostname, String scheme, Nullable`1 port) in /home/bibi/.cache/yay/jellyfin-git/src/jellyfin/Emby.Server.Implementation>
Mar 13 09:54:19 bibiserveur dotnet[581905]:    at System.UriBuilder.set_Scheme(String value)
Mar 13 09:54:19 bibiserveur dotnet[581905]: System.ArgumentException: Invalid URI: The URI scheme is not valid. (Parameter 'value')
Mar 13 09:54:19 bibiserveur dotnet[581905]: [09:54:19] [ERR] [15] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /system/info/public.
Mar 13 09:54:19 bibiserveur dotnet[581905]: [09:54:19] [INF] [11] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Mar 13 09:54:19 bibiserveur dotnet[581905]: [09:54:19] [INF] [11] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
Mar 13 09:54:19 bibiserveur dotnet[581905]: [09:54:19] [INF] [11] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
How are you connecting to your Jellyfin instance? Any chance you're using a socket file?

**Comment by bibitocarlos** [comment]
No socket file.
Still happens with latest release.
nginx.conf
`
location /jellyfin/ {
        proxy_pass      http://192.168.1.11:8096/jellyfin/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Proto $remote_addr;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_buffering off;

        }
`

**Comment by bibitocarlos** [comment]
http://192.168.1.11:8096/jellyfin/ is accessible

**Comment by bibitocarlos** [comment]
Debug log in debug mode :+1: 
`
[08:00:34] [ERR] [32] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /system/info/public.
System.ArgumentException: Invalid URI: The URI scheme is not valid. (Parameter 'value')
   at System.UriBuilder.set_Scheme(String value)
   at Emby.Server.Implementations.ApplicationHost.GetLocalApiUrl(String hostname, String scheme, Nullable`1 port)
   at Emby.Server.Implementations.ApplicationHost.GetSmartApiUrl(HttpRequest request)
   at Emby.Server.Implementations.ApplicationHost.GetPublicSystemInfo(HttpRequest request)
   at Jellyfin.Api.Controllers.SystemController.GetPublicSystemInfo()
   at lambda_method312(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)`

**Comment by bibitocarlos** [comment]
It happen at the page of the server choice 
`Connection Failure
We're unable to connect to the selected server right now. Please ensure it is running and try again`

**Comment by bibitocarlos** [comment]
Still happens with the release :
'+1: juin 12 18:46:21 bibiserveur dotnet[337738]: System.ArgumentException: Invalid URI: The URI scheme is not valid. (Parameter 'value')
juin 12 18:46:21 bibiserveur dotnet[337738]: [18:46:21] [ERR] [35] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Info/Public.'

**Comment by glatigny** [comment]
You should remove the line `proxy_set_header X-Forwarded-Proto $remote_addr;`.
Sending a wrong scheme value is messing with the UriBuilder.
Best is to use the latest version of the documentation : https://jellyfin.org/docs/general/networking/nginx.html

**Comment by alashow** [comment]
I had the same issue, removing `proxy_set_header X-Forwarded-Proto $remote_addr;` from nginx config fixed it.
