### ISSUE TITLE
[Issue]: Cannot transcode "*.iso" files

### ISSUE THREAD

**Issue by codehasbug** [jellyfin/jellyfin#7478]
### Please describe your bug

Hi, I tried to play a movie with suffix 'iso'. Unfortunately, An error occurs when ffmpeg transcode with command `/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/a116beb4b900840010922c476e2d1f61/" -hls_playlist_type event -hls_segment_filename "/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61%d.ts" -y "/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61.m3u8"`  Please check logs in the below for more details
I run jellyfin with container `docker.io/jellyfin/jellyfin  latest      0aa773b67433  6 months ago  771 MB`  .
Do anyone have the same problem? Is there any help? Thanks.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:ArchLinux
- Virtualization: Podman
- Clients: Browser and Kodi
- Browser: Edge
- FFmpeg Version: 4.3.2
- Playback Method: Transcode
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: HOST
- Storage: btrfs
```

### Jellyfin logs

```shell
[2022-03-20 05:32:21.411 +00:00] [INF] [132] Emby.Server.Implementations.IO.LibraryMonitor: "The.Godfather.Trilogy.1972-1990.2160p.UHD.Blu-ray.DV.REMUX.HEVC.TrueHD.5.1-HDH" ("/media/multimedia/Movies/The.Godfather.Trilogy.1972-1990.2160p.UHD.Blu-ray.DV.REMUX.HEVC.TrueHD.5.1-HDH") will be refreshed.
[2022-03-20 05:32:21.477 +00:00] [INF] [132] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-03-20 05:32:21.477 +00:00] [INF] [132] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  ""
[2022-03-20 05:32:21.479 +00:00] [INF] [132] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 1 items:  "ef9bddd6c0bd7faec8a3c9f45b83095a"
[2022-03-20 05:32:21.479 +00:00] [INF] [132] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-03-20 05:32:21.479 +00:00] [INF] [132] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:00.0017188"
[2022-03-20 05:32:23.523 +00:00] [INF] [95] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline|high 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "120", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2022-03-20 05:32:23.568 +00:00] [ERR] [136] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-03-20 05:32:23.662 +00:00] [INF] [136] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "yyjmedia". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-03-20 05:32:23.670 +00:00] [INF] [136] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-03-20 05:32:23.675 +00:00] [INF] [136] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso" with codec "Unknown codec"
[2022-03-20 05:32:23.687 +00:00] [INF] [136] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-03-20 05:32:23.687 +00:00] [INF] [136] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso" with codec "Unknown codec"
[2022-03-20 05:32:24.070 +00:00] [INF] [136] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/765cb2f4b16c2ee2adac1f5dcf602fe3/" -hls_playlist_type event -hls_segment_filename "/media/multimedia/.transcode/765cb2f4b16c2ee2adac1f5dcf602fe3%d.ts" -y "/media/multimedia/.transcode/765cb2f4b16c2ee2adac1f5dcf602fe3.m3u8"
[2022-03-20 05:32:24.123 +00:00] [ERR] [132] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
```

### FFmpeg logs

```shell
/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/a116beb4b900840010922c476e2d1f61/" -hls_playlist_type event -hls_segment_filename "/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61%d.ts" -y "/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61.m3u8"  -v trace
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Splitting the commandline.
Reading option '-i' ... matched as input url with argument 'file:/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso'.
Reading option '-map_metadata' ... matched as option 'map_metadata' (set metadata information of outfile from infile) with argument '-1'.
Reading option '-map_chapters' ... matched as option 'map_chapters' (set chapters mapping) with argument '-1'.
Reading option '-threads' ... matched as AVOption 'threads' with argument '0'.
Reading option '-sn' ... matched as option 'sn' (disable subtitle) with argument '1'.
Reading option '-copyts' ... matched as option 'copyts' (copy timestamps) with argument '1'.
Reading option '-avoid_negative_ts' ... matched as AVOption 'avoid_negative_ts' with argument 'disabled'.
Reading option '-max_muxing_queue_size' ... matched as option 'max_muxing_queue_size' (maximum number of packets that can be buffered while waiting for all streams to initialize) with argument '2048'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'hls'.
Reading option '-max_delay' ... matched as AVOption 'max_delay' with argument '5000000'.
Reading option '-hls_time' ... matched as AVOption 'hls_time' with argument '3'.
Reading option '-hls_segment_type' ... matched as AVOption 'hls_segment_type' with argument 'mpegts'.
Reading option '-start_number' ... matched as AVOption 'start_number' with argument '0'.
Reading option '-hls_base_url' ... matched as AVOption 'hls_base_url' with argument 'hls/a116beb4b900840010922c476e2d1f61/'.
Reading option '-hls_playlist_type' ... matched as AVOption 'hls_playlist_type' with argument 'event'.
Reading option '-hls_segment_filename' ... matched as AVOption 'hls_segment_filename' with argument '/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61%d.ts'.
Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
Reading option '/media/multimedia/.transcode/a116beb4b900840010922c476e2d1f61.m3u8' ... matched as output url.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'trace'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option copyts (copy timestamps) with argument 1.
Applying option y (overwrite output files) with argument 1.
Applying option v (set logging level) with argument trace.
Successfully parsed a group of options.
Parsing a group of options: input url file:/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso.
Successfully parsed a group of options.
Opening an input file: file:/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso.
[NULL @ 0x555cd88d0a80] Opening 'file:/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso' for reading
[file @ 0x555cd88d1600] Setting default whitelist 'file,crypto,data'
[AVIOContext @ 0x555cd88d9a80] Statistics: 1048576 bytes read, 0 seeks
file:/media/multimedia/Movies/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER/Batman.Forever.1995.2160P.UHD.BLURAY.HEVC.HDR10.TrueHD.7.1-COASTER.iso: Invalid data found when processing input
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
Try jellyfin 10.8 instead. `docker pull nyanmisaka/jellyfin:latest`

**Comment by codehasbug** [comment]
> Try jellyfin 10.8 instead. `docker pull nyanmisaka/jellyfin:latest`

It works, thank you for your replying. I will close the issue.
