### ISSUE TITLE
[Issue]: unattended install error

### ISSUE THREAD

**Issue by cyberb** [jellyfin/jellyfin#7485]
### Please describe your bug

I am trying to package jellyfin as a package for Syncloud project (https://github.com/syncloud/jellyfin), when user pushes install button system is expected to be configured and ldap plugin activated so ui setup wizard is not needed.

I have tried to copy few configs and ldap plugin and it seem to be detected correctly. The problem is I am trying to set IsStartupWizardCompleted to false to skip the wizard and get migrations apply error in the log.

As I understand this happens because wizard will create migrations.xml file. Is it possible to apply migrations but not show wizard?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: LDAP-Auth 12.0.0.0
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.7.0
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.7.0
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.7.0
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'DisableTranscodingThrottling'
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration 'DisableTranscodingThrottling' applied successfully
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'CreateLoggingConfigHeirarchy'
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration 'CreateLoggingConfigHeirarchy' applied successfully
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateActivityLogDatabase'
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateActivityLogDatabase'
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at SQLitePCL.pretty.SQLite3.Open(String filename, ConnectionFlags flags, String vfs)
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
Mar 21 21:47:01 db3d3e2ac580 jellyfin.server[1328]: [21:47:01] [FTL] [1] Main: Error while starting server.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cyberb** [comment]
Another reason I do not want to show the wizard is that I do not need additional account created just ldap is required.

It would be great to have a way to call some command line `./jellyfin install` instead of a ui wizard to tell the system that this is a first time start (install vs upgrade).
