### ISSUE TITLE
[Issue]: jellyfin in docker cant write samba file

### ISSUE THREAD

**Issue by swhoro** [jellyfin/jellyfin#7489]
### Please describe your bug

I install a ubuntu lxc on pve (uninstall apparmor in ubuntu or docker wont run correctly) and docker is installed on this ubuntu
I have a synlogy nas and run samba server on it.
In the ubuntu, I mount samba file via fstab:
```
//192.168.1.4/content/media /mnt/jellyfin/media cifs defaults,username=[synology user],password=[synology password]
//192.168.1.4/docker/jellyfin/config /mnt/jellyfin/config cifs defaults,username=[synology user],password=[synology password]
//192.168.1.4/docker/jellyfin/font /mnt/jellyfin/font cifs defaults,username=[synology user],password=[synology password]
//192.168.1.4/docker/jellyfin/ffmpeg /mnt/jellyfin/ffmpeg cifs defaults,username=[synology user],password=[synology password]
```
here is docker run command:
```
docker run -d -p 8096:8096 --name jellyfin -v /mnt/jellyfin/config:/config -v /mnt/jellyfin/media:/media -v /mnt/jellyfin/ffmpeg:/usr/lib/jellyfin-ffmpeg -v /mnt/jellyfin/font:/usr/share/fonts/truetype/dejavu  jellyfin/jellyfin
```

It seems jellyfin in docker cannot write database and anything in the samba mount pint
But in ubuntu I can create directory in /mnt/jellyfin/config as root

### Jellyfin Version

10.7.7

### if other:

docker jellyfin latest

### Environment

```markdown
- OS: ubuntu lxc in pve
- Virtualization:pve
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```
[04:47:45] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[04:47:45] [ERR] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Error loading configuration file: /config/config/network.xml
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderNetworkConfiguration.Read3_NetworkConfiguration()
   at System.Xml.XmlReader.MoveToContent()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.LoadConfiguration(String path, Type configurationType)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
[04:47:45] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[04:47:45] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[04:47:45] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[04:47:45] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[04:47:45] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[04:47:45] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
[04:48:17] [FTL] [1] Main: Error while starting server.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Jellyfin.Server.Implementations.JellyfinDbProvider..ctor(IServiceProvider serviceProvider, IApplicationPaths appPaths)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[04:48:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[04:48:17] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
From my experience SqlLite doesn't like to work on network mounts.

I'd personally keep the config on the box running the container, but you could try [this answer](https://stackoverflow.com/a/30284290) (add `,nobrl` to the options for the config mount in your fstab).

**Comment by swhoro** [comment]
> 

thanks for your reply
I finally set config folder to local and use rsync to backup

**Comment by Chris3773** [comment]
This is a common permission problem when running docker volumes over samba.

This is the mount option I use for jellyfin running in docker over samba volumes.
`username=[username],password=[password],iocharset=utf8,vers=3.0,mfsymlinks,nolock,noperm`

**Comment by cvium** [comment]
Closing this as it is not related to jellyfin
