### ISSUE TITLE
[Issue]: Unable to load user permission

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin#7505]
### Please describe your bug

https://www.reddit.com/r/jellyfin/comments/tpqrfm/the_first_beta_for_1080_is_up_were_getting_there/i2durtt/

### Jellyfin Version

Other

### if other:

10.8.0-beta.1

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
today at 6:24:52 PM[18:24:52] [ERR] [26] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /users/public.
today at 6:24:52 PMSystem.InvalidOperationException: Sequence contains no matching element
today at 6:24:52 PM   at System.Linq.ThrowHelper.ThrowNoMatchException()
today at 6:24:52 PM   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
today at 6:24:52 PM   at Jellyfin.Data.Entities.User.HasPermission(PermissionKind kind)
today at 6:24:52 PM   at Jellyfin.Api.Controllers.UserController.<>c__DisplayClass25_0.<Get>b__0(User i)
today at 6:24:52 PM   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
today at 6:24:52 PM   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
today at 6:24:52 PM   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
today at 6:24:52 PM   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
today at 6:24:52 PM   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
today at 6:24:52 PM   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
today at 6:24:52 PM   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 6:24:52 PM   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 6:24:52 PM   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
today at 6:24:52 PM--- End of stack trace from previous location ---
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
today at 6:24:52 PM--- End of stack trace from previous location ---
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
today at 6:24:52 PM   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
today at 6:24:52 PM   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
today at 6:24:52 PM   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
today at 6:24:52 PM   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
today at 6:24:52 PM   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
today at 6:24:52 PM   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
today at 6:24:52 PM   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
today at 6:24:52 PM   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
today at 6:24:52 PM   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Closing as duplicate of https://github.com/jellyfin/jellyfin/issues/6109
