### ISSUE TITLE
[Issue]: Failure to update a plugin stops the entire "Update Plugins" task

### ISSUE THREAD

**Issue by rigrig** [jellyfin/jellyfin#7511]
### Please describe your bug

After updating to 10.8.0-beta1, there was an [issue](https://github.com/lyarenei/jellyfin-plugin-listenbrainz/pull/8) with a 3rd party plugin repo, causing the update to fail because of a checksum mismatch.
When this happens, the entire "Update Plugins" task stops, meaning it won't update any other plugins either.

## Steps to reproduce:
1. Have an updateable official plugins installed (Playback Reporting 11.0.0.0)
2. Have a plugin installed from a 3rd party Plugin repository (Listenbrainz 2.0.0.0), for which the latest manifest points to a `sourceUrl` which doesn't match the `checksum`
3. Run the "Update Plugins" task

### Expected result:
The invalid plugin fails to install, but the updater continues with other plugins (or just plugins from other repos)

### Actual result:
The invalid plugin fails to install, and the updater stops.

## Workaround:
Remove the malfunctioning repo

### Jellyfin Version

Other

### if other:

10.8.0-beta1

### Environment

```markdown
- OS: Synology DSM
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox 98.0.2
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: AniDB 6.0.0.0, AniList 5.0.0.0, AniSearch 4.0.0.0, AudioDB 10.8.0.0, Fanart 8.0.0.0, Intros 1.3.0.0, Kitsu 3.0.0.0, Kodi Sync Queue 8.0.0.0, Listenbrainz 2.0.0.0, MusicBrainz 10.8.0.0, OMDb 10.8.0.0, Open Subtitles 18.0.0.0, Playback Reporting 12.0.0.0, SkinManager 1.5.0.0, Studio Images 10.8.0.0, TMDb 10.8.0.0, TMDb Box Sets 10.0.0.0, TheTVDB 8.0.0.0, Trakt 15.0.0.0, Webhook 11.0.0.0
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[13:35:58] [ERR] Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[13:35:58] [ERR] Error
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.PluginUpdateTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/7512
