### ISSUE TITLE
[Issue]: SQLitePCL.pretty.SQLiteException: disk I/O error

### ISSUE THREAD

**Issue by RobertS6A** [jellyfin/jellyfin#7522]
### Please describe your bug

Hello everyone

When I try to start the Jellyfin service it stops and gives me the disk I/O error.
I checked online for similar errors but could not find anything to help me.
The filesystem is a btrfs and it is not full at all. It was working before. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Linux Endeavour
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: VAAPI
- Plugins:
- Reverse Proxy: none
- Base URL:
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2022-03-29 17:50:06.671 -07:00] [INF] [1] Main: Jellyfin version: "10.7.7"
[2022-03-29 17:50:06.689 -07:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_ADD_OPTS, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIRECTORY, /var/lib/jellyfin]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_CACHE_DIRECTORY, /var/cache/jellyfin]"]
[2022-03-29 17:50:06.692 -07:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin", "--webdir=/usr/share/jellyfin/web"]
[2022-03-29 17:50:06.693 -07:00] [INF] [1] Main: Operating system: "Linux"
[2022-03-29 17:50:06.693 -07:00] [INF] [1] Main: Architecture: X64
[2022-03-29 17:50:06.693 -07:00] [INF] [1] Main: 64-Bit Process: True
[2022-03-29 17:50:06.693 -07:00] [INF] [1] Main: User Interactive: True
[2022-03-29 17:50:06.694 -07:00] [INF] [1] Main: Processor count: 16
[2022-03-29 17:50:06.694 -07:00] [INF] [1] Main: Program data path: "/var/lib/jellyfin"
[2022-03-29 17:50:06.694 -07:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2022-03-29 17:50:06.694 -07:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2022-03-29 17:50:06.906 -07:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/var/cache/jellyfin"
[2022-03-29 17:50:06.945 -07:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.6.6.0/28,10.9.9.0/24,10.10.10.0/24,127.0.0.1/8]"
[2022-03-29 17:50:06.945 -07:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2022-03-29 17:50:06.946 -07:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.6.6.0/28,10.9.9.0/24,10.10.10.0/24,127.0.0.1/8]"
[2022-03-29 17:50:06.952 -07:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2022-03-29 17:50:06.952 -07:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2022-03-29 17:50:06.988 -07:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2022-03-29 17:50:06.996 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/AniList_4.0.0.0/Jellyfin.Plugin.AniList.dll"
[2022-03-29 17:50:06.998 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Emby.AutoOrganize, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Auto Organize_9.0.0.0/Emby.AutoOrganize.dll"
[2022-03-29 17:50:06.998 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Intros, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Intros_1.3.1.0/Jellyfin.Plugin.Intros.dll"
[2022-03-29 17:50:06.999 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Kodi Sync Queue_6.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll"
[2022-03-29 17:50:07.000 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "/var/lib/jellyfin/plugins/Kodi Sync Queue_6.0.0.0/LiteDB.dll"
[2022-03-29 17:50:07.001 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "OpenSubtitlesHandler, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_12.0.0.0/OpenSubtitlesHandler.dll"
[2022-03-29 17:50:07.001 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_12.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2022-03-29 17:50:07.001 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.PlaybackReporting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Playback Reporting_10.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll"
[2022-03-29 17:50:07.002 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Reports, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Reports_12.0.0.0/Jellyfin.Plugin.Reports.dll"
[2022-03-29 17:50:07.003 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SkinManager, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Skin Manager_2.0.0/Jellyfin.Plugin.SkinManager.dll"
[2022-03-29 17:50:07.003 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.ThemeSongs, Version=10.7.0.2, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Theme Songs_10.7.0.2/Jellyfin.Plugin.ThemeSongs.dll"
[2022-03-29 17:50:07.004 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "YoutubeExplode, Version=5.1.6.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Theme Songs_10.7.0.2/YoutubeExplode.dll"
[2022-03-29 17:50:07.005 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "YouTubeSearch, Version=2.2.4.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Theme Songs_10.7.0.2/YouTubeSearch.dll"
[2022-03-29 17:50:07.006 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_6.0.0.0/TvDbSharper.dll"
[2022-03-29 17:50:07.007 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_6.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2022-03-29 17:50:07.008 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Trakt, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Trakt_12.0.0.0/Trakt.dll"
[2022-03-29 17:50:08.478 -07:00] [FTL] [1] Main: Error while starting server.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-03-29 17:50:08.483 -07:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2022-03-29 17:50:08.484 -07:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kjkent** [comment]
For the sake of preserving the issue, I am also having this problem.

**Comment by Bond-009** [comment]
Closing as duplicate of #3667
