### ISSUE TITLE
[10.8.0][Issue]: Can't play any newly added episodes of any show.

### ISSUE THREAD

**Issue by gerben838665** [jellyfin/jellyfin#7564]
### Please describe your bug

After adding a new episode to any show i'm unable to play the episode.
Trying to play it results in an infinite loading screen.
Client doesn't freeze during this clicking to another page in Jellyfin removes the loading animation.
Relevant logs are added below.

This problem doesn't show up for newly added movies.
Episodes that were added before updating to 10.8.0-beta1 have no problems playing in 10.8.0-beta1.
Reverting back to 10.7.7 makes me able to play the new episodes without any problems.
If I revert to 10.7.7 play an episode with the problem and then upgrade again to 10.8.0-beta1 the problem is fixed for that episode but remains for episodes added during 10.8.0-beta that i didn't play in 10.7.7.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: UNRAID v6.9.2
- Virtualization: Docker
- Clients: Browser & Jellyfin Media Player v1.7.0 Prerelease 4
- Browser: Edge 100
- FFmpeg Version: not sure version included in docker container i expect.
- Playback Method: Direct Play
- Hardware Acceleration: None
- Plugins: AudioDB, MusicBrainz, OMDb, Playback Reporting, Studio Images, TMDb, TheTVDB
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[2022-04-06 21:32:56.808 +02:00] [ERR] [15] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-04-06 21:32:56.843 +02:00] [INF] [15] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "MYUSERNAME". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-04-06 21:32:56.844 +02:00] [ERR] [15] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Items/c542f63d4f9b2e1c0b0af9e76cbc37c9/PlaybackInfo".
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.<>c__DisplayClass21_1.<GetVideoTranscodeProfile>b__1(TranscodingProfile transcodingProfile)
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToLookup[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToLookup[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at MediaBrowser.Model.Dlna.StreamBuilder.GetVideoTranscodeProfile(MediaSourceInfo item, VideoOptions options, MediaStream videoStream, MediaStream audioStream, IEnumerable`1 candidateAudioStreams, MediaStream subtitleStream, StreamInfo playlistItem)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Jellyfin.Api.Helpers.MediaInfoHelper.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy, IPAddress ipAddress)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
   at lambda_method501(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any browser or client logs here

```shell
POST https://jellyfin.mydomain.com/Items/c542f63d4f9b2e1c0b0af9e76cbc37c9/PlaybackInfo?UserId=1d2de838516f4e0c895435a8c5883048&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 500
b @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
value @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
value @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
value @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
H @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
le @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
ie @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
K @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
B @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
(anonymous) @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
Promise.then (async)
l.play @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
h @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
g @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
bt @ main.jellyfin.bundle.js?3124aa6da023ea578dfc:2
index.html#!/home.html:1 
        
Uncaught (in promise) Response {type: 'basic', url: 'https://jellyfin.mydomain.com/Items/c542f63d4f9b2e1…OpenLiveStream=true&MaxStreamingBitrate=140000000', redirected: false, status: 500, ok: false, …}body: (...)bodyUsed: falseheaders: Headers {}ok: falseredirected: falsestatus: 500statusText: ""type: "basic"url: "https://jellyfin.mydomain.com/Items/c542f63d4f9b2e1c0b0af9e76cbc37c9/PlaybackInfo?UserId=1d2de838516f4e0c895435a8c5883048&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"[[Prototype]]: ResponsearrayBuffer: ƒ arrayBuffer()blob: ƒ blob()body: (...)bodyUsed: (...)clone: ƒ clone()formData: ƒ formData()headers: (...)json: ƒ json()ok: (...)redirected: (...)status: (...)statusText: (...)text: ƒ text()type: (...)url: (...)constructor: ƒ Response()Symbol(Symbol.toStringTag): "Response"get body: ƒ body()get bodyUsed: ƒ bodyUsed()get headers: ƒ headers()get ok: ƒ ok()get redirected: ƒ redirected()get status: ƒ status()get statusText: ƒ statusText()get type: ƒ type()get url: ƒ url()[[Prototype]]: Object
main.jellyfin.bundle.js?3124aa6da023ea578dfc:2 Sending web socket message: KeepAlive
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourpatched** [comment]
Have you updated FFMPEG?

**Comment by gerben838665** [comment]
I didn't update FFMPEG manually I just updated to 10.8.0-beta1 by changed my docker container from `latest` to `10.8.0-beta1`.
Do you have to manually include FFMPEG in the config folder now? I thought it was just included in the docker container.
I did see the note about FFMPEG in the release but I didn't really need the newer improvements because I'm not using HWA or Tonemapping currently.

Note: I'm using the official jellyfin docker container.

But now that you mention it i could very well be missing FFMPEG somehow I found the following error in my server log:
```shell
[2022-04-06 21:26:12.848 +02:00] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/local/bin/ffmpeg' with working directory '/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[2022-04-06 21:26:12.851 +02:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: "/usr/local/bin/ffmpeg"
[2022-04-06 21:26:12.859 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: ""
```

**Comment by sourpatched** [comment]
>  An error occurred trying to start process '/usr/local/bin/ffmpeg' with working directory '/'. No such file or directory
This tells me it's not installed but it should be using Jellyfin ffmpeg not system, I could be wrong since I don't use docker.

I would say check your Config for docker as the path for FFMPEG isn't in installed on the OS.

**Comment by gerben838665** [comment]
Just found the following in config/encoding.xml:
```shell
<EncoderAppPath>/usr/local/bin/ffmpeg</EncoderAppPath>
<EncoderAppPathDisplay>/usr/lib/jellyfin-ffmpeg/ffmpeg</EncoderAppPathDisplay>
```

Looking at the documentation here: [EncodingOptions](https://jellyfin.org/docs/plugin-api/MediaBrowser.Model.Configuration.EncodingOptions.html?q=encodingoptions). I think those options should be set to the same value.
I'm gonna set EncoderAppPath to /usr/lib/jellyfin-ffmpeg/ffmpeg and check what happens later today when I get home.

**Comment by gerben838665** [comment]
Manually changing the EncoderAppPath seems to have fixed the issue for me.
