### ISSUE TITLE
[Issue]: Jellyfin Server Mac OS 10.15.7 - Corrupt: SQLitePCL.pretty.SQLiteException

### ISSUE THREAD

**Issue by mendocinotim** [jellyfin/jellyfin#7577]
### Please describe your bug

Been using Jellyfin for a couple of years now.
Never had a problem till now.
Jellyfin 10.7.7

Tail of log entry shown below.
How do I fix this?

Have already performed a full uninstall using CleanMyMac uninstall.
Am not very technical - any help would be greatly appreciated.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-04-09 21:20:24.830 -07:00] [FTL] [1] Main: Error while starting server.
Corrupt: SQLitePCL.pretty.SQLiteException: database disk image is malformed
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by certainlysylvia** [comment]
Same issue - new build I got the whole thing working and then crunch - now cannot reinstall from ground up - same issue over and over - I remove and manually delete all other bits including cache etc

Almalinux using https://computingforgeeks.com/install-jellyfin-media-server-on-centos-rocky/ alma is very very very likely to work the same binary compat and all

**Comment by certainlysylvia** [comment]
Further to previous - seems was an sqlite issue - corrupted

Handy details (though the db names differ) here -> https://support.emby.media/support/solutions/articles/44002210894-corrupt-database

Please don't hurt me to linking da evils - the advice is the advice :D
