### ISSUE TITLE
[10.8.0][Issue]: TMDB Unhandled Exception Error

### ISSUE THREAD

**Issue by srcrist** [jellyfin/jellyfin#7600]
### Please describe your bug

There is an unhandled exception in the TMDB provider that is spamming logs with errors.

This is happening both during media scans and (seemingly) when no scan is happening at all. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux (Ubuntu 21.10, installed from package)
- Virtualization: None
- Clients: N/A
- Browser: N/A
- FFmpeg Version: Jellyfin-FFMPEG 4.4.1-4
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: AniDB, AudioDB, InfuseSync, Kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb, TVmaze, TheTVDB
- Reverse Proxy: Nginx
- Base URL: N/A
- Networking: 1gbps data center
- Storage: nvme
```

### Jellyfin logs

```shell
[2022-04-15 00:29:11.792 -04:00] [ERR] Error in "TheMovieDb"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TMDbLib.Rest.RestResponse.Dispose()
   at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2022-04-15 00:29:11.862 -04:00] [INF] Processing playback tracker : "58c44def-f305-5874-b345-aca60f6ced5b-4e1bf52dc0354326ac99178f9c1693fb-5a47196fd0b22b0b0db3fe682528f900"
[2022-04-15 00:29:11.885 -04:00] [ERR] Error in "TheMovieDb"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TMDbLib.Rest.RestResponse.Dispose()
   at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2022-04-15 00:29:11.948 -04:00] [ERR] Error in "TheMovieDb"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TMDbLib.Rest.RestResponse.Dispose()
   at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2022-04-15 00:29:12.065 -04:00] [ERR] Error in "TheMovieDb"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TMDbLib.Rest.RestResponse.Dispose()
   at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Seems to be an upstream bug in TMDbLib: https://github.com/LordMike/TMDbLib/issues/405

**Comment by Cookie-Monster-Coder** [comment]
Same, I'm getting flooded by these.

**Comment by Shadowghost** [comment]
#7697 should fix this,
