### ISSUE TITLE
[Issue]: Disposing CoreAppHost, Received SIGTERM Signal

### ISSUE THREAD

**Issue by MuhammadAhsanDonuts** [jellyfin/jellyfin#7606]
### Please describe your bug

Jellyfin server crashed and now trying to restart the service back, but that isn't working. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: [Ubuntu 20.0 LTS]
- Virtualization: [Hypervisor Prox-mox]
- Clients: [Browser, Android, Firestick, etc]
- Browser: [All]
- FFmpeg Version: [Unknown]
- Playback Method: [Direct play]
- Hardware Acceleration: [none]
- Plugins: [none]
- Reverse Proxy: NGINX
- Base URL: 
- Networking: 
- Storage: [Local, NFS]
```

### Jellyfin logs

```shell
**THE ERROR:** 

Error while starting server.
Apr 16 18:34:47 jf-03 jellyfin[23590]: Full: SQLitePCL.pretty.SQLiteException: database or disk is full
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at SQLitePCL.pretty.StatementImpl.MoveNext()
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Apr 16 18:34:47 jf-03 jellyfin[23590]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Apr 16 18:34:47 jf-03 jellyfin[23590]: [18:34:47] [INF] Disposing CoreAppHost
Apr 16 18:34:47 jf-03 jellyfin[23590]: [18:34:47] [INF] Received a SIGTERM signal, shutting down
Apr 16 18:34:47 jf-03 systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
Apr 16 18:34:47 jf-03 systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Apr 16 18:34:47 jf-03 systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1076.
Apr 16 18:34:47 jf-03 systemd[1]: Stopped Jellyfin Media Server.
Apr 16 18:34:47 jf-03 systemd[1]: Started Jellyfin Media Server.
Apr 16 18:34:47 jf-03 telegraf[794]: 2022-04-16T18:34:47Z D! [outputs.influxdb] Wrote batch of 52 metrics in 40.234877ms
Apr 16 18:34:47 jf-03 telegraf[794]: 2022-04-16T18:34:47Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Your database is likely corrupted

**Comment by MuhammadAhsanDonuts** [comment]
@crobibero, but it didn't mention that database has been corrupted. Rather, It is showing disk is full? 

1. What could be the possible reason for database corruption?
Let's say, if it is corrupted, what are the possible options do I have for now?

**Comment by MuhammadAhsanDonuts** [comment]
Alright, I simply resized the disk and added 40G more to my VM. Issue has been resolved.
