### ISSUE TITLE
[Issue]: Jellyfin Docker 10.8.0-beta1 API does not seem to be working

### ISSUE THREAD

**Issue by mLgz0rn** [jellyfin/jellyfin#7609]
### Please describe your bug

When using the 10.8.0-beta1 tag for Docker the API for Jellyfin does not seem to be working.
Stuff like Organizr is unable to connect to Jellyfin.
Going back to the Unstable tag, and it works again.

Steps to reproduce:
1. Use 10.8.0-beta1 tag
2. API dosnt work
3. Use Unstable tag
4. API works

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Unraid 6.9.2
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox 99.0.1, Chrome 100.0.4896.88
- FFmpeg Version: 4.4.1
- Playback Method: Direct Play, Remux, Direct Stream, Transcode
- Hardware Acceleration: Intel QSV, VAAPI
- Plugins: AudioDB, Cover Art Archive, Fanart, Intros, Kodi Sync Queue, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, TVmaze, Trakt, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
today at 22:44:39[22:44:39] [ERR] [34] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users.
today at 22:44:39System.InvalidOperationException: Sequence contains no matching element
today at 22:44:39   at System.Linq.ThrowHelper.ThrowNoMatchException()
today at 22:44:39   at Jellyfin.Data.Entities.User.GetPreferenceValues[T](PreferenceKind preference)
today at 22:44:39   at Jellyfin.Server.Implementations.Users.UserManager.GetUserDto(User user, String remoteEndPoint)
today at 22:44:39   at Jellyfin.Api.Controllers.UserController.<>c__DisplayClass25_0.<Get>b__4(User i)
today at 22:44:39   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
today at 22:44:39   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
today at 22:44:39   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 22:44:39   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 22:44:39   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
today at 22:44:39--- End of stack trace from previous location ---
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
today at 22:44:39--- End of stack trace from previous location ---
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
today at 22:44:39   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
today at 22:44:39   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
today at 22:44:39   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
today at 22:44:39   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
today at 22:44:39   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
today at 22:44:39   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
today at 22:44:39   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
today at 22:44:39   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
today at 22:44:39   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
today at 22:44:39   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
today at 22:44:39   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
today at 22:44:39   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
today at 22:44:39   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
today at 22:44:39   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
today at 22:44:39   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
today at 22:44:39   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
today at 22:44:39   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
today at 22:44:39   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any browser or client logs here

POST http://mikl.local/api/v2/test/jellyfin 500 (Internal Server Error) 

Organizr API Function  Jellyfin Connection Error 
functions.js?v=c2c0d131c33235f849ced2b3ebf6311de66c205f:11610 console.trace

<html>
<body>

  | OrganizrApiError | @ | functions.js?v=c2c0d…6311de66c205f:11610
-- | -- | -- | --
  | (anonymous) | @ | functions.js?v=c2c0d…f6311de66c205f:7994
  | i | @ | jquery-2.2.4.min.js:2
  | fireWith | @ | jquery-2.2.4.min.js:2
  | z | @ | jquery-2.2.4.min.js:4
  | (anonymous) | @ | jquery-2.2.4.min.js:4
  | load (async) |   |  
  | send | @ | jquery-2.2.4.min.js:4
  | ajax | @ | jquery-2.2.4.min.js:4
  | organizrAPI2 | @ | functions.js?v=c2c0d…f6311de66c205f:4508
  | testAPIConnection | @ | functions.js?v=c2c0d…f6311de66c205f:7986
  | onclick | @ | (index):1

</body>
</html>

### Please attach any screenshots here

This is 10.8.0-beta1
![beta_api](https://user-images.githubusercontent.com/6141439/163690924-af2df2ce-8f07-4a1c-95e7-68af3a26e113.jpg)

This is Unstable
![api_unstable](https://user-images.githubusercontent.com/6141439/163690931-3d99b28f-fea4-4e71-a417-8a32a2e245af.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/7506
