### ISSUE TITLE
[Issue]: Cannot Connect any Clients

### ISSUE THREAD

**Issue by rockedsocks** [jellyfin/jellyfin#7612]
### Please describe your bug

Whenever I try to connect to my server from my phone (on my local network), I always time out. I can connect via my host machine, but not from the loopback address. I don't understand why this  is happening.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization:None
- Clients:Browser, Finamp, iOS
- Browser:Firefox 98
- FFmpeg Version:4.4
- Playback Method:
- Hardware Acceleration:none
- Plugins:none
- Reverse Proxy:none
- Base URL:none
- Networking:Host
- Storage:local
```

### Jellyfin logs

```shell
[14:29:43] [ERR] [95] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[14:29:43] [ERR] [95] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 192.168.1.27 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[14:29:44] [ERR] [94] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[14:29:44] [ERR] [94] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 192.168.1.27 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[14:29:44] [ERR] [93] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 0.0.0.0 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
[14:29:44] [ERR] [93] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 192.168.1.27 to 239.255.255.250:1900
System.Net.Sockets.SocketException (101): Network is unreachable
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
As i can read it from the logs you are trying to access an network external client via DLNA. That should not be possible. 239.255.255.250 is no private address but a multicast address. Is your phone in the same network as the jellyfin server? e.g not your guest wifi but the actual same wifi network as "192.168.1.27"?

**Comment by bialabs** [comment]
@rockedsocks same issue here on latest Jellyfin on Docker
Have you found a solution?

**Comment by JPVenson** [comment]
> @rockedsocks same issue here on latest Jellyfin on Docker Have you found a solution?

Did you read this:
https://jellyfin.org/docs/general/installation/container#docker
