### ISSUE TITLE
[10.8.0 beta 2][Issue]: Error: Cannot get image dimensions on all .svg logos

### ISSUE THREAD

**Issue by srcrist** [jellyfin/jellyfin#7626]
### Please describe your bug

During scans, Jellyfin is sending numerous errors to the logs about not being able to determine the image dimensions for .svg logo files in the metadata. Manual investigation has shown that the files are not corrupt, and otherwise load correctly in a viewer. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux [Ubuntu 21.10]
- Virtualization: Bare Metal
- Clients: N/A
- Browser: N/A
- FFmpeg Version: Jellyfin-FFMPEG 4.4.1-4
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: AniDB, AudioDB, InfuseSync, Kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb, TVmaze, TheTVDB
- Reverse Proxy: nginx
- Base URL: none
- Networking: Direct 1gbps, Data Center
- Storage: local with cloud media
```

### Jellyfin logs

```shell
[2022-04-19 21:58:08.375 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/88/88bf6d9eb317fed754379a5d9a1dd814/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-04-19 21:58:30.253 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/b4/b4ad202466414ae545d97fedf72a898b/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-04-19 21:58:47.527 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/7a/7a38914bb87174871eb4f707c95cfda0/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-04-19 21:59:31.571 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/7e/7e64089fe9eea0edf3fe0e2cc7701365/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-04-19 21:59:45.522 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/0c/0c3dd0e9e5216129e8e7746c213a5d39/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-04-19 21:59:58.292 -04:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/metadata/library/c1/c145024baf5e1baa4d2dbff5d0f46094/logo.svg"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Did this work in 10.7?

**Comment by srcrist** [comment]
> Did this work in 10.7?

I do not, unfortunately, have any logs remaining from 10.7 to check. I don't know, though.

**Comment by cvium** [comment]
I don't think skiasharp supports SVG. Dimensions for an SVG don't really make a lot of sense anyway?

**Comment by srcrist** [comment]
That was my thought too, but I'm not familiar enough with the code and what it's doing here that I felt comfortable proffering that as a suggestion. My intuition was that this might just be a case where an exception needs to be crafted so it simply skips this step of the image format is SVG. Sounds like you're considering the same?

**Comment by dannymichel** [comment]
> > Did this work in 10.7?
> 
> I do not, unfortunately, have any logs remaining from 10.7 to check. I don't know, though.

this is a new bug. i only started getting it in 10.8. didn't exist in 10.7

**Comment by LePips** [comment]
Possibly related: https://github.com/jellyfin/jellyfin-plugin-fanart/issues/24

**Comment by cvium** [comment]
Where are the logos from?

**Comment by Avamander** [comment]
This error can cause large amounts of logspam, it would be nice if it could be at least trimmed down if it happens for SVG images.

**Comment by JPVenson** [comment]
Bump. Go away bot

**Comment by rgmz** [comment]
Considering that [`SkiaSharp.Svg`](https://www.nuget.org/packages/SkiaSharp.Svg/) is deprecated and hasn't had a release since 2018, would it make sense to use a different SVG-handling component?

**Comment by JPVenson** [comment]
> Considering that [`SkiaSharp.Svg`](https://www.nuget.org/packages/SkiaSharp.Svg/) is deprecated and hasn't had a release since 2018, would it make sense to use a different SVG-handling component?

I am open for any recommendations

**Comment by JPVenson** [comment]
Issue should be mitigated by #9581

**Comment by BenMcLean** [comment]
This bug was always still happening for me on 10.11.6

**Comment by JPVenson** [comment]
@BenMcLean please open a new issue for that with all required infos. Its likely unrelated as this bug was closed 3 years ago with no further reports of it happening.
