### ISSUE TITLE
[10.8.0 Beta 2][Issue]: Live TV service becoming unresponsive and crashing.

### ISSUE THREAD

**Issue by srcrist** [jellyfin/jellyfin#7631]
### Please describe your bug

When the server is first started, live TV functions fine. After some indeterminate amount of time, however, attempts to load any channel's stream will fail, and an ffmpeg error (pasted below) will be sent to the logs. Restarting the Jellyfin service fixes the problem, and the channels become accessible again. I have reproduced this problem with both an M3U and HDHR tuner type.

These streams are created locally by ErsatzTV, which is not throwing errors and does not have to be restarted for correct behavior to resume. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux [Ubuntu 21.10, installed from package]
- Virtualization: Bare Metal
- Clients: Android, Android TV, Web Client, JF Media Player (Windows), ATV Swiftfin
- Browser: Firefox
- FFmpeg Version: Jellyfin-FFMPEG 4.4.1-4
- Playback Method: All
- Hardware Acceleration: QSV
- Plugins: AniDB, AudioDB, InfuseSync, Kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb, TVmaze, TheTVDB
- Reverse Proxy: Nginx
- Base URL: N/A
- Networking: Direct, 1gbps. Data Center. 
- Storage: Nvme local storage with cloud media.
```

### Jellyfin logs

```shell
(External IPs Removed)

[2022-04-20 15:39:27.281 -04:00] [INF] User policy for "Kids". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-04-20 15:39:27.281 -04:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="http://000.000.000.000:8096/LiveTv/LiveStreamFiles/98dcc019f7e84b6da08ebba2ae6398fd/stream.ts", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=AudioCodecNotSupported ) "media:/videos/63a669bb-91f9-6f88-9b90-dc5734ee4378/stream.ts?MediaSourceId=3b42323425d4cd14a5ea0263700fb7ce&VideoCodec=h264&AudioCodec=aac,mp3,wav&AudioStreamIndex=-1&VideoBitrate=359360000&AudioBitrate=640000&MaxFramerate=23.976025&api_key=<token>&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_3b42323425d4cd14a5ea0263700fb7ce&RequireAvc=false&h264-level=40&h264-videobitdepth=8&h264-profile=high&TranscodeReasons=AudioCodecNotSupported"
[2022-04-20 15:39:27.892 -04:00] [INF] "/usr/share/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 3000000 -user_agent \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36\" -fflags +igndts+genpts  -i \"http://000.000.000.000:8096/LiveTv/LiveStreamFiles/98dcc019f7e84b6da08ebba2ae6398fd/stream.ts\" -sn -codec:v:0 copy -fflags +genpts -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -ac 6 -ab 640000 -y \"/var/lib/jellyfin/transcodes/f462ac7c8534fb4830aad70b261cf8d2.ts\""
[2022-04-20 15:39:27.903 -04:00] [ERR] FFmpeg exited with code 1
[2022-04-20 15:39:28.002 -04:00] [ERR] Error processing request. URL "GET" "/videos/63a669bb-91f9-6f88-9b90-dc5734ee4378/stream.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Helpers.FileStreamResponseHelpers.GetTranscodedFile(StreamState state, Boolean isHeadRequest, HttpContext httpContext, TranscodingJobHelper transcodingJobHelper, String ffmpegCommandLineArguments, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource)
   at Jellyfin.Api.Controllers.VideosController.GetVideoStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1236(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
(External IPs Removed)

/videos/63a669bb-91f9-6f88-9b90-dc5734ee4378/stream.ts

{"Protocol":1,"Id":"3b42323425d4cd14a5ea0263700fb7ce","Path":"http://000.000.000.000:8096/LiveTv/LiveStreamFiles/98dcc019f7e84b6da08ebba2ae6398fd/stream.ts","EncoderPath":null,"EncoderProtocol>

/usr/share/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" ->


ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu2)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib >
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[tcp @ 0x55bfb5184000] Connection to tcp://000.000.000.000:8096 failed: Connection refused
http://000.000.000.000:8096/LiveTv/LiveStreamFiles/98dcc019f7e84b6da08ebba2ae6398fd/stream.ts: Connection refused
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
I'm going to close this. I still think this may be an issue, but it isn't this issue directly. I was getting errors about not being bound to an external IP around this same time (even though my binding is 0.0.0.0), and now that those have gone away, this issue has not recurred. Might still be an issue related to binding, might have been a temporary system fluke. But I don't think this is the issue any longer.
