### ISSUE TITLE
[Issue]: Missing Media Information

### ISSUE THREAD

**Issue by agodlydeciple** [jellyfin/jellyfin#7657]
### Please describe your bug

Every so often when adding new media, the media information will end up missing? This ends up causing down stream effects. For instance: 
* When streaming the files using the AndroidTV app, the videos have no end time. 
* You can't skip around in the video file 
* Because you can't skip around, you can't start the video and pick up where you left off. 
* You play 2 seconds of the video file it gets marked as complete. 

I saw that this issue was reported in #3912, however, it was reported and then instantly closed. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Arch Linux x86_64
- Virtualization:
- Clients: FireTV with official app
- Browser: Firefox
- FFmpeg Version: ffmpeg version n5.0
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- Storage: NFS
```

### Jellyfin logs

```shell
[2022-04-24 21:34:14.637 -05:00] [ERR] [104] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.chapters[0].id | LineNumber: 127 | BytePositionInLine: 37.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken) in /home/don/.cache/yay/jellyfin/src/jellyfin-10.7.7/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 437
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /home/don/.cache/yay/jellyfin/src/jellyfin-10.7.7/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs:line 127
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /home/don/.cache/yay/jellyfin/src/jellyfin-10.7.7/MediaBrowser.Providers/Manager/MetadataService.cs:line 765
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

The Media information screen looks like this: 
![image](https://user-images.githubusercontent.com/683837/165012357-a8bb58e5-df08-4e9d-be54-eb4ead1b5f26.png)

As opposed to this: 
![image](https://user-images.githubusercontent.com/683837/165012989-b0403e8a-df28-45d6-980b-cf1fd1abd9e5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
The stack trace you provided is a known issue with using ffmpeg 5 with jellyfin 10.7.7, it was fixed for 10.8 in #7363.

You can either downgrade your ffmpeg install or try upgrading to the 10.8 beta
