### ISSUE TITLE
Live TV m3u works fine with VLC and other players, Jellyfin won't play

### ISSUE THREAD

**Issue by ashipaek0** [jellyfin/jellyfin#7675]
**Media Info of the file**

**Logs**
https://gist.github.com/ashipaek0/3d6802eea11070c9cead2e5bdf334f6b

**FFmpeg Logs**
https://gist.github.com/ashipaek0/95a037d9866526bee4946807d5db2547

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Jellyfin Version: 10.8 beta 2
 - Hardware settings & device: 
 - Reverse proxy: cloudflare tunnel
 - Other hardware notes: Live TV M3U
 

**Client System (please complete the following information):**
 - Device: Laptop, phone
 - OS: Ubuntu, Android
 - Client: Web browser, Jellyfin Media Player, Jellyfin Android
 - Browser (if Web client): Brave browser
 - Client and Browser Version: v100

**Comment by eshirvana** [comment]
I have the same issue  on :

Version: 10.8.9
Operating System: Linux
Architecture: X64
I almost tried any live tv from https://iptv-org.github.io/ and It shows as multiple channels with no name like so :
![image](https://user-images.githubusercontent.com/72626662/221376954-32efb945-806f-4c1a-a355-031b859a1d92.png)

and still can't play anything , here tis last error trace ( not sure if ts's related but includes it here just in case :

```
023-02-25 19:55:17.598 +00:00] [INF] [16] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-02-25 19:55:17.601 +00:00] [INF] [16] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="stream-565092.ts", AudioStreamIndex=-1, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported, AudioCodecNotSupported ) "media:/videos/ce061024-b11c-64ba-3c4e-93047bef3f08/master.m3u8?MediaSourceId=707136082034332ae2275924fd013642&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=-1&VideoBitrate=139616000&AudioBitrate=384000&api_key=<token>&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707136082034332ae2275924fd013642&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-rangetype=SDR&h264-level=52&h264-deinterlace=true&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported,%20AudioCodecNotSupported"
[2023-02-25 19:55:17.618 +00:00] [INF] [19] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/config/transcodes/991a25ca7c5ba684f0821a24f54c5d31.m3u8"
[2023-02-25 19:55:17.680 +00:00] [INF] [19] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-02-25 19:55:17.683 +00:00] [INF] [19] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 3000000 -fflags +igndts -autorotate 0 -i file:\"stream-565092.ts\" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -preset superfast -crf 23 -maxrate 20000000 -bufsize 40000000 -profile:v:0 high -level 51 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 \"expr:gte(t,n_forced*3)\" -sc_threshold:v:0 0 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,yadif=0:-1:0,format=yuv420p\" -flags -global_header -codec:a:0 libfdk_aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url \"hls/f88cac19a6faad02be414cb14c151bac/\" -hls_segment_filename \"/config/transcodes/f88cac19a6faad02be414cb14c151bac%d.ts\" -hls_playlist_type event -hls_list_size 0 -y \"/config/transcodes/f88cac19a6faad02be414cb14c151bac.m3u8\""
[2023-02-25 19:55:17.747 +00:00] [ERR] [19] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2023-02-25 19:55:17.848 +00:00] [ERR] [19] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/ce061024-b11c-64ba-3c4e-93047bef3f08/live.m3u8".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
   at lambda_method1265(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-02-25 19:55:17.989 +00:00] [INF] [19] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/config/transcodes/f88cac19a6faad02be414cb14c151bac.m3u8"
[2023-02-25 19:55:19.514 +00:00] [INF] [16] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.9" playing null. Stopped at "0" ms
[2023-02-25 19:55:19.535 +00:00] [INF] [16] Emby.Server.Implementations.Library.MediaSourceManager: Live stream "707136082034332ae2275924fd013642" consumer count is now 0
[2023-02-25 19:55:19.536 +00:00] [INF] [16] Emby.Server.Implementations.Library.MediaSourceManager: Closing live stream "a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707136082034332ae2275924fd013642"
[2023-02-25 19:55:19.537 +00:00] [INF] [16] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Closing "LiveStream"
[2023-02-25 19:55:19.537 +00:00] [INF] [16] Emby.Server.Implementations.Library.MediaSourceManager: Live stream "a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_707136082034332ae2275924fd013642" closed successfully
[2023-02-25 19:55:19.554 +00:00] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.2.218:8096/Sessions/Playing/Stopped" to "192.168.2.225" in 0:00:01.6009744 with Status Code 204
```

**Comment by eshirvana** [comment]
I still have the same issue with  version 10.8.10

**Comment by Kakoluz** [comment]
I've found myself with this issue as well. After some digging i suspect that is something either with FFMPEG (my ffmpeg log ends with `Option reconnect_at_eof not found.`).

The thing that has me really confused is that i have setted up 2 channels (that are my own streamings for testing) one of them plays nicely and only remuxes and the other one, same settings just a different key, it won't play at all, jellyfin will try to transcode and fails.

Stream that fails (keys redacted)
[log](https://pastebin.com/A7G8BtUW
)
Stream that works:
[log](https://pastebin.com/Yq0LhtG1)

This is the /m3u8 file for both of them, the stream named kakoluz works, the one named dazn works 
https://pastebin.com/73emEBwg

VLC works fine for both. but jellyfin provide different arguments to them, even if i just stop one stream in OBS change the key and it won't play on the other with the exact same options.

**Comment by Next-Page-Vi** [comment]
mee too

**Comment by chminsc** [comment]
> Show

did you find a solution?

**Comment by PhynixP** [comment]
I have the same Problem (10.8.13). 
I hope the 10.9.0 will fix this problem.
