### ISSUE TITLE
Primary image missing from metadata in some cases

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#768]
**Describe the bug**
When I scrape with 10.1.0-1, it doesn't seem to get the portrait "poster" picture anymore and instead gets some kind of landscape picture, which would be fine if the tiles were landscape too, but somehow it looks weird now.
I noticed after scraping images from scratch on 10.1.0, so the difference is probably at scrape time.
This happens at least with tv and movie library types, so multiple different scrapers

**To Reproduce**
1. get 10.1.0
2. make sure there is no pre-existing image data for the library, that all the metadata is new
3. Start scanning
4. Go to /web/index.html#!/tv.html or equivalent and observe..

**Expected behavior**
I'm not sure which, but either it used to zoom to fill, or it got a different (poster style) picture.

**Screenshots**
![capture](https://user-images.githubusercontent.com/1411903/51947996-37342700-2427-11e9-8b96-0a43a1d2ae97.PNG)

**System (please complete the following information):**
 - OS: debian stretch
 - Browser: Firefox
 - Jellyfin Version: debian package 10.1.0-1

**Other**

I have another instance on 10.0.2, but I might have scraped even before that, here's how it looks and how I'd expect it:
![capture](https://user-images.githubusercontent.com/1411903/51948171-c6d9d580-2427-11e9-990b-dbf4cf0454d1.PNG)

**Comment by hawken93** [comment]
think I finally have found a usable title now lol.
Initial brainstorming is that maybe API key change might have messed this up? Or other changes to the scraping code?

**Comment by hawken93** [comment]
![metadata manager, 10.1.0](https://user-images.githubusercontent.com/1411903/51948394-99d9f280-2428-11e9-81f7-90cc6e9eefb2.png)

![metadata manager, 10.0.2](https://user-images.githubusercontent.com/1411903/51948360-79aa3380-2428-11e9-9cc8-e8814f0f8e13.png)

lacking Primary

**Comment by hawken93** [comment]
[relevant.log](https://github.com/jellyfin/jellyfin/files/2810286/relevant.log)

here's a log file that might be interesting

**Comment by hawken93** [comment]
Workaround: By clicking on the library, going to scan, replace existing+images, it seems to take another round and gets it right this time

**Comment by hawken93** [comment]
Closing this,

When migrating database and config between installs, then it would be a good practice to force replace all the metadata.

**Comment by hawken93** [comment]
Requesting to change this from bug to enhancement or similar.

I think it would be an improvement to handle these errors better.

From some digging, BaseDynamicImageProvider errored out here, and the class only handles Primary image types. This explains the special case where only primary images failed, the other images were fine. The provider seems to use other pictures dynamically create a poster.


Dug up some stack traces that could help too:
```
Jan 30 00:25:38 jellyfin jellyfin[27427]: [00:25:38] [ERR] Error in Dynamic Image Provider
Jan 30 00:25:38 jellyfin jellyfin[27427]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/metadata/library/0c/0c41907140d802bb58430fed7e2cd79e/poster.png'.
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateSingleImage(List`1 itemsWithImages, String outputPathWithoutExtension, ImageType imageType) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 305
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, List`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 103
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 61
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /jellyfin-10.1/MediaBrowser.Providers/Manager/MetadataService.cs:line 810
```

```
Jan 30 00:25:38 jellyfin jellyfin[27427]: System.IO.FileNotFoundException: File not found
Jan 30 00:25:38 jellyfin jellyfin[27427]: File name: '/var/lib/jellyfin/metadata/library/16/16f6daee5e7741b1c7227164e3ad053f/poster.jpg'
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Drawing.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, IFileSystem fileSystem, Nullable`1 orientation, SKEncodedOrigin& origin) in /jellyfin-10.1/Emby.Drawing/SkiaEncoder.cs:line 254
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.GetNextValidImage(String[] paths, Int32 currentIndex, Int32& newIndex) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 177
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.BuildThumbCollageBitmap(String[] paths, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 95
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.BuildThumbCollage(String[] paths, String outputPath, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 67
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options) in /jellyfin-10.1/Emby.Drawing/ImageProcessor.cs:line 750
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateCollage(BaseItem primaryItem, List`1 items, String outputPath, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 189
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, List`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 103
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 61
Jan 30 00:25:38 jellyfin jellyfin[27427]:    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /jellyfin-10.1/MediaBrowser.Providers/Manager/MetadataService.cs:line 810
```

```
Jan 30 00:25:39 jellyfin jellyfin[27427]: System.IO.FileNotFoundException: File not found
Jan 30 00:25:39 jellyfin jellyfin[27427]: File name: '/var/lib/jellyfin/metadata/library/95/952b2be6434d10ce290aae6f2d85243b/poster.jpg'
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Drawing.SkiaEncoder.Decode(String path, Boolean forceCleanBitmap, IFileSystem fileSystem, Nullable`1 orientation, SKEncodedOrigin& origin) in /jellyfin-10.1/Emby.Drawing/SkiaEncoder.cs:line 254
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.GetNextValidImage(String[] paths, Int32 currentIndex, Int32& newIndex) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 177
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.BuildThumbCollageBitmap(String[] paths, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 95
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Drawing.StripCollageBuilder.BuildThumbCollage(String[] paths, String outputPath, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Drawing/StripCollageBuilder.cs:line 67
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Drawing.ImageProcessor.CreateImageCollage(ImageCollageOptions options) in /jellyfin-10.1/Emby.Drawing/ImageProcessor.cs:line 750
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.CreateCollage(BaseItem primaryItem, List`1 items, String outputPath, Int32 width, Int32 height) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 189
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, List`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 103
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /jellyfin-10.1/Emby.Server.Implementations/Images/BaseDynamicImageProvider.cs:line 61
Jan 30 00:25:39 jellyfin jellyfin[27427]:    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /jellyfin-10.1/MediaBrowser.Providers/Manager/MetadataService.cs:line 810
```
