### ISSUE TITLE
OutOfRangeException\Bad Request (code 400) when searching

### ISSUE THREAD

**Issue by jamesmurphy746** [jellyfin/jellyfin#7680]
### Describe the bug

have only recently added music to my JF and now I seem to be getting quite a few volley client errors when searching from androidtv client which seem to be when IncludeItemTypes=Audio

### Logs

```shell
[Logcat events]
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Movie%2CBoxSet&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Series&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Episode&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Person%2CPeople&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Video&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Recording&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Program&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=MusicArtist&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=MusicAlbum&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Audio&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Series&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Episode&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Movie%2CBoxSet&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Video&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Program&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Person%2CPeople&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Recording&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=MusicAlbum&UserId=[redacted]&format=json
E/Volley  (32124): [113521] BasicNetwork.performRequest: Unexpected response code 400 for [redacted]/Search/Hints?Limit=50&SearchTerm=nazareth&IncludeItemTypes=Audio&UserId=[redacted]&format=json
E/Jellyfin-AndroidTV(32124): org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ClientError:
E/Jellyfin-AndroidTV(32124):    at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:24)
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Movie%2CBoxSet&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Series&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Episode&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Person%2CPeople&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Video&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Recording&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Program&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=MusicArtist&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=MusicAlbum&UserId=[redacted]&format=json
D/Jellyfin-AndroidTV(32124): Adding request to queue: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Audio&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Person%2CPeople&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Movie%2CBoxSet&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Series&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Episode&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Recording&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Video&UserId=[redacted]&format=json
I/Jellyfin-AndroidTV(32124): Response received from: [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Program&UserId=[redacted]&format=json
D/Volley  (32124): [113520] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Audio&UserId=[redacted]&format=json 0x2e832b68 NORMAL 215> [lifetime=3297], [size=25], [rc=400], [retryCount=0]
E/Volley  (32124): [113520] BasicNetwork.performRequest: Unexpected response code 400 for [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=Audio&UserId=[redacted]&format=json
D/Volley  (32124): [113519] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=MusicAlbum&UserId=[redacted]&format=json 0x2e832b68 NORMAL 214> [lifetime=3302], [size=39], [rc=200], [retryCount=0]
D/Volley  (32124): [113521] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] [redacted]/Search/Hints?Limit=50&SearchTerm=pet+shop&IncludeItemTypes=MusicArtist&UserId=[redacted]&format=json 0x2e832b68 NORMAL 213> [lifetime=3314], [size=1557], [rc=200], [retryCount=0]
E/Jellyfin-AndroidTV(32124): org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.ClientError:
E/Jellyfin-AndroidTV(32124):    at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:24)



[server]
[2022-04-29 14:32:42.686 +01:00] [ERR] Error processing request. URL "GET" "/Search/Hints".
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Jellyfin.Api.Controllers.SearchController.GetSearchHintResult(SearchHintInfo hintInfo)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Jellyfin.Api.Controllers.SearchController.Get(Nullable`1 startIndex, Nullable`1 limit, Nullable`1 userId, String searchTerm, String[] includeItemTypes, String[] excludeItemTypes, String[] mediaTypes, Nullable`1 parentId, Nullable`1 isMovie, Nullable`1 isSeries, Nullable`1 isNews, Nullable`1 isKids, Nullable`1 isSports, Boolean includePeople, Boolean includeMedia, Boolean includeGenres, Boolean includeStudios, Boolean includeArtists)
   at lambda_method603(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Application version

0.11.5 & 0.13.3

### Where did you install the app from?

Sideloaded APK

### Device information

multiple, Generic\Chinese branded & Amazon Fire Tablet

### Android version

multiple

### Jellyfin server version

10.7.7

**Comment by jamesmurphy746** [comment]
@nielsvanvelzen , is this a server issue? when searching same titles though web the error would not occur.. so far it's only happened on androidtv client?

**Comment by jamesmurphy746** [comment]
definitely has something to do with Music.. as a last resort I removed all the Music from Jellyfin and sure enough - the errors have stopped..

**Comment by nielsvanvelzen** [comment]
The error in the server logs makes me think this is a server issue yes.

**Comment by crobibero** [comment]
This was fixed by https://github.com/jellyfin/jellyfin/pull/7894
