### ISSUE TITLE
[Issue]: Bad metadata can cause hard-to-debug ffprobe errors

### ISSUE THREAD

**Issue by duckinator** [jellyfin/jellyfin#7681]
### Please describe your bug

I don't think this counts as a _bug_ (if you give software bunk data it's gonna break things), but more of a request for catching and explaining the cause of a specific type of bad metadata so the logs are more useful. A conditional like `(bytes * 8 / durationInSeconds) <= Int32.MaxValue` might be useful for catching this.

I don't know what the appropriate solution is here, but even catching the problem and providing a more useful error (mentioning that the metadata for a specific file may be bad) would be fine.

If metadata for a large video file specifies a very short duration, this part of `MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.GetMediaStream` gets called:

https://github.com/jellyfin/jellyfin/blob/28223704f3c1c38c5a4acc65b38e2e8a1a06ea3d/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L896-L900

In this case, the file is ~591MB (~591000000 bytes) and the reported duration is either 0.000000000 (ffprobe) or 0.032000000 (mkvinfo) seconds.

Using those numbers, `bytes * 8 / durationInSeconds` would be either undefined (if exactly 0) or 147750000000 (if 0.032).

You wind up with this problem:

```
147750000000 <-- number being converted to an Int32
2147483647   <-- Int32.MaxValue, the largest number that can be stored in an Int32
```

And you get this error: `System.OverflowException: Value was either too large or too small for an Int32.`

Heres an example of such bad metadata:

```
Stream #0:1(eng): Audio: ac3, 48000 Hz, 2 channels, fltp (default)
    Metadata:                                                                                                                      
      title           : Stereo                                                                                                     
      BPS             : 0                                        
      BPS-eng         : 0                                        
      DURATION        : 00:00:00.000000000                                                                                         
      DURATION-eng    : 00:00:00.000000000                                                                                         
      NUMBER_OF_FRAMES: 0                                        
      NUMBER_OF_FRAMES-eng: 0
      NUMBER_OF_BYTES : 0   
      NUMBER_OF_BYTES-eng: 0
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-08-18 02:45:15
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-08-18 02:45:15
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(jpn): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s         
    Metadata:                                                                                                                      
      title           : Stereo                                   
      BPS             : 192000                                   
      BPS-eng         : 192000                                                                                                     
      DURATION        : 00:25:50.080000000                                                                                         
      DURATION-eng    : 00:25:50.080000000           
      NUMBER_OF_FRAMES: 48440
      NUMBER_OF_FRAMES-eng: 48440
      NUMBER_OF_BYTES : 37201920 
      NUMBER_OF_BYTES-eng: 37201920       
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-08-18 02:45:15
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-08-18 02:45:15
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Virtualization: KVM
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: Whatever ships with Jellyfin 10.7.7
- Playback Method: (Unsure, but probably not relevant -- ask and I can check)
- Hardware Acceleration: NVENC
- Plugins: AudioDB, Bookshelf, Kitsu, Kodi Sync Queue, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, TheTVDB
- Reverse Proxy: Caddy
- Base URL: none
- Networking: (Unsure, but probably not relevant -- ask and I can check)
- Storage: local
```

### Jellyfin logs

```shell
[2022-04-29 21:09:16.676 +00:00] [ERR] Error in "ffprobe"
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at System.Double.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.GetMediaStream(Boolean isAudio, MediaStreamInfo streamInfo, MediaFormatInfo formatInfo)
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.<>c__DisplayClass8_0.<GetMediaInfo>b__0(MediaStreamInfo s)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.GetMediaInfo(InternalMediaInfoResult data, Nullable`1 videoType, Boolean isAudio, String path, MediaProtocol protocol)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-04-29 21:09:21.721 +00:00] [INF] Starting Library Sync...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by duckinator** [comment]
Also: As best I can tell, the problem is caused by the difference between `bytes` and `durationInSeconds` -- the cases that cause it will be large files with short reported durations.

I suspect there's a theoretical possibility this could happen with accurate metadata, but I don't know how likely that is.

**Comment by DarkVirtue** [comment]
I seem to have found an instance of this happening with accurate metadata - something in the chapters info during JSON processing:

```
[2022-05-15 13:41:03.750 -04:00] [ERR] Error in "ffprobe"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.chapters[0].id | LineNumber: 364 | BytePositionInLine: 38.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, 
T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions optio
ns, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, 
T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions 
options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, 
T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions optio
ns, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, 
T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions op
tions, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationTok
en)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractCh
apters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefre
shOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Comment by DarkVirtue** [comment]
The FFprobe output:
```
ffprobe version 5.0.1-Jellyfin Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[libdav1d @ 0x55892fa63b00] libdav1d 1.0.0-0-g99172b1
[matroska,webm @ 0x55892fa4fa40] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55892fa4fa40] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'Memories (1995).mkv':
  Metadata:
    title           : Memories
    creation_time   : 2022-05-14T22:27:49.000000Z
    ENCODER         : Lavf59.16.100
  Duration: 01:53:25.06, start: -0.007000, bitrate: 3144 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 37.996292
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 37.996292, end 281.990042
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 281.990042, end 571.571000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 571.571000, end 931.180250
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 931.180250, end 1336.418417
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 1336.418417, end 1602.684417
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 1602.684417, end 2028.067708
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 2028.067708, end 2333.205875
      Metadata:
        title           : Chapter 08
    Chapter #0:8: start 2333.205875, end 2549.547000
      Metadata:
        title           : Chapter 09
    Chapter #0:9: start 2549.547000, end 2661.116792
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 2661.116792, end 2823.278792
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 2823.278792, end 3062.017292
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 3062.017292, end 3518.431583
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 3518.431583, end 3874.078542
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 3874.078542, end 4181.969458
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 4181.969458, end 4476.513708
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 4476.513708, end 4745.991250
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 4745.991250, end 4936.890292
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 4936.890292, end 5075.445375
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 5075.445375, end 5289.158875
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 5289.158875, end 5439.308875
      Metadata:
        title           : Chapter 21
    Chapter #0:21: start 5439.308875, end 5859.228375
      Metadata:
        title           : Chapter 22
    Chapter #0:22: start 5859.228375, end 6024.935583
      Metadata:
        title           : Chapter 23
    Chapter #0:23: start 6024.935583, end 6144.138000
      Metadata:
        title           : Chapter 24
    Chapter #0:24: start 6144.138000, end 6411.696958
      Metadata:
        title           : Chapter 25
    Chapter #0:25: start 6411.696958, end 6803.755292
      Metadata:
        title           : Chapter 26
    Chapter #0:26: start 6803.755292, end 6805.048250
      Metadata:
        title           : Chapter 27
  Stream #0:0(eng): Video: av1 (Main), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      BPS             : 24652680
      NUMBER_OF_FRAMES: 163158
      NUMBER_OF_BYTES : 20970337597
      SOURCE_ID       : 001011
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      ENCODER         : Lavc59.18.100 libaom-av1
      DURATION        : 01:53:25.056000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : Surround 5.1
      BPS             : 2086150
      NUMBER_OF_FRAMES: 637974
      NUMBER_OF_BYTES : 1774546692
      SOURCE_ID       : 001100
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      ENCODER         : Lavc59.18.100 libopus
      DURATION        : 01:53:25.063000000
  Stream #0:2(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      title           : Stereo
      BPS             : 897434
      NUMBER_OF_FRAMES: 637974
      NUMBER_OF_BYTES : 763386808
      SOURCE_ID       : 001101
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      ENCODER         : Lavc59.18.100 libopus
      DURATION        : 01:53:25.063000000
  Stream #0:3(jpn): Audio: opus, 48000 Hz, 5.1, fltp
    Metadata:
      title           : Surround 5.1
      BPS             : 2264003
      NUMBER_OF_FRAMES: 637974
      NUMBER_OF_BYTES : 1925833868
      SOURCE_ID       : 001102
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      ENCODER         : Lavc59.18.100 libopus
      DURATION        : 01:53:25.063000000
  Stream #0:4(jpn): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      title           : Stereo
      BPS             : 896296
      NUMBER_OF_FRAMES: 637974
      NUMBER_OF_BYTES : 762418260
      SOURCE_ID       : 001103
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      ENCODER         : Lavc59.18.100 libopus
      DURATION        : 01:53:25.063000000
  Stream #0:5(eng): Subtitle: hdmv_pgs_subtitle (forced)
    Metadata:
      title           : Signs and Titles
      BPS             : 267
      NUMBER_OF_FRAMES: 28
      NUMBER_OF_BYTES : 211428
      SOURCE_ID       : 001200
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      DURATION        : 01:46:51.787000000
  Stream #0:6(eng): Subtitle: hdmv_pgs_subtitle (default)
    Metadata:
      BPS             : 25974
      NUMBER_OF_FRAMES: 2035
      NUMBER_OF_BYTES : 20622410
      SOURCE_ID       : 001201
      _STATISTICS_WRITING_APP: mkvmerge v65.0.0 ('Too Much') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-05-14 22:27:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      DURATION        : 01:46:51.787000000
[libdav1d @ 0x55892fce8280] libdav1d 1.0.0-0-g99172b1
```

**Comment by Shadowghost** [comment]
It's a known issue with ffmpeg 5.0 (the made changes to the type of some fileds) - it's fixed in the beta, that's also why we rolled back the repo to ffmpeg 4.4.3 for existing installs and introduced a new `jellyfin-ffmpeg5` package.

**Comment by DarkVirtue** [comment]
Hm, interesting. I'm using the Jellyfin repo for Debian 11 and the installed jellyfin-ffmpeg and -ffprobe are version 5:
```
:# /usr/share/jellyfin-ffmpeg/ffprobe -version
ffprobe version 5.0.1-Jellyfin Copyright (c) 2007-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
```
I do not have the jellyfin-ffmpeg5 package installed.
I had to manually reinstall the jelyfin-ffmpeg using the specific version `apt install jellyfin-ffmpeg=4.4.1-4-bullseye`

Now it's correct:
```
:# /usr/share/jellyfin-ffmpeg/ffprobe -version
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
```

**Comment by Shadowghost** [comment]
Yeah we accidentially pushed the first ffmpeg5 build to the wrong repo and some people got the updated package.
