### ISSUE TITLE
[Issue]: missing analyzeduration and probesize configuration for ffprobe option

### ISSUE THREAD

**Issue by chaichunyang** [jellyfin/jellyfin#7685]
### Please describe your bug

missing `analyzeduration` and `probesize` configuration for ffprobe option. with no this two options, will cause `ffprobe` output wrong json format info, with some warning or error info. when The video file bitrate is very high
```
[matroska,webm @ 0x5635adcd22c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5635adcd22c0] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
``` 
this data format can not be parsed to json DATA, so cause `MediaEncoder.GetMediaInfo` Error. Looking for the code, this error maybe or so will happend in 10.8.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Arch linux
- Virtualization: No
- Clients: Kodi
- Browser: Chrome
- FFmpeg Version: n5.0
- Playback Method:
- Hardware Acceleration: No
- Plugins: Kodi, InfuseSync
- Reverse Proxy: No
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-04-30 19:56:43.740 +08:00] [INF] [50] Emby.Server.Implementations.IO.LibraryMonitor: "The.Hobbit.The.Battle.of.the.Five.Armies.2014.EXTENDED.2160p.UHD.BluRay.x265-SMAHAWUG" ("/share/main/video/movie/4k/The.Hobbit.The.Battle.of.the.Five.Armies.2014.EXTENDED.2160p.UHD.BluRay.x265-SMAHAWUG") will be refreshed.
[2022-04-30 19:56:44.266 +08:00] [ERR] [50] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.chapters[0].id | LineNumber: 732 | BytePositionInLine: 38.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken) in /build/jellyfin/src/jellyfin-10.7.7/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 437
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /build/jellyfin/src/jellyfin-10.7.7/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs:line 127
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /build/jellyfin/src/jellyfin-10.7.7/MediaBrowser.Providers/Manager/MetadataService.cs:line 765
```

### FFmpeg logs

```shell
ffprobe version n5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
{
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 9 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 10 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 12 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 13 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 14 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 15 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 16 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 17 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f592cde2c0] Could not find codec parameters for stream 18 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'The.Hobbit.An.Unexpected.Journey.2012.EXTENDED.2160p.UHD.BluRay.x265-SMAHAWUG.mkv':
  Metadata:
    encoder         : libebml v1.4.0 + libmatroska v1.6.2
  Duration: 03:02:29.44, start: 0.000000, bitrate: 34689 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 611.569000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 611.569000, end 848.347000
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 848.347000, end 1046.921000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 1046.921000, end 1124.290000
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 1124.290000, end 1396.270000
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 1396.270000, end 1679.136000
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 1679.136000, end 2164.537000
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 2164.537000, end 2476.933000
      Metadata:
        title           : Chapter 08
    Chapter #0:8: start 2476.933000, end 2790.496000
      Metadata:
        title           : Chapter 09
    Chapter #0:9: start 2790.496000, end 3183.847000
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 3183.847000, end 3487.317000
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 3487.317000, end 3594.966000
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 3594.966000, end 4242.071000
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 4242.071000, end 4501.497000
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 4501.497000, end 4732.478000
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 4732.478000, end 5096.591000
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 5096.591000, end 5434.095000
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 5434.095000, end 5650.270000
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 5650.270000, end 5844.130000
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 5844.130000, end 5943.146000
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 5943.146000, end 6100.469000
      Metadata:
        title           : Chapter 21
    Chapter #0:21: start 6100.469000, end 6622.199000
      Metadata:
        title           : Chapter 22
    Chapter #0:22: start 6622.199000, end 6779.439000
      Metadata:
        title           : Chapter 23
    Chapter #0:23: start 6779.439000, end 7146.014000
      Metadata:
        title           : Chapter 24
    Chapter #0:24: start 7146.014000, end 7437.180000
      Metadata:
        title           : Chapter 25
    Chapter #0:25: start 7437.180000, end 7791.242000
      Metadata:
        title           : Chapter 26
    Chapter #0:26: start 7791.242000, end 8601.092000
      Metadata:
        title           : Chapter 27
    Chapter #0:27: start 8601.092000, end 8718.543000
      Metadata:
        title           : Chapter 28
    Chapter #0:28: start 8718.543000, end 8790.865000
      Metadata:
        title           : Chapter 29
    Chapter #0:29: start 8790.865000, end 9052.585000
      Metadata:
        title           : Chapter 30
    Chapter #0:30: start 9052.585000, end 9180.213000
      Metadata:
        title           : Chapter 31
    Chapter #0:31: start 9180.213000, end 9352.260000
      Metadata:
        title           : Chapter 32
    Chapter #0:32: start 9352.260000, end 10010.876000
      Metadata:
        title           : Chapter 33
    Chapter #0:33: start 10010.876000, end 10341.039000
      Metadata:
        title           : Chapter 34
    Chapter #0:34: start 10341.039000, end 10949.440000
      Metadata:
        title           : Chapter 35
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1610 [SAR 1:1 DAR 384:161], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 30591086
      DURATION-eng    : 03:02:29.439000000
      NUMBER_OF_FRAMES-eng: 262524
      NUMBER_OF_BYTES-eng: 41869404088
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit) (default)
    Metadata:
      title           : Atmos 7.1
      BPS-eng         : 3402708
      DURATION-eng    : 03:02:29.439000000
      NUMBER_OF_FRAMES-eng: 13139327
      NUMBER_OF_BYTES-eng: 4657218004
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : AC-3 5.1
      BPS-eng         : 448000
      DURATION-eng    : 03:02:29.440000000
      NUMBER_OF_FRAMES-eng: 342170
      NUMBER_OF_BYTES-eng: 613168640
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : SDH
      BPS-eng         : 29547
      DURATION-eng    : 02:55:52.793000000
      NUMBER_OF_FRAMES-eng: 4950
      NUMBER_OF_BYTES-eng: 38975966
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(fre): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : French
      BPS-eng         : 21961
      DURATION-eng    : 03:01:32.841000000
      NUMBER_OF_FRAMES-eng: 4012
      NUMBER_OF_BYTES-eng: 29903308
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(spa): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Spanish
      BPS-eng         : 24419
      DURATION-eng    : 03:01:32.841000000
      NUMBER_OF_FRAMES-eng: 4196
      NUMBER_OF_BYTES-eng: 33249978
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(spa): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Spanish
      BPS-eng         : 25872
      DURATION-eng    : 03:01:32.841000000
      NUMBER_OF_FRAMES-eng: 4406
      NUMBER_OF_BYTES-eng: 35227983
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(ita): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Italian
      BPS-eng         : 27937
      DURATION-eng    : 03:01:32.882000000
      NUMBER_OF_FRAMES-eng: 4920
      NUMBER_OF_BYTES-eng: 38039854
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(dut): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Dutch
      BPS-eng         : 24057
      DURATION-eng    : 02:50:05.779000000
      NUMBER_OF_FRAMES-eng: 4164
      NUMBER_OF_BYTES-eng: 30690251
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(swe): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Swedish
      BPS-eng         : 23846
      DURATION-eng    : 03:01:22.914000000
      NUMBER_OF_FRAMES-eng: 4174
      NUMBER_OF_BYTES-eng: 32439479
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10(nor): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Norwegian
      BPS-eng         : 23305
      DURATION-eng    : 03:01:32.841000000
      NUMBER_OF_FRAMES-eng: 4292
      NUMBER_OF_BYTES-eng: 31733460
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:11(dan): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Danish
      BPS-eng         : 21432
      DURATION-eng    : 03:01:32.924000000
      NUMBER_OF_FRAMES-eng: 4116
      NUMBER_OF_BYTES-eng: 29182366
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:12(fin): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Finnish
      BPS-eng         : 21886
      DURATION-eng    : 03:01:32.882000000
      NUMBER_OF_FRAMES-eng: 4156
      NUMBER_OF_BYTES-eng: 29800469
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:13(cze): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Czech
      BPS-eng         : 23429
      DURATION-eng    : 03:00:55.678000000
      NUMBER_OF_FRAMES-eng: 4378
      NUMBER_OF_BYTES-eng: 31792591
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:14(pol): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Polish
      BPS-eng         : 21674
      DURATION-eng    : 03:01:22.914000000
      NUMBER_OF_FRAMES-eng: 4138
      NUMBER_OF_BYTES-eng: 29485308
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:15(jpn): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Japanese
      BPS-eng         : 20192
      DURATION-eng    : 02:55:52.918000000
      NUMBER_OF_FRAMES-eng: 3546
      NUMBER_OF_BYTES-eng: 26636102
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:16(chi): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Chinese
      BPS-eng         : 20962
      DURATION-eng    : 03:00:55.679000000
      NUMBER_OF_FRAMES-eng: 4350
      NUMBER_OF_BYTES-eng: 28444877
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:17(kor): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Korean
      BPS-eng         : 18339
      DURATION-eng    : 03:00:55.345000000
      NUMBER_OF_FRAMES-eng: 4366
      NUMBER_OF_BYTES-eng: 24885163
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:18(tha): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : Thai
      BPS-eng         : 23526
      DURATION-eng    : 03:01:32.841000000
      NUMBER_OF_FRAMES-eng: 4398
      NUMBER_OF_BYTES-eng: 32034460
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaichunyang** [comment]
arch linux `ffmpeg` is too new, use `jellyfin-ffmpeg` instead.
