### ISSUE TITLE
[Issue]: MarkPlayedItem rest api null pointer exception appVersion cannot be null

### ISSUE THREAD

**Issue by sejmann** [jellyfin/jellyfin#7694]
### Please describe your bug

When calling the REST API for MarkPlayedItem (in a way that worked fine in 10.7.7) it appears a null pointer exception regarding appVersion being null is thrown in some logging.

`curl -X POST "http://10.0.0.11:8096/Users/${userId}/PlayedItems/${itemId}?datePlayed=${datePlayed}" -H "X-Emby-Token: ${apiKey}" -d ""`

I tried adding appVersion as a URL param, to no avail. It seems this call now (inadvertently) requires a session be created first, although, it's not entirely clear to me how to do that. In any case, I'm assuming this wasn't intentional.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: MacOS 12.3.1 M1
- Virtualization: none (Rosetta emulating intel)
- Clients: curl
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: InfuseSync
- Reverse Proxy: N/A
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
2022-05-01 18:56:06.739 -07:00] [INF] [29] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://10.0.0.11:8096/Users/[REDACTED]/PlayedItems/d2dec153bd6b230e749a7180d515fd69?datePlayed=2022-05-01T02:06:44Z application/x-www-form-urlencoded 0
[2022-05-01 18:56:06.750 -07:00] [INF] [29] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint '"Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem (Jellyfin.Api)"'
[2022-05-01 18:56:06.751 -07:00] [INF] [29] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Route matched with "{action = \"MarkPlayedItem\", controller = \"Playstate\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[MediaBrowser.Model.Dto.UserItemDataDto]] MarkPlayedItem(System.Guid, System.Guid, System.Nullable`1[System.DateTime])" on controller "Jellyfin.Api.Controllers.PlaystateController" ("Jellyfin.Api").
[2022-05-01 18:56:06.760 -07:00] [INF] [29] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action "Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem (Jellyfin.Api)" in 8.4712ms
[2022-05-01 18:56:06.760 -07:00] [INF] [29] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '"Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem (Jellyfin.Api)"'
[2022-05-01 18:56:06.761 -07:00] [ERR] [29] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Users/[REDACTED]/PlayedItems/d2dec153bd6b230e749a7180d515fd69".
System.ArgumentNullException: Value cannot be null. (Parameter 'appVersion')
   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
   at Jellyfin.Api.Helpers.RequestHelpers.GetSession(ISessionManager sessionManager, IAuthorizationContext authContext, HttpRequest request)
   at Jellyfin.Api.Controllers.PlaystateController.MarkPlayedItem(Guid userId, Guid itemId, Nullable`1 datePlayed)
   at lambda_method371(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-05-01 18:56:06.763 -07:00] [INF] [29] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 POST http://10.0.0.11:8096/Users/[REDACTED]/PlayedItems/d2dec153bd6b230e749a7180d515fd69?datePlayed=2022-05-01T02:06:44Z application/x-www-form-urlencoded 0 - 400 - text/plain 26.7305ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orangetechllc** [comment]
I'm having this same issue running 10.8 with the watchstate program. I get the same error log.

https://github.com/ArabCoders/watchstate/
