### ISSUE TITLE
Playback Error when file name contains � (unknown/invalid character)

### ISSUE THREAD

**Issue by SethFalco** [jellyfin/jellyfin#7722]
For context, I used youtube-dl to just download entire channels/playlists from YouTube, and I guess for some of them got saved with bad file names. 🤔 

Some of the songs ended up with special characters replaced with `�` which results in my file manager (Nautilus) displaying `(Invalid encoding)` after the name of the file.

The issue is immediately fixed by removing the `�`.
The root cause is not in Jellyfin, but I was wondering if Jellyfin could handle this situation more gracefully?

**Media Info of the file**

**Logs**

```log
file:/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3: No such file or directory
[13:15:55] [ERR] [283] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[13:15:55] [INF] [283] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for seth. EnableAudioPlaybackTranscoding: True
[13:15:55] [INF] [283] Jellyfin.Api.Helpers.MediaInfoHelper: Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[13:15:55] [INF] [283] Jellyfin.Api.Helpers.MediaInfoHelper: Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[13:15:55] [INF] [283] Jellyfin.Api.Helpers.MediaInfoHelper: Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[13:15:55] [ERR] [168] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3'. URL GET /Audio/6aed4a6c2c43ec0539d82f49cb1f0646/stream.mp3.
[13:15:55] [INF] [52] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: {"Name": "Jellyfin Media Player", "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 1280000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 5, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Photo", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": null, "Type": "Audio", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "ts", "Type": "Video", "VideoCodec": "h264,h265,hevc,mpeg4,mpeg2video", "AudioCodec": "aac,mp3,ac3,opus,flac,vorbis", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "jpeg", "Type": "Photo", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [{"Format": "srt", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "srt", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgssub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "dvdsub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgs", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}], "$type": "DeviceProfile"}
file:/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3: No such file or directory
[13:15:55] [ERR] [21] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[13:15:55] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for seth. EnableAudioPlaybackTranscoding: True
[13:15:55] [INF] [188] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3" -threads 0 -vn  -id3v2_version 3 -write_id3v1 1 -y "/config/transcodes/575dae681cac2ce9448c2d5c9a240005"
[13:15:55] [ERR] [146] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[13:15:55] [ERR] [188] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/transcodes/575dae681cac2ce9448c2d5c9a240005'. URL GET /audio/6aed4a6c-2c43-ec05-39d8-2f49cb1f0646/stream.
[13:15:55] [INF] [119] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: {"Name": "Jellyfin Media Player", "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 1280000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 5, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Photo", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": null, "Type": "Audio", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "ts", "Type": "Video", "VideoCodec": "h264,h265,hevc,mpeg4,mpeg2video", "AudioCodec": "aac,mp3,ac3,opus,flac,vorbis", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "jpeg", "Type": "Photo", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [{"Format": "srt", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "srt", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgssub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "dvdsub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgs", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}], "$type": "DeviceProfile"}
file:/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3: No such file or directory
[13:15:55] [ERR] [146] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[13:15:55] [INF] [146] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for seth. EnableAudioPlaybackTranscoding: True
[13:15:55] [INF] [119] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) /config/transcodes/575dae681cac2ce9448c2d5c9a240005
[13:15:55] [INF] [188] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/Music/mrsuicidesheep/skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix.mp3" -threads 0 -vn  -id3v2_version 3 -write_id3v1 1 -y "/config/transcodes/5d41c2b238218c934793d3d3bb5b8e94"
[13:15:55] [ERR] [119] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[13:15:55] [ERR] [119] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/transcodes/5d41c2b238218c934793d3d3bb5b8e94'. URL GET /audio/6aed4a6c-2c43-ec05-39d8-2f49cb1f0646/stream.
[13:15:55] [INF] [220] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) /config/transcodes/5d41c2b238218c934793d3d3bb5b8e94
[13:15:56] [INF] [220] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Media Player 1.6.1 playing skrillex-&-diplo-where-are-�-now-feat-justin-bieber-mr-fijiwiji-remix. Stopped at 0 ms
[13:15:57] [WRN] [220] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://0.0.0.0:8096/Sessions/Playing/Stopped to 172.18.0.1 in 0:00:01.5766116 with Status Code 204
```

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.7.7
 - Hardware settings & device: Tbh… now sure how to check this.
 - Reverse proxy: no
 - Other hardware notes: Media on file system and mounted via a Docker volume.
 
**Client System (please complete the following information):**
 - Device: Laptop
 - OS: Linux (Debian 11)
 - Client: Jellyfin Media Player via Flatpak
 - Browser (if Web client): N/A
 - Client and Browser Version: 1.6.1

![image](https://user-images.githubusercontent.com/22801583/167298058-4ac4068e-7a78-4afa-9901-915f51fc9ed7.png)

---

Even choosing not to load/display them in the library would be great, so it doesn't stop the music during a playlist.

**Comment by SethFalco** [comment]
Seems I'm unable to reproduce this anymore, closing the ticket.
