### ISSUE TITLE
Movie Library scan deletes movie-poster creates folder.jpg and uses -cover for poster cards

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#7740]
### Please describe your bug

Recently jumped from 10.7 stable to 10.8.0 beta 2 and created a test library. The files are JAV type in the format of ID.mp4 or ID.mkv.

Folder format is generally multiple movies in a actresses folder with each movie with the following files:

![image](https://user-images.githubusercontent.com/9695713/167962411-7f6911cd-70cc-4f30-b14b-e459ee74f44d.png)

Upon scanning the movie type library to read the nfo file, Jellyfin proceeds to delete the -poster.jpg file (destructive), creates a folder.jpg file from the -cover.jpg file.

This results in some awkward postercards:

![image](https://user-images.githubusercontent.com/9695713/167962541-ae3f03bf-b245-492f-94e6-f76522a6a69c.png)

Some logs of it deleting:

![image](https://user-images.githubusercontent.com/9695713/167962722-a9622d4c-c23a-4a98-bb1d-922719ea5d47.png)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10 Enterprise
- Virtualization: No
- Clients: Jellyfin Media Player, IOS
- Browser: Chrome
- FFmpeg Version: Latest 4.x version from jellyfin repository
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
(s) and 0 seconds
15:55:10] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
15:55:44] [ERR] [43] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of
the path 'C:\Windows\system32\null'. URL GET /Environment/DirectoryContents.
15:55:51] [ERR] [43] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of
the path 'C:\Windows\system32\null'. URL GET /Environment/DirectoryContents.
15:55:58] [ERR] [31] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The filename, directory
ame, or volume label syntax is incorrect. : 'C:\Windows\system32\"G:\"'. URL GET /Environment/DirectoryContents.
15:56:04] [ERR] [31] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The filename, directory
ame, or volume label syntax is incorrect. : 'C:\Windows\system32\"G:\"'. URL GET /Environment/DirectoryContents.
15:57:02] [INF] [74] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task RefreshMediaLibraryTask
15:57:02] [INF] [74] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
15:57:02] [INF] [74] Emby.Server.Implementations.Library.LibraryManager: Validating media library
15:57:02] [INF] [46] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image G:\(( NFC\(( Archive\__ Fi
\1 Process\Ai Sayama\MIMK-062-poster.jpg
15:57:02] [INF] [74] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image G:\(( NFC\(( Archive\__ Fi
\1 Process\Ai Sena\PRED-383-poster.jpg
15:57:02] [ERR] [46] MediaBrowser.Providers.Manager.ProviderManager: TmdbMovieImageProvider failed in GetImageInfos for
type Movie at G:\(( NFC\(( Archive\__ Fix\1 Process\Ai Sayama\MIMK-062.mp4
ystem.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
  at System.Convert.ToInt32(String value, IFormatProvider provider)
  at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieImageProvider.GetImages(BaseItem item, CancellationToken cance
lationToken)
  at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String pref
rredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
15:57:02] [ERR] [74] MediaBrowser.Providers.Manager.ProviderManager: TmdbMovieImageProvider failed in GetImageInfos for
type Movie at G:\(( NFC\(( Archive\__ Fix\1 Process\Ai Sena\PRED-383.mp4
ystem.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
Just wanted to add an update. I switched back to 10.7.7 and it recognizes the movie-poster.jpg file doesn't create a metadata folder and doesn't create a random folder.jpg. I'm assuming 10.7.7 recognized -poster.jpg and since 10.8.0beta1 and 2 no longer recognizes it, it looks in the folder for a cover and creates a postercard jpg to use for the library.

10.7.7
![image](https://user-images.githubusercontent.com/9695713/167964397-9303c09d-2d4b-4b66-b4a0-8e132bc08d20.png)

**Comment by gummykage** [comment]
Please note this problem would cause huge headaches for people with incredibly large libraries as it goes and start deleting files it deems not necessary.

**Comment by gummykage** [comment]
<details>
<summary>nsfw</summary>
![image](https://user-images.githubusercontent.com/9695713/169428917-6bbb05d6-afd3-461c-baaf-81352e6b8fe1.png)
</details>

In Beta3 this issue continues, <filename>-poster.jpg is deleted and cover.jpg is renamed to folder.jpg. As a result weird full bluray covers are cropped oddly and used as postercards.

**Comment by gummykage** [comment]
![image](https://user-images.githubusercontent.com/9695713/169429197-94a83b54-abc7-4c12-893e-6793784d2f71.png)

**Comment by cvium** [comment]
I believe this is related to #7836
