### ISSUE TITLE
[Issue][10.8.0 beta3]: New shows are not showing on lastest Tv Shows area

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin#7754]
### Please describe your bug

New episodes are fine but new tv shows are not added to the database 

### Jellyfin Version

10.8.0

### if other:

Beta3

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization:none
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: AudioDB10.8.0.0
Status: Active
Fanart9.0.0.0
Status: Active
MusicBrainz10.8.0.0
Status: Active
OMDb10.8.0.0
Status: Active
Playback Reporting12.0.0.0
Status: Active
Reports14.0.0.0
Status: Active
SkinManager1.4.0.0
Status: Active
Studio Images10.8.0.0
Status: Active
TMDb10.8.0.0
Status: Active
TV Maze5.0.0.0
Status: Active
TheTVDB8.0.0.0
Status: Active
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-05-16 17:34:32.019 +10:00] [ERR] Error in "The Open Movie Database"
System.Text.Json.JsonException: 'L' is invalid after a value. Expected either ',', '}', or ']'. Path: $.Episodes[5] | LineNumber: 0 | BytePositionInLine: 3660.
 ---> System.Text.Json.JsonReaderException: 'L' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | BytePositionInLine: 3660.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetSeasonRootObject(String imdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)


[2022-05-16 17:34:32.019 +10:00] [ERR] Error in "The Open Movie Database"
System.Text.Json.JsonException: 'L' is invalid after a value. Expected either ',', '}', or ']'. Path: $.Episodes[5] | LineNumber: 0 | BytePositionInLine: 3660.
 ---> System.Text.Json.JsonReaderException: 'L' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | BytePositionInLine: 3660.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetSeasonRootObject(String imdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourpatched** [comment]
Is this normal? 

[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.638 +10:00] [WRN] The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.639 +10:00] [WRN] The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.639 +10:00] [WRN] The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.639 +10:00] [WRN] The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-05-16 19:16:36.639 +10:00] [WRN] The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
