### ISSUE TITLE
[Issue]: Jellyfin (nightly) opening tens of thousands of files, reaching the ulimit and crashing services

### ISSUE THREAD

**Issue by HStep20** [jellyfin/jellyfin#7800]
### Please describe your bug

I run jellyfin in docker on Unraid, with the LinuxServer container on the Nightly branch. 

Starting on 5/24/2022, services on my server started crashing with a 'too many open files' error. A short investigation later, and it turned out to be Jellyfin opening tens of thousands of files at once, and holding onto them in an open state. After checking the logs, I noticed a repeating error for SkiaSharp.SKObject:

```
[2022-05-25 19:10:38.392 -07:00] [ERR] [43] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/config/data/metadata/library/f2/f2f8ddd71a701459e63399bbbc1759f1/poster.jpg"
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.3) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

It could be related, or not, but Im under the assumption it is, since its doing the same for all of the posters/images. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Unraid
- Virtualization: Docker
- Clients: Web
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: VAAPI
- Plugins:
"Merge Versions" "10.8.0.1"
"Playback Reporting" "12.0.0.0"
"Reports" "14.0.0.0"
"Theme Songs" "10.8.0.1"
"TheTVDB" "8.0.0.0"
"Trakt" "18.0.0.0"
"YoutubeMetadata" "1.0.3.5"
"TMDb" "10.8.0.0"
"Studio Images" "10.8.0.0"
"OMDb" "10.8.0.0"
"MusicBrainz" "10.8.0.0"
"AudioDB" "10.8.0.0"
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
I can provide a complete log file on request, but its basically filled with errors surrounding the SkiaSharp.SKObject

Blur Hash:

[2022-05-25 19:10:38.392 -07:00] [ERR] [43] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/config/data/metadata/library/f2/f2f8ddd71a701459e63399bbbc1759f1/poster.jpg"
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.3) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

Image Dimensions:
```
[2022-05-25 11:38:07.305 -07:00] [ERR] [60] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/media/Movies/Requested Movies/Harry Potter and the Deathly Hallows - Part 1 (2010)/logo.png"
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.3) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Spiritreader** [comment]
I'm so glad I came here to check out if my "too many open files" issue was related to Jellyfin.
Sadly it murdered multiple databases I was running on my server as my fuse got unmounted due to this.
I've been spending the last 2 days restoring databases from backup only to have my system drop out again.
Thank you for posting this!

Anyway to get back on topic:

I am getting the same errors
```
[2022-05-27 03:16:30.704 +02:00] [ERR] [23] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/tv/XYZ-thumb.jpg"
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.3) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```


```
[2022-05-27 03:50:07.557 +02:00] [ERR] [35] Emby.Server.Implementations.Dto.DtoService: Failed to determine primary image aspect ratio for "/config/metadata/library/e6/e647bb2a9f069d374c8bf3e272ca466a/poster.jpg"
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.3) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStream..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamRewindable..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamSeekable..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKStreamAsset..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at SkiaSharp.SKCodec.Create(String filename, SKCodecResult& result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
```

This appears tens of thousands of times for each thumbnail until something gives in eventually

**Comment by Spiritreader** [comment]
I think 
https://github.com/jellyfin/jellyfin/commit/714fd7d0a6a588f029da65734565cb539dda068b this dependabot auto-update of the SkiaSharp package might have something to do with it.
It was updated to 88, but the library seemingly wasn't.

**Comment by crobibero** [comment]
Sometimes dependency updates are hard :)

Glad this is fixed
