### ISSUE TITLE
[Issue]: failure when loading gzipped XMLTV file

### ISSUE THREAD

**Issue by bruor** [jellyfin/jellyfin#7822]
### Please describe your bug

When attempting to use the following EPG file: https://github.com/Apollo2000/TVGuide/raw/master/utc.lite.xml.gz
Errors are thrown in the log that are not present if I manually gunzip the file and import the resulting XML from disk.

If I try to inspect the content of the xml file in the below snippet
`/var/cache/jellyfin/xmltv/b6c9020f7f08482fab44fcd853b10f1c.xml`
the file exists on disk but it appears to be gzipped still

I cut the log output off, but this error and its associated stack trace repeat over and over again until the refresh task is cancelled. 
`[2022-05-29 21:03:45.236 -04:00] [ERR] Error extracting from gz file`

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22.04
- Virtualization: NO
- Clients: n/a
- Browser: Chrome 101
- FFmpeg Version: 4.4.1-Jellyfin
- Playback Method: n/a
- Hardware Acceleration: QSV
- Plugins: n/a
- Reverse Proxy: NO
- Networking: Wired 1gbps
- Storage: local SSD
```

### Jellyfin logs

```shell
[2022-05-29 21:03:44.371 -04:00] [INF] Found epg channel in "XmlTV" null "CBC Toronto" "cbc.cblt.toronto.on.ca"
[2022-05-29 21:03:44.371 -04:00] [INF] Found epg channel in "XmlTV" null "MLB Detroit Tigers" "mlb.teams.det.us"
[2022-05-29 21:03:44.371 -04:00] [INF] Found epg channel in "XmlTV" null "Real Time" "real.time.ze"
[2022-05-29 21:03:44.371 -04:00] [INF] Found epg channel in "XmlTV" null "FOX (WTVT) Tampa Bay FL" "fox.wtvt.tampa.bay.fl.us"
[2022-05-29 21:03:44.371 -04:00] [INF] Found epg channel in "XmlTV" null "Bally Sports Cincinnati US" "fox.sports.ohio.cincinnati.2.us"
[2022-05-29 21:03:44.415 -04:00] [INF] Refreshing guide with 7 days of guide data
[2022-05-29 21:03:44.421 -04:00] [INF] xmltv path: "https://github.com/Apollo2000/TVGuide/raw/master/utc.lite.xml.gz"
[2022-05-29 21:03:44.441 -04:00] [ERR] Error extracting from gz file "/var/cache/jellyfin/xmltv/b6c9020f7f08482fab44fcd853b10f1c.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(ReadOnlySpan`1 originalUrl, String file)
[2022-05-29 21:03:45.218 -04:00] [INF] xmltv path: "https://github.com/Apollo2000/TVGuide/raw/master/utc.lite.xml.gz"
[2022-05-29 21:03:45.236 -04:00] [ERR] Error extracting from gz file "/var/cache/jellyfin/xmltv/b6c9020f7f08482fab44fcd853b10f1c.xml"
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Emby.Server.Implementations.Archiving.ZipClient.ExtractAllFromGz(Stream source, String targetPath, Boolean overwriteExistingFiles)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.ExtractGz(String file)
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.UnzipIfNeeded(ReadOnlySpan`1 originalUrl, String file)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zehnerGIT** [comment]
What's your exact server version?

There are many PRs in 10.8 Beta3 that change the handling of gzipped xmltv files, so be sure, that you have installed the latest version, e.g.
https://github.com/jellyfin/jellyfin/pull/7567
https://github.com/jellyfin/jellyfin/pull/7592

**Comment by bruor** [comment]
This was happening on this version  20220517.13-unstable

**Comment by bonswouar** [comment]
Same error on `10.8.4`, although channels are still recognized.
@zehnerGIT The PRs you linked are effectively in that version

I dug a bit into the files, and found out that although it doesn't work for [ExtractAllFromGz](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs#L145), it does work for [ExtractFirstFileFromGz](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs#L132), which is executed after (**_I wonder why we need both by the way, and even more why the "extract only the first file" comes after?_**).
I effectively have my `/cache/temp/` populated with hash folders containing the first _(and luckily for me, the only)_ XMLs uncompressed files as `data.xml`.

@bruor Looking at the code, even if it's a bit weird, it seems normal that files in `/cache/xmltv/` are still compressed though:
`gz` extension is deduced from the original path ([code](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs#L104)), while the cache file itself has a static `.xml` extension ([code](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs#L75))

Seeing that the error seems to be `stream.Key` being `null`, and that `ExtractAllFromGz` and `ExtractFirstFileFromGz` are almost identical, I really have no clue what could be the problem. Maybe Stream is not available yet? Or it has something to do with `stream.Position = 0;`?
But I don't know C# at all, @crobibero @cvium as you're the last ones who commited on that you might have some better guess?
