### ISSUE TITLE
No Artists and Genres after scanning music library

### ISSUE THREAD

**Issue by drieslamberechts** [jellyfin/jellyfin#7837]
I have created a new music library in Jellyfin (version 10.7.7, Linux x64) and I enabled all metadata scanning. 
Scanning has definitely been completed but the software does not seem to recognize artists and genres for some reason.
An example of my folder structure:

```
Root
| - Artist
    | - 2022 - Album
        | - 01 SongName.mp3
        | - 02 SongName2.mp3
        | - ...
| - Artist 2
....
```

If I understand the documentation correctly this would be best for parsing.
- All available downloaders are enabled in the Library settings
- AudioDB and MusicBrainz plugin status is Active (this was by default and I kept the initial settings)

**Comment by Maxplosion** [comment]
did you check your file metadata with a tagging tool? maybe there is an issue in that.
also and that is just from the top of my head so I might be wrong, but try moving the year like so AwesomeAlbum(2022).

**Comment by extremelyonline** [comment]
Having the same problem on docker on the latest version. The metadata used to read fine, but lately the artist. album cover, and genre are all empty. I followed the folder structure and checked that the files' metadata are correct...

**Comment by extremelyonline** [comment]
I'm getting the following error:

```
 [ERR] [14] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe

System.InvalidOperationException: Cannot start process because a file name has not been provided.

   at System.Diagnostics.Process.Start()

   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)

   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)

   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)

   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)

   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

[01:51:24] [ERR] [14] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
```
