### ISSUE TITLE
[Issue][10.8.0 Beta3]: Episodes with 'trailer' in their name are not scrapped or displayed

### ISSUE THREAD

**Issue by texneus** [jellyfin/jellyfin#7851]
### Please describe your bug

I have a valid show where no specials are indexed by the usual sites (TV Maze, TVDB, TMDB, OMDB).  Regardless, there are several specials available that I wish to index in Jellyfin.  Since there are no official specials, I gave all specials an episode number so they sequence correctly when displayed in Jellyfin.  Jellyfin is set to save NFO and epsiode images upon scraping.  It is also set to generate images from the video when no other images exist.

Directory structure of example show "X" prior to scraping:
![image](https://user-images.githubusercontent.com/23441049/172083283-53889905-e605-49cd-ac2c-afe99b74e231.png)

After scraping:
![image](https://user-images.githubusercontent.com/23441049/172083629-6d2b74d7-31a8-40b5-aa90-d91c22043b52.png)

Note the three files ending with the word 'trailer' do not have an NFO or episode image created, where-as all the others do.

Affected specials **are not** displayed in Jellyfin:
![image](https://user-images.githubusercontent.com/23441049/172085410-30996ec1-ba3d-4439-8491-6f37d2e0ca61.png)

### Jellyfin Version

10.8.0

### if other:

Beta 3

### Environment

```markdown
- OS: MX Linux 19.4
- Virtualization: none
- Clients: web browser
- Browser: Firefox 91.10.0esr
- FFmpeg Version: jellyfin-ffmpeg_4.4.1-4
- Playback Method: n/a
- Hardware Acceleration: none
- Plugins: AudioDV, Fanart, IMVDb, MusicBrainz, OMDb, Studio Images, TMDb, TMDb Boxsets, TVMaz, TheTVDB
- Reverse Proxy: none
- Base URL: http://127.0.0.1:8096
- Networking: local
- Storage: local
```

### Jellyfin logs

```shell
"TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/223/559165.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/8/21446.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/223/559166.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }]
[2022-06-05 21:12:54.597 -05:00] [INF] [10] Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonImageProvider: [GetImages] Images found for "Specials": []
[2022-06-05 21:12:55.701 -05:00] [WRN] [19] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadataInternal(EpisodeInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2022-06-05 21:12:55.870 -05:00] [ERR] [13] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:7]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2022-06-05 21:12:55.880 -05:00] [WRN] [13] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider: [GetImages]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:56.035 -05:00] [ERR] [13] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "252322"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:7]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:56.375 -05:00] [WRN] [11] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadataInternal(EpisodeInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2022-06-05 21:12:56.513 -05:00] [ERR] [11] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:90]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2022-06-05 21:12:56.514 -05:00] [WRN] [11] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider: [GetImages]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:56.621 -05:00] [ERR] [11] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "252322"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:90]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:56.812 -05:00] [WRN] [15] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadataInternal(EpisodeInfo info)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2022-06-05 21:12:57.004 -05:00] [ERR] [13] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:23]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2022-06-05 21:12:57.005 -05:00] [WRN] [13] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider: [GetImages]
System.ArgumentException: season
   at TvMaze.Api.Client.Endpoints.Shows.ShowsEndpoint.GetEpisodeByNumberAsync(Int32 showId, Int32 season, Int32 episodeNumber)
   at Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:57.155 -05:00] [ERR] [13] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "252322"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:0 EpisodeNumber:23]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2022-06-05 21:12:58.663 -05:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 9 seconds
```

### Please attach any screenshots here

Settings for episode images:
![image](https://user-images.githubusercontent.com/23441049/172086054-6f2953a4-df68-4119-b98c-54ecb9b9f116.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by texneus** [comment]
More info:  I have confirmed episodes with the the word trailer in the filename are ignored by 10.8.0 even if metadata exists (i.e. manually created or scrapped with 10.7.7).  If not corrected, this will make all existing trailer episodes disappear when people upgrade.
