### ISSUE TITLE
[Issue]: [10.8.0] MovieMetadataService: Error in "ffprobe" System.Text.Json.JsonException: Expected depth to be zero at the end of the JSON payload.

### ISSUE THREAD

**Issue by ArabCoders** [jellyfin/jellyfin#7888]
### Please describe your bug

After upgrading to 10.8.x and adding NFO files back to movies folder. whenever a scan is performed for the movie library it's fails with the given error. Note this does not happen for tv shows library just movies.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker (linuxserver/jellyfin:latest)
- Clients: Browser and iOS
- Browser: Chrome 102
- FFmpeg Version: ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
- Playback Method: direct play
- Hardware Acceleration: VAAPI
- Plugins: audiodb, bookshelf, cover art archive, fanart, musicbrianz, OMDb, Playback reporting, Repots, Studio Images, TMDb, TVmaze, TheTVDB, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: NAT
- Storage: local
```

### Jellyfin logs

```shell
[2022-06-12 07:53:40.001 +03:00] [ERR] [30] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Bo
olean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Bo
olean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellat
ionToken)
```

### FFmpeg logs

```shell
None avaliable.
```

### Please attach any browser or client logs here

None avaliable.

### Please attach any screenshots here

Not applicable 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
It looks like you might have a movie with broken metadata?
Would you be able to narrow down which file(s) are erroring?

**Comment by ArabCoders** [comment]
@crobibero  Indeed, i managed to enable debug logging and by doing that i was able to narrow it down here is my findings

```log
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [17:18:13] [DBG] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Running FFProbeProvider for /storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [17:18:13] [DBG] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: /usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 200M -i file:"/storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [17:18:13] [DBG] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args -analyzeduration 200M -i file:"/storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [dvdsub @ 0x55eedc6cc200] [IMGUTILS @ 0x7ffc111dcb80] Picture size 0x0 is invalid
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [matroska,webm @ 0x55eedc6b5a80] Failed to open codec in avformat_find_stream_info
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [dvdsub @ 0x55eedc6cc200] [IMGUTILS @ 0x7ffc111dca90] Picture size 0x0 is invalid
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [dvdsub @ 0x55eedd1fac80] [IMGUTILS @ 0x7ffc111dcda0] Picture size 0x0 is invalid
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | Could not open codec for input stream 4
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | [17:18:13] [ERR] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    | System.Text.Json.JsonException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |  ---> System.Text.Json.JsonReaderException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 1 | BytePositionInLine: 0.
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Utf8JsonReader.Read()
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    --- End of inner exception stack trace ---
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
Jun 12 14:18:13 docker_host docker-compose[1424214]: jellyfin    |    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

running the exact command on cli fails with 

```log
root@8c0028a8247c:~# /usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 200M -i file:"/storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
{
[dvdsub @ 0x564a627b4140] [IMGUTILS @ 0x7ffdadb53040] Picture size 0x0 is invalid
[matroska,webm @ 0x564a6279dac0] Failed to open codec in avformat_find_stream_info
[dvdsub @ 0x564a627b4140] [IMGUTILS @ 0x7ffdadb52f50] Picture size 0x0 is invalid
[dvdsub @ 0x564a632e2940] [IMGUTILS @ 0x7ffdadb53260] Picture size 0x0 is invalid
Could not open codec for input stream 4
```

running normal ffprobe produce these results.

```log

root@8c0028a8247c:~# /usr/lib/jellyfin-ffmpeg/ffprobe '/storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv'
ffprobe version 5.0.1-Jellyfin Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3 --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[dvdsub @ 0x55903a1fb0c0] [IMGUTILS @ 0x7fffc129d060] Picture size 0x0 is invalid
[matroska,webm @ 0x55903a1e4980] Failed to open codec in avformat_find_stream_info
[dvdsub @ 0x55903a1fb0c0] [IMGUTILS @ 0x7fffc129cf70] Picture size 0x0 is invalid
Input #0, matroska,webm, from '/storage/media/movies/Movie Title (2016)/Movie Title (2016) [Bluray-1080p] [EN+KO] [x265 AC3 10bit].mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-08-19T16:39:02.000000Z
  Duration: 01:58:08.16, start: 0.000000, bitrate: 6842 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 662.536875
      Metadata:
        title           : Chapitre 01
    Chapter #0:1: start 662.536875, end 1175.215708
      Metadata:
        title           : Chapitre 02
    Chapter #0:2: start 1175.215708, end 1778.318208
      Metadata:
        title           : Chapitre 03
    Chapter #0:3: start 1778.318208, end 2353.142458
      Metadata:
        title           : Chapitre 04
    Chapter #0:4: start 2353.142458, end 3061.850458
      Metadata:
        title           : Chapitre 05
    Chapter #0:5: start 3061.850458, end 3570.024792
      Metadata:
        title           : Chapitre 06
    Chapter #0:6: start 3570.024792, end 4095.091000
      Metadata:
        title           : Chapitre 07
    Chapter #0:7: start 4095.091000, end 4856.059542
      Metadata:
        title           : Chapitre 08
    Chapter #0:8: start 4856.059542, end 5398.267875
      Metadata:
        title           : Chapitre 09
    Chapter #0:9: start 5398.267875, end 5883.460917
      Metadata:
        title           : Chapitre 10
    Chapter #0:10: start 5883.460917, end 6547.207333
      Metadata:
        title           : Chapitre 11
    Chapter #0:11: start 6547.207333, end 7088.081000
      Metadata:
        title           : Chapitre 12
    Chapter #0:12: start 6547.248000, end 7088.160000
      Metadata:
        title           : Chapter 12
  Stream #0:0(kor): Video: hevc (Main 10), yuv420p10le(tv), 1920x1042, SAR 1:1 DAR 960:521, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 5557201
      DURATION        : 01:58:08.081000000
      NUMBER_OF_FRAMES: 169944
      NUMBER_OF_BYTES : 4923736506
      _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-08-19 16:39:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      BPS             : 640000
      DURATION        : 01:58:08.160000000
      NUMBER_OF_FRAMES: 221505
      NUMBER_OF_BYTES : 567052800
      _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-08-19 16:39:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(kor): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      BPS             : 640000
      DURATION        : 01:58:08.096000000
      NUMBER_OF_FRAMES: 221503
      NUMBER_OF_BYTES : 567047680
      _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-08-19 16:39:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip (default) (forced)
    Metadata:
      BPS             : 22
      DURATION        : 01:52:28.999000000
      NUMBER_OF_FRAMES: 852
      NUMBER_OF_BYTES : 18723
      _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-08-19 16:39:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: dvd_subtitle (default)
    Metadata:
      BPS             : 3825
      DURATION        : 01:54:02.795000000
      NUMBER_OF_FRAMES: 1726
      NUMBER_OF_BYTES : 3272450
      _STATISTICS_WRITING_APP: mkvmerge v60.0.0 ('Are We Copies?') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-08-19 16:39:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5: Video: png, rgba(pc), 640x360, 90k tbr, 90k tbn (attached pic)
    Metadata:
      filename        : cover.png
      mimetype        : image/png
[dvdsub @ 0x55903a230bc0] [IMGUTILS @ 0x7fffc129d280] Picture size 0x0 is invalid
Could not open codec for input stream 4

root@8c0028a8247c:~#
```

**Comment by crobibero** [comment]
Looking at the ffprobe output I would say it's an issue with the media, not an issue with Jellyfin

**Comment by ArabCoders** [comment]
Oh, i think so too, i replaced the file and the library scan is working now. However, I honestly do not think a broken file should be able to break the scanner. and you cant really tell which file is doing it unless you know how to turn on debug logging which is not easily accessible via UI

**Comment by crobibero** [comment]
Ah I didn't realize that this was stopping the scanner - that's a good call. I will see how easy it is to fix

**Comment by crobibero** [comment]
Can you please provide a non-truncated log so I can see what happens before and after?

**Comment by ArabCoders** [comment]
Sorry i deleted the file. I will update this post if i manage to find it again.

**Comment by ArabCoders** [comment]
@crobibero hello, sorry i am unable to find the source file. I'll go ahead and close the issue, and if i encounter it again I'll post back.

**Comment by adamsocrat** [comment]
This also happens when ffprobe hits the max memory (so it runs out of memory)

**Comment by Maltavius** [comment]
Does this help?
It's present on 12.1 also.

```
[2026-09-16 13:55:25.682 +02:00] [INF] Validating media library
[2026-09-16 13:55:36.431 +02:00] [INF] ffmpeg subtitle extraction completed for "file:\"/media/Kids TV/Batman The Animated Series/Season01/Batman The Animated Series - S01E39 - Heart of Steel (1).1080p.mkv\"" to "/var/lib/jellyfin/data/subtitles/f6/f6372d31-c11a-0afa-d4b0-f29aab8401e7/2.srt"
[2026-09-16 13:55:36.433 +02:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-nostdin -y -i file:\"/media/Kids TV/Marvel's Spidey and His Amazing Friends/Season01/Marvels.Spidey.and.His.Amazing.Friends.S01E39E40.The.Wozzlesnook.-.Superhero.Switcheroo.1080p.HULU.WEB-DL.DDP5.1.H.264-LAZY.mkv\" -map 0:2 -an -vn -c:s copy -flush_packets 1 \"/var/lib/jellyfin/data/subtitles/53/53db42e9-e0dd-c63b-f1c1-e6f2a618c6d9/2.srt\""
[2026-09-16 13:55:45.432 +02:00] [INF] ffmpeg subtitle extraction completed for "file:\"/media/Kids TV/Marvel's Spidey and His Amazing Friends/Season01/Marvels.Spidey.and.His.Amazing.Friends.S01E39E40.The.Wozzlesnook.-.Superhero.Switcheroo.1080p.HULU.WEB-DL.DDP5.1.H.264-LAZY.mkv\"" to "/var/lib/jellyfin/data/subtitles/53/53db42e9-e0dd-c63b-f1c1-e6f2a618c6d9/2.srt"
[2026-09-16 13:55:45.434 +02:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-nostdin -y -i file:\"/media/Kids TV/Batman The Animated Series/Season01/Batman The Animated Series - S01E40 - Heart of Steel (2).1080p.mkv\" -map 0:2 -an -vn -c:s copy -flush_packets 1 \"/var/lib/jellyfin/data/subtitles/67/67df159b-e1cd-29c0-5236-5f6a88577a1c/2.srt\""
[2026-09-16 13:56:04.798 +02:00] [ERR] Error in "Probe Provider" for "/media/Swedish/Barnfilm/2010-2019/Hitta Doris (2016)/Hitta Doris (2016) - [1080p] [h264] [DTS].mkv"
System.Text.Json.JsonException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync[TReadBufferState,TStream](TStream utf8Json, TReadBufferState bufferState, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2026-09-16 13:56:04.839 +02:00] [WRN] Primary image for "Kaitlin Olson" (ffca1d5e-7818-1b79-1e4d-0f9362c5f6fd) not found at ""/config/metadata/People/K/Kaitlin Olson/folder.jpg"", source was "/config/metadata/People/K/Kaitlin Olson/folder.jpg"
[2026-09-16 13:56:04.847 +02:00] [WRN] Primary image for "Katherine Ringgold" (4b036dca-b7cd-ff2e-1d27-776a708abe07) not found at ""/config/metadata/People/K/Katherine Ringgold/folder.jpg"", source was "/config/metadata/People/K/Katherine Ringgold/folder.jpg"
[2026-09-16 13:56:04.861 +02:00] [WRN] Primary image for "Aaron Hendry" (8e3d1661-81e8-8e13-a960-b84bdc929a97) not found at ""/config/metadata/People/A/Aaron Hendry/folder.jpg"", source was "/config/metadata/People/A/Aaron Hendry/folder.jpg"
[2026-09-16 13:56:04.864 +02:00] [WRN] Primary image for "Andy Hirsch" (a911a88f-465b-f37d-18d7-7d7a0ce8f61f) not found at ""/config/metadata/People/A/Andy Hirsch/folder.jpg"", source was "/config/metadata/People/A/Andy Hirsch/folder.jpg"
```

**Comment by arabcoders** [comment]
not sure if it related, anyway i kindof went different why by literally replacing ffprobe with custom version https://github.com/arabcoders/ffprobe_cacher

1- i no longer hear the fan scream.
2- i no longer see the log spam.

The `ffprobe_cacher` serve dual purpose, hiding the unknown stream errors from view, and cache ffprobe calls so repeated call has no resource usage beyond opening the cache file and reading it.
