### ISSUE TITLE
[Issue]: CBR files don't always play within Jellyfin

### ISSUE THREAD

**Issue by sharkymcdongles** [jellyfin/jellyfin#7914]
### Please describe your bug

It seems some CBR files just don't play when I click play. If I check the web console I get:

```
{
    "message": "Parsing filters is unsupported.",
    "name": "Error",
    "stack": "Error: Parsing filters is unsupported.\n    at r.entries (https://jellyfin.filthypizza.com/web/libraries/worker-bundle.js:1:1421)\n    at entries.next (<anonymous>)\n    at self.onmessage (https://jellyfin.filthypizza.com/web/libraries/worker-bundle.js:1:71413)"
}
```

The ones that work the above doesn't appear in the logs. The CBR files are not broken or anything from what I can see because I can download and use them normally via the download button. Is there something I am missing or a header that is missing from the reverse proxy config set here maybe?: https://jellyfin.org/docs/general/networking/nginx.html

No idea why it only fails for some comics.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Virtualization: Containerized using linuxserver.io container
- Clients: JellyFin Android
- Browser: Chrome and Firefox
- FFmpeg Version: N/A
- Playback Method: Both app and webapp direct play clicking play icon.
- Hardware Acceleration: No
- Plugins: 
- Reverse Proxy: yes with settings recommended here: https://jellyfin.org/docs/general/networking/nginx.html
- Base URL: subdomain
- Networking: Gigabit
- Storage: HD
```

### Jellyfin logs

```shell
[09:51:33] [INF] [58] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.0 playing Comic - Issue 003. Stopped at 0 ms
[09:51:34] [INF] [57] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMS4wLjQ5NTEuNjcgU2FmYXJpLzUzNy4zNnwxNjUyOTcxMDY0MjUy-0c3a02440bb8443b9ba1d15c30f77f10-51b35d834070009adc5a0a779c5e59ec
[09:52:12] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : f53d4d44-64e0-43fa-b75f-4b45a3df6ad5-2928436cd48643cd95e142a2def837b6-bb6080323cad62436d308a39d87f95ec
[09:52:12] [INF] [33] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 06/13/2022 09:52:12
[09:52:12] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[09:52:12] [INF] [43] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Starting User Changes Sync...
[09:52:12] [INF] [43] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: "USERSYNC" User 2928436cd48643cd95e142a2def837b6(uh) posted 2 Updates: bb6080323cad62436d308a39d87f95ec,429cfa5c1648e89c5f696f08e19b138f
[09:52:12] [INF] [43] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Changes Sync Finished Taking 00:00:00.0358553
[09:54:05] [INF] [73] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.0 playing Comic - Issue 003. Stopped at 0 ms
[09:54:05] [INF] [69] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMS4wLjQ5NTEuNjcgU2FmYXJpLzUzNy4zNnwxNjUyOTcxMDY0MjUy-0c3a02440bb8443b9ba1d15c30f77f10-51b35d834070009adc5a0a779c5e59ec
[09:55:09] [INF] [52] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.0 playing Comic - Issue 002. Stopped at 0 ms
[09:55:09] [INF] [51] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMS4wLjQ5NTEuNjcgU2FmYXJpLzUzNy4zNnwxNjUyOTcxMDY0MjUy-0c3a02440bb8443b9ba1d15c30f77f10-d27466de8d0884b0e2c692686bac1582
[09:55:11] [INF] [66] Emby.Server.Implementations.HttpServer.WebSocketManager: WS CENSORED closed
[09:55:12] [INF] [48] Emby.Server.Implementations.HttpServer.WebSocketManager: WS CENSORED request
[10:00:33] [INF] [85] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.0 playing Comic - Issue 002. Stopped at 0 ms
[10:00:33] [INF] [87] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop did not have a tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMS4wLjQ5NTEuNjcgU2FmYXJpLzUzNy4zNnwxNjUyOTcxMDY0MjUy-0c3a02440bb8443b9ba1d15c30f77f10-d27466de8d0884b0e2c692686bac1582
[10:00:36] [INF] [85] Emby.Server.Implementations.HttpServer.WebSocketManager: WS CENSORED closed
[10:00:37] [INF] [79] Emby.Server.Implementations.HttpServer.WebSocketManager: WS CENSORED request
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

{
    "message": "Parsing filters is unsupported.",
    "name": "Error",
    "stack": "Error: Parsing filters is unsupported.\n    at r.entries (https://jellyfin.filthypizza.com/web/libraries/worker-bundle.js:1:1421)\n    at entries.next (<anonymous>)\n    at self.onmessage (https://jellyfin.filthypizza.com/web/libraries/worker-bundle.js:1:71413)"
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharkymcdongles** [comment]
I converted them to CBZ from CBR and now they work fine. Not sure why this is, but I have a workaround at least.
