### ISSUE TITLE
[Issue]: Error after upgrading to 10.8.0 from 10.7.7

### ISSUE THREAD

**Issue by badcrc** [jellyfin/jellyfin#7928]
### Please describe your bug

Hi,

I've Jellyfin deployed on my NAS (HP Microserver Gen8) with docker and [ansible-nas](https://github.com/davestephens/ansible-nas) witch uses [linuxserver.io](https://hub.docker.com/r/linuxserver/jellyfin) images. 

I also have watchtower running so it updates my images tagged with `:lattest`. After the last update I noticed that I get an ERR_CONNECTION_REFUSED trying to access the web and looking at the logs of the container, is in a loop and doesn't starts jellyfin.

Reversing to 10.7.7 and everything works.

IDK if I should open the issue here or on the linuxserver.io repo, sorry in advanced if the issue is misplaced.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 18 in the Host
- Virtualization: Docker
- Clients: Web browser
- Browser: Chrome 102.0.5005.115 
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: none
- Plugins: opensubtitles
- Reverse Proxy:
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
22:14:23] [FTL] [1] Main: Error while starting server.
System.ArgumentNullException: Value cannot be null. (Parameter 'authenticationProviderId')
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method44(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[22:14:23] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[22:14:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[22:14:23] [INF] [2] Main: Received a SIGTERM signal, shutting down
[22:14:24] [INF] [1] Main: Jellyfin version: 10.8.0
[22:14:24] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]"]
[22:14:24] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
[22:14:24] [INF] [1] Main: Operating system: Linux
[22:14:24] [INF] [1] Main: Architecture: X64
[22:14:24] [INF] [1] Main: 64-Bit Process: True
[22:14:24] [INF] [1] Main: User Interactive: True
[22:14:24] [INF] [1] Main: Processor count: 8
[22:14:24] [INF] [1] Main: Program data path: /config/data
[22:14:24] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[22:14:24] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[22:14:24] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[22:14:24] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[22:14:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly OpenSubtitlesHandler, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles_12.0.0.0/OpenSubtitlesHandler.dll
[22:14:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles_12.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[22:14:24] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Reports_12.0.0.0/Jellyfin.Plugin.Reports.dll
[22:14:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:14:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[22:14:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:14:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[22:14:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Spirarementum** [comment]
I have a similar problem after updating.

jellyfin service not starting after updating to Jellyfin.Server 10.8.0.0 on my Armbian 22.05.1 Buster with Linux 4.4.213-rk3399 ?
$ jellyfin
$  journalctl -u jellyfin.service
Jun 14 10:51:32 SpirareVault systemd[1]: jellyfin.service: Scheduled restart job, restart counter i
Jun 14 10:51:32 SpirareVault systemd[1]: Stopped Jellyfin Media Server.
Jun 14 10:51:32 SpirareVault systemd[1]: Started Jellyfin Media Server.
Jun 14 10:51:32 SpirareVault jellyfin[2378]: Failed to create CoreCLR, HRESULT: 0x8007FF02
Jun 14 10:51:32 SpirareVault systemd[1]: jellyfin.service: Main process exited, code=exited, status
Jun 14 10:51:32 SpirareVault systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jun 14 10:51:32 SpirareVault systemd[1]: jellyfin.service: Service RestartSec=100ms expired, schedu

Launching manually in a terminal:
$ jellyfin
[10:55:03] [INF] [4] Main: Jellyfin version: 10.8.0
[10:55:03] [INF] [4] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/sergio/.local/share/jellyfin/log]"]
[10:55:03] [INF] [4] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[10:55:03] [INF] [4] Main: Operating system: Linux
[10:55:03] [INF] [4] Main: Architecture: Arm64
[10:55:03] [INF] [4] Main: 64-Bit Process: True
[10:55:03] [INF] [4] Main: User Interactive: True
[10:55:03] [INF] [4] Main: Processor count: 6
[10:55:03] [INF] [4] Main: Program data path: /home/sergio/.local/share/jellyfin
[10:55:03] [INF] [4] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[10:55:03] [INF] [4] Main: Application directory: /usr/lib/jellyfin/bin/
[10:55:03] [ERR] [4] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.
[10:55:03] [INF] [2] Main: Received a SIGTERM signal, shutting down

What am I missing ?

**Comment by RainbowPants** [comment]
@Spirarementum try searching the error string, see https://github.com/jellyfin/jellyfin/issues/7503

**Comment by Spirarementum** [comment]
> @Spirarementum try searching the error code, see #7503
Thanks... A work-around is provided by r417 in https://github.com/jellyfin/jellyfin/issues/3638#
But why is this close ? There is a definite problem updating ?

My system is again ARM (Armbian 22.05.1 Buster with Linux 4.4.213-rk3399)
I did a standard installation following jellyfin doc, debian section Debian repository for installation on Debian Buster/Bullseye

**Comment by Spirarementum** [comment]
A work-around is provided by r417 in https://github.com/jellyfin/jellyfin/issues/3638 does not work for me. 
After implementing this: `ln -s /usr/share/jellyfin/web/ /usr/lib/jellyfin/bin/jellyfin-web` and launching jellyfin manually in a terminal, it lauche a new installation script. Can't log in to the server with my old credential.
Anyone ?

**Comment by Shadowghost** [comment]
Might be fixed by https://github.com/jellyfin/jellyfin/pull/7887

**Comment by Spirarementum** [comment]
Updating from 10.7.7 to 10.8.1 worked fine for me if this helps.

**Comment by 3nprob** [comment]
Some (crashes every startup) on 10.8.3 upgraded from 10.7.7.

```
[06:52:03] [FTL] [1] Main: Error while starting server.
System.ArgumentNullException: Value cannot be null. (Parameter 'passwordResetProviderId')
   at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
   at lambda_method44(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Comment by 3nprob** [comment]
Somehow there was a user with empty `PasswordResetProvider` in the db:

```
$ sqlite3 jellyfin.db "select count(1) from Users where PasswordResetProviderId = '';"
1
```

This solved it:
```
$ sqlite3 jellyfin.db "update Users SET PasswordResetProviderId = 'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' where PasswordResetProviderId = '';"
```

**Comment by badcrc** [comment]
> Somehow there was a user with empty `PasswordResetProvider` in the db:
> 
> ```
> $ sqlite3 jellyfin.db "select count(1) from Users where PasswordResetProviderId = '';"
> 1
> ```
> 
> This solved it (make sure process is not running):
> 
> ```
> $ sqlite3 jellyfin.db "update Users SET PasswordResetProviderId = 'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' where PasswordResetProviderId = '';"
> ```

Hi,

this fixed it! 

Thanks!

**Comment by AnonymousWebHacker** [comment]
> Somehow there was a user with empty `PasswordResetProvider` in the db:
> 
> ```
> $ sqlite3 jellyfin.db "select count(1) from Users where PasswordResetProviderId = '';"
> 1
> ```
> 
> This solved it (make sure process is not running):
> 
> ```
> $ sqlite3 jellyfin.db "update Users SET PasswordResetProviderId = 'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider' where PasswordResetProviderId = '';"
> ```

I ran, and I had 1 in jellyfin.db , but it still doesn't work for me.

Could you tell me how to check also `library.db` and `playback_reporting.db`

```
May  1 02:04:36 MediaX-Server jellyfin[15077]: [02:04:36] [INF] Using bind addresses: []
May  1 02:04:36 MediaX-Server jellyfin[15077]: [02:04:36] [INF] Using bind exclusions: []
May  1 02:04:38 MediaX-Server jellyfin[15077]: [02:04:38] [FTL] Error while starting server.
May  1 02:04:38 MediaX-Server jellyfin[15077]: System.ArgumentNullException: Value cannot be null. (Parameter 'authenticationProviderId')
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Data.Entities.User..ctor(String username, String authenticationProviderId, String passwordResetProviderId)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at lambda_method44(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
May  1 02:04:38 MediaX-Server jellyfin[15077]: [02:04:38] [INF] Running query planner optimizations in the database... This might take a while
May  1 02:04:38 MediaX-Server jellyfin[15077]: [02:04:38] [INF] Disposing CoreAppHost
May  1 02:04:38 MediaX-Server jellyfin[15077]: [02:04:38] [FTL] Unhandled Exception
May  1 02:04:38 MediaX-Server jellyfin[15077]: System.NullReferenceException: Object reference not set to an instance of an object.
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.DisposeAsyncCore()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.DisposeAsync()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Program.<Main>(String[] args)
May  1 02:04:38 MediaX-Server jellyfin[15077]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.DisposeAsyncCore()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Emby.Server.Implementations.ApplicationHost.DisposeAsync()
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
May  1 02:04:38 MediaX-Server jellyfin[15077]:    at Jellyfin.Server.Program.<Main>(String[] args)
May  1 02:04:38 MediaX-Server systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
May  1 02:04:38 MediaX-Server systemd[1]: jellyfin.service: Failed with result 'signal'.
May  1 02:04:38 MediaX-Server systemd[1]: jellyfin.service: Consumed 2.449s CPU time.

```
