### ISSUE TITLE
[Issue]: Getting database error on clean install of 10.8

### ISSUE THREAD

**Issue by brimur** [jellyfin/jellyfin#7943]
### Please describe your bug

This morning my Jellyfin server would not start after a reboot of my Ubuntu server. It never wrote anything to the Jellyfin logs in /var/log/jellyfin but doing a service jellyfin status gave me this...

```
Process: 2299 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} ${JELLYFIN_ADDITIONAL_OPTS} (code=exited, status=200/CHDIR)

Main PID: 2299 (code=exited, status=200/CHDIR)
Jun 15 15:44:47 BigPlex systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Jun 15 15:44:47 BigPlex systemd[1]: Stopped Jellyfin Media Server.
Jun 15 15:44:47 BigPlex systemd[1]: jellyfin.service: Start request repeated too quickly.
Jun 15 15:44:47 BigPlex systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jun 15 15:44:47 BigPlex systemd[1]: Failed to start Jellyfin Media Server.
```

I tried uninstalling and reinstalling but got the same result so I removed the app and deleted all associated folders and files from the following locations...

```
Program data path: "/var/lib/jellyfin"
Web resources path: "/usr/share/jellyfin/web"
 Application directory: "/usr/lib/jellyfin/bin/"
Setting cache path: "/var/cache/jellyfin"

```

When I was sure everything was removed I reinstalled with apt install jellyfin

Now I am getting the error below in the logs.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: VMware ESXi
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-06-15 15:59:44.440 +00:00] [INF] Jellyfin version: "10.8.0"
[2022-06-15 15:59:44.454 +00:00] [INF] Environment Variables: ["[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]"]
[2022-06-15 15:59:44.456 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2022-06-15 15:59:44.457 +00:00] [INF] Operating system: "Linux"
[2022-06-15 15:59:44.457 +00:00] [INF] Architecture: X64
[2022-06-15 15:59:44.457 +00:00] [INF] 64-Bit Process: True
[2022-06-15 15:59:44.457 +00:00] [INF] User Interactive: True
[2022-06-15 15:59:44.457 +00:00] [INF] Processor count: 6
[2022-06-15 15:59:44.457 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2022-06-15 15:59:44.458 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2022-06-15 15:59:44.458 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2022-06-15 15:59:44.564 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2022-06-15 15:59:44.570 +00:00] [INF] Loading assemblies
[2022-06-15 15:59:44.659 +00:00] [INF] Defined LAN addresses : "[192.168.0.0/16]"
[2022-06-15 15:59:44.659 +00:00] [INF] Defined LAN exclusions : "[]"
[2022-06-15 15:59:44.660 +00:00] [INF] Using LAN addresses: "[192.168.0.0/16]"
[2022-06-15 15:59:44.663 +00:00] [INF] Using bind addresses: "[]"
[2022-06-15 15:59:44.663 +00:00] [INF] Using bind exclusions: "[]"
[2022-06-15 15:59:45.566 +00:00] [INF] There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[2022-06-15 15:59:45.803 +00:00] [INF] EFCore migrations applied successfully
[2022-06-15 15:59:46.186 +00:00] [INF] Loaded plugin: "TMDb" "10.8.0.0"
[2022-06-15 15:59:46.186 +00:00] [INF] Loaded plugin: "Studio Images" "10.8.0.0"
[2022-06-15 15:59:46.187 +00:00] [INF] Loaded plugin: "OMDb" "10.8.0.0"
[2022-06-15 15:59:46.187 +00:00] [INF] Loaded plugin: "MusicBrainz" "10.8.0.0"
[2022-06-15 15:59:46.187 +00:00] [INF] Loaded plugin: "AudioDB" "10.8.0.0"
[2022-06-15 15:59:46.223 +00:00] [INF] Applying migration '"MigrateAuthenticationDatabase"'
[2022-06-15 15:59:46.226 +00:00] [ERR] Could not apply migration '"MigrateAuthenticationDatabase"'
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateAuthenticationDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-06-15 15:59:46.229 +00:00] [FTL] Error while starting server.
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateAuthenticationDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-06-15 15:59:46.229 +00:00] [INF] Running query planner optimizations in the database... This might take a while
[2022-06-15 15:59:46.269 +00:00] [INF] Disposing "CoreAppHost"
[2022-06-15 15:59:46.270 +00:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2022-06-15 15:59:46.270 +00:00] [INF] Disposing "EmbyTV"
[2022-06-15 15:59:46.271 +00:00] [INF] Disposing "SchedulesDirect"
[2022-06-15 15:59:46.272 +00:00] [INF] Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
> CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file

Potentially fixed by https://github.com/jellyfin/jellyfin/pull/7887
