### ISSUE TITLE
[Issue]: Jellyfin doesn't try to fetch any metadata in Mixed Libraries for files that are TV shows episodes

### ISSUE THREAD

**Issue by Nicryc** [jellyfin/jellyfin#8042]
### Please describe your bug

When a media library is configured on "Mixed content: Movie and TV Shows" (called "Other" in previous versions of Jellyfin) it doesn't even try to fetch metadata from folders that contain TV shows (even when there is a single file in the folder) and just displays a generic folder view (see screenshots). The result is that TV shows are not identified and don't have any metadata, while movies work just fine.

I'm aware that mixed content library aren't very robust and are known to be broken but the thing is, it used to work properly before 10.8.0. Even if there were some issues, TV shows and movies were in the vast majority of cases correctly identifies and metadata were fetched.

I tried to recreate a brand new mixed library with the exact same result.

### Some examples of what doesn't work:
- [Une espèce à part (2019)](https://www.themoviedb.org/tv/98340-une-espece-a-part) identified as a TV show on TMDb with one file containing all episodes named "Une Espèce à Part (2019) - S01E01-E10.mp4"
- The same TV show with two versions of the same file containing all episodes named "Une Espèce à Part (2019) - S01E01-E10.mp4" and "Une Espèce à Part (2019) - S01E01-E10.webm" (both versions are detected and can be selected in the UI).
- [Chine, le nouvel Empire (2013)](https://www.themoviedb.org/tv/81914-chine-le-nouvel-empire) identified as a TV show on TMDb with 3 files named "China-Le-Nouvel-Empire S01E0X.mp4"
- A folder containing a single episode of [Stupéfiant!](https://www.themoviedb.org/tv/100316-stupefiant) (a TV show) named "Sieff, le nu de père en fille - Stupéfiant !-x6xhhtb S00E00.mp4"
- [Apocalypse, la guerre des mondes (2019)](https://www.themoviedb.org/tv/95224-apocalypse-la-guerre-des-mondes-1945-1991) identified as a TV show on TMDb with 6 files named "APOCALYPSE, LA GUERRE DES MONDES - X.  DIFFERENT TITLE (19XX-19XX) S01E0X.mkv"

### Some examples of what works:
- [The Deminer (2017)](https://www.themoviedb.org/movie/488093-the-deminer) identified as a movie on TMDb with a single file named "Le démineur de Mossoul ARTE-720p.mp4"
- [Mystérieux trous noirs (2018)](https://www.themoviedb.org/movie/541386-black-hole-apocalypse) identified as a movie on TMDb with 2 versions of the movie named "Mystérieux trous noirs (2018) - Concaténation ffmpeg.mp4" and "Mystérieux trous noirs (2018) - Montage kdenlive.mp4" + some extras in a subfolder.
- [Finland from East to West (2017)](https://www.themoviedb.org/movie/491657-une-histoire-finlandaise)  identified as a movie on TMDb with 2 versions of the movie named "Une histoire finlandaise (2017) - Histoire de la Finlande-x7pbgqr.mp4" and "Une histoire finlandaise (2017) - Une.histoire.finlandaise.2017.FRENCH.HDTV.720p.x264.mp4"

Jellyfin logs show what happen when I try to force refresh metadata of the mixed content library.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows 10
- Clients: Browser and Jellyfin Media Server
- Browser: Firefox 102.0
- FFmpeg Version: 5.0.1-Jellyfin
- Storage: local
```

### Jellyfin logs

```shell
[2022-06-30 18:16:07.948 +02:00] [INF] [25] Emby.Drawing.ImageProcessor: Creating image collage and saving to "C:\ProgramData\Jellyfin\Server\cache\temp\a00dada5a6494ee585106ad599c10a45.png"
[2022-06-30 18:16:08.109 +02:00] [INF] [25] Emby.Drawing.ImageProcessor: Completed creation of image collage and saved to "C:\ProgramData\Jellyfin\Server\cache\temp\a00dada5a6494ee585106ad599c10a45.png"
[2022-06-30 18:16:22.021 +02:00] [INF] [34] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image "C:\ProgramData\Jellyfin\Server\metadata\library\e7\e7a3ff92d81bda20ae9afbcb2b7ad6b7\poster.jpg"
[2022-06-30 18:16:22.122 +02:00] [INF] [43] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image "C:\ProgramData\Jellyfin\Server\metadata\library\1e\1e1413639e7708194b3b411607254ed1\poster.jpg"
[2022-06-30 18:16:22.143 +02:00] [ERR] [34] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "C:\ProgramData\Jellyfin\Server\metadata\library\e7\e7a3ff92d81bda20ae9afbcb2b7ad6b7\poster.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-06-30 18:16:22.271 +02:00] [ERR] [43] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "C:\ProgramData\Jellyfin\Server\metadata\library\1e\1e1413639e7708194b3b411607254ed1\poster.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2022-06-30 18:16:25.779 +02:00] [INF] [43] MediaBrowser.Providers.Manager.ProviderManager: Deleting previous image "C:\ProgramData\Jellyfin\Server\metadata\library\a1\a17f6357813e9f506bb9175bac346bc5\poster.jpg"
[2022-06-30 18:16:25.837 +02:00] [ERR] [43] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "C:\ProgramData\Jellyfin\Server\metadata\library\a1\a17f6357813e9f506bb9175bac346bc5\poster.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### Please attach any screenshots here

![jellyfin-mixed-library-overview](https://user-images.githubusercontent.com/15157120/176729448-25100204-9e09-4433-ad89-98145fd2d062.png)
![jellyfin-mixed-library-folder-view](https://user-images.githubusercontent.com/15157120/176729502-c2a94831-2251-4767-9a2c-9aacb45467eb.png)
![jellyfin-mixed-library-media-view](https://user-images.githubusercontent.com/15157120/176729529-384e4c00-f0c3-463a-bb3a-e4e2d6929ac1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mastercho** [comment]
Same issue is here, also brokes down for movies which are split into CD1, CD2 shows 2 different movie now and no metadata fetched

**Comment by algirdasN** [comment]
Same issue here since 10.8.0. Was working fine with 10.7.x.

**Comment by DavidBrocho** [comment]
Anybody knows the new nomenclature?
I have same problem.

**Comment by SabaTsomaia** [comment]
i have the same problem too.

**Comment by DavidBrocho** [comment]
I solve partially: I use TINYMEDIAMANAGER. It's free.
Create NFO files in TvShows folder: ONLY "tvshow.nfo".
In movies isn't neccesary, because JellyFin recognizes all mixed content as movies, or movies inside subfolders.

**Comment by sand-bit** [comment]
This is currently indeed broken on [v10.8.5](https://github.com/jellyfin/jellyfin/releases/tag/v10.8.5).

**Comment by daves00** [comment]
+1 - seems to be introduced in either 10.8.4 or 10.8.5 - mine worked fine in earlier versions. Hope that helps

**Comment by illeatmyhat** [comment]
Doing the `S01E01` thing used to work
Now the only thing that works is shoving the entire series into a `Season 01` folder

There are a ton of shows with movie tie-ins, and they do have a timing in the series
Especially Japanese shows
It's really annoying separating them all
There really should be a more generic library where movies and shows are the exact same thing, because they often are.

**Comment by alpert1** [comment]
It doesn't even have to be a mix of series and movies. I'm trying to retrieve the metadata for the two pilot episodes of Battlestar Galactica, but since imdb lists these two episodes under a different id than the rest of the series, jellyfin refuses to retrieve their metadata even after manually adding the imdb id to the metadata of said two episodes.

pilot episodes: [https://www.imdb.com/title/tt0314979/](https://www.imdb.com/title/tt0314979/)
rest of the show: [https://www.imdb.com/title/tt0407362/](https://www.imdb.com/title/tt0407362/)

**Comment by joskapista44** [comment]
Same issue here, jellyfin 10.8.10

**Comment by onrecc** [comment]
Happening to me too

**Comment by mastercho** [comment]
i guess this issue will be closed also without fix

**Comment by chadsr** [comment]
This is still the case.

To make it more confusing, when creating a new "Mixed Films & Programmes" library, the description reads:
 `Content will be displayed as plain folders. For best results use the metadata manager to set the content types of sub-folders.
`

Nowhere in the metadata manager does there seem to be a setting to do what this states should be possible?

**Comment by mastercho** [comment]
> This is still the case.
> 
> To make it more confusing, when creating a new "Mixed Films & Programmes" library, the description reads: `Content will be displayed as plain folders. For best results use the metadata manager to set the content types of sub-folders. `
> 
> Nowhere in the metadata manager does there seem to be a setting to do what this states should be possible?

Agree, maybe in new 10.9 version will be fixed lol
