### ISSUE TITLE
[Issue]: Error in ffprobe:'L' is an invalid start of a value.

### ISSUE THREAD

**Issue by MoFanFr** [jellyfin/jellyfin#8046]
### Please describe your bug

Hello,
I use a NAS QNAP TS-464C and I have reinstalled the last version (10.8.1).
With this version, I can't run any video.
I always have the same error in the log. I have no error in the client but no video either.
Thank you for your help.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: QNAP
- Virtualization:No
- Clients:Android
- Browser:Chrome
- FFmpeg Version:No idea
- Playback Method:
- Hardware Acceleration:VAAPI
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: TS-464C
```

### Jellyfin logs

```shell
[2022-07-02 09:26:22.405 +08:00] [ERR] [76] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'L' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pdulvp** [comment]
This issue is fixed in the latest qnap release https://github.com/pdulvp/jellyfin-qnap/releases/tag/10841.10841.511_2 and was more a packaging issue than a jellyfin one.
https://github.com/pdulvp/jellyfin-qnap/issues/22
Can be closed.
