### ISSUE TITLE
[Issue]: VPN used with split tunneling prevents the "Catalog" page of "Plugins" to return any results

### ISSUE THREAD

**Issue by EcceGratum** [jellyfin/jellyfin#8054]
### Please describe your bug

I use Mullvad VPN with split tunneling. Jellyfin is among the list of apps that are excluded from using it so they should access internet directy with the vanilla network interface.

But for some reason, the "Catalog" page of "Plugins" always remains empty. Repro rate is 100%.
When the VPN is disabled, it works. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows
- Virtualization: none
- Clients: Browser
- Browser: Firefox 102.0
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: aniDB, AniList, AniSearch, Kitsu, Shoko
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-07-03 21:37:36.218 -04:00] [INF] [92] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "fe80::b135:a745:f6f:21f1%15" closed
[2022-07-03 21:37:40.864 -04:00] [INF] [113] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-07-03 21:37:40.866 -04:00] [INF] [113] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  ""
[2022-07-03 21:37:43.215 -04:00] [INF] [113] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 16 items:  "344a31d0462e30db1c28af604e20e2cd,185edf8a1b5a3bf51e6b58906c1bf3e1,3760a00eb6fdde0182ef8bb02384579e,7981bcadecda85747293e5da2e987dc0,399dd44e3919d0975dce5bff30ec6538,db3e8e67af48d99087333dae9a5d7fef,e00fd2624a49d86e38bc765aa5633817,72dee3c96ed50b0e4e4d6e470539c8ca,260c4204e87e6f1792bef05f584ac44f,a0dd3a17b867f7b7ebd7bdc644430804,2a319763c46ed231ba293c47b084ba92,052dcf25a02e28755d539aed08dfc77a,f840358952e08715e214acd8be7429c8,8513022308704abd0e2415c413a0603f,504b6524d67c7eaa7f90527daf2c4863,c45f1fe6b3fffd3eb8034869b1c92df4"
[2022-07-03 21:37:43.218 -04:00] [INF] [113] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-07-03 21:37:43.221 -04:00] [INF] [113] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:02.3546492"
[2022-07-03 21:38:48.014 -04:00] [INF] [92] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "fe80::b135:a745:f6f:21f1%15" request
[2022-07-03 21:38:57.989 -04:00] [ERR] [20] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The process cannot access the file 'C:\ProgramData\Jellyfin\Server\log\log_20220703.log' because it is being used by another process". URL "GET" "/System/Logs/Log".
[2022-07-03 21:39:04.653 -04:00] [INF] [116] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "fe80::b135:a745:f6f:21f1%15" closed
[2022-07-03 21:39:36.031 -04:00] [INF] [92] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:192.168.2.13" closed
[2022-07-03 21:40:05.327 -04:00] [INF] [114] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "fe80::b135:a745:f6f:21f1%15" request
[2022-07-03 21:40:14.416 -04:00] [ERR] [110] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (repo.jellyfin.org:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
[2022-07-03 21:40:14.489 -04:00] [ERR] [114] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://raw.githubusercontent.com/ShokoAnime/Shokofin/master/manifest.json"
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
[2022-07-03 21:40:14.503 -04:00] [ERR] [110] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://raw.githubusercontent.com/ShokoAnime/Shokofin/master/manifest-unstable.json"
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FilouGK** [comment]
I would like to add the the same issue happens to installed scrapper plugins when they try to scrape something.
TheMovieDb, The Open Movie Database, AniDB, AniList, etc...

**Comment by jfarre20** [comment]
Happens on emby too

**Comment by crobibero** [comment]
Without knowing your full configuration my initial guess is that you need to bind Jellyfin to a specific interface.

**Comment by FilouGK** [comment]
> Without knowing your full configuration my initial guess is that you need to bind Jellyfin to a specific interface.

I agree with your assessment. Mullvad VPN (and other VPNs) tend to add a second network interface but there is no setting to force Jellyfin to use a specific network interface.

My configuration is quite simple. it's a standard win10 pro + jellyfin install with mullvad VPN, no extra network apps / firewalls / rules. The machine only has one physical network card, Mullvad creates a second network interface.

**Comment by jfarre20** [comment]
mullvad does something with the windows routing tables, could be the issue there.

**Comment by FilouGK** [comment]
I played a little with the network settings of Jellyfin to see if i could make it work.

I tried "VirtualInterfaceNames" to ignore either the Mullvad interface or the vanilla one.
I tried binding to the local network addresses of either the Mullvad interface or the vanilla one.

I debug it a little using the sources, didn't found anything.

In the end, i went into Mullvad split tunneling configuration tab and set Jellyfin to connect to the internet using the VPN's network interface instead of the vanilla one.

I can live with that although if someone uses a dynamic dns service it would require a forwarded port on the VPN which most VPNs don't provide.

**Comment by FilouGK** [comment]
I stumble upon this post [https://github.com/dotnet/runtime/issues/44686](https://github.com/dotnet/runtime/issues/44686).

I tried one of the 2 recommended fixes and it seems to fix the issue.

Basically, forcing ipv4 when a new socket is created for a new HttpClient.

In "Startup.cs", in the creation of "defaultHttpClientHandlerDelegate" at line 83 :

```
Func<IServiceProvider, HttpMessageHandler> defaultHttpClientHandlerDelegate = (_) => new SocketsHttpHandler()
            {
                AutomaticDecompression = DecompressionMethods.All,
                RequestHeaderEncodingSelector = (_, _) => Encoding.UTF8,
// CHANGES START
                ConnectCallback = async (context, cancellationToken) =>
                {
                    // Use DNS to look up the IP addresses of the target host:
                    // - IP v4: AddressFamily.InterNetwork
                    // - IP v6: AddressFamily.InterNetworkV6
                    // - IP v4 or IP v6: AddressFamily.Unspecified
                    // note: this method throws a SocketException when there is no IP address for the host
                    var entry = await Dns.GetHostEntryAsync(context.DnsEndPoint.Host, AddressFamily.InterNetwork, cancellationToken).ConfigureAwait(false);

                    // Open the connection to the target host/port
                    var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

                    // Turn off Nagle's algorithm since it degrades performance in most HttpClient scenarios.
                    socket.NoDelay = true;

                    try
                    {
                        await socket.ConnectAsync(entry.AddressList, context.DnsEndPoint.Port, cancellationToken).ConfigureAwait(false);

                        // If you want to choose a specific IP address to connect to the server
                        // await socket.ConnectAsync(
                        //    entry.AddressList[Random.Shared.Next(0, entry.AddressList.Length)],
                        //    context.DnsEndPoint.Port, cancellationToken);

                        // Return the NetworkStream to the caller
                        return new NetworkStream(socket, ownsSocket: true);
                    }
                    catch
                    {
                        socket.Dispose();
                        throw;
                    }
// CHANGES END
                }                
            };
```

I tried all possible combinations (Forcing Ipv4, Forcing Ipv6, default socket) and VPN allowing Ipv6 or not (In the VPN, Jellyfin was excluded from using the VPN access to the internet with Split Tunneling).

It only works if Ipv4 is forced on the socket.

NB: I have very little experience with C#, not a language i used often in my daily job.

**Comment by TheRedSpy15** [comment]
This worked for me: https://www.reddit.com/r/jellyfin/comments/xyuhdt/comment/ish6ewz/?utm_source=share&utm_medium=web2x&context=3
