### ISSUE TITLE
[Issue]: Movie info not fetch if selected language doesn't exist

### ISSUE THREAD

**Issue by mastercho** [jellyfin/jellyfin#8064]
### Please describe your bug

I did set to fetch Bulgarian info for my movies and back in 10.7.x versions was working in a way if Bulgarian doesn't exist pulls English summary, since i update  to 10.8 im getting no info pulled if Bulgarian doesn't exist. And rating was pulled correctly from OMDB before in 10.7, since 10.8 its gets incorrect ratings from TMDB.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Chrome 103.0.5060.66
- FFmpeg Version:
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: Fanart, Kinopoisk, Reports
- Reverse Proxy:none
- Base URL:none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[2022-07-05 00:56:41.853 +03:00] [INF] [324] Emby.Server.Implementations.IO.LibraryMonitor: "movies" ("/movies") will be refreshed.
[2022-07-05 00:57:20.065 +03:00] [ERR] [255] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-07-05 00:57:27.064 +03:00] [INF] [255] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 2 inactive WebSockets.
[2022-07-05 00:57:32.696 +03:00] [INF] [112] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-07-05 00:57:32.775 +03:00] [INF] [112] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 1 items:  "2f6bcae011ecfb0540e579def93d3b47"
[2022-07-05 00:57:34.200 +03:00] [INF] [112] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 4 items:  "cb6463cce1ce453101e3cb1109ac2dec,99071660470cdf8d3e0a0ca241cfd14c,6fba779e45bf9b36f133c22f83bdd793,224d11e0c065229737138004836b143c"
[2022-07-05 00:57:34.200 +03:00] [INF] [112] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-07-05 00:57:34.200 +03:00] [INF] [112] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:01.5043931"
[2022-07-05 00:58:27.065 +03:00] [INF] [235] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 2 inactive WebSockets.
[2022-07-05 00:58:39.180 +03:00] [INF] [313] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.100.117" closed
[2022-07-05 00:58:51.562 +03:00] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=26f37d781352e4034106d4e12d8149b1" to "192.168.100.117" in 0:00:00.7626827 with Status Code 200
[2022-07-05 00:58:51.712 +03:00] [WRN] [377] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=fa6b2c7b16621cbe36b641e047f36017" to "192.168.100.117" in 0:00:00.9124774 with Status Code 200
[2022-07-05 00:58:51.937 +03:00] [WRN] [110] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=8d751529513e4ce6a54cd5b493300b4e&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2021-07-04T21%3A58%3A45.046Z&EnableRewatching=false" to "192.168.100.117" in 0:00:01.1416489 with Status Code 200
[2022-07-05 00:59:14.134 +03:00] [WRN] [247] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio" to "192.168.100.117" in 0:00:00.5891158 with Status Code 200
[2022-07-05 00:59:14.135 +03:00] [WRN] [15] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=26f37d781352e4034106d4e12d8149b1" to "192.168.100.117" in 0:00:00.5826085 with Status Code 200
[2022-07-05 00:59:14.355 +03:00] [WRN] [321] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=fa6b2c7b16621cbe36b641e047f36017" to "192.168.100.117" in 0:00:00.8022478 with Status Code 200
[2022-07-05 00:59:14.563 +03:00] [WRN] [110] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=8d751529513e4ce6a54cd5b493300b4e&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2021-07-04T21%3A59%3A07.838Z&EnableRewatching=false" to "192.168.100.117" in 0:00:01.0137836 with Status Code 200
[2022-07-05 00:59:26.697 +03:00] [WRN] [323] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items?searchTerm=Torbaaz&IncludeItemTypes=Series,Movie,Episode&Limit=24&Fields=OriginalTitle,ProviderIds&Recursive=true" to "192.168.100.117" in 0:00:00.5547539 with Status Code 200
[2022-07-05 00:59:47.126 +03:00] [WRN] [321] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=26f37d781352e4034106d4e12d8149b1" to "192.168.100.117" in 0:00:00.5619702 with Status Code 200
[2022-07-05 00:59:47.276 +03:00] [WRN] [110] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio" to "192.168.100.117" in 0:00:00.7133746 with Status Code 200
[2022-07-05 00:59:47.276 +03:00] [WRN] [323] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book" to "192.168.100.117" in 0:00:00.7136046 with Status Code 200
[2022-07-05 00:59:47.339 +03:00] [WRN] [4] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Users/8d751529513e4ce6a54cd5b493300b4e/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=fa6b2c7b16621cbe36b641e047f36017" to "192.168.100.117" in 0:00:00.7005396 with Status Code 200
[2022-07-05 00:59:47.559 +03:00] [WRN] [15] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://mthtower:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CBasicSyncInfo%2CPath%2CMediaSourceCount&UserId=8d751529513e4ce6a54cd5b493300b4e&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2021-07-04T21%3A59%3A40.738Z&EnableRewatching=false" to "192.168.100.117" in 0:00:00.9979847 with Status Code 200
[2022-07-05 00:59:48.655 +03:00] [INF] [110] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-07-05 00:59:48.655 +03:00] [INF] [110] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  ""
[2022-07-05 00:59:49.707 +03:00] [INF] [110] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 1 items:  "2f6bcae011ecfb0540e579def93d3b47"
[2022-07-05 00:59:49.707 +03:00] [INF] [110] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-07-05 00:59:49.707 +03:00] [INF] [110] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:01.0519365"
[2022-07-05 01:03:16.104 +03:00] [INF] [369] Emby.Server.Implementations.IO.LibraryMonitor: "Torbaaz" ("/movies/Torbaaz 2020.HD-WEB.1080p.H264.DD+5.1.noFreeman/Torbaaz 2020.HD-WEB.1080p.H264.DD+5.1.noFreeman.mkv") will be refreshed.
[2022-07-05 01:03:21.197 +03:00] [INF] [270] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-07-05 01:03:21.197 +03:00] [INF] [270] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  ""
[2022-07-05 01:03:22.475 +03:00] [INF] [270] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 1 items:  "2f6bcae011ecfb0540e579def93d3b47"
[2022-07-05 01:03:22.475 +03:00] [INF] [270] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-07-05 01:03:22.475 +03:00] [INF] [270] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:01.2778686"
[2022-07-05 01:04:39.978 +03:00] [INF] [254] Emby.Server.Implementations.IO.LibraryMonitor: "movies" ("/movies") will be refreshed.
[2022-07-05 01:05:20.900 +03:00] [ERR] [247] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-07-05 01:05:35.447 +03:00] [INF] [271] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
[2022-07-05 01:05:35.520 +03:00] [INF] [271] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 1 items:  "b6723cddfc4bae4ba76746402767eb10"
[2022-07-05 01:05:36.832 +03:00] [INF] [271] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 4 items:  "cb6463cce1ce453101e3cb1109ac2dec,99071660470cdf8d3e0a0ca241cfd14c,6fba779e45bf9b36f133c22f83bdd793,224d11e0c065229737138004836b143c"
[2022-07-05 01:05:36.833 +03:00] [INF] [271] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  ""
[2022-07-05 01:05:36.833 +03:00] [INF] [271] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking "00:00:01.3857646"
```

### Please attach any browser or client logs here

![Chrome](https://ruri.please-fuck.me/5AWAems1S.png)

### Please attach any screenshots here

![Chrome](https://ruri.please-fuck.me/5AWAVe8tP.jpeg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solbu** [comment]
I was about to open a ticket for the same problem.
I have norwegian selected as my _Prefered_ language, but if a norwegian summary does not exist, no english info is grabbed.

It used to work in 10.7 and stopped working in 10.8.

**Comment by daullmer** [comment]
What metadata provider are you using? TMDb or OMDB? From your description it sounds like it is not using the provider you expect which would be another topic.

**Comment by solbu** [comment]
> What metadata provider are you using? TMDb or OMDB?

I have both selected.

And again, this Worked in version 10.7.x, it just stopped working as of 10.8.x and I did not change any settings.
I only upgraded to 10.8 when it came out.

**Comment by daullmer** [comment]
And which of the two is first in the list and has priority?

**Comment by solbu** [comment]
> And which of the two is first in the list and has priority?

TMDB.

**Comment by daullmer** [comment]
I have just confirmed this. In 10.7 if TMDb didn't have a translation for your language, we would fall back to your next provider (OMDB in this case). Since TMDb doesn't provide a way to fall back to multiple languages in the API like on their website, we can't just do `if your language not available on TMDb -> English from TMDb`.

But you seem to be correct that the fallback logic has changed from 10.7 to 10.8

**Comment by solbu** [comment]
Just tested the new 10.8.7 release, and it does indeed fix the issue. :-)
