### ISSUE TITLE
[Issue]: Can't DLNA on SONY KDL-40WE663 

### ISSUE THREAD

**Issue by ysharoiko** [jellyfin/jellyfin#8075]
### Please describe your bug

Using DLNA server in jellyfin 10.8.1
On TV SONY Bravia KDL-40WE663  software version 8.609-1000-2.700-0002
open DLNA server and go into video folder - got "There are no items to display"
same thing is with LIVE TV folder
On another Sony KDL-32W653A i see files, but live TV does not plays, video files plays. 
In web browser on jellyfin page live tv and video plays normally.

### Jellyfin Version

10.8.0

### if other:

10.8.1

### Environment

```markdown
- OS: Linux LMDE 4 (debbie) linux 4.19.0-19-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64 GNU/Linux
- Virtualization: No
- Clients: SONY BRAVIA TV kdl40WE663, 
- Browser: google chrome
- FFmpeg Version: 
ffmpeg:  7:4.1.9-0+deb10u1
ffmpegthumbnailer:  2.1.1-0.2+b1
jellyfin-ffmpeg5:  5.0.1-7-buster
libffmpegthumbnailer4v5:  2.1.1-0.2+b1      
- Playback Method: DLNA
- Hardware Acceleration:
- Plugins:
AudioDB10.8.1.0
MusicBrainz10.8.1.0
NextPVR8.0.0.0
OMDb10.8.1.0
Open Subtitles18.0.0.0
Studio Images10.8.1.0
TMDb10.8.1.0

- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
for LIVE TV

[2022-07-07 10:30:20.991 +03:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/SHARE/video"
[2022-07-07 10:30:23.421 +03:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2022-07-07 10:30:23.422 +03:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2022-07-07 10:30:23.426 +03:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2022-07-07 10:30:25.141 +03:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2022-07-07 10:30:25.146 +03:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-07-07 10:30:25.915 +03:00] [INF] [32] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
DeviceIdentification { FriendlyName: "KDL-40WE663", ModelNumber: "1.0", SerialNumber: null, ModelName: "KDL-32W700B", ModelDescription: "IPI Media Renderer", ModelUrl: "http://www.access-company.com/", Manufacturer: "Sony Corporation", ManufacturerUrl: "http://www.access-company.com/", Headers: [] }
[2022-07-07 10:30:25.918 +03:00] [INF] [32] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "KDL-40WE663" - "KDL-32W700B"
[2022-07-07 10:30:25.954 +03:00] [INF] [13] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "BRAVIA KDL-32W653A" - "KDL-32W653A"
[2022-07-07 10:30:26.807 +03:00] [INF] [30] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "foobar2000 Renderer (root) [WSIT005]" - "foobar2000 Media Renderer"
[2022-07-07 10:30:27.524 +03:00] [INF] [30] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:30:27.540 +03:00] [INF] [30] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:30:27.633 +03:00] [INF] [23] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:30:27.633 +03:00] [INF] [23] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:30:30.452 +03:00] [INF] [23] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:30:30.452 +03:00] [INF] [23] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:30:30.519 +03:00] [ERR] [25] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
   at Emby.Dlna.ContentDirectory.ControlHandler.WriteResult(String methodName, IReadOnlyDictionary`2 methodParams, XmlWriter xmlWriter)
   at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```

For video folder
```
DeviceIdentification { FriendlyName: "KDL-40WE663", ModelNumber: "1.0", SerialNumber: null, ModelName: "KDL-32W700B", ModelDescription: "IPI Media Renderer", ModelUrl: "http://www.access-company.com/", Manufacturer: "Sony Corporation", ManufacturerUrl: "http://www.access-company.com/", Headers: [] }
[2022-07-07 10:28:51.581 +03:00] [INF] [11] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "KDL-40WE663" - "KDL-32W700B"
[2022-07-07 10:28:51.590 +03:00] [INF] [11] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "foobar2000 Renderer (root) [WSIT005]" - "foobar2000 Media Renderer"
[2022-07-07 10:28:51.716 +03:00] [INF] [17] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "BRAVIA KDL-32W653A" - "KDL-32W653A"
[2022-07-07 10:29:03.079 +03:00] [INF] [20] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:29:03.098 +03:00] [INF] [20] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:29:03.186 +03:00] [INF] [22] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:29:03.186 +03:00] [INF] [22] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:29:05.398 +03:00] [INF] [17] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start GetRecordings Async, retrieve all 'Pending', 'Inprogress' and 'Completed' recordings 
[2022-07-07 10:29:05.398 +03:00] [INF] [17] Jellyfin.Plugin.NextPVR.LiveTvService: [NextPVR] Start InitiateSession
[2022-07-07 10:29:05.513 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Traumschiff.Surprise.Periode.1.2004.BDRip-AVC.720p.by.farvis[rutracker.org].mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/0d26955b-dfe0-1063-35b4-880a92bcb1c0/stream.mkv?MediaSourceId=0d26955bdfe0106335b4880a92bcb1c0&Static=true&VideoCodec=h264&AudioCodec=ac3&AudioStreamIndex=1&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=4040d4696f23aed07ece45bb17c4f08d"
[2022-07-07 10:29:05.536 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/2ANNA/Дорога домой.2021.WEB-DL.1080p.HDR.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/4f63e09f-2725-2ba8-8fd2-e8df684761e7/stream.mkv?MediaSourceId=4f63e09f27252ba88fd2e8df684761e7&Static=true&VideoCodec=hevc&AudioCodec=eac3&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Embed&Tag=c283f2659cd1f5c8d1511e8b96fc3080"
[2022-07-07 10:29:05.537 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Шестеро вне закона (2019) WEB-DLRip-AVC__ivanes.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/63816c7e-7665-a169-9067-b9b5487446c1/stream.mkv?MediaSourceId=63816c7e7665a1699067b9b5487446c1&Static=true&VideoCodec=h264&AudioCodec=ac3&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Embed&Tag=6622d75af477b0328b2c17ae400bcf05"
[2022-07-07 10:29:05.539 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/42.2013.BDRip.ELmusic.MVO/42.2013.BDRip.ELmusic.avi", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/afe40801-bf0c-705d-69dc-8a1666357496/stream.avi?MediaSourceId=afe40801bf0c705d69dc8a1666357496&Static=true&VideoCodec=mpeg4&AudioCodec=ac3&AudioStreamIndex=3&api_key=<token>&Tag=7a367941b84f9241a2dd070297b2c261"
[2022-07-07 10:29:05.541 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Abominable.2019.BDRip.x264.960x.rip by Frost O.S.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/96ce4183-d17e-d774-6640-dad5e7f4a1ef/stream.mov?MediaSourceId=96ce4183d17ed7746640dad5e7f4a1ef&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=597da104103ea5afac5d13f5cbabd0a5"
[2022-07-07 10:29:05.542 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Борьба со льдом_2022_WEB-DLRip/Борьба со льдом_2022_WEB-DLRip.avi", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/11dab527-44e2-c5f5-49bf-e23ba5da6112/stream.avi?MediaSourceId=11dab52744e2c5f549bfe23ba5da6112&Static=true&VideoCodec=mpeg4&AudioCodec=ac3&AudioStreamIndex=1&api_key=<token>&Tag=59cc06a07c424a91e4da1d62a2da8b6b"
[2022-07-07 10:29:05.543 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Aloha (HD).mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/ba852245-3be5-d34d-b9e2-f039e4686a6c/stream.mkv?MediaSourceId=ba8522453be5d34db9e2f039e4686a6c&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&api_key=<token>&Tag=3d823f0edbf6d392cf30363a4d44fb42"
[2022-07-07 10:29:05.545 +03:00] [INF] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/media/SHARE/video/Arcane.S01.WEBDL.1080p.Rus.Eng/Arcane.S01E01.WEBDL.1080p.RGzsRutracker.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/6d860225-d798-c394-57db-a84be599a81f/stream.mkv?MediaSourceId=6d860225d798c39457dba84be599a81f&Static=true&VideoCodec=hevc&AudioCodec=ac3&AudioStreamIndex=1&SubtitleStreamIndex=5&api_key=<token>&SubtitleMethod=Embed&Tag=4b4da7ed3bd68961338ee374c2d8bf73"
[2022-07-07 10:29:05.548 +03:00] [ERR] [24] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
   at Emby.Dlna.ContentDirectory.ControlHandler.WriteResult(String methodName, IReadOnlyDictionary`2 methodParams, XmlWriter xmlWriter)
   at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ysharoiko** [comment]
So far i managed to send directly transcoded data from IPTV channel with 	
Home Media Server (UPnP, DLNA, HTTP) version 2.14 from 25.03.2016
with profile samsung tv 2009 (DLNA)
and it shows normally. 
Maybe i can help to find some more details? got some developer tools for uPnP

**Comment by sufferpriest** [comment]
Hi hit same issue, VLC can't show TV Live's any content, only a "TV Live" title(empty folder) shown in VLC DLNA.
version: 10.8.4, linux, x86 ubuntu docker
for movie was ok shown in VLC DLNA, only TV Live failed.
I can see TV channels in jellyfin web.

sudo docker logs -f -n 100 jellyfin
[14:23:07] [ERR] [55] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
   at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
   at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
   at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)

**Comment by Daniel-Svensson** [comment]
This seems like the same or similar to #8200 

Both contains nullreferenceexeption at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem.

Having the same issue since updating to 1.8.4 (1.7.5 did not have the issue).

**Comment by Daniel-Svensson** [comment]
I did a quick troubleshoot of the issue and for my case it seems It (first?) triggered for an iso file in my collection.

For the iso file tile "videoStream" property is null, but the code still tries to access the Codec property leading to the crash.

https://github.com/jellyfin/jellyfin/blob/790f67aac11e5c32bad19126d4e35b2afa259006/MediaBrowser.Model/Dlna/StreamBuilder.cs#L633

I hope this should be easily fixed by someone more accustomed to the code with the help of this information.
- Maybe the dlna code should ignore iso somehow if they are not supported, but I don't know where and how myself

Some additional details from the crash:


The "item" property sent to the method


<HTML>
<head>
<title>Document</title></head>
<body>



  | Name | Value | Type
-- | -- | -- | --
◢ | item | {MediaBrowser.Model.Dto.MediaSourceInfo} | MediaBrowser.Model.Dto.MediaSourceInfo
  | AnalyzeDurationMs | null | int?
  | Bitrate | null | int?
  | BufferMs | null | int?
  | Container | "iso" | string
  | DefaultAudioStreamIndex | null | int?
  | DefaultSubtitleStreamIndex | null | int?
  | ETag | "a8b4aa62dc342e9d067863b90053e245" | string
  | EncoderPath | null | string
  | EncoderProtocol | null | MediaBrowser.Model.MediaInfo.MediaProtocol?
  | Formats | {string[0]} | string[]
  | GenPtsInput | false | bool
  | Id | "4e4f8d8c47d4115f0a0c1a69e844ab10" | string
  | IgnoreDts | false | bool
  | IgnoreIndex | false | bool
  | IsInfiniteStream | false | bool
  | IsRemote | false | bool
  | IsoType | null | MediaBrowser.Model.Entities.IsoType?
  | LiveStreamId | null | string
  | ▶ MediaAttachments | Count = 0 | System.Collections.Generic.IReadOnlyList<MediaBrowser.Model.Entities.MediaAttachment> {System.Collections.Generic.List<MediaBrowser.Model.Entities.MediaAttachment>}
  | ▶ MediaStreams | Count = 0 | System.Collections.Generic.IReadOnlyList<MediaBrowser.Model.Entities.MediaStream> {System.Collections.Generic.List<MediaBrowser.Model.Entities.MediaStream>}
  | Name | "THE_CROODS/ISO" | string
  | OpenToken | null | string
  | Path | "E:\\Movies\\THE_CROODS.iso" | string
  | Protocol | File | MediaBrowser.Model.MediaInfo.MediaProtocol
  | ReadAtNativeFramerate | false | bool
  | ▶ RequiredHttpHeaders | Count = 0 | System.Collections.Generic.Dictionary<string, string>
  | RequiresClosing | false | bool
  | RequiresLooping | false | bool
  | RequiresOpening | false | bool
  | RunTimeTicks | null | long?
  | Size | null | long?
  | SupportsDirectPlay | true | bool
  | SupportsDirectStream | true | bool
  | SupportsProbing | true | bool
  | SupportsTranscoding | true | bool
  | Timestamp | null | MediaBrowser.Model.MediaInfo.TransportStreamTimestamp?
  | TranscodeReasons | 0 | MediaBrowser.Model.Session.TranscodeReason
  | TranscodingContainer | null | string
  | TranscodingSubProtocol | null | string
  | TranscodingUrl | null | string
  | Type | Default | MediaBrowser.Model.Dto.MediaSourceType
  | Video3DFormat | null | MediaBrowser.Model.Entities.Video3DFormat?
  | ▶ VideoStream | null | MediaBrowser.Model.Entities.MediaStream
  | VideoType | Iso | MediaBrowser.Model.Entities.VideoType?



</body>
</HTML>


The code before the crash (it crashes on last instruction)
``` asm
00007FFF63872D17  je          MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaBrowser.Model.Dto.MediaSourceInfo, MediaBrowser.Model.Dlna.VideoOptions)+0939h (07FFF63872FB9h)  
00007FFF63872D1D  mov         rcx,qword ptr [rbp-70h]  
00007FFF63872D21  mov         r11,rcx  
00007FFF63872D24  mov         dword ptr [r15+70h],r10d  
00007FFF63872D28  mov         rcx,qword ptr [rsi+20h]  
00007FFF63872D2C  mov         rdx,qword ptr [rdi+10h]  
00007FFF63872D30  mov         qword ptr [rbp-0E8h],r11  
00007FFF63872D37  mov         r9,r11  
00007FFF63872D3A  mov         r8d,1  
00007FFF63872D40  call        Method stub for: MediaBrowser.Model.Dlna.StreamBuilder.NormalizeMediaSourceFormatIntoSingleContainer(System.String, MediaBrowser.Model.Dlna.DeviceProfile, MediaBrowser.Model.Dlna.DlnaProfileType, MediaBrowser.Model.Dlna.DirectPlayProfile) (07FFF60B8C768h)  
00007FFF63872D45  lea         rcx,[r15+8]  
00007FFF63872D49  mov         rdx,rax  
00007FFF63872D4C  call        CORINFO_HELP_ASSIGN_REF (07FFFBFF1AEB0h)  
00007FFF63872D51  mov         rcx,7FFF60457D58h  
00007FFF63872D5B  mov         edx,1  
00007FFF63872D60  call        CORINFO_HELP_NEWARR_1_OBJ (07FFFBFF1B460h)  
00007FFF63872D65  mov         qword ptr [rbp-198h],rax  
00007FFF63872D6C  mov         r8,qword ptr [rbp-0E0h]  
00007FFF63872D73  mov         rdx,qword ptr [r8+8]  
```

**Comment by Daniel-Svensson** [comment]
This seems to still be an issue

**Comment by ZzZombo** [comment]
Could this issue get more priority? For me it crashes on a folder with valid `.MP4` videos.

**Comment by theopus** [comment]
For anyone facing same problem.
Check "Display a folder view to show plain media folders" in Libraries -> Display Settings.
it will somewhat mitigate issue by providing full file tree while using DLNA

**Comment by yablos** [comment]
The same apply to regular windows dlna browser -> thic pc->network -> "jellyfin dlna server" -> navigate to the folder->and is empty.
Last message from jellyfin the log is:

Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.NullReferenceException: Object reference not set to an instance of an object.

Unfortunately suggestion from @theopus "Display a folder view to show plain media folders", does not mage any difference.

**Comment by felix920506** [comment]
Sample files that this error happens with would be nice as the server team was unsuccessful in recreating the issue.

**Comment by nestingBiscuit** [comment]
I had this exact issue and noticed the 'media info' was missing for some files when using the web interface. To diagnose the issue, I used the webAPI to identify all files with missing codec info, and it turned out that all these files had their file permissions set to 700.

To address this, I changed the permissions to 766 with 'chmod 766 *mp4.' Subsequently, I initiated a library scan for metadata, and this resolved the issue of missing media info in the web interface. Additionally, DLNA functionality now workes once again.

The error I observed in the logs matched the error reported in this thread.

**Comment by Daniel-Svensson** [comment]
For me the issue happens with dvd backups (folder structure with all the files) and blu ray (iso backup).

I am hesitant to share the files due to copyright laws but maybe you have any dvd you can use yourselves?
