### ISSUE TITLE
[Issue]: SMI subtitle format support not working on specific files

### ISSUE THREAD

**Issue by ied206** [jellyfin/jellyfin#8083]
## Summary

.smi (SAMI) subtitles are broken in the latest jellyfin (v10.8.1).
These are listed in the subtitles selection, but not displayed on the video playback screen.

### Steps to reproduce

1. Prepare a video and a .smi subtitle file.
    - This issue happens **only on specific video/sub combinations**. If I pair same .smi file with another video, it works properly.
1. Select the `Undefined - SMI - External` subtitle and play the video with `direct play`.
    - In case of FFmpeg transcoding, the subtitles are successfully displayed.
1. .smi subtitles are not displayed while .srt/.ass works well.

#### Log

I have compared the logs from v10.8.1 (buggy) and v10.7.6 (works).
- On v10.7.6, `MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder` successfully converts .smi file into a .srt, then use it for playback.
- On v10.8.1, `MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder` fails with `Unsupported format: smi` message.

### Jellyfin Version

10.8.1

### Environment

```markdown
- OS: Linux Mint 20.3 (Ubuntu 20.04)
- Virtualization: Docker (jellyfin/jellyfin:latest - dd15a03)
- Clients: Jellyfin Official Client, Firefox
- Browser: Firefox 
- FFmpeg Version: ffmpeg 4.3.2 from docker container
- Playback Method: Jellyfin Official Client
- Hardware Acceleration: VAAPI
- Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles, Studio Images, TMDb
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
ERROR LOG after upgrading to 10.8.1
- .smi subtitles are listed and selectable, but not displayed on video playback.

[2022-07-08 15:02:31.660 +00:00] [ERR] [30] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/cbea99e1-85ee-9056-fdbc-309900791ff2/cbea99e185ee9056fdbc309900791ff2/Subtitles/15/0/Stream.smi".                                                                                                  
System.ArgumentException: Unsupported format: smi
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetWriter(String format)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ConvertSubtitles(Stream stream, String inputFormat, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.GetSubtitle(Guid routeItemId, String routeMediaSourceId, Int32 routeIndex, String routeFormat, Nullable`1 itemId, String mediaSourceId, Nullable`1 index, String format, Nullable`1 endPositionTicks, Boolean copyTimestamps, Boolean addVttTimeMap, Int64 startPositionTicks)
   at lambda_method1032(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)


-----------------
SUCCESS LOG from v10.7.6
- .smi subtitles are successfully displayed.

[2022-07-08 13:53:09.376 +00:00] [INF] [105] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "/usr/lib/jellyfin-ffmpeg/ffmpeg" " -sub_charenc euc-kr -i \"/<SUBTITLE_FILE>.smi\" -c:s srt \"/config/data/subtitles/6/62574ecc-32b8-aeb6-1146-c7995bae16ef.srt\""
[2022-07-08 13:53:09.398 +00:00] [INF] [105] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Setting ass font within "/config/data/subtitles/6/62574ecc-32b8-aeb6-1146-c7995bae16ef.srt"
[2022-07-08 13:53:09.401 +00:00] [INF] [111] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle conversion succeeded for "<SUBTITLE_FILE>.smi"
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/7675657/178025164-0a81a77d-9915-464c-af3d-8860a8a1dce2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ied206** [comment]
I tried resetting the metadata of a movie library, and now the problematic .smi file now works again.
Maybe the issue was related to a v10.7.6 -> v10.8.1 subtitle migration process.

I am closing the issue. If you have any questions, feel free the tag me.
