### ISSUE TITLE
Media downloads failing for unknown reasons

### ISSUE THREAD

**Issue by Medath** [jellyfin/jellyfin#811]
**Describe the bug**
My sister was trying to download three movies (all .mkv files) from my server today. The downloads were going fine, but at some point they just stopped. She lives a few thousand kilometres away, so I can't tell you how exactly she initiated the downloads or if some error message popped up or whatever.

**To Reproduce**
I'm not sure how to reproduce this. The downloads fail for her after some time (she was accessing the server via direct IP in my local network through an openvpn server with some macbook), but I'm unable to reproduce it on my machine running Arch (which is also the server) or on my Android phone (using the web browser).

**Expected behavior**
She is able to download the movies without any issues

**Logs**
(Please note that she started downloading three files at the same time, all of which failed at roughly the same time)
```
[16:25:38] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value) in /repo/SocketHttpListener/Net/HttpListenerResponse.cs:line 89
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 688
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 229
[16:25:38] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value) in /repo/SocketHttpListener/Net/HttpListenerResponse.cs:line 89
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 688
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 229
[16:25:38] [INF] HTTP Response 500 to 192.168.178.52. Time: 781528ms. http://192.168.178.46:8096/emby/Items/3fc3d52fa0e105818fe76c608aff0e33/Download 
[16:25:38] [INF] HTTP Response 500 to 192.168.178.52. Time: 1000960ms. http://192.168.178.46:8096/emby/Items/dbf5bb91c7fa7e54820a892da0a69e8d/Download 
[16:25:39] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value) in /repo/SocketHttpListener/Net/HttpListenerResponse.cs:line 89
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 688
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 229
[16:25:39] [INF] HTTP Response 500 to 192.168.178.52. Time: 783091ms. http://192.168.178.46:8096/emby/Items/508de393f017f68e9f389787b277b7da/Download
```

**Screenshots**
None

**System (please complete the following information):**
 - OS: Docker on Linux
 - Browser: Safari
 - Jellyfin Version: 10.1.0

**Additional context**
None

**Comment by Medath** [comment]
Oh how did I forget to do that? xD
Looks like you're right. Time to troubleshoot :unamused: 
```
Feb  4 16:25:25 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:25:25 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:26:40 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:26:40 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:27:55 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:27:55 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:29:10 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:29:10 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:30:08 raspberrypi ovpn-server[328]: some-profile/183.18.33.120:37349 SIGTERM[soft,remote-exit] received, client-instance exiting
Feb  4 16:30:25 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:30:25 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:31:40 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:31:40 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:32:56 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:32:56 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:34:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:34:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:35:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:35:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:36:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:36:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:37:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:37:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:39:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:39:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:40:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:40:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:41:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:41:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:42:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:42:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:44:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:44:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:45:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:45:27 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:46:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:46:42 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:47:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:47:57 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:49:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:49:12 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:50:28 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:50:28 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:51:43 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:51:43 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:52:58 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Feb  4 16:52:58 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 TLS Error: TLS handshake failed
Feb  4 16:54:07 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 [UNDEF] Inactivity timeout (--ping-restart), restarting
Feb  4 16:54:07 raspberrypi ovpn-server[328]: some-profile/123.123.123.321:16933 SIGUSR1[soft,ping-restart] received, client-instance restarting
```
