### ISSUE TITLE
[Issue]: DLNA does not sends all names

### ISSUE THREAD

**Issue by hetzbh** [jellyfin/jellyfin#8200]
### Please describe your bug

When trying to browse DLNA list from many devices (kodi on TV, PC, Android, VLC on many devices, Samsung TV's built in media player, etc) shows only partial list. On some devices it only shows here "Collections" but not Movies, TV and other media libraries which I have. 

I'm using Jellyfin 10.8.1 on Ubuntu 22 and when trying with VLC to browse DLNA, I see the error which I will enclose in the jellyfin logs section.

### Jellyfin Version

Other

### if other:

10.8.1 official, Ubuntu 22

### Environment

```markdown
- OS: Ubuntu 22
- Virtualization: none
- Clients: VLC, Kodi, others
- Browser:
- FFmpeg Version: one that being installed by Jellyfin on Ubuntu
- Playback Method:
- Hardware Acceleration: nvenc
- Plugins: opensubtitles
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Aug 02 12:37:34 jelly-test jellyfin[2463069]: [12:37:34] [ERR] Error processing control request
Aug 02 12:37:34 jelly-test jellyfin[2463069]: System.NullReferenceException: Object reference not set to an instance of an object.
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.ContentDirectory.ControlHandler.WriteResult(String methodName, IReadOnlyDictionary`2 methodParams, XmlWriter xmlWriter)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
Aug 02 12:37:34 jelly-test jellyfin[2463069]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hetzbh** [comment]
Update: just updated to 10.8.3-1 - still has this issue.

**Comment by abraithwaite** [comment]
Same in 10.8.5
