### ISSUE TITLE
[Issue]: Test failure on alpinelinux

### ISSUE THREAD

**Issue by bl4ckb0ne** [jellyfin/jellyfin#8244]
### Please describe your bug

Hi, I'm the maintainer of the jellyfin package on [Alpinelinux][1].

I started the [upgrade][2] from 10.8.1 to 10.8.3 and the tests are failing with the following error

```
[13:13:29 WRN] Storing keys in a directory '/home/buildozer/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[13:13:29 INF] User profile is available. Using '/home/buildozer/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[13:13:30 INF] Creating key {26cd9188-bece-4935-a9fd-058d4d4569b8} with creation date 2022-08-11 13:13:30Z, activation date 2022-08-11 13:13:30Z, and expiration date 2022-11-09 13:13:30Z.
[13:13:30 WRN] No XML encryptor configured. Key {26cd9188-bece-4935-a9fd-058d4d4569b8} may be persisted to storage in unencrypted form.
[13:13:30 INF] Writing data to file '/home/buildozer/.aspnet/DataProtection-Keys/key-26cd9188-bece-4935-a9fd-058d4d4569b8.xml'.
[13:13:31 INF] There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
  Jellyfin.Server.Implementations.Tests -> /builds/bl4ckb0ne/aports/testing/jellyfin/src/jellyfin-10.8.3/tests/Jellyfin.Server.Implementations.Tests/bin/Debug/net6.0/Jellyfin.Server.Implementations.Tests.dll
Test run for /builds/bl4ckb0ne/aports/testing/jellyfin/src/jellyfin-10.8.3/tests/Jellyfin.Server.Implementations.Tests/bin/Debug/net6.0/Jellyfin.Server.Implementations.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0+68bd10d3aee862a9fbb0bac8b3d474bc323024f3
Copyright (c) Microsoft Corporation.  All rights reserved.
```

Here's the complete build log [build-jellyfin.log](https://github.com/jellyfin/jellyfin/files/9310938/build-jellyfin.log)

We've had some issues with dotnet6 recently but it doesn't seems to be related. Let me know if this is not a Jellyfin issue.

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/jellyfin/APKBUILD
[2]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/37474#note_255039

### Jellyfin Version

Other

### if other:

10.8.3

### Environment

```markdown
- OS: Alpinelinux
- Virtualization: No
- FFmpeg Version: `ffmpeg version 5.1`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
`Reason: Test host process crashed`
Doesn't look like a Jellyfin issue to me?

**Comment by ayakael** [comment]
We suspect a library change sometime along the way - this error only occurs on Alpine's `edge` version. The current stable `3.16` version runs the test suite fine. Have ya'll encountered any issues on bleeding edge platforms?

**Comment by ayakael** [comment]
I did some more tests, and this issue seems to caused by [this bug](https://github.com/jellyfin/jellyfin/issues/8244) that is also affecting Alpine's `dotnet6` package. Thus, it seems unrelated to `Jellyfin`

**Comment by bl4ckb0ne** [comment]
closing as not related to jellyfin
