### ISSUE TITLE
Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel xxx

### ISSUE THREAD

**Issue by kellcomnet2** [jellyfin/jellyfin#8253]
OS: synology DSM
Virtualization: Docker
Jellyfin Version: 10.8.3 latest
Installed Plugins: 
- AudioDB10.8.3.0
- Email Notifications9.0.0.0
- LDAP-Auth14.0.0.0
- MusicBrainz10.8.3.0
- OMDb10.8.3.0
- Playback Reporting13.0.0.0
- Refresh Sparse Metadata0.1.0.0
- Reports15.0.0.0
- Session Cleaner2.0.0.0
- Studio Images10.8.3.0
- TMDb10.8.3.0

This looks similar to #6085 but the error is different enough I felt a new issue was warranted.

My EPG is no longer loading as of a couple of days ago, I figure the source changed something but I have no way of knowing what as I did not keep previous version of the guide data. If it is a formatting/tag issue then I can correct it in my intermediate processing but I am unsure where the problem lays. The below error is seen for each channel in the EPG.

```
2022-08-13 12:58:24.644 +00:00] [ERR] [11] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "TVLAND"
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)

```

[guide.txt](https://github.com/jellyfin/jellyfin/files/9331496/guide.txt)

**Comment by kellcomnet2** [comment]
FYI this was caused by empty categories, leaving issue open as I feel it should gracefully ignore empty entries but issue is resolved by channels dvr in latest pre release.
[Release notes](https://community.getchannels.com/t/channels-xmltv-data-empty-categories/32937?u=kellcomnet)
