### ISSUE TITLE
Jellyfin unable to start when option Networking/LAN networks is out of expected range

### ISSUE THREAD

**Issue by migui06** [jellyfin/jellyfin#8256]
### Please describe your bug

I am running Jellyfin on my Ubuntu 22.04 Desktop, not in a docker install.

I had issues with my DLNA so I followed this issue solution: [#3610](https://github.com/jellyfin/jellyfin/issues/3610#issuecomment-661075230)
But instead of putting my LAN networks to 192.168.1.1/24, I wrote **192.168.1.2/255**
My Jellyfin instance stopped responding with a "**SERVER INTERNAL ERROR**" popup in Jellyfin
, so I restarted it in my Ubuntu Server (systemctl restart Jellyfin)

But it wouldn't open back up, it would always throw errors about my networks settings in the logs and then say "SIGTERM SIGNAL; shutting down":

I am not looking for help, but the because Jellyfin couldn't open back up I had to find this network.xml in my /etc/jellyfin root folder and change the string value manually
I would expect Jellyfin to notice something is wrong, by catching the error or something.

Expected behavior would be: "Not, you cannot do that"

I hope this can help

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Virtualization: Not Docker
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
`[2022-08-13 15:19:53.630 -04:00] [INF] Jellyfin version: "10.8.1"
[2022-08-13 15:19:53.649 -04:00] [INF] Environment Variables: ["[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]"]
[2022-08-13 15:19:53.651 -04:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2022-08-13 15:19:53.652 -04:00] [INF] Operating system: "Linux"
[2022-08-13 15:19:53.652 -04:00] [INF] Architecture: X64
[2022-08-13 15:19:53.652 -04:00] [INF] 64-Bit Process: True
[2022-08-13 15:19:53.652 -04:00] [INF] User Interactive: True
[2022-08-13 15:19:53.652 -04:00] [INF] Processor count: 8
[2022-08-13 15:19:53.652 -04:00] [INF] Program data path: "/var/lib/jellyfin"
[2022-08-13 15:19:53.653 -04:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2022-08-13 15:19:53.653 -04:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2022-08-13 15:19:53.748 -04:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2022-08-13 15:19:53.760 -04:00] [INF] Loading assemblies
[2022-08-13 15:19:53.847 -04:00] [FTL] Error while starting server.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Common.Net.IPObject.NetworkAddressOf(IPAddress address, Byte prefixLength)
   at MediaBrowser.Common.Net.IPNetAddress.Contains(IPAddress address)
   at MediaBrowser.Common.Net.NetworkExtensions.ContainsAddress(Collection`1 source, IPAddress item)
   at Jellyfin.Networking.Manager.NetworkManager.IsInLocalNetwork(IPAddress address)
   at Jellyfin.Networking.Manager.NetworkManager.IsInLocalNetwork(IPObject address)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Jellyfin.Networking.Manager.NetworkManager.CreateCollection(IEnumerable`1 source)
   at Jellyfin.Networking.Manager.NetworkManager.InitialiseLAN(NetworkConfiguration config)
   at Jellyfin.Networking.Manager.NetworkManager.UpdateSettings(Object configuration)
   at Jellyfin.Networking.Manager.NetworkManager..ctor(IConfigurationManager configurationManager, ILogger`1 logger)
   at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-08-13 15:19:53.851 -04:00] [INF] Disposing "CoreAppHost"
[2022-08-13 15:19:53.853 -04:00] [INF] Received a SIGTERM signal, shutting down`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
#8147 should fix that by not using wrongly defined or non-existing (meaning no interface exists that has the IP) addresses.

**Comment by migui06** [comment]
> #8147 should fix that by not using wrongly defined or non-existing (meaning no interface exists that has the IP) addresses.

Ah I see, thanks, so I guess it should eventually come to a future Jellyfin update?
