### ISSUE TITLE
[Issue]: Unable to update user password via API.

### ISSUE THREAD

**Issue by LSchallot** [jellyfin/jellyfin#8287]
### Please describe your bug

When attempting to update a user's password via the API, an error is thrown even though my call appears to be valid.

The following curl command reflects the command I was attempting on my testing server (no issues with username and password being embedded):
`curl -X POST \
  'https://<server_address>/Users/7aa0ddad313c437e83c5f0a3537e25c7/Password' 
  -H 'accept: application/json' 
  -H 'content-type: application/json' 
  -H 'x-emby-token: 7e484db6bf744035be73b05e7ab6359c' 
  -d '{ "CurrentPassword": "283d47a9338ed1100b5fe2a5aff2d1f7c799bfd0", "CurrentPwd": "newPassword", "NewPw": "newPassword123", "ResetPassword": true }'`

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Raspbian
- Virtualization: None
- Clients: cURL API Call
- Browser: None
- FFmpeg Version: 
- Playback Method: Direct Stream
- Hardware Acceleration: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
`[2022-08-20 13:40:36.694 -05:00] [ERR] [206] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Users/7aa0ddad313c437e83c5f0a3537e25c7/Password".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Api.Helpers.RequestHelpers.AssertCanUpdateUser(IAuthorizationContext authContext, HttpRequest requestContext, Guid userId, Boolean restrictUserPreferences)
   at Jellyfin.Api.Controllers.UserController.UpdateUserPassword(Guid userId, UpdateUserPassword request)
   at lambda_method1284(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)`
```

### Please attach any browser or client logs here

`Error processing request.`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LSchallot** [comment]
After looking around a bit more, this seems mostly similar to #7610 in that I am also using an API key and the error is the same stack trace.

**Comment by LSchallot** [comment]
Additional testing has shown that if I authenticate via username/password an supply my token the API call functions as expected.  This only seems to be an issue when using a generated API key.

Functioning example:
`
curl -X POST 
  'https://<server_address>/Users/7aa0ddad313c437e83c5f0a3537e25c7/Password' 
  -H 'accept: application/json' 
  -H 'content-type: application/json' 
  -H 'x-emby-authorization: MediaBrowser Client="Custom Client", Device="Custom Device", DeviceId="1", Version="0.0.1", Token="**********"' 
  -d '{ "CurrentPwd" : "newPassword", "NewPw" : "newPassword123" }'
`
