### ISSUE TITLE
[Issue]: i'cant login to unlock my only administrator account，after enter wrong password too many times

### ISSUE THREAD

**Issue by kkkkllll00** [jellyfin/jellyfin#8372]
### Please describe your bug

After  enter wrong password too many times when i  use the administrator account ,
i **can’t login in my administrator account any more**,
even i try to reset my password.
and i look up the jellyfin documentation,it only describe how to unlock user with the administrator account，and **did not explain how to unlock administrator account**.
When I log in, it is displayed as follows.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows 10
- Version: combined/jellyfin_10.8.4
```

### Jellyfin logs

```shell
[00:18:56] [ERR] [66] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[00:18:56] [INF] [66] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has been denied because this account is currently disabled (IP: 192.168.1.109).
[00:18:56] [ERR] [66] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: [192.168.1.109] The admin account is currently disabled. Please consult with your administrator. URL POST /Users/authenticatebyname.
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/61173650/189171657-ac3eeebe-de3e-44d1-89ba-d7ba51a680b9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
This is not a troubleshooting forum. Please reference https://jellyfin.org/docs/general/getting-help.html for the correct places to ask this type of question.

Our documentation also covers this question in depth. https://jellyfin.org/docs/general/administration/troubleshooting.html#unlock-locked-user-account

**Comment by silentTeee** [comment]
I just want to point out that the SQL commands on the mentioned doc page are out of date and won't work. I already submitted a [pull request](https://github.com/jellyfin/jellyfin-docs/pull/700) with the correct SQL commands and it got merged, but it seems to not be live yet.

Hope this helps

**Comment by thornbill** [comment]
Thanks @silentTeee! The docs page should be updated now. We were having an issue with the CI builds there, but it seems to be resolved after a manual run.
