### ISSUE TITLE
MatroskaKeyframeExtractor - unhandled exception and hanging

### ISSUE THREAD

**Issue by velaar** [jellyfin/jellyfin#8413]
Moving my library from Plex to Jellyfin. It's an amazing project! 

Just want to help. I have 2 files (out of over a 100) that crash MatroskaKeyframeExtractor. One causes an infinite loop (the process never finishes while consuming 100% of a single core CPU and running pread64 of the same address infinitely. Another file produces the following exception:

```
Jellyfin.MediaEncoding.Hls.Extractors.MatroskaKeyframeExtractor: Extracting keyframes from "/mnt/crypt/media/Movies/Moneyball/Moneyball.mkv" using matroska metadata failed
System.InvalidOperationException: SeekHead is missing or does not contain Info, Tracks and Cues positions. SeekHead referencing another SeekHead is not supported
   at Jellyfin.MediaEncoding.Keyframes.Matroska.Extensions.EbmlReaderExtensions.ReadSeekHead(EbmlReader reader) in /home/velaar/.cache/yay/jellyfin/src/jellyfin-10.8.4/src/Jellyfin.MediaEncoding.Keyframes/Matroska/Extensions/EbmlReaderExtensions.cs:line 109
   at Jellyfin.MediaEncoding.Keyframes.Matroska.MatroskaKeyframeExtractor.GetKeyframeData(String filePath) in /home/velaar/.cache/yay/jellyfin/src/jellyfin-10.8.4/src/Jellyfin.MediaEncoding.Keyframes/Matroska/MatroskaKeyframeExtractor.cs:line 25
   at Jellyfin.MediaEncoding.Hls.Extractors.MatroskaKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData) in /home/velaar/.cache/yay/jellyfin/src/jellyfin-10.8.4/src/Jellyfin.MediaEncoding.Hls/Extractors/MatroskaKeyframeExtractor.cs:line 37

```
I wonder if there is a way to skip the files that behave like this. 

Thanks a lot! 
Velaar

**Comment by cvium** [comment]
The exception shouldn't cause any issues as such. The infinite loop points to a bug somewhere, but without the file it might be hard to debug properly
