### ISSUE TITLE
[Bug]: When Casting to Bose 300 Speaker only one song is sent out of a playlist

### ISSUE THREAD

**Issue by cpuetzer** [jellyfin/jellyfin#8418]
### Please describe your bug

When using the JellyFin client or a browser (Chrome, Firefox) if I attempt to cast a playlist only one song is casted to the device and have to manually select and play another song. 
The play bar at the bottom of the screen disappears. 
Please reference attached screenshots.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Ubuntu 20.04.5 LTS
- Virtualization: Yes via TrueNas VM
- Clients: JellyFin Client, Chrome, Firefox
- Browser: Chrome, Firefox
- FFmpeg Version: 10.8.4 JellyFin
- Playback Method: via Chromcast
- Hardware Acceleration: None
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: None
- Base URL: Yes puetzer.org:8096
- Networking: NAT
- Storage: NFS
```

### Jellyfin logs

```shell
Manufacturer: "Bose", ManufacturerUrl: "http://www.bose.com", Headers: [] }
[2022-09-16 14:31:13.742 -04:00] [ERR] Error processing request. URL "POST" "/Sessions/9709f394cfb8aa155b4cc14afa902330/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.SetNextAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SendNextTrackMessage(Int32 currentPlayListItemIndex, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SessionController.Play(String sessionId, PlayCommand playCommand, Guid[] itemIds, Nullable`1 startPositionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 startIndex)
   at lambda_method1278(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-09-16 14:31:13.747 -04:00] [WRN] Slow HTTP Response from "http://192.168.1.102:8096/Sessions/9709f394cfb8aa155b4cc14afa902330/Playing?ItemIds=7ea1f5f8e16224dd4b66c2dfef0dac71&PlayCommand=PlayShuffle" to "192.168.1.2" in 0:00:00.6712186 with Status Code 500
[2022-09-16 14:31:13.877 -04:00] [ERR] Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2022-09-16 14:31:13.877 -04:00] [ERR] Failed to parse xml: 
 "&lt;res duration=&quot;00:06:49.3206272&quot; size=&quot;6561792&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;128000&quot; protocolInfo=&quot;http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.102:8096/audio/36449a72-a6b0-0642-a41e-cd4d257e97f3/stream.mp3?DeviceProfileId=80cb62254ec7464eaadbfa3535612639&amp;amp;DeviceId=4a375562-146d-8790-4bc4-602919a7d6f2&amp;amp;MediaSourceId=36449a72a6b00642a41ecd4d257e97f3&amp;amp;Static=true&amp;amp;Tag=1f4599b844463e1f05f3f695bf635d35&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2022-09-16 14:31:23.932 -04:00] [ERR] Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2022-09-16 14:31:23.933 -04:00] [ERR] Failed to parse xml: 
 "&lt;res duration=&quot;00:06:49.3206272&quot; size=&quot;6561792&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;128000&quot; protocolInfo=&quot;http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.102:8096/audio/36449a72-a6b0-0642-a41e-cd4d257e97f3/stream.mp3?DeviceProfileId=80cb62254ec7464eaadbfa3535612639&amp;amp;DeviceId=4a375562-146d-8790-4bc4-602919a7d6f2&amp;amp;MediaSourceId=36449a72a6b00642a41ecd4d257e97f3&amp;amp;Static=true&amp;amp;Tag=1f4599b844463e1f05f3f695bf635d35&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2022-09-16 14:31:33.983 -04:00] [ERR] Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2022-09-16 14:31:33.984 -04:00] [ERR] Failed to parse xml: 
 "&lt;res duration=&quot;00:06:49.3206272&quot; size=&quot;6561792&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;128000&quot; protocolInfo=&quot;http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.102:8096/audio/36449a72-a6b0-0642-a41e-cd4d257e97f3/stream.mp3?DeviceProfileId=80cb62254ec7464eaadbfa3535612639&amp;amp;DeviceId=4a375562-146d-8790-4bc4-602919a7d6f2&amp;amp;MediaSourceId=36449a72a6b00642a41ecd4d257e97f3&amp;amp;Static=true&amp;amp;Tag=1f4599b844463e1f05f3f695bf635d35&amp;amp;dlnaheaders=true&lt;/res&gt;"
```

### Please attach any screenshots here

Prior to casting
![image](https://user-images.githubusercontent.com/67061016/190708893-a9ff6faf-23d6-434e-bd21-2871afea9f4a.png)
After casting
![image](https://user-images.githubusercontent.com/67061016/190709118-5b7483a2-66fd-40b4-a5bf-8c36ca0c04d5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by folosleg** [comment]
It seems like a general Chromecast issue.
I'm using Jellyfin 10.8.4 with multiple devices, like Chromecast with Google TV, Chromecast Ultra, and such.
If I try to cast a music album, I'm unable to start play any song from it, but the very first one. This is 100% consistent behaviour.
Only a couple of tracks going to play, unable to skip to the next track, but there are exceptions sometimes... It's hard to describe exactly what's happening, doesn't seem like a consistent behaviour. But there's definately no such scenario where playback is flawless.
If you need any further assistance debugging, I'm happy to help!

**Comment by rea-ducks** [comment]
I can't really help on the issue but confirm it.
Running Jellyfin 10.8.8 and casting to Chromecast with Google TV, Google Home Mini and Pioneer X-HM76 all yield the same result: Only the first song is played and I can't jump to the next.

I'd also like help debugging but need advice what to provide. I don't see any errors in logfile.

**Comment by espector** [comment]
I'm having a similar issue - https://github.com/jellyfin/jellyfin/issues/9521
