### ISSUE TITLE
[Issue]: Live TV Playback Permission Issue

### ISSUE THREAD

**Issue by soxrok2212** [jellyfin/jellyfin#8466]
### Please describe your bug

Here's my setup:
1. A "NAS" (just an a samba server with a few TB, CIFS share to Jellyfin
2. Jellyfin, with my transcoding directory on that share
3. HDHomeRun Flex 4k

Here's the issue: I can transcode a movie just fine. No issues writing to my samba share. But when I try to transcode a live TV show, I get a permission error:

```
Sep 28 05:22:16 jellyfin jellyfin[1228]: [05:22:16] [ERR] Error copying live stream SharedHttpStream to /media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts
Sep 28 05:22:16 jellyfin jellyfin[1228]: System.UnauthorizedAccessException: Access to the path '/media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts' is denied.
Sep 28 05:22:16 jellyfin jellyfin[1228]:  ---> System.IO.IOException: Permission denied
Sep 28 05:22:16 jellyfin jellyfin[1228]:    --- End of inner exception stack trace ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
Sep 28 05:22:16 jellyfin jellyfin[1228]: --- End of stack trace from previous location ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(CancellationToken cancellationToken)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync()
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync()
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.<>c__DisplayClass4_0.<<StartStreaming>b__0>d.MoveNext()
Sep 28 05:22:16 jellyfin jellyfin[1228]: --- End of stack trace from previous location ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.<>c__DisplayClass4_0.<<StartStreaming>b__0>d.MoveNext()
Sep 28 05:22:16 jellyfin jellyfin[1228]: [05:22:16] [INF] Deleting temp file /media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts
```

Checking permissions... all looks good here.
```
$ ls -la /media/transcodes/
total 182
drwxrwxrwx 2 jellyfin jellyfin      0 Sep 28 05:22 .
drwxrwxrwx 2 jellyfin jellyfin      0 Sep 28 04:34 ..
-rwxrwxrwx 1 jellyfin jellyfin    207 Sep 28 05:21 4eec306f070e8653e78c67a6c00c1088.m3u8
-rwxrwxrwx 1 jellyfin jellyfin 113740 Sep 28 05:22 4eec306f070e8653e78c67a6c00c10880.ts
-rwxrwxrwx 1 jellyfin jellyfin  65316 Sep 28 05:22 a892d6c7725047fea33d9d836acf0d9a.ts
```

Tried disabling Nvidia T600 for transcoding, same issue.

If I set back the default transcoding location, TV works fine. But I'm just confused why movies would transcode fine to my NAS but live TV would not.

Here's the `smbd.conf` on the NAS:
```
[media]
	comment = Media Server
	path = /storage
	browsable = yes
	read only = no
	valid users = @media //has jellyfin user in it
	create mask = 0644
	directory mask = 0755
	force user = <not the jellyfin user>
	vfs object = fruit streams_xattr
```

And my `/etc/fstab` on my Jellyfin server:
```
//nas/media /media cifs credentials=/home/user/.smbpasswd,uid=jellyfin,gid=jellyfin,iocharset=utf8,file_mode=0777,dir_mode=0777,vers=3.0 0 0
```

Versions:
```
jellyfin-ffmpeg5/unknown,now 5.1.1-2-jammy amd64 [installed,automatic]
jellyfin-server/unknown,now 10.8.5-1 amd64 [installed,automatic]
jellyfin-web/unknown,now 10.8.5-1 all [installed,automatic]
jellyfin/unknown,now 10.8.5-1 all [installed]
```

Any advice?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22
- Virtualization: LXC (Proxmox)
- Clients: LG WebOS 3 homebrew, MacBook Pro M2 (Jellyfin App), iPhone (Jellyfin App)
- Browser:
- FFmpeg Version: 5.1.1-2
- Playback Method:
- Hardware Acceleration: Nvidia T600 and disabled
- Plugins:
- Reverse Proxy: Nginx
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Sep 28 05:22:16 jellyfin jellyfin[1228]: [05:22:16] [ERR] Error copying live stream SharedHttpStream to /media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts
Sep 28 05:22:16 jellyfin jellyfin[1228]: System.UnauthorizedAccessException: Access to the path '/media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts' is denied.
Sep 28 05:22:16 jellyfin jellyfin[1228]:  ---> System.IO.IOException: Permission denied
Sep 28 05:22:16 jellyfin jellyfin[1228]:    --- End of inner exception stack trace ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
Sep 28 05:22:16 jellyfin jellyfin[1228]: --- End of stack trace from previous location ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(CancellationToken cancellationToken)
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync()
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync()
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.<>c__DisplayClass4_0.<<StartStreaming>b__0>d.MoveNext()
Sep 28 05:22:16 jellyfin jellyfin[1228]: --- End of stack trace from previous location ---
Sep 28 05:22:16 jellyfin jellyfin[1228]:    at Emby.Server.Implementations.LiveTv.TunerHosts.SharedHttpStream.<>c__DisplayClass4_0.<<StartStreaming>b__0>d.MoveNext()
Sep 28 05:22:16 jellyfin jellyfin[1228]: [05:22:16] [INF] Deleting temp file /media/transcodes/a892d6c7725047fea33d9d836acf0d9a.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soxrok2212** [comment]
FWIW, I logged into my jellyfin server as the jellyfin user and created a file as that user in /media/transcodes without any issue. I'm not sure if SharedHttpStream is running under a different user/context?

**Comment by soxrok2212** [comment]
This was fixed by ditching SMB in favor of NFS. I wouldn't consider it a solution for this specific issue, so I'll leave it open for now.
