### ISSUE TITLE
[Issue]: Backup Sqlite databases with Litesream

### ISSUE THREAD

**Issue by pettijohn** [jellyfin/jellyfin#8478]
### Please describe your bug

I'm trying to back up the Jellyfin without downtime ([as discussed](https://github.com/jellyfin/jellyfin/discussions/7063)) by using [Litestream](https://github.com/benbjohnson/litestream). Litestream works unless the Sqlite database is opened in exclusive mode ([discussion](https://github.com/benbjohnson/litestream/issues/58), [locking mode](https://www.sqlite.org/pragma.html#pragma_locking_mode)). When attempting to start Jellyfin with Litestream running on `config/data/data/authentication.db`, `library.db`, or `jellyfin.db` I get errors of this form at startup, and Jellyfin fails to start:

```
[13:09:46] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

I suppose this is more of an enhancement request than a bug to open the database in Normal mode instead of Exclusive mode. Or maybe it is an [Emby issue](https://github.com/MediaBrowser/Emby/blob/1d7c2ab4bfebdae31f89fdaabd3b68782ccf495a/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L133).

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 22.0.4
- Virtualization: Docker
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
[13:09:46] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by userbradley** [comment]
This still persists as an issue, and I've been trying to work on this for ages and I hope that maybe version 12 and onwards will start to support external databases.
