### ISSUE TITLE
[Issue]: Unable to get SchedulesDirect Data

### ISSUE THREAD

**Issue by ryantiger658** [jellyfin/jellyfin#8502]
### Please describe your bug

When I run TV Guide update my system throws a much of HTTP exceptions and no data is collected from SchedulesDirect.

I am able to see the Lineup options, but am unable to get the Schedule data.

I have updated and restarted the server, as well as deleted and re-created all of the Live TV settings

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Docker
- Virtualization: Docker
- Clients: All
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
15:46:53] [INF] [26] Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: REDACTED
[15:46:53] [ERR] [26] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel MYST
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannelFromTunerChannel(IListingsProvider provider, ListingsProviderInfo info, ChannelInfo tunerChannel, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[15:46:53] [INF] [26] Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: REDACTED
[15:46:53] [ERR] [26] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)
[15:46:53] [INF] [26] Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: REDACTED
[15:46:53] [ERR] [26] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel DABL
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannelFromTunerChannel(IListingsProvider provider, ListingsProviderInfo info, ChannelInfo tunerChannel, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[15:46:53] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 17 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jedthe3rd** [comment]
Schedules Direct updated their API for SD-JSON. Images now require a user token. There was some abuse occurring I think with that specific functionality. https://www.schedulesdirect.org/news/056/SD-JSON-images-now-require-tokens

**Comment by ryantiger658** [comment]
Unfortunately I am not getting any guide data. Does the user-token apply to standard guide data as well?

**Comment by Bond-009** [comment]
We try to send a `HttpRequestMessage` again if the first one failed, this isn't allowed.
https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/SchedulesDirect.cs#L639
Regression from #4030 @crobibero

**Comment by ryantiger658** [comment]
Hello, I just wanted to see if there was any update. I am still getting the same errors.

**Comment by chibiconsulting** [comment]
Also seeing this as well
Version: 10.8.13
Operating System: Linux
Architecture: Arm64
[2023-12-06 23:43:03.329 -08:00] [INF] Authenticated with Schedules Direct token: "***"
[2023-12-06 23:43:03.338 -08:00] [ERR] Error adding metadata
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.Send(HttpRequestMessage options, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)

**Comment by mega-mac-slice** [comment]
Gave this a shot against https://github.com/jellyfin/jellyfin/pull/10847 running locally and was still having issues:
```
[2024-01-23 04:13:48.816 +00:00] [ERR] [14] Jellyfin.LiveTv.LiveTvManager: Error getting programs for channel "Laff"
System.Net.Http.HttpRequestException: Request failed: Bad Request
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 611
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 624
   at Jellyfin.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 733
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 387
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetEpgChannelFromTunerChannel(IListingsProvider provider, ListingsProviderInfo info, ChannelInfo tunerChannel, CancellationToken cancellationToken) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 403
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 905
   at Jellyfin.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, ActionableProgress`1 progress, CancellationToken cancellationToken) in /root/jellyfin-schedulesdirect-fix/src/Jellyfin.LiveTv/LiveTvManager.cs:line 1171
[2024-01-23 04:13:48.820 +00:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Refresh Guide" Completed after 0 minute(s) and 32 seconds
```

**Comment by felix920506** [comment]
Hi @mega-mac-slice , thanks for testing out the PR. However, it would be better to comment your findings to the PR as opposed to commenting them here.

**Comment by mega-mac-slice** [comment]
Yeah, I wasn't really sure where we wanted information to trail off on - this seemed like the better option.

I poked a bit more this evening and have posted to https://forums.schedulesdirect.org/viewtopic.php?f=5&t=3293 and am currently awaiting moderation to be visible.

It might be on SDs side - setting breakpoints in master's `Jellyfin.Server` I see we're calling out to:

```
> https://json.schedulesdirect.org/20141201/lineups/USA-OTA-77835?token=<redacted>
{
  "response": "LINEUP_NOT_FOUND",
  "code": 2101,
  "serverID": "20141201.web",
  "message": "Lineup not in account. Add lineup to account before requesting mapping.",
  "datetime": "2024-01-24T00:39:51Z"
}
```
It looks like other's in this issue are also encountering issues with OTA/Antenna channels so I'm hoping it's related.

I also have a working Lineup configured so can kind of confirm this isn't really a hard break in the Jellyfin code.

**Comment by barronpm** [comment]
Based on the logs I'm seeing, I think jf#10847 solves the issue on our side - requests are now correctly re-tried, the response from SD is an error, meaning the remaining issue should be either on your end, or SD.

**Comment by mega-mac-slice** [comment]
Working off of #10847 - if I go to add a new Lineup I get the following:
```
[17:15:27] [INF] [28] Jellyfin.LiveTv.Listings.SchedulesDirect: Headends on account 
[17:15:28] [INF] [28] Jellyfin.LiveTv.Listings.SchedulesDirect: Adding new LineUp 
[17:15:31] [INF] [24] Jellyfin.LiveTv.EmbyTV.EmbyTV: Discovered tuner device HD Homerun at http://192.168.1.197
[17:15:31] [INF] [24] Jellyfin.LiveTv.EmbyTV.EmbyTV: Discovered tuner device HD Homerun at http://192.168.1.197
[17:15:31] [INF] [24] Jellyfin.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: <redact>
[17:15:31] [ERR] [28] Jellyfin.LiveTv.Listings.SchedulesDirect: Request to https://json.schedulesdirect.org/20141201/lineups/USA-OTA-77835 failed with response {"response":"LINEUP_NOT_FOUND","code":2101,"serverID":"20141201.web","message":"Lineup not in account. Add lineup to account before requesting mapping.","datetime":"2024-01-24T23:15:31Z"}
[17:15:32] [ERR] [28] Jellyfin.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.Net.Http.HttpRequestException: Request failed: Bad Request
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 613
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 626
   at Jellyfin.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 735
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 387
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 358
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 336
[17:15:32] [INF] [28] Jellyfin.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[17:15:32] [INF] [24] Jellyfin.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: a8dec9d7833018a017061bf2e72705b8
[17:15:32] [ERR] [24] Jellyfin.LiveTv.Listings.SchedulesDirect: Request to https://json.schedulesdirect.org/20141201/lineups/USA-OTA-77835 failed with response {"response":"LINEUP_NOT_FOUND","code":2101,"serverID":"20141201.web","message":"Lineup not in account. Add lineup to account before requesting mapping.","datetime":"2024-01-24T23:15:32Z"}
[17:15:33] [ERR] [24] Jellyfin.LiveTv.EmbyTV.EmbyTV: Error adding metadata
System.Net.Http.HttpRequestException: Request failed: Bad Request
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 613
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 626
   at Jellyfin.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 735
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 387
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 358
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 336
[17:15:33] [INF] [24] Jellyfin.LiveTv.Listings.SchedulesDirect: Authenticated with Schedules Direct token: d6a6a5887b1daba052aed8bb44fc3d54
[17:15:33] [ERR] [28] Jellyfin.LiveTv.Listings.SchedulesDirect: Request to https://json.schedulesdirect.org/20141201/lineups/USA-OTA-77835 failed with response {"response":"LINEUP_NOT_FOUND","code":2101,"serverID":"20141201.web","message":"Lineup not in account. Add lineup to account before requesting mapping.","datetime":"2024-01-24T23:15:33Z"}
[17:15:34] [ERR] [28] Jellyfin.LiveTv.LiveTvManager: Error getting programs for channel KBTX-DT
System.Net.Http.HttpRequestException: Request failed: Bad Request
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 613
   at Jellyfin.LiveTv.Listings.SchedulesDirect.Request[T](HttpRequestMessage message, Boolean enableRetry, ListingsProviderInfo providerInfo, CancellationToken cancellationToken, HttpCompletionOption completionOption) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 626
   at Jellyfin.LiveTv.Listings.SchedulesDirect.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs:line 735
   at Jellyfin.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken) in /home/me/dev/src/jellyfin/src/Jellyfin.LiveTv/EmbyTV/EmbyTV.cs:line 387
 ```
 I definitely showed up to the SD Forums a little lost but Robert was nice enough to answer me - https://forums.schedulesdirect.org/viewtopic.php?p=10954#p10954
 
 Going off of their information I guess I'm either miss-understanding how to configure a Lineup in Jellyfin - or that somewhere in Jellyfin there is a post/create/update call that might be silently failing when adding a Lineup to an account.
 
 I'm assuming this is where I am adding a Lineup under - http://localhost:8096/web/#/dashboard/livetv/guide?type=schedulesdirect&id=68f6e0b8a7934c75b869ac7b67ffd096
 
![Screenshot from 2024-01-24 17-24-51](https://github.com/jellyfin/jellyfin/assets/25651292/2ead14a9-f903-460c-b1fa-4aaede764b30)

**Comment by mega-mac-slice** [comment]
```
me@me-AK50:~/dev/src/jellyfin$ git diff
diff --git a/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs b/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs
index bf1b53237..777260aef 100644
--- a/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs
+++ b/src/Jellyfin.LiveTv/Listings/SchedulesDirect.cs
@@ -608,7 +608,7 @@ namespace Jellyfin.LiveTv.Listings
 
             if (!enableRetry || (int)response.StatusCode >= 500)
             {
-                _logger.LogError("Request to {Url} failed with response {Response}", message.RequestUri, response.Content);
+                _logger.LogError("Request to {Url} failed with response {1}", message.RequestUri, await response.Content.ReadAsStringAsync().ConfigureAwait(false));
 
                 throw new HttpRequestException(
                     string.Format(CultureInfo.InvariantCulture, "Request failed: {0}", response.ReasonPhrase),
@@ -661,7 +661,9 @@ namespace Jellyfin.LiveTv.Listings
 
             using var options = new HttpRequestMessage(HttpMethod.Put, ApiUrl + "/lineups/" + info.ListingsId);
             options.Headers.TryAddWithoutValidation("token", token);
-            using var response = await _httpClientFactory.CreateClient(NamedClient.Default).SendAsync(options, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
+            using var client = _httpClientFactory.CreateClient(NamedClient.Default);
+            using var response = await client.SendAsync(options, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
+            _logger.LogInformation("[AddLineupToAccount] Request to {Url} failed with response {1}", options.RequestUri, await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false));
         }
 
         private async Task<bool> HasLineup(ListingsProviderInfo info, CancellationToken cancellationToken)
```

```
[17:42:07] [INF] [16] Jellyfin.LiveTv.Listings.SchedulesDirect: Adding new LineUp 
[17:42:07] [INF] [24] Jellyfin.LiveTv.Listings.SchedulesDirect: [AddLineupToAccount] Request to https://json.schedulesdirect.org/20141201/lineups/USA-OTA-77385 failed with response {"response":"MAX_LINEUPS","code":4101,"serverID":"20141201.web","message":"Exceeded number of lineups for this account.","datetime":"2024-01-24T23:42:07Z"}
```
Yeah - guessing this is something I need to follow up with SD. I wonder if a delete is also failing somewhere - I only just got setup with SD so can't imagine I've gone too crazy - unless the limit is literally 1.

**Comment by mega-mac-slice** [comment]
https://github.com/SchedulesDirect/JSON-Service/wiki/API-20141201#getting-status

Calling that I can see that `maxLineups` is 4 - iterating over those and deleting them seemed to get me out of this situation and allowed me to add SD lineups in Jellyfin without errors.

**Comment by ryantiger658** [comment]
> https://github.com/SchedulesDirect/JSON-Service/wiki/API-20141201#getting-status
> 
> Calling that I can see that `maxLineups` is 4 - iterating over those and deleting them seemed to get me out of this situation and allowed me to add SD lineups in Jellyfin without errors.

THANK YOU!!! This worked for me too
