### ISSUE TITLE
[Issue]: web server not start - probably conflict with lighttpd

### ISSUE THREAD

**Issue by msa2020user** [jellyfin/jellyfin#8509]
### Please describe your bug

I have been using Jellifin for at least 3 years, on MAC, I recently installed Lighttpd server using brew.sh, and somehow Jellyfin stopped working. Lighttpd uses port 8011.
I tried to start Jellyfin with Lighttpd started or stopped, nothing change.

This is my configuration:
macOS Monterey version 12.6
Jellyfin version 10.8.5
Lighttpd version 1.4.67 (port 8011)

➜  ~ lsof -i -P | grep -i "listen"
ControlCe   546 msa  20u  IPv4 0xd25cde4cccc49ae1      0t0  TCP *:7000 (LISTEN)
ControlCe   546 msa   21u  IPv6 0xd25cde47ffbd58d9      0t0  TCP *:7000 (LISTEN)
ControlCe   546 msa   22u  IPv4 0xd25cde4cccc48591      0t0  TCP *:5000 (LISTEN)
ControlCe   546 msa   23u  IPv6 0xd25cde47ffbd5fd9      0t0  TCP *:5000 (LISTEN)
rapportd    563 msa    3u  IPv4 0xd25cde4ccc3cf591      0t0  TCP *:58733 (LISTEN)
rapportd    563 msa    4u  IPv6 0xd25cde47fff55cd9      0t0  TCP *:58733 (LISTEN)
LogiMgrDa   607 msa    4u  IPv4 0xd25cde4ccc53e591      0t0  TCP *:59866 (LISTEN)
lighttpd  19795 msa    4u  IPv4 0xd25cde4ccbb6bae1      0t0  TCP *:8011 (LISTEN)

Some suggestions? thanks

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS: macOS Monterey version 12.6
- Virtualization:
- Clients:
- Browser: Safari and Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-10-07 11:01:24.704 +03:00] [INF] [1] Main: Jellyfin version: "10.8.5"
[2022-10-07 11:01:24.741 +03:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /Users/msa/.local/share/jellyfin/log]"]
[2022-10-07 11:01:24.743 +03:00] [INF] [1] Main: Arguments: ["/Applications/Jellyfin.app/Contents/MacOS/jellyfin.dll", "--webdir", "/Applications/Jellyfin.app/Contents/Resources/jellyfin-web"]
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: Operating system: "macOS"
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: Architecture: X64
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: 64-Bit Process: True
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: User Interactive: True
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: Processor count: 8
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: Program data path: "/Users/msa/.local/share/jellyfin"
[2022-10-07 11:01:24.745 +03:00] [INF] [1] Main: Web resources path: "/Applications/Jellyfin.app/Contents/Resources/jellyfin-web"
[2022-10-07 11:01:24.746 +03:00] [INF] [1] Main: Application directory: "/Applications/Jellyfin.app/Contents/MacOS/"
[2022-10-07 11:01:24.922 +03:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/Users/msa/.cache/jellyfin"
[2022-10-07 11:01:24.954 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2022-10-07 11:01:25.088 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-10-07 11:01:25.088 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2022-10-07 11:01:25.089 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-10-07 11:01:25.089 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2022-10-07 11:01:25.089 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2022-10-07 11:01:27.122 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.5.0"
[2022-10-07 11:01:27.122 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.5.0"
[2022-10-07 11:01:27.123 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.5.0"
[2022-10-07 11:01:27.123 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.5.0"
[2022-10-07 11:01:27.123 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.5.0"
[2022-10-07 11:01:27.177 +03:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"MigrateUserDatabase"'
[2022-10-07 11:01:27.181 +03:00] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateUserDb: Migrating the user database may take a while, do not stop Jellyfin.
[2022-10-07 11:01:27.268 +03:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"MigrateUserDatabase"'
System.InvalidOperationException: There was an error reflecting type 'MediaBrowser.Model.Users.UserPolicy'.
 ---> System.InvalidOperationException: Cannot serialize member 'MediaBrowser.Model.Users.UserPolicy.AccessSchedules' of type 'Jellyfin.Data.Entities.AccessSchedule[]', see inner exception for more details.
 ---> System.InvalidOperationException: Jellyfin.Data.Entities.AccessSchedule cannot be serialized because it does not have a parameterless constructor.
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.GetPropertyModel(PropertyInfo propertyInfo)
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.<>c.<GetSerializer>b__1_0(String _, Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.GetSerializer(Type type)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.Routines.MigrateUserDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-10-07 11:01:27.282 +03:00] [FTL] [1] Main: Error while starting server.
System.InvalidOperationException: There was an error reflecting type 'MediaBrowser.Model.Users.UserPolicy'.
 ---> System.InvalidOperationException: Cannot serialize member 'MediaBrowser.Model.Users.UserPolicy.AccessSchedules' of type 'Jellyfin.Data.Entities.AccessSchedule[]', see inner exception for more details.
 ---> System.InvalidOperationException: Jellyfin.Data.Entities.AccessSchedule cannot be serialized because it does not have a parameterless constructor.
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.GetPropertyModel(PropertyInfo propertyInfo)
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.<>c.<GetSerializer>b__1_0(String _, Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.GetSerializer(Type type)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.Routines.MigrateUserDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-10-07 11:01:27.283 +03:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2022-10-07 11:01:27.292 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2022-10-07 11:01:27.293 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2022-10-07 11:01:27.293 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2022-10-07 11:01:27.293 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2022-10-07 11:01:27.296 +03:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neilsb** [comment]
It looks like it may be a problem with one of your XML configuration files.   The best place for assistance with this would be our troubleshooting room.  Details are available on our  [Contact Page](https://jellyfin.org/contact)

**Comment by msa2020user** [comment]
Actually I uninstalled Lighttpd... I have no time to do further tests actually. Probably I need to do a test with a French installation of Lighttpd and after Jellyfin.

**Comment by cvium** [comment]
Lighttpd is really not to blame

**Comment by Bond-009** [comment]
A migration for the user database is failing, possibly because your install is so old.
I would recommend reinstalling Jellyfin and deleting all jellyfin data (Should be mostly in /Users/msa/.local/share/jellyfin for you )
