### ISSUE TITLE
[Issue]: Tasks Extracting keyframes get a error

### ISSUE THREAD

**Issue by KeepNaivety3** [jellyfin/jellyfin#8513]
### Please describe your bug

When I run the Extracting keyframes task, there is an error in the console. The running task ended, but ffprobe is still running and reading the file with errors.
```
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.Specials.S00E04.2017.1080p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.S01E02.2012.2160p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.S06E11.2017.2160p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
```

Mediainfo from those video
```
General
Complete name                            : E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.S01E02.2012.2160p.bilibili.WEB-DL.H264.AAC-KN233.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 3.35 GiB
Duration                                 : 24 min 13 s
Overall bit rate                         : 19.8 Mb/s
Movie name                               : 第二话 丰岛区驹込的煮鱼套餐
Album                                    : 孤独的美食家 第一季
Description                              : 井之头五郎(松重丰 饰)独自经营着一家杂货店，他的小店虽然不是实体店，却接到不少客人的订单。每次接单他都亲自登门拜访客户，也因此发现了隐藏在城市里各个角落的美食。每当完成工作任务后，饥肠辘辘的他放下一切，专心地寻找着东京街头巷尾能勾起他食欲的小店，美食总是与他不期而遇。香喷喷的烤鸡肉串、热辣的无汤担担面、一个人的美味烤肉、入口即化的静冈关东煮、香脆可口的炸猪排套餐等等，每当沉浸在一个人享受美食的过程中，井之头五郎内心除了美味心无旁骛，填饱肚子后烦恼也一扫而光。 / 本剧是根据久住昌之创作、谷口二郎作画的同名漫画改编而成，运用了类似纪录片的描述方式，其中剧中登场的餐馆全部都是真实存在的，每集之后更有作者亲自走访剧中小店，采访老板并且品尝更多特色美食。
Writing application                      : Lavf59.27.100
Cover                                    : Yes

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 24 min 13 s
Bit rate                                 : 19.4 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 29.412 FPS
Maximum frame rate                       : 16 000.000 FPS
Original frame rate                      : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.078
Stream size                              : 3.29 GiB (98%)
Writing library                          : BiliBili H264 Encoder v1.0
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
mdhd_Duration                            : 1453785
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 24 min 13 s
Bit rate mode                            : Constant
Bit rate                                 : 320 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 55.5 MiB (2%)
Default                                  : Yes
Alternate group                          : 1

```

### Jellyfin Version

10.8.0

### if other:

Windows build from nyanmisaka/jellyfin

### Environment

```markdown
- OS: Windows11
- Virtualization: no
- Clients: Chrome
- Browser: Chrome
- FFmpeg Version: ffmpeg version 5.1.1-Jellyfin 
- Playback Method: 
- Hardware Acceleration: none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: server
- Storage: local
```

### Jellyfin logs

```shell
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.Specials.S00E04.2017.1080p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.S01E02.2012.2160p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[00:01:59] [ERR] [20] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from E:\Videos\test\Solitary Gourmet\Solitary.Gourmet.S06E11.2017.2160p.bilibili.WEB-DL.H264.AAC-KN233.mp4 using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/101695437/194603241-bb496200-d30d-479a-b0bd-7e9fe2bb192d.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Fixed by #8516 and #8517

**Comment by drspangle** [comment]
I'm running 10.8.5 X64 in Windows 10 with ffmpeg version 5.1.2-Jellyfin with VAAPI. I'm seeing the same exact error message and symptoms. Here's a log snippet:

```
[2022-10-20 18:40:03.211 -04:00] [ERR] [16] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from "D:\TV\Star Trek Voyager\Season 05\Star Trek Voyager S05E06 SD DVD.avi" using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[2022-10-20 18:40:06.673 -04:00] [ERR] [16] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from "D:\TV\Cops\Season 8\Cops - S08E15 - New Orleans, LA SDTV.avi" using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[2022-10-20 18:40:07.436 -04:00] [ERR] [16] Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor: Extracting keyframes from "D:\TV\Beast Machines - Transformers\Season 1\Beast Machines - Transformers - S01E13 - End of the Line SDTV.avi" using ffprobe failed
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.ParseStream(StreamReader reader)
   at Jellyfin.MediaEncoding.Keyframes.FfProbe.FfProbeKeyframeExtractor.GetKeyframeData(String ffProbePath, String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.FfProbeKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
```

**Comment by cvium** [comment]
The fix is not out yet
