### ISSUE TITLE
[Issue]: Unable to start as normal user

### ISSUE THREAD

**Issue by silajim** [jellyfin/jellyfin#8552]
### Please describe your bug

I just installed jellyfin for the first time and I am getting this error "Could not apply migration 'MigrateAuthenticationDatabase'" 
I am running Jellyfin 10.8.5, there was an issue with the /var/lib/jellyfin folder (it had the wrong group) after I fixed it, this propper up. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 20.04 LTS 
Not run in the docker image, normal apt install following the web page.
```

### Jellyfin logs

```shell
[22:20:39] [INF] Jellyfin version: 10.8.5
[22:20:39] [INF] Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]"]
[22:20:39] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir", "/usr/share/doc/jellyfin-web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[22:20:39] [INF] Operating system: Linux
[22:20:39] [INF] Architecture: X64
[22:20:39] [INF] 64-Bit Process: True
[22:20:39] [INF] User Interactive: True
[22:20:39] [INF] Processor count: 14
[22:20:39] [INF] Program data path: /var/lib/jellyfin
[22:20:39] [INF] Web resources path: /usr/share/doc/jellyfin-web
[22:20:39] [INF] Application directory: /usr/lib/jellyfin/bin/
[22:20:40] [DBG] Skipping migration 'CreateNetworkConfiguration' since it is already applied
[22:20:40] [INF] Setting cache path: /var/cache/jellyfin
[22:20:40] [INF] Loading assemblies
[22:20:40] [DBG] Creating instance of Jellyfin.Server.Migrations.MigrationsFactory
[22:20:40] [DBG] Refreshing interfaces.
[22:20:40] [DBG] Discovered 4 interfaces.
[22:20:40] [DBG] Interfaces addresses : [192.168.1.5/24,192.168.1.8/24,172.17.0.1/16,127.0.0.1/8]
[22:20:40] [DBG] Refreshing LAN information.
[22:20:40] [DBG] Using LAN interface addresses as user provided no LAN details.
[22:20:40] [INF] Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:20:40] [INF] Defined LAN exclusions : []
[22:20:40] [INF] Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[22:20:40] [DBG] Invalid or unknown object vEthernet*.
[22:20:40] [INF] Using bind addresses: []
[22:20:40] [INF] Using bind exclusions: []
[22:20:40] [DBG] Found API endpoints in plugin MediaBrowser.Providers, Version=10.8.5.0, Culture=neutral, PublicKeyToken=null
[22:20:41] [DBG] Creating instance of Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider
[22:20:41] [DBG] Creating instance of Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider
[22:20:41] [DBG] Creating instance of Jellyfin.Server.Implementations.Users.InvalidAuthProvider
[22:20:42] [DBG] Creating instance of MediaBrowser.Providers.Plugins.Tmdb.Plugin
[22:20:42] [INF] Loaded plugin: TMDb 10.8.5.0
[22:20:42] [DBG] Creating instance of MediaBrowser.Providers.Plugins.StudioImages.Plugin
[22:20:42] [INF] Loaded plugin: Studio Images 10.8.5.0
[22:20:42] [DBG] Creating instance of MediaBrowser.Providers.Plugins.Omdb.Plugin
[22:20:42] [INF] Loaded plugin: OMDb 10.8.5.0
[22:20:42] [DBG] Creating instance of MediaBrowser.Providers.Plugins.MusicBrainz.Plugin
[22:20:42] [INF] Loaded plugin: MusicBrainz 10.8.5.0
[22:20:42] [DBG] Creating instance of MediaBrowser.Providers.Plugins.AudioDb.Plugin
[22:20:42] [INF] Loaded plugin: AudioDB 10.8.5.0
[22:20:42] [DBG] Creating instance of Emby.Server.Implementations.Library.CoreResolutionIgnoreRule
[22:20:42] [DBG] Creating instance of Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider
[22:20:42] [DBG] Creating instance of Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider
[22:20:42] [DBG] Creating instance of Emby.Server.Implementations.Channels.ChannelDynamicMediaSourceProvider
[22:20:42] [DBG] Creating instance of Emby.Notifications.CoreNotificationTypes
[22:20:42] [DBG] Skipping migration 'DisableTranscodingThrottling' since it is already applied
[22:20:42] [DBG] Skipping migration 'CreateLoggingConfigHeirarchy' since it is already applied
[22:20:42] [DBG] Skipping migration 'MigrateActivityLogDatabase' since it is already applied
[22:20:42] [DBG] Skipping migration 'RemoveDuplicateExtras' since it is already applied
[22:20:42] [DBG] Skipping migration 'AddDefaultPluginRepository' since it is already applied
[22:20:42] [DBG] Skipping migration 'MigrateUserDatabase' since it is already applied
[22:20:42] [DBG] Skipping migration 'ReaddDefaultPluginRepository' since it is already applied
[22:20:42] [DBG] Skipping migration 'MigrateDisplayPreferencesDatabase' since it is already applied
[22:20:42] [DBG] Skipping migration 'RemoveDownloadImagesInAdvance' since it is already applied
[22:20:42] [DBG] Skipping migration 'AddPeopleQueryIndex' since it is already applied
[22:20:42] [INF] Applying migration 'MigrateAuthenticationDatabase'
[22:20:42] [ERR] Could not apply migration 'MigrateAuthenticationDatabase'
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateAuthenticationDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[22:20:42] [FTL] Error while starting server.
CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
   at Jellyfin.Server.Migrations.Routines.MigrateAuthenticationDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[22:20:42] [INF] Running query planner optimizations in the database... This might take a while
[22:20:42] [INF] Disposing CoreAppHost
[22:20:42] [INF] Disposing MusicBrainzAlbumProvider
[22:20:42] [INF] Disposing EmbyTV
[22:20:42] [INF] Disposing SchedulesDirect
[22:20:42] [INF] Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
> unable to open database file

You have a permissions issue

**Comment by silajim** [comment]
Any idea which file? Because the debug does not say anything. Nor does the log file.


-------- Original message --------
From: Cody Robibero ***@***.***>
Date: 10/15/22 03:52 (GMT+01:00)
To: jellyfin/jellyfin ***@***.***>
Cc: Michail ***@***.***>, Author ***@***.***>
Subject: Re: [jellyfin/jellyfin] [Issue]: Unable to start as normal user (Issue #8552)


unable to open database file

You have a permissions issue

**Comment by crobibero** [comment]
jellyfin.db

**Comment by silajim** [comment]
The permissions are correct, aren't they? 

> -rwxrwxrwx 1 jellyfin jellyfin 155648 Oct 14 21:08 jellyfin.db
-rwxrwxrwx 1 jellyfin jellyfin 172032 Oct 14 22:20 library.db
-rwxrwxrwx 1 jellyfin jellyfin      0 Oct 14 22:20 library.db-journal

**Comment by silajim** [comment]
I correct myself for me the proper owner is jellyfin:adm it also seems I had an old installation in the server after a purge of everything and reinstall it worked
