### ISSUE TITLE
ffmpeg attachment extraction failed for file

### ISSUE THREAD

**Issue by soultaco83** [jellyfin/jellyfin#8607]
Created pastebins as showing body was too long

**Media Info of the file**
https://pastebin.com/aN1m1B3y

**Logs**
https://pastebin.com/MTNMxWRy

```
[2022-10-22 02:55:04.805 -04:00] [ERR] [55] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/83611ded-c61c-1d9e-726b-d0ee92f3291e/83611dedc61c1d9e726bd0ee92f3291e/Attachments/14".
System.InvalidOperationException: ffmpeg attachment extraction failed for file:"/mnt/plex/anime/Subbed only/Shinobi no Ittoki (2022)/Season 1/S01E003 - Quirks of Fate(Subbed).mkv" to /config/data/data/attachments/a/aed3dd94-58be-c18d-dbde-ece46dd73e50
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAttachmentInternal(String inputPath, Int32 attachmentStreamIndex, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAttachment(String inputFile, MediaSourceInfo mediaSource, Int32 attachmentStreamIndex, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetReadableFile(String mediaPath, String inputFile, MediaSourceInfo mediaSource, MediaAttachment mediaAttachment, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetAttachmentStream(MediaSourceInfo mediaSource, MediaAttachment mediaAttachment, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetAttachment(BaseItem item, String mediaSourceId, Int32 attachmentStreamIndex, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.VideoAttachmentsController.GetAttachment(Guid videoId, String mediaSourceId, Int32 index)
   at lambda_method1383(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-10-22 02:55:04.811 -04:00] [ERR] [76] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg attachment extraction failed for "file:\"/mnt/plex/anime/Subbed only/Shinobi no Ittoki (2022)/Season 1/S01E003 - Quirks of Fate(Subbed).mkv\"" to "/config/data/data/attachments/0/0d4f69b3-4654-c761-355d-acd0d032bfde"
[2022-10-22 02:55:04.812 -04:00] [ERR] [76] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/83611ded-c61c-1d9e-726b-d0ee92f3291e/83611dedc61c1d9e726bd0ee92f3291e/Attachments/11".
System.InvalidOperationException: ffmpeg attachment extraction failed for file:"/mnt/plex/anime/Subbed only/Shinobi no Ittoki (2022)/Season 1/S01E003 - Quirks of Fate(Subbed).mkv" to /config/data/data/attachments/0/0d4f69b3-4654-c761-355d-acd0d032bfde
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAttachmentInternal(String inputPath, Int32 attachmentStreamIndex, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAttachment(String inputFile, MediaSourceInfo mediaSource, Int32 attachmentStreamIndex, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetReadableFile(String mediaPath, String inputFile, MediaSourceInfo mediaSource, MediaAttachment mediaAttachment, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetAttachmentStream(MediaSourceInfo mediaSource, MediaAttachment mediaAttachment, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.GetAttachment(BaseItem item, String mediaSourceId, Int32 attachmentStreamIndex, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.VideoAttachmentsController.GetAttachment(Guid videoId, String mediaSourceId, Int32 index)
   at lambda_method1383(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-10-22 02:55:04.986 -04:00] [INF] [16] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2022-10-22 02:55:04.986 -04:00] [INF] [16] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/transcode/728a784b9fefea2ee07784c7cd9a33a6.m3u8"
[2022-10-22 02:55:06.487 -04:00] [INF] [16] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.5" playing "Quirks of Fate". Stopped at "388065" ms
```

**FFmpeg Logs**
https://pastebin.com/b5GFvJqY

**Stats for Nerds Screenshots**
N/A unable to get that far

**Server System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.8.5
 - Hardware settings & device: Nvidia 2060 for Transcoding with AMD 3900x CPU
 - Reverse proxy: nginx is enabled. Testing done locally not through proxy
 - Other hardware notes: unraid Docker image
 
**Client System (please complete the following information):**
 - Device: Computer
 - OS: Windows
 - Client: Web/Browser
 - Browser (if Web client): Chrome, Firefox, Edge (all used for testing)
 - Client and Browser Version: 
 - Chrome Version: 106.0.5249.119 (Official Build) (64-bit)

**Comment by soultaco83** [comment]
--Update: As of now I believe I fixed the issue. I ended up deleted all of the data from the database table mediaattachments located in the Library.db folder. Once I did that. I ran a library scan so that it could regenerate missing data and no more errors on the files that were issues. I will need to keep a close eye on this though.
