### ISSUE TITLE
[Issue]: Can't play any file via DLNA - FFmpeg "Invalid argument"

### ISSUE THREAD

**Issue by JolanGorges** [jellyfin/jellyfin#8680]
### Please describe your bug

I am using the default settings and have only enabled the DLNA server. I can't play any file.

I think the problem is with the query string that ends up in the FFmpeg output file as you can see in the FFmpeg logs.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients: Orange Sagemcom Decodeur TV UHD (set-top box)
- Browser: None
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Remux
- Hardware Acceleration: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2022-11-02 20:44:50.508 +01:00] [DBG] [9] Emby.Dlna.Main.DlnaEntryPoint: Attempting to create PlayToController from location http://192.168.1.14:42300/description.xml
[2022-11-02 20:44:50.604 +01:00] [DBG] [16] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: True:
[2022-11-02 20:44:50.607 +01:00] [DBG] [16] Jellyfin.Networking.Manager.NetworkManager: "Any IP4 Address": External request received, but no WAN interface found. Need to route through internal network.
[2022-11-02 20:44:50.608 +01:00] [DBG] [16] Jellyfin.Networking.Manager.NetworkManager: "Any IP4 Address": GetBindInterface: Matched first internal interface. "192.168.1.20"
[2022-11-02 20:44:50.611 +01:00] [DBG] [16] Emby.Dlna.Main.DlnaEntryPoint: Dlna Device.Start
[2022-11-02 20:44:50.616 +01:00] [INF] [16] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
DeviceIdentification { FriendlyName: "Décodeur TV UHD", ModelNumber: "1.7.19", SerialNumber: "80222878", ModelName: "SoftAtHome Media Renderer", ModelDescription: "DLNA 1.5 Compliant Media Renderer from SoftAtHome", ModelUrl: "http://www.softathome.com", Manufacturer: "SoftAtHome", ManufacturerUrl: "http://www.softathome.com", Headers: [] }
[2022-11-02 20:44:50.625 +01:00] [INF] [16] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "Décodeur TV UHD" - "SoftAtHome Media Renderer"
[2022-11-02 20:44:55.302 +01:00] [DBG] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2022-11-02 20:44:55.513 +01:00] [INF] [10] Jellyfin.Api.Helpers.TranscodingJobHelper: "ffmpeg" "-analyzeduration 200M -fflags +genpts -f matroska,webm  -i file:\"C:\dlnatest\test.mkv\" -map 0:0 -map -0:a -map -0:s -codec:v:0 copy -map_metadata -1 -map_chapters -1 -threads 0  -y \"C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true\""
[2022-11-02 20:44:55.566 +01:00] [DBG] [10] Jellyfin.Api.Helpers.TranscodingJobHelper: Launched FFmpeg process
[2022-11-02 20:44:55.591 +01:00] [DBG] [10] Jellyfin.Api.Helpers.TranscodingJobHelper: Waiting for the creation of "C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true"
[2022-11-02 20:44:55.602 +01:00] [DBG] [16] Jellyfin.Api.Helpers.TranscodingJobHelper: Disposing stream resources
[2022-11-02 20:44:55.604 +01:00] [ERR] [16] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2022-11-02 20:44:55.702 +01:00] [DBG] [10] Jellyfin.Api.Helpers.TranscodingJobHelper: File "C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true" created or transcoding has finished
[2022-11-02 20:44:55.711 +01:00] [ERR] [10] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/6c93bd4f-adfa-f6cf-16c3-1e3cc4722073/stream.mkv%3FDeviceProfileId=e9c8c8a7440f4cc4b5fa298e5a218180&DeviceId=test&MediaSourceId=6c93bd4fadfaf6cf16c31e3cc4722073&Static=true&VideoCodec=h264&Tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Helpers.FileStreamResponseHelpers.GetTranscodedFile(StreamState state, Boolean isHeadRequest, HttpContext httpContext, TranscodingJobHelper transcodingJobHelper, String ffmpegCommandLineArguments, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource)
   at Jellyfin.Api.Controllers.VideosController.GetVideoStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method318(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
/videos/6c93bd4f-adfa-f6cf-16c3-1e3cc4722073/stream.mkv%3FDeviceProfileId=e9c8c8a7440f4cc4b5fa298e5a218180&DeviceId=test&MediaSourceId=6c93bd4fadfaf6cf16c31e3cc4722073&Static=true&VideoCodec=h264&Tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true

{"Protocol":0,"Id":"6c93bd4fadfaf6cf16c31e3cc4722073","Path":"C:\\dlnatest\\test.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":22451664,"Name":"test","IsRemote":false,"ETag":"de0d61164addfecb9ebdfc437e88de27","RunTimeTicks":599769984,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"h264","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"ChannelLayout":null,"BitRate":2994703,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Profile":"High","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":40,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":2994703,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

ffmpeg -analyzeduration 200M -fflags +genpts -f matroska,webm  -i file:"C:\dlnatest\test.mkv" -map 0:0 -map -0:a -map -0:s -codec:v:0 copy -map_metadata -1 -map_chapters -1 -threads 0  -y "C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true"


ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220324
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3f -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'file:C:\dlnatest\test.mkv':
  Metadata:
    encoder         : libebml v1.2.3 + libmatroska v1.3.0
    creation_time   : 2012-08-20T01:38:27.000000Z
  Duration: 00:00:59.98, start: 0.000000, bitrate: 2994 kb/s
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
[NULL @ 00000225e3afe980] Unable to find a suitable output format for 'C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true'
C:\ProgramData\Jellyfin\Server\transcodes\d67a46ae5ef1bc076f3d03c4e3b34d9b.mkv?deviceprofileid=e9c8c8a7440f4cc4b5fa298e5a218180&deviceid=test&mediasourceid=6c93bd4fadfaf6cf16c31e3cc4722073&static=true&videocodec=h264&tag=de0d61164addfecb9ebdfc437e88de27&dlnaheaders=true: Invalid argument
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JolanGorges** [comment]
I discovered where the problem came from, all the requests use an encoded query string
