### ISSUE TITLE
[Issue]: Server Crash "An invalid IP address was specified. (Parameter 'address')"

### ISSUE THREAD

**Issue by shortN0te** [jellyfin/jellyfin#8687]
### Please describe your bug

Jellyfin version: 10.8.7
Installed on an Debian host with docker managed by Portainer.
docker-compose.yml:
version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /opt/docker/jellyfin/media:/media
      - /opt/docker/jellyfin/config:/config
      - /opt/docker/jellyfin/cache:/cache
      - /expanse/Media/Movies:/mediaGERMovies:ro
      - /expanse/Media/Movies-English:/mediaENMovies:ro
      - /expanse/Media/Series:/mediaShows:ro
      - /expanse/Media/Music:/mediaMusic:ro
      - /expanse/Media/OST:/mediaOST:ro
      - /expanse/Media/Youtube:/mediaYT:ro
    restart: "no"
   environment:
      - JELLYFIN_PublishedServerUrl=https://removed
 
Disabled all Plugins and disabled DLNA Server. This happens randomly when clients are connected or not and the time frame between those crashes is random as well. Extended Log here: https://pastebin.com/AUYhU9T8 but not much happening.

It coincided with the 10.8.6 release, the setup was running fine for months before that.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS:Debian
- Virtualization:Docker
- Clients:Jellyfin Media Player, Web Client
- Plugins: TheTVDB, Webhook, YoutubeMetadata
- Reverse Proxy: nginx
- Networking: Host
```

### Jellyfin logs

```shell
[15:22:16] [FTL] [26] Main: Unhandled Exception

System.ArgumentException: An invalid IP address was specified. (Parameter 'address')

   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)

   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()

   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()

   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)

   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)

   at System.Threading.TimerQueue.FireNextTimers()

Unhandled exception. System.ArgumentException: An invalid IP address was specified. (Parameter 'address')

   at System.Net.IPAddress..ctor(ReadOnlySpan`1 address)

   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()

   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()

   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)

   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)

   at System.Threading.TimerQueue.FireNextTimers()
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by shortN0te** [comment]
Looking at the commits and merges of 10.8.5 it would guess it is related to the PR #8600

**Comment by Bond-009** [comment]
This is an issue with .NET itself
https://github.com/dotnet/runtime/issues/49515

**Comment by Bond-009** [comment]
Should be fixed in master

**Comment by lettore** [comment]
Still happening on me on docker x64 on latest tag

**Comment by Shadowghost** [comment]
Latest is the current stable release, not what's in the master branch.

**Comment by lettore** [comment]
> Latest is the current stable release, not what's in the master branch.

And which image a user should use? 10.8.9 present the same problem, and the unstable tag it's unusable because of #9569.

**Comment by Shadowghost** [comment]
You can use an unstable tag from before the PR that broke the migration was applied (or wait till me or someone else fixes it, I still have no time for this for the next 2 weeks).

**Comment by joshuacox** [comment]
This seems to still be an issue, what is the 

> tag  from before the PR that broke the migration was applied

as this does not look to be resolved anytime soon.

**Comment by ristein** [comment]
I'm running on hotfix 10.8.13 (which everyone should do).
I have this problem too, I only mentioned now because it does not cause problems in playback.
Only my media hard drive was running randomly and I was looking for the cause for months.
Seems like

**Comment by felix920506** [comment]
Please confirm on master

**Comment by ristein** [comment]
> Please confirm on master

sorry, I was trying but I'm not able to get master running.
There is no test build available via apt I guess?

**Comment by crobibero** [comment]
@ristein https://jellyfin.org/downloads/server, then click "Unstable" in the upper right

**Comment by ristein** [comment]
thank you, got it running. (I had to copy /usr/share/jellyfin/web to /var/lib/jellyfin/wwwroot to get it running.)
Server version  10.9.0
Web version  10.9.0
Build version  2024032505

But already got error in log:

> [FTL] Unhandled Exception
System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

I also edited my comment from yesterday: Playback in Client does not seem to be affected by server crashes, but via chrome is.

**Comment by cvium** [comment]
You do realize that this is a bug in the .NET runtime?

**Comment by lettore** [comment]
I realize that many said was fixed long time ago, closed the issue and then now you say is a bug of .NET that was not addressed for 1.5+ years? Looks strange, anyhow something is wrong in Jellyfin, why it should monitor every single network that is created on the system. Why I can't just say use eth0 as network and don't mess up with any others that will be created? In the end, if you use a library with a bug, that is not fixed for ages, you cannot blame them for the bug fix, just change library.

**Comment by felix920506** [comment]
Please test on master or [the latest unstable build](https://jellyfin.org/docs/general/testing/server)

**Comment by gnattu** [comment]
> I realize that many said was fixed long time ago, closed the issue and then now you say is a bug of .NET that was not addressed for 1.5+ years? 

We thought it was fixed by upstream, but it was never the case. The upstream just closed the issue without taking further action.

> Looks strange, anyhow something is wrong in Jellyfin, why it should monitor every single network that is created on the system. Why I can't just say use eth0 as network and don't mess up with any others that will be created? 

Ask Microsoft for why, dotnet queries every interfaces to check network availability: https://github.com/dotnet/runtime/blob/8c68710084b861c44b6868c0bd972ce24aed55dd/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L94

> In the end, if you use a library with a bug, that is not fixed for ages, you cannot blame them for the bug fix, just change library.

This almost has the same meaning as rewriting the entire codebase. Dotnet is a foundational framework, not a random library that can be easily replaced with equivalents.

**Comment by gnattu** [comment]
with #11253 merged, if the network change detection still causes unhanded exceptions (now caused by us, but thrown by dotnet) and crashing the main thread, you can add cli `--nonetchange` to disable automatic network change detection to see if that helps

**Comment by DevilsDesigns** [comment]
has this been fixed yet. my docker jellyfin on unraid crashes every day within 24hrs after starting

**Comment by FML128** [comment]
@Danie10 from the nature of this issue you can work around it by not using network_mode: "host"

**Comment by gnattu** [comment]
See https://github.com/jellyfin/jellyfin/issues/8687#issuecomment-2351479451

If you are using container and it is impractical for you to specify custom command line options, you can export env variable `JELLYFIN_DETECTNETWORKCHANGE=false` to disable the unreliable dotnet networking change as well which should help with this issue.

**Comment by Danie10** [comment]
> @Danie10 from the nature of this issue you can work around it by not using network_mode: "host"

Ah thanks very much I'll try that as it was set to host. Thanks.

**Comment by StNiosem** [comment]
This is not yet fixed for me on 10.11.0-rc3, Docker x64, Host Networking. 
This could be because I'm running an RC but this also happened on 10.10.7.
All official docker images (ghcr.io/jellyfin/jellyfin)

**Comment by NewPing** [comment]
Just wanted to add another data point for this issue. I m still encountering this server crash with the very latest Jellyfin version (10.11.2) running on Unraid. It seems to consistently happen when Jellyfin tries to check for network availability, citing "An invalid IP address was specified." in the `System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()` call. This issue has happened several times now over the last 2 weeks.

Here is a quick summary of my setup and the relevant logs:

**Jellyfin Version:** 10.11.2 (latest)
**Docker Version:** 27.0.3 (running inside Unraid)

**Environment Details:**
- **OS:** Unraid OS 7.0 x86_64, Kernel 6.6.78-Unraid
- **Container Image:** `jellyfin/jellyfin:latest`
- **Network Mode:** The container is running in `host` network mode on Unraid.

```
[05:20:10] [FTL] [79] Main: Unhandled Exception
System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.ArgumentException: An invalid IP address was specified. (Parameter 'address')
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Happy to provide further details if needed.

**Comment by jakoss** [comment]
This just started happening for me too after running jellyfin for 5 years without issue. The only thing that changed - minor host server (Ubuntu server) update. Jellyfin is running on docker
