### ISSUE TITLE
[Issue]: ffprobe failed - streams and format are both null

### ISSUE THREAD

**Issue by theg00s3** [jellyfin/jellyfin#8773]
### Please describe your bug

The below error message repeats for (seemingly) every external subtitle I have, and subsequently they don't appear in Jellyfin as available subtitles. I've uploaded one of the subtitles to mega [here](https://mega.nz/file/LH40WDZY#BdOKxkY8zSeHrQBCj_SKdOTHLGBoo9UyXvGMA3cOW0M), just in case something's wrong with my subtitles.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: Ubuntu 20.04.1
- Virtualization: N/A
- Clients: Browser
- Browser: Firefox 107.0
- FFmpeg Version: 5.1.2-Jellyfin
- Plugins: AudioDB, Fanart, InfuseSync, Intro Skipper, Jellyscrub, Kodi Sync Queue, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, TV Maze, TheTVDB, Trakt
- Reverse Proxy: yes
- Storage: local
```

### Jellyfin logs

```shell
[2022-11-15 09:09:51.946 +11:00] [ERR] Error getting external streams from "/media/windows/TV/Modern Family/Season 4/Modern Family - S04E23 - Games People Play Bluray-1080p.en.srt"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theg00s3** [comment]
potentially related to #7710

**Comment by 97WaterPolo** [comment]
@theg00s3 
Just to help narrow down to see if we have the same issue, if you go to the Media and click the three dots and go to "Edit Subtitles" and manually add the exact same .srt that failed does it work?

**Comment by theg00s3** [comment]
I figured out my issue. It was caused by the BOM at the start of some subtitles.

**Comment by maksim-murashev** [comment]
I got same problems because docker user don't have permissions on folder
`sudo chown -R arrs:dockergroup /hddpool/dockers/data/
sudo chmod -R a=,a+rX,u+w,g+w /hddpool/dockers/data/
`

**Comment by d03j** [comment]
> BOM

Can you elaborate? I am having some issues with one ssa file. Permissions and the file ok It look ok
