### ISSUE TITLE
Failed to start jellyfin on Windows 10 21H2

### ISSUE THREAD

**Issue by farawayzheng** [jellyfin/jellyfin#8798]
Help!
Failed to start jellyfin on Windows 10 21H2.
Jellyfin version: "10.8.7",   Windows Installer downloaded from jellyfin official web-site.

Port 8096/tcp, 8920/tcp, 1900/udp, 7359/udp are not used by other processes.

Jellyfin logs:
[2022-11-26 00:20:07.418 +08:00] [INF] [1] Main: Kestrel listening on "192.168.1.2/24"
[2022-11-26 00:20:07.773 +08:00] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again.
[2022-11-26 00:20:07.776 +08:00] [FTL] [1] Main: Error while starting server.
System.Net.Sockets.SocketException (10013): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2022-11-26 00:20:07.795 +08:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2022-11-26 00:20:07.871 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2022-11-26 00:20:07.873 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2022-11-26 00:20:07.875 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2022-11-26 00:20:07.876 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2022-11-26 00:20:07.886 +08:00] [INF] [2] Main: Received a SIGTERM signal, shutting down

**Comment by RenHoekNL** [comment]
Same issue. Updated from 10.8.7 to 10.8.8; issue remains.

I stopped the SSDP Discovery service to free up port 1900, no change. I ran the server as Administrator, no change.

Increased logging level to Debug but Kestrel is not being more helpful in what is actually going wrong. Would be a good idea to at least insert some debug messages on what port is being opened on what IP.
