### ISSUE TITLE
[Issue]: Scan Media Library Fails Immediately. Method not found: 'Boolean 

### ISSUE THREAD

**Issue by alexi741** [jellyfin/jellyfin#8815]
### Please describe your bug

The scheduled task "Scan Media Library" fails immediately after it starts.

### Jellyfin Version

Other

### if other:

Debian Unstable Repo: 20221127.4

### Environment

```markdown
- OS: Debian Bullseye
- Virtualization: None
- Clients: Web
- Browser: Firefox
- FFmpeg Version: 5.1.2-4-bullseye
```

### Jellyfin logs

```shell
[2022-11-28 00:36:42.151 -05:00] [INF] Executing "Scan Media Library"
[2022-11-28 00:36:42.151 -05:00] [INF] Stopping directory watching for path "/movies"
[2022-11-28 00:36:42.153 -05:00] [INF] Validating media library
[2022-11-28 00:36:42.563 -05:00] [ERR] Error
System.MissingMethodException: Method not found: 'Boolean MediaBrowser.Controller.BaseItemManager.IBaseItemManager.IsMetadataFetcherEnabled(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.String)'.
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.IsEnabledForLibrary(BaseItem item)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnProviderManagerRefreshComplete(Object sender, GenericEventArgs`1 genericEventArgs)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshComplete(BaseItem item)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-11-28 00:36:42.564 -05:00] [INF] "Scan Media Library" Failed after 0 minute(s) and 0 seconds
[2022-11-28 00:36:42.566 -05:00] [INF] ExecuteQueuedTasks
[2022-11-28 00:36:42.599 -05:00] [INF] Watching directory "/movies"
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/1930427/204202355-c0358c0b-dd12-4973-8872-f572d0b20e01.png)

**Comment by crobibero** [comment]
Unstable Jellyfin is not supported. The metadata plugins will need to be updated when Jellyfin 10.9 is released.
