### ISSUE TITLE
[Issue]: DLNA Play To 404 on client that works with Universal Media Server

### ISSUE THREAD

**Issue by jonpas** [jellyfin/jellyfin#8855]
### Please describe your bug

I have an old Philips TV (46PFL6606H/12) with which I would like to use DLNA Play To.

First some confirmed working things on my Jellyfin instance and/or local network:
- DLNA browsing and playback works with all devices, including this Philips TV _(through "Browse Computer" functionality, Jellyfin DLNA server comes up and playback works)_.
- DLNA Play To works with all other devices **except** this Philips TV.
- DLNA playback on Philips TV with **Universal Media Server works** correctly _(["Push from the UMS interface to a renderer"](https://support.universalmediaserver.com/books/use/page/how-to-play-media))_
- Everything was attempted through `http://tyr:8096` (local domain) as well as `192.168.178.87` (local IP).

UMS playback works using the ["Philips PFL" profile](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/045521e7b8344959ba9bf7660d01cc525105c834/src/main/external-resources/renderers/Philips-PFL.conf). Creating a custom DLNA profile in Jellyfin was attempted by specifying the Identification data (which results in correct profile selection as seen in the logs) and specifying limited set of formats as seen in the UMS profile. Removing all supported formats was also attempted. _Neither of those did anything, presumably the error happens earlier. No transcoding was even started in any of the cases, although log confirms `PlayMethod=Transcode`)._

2 errors occur.
1. On device detection, presumably harmful overall as we can define our own profile, but comparing to 2nd error, it is also a 404.
```
[2022-12-05 02:32:04.222 +00:00] [INF] [21] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "Philips TV" - "NMR"
[2022-12-05 02:32:05.234 +00:00] [ERR] [13] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for "Philips TV"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```
2. On "Play" with Philips TV selected as "Play On" target.
```
[2022-12-05 02:32:23.924 +00:00] [INF] [8] Emby.Dlna.Main.DlnaEntryPoint: StreamBuilder.BuildVideoItem( Profile="Philips TV", Path="/srv/jellyfin/Movies/13 Hours (2016)/rep-13hoursthesecretsoldiers.1080p.bluray.x264.mkv", AudioStreamIndex=2, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=DirectPlayError ) "media:/videos/a65fb37a-47ef-4313-d9dd-c51321e92766/stream?MediaSourceId=a65fb37a47ef4313d9ddc51321e92766&AudioStreamIndex=2&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=da917d13f1188ced37ccd6a49c7e1328&TranscodeReasons=DirectPlayError"
[2022-12-05 02:32:24.003 +00:00] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/cd0f31a079d153187a56a46efc6e0a1d/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
<snip, see bottom of full log for the rest of the exception trace>
```

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: Arch Linux (kernel 6.0.10)
- Virtualization: none
- Clients: Browser, Android, DLNA (VLC), **DLNA (old TV)**
- Browser: Firefox 107
- FFmpeg Version: 5.1.2-jellyfin
- Playback Method: Any
- Hardware Acceleration: NVENC (GTX 1050 Ti)
- Plugins: OpenSubtitles, subbuzz, Session Cleaner
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2022-12-05 02:31:53.407 +00:00] [INF] [1] Main: Jellyfin version: "10.8.7"
[2022-12-05 02:31:53.427 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIRECTORY, /var/lib/jellyfin]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_CACHE_DIRECTORY, /var/cache/jellyfin]", "[JELLYFIN_ADD_OPTS, --webdir=/usr/share/jellyfin/web]"]
[2022-12-05 02:31:53.430 +00:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin", "--webdir=/usr/share/jellyfin/web"]
[2022-12-05 02:31:53.431 +00:00] [INF] [1] Main: Operating system: "Linux"
[2022-12-05 02:31:53.431 +00:00] [INF] [1] Main: Architecture: X64
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: 64-Bit Process: True
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: User Interactive: True
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: Processor count: 4
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: Program data path: "/var/lib/jellyfin"
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2022-12-05 02:31:53.432 +00:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2022-12-05 02:31:53.601 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/var/cache/jellyfin"
[2022-12-05 02:31:53.647 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2022-12-05 02:31:53.659 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=18.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Open Subtitles_18.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"
[2022-12-05 02:31:53.659 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.SessionCleaner, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Session Cleaner_2.0.0.0/Jellyfin.Plugin.SessionCleaner.dll"
[2022-12-05 02:31:53.697 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "subbuzz, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/subbuzz_1.0.3.0/subbuzz.dll"
[2022-12-05 02:31:53.702 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_8.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2022-12-05 02:31:53.703 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_8.0.0.0/TvDbSharper.dll"
[2022-12-05 02:31:53.796 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-12-05 02:31:53.796 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2022-12-05 02:31:53.797 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-12-05 02:31:53.804 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[192.168.178.87/32]"
[2022-12-05 02:31:53.804 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2022-12-05 02:31:55.762 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "18.0.0.0"
[2022-12-05 02:31:55.763 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Session Cleaner" "2.0.0.0"
[2022-12-05 02:31:55.764 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "subbuzz" "1.0.3.0"
[2022-12-05 02:31:55.764 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "8.0.0.0"
[2022-12-05 02:31:55.765 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.7.0"
[2022-12-05 02:31:55.765 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.7.0"
[2022-12-05 02:31:55.765 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.7.0"
[2022-12-05 02:31:55.765 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.7.0"
[2022-12-05 02:31:55.766 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.7.0"
[2022-12-05 02:31:55.841 +00:00] [INF] [1] Main: Kestrel listening on "192.168.178.87/32"
[2022-12-05 02:31:56.209 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2022-12-05 02:31:56.242 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2022-12-06 02:00:00.000 +00:00, which is 23:28:03.7573628 from now.
[2022-12-05 02:31:56.320 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.2"
[2022-12-05 02:31:56.375 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2022-12-05 02:31:56.413 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2022-12-05 02:31:56.463 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2022-12-05 02:31:56.695 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2022-12-05 02:31:56.870 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2022-12-05 02:31:56.870 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "930495f6fdc94cbe8c52a6177ab7a977"
[2022-12-05 02:31:56.995 +00:00] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.178.87/32"
[2022-12-05 02:31:57.018 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1394245
[2022-12-05 02:31:57.018 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2022-12-05 02:31:57.224 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/srv/jellyfin/Shows"
[2022-12-05 02:31:57.225 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.2072229
[2022-12-05 02:31:57.225 +00:00] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/srv/jellyfin/Movies"
[2022-12-05 02:31:57.225 +00:00] [INF] [1] Main: Startup complete 0:00:03.9677441
[2022-12-05 02:31:59.251 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2022-12-05 02:31:59.253 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2022-12-05 02:31:59.258 +00:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2022-12-05 02:32:00.364 +00:00] [INF] [22] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" request
[2022-12-05 02:32:00.661 +00:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" closed
[2022-12-05 02:32:01.043 +00:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2022-12-05 02:32:01.054 +00:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-12-05 02:32:04.215 +00:00] [WRN] [21] Jellyfin.Networking.Manager.NetworkManager: "Any IP4 Address": External request received, however, only an internal interface bind found.
[2022-12-05 02:32:04.222 +00:00] [INF] [21] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "Philips TV" - "NMR"
[2022-12-05 02:32:05.234 +00:00] [ERR] [13] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for "Philips TV"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
[2022-12-05 02:32:08.695 +00:00] [INF] [13] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" request
[2022-12-05 02:32:08.813 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" closed
[2022-12-05 02:32:19.230 +00:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" request
[2022-12-05 02:32:19.320 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.320 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.320 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.320 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.320 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:19.327 +00:00] [WRN] [22] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-12-05 02:32:23.924 +00:00] [INF] [8] Emby.Dlna.Main.DlnaEntryPoint: StreamBuilder.BuildVideoItem( Profile="Philips TV", Path="/srv/jellyfin/Movies/13 Hours (2016)/rep-13hoursthesecretsoldiers.1080p.bluray.x264.mkv", AudioStreamIndex=2, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=DirectPlayError ) "media:/videos/a65fb37a-47ef-4313-d9dd-c51321e92766/stream?MediaSourceId=a65fb37a47ef4313d9ddc51321e92766&AudioStreamIndex=2&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=da917d13f1188ced37ccd6a49c7e1328&TranscodeReasons=DirectPlayError"
[2022-12-05 02:32:24.003 +00:00] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/cd0f31a079d153187a56a46efc6e0a1d/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SessionController.Play(String sessionId, PlayCommand playCommand, Guid[] itemIds, Nullable`1 startPositionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 startIndex)
   at lambda_method883(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-12-05 02:32:24.846 +00:00] [INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.178.30" request
```

### FFmpeg logs

```shell
_Never started transcoding._
```

### Please attach any browser or client logs here

![image](https://user-images.githubusercontent.com/7935003/205538378-7f71449b-d83f-4a53-b10f-891ef12f7f3e.png)

_`http://tyr:8096` is internal address of the Jellyfin server._

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonpas** [comment]
Similar to #8690 but different error code it seems.

**Comment by jonpas** [comment]
Still affected.

**Comment by jonpas** [comment]
Still affected.
