### ISSUE TITLE
Import of XMLTV program info fails

### ISSUE THREAD

**Issue by bruor** [jellyfin/jellyfin#8883]
### Please describe your bug

I have tried many XMLTV files and all result in the same error.  However, this is the one I'm currently using in my environment. 
https://github.com/Apollo2000/TVGuide/raw/master/utc.xml.gz 
I run a script to download and gunzip the file to bare XML where it is loaded from disk into Jellyfin. 

I've just imported this to 10.8 stable on windows without issue and the channel list is updating with guide information. 
In both cases I manually deleted the channel/xmltv cache files as suggested here: https://github.com/jellyfin/jellyfin/issues/6103

### Jellyfin Version

Other

### if other:

jellyfin-server:amd64 20221209.1-unstable

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Virtualization: ESXI 7.0u3
- Storage: local
```

### Jellyfin logs

```shell
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "TCM"
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "Telecinco"
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "Teledeporte"
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "Telemadrid"
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "TEN"
[2022-12-09 09:58:52.095 -05:00] [INF] Parsed channel: "Toros TV"
[2022-12-09 09:58:52.096 -05:00] [INF] Parsed channel: "TV3 CAT"
[2022-12-09 09:58:52.101 -05:00] [INF] xmltv path: "/mnt/data/ApolloEPG/utc.xml"
[2022-12-09 09:58:53.454 -05:00] [ERR] Error adding metadata
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.<>c.<GetChannels>b__16_0(XmlTvChannel c)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)
[2022-12-09 09:58:53.468 -05:00] [INF] Refreshing guide with 7 days of guide data
[2022-12-09 09:58:53.469 -05:00] [INF] xmltv path: "/mnt/data/ApolloEPG/utc.xml"
[2022-12-09 09:58:54.432 -05:00] [ERR] Error adding metadata
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.<>c.<GetChannels>b__16_0(XmlTvChannel c)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)
[2022-12-09 09:58:54.433 -05:00] [INF] xmltv path: "/mnt/data/ApolloEPG/utc.xml"
[2022-12-09 09:58:55.393 -05:00] [ERR] Error getting programs for channel "Star Max (East)"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.<>c.<GetChannels>b__16_0(XmlTvChannel c)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannelFromTunerChannel(IListingsProvider provider, ListingsProviderInfo info, ChannelInfo tunerChannel, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetProgramsAsync(String channelId, DateTime startDateUtc, DateTime endDateUtc, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)
[2022-12-09 09:58:55.396 -05:00] [INF] xmltv path: "/mnt/data/ApolloEPG/utc.xml"
.......
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bruor** [comment]
I was able to successfully downgrade to 10.8.8 stable on my ubuntu system by following these steps: 

Check for unstable repo: 
`apt policy | grep unstable
`
Remove it: 
`rm /etc/apt/sources.list.d/jellyfin*; rm /etc/apt/trusted.gpg.d/jellyfin.gpg; apt update
`
Remove references to jellyfin packages from /var/lib/dpkg/status

Follow steps on the website to add the repo, installed "jellyfin" with this modified command: 
`sudo apt install --reinstall jellyfin
`

**Comment by Nostradamus1973** [comment]
Good morning,
Thanks for the quick tutorial.
Are you saying that we should downgrade because this issue won't be fixed in a timely manner? I purposely installed the unstable version because I was told that a project like this moves so fast that features and client compatibility can become a problem and bugs would be addressed quicker; of course, I'm aware that the very nature of nightly builds is to identify problems and fix them accordingly.
So, I'm just curious to know if anyone knows how long something like this takes to be addressed and fixed.
I would very much rather move forward and get to the bottom of this problem instead of downgrading.
Thank you and have a nice day.

**Comment by bruor** [comment]
I only mentioned the downgrade to help devs pinpoint what change might have caused this bug. 

Previous to noticing any issues I was on a unstable build that was dated 20221102. 

I too was on unstable since I started because of new features but it was right before 10.8 dropped that I got into this.  Not I'm just looking to get a reliable setup running.
