### ISSUE TITLE
[Issue]: Library scan error. "Method not found" 

### ISSUE THREAD

**Issue by Anti-ctrl** [jellyfin/jellyfin#8891]
### Please describe your bug

The Library Scan doesn't start and Fails with "Method not found"

I use Jellyfin unstable because i passed through an AMD iGPU from a 5650G PRO into the LXC.

For testing purposes i put Jellyfin into a full VM, also on Proxmox. Debian 11 was the base system. Worked flawless there. Anyone got any Idea what went wrong here?

If anything more is needed, then don't hesitate to ask for it!
Many thanks in advance for the great work and Happy Holidays!

### Jellyfin Version

Other

### if other:

10.9.0 - 20221210.2-unstable amd64

### Environment

```markdown
- OS: Proxmox - LXC - Ubuntu 20.04
- Virtualization: yes
- Clients: Local, external
- Browser: Firefox, Chrome
- FFmpeg Version: 5.1.2-5-focal
- Playback Method: /
- Hardware Acceleration: VA-API
- Plugins: Please check the Screenshot
- Reverse Proxy: NGINX
- Base URL:
- Networking:
- Storage: CIFS/Samba Readonly
```

### Jellyfin logs

```shell
[2022-12-11 20:50:01.906 +00:00] [INF] Executing "Scanne Medien-Bibliothek"
[2022-12-11 20:50:01.909 +00:00] [INF] Stopping directory watching for path "/redacted"
[2022-12-11 20:50:01.910 +00:00] [INF] Stopping directory watching for path "/redacted"
[2022-12-11 20:50:01.913 +00:00] [INF] Stopping directory watching for path "/redacted"
[2022-12-11 20:50:01.914 +00:00] [INF] Validating media library
[2022-12-11 20:50:02.838 +00:00] [ERR] Error
System.MissingMethodException: Method not found: 'Boolean MediaBrowser.Controller.BaseItemManager.IBaseItemManager.IsMetadataFetcherEnabled(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.String)'.
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.IsEnabledForLibrary(BaseItem item)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnProviderManagerRefreshComplete(Object sender, GenericEventArgs`1 genericEventArgs)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshComplete(BaseItem item)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-12-11 20:50:02.839 +00:00] [INF] "Scanne Medien-Bibliothek" Failed after 0 minute(s) and 0 seconds
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/68434734/206928739-693d49aa-fd02-4b37-a1cc-d01b5fc2e2c2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
10.8 plugins are not compatible with 10.9.

**Comment by Anti-ctrl** [comment]
> 10.8 plugins are not compatible with 10.9.

Thanks. I didn't check for that. Problem is that TVDB doesnt seem removable. Jellyfin automatically re-downloads the (wrong version) of the Plugin and asks for a restart.

I removed it as a source from my library and removed the Plugin afterwards to no avail.

Following Output gets produced:

`[2022-12-12 07:05:55.524 +00:00] [INF] "StartupTrigger" fired for task: "Aktualisiere Plugins"
[2022-12-12 07:05:55.524 +00:00] [INF] Queuing task "PluginUpdateTask"
[2022-12-12 07:05:55.526 +00:00] [INF] Executing "Aktualisiere Plugins"
[2022-12-12 07:05:56.565 +00:00] [INF] Watching directory "/redacted"
[2022-12-12 07:05:57.400 +00:00] [INF] Plugin "installed": "TheTVDB" "8.0.0.0"
[2022-12-12 07:05:57.401 +00:00] [INF] App needs to be restarted.
[2022-12-12 07:05:57.686 +00:00] [INF] Plugin "updated": "TheTVDB" "8.0.0.0"
[2022-12-12 07:05:57.686 +00:00] [INF] App needs to be restarted.
[2022-12-12 07:05:57.971 +00:00] [INF] Plugin "updated": "TheTVDB" "8.0.0.0"
[2022-12-12 07:05:57.971 +00:00] [INF] App needs to be restarted.
[2022-12-12 07:05:57.972 +00:00] [INF] "Aktualisiere Plugins" Completed after 0 minute(s) and 2 seconds`

**Comment by cvium** [comment]
It should be fixed
