### ISSUE TITLE
[Issue]: Healthcheck is failing with the error: "Error processing request."

### ISSUE THREAD

**Issue by Maeur1** [jellyfin/jellyfin#8919]
### Please describe your bug

Logging shows failing HealthCheck, seems to correlate with the upgrade to DotNet 7.0. Maybe something implementation wise is up and causing the healthcheck to fail?

Also looking at the other issues, perhaps this is causing some [docker images to fail ](https://github.com/jellyfin/jellyfin/issues/8915#issuecomment-1353617231) if they depend on the healthcheck?

Or perhaps my JellyfinDB file is broken hence it cannot initialize a SQLite DB of the file? Or do other users have this issue too?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: Browser, IOS, Android TV
- Browser: Chrome 
- FFmpeg Version: 4.4.1
- Playback Method: Transcode
- Hardware Acceleration: VAAPI
- Plugins: None
- Reverse Proxy: Ngnix
- Base URL: none
- Networking: host
- Storage: NFS
```

### Jellyfin logs

```shell
[2022-12-18 18:33:12.779 +11:00] [ERR] [7] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/health".
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Server.Implementations.JellyfinDb' while attempting to activate 'Microsoft.Extensions.Diagnostics.HealthChecks.DbContextHealthCheck`1[Jellyfin.Server.Implementations.JellyfinDb]'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxi1134** [comment]
I also have this issue on a fresh install, did you found a solution?

**Comment by nielsvanvelzen** [comment]
I'm not able to reproduce this issue on 10.8.8. Opening the /Health page prints "Healthy" as expected.

**Comment by Maeur1** [comment]
I think an extra bit of info I forgot to add: I built the docker image fresh from the repo so it's running "10.9" as that's what the dashboard says. Hence I reckon it's something to do with the Dot Net upgrade: the error message seems to be some C# dependency injection issue that I'm not well versed in C# to understand.
