### ISSUE TITLE
[Issue]: Unhandled WebSocket System.ObjectDisposedException

### ISSUE THREAD

**Issue by ipitio** [jellyfin/jellyfin#8991]
### Please describe your bug

After updating to v10.8.8, Jellyfin has been crashing once or twice a day due to an uncaught Exception. The logs indicate that the fatal error is thrown when a client improperly closes a connection. The connection is then closed on the server after it times out; yet, the server still tries to write to the stream.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Windows 10
- Virtualization: N/A
- Clients: Web (browser, mobile), Android TV, Roku, webOS
- Browser: Firefox latest
- FFmpeg Version: the one that was shipped with 10.8.8
- Playback Method: All
- Hardware Acceleration: NVENC
- Plugins: AniDB7.0.0.0,AniList5.0.0.0,AniSearch4.0.0.0,AudioDB10.8.8.0,Bookshelf9.0.0.0,Cover Art Archive7.0.0.0,Email Notifications9.0.0.0,Fanart10.0.0.0,IMVDb3.0.0.0,InfuseSync1.4.2.0,Intro Skipper0.1.7.0,Jellyscrub1.0.0.7,Kitsu4.0.0.0,Kodi Sync Queue9.0.0.0,MusicBrainz10.8.8.0,OMDb10.8.8.0,OPDS Feed4.0.0.0,Open Subtitles18.0.0.0,Playback Reporting13.0.0.0,Reports15.0.0.0,Studio Images10.8.8.0,TMDb10.8.8.0,TMDb Box Sets10.0.0.0,TMDb Trailers10.0.0.0,TVmaze10.0.0.0,TheTVDB8.0.0.0,Trakt22.0.0.0,VGMdb2.0.0.0,КиноПоиск10.7.5.4
- Reverse Proxy: Apache for internet clients, none for local/vpn
- Base URL: none
- Networking: Apache runs in WSL (Jellyfin doesn't), VPN is on the router (split tunnel)
- Storage: local
```

### Jellyfin logs

```shell
[WRN] [72] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "{CLIENT_IP_ADDR}" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
```
```
[INF] [72] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "{CLIENT_IP_ADDR}" closed
```
```
[ERR] [62] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "{CLIENT_IP_ADDR}" WebSocketRequestHandler error
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was timed out by the server because the response was not read by the client at the specified minimum data rate.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1UpgradeMessageBody.ReadAsyncInternalAwaited(ValueTask`1 readTask, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Emby.Server.Implementations.HttpServer.WebSocketConnection.ProcessAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.WebSocketManager.WebSocketRequestHandler(HttpContext context)
```
```
[ERR] [25] Jellyfin.Api.WebSocketListeners.ScheduledTasksWebSocketListener: Error sending web socket message ScheduledTasksInfo
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.ObjectDisposedException: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.<ValidateState>g__ThrowObjectDisposedException|15_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpUpgradeStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.SendData(Tuple`3 tuple)
```
```
[FTL] [17] Main: Unhandled Exception
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.ObjectDisposedException: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.<ValidateState>g__ThrowObjectDisposedException|15_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpUpgradeStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.SendNotifications(List`1 changes, CancellationToken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.UpdateTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daramos** [comment]
I'm experiencing this on 10.8.9 as well.

```
[2023-02-15 03:29:59.789 +00:00] [FTL] [96] Main: Unhandled Exception
System.OperationCanceledException: The operation was canceled.
 ---> System.ObjectDisposedException: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.<ValidateState>g__ThrowObjectDisposedException|15_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpUpgradeStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.SendNotifications(List`1 changes, CancellationToken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier.UpdateTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by a-jackson** [comment]
I think I've been getting this on 10.8.10

```
[19:19:38] [FTL] [60] Main: Unhandled Exception
System.OperationCanceledException: The operation was canceled.
 ---> System.ObjectDisposedException: Cannot write to the response
body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRe
sponsePipeWriter.<ValidateState>g__ThrowObjectDisposedException|15_
0()
ancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync
(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompres
sion, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationTo
ken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync
(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompres
sion, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationTo
ken cancellationToken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifie
r.SendNotifications(List`1 changes, CancellationToken cancellationT
oken)
   at Emby.Server.Implementations.EntryPoints.UserDataChangeNotifie
r.UpdateTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContex
t executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
