### ISSUE TITLE
[Issue]: HTTP Proxy authorization not working

### ISSUE THREAD

**Issue by mazzz1y** [jellyfin/jellyfin#8997]
### Please describe your bug

Looks like jellyfin doesn't respect proxy auth passed by environment variables:

```bash
export http_proxy=http://user:password@proxy:1080
export https_proxy=http://user:password@proxy:1080

curl http://ifconfig.co # make sure that http_proxy is working with curl
curl https://ifconfig.co # make sure that https_proxy is working with curl
# requests successful

# then run jellyfin
...
System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://user:password@proxy:1080/' failed with status code '407'.
...
```

It means that currently is impossible to use proxy with authorization. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux 6.0
- Virtualization: official docker image
```

### Jellyfin logs

```shell
System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://user:password@proxy:1080/' failed with status code '407'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Jellyfin doesn't support proxy auth so this error makes sense.

**Comment by mazzz1y** [comment]
So, maybe add this support?

**Comment by Shadowghost** [comment]
We are all volunteers. You can propose features at https://features.jellyfin.org and if somebody is willing to implement it they will. Or you can do it yourself if it's that important to you.

**Comment by mazzz1y** [comment]
Of course, my message is to community. I just propose to not close the issue until it resolved
