### ISSUE TITLE
TheMovieDb : Input string was not in a correct format

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jellyfin/jellyfin#9005]
I'm getting this error during add new media and search for TheMovieDb, extra informations can't be downloaded from TheMovieDb

```
[2023-01-03 17:43:21.284 +01:00] [ERR] Provider "TheMovieDb" failed to retrieve search results
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2023-01-03 17:43:34.680 +01:00] [INF] Setting provider id's to item df1eb96a-5ba6-5aef-4b9a-41fd1701ac6a-"Anton Krupicka, Ultra Pur": "{\"Tmdb\":\"1069114\"}"
```

**Comment by Bond-009** [comment]
What's the file name/does is have nfo data?

**Comment by Bond-009** [comment]
Closing as stale
