### ISSUE TITLE
[Issue]: error receiving data: The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by riccardofinkers** [jellyfin/jellyfin#9040]
### Please describe your bug

I've removed IP address and replaced it with xxxxxxxxx for privacy reasons.

Everytime I play something on my tv  jellyfin stops with it after a few minutes. 

Running Jellyfin in Docker on Proxmox and accessing the URL through Cloudflare Tunnel.

I always run up with the following error:
````
error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
````

What steps can I take to debug/resolve this annoying issue ?

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: Proxmox
- Virtualization: Docker
- Clients: Samsung Smart TV
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Tried None and VAAPI
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[12:04:58] [INF] [79] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 01/08/2023 12:04:58
[12:04:58] [INF] [79] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[12:04:58] [INF] [37] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[12:04:59] [INF] [37] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : xxxxxxxxx
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = 35ce6768cda76d1b60cf876dabfd3c17
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 8051c3b4ade142a6a8ce7542f3e3fece
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 1
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = 35ce6768cda76d1b60cf876dabfd3c17
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 8051c3b4ade142a6a8ce7542f3e3fece
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = DirectPlay
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Jellyfin for Tizen
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = Samsung Smart TV
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = Buscando a Nemo
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = 35ce6768cda76d1b60cf876dabfd3c17
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Movie
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : All matches, playback registered
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback tracker found, adding playback info : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[12:05:18] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[12:05:19] [INF] [84] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:05:40] [INF] [32] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:06:01] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:06:21] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:06:41] [INF] [52] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:07:01] [INF] [37] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:07:14] [WRN] [37] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS xxxxxxxxx error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[12:07:18] [INF] [37] Emby.Server.Implementations.HttpServer.WebSocketManager: WS xxxxxxxxx closed
[12:07:14] [ERR] [32] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 3088f61bdc24e83b6aecdb22003f3168 not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[12:07:17] [ERR] [27] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 3088f61bdc24e83b6aecdb22003f3168 not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[12:07:16] [ERR] [55] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 3088f61bdc24e83b6aecdb22003f3168 not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[12:07:15] [ERR] [52] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 3088f61bdc24e83b6aecdb22003f3168 not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[12:07:39] [INF] [55] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:07:43] [INF] [32] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin for Tizen 0.1.0 playing Buscando a Nemo. Stopped at 6053984 ms
[12:07:43] [INF] [52] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : TW96aWxsYS81LjAgKFNNQVJULVRWOyBMSU5VWDsgVGl6ZW4gNC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBUViBTYWZhcmkvNTM3LjM2fDE2NzE0ODgzMDQyNDY1-8051c3b4ade142a6a8ce7542f3e3fece-35ce6768cda76d1b60cf876dabfd3c17
[12:07:43] [INF] [52] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 01/08/2023 12:07:43
[12:07:43] [INF] [52] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[12:07:58] [INF] [52] Emby.Server.Implementations.HttpServer.WebSocketManager: WS xxxxxxxxx request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdamWHY2K** [comment]
Having a similar issue, only when streaming audio though.

```
[2024-01-15 18:33:49.835 +00:00] [INF] PlaybackTracker : Adding Start Event : 01/15/2024 18:33:49
[2024-01-15 18:33:49.835 +00:00] [INF] Creating StartPlaybackTimer Task
[2024-01-15 18:33:49.835 +00:00] [INF] StartPlaybackTimer : Entered
[2024-01-15 18:33:49.835 +00:00] [WRN] Slow HTTP Response from "http://xxx.xxx.x.xxx:xxxx/Sessions/Playing" to "xxx.xxx.x.xx" in 0:00:00.8909112 with Status Code 204
[2024-01-15 18:33:50.332 +00:00] [INF] Started user data sync
[2024-01-15 18:33:50.876 +00:00] [INF] User Data Sync: User "xxxxxxxxx" ("664acdf619e540e5935b1e66fe6c0694") posted 2 updates
[2024-01-15 18:33:50.876 +00:00] [INF] Finished user data sync, taking "00:00:00.5443476"
[2024-01-15 18:33:51.290 +00:00] [INF] Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MDIyMjc4Njg4NTc1-664acdf619e540e5935b1e66fe6c0694-e1de08bdeee17c842f3e15ecfa9b3ae9"
[2024-01-15 18:34:03.606 +00:00] [WRN] WS "xxx.xxx.x.xx" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-01-15 18:34:03.611 +00:00] [INF] WS "xxx.xxx.x.xx" closed
[2024-01-15 18:34:03.859 +00:00] [INF] StartPlaybackTimer : session Not Found
[2024-01-15 18:34:03.859 +00:00] [INF] StartPlaybackTimer : Exited
[2024-01-15 18:34:09.837 +00:00] [INF] session.RemoteEndPoint : "xxx.xxx.x.xx"
[2024-01-15 18:34:09.837 +00:00] [INF] StartPlaybackTimer : event_playing_id     = "e1de08bdeee17c842f3e15ecfa9b3ae9"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : event_user_id        = "664acdf619e540e5935b1e66fe6c0694"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : event_user_id_int    = 4
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : session_playing_id   = "e1de08bdeee17c842f3e15ecfa9b3ae9"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : session_user_id      = "664acdf619e540e5935b1e66fe6c0694"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : e.DeviceName         = "Chrome"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : ItemName             = "Tech N9ne - Drill Team (Killer)"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : ItemId               = "e1de08bdeee17c842f3e15ecfa9b3ae9"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : ItemType             = "Audio"
[2024-01-15 18:34:09.838 +00:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-01-15 18:34:09.838 +00:00] [INF] Playback tracker found, adding playback info : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MDIyMjc4Njg4NTc1-664acdf619e540e5935b1e66fe6c0694-e1de08bdeee17c842f3e15ecfa9b3ae9"
[2024-01-15 18:34:09.838 +00:00] [INF] Saving playback tracking activity in DB
[2024-01-15 18:34:09.845 +00:00] [INF] StartPlaybackTimer : Exited
```

**Comment by hellcry37** [comment]
same here, I am using my server with android app

**Comment by wanyulaowang** [comment]
I have also encountered similar problems
jellyfin version：10.10.5
Client ：jellyfin-android-v2.6.2-libre-release.apk use Web player
log:
[2025-02-04 08:11:47.290 +00:00] [INF] [23] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2025-02-04 08:11:47.294 +00:00] [INF] [23] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "user_lm" ("d828f7c8f20a4365b0e522e3345dea36") posted 2 updates
[2025-02-04 08:11:47.294 +00:00] [INF] [23] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Finished user data sync, taking "00:00:00.0033008"
[2025-02-04 08:12:10.917 +00:00] [INF] [11] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "user_lm". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-02-04 08:12:10.917 +00:00] [INF] [11] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 10000000, RemoteIP: "192.168.2.173", IsInLocalNetwork: True
[2025-02-04 08:12:12.208 +00:00] [INF] [20] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2025-02-04 08:12:12.212 +00:00] [INF] [20] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "user_lm" ("d828f7c8f20a4365b0e522e3345dea36") posted 2 updates
[2025-02-04 08:12:12.212 +00:00] [INF] [20] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Finished user data sync, taking "00:00:00.0042338"
[2025-02-04 08:12:21.142 +00:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:12:21.814 +00:00] [INF] [29] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:13:52.143 +00:00] [INF] [29] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:13:52.815 +00:00] [INF] [29] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:15:23.145 +00:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:15:23.815 +00:00] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:16:54.146 +00:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:16:54.817 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:18:25.148 +00:00] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:18:25.817 +00:00] [INF] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:19:56.148 +00:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:19:56.817 +00:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:20:41.134 +00:00] [INF] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2025-02-04 08:20:41.559 +00:00] [WRN] [23] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.2.173" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2025-02-04 08:20:41.559 +00:00] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.173" closed
[2025-02-04 08:21:27.147 +00:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:21:27.817 +00:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:21:29.639 +00:00] [INF] [32] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "sc-jellyfin" has succeeded.
[2025-02-04 08:21:29.639 +00:00] [INF] [32] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "sc-jellyfin": 1/0
[2025-02-04 08:21:29.639 +00:00] [INF] [32] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 74de849e-6a79-498a-8c12-4a089bf4f82a
[2025-02-04 08:21:29.903 +00:00] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.28" request
[2025-02-04 08:21:42.449 +00:00] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.173" request
[2025-02-04 08:22:58.148 +00:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:22:58.817 +00:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
[2025-02-04 08:23:08.055 +00:00] [WRN] [23] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.2.173" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
