### ISSUE TITLE
[Issue]: Keyframe extractor gets stuck at 2.6%

### ISSUE THREAD

**Issue by SamuraiMarv** [jellyfin/jellyfin#9052]
### Please describe your bug

Keyframe extractor gets stuck at 2.6%. When looking at the logs I see the error below for one file. When attempting to cancel the task it just says canceling without ever finishing. After rebooting the system and starting the keyframe extractor again it gets stuck at 2.6% again sometimes on the same file and sometimes on a different file. 

I saw a similar issue report but that user was told the issue was fixed in 10.6, I'm on the latest and still having the issue. Is there a way to tell it to just skip files it couldn't extract the keyframes from? I'd rather not mess around with removing and reading media to see if it will get the task to actually finish.

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: Unraid
- Virtualization: Docker
- Clients: Browser, iOS, macOS, tvOS
- Browser: Safari, Edge
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Direct play
- Hardware Acceleration: NVENC
- Plugins:Playback Reporting, Ani-Sync, Webhook, Theme Songs, TheTVDB
- Reverse Proxy: Nginx
- Base URL: yes
- Networking: Bridge
- Storage: Unraid
```

### Jellyfin logs

```shell
2023-01-09 05:50:32.192 -05:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Keyframe Extractor"
[2023-01-09 05:50:32.455 -05:00] [ERR] [17] Jellyfin.MediaEncoding.Hls.Extractors.MatroskaKeyframeExtractor: Extracting keyframes from "/media/Shows/Cyberpunk - Edgerunners (2022) [tvdbid-384541]/Season 01/Cyberpunk - Edgerunners (2022) - S01E01 - 001 - Let You Down [WEBDL-1080p][8bit][x264][EAC3 5.1][JA+CS+DE+EN+ES+FR+HU+ID+IT+PL+PT+TH]-NanDesuKa.mkv" using matroska metadata failed
System.InvalidOperationException: SeekHead is missing or does not contain Info, Tracks and Cues positions. SeekHead referencing another SeekHead is not supported
   at Jellyfin.MediaEncoding.Keyframes.Matroska.Extensions.EbmlReaderExtensions.ReadSeekHead(EbmlReader reader)
   at Jellyfin.MediaEncoding.Keyframes.Matroska.MatroskaKeyframeExtractor.GetKeyframeData(String filePath)
   at Jellyfin.MediaEncoding.Hls.Extractors.MatroskaKeyframeExtractor.TryExtractKeyframes(String filePath, KeyframeData& keyframeData)
[2023-01-09 05:50:42.627 -05:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
```

### Please attach any screenshots here

<img width="860" alt="Screenshot 2023-01-08 at 18 53 43" src="https://user-images.githubusercontent.com/121644108/211429544-1cadb31e-43b6-4b21-8664-857b5e3c76e5.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marvagabi** [comment]
Confirming the issue is still present

**Comment by deanrbennett** [comment]
Having same issue. Ubuntu 22.04 LTS
[jellyfin.log.txt](https://github.com/jellyfin/jellyfin/files/13676079/jellyfin.log.txt)


Version: 10.8.13
Operating System: Linux
Architecture: X64
