### ISSUE TITLE
[Issue]: Debian install jellyfin-web and ffmpeg errors

### ISSUE THREAD

**Issue by EZUsername42** [jellyfin/jellyfin#9083]
### Please describe your bug

The Debian Jellyfin install metapackage points jellyfin to the wrong location for jellyfin-web. This issue is documented here with a fix: https://github.com/jellyfin/jellyfin/issues/8976

However, even after performing the command to fix it (sudo jellyfin -w /usr/share/jellyfin/web) the web UI does not load, it just displays the jellyfin logo and never goes to the configuration screen (as opposed to displaying Unable To Connect).

I suspect this may be due to the above fix no longer working? 

```
greg@hp600g2mini:~$ sudo systemctl status jellyfin-web
Unit jellyfin-web.service could not be found.

greg@hp600g2mini:~$ cat /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf
# Jellyfin systemd configuration options

# Use this file to override the user or environment file location.

[Service]
# Alter the user that Jellyfin runs as
#User = jellyfin

# Alter where environment variables are sourced from
#EnvironmentFile = /etc/default/jellyfin

# Service hardening options
# These were added in PR #6953 to solve issue #6952, but some combination of
# them causes "restart.sh" functionality to break with the following error:
#   sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the
#   'nosuid' option set or an NFS file system without root privileges?
# See issue #7503 for details on the troubleshooting that went into this.
# Since these were added for NixOS specifically and are above and beyond
# what 99% of systemd units do, they have been moved here as optional
# additional flags to set for maximum system security and can be enabled at
# the administrator's or package maintainer's discretion.
# Uncomment these only if you know what you're doing, and doing so may cause
# bugs with in-server Restart and potentially other functionality as well.
#NoNewPrivileges=true
#SystemCallArchitectures=native
#RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
#RestrictNamespaces=false
#RestrictRealtime=true
#RestrictSUIDSGID=true
#ProtectControlGroups=false
#ProtectHostname=true
#ProtectKernelLogs=false
#ProtectKernelModules=false
#ProtectKernelTunables=false
#LockPersonality=true
#PrivateTmp=false
#PrivateDevices=false
#PrivateUsers=true
#RemoveIPC=true
#SystemCallFilter=~@clock
#SystemCallFilter=~@aio
#SystemCallFilter=~@chown
#SystemCallFilter=~@cpu-emulation
#SystemCallFilter=~@debug
#SystemCallFilter=~@keyring
#SystemCallFilter=~@memlock
#SystemCallFilter=~@module
#SystemCallFilter=~@mount
#SystemCallFilter=~@obsolete
#SystemCallFilter=~@privileged
#SystemCallFilter=~@raw-io
#SystemCallFilter=~@reboot
#SystemCallFilter=~@setuid
#SystemCallFilter=~@swap
#SystemCallErrorNumber=EPERM
```

```
greg@hp600g2mini:~$ cat /lib/systemd/system/jellyfin.service

[Unit]
Description = Jellyfin Media Server
After = network-online.target

[Service]
Type = simple
EnvironmentFile = /etc/default/jellyfin
User = jellyfin
Group = jellyfin
WorkingDirectory = /var/lib/jellyfin
ExecStart = /usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITIONAL_OPTS
Restart = on-failure
TimeoutSec = 15
SuccessExitStatus=0 143

[Install]
WantedBy = multi-user.target
```

```
greg@hp600g2mini:~$ sudo systemctl status jellyfin
● jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
     Active: failed (Result: signal) since Thu 2023-01-12 14:45:16 PST; 51min ago
    Process: 10114 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITIONAL_OPTS (code=killed, signal=ABRT)
   Main PID: 10114 (code=killed, signal=ABRT)
        CPU: 424ms

Jan 12 14:45:16 hp600g2mini systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Jan 12 14:45:16 hp600g2mini systemd[1]: Stopped Jellyfin Media Server.
Jan 12 14:45:16 hp600g2mini systemd[1]: jellyfin.service: Start request repeated too quickly.
Jan 12 14:45:16 hp600g2mini systemd[1]: jellyfin.service: Failed with result 'signal'.
Jan 12 14:45:16 hp600g2mini systemd[1]: Failed to start Jellyfin Media Server.
```

In addition, _something_ is wrong with installing and setting up ffmpeg via the jellyfin-ffmpeg5 installer that the metapackage utilizes:

```
greg@hp600g2mini:~$ jellyfin 
[13:57:27] [INF] [1] Main: Jellyfin version: 10.8.8
[13:57:27] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/greg/.local/share/jellyfin/log]"]
[13:57:27] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[13:57:27] [INF] [1] Main: Operating system: Linux
[13:57:27] [INF] [1] Main: Architecture: X64
[13:57:27] [INF] [1] Main: 64-Bit Process: True
[13:57:27] [INF] [1] Main: User Interactive: True
[13:57:27] [INF] [1] Main: Processor count: 4
[13:57:27] [INF] [1] Main: Program data path: /home/greg/.local/share/jellyfin
[13:57:27] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[13:57:27] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[13:57:27] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/greg/.cache/jellyfin
[13:57:27] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[13:57:27] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:57:27] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[13:57:27] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[13:57:27] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[13:57:27] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[13:57:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.8.0
[13:57:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.8.0
[13:57:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.8.0
[13:57:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.8.0
[13:57:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.8.0
[13:57:29] [INF] [1] Main: Kestrel listening on Any IP4 Address
[13:57:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[13:57:30] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2023-01-13 02:00:00.000 -08:00, which is 12:02:29.9904830 from now.
[13:57:30] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ffmpeg' with working directory '/home/greg'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[13:57:30] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: ffmpeg
[13:57:30] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: 
[13:57:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: e5ee5e77a0a942f6b271bd2f9e0a5c0c
[13:57:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0855948
[13:57:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[13:57:30] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1127052
[13:57:30] [INF] [1] Main: Startup complete 0:00:02.9714563
```

After apt installing ffmpeg manually, the web UI still does not load, although it's unclear to me whether this is due to the jellyfin-web error or some other bug.

```
[15:02:48] [INF] [1] Main: Jellyfin version: 10.8.8
[15:02:48] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /home/greg/.local/share/jellyfin/log]"]
[15:02:48] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[15:02:48] [INF] [1] Main: Operating system: Linux
[15:02:48] [INF] [1] Main: Architecture: X64
[15:02:48] [INF] [1] Main: 64-Bit Process: True
[15:02:48] [INF] [1] Main: User Interactive: True
[15:02:48] [INF] [1] Main: Processor count: 4
[15:02:48] [INF] [1] Main: Program data path: /home/greg/.local/share/jellyfin
[15:02:48] [INF] [1] Main: Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
[15:02:48] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[15:02:48] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/greg/.cache/jellyfin
[15:02:48] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[15:02:48] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[15:02:48] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[15:02:48] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[15:02:48] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[15:02:48] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[15:02:50] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.8.0
[15:02:50] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.8.0
[15:02:50] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.8.0
[15:02:50] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.8.0
[15:02:50] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.8.0
[15:02:50] [INF] [1] Main: Kestrel listening on Any IP4 Address
[15:02:50] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[15:02:50] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2023-01-13 02:00:00.000 -08:00, which is 10:57:09.5463736 from now.
[15:02:50] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.5
[15:02:50] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "h264", "h264_qsv", "hevc", "hevc_qsv", "mpeg2video", "mpeg2_qsv", "mpeg4", "msmpeg4", "vc1_qsv", "vp8", "libvpx", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[15:02:50] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[15:02:51] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "overlay_opencl", "overlay_qsv", "procamp_vaapi", "scale_qsv", "scale_vaapi", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv"]
[15:02:51] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: scale_cuda with option Output format (default "same") is not available
[15:02:51] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: tonemap_cuda with option GPU accelerated HDR to SDR tonemapping is not available
[15:02:51] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: overlay_vaapi with option Action to take when encountering EOF from secondary input is not available
[15:02:51] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "vaapi", "qsv", "drm", "opencl"]
[15:02:51] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: ffmpeg
[15:02:51] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: e5ee5e77a0a942f6b271bd2f9e0a5c0c
[15:02:51] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0821571
[15:02:51] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[15:02:51] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1107457
[15:02:51] [INF] [1] Main: Startup complete 0:00:03.9040358
[15:02:53] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[15:02:53] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[15:02:53] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[15:02:54] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[15:02:54] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

possibly related to: https://github.com/jellyfin/jellyfin/issues/7902 ?

Unrelated to issue: is it recommended to use for hardware acceleration VA-API, or QSV? 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
      Kernel: Linux 5.10.0-20-amd64
      Architecture: x86-64
- Virtualization: no
- Clients: n/a
- Browser: Chromium
- FFmpeg Version: unknown
- Playback Method: n/a
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: default
- Networking: default
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tequenikality** [comment]
What method did you use to install JellyFin? I recently install JF on Debian 11 (stable) and used the cURL script that sets up the APT repository and everything for you, and I didn't experience this problem.

**Comment by EZUsername42** [comment]
> What method did you use to install JellyFin? I recently install JF on Debian 11 (stable) and used the cURL script that sets up the APT repository and everything for you, and I didn't experience this problem.

install-debuntu.sh
