### ISSUE TITLE
[Issue]: No artist images

### ISSUE THREAD

**Issue by YSPESHNUY** [jellyfin/jellyfin#9138]
### Please describe your bug

I'm new to jellyfin and I'm bad at computers. I can't get artist arts at all. They are all just blank. And I think that I can't get any metadata at all, for me it looks like it.

Steps to reproduce:
1. Install Jellyfin
2. Scan for metadata
3. Rescan 
4. No images are added

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: 5.1.2
- Playback Method: No idea 
- Hardware Acceleration: none
- Plugins: audiodb, coverartarchive, musicbrainz, omdb, playback reporting, reports, studio images, tmdb
- Reverse Proxy:caddy
- Base URL: none
- Networking: none
- Storage: local
```

### Jellyfin logs

```shell
When I try to search for image in "edit images":
[2023-01-20 16:50:42.328 +00:00] [ERR] [35] MediaBrowser.Providers.Manager.ProviderManager: "AudioDbArtistImageProvider" failed in GetImageInfos for type "MusicArtist" at "/config/metadata/artists/Boards of Canada"
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.AudioDb.AudioDbArtistImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.AudioDb.AudioDbArtistImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)

When I just hit rescan metadata:
[2023-01-20 16:58:05.626 +00:00] [ERR] [106] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.InvalidOperationException: Cannot update refresh progress of item 'MusicArtist' (b083813b67226ba3a8359d9c29b02d3f) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass65_2.<ValidateChildrenInternal2>b__1(Double innerPercent)
   at MediaBrowser.Common.Progress.ActionableProgress`1.Report(T value)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<RunTasks>g__UpdateProgress|0()
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_1`1.<RunTasks>b__2(Double innerPercent)
   at MediaBrowser.Common.Progress.ActionableProgress`1.Report(T value)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass67_0.<<RefreshAllMetadataForContainer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshArtist(MusicArtist item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YSPESHNUY** [comment]
Fixed, just live somewhere outside of Russia

**Comment by YSPESHNUY** [comment]
Fixed, you just need to be somewhere not in Russia
