### ISSUE TITLE
[Issue]:  10.9.0/unstable - Scanning media library immediately fails.

### ISSUE THREAD

**Issue by satmandu** [jellyfin/jellyfin#9165]
### Please describe your bug

Scanning the media library immediately fails after switching the docker image to `jellyfin:unstable` from `jellyfin:latest`.

Also the first page (at `/web/index.html#/home.html`) shows nothing under the entries for collections/movies/shows.

Reverting the container to `jellyfin:latest` fixes the issue.

### Jellyfin Version

Other

### if other:

10.9.0 (docker jellyfin:unstable)

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Browser
- Browser: Google Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
2023-01-23 19:39:25.787 -05:00] [INF] [8] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2023-01-23 19:39:26.390 -05:00] [ERR] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.MissingMethodException: Method not found: 'Boolean MediaBrowser.Controller.BaseItemManager.IBaseItemManager.IsMetadataFetcherEnabled(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.String)'.
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.IsEnabledForLibrary(BaseItem item)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnProviderManagerRefreshComplete(Object sender, GenericEventArgs`1 genericEventArgs)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshComplete(BaseItem item)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-01-23 19:39:26.398 -05:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 0 seconds
[2023-01-23 19:39:26.402 -05:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
The Tvdb plugin hasn't been updated for 10.9 yet
