### ISSUE TITLE
[Issue]: Genres list in movie/tv show library not populated

### ISSUE THREAD

**Issue by Killface1980** [jellyfin/jellyfin#9232]
### Please describe your bug

Not sure if I've missed some configuration.
I have JF Server succesfully running on Windows for testing purposes with a fully populated genres list. All movies/shows reside in their own directory, together with an nfo which gets updated in JF.

On my QNAP, I have several setups failing to populate the genres listing. Used a QNAP package, now Container Station/Docker with r/w access. The Genre overview says "Nichts hier. Aktiviere einige Metadaten-Anbieter, um Genres aus dem Internet zu laden." ("Nothing here. Enable some metadata provider ...").
The genres show up on the movies, once clicked the JF wheel starts spinning and an error pops up in the log, see below.
In the movies/shows overview, filtering by genre works normally without issues.
Using a German UI with English genres for Kodi.
Using current 1.8.9. OMDB and TMDB plugins in that order are enabled and active for the library scan.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: QTS 5.0.1.2248
- Virtualization: Container Station / QPKG
- Clients:
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-02-01 20:27:19.187 +00:00] [ERR] [20] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/b30bb5d6adcc4932948955fa7c02181a/Items/1ffc72e19987e5fa4047c6a6870646cf".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method1020(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/16738568/216158019-f8252f78-e3d2-4dac-bc81-02207ef1eaaf.png)
![image](https://user-images.githubusercontent.com/16738568/216158238-6f06d7ac-a8b6-41da-a3a8-39f4acd19d30.png)
![image](https://user-images.githubusercontent.com/16738568/216159802-18644ff2-b422-4b5e-adaf-6b60edd2ecd4.png)
![image](https://user-images.githubusercontent.com/16738568/216160075-ab893e81-7c64-48a8-ad2e-f4caad098617.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Killface1980** [comment]
Update:

On the faulty version, I've renamed my libraries which forced a metadata deletion.
Once scanning started, the genres began populating and work as expected.

**Comment by crisc2000** [comment]
This bug still exist in the version jellyfin_10.8.10_windows-x64 . It was first install, I have added a Movies type library, and added some folders that contain movie files. All the settings where left default.

When I try to access Library Movies -> Genres , this message appear.
![2023-08-28](https://github.com/jellyfin/jellyfin/assets/1497398/2868ecee-a274-49f8-9051-1099b6ed6ed1)

I had to do the same as original poster. I did not modified any settings, just I have rename the Movies library and that forced a refresh. After that the Genres appeared.

This is clearly an unfixed bug.

**Comment by lochsenfeld** [comment]
Same for me on lscr.io/linuxserver/jellyfin:latest running on arm64
Fixed it by renaming the library

**Comment by sevenrats** [comment]
Hey guys, thank you for this info. We could use some specific information about this issue.  My guess is that your media comes with nfo files which do not contain genre info and this is causing unexpected behavior.  I'd like you guys to test a few different things if you don't mind.  Does simply  scanning with "Replace all metadata" fix the issue, without renaming?  Does deleting the .nfo file and rescanning with "Check for new and updated files" correct it, without otherwise replacing or renaming?  Can you please show us some .nfo files before and after correcting this issue? I'm going to queue this issue up for reproduction by our triage team, but the fastest way forward is to get the info from you, the reporters.  Please let us know if you find the answer to any of these questions.

**Comment by Killface1980** [comment]
As I resolved the issue, I'll try to answer from my memory.

> My guess is that your media comes with nfo files which do not contain genre info and this is causing unexpected behavior. 
Possible that the genre was empty in some cases (1 of 500?), but cannot confirm. Maybe the nfo of a release group found its way into my library?

> I'd like you guys to test a few different things if you don't mind. Does simply scanning with "Replace all metadata" fix the issue, without renaming?
Did it multiple times without success.

> Does deleting the .nfo file and rescanning with "Check for new and updated files" correct it, without otherwise replacing or renaming? Can you please show us some .nfo files before and after correcting this issue? 
Unfortunately not, as this happened a while ago.

**Comment by joshuaavalon** [comment]
I can trigger it on a new Jellyfin (10.8.11) install with 1 movie.

![image](https://github.com/jellyfin/jellyfin/assets/7152420/11163465-3ba9-4301-a100-9d5d133f0675)
![image](https://github.com/jellyfin/jellyfin/assets/7152420/c58c6335-2f96-4264-bf34-88f7d644def5)
![image](https://github.com/jellyfin/jellyfin/assets/7152420/7ae61e84-21c9-42c9-821f-50c704e68259)
![image](https://github.com/jellyfin/jellyfin/assets/7152420/e3e4f405-5f8a-45c1-a66d-ea33c4f6c0f3)

I just click on the genre on the movie page cause the error log.

```
[19:19:02] [ERR] [30] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/321575e76b0f456eb74b1c88780ec885/Items/dffb0592c24fdc00277dcd7f62b4469a.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method637(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by sevenrats** [comment]
thanks everybody.  this issue could use reproduction instructions. @joshuaavalon do you mind commenting step-by-step how you reproduced this? the lower we hang this fruit the more likely it is that some dev will pick it.

**Comment by kavemang** [comment]
I'm experiencing this on a new db with an old library 10.10.7 (f4b8aa0ed)

**Comment by rpatterson** [comment]
Here's what I observe under Jellyfin Server v10.11.0 running on Windows.

- add a new genre to a movie using the `Edit Metadata` web UI
- the new genre shows up in the filters checkboxes of the main movies listing at `/web/#/movies`
- that movie shows up when checking the new genre filter
- the `Genres` tab at the top of the main movies listing lists other existing genres,  but the new genre isn't listed
- the new genre shows as a link on the individual movies details page, and clicking it loads the  page at `/web/#/list`
- but the listing is empty and the progress indicator spins for a very long time and I assume it times out
- and the new genre does *not* show up under `Filter` on that page while the existing genres do

**Comment by rpatterson** [comment]
I clicked the `Scan All Libraries` on the `/web/#/dashboard` page and the new genre now shows up in all the places it was missing from and the link from the movie details page also now works. The new genre does *not* show up in those places when scanning the individual library with either `Scan for new and updated files` or `Search for missing metadata` options.

**Comment by awghdbs** [comment]
> I clicked the `Scan All Libraries` on the `/web/#/dashboard` page and the new genre now shows up in all the places it was missing from and the link from the movie details page also now works. The new genre does _not_ show up in those places when scanning the individual library with either `Scan for new and updated files` or `Search for missing metadata` options.

Thanks a lot, this works for my music only library where some genres does not show up before run `Scan All Libraries`.
