### ISSUE TITLE
[Issue]: Library folders as symlinks are not detected

### ISSUE THREAD

**Issue by skibbipl** [jellyfin/jellyfin#9257]
### Please describe your bug

My media collection is scattered on multiple drives and I merged them into one folder /media by using symlinks:
```
ls -la /media
movies -> /mnt/NAS/disk1/movies
tvseries -> /mn/NAS/disk2/tvseries
```
However when I mapped my `/media` folder in docker I don't see mapped folder in library browser.

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: None
- Plugins: N/A
- Reverse Proxy: haproxy
- Base URL: N/A
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2023-02-05 13:49:06.857 +00:00] [ERR] [31] Emby.Server.Implementations.IO.ManagedFileSystem: Reading the file size of the symlink at "/media/movies" failed. Marking the file as not existing.
System.IO.FileNotFoundException: Could not find file '/media/movies'.
File name: '/media/movies'
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemMetadata(FileSystemInfo info)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmitrylyzo** [comment]
Isn't that how Docker works? Docker doesn't see the `/mnt` that is in the host system.

You can probably map `/mnt/NAS/disk1/movies` to `/media/movies` (I assume you don't want to map `/mnt/NAS/disk1` to docker `/media` directly).

You can also `mount --bind /mnt/NAS/disk1/movies /media/movies` instead of using the link. Be careful: don't remove `/media/movies` when bound - this will remove the actual data.

**Comment by Bond-009** [comment]
User error
