### ISSUE TITLE
Jellyfin Crash in unhandled exception everytime after playback stopped.

### ISSUE THREAD

**Issue by zelphar** [jellyfin/jellyfin#9262]
### Please describe your bug
After upgrade docker image to latest version.
everytime after playback stopped. jellyfin server crashed with below error:
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')

I have tried many times with many different media files.
and I have tried disable almost all of the 3rd party plugins.
last version have no error like this.

### Jellyfin Version
tested both in 10.8.9 Latest and 10.9.0 Unstable.
### Jellyfin logs
```
[2023-02-06 00:48:46.585 +08:00] [INF] [57] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "9a61d54a-2ab6-4873-a688-40a0e1dfe1c5-5444d3eb2d3344a19e3c8643efd691a5-9a552671942bf32a2af315cfe43d7f72"
[2023-02-06 00:49:07.585 +08:00] [INF] [60] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "9a61d54a-2ab6-4873-a688-40a0e1dfe1c5-5444d3eb2d3344a19e3c8643efd691a5-9a552671942bf32a2af315cfe43d7f72"
[2023-02-06 00:49:14.875 +08:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Kodi" "0.7.10 py3" playing "预言". Stopped at "1351000" ms
[2023-02-06 00:49:15.089 +08:00] [FTL] [51] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2023-02-06 00:49:15.095 +08:00] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "9a61d54a-2ab6-4873-a688-40a0e1dfe1c5-5444d3eb2d3344a19e3c8643efd691a5-9a552671942bf32a2af315cfe43d7f72"
[2023-02-06 00:49:15.096 +08:00] [INF] [46] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 02/06/2023 00:49:15
[2023-02-06 00:49:15.096 +08:00] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
```
### FFmpeg logs
```
frame=31028 fps=20678 q=-1.0 size=N/A time=00:21:34.37 bitrate=N/A speed= 863x    
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc236.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc237.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc238.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc239.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc240.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc241.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc242.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc243.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc244.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc245.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc246.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc247.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc248.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc249.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc250.ts' for writing
[hls @ 0x56001b1e7d80] Opening '/config/transcodes/188250dee6466e9847e3f3a061b87ccc251.ts' for writing
frame=33179 fps=21304 q=-1.0 Lsize=N/A time=00:23:03.97 bitrate=N/A speed= 889x    
video:359446kB audio:21623kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```
### Please attach any browser or client logs here

No response
### Please attach any screenshots here
![图片](https://user-images.githubusercontent.com/15126825/216833268-b53cd9b9-840b-4390-a68f-01405a666e90.png)

No response
### Code of Conduct

**Comment by Bond-009** [comment]
Issue with the `jellyfin_ani_sync` plugin
https://github.com/vosmiic/jellyfin-ani-sync
