### ISSUE TITLE
can not play video

### ISSUE THREAD

**Issue by sakka6868** [jellyfin/jellyfin#9265]
**Media Info of the file**

概览
ID                             : 1 (0x1)
完整名称                           : D:\download\videos\狂飙\狂飙-01.mp4
格式                             : MPEG-TS
文件大小                           : 702 MiB
时长                             : 45 分 44 秒
总体码率模式                         : 动态码率 (VBR)
总体码率                           : 2 146 kb/s
FileExtension_Invalid          : ts m2t m2s m4t m4s tmf ts tp trp ty

视频
ID                             : 256 (0x100)
菜单 ID                          : 1 (0x1)
格式                             : AVC
格式/信息                          : Advanced Video Codec
格式配置 (Profile)                 : High@L4
格式设置                           : CABAC / 3 Ref Frames
格式设置, CABAC                    : 是
格式设置, 参考帧                      : 3 帧
编解码器 ID                        : 27
时长                             : 45 分 44 秒
宽度                             : 1 920 像素
高度                             : 1 080 像素
画面比例                           : 16:9
帧率                             : 25.000 FPS
色彩空间                           : YUV
色度抽样                           : 4:2:0
位深                             : 8 位
扫描类型                           : 逐行扫描 (连续)
色彩范围                           : Limited
色彩原色                           : BT.709
传输特性                           : BT.709
矩阵系数                           : BT.709

音频
ID                             : 257 (0x101)
菜单 ID                          : 1 (0x1)
格式                             : AAC LC
格式/信息                          : Advanced Audio Codec Low Complexity
格式版本                           : Version 4
混流模式                           : ADTS
编解码器 ID                        : 15-2
时长                             : 45 分 44 秒
码率模式                           : 动态码率 (VBR)
声道数                            : 2 声道
声道布局                           : L R
采样率                            : 44.1 kHz
帧率                             : 43.066 FPS (1024 SPF)
压缩模式                           : 有损

菜单
ID                             : 4096 (0x1000)
菜单 ID                          : 1 (0x1)
格式                             : AVC / AAC
时长                             : 45 分 44 秒
列表                             : 256 (0x100) (AVC) / 257 (0x101) (AAC)
服务名称                           : Service01
服务提供商                          : FFmpeg
服务类型                           : digital television

**Logs**
```
[2023-02-06 04:19:41.921 +00:00] [ERR] [109] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Items/ec2d7da8e9d45da59da55530f3137b10/PlaybackInfo".
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.IsEligibleForDirectPlay(MediaSourceInfo item, Int64 maxBitrate, MediaStream subtitleStream, MediaStream audioStream, VideoOptions options, PlayMethod playMethod)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Jellyfin.Api.Helpers.MediaInfoHelper.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy, IPAddress ipAddress)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
   at lambda_method1069(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
**FFmpeg Logs**

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/23228684/216883863-7d280320-0d3e-4e64-a6a5-bc61a99bccef.png)
![image](https://user-images.githubusercontent.com/23228684/216883929-d15fe551-6c2f-4984-be37-d46bb6218e9f.png)

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.0
 - Hardware settings & device: NVENC 

 
**Client System (please complete the following information):**
 - OS: Windows
 - Client: Web/Browser
 - Browser (if Web client): Chrome
 - Client and Browser Version: 109.0.5414.120

**Comment by Silur** [comment]
Same issue, trying to play any video into a DLNA sink using 10.8.0 on linux
