### ISSUE TITLE
[Issue]: Error in "MusicBrainz"

### ISSUE THREAD

**Issue by jagiella** [jellyfin/jellyfin#9283]
### Please describe your bug

Since a few weeks scanning the music library is slow and frequently leads to crash and restart of the jellyfin server. 

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: armbian 
- Virtualization: deb-package from unstable repository
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: default plugins + Trakt
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-02-09 00:08:58.315 +01:00] [ERR] Error in "MusicBrainz"
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at MetaBrainz.MusicBrainz.Query.BuildUri(String path, String extra)
   at MetaBrainz.MusicBrainz.Query.<>c__DisplayClass706_0.<PerformRequestAsync>b__0()
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`1 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(String entity, String id, String extra, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.PerformRequestAsync(CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.NextAsync(CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
I'm using personal fork from master as well and also encounters this issue.

I ended up with commenting out artist search in `MusicBrainzArtistProvider` as I do not need it and here's the patch:

```patch
Subject: [PATCH] force disable buggy musicbrainz
---
Index: MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs b/MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs
--- a/MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs	(revision 073a064a8e27b33ae794d8cce7cda20fcb39f376)
+++ b/MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzArtistProvider.cs	(revision f7e0ccdca6b25894ed2f2a3104ee385ad3df084e)
@@ -72,23 +72,23 @@
             return GetResultFromResponse(artistResult).SingleItemAsEnumerable();
         }

-        var artistSearchResults = await _musicBrainzQuery.FindArtistsAsync($"\"{searchInfo.Name}\"", null, null, false, cancellationToken)
-            .ConfigureAwait(false);
-        if (artistSearchResults.Results.Count > 0)
-        {
-            return GetResultsFromResponse(artistSearchResults.Results);
-        }
-
-        if (searchInfo.Name.HasDiacritics())
-        {
-            // Try again using the search with an accented characters query
-            var artistAccentsSearchResults = await _musicBrainzQuery.FindArtistsAsync($"artistaccent:\"{searchInfo.Name}\"", null, null, false, cancellationToken)
-                .ConfigureAwait(false);
-            if (artistAccentsSearchResults.Results.Count > 0)
-            {
-                return GetResultsFromResponse(artistAccentsSearchResults.Results);
-            }
-        }
+        // var artistSearchResults = await _musicBrainzQuery.FindArtistsAsync($"\"{searchInfo.Name}\"", null, null, false, cancellationToken)
+        //     .ConfigureAwait(false);
+        // if (artistSearchResults.Results.Count > 0)
+        // {
+        //     return GetResultsFromResponse(artistSearchResults.Results);
+        // }
+        //
+        // if (searchInfo.Name.HasDiacritics())
+        // {
+        //     // Try again using the search with an accented characters query
+        //     var artistAccentsSearchResults = await _musicBrainzQuery.FindArtistsAsync($"artistaccent:\"{searchInfo.Name}\"", null, null, false, cancellationToken)
+        //         .ConfigureAwait(false);
+        //     if (artistAccentsSearchResults.Results.Count > 0)
+        //     {
+        //         return GetResultsFromResponse(artistAccentsSearchResults.Results);
+        //     }
+        // }

         return Enumerable.Empty<RemoteSearchResult>();
     }

```

If you do rely on this then you need a proper fix.

**Comment by Bond-009** [comment]
This should have been fixed by #8833 which commit are you running?

**Comment by gnattu** [comment]
The last commit I rebased on was 421b062ca423c292d33490f0286925f2f1a0c033

And my tree does contain #8833. My MusicBranz Config page has a url set to `https://musicbrainz.org`

**Comment by jagiella** [comment]
```bash
jellyfin-ffmpeg5/unbekannt,now 5.1.2-7-kinetic arm64  [installiert]
jellyfin-ffmpeg/now 5.0.1-2-jammy arm64 [Konfiguration-verbleibend]
jellyfin-server/unbekannt,now 20230204.1-unstable arm64  [Installiert,automatisch]
jellyfin-web/now 20220906.1-unstable all  [Installiert,lokal]
jellyfin/unbekannt,now 10.8.9-1 all  [installiert]
```
