### ISSUE TITLE
[Issue]: Docker using specific user and group not root

### ISSUE THREAD

**Issue by HuwSy** [jellyfin/jellyfin#9317]
### Please describe your bug

**Environment**
Docker on ReadyNAS (v18 under Debian Jessie)
Jellyfin :latest and :unstable

**Config**
```
docker create --name=jellyfin \
--restart=always \
--user 1001:1001 \
--group-add=$(cat /etc/group | grep -e video | cut -d ":" -f 3)\
-v /home/jellyfin/[config:/config](http://config/config) \
-v /home/jellyfin/[cache:/cache](http://cache/cache) \
--mount type=bind,source=/data/Media,target=/Media,readonly \
--device=/dev/dri/[card0:/dev/dri/card0](http://card0/dev/dri/card0) \
--device=/dev/dri/[renderD128:/dev/dri/renderD128](http://renderd128/dev/dri/renderD128) \
-e TZ=Europe/London \
-p 8096:8096 \
jellyfin/jellyfin:unstable
docker start jellyfin
```

**Expected outcome**
Docker running under non root user and still fully functional

**Actual outcome**
Docker starts and runs successfully and lets me click into the media and click download to get the media at client (so file access permission is correct) but clicking to play in client just sits there loading not even progressing to the media player screen.

I have tried with non existent user uid, gid, ones that are in the container, ones that are on host and ones that are on both container and host but it only ever plays with root.

I have also tried with and without hardware transcoding enabled.

I have connected to the docker session using _docker exec -it jellyfin bash_ to confirm that it can access the media and _head /Media/bbb.mkv_ outputs data as expected. Using _/usr/lib/jellyfin-ffmpeg/ffmpeg -i /..._ within the docker container I get

```
  Duration: 01:52:40.32, start: 0.000000, bitrate: 867 kb/s
  Stream #0:0: Video: mpeg4 (DX50 / 0x30355844), yuv420p, 512x208 [SAR 1:1 DAR 32:13], 761 kb/s, 25 fps, 25 tbr, 25 tbn
  Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, fltp, 96 kb/s
```
 

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: ReadyNAS OS 10.8.6 Debian Jessie
- Virtualization: Docker v18
- Clients: Web and Roku
- Browser: Safari ios16, Firefox 102
- FFmpeg Version: Jellyfin within docker
- Playback Method: Direct stream, Transcode
- Hardware Acceleration: None, VAAPI, Intel
- Plugins: No additional
- Reverse Proxy: None
- Base URL: /
- Networking: Docker port 8096 NAT
- Storage: local
```

### Jellyfin logs

```shell
[2023-02-15 16:07:44.061 +00:00] [INF] [1] Main: Jellyfin version: "10.9.0"
[2023-02-15 16:07:44.089 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_DATA_DIR, /config]"]
[2023-02-15 16:07:44.091 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2023-02-15 16:07:44.091 +00:00] [INF] [1] Main: Operating system: "Linux 4.4.218.x86_64.1 #1 SMP Mon Mar 14 21:33:09 UTC 2022"
[2023-02-15 16:07:44.091 +00:00] [INF] [1] Main: Architecture: X64
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: 64-Bit Process: True
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: User Interactive: True
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: Processor count: 4
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: Program data path: "/config"
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2023-02-15 16:07:44.096 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2023-02-15 16:07:44.550 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2023-02-15 16:07:44.954 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-02-15 16:07:45.050 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/TMDb Box Sets_10.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll"
[2023-02-15 16:07:45.213 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[172.16.0.1/16]"
[2023-02-15 16:07:45.213 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-02-15 16:07:45.214 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[172.16.0.0/16]"
[2023-02-15 16:07:45.221 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-02-15 16:07:45.222 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-02-15 16:07:49.066 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb Box Sets" "10.0.0.0"
[2023-02-15 16:07:49.067 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.0.0"
[2023-02-15 16:07:49.068 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.0.0"
[2023-02-15 16:07:49.068 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.0.0"
[2023-02-15 16:07:49.093 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.0.0"
[2023-02-15 16:07:49.093 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.0.0"
[2023-02-15 16:07:49.197 +00:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[2023-02-15 16:07:49.197 +00:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[2023-02-15 16:07:49.202 +00:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2023-02-15 16:07:49.226 +00:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {ee73ed26-db97-4ef2-9351-9976cbe18df6} may be persisted to storage in unencrypted form.
[2023-02-15 16:07:49.811 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-02-15 16:07:49.860 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Scan library for new box sets" set to fire at 2023-02-16 04:00:00.000 +00:00, which is 11:52:10.1401889 from now.
[2023-02-15 16:07:49.868 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Download missing subtitles" set to fire at 2023-02-16 06:00:00.000 +00:00, which is 13:52:10.1319551 from now.
[2023-02-15 16:07:49.868 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2023-02-16 06:00:00.000 +00:00, which is 13:52:10.1313708 from now.
[2023-02-15 16:07:49.869 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Clean Cache Directory" set to fire at 2023-02-16 04:00:00.000 +00:00, which is 11:52:10.1303381 from now.
[2023-02-15 16:07:49.870 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Clean Log Directory" set to fire at 2023-02-16 04:00:00.000 +00:00, which is 11:52:10.1299970 from now.
[2023-02-15 16:07:49.870 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Clean Transcode Directory" set to fire at 2023-02-16 04:00:00.000 +00:00, which is 11:52:10.1297206 from now.
[2023-02-15 16:07:49.870 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Optimise database" set to fire at 2023-02-16 04:00:00.000 +00:00, which is 11:52:10.1294393 from now.
[2023-02-15 16:07:49.870 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Refresh People" set to fire at 2023-02-16 06:00:00.000 +00:00, which is 13:52:10.1291621 from now.
[2023-02-15 16:07:51.429 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.2"
[2023-02-15 16:07:51.456 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2023-02-15 16:07:51.472 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2023-02-15 16:07:51.487 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-02-15 16:07:51.577 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2023-02-15 16:07:51.726 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2023-02-15 16:07:51.727 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "7e87a296454f41ba9a119bf7e466763d"
[2023-02-15 16:07:51.864 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1313558
[2023-02-15 16:07:51.864 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2023-02-15 16:07:52.093 +00:00] [ERR] [11] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "/..."
System.UnauthorizedAccessException: Access to the path '/...' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2023-02-15 16:07:52.094 +00:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/..."
[2023-02-15 16:07:52.096 +00:00] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/..."
[2023-02-15 16:07:52.096 +00:00] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/config/data/collections"
[2023-02-15 16:07:52.097 +00:00] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/..."
[2023-02-15 16:07:52.098 +00:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/..."
[2023-02-15 16:07:52.105 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.2413959
[2023-02-15 16:07:52.106 +00:00] [INF] [1] Main: Startup complete 0:00:08.6362276
[2023-02-15 16:07:52.903 +00:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2023-02-15 16:07:52.905 +00:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2023-02-15 16:07:52.910 +00:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2023-02-15 16:07:53.948 +00:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2023-02-15 16:07:53.953 +00:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-02-15 16:07:55.365 +00:00] [ERR] [12] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/58442033fc3031921a2c9685524e31d5/AdditionalParts".
System.TypeInitializationException: The type initializer for 'Nikse.SubtitleEdit.Core.Common.Configuration' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path '/Subtitle Edit' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Nikse.SubtitleEdit.Core.Common.Configuration.GetDataDirectory()
   at Nikse.SubtitleEdit.Core.Common.Configuration..cctor()
   --- End of inner exception stack trace ---
   at Nikse.SubtitleEdit.Core.Common.Configuration.get_Settings()
   at Nikse.SubtitleEdit.Core.SubtitleFormats.MPlayer2.get_Extension()
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser.<>c.<.ctor>b__2_0(SubtitleFormat subtitleFormat)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser..ctor(ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-02-15 16:08:07.740 +00:00] [INF] [10] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.16.162.172" request
```

### FFmpeg logs

```shell
Never gets here to generate any logs
```

### Please attach any browser or client logs here

Requesting http://172.16.0.254:8096/Users/b5fbf68f7c8c449183209c346f3cd9a8/Items/58442033fc3031921a2c9685524e31d5 node_modules.jellyfin-apiclient.bundle.js:1:5395
Requesting http://172.16.0.254:8096/Videos/58442033fc3031921a2c9685524e31d5/AdditionalParts?userId=b5fbf68f7c8c449183209c346f3cd9a8 node_modules.jellyfin-apiclient.bundle.js:1:5395
XHRGEThttp://172.16.0.254:8096/Videos/58442033fc3031921a2c9685524e31d5/AdditionalParts?userId=b5fbf68f7c8c449183209c346f3cd9a8
[HTTP/1.1 500 Internal Server Error 46ms]

Request failed to http://172.16.0.254:8096/Videos/58442033fc3031921a2c9685524e31d5/AdditionalParts?userId=b5fbf68f7c8c449183209c346f3cd9a8 [object Response] node_modules.jellyfin-apiclient.bundle.js:1:5775
Reporting request failure node_modules.jellyfin-apiclient.bundle.js:1:5921
Uncaught (in promise) 
Response { type: "basic", url: "http://172.16.0.254:8096/Videos/58442033fc3031921a2c9685524e31d5/AdditionalParts?userId=b5fbf68f7c8c449183209c346f3cd9a8", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers(5), body: ReadableStream, bodyUsed: false }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HuwSy** [comment]
Actually my error on latest was different and resolvable permissions. Unstable the error above seems to be related to an existing open issue so closing this here.

**Comment by badaz** [comment]
> Actually my error on latest was different and resolvable permissions. Unstable the error above seems to be related to an existing open issue so closing this here.

Could you link the issue please?
