### ISSUE TITLE
Error pulling metadata from gz compressed XML source pulled from Xtream

### ISSUE THREAD

**Issue by maurirope** [jellyfin/jellyfin#9324]
https://github.com/jellyfin/jellyfin/blob/43c3a465e6a24d4d5c9602fb478da41ec09009ae/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs#L374

I'm getting the following logs when trying to pull XMLTV data from that provider for EPG

[2023-02-16 01:05:56.697 +00:00] [INF] xmltv path: "https://xtream-editor.com/en/get/epg/F49D33B008EC4528897C914D78D74A0B"
[2023-02-16 01:05:56.697 +00:00] [INF] Downloading xmltv listings from "https://xtream-editor.com/en/get/epg/F49D33B008EC4528897C914D78D74A0B"
[2023-02-16 01:06:11.322 +00:00] [ERR] Error adding metadata
System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Jellyfin.XmlTv.XmlTvReader.GetChannels()
   at Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.GetChannelsAsync(Boolean enableCache, CancellationToken cancellationToken)
[2023-02-16 01:06:15.102 +00:00] [INF] Refreshing guide with 7 days of guide data
[2023-02-16 01:06:15.103 +00:00] [INF] xmltv path: "https://xtream-editor.com/en/get/epg/F49D33B008EC4528897C914D78D74A0B"
[2023-02-16 01:06:15.103 +00:00] [ERR] Error adding metadata
System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.

I've downloaded your source code to look around the exception and try and figure out where it originates or what it is Jellyfin trying to do when the exception happens. So far my limited knowledge hasn't brought me anywhere but I couldn't stop to notice there is an IF statement on line 372 that has some code under it that will not run due to being commented and it seems like something important because it references the name of the item that I guess is trying to get accesed. Also it is just untidy for that code to be there so I thought it would be useful if I brought it to your attention.

At first I thought it couldn't be open because of compression but I realized you do have support for that so I don't think it is related to that. Also it seems that this char 0x1F is some kind of windows control char for empty char and so that sounds to be related to not being able to pull a name from an empty string. Sorry if this is confusing.

The URL for the XML data I'm using is https://xtream-editor.com/en/get/epg/F49D33B008EC4528897C914D78D74A0B

I am able to provide more info if needed for diagnosis.

Thanks for your attention today,
Mauricio

**Comment by bugfixin** [comment]
I think your link includes a personal token which has resulted in your token being blocked for the day - you may want to hide that and instead include a verbose log of the web request (with headers / file data), but it also seems that their server is replying with an .xml.gz - I would expect jellyfin to handle transparent compression from the HTTP transfer, but I'm not sure it can handle receiving a gz file instead of xml. 

Based on the fact that the exception is thrown on line1 position1 it definitely seems like the xmlreader is being passed non-xml content.
