### ISSUE TITLE
Server without internet and TMDB on demand people metadata

### ISSUE THREAD

**Issue by TotoCon** [jellyfin/jellyfin#9347]
I run my server without internet, disabled all metadata providers and manage my metadata with Tinimediamanager.
Right now, jellyfin tries to reach out to TMDB for additional metadata for people **on demand** when you click on an actors image, even if you have disabled metadata providers. This request times out after around 10 seconds, because there is no internet connection.

This is the log and i know it is supposed to do exactly what it does:
```
[2023-02-18 13:10:50.199 +01:00] [ERR] [48] MediaBrowser.Providers.People.PersonMetadataService: Error in "TheMovieDb"
System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found. (api.themoviedb.org:443)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.EnsureClientConfigAsync()
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.SearchPersonAsync(String name, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.People.TmdbPersonProvider.GetMetadata(PersonLookupInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

There is no setting in jellyfin to avoid getting additional **on demand** metadata from TMDB. 
Is there any specific file i could edit as a workaround to shorten the timeout after given time or retries?

**Comment by shaino** [comment]
If it's simpler, you can change the DNS of 'api.themovedb. org' to 127.0.0.1, So the actor related movie will be released in seconds.

If you can compile the source code, you can go to "\ MediaBrowser.Providers \ plugins \ Tmdb \ People \ TmdbPersonProviders. cs
”Find the relevant code on line 89.
You can set the logical condition to set 'personTmdbId' to 0/1 and skip 'SearchPersonAsynchronous' and' GetPersonAssync '. The cost is that you lose the ability to update actor information and other features.
