### ISSUE TITLE
[Issue]: Having issues scanning my libraries

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin/jellyfin#9354]
### Please describe your bug

I have tried to scan my libraries over the past few days but it keeps failing. I just looked at the logs but i don't understand it. Any help would be appreciated.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS:Windows 10
- Clients:JMP, Roku, Web
- Browser:Firefox and Safari
```

### Jellyfin logs

```shell
[2023-02-19 13:01:53.550 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2023-02-19 13:01:53.557 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\Music\Kim Music"
[2023-02-19 13:01:53.560 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "M:\"
[2023-02-19 13:01:53.563 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "L:\"
[2023-02-19 13:01:53.566 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\Music\AlexMusic"
[2023-02-19 13:01:53.569 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "G:\Anime Movies"
[2023-02-19 13:01:53.571 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "I:\"
[2023-02-19 13:01:53.573 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "E:\Anime"
[2023-02-19 13:01:53.577 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "G:\Movies"
[2023-02-19 13:01:53.580 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "E:\Cartoons"
[2023-02-19 13:01:53.582 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "J:\"
[2023-02-19 13:01:53.584 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\Internet Archive"
[2023-02-19 13:01:53.586 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "G:\4K Movies"
[2023-02-19 13:01:53.588 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\Music\Audio Books"
[2023-02-19 13:01:53.590 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "F:\TV1"
[2023-02-19 13:01:53.593 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "H:\"
[2023-02-19 13:01:53.598 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "N:\"
[2023-02-19 13:01:53.601 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "K:\"
[2023-02-19 13:01:53.604 +00:00] [INF] [31] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2023-02-19 13:01:58.383 +00:00] [ERR] [14] Jellyfin.Drawing.Skia.SkiaEncoder: Unable to determine image dimensions for "E:\Cartoons\Family Guy (1999)\Season 04\Family Guy - S04E12-20 - The Perfect Castaway + Jungle Love + PTV + Brian Goes Back to College + The Courtship of Stewie's Father + The Fat Guy Strangler + The Father, The Son, and The Holy Fonz + Brian Sings and Swings + Patriot Games.jpg": InternalError
[2023-02-19 13:02:02.774 +00:00] [INF] [37] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\Music\Kim Music"
[2023-02-19 13:02:02.774 +00:00] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\Music\AlexMusic"
[2023-02-19 13:02:02.774 +00:00] [INF] [7] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Anime Movies"
[2023-02-19 13:02:02.774 +00:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Anime"
[2023-02-19 13:02:02.774 +00:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Cartoons"
[2023-02-19 13:02:02.774 +00:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\4K Movies"
[2023-02-19 13:02:02.774 +00:00] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\Internet Archive"
[2023-02-19 13:02:02.774 +00:00] [INF] [40] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\Music\Audio Books"
[2023-02-19 13:02:02.774 +00:00] [INF] [28] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "G:\Movies"
[2023-02-19 13:02:02.774 +00:00] [INF] [41] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "F:\TV1"
[2023-02-19 13:02:02.774 +00:00] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "H:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [29] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "I:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "K:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "M:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [27] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "L:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [26] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "N:\"
[2023-02-19 13:02:02.774 +00:00] [INF] [38] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "J:\"
[2023-02-19 13:02:02.774 +00:00] [ERR] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.InvalidOperationException: Cannot update refresh progress of item 'Series' (3cfc7401ebf65a84bd5405fc13511256) because a refresh for this item is not running
   at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass72_0.<OnRefreshProgress>b__0(Guid _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-02-19 13:02:02.822 +00:00] [INF] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 9 seconds
[2023-02-19 13:02:02.827 +00:00] [INF] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

### Please attach any screenshots here

I have tried to scan my libraries over the past few days but it keeps failing. I just looked at the logs but i don't understand it. Any help would be appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gaffers2277** [comment]
Figured it out. I don't know how it is possibile but i had to folders in the same directory named the exact same. I thought that was impossible as windows would autorename it to like Folder(1) or something but deleting one of the folders fixed the scanning issue.
