### ISSUE TITLE
[Issue]: cannot play music on upnp device

### ISSUE THREAD

**Issue by rockymystic** [jellyfin/jellyfin#9396]
### Please describe your bug

I have issues while playing portable jellyfin in win server 2019, specifically while attempt to play on upnp device  https://www.engineered.ch/products/ered-dock/

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: windows server 2019
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[05:42:11] [INF] [4] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for ered-132 - eRED Audio Renderer
[05:42:11] [INF] [4] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
{"FriendlyName": "BubbleUPnP (SM-N950U)", "ModelNumber": "3.7.3.1", "SerialNumber": null, "ModelName": "BubbleUPnP Media Renderer", "ModelDescription": "BubbleUPnP Media Renderer", "ModelUrl": "", "Manufacturer": "Bubblesoft", "ManufacturerUrl": "http://forum.xda-developers.com/showthread.php?t=1118891", "Headers": [], "$type": "DeviceIdentification"}
[05:42:11] [INF] [4] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for BubbleUPnP (SM-N950U) - BubbleUPnP Media Renderer
[05:42:12] [ERR] [4] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for ered-132
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetAVProtocolAsync(CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rockymystic** [comment]
Hello, Is there anything more that i have to share? can anyone help me out here?
