### ISSUE TITLE
Specific season of TV show will not play if SyncPlay is enabled

### ISSUE THREAD

**Issue by xBelladonna** [jellyfin/jellyfin#9426]
This problem happens to every episode in Season 1 of Pokemon (Indigo League), and only that season, only when SyncPlay is enabled. Even if there is no other members except the group creator, playback still doesn't start. Without SyncPlay enabled, all episodes of this season play back successfully. The error displayed in the logs is shown as soon as the media playback starts, and happens whether SyncPlay is enabled or not. The browser console reports this error, also regardless of whether SyncPlay is enabled or not:

```
Uncaught (in promise) 
Response { type: "basic", url: "https://media.nightshade.fun/Sessions/Playing", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers(6), body: ReadableStream, bodyUsed: false }
body: ReadableStream { locked: false }
bodyUsed: false
headers: Headers(6) { "access-control-allow-origin" → "*", "content-type" → "text/plain", date → "Sat, 04 Mar 2023 05:06:34 GMT", … }
ok: false
redirected: false
status: 500
statusText: "Internal Server Error"
type: "basic"
url: "https://media.nightshade.fun/Sessions/Playing"
```

This issue persists even after reinstalling Jellyfin from scratch and using different versions of the media files in question, with different encoding. Jellyfin appears just to be allergic to the concept of Pokemon Season 1 when using SyncPlay.

**Media Info of the file**
```
Pokémon SE1 EP001 - Pokémon - I Choose You!
Container: avi
Path: /media/tvshows/Pokemon/Season 1 - Indigo League/Pokémon SE1 EP001 - Pokémon - I Choose You!.avi
Size: 174 MB

Video
Title: 480p MPEG4 SDR
Codec: MPEG4
Codec tag: XVID
Profile: Advanced Simple Profile
Level: 5
Resolution: 640x480
Aspect ratio: 4:3
Interlaced: No
Framerate: 23.976
Bitrate: 985 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1

Audio
Title: MP3 - Stereo
Codec: MP3
Layout: stereo
Channels: 2 ch
Bitrate: 128 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No
```

**Logs**
```
[15:43:50] [INF] [32] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -f avi -autorotate 0 -i file:"/media/tvshows/Pokemon/Season 1 - Indigo League/Pokémon SE1 EP001 - Pokémon - I Choose You!.avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 4925460 -bufsize 9850920 -profile:v:0 high -level 51 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -sc_threshold:v:0 0 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(640\,480*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(640/a\,480))/2)*2,format=yuv420p" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 4096 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/3f6b5bd22b74bf18a61e540fe166ca67%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/3f6b5bd22b74bf18a61e540fe166ca67.m3u8"
[15:43:51] [ERR] [20] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Sessions/Playing.
Error: SQLitePCL.pretty.SQLiteException: Expression tree is too large (maximum depth 1000)
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemList(InternalItemsQuery query, Boolean allowExternalContent)
   at Emby.Server.Implementations.Session.SessionManager.UpdateNowPlayingItem(SessionInfo session, PlaybackProgressInfo info, BaseItem libraryItem, Boolean updateLastCheckInTime)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackStart(PlaybackStartInfo info)
   at Jellyfin.Api.Controllers.PlaystateController.ReportPlaybackStart(PlaybackStartInfo playbackStartInfo)
   at lambda_method1197(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
```

**FFmpeg Logs**
Included above on first line

**Stats for Nerds Screenshots**
Unsure if "Playback Info" is what is meant by this as I cannot find "Stats for Nerds" anywhere in the playback interface. Here is the Playback Info popup:
![image](https://user-images.githubusercontent.com/47324660/222876525-83ebde7c-a10c-4c7d-8352-1e1cddde9a7d.png)

**Server System (please complete the following information):**
 - OS: Docker on Debian 11 (using Jellyfin container by LinuxServer)
 - Jellyfin Version: 10.8.9
 - Hardware settings & device: No hardware acceleration enabled
 - Reverse proxy: nginx
 - Other hardware notes: Media mounted from NFS share onto the host and bind mounted in container
 
**Client System (please complete the following information):**
Multiple client devices tested, all devices using same client and browser configuration as below:
 - Device: QEMU KVM-based VM running Debian 11, QEMU KVM-based VM running Windows 11, and Dell XPS 13 9305 running Debian 11
 - OS: Linux, Windows
 - Client: Jellyfin web client
 - Browser (if Web client): Firefox, Chromium
 - Client and Browser Version: 10.8.9, 110.0.5481.100 (Chromium), 110.0 (Firefox)

**Comment by xBelladonna** [comment]
Issue has been solved. Thanks.

**Comment by meteorite6** [comment]
@xBelladonna 
How did you solve it? Thank you
