### ISSUE TITLE
[Issue]: TheMovieDB requests always timeout

### ISSUE THREAD

**Issue by saloniamatteo** [jellyfin/jellyfin#9438]
### Please describe your bug

When I try to fetch metadata for a movie, Jellyfin/TheMovieDB always times out.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Gentoo x86-64
- Virtualization: None
- Clients: Browser
- Browser: Firefox 109
- Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles, Studio Images, TMDb, TheTVDB
- Reverse Proxy: nginx
- Base URL: yes (I do not want to disclose it)
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2023-03-05 19:41:58.641 +01:00] [ERR] [339] MediaBrowser.Providers.Manager.ProviderManager: Provider "TheMovieDb" failed to retrieve search results
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.FindAsync(FindExternalSource source, String id, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.FindByExternalIdAsync(String externalId, FindExternalSource source, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cichy45** [comment]
Hm, I have something similar on Windows when using VPN. JF can not download movie info when VPN is enabled. All JF exe files are selected as not using VPN in VPN app and it is working for streaming but not for downloading metadata - it looks like no connection. I can not provide any logs at this moment however.

**Comment by saloniamatteo** [comment]
I was able to solve this issue, by disabling IPv6 connectivity.

This means, Jellyfin networking code needs to be fixed in order to properly handle IPv6 (timeouts, requests, etc.)

**Comment by kambala-decapitator** [comment]
at least server responds to `/Users/AuthenticateByName` just fine from LAN and external network over IPv6
