### ISSUE TITLE
[Issue]: Possible memory leak on error System.NullReferenceException

### ISSUE THREAD

**Issue by dr41nU** [jellyfin/jellyfin#9442]
### Please describe your bug

The amount of memory used is constantly increasing even when idle
After a while, the process is killed by OOM.
This trouble is probably linked to some errors (System.NullReferenceException: Object reference not set to an instance of an object) during scan phase, since the used memory is growing at the same time the errors are shown in log

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Debian
- Virtualization: No
- Clients: DLNA eventually
- Browser: Firefox (bug occurs at idle)
- FFmpeg Version: 7:4.3.5-0+deb11u1
- Playback Method: Any (bug occurs at idle)
- Hardware Acceleration: VAAPI
- Plugins: AudioDB 10.8.9.0, LDAP-Auth 16.0.0.0, MusicBrainz 10.8.9.0, OMDb 10.8.9.0, Studio Images 10.8.9.0, TMDb 10.8.9.0
- Reverse Proxy: nginx
- Base URL: /jellyfin
- Networking: 
- Storage: local
```

### Jellyfin logs

```shell
Mar 01 20:23:40 xxxxxxxxxx.fr jellyfin[579722]: [20:23:40] [WRN] [62] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.0.3:8096/jellyfin/dlna/ba355823-8553-4bee-a8a9-b35c4e7ffc86/contentdirectory/control to 192.168.0.20 in 0:00:00.6769408 wit
h Status Code 200
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]: [20:23:41] [INF] [26] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile=LG Smart TV, Path=/home/yunohost.multimedia/share/Picture/xxxxxxxx/VID_20180610_095646.mp4, AudioStreamIndex=null
, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/0082370c-31f2-079d-4fd5-73b16a1dbbe8/stream.mp4?MediaSourceId=0082370c31f2079d4fd573b16a1dbbe8&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=26c2370fc594d8
05d97ad26e58957ff5
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]: [20:23:41] [ERR] [26] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]: System.NullReferenceException: Object reference not set to an instance of an object.
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.ContentDirectory.ControlHandler.HandleSearch(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.ContentDirectory.ControlHandler.WriteResult(String methodName, IReadOnlyDictionary`2 methodParams, XmlWriter xmlWriter)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
Mar 01 20:23:41 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)

Mar 01 21:31:34 xxxxxxxxxx.fr jellyfin[579722]: [21:31:34] [WRN] [100] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.0.3:8096/jellyfin/dlna/ba355823-8553-4bee-a8a9-b35c4e7ffc86/contentdirectory/control to 192.168.0.20 in 0:00:00.6672427 wi
th Status Code 200
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]: [21:31:35] [INF] [51] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile=LG Smart TV, Path=/home/yunohost.multimedia/share/Picture/xxxxxxxxx/VID_20180610_095646.mp4, AudioStreamIndex=null
, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/0082370c-31f2-079d-4fd5-73b16a1dbbe8/stream.mp4?MediaSourceId=0082370c31f2079d4fd573b16a1dbbe8&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=26c2370fc594d8
05d97ad26e58957ff5
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]: [21:31:35] [ERR] [51] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]: System.NullReferenceException: Object reference not set to an instance of an object.
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.ContentDirectory.ControlHandler.HandleSearch(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
Mar 01 21:31:35 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)

Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]: [21:44:34] [INF] [72] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile=LG Smart TV, Path=/home/yunohost.multimedia/share/Picture/xxxxxxxxxx/VID_20180610_095646.mp4, AudioStreamIndex=null
, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/0082370c-31f2-079d-4fd5-73b16a1dbbe8/stream.mp4?MediaSourceId=0082370c31f2079d4fd573b16a1dbbe8&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=26c2370fc594d8
05d97ad26e58957ff5
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]: [21:44:34] [ERR] [72] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]: System.NullReferenceException: Object reference not set to an instance of an object.
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.ContentDirectory.ControlHandler.HandleSearch(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
Mar 01 21:44:34 xxxxxxxxxx.fr jellyfin[579722]:    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```

### FFmpeg logs

```shell
none
```

### Please attach any browser or client logs here

none

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/50152843/223235257-a6c1f7f6-1016-48be-9578-716355067db2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dpsoccerdude101** [comment]
I have this issue, too, on my m2 mac mini. This issue leads me to `force quitting` the process in activity monitor and rebooting Jellyfin once a day.

**Comment by ilteoood** [comment]
Same issue here, on a Raspberry PI 4
