### ISSUE TITLE
Jellyfin doesn't honour ffmpeg custom directory

### ISSUE THREAD

**Issue by Anessen97** [jellyfin/jellyfin#9495]
### Please describe your bug

I tried configuring the --ffmpeg option with a custom value, because ffmpeg isn't installed in /usr/share/ffmpeg on my system.
However, it doesn't matter which custom directory I point Jellyfin to, it always defaults to /usr/share/ffmpeg.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Gentoo ARM64
- Virtualization: Bare metal
- Clients: Browser, Android
- Browser: Firefox 111
- FFmpeg Version: 4.4.3
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: apache
- Base URL: none
- Networking: don't know
- Storage: local
```

### Jellyfin logs

```shell
[2023-03-14 12:23:25.278 +01:00] [INF] [1] Main: Jellyfin version: "10.8.9"
[2023-03-14 12:23:25.402 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /opt/jellyfin/log]"]
[2023-03-14 12:23:25.415 +01:00] [INF] [1] Main: Arguments: ["/opt/jellyfin/jellyfin_10.8.9/jellyfin.dll", "-d", "/opt/jellyfin/data", "-C", "/opt/jellyfin/cache", "-c", "/opt/jellyfin/config", "-l", "/opt/jellyfin/log", "--ffmpeg", "/usr/share/ffmpeg/ffmpeg"]
[2023-03-14 12:23:25.419 +01:00] [INF] [1] Main: Operating system: "Linux"
[2023-03-14 12:23:25.420 +01:00] [INF] [1] Main: Architecture: Arm64
[2023-03-14 12:23:25.423 +01:00] [INF] [1] Main: 64-Bit Process: True
[2023-03-14 12:23:25.423 +01:00] [INF] [1] Main: User Interactive: True
[2023-03-14 12:23:25.423 +01:00] [INF] [1] Main: Processor count: 4
[2023-03-14 12:23:25.423 +01:00] [INF] [1] Main: Program data path: "/opt/jellyfin/data"
[2023-03-14 12:23:25.424 +01:00] [INF] [1] Main: Web resources path: "/opt/jellyfin/jellyfin_10.8.9/jellyfin-web"
[2023-03-14 12:23:25.424 +01:00] [INF] [1] Main: Application directory: "/opt/jellyfin/jellyfin_10.8.9/"
[2023-03-14 12:23:26.003 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/opt/jellyfin/cache"
[2023-03-14 12:23:26.068 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-03-14 12:23:26.513 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-03-14 12:23:26.513 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-03-14 12:23:26.516 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-03-14 12:23:26.521 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-03-14 12:23:26.521 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-03-14 12:23:34.324 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.9.0"
[2023-03-14 12:23:34.327 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.9.0"
[2023-03-14 12:23:34.329 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.9.0"
[2023-03-14 12:23:34.331 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.9.0"
[2023-03-14 12:23:34.333 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.9.0"
[2023-03-14 12:23:34.594 +01:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2023-03-14 12:23:36.113 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-03-14 12:23:36.321 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2023-03-15 02:00:00.000 +01:00, which is 13:36:23.6790100 from now.
[2023-03-14 12:23:36.535 +01:00] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/share/ffmpeg/ffmpeg' with working directory '/'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[2023-03-14 12:23:36.549 +01:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: "/usr/share/ffmpeg/ffmpeg"
[2023-03-14 12:23:36.593 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: ""
[2023-03-14 12:23:36.596 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "0f9a0f1f7bea4dbfa8aeb60a24b4c17c"
[2023-03-14 12:23:37.009 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.3733924
[2023-03-14 12:23:37.010 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2023-03-14 12:23:37.757 +01:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/mnt/Data/Jellyfin/Shows"
[2023-03-14 12:23:37.780 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.7699275
[2023-03-14 12:23:37.780 +01:00] [INF] [1] Main: Startup complete 0:00:13.109419
[2023-03-14 12:23:39.343 +01:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2023-03-14 12:23:39.347 +01:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2023-03-14 12:23:39.360 +01:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2023-03-14 12:23:40.513 +01:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2023-03-14 12:23:40.549 +01:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-03-14 12:24:01.163 +01:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2023-03-14 12:24:01.166 +01:00] [INF] [2] Main: Running query planner optimizations in the database... This might take a while
[2023-03-14 12:24:01.440 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-03-14 12:24:01.443 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UdpServerEntryPoint"
[2023-03-14 12:24:01.445 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "ExternalPortForwarding"
[2023-03-14 12:24:01.448 +01:00] [INF] [2] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[2023-03-14 12:24:01.460 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2023-03-14 12:24:01.462 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2023-03-14 12:24:01.462 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "NotificationEntryPoint"
[2023-03-14 12:24:01.467 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2023-03-14 12:24:01.468 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DeviceAccessEntryPoint"
[2023-03-14 12:24:01.468 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2023-03-14 12:24:01.470 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DlnaEntryPoint"
[2023-03-14 12:24:01.472 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing PlayToManager
[2023-03-14 12:24:01.475 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
[2023-03-14 12:24:01.478 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
[2023-03-14 12:24:01.480 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing _BroadcastListenSocket
[2023-03-14 12:24:01.485 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" Disposing 3 sendSockets
[2023-03-14 12:24:01.486 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "0.0.0.0"
[2023-03-14 12:24:01.486 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "10.0.0.254"
[2023-03-14 12:24:01.486 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "127.0.0.1"
[2023-03-14 12:24:01.487 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UserDataChangeNotifier"
[2023-03-14 12:24:01.488 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "RecordingNotifier"
[2023-03-14 12:24:01.495 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2023-03-14 12:24:01.499 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryMonitorStartup"
[2023-03-14 12:24:01.500 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryChangedNotifier"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by AmbulantRex** [comment]
As @nyanmisaka pointed out, it seems like your `ffmpeg` binaries aren't in the /usr/share path you think. Are you using the `arm64` container image for jellyfin or manual install? 

If this is a manual install, and you know `ffmpeg` is installed, you can try the following command to identify the install path. 
```bash
 whereis ffmpeg
```

**Comment by Anessen97** [comment]
They are installed in /usr/bin.
The problem is that even though I configured Jellyfin to look for ffmpeg in another directory, it still looks inside /usr/share/ffmpeg.

**Comment by Anessen97** [comment]
Weirdly, modifying the relevant line in the xml file and updating the path does work and `/usr/bin` is used.
But, as soon as I go back to `/usr/share/ffmpeg`, the original behaviour presents itself again

**Comment by AmbulantRex** [comment]
@Anessen97 is this issue resolved then?

**Comment by Anessen97** [comment]
Yes, I think it can be marked as solved
