### ISSUE TITLE
[Issue]:  System.InvalidOperationException: There is an error in XML document (1, 1).

### ISSUE THREAD

**Issue by dxomg** [jellyfin/jellyfin#9508]
### Please describe your bug

I Literally just extracted the tarball then executed the binary and I got the error on the title, I'm currently using a raspberry pi

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye) aarch64
- Virtualization: Bare Metal
- Clients: Dosen't apply
- Browser: Dosen't apply
- FFmpeg Dosen't apply
- Playback Method: Dosen't apply
- Hardware Acceleration: Dosen't apply
- Plugins: Dosen't apply
- Reverse Proxy: Dosen't apply
- Base URL: Dosen't apply
- Networking: Dosen't apply
- Storage: NEW 64 Gb SD CARD
```

### Jellyfin logs

```shell
[23:29:33] [INF] [1] Main: Jellyfin version: 10.8.9
[23:29:34] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /root/.local/share/jellyfin/log]"]
[23:29:34] [INF] [1] Main: Arguments: ["/root/jellyfin_10.8.9/jellyfin.dll"]
[23:29:34] [INF] [1] Main: Operating system: Linux
[23:29:34] [INF] [1] Main: Architecture: Arm64
[23:29:34] [INF] [1] Main: 64-Bit Process: True
[23:29:34] [INF] [1] Main: User Interactive: True
[23:29:34] [INF] [1] Main: Processor count: 4
[23:29:34] [INF] [1] Main: Program data path: /root/.local/share/jellyfin
[23:29:34] [INF] [1] Main: Web resources path: /root/jellyfin_10.8.9/jellyfin-web
[23:29:34] [INF] [1] Main: Application directory: /root/jellyfin_10.8.9/
[23:29:34] [FTL] [1] Main: Unhandled Exception
System.InvalidOperationException: There is an error in XML document (1, 1).
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderServerConfiguration.Read10_ServerConfiguration()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.InvalidOperationException: There is an error in XML document (1, 1).
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderServerConfiguration.Read10_ServerConfiguration()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Aborted
```

### FFmpeg logs

```shell
Dosen't Apply
```

### Please attach any browser or client logs here

Dosen't Apply

### Please attach any screenshots here

https://user-images.githubusercontent.com/101947415/225777240-06557194-700c-44af-a292-0aa4b07e7956.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dxomg** [comment]
No response :(?

**Comment by AmbulantRex** [comment]
@dxomg, which tarball did you extract exactly? Many of the install guides involve importing the signing key, then adding the jellyfin source, and finally installing it using `apt`. It might be better to go through the install process outlined in the [installation guide](https://jellyfin.org/downloads/server/) for debian. 

Your specific issue with the xml file could be related to a byte-order mark (BOM) at the start of the file. If the BOM is wrong for the arm64 version of debian you're running, then I suppose it could fail. It's hard to say without knowing which file you downloaded. In any case, I'd encourage starting fresh and going through the install guide to make sure you'd got the right stuff.
