### ISSUE TITLE
DLNA Play On remote is broken for Bose Soundtouch 309

### ISSUE THREAD

**Issue by espector** [jellyfin/jellyfin#9521]
I'm able to play to my Bose Soundtouch 300 sound bar. However, the remote screen is blank and doesn't show the play status. There's no way to control once the music stats casting. I can't pause, go to the next track, etc. 

I can control the volume on Soundtouch though. 

Setup: linuxserver jellyfin docker image, running on Synology. 

Screenshots below. 
![7939729A-577E-49AA-B028-34FEFC70439C](https://user-images.githubusercontent.com/3356907/226623820-0a8f2104-45a0-4d07-9c6c-95d7c012549c.jpeg)
![9830D10A-C002-4169-B7C7-5D930B584F15](https://user-images.githubusercontent.com/3356907/226623823-f45795f7-b3de-43e8-8d6b-475094389d26.png)

**Comment by seaeagle1** [comment]
I'm having a similar issue with my Yamaha amplifier: PlayTo, song starts fine, but can't access the remote control function. Jellyfin gives the following error in the log:
```
[2023-05-12 12:19:16.075 +00:00] [ERR] [51] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for "R-N303D 42CCC0"
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 1, position 2605.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(Boolean isInAttributeValue, EntityExpandType expandType)
   at System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity(Int32 outOrChars, Char[] chars, Int32 pos, Int32 rcount, Int32 rpos, Int32 orChars, Char c)
   at System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc(Task'1 task)
   at System.Xml.XmlTextReaderImpl.FinishPartialValueAsync()
   at System.Xml.XmlTextReaderImpl._GetValueAsync()
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFromAsync(XmlReader r, CancellationToken cancellationToken)
   at System.Xml.Linq.XContainer.ReadContentFromAsync(XmlReader r, LoadOptions o, CancellationToken cancellationToken)
   at System.Xml.Linq.XDocument.LoadAsyncInternal(XmlReader reader, LoadOptions options, CancellationToken cancellationToken)
   at System.Xml.Linq.XDocument.LoadAsync(Stream stream, LoadOptions options, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

I did some package capture and it probably is the case that Jellyfin's XML handling doesn't like the fact that the amplifier doesn't properly escape the URL in the TrackURI tag:

```
POST /AVTransport/ctrl HTTP/1.1
Host: 192.168.100.27:49154
User-Agent: Microsoft-Windows/6.2 UPnP/1.0 Microsoft-DLNA DLNADOC/1.50
SOAPACTION: "urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo"
Pragma: no-cache
FriendlyName.DLNA.ORG: Jellyfin
Accept: application/json; q=1.0, application/xml; q=0.9, */*; q=0.8
Accept-Encoding: gzip, deflate, br
Content-Type: text/xml; charset=utf-8
Content-Length: 413
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><m:GetPositionInfo xmlns:m="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="ui4">0</InstanceID></m:GetPositionInfo></SOAP-ENV:Body></SOAP-ENV:Envelope>

HTTP/1.1 200 OK
Server: Network_Module/1.0 (R-N303D)
Content-Type: text/xml; charset="utf-8"
EXT:
Content-Length: 2911
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetPositionInfoResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><Track>1</Track><TrackDuration>0:02:10</TrackDuration><TrackMetaData>&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dlna=&quot;urn:schemas-dlna-org:metadata-1-0/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item restricted=&quot;1&quot; id=&quot;d0fee4e6db299f01c98f236c20228930&quot; parentID=&quot;8de33240f27833adee941540c7d4731a&quot;&gt;&lt;dc:title&gt;Cornfield Chase (From &apos;Interstellar&apos;) - Midnight Sessions at the Royal Albert Hall&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;upnp:genre&gt;Classical Crossover&lt;/upnp:genre&gt;&lt;upnp:publisher&gt;Sony&lt;/upnp:publisher&gt;&lt;upnp:composer&gt;Hans Zimmer&lt;/upnp:composer&gt;&lt;upnp:artist&gt;anna lapwood&lt;/upnp:artist&gt;&lt;dc:creator&gt;anna lapwood&lt;/dc:creator&gt;&lt;upnp:artist role=&quot;AlbumArtist&quot;&gt;Anna Lapwood&lt;/upnp:artist&gt;&lt;upnp:album&gt;Midnight Sessions at the Royal Albert Hall&lt;/upnp:album&gt;&lt;upnp:originalTrackNumber&gt;1&lt;/upnp:originalTrackNumber&gt;&lt;res duration=&quot;00:02:10.7024000&quot; size=&quot;9280875&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;568061&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;https://192.168.0.5:8920/audio/d0fee4e6-db29-9f01-c98f-236c20228930/stream.flac?DeviceProfileId=9f649eb005ee72f27ff01580901f2c2b&amp;amp;DeviceId=9ab0c000-f668-11de-9976-ac44f242ccc0&amp;amp;MediaSourceId=d0fee4e6db299f01c98f236c20228930&amp;amp;Static=true&amp;amp;Tag=704f90733a29eed52394c40b95246493&amp;amp;dlnaheaders=true&lt;/res&gt;&lt;upnp:albumArtURI dlna:profileID=&quot;JPEG_SM&quot;&gt;https://192.168.0.5:8920/Items/d0fee4e6db299f01c98f236c20228930/Images/Primary/0/d5b8e78250233b1933bdfefa06ae3347/jpg/480/480/0/0&lt;/upnp:albumArtURI&gt;&lt;upnp:icon&gt;https://192.168.0.5:8920/Items/d0fee4e6db299f01c98f236c20228930/Images/Primary/0/d5b8e78250233b1933bdfefa06ae3347/jpg/48/48/0/0&lt;/upnp:icon&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</TrackMetaData><TrackURI>http://192.168.0.5:8920/audio/d0fee4e6-db29-9f01-c98f-236c20228930/stream.flac?DeviceProfileId=9f649eb005ee72f27ff01580901f2c2b&DeviceId=9ab0c000-f668-11de-9976-ac44f242ccc0&MediaSourceId=d0fee4e6db299f01c98f236c20228930&Static=true&Tag=704f90733a29eed52394c40b95246493&dlnaheaders=true</TrackURI><RelTime>0:00:00</RelTime><AbsTime>0:00:00</AbsTime><RelCount>0</RelCount><AbsCount>0</AbsCount></u:GetPositionInfoResponse></s:Body></s:Envelope>
```

**Comment by espector** [comment]
> If anyone's looking for it, I've indeed been able to fix the issue for me by catching the XmlException and then correcting the received Xml response on the fly: [171d7b3](https://github.com/jellyfin/jellyfin/commit/171d7b3b46a7c14d1be6729a3a56bec8e8dff672)

@seaeagle1 I would love to try this out. How can I patch this into the Linuxserver Jellyfin version?

**Comment by seaeagle1** [comment]
A fix is now being included in the latest development version. 

If you want to try it on the current 10.8.10, and don't know how to build jellyfin yourself, attached is an updated Emby.Dlna.dll. In theory you should be able to temporarily replace that (it's probably located in /usr/lib/jellyfin/bin). But I don't make promises there, make backups etc. before you change anything.

[Emby.Dlna.zip](https://github.com/jellyfin/jellyfin/files/11536739/Emby.Dlna.zip)

**Comment by espector** [comment]
hi @seaeagle1 I tried your fix and unfortunately it didn't work for my Bose Soundtouch 300.

**Comment by espector** [comment]
also, confirming that the issue still exists in the latest release 10.8.11
