### ISSUE TITLE
Windows Core: Can not assign ffmpeg path

### ISSUE THREAD

**Issue by Arthurdw** [jellyfin/jellyfin#9524]
**Issue:**

When trying to set a ffmpeg path in the jellyfin client on a windows core server, it says that this could not be found. Even though this exists. 

![image](https://user-images.githubusercontent.com/38541241/226653670-911f2ecd-855f-4116-bb45-686ea69228a4.png)

**Fixes I tried:**
My first thought was that it was having issues with the spaces in the program files path. But even when moving it to a ProgramData folder (like how the other paths are set), it still raises the same error.

I also checked if the service had enough permissions, and it does.

**Media Info of the file**
All files

**Logs**
```
[2023-03-21 08:16:14.345 -07:00] [INF] [60] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "C:\ProgramData\Jellyfin\Server\ffmpeg". pathType: "Custom"
[2023-03-21 08:16:14.394 -07:00] [ERR] [60] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
[2023-03-21 08:16:14.402 -07:00] [ERR] [60] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/System/MediaEncoder/Path".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.UpdateEncoderPath(String path, String pathType)
   at Jellyfin.Api.Controllers.ConfigurationController.UpdateMediaEncoderPath(MediaEncoderPathDto mediaEncoderPath)
   at lambda_method897(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   ```

**FFmpeg Logs**
Not available because of issue

**Server System (please complete the following information):**
 - OS Name: Microsoft Windows Server 2022 Datacenter
 - OS Version: 10.0.20348 N/A Build 20348
 - System Type: x64-based PC
 - Jellyfin Version: 10.8.9
 - Hardware settings & device: na
 - Reverse proxy: na
 - Other hardware notes: ran within VM
 
**Client System (please complete the following information):**
Has no impact

**Comment by Arthurdw** [comment]
When manually providing the ffmpeg path, it fails the version check. And says the process returns no result. (see logs)  
  
\`\`\`  
PS C:\\Users\\Administrator> & 'C:\\Program Files\\Jellyfin\\Server\\Jellyfin.exe' --ffmpeg 'C:\\Program Files\\Jellyfin\\Server\\ffmpeg.exe'  
\[09:07:26\] \[INF\] \[1\] Main: Jellyfin version: 10.8.9  
\[09:07:26\] \[INF\] \[1\] Main: Environment Variables: \["\[JELLYFIN\_LOG\_DIR, C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\jellyfin\\\\log\]"\]  
\[09:07:26\] \[INF\] \[1\] Main: Arguments: \["C:\\\\Program Files\\\\Jellyfin\\\\Server\\\\jellyfin.dll", "--ffmpeg", "C:\\\\Program Files\\\\Jellyfin\\\\Server\\\\ffmpeg.exe"\]  
\[09:07:26\] \[INF\] \[1\] Main: Operating system: Windows  
\[09:07:26\] \[INF\] \[1\] Main: Architecture: X64  
\[09:07:26\] \[INF\] \[1\] Main: 64-Bit Process: True  
\[09:07:26\] \[INF\] \[1\] Main: User Interactive: True  
\[09:07:26\] \[INF\] \[1\] Main: Processor count: 4  
\[09:07:26\] \[INF\] \[1\] Main: Program data path: C:\\Users\\Administrator\\AppData\\Local\\jellyfin  
\[09:07:26\] \[INF\] \[1\] Main: Web resources path: C:\\Program Files\\Jellyfin\\Server\\jellyfin-web  
\[09:07:26\] \[INF\] \[1\] Main: Application directory: C:\\Program Files\\Jellyfin\\Server\\  
\[09:07:26\] \[INF\] \[1\] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: C:\\Users\\Administrator\\AppData\\Local\\jellyfin\\cache  
\[09:07:26\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: Loading assemblies  
\[09:07:26\] \[INF\] \[1\] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : \[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16\]  
\[09:07:26\] \[INF\] \[1\] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : \[\]  
\[09:07:26\] \[INF\] \[1\] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: \[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16\]  
\[09:07:26\] \[INF\] \[1\] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: \[\]  
\[09:07:26\] \[INF\] \[1\] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: \[\]  
\[09:07:28\] \[INF\] \[1\] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.9.0  
\[09:07:28\] \[INF\] \[1\] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.9.0  
\[09:07:28\] \[INF\] \[1\] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.9.0  
\[09:07:28\] \[INF\] \[1\] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.9.0  
\[09:07:28\] \[INF\] \[1\] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.9.0  
\[09:07:29\] \[INF\] \[1\] Main: Kestrel listening on Any IP4 Address  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: Running startup tasks  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2023-03-22 02:00:00.000 -07:00, which is 16:52:30.5365968 from now.  
\[09:07:29\] \[ERR\] \[1\] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result  
\[09:07:29\] \[WRN\] \[1\] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: C:\\Program Files\\Jellyfin\\Server\\ffmpeg.exe  
\[09:07:29\] \[INF\] \[1\] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg:  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: ServerId: f33fc47861824b93ad6e0ffe151068f5  
\[09:07:29\] \[INF\] \[10\] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1077952  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: Core startup complete  
\[09:07:29\] \[INF\] \[1\] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1711262  
\[09:07:29\] \[INF\] \[10\] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.  
\[09:07:29\] \[INF\] \[1\] Main: Startup complete 0:00:03.8199057  
\[09:07:29\] \[INF\] \[10\] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.  
\[09:07:32\] \[INF\] \[10\] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins  
\[09:07:32\] \[INF\] \[10\] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask  
\[09:07:32\] \[INF\] \[16\] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins  
\[09:07:33\] \[INF\] \[17\] Main: Ctrl+C, shutting down  
\[09:07:33\] \[INF\] \[17\] Main: Running query planner optimizations in the database... This might take a while  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing RecordingNotifier  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing LibraryChangedNotifier  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing ExternalPortForwarding  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing DlnaEntryPoint  
\[09:07:33\] \[INF\] \[17\] Emby.Dlna.Main.DlnaEntryPoint: Disposing PlayToManager  
\[09:07:33\] \[INF\] \[17\] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery  
\[09:07:33\] \[INF\] \[17\] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing DeviceAccessEntryPoint  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing SchedulesDirect  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing NotificationEntryPoint  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing UserDataChangeNotifier  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing LibraryMonitorStartup  
\[09:07:33\] \[INF\] \[17\] Emby.Server.Implementations.ApplicationHost: Disposing UdpServerEntryPoint  
\`\`\`

**Comment by nyanmisaka** [comment]
So what's the FFmpeg version?

**Comment by Arthurdw** [comment]
> So what's the FFmpeg version?

It is the one which was provided by the Jellyfin windows installer. It does not provide output to the version command, or to any command call as a matter of fact.  
 

![](https://user-images.githubusercontent.com/38541241/226673406-39118fef-e65b-471a-9f66-6dddf8b476f1.png)

**Comment by nyanmisaka** [comment]
Windows Core is so stripped down that it lacks the most basic runtime library to support ffmpeg.

Search in Google with `windows core "ffmpeg"`;

https://superuser.com/questions/1742768/ffmpeg-on-windows-server-core-2022

We do not recommend using such a system as a server, because it sacrifices the most fundamental feature of Windows - compatibility.

**Comment by Arthurdw** [comment]
Aight, after adding those files, everything was resolved. Thanks for the amazing support. ♥
