### ISSUE TITLE
Android TV not playing anything

### ISSUE THREAD

**Issue by Jarr-ett** [jellyfin/jellyfin#954]
Whenever I try to play any media on an Nvidia Shield it says "Failed to load content"

Server errors when trying to play:
```
Feb 19 14:21:04 jelly jellyfin[17612]: [14:21:04] [ERR] AcceptWebSocketAsync error
    Feb 19 14:21:04 jelly jellyfin[17612]: SocketHttpListener.WebSocketException: net_WebSockets_AcceptUnsupportedWebSocketVersion
    Feb 19 14:21:04 jelly jellyfin[17612]:    at SocketHttpListener.Net.WebSockets.HttpWebSocket.ValidateWebSocketHeaders(HttpListenerContext context) in /jellyfin/SocketHttpListener/Net/WebSockets/HttpWebSocket.cs:line 155
    Feb 19 14:21:04 jelly jellyfin[17612]:    at SocketHttpListener.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore(HttpListenerContext context, String subProtocol, Int32 receiveBufferSize, TimeSpan keepAliveInterval, Nullable`1 internalBuffer) in /jellyfin/SocketHttpListener/Net/WebSockets/HttpWebSocket.Managed.cs:line 23
    Feb 19 14:21:04 jelly jellyfin[17612]:    at Jellyfin.Server.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpListenerContext ctx) in /jellyfin/Jellyfin.Server/SocketSharp/WebSocketSharpListener.cs:line 151
```
```
    Feb 19 14:21:24 jelly jellyfin[17612]: [14:21:24] [ERR] Error processing request
    Feb 19 14:21:24 jelly jellyfin[17612]: MediaBrowser.Common.Extensions.ResourceNotFoundException: Nickelodeon does not have an image of type Primary
    Feb 19 14:21:24 jelly jellyfin[17612]:    at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest) in /jellyfin/MediaBrowser.Api/Images/ImageService.cs:line 572
    Feb 19 14:21:24 jelly jellyfin[17612]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName) in /jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 88
    Feb 19 14:21:24 jelly jellyfin[17612]:    at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req) in /jellyfin/Emby.Server.Implementations/Services/ServiceController.cs:line 177
    Feb 19 14:21:24 jelly jellyfin[17612]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
    Feb 19 14:21:24 jelly jellyfin[17612]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
```
```
    Feb 19 14:21:27 jelly jellyfin[17612]: [14:21:27] [ERR] Error this.ProcessRequest(context)(Exception while writing error to the response)
    Feb 19 14:21:27 jelly jellyfin[17612]: System.InvalidOperationException: Operation is not valid due to the current state of the object.
    Feb 19 14:21:27 jelly jellyfin[17612]:    at SocketHttpListener.Net.HttpListenerResponse.set_ContentLength64(Int64 value) in /jellyfin/SocketHttpListener/Net/HttpListenerResponse.cs:line 89
    Feb 19 14:21:27 jelly jellyfin[17612]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.Write(IResponse response, String text) in /jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 688
    Feb 19 14:21:27 jelly jellyfin[17612]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.ErrorHandler(Exception ex, IRequest httpReq, Boolean logExceptionStackTrace, Boolean logExceptionMessage) in /jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 229`
```

Server info
 - OS: Debian 9
 - Jellyfin Version: 10.2.0 from PPA

Client info
- Nvidia Shield 
- jellyfin-androidtv_google-release_beta3.apk

**Comment by JustAMan** [comment]
Can you play same media from Web UI? Did you make your data afresh or migrated from Emby?

**Comment by sparky8251** [comment]
Potentially related to?

https://www.reddit.com/r/jellyfin/comments/asmkfj/dlna_not_working/

**Comment by Jarr-ett** [comment]
> Potentially related to?
> 
> https://www.reddit.com/r/jellyfin/comments/asmkfj/dlna_not_working/

DLNA works fine, I use it to get around this issue.



> Can you play same media from Web UI? Did you make your data afresh or migrated from Emby?

Works fine from the web UI as well Android phone and Android app (not AdroidTV app) on Sheild.
This is on a fresh install.

**Comment by flex36ty** [comment]
> Can you play same media from Web UI? Did you make your data afresh or migrated from Emby?

Web UI and regular Android mobile app works fine
Its just with the Android TV playing from a Linux server

Android TV plays fine when playing from a WIndows server

**Comment by cvium** [comment]
https://emby.media/community/index.php?/topic/63905-emby-353-web-socket-error/

**Comment by ddurdle** [comment]
I concur, I tried Android TV app 2 weeks ago and nothing would play -- movies, tv shows or Live TV.  Worked from Android mobile version of the app and from Chrome website.  Running the server on Debian.

**Comment by ddurdle** [comment]
I don't think the error here (AcceptWebSocketAsync) is really related to the Emby 3.5.x not handling exceptions in WebSockets (which is a different error)

**Comment by cvium** [comment]
`net_WebSockets_AcceptUnsupportedWebSocketVersion` is an inherited bug

**Comment by thornbill** [comment]
I've been able to reproduce some playback issues with different media types in the Android TV app. It does not seem to be caused by any changes server-side, so this should probably be moved to https://github.com/jellyfin/jellyfin-androidtv.

If you can provide any additional information about the types of media that you are trying to play, that could help narrow this down.
