### ISSUE TITLE
[Issue]: FixPlaylistOwner db migration fails

### ISSUE THREAD

**Issue by Madokamiiiiii** [jellyfin/jellyfin#9569]
### Please describe your bug

After upgrading to the latest version with `docker pull` the migration step `FixPlaylistOwner` fails and the application doesn't start.
The last time I upgraded was on March 28th. Unfortunately I can't determine the exact version but it should be related to this commit **9c500bd**.

### Jellyfin Version

Other

### if other:

eb59456

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Plugins: none
- Storage: local
```

### Jellyfin logs

```shell
[2023-03-31 10:22:54.471 +02:00] [INF] [1] Main: Jellyfin version: "10.9.0"
[2023-03-31 10:22:54.488 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_DATA_DIR, /config]"]
[2023-03-31 10:22:54.490 +02:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2023-03-31 10:22:54.490 +02:00] [INF] [1] Main: Operating system: "Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)"
[2023-03-31 10:22:54.490 +02:00] [INF] [1] Main: Architecture: X64
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: 64-Bit Process: True
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: User Interactive: True
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: Processor count: 4
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: Program data path: "/config"
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2023-03-31 10:22:54.493 +02:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2023-03-31 10:22:54.601 +02:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2023-03-31 10:22:54.626 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-03-31 10:22:54.739 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: "[192.168.178.0/24]"
[2023-03-31 10:22:54.739 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: "[]"
[2023-03-31 10:22:54.739 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[192.168.178.0/24]"
[2023-03-31 10:22:54.744 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-03-31 10:22:54.744 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-03-31 10:22:57.522 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.0.0"
[2023-03-31 10:22:57.523 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.0.0"
[2023-03-31 10:22:57.524 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.0.0"
[2023-03-31 10:22:57.537 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.0.0"
[2023-03-31 10:22:57.538 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.0.0"
[2023-03-31 10:22:57.576 +02:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"FixPlaylistOwner"'
[2023-03-31 10:22:57.743 +02:00] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration '"FixPlaylistOwner"'
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-03-31 10:22:57.747 +02:00] [FTL] [1] Main: Error while starting server
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-03-31 10:22:57.747 +02:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2023-03-31 10:22:57.759 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-03-31 10:22:57.760 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "SchedulesDirect"
[2023-03-31 10:22:57.760 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzArtistProvider"
[2023-03-31 10:22:57.761 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "MusicBrainzAlbumProvider"
[2023-03-31 10:22:57.761 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2023-03-31 10:22:57.783 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
I overlooked a case when designing the migration. I'm currently writing  a fix for it but didn't have the time to finish it.
I'll reference this issue in the PR once it's up (might take some time though).

**Comment by nreal2** [comment]
I have this same issue..
Can anyone point me a way to go back to that version previously was installed using apt in Debian?


[2023-03-31 20:40:34.203 +03:00] [ERR] Could not apply migration '"FixPlaylistOwner"'
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[2023-03-31 20:40:34.203 +03:00] [FTL] Error while starting server
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-03-31 20:40:34.204 +03:00] [INF] Running query planner optimizations in the database... This might take a while
[2023-03-31 20:40:34.220 +03:00] [INF] Disposing "CoreAppHost"
[2023-03-31 20:40:34.221 +03:00] [INF] Disposing "MusicBrainzArtistProvider"
[2023-03-31 20:40:34.221 +03:00] [INF] Disposing "EmbyTV"
[2023-03-31 20:40:34.222 +03:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2023-03-31 20:40:34.223 +03:00] [INF] Disposing "SchedulesDirect"
[2023-03-31 20:40:34.223 +03:00] [INF] Disposing "CoverArtArchiveImageProvider"
[2023-03-31 20:40:34.263 +03:00] [INF] Received a SIGTERM signal, shutting down

**Comment by nreal2** [comment]
Still broken and not able to start. Any info when this is going to be fixed or rolled back?

[2023-04-07 07:57:12.194 +03:00] [ERR] Could not apply migration '"FixPlaylistOwner"'
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[2023-04-07 07:57:12.195 +03:00] [FTL] Error while starting server
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-04-07 07:57:12.196 +03:00] [INF] Running query planner optimizations in the database... This might take a while
[2023-04-07 07:57:12.211 +03:00] [INF] Disposing "CoreAppHost"
[2023-04-07 07:57:12.212 +03:00] [INF] Disposing "MusicBrainzArtistProvider"
[2023-04-07 07:57:12.213 +03:00] [INF] Disposing "EmbyTV"
[2023-04-07 07:57:12.214 +03:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2023-04-07 07:57:12.214 +03:00] [INF] Disposing "SchedulesDirect"
[2023-04-07 07:57:12.214 +03:00] [INF] Disposing "CoverArtArchiveImageProvider"
[2023-04-07 07:57:12.258 +03:00] [INF] Received a SIGTERM signal, shutting down

**Comment by crobibero** [comment]
Unstable is exactly that- unstable.

**Comment by nreal2** [comment]
Yes unstable, but if it is totally broken there might be an idea to go back if it cannot be fixed.

**Comment by aanno** [comment]
Same problem here.

**Comment by Cic0r** [comment]
Same problem for me and still not working. :(

**Comment by nreal2** [comment]
[2023-04-13 14:08:04.653 +03:00] [INF] Applying migration '"FixPlaylistOwner"'
[2023-04-13 14:08:04.813 +03:00] [ERR] Could not apply migration '"FixPlaylistOwner"'
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-04-13 14:08:04.814 +03:00] [FTL] Error while starting server
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Server.Migrations.Routines.FixPlaylistOwner.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2023-04-13 14:08:04.815 +03:00] [INF] Running query planner optimizations in the database... This might take a while
[2023-04-13 14:08:04.831 +03:00] [INF] Disposing "CoreAppHost"
[2023-04-13 14:08:04.832 +03:00] [INF] Disposing "MusicBrainzArtistProvider"
[2023-04-13 14:08:04.832 +03:00] [INF] Disposing "EmbyTV"
[2023-04-13 14:08:04.833 +03:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2023-04-13 14:08:04.834 +03:00] [INF] Disposing "SchedulesDirect"
[2023-04-13 14:08:04.834 +03:00] [INF] Disposing "CoverArtArchiveImageProvider"
[2023-04-13 14:08:04.881 +03:00] [INF] Received a SIGTERM signal, shutting down

**Comment by nielsvanvelzen** [comment]
As stated before, this issue is known and will be fixed before the 10.9 release candidates come out. There is no need to tell us if you're affected by it.

**Comment by AnonymousWebHacker** [comment]
> Mismo problema para mí y todavía no funciona. :(

`del /var/lib/jellyfin/data/*.db` and, restart server

**Comment by Cebrain** [comment]
If someone is interested, i tried some older Unstable Versions and this one is working for me
20230316.13-unstable

**Comment by stom66** [comment]
Having this issue when upgrading to 10.9.6 on Rocky 8.

Starting the service for the first time after updating fails, with the error:

```
Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'FixPlaylistOwner'
System.FormatException: Unrecognized Guid format.
```

**Comment by KodeToad** [comment]
This is still an issue in 10.10.
First encountered upgrading from 10.8 to 10.9 and followed advice (rm /var/lib/jellyfin/data/library.db) and got it working.
Then upgrading to 10.10 and the same issue.
Waiting for a library rebuild and repairing the watched media was tiresome and inacurate.
Is there another way?
How can I identify/remove the GUID it's referring to?
Logs:
`root@jellyfin ~# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  jellyfin-ffmpeg6
The following NEW packages will be installed:
  jellyfin-ffmpeg7
The following packages will be upgraded:
  jellyfin jellyfin-server jellyfin-web
3 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 122 MB of archives.
After this operation, 11.2 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://repo.jellyfin.org/debian bookworm/main amd64 jellyfin-server amd64 10.10.0+deb12 [46.8 MB]
Get:2 https://repo.jellyfin.org/debian bookworm/main amd64 jellyfin-web all 10.10.0+deb12 [32.7 MB]
Get:3 https://repo.jellyfin.org/debian bookworm/main amd64 jellyfin all 10.10.0+deb12 [2438 B]
Get:4 https://syd1.mirror.jellyfin.org/files/debian bookworm/main amd64 jellyfin-ffmpeg7 amd64 7.0.2-5-bookworm [43.0 MB]
Fetched 122 MB in 3s (37.3 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 47956 files and directories currently installed.)
Preparing to unpack .../jellyfin-server_10.10.0+deb12_amd64.deb ...
Stopping Jellyfin!
Unpacking jellyfin-server (10.10.0+deb12) over (10.9.11+deb12) ...
Preparing to unpack .../jellyfin-web_10.10.0+deb12_all.deb ...
Unpacking jellyfin-web (10.10.0+deb12) over (10.9.11+deb12) ...
Preparing to unpack .../jellyfin_10.10.0+deb12_all.deb ...
Unpacking jellyfin (10.10.0+deb12) over (10.9.11+deb12) ...
(Reading database ... 47869 files and directories currently installed.)
Removing jellyfin-ffmpeg6 (6.0.1-8-bookworm) ...
Selecting previously unselected package jellyfin-ffmpeg7.
(Reading database ... 47739 files and directories currently installed.)
Preparing to unpack .../jellyfin-ffmpeg7_7.0.2-5-bookworm_amd64.deb ...
Unpacking jellyfin-ffmpeg7 (7.0.2-5-bookworm) ...
Setting up jellyfin-ffmpeg7 (7.0.2-5-bookworm) ...
Setting up jellyfin-web (10.10.0+deb12) ...
Setting up jellyfin-server (10.10.0+deb12) ...
Setting up jellyfin (10.10.0+deb12) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
[master c22658a] committing changes in /etc made by "apt-get dist-upgrade"
 3 files changed, 11 insertions(+), 4 deletions(-)
Enumerating objects: 3141, done.
Counting objects: 100% (3141/3141), done.
Delta compression using up to 4 threads
Compressing objects: 100% (1447/1447), done.
Writing objects: 100% (3141/3141), done.
Total 3141 (delta 1023), reused 3132 (delta 1018), pack-reused 0
root@jellyfin ~# systemctl status jellyfin.service
* jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             `-jellyfin.service.conf
     Active: inactive (dead) since Mon 2024-10-28 04:59:11 AEST; 3min 22s ago
   Duration: 28.295s
    Process: 1784568 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITIONAL_OPTS (code=exited, status=0/SUCCESS)
   Main PID: 1784568 (code=exited, status=0/SUCCESS)
        CPU: 19.607s

Oct 28 04:59:10 jellyfin jellyfin[1784568]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
Oct 28 04:59:10 jellyfin jellyfin[1784568]:    at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
Oct 28 04:59:10 jellyfin jellyfin[1784568]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Oct 28 04:59:10 jellyfin jellyfin[1784568]: [04:59:10] [INF] Running query planner optimizations in the database... This might take a while
Oct 28 04:59:10 jellyfin jellyfin[1784568]: [04:59:10] [INF] Disposing CoreAppHost
Oct 28 04:59:10 jellyfin jellyfin[1784568]: [04:59:10] [INF] Disposing MusicBrainzArtistProvider
Oct 28 04:59:10 jellyfin jellyfin[1784568]: [04:59:10] [INF] Disposing MusicBrainzAlbumProvider
Oct 28 04:59:10 jellyfin jellyfin[1784568]: [04:59:10] [INF] Disposing PluginManager
Oct 28 04:59:11 jellyfin systemd[1]: jellyfin.service: Deactivated successfully.
Oct 28 04:59:11 jellyfin systemd[1]: jellyfin.service: Consumed 19.607s CPU time.
`

`root@jellyfin ~# journalctl -eu jellyfin`
[jellyfail-28-Oct-2024.log](https://github.com/user-attachments/files/17535174/jellyfail-28-Oct-2024.log)

**Comment by stom66** [comment]
@KodeToad I had an absolute mare of a time fixing this. The processs was (roughly, it's been a while): 

* download database and open in a local editor
* browse through the various tables looking for the playlists and their guids
* manually find which ones have guids that didn't look like the others
* try and fix them by replacing them with new guids
* that failed so I think I copied the relevant data from the other fields
* removed the offending entries
* re-created them via jellyfin
* re-edit the databse and manually paste in the data I needed
* realise only half of them have worked, and some of the deleted entries are still there but not accessible
* pray that someone else with more technical experience has this issue and writes a proper fix/repair tool for it

**Comment by KodeToad** [comment]
> * browse through the various tables looking for the playlists and their guids

Which tables are these bogus guids in @stom66 ?

**Comment by stom66** [comment]
Sorry i don't have that information noted down. I believe they were embedded in a JSON string, if memory serves. I just searched the db for "guid" and looked for entries which seemed related to the error I was having.
