### ISSUE TITLE
[Issue]: oh-my-God! Jellyfin removed a lot of movies from multiple libraries!

### ISSUE THREAD

**Issue by LittleNewton** [jellyfin/jellyfin#9604]
### Please describe your bug

Hi.

I have been using Jellyfin 10.8.9 docker container for a long time. This day, I rebooted my NAS with another server running jellyfin docker not been pre-closed. After rebooting and restarting Jellyfin, I found a lot of movies were unably to open! After checking the log, I found that Jellyfin has removed a lot of movies. Totally, Jellyfin has removed more than 4,000 videos from my database.

Logs are like the following:

```
jellyfin Emby.Server.Implementations.Library.LibraryManager: Removing item xxx
jellyfin Emby.Server.Implementations.Library.LibraryManager: Removing item xxx
jellyfin Emby.Server.Implementations.Library.LibraryManager: Removing item xxx
```

I don't know why. I checked the NAS file system and the NFS sharing, and all performed well.

Please tell me the reason and the method to deal with that.

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: TrueNAS SCALE as NAS and Debian bullseye as server
- Virtualization: NAS is an ESXi virtual machine, and Debian is a physical machine. Connected with ethernet.
- Clients: 10.8.9
- Browser: Edge Chromium
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: NVIDIA NVENC RTX2070
- Plugins: No
- Reverse Proxy: NginxProxyManager
- Base URL:
- Networking: 10G Ethernet
- Storage: TrueNAS SCALE
```

### Jellyfin logs

```shell
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 
[07:12:31] [INF] [105] Emby.Server.Implementations.Data.CleanDatabaseScheduledTask: Cleaning item 
[07:12:31] [INF] [105] Emby.Server.Implementations.Library.LibraryManager: Removing 

[07:12:33] [ERR] [143] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /db_tv_series
System.UnauthorizedAccessException: Access to the path '/db_tv_series/继母的拖油瓶是我的前女友 (2022)' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---

System.UnauthorizedAccessException: Access to the path '/db_xx/xxx/xxxx.nfo' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/17793356/230235875-b998392f-e7a8-4adc-b520-6fb42d4d389b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LittleNewton** [comment]
After logging into jellyfin with Bash, I found that all the resources removed were unable to access.

After `chmod -R 755 *`, it looked that all the resources which have been deleted came back!

**Comment by Bond-009** [comment]
Closing as non-issue
