### ISSUE TITLE
[Issue]: Cannot get image dimensions for `.../logo.svg`

### ISSUE THREAD

**Issue by rgmz** [jellyfin/jellyfin#9619]
### Please describe your bug

While reviewing the logs I noticed two distinct errors stemming from [`Emby.Server.Implementations.Library.LibraryManager#UpdateImagesAsync()`](
https://github.com/jellyfin/jellyfin/blob/c0b7f77c34949baa4aeebd2af280edd3e81a16bb/Emby.Server.Implementations/Library/LibraryManager.cs#L1878-L1891), repeated several times (presumably every time the task runs). Both errors happen when attempting to process an `.svg` file. I've attached the full logs below.

The first error should be reproducible with [this image](https://user-images.githubusercontent.com/32133502/230747018-2653dfe7-211e-4a95-b9cb-b1d3f14eb074.svg):
```
2023-04-08 18:36:08.280 +00:00] [ERR] [18] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/library/b1/b1468ca5910e2b4f8633becdaccea026/logo.svg"
System.FormatException: Input string was not in a correct format.
```

The second error should be reproducible with [this image](https://user-images.githubusercontent.com/32133502/230747046-cff950ea-2b4d-493d-8bce-edd7b7ce0eda.svg).
```
[2023-04-08 08:58:16.199 +00:00] [ERR] [3] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/library/fb/fb52416928944f9abecfeeaec282ab83/logo.svg"
System.Xml.XmlException: Reference to undeclared entity 'ns_extend'. Line 13, position 16.
```

-----

The issue with the second image is quite straightforward; I am not sure what the error is with the first image. 

I only recently started using Jellyfin and I am not familiar with the code base, but the cause seems to be [`Jellyfin.Drawing.Skia.SkiaEncoder#GetImageSize`](https://github.com/jellyfin/jellyfin/blob/c0b7f77c34949baa4aeebd2af280edd3e81a16bb/src/Jellyfin.Drawing.Skia/SkiaEncoder.cs#L112) and is most likely an issue with the upstream [SkiaSharp.Svg](https://github.com/mono/SkiaSharp.Extended) library (e.g. similar issue described in [luberda-molinet/FFImageLoading#1183](https://github.com/luberda-molinet/FFImageLoading/issues/1183#issuecomment-747472298)). Regardless, I am opening the issue here to track it as these are images downloaded by Jellyfin.

*Edit:* Skia.Svg is apparently [deprecated](https://github.com/mono/SkiaSharp.Extended/pull/36#issuecomment-674316158) so this is unlikely to be resolved. The solution might be to migrate to [`Svg.Skia`](https://github.com/wieslawsoltes/Svg.Skia) which would obviously take some effort (unless Jellyfin is already using it, but I don't think so.)

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Synology DSM 7
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-04-08 18:35:57.920 +00:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "RefreshMediaLibraryTask"
[2023-04-08 18:35:57.922 +00:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2023-04-08 18:35:57.922 +00:00] [INF] [18] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2023-04-08 18:36:05.307 +00:00] [ERR] [18] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/library/fb/fb52416928944f9abecfeeaec282ab83/logo.svg"
System.Xml.XmlException: Reference to undeclared entity 'ns_extend'. Line 13, position 16.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at SkiaSharp.Extended.Svg.SKSvg.Load(Stream stream)
   at SkiaSharp.Extended.Svg.SKSvg.Load(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-08 18:36:08.280 +00:00] [ERR] [18] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/library/b1/b1468ca5910e2b4f8633becdaccea026/logo.svg"
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at SkiaSharp.Extended.Svg.ColorHelper.TryParse(String str, SKColor& color)
   at SkiaSharp.Extended.Svg.SKSvg.ReadPaints(Dictionary`2 style, SKPaint& strokePaint, SKPaint& fillPaint, Boolean isGroup)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.LoadElements(IEnumerable`1 elements, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.Load(XDocument xdoc)
   at SkiaSharp.Extended.Svg.SKSvg.Load(Stream stream)
   at SkiaSharp.Extended.Svg.SKSvg.Load(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-08 18:36:08.759 +00:00] [ERR] [18] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/library/76/769996284b493e6c813c7e44a1a5a8d7/logo.svg"
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at SkiaSharp.Extended.Svg.ColorHelper.TryParse(String str, SKColor& color)
   at SkiaSharp.Extended.Svg.SKSvg.ReadPaints(Dictionary`2 style, SKPaint& strokePaint, SKPaint& fillPaint, Boolean isGroup)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.ReadElement(XElement e, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.LoadElements(IEnumerable`1 elements, SKCanvas canvas, SKPaint stroke, SKPaint fill)
   at SkiaSharp.Extended.Svg.SKSvg.Load(XDocument xdoc)
   at SkiaSharp.Extended.Svg.SKSvg.Load(Stream stream)
   at SkiaSharp.Extended.Svg.SKSvg.Load(String filename)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgmz** [comment]
Can't believe I missed that there was already an existing issue for this, #7626. I'll check out PR #9581 and see if that works.
