### ISSUE TITLE
Too many files error - Connections in close-wait?

### ISSUE THREAD

**Issue by daniel-widrick** [jellyfin/jellyfin#965]
Had Jellyfin set to record some shows on a saturday night. I believe I had 3 shows scheduled at an overlapping time (all 3 overlapped for 15 minutes) and my tuner only has two streams.

I received a "too many open files" error and Jellyfin crashed from the unhandled exception.

I BELIEVE this to be related to my tuner... but it could be an os file limit...

**To Reproduce**
I haven't confirmed this. but will try tonight.
1) Have a tuner setup in jellyfin with x streams
2) setup shows to be recorded such that x+1 overlap
3) crash happens when streams on tuner are exhausted?

**Expected behavior**
I would expect jelly fin to either wait until the stream is available, or just cancel the recording attempt.

**Logs**
```
03:00:00] [INF] Live stream opened: {"Protocol":"Http","Id":"native_797bf9f08cf7121fd313bb4cfbd5416a_3f8cf1ab34e4254e0c6e92c33c61b42a","Path":"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/cd488cd375c84cfa8109f8e8b1ae9f3f/stream.ts","Type":"Default","Container":"mpegts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_797bf9f08cf7121fd313bb4cfbd5416a_3f8cf1ab34e4254e0c6e92c33c61b42a","BufferMs":0,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mpeg2video","TimeBase":"1/90000","CodecTimeBase":"1001/60000","VideoRange":"SDR","DisplayTitle":"1080P MPEG2VIDEO","IsInterlaced":false,"BitRate":20000000,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":29.97003,"RealFrameRate":59.94006,"Profile":"Main","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":4,"IsAnamorphic":false},{"Codec":"ac3","CodecTag":"AC-3","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"Dolby Digital 5.1","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":384000,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":20384000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}
[03:00:00] [INF] Beginning recording. Will record for 59.9868720866667 minutes.
[03:00:00] [INF] Writing file to path: /srv/media/dvr/Saturday Night Live/Saturday Night Live 2019_02_17_03_00_00.ts
[03:00:01] [INF] Copying recording stream to file /srv/media/dvr/Saturday Night Live/Saturday Night Live 2019_02_17_03_00_00.ts
[03:00:01] [ERR] Error recording to /srv/media/dvr/Saturday Night Live/Saturday Night Live 2019_02_17_03_00_00.ts
System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, FileOpenOptions fileOpenOptions) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 441
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyFile(String path, Boolean seekFile, Int32 emptyReadLimit, Boolean allowAsync, Stream stream, CancellationToken cancellationToken) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs:line 206
   at Emby.Server.Implementations.LiveTv.TunerHosts.LiveStream.CopyToAsync(Stream stream, CancellationToken cancellationToken) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/TunerHosts/LiveStream.cs:line 175
   at Emby.Server.Implementations.LiveTv.EmbyTV.DirectRecorder.RecordFromDirectStreamProvider(IDirectStreamProvider directStreamProvider, String targetFile, TimeSpan duration, Action onStarted, CancellationToken cancellationToken) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/DirectRecorder.cs:line 57
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.RecordStream(TimerInfo timer, DateTime recordingEndDate, ActiveRecordingInfo activeRecordingInfo) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 1384
[03:00:01] [FTL] Unhandled Exception
System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, FileOpenOptions fileOpenOptions) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 441
   at Emby.Server.Implementations.Serialization.JsonSerializer.SerializeToFile(Object obj, String file) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/Serialization/JsonSerializer.cs:line 62
   at Emby.Server.Implementations.LiveTv.EmbyTV.ItemDataProvider`1.UpdateList(List`1 newList) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs:line 78
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.<>c__DisplayClass87_0.<<RecordStream>b__0>d.MoveNext() in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 1372
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[03:00:01] [INF] Live stream Unhandled Exception:native_797bf9f08cf7121fd313bb4cfbd5416a_3f8cf1ab34e4254e0c6e92c33c61b42a  consumer count is now 0
System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, FileOpenOptions fileOpenOptions) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 441
   at Emby.Server.Implementations.Serialization.JsonSerializer.SerializeToFile(Object obj, String file) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/Serialization/JsonSerializer.cs:line 62
   at Emby.Server.Implementations.LiveTv.EmbyTV.ItemDataProvider`1.UpdateList(List`1 newList) in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/ItemDataProvider.cs:line 78
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.<>c__DisplayClass87_0.<<RecordStream>b__0>d.MoveNext() in /var/home/joshua/Projects/Jellyfin/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 1372
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[03:00:01] [INF] Closing live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_797bf9f08cf7121fd313bb4cfbd5416a_3f8cf1ab34e4254e0c6e92c33c61b42a
[03:00:01] [INF] Closing SharedHttpStream
[03:00:01] [INF] Live stream a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_797bf9f08cf7121fd313bb4cfbd5416a_3f8cf1ab34e4254e0c6e92c33c61b42a closed successfully
[03:00:01] [INF] Triggering refresh on /srv/media/dvr/Saturday Night Live/Saturday Night Live 2019_02_17_03_00_00.ts
Aborted
```

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.0.1]

**Additional context**

**Comment by daniel-widrick** [comment]
Upon further review and testing... jellyfin does seem to behave correctly with the lack of tuner streams (less tuner streams than scheduled recordings)...

Which leads me to suspect that there are connections "leaking" or perhaps just waiting to close:

`[root@Jellyfin ~]# netstat -punta | grep jellyfin | grep CLOSE_WAIT | wc -l
84`

**Comment by daniel-widrick** [comment]
```
[03:41:56] [ERR] Error ProtocolError getting response from https://webservice.fanart.tv/v3/movies/312202?api_key=<REDACTED>
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

Perhaps this handle isn't being released when the above 404 exception occurs?

**Comment by JustAMan** [comment]
@daniel-widrick which Jellyfin version are you running? Note that issue template requested that.

The reason I'm asking is that we've fixed similar looking issue in #901 which is part of `10.2.0` release.

**Comment by daniel-widrick** [comment]
Version 10.2.0

I've let jellyfin running overnight and it did a scrape when it started took maybe half an hour and left 108 connections open. came home from work the next day and those 108 connections are still in close_wait

**Comment by daniel-widrick** [comment]
Looking through the code, Thank's for pointing me toward the file, I'm not an expert with csharp.. what I'm reading online seems to suggest that the connection shouldn't leak or need ANY special treatment...

HttpWebResponse appears to implement IDisposable and I would expect it to get cleaned up as soon as the handles are done. Is perhaps this async copy line causing a duplicate that isn't getting closed somehow?
https://github.com/cvium/jellyfin/blob/2845e7e1017386e1069ac3c990af6256c073cea7/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs#L546

**Comment by JustAMan** [comment]
@cvium does this look familiar to you? As you was the guy who fixed similar issue by #901.

**Comment by daniel-widrick** [comment]
this might be fixed. i've got rc1 of 10.2.0 let me see if I can get a newer release

**Comment by daniel-widrick** [comment]
Switched to 10.2.1 and things seem much smoother with the CLOSE_WAITs.. (Eg no connections in that state right now). I haven't seen the 404 that caused the exception before but for now the above fixes in the more recent releases probably did resolve the issue.

**Comment by cvium** [comment]
@daniel-widrick Nice find. I'm pretty sure there's an issue here, so I'm gonna reopen it.
