### ISSUE TITLE
[Issue]: Can't upgrade 10.8.5 -> 10.8.9 -- SQLiteException: database is locked

### ISSUE THREAD

**Issue by abstrakct** [jellyfin/jellyfin#9654]
### Please describe your bug

When trying to upgrade Jellyfin from 10.8.5 to 10.8.9, with the same data folders as 10.8.5, the server crashes because the database is locked:

`SQLitePCL.pretty.SQLiteException: database is locked`
(see also logs below)

I'm running the linuxserver.io image, with rffmpeg added by myself (shouldn't touch anything related to sqlite). It runs in podman.

I have tried to unlock jellyfin.db and library.db (and even rffmpeg.db) using this method: https://stackoverflow.com/a/7740613
but no change.

I've tried stopping and completely removing the old container, and even rebooting the VM, before starting the new Jellyfin container, but no change.

I'm not running two containers at once, or other instances of Jellyfin.

**Going back to 10.8.5 solves the issue - jellyfin starts without errors.**

Any ideas? Jellyfin bug, or is the problem on my end? I'm running out of ideas...
Thanks for any help!

For reference, here's the Dockerfile I use to build the container image I'm running:

```
FROM lscr.io/linuxserver/jellyfin:10.8.9

ARG TEMPDIR="/config/rffmpeg"

RUN apt update && \
    apt install -y openssh-client python3-click python3-yaml wget python3-pip && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg -O /usr/local/bin/rffmpeg && \
    chmod +x /usr/local/bin/rffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffprobe && \
    mkdir -p /etc/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg.yml.sample -O /etc/rffmpeg/rffmpeg.yml && \
    python3 -m pip install -U yt-dlp && \
    apt purge wget -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove --purge -y && \
    apt clean && \
    mkdir ${TEMPDIR} && chown 1000:1000 ${TEMPDIR} && \
    mkdir /config/log && touch /config/log/rffmpeg.log && chown 1000:1000 -R /config/log && chown -R 1000:1000 /var/log/jellyfin && chown -R 1000:1000 /var/lib/jellyfin
```

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.2.2
- Virtualization: Podman running in a VM
- Plugins: anidb, anilist, fanart, kitsu, kodisyncqueue, ldap auth, open subtitles, playback reporting, reports, shoko, thetvdb, tmdb box sets, trakt, tvmaze, webhook, youtubemetadata
```

### Jellyfin logs

```shell
[2023-04-18 15:26:44.620 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "System.IO.Abstractions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=96bf224d23c43e59" from "/config/data/plugins/YoutubeMetadata_1.0.3.9/System.IO.Abstractions.dll"
[2023-04-18 15:26:44.737 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/24,10.100.0.0/24]"
[2023-04-18 15:26:44.737 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-04-18 15:26:44.738 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/24,10.100.0.0/24]"
[2023-04-18 15:26:44.742 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-04-18 15:26:44.742 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-04-18 15:26:47.166 +02:00] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean readOnly)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2023-04-18 15:26:47.171 +02:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2023-04-18 15:26:47.221 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2023-04-18 15:26:47.223 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2023-04-18 15:26:48.391 +02:00] [INF] [1] Main: Jellyfin version: "10.8.9"
[2023-04-18 15:26:48.414 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]"]
[2023-04-18 15:26:48.417 +02:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
[2023-04-18 15:26:48.417 +02:00] [INF] [1] Main: Operating system: "Linux"
[2023-04-18 15:26:48.417 +02:00] [INF] [1] Main: Architecture: X64
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: 64-Bit Process: True
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: User Interactive: True
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: Processor count: 12
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: Program data path: "/config/data"
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2023-04-18 15:26:48.418 +02:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2023-04-18 15:26:48.516 +02:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abstrakct** [comment]
Update: upgrade from 10.8.5 to 10.8.6 works, and then upgrading from 10.8.6 to 10.8.7 also works. Between each upgrade I waited for any queued tasks etc to finish running, and then stopped the container.

But after upgrading from 10.8.7 to 10.8.8 I once again get the "database is locked" error. This is kinda strange, since there seems to be no changes related to database/sqlite in the commits between .7 and .8 

I see now that the linuxserver jellyfin image, starting with 10.8.8, has been updated to use Ubuntu 22.04 and s6v3. Starting to suspect this is the cause of my issues...

**Comment by abstrakct** [comment]
Final update: This issue has been resolved by migrating my Jellyfin deployment to using the official Jellyfin container image instead of the linuxserver.io image. Upgrading this way from 10.8.7 to 10.8.10 was painfree 

Still not sure what the exact root cause was, but as mentioned it is most likely related to linuxserver's update to Ubuntu 22.04 and/or s6v3.
