### ISSUE TITLE
[Issue]: Jellyfin crashes the whole system

### ISSUE THREAD

**Issue by bialabs** [jellyfin/jellyfin#9777]
### Please describe your bug

Hi, sometimes while playing movies with Jellyfin the the whole system crashes.
It happens ramdomly and rarely, almost 1 times a week, yesterday two times
Here are the logs before and after the crash.
The system becomes unreachable, including ssh, webserver, dockers...the only solution is the power off
Anyone can help me to identify the cause?

Thanks

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: Linux 6.1.0-0.deb11.6-amd64
- Virtualization: Docker
- Clients: Windows, Android
- Browser: Chrome latest
- Playback Method: Direct play
- Plugins: Default
- Reverse Proxy: NPM
- Storage: External USB EXT4 HD
```

### Jellyfin logs

```shell
[2023-05-15 19:02:06.961 +00:00] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-05-15 19:02:06.961 +00:00] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-15 19:03:00.545 +00:00] [INF] [1] Main: Jellyfin version: "10.8.10"
[2023-05-15 19:03:00.612 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]"]
[2023-05-15 19:03:00.616 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2023-05-15 19:03:00.622 +00:00] [INF] [1] Main: Operating system: "Linux"
[2023-05-15 19:03:00.622 +00:00] [INF] [1] Main: Architecture: X64
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: 64-Bit Process: True
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: User Interactive: True
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: Processor count: 4
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: Program data path: "/config"
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2023-05-15 19:03:00.624 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2023-05-15 19:03:01.318 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2023-05-15 19:03:01.614 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-05-15 19:03:01.655 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "9.0.0.0" of "Kodi Sync Queue"
[2023-05-15 19:03:01.747 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Reports, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Reports_15.0.0.0/Jellyfin.Plugin.Reports.dll"
[2023-05-15 19:03:01.749 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "23.0.0.0" of "Trakt"
[2023-05-15 19:03:02.009 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-15 19:03:02.009 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"

----

2023-05-16T06:08:51.938177535Z [06:08:51] [INF] [75] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
2023-05-16T06:08:51.938198791Z [06:08:51] [INF] [75] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2023-05-16T06:08:53.465856908Z [06:08:53] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for xxxxxxx. EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
2023-05-16T06:08:53.466312023Z [06:08:53] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Jellyfin Android, Path=/media/xxxxx/xxxxxxx/xxxxxxxx.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/9e34f624-64cd-20e9-c55c-fbb2347840b3/stream.mkv?MediaSourceId=9e34f62464cd20e9c55cfbb2347840b3&Static=true&VideoCodec=hevc&AudioCodec=ac3&AudioStreamIndex=1&api_key=<token>&Tag=ca33db4752cceafe7ffea0550eb93a94
2023-05-16T06:08:53.495473282Z [06:08:53] [ERR] [86] Microsoft.EntityFrameworkCore.Query: An exception occurred while iterating over the results of a query for context type 'Jellyfin.Server.Implementations.JellyfinDb'.
2023-05-16T06:08:53.495533836Z System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
2023-05-16T06:08:53.495555461Z    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
2023-05-16T06:08:53.495572577Z    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
2023-05-16T06:08:53.495640048Z System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
2023-05-16T06:08:53.495661868Z    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
2023-05-16T06:08:53.495679229Z    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
2023-05-16T06:08:53.515287721Z [06:08:53] [ERR] [86] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /DisplayPreferences/usersettings.
2023-05-16T06:08:53.515411520Z System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
2023-05-16T06:08:53.515438845Z    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
2023-05-16T06:08:53.515456071Z    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
2023-05-16T06:08:53.515473007Z    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
2023-05-16T06:08:53.515491057Z    at lambda_method452(Closure , QueryContext )
2023-05-16T06:08:53.515507483Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
2023-05-16T06:08:53.515523308Z    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
2023-05-16T06:08:53.515539529Z    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
2023-05-16T06:08:53.515557154Z    at Jellyfin.Server.Implementations.Users.DisplayPreferencesManager.GetDisplayPreferences(Guid userId, Guid itemId, String client)
2023-05-16T06:08:53.515574260Z    at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)
2023-05-16T06:08:53.515591855Z    at lambda_method430(Closure , Object , Object[] )
2023-05-16T06:08:53.515608656Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-05-16T06:08:53.515626022Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2023-05-16T06:08:53.515642587Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-05-16T06:08:53.515661758Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2023-05-16T06:08:53.515680063Z --- End of stack trace from previous location ---
2023-05-16T06:08:53.515700729Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-05-16T06:08:53.515765786Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-05-16T06:08:53.515788622Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2023-05-16T06:08:53.515805862Z --- End of stack trace from previous location ---
2023-05-16T06:08:53.515821828Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-05-16T06:08:53.515841964Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2023-05-16T06:08:53.515859149Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-05-16T06:08:53.515878000Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2023-05-16T06:08:53.515895875Z --- End of stack trace from previous location ---
2023-05-16T06:08:53.515913501Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-05-16T06:08:53.515933177Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-05-16T06:08:53.515951552Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-05-16T06:08:53.515969708Z    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
2023-05-16T06:08:53.515987413Z    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
2023-05-16T06:08:53.516004219Z    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
2023-05-16T06:08:53.516020414Z    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
2023-05-16T06:08:53.516040720Z    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2023-05-16T06:08:53.516059291Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-05-16T06:08:53.516075811Z    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
2023-05-16T06:08:53.516092662Z    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
2023-05-16T06:08:53.516110217Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2023-05-16T06:08:53.516126698Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2023-05-16T06:08:53.516170899Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-05-16T06:08:53.516189695Z    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
2023-05-16T06:08:53.516206905Z    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
2023-05-16T06:08:53.516223696Z    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
2023-05-16T06:08:53.516241307Z    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
2023-05-16T06:08:53.516259732Z    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
2023-05-16T06:08:53.519020167Z [06:08:53] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for xxxxxx. EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
2023-05-16T06:08:53.519521788Z [06:08:53] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Jellyfin Android, Path=/media/xxxxxx/xxxxxxxxx.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/9e34f624-64cd-20e9-c55c-fbb2347840b3/stream.mkv?MediaSourceId=9e34f62464cd20e9c55cfbb2347840b3&Static=true&VideoCodec=hevc&AudioCodec=ac3&AudioStreamIndex=1&api_key=<token>&Tag=ca33db4752cceafe7ffea0550eb93a94
2023-05-16T06:08:53.944805134Z [06:08:53] [INF] [76] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2023-05-16T06:08:53.944872996Z [06:08:53] [INF] [76] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
```

### Please attach any browser or client logs here

SYSLOGS

```
May 15 21:02:05 xxxxxxxxx dockerd[861]: time="2023-05-15T21:02:05.628762930+02:00" level=warning msg="[resolver] failed to read from DNS server: 192.168.178.1:53, query: ;php-fpm.\tIN\t A" error="read udp 172.21.0.3:40989->192.168.178.1:53: i/o timeout"
May 15 21:02:10 xxxxxxxxx dockerd[861]: time="2023-05-15T21:02:10.633814124+02:00" level=warning msg="[resolver] failed to read from DNS server: 192.168.178.1:53, query: ;php-fpm.\tIN\t A" error="read udp 172.21.0.3:51439->192.168.178.1:53: i/o timeout"
May 15 21:02:11 xxxxxxxxx systemd[1]: docker-105f833dae48cfde4b86733c1267d63bb294be51cd8289588dfeaf9312ac7589.scope: Succeeded.
May 15 21:02:11 xxxxxxxxx containerd[817]: time="2023-05-15T21:02:11.674453745+02:00" level=info msg="shim disconnected" id=105f833dae48cfde4b86733c1267d63bb294be51cd8289588dfeaf9312ac7589
May 15 21:02:11 xxxxxxxxx containerd[817]: time="2023-05-15T21:02:11.674601030+02:00" level=warning msg="cleaning up after shim disconnected" id=105f833dae48cfde4b86733c1267d63bb294be51cd8289588dfeaf9312ac7589 namespace=moby
May 15 21:02:11 xxxxxxxxx containerd[817]: time="2023-05-15T21:02:11.674652052+02:00" level=info msg="cleaning up dead shim"
May 15 21:02:11 xxxxxxxxx dockerd[861]: time="2023-05-15T21:02:11.674527872+02:00" level=info msg="ignoring event" container=105f833dae48cfde4b86733c1267d63bb294be51cd8289588dfeaf9312ac7589 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 15 21:02:11 xxxxxxxxx containerd[817]: time="2023-05-15T21:02:11.696486523+02:00" level=warning msg="cleanup warnings time=\"2023-05-15T21:02:11+02:00\" level=info msg=\"starting signal loop\" namespace=moby pid=76309 runtime=io.containerd.runc.v2\n"
May 15 21:02:11 xxxxxxxxx kernel: [10172.211624] br-5a2a15a55b30: port 2(veth16a40b4) entered disabled state
May 15 21:02:11 xxxxxxxxx kernel: [10172.211973] veth947a251: renamed from eth0
May 15 21:02:11 xxxxxxxxx systemd-networkd[330]: veth16a40b4: Lost carrier
May 15 21:02:11 xxxxxxxxx NetworkManager[713]: <info>  [1684177331.8098] manager: (veth947a251): new Veth device (/org/freedesktop/NetworkManager/Devices/578)
May 15 21:02:11 xxxxxxxxx systemd-udevd[76328]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 15 21:02:11 xxxxxxxxx systemd-udevd[76328]: Using default interface naming scheme 'v247'.
May 15 21:02:11 xxxxxxxxx systemd-networkd[330]: veth16a40b4: Link DOWN
May 15 21:02:11 xxxxxxxxx kernel: [10172.261982] br-5a2a15a55b30: port 2(veth16a40b4) entered disabled state
May 15 21:02:11 xxxxxxxxx kernel: [10172.264314] device veth16a40b4 left promiscuous mode
May 15 21:02:11 xxxxxxxxx kernel: [10172.264335] br-5a2a15a55b30: port 2(veth16a40b4) entered disabled state
May 15 21:02:11 xxxxxxxxx systemd-networkd[330]: rtnl: received neighbor for link '392' we don't know about, ignoring.
May 15 21:02:11 xxxxxxxxx systemd-networkd[330]: rtnl: received neighbor for link '392' we don't know about, ignoring.
May 15 21:02:11 xxxxxxxxx NetworkManager[713]: <info>  [1684177331.8398] device (veth16a40b4): released from master device br-5a2a15a55b30
May 15 21:02:11 xxxxxxxxx systemd-udevd[76332]: veth947a251: Failed to query device driver: No such device
May 15 21:02:11 xxxxxxxxx systemd-udevd[76332]: veth947a251: Failed to get link config: No such device
May 15 21:02:11 xxxxxxxxx systemd[1]: run-docker-netns-79aedc0fb7a6.mount: Succeeded.
May 15 21:02:11 xxxxxxxxx systemd[1]: var-lib-docker-overlay2-5d269e918d89c922aea770fcde66824df0e5e3a1cee088861473ce40ca271bf8-merged.mount: Succeeded.
May 15 21:02:51 xxxxxxxxx systemd-modules-load[290]: Inserted module 'softdog'
May 15 21:02:51 xxxxxxxxx blkmapd[312]: open pipe file /run/rpc_pipefs/nfs/blocklayout failed: No such file or directory
May 15 21:02:51 xxxxxxxxx systemd[1]: Starting Flush Journal to Persistent Storage...
May 15 21:02:51 xxxxxxxxx systemd[1]: Started Rule-based Manager for Device Events and Files.
May 15 21:02:51 xxxxxxxxx systemd[1]: Starting Network Service...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by digital-mystik** [comment]
I have been experiencing the same for a little while now, but am not sure how to debug this as nothing of relevance shows up in journalctl.

Have tried containers (via podman) and a native installation. Not sure how to describe it, but I will notice media disconnecting, then zsh will crash (able to move my mouse and switch workspaces but not able to execute any commands).. unable to perform a clean reboot or shutdown and need to do an inevitable hard reset.


My NVME drive checks out with SMART and memtest86+ passes which leads me to believe my hardware is fine (fingers crossed it isn't failing).

**Comment by prahal** [comment]
This likely is a kernel issue (or a hardware issue, you might want to test your RAM).
To give your BIOS details:
`sudo dmidecode --type 0`
system:
`sudo dmidecode --type 1`
and
`lshw  -short`.

On my skylake box "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz" with integrated "HD Graphics 530 graphics" I happen to get hangs which when I ssh to the box and keep a `journalctl -b -f` running until the crash happens I can see most of the times some gpu timeout warning from the i915 driver. This happens only when I stress the box really hard (even with free RAM left), ie a load of 30 or so with firefox using gpu acceleration I believe.

Though as you are "direct playing" the videos I do not see how jellyfin could trigger a kernel driver issue.
(which otherwise be could gpu or video acceleration related). Ie CPU processing would not crash the box on its own.

Also is the box freezing only  when playing a video (could be ffmpeg called with acceleration for background tasks, even if I do not know if jellyfin runs with acceleration for such tasks as video thumbnails generation)

**Comment by digital-mystik** [comment]
Fingers crossed, but the crashing issue may be worked out on my end. 
Instead of using the official binaries and stable branch, I built from main (`jellyfin-git` group on the AUR) which uses latest dotnet (v7) in lieu of v6 and also allows for `jellyfin-ffmpeg6` as well.

Will report back if I see any crashes but for now it seems ironed out.

**Comment by yllekz** [comment]
I had an issue last night where jellyfin/ffmpeg spiked CPU/RAM to max on my openmediavault server and i had to reboot it to get it to stop. Based on prior issues it sounds like this seems to be a historical problem.

**Comment by srcrist** [comment]
Hi there. That this is an isolated, seldom reported issue suggests that the most likely culprit lies outside of Jellyfin itself. It may be hardware, or an OS issue. Are you still experiencing these crashes?

**Comment by bialabs** [comment]
In my case the issue is gone. For sure not related to Jellyfin
I think a Docker update fixed the issue

**Comment by iskenyildiz** [comment]
I experience this on my raspberry pi as well. I used jellyfin as a systemctl service and as a docker container but both times the whole sustem crashed and i had to reboot by taking the power on and off. I use ssd drive for my storage. While playback, sometimes the system just crashes. I watch my system with metrics on grafana but no historical metric points to it being a cpu/ram resource issue.
