### ISSUE TITLE
[Issue]: Scan Media Library failed when get invalid image

### ISSUE THREAD

**Issue by xxxsen** [jellyfin/jellyfin#9784]
### Please describe your bug

If the "thumb" item in the "actor" block is an abnormal image, it may cause Jellyfin to throw an exception while scanning the media.

error log: 
```log
jellyfin  | [00:10:52] [INF] [71] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
jellyfin  | [00:10:52] [INF] [71] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /data/movies
jellyfin  | [00:10:52] [INF] [71] Emby.Server.Implementations.Library.LibraryManager: Validating media library
jellyfin  | [00:10:52] [INF] [60] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /data/movies
jellyfin  | [00:10:52] [ERR] [61] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
jellyfin  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.SavePeopleMetadataAsync(IEnumerable`1 people, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, List`1 people, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass68_0.<<RefreshChildMetadata>b__0>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
jellyfin  | [00:10:52] [INF] [61] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Failed after 0 minute(s) and 0 seconds
jellyfin  | [00:10:52] [INF] [61] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
jellyfin  | [00:11:16] [INF] [67] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
jellyfin  | [00:11:16] [INF] [67] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /data/movies
jellyfin  | [00:11:16] [INF] [67] Emby.Server.Implementations.Library.LibraryManager: Validating media library
jellyfin  | [00:11:17] [WRN] [69] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from https://abc.com
jellyfin  | System.InvalidOperationException: Operation is not valid due to the current state of the object.
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
jellyfin  | [00:11:17] [ERR] [69] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
jellyfin  | System.IO.IOException: Read-only file system : '/data/movies/2023/aaaaa.nfo'
jellyfin  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.FileStream..ctor(String path, FileStreamOptions options)
jellyfin  |    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
jellyfin  |    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
```

here is a test xml to reproduce.

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
  <plot>plot txt</plot>
  <customrating>rating txt</customrating>
  <lockdata>false</lockdata>
  <dateadded>2023-03-04 10:48:36</dateadded>
  <title>title txt</title>
  <originaltitle>origin title txt</originaltitle>
  <director>director txt</director>
  <year>2023</year>
  <sorttitle>sort title txt</sorttitle>
  <mpaa>mpaa txt</mpaa>
  <premiered>2023-03-23</premiered>
  <releasedate>2023-03-23</releasedate>
  <runtime>125</runtime>
  <genre>FALENOstar</genre>
  <genre>123</genre>
  <genre>234</genre>
  <genre>345</genre>
  <genre>456</genre>
  <genre>567</genre>
  <genre>678</genre>
  <studio>text</studio>
  <tag>text</tag>
  <tag>1</tag>
  <tag>2</tag>
  <tag>3</tag>
  <tag>4</tag>
  <tag>5</tag>
  <tag>6</tag>
  <art>
    <poster>aaaaa-poster.jpg</poster>
    <fanart>aaaaa-fanart.jpg</fanart>
    <fanart>aaaaa-fanart.jpg</fanart>
  </art>
  <actor>
    <name>cccc</name>
    <type>Actor</type>
    <thumb>http://www.javbus.com</thumb>
  </actor>
</movie>
```

step to reproduce: 
1. create a folder contains necessary movie files(save xml above as aaaaa.nfo) like this:
<img width="548" alt="image" src="https://github.com/jellyfin/jellyfin/assets/3880276/03f3cb47-4aae-473c-8e5d-bdda6510f6f8">

2. enter jellyfin sever setting->cronjob, click `Scan Media Library`

conclusion:
After testing, it appears that the issue may be caused by Jellyfin sending an HTTP request with the "Accept-Encoding: gzip, deflate, br" header, which results in the remote website sending back compressed data. However, Jellyfin fails to check whether this data is an image, leading to the eventual exception being thrown.

may be the same issue:

https://github.com/jellyfin/jellyfin/issues/9503

### Jellyfin Version

10.8.z

### Environment

```markdown
- env: docker
```

### Jellyfin logs

```shell
none
```

### FFmpeg logs

```shell
none
```

### Please attach any browser or client logs here

none

### Please attach any screenshots here

<img width="868" alt="image" src="https://github.com/jellyfin/jellyfin/assets/3880276/436a376c-051a-4890-8b05-a27af41e0eea">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChuckSerious** [comment]
I had the case with some *.tif pictures in 10.9.0...
