### ISSUE TITLE
Audiocast M5

### ISSUE THREAD

**Issue by Sonusss** [jellyfin/jellyfin#9833]
Hello,

I have several DLNA Audiocast M5 players well recognized by Jellyfin
https://audiocast.io/
However trying to play some audio makes everything looking fine in the GUI but no audio out
Streaming to brower (computer) works perfectly

**Media Info of the file**

Audio
Title: MP3 - Stereo
Codec: MP3
Layout: stereo
Channels: 2 ch
Bitrate: 320 kbps
Sample rate: 44100 Hz
Default: No
Forced: No
External: No

**Logs**

[2023-05-29 16:37:59.435 +00:00] [INF] [41] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
DeviceIdentification { FriendlyName: "Office", ModelNumber: "V01-Sep 13 2022
", SerialNumber: "00001", ModelName: "AudioCast", ModelDescription: "AudioCast", ModelUrl: "http://audiocast.ieast.net", Manufacturer: "iEAST", ManufacturerUrl: "http://www.ieast.net", Headers: [] }
[2023-05-29 16:38:09.720 +00:00] [ERR] [53] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for "Office"
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.PostSoapDataAsync(String url, String soapAction, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)

**Server System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: None
 - Reverse proxy: None
 - Other hardware notes: media directory as docker mounted volume

**Comment by Sonusss** [comment]
I would like to add that the playback appears normal too in the genuine manufacturer app. Title and track details are well displayed but no playback progress bar. (allways 00:00 and total duration 00:00)

**Comment by Sonusss** [comment]
I found that it seem to be related to Linkplay chipset (which Audiocast M5 uses), I found several posts telling the same story.
Example: https://wiim.community.forum/threads/dlna-playback-with-jellyfin.295/
There are a bunch of Linkplay devices: https://www.linkplay.com/products-powered-by-linkplay with famous names like JBL, Harman Kardon, etc...
Any chance to fix this ?

**Comment by Sonusss** [comment]
I bought two other players for testing; WiiM Mini & Arylic Mini V3 and getting same issue. 
All these players are using **Linkplay** modules...
This issue is then related to **LinkPlay** technologies and not a specific audio device.
I can play nicely on all of them from Synology Audio Station

**Comment by Sonusss** [comment]
If someone from developer team would like to dig in, here is the link to Linplay API documentation:
https://github.com/AndersFluur/LinkPlayApi/blob/master/api.md
