### ISSUE TITLE
Linkplay based audio player

### ISSUE THREAD

**Issue by Sonusss** [jellyfin/jellyfin#9856]
Hello,

I have several DLNA Audiocast M5 players well recognized by Jellyfin
https://audiocast.io/
However trying to play some audio makes everything looking fine in the GUI but no audio out
Streaming to browser (computer) works perfectly
I have found some forums reporting this issue due to LinkPlay chipset

**Audiocast M5 works well when used from Synology DS Audio platform**

Media Info of the file

Audio
Title: MP3 - Stereo
Codec: MP3
Layout: stereo
Channels: 2 ch
Bitrate: 320 kbps
Sample rate: 44100 Hz
Default: No
Forced: No
External: No

Logs

[2023-05-29 16:37:59.435 +00:00] [INF] [41] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used.
DeviceIdentification { FriendlyName: "Office", ModelNumber: "V01-Sep 13 2022
", SerialNumber: "00001", ModelName: "AudioCast", ModelDescription: "AudioCast", ModelUrl: "http://audiocast.ieast.net/", Manufacturer: "iEAST", ManufacturerUrl: "http://www.ieast.net/", Headers: [] }
[2023-05-29 16:38:09.720 +00:00] [ERR] [53] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for "Office"
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The response ended prematurely.
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Emby.Dlna.PlayTo.SsdpHttpClient.PostSoapDataAsync(String url, String soapAction, String postData, String header, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)

Server System (please complete the following information):

    OS: Docker
    Jellyfin Version: 10.8.10
    Hardware settings & device: None
    Reverse proxy: None
    Other hardware notes: media directory as docker mounted volume

**Comment by Bond-009** [comment]
You already opened an issue for this, no?
#9833

**Comment by Sonusss** [comment]
Yeaaaah, but nothing seems to have waken up someone !!!

**Comment by Bond-009** [comment]
Everyone here is a volunteer, it will get done when someone wants to do it.
