### ISSUE TITLE
[Issue]: Can't create PlayTo device on LG TV

### ISSUE THREAD

**Issue by pitbuster** [jellyfin/jellyfin#9917]
### Please describe your bug

Lately I haven't been able to use PlayTo on my TV (a LG Smart TV). Looking through the logs, I see

````
Jun 21 18:40:50 hostname jellyfin[241914]: [18:40:50] [DBG] [30] Emby.Dlna.Main.DlnaEntryPoint: Attempting to create PlayToController from location http://192.168.1.93:1328/
Jun 21 18:41:10 hostname jellyfin[241914]: [18:41:10] [ERR] [30] Emby.Dlna.Main.DlnaEntryPoint: Error creating PlayTo device.
Jun 21 18:41:10 hostname jellyfin[241914]: System.Net.Http.HttpRequestException: An error occurred while sending the request.
Jun 21 18:41:10 hostname jellyfin[241914]:  ---> System.IO.IOException: The response ended prematurely.
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    --- End of inner exception stack trace ---
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.Device.CreateuPnpDeviceAsync(Uri url, IHttpClientFactory httpClientFactory, ILogger logger, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.PlayToManager.AddDevice(UpnpDeviceInfo info, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.PlayToManager.OnDeviceDiscoveryDeviceDiscovered(Object sender, GenericEventArgs`1 e)
````

But going to the IP on a browser I get the XML file correctly:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:dlna="urn:schemas-dlna-org:device-1-0" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11" xmlns:df="http://schemas.microsoft.com/windows/2008/09/devicefoundation">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
    <friendlyName>LG dorm</friendlyName>
    <manufacturer>LG Electronics.</manufacturer>
    <manufacturerURL>http://www.lge.com</manufacturerURL>
    <modelDescription>LG WebOSTV DMRplus</modelDescription>
    <modelName>LG TV</modelName>
    <modelURL/>
    <modelNumber>1.0</modelNumber>
    <serialNumber/>
    <UDN>uuid:d3cea452-d83f-8ede-ec77-5f22eb84b208</UDN>
    <pnpx:X_compatibleId>MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
    <pnpx:X_deviceCategory>MediaDevices</pnpx:X_deviceCategory>
    <df:X_deviceCategory>Multimedia.DMR</df:X_deviceCategory>
    <df:X_modelId>LG Digital Media Renderer TV</df:X_modelId>
    <lge:X_LG_DLNA_DOC xmlns:lge="urn:lge-com:device-1-0">1.0</lge:X_LG_DLNA_DOC>
    <dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
    <iconList>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/dmrIcon_48.jpeg</url>
      </icon>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/dmrIcon_120.jpeg</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/dmrIcon_48.png</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>8</depth>
        <url>/dmrIcon_120.png</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
        <SCPDURL>/AVTransport/d3cea452-d83f-8ede-ec77-5f22eb84b208/scpd.xml</SCPDURL>
        <controlURL>/AVTransport/d3cea452-d83f-8ede-ec77-5f22eb84b208/control.xml</controlURL>
        <eventSubURL>/AVTransport/d3cea452-d83f-8ede-ec77-5f22eb84b208/event.xml</eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
        <SCPDURL>/ConnectionManager/d3cea452-d83f-8ede-ec77-5f22eb84b208/scpd.xml</SCPDURL>
        <controlURL>/ConnectionManager/d3cea452-d83f-8ede-ec77-5f22eb84b208/control.xml</controlURL>
        <eventSubURL>/ConnectionManager/d3cea452-d83f-8ede-ec77-5f22eb84b208/event.xml</eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
        <SCPDURL>/RenderingControl/d3cea452-d83f-8ede-ec77-5f22eb84b208/scpd.xml</SCPDURL>
        <controlURL>/RenderingControl/d3cea452-d83f-8ede-ec77-5f22eb84b208/control.xml</controlURL>
        <eventSubURL>/RenderingControl/d3cea452-d83f-8ede-ec77-5f22eb84b208/event.xml</eventSubURL>
      </service>
    </serviceList>
  </device>
</root>
````

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Arch Linux
- Linux Kernel: 6.2.10
- Virtualization: no
- Clients: Android
- Browser: Firefox 114
- FFmpeg Version: 6.0
- Playback Method:N/A
- Hardware Acceleration: none
- GPU Model: N/A
- Plugins:
- Reverse Proxy: Caddy
- Base URL: none
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
Jun 21 18:40:50 hostname jellyfin[241914]: [18:40:50] [DBG] [30] Emby.Dlna.Main.DlnaEntryPoint: Attempting to create PlayToController from location http://192.168.1.93:1328/
Jun 21 18:41:10 hostname jellyfin[241914]: [18:41:10] [ERR] [30] Emby.Dlna.Main.DlnaEntryPoint: Error creating PlayTo device.
Jun 21 18:41:10 hostname jellyfin[241914]: System.Net.Http.HttpRequestException: An error occurred while sending the request.
Jun 21 18:41:10 hostname jellyfin[241914]:  ---> System.IO.IOException: The response ended prematurely.
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    --- End of inner exception stack trace ---
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.SsdpHttpClient.GetDataAsync(String url, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.Device.CreateuPnpDeviceAsync(Uri url, IHttpClientFactory httpClientFactory, ILogger logger, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.PlayToManager.AddDevice(UpnpDeviceInfo info, CancellationToken cancellationToken)
Jun 21 18:41:10 hostname jellyfin[241914]:    at Emby.Dlna.PlayTo.PlayToManager.OnDeviceDiscoveryDeviceDiscovered(Object sender, GenericEventArgs`1 e)
`
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by pitbuster** [comment]
It seems that after the work that happened on the DLNA code, this got solved.
