### ISSUE TITLE
Debian armhf build fails to install plugins

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#993]
**Describe the bug**
Plugin installation fails on armhf Debian builds.

**To Reproduce**
1. Install Jellyfin 10.2.1 on a Raspberry Pi running Raspbian Stretch
1. Attempt a plugin installation.

**Expected behavior**
Plugin is downloaded, extracted, and installed.

**Logs**
```
Feb 23 00:21:48 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:48] [INF] HttpClientManager GET: https://repo.jellyfin.org/releases/plugin/manifest.json                                                                           
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [INF] HttpClientManager.GetTempFileResponse url: https://repo.jellyfin.org/releases/plugin/jellyfin-plugin-emailnotifications/jellyfin-plugin-emailnotifications_1.0.0.zip                                  
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [INF] HTTP GET http://10.22.0.190:8096/web/bower_components/emby-webcomponents/notifications/notificationicon.png. UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [INF] HTTP Response 304 to 10.42.0.101. Time: 2ms. http://10.22.0.190:8096/web/bower_components/emby-webcomponents/notifications/notificationicon.png
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [ERR] Package installation failed
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(IProgress`1 progress, String target, PackageVersionInfo package, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 564
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 514
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 444
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [ERR] Error processing request
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(IProgress`1 progress, String target, PackageVersionInfo package, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 564
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 514
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Updates/InstallationManager.cs:line 444
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at MediaBrowser.Api.PackageService.Post(InstallPackage request) in /jellyfin/MediaBrowser.Api/PackageService.cs:line 200
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 113
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
Feb 23 00:21:49 jfbuildpi1.m.bonilan.net jellyfin[12171]: [00:21:49] [INF] HTTP Response 500 to 10.42.0.101. Time: 475ms. http://10.22.0.190:8096/emby/Packages/Installed/Email%20Notifications?updateClass=Release&AssemblyGuid=cfa0f7f4-4155-4d71-849b-d6598dc4c5bb&version=1.0.0
```

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Raspbian armhf (Raspberry Pi)
 - Browser: Firefox 65
 - Jellyfin Version: 10.2.1

**Additional context**
Does not occur on amd64. Reported via Reddit and confirmed by myself.

**Comment by joshuaboniface** [comment]
Could not replicate with a fresh build - likely an obscure bug in the released build. Should be fixed by a simple rebuild for the next release.

**Comment by airsay** [comment]
Can also confirm this as a bug as well. Running 10.2.1-1 armhf and I was unable to install any of the pluhins
