### ISSUE TITLE
[Issue]: Switching back to stable from unstable gives this error

### ISSUE THREAD

**Issue by nurailroaddev** [jellyfin/jellyfin#9953]
### Please describe your bug

Went to the newest unstable with a running install and then found out that the way the plugin logins worked was changed and thus planned broken until a future release. Now when I try to switch back, I get this error in the logs

 Main: Error while starting server.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: u.EasyPassword'.

Anyone have a fix or an idea on where to start with this?

### Jellyfin Version

Other

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: YEP
- GPU Model: 2070 SUPER
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-07-02 15:57:27.164 -07:00] [FTL] [1] Main: Error while starting server.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: u.EasyPassword'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
There is no support for downgrading. You must either restore from a backup or start fresh.

**Comment by Xeyame** [comment]
For anyone coming from google, adding EasyPassword (Type TEXT, Nullable true, Default null, Primary false) to the Columns in the Users entity in the Jellyfin.db sqlite file with something like beekeeper fixes this.

**Comment by aiac** [comment]
> For anyone coming from google, adding EasyPassword (Type TEXT, Nullable true, Default null, Primary false) to the Columns in the Users entity in the Jellyfin.db sqlite file with something like beekeeper fixes this.

It works, thank you
