### ISSUE TITLE
[Issue]: Health endpoint wrongly returns 'healthy'

### ISSUE THREAD

**Issue by chevdor** [jellyfin/jellyfin#9954]
### Please describe your bug

I cannot access Jallyfin and the UI reports an error.
Looking at the server logs, I see the issue shown below.

Whatever the issue is, it means, the jellyfin server is not healthy. The `health` endpoint nonetheless reports that eveything is fine.

<details>
<summary>Server Logs</summary>

```
[07:13:45] [ERR] [82] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/5c6c9a17f98540eea6fb140a5ab16ff9/Views.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(IStatement statement)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at Emby.Server.Implementations.Playlists.PlaylistsFolder.GetEligibleChildrenForRecursiveChildren(User user)
   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
   at Emby.Server.Implementations.Playlists.PlaylistsFolder.IsVisible(User user)
   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
   at lambda_method1009(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[07:13:45] [ERR] [88] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Users/5c6c9a17f98540eea6fb140a5ab16ff9/Views.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(IStatement statement)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at Emby.Server.Implementations.Playlists.PlaylistsFolder.GetEligibleChildrenForRecursiveChildren(User user)
   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
   at Emby.Server.Implementations.Playlists.PlaylistsFolder.IsVisible(User user)
   at MediaBrowser.Controller.Entities.Folder.AddChildren(User user, Boolean includeLinkedChildren, Dictionary`2 result, Boolean recursive, InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
   at Emby.Server.Implementations.Library.UserViewManager.GetUserViews(UserViewQuery query)
   at Jellyfin.Api.Controllers.UserViewsController.GetUserViews(Guid userId, Nullable`1 includeExternalContent, String[] presetViews, Boolean includeHidden)
   at lambda_method1009(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
</details>

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: K8s / Docker
- Linux Kernel: Official image
- Virtualization: K8S
- Clients: Tested on Android / Web / Firetv
- Browser: Brave
- FFmpeg Version: no clue
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: n/a
- Reverse Proxy: n/a
- Base URL: n/a
- Networking: n/a
- Storage: nfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chevdor** [comment]
After fetching the logs, I killed my pod so the k8s deployment created a new one and Jallyfin is back online.
That means:
- it is not a DB / storage issue (a transient issue maybe...)
- if health would return a proper value, k8s would have killed this pod and "fixed the problem" by starting a new pod
- if the DB issue was transient, jellyfin should try to reconnect/recover, if a restart is preferable, then the `health` endpoint should return an unhealthy state

**Comment by Malinskiy** [comment]
I'm seeing the same error after a transient failure of the underlying disk.
I've patched this problem by using a simple `SELECT 1` in the health check https://github.com/Malinskiy/jellyfin/commit/2ca371ca4e700ea9cb522d9be87b1e841f6f9f6e#diff-9e0b2aae8c24aac174575b10a93a4ec89f3e7e4e0fcb09f40de20fa6c4d747fdR35 but to my surprise, this didn't help: seems like there is some caching happening of db context that doesn't allow the jellyfin to recover properly

**Comment by chevdor** [comment]
This issue makes Jellyfin unusable to me since it never works when I access it and I need to restart it manually.
If the health endpoint would work, I would let k8s do the restart when required. This does not fix the underlaying issue but at least makes it usable again.

As an alternate option, it would be nice haivng a command (ie runnable via cli) that can return that we are locked up and a restart is required.

**Comment by chevdor** [comment]
I will do a lame force restart evey N hours for now... hoping this issue will be addressed nonetheless at some point.
@Malinskiy I don't think I have disk issues. How did you notice the issue on your end ?

```
FILE=/tmp/.daily-reboot
MAX_HOURS=12
MAX_SEC=$(echo $((($MAX_HOURS*60*60))))
if [[ -f "$FILE" ]]; then
    AGE_IN_SEC=$(expr `date +%s` - `stat -c %Y $FILE`)
    if [ $AGE_IN_SEC -gt $MAX_SEC ]; then
        echo "File is older than $MAX_HOURS hours"
        rm $FILE; touch $FILE
        return 1
    else
        echo "File is not older than $MAX_HOURS hours"
        return 0
    fi
else
  touch $FILE
  return 0
fi
```

**Comment by Malinskiy** [comment]
For my case once there is a failure in the underlying disk read I see `IOError: SQLitePCL.pretty.SQLiteException: disk I/O error` every time JF tries to read something from the jellyfin.db. Once it happens I verified by manually `exec`ing into the pod and checking if the file was there and also checking if regular terminal `sqlite3` could read the db and it could while jellyfin would not give up spamming `IOError: SQLitePCL.pretty.SQLiteException: disk I/O error` every time it tried to query something. Restarting the pod seems to help, but I'm also manually restarting now since there is no good way of really checking the health. Unless I resort to grep'ing the stdout/stderr for this exact message I guess.

**Comment by chevdor** [comment]
Thanks for the details @Malinskiy. I did not look into the code but a cheap option would be to touch a signal file when the Exception is raised. This would at least something easy to detect from the outside.
It sounds like the db connector intermitendly fails and does not recover properly.
